### ISSUE TITLE
Remove quotes from delete dialog

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#10008]
# Summary

Quotation marks should be used to delineate things and make it clear that things are not prose.

There are other ways to delineate such things, e.g. `<tt>text</tt>` instead of `'text'`.

# Motivation

I've watched people try to select the name of the resource in order to delete an object, e.g.:
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/2119212/179267163-ccb4d7ff-b48b-438c-8075-3f65162de0c3.png">

They generally trip on the `'`s (there are magical ways to use a mouse to avoid grabbing them, but, forcing users to deal w/ this isn't very nice).

# Proposal

1. Switch from `'%s'` to `<tt>%s</tt>` (or the equivalent of `<tt>`...)
2. Don't include the name of the resource in the delete line, watching people try to copy the name from the field and having it run away is watching them be tortured...

**Comment by deepto98** [comment]
Can I pick this up?

**Comment by JessieTeng89** [comment]
@crenshaw-dev I can work on this if this is still available

**Comment by jsoref** [comment]
@deepto98: sure.

**Comment by souravsk** [comment]
Hi, @deepto98 did you solve this issue and if you did then can you please how did you do that I know to this so it will be very helpful to understand how to work on this type of issue.

**Comment by crenshaw-dev** [comment]
Here's an attempt: https://github.com/argoproj/argo-cd/pull/10305

I haven't tested it yet.

**Comment by JessieTeng89** [comment]
Can I work on this issue and assign to me if it is still needed?
@crenshaw-dev @jsoref

**Comment by JessieTeng89** [comment]
Following is the plan, I will firstly use some HTML elements to instead of quotation marks for the resource name, and then I will disable the text selection for the resource name so that we can force user to input the resource name by manually without copy/paste.
![image](https://user-images.githubusercontent.com/101035990/186115652-e6fc9f79-89d2-499f-a45e-10d101b2d024.png)

**Comment by jsoref** [comment]
Disabling text selection is a no-no in my book. That's just torture. Lots of sites try to do such things and it's a really bad anti-pattern.

I'm reasonably happy w/ the theoretical changes @crenshaw-dev made, although I'd like to know if they work...

**Comment by JessieTeng89** [comment]
@jsoref I agree, I saw the pull request created by @crenshaw-dev has been closed, so I tried to find a solution for this issue.
Maybe we can update the message and replace the quotes first.

**Comment by JessieTeng89** [comment]
@jsoref Are you good with the message style change like following screenshot? I removed the unused quotes and display the resource/application name with bold, or do you have any other ideas?
![Screen Shot 2022-08-25 at 13 28 02](https://user-images.githubusercontent.com/101035990/186582476-b4db816e-25de-4ea1-a58d-8d270ed52ee4.png)

**Comment by jsoref** [comment]
If we could have the equivalent of `<tt>` (monospace font) instead of bold, I'd prefer it. But, what you have is better than the current.

**Comment by JessieTeng89** [comment]
By researching, it seems `<tt>` is already deprecated in HTML5, please see this blog https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt.
Instead it recommends us to use the more semantically helpful `<code>`, `<kbd>`, `<samp>`, or `<var>` elements for inline text that needs to be presented in monospace type
I tried all in my local environment, please check if any style you preferrer to use.
`<code>`
![image](https://user-images.githubusercontent.com/101035990/186796149-97cc9a06-e62c-4777-b71b-b8909df63f6d.png)

`<kbd>`
![image](https://user-images.githubusercontent.com/101035990/186796207-59331bda-192f-4ed0-a45a-6ef693e2787f.png)

`<samp>`
![image](https://user-images.githubusercontent.com/101035990/186796269-243bf676-7746-4e66-a2cc-14c4ab4672df.png)

`<var>`
![image](https://user-images.githubusercontent.com/101035990/186796320-2510ed13-11df-4615-9370-97c3bfe0fe83.png)

**Comment by jsoref** [comment]
Ah, I didn't necessarily mean the literal html `<tt>`, just a conceptual monospace w/o me writing a css style.

That said, `<kbd>` appears to both be semantically correct and have a reasonable rendering.

**Comment by JessieTeng89** [comment]
@jsoref 
Created a PR for this issue, please help to check if it is good for merging.
