### ISSUE TITLE
Expose `bcrypt` as part of `argocd`

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#10050]
# Summary

If `bcrypt` is an important component of how `argocd` works, and argo-cd (the project) doesn't believe everyone has easy access to `bcrypt` (I'm willing to believe this, although at this point, it might be possible to argue that everyone has `python` or even access to `docker`), then `argocd` (the program) should offer `bcrypt` as a command that can be run to do whatever is needed to perform a `bcrypt`.

# Motivation

https://argo-cd.readthedocs.io/en/stable/faq/#i-forgot-the-admin-password-how-do-i-reset-it

> To change the password, edit the argocd-secret secret and update the admin.password field with a new bcrypt hash. You can use a site like https://www.browserling.com/tools/bcrypt to generate a new hash.

One should *never* suggest a website for something relating to credentials. It's always the wrong answer.

# Proposal

Add a `argocd bcrypt` that supports performing whatever action this series of steps imagines a user needs to do.

---

Disclaimer: At this point, I am not remotely certain these steps are meaningful as they certainly don't correspond to the structure of my instances.

**Comment by crenshaw-dev** [comment]
At the very least, we should change the docs to recommend a binary install of `bcrypt` rather than a website.

**Comment by jsoref** [comment]
@jannfis: Do you want to reopen this to cover https://github.com/argoproj/argo-cd/pull/10056#pullrequestreview-1062377967

**Comment by crenshaw-dev** [comment]
Yep, my bad, that PR didn't cover everything asked here.

**Comment by jannfis** [comment]
Yes, I actually merged the linked PR without looking at this issue.

I'm totally in favor of this enhancement proposal. Thanks.

**Comment by jannfis** [comment]
I'm not necessarily fond of exposing it as a first class command.

I think the right place where it should live is at `argocd admin account` - WDYT?

**Comment by jsoref** [comment]
If that's the only place that needs it, that sounds good.

(I wasn't trying to ask for a first class command, just a thing to cover whatever argocd needs users to use bcrypt to do)

**Comment by ameytotawar** [comment]
I am working on this issue.
