### ISSUE TITLE
Failed to sync cluster

### ISSUE THREAD

**Issue by adieu** [argoproj/argo-cd#1006]
I just upgraded our argocd instance to 0.11.0 today. The overall experience was smooth but had one issue which did not exist in 0.10.5.

Argocd is running in one of our k8s clusters and it's trying to manage applications in other k8s clusters.

One cluster failed to sync and here is the log:

```
time="2019-01-11T09:13:11Z" level=info msg="Start syncing cluster" server="https://10.0.0.1:6443"
time="2019-01-11T09:14:14Z" level=error msg="Failed to sync cluster https://10.0.0.1:6443: the server was unable to return a response in the time allotted, but may still be processing the request"
```
It looks like the sync process got timeout after around 1 minute which is possible because those two clusters are not in the same location. 

We didn't have this issue before the latest release and I was trying to identify the timeout request but failed.

I saw this log on the apiserver of the failed cluster:

```
I0111 09:38:04.687179       1 controller.go:105] OpenAPI AggregationController: Processing item v1alpha1.repositories.stash.appscode.com
I0111 09:38:04.724927       1 controller.go:116] OpenAPI AggregationController: action for item v1alpha1.repositories.stash.appscode.com: Requeue.
```

Not sure if it's related.

**Comment by jessesuen** [comment]
This was our issue:
https://github.com/argoproj/argo-cd/issues/650

One way to test is to run `kubectl get <problematic-custom-resource>`. If this is slow or fails, then it could cause problems for Argo CD.

**Comment by jessesuen** [comment]
Also it will help to enable kubernetes related logs in the `argocd-application-controller` by adding: --gloglevel 6 to see which API request may be blocked.

**Comment by adieu** [comment]
@jessesuen Thank you for your reply. I tested `repositories` resource from Stash and it will return normally. I'll enable verbose logging on `argocd-application-controller` to check if there's any block request.

**Comment by jessesuen** [comment]
Ok it may be another one. Can you share:
```
kubectl get apiservice
kubectl get crd
kubectl api-resources
```

everything in `kubectl api-resources` is expected to return in a reasonable time.

**Comment by adieu** [comment]
I can confirm there are requests got timeout but which resource caused the problem is unknown. I'll try  crd resources one by one.

```
I0115 15:25:59.852076       1 round_trippers.go:408] Response Status: 504 Gateway Timeout in 60166 milliseconds
time="2019-01-15T15:25:59Z" level=error msg="Failed to sync cluster https://10.0.0.1:6443: the server was unable to return a response in the time allotted, but may still be processing the request"
```

**Comment by jessesuen** [comment]
@adieu you may want to try `argoproj/argocd:latest` which has the fix to become best effort when api resource discovery fails for a particular api group.

**Comment by adieu** [comment]
Sadly the latest image does not help. I guess it's because the backend server is running alive and responding to discovery request correctly. The `get` request is slow but it would not timeout when getting resources from a single namespace. The timeout error will only occur when getting all snapshot resources at once. A temporary fix might be deleting some old snapshots to make the request faster.

**Comment by jessesuen** [comment]
Ok. Then we need to implement resource exclusion (issue #1010).
I assume that snapshot is not a managed resource that you need Argo CD to track/view in UI or deploy from git?

**Comment by adieu** [comment]
No. I don't need snapshot resource. I manage to work around the problem by patch the code to exclude the snapshots resource.

**Comment by alexmt** [comment]
Resource exclusion feature was implemented
