### ISSUE TITLE
applicationset - use GitHub Apps for generators when available

### ISSUE THREAD

**Issue by iamnoah** [argoproj/argo-cd#10079]
# Summary

For any generator that connects to GitHub, it should default to using any existing GitHub App repo-creds that have already been configured, or specific application credentials may be configured.

# Motivation

The best practice for giving ArgoCD (or any other code) access to repos on GitHub is to a setup an App with contents permissions (and potentially a limited set of repos.) If I am using the SCM or Pull Request generator, SCM should be able to use that app authentication to access the API without any additional permissions, and PR with one additional permission.

This is both more secure and easier for organizations to manage.

# Proposal

I have two interrelated proposals:

 1. Adopt the configuration from #9078 for the SCM & PR generators - allow a specific secret in `argocd.argoproj.io/secret-type=repo-creds` [format](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#github-app-repositories) to be configured as GitHub App authentication for a generator.
 2. If no token or other secret is specified for a generator, use any existing GitHub App repo-creds that has access to the targeted organization.

This is easily implemented by wrapping a service around argoCDDB and passing it into the SCM and PR providers.

**Comment by ricardojdsilva87** [comment]
Hello, first of all sorry for revisiting this old topic.
I can see that in the [documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Pull-Request/#github) there is the possibility to use optionally a tokenRef based on a kubernetes secret or the github app name already existent and used for the github interactions.
For the github app secret name it does not mention if is is also optional. Is the Application Controller implemented to use the same logic that is used in the [repository credentials as template](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repository-credentials)?
This way the user would only need to specify the `owner`, `repo` and `api` on the `ApplicationSet` and based on the generated link the correct credential would be used to check for the PRs.
If necessary we can modify the already used GitHub application and add any missing permissions that might be needed.
Thanks!
