### ISSUE TITLE
Can we get -l or --label CLI flag to delete apps by label?

### ISSUE THREAD

**Issue by pentago** [argoproj/argo-cd#10091]
Currently, apps can be deleted from CLI only by listing each of them individually while adding the ability to delete apps by the label can provide much-needed flexibility.

For example, `argocd sync` command has `--label` flag, we should have one for delete subcommand as well.

Thoughts?

**Comment by crenshaw-dev** [comment]
Daniel has opened a PR, but I'd [much prefer](https://github.com/argoproj/argo-cd/pull/10118#discussion_r940678585) to do the filtering server side.
