### ISSUE TITLE
Status out of sync sealed secret after syncing argocd

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1009]
```
argocd: v0.11.0+71b646d
  BuildDate: 2019-01-10T23:17:31Z
  GitCommit: 71b646dfaedfdbab9e83d314f1b76287561a18e1
  GitTreeState: clean
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v0.11.0+71b646d
  BuildDate: 2019-01-10T23:18:32Z
  GitCommit: 71b646dfaedfdbab9e83d314f1b76287561a18e1
  GitTreeState: clean
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

```
argocd app diff registry
===== /ConfigMap test-ops/registry ======
===== /Service test-ops/registry ======
===== apps/Deployment test-ops/registry ======
===== extensions/Ingress test-ops/registry ======
===== bitnami.com/SealedSecret test-ops/registry ======
7c7
<   creationTimestamp: null
---
>   creationTimestamp: 2019-01-14T11:11:53Z
```

**Comment by peterbosalliandercom** [comment]
It doesn't get applied so the secret is actually not created. When doing manually kubectl apply -f secret-sealed.yaml than it works

**Comment by jessesuen** [comment]
I believe the reason is because in git, you have: `creationTimestamp: null`. However in live, it is a date. Can you confirm?

If so, then omitting the `creationTimestamp` field in your git manifests should fix the OutOfSync issue.

That said, `creationTimestamp` is a field that Argo CD probably should ignore, since k8s has full control over that field and it is impossible to change or have configuration drift against creationTimestamp. This is something that can be easily improved in the diff libraryl

**Comment by jessesuen** [comment]
> It doesn't get applied so the secret is actually not created

Is there an error that gets displayed when Argo CD tries to apply this resource but doesn't?

**Comment by peterbosalliandercom** [comment]
CreationTimeStamp is null in the created sealed secret indeed, I can remove that but is was created by bitnami automatically: 
```
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "registry",
    "namespace": "test-ops",
    "creationTimestamp": null
  },
  "spec": {
    "encryptedData": {
...   }
  }
}
````

**Comment by peterbosalliandercom** [comment]
> > It doesn't get applied so the secret is actually not created
> 
> Is there an error that gets displayed when Argo CD tries to apply this resource but doesn't?

Did it another time and now it was deployed as secret .... strange

**Comment by peterbosalliandercom** [comment]
What about the default null value for createtimestamp? Who should check for that? I can remove it from the yaml file for now.

**Comment by jessesuen** [comment]
@peterbosalliandercom the diff library will be improved such that creationTimestamp will not affect the sync status.
