### ISSUE TITLE
Invalid label after label+annotation tracking truncation 

### ISSUE THREAD

**Issue by jgray1206** [argoproj/argo-cd#10110]
We have some apps with long names. Thankfully, in label+annotation resource tracking mode, we are able to sync most all of them! We sadly had to rename one app because it was unfortunate enough to end in a hyphen when the label was truncated to 63 chars. 

Would it be possible to strip labels of ending hyphens (and other potential invalid chars) after truncating in label+annotation tracking mode? Thank you!

**Comment by stormbeta** [comment]
We got bit by this recently as well, would be great if it could be fixed upstream so that we don't have to disable label tracking.
