### ISSUE TITLE
Application controller should expose more cluster status

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1011]
The cluster syncing process taking time and might fail due to timeouts. It would be useful to expose syncing progress to a user. The following information could be exposed:
 - syncing start time
 - syncing progress ( number of synced resource kinds / total resource kinds  )
 - average, min, max, most recent sync duration
 - most recent sync error

**Comment by alexec** [comment]
Can we close this? We can find this information in the "Sync Status" panel. Is that not good enough?

**Comment by alexmt** [comment]
Requested changes had been implemented and available via argocd-app-controller metrics.
