### ISSUE TITLE
terraform and terraform-consul-sync support

### ISSUE THREAD

**Issue by yuriy-yarosh** [argoproj/argo-cd#10145]
# Summary

Add an ArgoCD sidecar plugin for either [terraform](https://www.terraform.io/) or [terraform-consul-sync](https://github.com/hashicorp/consul-terraform-sync) (CTS) support.

# Motivation

All my yamls are in tf already, I'd like yet another config management integration, with the respective infrastructure state atomicity and locking. [tf-controller](https://github.com/weaveworks/tf-controller) is somewhat still raw, and I'm not a huge fan of [fluxcd subsystem](https://flux-subsystem-argo.github.io/website/) either.

Consul Terraform Sync (CTS) allows to replace simplest operators based on [keda](https://keda.sh/) observability i.e. keda can modify the consul k/v and trigger the respective terraform infra change via cts. It's much more flexible and simpler than [Kudo](https://kudo.dev/). Well, kudo needs some refactoring as well, so keeping the tool count minimal is always a good option.

Pretty common operators, especially database ones, could be replaced with a terraform module this way.

# Proposal

Add a sidecar plugin with either terraform or terraform-consul-sync for terraform config.
All the [kubernetes provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs) managed resources could be exported directly from the terraform state, alongside the resulted resource definitions.

**Comment by yuriy-yarosh** [comment]
There could be also a [docker](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs) provider integration there, as well.

**Comment by RossComputerGuy** [comment]
I've been looking into this since I'm looking to deploy AWS and Kubernetes things through ArgoCD. I've determined that `terraform plan --out=[file]` can output the stack in a weird binary format then use `terraform show -json [file]` to get a JSON formatted version of that. A sidecar would have to build YAML files unless there's a way to override the apply.

**Comment by yuriy-yarosh** [comment]
@RossComputerGuy there are couple of limitations and caveats - the exact pending terraform plan shouldn't break the argocd deployment itself.

My primary motivation is to simplify operator/CRD deployments by replacing them with Terraform Sync.

> A sidecar would have to build YAML files unless there's a way to override the apply.

TF Kubernetes provider itself gives you yaml.

**Comment by adamdecaf** [comment]
We plan/apply using the native Kubernetes TF provider so being able to use that without a rewrite would really help us. Terraform also serves as a fallback if our ArgoCD deploy has issues or during disaster recovery planning - as we need to simulate partial failures within our environment.

**Comment by blakepettersson** [comment]
>It seems that's where both tools should work together better.

I agree that there should be more integration between the two tools, but that should happen on the Terraform (or maybe opentofu) side IMO.

Will close this for now since the prospect of this being worked on is quite low.
