### ISSUE TITLE
Add explicit "dependsOn" functionality to Applications

### ISSUE THREAD

**Issue by karlschriek** [argoproj/argo-cd#10154]
# Summary

We would love to have the ability to define an explicit "dependsOn" field on Applications. For example:

App1 doesn't depend on anything:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: App1
spec:
  project: default
  ...
```

App2 depends on App1:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: App2
spec:
  project: default
  dependsOn: 
    - App1
  ...
```

At this stage I would like to clarify a misunderstanding that I have come across in various (now-defunc) issues. See for example:
https://github.com/argoproj/argo-cd/issues/3454
https://github.com/argoproj/argo-cd/issues/7978

The pattern described above _is not_ the same as using sync-waves with the App-of-Apps pattern (which in any case is no longer directly supported, and needs to be reactivated explicitly in order to be used, see https://github.com/argoproj/argo-cd/issues/8358, https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/1.7-1.8/#health-assessment-of-argoprojioapplication-crd-has-been-removed). 

What we are looking for is something that is self-contained on the Application itself. I.e. I want to be able to define directly on App2 that it depends on App1. If App1 doesn't exist, then App2 doesn't sync. Once App1 comes into existence, App2 will sync. If App1 re-syncs, App2 will re-sync as well after App1's sync has completed.

# Motivation

There are several circumstances where the order of deployment matters. A good example are mutating webhooks, such as Istio's `istio-sidecar-injector` which will look for the annotation `istio-injection: enabled`. If it finds it, it will inject sidecars into Pods. However, if a Pod that has been thus annotated starts up before the webhook is ready, then it will not receive the sidecars. In this case it needs to be manually restarted at a later stage. It would therefore here be extremely useful to instruct ArgoCD to wait with rolling out an Application that contains that Pod until such time as the Application with the Istio webhook is ready.

To also further clarify why using sync-waves with the "App-of-Apps" is not desired here: Our Application specs do not live inside a GitOps repo. (Only the actual resources we want ArgoCD to sync for us live inside a GitOps repo). Our Application specs are dynamically composed and rolled out. As such it is not possible to do App-of-Apps. There are some other reasons as well related to the plugin-approach we use to render our manifests, but that goes quite far beyond the scope of what we are discussing here.

# Proposal

Add the field `dependsOn` to the Application spec and then add the following to the sync logic: (I'll use App1 and App2 as listed above for example)

- If App1 does not exist, or exists but hasn't successfully synced, report that back as a "depensdOn" sync failure on App2
- If App1 has succesfully synced, proceed to sync App2

**Comment by rouke-broersma** [comment]
```
Our Application specs do not live inside a GitOps repo. (Only the actual resources we want ArgoCD to sync for us live inside a GitOps repo). Our Application specs are dynamically composed and rolled out. As such it is not possible to do App-of-Apps.
```

It seems to me your whole problem rests on and is caused by this issue you're describing. Dynamic composition of app-of-apps is very possible by using helm chart templating imo so I think your 'we cannot use app-of-apps' needs clarification. Right now it reads more like you don't want to use app-of-apps, but if you would use app-of-apps the dependsOn would not be neccesary.

**Comment by rouke-broersma** [comment]
We use app-of-apps to construct app-of-apps which are modules that contain applications + external resource manifests (like terraform operator and such) using templating. 🤷‍♀️

**Comment by karlschriek** [comment]
@crenshaw-dev thanks, I have not come across those two issues before. The topic seems to be already quite splintered, so my apologies for opening up yet another one. #7437 seems like the right home for this one (altough #3517 actually hits the nail on the head by giving it right name: what we need is the ability to define a DAG).

Shall I close this issue in favour or #7437?

**Comment by karlschriek** [comment]
@rouke-broersma that is an interesting approach. That means you cloud resources with controllers running on Kubernetes, correct?

**Comment by rouke-broersma** [comment]
Yes exactly. I thought you did as well but I guess your modules are external from kubernetes so I see how that could be an issue then.

**Comment by crenshaw-dev** [comment]
Yeah @karlschriek, let's continue to track this in https://github.com/argoproj/argo-cd/issues/7437. Depending on where most engagement goes, we can decide whether to consolidate on #3517 or #7437.

**Comment by crenshaw-dev** [comment]
"Not planned" is a terrible name for this "closed" state - just means duplicate in this context.
