### ISSUE TITLE
Importing existing k8s cluster resources into argocd

### ISSUE THREAD

**Issue by AmoghHegde21** [argoproj/argo-cd#10168]
We have already applied the helm chart in our k8s cluster manually long back. now we want to manage the deployment process through argocd. we have created the repo where we keep all the argocd application file which specify the source and destination where it should apply. now instead of syncing with already existing resource in the cluster it is recreating it 

can u help me how can i sync existing resources (importing existing resources) without overriding or recreating it.
cc: @alexmt

**Comment by iam-veeramalla** [comment]
Hi @AmoghHegde21 , Alex has answered a similar question in one of the previous issues. Please find the response below.

```
This should be supported as long as such resources can be modified using "kubectl apply".

You would have to create an application which includes resource manifest with apiVersion/name of an existing resource and add fields which you want to manage. Argo CD should detect that object exist and run kubectl apply agains it.
```

Issue comment for your reference:
https://github.com/argoproj/argo-cd/issues/2437#issuecomment-542244149

**Comment by et304383** [comment]
@iam-veeramalla can you please elaborate on whether or not you can switch from a bunch of helm charts deployed manually  to having those charts (and underlying resources) managed by ArgoCD without having to recreate said charts/resources?

IE - a zero downtime migration to using ArgoCD.

If this isn't possible, I can't imagine ArgoCD being taken seriously by anyone who already has production workloads running that wants to start using ArgoCD.

**Comment by todaywasawesome** [comment]
@et304383 Moving Helm charts to Argo CD is generally pretty straightforward. Just create an application, you can start with auto-sync turned off to see if it picks up on resources etc. The only thing Argo CD should want to do is add an annotation to resources. 

The exceptions are if the Helm charts rely on something Argo CD doesn't support, for example value lookups from the server. That's not supported so it wouldn't work.

**Comment by headyj** [comment]
@todaywasawesome what about resources on which certain field are immutable? e.g Statefulsets ?

```
one or more objects failed to apply, reason: StatefulSet.apps "postgresql" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden (retried 5 times).
```

**Comment by todaywasawesome** [comment]
@headyj hmm, I've migrated stateful sets before. It's only the annotation that needs updating. But it failed for you?

**Comment by headyj** [comment]
@todaywasawesome Yes indeed it's working, it's just a bit annoying that deployments and statefulsets needs to be recreated because labels and annotations are immutable, but I that's not related to ArgoCD.

**Comment by thiagowfx** [comment]
> The only thing Argo CD should want to do is add an annotation to resources.

@todaywasawesome (nice nickname ;)) Does it make sense to delete old helm annotations afterwards, to clean up?

**Comment by todaywasawesome** [comment]
> > The only thing Argo CD should want to do is add an annotation to resources.
> 
> @todaywasawesome (nice nickname ;)) Does it make sense to delete old helm annotations afterwards, to clean up?

Creating apps from Helm charts will create whatever annotations the Helm chart is configured to generate so I don't see that as an issue. I would probably remove the release secrets if people are going to access the cluster directly as Argo CD does not update those and it may lead to some confusion.
