### ISSUE TITLE
Helm parameter overrides not applying from .argocd-source-<appname>.yaml

### ISSUE THREAD

**Issue by egkelly** [argoproj/argo-cd#10177]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Helm parameter overrides are not being applied from my argocd-source-<appname>.yaml file that is being generated via argocd-image-updater. It looks like `appName` is not being set according to the conditional here: https://github.com/argoproj/argo-cd/blob/179d1e0e8a8859e8cc865c2adc4a8038fca84299/reposerver/repository/repository.go#L1053-L1058

When argocd-image-updater updates the image tag in `.argocd-source-<appname>.yaml`, my helm application doesn't recognize the tag override. However, if I rename `.argocd-source-<appname>.yaml` to `.argocd-source.yaml`, argocd picks up the image tag change and I can manually sync the application with the new image version. 

**To Reproduce**

1. Create a helm chart application in argocd
2. Create a file in the helm chart root called `.argocd-source-<appname>.yaml` with the following format:
```helm:
  parameters:
  - name: image.name
    value: XXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/webapp
    forcestring: true
  - name: image.tag
    value: somerandomimagehash
    forcestring: true
```
3. Return to argocd and trigger a sync on the application. Note the image-tag.
4. Change the image.tag to another valid image hash in `.argocd-source-<appname>.yaml`
5. Return to argocd and trigger a sync on the application. The image tag is not updated according to the change in the argocd-source file
6. Rename `.argocd-source-<appname>.yaml` to `.argocd-source.yaml`
7. Return to argocd and trigger a sync on the application. The image tag is updated according to the change in the argocd-source file

**Expected behavior**

The image tag should be overridden based on the image.tag value in `.argocd-source-<appname>.yaml` according to the documentation. Note that simply renaming `.argocd-source-<appname>.yaml` to `.argocd-source.yaml` is only a temporary fix as argocd-image-updater via the git writeback method will create and write to  `.argocd-source-<appname>.yaml`, ignoring `.argocd-source.yaml`

<img width="1256" alt="Screen Shot 2022-08-02 at 12 08 08 PM" src="https://user-images.githubusercontent.com/39836626/182462060-65e2c67d-4738-4593-8822-47ea7d208b94.png">

**Version**

```shell
v1.8.4+28aea3d
```

**Comment by egkelly** [comment]
Link to original issue in argocd-image-updater for more context: https://github.com/argoproj-labs/argocd-image-updater/issues/461

**Comment by crenshaw-dev** [comment]
While `.argocd-source.yaml` was supported starting in 1.8, `.argocd-source-<app name>.yaml` is [only supported starting in 1.9](https://argo-cd.readthedocs.io/en/stable/user-guide/parameters/#store-overrides-in-git).

Aside: I would strongly recommend updating to a more recent minor version. 2.2.x is the earliest version currently receiving security updates, and the prior versions have a number of [critical-severity vulnerabilities](https://github.com/argoproj/argo-cd/security/advisories).
