### ISSUE TITLE
argocd version hangs if server is unreachable

### ISSUE THREAD

**Issue by jimsnab** [argoproj/argo-cd#10178]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Similar to [login issue](https://github.com/argoproj/argo-cd/issues/9679)

I am in the middle of redeploying and my argocd is down. I have a CLI that was logged in. I do `argocd version` and it infinitely hangs trying to get the remote version.

**To Reproduce**

1. Establish argocd server (mine is stood up with Helm in k8s)
2. Use argocd CLI to log in
3. Verify proper `argocd version`
4. Take down the server
5. Try `argocd version` with server offline

**Expected behavior**

`argocd version` does not hang

Preferably something like checking local CLI version should not depend upon service connectivity. Could it be `argocd version --server`? Or `argocd version --local`? or...

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
```
argocd: v2.4.7+81630e6
  BuildDate: 2022-07-18T21:38:56Z
  GitCommit: 81630e6d5075ac53ac60457b51343c2a09a666f4
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
^C  <--- hangs infinitely here
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by iam-veeramalla** [comment]
Hi @jimsnab , I was trying to reproduce the issue using the same Argo CD CLI version and the steps that you mentioned.
```
argocd: v2.4.7+81630e6
  BuildDate: 2022-07-18T21:33:15Z
  GitCommit: 81630e6d5075ac53ac60457b51343c2a09a666f4
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: darwin/amd64
FATA[0001] Failed to establish connection to argocd-server-********.com:443: EOF
```

Am I missing something ?

**Comment by jimsnab** [comment]
I see that response and it would be the expected one. But there are times argocd will hang. I've given it 10 minutes. My argocd setup is relying on GKE and its load balancers, so apparently, the CLI is able to maintain a socket connection to the LB but isn't communicating.

I have automation that initially checks for argocd version and the job will get stuck.

Bottom line, getting a version shouldn't block on possibly unreliable network connectivity.

**Comment by iam-veeramalla** [comment]
@jimsnab so this is an intermittent issue at your end. I am only trying to reproduce the issue to understand the issue :).

**Comment by jimsnab** [comment]
Even if you can't reproduce it, because perhaps it is related to infrastructure such as GKE that you might not have, fundamentally the repo doesn't matter because networks by definition are unreliable. Getting a local version shouldn't assume otherwise.

**Comment by jimsnab** [comment]
Are you sure you can't reproduce this? I just tried this - 

1. argocd login (success)
2. go to kubernetes and delete argocd namespace
3. argocd version (hung)

It would be nice to have `--local` and `--server` flags to `version` command, and then a timeout around network i/o.

**Comment by jimsnab** [comment]
`argocd version --client`
