### ISSUE TITLE
Upgrade to go 1.19

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#10176]
# Summary

Upgrade to go 1.19.

# Motivation

There are new features/improvements. I'm particularly interested in [go gc metrics reporting](https://tip.golang.org/doc/gc-guide).

# Proposal

The PR upgrading to 1.18 can be used as a guide.

We should document that plugins might be affected by this from the [release notes](https://tip.golang.org/doc/go1.19):

> [Command](https://tip.golang.org/pkg/os/exec/#Command) and [LookPath](https://tip.golang.org/pkg/os/exec/#LookPath) no longer allow results from a PATH search to be found relative to the current directory. This removes a [common source of security problems](https://tip.golang.org/blog/path-security) but may also break existing programs that depend on using, say, exec.Command("prog") to run a binary named prog (or, on Windows, prog.exe) in the current directory. See the [os/exec](https://tip.golang.org/pkg/os/exec/) package documentation for information about how best to update such programs.

Plugin users might be relying on a binary being in the repo where the plugin is executed. v2.4 users won't be affected, because [2.4 strips executable permissions of repo contents before running plugins](https://github.com/argoproj/argo-cd/issues/9647). But folks upgrading from previous versions might notice a regression.

(Note: try not to run binaries loaded via repos. That seems bad for security.)

**Comment by OmarKalloush** [comment]
If this is as simple as upgrading to 1.18 I would like to do this please.

**Comment by crenshaw-dev** [comment]
@OmarKalloush sure! If you want to do the upgrade part, I can add the plugin docs notes later. Let me know if you need any help.
