### ISSUE TITLE
Exclude option enhancement in argocd application CRD

### ISSUE THREAD

**Issue by rshiva777** [argoproj/argo-cd#10179]
# Summary

I want an exclude particular directories/files with exact path or regex pattern  from the git repo in application manifest

What change you think needs making.

At present i am able to exclude only files with regex pattern

# Motivation

Please give examples of your use case, e.g. when would you use this.

I have the below directory structure,
**github
  -- app-front
  -- app-backend
  -- app-db
  -- app-exporter**

I want an exclude app-db and app-exporter directory in application manifest and apply yamls from other directories

# Proposal

How do you think this should be implemented?

 source:
    directory:
      recurse: true
      exclude: app-db,app-exporter ## so this will exclude all the manifests in this directories

**Comment by crenshaw-dev** [comment]
I think we already support a single exclude pattern:

https://github.com/argoproj/argo-cd/blob/3f858f58f42aeafd4029872e1fe7690d5c7d1cbd/docs/operator-manual/application.yaml#L100-L105

That field is evaluated by a [glob library](https://pkg.go.dev/github.com/gobwas/glob#Compile) that supports multiple patterns.

So I think you could use `{app-db,app-exporter}` as your exclude pattern.

**Comment by rshiva777** [comment]
@crenshaw-dev  Thanks for the inputs, but seems like the pattern {app-db**,app-exporter**} is not working.  Its expecting only string

error: error validating "app.yaml": error validating data: ValidationError(Application.spec.source.directory.exclude): invalid type for io.argoproj.v1alpha1.Application.spec.source.directory.exclude: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by rshiva777** [comment]
@crenshaw-dev  Thanks for the quick support. Seems to be the pattern is working fine.

**Comment by crenshaw-dev** [comment]
@rshiva777 ah yeah, it's trying to parse the pattern as yam. Try this:

```yaml
exclude: "{app-db**,app-exporter**}"
```

The quotes should force the YAML parser to treat the pattern as a string.

**Comment by rshiva777** [comment]
yes, it is working with double quotes. Thanks @crenshaw-dev
