### ISSUE TITLE
ArgoCD url become unresponsive and need to exit or refresh to get back to the page

### ISSUE THREAD

**Issue by renjithvchandran** [argoproj/argo-cd#10182]
Hi, We have seen argocd become unresponsive frequently while click on applications and the page either need to exit or refresh every time to get back to the page.

**Comment by iam-veeramalla** [comment]
Hi @renjithvchandran , Can you please provide additional information about issue ?
1. What is the Argo CD version ?
2. Can you see any error in the Argo CD Server logs ?

**Comment by renjithvchandran** [comment]
Hi @iam-veeramalla , We are not seeing any error during the time of issue, as its just hung in the console and we need exit the page and refresh.

Currently we are using [argocd:v2.2.9]
![Error ](https://user-images.githubusercontent.com/51434515/182789785-10ed3701-7e20-4244-815d-66495cd84308.png)

**Comment by Marvin9** [comment]
Can you try [this](https://stackoverflow.com/a/46186556/8329916) when page become unresponsive and share the screenshot of code from dev tools at which point it is stuck? @renjithvchandran
