### ISSUE TITLE
Docs: ssh repo guidance specifies url incorrectly

### ISSUE THREAD

**Issue by jimsnab** [argoproj/argo-cd#10197]
The documentation contributes to the difficulty of troubleshooting ssh repo connections by a minor oversight. [This page](https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/) shows entering an ssh URL without the `ssh://` prefix.

The prefix is required.

**Comment by crenshaw-dev** [comment]
@jimsnab per point 3 in [this section](https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#ssh-private-key-credential):

> When your SSH repository is served from a non-standard port, you have to use ssh://-style URLs to specify your repository. The scp-style git@yourgit.com:yourrepo URLs do not support port specification, and will treat any port number as part of the repository's path.

I think the prefix is only required for non-standard ports.

**Comment by christianh814** [comment]
This has already been documented https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/

Should probably close this issue
