### ISSUE TITLE
ksonnet show should order resources by k8s proper creation order

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#102]
A promised feature of ArgoCD is that it should create things in proper kubernetes ordering (e.g. namespaces, configmaps, secrets earlier than deployments, etc...)

**Comment by merenbach** [comment]
@jessesuen is this server-side only? During install?  Does this apply to updates, too?

**Comment by jessesuen** [comment]
I think instead of sorting based on what we think is the correct kuberentes order, we should support helm-style numeric weight annotations. When deploying, we can sort by weight before applying in the sorted order.

**Comment by jessesuen** [comment]
> I think instead of sorting based on what we think is the correct kuberentes order, we should support helm-style numeric weight annotations. When deploying, we can sort by weight before applying in the sorted order.

Actually, helm has already done the hard work of figuring out the proper creation order. We can leverage what they have done:
https://github.com/kubernetes/helm/blob/master/pkg/tiller/kind_sorter.go

I think we can start with a default deploy order, before deciding if weights are desired. Implementing weights will be a separate issue

**Comment by jessesuen** [comment]
Fixed
