### ISSUE TITLE
Is it a good idea to move url from out of configMap argocd-cm?

### ISSUE THREAD

**Issue by mfabricanti** [argoproj/argo-cd#10205]
# Summary

For now, we have around 20+ clusters with one ArgoCD instance per cluster.
In order to manage (mainly thinking in the update process) we've installed one instance to rule all other instances.

When I download the new [installation manifest](https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.8/manifests/ha/install.yaml) and commit to the repo, this ArgoCD instance (named as One Ring... call me nerd... lol) applies it to all other instances.

# Motivation

Since the argocd-cm has the URL field, I cannot sync this cm with this process.
So before commit the installation manifest in the repo, I remove the argocd-cm block.

This causes me a problem when a need to sync another config change (like accounts permissions, for example) to all clusters. I have to do it manually!

# Proposal

My proposal to solves this: **when no {data.url} parameter is found in cm argocd-cm, the server will try to read an environment variable in the argocd-server deployment.**

This will enables me to store the cluster URL in a different configMap or secret with only this config, and achieve my main goal that is to put argocd-cm in my automatic updating process.

What do you think about this idea?

**Comment by crenshaw-dev** [comment]
Have you considered using a Kustomize overlay to modify the install manifests? I'm not sure how powerful Kustomize's ConfigMap-overriding capabilities are, but at the very least it should be possible with a JSON patch.

**Comment by rouke-broersma** [comment]
Either that or use helm if Kustomize is not sufficient.

**Comment by crenshaw-dev** [comment]
Closing for now. @mfabricanti let me know if the proposed workarounds aren't sufficient!
