### ISSUE TITLE
Failed to query provider <url>/api/dex: 503 Service Unavailable: upstream connect error or disconnect/reset before headers. reset reason: connection termination

### ISSUE THREAD

**Issue by Prarthana29** [argoproj/argo-cd#10249]
I had set up the SSO auth using GitHub which resulted in this 503 service being unavailable
Checklist:

*   [SSO setup with dex ](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management)

**Describe the bug**
When I tried to set up the SSO resulted in the `503 Service Unavailable: upstream connect error or disconnect/reset before headers. reset reason: connection termination
`

**Expected behavior**

Login to the ArgoCD UI using Github

**Comment by Prarthana29** [comment]
the issue got resolved by adding field appprotocol as TCP in  **argocd-dex-server** service as per the [istio documentation ](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/). I am not sure if it is a bug

**Comment by da6d6i7-bronga** [comment]
I am seeing the same issue. I also was able to resolve it with the above fix.

`ports:
  - appProtocol: TCP
    name: http
    port: 5556
    protocol: TCP
    targetPort: 5556`
