### ISSUE TITLE
error while creating application

### ISSUE THREAD

**Issue by zillani** [argoproj/argo-cd#10243]
**How to reproduce?**

From argocd UI,
New App -> specify helm chart repo URL -> chart -> version

**Error**
The network call from argocd is giving 500x error with the log, 

{"error":"lstat /tmp/31b66186-770d-48e3-aa6a-7e3ad6c99ca8/mychart: no such file or directory","code":2,"message":"lstat /tmp/31b66186-770d-48e3-aa6a-7e3ad6c99ca8/cuup: no such file or directory"}

the logs of argocd repo server also has the same error
```
lstat /tmp/31b66186-770d-48e3-aa6a-7e3ad6c99ca8/mychart
```

**Comment by zillani** [comment]
This is happening only for a specific version of my chart.

**Comment by todaywasawesome** [comment]
Sounds like a chart specific issue. Closing for now. If you find more information about why that specific chart is causing an error, let us know :)
