### ISSUE TITLE
ArgoCD not auto syncing when using annotation based resource tracking

### ISSUE THREAD

**Issue by roelvdberg** [argoproj/argo-cd#10269]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Diffing/syncing is not working correctly when using annotation based tracking.
We see this clearly when we deploy a custom resource which is not compliant with its CRD.

**To Reproduce**

Configure annotation based tracking 
Deploy a valid manifest and make sure it is synced.
Change the manifest, ArgoCD is not detecting that it should sync the manifest.

It is detecting that there is a diff in the manifest.

**Expected behavior**
I would expect ArgoCD to start syncing as soon as it detects a new change. At least say that it is out of sync. (when autosync is off)

**Screenshots**
Annotations:
![1 img-1-annotation](https://user-images.githubusercontent.com/5803989/183944849-efc59d50-b15a-439c-9fe0-a1c4f960a434.PNG)
![2 img-2-annotation](https://user-images.githubusercontent.com/5803989/183945025-d18c21bf-dee5-4274-81d1-40780e546bd3.PNG)
Labels:

![3 img-1-label](https://user-images.githubusercontent.com/5803989/183945173-1b1fe6c4-87c9-4a4f-964c-bff1215f3cb9.PNG)
![4 img-2-label](https://user-images.githubusercontent.com/5803989/183945196-6e460cec-cac9-4bea-af1c-b2991b96a2b3.PNG)

**Version**

```shell
argocd: v2.4.7+81630e6
  BuildDate: 2022-07-18T21:38:56Z
  GitCommit: 81630e6d5075ac53ac60457b51343c2a09a666f4
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.8+844f79e
  BuildDate: 2022-07-29T17:01:39Z
  GitCommit: 844f79eb9d8f3ab96d4ce6f8df211c6093a660ba
  GitTreeState: clean
  GoVersion: go1.18.4
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jannfis** [comment]
@todaywasawesome Thanks, it actually is related. I have a patch ready that I'm currently writing e2e tests for.

**Comment by jannfis** [comment]
Just as a heads-up, v2.4.11 which includes the fix for this issue has been released today.
