### ISSUE TITLE
Update built-in tools for 2.5

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#10273]
We'll be cutting an RC for 2.5 soon and, as such, we should probably get all the built-in tools as up to date as possible. 

https://github.com/argoproj/argo-cd/blob/master/hack/tool-versions.sh

In particular, I known Helm 3.9.3 includes some transient security fixes, I believe due to upgrading golang.

**Comment by 34fathombelow** [comment]
Feel free to assign this one to me as well.

Holding off on Kustomize at this time.  Bumping from v4.5.5 --> v4.5.7 does not provide much functionality nor does it address 2 high CVE's in the binary.

**Comment by ejhayes** [comment]
Hey @crenshaw-dev any idea when the 2.5 RC will be created?

**Comment by crenshaw-dev** [comment]
@ejhayes given that we really want to get multi-source apps into this release, and that PR is still under heavy review/testing, I think Friday of next week (9/30) would be a _very_ aggressive timeline for the first RC.
