### ISSUE TITLE
Summary Information at resource level can be enhanced 

### ISSUE THREAD

**Issue by Avni-Sharma** [argoproj/argo-cd#10286]
# Summary
Summary Information can be enhanced with more information for more visibility, like the total time of a resource.

# Motivation

While right now we get to see the resource's time elapsed attached as a block on the resource tile/node, it was seen during interaction with end users that they intuitively went to the summary information level to view all the info for that particular resource. We currently have the created_at.  So information like the total time of a resource can be surfaced as well.  
<img width="974" alt="Screen Shot 2022-08-11 at 12 21 53 PM" src="https://user-images.githubusercontent.com/18097007/184222592-8e305cdb-a95e-4d5f-8c72-1d0033c06825.png">

# Proposal
surface another field like time_existing/time_elapsed at the summary info level for each resource.

####  difficulty: low

**Comment by ashutosh16** [comment]
User can  use basic math to compute the total time since the resource was created. Adding one more key/value is not recommended as it will push the manifest block further down. Any suggestions?

**Comment by crenshaw-dev** [comment]
@ashutosh16 what if we added the "duration" form of the time on the same line? Like "12/16/2021 16:37:35 (5 hours ago)".
