### ISSUE TITLE
Too large app names are not so useful when viewed on the UI

### ISSUE THREAD

**Issue by Avni-Sharma** [argoproj/argo-cd#10291]
# Summary
 Sometimes users can give extremely large App Names which are not very helpful when viewed on the ArgoCD. 

# Motivation
Sometimes the App names can be too large, given by the user or being generated

<img width="1242" alt="184260697-0c92bca3-4c33-4957-b778-d84c324727a9" src="https://user-images.githubusercontent.com/350466/184942358-2ee801b2-5595-4fd4-81c0-213d34c53150.png">

# Proposal
Additional tooltips can help in a better user experience. 

####  difficulty: medium

**Comment by ashutosh16** [comment]
The issue was fixed in v2.4 against the [PR](https://github.com/argoproj/argo-cd/pull/9130)

**Comment by ashutosh16** [comment]
@crenshaw-dev  Issue seems to be resolved. Please check the fix [pull/9130]
(https://github.com/argoproj/argo-cd/pull/9130) and close the issue as needed. Thx!
