### ISSUE TITLE
Web terminal should print errors messages instead of failing request with error code

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#10307]
**Describe the bug**

Web terminal API returns errors if something is misconfigured. For example, if the user doesn't have permissions, then API just returns 500:

![image](https://user-images.githubusercontent.com/426437/184415231-954bbff6-9de4-4395-bf0c-059c4cc2f2e7.png)

It makes it pretty difficult to troubleshoot any errors and user experience is not great.

**To Reproduce**

* Enable web terminal
* Try to access terminal using user who don't have permissions

**Expected behavior**

Error messages should be printed in terminal itself to clearly communicate problem to user.

**Version**

```shell
v2.4.9
```

**Comment by linjun0703** [comment]
I was in the same situation

**Comment by jannfis** [comment]
We should make sure not to pass too detailed error messages to the user, as they could contain sensitive information.

Generally, from the recent security audits, we came to the conclusion that the less details are included in an error message displayed to the user, the better and that details belong to the log files.

In this case, it probably makes sense to return a 401 and maybe even display "Unauthorized" in the web terminal. But I wouldn't go into much more detail.

**Comment by jannfis** [comment]
Also, maybe it even makes sense to hide the Terminal tab in case when the user doesn't have permission to access the web terminal for a given application.

**Comment by crenshaw-dev** [comment]
@alexmt that should have been fixed in 2.4.9 with this change: https://github.com/argoproj/argo-cd/issues/9920

What's the exact error on the backend?

**Comment by alexmt** [comment]
It is fixed indeed. Terminal no longer visible if user don't have permissions.
