### ISSUE TITLE
Ability to subscribe to notification from Application Details page

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#10310]
# Summary

It should be possible to subscribe to a notification from the Application Details. The user should be able to open the Application Details page and add required subscriptions using input with auto-completion.

# Motivation

It is already possible to subscribe to notifications by modifying annotations hoverer this is a pretty poor user experience. User have to understand annotation structure and have to guess which services and triggers are available.

# Proposal

Two changes are required: 

* [x] Implement notifications API that would expose list of configured triggers and services
* [ ] Implement UI that leverages notifications API and helps user to create correct annotation.

**Comment by aborilov** [comment]
working on it

**Comment by alexmt** [comment]
API is done. Thanks @aborilov
