### ISSUE TITLE
Cluster resources are no longer considered tracked

### ISSUE THREAD

**Issue by dctrwatson** [argoproj/argo-cd#10314]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Cluster resources are no longer tracked when using `annotation` or `annotation+label` method

Bug was introduced by: https://github.com/argoproj/argo-cd/pull/9791

In order to known the structure of the annotation value, a namespace is always added: https://github.com/argoproj/argo-cd/blob/b0bb52adcac1903779d44480c6e9c8d624610970/util/argo/resource_tracking.go#L114-L116

However, cluster resources are namespace-less, so this check will always fail: https://github.com/argoproj/argo-cd/blob/b0bb52adcac1903779d44480c6e9c8d624610970/controller/state.go#L705

**To Reproduce**

- Set `application.resourceTrackingMethod: annotation` or `application.resourceTrackingMethod: annotation+label`
- Cluster resources are now all `Unknown`

**Expected behavior**

- Cluster resources are tracked no matter than the `resourceTrackingMethod`

**Comment by jessesuen** [comment]
> Cluster resources are now all Unknown

This seems like it would be a serious issue if true. I'm not seeing this issue myself running v2.4.8. @jannfis could you verify this is really the case?

**Comment by jannfis** [comment]
Thanks for the heads-up, checking.

**Comment by jannfis** [comment]
Yep. Can verify. The `annotation` tracking method sets a namespace in the annotation for the cluster scoped resource, and the new code for checking for self-reference obviously returns false, thus marking the resource as unmanaged.

**Comment by jannfis** [comment]
Thank you @dctrwatson , your analysis was spot on.

**Comment by dctrwatson** [comment]
Thank you for @jannfis for fixing!

**Comment by jannfis** [comment]
Just as a heads-up, v2.4.11 which includes the fix for this issue has been released today.

**Comment by dctrwatson** [comment]
> Just as a heads-up, v2.4.11 which includes the fix for this issue has been released today.

Awesome! thanks for the heads-up
