### ISSUE TITLE
Lots of logs on application-controller due to info logs related to CRDs

### ISSUE THREAD

**Issue by diodel-agr** [argoproj/argo-cd#10369]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

By default, ArgoCD ignores the "status" and "spec.preserveUnknownFields fields" of the CRDs. These actions are logged as INFO in the code, which generates a lot of logs.

For instance, we have a cluster with roughly 140 Applications and in a 15 minutes period, ArgoCD application-controller exports around 16000 logs only with `Ignore '/spec/preserveUnknownFields' for CustomResourceDefinitions`. This log follows another frequent log message: `Ignore status for CustomResourceDefinitions`. In a 15 minutes period, application-controller has around 116000 logs, 25% of these are from these log messages.

Looking into the source code, those log messages are logged as INFO and were introduced as part of [this](https://github.com/argoproj/argo-cd/pull/3754/files#diff-3b21889f7a356a28ebba12c6d339b945d7171a83b4dd603c0902e62cee3051ffR482) issue. Last update to that code has been made as part of [this](https://github.com/argoproj/argo-cd/pull/6503/files#diff-3b21889f7a356a28ebba12c6d339b945d7171a83b4dd603c0902e62cee3051ffR560) issue.

**To Reproduce**

I do not have reproducing steps, but I guess that any deployment of ArgoCD with some Applications might give similar results.
To give you more details about our environment:

- we have ArgoCD version 2.3.3 deployed inside a kubernetes cluster version 1.21
- we have around 140 Applications
- we employ the apps-of-apps pattern using a single app-root Application
- every change inside the gitops repository, will trigger 2 API calls on ArgoCD: sync on the updated Application resource + another sync on the app-root Application (refresh=true).

**Expected behavior**

We expect that those logs be exported as DEBUG or TRACE, or they should be exported only once when the application starts.

**Version**

```shell
argocd: v2.3.3+07ac038
  BuildDate: 2022-03-30T00:06:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
Lots of:
```
Ignore status for CustomResourceDefinitions
Ignore '/spec/preserveUnknownFields' for CustomResourceDefinitions
```

**Comment by jessesuen** [comment]
I agree that the `Ignore '/spec/preserveUnknownFields' for CustomResourceDefinitions` message is annoying and should be removed
