### ISSUE TITLE
Pulling ArgoCD into Istio service-mesh leads to configmap/secret informers failing

### ISSUE THREAD

**Issue by karlschriek** [argoproj/argo-cd#10391]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Pulling ArgoCD into the Istio service mesh (e.g. by setting the `istio-injection: enabled` label on the argocd namespace) so that all deployed Pods start with an istio-proxy sidecar, leads to the following error message on argocd-server starting up:

```
time="2022-08-18T19:12:22Z" level=info msg="Starting configmap/secret informers"
W0818 19:12:22.088648       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.Secret: Get "https://10.1.0.1:443/api/v1/namespaces/argocd/secrets?limit=500&resourceVersion=0": dial tcp 10.1.0.1:443: connect: connection refused
W0818 19:12:22.088650       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.ConfigMap: Get "https://10.1.0.1:443/api/v1/namespaces/argocd/configmaps?labelSelector=app.kubernetes.io%2Fpart-of%3Dargocd&limit=500&resourceVersion=0": dial tcp 10.1.0.1:443: connect: connection refused
E0818 19:12:22.088698       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: Get "https://10.1.0.1:443/api/v1/namespaces/argocd/secrets?limit=500&resourceVersion=0": dial tcp 10.1.0.1:443: connect: connection refused
E0818 19:12:22.088702       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://10.1.0.1:443/api/v1/namespaces/argocd/configmaps?labelSelector=app.kubernetes.io%2Fpart-of%3Dargocd&limit=500&resourceVersion=0": dial tcp 10.1.0.1:443: connect: connection refused
time="2022-08-18T19:12:23Z" level=info msg="Configmap/secret informer synced"
time="2022-08-18T19:12:23Z" level=info msg="argocd v2.4.8+844f79e serving on port 8080 (url: , tls: false, namespace: argocd, sso: false)"
time="2022-08-18T19:12:23Z" level=info msg="0xc000115200 subscribed to settings updates"
time="2022-08-18T19:12:23Z" level=info msg="Starting rbac config informer"
time="2022-08-18T19:12:23Z" level=info msg="RBAC ConfigMap 'argocd-rbac-cm' added"
```

The same errors also occur on argocd-application-controller, argocd-dex-server etc.

**To Reproduce**

Deploy istio and set the label `istio-injection=enabled` on the ArgoCD namespace

**Expected behavior**

The istio-sidecar regulates traffic within the service mesh based on various Istio CRs, such as AuthorizationPolicies. The above error however occurs with an "allow-all" authorization policy being switched on, so there should be nothing that Istio is explicitly blocking here.

**Version**

```shell
argocd: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:44:14Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:23:37Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Comment by alxivanov** [comment]
I know this an old issue, but for anyone who stubles across this problem there is a workaround that might help:
`oc edit deploy argocd-server` -> Add the following annotations:
              traffic.sidecar.istio.io/excludeOutboundIPRanges: "172.30.0.1/32"
              traffic.sidecar.istio.io/excludeOutboundPorts: "443"
I think they can be added to your kustomization.yaml file along with sidecar.istio.io/inject: "true".
For me the IP range was based on `oc get svc kubernetes -n default -o jsonpath='{.spec.clusterIP}'`
