### ISSUE TITLE
Namespace field in New Application panel is confusing

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#10392]
**Describe the bug**

The new `Application Namespace` field is confusing. Users ( including myself ) confuse this field with the project field. The error message sounds like the application destination namespace is not allowed in the project.

**To Reproduce**

Reproduced it trying to create guestbook app in new Argo CD version

**Expected behavior**

I think `Application Namespace` field should be hidden unless multiple namespace feature is enabled.

**Screenshots**

<img width="739" alt="Screen Shot 2022-08-18 at 1 23 27 PM" src="https://user-images.githubusercontent.com/426437/185487906-7beb8de9-7340-4a07-aa37-4fcf29db3a56.png">

**Version**

```shell
master (v2.5.0-unreleased)
```

**Comment by jannfis** [comment]
Do you think it makes sense to handle this similar to as in the CLI, @alexmt ?

E.g. having only the `Name` field, and if someone specifies the application name as `guestbook` or `argocd/guestbook` it will be created in the control plane's namespace, and if someone specifies `default/guestbook`, it would be created in the `default` namespace.

I was initially thinking about that, but I was going the easy way for the UI changes :)

As for the error message, WDYT about the following:

`Application XXX with project PPP is not allowed to be created in namespace YYY`
