### ISSUE TITLE
ArgoCD can't create namespace automatically on cluster

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-cd#10411]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.

**Describe the bug**
ArgoCD can't create namespace automatically.

**To Reproduce**
I have follow [this](https://github.com/argoproj/argo-cd/issues/1809#issuecomment-860123674) for declarative setup on my yaml file.
But the namespace didn't create automatically. I must manual create the namespace via kubectl or yaml file.

**Expected behavior**
ArgoCD can create namespace automatically without my intervention directly.

**Screenshots**
![image](https://user-images.githubusercontent.com/102344789/185771450-f04e11db-694e-4662-81d8-44b60acb13be.png)

**Comment by filipjosifoski** [comment]
Hello mueherizky. 

The syncOption to create namespace seems to be working fine for me, could you give us more information about the version of your ArgoCD and possibly the Application manifest?

**Comment by mueherizky** [comment]
> Hello mueherizky.
> 
> The syncOption to create namespace seems to be working fine for me, could you give us more information about the version of your ArgoCD and possibly the Application manifest?

Sorry, only this time i can reply your comment. I use minikube cluster with docker driver. I use Pop OS 22.04 before, now in fedora 36.
btw, i'm not use argo cli, i just apply argo manifest file from [this method](https://argo-cd.readthedocs.io/en/stable/getting_started/#1-install-argo-cd)
I just want to test argo on CD step. My CI use jenkins, but now i want to use github actions.

1. My argo setup file:
    https://pastebin.com/KFDV7UUx
1. My deployment file:
    https://pastebin.com/TLSGkG7i

**Comment by crenshaw-dev** [comment]
The value of the sync option is case-sensitive. Use `CreateNamespace=true`.
