### ISSUE TITLE
http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by Gimbitgaram** [argoproj/argo-cd#10418]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
I created a pod by importing the image in the nexus docker repo, but I get an error

**To Reproduce**

**Expected behavior**
creation of pods

**Screenshots**
![image](https://user-images.githubusercontent.com/97927143/185818936-42857fa7-d099-4f4d-a9be-ca8cc924e843.png)

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
@Gimbitgaram I don't think this is an Argo CD issue. Argo CD is just reporting the Event associated with your Pod. Kubernetes tried to pull a container and got an error. This will have to be debugged at the Kubernetes/image-pull level. Argo CD is just the messenger.  :-)
