### ISSUE TITLE
Rollouts Extension UI More Tab Displays "Something went wrong with Extension for Rollout"

### ISSUE THREAD

**Issue by kmlamkin9** [argoproj/argo-cd#10424]
**Describe the bug**

When traversing through rollout detail tabs, under more I see the message: "Something went wrong with Extension for Rollout". This takes place when a rollout has no pods currently running and in other instances as well. 

**To Reproduce**

* Navigate to ArgoCD UI
* Select an application to go to the Application Details Tree View
* Select the rollout object in the Application Details Tree View
* Select the more tab and see the error message

**Expected behavior**

We want to display a more graceful message explaining there needs to be pods running in order for the dashboard to provide insights and for other issues that may be taking place in the rollout.

**Screenshots**

![error in rollouts](https://user-images.githubusercontent.com/57961933/186033528-086fee4a-8fb7-4ba6-a5e3-1c138c90c663.png)

**Version**

{
    "Version": "v2.4.6+aa2ec7a.dirty",
    "BuildDate": "2022-08-18T13:04:25Z",
    "GitCommit": "aa2ec7a5612198ce1f4193cc6d8aa8d30331ee96",
    "GitTreeState": "dirty",
    "GoVersion": "go1.18.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.1+g5cb9af4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by schakrad** [comment]
@Hari, Could you please assign me this issue.

**Comment by schakrad** [comment]
https://github.com/argoproj-labs/rollout-extension/commit/6022db1c82d7bd73fca096ddee8d721ec98b13e2
Th above commit will resolve the bug.

**Comment by kmlamkin9** [comment]
Thanks @schakrad ! Closing issue
