### ISSUE TITLE
Synchronization failed when using non existing application namespace on cluster resources

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1045]
Cluster resources do not need a namespace for deployment:

![image](https://user-images.githubusercontent.com/9946020/51371763-5ebbf300-1afb-11e9-98f3-955d9f86e19c.png)

So it shouldn't use a namespace at all. 

An error occurs if you use a non existing namespace, this is not correct. 

![image](https://user-images.githubusercontent.com/9946020/51371828-8a3edd80-1afb-11e9-8693-b7e04008e041.png)

**Comment by alexmt** [comment]
Issue was fixed by https://github.com/alexmt/argo-cd/commit/cafe24da864d3e263eae78cb38c87b7cb21768b9 and fix is available in v1.0-rc1.
