### ISSUE TITLE
No such entrypoint in argocd-applicationset image

### ISSUE THREAD

**Issue by magf** [argoproj/argo-cd#10453]
**Describe the bug**

argocd-applicationset-controller deployment says:

> [FATAL tini (7)] exec argocd-applicationset-controller failed: No such file or directory

**To Reproduce**

Just try to install any versions newer 2.3 (_latest 2.4.11 today, for example_) where is file `manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml` present

Or just run container with command from `argocd-applicationset-controller-deployment.yaml`

```bash
docker run -it --rm quay.io/argoproj/argocd-applicationset:v0.4.1 entrypoint.sh argocd-applicationset-controller
```

You'll see:

> [FATAL tini (7)] exec argocd-applicationset-controller failed: No such file or directory

Because `argocd-applicationset-controller` not exist. You should use `applicationset-controller`  instead of `argocd-applicationset-controller` or rename `applicationset-controller` to `argocd-applicationset-controller` in `quay.io/argoproj/argocd-applicationset` image

```bash
docker run -it --rm quay.io/argoproj/argocd-applicationset:v0.4.1 whereis applicationset-controller
applicationset-controller: /usr/local/bin/applicationset-controller
```

latest too

```bash
docker run -it --rm quay.io/argoproj/argocd-applicationset whereis applicationset-controller
applicationset-controller: /usr/local/bin/applicationset-controller
```

but in `argocd-applicationset-controller-deployment.yaml`:

```
...
    spec:
      containers:
        - command:
            - entrypoint.sh
            - argocd-applicationset-controller
...
```

**Comment by kosksq** [comment]
I got the same error too, but I deployed with Rancher. I also got "TypeError: Cannot read properties of null (reading 'Version')" while I try to access the GUI.

**Comment by AydinChavez** [comment]
have the same issue. But adjusting the entrypoint in the deployment part to 
`- applicationset-controller`
did not help. Still same error

**Comment by crenshaw-dev** [comment]
quay.io/argoproj/argocd-applicationset used applicationset-controller as the command name.

That image is no longer being maintained. Starting with 2.4.0, the ApplicationSet controller uses quay.io/argoproj/argocd, and the entrypoint command is argocd-applicationset-controller.

Make sure you're using the latest manifests, which reference the new image and new entrypoint command.

Also make sure nothing in your manifest build process is replacing the new image reference with the old image reference (for example, a Kustomize overlay with an image override).
