### ISSUE TITLE
Permission error on `History and Rollback` tab on Argo UI

### ISSUE THREAD

**Issue by SharifiFaranak** [argoproj/argo-cd#10464]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Some Argo users (not all) are seeing the following error when they are on the `History and Rollback tab` on the ArgoCD UI. 
```
Unable to load data: permission denied: repositories, get, https://github.com/<org>/<repo>
```
The way that their permissions are set up is not any different than permissions of those who do not see this error in that tab. 
**To Reproduce**

This error only shows for some users and thus isn't 💯 reproducible. 
But for someone who does see this error, all they would do is to log in to Argo, select an application, go to the History and Rollback tab, and see the error. 
**Expected behavior**

Expect there to be no error
**Screenshots**
![Screen Shot 2022-08-26 at 1 38 54 PM](https://user-images.githubusercontent.com/35040509/186961331-a1795121-2a7b-4b5a-a1a0-9d7b3c5ce70d.png)

**Version**

```shell
`v2.4.7+81630e6` 
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by stephenpmurray** [comment]
+1 We are also seeing this error

**Comment by bezio** [comment]
How did you fix it? We're also running into that issue....
