### ISSUE TITLE
ArgoCD UI buttons/search not working in top bar

### ISSUE THREAD

**Issue by EugeneLugovtsov** [argoproj/argo-cd#10461]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The top bar buttons stop working after upgrading from 2.4.7 to 2.4.11. 
On the second screenshot, I can click the buttons at the bottom of the top bar.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/34510252/186880080-fc11ada4-3aeb-4b18-9649-b74e7c596507.png)
![image](https://user-images.githubusercontent.com/34510252/186880148-47efc580-766f-4fd1-be3c-8529110afb27.png)

**Version**

```shell
argocd: v2.2.3+987f665
  BuildDate: 2022-01-18T17:58:47Z
  GitCommit: 987f6659b88e656a8f6f8feef87f4dd467d53c44
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.4.11+3d9e9f2
  BuildDate: 2022-08-22T09:13:16Z
  GitCommit: 3d9e9f2f95b7801b90377ecfc4073e5f0f07205b
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by EugeneLugovtsov** [comment]
I found that for div element with class page__top-bar is 100px and it covers buttons (new app, sync apps and etc). The same element on the https://cd.apps.argoproj.io/ is 50 px

![image](https://user-images.githubusercontent.com/34510252/187914726-ae92e179-a5a4-4da9-9579-cfa1fa1bdd92.png)

**Comment by EugeneLugovtsov** [comment]
https://github.com/argoproj/argo-cd/issues/10677

**Comment by jessesuen** [comment]
@EugeneLugovtsov @nice-pink - are either of you happen to be using the rollout extension or any other UI extension for that matter? There was a bug in v0.2.0 and below, fixed in rollouts v0.2.1, that caused the same issue.

https://github.com/argoproj-labs/rollout-extension/releases/tag/v0.2.1

**Comment by nice-pink** [comment]
@jessesuen we are using rollouts extension. I'll check if the update fixes the issue for us.

**Comment by EugeneLugovtsov** [comment]
I can confirm after updating the rollout extension to 0.2.1; everything works as expected. Thanks @jessesuen
