### ISSUE TITLE
argocd-server pod crashing with Liveness probe failed and restarts

### ISSUE THREAD

**Issue by sandeepitachi** [argoproj/argo-cd#10485]
argocd-server pod is crashing and restarting the container. Error shown in events is below
`Liveness probe failed: Get "http://x.x.x.x:8080/healthz?full=true": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

argocd version - v2.4.0

![image](https://user-images.githubusercontent.com/25717719/187519193-817845cd-4b5e-42ec-ae2e-6b2af2efa336.png)

The other pods (repo-server and application-server) are healthy 
This issue is on our prod argocd server. Any idea what could fix the issue? thanks in advance!

**Comment by mnacharov** [comment]
Lack of information...

check logs and make sure argocd-server has enough resources

**Comment by sandeepitachi** [comment]
Forgot to close this. Yes had to bump resources
