### ISSUE TITLE
2.4.10 installation issue: standard_init_linux.go:220: exec user process caused "permission denied"

### ISSUE THREAD

**Issue by yangtian9999** [argoproj/argo-cd#10487]
Checklist:

* [y ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ y] I've included steps to reproduce the bug.
* [y ] I've pasted the output of `argocd version`.

**Describe the bug**

simply installation via 
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.10/manifests/install.yaml

pod: argocd-dex-server
container: dex
error logs in dex container:  
standard_init_linux.go:220: exec user process caused "permission denied"
2022/8/31 09:57:37 libcontainer: container start initialization failed: standard_init_linux.go:220: exec user process caused "permission denied"

**To Reproduce**
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.10/manifests/install.yaml

**Expected behavior**

**Screenshots**

NAMESPACE                 NAME                                                READY   STATUS             RESTARTS   
argocd                    argocd-application-controller-0                     1/1     Running            0          
argocd                    argocd-applicationset-controller-658658c54d-xx7pp   1/1     Running            0          
argocd                    argocd-dex-server-55dff58875-gbbxq                  0/1     CrashLoopBackOff   6          
argocd                    argocd-notifications-controller-766797cb5f-wnf87    1/1     Running            0          
argocd                    argocd-redis-7b8959877f-q2qqn                       1/1     Running            0          
argocd                    argocd-repo-server-7bbdb5bcf6-dhdlr                 0/1     Running            6          
argocd                    argocd-server-8b8669977-2msgv                       1/1     Running            0          

pod: argocd-dex-server
container: dex
error logs in dex container:  
standard_init_linux.go:220: exec user process caused "permission denied"
2022/8/31 09:57:37 libcontainer: container start initialization failed: standard_init_linux.go:220: exec user process caused "permission denied"

**Version**

argocd: 2.4.10
k8s: 1.19.8
docker: 18.09.0
os: Kylin Linux Advanced Server V10
kernel: 4.19.90-23.8.v2101.ky10.x86_64

```shell
Paste the output from `argocd version` here.
```

**Logs**
pod: argocd-dex-server
container: dex
error logs in dex container:  
standard_init_linux.go:220: exec user process caused "permission denied"
2022/8/31 09:57:37 libcontainer: container start initialization failed: standard_init_linux.go:220: exec user process caused "permission denied"
```
Paste any relevant application logs here.
```

**Comment by bernardyoung** [comment]
遇到了相同的问题，
argocd: 2.3.0
k8s: 1.23.14
docker: 19.03.15
os: Kylin Linux Advanced Server V10
内核：4.19.90-24.4.v2101.ky10.x86_64

**Comment by yang1hc** [comment]
Modify as follows
os: Kylin Linux Advanced Server V10
 containers:
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
      initContainers:
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 0
          runAsGroup: 0
          seccompProfile:
            type: RuntimeDefault
------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/name: argocd-dex-server
    app.kubernetes.io/part-of: argocd
  name: argocd-dex-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-dex-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/part-of: argocd
              topologyKey: kubernetes.io/hostname
            weight: 5
      containers:
      - command:
        - /shared/argocd-dex
        - rundex
        env:
        - name: ARGOCD_DEX_SERVER_DISABLE_TLS
          valueFrom:
            configMapKeyRef:
              key: dexserver.disable.tls
              name: argocd-cmd-params-cm
              optional: true
        image: xxxx/library/dexidp/dex:v2.37.0
        imagePullPolicy: Always
        name: dex
        ports:
        - containerPort: 5556
        - containerPort: 5557
        - containerPort: 5558
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /shared
          name: static-files
        - mountPath: /tmp
          name: dexconfig
        - mountPath: /tls
          name: argocd-dex-server-tls
      initContainers:
      - command:
        - cp
        - -n
        - /usr/local/bin/argocd
        - /shared/argocd-dex
        image: xxxx/library/argoproj/argocd:v2.6.13
        imagePullPolicy: Always
        name: copyutil
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 0
          runAsGroup: 0
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /shared
          name: static-files
        - mountPath: /tmp
          name: dexconfig
      serviceAccountName: argocd-dex-server
      volumes:
      - emptyDir: {}
        name: static-files
      - emptyDir: {}
        name: dexconfig
      - name: argocd-dex-server-tls
        secret:
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          - key: ca.crt
            path: ca.crt
          optional: true
          secretName: argocd-dex-server-tls

**Comment by mfmessaoudi** [comment]
Hello, 
I got the same error trying to install argocd 
**unable to start container process: exec: "/shared/argocd-dex": permission denied: unknown**

images in yaml file:

------
quay.io/argoproj/argocd:latest
ghcr.io/dexidp/dex:v2.37.0
haproxy:2.6.14-alpine
redis:7.0.14-alpine
------

Pods status:

# k get pod -n argocd
NAME                                                READY   STATUS             RESTARTS      AGE
argocd-application-controller-0                     1/1     Running            0             92s
argocd-applicationset-controller-56cf6c6f59-429t6   1/1     Running            0             92s
argocd-dex-server-5cb48d6f7f-xgl6k                  0/1     CrashLoopBackOff   3 (45s ago)   92s
argocd-notifications-controller-699b74864-zkfqm     1/1     Running            0             92s
argocd-redis-65c9496b5b-7m8jd                       1/1     Running            0             92s
argocd-repo-server-5d5bf47f99-ldhxm                 1/1     Running            0             92s
argocd-server-84d7bffcd9-dmkwh                      1/1     Running            0             92s

------

k describe pod:
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m25s                  default-scheduler  Successfully assigned argocd/argocd-dex-server-5cb48d6f7f-xgl6k to k8snode1h02
  Normal   Pulling    4m24s                  kubelet            Pulling image "harbor.indus.intra.monext.fr/sys/quay.io/argoproj/argocd@sha256:672920898f3e6b28f0f9ba2d3e0a1591dce9250e11a40b18046ac7c36d22128e"
  Normal   Pulled     4m24s                  kubelet            Successfully pulled image "harbor.indus.intra.monext.fr/sys/quay.io/argoproj/argocd@sha256:672920898f3e6b28f0f9ba2d3e0a1591dce9250e11a40b18046ac7c36d22128e" in 136.416791ms (210.821387ms including waiting)
  Normal   Created    4m23s                  kubelet            Created container copyutil
  Normal   Started    4m23s                  kubelet            Started container copyutil
  Normal   Pulled     4m22s                  kubelet            Successfully pulled image "harbor.indus.intra.monext.fr/sys/ghcr.io/dexidp/dex@sha256:e9e1d55ad55d8135e6fa160051ab501b22d6e5db41374273772f0235f257779a" in 101.75997ms (150.321178ms including waiting)
  Normal   Pulled     4m21s                  kubelet            Successfully pulled image "harbor.indus.intra.monext.fr/sys/ghcr.io/dexidp/dex@sha256:e9e1d55ad55d8135e6fa160051ab501b22d6e5db41374273772f0235f257779a" in 107.738826ms (107.74471ms including waiting)
  Normal   Pulled     4m6s                   kubelet            Successfully pulled image "harbor.indus.intra.monext.fr/sys/ghcr.io/dexidp/dex@sha256:e9e1d55ad55d8135e6fa160051ab501b22d6e5db41374273772f0235f257779a" in 96.003039ms (96.008861ms including waiting)
  Normal   Pulling    3m38s (x4 over 4m22s)  kubelet            Pulling image "harbor.indus.intra.monext.fr/sys/ghcr.io/dexidp/dex@sha256:e9e1d55ad55d8135e6fa160051ab501b22d6e5db41374273772f0235f257779a"
  Normal   Created    3m38s (x4 over 4m22s)  kubelet            Created container dex
  Warning  Failed     3m38s (x4 over 4m22s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/shared/argocd-dex": permission denied: unknown
  Normal   Pulled     3m38s                  kubelet            Successfully pulled image "registry.example/sys/ghcr.io/dexidp/dex@sha256:e9e1d55ad55d8135e6fa160051ab501b22d6e5db41374273772f0235f257779a" in 76.417212ms (76.425582ms including waiting)
  Warning  BackOff    3m37s (x5 over 4m20s)  kubelet            Back-off restarting failed container dex in pod argocd-dex-server-5cb48d6f7f-xgl6k_argocd(9872f57f-584a-4f4e-8db1-5962616b8fab)

kubernetes version: 1.26.9

I've tried old version of dex /argocd , still have the same issue for argocd-dex-server

Best regards
