### ISSUE TITLE
Backup state

### ISSUE THREAD

**Issue by robertrbruno** [argoproj/argo-cd#1048]
Is there currently a way to backup the state of argo-cd?  I didn't see anything in the documentation.  If not could this be added? 

Could you for now please let me know at least where the state is stored so I can start saving it off.  I found the configmap, but only see repos in it not applications, projects, etc.

**Comment by jessesuen** [comment]
@robertrbruno applications and projects are custom resources. You can save them like you can a configmap/secret. For backup purposes, you can save all secrets, configmap, applications, projects in the namespace where argo cd is running in.

**Comment by alexmt** [comment]
@jessesuen updated argocd-util . Now `argocd-util ` supports import/export and can be used for backup and restore. We need to document it next

**Comment by stgarf** [comment]
@robertrbruno The docs were just updated with [this](https://argoproj.github.io/argo-cd/operator-manual/disaster_recovery/) info on disaster recovery recently.

**Comment by alexec** [comment]
Please re-open if you have more questions.
