### ISSUE TITLE
{{branch_slug}} does not work

### ISSUE THREAD

**Issue by tomjohnburton** [argoproj/argo-cd#10502]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using the pull_request generator, I want to use the `branch_slug` template var to create a namespace. When I reference it in my application, argocd just outputs `{{branch_slug}}` as the value.

**To Reproduce**

Create an applicationset with the pull_request generator, and try to set `{{branch_slug}}` to the namespace

**Expected behavior**

ArgoCD should output the formatted branch name.

**Screenshots**
<img width="377" alt="Screenshot 2022-09-02 at 10 40 26" src="https://user-images.githubusercontent.com/39559415/188100325-62c98b93-1220-40cf-bb26-c6246d13319c.png">

**Version**

```shell
argocd: v2.1.2+7af9dfb.dirty
  BuildDate: 2021-09-02T21:28:55Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: dirty
  GoVersion: go1.17
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.4.11+3d9e9f2
```

**Logs**

```
"validation error found during application validation: ApplicationSet preview-block-explorer contains applications with duplicate name: block-explorer-{{branch_slug}}"
```

**Comment by tomjohnburton** [comment]
I see now that this was removed, any reason why? And can I do something to replicate the functionality of branch slug?

**Comment by Aym3nTN** [comment]
@tomjohnburton this feature didn't yet been release in a stable version.
You can follow these steps provided by @crenshaw-dev and `cherry-pick` these 3 commits "dd4dbe2a811586dd411a7dd8ee39f00727cd3dd6", "8a1d9fe76d15699de21a4f2203574bdf203ea3c5" and  "f209ae197520328085e6f5c0e7ca0dd689fc72e4"

https://github.com/argoproj/argo-cd/pull/9264#issuecomment-1125274276

**Comment by pyama86** [comment]
Thank you for your always great products.
Do you have any plans to resolve this issue?

**Comment by Aym3nTN** [comment]
@pyama86  Check your ArgoCD version because this has been released in ArgoCD v2.5 ([link](https://argo-cd.readthedocs.io/en/release-2.5/operator-manual/applicationset/Generators-Pull-Request/#:~:text=pull%20request%20head.-,branch_slug,-%3A%20The%20branch%20name)).

**Comment by pyama86** [comment]
thanks!

**Comment by jgwest** [comment]
Based on comments, this appears resolved.
