### ISSUE TITLE
Declarative Application - Cannot disable auto sync

### ISSUE THREAD

**Issue by egkelly** [argoproj/argo-cd#10512]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am defining our applications via yaml and upon applying the files, each application has auto sync turned on despite defining the syncPolicy as follows:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  ...
  syncPolicy:
    automated: {}
```

**To Reproduce**

Create a yaml application file with `syncPolicy.automated: {}`. Kubectl apply the file and log into ArgoCD instance. The application will have auto sync enabled.

<img width="530" alt="Screen Shot 2022-09-02 at 2 48 13 PM" src="https://user-images.githubusercontent.com/39836626/188233333-2b2d8bb5-3ecc-403a-a270-76ccb158aa5c.png">

**Expected behavior**

Auto sync is disabled. Along these lines, though this is a bug report, I think it would be a great feature to be able to define `syncPolicy = manual/automatic`

**Version**

```shell
v2.4.7+81630e6
```

**Comment by jessesuen** [comment]
This is working as intended. See: https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/#automated-sync-policy

> Alternatively, if creating the application an application manifest, specify a syncPolicy with an automated policy.

```yaml
spec:
  syncPolicy:
    automated: {}
```

The `{}` indicates it should be used (similar to `emptyDir: {}`)

**Comment by allamand** [comment]
@jessesuen but why the disable sync button in the UI don't work ? (in my case it directly reactivate the sync event if asking to disable it through the UI)

**Comment by adrian-sturm** [comment]
Similar to https://github.com/argoproj/argo-cd/issues/3895
The changes made by clicking the UI buttons seem to be immediately overridden by argos self-heal & auto-sync again so its impossible to change the configuration from there, as long as the "desired state" in your source repo still has the options enabled.
I dont know how it was intended to work, but somehow the changes made by the UI buttons must be excluded from auto-healing and snycing for this to work.
