### ISSUE TITLE
[CLI] Misleading error message with whitespace in --auth-token

### ISSUE THREAD

**Issue by andrewm-aero** [argoproj/argo-cd#10539]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

If the argument to --auth-token mistakenly contains whitespace (e.g. a newline accidentally captured when base64-encoding a secret), the following misleading error will be produced:

```
time="2022-09-06T22:19:04Z" level=fatal msg="rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR"
```

for anyone who is not well-versed in gRPC internals, this is not easy to debug.

**To Reproduce**

```bash
export TOKEN='<some valid token>
'
argocd --auth-token="${TOKEN}" --server=argocd.example.com version
```

**Expected behavior**

Validation of the allowable characters in the token, or at least an entry be added to the FAQ for this error.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.3.2+ecc2af9
  BuildDate: 2022-03-23T00:40:57Z
  GitCommit: ecc2af9dcaa12975e654cde8cbbeaffbb315f75c
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.2+ecc2af9
  BuildDate: 2022-03-23T00:40:57Z
  GitCommit: ecc2af9dcaa12975e654cde8cbbeaffbb315f75c
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

See above

**Comment by crenshaw-dev** [comment]
Reproduced it in 2.4.12:

```
$ argocd app list --auth-token='
                                                              '
FATA[0000] rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR
```

**Comment by mabhi** [comment]
@crenshaw-dev, I would like to work on this issue and analyse further. If this is still unassigned, can you assign it to me.

**Comment by cleverhu** [comment]
@mabhi Is there any progress? I checked the code and I'd like to fix it. Can the issue been assigned to me?
@crenshaw-dev

**Comment by mabhi** [comment]
Hi @cleverhu , i had completed the work, but was waiting for assignment. But now since you have raised PR. you go forward.

**Comment by jannfis** [comment]
Hey folks. We don't work with issue assignments on small things usually. You see an issue you are able to fix, you write code, you submit PR - easy as that :) Obviously, someone else could do similar in the meanwhile.

For larger things, where redundant work could actually hurt, assignment makes sense. Or, if there is a bug for a particular piece of code someone has contributed recently, it makes sense to assign the issue to them for fixing it.

@mabhi Sorry for the confusion on this one and thanks for your willingness to contribute! Please feel free to submit a PR to any open issue as you see fit - without waiting for someone to "officially" assign the issue to you. For first time contributors, or those rather new to the community, we recommend to pick up on smaller issues (or those labeled as good-first-issue) just as this one.

**Comment by mabhi** [comment]
Thank you @jannfis . This clarifies for me, would do as suggested.

**Comment by voltbit** [comment]
I managed to fall for this even with the previous fix in place. Because of the length of the token I could not tell that I had a \n in the middle of it when I put it in the rc file. The fix implemented trims the whitespace with `strings.TrimSpace` so it removes whitespace only from the start/end.

https://github.com/argoproj/argo-cd/pull/10704/files#diff-1a6043a20c977e597fbec4c3f623109a768f1b95792011a1a365ed3fed11904cR235
