### ISSUE TITLE
zsh autocompletion doesn't work

### ISSUE THREAD

**Issue by dimisjim** [argoproj/argo-cd#10534]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

zsh autocompletion doesn't work, with the instructions given in https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/commands/argocd_completion.md

**To Reproduce**

- add the output of argocd completion zsh to a file in $fpath
- try to do tab completion
- doesn't work

**Expected behavior**

for completion to work in zsh

**Version**

```shell
argocd: v2.4.11+3d9e9f2
  BuildDate: 2022-08-22T09:35:38Z
  GitCommit: 3d9e9f2f95b7801b90377ecfc4073e5f0f07205b
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
```

**Comment by dimisjim** [comment]
A workaround that worked for me was to add this line in the top of the file generated by: `argocd completion zsh`

```
compdef _argocd argocd
```

and then add in my ~/.zshrc this: (in the same style as `kubectl`'s [autocomplete instructions](https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-zsh/)) 
```
source <(cat /path/to/modified/.oh-my-zsh/completions/_argocd.zsh)
```

**Comment by jmagder** [comment]
I just ran into the same problem.  https://github.com/argoproj/argo-cd/issues/10534#issuecomment-1238538079 is right about the fix.  It looks like the generated output from `argocd completion zsh` has `#compdef _argocd argocd` as the first line.  ie:

Running `argocd completion zsh | head` returns: 

```
#compdef _argocd argocd

# zsh completion for argocd                               -*- shell-script -*-

__argocd_debug()
{
    local file="$BASH_COMP_DEBUG_FILE"
    if [[ -n ${file} ]]; then
        echo "$*" >> "${file}"
    fi
```

The source of the problem is probably that being accidentally commented out in the generating scripts.

**Comment by emanserav** [comment]
same workaround works for argo (argo-workflows)

**Comment by confiq** [comment]
yes ^ 

for argo workflow you can do this:

```
compdef _argo argo
source <(argo completion zsh)
```

in `~/.zshrc`
