### ISSUE TITLE
Proposal: Allow negative/inverse selection for label and resource selectors

### ISSUE THREAD

**Issue by jgn-epp** [argoproj/argo-cd#10548]
# Summary
When using the `argocd app wait` and `argo app sync` commands, it is possible to use the `-l / --selector` parameter filter based on labels and their values. It is also possible to use the `--resource` filter to only target certain types of resources. Unfortunately it is (as far as I can tell) not possible to do negative/inverse selection on these - for example so that you could filter out resources with a certain label or of a certain type.

# Motivation
As part of our deployment pipeline, we have a step where we use `argocd app wait <appname> --health --sync`, but the process sometimes gets stuck because of objects in the deployment that continually mark their health as `Progressing` and are not always necessary to wait for. I would like to be able to easily filter these objects out of the `argocd app wait` call, but as only positive selection is possible, I would have to either:
- Tag everything that I want to wait for and use the `-l` parameter to select those resources. I would like to avoid this since that means adding a label to every single resource besides that particular one that I am trying to avoid.
- Use the `--resource` parameter for every possible resource that is NOT the type of resource that I want to filter out. I would like to avoid this since that means I would have to include every type of resource in use now and it would need to be updated if custom resources are introduced to make sure they are included.

# Proposal
I would like the `-l / --selector` to allow negative/inverse selection, example:
- `argocd app wait <appname> -l label_example!=hello`

Additionally/alternatively it would also be nice if the `--resource` parameter allowed some kind of negative/inverse selection, example:
- `argocd app wait <appname> --resource :!ResourceToFilterOut:`

**Comment by crenshaw-dev** [comment]
Looks like kubectl supports this. It would be nice to have feature-parity with kubectl. https://stackoverflow.com/a/58936877/684776

**Comment by maheshbaliga** [comment]
Hi @crenshaw-dev. I would like to attempt this one. Could you please assign this to me?

**Comment by maheshbaliga** [comment]
Hi @crenshaw-dev, can you please review PR #10729 and let me know if any changes are required.

**Comment by maheshbaliga** [comment]
Hi @crenshaw-dev. Are we looking at implementing the --resource filtering as well? If yes, which wildcard characters should be supported apart from `!` negation?

Currently, looks like the resources are selected only if it matches all the criteria - Group, Kind & Name (Namespace, if specified). Filtering based on `apps:Deployment:guestbook-ui` works, but `:Deployment:` or `:Deployment:guestbook-ui` doesn't. Should a blank value be supported in Kind & Name as well?

**Comment by maheshbaliga** [comment]
Hi @crenshaw-dev. Since `--resource` can be specified repeatedly, they currently act as OR conditions. The resource has to satisfy one of the filters. 

Is the same behaviour expected with the inclusion of `!` too? If yes, `argocd app wait guestbook --resource '!*:Deployment:*' --resource '!*:Service:*'`, will wait for both Deployment & Service. Is this behaviour OK?

**Comment by crenshaw-dev** [comment]
That seems like the most intuitive behavior to me.  :-)

**Comment by maheshbaliga** [comment]
Hi. I've almost completed `--resource` part of this issue, will submit a PR very soon.
