### ISSUE TITLE
bump of kustomize version from 4.4.1 to 4.5.X

### ISSUE THREAD

**Issue by vhsantos** [argoproj/argo-cd#10540]
# Summary

kustomize version should be upgrade to 4.5.X on argo-cd

# Motivation

Actually, argo-cd 2.4.11 is using kustomize version 4.4.1 (last on this branch).
Which contain some bugs, like [this 4406](https://github.com/kubernetes-sigs/kustomize/pull/4406) preventing argo-cd to work correctly when an image contain the NAME:TAG:SHA, example:
```
registry.k8s.io/ingress-nginx/controller:v1.3.0@sha256:d1707ca76d3b044ab8a28277a2466a02100ee9f58a86af1535a3edf9323ea1b5
```

# Proposal

We should upgrade it to version 4.5.X to fix it.

**Comment by crenshaw-dev** [comment]
Let's track this discussion in https://github.com/argoproj/argo-cd/issues/10533
