### ISSUE TITLE
[UI] Rework application view

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1055]
The current v0.11.X application view has usability issues and is not suitable for viewing more than a dozen or so applications. This issue is to rework this view so that usability can scale despite number of apps.

1. [x] Replace card view with a traditional table view. This is more space efficient and can present the most information in small amount of space. Bonus points to have customizable columns.

1. [x] Pagination

1. [x] Yelp-like filter sidepane which would provide filters by:
* project (this is already available)
* cluster
* git repository
* namespace
* application sync & health status
* application name pattern match (useful for those using naming conventions and want to filter by something like  `*-prod-*` or `*-us-east-*`)

1. [x] Based on the current selected filters, a top level summary displaying statistics on:
* total applications
* number of applications healthy
* number of applications synced
* pie charts for both of the above

**Comment by alexmojo** [comment]
I totally agree with tables but it should be used with pagination. We have about 50 applications in few projects, and it's not easy to navigate right now even with filters - because they reseting after every action

**Comment by jessesuen** [comment]
> it's not easy to navigate right now even with filters - because they reseting after every action

The issue about filter reset is a bug which we are aware of and will get fixed. Pagination would be ideal, but more difficult to implement since it requires backend changes. I think if converting to a table view with usable/persistent filters, that would be a good start.

**Comment by alexmt** [comment]
Applications list view redesign is completed. The labels requirement had been moved into https://github.com/argoproj/argo-cd/issues/1099 since it requires more thinking
