### ISSUE TITLE
In Application Details, link the `path` field directly to the path in the repo

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#10568]
# Summary

The bottom field should be a link.

![Screenshot of Argo CD Application Details page. The bottom field is `path`, and the value is just text. It is not a link.](https://user-images.githubusercontent.com/350466/189553163-c465cf1f-d693-45b5-8d00-b36157dd17d8.png)

# Motivation

It would be nice to be able to navigate directly to the directory containing the resources which are to be deployed by the app.

# Proposal

For GitHub the path should be predictable. I'm not sure about other providers.

**Comment by crenshaw-dev** [comment]
@surbhiahuja probably [this file](https://github.com/argoproj/argo-cd/blob/e53ab49cb5f5647973b32fa956170f8db7111340/ui/src/app/applications/components/application-summary/application-summary.tsx#L142).

**Comment by RutviShukla** [comment]
@crenshaw-dev , If this issue isn't already solved, can I also work on this?

**Comment by celanthe** [comment]
@RutviShukla -- Yes, you can absolutely work on this as well! :) If you need any assistance, please feel free to send a message in the #argo-proj Open Source Day Slack channel.

**Comment by nirsht** [comment]
Hey I made PR that support this request https://github.com/argoproj/argo-cd/pull/10860. How can take a look ?
