### ISSUE TITLE
[UI] color indication for pending, unhealthy, unready pods

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1056]
Users seem to not understand when their pod is pending due to scheduling issues, failing health checks, crashlooping, etc... despite the fact that we have added informational labels such as `0/1`, `pending`, `crashloopbackoff`. Perhaps if we had some type of color indications for pods, we would avoid a lot of questions and confusion.

**Comment by alexec** [comment]
I think we can make the state of resources much clearer. E.g. highlighting in red failing pods. Highlighting in orange out-of-sync resources. Making icon bigger and clearer.

**Comment by alexec** [comment]
Specifically pod health.

**Comment by alexec** [comment]
We've implemented a number of improvements and `crashloopbackoff` will be red.
