### ISSUE TITLE
helm ComparisonError

### ISSUE THREAD

**Issue by sercanacar** [argoproj/argo-cd#1057]
Hi,
While creating an application with helm, I'm getting:

``` rpc error: code = Unknown desc = Error: render error in "helloworld/templates/deployment.yaml": template: helloworld/templates/deployment.yaml:24:27: executing "helloworld/templates/deployment.yaml" at <.Values.image.reposi...>: can't evaluate field repository in type interface {}```

`          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"`

What have I missed?

Regards

**Comment by PaulVanStaden** [comment]
Hey @sercanacar 

Can you perhaps create a bigger example of your error and upload to https://gist.github.com/. Helm render issues often occur within a specific context. 

If everything looks file, ensure that you are using spaces and not tabs. Helm don't do tabs.
When you run `helm lint <chartname>` it will ensure that your chart is successfully rendered.

**Comment by jessesuen** [comment]
Yes I strongly suspect this is a problem with your helm chart. If you run `helm template .` in your chart directory, you will likely get the same error.

**Comment by c4m4** [comment]
I have the same issue with argocd 1.7 and if I execute helm template . and helm lint . in my chart root directory, I don't have any errors :(
