### ISSUE TITLE
UI Logs - 'previous logs' button and 'download' will download current logs instead of previous logs

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-cd#10570]
viewing 'previous' pod logs works but 'download' button always downloads the current logs instead of the previous logs

version 2.4.11

**Comment by keithchong** [comment]
I can reproduce this.  Cursory glance at this shows that possibly, issue is that the `getDownloadLogsURL` API doesn't allow for `showPreviousLogs`, unlike the `getContainerLogs` API.
