### ISSUE TITLE
[UI] Enhance app creation page with auto-sync and auto-prune options

### ISSUE THREAD

**Issue by zcahana** [argoproj/argo-cd#1058]
It would be useful to be able to enable auto-sync and auto-prune right from the app creation page in the UI, in a similar manner to `argocd app create --sync-policy automated --auto-prune`. 

This provides two benefits:
- Make it explicit and visible whether an application is created with these attributes on or off. Today, it's easy to overlook the fact that an application has been created with auto-sync off, only to later discover it when it's out-of-sync.
- Make it quicker and easier to create an application with these attributes turned on, which at least for me, is the common case.

**Comment by alexec** [comment]
Implemented.
