### ISSUE TITLE
[UI] Enhance app creation page with Helm parameters overrides

### ISSUE THREAD

**Issue by zcahana** [argoproj/argo-cd#1059]
It would be useful to be able to override individual parameters (in contrast to complete "values" files) for a Helm-based application, right from the app creation page in the UI, in a similar manner to `argocd app create --parameter key=value`.

**Comment by alexmt** [comment]
@zcahana this is already supported. Helm value can be specified the same way as ksonnet , except you would have to use empty string as component name:

```
app create --parameter =key=value
```

**Comment by zcahana** [comment]
@alexmt this issue is about supporting this option in the GUI.

By the way, I've successfully used the CLI to set a Helm parameter, without specifying the leading `=`:
```
argocd app create --parameter key=value
```

**Comment by alexmt** [comment]
Sorry, I did not read description carefully.  You are right about CLI, we have special handling of `parameter` flag in CLI for helm. 

UI should support changing values as long as value if specified in `values.yaml` file. Argo CD uses `helm inspect values` to get list of available values

https://github.com/argoproj/argo-cd/blob/ccbf80312ede25a1b4661868c7b4b3520b21d250/util/helm/helm.go#L150-L152

Probably your helm chart don't have default value in `values.yaml` or it a bug. Either way I think UI should match CLI behavir and allow user specifying parameter with any name (e.g. we need new override button). 

Can you please check if `helm inspect values` returns values of your chart?

**Comment by zcahana** [comment]
> Can you please check if `helm inspect values` returns values of your chart?

Yes, `helm inspect values` returns the chart values.

Nonetheless, I can't find any place in the UI to provide individual parameters - only values files.
Attaching a screenshot from the app creation page (`v0.11.1`).

![image](https://user-images.githubusercontent.com/17428696/51799192-477db380-2227-11e9-95e4-a76f034b2d71.png)

**Comment by alexmt** [comment]
Ah, you are right. Creation page doesn't have parameters section at all. Only Application details page has it. I agree this would be useful to support parameters during app creation.

**Comment by alexec** [comment]
Workaround exists. User demand.

**Comment by alexec** [comment]
Can we close this?

**Comment by alexmt** [comment]
Please keep it open. I hope to work on app creation panel enhancement next release.

**Comment by alexec** [comment]
See #1930

**Comment by alexec** [comment]
Is this needed due to #1930?

**Comment by zcahana** [comment]
I think this is somewhat different than #1930 as this one is about the ability to override helm chart value via the UI, whereas #1930 adds the ability to override via the Application object.

With that being said, if there's no real demand for it, it can probably be closed for now.
