### ISSUE TITLE
Upgrade dex to v2.34.0, for adding ppc64le support

### ISSUE THREAD

**Issue by mayurwaghmode** [argoproj/argo-cd#10615]
# Summary

A recent Dex release([v2.34.0](ghcr.io/dexidp/dex:v2.34.0)) has added ppc64le support. With this ArgoCD can also be fully functional on ppc64le architecture, as already it supports the rest of the images(argocd:v2.4.6, redis:7.0.0-alpine).

# Motivation

PPC64Le users can use Argo CD for their use case

# Proposal

Replace the existing dex image tag with the latest [v2.34.0](ghcr.io/dexidp/dex:v2.34.0).

**Comment by crenshaw-dev** [comment]
@mayurwaghmode are you willing to put up a PR? Would love to get this into 2.5.

**Comment by mayurwaghmode** [comment]
@crenshaw-dev yes, I am going to create it :)

**Comment by mayurwaghmode** [comment]
@crenshaw-dev I have opened a PR for the same - https://github.com/argoproj/argo-cd/pull/10617 :)
