### ISSUE TITLE
All logs icons are unclear

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#10624]
# Summary

I have to hover over each of these icons to understand what they do:

![image](https://user-images.githubusercontent.com/1142830/190707371-3055dccd-e5c3-43b7-8a5c-6236a640ba85.png)

As a result, I missed the fact that there is a "containers" icon and I need to use to find the right container. I wasted an hour thinking that it was a bug and using `kubectl logs` intead with all the attendant cost.

The current icons don't mean anything to me as they're not commonly used.

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

* Please add text to these buttons.
* Please make it clear which containing the logs are from. Maybe like workflows does it :)

![image](https://user-images.githubusercontent.com/1142830/190707660-5c8b1420-e869-40b4-9e4a-a65bbcfd8156.png)

**Comment by shogohida** [comment]
@alexec 
Hi, Alex. Can I work on this? This issue has good first issue label and I thought I could contribute to Argo CD for the first time.

**Comment by alexec** [comment]
fixed
