### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'kind')

### ISSUE THREAD

**Issue by simtuitive-jay** [argoproj/argo-cd#10647]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by keithchong** [comment]
Hi @simtuitive-jay , this sounds like a UI issue. Could you please provide more information.

**Comment by alexmt** [comment]
Based on error message this is duplicated of https://github.com/argoproj/argo-cd/issues/10647 . Closing since 10647 has more details
