### ISSUE TITLE
JumpCloud SSO Support

### ISSUE THREAD

**Issue by hakobmkoyan772** [argoproj/argo-cd#10659]
### Discussed in https://github.com/argoproj/argo-cd/discussions/10658

<div type='discussions-op-text'>

<sup>Originally posted by **hakobmkoyan772** September 21, 2022</sup>
Hi.
Does your application support Single Sign On for JumpCloud Custom SAML app, if you answer is yes, below will be my info about my mess in that with all configurations that I have, can you help me with that mess?
**So here is the thing, I created custom SAML app in JumpCloud, provided configurations in argocd chart's values.yaml file undex dex.config like this one below:**

_url: "https://localhost:8080"
  dex.config: |
      connectors:
        - type: saml
          id: jumpcloud
          name: JumpCloud
          config:
            ssoURL: https://sso.jumpcloud.com/saml2/saml2
            caData: | <certificate provided from jumpcloud custom saml app>
            usernameAttr: username
            emailAttr: email
            groupsAttr: group_

**And here is the configuration of JumpCloud custom SAML app :**
_IdP Entity ID: jumpcloud
SP Entity ID: https://localhost:8080/api/dex
ACS URL: https://localhost:8080
SAMLSubject NameID: email
SAMLSubject NameID Format: urn:oasis:names:tc:SAML:1.0:nameid-format:unspecified
Signature Algorithm: RSA-SHA256
Login URL: https://localhost:8080
IDP URL: https://sso.jumpcloud.com/saml2/saml2
User Attributes: 
  usernameAttr: username
  emailAttr: email_

So, after these all, I installed argocd chart with custom values.yaml file, it ran perfectly, **BUT**, when I clicked **Login via JUMPCLOUD**, At first it asked me my jumpcloud username-password, I entered, after that it again redirected me to login page.
The same thing happens when I call command from CLI _argocd login localhost:8080 --sso --insecure_.

I want to understand, does this all mess happens because ArgoCD doesn't support JumpCloud or it is my fault?</div>

**Comment by hakobmkoyan772** [comment]
HELP!

**Comment by jessesuen** [comment]
Answered in https://github.com/argoproj/argo-cd/discussions/10658
