### ISSUE TITLE
Consider using swagger client in Argo CD cli

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1065]
Argo CD CLI uses GRPC to access API server. This requires additional configuration in case if API server is exposed via load balancer. To simplify configuration we should consider using generated swagger client to enable connection through plain HTTP/HTTPS

**Comment by BoyangHuang** [comment]
It is an extremely common pattern for Kubernetes clusters to expose their ingresses via a load balancer, so this will feature would be _extremely_ useful!

In AWS, the current solution for making the Argo CD cli work is to update the load balancer type to a network load balancer, which permits HTTP\2 traffic, but also does away with SSL termination at the elb as well as breaking all health checks that communicate on HTTP1.0.

**Comment by jessesuen** [comment]
So the swagger option is pretty ugly on the client and we didn't want to go that route.

But @alexmt has come up with a different/elegant solution which will provide the client the option to use [gRPC-web](https://grpc.io/blog/grpc-web-ga) to communicate to the API server. gRPC web is basically being able to send protocol buffers over http 1.1. Which means the CLI could work through standard HTTP ingresses without HTTP2/gRPC.

Looking forward to his PR.

**Comment by alexmt** [comment]
PR is ready: https://github.com/argoproj/argo-cd/pull/1077 :)
