### ISSUE TITLE
Multi-namespace support for applicationset

### ISSUE THREAD

**Issue by TMaYaD** [argoproj/argo-cd#10655]
# Summary

Following  #9755 and #10270, it would be nice to have similar support for applicationsets as well.

# Motivation

We are currently using SCM discovery to deploy new environments for each branch. Each environment consists of multiple applications following app of apps pattern and it would be nice to setup each environment in its own namespace and project. 

# Proposal

applicationset-controller should respect the same arguments / configmap entries supported by application-controller.

**Comment by bobertrublik** [comment]
Yes please! Thanks to 2.5.0 I was finally able to place Argo Apps in their respective namespaces and only miss AppSets :)

**Comment by tossmilestone** [comment]
Hope this feature could be done in 2.6.0, it's very important if we want to support isolation of applicationset into multi-namespaces.

**Comment by crenshaw-dev** [comment]
Please take a look at this PR and see if it will solve your use cases: https://github.com/argoproj/argo-cd/pull/12378

**Comment by eightseventhreethree** [comment]
Would this PR resolve an issue where I've installed argocd in a namespace like: `argocd-foo` and I have all my configs defined in `argocd-foo` including ApplicationSets, and I get the following error when trying to have them render:
"application references project xyz which does not exist" even though it does exist in the namespace? I tried setting the configmap value, etc. Version: `v2.7.3+e7891b8.dirty`

**Comment by crenshaw-dev** [comment]
@eightseventhreethree that's super weird,  sounds like a separate bug to me.
