### ISSUE TITLE
ARGOCD- Cache error  (Unable to load data: error getting cached app state: cache: key is missing)

### ISSUE THREAD

**Issue by pawanbony** [argoproj/argo-cd#10666]
I tried to update our tst environment ArgoCD from  v2.3.0 to 2.4.0. update was successful. I was able to login and see all the applications. But when I open the application and click on a resource(pod, deployment, etc) it is giving me the following error instead of showing the details

![image](https://user-images.githubusercontent.com/74630240/191616646-cd03db10-6f78-453f-ba1f-f0763c26aa25.png)

I have rolled back the update and still the issue is same. I have tried restarting the redis deployment but of no use. I did the same in our  sandbox environment and it went smooth with no issues. Can anyone help me out here?

**Comment by pawanbony** [comment]
Can anyone help me here

**Comment by baileydoestech** [comment]
Try restarting everything BUT your redis container - failing that a few people have suggested that an empty secret may be causing the issue.

**Comment by pawanbony** [comment]
Thanks @SebastianBakala-TomTom . It worked.

**Comment by emon5122** [comment]
@SebastianBakala-TomTom I am having the same issue. Your solution has partially worked for me but [ Unable to load data: error getting cached app state: dial tcp 10.43.94.157:6379: i/o timeout ] this is what I am getting when I am trying to open details.
![image](https://user-images.githubusercontent.com/92997182/200595307-626796ed-5ad2-42e6-abab-60b02fc6f7ec.png)

**Comment by andrew-aiken** [comment]
Also running into issue with getting cached app state

```json
{
    "Version": "v2.5.1+504da42",
    "BuildDate": "2022-11-01T21:14:30Z",
    "GitCommit": "504da424c2c9bb91d7fb2ebf3ae72162e7a5a5be",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.8",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.1+g9f88ccb",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.18.0"
}
```

**Comment by psibi** [comment]
I was able to reproduce this in v2.3.3. I had to restart all the deployments/statefulsets including redis to make it work.

**Comment by vl-kp** [comment]
still same on v2.7.2+cbee7e6.dirty, all restart doesn't help

**Comment by decipher27** [comment]
Can this case be re-opened? Looks like most folks are resolving by doing a restart.. Can we come up with a permanent fix?

**Comment by decipher27** [comment]
Will making Redis HA fix this?

**Comment by Sean-McAuliffe** [comment]
having this same issue, any ideas so far? restarting does nothing

**Comment by crenshaw-dev** [comment]
`error getting cached app state: cache: key is missing` is a generic error message which may appear due to a variety of problems.

If you encounter this message, please file a new issue with the full issue template filled out (versions, logs, full error messages, reproduction steps if possible).
