### ISSUE TITLE
Azure Git Repos Fail: unexpected client error: status code: 400

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1067]
Spawned from https://github.com/argoproj/argo-cd/issues/643#issuecomment-426769582.

Azure DevOps Git Repos fail cloning with error:
```
Unable to load data: Failed to fetch git repo: unexpected client error: unexpected requesting "https://dev.azure.com/<account>/<project>/_git/<repository>/git-upload-pack" status code: 400
```

**Comment by JacobHeidelbachDFDS** [comment]
Just tried adding from CLI, and I get this error when trying the SSH-endpoint provided by Azure DevOps:

```BASH
./argocd repo add ssh://YYY@vs-ssh.visualstudio.com:v3/YYY/PROJECT/REPONAME --ssh-private-key-path /home/user/.ssh/argo_id_rsa
FATA[0000] unknown error: remote: Command git-upload-pack '/YYY/PROJECT/REPONAME' is not in expected format.
```

**Comment by jessesuen** [comment]
I pinpointed this to a bug in the go-git library. If I change the implementation from the go-git library to forking `git` to do the fetch, things will work. I will file upstream issue with go-git and move to git CLI to perform fetch for the time being.

**Comment by jessesuen** [comment]
Here is the upstream go-git issue https://github.com/src-d/go-git/issues/1058.

**Comment by jessesuen** [comment]
Re-opening due to report of fix not working properly with private git repos.

**Comment by HugoS99** [comment]
I am still having problems with this is there a fix in the upcomming future? @jessesuen

**Comment by dirien** [comment]
I just wanted to let you know, that the team aroud flux / Gitops Toolkits enalbed go2git in their Repository Spec.

Maybe it is worth a try?
