### ISSUE TITLE
ArgoCD not creating correctly defined resources

### ISSUE THREAD

**Issue by MikeK184** [argoproj/argo-cd#10671]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've pasted the output of `argocd version`.
`v2.3.6`

**Describe the bug**

I'm currently facing the issue that ArgoCD isn't creating a RoleBinding, and no errors can be found. However templating with Helm shows me the resource.
We're using the Apps of apps pattern and the root application is creating a numerous of resources such as namespaces, netpols, quotas, roles, rolebindings ect. There is an identical application deployed into two respective namespace. But one application/namespace is missing the rolebinding for one of its ServiceAccounts.
ArgoCD doesn't seem to log any errors/warnings nor does the UI show any problems. Is there a way to debug this behaviour/bug?
Here is the templated applications, the left rolebinding isn't being created, but the right one is (this is just a vscode compare...): 
![image](https://user-images.githubusercontent.com/56921065/191782539-1553e165-7745-4e7d-85f0-f08aa629f740.png)

**Comment by jgwest** [comment]
Closing as stale w/ insufficient reproductions steps.
