### ISSUE TITLE
`...repoURL and ...path either ...chart are required` message isn't grammatical

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#10684]
https://github.com/argoproj/argo-cd/blob/02bf903dd9b25c141d073bab3c7588d190145eb3/util/argo/argo.go#L308

I'm not sure what it's trying to say.

**Comment by crenshaw-dev** [comment]
It should be "spec.source.repoURL and either spec.source.path or spec.source.chart are required".

**Comment by cleverhu** [comment]
I'd like to work on this issue, please assign to me, thanks.
