### ISSUE TITLE
bug(ui): Version panel is transparent

### ISSUE THREAD

**Issue by rbreeze** [argoproj/argo-cd#10710]
<img width="427" alt="CleanShot 2022-09-22 at 17 21 23@2x" src="https://user-images.githubusercontent.com/6250584/192370949-c67e8e91-ae4a-4f2c-b2ce-471eded8bfeb.png">

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
2.5.0+675cbf4
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by keithchong** [comment]
I _think_ this might be related to the changes made to support dark mode. FYI @saumeya  (I tried the UI without the dark mode changes)

<img width="1268" alt="Screen Shot 2022-09-29 at 12 57 29 PM" src="https://user-images.githubusercontent.com/7726022/193093045-d2a92fb8-0441-41c7-ae61-b50a868a78f4.png">

**Comment by ashutosh16** [comment]
I see the CSS applied when I use a dark theme, but when I disable the theme, I don't see the default(light) . Is it the right assumption? (Sorry if question is  irrelevant, I am not an expert in UI)

`.theme-dark .sliding-panel__wrapper {
    background-color: #303237;
    color: #ffffff;
}`

Issue  [argoproj/argo-cd/issues/10733](https://github.com/argoproj/argo-cd/issues/10733) could be related to theme.

**Comment by saumeya** [comment]
Checking
