### ISSUE TITLE
Unable to sync kube-dns Service

### ISSUE THREAD

**Issue by glerchundi** [argoproj/argo-cd#1072]
First of all thanks for this awesome project specially after the big refactor you did in 0.11 milestone which has made possible the use of it in our products. All of our components where synced on the first attempt which is amazing as we thought that we would find more problems.

Except for `kube-dns` `Service`...I don't know why ArgoCD says that it cannot sync, this is the info. I currently have:
* Using ArgoCD 0.11.1
* Ksonnet for app manifests
* The app deploys to one namespace but the `kube-dns` `Service` is deploying to another (`kube-dns`) which is supported in the latest version (0.11.x). This is confirmed because we're currently deploying another component to `kube-system` when the app is pointing to another namespace.

![screenshot 2019-01-31 at 09 00 30](https://user-images.githubusercontent.com/2232214/52040205-fa575580-2536-11e9-99e8-f4f027631eee.png)

![screenshot 2019-01-31 at 09 02 11](https://user-images.githubusercontent.com/2232214/52040211-fe837300-2536-11e9-8f8e-b3fc3d06bb53.png)

Could you shed some light on this? Thanks!

**Comment by glerchundi** [comment]
Hei @jessesuen thanks for your quick answer!

As you guessed Kubernetes is modifying the spec once it's deployed. It comes to my mind a use-case that could trigger the same issue: horizontal pod autoscaling which modifies the replica count once deployed. How does ArgoCD behave in these cases? Is it possible to 'ignore' those changes?

**Comment by jessesuen** [comment]
@glerchundi  - for HPA, we recommend leaving replicas unset. See: https://github.com/argoproj/argo-cd/blob/master/docs/best_practices.md#leaving-room-for-imperativeness

I will dupe this bug to https://github.com/argoproj/argo-cd/issues/1075 which is request to selectively ignore some fields in a manifest when comparing objects.

**Comment by glerchundi** [comment]
Thanks @jessesuen, will keep an eye on that issue then.
