### ISSUE TITLE
Make secrets available for notification templates

### ISSUE THREAD

**Issue by eroznik** [argoproj/argo-cd#10724]
# Summary

ArgoCD internally uses `argoproj/notifications-engine` which exposes the ability to configure which variables are available when executing notification templates. Within ArgoCD this is done [here](https://github.com/argoproj/argo-cd/blob/master/util/notification/settings/settings.go#L36) where ArgoCD sets `app` and `context`.

# Motivation

Sometimes you have to provide secrets in notification payloads, especially with web-hooks. One example for this use case is the Gitlab pipeline trigger endpoint which supports only "form" and "query parameter" token authorization([ref](https://docs.gitlab.com/ee/ci/triggers/)).

# Proposal

My suggestion would be to add `secrets` beside app/context [within this part](https://github.com/argoproj/argo-cd/blob/master/util/notification/settings/settings.go#L36) which would contain data from `secret *v1.Secret`, thus enabling users to to use secrets within templates and not just for notification service configuration.
Is this something that fits within ArgoCD? Lmk, I'll prepare a PR.

**Comment by aa-mikemonaghan** [comment]
Popping in to say we could use this as well - many 3rd-party APIs consume secrets from the body of an HTTP request, rather than canonical headers. 

Being able to use secrets within notification templates would prevent us having to inject secret values in instances where we need to interact with such an API.

**Comment by eroznik** [comment]
It's been a year, and while I do understand this is not a top priority feature, it's still somewhat of an important bit to have at least work-around in place since we're talking about sensitive values(authorization keys).

I'm thinking about writing up a small sidecar container which we could deploy alongside ArgoCD that would act as an interpreter and apply the required mutations.

Something along the lines of:
1. receive request
2. read headers
3. move auth values from headers to the desired JSON body attributes(template engine)
4. proxy the request to the target destination configured through headers

**Comment by crenshaw-dev** [comment]
I don't see any reason not to do this. We'd just have to take care not to accidentally log the secret after injecting it into the payload.
