### ISSUE TITLE
Toast error message looks strange on application details page

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#10733]
**Describe the bug**

Toast error message has red background and text is hard to read:

**To Reproduce**

* Navigate to any app details page
* Somehow trigger API error on app details page (e.g. run UI/API without repo-server)
* See error message with red background

**Expected behavior**

I think background should be just white

**Screenshots**

<img width="474" alt="image" src="https://user-images.githubusercontent.com/426437/192895290-f57ca41d-6896-4743-b918-1fb099bedc37.png">

**Version**

```shell
v2.5.0 unreleased
```

**Comment by ashutosh16** [comment]
@alexmt Argo CD UI in version 2.5 uses Toastify [ v9](https://github.com/argoproj/argo-ui/blob/master/package.json#L38), which changes the background color from red/blue to icon-based and adds icons based on the notification type. 

From the Docs - https://fkhadra.github.io/react-toastify/migration-v8
```
Let's break down what is happening in the video above. Notifications of different types (toast.info, toast.error, toast.success, toast.warning) display an icon associated with the selected type. You can also notice that the progress bar color matches the type color.
```
The new screenshot will looks like this
![Screen Shot 2022-10-03 at 2 56 09 PM](https://user-images.githubusercontent.com/11219262/193696291-2ed36074-5f53-4b88-8aff-bf87482ec5da.png)

**Comment by alexmt** [comment]
The notification on screenshot looks as expected. However the same notification on the application details page looks different: 
![image](https://user-images.githubusercontent.com/426437/193701839-19d71e7f-244e-4d16-8bf5-2106738fc49c.png)

**Comment by alexmt** [comment]
@ashutosh16 Ah, this is happening because of rollout extension - sorry for confusion. Moving ticket to the https://github.com/argoproj-labs/rollout-extension repo.
