### ISSUE TITLE
Remove Application Update API in favor of UpdateSpec

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1074]
For applications, we only need UpdateSpec and not Update. Update should not be allowed, because only the controller can update status. Similarly Sync and TerminateOperation are a separate API calls (so updating the Operation is not necessary).

**Comment by alexmt** [comment]
In case we want to let user edit application labels (https://github.com/argoproj/argo-cd/issues/1099) when we should introduce PUT `/application/<appName>/labels` api

**Comment by jessesuen** [comment]
Good point. Then instead of removing Update, we can keep it but ensure API will ignore/drop the status/operation fields.
