### ISSUE TITLE
Not able to deploy application through Argo-CD in Kubernetes cluster

### ISSUE THREAD

**Issue by Nayana-Nagaraj** [argoproj/argo-cd#10771]
### Discussed in https://github.com/argoproj/argo-cd/discussions/10768

<div type='discussions-op-text'>

<sup>Originally posted by **Nayana-Nagaraj** October  3, 2022</sup>
Hello Team,

I am trying to deploy through argocd in kubernetes cluster. But unfortunately i am getting the below error: 
rpc error: code = DeadlineExceeded desc = context deadline exceeded 

![image](https://user-images.githubusercontent.com/96725710/193581972-6bc9d7f4-9e56-45b5-9ee5-109679f3c443.png)

And also i am getting the name error when trying to connect with git repository.
![image](https://user-images.githubusercontent.com/96725710/193582174-27de0c10-d0a2-43ac-9622-e29667916b51.png)

Can you please help me to resolve this </div>

**Comment by todaywasawesome** [comment]
@Nayana-Nagaraj We're use the repo is accessible from the cluster?

**Comment by Nayana-Nagaraj** [comment]
@todaywasawesome yes its accessible.. i even tried to clone the repo in the server. I am able to do

**Comment by todaywasawesome** [comment]
@Nayana-Nagaraj likely aren't enough resources for things to run properly. Were you able to figure this out?

**Comment by blakepettersson** [comment]
Closing due to a lack of info.
