### ISSUE TITLE
Argocd Upgrade path

### ISSUE THREAD

**Issue by rajeshnair** [argoproj/argo-cd#10786]
### Discussed in https://github.com/argoproj/argo-cd/discussions/10683

<div type='discussions-op-text'>

<sup>Originally posted by **rajeshnair** September 23, 2022</sup>
We have been using an argocd deployment 2.0.5 with some 80+ applications deployed.

We now need to upgrade to latest 2.4.0 and I have been trying to find a safe upgrade path documentation but could not find it.

The [upgrading documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/overview/) simply point to how to install a specific version but does not document how would upgrading impact the existing applications. 

So here are my questions
1. What is the best way to upgrade argocd without impacting existing applications running in it?
2. Is it possible/safe/recommended to deploy newer version of argocd on a new cluster and point gitops repo to that ?
3. How can I export all applications/configurations of existing argocd deployment ?</div>

**Comment by rajeshnair** [comment]
Creating an issue as the question posted on discussions forum did not elicit any response

**Comment by crenshaw-dev** [comment]
> What is the best way to upgrade argocd without impacting existing applications running in it?

It is generally safe to move _forward_ in Argo CD versions. As you pointed out, it's important to read the [upgrading](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/overview/) documentation for all versions which you are moving through. 

It is also generally safe to skip minor versions. For example, you should be able to upgrade from 2.0.5 directly to 2.4.13 (currently the latest 2.4.x release) without trouble (aside from any issues described in the upgrade guides).

At Intuit, we have upgrade "waves". Each wave is a group of several Argo CD instances. Wave 1 represents the least-critical instances, and the importance of the instances increases with the wave number. By upgrading one wave at a time, we identify any issues early. (For example, the upgrade from 2.3 to 2.4 revealed a rare issue causing sync failures, so we paused the upgrades until we fixed the bug.) Smaller orgs might not have enough instances to justify multiple waves, but they might at least have one "test" instance besides their prod instance.

> Is it possible/safe/recommended to deploy newer version of argocd on a new cluster and point gitops repo to that ?

I would definitely _not_ point two Argo CD instances at the same resources. That could cause issues of instances "fighting" for control over the resources.

You could theoretically shut down one instance and then hand over control to another (upgraded) instance. But I think that's effectively the same as upgrading a single instance in-place. It just introduces unnecessary downtime.

> How can I export all applications/configurations of existing argocd deployment ?

The [`argocd admin export`](https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_admin_export/) command is meant to help with backups. You could also simply use `kubectl` to backup Application manifests. If your manifests are served via gitops, then the git source of truth already serves as your "backup".

**Comment by rajeshnair** [comment]
@crenshaw-dev 

Do you mean is it ok to run `kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/2.4.13/manifests/install.yaml` on an existing 2.0.5 argocd with 80+ apps running on it?
Would that recreate the apps ?
If so, do we have to prepare for PVC recreation which can cause data loss ?
These are the things which are not clear for an argocd upgrade path

**Comment by crenshaw-dev** [comment]
> Do you mean is it ok to run kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/2.4.13/manifests/install.yaml on an existing 2.0.5 argocd with 80+ apps running on it?
Would that recreate the apps ?

So, the apps aren't going to go anywhere, unless you explicitly delete them.

If you're managing the Argo CD manifests manually (rather than via GitOps), it's important to consider whether you've made any manual changes to Argo CD resources which might be erased by a new `kubectl apply`. For example, if you've changed an env var value on the controller StatefulSet, that could be wiped out by a `kubectl apply`.

If you're at all concerned that there may be changes in the live resources, I'd recommend pulling down the manifests and comparing them to the manifests to be installed.

Probably the easiest way to do this is to create a new Application to manage Argo CD's resources. Point this new Application at the 2.4.13 manifests (_without_ turning on auto-sync!) and use Argo CD's diff interface to analyze what changes would be applied by a sync.

**Comment by rajeshnair** [comment]
I think now it makes more sense
`kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/2.4.13/manifests/install.yaml` would simply install the argoCD CRD. This I presume would trigger the redeployment of ArgoCD deployment/services/pods to the updated version.

BTW we use app-of-apps pattern , where all 83 apps are child of 1 single app. Hence it would be simple to turn off/on sync at the app-of-apps level.

One of the reason we are looking at upgraded version is to move away from app-of-apps to ApplicationSet.

**Comment by crenshaw-dev** [comment]
> kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/2.4.13/manifests/install.yaml would simply install the argoCD CRD. This I presume would trigger the redeployment of ArgoCD deployment/services/pods to the updated version.

That command will apply more than the Argo CD CRDs (I believe there are three of them - `Application`, `AppProject`, and `ApplicationSet`). It will apply everything in install.yaml (which you can download to inspect).

> One of the reason we are looking at upgraded version is to move away from app-of-apps to ApplicationSet.

2.0.x is also un-maintained, and there are quite a few security fixes in the newer versions!  :-)
