### ISSUE TITLE
OIDC login failed: invalid_client 

### ISSUE THREAD

**Issue by CharlieR-o-o-t** [argoproj/argo-cd#10802]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Non public oidc clients unable to login with sso, no *client_secret* provided during login session

**To Reproduce**
1) Create non public client_id at the side of OIDC 
2) Try to login to argo with command:
`argocd login <argocd_host> --sso --loglevel debug`

results in error:
`FATA[0002] oauth2: cannot fetch token: 401 Unauthorized
Response: {"error": "invalid_client"}`

**Expected behavior**
login successful 

**Version**

```shell
argocd-server: v2.4.8+844f79e
BY1-AL-356:argo-cd raskin$ argocd  version
argocd: v2.2.2+03b17e0.dirty
  BuildDate: 2022-01-01T16:53:02Z
  GitCommit: 03b17e0233e64787ffb5fcf65c740cc2a20822ba
  GitTreeState: dirty
  GoVersion: go1.17.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.4.8+844f79e
```

**Comment by crenshaw-dev** [comment]
@CharlieR-o-o-t if I understand correctly, the fix would require allowing the `argocd login` command to accept and then send a `client_secret` to the OIDC provider. I'm not sure how that's generally done... config file, param, env var?

**Comment by CharlieR-o-o-t** [comment]
@crenshaw-dev , there is already method to gather oidc configuration from argocd, but for some reason clientSecret missing. 
`https://github.com/argoproj/argo-cd/blob/master/pkg/apiclient/settings/settings.pb.go#L574`

so during "argo login" all necessary parameters forwarded to OIDC server, but no clientSecret.

**Comment by crenshaw-dev** [comment]
@CharlieR-o-o-t I'm not sure the client secret _should_ be sent to the CLI from the API server. It seems to me that, if you want to log in to your OIDC provider as a confidential client, then you should hold that secret locally, where the CLI is installed.

**Comment by zachaller** [comment]
Yea I don't like sending the secret to the client there are protections in place with public clients like only allowing redirects to localhost etc that make it somewhat more acceptable to need to send the client secret during the auth flow. Sending the secret for confidential clients allows it to be easily misconfigured as well as leaves a window of time for the secret to be compromised either via mitm https or software running on the client machine looking for the secret while in transit or in ram.

**Comment by CharlieR-o-o-t** [comment]
@zachaller , now I got the point. There is no sense to add clientSecret to API server output since it's public endpoint, and it'll be the equivalent of public oidc client.
