### ISSUE TITLE
Add copy button to user interface

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#10803]
# Summary

In workflows, we added copy button to many places to make it easier to go to the CLI and do stuff:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/1142830/194109751-5ae2ab7d-79b0-4c6e-a8ec-c61a5ff0748f.png">

I'd love to see this is Argo CD:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/1142830/194109985-d34097ca-b919-4517-8412-a37e5e926c49.png">

This is especially useful with long text.

**Comment by thirunavukkarasu95** [comment]
I am interested in this, can i try this ?

**Comment by crenshaw-dev** [comment]
@thirunavukkarasu95 let me know if you need any help!

**Comment by bharatveeryadav** [comment]
this issue is still open

**Comment by thirunavukkarasu95** [comment]
@bharatveeryadav Hi, I am a beginner to OS, still working on this issue.

**Comment by akhilchoudhary2k** [comment]
!assign

**Comment by bharatveeryadav** [comment]
@akhilchoudhary2k  yes I Like to work on

**Comment by crenshaw-dev** [comment]
Reopening since, as implemented, this applies only to resources within applications. It would be nice to have the same feature in the Application Details page as well. 

Still a valid hacktoberfest task!  :-)

**Comment by crenshaw-dev** [comment]
Looking at it again, I think it's fine to not have this on the Application Details page.
