### ISSUE TITLE
Log viewer does not respect `kubectl.kubernetes.io/default-container` or `kubectl.kubernetes.io/default-logs-container`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#10805]
When either of these are specified, that should be the container default for logs.

#10624

**Comment by crenshaw-dev** [comment]
This was supposed to have been done in https://github.com/argoproj/argo-cd/issues/8015. There might be a regression.

**Comment by crenshaw-dev** [comment]
Oh I guess I should have asked which version you saw this in. If 2.5, there's a regression. If earlier, this will be partially fixed in 2.5.0-rc1.

I don't think support has yet been added for `kubectl.kubernetes.io/default-logs-container`.

**Comment by alexec** [comment]
I don't care much about `kubectl.kubernetes.io/default-logs-container`.

**Comment by alexec** [comment]
I'm running v2.4.
