### ISSUE TITLE
Customize argocd cli using ARGOCD_OPTS env variable

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1081]
ARGOCD_OPTS env variable should allow user to override argocd cli global flags (such as `--server`, `--plaintext`, `--insecure`  etc ). Env variable usage example:

```
export ARGOCD_OPTS="--grpc-web --insecure"
argocd app sync guest-book
```

**Comment by alexec** [comment]
https://github.com/spf13/cobra/issues/825

**Comment by alexec** [comment]
@jessesuen @sctsang has requested that the token should be in a single envvar (e.g. `ARGOCD_AUTH_TOKEN` because this can be set as a Jenkins pipeline credential. He also needs support for `--insecure` by envvar.

**Comment by jessesuen** [comment]
Right, we already have ARGOCD_AUTH_TOKEN. The goal is that we have the following envs for the client:

- ARGOCD_SERVER - server address of argo cd
- ARGOCD_AUTH_TOKEN - JWT auth token for requests
- ARGOCD_OPTS - all other options: `--grpc-web --insecure --plaintext`

What we should avoid is having an environment variable for every option:
ARGOCD_GRPC_WEB=true
ARGOCD_INSECURE=true
ARGOCD_PLAINTEXT=true
