### ISSUE TITLE
Admins should have full `applicationsets` permissions by default

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#10810]
**Describe the bug**

Admin should have full permissions for `applicationsets` by default. But they do not.

**To Reproduce**

Logged in as admin

```
$ kubectl apply -n argocd -f applicationset/examples/list-generator/list-example.yaml
$ argocd appset get guestbook
FATA[0000] rpc error: code = PermissionDenied desc = permission denied: applicationsets, get, default/guestbook, sub: admin, iat: 2022-10-05T19:27:42Z 
```

**Expected behavior**

The admin user should be able to get the applicationset.

**Version**

```
argocd: v2.5.0+f7b0879
...
argocd-server: v2.5.0-rc1+2bf51f4
...
```

**Proposed fix**

Update the [builtin RBAC policy](https://github.com/argoproj/argo-cd/blob/master/assets/builtin-policy.csv) to give admin `get`, `create`, `update`, and `delete` on the `applicationsets` resource.

Thanks to Raymond Wong for pointing out the problem!

**Comment by karengineering** [comment]
I would like to work on this issue.
