### ISSUE TITLE
Document the "application info" feature

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#10814]
# Summary

There's an [undocumented field](https://github.com/argoproj/argo-cd/issues/4281#issuecomment-689133740) in the Application spec which allows folks to add additional info to an Application details page.

# Proposal

We could probably have a new page like the [one for external links](https://argo-cd.readthedocs.io/en/stable/user-guide/external-url/).

We should also document the field in the [example application spec](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml).

**Comment by 26tanishabanik** [comment]
@crenshaw-dev , I would like to work on this issue

**Comment by crenshaw-dev** [comment]
@26tanishabanik check out the two links at the bottom of the issue. The first one shows a page that can be used as an example to create a new page in `docs`. After adding the page in the docs directory, you can test the docs with `make serve-docs`. The second link shows a file where examples of the feature can be added (that file is meant to document every possible field in the Application spec).

**Comment by Abhishek-569** [comment]
Hey @crenshaw-dev can I work on this issue since there is no update for last 4 months?
