### ISSUE TITLE
argocd-application-controller deletes server.secretkey

### ISSUE THREAD

**Issue by jvoeller** [argoproj/argo-cd#10831]
**Describe the bug**

When Argocd manages itself and detects a drift the argocd-application-controller will sometimes replace the existing argocd-secret with an empty one. But it will not restart the argocd-server. This will immediately result in argocd no longer working due to a missing server.secretkey, which will only be generated at boot time.

**To Reproduce**

Set up argocd to manage itself. 
Change something in the argocd config (but not touching the argocd-server config).

**Expected behavior**

The argocd-application-controller should either generate a new argocd-secret, or in cases in which it is needed also restart the argocd-server to fill the new secret.

**Version**

v2.4.0

**Logs**

argocd-application-controller:

`time="2022-10-04T14:22:03Z" level=info msg="Replacing resource Secret/argocd-secret in cluster: [https://10.0.0.1:443](https://10.0.0.1/), namespace: argocd"`

argocd-server:

`time="2022-10-04T14:22:04Z" level=warning msg="Unable to parse updated settings: server.secretkey is missing"`

**Comment by jgwest** [comment]
@jvoeller do you have an example of how you are deploying Argo CD with Argo CD?

**Comment by jvoeller** [comment]
> @jvoeller do you have an example of how you are deploying Argo CD with Argo CD? I don't fully understand why Argo CD would be replacing a secret that isn't defined in the source manifests.

Okay, I found the issues. Argo CD was detecting a change in the cluster and deployed itself again. Our Argo CD Helm Chart however had a argocd-secret  which was empty. It then replaced the current argocd-secret. To fix this issue I disabled the `create-secret` flag in the helm chart and manually created the secret.
