### ISSUE TITLE
Automatically update the `stable` tag after a release

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#10848]
**Describe the bug**

After a release on the current stable branch, we currently have to manually bump the tag. This results in folks not getting the latest manifests: https://github.com/argoproj/argo-cd/pull/10775#issuecomment-1271625320

**To Reproduce**

Do a release on the current stable minor release series and then note that the `stable` tag target does not change.

**Expected behavior**

The GitHub release action should be modified to bump the stable tag on a stable release.

That'll probably involve scripting that
1) checks what minor version `stable` currently points to
2) if the release is for the same minor version, update and push the tag at the end of the release

**Comment by alubbock** [comment]
The `stable` tag is currently at v2.6.0 - any chance of an update to get the latest patches, please?

Also, this issue seems identical to #11057 (unless there's a reason you're tracking this separately as a bug and an enhancement?)

**Comment by crenshaw-dev** [comment]
Updated! The other issue is a result of my poor memory, thanks for catching it. :-)
