### ISSUE TITLE
Github Login broken after upgrade to 2.5.0-rc1

### ISSUE THREAD

**Issue by tback** [argoproj/argo-cd#10841]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [] I've pasted the output of `argocd version`.

**Describe the bug**
I have an argocd installation (v2.4.14) installed via helm (v5.5.9). I am using the nginx ingress controller. I tried upgrading to v2.5.0-rc1 by setting `global.image.tag: v2.5.0-rc1`.
Now github login is broken and I get an error in the browser: Failed to query provider "https://<argocd_url>/api/dex": 400 Bad Request: Client sent an HTTP request to an HTTPS server.

**To Reproduce**
Install latest version of argocd via helm. Configure nginx as ingress controller. Configure github login. Try logging in via github.

**Expected behavior**
I expect the login to succeed and to be redirected to the applications overview.

** Actual behavior **
Bad request on dex.

I'm not writing this to complain, I'm writing this so you get early feedback during the rc phase.

**Comment by tback** [comment]
Probably related to #9424 / #9883

**Comment by tback** [comment]
Found the fix: Add 
```
configs:
  params:
    dexserver.disable.tls: true
```

I leaving this issue open, so someone can decide if this should be mentioned in the upgrade documentation / general documentation somewhere.

**Comment by crenshaw-dev** [comment]
I'm not sure how this is happening. The API server bases its http client config on the configured Dex URL. 

The Dex URL is determined by two environment variables.

If `ARGOCD_SERVER_DEX_SERVER` is set, and the value contains `://`, then the schema in that string is used. If `ARGOCD_SERVER_DEX_SERVER` is not set, or it does not contain `://`, then a schema is prepended depending on the value of `ARGOCD_SERVER_DEX_SERVER_PLAINTEXT`. If that env var is set to `true`, it uses `http`. If that env var is unset or is set to `false`, it uses `https`. The default value is `false`.

So I'm not sure how we're getting the behavior you encountered. If you did not set `server.dex.server` or `server.dex.server.plaintext` under `config.params`, then the defaults should cause the API server to construct an `https` URL for Dex and then use an HTTPS client.

**Comment by psimms-r7** [comment]
Seeing this too on an upgrade from 2.4.14 using the helm chart and not touching server.dex.server
Manual fix amending the argocd-cmd-params-cm configmap

**Comment by tback** [comment]
thank you @crenshaw-dev, that works for me

**Comment by crenshaw-dev** [comment]
@psimms-r7 can you elaborate? HTTPS communication with Dex is only available in 2.5. 2.4.x should be unaffected.
