### ISSUE TITLE
Bring CLOMonitor score to 100%

### ISSUE THREAD

**Issue by eddie-knight** [argoproj/argo-cd#10852]
Per discussion in slack, this issue is to track the efforts necessary to bring argo-cd [CLOMonitor](https://clomonitor.io/projects/cncf/argo) score to 100%

Updating to use the new auto-generated CLOMonitor checklist:

### Summary

**Repository**: argo-cd
**URL**: https://github.com/argoproj/argo-cd
**Checks sets**:  `CODE`
**Score**: 88

### Checks passed per category

| Category  |  Score  |
| :----------------- | --------: |
|  Documentation  |  100%  |
|  License  |  75%  |
|  Best Practices  |  100%  |
|  Security  |  80%  |
|  Legal  |  n/a  |

### Documentation [100%]

  - [x] [Changelog](https://github.com/argoproj/argo-cd/blob/master/CHANGELOG.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [x] [Contributing](https://github.com/argoproj/argo-cd/blob/master/docs/CONTRIBUTING.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [x] [Maintainers](https://github.com/argoproj/argo-cd/blob/master/OWNERS) ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/argoproj/argo-cd/blob/master/README.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  
### License [75%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#license_spdx_id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#license_approved))
  - [ ] License scanning ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))
  
### Best Practices [100%]

  - [x] [Artifact Hub badge](https://artifacthub.io/packages/helm/argo/argo-cd) ([_docs_](https://clomonitor.io/docs/topics/checks/#artifacthub_badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#cla)) `EXEMPT`
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#dco))
  - [x] [OpenSSF badge](https://bestpractices.coreinfrastructure.org/projects/4486) ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf_badge))
  - [x] [Recent release](https://github.com/argoproj/argo-cd/releases/tag/v2.5.0-rc2) ([_docs_](https://clomonitor.io/docs/topics/checks/#recent_release))
  
### Security [80%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary_artifacts))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code_review))
  - [x] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous_workflow))
  - [x] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency_update_tool))
  - [x] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained))
  - [x] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#sbom))
  - [x] [Security policy](https://github.com/argoproj/argo-cd/blob/master/SECURITY.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#security_policy))
  - [x] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed_releases))
  - [x] Token permissions ([_docs_](https://clomonitor.io/docs/topics/checks/#token_permissions))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).

**Comment by eddie-knight** [comment]
Optional: we could add a CLOMonitor badge or report summary to the README

badge:
[![CLOMonitor](https://img.shields.io/endpoint?url=https://clomonitor.io/api/projects/cncf/argo/badge)](https://clomonitor.io/projects/cncf/argo)


report summary:
[![CLOMonitor report summary](https://clomonitor.io/api/projects/cncf/argo/report-summary?theme=light)](https://clomonitor.io/projects/cncf/argo)

**Comment by crenshaw-dev** [comment]
I've merged the token permissions PR, so hopefully that'll get marked as done soon.

We do have SBOMs, and the [CLOMonitor page](https://clomonitor.io/projects/cncf/argo#argo-cd_security) reflects that, so I think we can mark that done.

**Comment by eddie-knight** [comment]
Perfect, checked SBOM as done ✅ 

Regarding the token permissions, I think we're going to have a [headache](https://github.com/ossf/scorecard/issues/2338) with that... OpenSSF frowns heavily on using [github actions that require write permissions](https://github.com/argoproj/argo-cd/blob/master/.github/workflows/release.yaml#L274). 😓

**Comment by crenshaw-dev** [comment]
I find that really odd. I'm just trying to think of how folks are expected to automate without having GitHub actions with write permissions. Is there some better way of automating that I'm unaware of? 0_o

**Comment by eddie-knight** [comment]
AFAIK the current process is to only approve actions in the github/ library.

Discussion on the linked issue seems to be in the direction of allowing any github actions so long as the permissions are assigned on a granular basis (implying user awareness).

**Comment by crenshaw-dev** [comment]
Gotcha. Maybe there are opportunities to use the github/ library which we are currently missing.

**Comment by crenshaw-dev** [comment]
We push seven binaries and two source code archives. I wonder if all nice of those artifacts need to be signed. 0_o

I also question the utility of signing those, when the most important artifact is the container image.

**Comment by eddie-knight** [comment]
From what I can tell, its just looking for one signature per release

https://github.com/ossf/scorecard/blob/main/docs/checks.md#signed-releases

**Comment by crenshaw-dev** [comment]
Looks like flux signs a checksum file which contains checksums for all the artifacts. I like that, nice and compact. https://github.com/fluxcd/flux2/releases

**Comment by crenshaw-dev** [comment]
@34fathombelow I think that would be great!

**Comment by 34fathombelow** [comment]
> Perfect, checked SBOM as done white_check_mark
> 
> Regarding the token permissions, I think we're going to have a [headache](https://github.com/ossf/scorecard/issues/2338) with that... OpenSSF frowns heavily on using [github actions that require write permissions](https://github.com/argoproj/argo-cd/blob/master/.github/workflows/release.yaml#L274). sweat

@eddie-knight According to the [OpenSFF documentation](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) on token permissions for ```contents:write``` it states "However, points are not reduced if the job utilizes a recognized packaging action or command.  Can you clarify what a recognized package action or command is?  

We also have all top level permissions set to read-only.  I feel that we have meet all the required criteria for token permissions.

**Comment by eddie-knight** [comment]
> > Perfect, checked SBOM as done white_check_mark
> 
> > 
> 
> > Regarding the token permissions, I think we're going to have a [headache](https://github.com/ossf/scorecard/issues/2338) with that... OpenSSF frowns heavily on using [github actions that require write permissions](https://github.com/argoproj/argo-cd/blob/master/.github/workflows/release.yaml#L274). sweat
> 
> 
> 
> @eddie-knight According to the [OpenSFF documentation](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) on token permissions for ```contents:write``` it states "However, points are not reduced if the job utilizes a recognized packaging action or command.  Can you clarify what a recognized package action or command is?  
> 
> 
> 
> We also have all top level permissions set to read-only.  I feel that we have meet all the required criteria for token permissions.

The permissions check is a bit of a headache right now because there is an issue open ti fix it, but the expected behavior currently is to just use permissions:write on a job if it uses an action published by github.

The release workflow in this repo has permissions:write on a job that uses a third party action, causing the check to fail 😓

**Comment by eddie-knight** [comment]
Mentioned this on slack, but dropping it here also for reference. The [OpenSSF Scorecard issue](https://github.com/ossf/scorecard/issues/2338) is being actioned to resolve the Token-Permissions issue with limited disruption to existing workflows.

**Comment by eddie-knight** [comment]
The only thing pending on this checklist is the License Scanner. Not a security issue, but it'll be good to have regardless. FOSSA will likely be the best tool to implement for this.

**Comment by crenshaw-dev** [comment]
@eddie-knight I just requested Argoproj access from FOSSA.

**Comment by agilgur5** [comment]
> * [x]  License scanning ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))

> The only thing pending on this checklist is the License Scanner. Not a security issue, but it'll be good to have regardless. FOSSA will likely be the best tool to implement for this.

For posterity, a FOSSA badge was added in #11956

**Comment by agilgur5** [comment]
Gonna close out this issue as all the checks from last year were completed.

All non-security checks are still 100%.
But there are some [new CLOMonitor checks](https://clomonitor.io/projects/cncf/argo#argo-cd) from last month for security (re: `SECURITY-INSIGHTS.yml`).
There's also some work for some [OpenSSF checks](https://api.securityscorecards.dev/projects/github.com/argoproj/argo-cd) (new dep vulns, some dep pinning remaining, and fuzzing) that are not currently part of CLOMonitor.

I would propose improvements to those be opened in new issues for better history etc (e.g. totally new thread)
