### ISSUE TITLE
Kustomize 2.0 support

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1085]
Kustomize 2 is radically different and has many breaking changes, including to the CLI. It's very likely Argo CD will need to simultaneously support both versions for some time, and selectively choose the correct CLI based on the detected version of the kustomization.yaml.

**Comment by jessesuen** [comment]
Targeting v0.12 since Kustomize 2 is released.

**Comment by jessesuen** [comment]
2.0 differences:
* kustomization.yaml requires API version to be specified. This should be used to decide which version of kustomize to invoke.
* CLI differences with `kustomize edit set imagetag` (1.0) vs. `kustomize edit set image` (2.0). Based on kustomization.yaml, this affects how we set user defined parameters before running `kustomize build`.

Argo CD `spec.source.componentParameterOverrides` may need to use a different value for the `component` field. Currently this is `imagetag`. This may affect how our UI works.

**Comment by alexec** [comment]
https://github.com/kubernetes-sigs/kustomize/blob/master/docs/version2.0.0.md

**Comment by alexec** [comment]
> Kustomization filename

In previous versions, the canonical name of a kustomization file is kustomization.yaml. Kustomize 2.0.0 is extended to recognize more file names: kustomization.yaml, kustomization.yml and Kustomization. In a directory, only one of those filenames is allowed. If there are more than one found, Kustomize will exit with an error. Please select the best filename for your use cases.
