### ISSUE TITLE
Support migration to Google Analytics 4 (GA4) - upgrade mkdocs-material to v7.1.8+

### ISSUE THREAD

**Issue by chalin** [argoproj/argo-cd#10850]
- For the umbrella issue, see https://github.com/argoproj/argo-site/issues/102.
- As of the time of writing this, the docs are built from mkdocs-material==7.1.7 (for GA support of 7.1.7, see [here](https://github.com/squidfunk/mkdocs-material/blob/3d6cbc9d2918deb7ef7b37f7d3cbe708288c2f7a/docs/setup/setting-up-site-analytics.md)):
  https://github.com/argoproj/argo-cd/blob/90760a5088d0d1f965965b4f4d4d2d9335e337fa/docs/requirements.txt#L1-L2
  We need at least 7.1.8 (the next patch release), in order to have **support for GA4**, as [documented here](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics):
  > <img width="600" alt="image" src="https://user-images.githubusercontent.com/4140793/194634823-c8f300bf-b51c-447f-8baa-f12b1d9700de.png">

---

- [ ] Upgrade mkdocs-material to v7.1.8+
- [ ] If it turns out that GA4 doesn't support  the equivalent of UA [search-and-replace](https://support.google.com/analytics/answer/1034834) filters, then a change in path of the published doc pages for this site might be in order. I'm still investigating this. Until a solution is found, we probably shouldn't register this site's page view with the unified GA4 web site tag.

/cc @alexmt @alexec

**Comment by chalin** [comment]
SO question: [Write a search-and-replace filter in Google Analytics 4 (GA4)?](https://stackoverflow.com/questions/73991772/write-a-search-and-replace-filter-in-google-analytics-4-ga4)

**Comment by chalin** [comment]
Related:

- #11174
- #11175

**Comment by chalin** [comment]
Friendly ping @alexmt et al. Can someone update mkdocs-material to v7.1.8+? Also see the issues listed in the comment above. Thanks.

**Comment by chalin** [comment]
Btw, the Argo workflows website is built using v8.x of `mkdocs_material`: https://github.com/argoproj/argo-workflows/blob/1487bbc197a54a2e8caae4205aa98283583956f1/Makefile#L636-L637. If this repo could update to v8 as well, that would be grand, but I understand that that might be too big of a version jump.

**Comment by alexef** [comment]
@chalin see: https://github.com/argoproj/argo-cd/pull/11248 as a starting point

**Comment by chalin** [comment]
Great, thanks @alexef! I'll track that PR.
