### ISSUE TITLE
Propagation policy radio buttons/labels don't use `cursor: pointer`

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#10864]
**Describe the bug**

Hovering the propagation policy checkboxes/labels does not use the `cursor: pointer` as do other radio buttons/labels in the UI.

**To Reproduce**

1. Click the "delete" button on an Application.
2. Hover the propagation policy radio buttons/labels
3. Note that the cursor does not change to a pointer

**Expected behavior**

The cursor should change to a pointer on hover.

**Screenshots**

https://user-images.githubusercontent.com/350466/194726950-46c83fcf-d675-48a7-b753-2d8ffd5a2be4.mov

**Version**

2.5.0-rc1

**Comment by Sakshi-75** [comment]
Hi @crenshaw-dev ,
I would like to work on this. Can you assign it to me please?

**Comment by Sakshi-75** [comment]
Hi @crenshaw-dev ,
I've raised a PR for this: https://github.com/argoproj/argo-cd/pull/10867
Please review it.
