### ISSUE TITLE
[UI] Switch to text based YAML diff instead of json diff

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1086]
I think the json diff we show in the UI is not as easy to read as a simple text based diff. The issue is that the view is in JSON and most people want to see YAML. And also, the rendering of fields is inconsistent and sometimes weird:

![image](https://user-images.githubusercontent.com/12677113/52157815-016d8900-2647-11e9-9f42-e580f42ef042.png)

I propose we move off of jsondiff and just use plain text base diff of YAML.

**Comment by jessesuen** [comment]
Compared to CLI which is configured to use text-based `colordiff` of yaml:

![image](https://user-images.githubusercontent.com/12677113/52157912-f109de00-2647-11e9-979e-7fe658a03f72.png)

**Comment by jessesuen** [comment]
Another reason is we cannot easily see diffs of contents of configmaps:

![image](https://user-images.githubusercontent.com/12677113/52174368-85a73580-2747-11e9-8a2b-f8040c03cc5d.png)

vs. 

![image](https://user-images.githubusercontent.com/12677113/52174386-c0a96900-2747-11e9-8bb7-276ce3afb933.png)

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-cd-ui/commit/a1edbb5972c380ff182789e86d12c31a2fab9804
