### ISSUE TITLE
Cursor doesn't change to pointer on labels for resource names in sync panel

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#10888]
**Describe the bug**

When hovering the (clickable) label for each resource in a sync panel, the cursor does not change to a pointer.

**To Reproduce**

1. Create an app in the Argo CD UI
2. In the main Applications page, click the Sync button on the app's card
3. In the list at the bottom of the sync panel, hover the label for any resource checkbox
4. Note that the cursor doesn't change to a pointer

**Expected behavior**

I'd expect the cursor to change to a pointer, since the label is clickable.

**Screenshots**

https://user-images.githubusercontent.com/350466/194936384-22627611-b170-4dab-a5ab-9a90ffcee66c.mov

**Version**

2.5.0-rc1

**Comment by theadeyemiolayinka** [comment]
Hey @crenshaw-dev I would love to be assigned to fix this. Thanks

**Comment by crenshaw-dev** [comment]
@Kunalbhandari not yet. Feel free to open a PR!

Here's the guide to run locally: https://argo-cd.readthedocs.io/en/stable/developer-guide/running-locally/

**Comment by crenshaw-dev** [comment]
Leaving this unassigned for now. Will review any PRs.  :-)

**Comment by aimanfatima** [comment]
created a PR for this issue - https://github.com/argoproj/argo-cd/pull/10959
Please review.

**Comment by crenshaw-dev** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/10959
