### ISSUE TITLE
Prod Argo needs to be distinctive from other Argo environments

### ISSUE THREAD

**Issue by MarySmith5** [argoproj/argo-cd#10899]
Add a warning label in the PROD Argo asking that changes be approved before implemented. The Argo tool looks very similar for every environment. For this reason, it would be very easy for an engineer with multiple tabs open to inadvertently change the PROD Argo. We would like a warning banner or some eye catching feature that would warn an engineer that they are in a "dangerous" environment.

**Comment by saumeya** [comment]
Hi @MarySmith5, there is a feature to add banner message on top - https://argo-cd.readthedocs.io/en/stable/operator-manual/custom-styles/#banners that could be used to specify different environments. The styles like color could also be added to these banners using custom styles  - https://argo-cd.readthedocs.io/en/stable/operator-manual/custom-styles/#adding-styles-via-remote-url . Let me know if this works for you or if you have more suggestions.

**Comment by wanghong230** [comment]
The feature is available to leverage. Close for now.
