### ISSUE TITLE
.argoIgnore (like .gitignore)

### ISSUE THREAD

**Issue by doug62** [argoproj/argo-cd#10892]
As a user, I would like the ability to instruct Argo to ignore files within a git repo based upon a .argoIgnore file (Much like .gitignore, .dockerignore).

While this ability kinda exists in the argo crd/manifests it seems more consistent with source control/cloud patterns such as dockerignore to use a file within the repo to guid how that repo is filtered/represented.  Argo applies Kustomize files which only 'see' resources, Helm files are also declarative - seems that this declarative type feature is consistent.

How do you think this should be implemented?:
Prior art/code examples for implementing this can be found in the docker repo at:
https://github.com/docker/cli/blob/master/cli/command/image/build/dockerignore.go

Alternatively: Perhaps create a yaml file like '.argoCdOverrides.yaml' in directories and that could override behaviors...

**Comment by crenshaw-dev** [comment]
Good explanation. Maybe call it `.argocd-ignore`, since we also have a `.argocd-source.yaml` feature.

**Comment by wanghong230** [comment]
Will it make the repo less readable? With kustomization overlay including feature and Helm templating, there should be enough knobs here and there.

**Comment by crenshaw-dev** [comment]
Someone could use Helm or Kustomize to selectively include certain files. But 1) I'm not sure those support simple globs and 2) either tool is a bit heavy-weight for this use case.

But I do sympathize with the notion that providing too many ways to do something gets clunky.

**Comment by crenshaw-dev** [comment]
Actually @doug62 I think what you're trying to accomplish is already possible with [git-based parameter overrides](https://argo-cd.readthedocs.io/en/latest/user-guide/parameters/#store-overrides-in-git).

You can add argocd-source.yaml to your app's directory and add these contents:

```yaml
directory:
  include: your-pattern
  exclude: your-pattern
```

**Comment by crenshaw-dev** [comment]
Closing this because I'm pretty certain .argocd.source.yaml solves this problem.

**Comment by doug62** [comment]
Thx - where is .argocd.source.yaml  documented?

**Comment by crenshaw-dev** [comment]
@doug62 here you go: https://argo-cd.readthedocs.io/en/latest/user-guide/parameters/#store-overrides-in-git

**Comment by doug62** [comment]
Thanks, however that link only has the following type of info...
kustomize:
  images:
    - gcr.io/heptio-images/ks-guestbook-demo:0.2
