### ISSUE TITLE
cmp v2 named plugins

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-cd#10902]
cmp legacy has named plugins

cmp v2 cannot use named plugins, and has to rely on things like find commands

when cmp legacy is removed in 2.6, cmp v2 should get named plugins back

**Comment by crenshaw-dev** [comment]
Support will be added in v2.6 with this PR: https://github.com/argoproj/argo-cd/pull/11341

We plan to delay removing argocd-cm plugin support until 2.7 to give folks time to transition.
