### ISSUE TITLE
Github integration?

### ISSUE THREAD

**Issue by marcb1** [argoproj/argo-cd#1091]
Looking at the argo docs, I see github webhook integration to force sync.
Was wondering if there is any other Github integration: for example showing the diffs on PR's would be useful.
Or if you could point me to any tools, you use internally with Argo that I could set-up.

**Comment by rowleyaj** [comment]
It would be nice to see if anyone has tied this into the GitHub Deployments API as well.

**Comment by alexmt** [comment]
@marcb1 great idea about showing diffs on PR! this should be easy to implement since argocd cli already supports diffing local and actual state ( `argocd diff --local` ).

ArgoCD github bot which implements such functionality would be very useful.

**Comment by marcb1** [comment]
I'm willing to work on this in my free time. I'm a bit familiar with Go, and can put a simple Github bot together, and we can have it exec `argocd diff` correctly. Anyone willing to help with this, also any suggestions where the repo should live?

**Comment by alexmt** [comment]
I'm not ready to 100% commit to it  but will try to find time this weekend or next weekend :)  . Apparently, there is a nodejs based framework for github bots: https://github.com/probot . Here is example which run javascript linter https://github.com/probot/linter . I would consider using it since seems like it handles github integration well.

**Comment by marcb1** [comment]
I had a half day at work, so I put this together, https://github.com/marcb1/argo-bot (using probot)
Still a WIP , but I'll keep working on it, during my spare time/weekends. 
Documented the workflow in the README, and If there's interest, we can move it to the argo project org.

**Comment by alexmt** [comment]
@marcb1 I think this would be very useful. Added my thoughts to https://github.com/marcb1/argo-bot/commit/bac120e38c49181eddefdfc88ea80dab4bea9c0e#r32342988 . Would be happy to help to work on it. 

I think it make sense to keep working in your repo . Once MVP is ready we can move it to argoproj if you don't mind.

**Comment by marcb1** [comment]
sounds good to me, I updated the README

**Comment by marcb1** [comment]
I have a very minimal set-up working. I'm not an expert in JS, so I welcome any PR's. I'm also having some trouble with the unit tests, currently attempting to use `sinon.stub`. If anyone wants to take a look, would appreciate it.

**Comment by marcb1** [comment]
Bot lives here: https://github.com/argoproj-labs/argocd-bot
Closing this ticket

**Comment by MPV** [comment]
Just found this now, maybe helpful for others here too?
- https://github.com/int128/argocd-commenter
