### ISSUE TITLE
RequeueAfterSeconds for PR generator not being detected when using Matrix generator 

### ISSUE THREAD

**Issue by Aym3nTN** [argoproj/argo-cd#10914]
When trying to use Matrix generator with PR + Cluster generators, the 'RequeueAfterSeconds' parameter of the PullRequest generator always returns 0.

**Describe the bug**

The ApplicationSet is not detecting new PullRequests when the PR generator is used with the Matrix gen.

**To Reproduce**

- Create an AppSet resource with Matrix generator (Here is mine)
- Set RequeueAfterSeconds to whatever value, say 15
- Apply the AppSet to your cluster (I tested with kind and EKS)
- Checks the argocd/argocd-applicationset-controller-xxxxx pod's log, and you'll see sth similar to the below one:

```
time="2022-10-12T15:23:33Z" level=info msg="matched cluster secret" cluster=cluster-aaaaa.sk1.eu-west-1.eks.amazonaws.com-927495557
time="2022-10-12T15:23:33Z" level=info msg="matched cluster secret" cluster=cluster-bbbbb.gr7.eu-west-2.eks.amazonaws.com-1658368765
time="2022-10-12T15:23:34Z" level=info msg="generated 0 applications" generator="{nil nil nil nil nil nil &MatrixGenerator{Generators:xxxx ....}"
time="2022-10-12T15:23:34Z" level=info msg="end reconcile" requeueAfter=0s <--------
```

The doc says that the default value of `requeueAfterSeconds` is 30mins, and in our buggy-case, if I don't provide it I still get 0s in the logs.

**Version**

argocd: v2.5.0-rc1
clusters: kind and EKS v1.23
Git: Gitlab MRs and Github PRs (same issue)

**Comment by mubarak-j** [comment]
@Aym3nTN did you meant to share your AppSet manifest?

**Comment by Aym3nTN** [comment]
@jannfis Could someone take a look at this issue/PR?

**Comment by balzhik95** [comment]
Same problem(
