### ISSUE TITLE
Some way to provide helm values from another file (.argocd-source.yaml / valueFiles / ...)

### ISSUE THREAD

**Issue by kosta** [argoproj/argo-cd#10943]
# Summary

The ability to provide additional helm values from a file _outside_ of the application `release.yaml` but from _inside_ the git repo that the application is defined in.

# Motivation

I have multiple kubernetes clusters and an argo-cd app-of-apps `Application` for each, that reads the actual apps from a directory, e.g.

```
cluster1/app1/release.yaml
cluster1/app2/release.yaml
cluster2/app1/release.yaml
cluster2/app3/release.yaml
...
```

Now, when I update e.g. app1, I would like to write the version to a separate file (via some CI/CD automation), to be picked up by _both_ `cluster1/app1` _and_ `cluster2/app1`. I want this so that the CI/CD automation script does not need to know (or enumerate) all the clusters where app1 is deployed to. (Also, I dont want to fiddle with user-written yaml in that script).

This is currently not possible:
* helm `valueFiles` can only include files from the helm repo, not the git repo.
* `.argocd-source.yaml` and `.argocd-source-<app-name>.yaml` [can change `chart`, `path`, `repoURL`, `targetRevision` but not `helm`](https://github.com/argoproj/argo-cd/blob/master/reposerver/repository/repository.go#L1183)

# Proposal

Either:
* Allow some magic syntax in [`ResolveFilePath`](https://github.com/argoproj/argo-cd/blob/master/util/io/path/resolved.go#L91) to allow referencing values from git, e.g. when using `$` as prefix or `git:` or similar. Then `valueFiles` can be included from the git repo.
* Allow `.argocd-source.yaml` and `.argocd-source-<app-name>.yaml` to overwrite `source.helm` as well (one line change?)

**Comment by crenshaw-dev** [comment]
> .argocd-source.yaml and .argocd-source-<app-name>.yaml [can change chart, path, repoURL, targetRevision but not helm](https://github.com/argoproj/argo-cd/blob/master/reposerver/repository/repository.go#L1183)

I think that misinterprets the code. Those four fields are the only fields in `source` which may _not_ be overridden by .argocd-source.yaml. The code merges the Application source with the .argocd-source.yaml source and then overrides the four protected fields with whatever was in the Application. It's a security measure to keep folks from changing those more sensitive fields.

https://github.com/argoproj/argo-cd/blob/254f3b69aef1ea261e25aca680248df126239b1d/reposerver/repository/repository.go#L1183-L1187

**Comment by kosta** [comment]
Ah yes, I read that the wrong way around 🙈 

So should this already be possible using `.argocd-source.yaml`?

**Comment by crenshaw-dev** [comment]
Yep, I think so!

**Comment by kosta** [comment]
Ok, I tried again and my issue is that I can only override the "app of apps" (application source "directory") but there is nothing that I want to override. I want to override the individual apps (e.g. cluster1/app1/release.yaml), which is not possible from `.argocd-source.yaml`. Or am I missing something?

**Comment by kosta** [comment]
To apply this to your [app of apps example](https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/#helm-example):

```
├── Chart.yaml
├── templates
│   ├── guestbook.yaml
│   ├── helm-dependency.yaml
│   ├── helm-guestbook.yaml
│   └── kustomize-guestbook.yaml
└── values.yaml
```

Is there some way for an app in `templates` to read another values file from within the same git repo or use a `.argocd-source.yaml` or `.argocd-source-<app name>.yaml` file?

**Comment by kosta** [comment]
Actually, it seems the right way to to do this is documented here:
https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
