### ISSUE TITLE
Out of sync resource deployment after syncing

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1094]
With argocd 0.11.1
After syncing deployment:

diff stays 

![image](https://user-images.githubusercontent.com/9946020/52338433-afdc4a00-2a0a-11e9-9d4c-95d221670226.png)

**Comment by peterbosalliandercom** [comment]
cli does not see diff:

argocd app diff sonarqube
===== /ConfigMap nebm-ops/sonarqube-sonarqube-config ======
===== /ConfigMap nebm-ops/sonarqube-sonarqube-copy-plugins ======
===== /ConfigMap nebm-ops/sonarqube-sonarqube-install-plugins ======
===== /ConfigMap nebm-ops/sonarqube-sonarqube-tests ======
===== /PersistentVolumeClaim nebm-ops/sonarqube-sonarqube ======
===== /Service nebm-ops/sonarqube-sonarqube ======
===== apps/Deployment nebm-ops/sonarqube-sonarqube ======
===== extensions/Ingress nebm-ops/sonarqube-sonarqube ======
===== bitnami.com/SealedSecret nebm-ops/sonarqube-sonarqube ======

**Comment by peterbosalliandercom** [comment]
with 0.11.2 problem still remains

**Comment by alexmt** [comment]
Issue was fixed in v0.12. Now  Argo CD UI and Argo CD CLI are consistent.

**Comment by rosscdh** [comment]
seems to be alive in `argoproj/argocd:v1.0.2` too
