### ISSUE TITLE
Unable to run `argocd app edit` when using docker image

### ISSUE THREAD

**Issue by duxing** [argoproj/argo-cd#10990]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

 Receive `FATA[0000] exec: "vi": executable file not found in $PATH` when running `argocd app edit` inside the docker container

tested in `latest`, `v2.3.10`, `v2.4.0`, `v2.4.10`: all versions of docker image have this issue.

**To Reproduce**

 - `docker pull argoproj/argocd:latest`
 - `docker run --rm -it -v $(HOME)/.config/argocd:/home/argocd/.config/argocd argoproj/argocd:v2.4.0` (this issue exists in all the versions I've tested)
 - handle `argocd login` if not already done.
 - `argocd app edit <any_of_your_app>`

=> receive the error message above

**Expected behavior**

a valid `vi` edit screen instead

**Screenshots**

 - running `argocd app edit <any_of_your_app>` inside the container:
![Screen Shot 2022-10-18 at 4 10 36 PM](https://user-images.githubusercontent.com/1322437/196562167-a66896cb-9d9d-416d-ba80-03c2578a3076.png)

 - running `argocd app edit <any_of_your_app>` on my laptop (with `vim` installed):
![Screen Shot 2022-10-18 at 4 11 06 PM](https://user-images.githubusercontent.com/1322437/196561986-4ca88612-adc3-486f-85f0-b059b22546b8.png)

**Version**

```shell
argocd: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:23:37Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:23:37Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

N/A

**Comment by crenshaw-dev** [comment]
For reasons discussed on the PR, we won't be adding vim to the main image. If lots of folks want an argocd-cli image, we'll consider adding that to our repo/build.
