### ISSUE TITLE
[UI] Add application labels to Applications list and Applications details page

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1099]
The issue is to add labels to Applications list and Applications details page:

1. [ ] Applications details page should display application labels and allow user to add/remove labels.
1. [ ] Applications list page should allow filter by application labels

**Comment by alexec** [comment]
Can we close this? No up votes.

**Comment by iremmats** [comment]
Please prioritize this. We have about 400 applications and would dream of sorting them by labels like team, environment, component etc.
Doesnt have to be generic and sortable by anything. Adding just environment and cluster would be super useful.

**Comment by alexec** [comment]
This would be a great one for community contribution. It'll mostly be UI (JavaScript and React) changes.

**Comment by alexec** [comment]
@alexmt do you plan to do this? @jessesuen this is a 5th most popular issue (by community votes), do we want it in v1.3?

**Comment by alexmt** [comment]
Yes, plan to work on it in 1.3
