### ISSUE TITLE
Enhanced log viewer

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#11000]
I would like to improve this.

* Infinite scrolling.
* Clearer labels on button + tooltips.
* Highlight errors and exceptions. Stderr output is in red.
* Search terms highlighted.

Maybe the component could be reused?

**Comment by crenshaw-dev** [comment]
Highlighting stderr will be blocked on https://github.com/argoproj/argo-cd/issues/3491

In the meantime, we could use structured logs to determine what's an error.
