### ISSUE TITLE
Docs: Unclear behavior with resource hooks

### ISSUE THREAD

**Issue by Gianluca755** [argoproj/argo-cd#11007]
Hello, it is not clear to me the behavior of hooks in the cases of failure, as in the [docs](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/).
If we have presync, sync, syncfail, and postsync, and a failure happen in the pre or post, the syncfail will be executed?
If we have presync, sync, syncfail, and postsync, and a failure happen in the sync, the postsync will be executed?
Thanks

**Comment by StinkyBenji** [comment]
Hey there, afaik, the resource marked with `SyncFail` hook will only be executed when the resource marked with `Sync` hook failed.
There is a chapter in the course "GitOps at Scale" from Codefresh, which explains the concept and usage of Sync Wave/hook/window very well.
