### ISSUE TITLE
[UI] Improve Application details client side performance

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1100]
The Application details page is slow while rendering large applications. Following improvements should be implemented to improve performance:

1. [ ] Switch to [PureComponents](https://reactjs.org/docs/react-api.html#reactpurecomponent) , stateless components where possible
1. [ ] Use memoization with event handlers to avoid unnecessary re-rendering
1. [ ] The [application-resource-tree.tsx](https://github.com/argoproj/argo-cd-ui/blob/master/src/app/applications/components/application-resource-tree/application-resource-tree.tsx) component recalculate DAG node positions from scratch on every application change. DAG layout should be cached.

**Comment by alexec** [comment]
Can we close this?
