### ISSUE TITLE
Upgrade git to >=2.34.5

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#11002]
# Summary

The release [patches](https://lore.kernel.org/git/xmqq4jw1uku5.fsf@gitster.g/T/#u) two [vulnerabilities](https://github.blog/2022-10-18-git-security-vulnerabilities-announced/).

# Proposal

Looks like there's no [ubuntu package in 22.04](https://packages.ubuntu.com/jammy/git) yet. We might just have to wait for them.

**Comment by crenshaw-dev** [comment]
We can track the fix availability here: https://security.snyk.io/vuln/SNYK-UBUNTU2204-GIT-3051753

**Comment by 34fathombelow** [comment]
https://ubuntu.com/security/notices/USN-5686-1
Ubuntu will not upgrade versions of git on an LTS.  Instead they will backport the fix, which has already been done.

**Comment by 34fathombelow** [comment]
@crenshaw-dev are you ok with closing this issue?   The last round of releases patched these 2 vulnerabilities.
