### ISSUE TITLE
argocd app create: unknown flag: --set-finalizer

### ISSUE THREAD

**Issue by sekizi** [argoproj/argo-cd#11027]
**Describe the bug**

https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_app_create/ claims to support `--set-finalizer` but in fact an error is thrown when trying to use it.

**To Reproduce**

`argocd app create --set-finalizer ...`

**Expected behavior**

`--set-finalizer` works

**Version**

```
argocd: v2.2.15+b262249
  BuildDate: 2022-10-18T21:57:16Z
  GitCommit: b26224950abcd2a15d2f94c9adce941f4a9c2375
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.2.15+b262249
  BuildDate: 2022-10-18T21:57:16Z
  GitCommit: b26224950abcd2a15d2f94c9adce941f4a9c2375
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: unable to determine ksonnet version: exec: "ks": executable file not found in $PATH
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.6.2+gee407bd
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0
```

**Comment by cleverhu** [comment]
the fist arg must be the app name, so you should try to use command like `argocd app create guestbook --repo https://github.com/argoproj/argocd-example-apps.git --path guestbook --dest-namespace default --dest-server https://kubernetes.default.svc --directory-recurse --set-finalizer`.

**Comment by maheshbaliga** [comment]
Hi @sekizi, I tried to reproduce this issue in the latest code, this functionality works as expected. 

Used this CLI command - `argocd app create guestbook --repo https://github.com/argoproj/argocd-example-apps.git --path guestbook --dest-server https://kubernetes.default.svc --dest-namespace default --set-finalizer` to create the app and the same gets created successfully.

Can you please paste the command and the error that you are getting, here?
