### ISSUE TITLE
go.mod issues while importing argocd package  (v0.0.0 not found)

### ISSUE THREAD

**Issue by balajisa09** [argoproj/argo-cd#11041]
# Summary

Whenever i try to import the argocd package in my own project and do a go mod tidy , the indirect dependencies are looking for packages with v0.0.0 in kubernetes. so inorder to solve this , i had to add some dependencies with a legit version in the replace part of the go.mod file. I assume this is the same case for all projects depending upon kubernetes. afaik, this is a known issue in the cncf community, but it would be better to give an example on how to solve this , so the beginners  like would found it useful.

# Motivation

This would be useful when we create our own projects importing argocd package.

# Proposal

we can have a example go.mod file under the examples folder.

**Comment by crenshaw-dev** [comment]
I think an example go.mod would be good... could we generate it, so that people don't have to update the example go.mod every time the main go.mod changes?

**Comment by balajisa09** [comment]
Could you please assign this to me and guide me on how to generate the example go.mod ? @crenshaw-dev

**Comment by crenshaw-dev** [comment]
Can you post the contents of what you were imagining as the example go.mod? Maybe there's nothing in it that needs to be generated.

**Comment by balajisa09** [comment]
so , i am thinking this should be a doc rather than an example. Under docs/user-guide/import.md , we can mention that , if you are trying to import argocd packages in your own projects , you should have the corresponding version's go.mod replace section in your own go.mod. Hope this makes sense.

**Comment by crenshaw-dev** [comment]
Yeah I like that! Would you have time to write up a PR?

**Comment by balajisa09** [comment]
sure will do.

**Comment by balajisa09** [comment]
@crenshaw-dev  can you review this PR ? https://github.com/argoproj/argo-cd/pull/11096
