### ISSUE TITLE
Deprecate resource.customizations 

### ISSUE THREAD

**Issue by reginapizza** [argoproj/argo-cd#11055]
# Summary

`resource.customizations` without subkeys in the argocd-cm should be deprecated in 3.0 milestone. Subkeys were added way back in Argo CD 2.1 (see this [PR](https://github.com/argoproj/argo-cd/pull/6060) and [blog post](https://blog.argoproj.io/argo-cd-v2-1-first-release-candidate-is-ready-c1aab7795638) announcing the feature). There has been no mention about when it will be deprecated, but as discussed in the argocd contributor's call on Oct 20th, 2022 it should be deprecated. 

# Proposal

We need to immediately add warnings to impacted code and documentation (currently no recent documentation needs to be fixed since it was removed but documentation for older versions needs to have the warning/note added).  Then when the times comes we will need to remove the affected code.

**Comment by crenshaw-dev** [comment]
I think we can't actually do this and still support glob patterns, since ConfigMap keys can't contain asterisks.
