### ISSUE TITLE
Allow the Applicationset policy to be set on ApplicationSet object instead of global flag

### ISSUE THREAD

**Issue by jdomag** [argoproj/argo-cd#11073]
# Summary

The [policy](https://argocd-applicationset.readthedocs.io/en/stable/Controlling-Resource-Modification/#policy-create-only-prevent-applicationset-controller-from-modifying-or-deleting-applications) is set per whole controller, while it should be set per ApplicationSet object. 

# Motivation

We use have staging and dev environments on the same k8s cluster separated by namespace. For staging it's not allowed to override Application parameters and applicationset `policy=create-update` should be applied. For dev namespaces it's totally fine to edit application parameters from cli or gui - for example to switch target branch to simplify testing of changes in helm charts. In that case we need `policy=create-only` to be set. 

# Proposal

default policy field can be overridden by spec of  ApplicationSet object.

**Comment by nhuray** [comment]
It's definitely a feature all ArgoCD users would benefit. At the moment the workaround is to deploy 2 ArgoCD instances.
