### ISSUE TITLE
Dark mode still leaves a white bar at the bottom

### ISSUE THREAD

**Issue by agentq15** [argoproj/argo-cd#11087]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
When activating dark mode, under applications you still see a white bar if you have a tall enough screen.

**To Reproduce**
Enable dark mode and go to applications view

**Expected behavior**
No white bar

**Screenshots**
![image](https://user-images.githubusercontent.com/10948042/198251377-0336d50e-49b1-477e-ae60-ddcf0561ad3d.png)

**Version**
2.5.0

**Comment by Starslider** [comment]
I can not reproduce that behaviour on v2.5.0+b895da4 and Google Chrome Version 107.0.5304.88 - what browser do you use @agentq15 ?

**Comment by agentq15** [comment]
I use Edge but tested with firefox now and it is the same. On the application page when I only show 3 applications so it doesn't cover the whole area

**Comment by Starslider** [comment]
Ok I can reproduce it when I have a browser zoom level of under 100%. Did you have the same behaviour? 100% zoom looks good, under that, a white bar appears at the bottom like your described. @agentq15

**Comment by agentq15** [comment]
The same with 100%
![image](https://user-images.githubusercontent.com/10948042/198560693-13421073-44df-4f75-b727-adf5622c42fc.png)

**Comment by CRASH-Tech** [comment]
I have this bug too.

**Comment by thetredev** [comment]
For what it's worth, it's 100% reproducible this way on `v2.7.2+cbee7e6`:
1. Navigate to the Argo CD applications overview page
2. CTRL + Shift + R to clear website cache and reload the page
3. Click on an application which is running a pod
4. Click on a pod, open the Logs view
5. Click out of the pod, so you see the application view again
6. CTRL + R to reload the page - white bar is present now

**Comment by saumeya** [comment]
Yes, the fix is approved - will ask someone to merge.
