### ISSUE TITLE
sidecar plugin can't read any env var when discover

### ISSUE THREAD

**Issue by PengLingJun** [argoproj/argo-cd#11091]
version is 2.5.0.
I use sidecar plugin to do something,but sidecar discover is scan in repo root path,that not reasonable。
I wonder if it is possible to read a piece of information to distinguish applicaiton from the environment variable, preferably $ARGOCD_APP_SOURCE_PATH. This will determine whether the project can use the plug-in. The configmap management plug-in method of 2.6 will be abandoned, if it cannot be judged by project. Very inflexible. So I read the code and found the following line, the environment variable is empty.
But the documentation says it should be possible to read environment variables

https://github.com/argoproj/argo-cd/blob/309654cece2292fb09959055e8602b9b6dc68077/util/app/discovery/discovery.go#L36

**Comment by crenshaw-dev** [comment]
@PengLingJun the `DetectConfigManagementPlugin` is called from multiple places. In other cases, the env var is passed. In this case, it's not. We just need to thread through the env vars from those other calls. The env var list shouldn't be empty here.
