### ISSUE TITLE
StatefulSet and other resources stay in "OutOfSync", if ServerSideApply =true is enabled

### ISSUE THREAD

**Issue by jkroepke** [argoproj/argo-cd#11106]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have enabled `ServerSideApply=true` on my ArgoCD application. As result, all StatefulSets with claimTemplates are always out of sync

**To Reproduce**

1. kubectl apply -f https://github.com/jkroepke/homelab/blob/90060cf2a6f8ff6d7326dccb92602e70f52440b9/aks/argocd/kube-prometheus-stack.yaml

**Expected behavior**

All Resources are in sync

**Screenshots**

Statefulsets from Loki or other helm charts are also affected 

![image](https://user-images.githubusercontent.com/1560587/198682950-5ce965f6-9bfd-4c4e-9444-8c5e3e4caaf0.png)

ServiceMonitors are also affected:

![image](https://user-images.githubusercontent.com/1560587/198683171-80cfd1e4-611b-49e1-88df-e4f461447c6e.png)

**Version**

```shell
argocd version
argocd: v2.5.0+b895da4
  BuildDate: 2022-10-25T14:40:01Z
  GitCommit: b895da457791d56f01522796a8c3cd0f583d5d91
  GitTreeState: clean
  GoVersion: go1.18.7
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

**Comment by maartengo** [comment]
This looks like a duplicate of https://github.com/argoproj/argo-cd/issues/11074

**Comment by jkroepke** [comment]
Yes, I do not found the issue by search. Consider to change the title.
