### ISSUE TITLE
Application list: add filter for "auto-sync enabled"

### ISSUE THREAD

**Issue by alexef** [argoproj/argo-cd#11102]
# Summary

Make it easy to find applications that have Auto Sync disabled (either manually or because someone rolled back). 

The existing "Out of Sync" filter doesn't really cover this use case. An application can have Auto Sync enabled, but still go "Out of Sync" (temporarily, or because Self Heal is not enabled), so the existing Sync Status filter cannot be used to detect these application.

# Motivation

We manage a large set of applications with Argo CD. One issue that comes up often is that we want to see which Applications have the AutoSync enabled. This is not easily possible in the Application list view, also not on the Application Details page. 

The only place where this is visible UI is in the Application Details dialog.

# Proposal

This can be implemented by either (see mockups):

- adding a filter to the sidebar
- adding a badge/text to the Application card (on the Status line)
- adding a notice on the Application Details page (under sync status)
- all of the above

<img width="254" alt="Screenshot 2022-10-28 at 11 04 21" src="https://user-images.githubusercontent.com/346576/198549912-b2089c18-abb4-4c3a-bfaf-50c8aa866749.png">
<img width="478" alt="Screenshot 2022-10-28 at 11 12 07" src="https://user-images.githubusercontent.com/346576/198550974-8794f184-17ee-4012-8f1a-8182b0d08823.png">
<img width="644" alt="Screenshot 2022-10-28 at 11 10 14" src="https://user-images.githubusercontent.com/346576/198550440-abf4c01f-3e5f-4b34-9333-8b157bcb4872.png">

**Comment by alexef** [comment]
Correct!

**Comment by crenshaw-dev** [comment]
If we add more than those 2, maybe collapse by default. Crutchfield's filter system is pretty good, and it does that. The most popular filters are expanded, others are collapsed. 

Example: https://www.crutchfield.com/g_359550/Audiophile-Headphones.html

<img width="400" alt="filters on ecommerce site Crutchfield with popular filters like 'rating' expanded and others collapsed" src="https://user-images.githubusercontent.com/350466/199765117-5151a6a3-73c6-4bd8-bb0a-c56405d2a573.png">

**Comment by todaywasawesome** [comment]
It would be great if we had an additional filter drawer for options like auto-sync, or other sync options like self-heal etc. It would be nice to have a more generic way of bringing in additional filters for sync options. I'd also like a filter for apps that are defined in git vs apps that are defined via the UI/CLI only. 

Maybe we could do a larger UI update that would enable lots of generic options. I suggest bringing this up in the UI meeting. The next one is [Nov 16th](https://calendar.google.com/calendar/u/0/embed?src=argoproj@gmail.com).

**Comment by alexef** [comment]
Closing this as implemented in 2.6.
