### ISSUE TITLE
Registry login error with helm OCI private dependencies ca-file flag being added unnecessarily 

### ISSUE THREAD

**Issue by timgriffiths** [argoproj/argo-cd#11100]
Checklist:

* [ X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X] I've included steps to reproduce the bug.
* [X ] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to connect to a [Harbor](https://goharbor.io/) helm repository which is self-hosted and has a self-signed certificate. 

for the self-signed certificate, I add the pem to the argocd-tls-certs-cm config map

For public repo's this is fine everything works ok, but for private projects, I believe I need to create a repository definition in argo and this is where I hit problems (otherwise i get unauthorised errors as expected)

https://github.com/argoproj/argo-cd/blob/45fc484447bb46e2768af8cbef4e254a5c2ec9a1/util/helm/cmd.go#L93 it looks like just an oversight as helm does not support this flag for registry login's https://helm.sh/docs/helm/helm_registry_login/ 

**To Reproduce**

For simplicity did this all within a running argo server pod

First, add the harbor self-signed cert to the argocd-tls-certs-cm config map

```
argocd@argocd-server-5d7f4656b-mtwbh:~$ argocd repo add registry.magic.com --name private-repo --enable-oci --type helm --username user --password magic
FATA[0000] rpc error: code = Unknown desc = error testing repository connectivity: `helm registry login registry.magic.com --username ****** --password ****** --ca-file /app/config/tls/registry.magic.com` failed exit status 1: Error: unknown flag: --ca-file
```
If i run the same helm command in the pod, minus the --ca-file flag it works fine

I have also tried running the repo add command with `--insecure-skip-server-verification` but it has the same result. ... If I remove my certificate from  argocd-tls-certs-cm config map I get a bunch of certificate issues when trying to pull in the charts when they are set up as dependent charts

**Expected behavior**

Argo is able to add a private oci repo from Harbor

**Version**

```shell
argocd: v2.4.8+844f79e
  BuildDate: 2022-07-29T17:01:39Z
  GitCommit: 844f79eb9d8f3ab96d4ce6f8df211c6093a660ba
  GitTreeState: clean
  GoVersion: go1.18.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.8+844f79e
  BuildDate: 2022-07-29T17:01:39Z
  GitCommit: 844f79eb9d8f3ab96d4ce6f8df211c6093a660ba
  GitTreeState: clean
  GoVersion: go1.18.4
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

I am not sure if I will hit any issues raised in https://github.com/argoproj/argo-cd/issues/8563 but this is my main stumbling block

**Comment by alexef** [comment]
> First, add the harbor self-signed cert to the argocd-tls-certs-cm config map

Checking the code, it seems like the `--ca-file` flag is only added when the ca file is present. Have you tried to add repo without the ca-file?

**Comment by timgriffiths** [comment]
Without the ca file being present the non-secure repo's don't work, you get certificate errors as we are using a self-signed certificate

**Comment by geowalrus4gh** [comment]
we are also affected by this while upgrading ArgoCD from v2.3.4 to v2.4.17. Any workaround for this or any fix planned ?

**Comment by geowalrus4gh** [comment]
is this issue related to  https://github.com/helm/helm/issues/11352 ?
