### ISSUE TITLE
Add admin command to get initial password

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#11117]
# Summary

Add an `argocd admin initial-password` command to get the initial password.

# Motivation

It's annoying to remember/use the `kubectl` command from the docs. That command also doesn't explicitly remind you to change the initial password.

# Proposal

The command should use your current kube config to pull down the initial password. Then it should strongly encourage you to change that password.

**Comment by iam-veeramalla** [comment]
Hi @crenshaw-dev , Assigning it to myself. Please let me know for any objections :)
