### ISSUE TITLE
Disable argo-cd namespace in applications title on web-ui

### ISSUE THREAD

**Issue by CRASH-Tech** [argoproj/argo-cd#11111]
# Summary

Disable argo-cd "release name" in applications title on web-ui

# Motivation

No reason to show it

# Proposal

Disable it

![test](https://user-images.githubusercontent.com/13507148/198844155-95c1f914-7844-45ce-b230-460a45d78c7e.jpg)

**Comment by alexef** [comment]
See related Slack thread: https://cloud-native.slack.com/archives/C01TSERG0KZ/p1666947440257579 - this was introduced together with application in multiple namespaces, and it may make sense to hide it when that flag is not active.

**Comment by alexef** [comment]
yes, this is the problem: even though the flag is not enabled, the prefix shows up.

**Comment by crenshaw-dev** [comment]
Started a draft with the backend work: https://github.com/argoproj/argo-cd/pull/11165

I got lost in trying to pass down the setting from the top level of the app to the applications list. I want to avoid excessive blocking calls to the settings endpoint.

@keithchong or @rbreeze would you be able to help?

**Comment by crenshaw-dev** [comment]
@ashutosh16 looks like we missed a spot.  :-)

**Comment by ashutosh16** [comment]
> @ashutosh16 looks like we missed a spot. :-)

The format is not consistent with how it is displayed on the UI. I have put another [PR](https://github.com/argoproj/argo-cd/pull/11493) to fix search

**Comment by abhishakeonteddu** [comment]
> See related Slack thread: https://cloud-native.slack.com/archives/C01TSERG0KZ/p1666947440257579 - this was introduced together with application in multiple namespaces, and it may make sense to hide it when that flag is not active.

not able to access this slack link.
what is the fix for this issue
