### ISSUE TITLE
Override values.yaml with values coming from another git repo

### ISSUE THREAD

**Issue by Emmerson-Miranda** [argoproj/argo-cd#11112]
# Summary

In the current Helm integration from an ArgoCD "application" you can specify custom values to the helm chart reading from a file or creating the values inline.

Should be good if we have another option to be able to pull the values.yaml from another git repo also.

# Motivation

I want to have my Helm chart definitions separated from especific helm values per environment.

# Proposal

Add a thrid option to get values similar to this:

      valueGit:
        repoURL: https://gith...    #git https repo
        targetRevision: HEAD        #this refers to the values repo version.
        path: ./uat/values.yaml     #path to the values.yaml to be passed to helm

**Comment by crenshaw-dev** [comment]
@Emmerson-Miranda thanks for the issue! This feature is being tracked in https://github.com/argoproj/argo-cd/issues/2789, and it is planned for 2.6.

**Comment by Emmerson-Miranda** [comment]
Thank you @crenshaw-dev , when is planned release the version 2.6
