### ISSUE TITLE
Network policy egress rules break HA Redis on GKE with NodeLocal DNSCache

### ISSUE THREAD

**Issue by busser** [argoproj/argo-cd#11126]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When installing ArgoCD with the provided HA manifests, the Redis cluster never reaches a healthy state:
- The Redis server's `config-init` init-container fails for instances 1 and 2 (instance 0 starts OK).
- The HAProxy `config-init` init-container fails for all instances.

Logs indicate that they fail because DNS lookup of `argocd-redis-ha-announce-0` fails.

**To Reproduce**

1. Create a GKE cluster with NodeLocal DNSCache enabled ([Kubernetes docs](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/)) ([GKE docs](https://cloud.google.com/kubernetes-engine/docs/how-to/nodelocal-dns-cache))
2. Install ArgoCD with these manifests: https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.0/manifests/ha/install.yaml

**Expected behavior**

I expected the 3 Redis nodes to reach a Ready state and the 3 HAProxy instances to reach a Ready state.

**Version**

```shell
argocd: v2.5.0+b895da4
  BuildDate: 2022-10-25T14:40:01Z
  GitCommit: b895da457791d56f01522796a8c3cd0f583d5d91
  GitTreeState: clean
  GoVersion: go1.18.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.0+b895da4
```

**Logs**

HAProxy (regardless of whether Redis is running or not):

```
Waiting for service argocd-redis-ha-announce-0 to be ready (1) ...
Waiting for service argocd-redis-ha-announce-0 to be ready (2) ...
Waiting for service argocd-redis-ha-announce-0 to be ready (3) ...
Waiting for service argocd-redis-ha-announce-0 to be ready (4) ...
Waiting for service argocd-redis-ha-announce-0 to be ready (5) ...
Waiting for service argocd-redis-ha-announce-0 to be ready (6) ...
Waiting for service argocd-redis-ha-announce-0 to be ready (7) ...
Waiting for service argocd-redis-ha-announce-0 to be ready (8) ...
Waiting for service argocd-redis-ha-announce-0 to be ready (9) ...
Waiting for service argocd-redis-ha-announce-0 to be ready (10) ...
Could not resolve the announce ip for argocd-redis-ha-announce-0
```

Redis:

```
Mon Oct 31 14:17:36 UTC 2022 Start...
Initializing config..
Copying default redis config..
  to '/data/conf/redis.conf'
Copying default sentinel config..
  to '/data/conf/sentinel.conf'
Identifying redis master (get-master-addr-by-name)..
  using sentinel (argocd-redis-ha), sentinel group name (argocd)
Could not connect to Redis at argocd-redis-ha:26379: Try again
Could not connect to Redis at argocd-redis-ha:26379: Try again
Could not connect to Redis at argocd-redis-ha:26379: Try again
  Mon Oct 31 14:18:51 UTC 2022 Did not find redis master ()
Identify announce ip for this pod..
  using (argocd-redis-ha-announce-2) or (argocd-redis-ha-server-2)
  identified announce (10.240.0.44)
Setting up defaults..
  using statefulset index (2)
Getting redis master ip..
  blindly assuming (argocd-redis-ha-announce-0) or (argocd-redis-ha-server-0) are master
  identified redis (may be redis master) ip ()
Error: Unable to resolve redis master (getent hosts).
```

**Root-cause analysis**

Further troubleshooting shows that the DNS lookup fails because of an egress rule added to the following network policies in release 2.5.0:
- `argocd-redis-ha-server-network-policy` makes Redis fail
- `argocd-redis-ha-proxy-network-policy` makes HAProxy fail

The egress rule responsible is, in both:

```yaml
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector: {}
```

We currently have three workarounds:

1. Allow DNS queries to servers running outside the cluster:

```diff
  spec:
    egress:
    - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
-     to:
-     - namespaceSelector: {}
```

2. Allow DNS queries to the `kube-system/kube-dns` service's cluster IP:

```diff
  spec:
    egress:
    - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
      to:
-     - namespaceSelector: {}
+     - ipBlock:
+         cidr: 10.240.128.10/32 # Address varies from cluster to cluster
```

3. Deactivate NodeLocal DNSCache.

**Hypothesis**

GKE's implementation of NodeLocal DNSCache routes connections to KubeDNS's IP address to a non-pod IP address, which the network policies block. If this is the case, then users of [Cloud DNS with GKE](https://cloud.google.com/kubernetes-engine/docs/how-to/cloud-dns) may encounter the same issue. So may anyone using a DNS server running outside the Kubernetes cluster.

In any case, ArgoCD's manifests assume that pods use a DNS server running inside the cluster. When this is not the case, the Redis cluster never gets up and running.

**Comment by 34fathombelow** [comment]
@busser thank you for your bug report and very detailed analysis.   I would be in favor for option 1.  I have no issue with the pod making make requests to outside dns services.

@crenshaw-dev what do you think?

**Comment by busser** [comment]
@34fathombelow thank you for the rapid response. PR #11127 implements option 1.

**Comment by 34fathombelow** [comment]
@busser by any chance have you tried running the manifest that contains your fix? If so do all the pods come up?  I'd do believe your fix would solve the problem with NodeLocal DNSCache,  but we may be also facing a separate issue.

**Comment by busser** [comment]
@34fathombelow yes, with the manifest from PR #11127 all pods reach a Ready state 👍

**Comment by sthomson-wyn** [comment]
Noting that the fix in https://github.com/argoproj/argo-cd/pull/11176 did not work for us when using NodeLocal DNSCache... 

Workaround #1 still works for us, however

**Comment by DimitarKapashikov** [comment]
We still experience issues with version 2.5.2 . It is stuck waiting for the ArgoCD server health check.

**Comment by radoslav-tomov** [comment]
Had the same issue and traced it to NodeLocal DNSCache. In our case the DNS was using different port than 53 TCP/UDP.  Adding the port to the egress configuration solved it for me.
