### ISSUE TITLE
argocd logo partially overlapped by permanent banner in 2.5.0

### ISSUE THREAD

**Issue by rtoma-pq** [argoproj/argo-cd#11125]
**Describe the bug**

The argocd logo is partially overlapped by a permanent banner.

See following screenshot where the head of the mascotte is overlapped by the banner:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/114475822/199020791-d6bd902d-6805-455f-a56a-f10e8481cc01.png">

Same when sidebar is collapsed:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/114475822/199021622-94e28497-e851-49dd-98fb-d94ade88cf54.png">

**To Reproduce**

Install argocd 2.5.0 with following keys in configmap argocd-cm:

```
  ui.bannercontent: ArgoCD for k8s-xxx
  ui.bannerpermanent: "true"
```

**Expected behavior**

No overlap, like in argocd 2.4.x:

<img width="816" alt="image" src="https://user-images.githubusercontent.com/114475822/199021176-26132e7d-561f-427f-9652-f36e9e6b6565.png">

**Screenshots**

See above sections.

**Version**

2.5.0

**Logs**

n/a

**Comment by saumeya** [comment]
this should fix https://github.com/argoproj/argo-cd/pull/11101
