### ISSUE TITLE
argocd-initial-admin-secret password invalid

### ISSUE THREAD

**Issue by dairta** [argoproj/argo-cd#11167]
kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | echo
returns the password

using argocd-initial-admin-secret or admin and the secret returns Invalid username or password

**Comment by iam-veeramalla** [comment]
Hey @dairta , the password is base64 encrypted. 

Please use the below command
`kubectl -n argocd-e2e get secrets argocd-initial-admin-secret -o jsonpath='{.data.password}'|base64 -d`

In future, you can use the `argocd admin initial-password` command being added by this 
#11117

**Comment by dairta** [comment]
running this from windows 10 cmd connected to a aks cluster I get 
'base64' is not recognized as an internal or external command,
operable program or batch file.

kubectl get namespaces
NAME              STATUS   AGE
argocd            Active   70m
default           Active   5h11m
kube-node-lease   Active   5h11m
kube-public       Active   5h11m
kube-system       Active   5h11m

**Comment by dairta** [comment]
So for anyone else confused by the documentation. If you are in VSCode and at a terminal don't use cmd, pwsh, or powershell. Open a Git Bash prompt and execute the the line above iam-veeramalla suggested but replace the argocd-e2e with the namespace which by default is argocd.

kubectl -n argocd get secrets argocd-initial-admin-secret -o jsonpath='{.data.password}'|base64 -d
