### ISSUE TITLE
Exec in apps outside of ArgoCD namespace not working

### ISSUE THREAD

**Issue by bobertrublik** [argoproj/argo-cd#11166]
Together with the 2.5.0 update I deployed all ArgoCD apps apart from ArgoCD itself to their respective namespaces. When I want to exec into an ArgoCD pod everything works as usual. However when I try to exec into a pod in a different namespace I receive the error `Terminal Connection Error: Internal error`.

My policy.csv

```
p, admin, exec, create, */*, allow
g, group-name, admin
```

Checking the RBAC permissions for the argocd-server serviceaccount everything also looks good.

```
kubectl auth can-i create pods --subresource='exec' --as=system:serviceaccount:argocd:argocd-server
yes
```

The logs unfortunately don't print anything useful.

**Comment by crenshaw-dev** [comment]
I bet we just failed to parameterize the request to terminal.go with the appNamespace.

**Comment by Dbzman** [comment]
I think we have even more cases where this is missing:
* terminating a sync
* marking an app as favorite

**Comment by bobertrublik** [comment]
Additionally using the App of Apps concept when I click on "Open application" the link is missing the namespace and it can't open the app. :)

**Comment by EladDolev** [comment]
Not sure if it is related, but the Restart/Resume buttons are missing when expanding the menu on a Deployment

**Comment by yevgeniyo** [comment]
Same here, web terminal stopped work for us after the upgrade to 2.5

**Comment by bobertrublik** [comment]
Are there any updates? :) I would really dislike having to revert all apps to the ArgoCD namespace due to this bug.

**Comment by crenshaw-dev** [comment]
> Same here, web terminal stopped work for us after the upgrade to 2.5

@yevgeniyo did you also enable apps-in-any-namespace? If not, that sounds like a different bug.

**Comment by yevgeniyo** [comment]
@crenshaw-dev no, we have apps on the namespace `argocd`
but web terminal to pods is not working

**Comment by crenshaw-dev** [comment]
@yevgeniyo can you open a new issue for that? This one is specific to apps outside `argocd`.

**Comment by crenshaw-dev** [comment]
Threw this together as a start (I can't dedicate too much time to it at the moment): https://github.com/argoproj/argo-cd/pull/11400/files

Would someone be willing to give that a test?

**Comment by bobertrublik** [comment]
> Threw this together as a start (I can't dedicate too much time to it at the moment): https://github.com/argoproj/argo-cd/pull/11400/files
> 
> Would someone be willing to give that a test?

Yes it worked! I built the image from your PR, deployed it to my dev environment and was able to create a terminal for apps in other namespaces. The only bug I have left is the App links in App of App configurations being broken since the namespace is missing in the URL call.

However thank you very much!

**Comment by crenshaw-dev** [comment]
Remaining bugs:

- [ ] terminating a sync
- [ ] marking an app as favorite
- [ ] App links in App of App configurations

**Comment by quentinlacrouts** [comment]
Any update on that one ?

**Comment by crenshaw-dev** [comment]
@quentinlacrouts thanks for the nudge! I'll get it merged today.
