### ISSUE TITLE
Orphaned resources no longer have a distinct color in the UI

### ISSUE THREAD

**Issue by danieljkemp** [argoproj/argo-cd#11180]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Orphaned resources no longer have a distinct color in the UI.

**To Reproduce**

View an application in the UI, and select "Show Orphaned"

**Expected behavior**
In the past, orphaned resources were grayed out, and could be visually distinguished from non-orphaned objects.

**Screenshots**

![image](https://user-images.githubusercontent.com/10280889/199739644-8e043bc1-cd67-48af-b3f6-18e15a2f0739.png)

**Version**

```shell
v2.5.1+504da42
```

**Logs**

```
N/A
```

**Comment by danieljkemp** [comment]
![image](https://user-images.githubusercontent.com/10280889/200339163-535ee443-fd88-419a-8f51-7733d4e7965d.png)
https://argo-cd.readthedocs.io/en/stable/user-guide/orphaned-resources/

example in the docs of what it should look like. In the screenshot above, both of the resources should be grey.

**Comment by alexef** [comment]
I can confirm they show white and not grayed out. Will take a look at the code.

**Comment by alexef** [comment]
Seems like the problem was introduced along with themes:
<img width="328" alt="Screenshot 2022-11-07 at 16 05 42" src="https://user-images.githubusercontent.com/346576/200343577-a859c815-0fd8-46d2-8f63-8b0c584a073b.png">

The fix is to add the class to the theme.
