### ISSUE TITLE
Sync with Nexus repository doesn't work

### ISSUE THREAD

**Issue by csscriptplus** [argoproj/argo-cd#11195]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I used Jenkins to build my application and the build generated the Helm charts and put them into the Nexus repository as xxx.1.0.1-SNAPSHOT.tgz.
In ArgoCD I created a new app and it checked out the xxx.1.0.1-SNAPSHOT version and deployed it to the Kubernetes cluster.
So far everything is ok.
Now I built a new version in Jenkins xxx.1.0.2-SNAPSHOT.tgz. It was also deployed to the Nexus repository.
But the ArgoCD Sync does not recognize that a new version exists. I also can't manually switch to the new revision.

**Version**

```shell
v2.5.0+b895da4
```

**Comment by crenshaw-dev** [comment]
I'm not familiar with Nexus... if it's an OCI registry, we don't currently support targetRevision ranges (though there is a [PR](https://github.com/argoproj/argo-cd/pull/10641) for that). If it's a standard Helm repo, you can specify a range, and Argo CD will automatically pick up new versions. https://argo-cd.readthedocs.io/en/stable/user-guide/tracking_strategies/

**Comment by csscriptplus** [comment]
Hi @crenshaw-dev, thanks, when I specify a range it works. I built a new Helm tgz and ArgoCD found the new version. But the sync has an error:
`Failed sync attempt to 1.0.3-SNAPSHOT: one or more objects failed to apply, reason: StatefulSet.apps "user-rest" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden (retried 5 times).`

**Comment by crenshaw-dev** [comment]
Certain changes can't be applied without re-creating the resource. I think the Replace sync option is appropriate for this case.

**Comment by csscriptplus** [comment]
A revision with wildcards works. The auto sync found the new version. But the sync option "replace" is not enough. Sync can't replace my StatefuleSet I need the option "force" too. But this option I have only by the manual sync.

**Comment by csscriptplus** [comment]
Quarkus Helm has an option to remove the version information of the labels.
