### ISSUE TITLE
feat(ui): show application's age in the application list view

### ISSUE THREAD

**Issue by alexef** [argoproj/argo-cd#11209]
# Summary

Show application age (time since created) in the application list view.

# Motivation

While dealing with a large number of applications (and some of them short lived), it would be useful to see when the application was created (or what age does it have in the cluster).

This is only possible atm by clicking on a panel and checking the root node of the application details view.

# Proposal

This could be implemented as a label on the card, like in this mockup:

<img width="495" alt="Screenshot 2022-11-06 at 16 01 14" src="https://user-images.githubusercontent.com/346576/200178674-163bd993-7ce9-4664-a91d-c2f2507ec610.png">

**Comment by schakrad** [comment]
I would like to work on this issue.

**Comment by alexef** [comment]
@schakrad see also comment on #11304 . if you're implementing it, just add it as a new row under Namespace :)
