### ISSUE TITLE
User Info text in sidebar is not aligned

### ISSUE THREAD

**Issue by LS80** [argoproj/argo-cd#11203]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

A minor UI issue - some text in the sidebar is not properly aligned. See the screenshot.

**Screenshots**

<img width="282" alt="image" src="https://user-images.githubusercontent.com/4941953/200119443-7933dd60-3a42-47f6-ace1-a7ba76880fb1.png">

**Version**

```
v2.5.1+504da42
```

**Comment by JessieTeng89** [comment]
Hi @LS80 @saumeya @alexec 
I would like to work on this issue, could you please assign it to me?

**Comment by rbreeze** [comment]
Hi @JessieTeng89, this issue will actually be fixed as part of a larger redesign effort. The first PR in this effort is here: https://github.com/argoproj/argo-cd/pull/12053

This alignment problem is also detailed in another issue, so I'll close this one as duplicate.

https://github.com/argoproj/argo-cd/issues/11302
