### ISSUE TITLE
bug: helm dependency conditions are not respected

### ISSUE THREAD

**Issue by alexef** [argoproj/argo-cd#11201]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

When a helm uses subcharts that are only conditionally enabled, and the condition is false, they should not be rendered. Argo renders all subcharts at all times by default.

**To Reproduce**
Assume the following chart structure:

```
- chart1
+--+ Chart.yaml
      + values.yaml
       + charts/
       +-----+ chart2/
                  + Chart.yaml
                  + templates/
                  +-----+ cm.yml
```

in `chart1/Chart.yaml` we define:
```
dependencies:
- name: chart2
  condition: chart2.enabled
```

in`chart1/values.yaml` we set:
```yaml
chart2:
   enabled: false
```

We test this locally with `helm template` and observe that the chart2's `cm.yaml` template is NOT generated.

We deploy this with argo and we see that regardless of values/parameters override, chart2's `cm.yaml` template is ALWAYS generated.

**Expected behavior**

We expect Argo to respect dependency conditions when a chart uses subcharts.

**Screenshots**

**Version**

```
2.5, latest
```

**Comment by 34fathombelow** [comment]
@alexef Which version of helm are you using locally?  Argo CD v2.5.x is now using helm-3.10.1, previous v2.4.x was using helm-3.8.1  Currently looking into [issues ](https://github.com/helm/helm/issues) for upstream helm.

**Comment by alexef** [comment]
@34fathombelow I'm using 3.9 and argo has 3.10 inside.

after hitting my head on the wall for hours, I figured it out:
- in `chart1/Chart.yaml` I am missing this crucial line:
```
apiVersion: v2
```
- because of that, when I package and upload to the registry for Argo Consumption, although the subchart (chart2) is packaged, the `dependencies: ...` section of `chart1/Chart.yaml` is wiped out, including conditions.

This is the reason argo always rendered chart2, b/c helm in reposerver had no clue about about the conditions.

This bug can be closed, [pebkac](https://github.com/helm/helm/issues/11170).
