### ISSUE TITLE
Apllications in ArgoCD UI not visible but deployed when exposed via Ingress.

### ISSUE THREAD

**Issue by GeorgiDimv** [argoproj/argo-cd#11215]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I expose my ArgoCD via ingress, my applications are not visible in the UI. When I change from ingress to clusterIP or load balancer they are visible. 

**To Reproduce**

Deploy ArgoCD with ingress according to the docs 
https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#kubernetesingress-nginx

**Expected behavior**

Applicaitons to be visible in UI

**Version**

Argocd version 2.5.1

**Comment by iam-veeramalla** [comment]
Hi @GeorgiDimv , Can you please provide the correct Argo CD version ?

**Comment by GeorgiDimv** [comment]
> Hi @GeorgiDimv , Can you please provide the correct Argo CD version ?

2.5.1, sorry for mistake
