### ISSUE TITLE
Terminating sync leads to "error getting application by name"

### ISSUE THREAD

**Issue by karlschriek** [argoproj/argo-cd#11239]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Since the release of v.2.5.0 we have been making use of the feature that allows us to deploy Application resources into namespaces other than the default `argocd` Namespace. The full implications of this feature is described here: https://github.com/argoproj/argo-cd/pull/9755. One of the relevant changes is that Applications with the same name can now be rolled out to different namespace. I.e., just `[application name]` is no longer a unique identifier. Instead, applications must be referenced as `[namespace]/[application name]`. Just referencing `[application name]` serves as a shorthand for `argocd/[application name]`.

I believe I have stumbled upon a UI feature that has not implemented this change yet.

There is a "terminate" button that you can hit to abort a sync. If I do this now, I get the following error:

`Unable to terminate operation: error getting application by name: applications.argoproj.io "my-application" not found`

I am fairly certain this is happening since it isn't properly appending the namespace of the request it is sending. I.e. it is trying to terminate the sync on `argocd/my-application` (since that is what `my-application` is shorthand for) instead of terminating `my-namespace/my-application`

**To Reproduce**

Roll out a Application into a namespace other than `argocd` (see https://github.com/argoproj/argo-cd/pull/9755 for instructions on how to enable this feature; it doesn't work out of the box). Make it sync and then hit the "terminate" button before the sync completes.

**Expected behavior**

I would expect terminate to correctly reference my application, even if it is in a custom namespace.

**Screenshots**
hit terminate:
![image](https://user-images.githubusercontent.com/25316920/200833823-bb9cb20e-a1cb-40a4-a35c-1a325ac3a646.png)

error message:
![image](https://user-images.githubusercontent.com/25316920/200833941-7d12c561-c3d1-4dcf-8eac-8fbea5cf3dfc.png)

**Version**

```shell
v2.5.2
```

**Comment by jannfis** [comment]
Oops. Sorry. Fix for that: #11724
