### ISSUE TITLE
Notifications for applications in namespaces do not work

### ISSUE THREAD

**Issue by ArchdukeNavaron** [argoproj/argo-cd#11252]
**Describe the bug**

We migrated our applications to specific namespaces which made it easier for us to logically group applications within Kubernetes. After we migrated them we also wanted to configure notifications for them but it does not work. We had a quick look into it and it seems that first, that the notification controller does not have permissions to get all applications in all namespaces (a ClusterRole is missing). Second, we are not totally sure, if the controller itself can manage applications within other namespaces (we were not able to figure it out with a quick look over the code - but we didn't spent too much time looking for it).

In this specific case we wanted to receive Slack notifications. But I don't think that it would work with other services either. We were not able to see any activity of the application controller whatsoever.

For test purposes we configured an application in the argocd namespace. When we configured a notification subscription for it it immidiatly worked and we were able to see logs in the notification controller.

**To Reproduce**

- Deploy at least ArgoCD 2.5.0
- Allow ArgoCD to manage applications in other namespaces
- Configure notification templates and triggers
- Deploy an application into an allowed namespace (but not `argocd`)
- Configure notficiation subscription (either global or application annotation)

**Expected behavior**

The notification controller can monitor all applications in the cluster and react to events.

**Version**

```shell
argocd: v2.5.2+148d8da
  BuildDate: 2022-11-07T16:42:47Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
```

**Comment by patrickbardo** [comment]
Same issue. Running an apps-in-any-namespace setup, and would like the notification controller to monitor application resources in other namespaces. 

Current workaround for us is to put the subscription annotation on the AppProject resource (since we manage those in the argocd namespace), but would like this functionality so users can manage their own notifications.

**Comment by cw-sakamoto** [comment]
Same issue.
I think it is because the namespace of the informer is restricted.
https://github.com/argoproj/argo-cd/blob/master/notification_controller/controller/controller.go#L61

**Comment by lukma99** [comment]
Same issue. Tried again with debug logs activated. Applications in other namespaces don't create a single line of log in the notifications controller. So there has to be a configuration mismatch somewhere in the beginning of the logic. I tried to find it, but this was the first time I looked into the Argo CD codebase and unfortunately I could not find anything. Maybe what @cw-sakamoto said is a good hint.

**Comment by Niksko** [comment]
The [appInformer](https://github.com/argoproj/argo-cd/blob/ceed6538172a324c22e4b549ac288fae6d80c7e4/notification_controller/controller/controller.go#L62) has an appClient which only looks at a specific namespace.

Instead, the controller needs to do something like what happens in the Application controller: https://github.com/argoproj/argo-cd/blob/ceed6538172a324c22e4b549ac288fae6d80c7e4/controller/appcontroller.go#L1835

i.e. look for applications in all namespaces and then filter them down based on some configuration.

**Comment by ketronkowski** [comment]
Any feedback from ArgoCD maintainers on the PR from @Niksko as a fix for this issue?

**Comment by asajoshi** [comment]
@patrickbardo , did setting the subscription annotation on AppProject in argocd ns work for you ? It does not seem to work for me. I have my AppProject in argocd ns but the applications are in different ns.  wondering if something is missing!

**Comment by akashkaveti** [comment]
I ran into the same issue. It seems like [describe the issue briefly]. I tried modifying the role to cluster role so that notification controller can watch/get details about the other namespaced argo applications, but unfortunately, that didn't work for me either.

**Comment by patrickbardo** [comment]
Sorry @asajoshi, I just tried to validate again and it looks like I was wrong, only the argocd namespaced applications are being picked up. Looks like @Niksko has a PR fix :)

**Comment by AndreyBlum** [comment]
Im having the same issue, my notifications dont work in another namespace

**Comment by crenshaw-dev** [comment]
Resolved by https://github.com/argoproj/argo-cd/pull/15702
