### ISSUE TITLE
PermissionDenied errors should be more specific

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1126]
PermissionDenied does not specify what permissions are lacking, making it hard for users to debug or understand what is needed to gain privileges to do some action. It would be better to include which resource and action is being rejected.

**Comment by alexmt** [comment]
To help troubleshot PermissionDenied errors user should be able to see list of JWT token claims in UI. This information is already available in browser

**Comment by jessesuen** [comment]
Fixed
