### ISSUE TITLE
link to argoWorkflows for related CRDs

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-cd#11278]
argoWorkflows users will often also use argoCD
there are certain CRDs in argoWorkflows (ie cronworkflow, workflowtemplate, sensor, eventsource..etc), idea is to have a link on the specific object (ie cronworkflowXYZ) that will open up that object in argoWorkflows UI (ie the cronworkflow page for that specific named object)

basic implementation idea:
optional config for argoWorkflows base URL (or perhaps it can be auto derived from Ingress manifest of argoWorkflows)
have a list of CRDs relevant to argoWorkflows
ui change to show that argoWorkflows href link on each relevant object in argoCD

**Comment by jessesuen** [comment]
Duplicate of https://github.com/argoproj/argo-cd/pull/10278

This should be solved with deep linking feature
