### ISSUE TITLE
Update ApplicationSets to use the sprig library v3

### ISSUE THREAD

**Issue by genehand** [argoproj/argo-cd#11277]
# Summary

Go templates in ApplicationSets are a nice addition, but I was surprised to find some missing sprig functions from the [linked documentation](https://masterminds.github.io/sprig/).

# Motivation

I was looking to specify defaults for config not passed through the values field.  Because `{{ .values }}` now comes through as an object like [metadata](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/#cluster-generators), this gets a little trickier.  

The [dig](https://masterminds.github.io/sprig/dicts.html#dig) function can help by traversing nested dicts or falling back to a default.  It was added in [v3.2.0](https://github.com/Masterminds/sprig/releases/tag/v3.2.0) of the sprig library and isn't available in [v2.22.0](https://github.com/argoproj/argo-cd/blob/41b1ebef83b3ea9f38108bb0ca02222b067152bc/go.mod#L131)

# Proposal

I have a [branch](https://github.com/argoproj/argo-cd/compare/master...genehand:argo-cd:sprig-v3) up after running `go get github.com/Masterminds/sprig/v3` and updating the reference in `applicationset/utils/utils.go` (v2 is still used by the notifications-engine.)  If this is accepted I'm happy to open a PR!

**Comment by crenshaw-dev** [comment]
Honestly, can't believe I missed that there was a new major version.

Would love to see a PR to update. Can you check for any breaking changes or potential backwards-compatibility issues?

**Comment by genehand** [comment]
No worries, tests are running for the PR now.  Sounds like no breaking changes from [v3](https://github.com/Masterminds/sprig/releases/tag/v3.0.0) but an abundance of caution:

> Sprig v3 brings some changes while retaining the same Go API. This should enable projects to migrate to v3 with relative ease.
> You might be wondering, why increment the major version if the Go API didn't break? The reason for that is some edge case behavior changed. Most importantly the use of `^` while handling major version 0 use cases with semver. To be cautious, the major version of sprig was incremented to limit the number of surprises.
