### ISSUE TITLE
Enabling SSO on ArgoCD with OIDC Configuration using Helm Chart

### ISSUE THREAD

**Issue by rajnikhil17** [argoproj/argo-cd#11279]
### Discussed in https://github.com/argoproj/argo-cd/discussions/11222

<div type='discussions-op-text'>

<sup>Originally posted by **rajnikhil17** November  8, 2022</sup>
I am trying to enable SSO on ArgoCD.
I am trying the OIDC Way.
I was able to make things work by editing the configmap and the secret.
But, If we again do the Helm Upgrade. There is a chance that we might loss the configuration and again we have to modify the secret and configmap.
So, We want to follow the GitOps Pattern of passing the OIDC.CONFIG during the helm Upgrade.

I tried few ways of setting it.
Now, 
	`--set-file argo-cd.server.config.oidc.config="$(ARGO_CD_SSO_CONFIG_FILE)"`
If I try this way and make it template before deploying it.
We are getting the below pattern.

oidc:
   config: |
  
 But ArgoCD Expects it to be "oidc.config".
 Can anyone help me with this.</div>

**Comment by crenshaw-dev** [comment]
I think the correct syntax is something like this:

```
--set-file argo-cd.server.config."oidc\.config"="$(ARGO_CD_SSO_CONFIG_FILE)"
```

https://stackoverflow.com/questions/49522776/helm-how-to-override-value-with-periods-in-name

**Comment by jessesuen** [comment]
Proper procedure explained
