### ISSUE TITLE
Sonatype Nexus Repository connection failed

### ISSUE THREAD

**Issue by csscriptplus** [argoproj/argo-cd#11310]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I have 2 Kubernetes clusters. 1 large internal and 1 small MicroK8s in the DMZ. ArgoCD is running in both clusters. In internal cluster is running Sonatype Nexus repository. ArgoCD in internal cluster has successful repository connections. But only through Kubernetes DNS from Sonatype Nexus and port.
**Successful (internal): Deployment DNS**
`http://nexus.development:8081/repository/Demmtop-Helm-Devops`
There is no connection via the Ingress name.
**Failed (internal): Ingress Name**
`http://nexus.demmtop.local/repository/Demmtop-Helm-Devops`
Now I try to establish repository connection from DMZ to Sonatype Nexus.
**Failed (DMZ): Ingress Name**
`http://nexus.demmtop.local/repository/Demmtop-Helm-Devops`
**Failed (DMZ): Managed Node IP + Nexus NodePort**
`http://192.168.2.9:30881/repository/Demmtop-Helm-Devops`
A firewall rule for the DMZ to internal exists. A curl with the IP and port is successful. I get a response from Sonatype Nexus.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
argocd: v2.5.0+b895da4
  BuildDate: 2022-10-25T14:40:01Z
  GitCommit: b895da457791d56f01522796a8c3cd0f583d5d91
  GitTreeState: clean
  GoVersion: go1.18.7
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2022-11-16T11:05:46Z" level=warning msg="getConnectionState cache set error http://192.168.2.9:30881/repository/Demmtop-Hel │
│ m-Devops: dial tcp: lookup argocd-redis on 127.0.0.53:53: read udp 127.0.0.1:55565->127.0.0.53:53: read: connection refused" 
```

**Comment by jessesuen** [comment]
> read udp 127.0.0.1:55565->127.0.0.53:53: read: connection refused

@csscriptplus this is most certainly a problem specific to your environment and not an Argo CD bug. It appears to be trying to resolve hostnames over localhost but no server listening on port 53.
