### ISSUE TITLE
Argocd requires HPA metrics to be in a specific order

### ISSUE THREAD

**Issue by tico24** [argoproj/argo-cd#11328]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When deploying a HorizontalPodAutoscaler, argocd will throw an OutOfSync issue unless you specify your metrics in a specific order. This feels anti-declarative to me.

**To Reproduce**
I created a demo argocd app deployment here: https://github.com/tico24/argocd-hpa-issue

To install it:

```
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.2/manifests/install.yaml
kubectl apply -n argocd -f https://raw.githubusercontent.com/tico24/argocd-hpa-issue/main/hpa-app.yml
```

Argocd will show out of sync because it wants to swap the memory and cpu metrics around.

**Expected behavior**

It should not matter which order I declare my HPA metrics in.

**Screenshots**

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/45351296/202380626-744f2850-33f4-4704-b981-3ec0e33e2ec6.png">

**Version**

```shell
argocd: v2.5.2+148d8da
  BuildDate: 2022-11-07T16:42:47Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
n/a
```

**Comment by Gianluca755** [comment]
It is a known issue and nobody seems to be interested in fixing it https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/

**Comment by tico24** [comment]
Ah dang it. It's a k8s issue. Thanks.
