### ISSUE TITLE
Error with field managedNamespaceMetadata

### ISSUE THREAD

**Issue by quadrinho** [argoproj/argo-cd#11385]
Checklist:

* [X ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X] I've included steps to reproduce the bug.
* [X ] I've pasted the output of `argocd version`.   I have pasted the version of the Argo-Cd chart

**Describe the bug**
Following this documentation:

https://argo-cd.readthedocs.io/en/latest/user-guide/sync-options/#namespace-metadata

I tried to configure a managedNamespaceMetadata section:

```
managedNamespaceMetadata:
  labels:
  - cosigned.sigstore.dev/include="true"
```

I recieve this error:

**Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Application.spec.syncPolicy): unknown field "managedNamespaceMetadata" in io.argoproj.v1alpha1.Application.spec.syncPolicy**

**To Reproduce**

In our application.yaml we have this configuration:

```
  syncPolicy:
    syncOptions:
      {{- if $.Values.syncOptions }}
      {{- range $.Values.syncOptions  }}
      - {{ . }}
      {{- end }}
      {{- end }}
      {{- if .syncOptions }}
      {{- range .syncOptions  }}
      - {{ . }}
      {{- end }}
      {{- end }}
    managedNamespaceMetadata:
      {{- if $.Values.managedNamespaceMetadata }}
      {{- range $.Values.managedNamespaceMetadata  }}
      - {{ . }}
      {{- end }}
      {{- end }}
      {{- if .managedNamespaceMetadata }}
      {{- range .managedNamespaceMetadata  }}
      - {{ . }}
      {{- end }}
      {{- end }}
```

**Expected behavior**

We expected that the application will be installed in the namespace with correct Label

**Screenshots**

**Version**

Version installed is the last version released --> 5.14.1

**Logs**

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Application.spec.syncPolicy): unknown field "managedNamespaceMetadata" in io.argoproj.v1alpha1.Application.spec.syncPolicy

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
The `managedNamespaceMetadata` feature was merged, but will not be available until the 2.6 release (about 1 month from now).

**Comment by quadrinho** [comment]
hello @crenshaw-dev ,

so it means we cannot use this feature from now.

Thanks for the reply,

**Comment by crenshaw-dev** [comment]
Correct, you'll have to wait until 2.6 to use this feature.
