### ISSUE TITLE
Enable password-protected Redis by default

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#11386]
# Summary

Enable password-protected Redis by default.

# Motivation

Password-protecting Redis is [currently an undocumented feature](https://github.com/argoproj/argo-cd/issues/3130). Adding password protection provides an additional layer of security to protect cached information (e.g. rendered manifests) from unauthorized access.

# Proposal

Randomly generate a password, and store it in a Secret shared by Redis and its clients (application-controller and repo-server if I recall correctly).

**Comment by rowanmoul** [comment]
As noted in the above linked issue, this has been completed!
