### ISSUE TITLE
Exposing Application labels in events

### ISSUE THREAD

**Issue by mrysavy** [argoproj/argo-cd#11381]
# Summary

I would like to have Application labels also in argo-cd events, the same way as it is possible to have them in Prometheus metrics (see https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/#exposing-application-labels-as-prometheus-metrics)

# Motivation

Our use-case is almost the same as the one stated in the documentation for [`Exposing Application labels as Prometheus metrics`](https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/#exposing-application-labels-as-prometheus-metrics).
We have several Application labels which differentiate team (business application) and environment (dev/test/prod) and we would like to forward ArgoCD Application events (as well as container stdout) to central ELK, particular index.
Unfortunately we don't have strict naming convention for Kubernetes namespaces or ArgoCD application which we could use for the corrent messages distribution.

# Proposal

The implementation should be similar to the implementation for Prometheus metrics - specify application labels for events and use them in `event.metadata.anotations` (like `dest-namespace` and `dest-server` [here](https://github.com/argoproj/argo-cd/blob/master/util/argo/audit_logger.go#L103) and [here](https://github.com/argoproj/argo-cd/blob/a259654e32ea93b1252eaad09d4422930112b85d/util/argo/audit_logger.go#L68)).

Finaly I would like to ask if there is some workaround that can we use now.

Thanks

**Comment by mrysavy** [comment]
I would like to extend this proposal. Sometimes using Application labels may not be enough, because important labels are on the AppProject only (our another case). So I propose to allow to expose particular labels from AppProject as well.

**Comment by jannfis** [comment]
I think this would be useful. However, I have a slight concern about using both, labels from `Application` and `AppProject` here.

If both, `Application` and `AppProject` have a label with the same name, but a different value, how would we decide which one will end up on the event? Making this configurable would considerably increase the effort to be put into the change for little value add. I'd prefer it to be a one-size-fits-all solution, i.e. to just copy all labels from the Application over to the Event, minus the ones that are already defined (dest-namespace and dest-server).

**Comment by mrysavy** [comment]
I have several ideas:
- specify both AppProject labels and AppProject labels (enabled for storing in events) as different application-controller arguments ("events-application-labels" and "events-appproject-labels" for example) and fail start when both arguments contain same label
  - and similarly for metrics - metrics-application-labels / metrics-appproject-labels
- prioritize Application before AppProject and have only one argument for both labels (more precisly one argument for both Application and AppProject for event and another one for both Application and AppProject for metrics), so when Application and AppProject both of them have values for the same label - Application wins
  - so first get labels from AppProject and then get labels from Application (with override)

**I prefer second variant ("prioritize Application before AppProject")** - almost the same as you said. But I'm not sure if you count with argument for selecting labels for propagating to events. I count with it, because propagating labels to metrics is based on it.

There is also possibility to have only one argument for all combination Application/AppProject, metrics/events (and not different for metrics and events as I stated above). It doesn't matter in our case.

**Comment by jannfis** [comment]
As long as this behaviour is documented, I'd be fine with labels on the Application to override labels from the AppProject on the emitted events.

**Comment by jannfis** [comment]
I was wondering though, what ends up on the events should be _annotations_, not _labels_, right?

**Comment by mrysavy** [comment]
We count with labels.
Also current implementation of metrics exposing counts with labels (see https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/#exposing-application-labels-as-prometheus-metrics).

**Comment by svghadi** [comment]
I am working on implementing this feature and was thinking, would it make sense to have all the app & proj labels added by default without making it configurable. We already have lot of configurable params in Argo CD and making this configurable will introduce 2 more flags in app-controller and argocd-server. 
Although, I believe adding all the labels in events may not have a significant impact on performance/storage/security, I am not sure on other potential consequences.

**Comment by svghadi** [comment]
Hi @mrysavy , @jannfis, I have a PR (https://github.com/argoproj/argo-cd/pull/18160) up to implement this enhancement. I have introduced a new key in argocd-cm instead of cli flags. Configmap approach made more sense to me as we could eliminate the need of updating flag configurations in 2 places i.e app-controller and argocd-server. PTAL. Thanks.

**Comment by michalrysavy-ext95730** [comment]
Hi @svghadi, I've tried the patch and it looks good. Thanks for the implementation
