### ISSUE TITLE
New sidecar plugin does not support repositories that contain `symlinks`

### ISSUE THREAD

**Issue by cyrus-mc** [argoproj/argo-cd#11444]
**Describe the bug**

I am attempting to upgrade from 2.2.5 to 2.5.2 and moving our custom plugins to the new style `sidecar` approach. Our repositories contain some `symlinks` used to share helper code, etc.

In attempting to setup the new sidecar plugin I am receiving the following error:

```
time="2022-11-27T05:30:31Z" level=debug msg="pluginSockFilePath is: /home/argocd/cmp-server/plugins" CWE=775 security=1
time="2022-11-27T05:30:31Z" level=error msg="repository /tmp/_argocd-repo/d38cbe32-780f-4eeb-aac0-f0c8ad37e7ac/node-canary is not the match because error receiving stream response: rpc error: code = Unknown desc = match repository error receiving stream: error decompressing tgz file: illegal filepath in symlink: /tmp/_cmp_server/clone.sh" CWE=775 security=2
```

**To Reproduce**

Create an application source repo that contains `symlink` files and configure Application to use sidecar plugin. In our case the symlink is to the root of the repository.

So we have the following structure:

  /clone.sh
  /node-canary/
                         /env.yaml
                         /plugin.sh -> ./clone.sh

**Expected behavior**

I would expect ArgoCD to not care about the existence of symlinks. 

**Version**

```shell
argargoargocd@argocd-repo-server-794866bd84-nnkqb:~$ argocd version
argocd: v2.5.2+148d8da
  BuildDate: 2022-11-07T16:42:47Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
```

**Logs**

```
time="2022-11-27T05:30:32Z" level=info msg="manifest error cache miss: &ApplicationSource{RepoURL:https://github.com/xxxxx/gitops.git,Path:node-canary,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Directory:nil,Plugin:&ApplicationSourcePlugin{Name:,Env:[]*EnvEntry{&EnvEntry{Name:APPLICATION,Value:node-canary,},&EnvEntry{Name:ENVIRONMENT,Value:non-prod,},&EnvEntry{Name:DEPLOYMENT,Value:test,},&EnvEntry{Name:REGION,Value:us-west-2,},&EnvEntry{Name:AWS_ACCOUNT_ID,Value:xxxxx,},&EnvEntry{Name:DOMAIN,Value:infrastructure,},},},Chart:,}/d40ebe087d21c640de267b00194152ddf91084c6"
time="2022-11-27T05:30:32Z" level=debug msg="pluginSockFilePath is: /home/argocd/cmp-server/plugins" CWE=775 security=1
time="2022-11-27T05:30:32Z" level=error msg="repository /tmp/_argocd-repo/d38cbe32-780f-4eeb-aac0-f0c8ad37e7ac/node-canary is not the match because error receiving stream response: rpc error: code = Unknown desc = match repository error receiving stream: error decompressing tgz file: illegal filepath in symlink: /tmp/_cmp_server/clone.sh" CWE=775 security=2
```

**Comment by crenshaw-dev** [comment]
Due to a few [symlink](https://github.com/argoproj/argo-cd/security/advisories/GHSA-q4w5-4gq2-98vm)-[following](https://github.com/argoproj/argo-cd/security/advisories/GHSA-6gcg-hp2x-q54h) [vulnerabilities](https://github.com/argoproj/argo-cd/security/advisories/GHSA-63qx-x74g-jcr7), we [disabled](https://github.com/argoproj/argo-cd/issues/9738) all out-of-repo-bounds symlinks by default starting in 2.5.0.

The logs indicate that the symlink is to `../clone.sh` instead of `./clone.sh`. It's possible there's a bug, but I've not been able to reproduce it. Can you double-check the link destination?

**Comment by cyrus-mc** [comment]
I am going to close this off. I re-factored our repo layout to remove dependency on `symlinks`.
