### ISSUE TITLE
argocd applicationcontroller stops working/syncing

### ISSUE THREAD

**Issue by andreasschramm** [argoproj/argo-cd#11458]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After running for some time, application controller stops working, just sitting there and not watching/syncing objects. We can observe the goroutines within the controller dropping sharply. (see below)
This behaviour has been observed some times in the past, now is happening more frequently with growing load and number of applications, currently about 1 failure every 2 days, with ~1k apps.
(Some applications have selfheal activated with errors within the application, which creates high load, but that will need some more investigation.)

Last occurence was accompanied by a slew of messages like:
`retrywatcher.go:130] "Watch failed" err="Get \"https://yadda/apis/apps/v1/namespaces/NAMESPACE_HERE/RESOURCE_NAME_HERE/?allowWatchBookmarks=true&resourceVersion=5645476686&watch=true\": context canceled"`

This seems to indicate that these watchers error out, but are not restarted again. This could explain the observed drop in goroutines.

Other argocd instance was not affected, so cluster api issues can be excluded.

**To Reproduce**
difficult, heisenbug.

run an argocd instance, watch 1k partially broken apps with self heal, wait 2 days.

**Expected behavior**

When an watchers stop, they should be restarted, or the livenessprobe should fail, so that controller can be restarted by cluster.

**Screenshots**

![image](https://user-images.githubusercontent.com/16651411/204229004-e4b12a31-8b26-499c-9484-d3ae594cd8dd.png)
**Version**

```shell
Paste the output from `argocd version` here.
```
$ argocd version
argocd: v2.4.11+3d9e9f2
  BuildDate: 2022-08-22T09:13:16Z
  GitCommit: 3d9e9f2f95b7801b90377ecfc4073e5f0f07205b
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified  

**Logs**
1000's of:

```
retrywatcher.go:130] "Watch failed" err="Get \"https://yadda/apis/apps/v1/namespaces/NAMESPACE_HERE/RESOURCE_NAME_HERE/?allowWatchBookmarks=true&resourceVersion=5645476686&watch=true\": context canceled"
```

**Comment by jmmclean** [comment]
I encountered this same issue (2nd time). I thought the first time was bc of resource starvation, so I implemented CPU requests at 2 cores. This did NOT help the issue...it just seems like that application controller dies at some point. To fix the issue I had to do a rolling restart of the stateful and things were fine.

We are only managing around 220 applications with this argo instance.

```
argocd-server: v2.5.4+86b2dde
  BuildDate: 2022-12-06T19:46:25Z
  GitCommit: 86b2dde8e4bf1187acd2b4294e94451cd104dad8
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```
![image](https://user-images.githubusercontent.com/16881666/220913418-c31bd464-2839-4204-9fd7-f93adc196a62.png)


![image](https://user-images.githubusercontent.com/16881666/220911462-68b41478-2905-4e44-b128-565b9c4f0279.png)

**Comment by d-wierdsma** [comment]
Just experienced the same issue, around 120 applications, application-controller stopped processing changes completely.

```
argocd version
argocd: v2.6.1+3f143c9
  BuildDate: 2023-02-08T18:51:05Z
  GitCommit: 3f143c9307f99a61bf7049a2b1c7194699a7c21b
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  ```
  
  Similarly to others, I was able to manually restart the application controller and did not experience anymore issues afterwards.
  
![image](https://user-images.githubusercontent.com/13317139/225636179-e281d753-5ebc-4e95-89cd-764e1c716f65.png)

Just before this started for me I saw issues in the application-controller logs like this:

```
2023-03-15 13:33:28	W0315 17:33:28.173842       1 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
2023-03-15 13:33:27	W0315 17:33:27.868821       1 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
2023-03-15 13:33:27	W0315 17:33:27.866049       1 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
2023-03-15 13:32:58	{"level":"info","msg":"warning loading openapi schema: %s","server":"<EKS_CLUSTER_API_URL>","time":"2023-03-15T17:32:58Z"}
2023-03-15 13:32:56	{"level":"info","msg":"warning loading openapi schema: %s","server":"<EKS_CLUSTER_API_URL>","time":"2023-03-15T17:32:56Z"}
2023-03-15 13:32:54	I0315 17:32:54.880850       1 request.go:601] Waited for 1.015990162s due to client-side throttling, not priority and fairness, request: GET:<EKS_CLUSTER_API_URL>/apis/apigateway.aws.upbound.io/v1beta1?timeout=32s
2023-03-15 13:31:58	{"level":"info","msg":"warning loading openapi schema: %s","server":"<EKS_CLUSTER_API_URL>","time":"2023-03-15T17:31:58Z"}
2023-03-15 13:31:56	{"level":"info","msg":"warning loading openapi schema: %s","server":"<EKS_CLUSTER_API_URL>","time":"2023-03-15T17:31:56Z"}
```

**Comment by Unfaced85** [comment]
We have the Same issues, ArgoCD running on OKD 4.11

`argocd: v2.4.8+844f79e
  BuildDate: 2022-07-29T17:01:39Z
  GitCommit: 844f79eb9d8f3ab96d4ce6f8df211c6093a660ba
  GitTreeState: clean
  GoVersion: go1.18.4
  Compiler: gc
  Platform: linux/amd64`

Logs are the same as previous comments

**Comment by d-wierdsma** [comment]
My set-up manages around 5 different clusters at the moment, with more incoming.

**Comment by robmonct** [comment]
We are also affected. We are running ArgoCD 2.6.7 into a GKE cluster

**Comment by leoluz** [comment]
This issue was discussed in the last contributor's meeting and @jaideepr97 will bring it to sig-scalibility group.

**Comment by jsoref** [comment]
Good, because we just tripped on it and I was going to start asking folks about it...

**Comment by ericblackburn** [comment]
**Application Controller Disconnects From All Clusters**

We manage multiple clusters. We often see the Application Controller disconnect from all clusters it was managing when one of the clusters it was managing is removed from Argo.  We are working on producing this in a lab, so we can provide more details. 

A simple restart of that Application Controller fixes this scenario 

**Bad Argo Apps Slow Argo to a crawl**

Another scenario we want to reliably prove in a lab is a case where an Argo App gets into such a bad state, I think it can't talk to the cluster that was removed and it has other major issues like a missing App Project, that it slows the entire Argo instance to a crawl (doesn't stop it, but slows it by 95%) for all Application Controllers, not just the one that was supposed to support the removed cluster. When I open up the Argo App, I see a flurry of red error boxes that go in and out of existence faster than can be red.  It is a lot. I wonder if this case has to do with the Argo Server instead of App Controller, because of it affecting all Application Controllers equally.

In this case, you can't restart your way out of this. You have to find the offending Argo App and remove it.

**Comment by crenshaw-dev** [comment]
@alexmt can we cherry-pick the gitops-engine upgrade at least to 2.7 to fix this?

**Comment by alexmt** [comment]
Reopening since I found an almost identical bug that also causes deadlock. Creating PR with the fix in few minutes

**Comment by marcusnh** [comment]
Experienced same problem with ArgoCD version 2.9.5:
<img width="1403" alt="image" src="https://github.com/argoproj/argo-cd/assets/44726949/27410328-35e4-4bc2-bc5c-6bb1efad38f9">
Is there a fix to avoid this problem in the future?

**Comment by LeifSchumi** [comment]
Experienced same problem with OpenShift GitOps Operator v1.11.1 running ArgoCD version 2.9.5. We run into this error on a daily bases. After restarting the application controller ArgoCD works fine for some time before it crashes again.

**Comment by ibbw** [comment]
Same problem with ArgoCD version v2.10.5+335875d, can we please reopen this issue?

**Comment by jsoref** [comment]
I'd rather someone file a new issue and link to this. It's a really bad strategy to constantly resurrect generic issues when there are distinct causes for each case.

Otherwise, most software projects would only need a handful of issues:
* Program Crashes
* Program is Slow
* Program is Ugly
* Program is Buggy
