### ISSUE TITLE
Environment styling

### ISSUE THREAD

**Issue by barryoneill** [argoproj/argo-cd#1148]
It would be really nice if the UI has some configuration options offering some rudimentary style overrides, to make it clearer to a user who may have access to dev _and_ production argocd deployments.  

Eg, for production, some text could be added to the header, and perhaps some colors could be overridden:
![screen shot 2019-02-20 at 3 13 44 pm](https://user-images.githubusercontent.com/885049/53101762-4e47cf80-3522-11e9-9ad6-b4125bac40cd.png)

**Comment by barryoneill** [comment]
Pinging to keep alive, in the case I get a chance to contribute this fix.

**Comment by alexec** [comment]
If you'd like to contribute, this should help you:

https://argoproj.github.io/argo-cd/developer-guide/

**Comment by AndiDog** [comment]
How fine-grained should the customization be? My first idea would be to override the `page` element's background, e.g. using a transparent PNG. Here's a contrived example:

![Argo CD background customization](https://user-images.githubusercontent.com/1376043/61948959-91164380-afa9-11e9-9a4c-a9bc0a90c62a.png)

That could read "production" or "dev".

Configuration-wise, this could be done with a new parameter like `argocd-server [default params like --staticassets /shared/app ...] --extracss /my/mounted/config/map/files/style-production.css` and users configure the CSS files inside a config map (1MB limit should suffice).

**Comment by christianh814** [comment]
You should be able to do this now with [custom styles](https://argo-cd.readthedocs.io/en/stable/operator-manual/custom-styles/). Closing.
