### ISSUE TITLE
Add mastodon as new notification channel

### ISSUE THREAD

**Issue by developer-guy** [argoproj/argo-cd#11499]
# Summary

[Mastodon](https://joinmastodon.org) is free and open-source software for running self-hosted social networking services. 

# Motivation

Mastodon will become one of the leading social networks in the industry. So, there is considerable interest in moving out from Twitter to Mastodon these days. 

# Proposal

There is a Go SDK of the Mastodon API[^1], so we can add Mastodon as a new notification channel.

Similar work has been done in the GoReleaser project[^2].

[^1]: https://github.com/mattn/go-mastodon
[^2]: https://github.com/goreleaser/goreleaser/pull/3567

/cc @dentrax

**Comment by alexef** [comment]
I believe this issue belongs to this project instead: https://github.com/argoproj/notifications-engine

**Comment by developer-guy** [comment]
Sorry, I'm going to open it in the right repository, let me close this one, thx.
