### ISSUE TITLE
the button on remove override does not work

### ISSUE THREAD

**Issue by Iceforestik** [argoproj/argo-cd#11506]
the steps are pretty standard, I go in and change the parameters in applications, then I want to press the remove override button, but it doesn't work

for example, I want to erase the image tag line with this button, I fall into edit and I try to press the button , but it doesn 't respond
![изображение](https://user-images.githubusercontent.com/47591939/204843759-d2e6864b-fbbb-4162-92e8-84bf1343d250.png)
![изображение](https://user-images.githubusercontent.com/47591939/204844120-ca6ea307-9e1d-4487-bca2-aa9847459c1b.png)
there is no error in the developer console in browsers

**Comment by crenshaw-dev** [comment]
I've cherry-picked back the fix. It will be released with 2.5.4 (some time in the next few days).
