### ISSUE TITLE
UI redirect issue from mother app to child app view

### ISSUE THREAD

**Issue by mikeeq** [argoproj/argo-cd#11518]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using the new feature of deploying application objects in different namespaces than `argocd` one, the URL for application consists of: 
`https://{{ argocd_server_url }}/applications/{{ application_namespace }}/{{ application_name }}`
i.e.: 
`https://argocd.test.com/applications/test-namespace/app-name?view=tree&orphaned=false&resource=`
and when you're in the UI view of the application which contains other applications there is an icon which redirects you to the child app and when you click on it the namespace is missing in the URL and 403 is returned.

**To Reproduce**

Following application objects should be deployed in other namespace than ArgoCD

(mother application - application which contains other application objects)

1. Open mother application view in the UI
2. Click on the redirect icon in the child app box
3. Get HTTP 403 response - user was redirected to wrong URL (with missing namespace in it)

**Expected behavior**

User should be redirected correctly to the child app view.

**Screenshots**

![mother_app_view](https://user-images.githubusercontent.com/15999352/205039627-209b56b8-2baa-4ee0-a3d6-172a13797cf2.jpg)
![icon](https://user-images.githubusercontent.com/15999352/205039672-94534ad4-1dd5-4b34-bf17-e2b13f487aa5.jpg)
![url_issue](https://user-images.githubusercontent.com/15999352/205039705-96eb757e-e751-4a46-898d-a5c6568149e9.jpg)
![child_app_view_network](https://user-images.githubusercontent.com/15999352/205039729-e14612a8-55c8-4648-8c18-e93ccc373a22.jpg)
![child_app_view_console](https://user-images.githubusercontent.com/15999352/205039736-284ec385-8a00-4157-aa9a-4b2ba34c2bde.jpg)
### How it should look like
![how_url_should_look_like](https://user-images.githubusercontent.com/15999352/205040650-387ca2cf-2d9b-49c4-a090-258ab3e9a5e3.jpg)

**Version**

```shell
argocd-server: v2.5.3+0c7de21
  BuildDate: 2022-11-28T16:51:33Z
  GitCommit: 0c7de210ae66bf631cc4f27ee1b5cdc0d04c1c96
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**

```
argocd-server-6f7dd94458-zqxpk server time="2022-12-01T11:22:11Z" level=info msg="received unary call /application.ApplicationService/ManagedResources" grpc.method=ManagedResources grpc.request.claims="{\"aio\":\"AVQAq/8TAAAAHFIdDt1xu/2pdKaoNIz3bkv8LMYNiNE0ST5AsR87TXj9qrjvCaOZ2IApiAP7JEctbKtxgB4speVPxdR4mZZof/MowjxZK61+Ei2w1GovNV8=\",\"aud\":\"e9d41d8f-6f08-420e-a3ee-2cd6bd4611bc\",\"exp\":1669895401,\"iat\":1669891501,\"iss\":\"https://login.microsoftonline.com/adf10e2b-b6e9-41d6-be2f-c12bb566019c/v2.0\",\"name\":\"Admin\",\"nbf\":1669891501,\"oid\":\"79a2a4c7-5466-485e-8418-7d20d58e5ff0\",\"preferred_username\":\"ADM\",\"rh\":\"0.AQIAKw7xrem21kG-L8ErtWYBnI8d1OkIbw5Co-4s1r1GEbwCAK4.\",\"sub\":\"mCcqp19_aPRsjpDNvroDcq_JbOgD5X6ZqLurU-T2n6Q\",\"tid\":\"adf10e2b-b6e9-41d6-be2f-c12bb566019c\",\"uti\":\"3EwF-29GsEWfdxkMc-crAA\",\"ver\":\"2.0\"}" grpc.request.content="applicationName:\"tenant2-app-of-apps-nonprod001\" namespace:\"management-tenant2\" name:\"standard-workload-nonprod001\" group:\"argoproj.io\" kind:\"Application\" appNamespace:\"management-tenant2\" " grpc.service=application.ApplicationService grpc.start_time="2022-12-01T11:22:11Z" span.kind=server system=grpc
argocd-server-6f7dd94458-dtvdb server time="2022-12-01T11:22:11Z" level=info msg="received unary call /application.ApplicationService/GetResource" grpc.method=GetResource grpc.request.claims="{\"aio\":\"AVQAq/8TAAAAHFIdDt1xu/2pdKaoNIz3bkv8LMYNiNE0ST5AsR87TXj9qrjvCaOZ2IApiAP7JEctbKtxgB4speVPxdR4mZZof/MowjxZK61+Ei2w1GovNV8=\",\"aud\":\"e9d41d8f-6f08-420e-a3ee-2cd6bd4611bc\",\"exp\":1669895401,\"iat\":1669891501,\"iss\":\"https://login.microsoftonline.com/adf10e2b-b6e9-41d6-be2f-c12bb566019c/v2.0\",\"name\":\"Admin\",\"nbf\":1669891501,\"oid\":\"79a2a4c7-5466-485e-8418-7d20d58e5ff0\",\"preferred_username\":\"ADM\",\"rh\":\"0.AQIAKw7xrem21kG-L8ErtWYBnI8d1OkIbw5Co-4s1r1GEbwCAK4.\",\"sub\":\"mCcqp19_aPRsjpDNvroDcq_JbOgD5X6ZqLurU-T2n6Q\",\"tid\":\"adf10e2b-b6e9-41d6-be2f-c12bb566019c\",\"uti\":\"3EwF-29GsEWfdxkMc-crAA\",\"ver\":\"2.0\"}" grpc.request.content="name:\"tenant2-app-of-apps-nonprod001\" namespace:\"management-tenant2\" resourceName:\"standard-workload-nonprod001\" version:\"v1alpha1\" group:\"argoproj.io\" kind:\"Application\" appNamespace:\"management-tenant2\" " grpc.service=application.ApplicationService grpc.start_time="2022-12-01T11:22:11Z" span.kind=server system=grpc
```

**Comment by mikeeq** [comment]
FYI @alexef @rbreeze @crenshaw-dev

**Comment by ohauer** [comment]
Found some additional places where the URL should be adjusted.

PS: Thanks for implementing this feature!

![02_application](https://user-images.githubusercontent.com/789018/214091564-f3844a7b-7bef-4394-93d1-856b208c0374.png)

![03_application](https://user-images.githubusercontent.com/789018/214092336-0b3f03d8-a824-4159-ac5f-1d70123008be.png)
