### ISSUE TITLE
Error "authentication required " while adding a new repo(Github Org)

### ISSUE THREAD

**Issue by vivekyad4v** [argoproj/argo-cd#11517]
Seems like a weird issue, not sure what am i missing. Please suggest. I tried creating repo with CLI, Declarative & UI, all are throwing same error. Seems to be working fine with public repos. 

Find the details below - 

Kube - 
```
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.23.13-eks-fb459a0
```
ArgoCD - 
```
CLI - v2.5.3
Server - v 2.5.3
Ref - https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.3/manifests/ha/install.yaml
```

CLI run - `argocd repo add https://github.com/org-in/core-repo --username "vivekxxx" --password "vivekxxxxx` 

Error - `FATA[0001] rpc error: code = Unknown desc = error testing repository connectivity: authentication required `

PS - It would be a silly one i believe.

**Comment by usernameisnull** [comment]
use username and password for authentication is impossible:
https://docs.github.com/en/rest/overview/troubleshooting?apiVersion=2022-11-28#basic-authentication-errors

**Comment by vivekyad4v** [comment]
Thanks for pointing that out. I guess in that case, it should be removed from the ArgoCD docs too.
