### ISSUE TITLE
Add Support for promote for rollout objects

### ISSUE THREAD

**Issue by zachaller** [argoproj/argo-cd#11528]
# Summary

Currently ArgoCD only supports promote-full for rollouts actions, we should also allow just the promotion of a single step.

Logic for how promo works found https://github.com/argoproj/argo-rollouts/blob/master/pkg/kubectl-argo-rollouts/cmd/promote/promote.go

**Comment by kaiquerass** [comment]
any updates on this issue?

**Comment by Aym3nTN** [comment]
@crenshaw-dev is similar to how this https://github.com/argoproj/argo-cd/pull/4777 has added 'promote-full' action?

**Comment by zachaller** [comment]
Closing this as it is already supported there is just a naming change, argocd calls it resume, https://github.com/argoproj/argo-cd/blob/master/resource_customizations/argoproj.io/Rollout/actions/resume/action.lua
