### ISSUE TITLE
Error upgrading ArgoCD to latest version

### ISSUE THREAD

**Issue by yas-khan** [argoproj/argo-cd#11527]
Trying to upgrade ArgoCD to latest version. currently at 5.2.1. Want to upgrade to 5.14.3. Is there  way to jump to latest version?

**Error: 1**

helm upgrade --install argo-cd argo/argo-cd --version 5.5.0 --reuse-values --namespace argo-cd

Error: UPGRADE FAILED: template: argo-cd/templates/dex/deployment.yaml:15:32: executing "argo-cd/templates/dex/deployment.yaml" at <include (print $.Template.BasePath "/a
rgocd-configs/argocd-cmd-params-cm.yaml") .>: error calling include: template: argo-cd/templates/argocd-configs/argocd-cmd-params-cm.yaml:7:16: executing "argo-cd/templat
es/argocd-configs/argocd-cmd-params-cm.yaml" at <.Values.configs.params.annotations>: nil pointer evaluating interface {}.annotations

**Error 2**
helm upgrade --install argo-cd argo/argo-cd --version 5.4.0 --reuse-values --namespace argo-cd
Error: UPGRADE FAILED: template: argo-cd/templates/argocd-server/deployment.yaml:54:27: executing "argo-cd/templates/argocd-server/deployment.yaml" at <.Values.global.log
ging.format>: nil pointer evaluating interface {}.format

**Error 3**
helm upgrade --install argo-cd argo/argo-cd --version 5.2.2 --reuse-values --namespace argo-cd
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: Secret "argocd-notifications-secret" in namespace "argo-
cd" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to
 "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "argo-cd"; annotation validation error: missing key "meta.helm.sh/release-na
mespace": must be set to "argo-cd"

**Comment by yas-khan** [comment]
Anyone faced this issue?

**Comment by crenshaw-dev** [comment]
I think https://github.com/argoproj/argo-helm is the better venue for this question.

**Comment by sondrelg** [comment]
Yep, seems related to this change: https://artifacthub.io/packages/helm/argo/argo-cd/5.2.2?modal=changelog&version=5.2.2

> [Changed]: Move notification configs to config folder

**Comment by sondrelg** [comment]
This fixed it for me :slightly_smiling_face: 

```
kubectl label cm argocd-notifications-cm app.kubernetes.io/managed-by=Helm -n argocd \
  && kubectl label cm argocd-notifications-cm meta.helm.sh/release-name=argo-cd \
  && kubectl label cm argocd-notifications-cm meta.helm.sh/release-namespace=argocd
```
