### ISSUE TITLE
Application Helm Parameters/Values/ValueFiles Precedence Documentation Unclear

### ISSUE THREAD

**Issue by LaikaN57** [argoproj/argo-cd#11529]
The ArgoCD Application docs are unclear on the precedence of the following keys in `spec.source.helm`:
- `parameters`
- `values`
- `valuesFiles`

https://github.com/argoproj/argo-cd/blob/f9f27cc6444f0fa57978b6359a14aa64a8ef9d4a/docs/operator-manual/application.yaml#L28-L62

It is pretty clear about how the `parameters` override all other options (see https://github.com/argoproj/argo-cd/blob/f9f27cc6444f0fa57978b6359a14aa64a8ef9d4a/docs/operator-manual/application.yaml#L27), however the other two are a unclear. Additionally, because `valuesFiles` is a list, what order do these take precedence?

I am willing to help make the doc fixes, if someone can assist in finding the evidence/authoritative info for how this works.

Thanks in advance for any assistance here.

**Comment by alexef** [comment]
hi @LaikaN57 !

According to the only place values are passed in order - [`helm template` call, the order is:](https://github.com/argoproj/argo-cd/blob/master/reposerver/repository/repository.go#L855-L903)
- valuesFiles - list of files/remote addresses
- values (as literal)
- parameters as key values
- parameters as files

**Comment by LaikaN57** [comment]
@alexef Perfect! This is exactly what I needed. I will draft a doc fix next week and then close out this issue.

**Comment by blakepettersson** [comment]
This should have been fixed with #15755
