### ISSUE TITLE
Need to set HELM_PLUGIN for helm plugin support

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1153]
Even if a user customizes their repo server through a custom Dockerfile, they will not benefit from installing helm plugins, because we create a temporary, throwaway HELM_HOME whenever we run `helm template`. In order to support plugins, we should set HELM_PLUGIN to `/home/argocd/.helm/plugins` so that HELM_HOME can be a temp directory, and HELM_PLUGIN will be the customized location.

One approach might be to just change the Dockerfile to have the HELM_PLUGIN set to `home/argocd/.helm/plugins` and we inherit these environment variables when running `helm template`.

Another approach is to just set the HELM_PLUGIN environment variable for all fork/execs.

**Comment by jessesuen** [comment]
> because we create a temporary, throwaway HELM_HOME whenever we run `helm template`

In case anyone is wondering why we do this, this is because Argo CD helm repository list dynamic, and the full list is supplied on-request for each GetManifests call. This allows the repo server to run without K8s service account & token. So if the repo-server is compromised (which will be more possible with custom templating), at least it cannot talk to the K8s API server.

Here is helm docs on it's env vars:
https://github.com/helm/helm/blob/master/docs/plugins.md#environment-variables

**Comment by alexec** [comment]
https://github.com/argoproj/argo-cd/issues/1105

**Comment by jessesuen** [comment]
Should be now possible to do this with fix in https://github.com/argoproj/argo-cd/pull/1306. Requires a custom repo server which sets HELM_PLUGIN environment variable.
