### ISSUE TITLE
kubectl explain Application.spec shows empty

### ISSUE THREAD

**Issue by binchenX** [argoproj/argo-cd#11536]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

```
kubctl explain Application.spec
KIND:     Application
VERSION:  argoproj.io/v1alpha1

DESCRIPTION:
     <empty>
 ```

**Expected behavior**

kubectl explain Application.spec should show the specification.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by r0bj** [comment]
I have the same issue on argocd which was upgraded over many versions.
