### ISSUE TITLE
Application in namespace is not permitted to use project

### ISSUE THREAD

**Issue by sebolabs** [argoproj/argo-cd#11597]
**Describe the bug**
_First of all, I'm not explicitly saying it's a bug.
I did my best, read the docs, and tried to ask on forums but received no help hence I'm raising this issue.
I might be simply missing something and can't figure it out._

I've been trying to deploy an app to a namespace called `test-hello-world` within my custom project `project-test`.

In the `argocd-cmd-params-cm` ConfigMap I've got this:
```json
{
    "apiVersion": "v1",
    "data": {
        "application.namespaces": "test-*",

```

For the project I've got the following configured with wildcards (*):
- source repos
- destinations
- cluster resource allow list
- namespace resource allow list

It's not working!
And I'm getting the following error message:
```
application 'test-hello-world' in namespace 'test-hello-world' is not permitted to use project 'project-test'
```

Note: when I change the namespace to `argocd` it works, obviously.

**To Reproduce**

See above.

**Expected behavior**

The app should be successfully deployed.

**Screenshots**

N/A

**Version**

```shell
v2.5.3+0c7de21
```

**Logs**

N/A

**Comment by crenshaw-dev** [comment]
I think you need to add this to the `project-test` AppProject:

```yaml
sourceNamespaces:
- test-*
```

**Comment by sebolabs** [comment]
LOL, yet another hidden configuration option for _admins_ only - invisible from the UI.

**It worked!** Thank you! It's not over yet though :) 

Here's what I've got:
A top level app: `my-app` - URL path: `/applications/argocd/my-app` with a nested app: `test-hello-world`.
When I click the `Open application` link on the `test-hello-world` application tile it takes me to the following URL path: `/applications/test-hello-world`, and I'm getting the following error:
```
Unable to load data: error getting application: applications.argoproj.io "test-hello-world" not found
```
That's because that app belongs to the `test-hello-world` namespace so the correct URL path should be `/applications/test-hello-world/test-hello-world`.

**Comment by crenshaw-dev** [comment]
> yet another hidden configuration option for admins only - invisible from the UI.

Well, every configuration option in AppProject is admin-only, because AppProject update access effectively == admin access. Lack of UI support is its own problem. :-)

> That's because that app belongs to the test-hello-world namespace so the correct URL path should be /applications/test-hello-world/test-hello-world

Yep, that's a known issue, being tracked [here](https://github.com/argoproj/argo-cd/issues/11166#issuecomment-1302118205).

**Comment by sebolabs** [comment]
Alright, I get that :)

I'm glad the _Open application_ issue is known and looking forward to getting it resolved soon.
Closing this one here. Thanks again for your help!!

**Comment by kopax-polyconseil** [comment]
I use default AppProject, and I have this error also. do you know how to solve it ?
