### ISSUE TITLE
Add resource hook weighting

### ISSUE THREAD

**Issue by nxc933** [argoproj/argo-cd#11592]
# Summary

It would be useful to provide an order for when hooks should run that run during the same stage. Helm hooks support this, and it would be great to see this implement in a similar manner to how helm has implemented the feature.

# Motivation

Often I want to run database migrations after a sync has completed, as well as run some sort of integration tests. Often, these integration tests would be dependent on the database migrations being completed, but as current there is no good way to enforce a dependency between the two.

# Proposal

Likely this could be implemented by adding an additional annotation to the hook resource, `argocd.argoproj.io/hook-weight`. This value should be either a positive or negative integer, and argo should then run hooks which share the same `argocd.argoproj.io/hook` in ascending order of their weights.

**Comment by kostis-codefresh** [comment]
@nxc933 Sync waves do exactly what you want https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/#how-do-i-configure-waves

Did you have an issue with them?

**Comment by crenshaw-dev** [comment]
Closing for now. Feel free to reopen if we need to turn this into a docs PR or if sync waves don't do the job.
