### ISSUE TITLE
Unknown sync operation state on app list page

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#11599]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Application list page incorrectly displays `unknown` sync operation  state

**To Reproduce**

* Create any application and sync it once
* Navigate to application list page

**Expected behavior**

Correct sync operation state should be shown 

**Screenshots**

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/426437/206315095-509262e0-83e5-4732-8890-95d7006391c1.png">

**Version**

```shell
v2.6.0 unreleased
```

**Comment by ashutosh16** [comment]
I suspect the issue is coming after this commit https://github.com/argoproj/argo-cd/commit/9bd0ed0d5601f6408ef822b282841464d9784a27

**Comment by alexef** [comment]
I concur. Seems like the problem is that application.operation is always set, some times to an empty object. The front end logic trips out, and assumes that some operation is ongoing. This can probably be solved without changing the backend.

**Comment by alexmt** [comment]
Yeah, I think https://github.com/argoproj/argo-cd/commit/9bd0ed0d5601f6408ef822b282841464d9784a27 broke it. Let me fix it please since I introduced the bug
