### ISSUE TITLE
[UI] Non-Obvious OutOfSync resource due to pruning

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1159]
When a resource is OutOfSync because it needs to be pruned, the resource details is not-obvious because the diff does not show anything.

**Comment by jessesuen** [comment]
This is fixed with new diff view.

**Comment by alexmt** [comment]
I think UI still needs to be improved. I've got confused several times if the resource is missing or present and have to be pruned. Reopening it to add an explicit indicator (icon or text).
