### ISSUE TITLE
ui: cluster server url label overlaps

### ISSUE THREAD

**Issue by ashutosh16** [argoproj/argo-cd#11600]
When the Cluster Server URL is long, it overlaps. 
The server URL information is redundant. There are multiple places on the cluster web page where this information can be found. We can remove the label on the right or wrap the server URL when it is too long.
![Screen Shot 2022-12-07 at 2 49 14 PM](https://user-images.githubusercontent.com/11219262/206314022-dc92f27b-932e-4c54-9949-79c2a0b9f70a.png)

**Comment by jiwonaid** [comment]
Hi team,
May I take this as my `good first issue`?

cc. @saumeya

**Comment by saumeya** [comment]
Go ahead @jiwonaid
