### ISSUE TITLE
[UI] Deleting an application child resource from a parent application deletes the parent

### ISSUE THREAD

**Issue by conorfennell** [argoproj/argo-cd#1160]
In the screenshot below I am selecting to delete the child application argocd. 
![child-application](https://user-images.githubusercontent.com/520376/53246837-ab21c200-36a9-11e9-9ae3-f949026ef477.png)

When the delete box pops up you can see it is actually going to delete the argocd-bootstrap application which is its parent.
![parent-delete](https://user-images.githubusercontent.com/520376/53246944-f340e480-36a9-11e9-857b-16e2e1cbe5a7.png)

This only happens with application resources.

**Comment by alexmt** [comment]
Thanks for catching it! Fixed by https://github.com/argoproj/argo-cd-ui/commit/98caad1ff707ff4581bbd1b734648f88e79244da
