### ISSUE TITLE
Resource details panel does not work

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#11601]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Resouce details panel does not work anymore

**To Reproduce**

* Navigate to any app any try to click on any resource
* Details panel expanded and disappears in the loop

**Expected behavior**

Panel should show resource details

**Screenshots**

https://user-images.githubusercontent.com/426437/206320010-0d931917-9c07-4942-a8ea-c85e25c71943.mov

**Version**

```shell
v2.6.0 ( unreleased )
```

**Comment by crenshaw-dev** [comment]
I suspect it's one of the recent JS dependency upgrades. It's not https://github.com/argoproj/argo-cd/pull/11533, because that was cherry-picked to 2.5, and 2.5 doesn't have the bug.

**Comment by alexef** [comment]
<img width="1503" alt="Screenshot 2022-12-08 at 02 09 26" src="https://user-images.githubusercontent.com/346576/206331449-77fc3426-ceae-46d4-a82e-d00996cd9357.png">
seems to happen while the monaco editor is loading

**Comment by divyanjali1** [comment]
I am facing same issue in our EKS cluster 
argocd version : v2.5.0+661afe0
argocd version : v2.5.0+9839564
and I am facing this issue also #11599 

any resolution ?

**Comment by crenshaw-dev** [comment]
@divyanjali1 those are both development builds off the master branch. If you're running those in prod, I'd recommend moving to a tagged release like 2.5.4.

**Comment by ashutosh16** [comment]
error from console.log
```
The above error occurred in one of your React components:
    in Unknown (created by MonacoEditor)
    in Suspense (created by MonacoEditor)
    in MonacoEditor (created by YamlEditor)
    in div (created by YamlEditor)
    in YamlEditor (created by DataLoader)
    in DataLoader (created by ApplicationNodeInfo)
    in div (created by Tabs)
    in div (created by Tabs)
    in Tabs (created by DataLoader)
    in DataLoader (created by ApplicationNodeInfo)
    in div (created by ApplicationNodeInfo)
    in div (created by ApplicationNodeInfo)
    in ApplicationNodeInfo (created by DataLoader)
    in div (created by Tabs)
    in div (created by Tabs)
    in Tabs (created by DataLoader)
    in DataLoader (created by ResourceDetails)
    in div (created by ResourceDetails)
    in ResourceDetails (created by DataLoader)
    in div (created by RenderSlidingPanel)
    in div (created by RenderSlidingPanel)
    in div (created by RenderSlidingPanel)
    in RenderSlidingPanel (created by SlidingPanel)
    in KeybindingProvider (created by SlidingPanel)
    in SlidingPanel (created by DataLoader)
    in div (created by Page)
    in div (created by Page)
    in Page (created by DataLoader)
    in div (created by DataLoader)
    in DataLoader (created by Page)
    in Page (created by DataLoader)
    in div (created by DataLoader)
    in DataLoader (created by ObservableQuery)
    in ObservableQuery (created by ApplicationDetails)
    in ApplicationDetails (created by Route2)
    in Route2 (created by ApplicationsContainer)
    in Switch2 (created by ApplicationsContainer)
    in ApplicationsContainer (created by DataLoader)
    in DataLoader (created by Banner)
    in Banner (created by DataLoader)
    in div (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by DataLoader)
    in DataLoader (created by Route2)
    in Route2 (created by App)
    in Switch2 (created by App)
    in Router2 (created by App)
    in App
```
