### ISSUE TITLE
could not add an oci repo

### ISSUE THREAD

**Issue by Codecaver** [argoproj/argo-cd#11612]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**
could not add an oci repo

**Expected behavior**
add an oci repo

**Screenshots**
![image](https://user-images.githubusercontent.com/51467533/206427761-a0f5dd16-e43e-4b50-969f-34d6a7350468.png)

**Version**
```shell
v2.5.2
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexef** [comment]
1. have you tried the CLI? 

```
argocd repo add xxx.dkr.ecr.eu-central-1.amazonaws.com --type helm --name ecr --enable-oci --username AWS --password xxx
``` 
works for me
2. make sure you remove the oci:// prefix (and not add https://) either

**Comment by Codecaver** [comment]
> 1. have you tried the CLI?
> 
> ```
> argocd repo add xxx.dkr.ecr.eu-central-1.amazonaws.com --type helm --name ecr --enable-oci --username AWS --password xxx
> ```
> 
> works for me 2. make sure you remove the oci:// prefix (and not add https://) either


 I have tried the CLI, but it seems something wrong
```
argocd@argo-cd-argocd-server-5ff5976fc4-6pbvf:~$ argocd repo add ghcr.io/eshepelyuk/helm/cmak-operator --type helm --name cmak --enable-oci
FATA[0000] Argo CD server address unspecified
```

**Comment by fengshunli** [comment]
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/18587688/206960802-b38e397b-416b-4f8f-b8a4-244dd5074222.png">
@Codecaver no problem

**Comment by blakepettersson** [comment]
This seems to have been resolved, feel free to reopen if that's not the case.
