### ISSUE TITLE
"Deny sources" for Projects 

### ISSUE THREAD

**Issue by blakepettersson** [argoproj/argo-cd#11639]
# Summary

Now that we have "deny destinations" on Projects (#9652), it would be natural for this to be extended to application sources as well.

# Motivation

We have a use case where we have a quite restricted `AppProject`, which only has a restricted number of repos and destinations which it is allowed to use. The dual of this is that we have a more liberal `AppProject` where we now use deny destinations, but it'd also be nice to add restrictions on which repos are _not_ allowed to be used. 

# Proposal

In order to be consistent with the deny destinations feature, we'd also allow sources to be prefixed with `!`, which would negate the source value if it has been matched. The implementation would pretty much look like this:

```go
func (proj AppProject) IsSourcePermitted(src ApplicationSource) bool {
	srcNormalized := git.NormalizeGitURL(src.RepoURL)

	var normalized string
	anySourceMatched := false
	noDenySourcesMatched := true

	for _, repoURL := range proj.Spec.SourceRepos {
		if isDenyPattern(repoURL) {
			normalized = "!" + git.NormalizeGitURL(strings.TrimPrefix("!", repoURL))
		} else {
			normalized = git.NormalizeGitURL(repoURL)
		}

		matched := globMatch(normalized, srcNormalized, true, '/')
		if matched {
			anySourceMatched = true
		} else if !matched && isDenyPattern(normalized) {
			noDenySourcesMatched = false
		}
	}

	return anySourceMatched && noDenySourcesMatched
}
```

As with deny destinations we would check that if there are any sources that are matched _and_ check that there are no deny sources matched.

**Comment by ashutosh16** [comment]
@blakepettersson  Since you work on this feature [add deny destinations for projects](https://github.com/argoproj/argo-cd/pull/9652), will you be able to put a PR for this issue?

**Comment by blakepettersson** [comment]
@ashutosh16 sure thing, see #11646.
