### ISSUE TITLE
Server side apply stuck in calculating diff for StatefulSet and CRD

### ISSUE THREAD

**Issue by xinbinhuang** [argoproj/argo-cd#11630]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Stateful set is stuck in `OutOfSync` status with `ServerSideApply=true`, and argocd continually try to resync.

A similar issue happens to Caclico's CRD [`Installation`](https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.Installation). 

**To Reproduce**

**Expected behavior**

Sync successfully without diff.

**Screenshots**

StatefulSet: 

![image](https://user-images.githubusercontent.com/27927454/206625902-257cad41-6817-429e-998e-2d4f656f6a61.png)

Calico: 
![image](https://user-images.githubusercontent.com/27927454/206626429-9369e830-b2be-4e77-90e5-35b1877344b0.png)

**Version**

It's actually 2.54 because 
```shell
argocd: v2.5.4+86b2dde
  BuildDate: 2022-12-06T20:09:11Z
  GitCommit: 86b2dde8e4bf1187acd2b4294e94451cd104dad8
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.4+86b2dde
  BuildDate: 2022-12-06T20:09:11Z
  GitCommit: 86b2dde8e4bf1187acd2b4294e94451cd104dad8
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.9.3+g414ff28
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by leoluz** [comment]
Duplicated issue.
Closing it in favor of https://github.com/argoproj/argo-cd/issues/11143
