### ISSUE TITLE
Ability to generate a warn/alert when a namespace deviates from the expected state

### ISSUE THREAD

**Issue by edlee2121** [argoproj/argo-cd#1167]
It would be a useful security feature if we can warn/alert when a namespace deviates from the expected state. E.g. there is a pod that shouldn't be running based on the deployment manifests.

**Comment by alexec** [comment]
https://github.com/argoproj/argo-cd/issues/1480

**Comment by edlee2121** [comment]
Please prioritize for the next release.

**Comment by alexec** [comment]
I think it's a bit late for v1.2, Can we push back to v1.3?

**Comment by edlee2121** [comment]
v1.3 is fine

**Comment by alexec** [comment]
See #1479
