### ISSUE TITLE
Parameters > Values text entry broken for applications without existing values by #11316

### ISSUE THREAD

**Issue by booleanbetrayal** [argoproj/argo-cd#11676]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

From ArgoCD v2.5.3 -> v2.5.4, the freeform Parameters > Values section does not render the textarea unless there are already values defined. This breaks several operational workflows through the web UX. This appears to be a result of this [new null check](https://github.com/argoproj/argo-cd/pull/11316/files#diff-5aa688c8363519e0872e7dc3c5fec9b665f7b3ee2cc6db59d14e6ac2eeef1907R193-R193) on #11316 .

**To Reproduce**

- Upgrade from v2.5.3 -> v2.5.4. 
- View an application where no freeform value overrides were specified and note that no textarea for input is provided. 
- View an application where freeform value overrides were already provided and note that the textarea is presented.

**Expected behavior**

Textarea is always rendered regardless of existing values.

**Screenshots**

No Pre-Existing Values - No "Values" section
<img width="810" alt="Screenshot 2022-12-12 at 4 49 28 PM" src="https://user-images.githubusercontent.com/981825/207184174-1583a489-2fcf-42fd-973d-74f45a0559f4.png">

Pre-Existing Values - "Values" section
<img width="831" alt="Screenshot 2022-12-12 at 4 50 18 PM" src="https://user-images.githubusercontent.com/981825/207184520-7a6ba08e-2699-43d9-a356-192ebed547f6.png">

**Version**

```shell
argocd: v2.5.4+86b2dde
  BuildDate: 2022-12-06T20:09:11Z
  GitCommit: 86b2dde8e4bf1187acd2b4294e94451cd104dad8
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.4+86b2dde
```

**Logs**

NA

**Comment by alexef** [comment]
The null check is removed again in: https://github.com/argoproj/argo-cd/pull/11538/files#diff-5aa688c8363519e0872e7dc3c5fec9b665f7b3ee2cc6db59d14e6ac2eeef1907L194 but that PR might take a bit more to review and merge.

Let me roll back this one line change for 2.6.

**Comment by booleanbetrayal** [comment]
Thank you @alexef !
