### ISSUE TITLE
github.com/argoproj/argo-cd/v2 v2.5.4 auth.HostKeyCallback undefined (type *PublicKeysWithOptions has no field or method HostKeyCallback)

### ISSUE THREAD

**Issue by DomineCore** [argoproj/argo-cd#11684]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
I use argocd project package found an error：
github.com/argoproj/argo-cd/v2/util/git
../../../../../go/pkg/mod/github.com/argoproj/argo-cd/v2@v2.5.3/util/git/client.go:255:9: auth.HostKeyCallback undefined (type *PublicKeysWithOptions has no field or method HostKeyCallback)
../../../../../go/pkg/mod/github.com/argoproj/argo-cd/v2@v2.5.3/util/git/client.go:259:9: auth.HostKeyCallback undefined (type *PublicKeysWithOptions has no field or method HostKeyCallback)
../../../../../go/pkg/mod/github.com/argoproj/argo-cd/v2@v2.5.3/util/git/ssh.go:58:11: a.SetHostKeyCallback undefined (type *PublicKeysWithOptions has no field or method SetHostKeyCallback)

### this is my code:
<img width="894" alt="image" src="https://user-images.githubusercontent.com/50765823/207346788-0a0350bd-dec7-45ff-ae46-132b8e787208.png">

![image](https://user-images.githubusercontent.com/50765823/207347321-26f799a9-ded1-42f7-b8d3-00ce546c3d21.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
2.x
```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by YeKc1M** [comment]
@DomineCore I've also met this problem. Do you have some solution to this now?

**Comment by YeKc1M** [comment]
I try to update my go.mod go-git/v5 to v5.4.2, and it fixes
