### ISSUE TITLE
Add UI write support for CMP parameters

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#11754]
# Summary

v2.6 [includes](https://github.com/argoproj/argo-cd/pull/9216) a new way to parameterize Applications that use config management plugins.

When a plugin "advertises" a certain parameter, that parameter appears in the UI under the Application's "Parameters" tab.

That view is currently read-only for those parameters. The UI should allow a user to edit the values. The UI should transform the value as presented in the UI into the `spec.source.plugin.parameters` format.

What it looks like as a read-only interface:

![image](https://user-images.githubusercontent.com/350466/208507340-c34615e5-dc66-45dc-9da0-994be5242758.png)

What it should look like in the manifest after editing:

![image](https://user-images.githubusercontent.com/350466/208507412-23faee66-001e-4fd7-adde-6fab8a05fe70.png)

(Look under `source.plugin.parameters`.)

# Motivation

This will significantly ease the user experience of setting plugin parameters.

# Proposal

Mimic the current Helm and Kustomize parameters edit experience as much as possible.

**Comment by Marvin9** [comment]
Would you please assign this to me @crenshaw-dev ?

**Comment by crenshaw-dev** [comment]
@Marvin9 we typically don't assign issues. Just link back to this issue from a PR, and they'll be connected. :-)
