### ISSUE TITLE
Wildcard filter in UI

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#11781]
# Summary

The "name" field search by exact match. I'd like to search for wildcards so I can file all the resources name "workflow*".

![image](https://user-images.githubusercontent.com/1142830/208718444-633fade9-6e70-4330-b690-815c15cbe76d.png)
 

# Motivation

Find resources grouped by name.

# Proposal

Sorry.

**Comment by NickLarsenNZ** [comment]
I've been wanting this for so long. It's the first thing I try in the UI whenever I upgrade 😊 .

Is there a technical limitation (like an expensive operation)? It appears the list is populated in the UI anyway, so it might be something that can be done in the UI only and not have to communicate with the backend. I'm not so familiar with the UI-backend interactions though.

**Comment by alexef** [comment]
@NickLarsenNZ you are correct, this is done in the frontend and yes there is no technical limitation. Just lack of time to implement it.

**Comment by NickLarsenNZ** [comment]
I can take a look. I haven't looked at which frontend framework is being used, but I imagine it can be passed through some kind of filter.

Should it be a regex search? Or just simple wildcards? I prefer the former.

**Comment by NickLarsenNZ** [comment]
I had a quick look and am a little lost trying to find where the input ends up.

For anyone wanting to take a look, I started here: https://github.com/argoproj/argo-cd/blob/master/ui/src/app/applications/components/filter/filter.tsx and I think `input` is probably the variable that would then have the regex/wildcard string.

I'm guessing somewhere else is where it actually gets used.

**Comment by alexef** [comment]
@NickLarsenNZ yes, simple wildcards or glob would also be my preference.

I believe the place where the filter is actually used is here: https://github.com/argoproj/argo-cd/blob/master/ui/src/app/applications/components/application-details/application-details.tsx#L736 where the name of a resource is checked for presence in an array of hardcoded names. doing the glob here should work, unless I'm missing something.

The options are hardcoded: https://github.com/argoproj/argo-cd/blob/master/ui/src/app/applications/components/application-details/application-resource-filter.tsx#L125 (filled with all names), but the component might accept extra options.

**Comment by NickLarsenNZ** [comment]
Thanks @alexef, so if I understand this correctly, this: `filterInput.name.indexOf(node.name) > -1` would need to change to a regex/glob search in the `filterInput.name` list.

**Comment by NickLarsenNZ** [comment]
Maybe like this:

```ts
filterInput.name.filter(item => item.match(`/{node.name}/g`).count() > 0).count() > 0
```

_Disclaimer: I'm not 100% certain that is valid ES/TS, but just testing the general approach is fit_
