### ISSUE TITLE
Unable to load data: unknown method ListPlugins for service repository.RepoServerService

### ISSUE THREAD

**Issue by robcxyz** [argoproj/argo-cd#11784]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [?] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I all of a sudden got this error while trying to access argo. Not seeing any other errors while searching keywords / error. I updated the token used to access GH to no avail but likely completely unrelated. Also restarted server and no changes. 

**To Reproduce**

Try to access argo. Not able to reproduce in sandbox. Also argo not deploying new applications. Was working before. 

**Expected behavior**

Argo should be working. 

**Screenshots**

Can't access. 

**Version**

```shell
argocd: v2.6.0+f8bc471
  BuildDate: 2022-12-20T19:00:48Z
  GitCommit: f8bc471801fa35d2be074c076eaa8b505a6e1503
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
level=error msg="finished unary call with code Unimplemented" error="rpc error: code = Unimplemented desc = unknown method ListPlugins for service repository.RepoServerService" grpc.code=Unimplemented grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2022-12-20T22:01:22Z" grpc.time_ms=14.259 span.kind=server system=grpc ```

**Comment by robcxyz** [comment]
Oh god I feel dumb. Restarted repo-server. All good.

**Comment by crenshaw-dev** [comment]
@robcxyz do you use a pinned release version in your manifests? If you're using the `:latest` tag, you're gonna get these contract mismatches when containers/Pods restart.

**Comment by robcxyz** [comment]
@crenshaw-dev Yeah you were right. It had the latest tag. Will pin that in the deployment. Thanks for response.

**Comment by neron-traice** [comment]
> Oh god I feel dumb. Restarted repo-server. All good.

I also got the same issue and resolved it after restarting the repo-server pod. Do we know is there any specific reason for this? I couldn't find anything in the logs section.
