### ISSUE TITLE
2.6 RC1: missing required field "pathParamPrefix" in io.argoproj.v1alpha1.ApplicationSet.spec.generators.git

### ISSUE THREAD

**Issue by gaeljw** [argoproj/argo-cd#11796]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading to 2.6 RC1, we are unable to sync AppSet using a git generator without the `pathParamPrefix`.

This is related to https://github.com/argoproj/argo-cd/issues/10522 but I thought the prefix would be non mandatory.

**To Reproduce**

Just create an AppSet with git generator. I can provide an example but any will work.

**Expected behavior**

`pathParamPrefix` should be optional, at least in a transition phase.

**Screenshots**

N/A

**Version**

```shell
v2.6.0-rc1+81e40d5
```

**Logs**

```
error validating data: ValidationError(ApplicationSet.spec.generators[0].git): missing required field "pathParamPrefix" in io.argoproj.v1alpha1.ApplicationSet.spec.generators.git
```

**Comment by crenshaw-dev** [comment]
Good catch, it should definitely be optional.

**Comment by alecgerona** [comment]
This also happens in v2.5.5+fc3eaec

**Comment by crenshaw-dev** [comment]
@alecgerona the string `pathParamPrefix` doesn't exist in the `release-2.5` branch. I suspect you applied the latest CRD, which includes that field as required.
