### ISSUE TITLE
argocd app-of-apps pattern for deployments

### ISSUE THREAD

**Issue by rshiva777** [argoproj/argo-cd#11793]
# Summary

What change you think needs making.

# Motivation

Lets say i want to deploy an application using app-of-apps model.

- parent-app.yaml  (I will create the parent app manually from argocd, this application should in turn create 2 new applications
   - frontend.yaml
   - backend.yaml

But, as per the current argocd approach, if my project is restricted to deploy the application only to a single namespace then the app-of-apps model wont work, as the frontend.yaml and backend.yaml should be created under the argocd namespace, and our project dont have the argocd namespace access

![image](https://user-images.githubusercontent.com/42074614/208834437-614d3c81-6386-4340-89b6-def5a3c8c64e.png)

 

Please give examples of your use case, e.g. when would you use this.

- parent-app.yaml  (I will create the parent app manually from argocd, this application should in turn create 2 new applications
   - frontend.yaml
   - backend.yaml

If i give the project access to only test namespace where i want to deploy my frontend and backend apps, the frontend.yaml and backend.yaml application kind wont be deployed because they should be deploy under argocd namespace and the destination would be test namespace.

In order to overcome the above case, i have added the project access to argocd namespace also, so that the child apps are created 

![image](https://user-images.githubusercontent.com/42074614/208835428-f88db111-1f28-4e82-80dc-d64a79d1571b.png)

But if i follow the approach, the end user has the access to deploy application in argocd namespace as well which should not be the case.

Whitelist feature is common across all namespace mentioned in the project, what ever the test namespace have RBAC, same will be application for argocd namespace

# Proposal

I feel that RBAC should be created at namespace level at project so that, we can select what are the resources that are whitelisted for a particular namespace.

Eg:  In the above example i mentioned,

test namespace: should have deployment, pvc, statefulset, cm, secret, ingress resources access
argocd namespace: should have only application crd access

How do you think this should be implemented?

**Comment by jgwest** [comment]
This is, in equal parts, covered  by other issues and/or is a design choice.
