### ISSUE TITLE
argocd app going in syncing status forever. Recovering only after deleting the application and resyncing

### ISSUE THREAD

**Issue by vijay-dcrust** [argoproj/argo-cd#11806]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

  We have hundreds of applications created by argocd. But one particular application is going into syncing forever after certain changes. The change is basically creation of some configmaps and mounting it in the existing deployment. 
 If i run dry-run also from cli, it goes into syncing forever.
```argocd app sync --dry-run dev-app-name --local ```

If i delete the app, then app is recreated fine throguh gitops (app-of app pattern) But again if i make any change, the same issue happens.

**To Reproduce**
   Create a new configmap and mount it as volume on existing deployment.
 

**Expected behavior**

  The application status should not be syncing. Either it should sync fine or throw an error to rectify.

**Screenshots**

  Attached the screenshot.

```shell
$ argocd version
argocd: v2.4.9+1ba9008.dirty
  BuildDate: 2022-08-11T18:34:44Z
  GitCommit: 1ba9008536b7e61414784811c431cd8da356065e
  GitTreeState: dirty
  GoVersion: go1.19
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.5.3+0c7de21
  BuildDate: 2022-11-28T16:51:33Z
  GitCommit: 0c7de210ae66bf631cc4f27ee1b5cdc0d04c1c96
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: [v0.18.0]([url]( @url))

```

**Logs**

```
time="2022-12-22T02:24:30Z" level=info msg="Comparing app state (cluster: https://XXXXXXXXXX.gr7.ap-southeast-1.eks.amazonaws.com, namespace: app-namespace)" application=argocd/dev-app-name
time="2022-12-22T02:24:30Z" level=info msg="getRepoObjs stats" application=argocd/dev-app-name build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=64 unmarshal_ms=63 version_ms=0
time="2022-12-22T02:24:31Z" level=info msg="No status changes. Skipping patch" application=argocd/dev-app-name
time="2022-12-22T02:24:31Z" level=info msg="Reconciliation completed" application=argocd/dev-app-name dedup_ms=0 dest-name= dest-namespace=app-namespace-server="https://XXXXXXXXXX.gr7.ap-southeast-1.eks.amazonaws.com" diff_ms=6 fields.level=1 git_ms=64 health_ms=0 live_ms=1 settings_ms=0 sync_ms=0 time_ms=351

```

**Comment by vijay-dcrust** [comment]
I get this error, when i try to sync it again.

FATA[0004] rpc error: code = FailedPrecondition desc = another operation is already in progress

**Comment by vijay-dcrust** [comment]
If i try to terminate the op, i get this.

FATA[0002] rpc error: code = InvalidArgument desc = Unable to terminate operation. No operation is in progress

**Comment by jdomag** [comment]
We had the same in 2.4.8 - however deleting app and resyncing didn't help - app always stuck in syncing (the app is just to create about 100 configmaps). We restarted all argocd related pods and app managed to sync properly.

**Comment by jgwest** [comment]
Dupe of https://github.com/argoproj/argo-cd/issues/7890, among others.
