### ISSUE TITLE
Webhook only refresh applications in argocd installation namespace

### ISSUE THREAD

**Issue by RaveNoX** [argoproj/argo-cd#11867]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**
I'm trying to use new [applications in any namespace](https://argo-cd.readthedocs.io/en/latest/operator-manual/app-any-namespace/) feature.
With this feature, [git webhook](https://argo-cd.readthedocs.io/en/latest/operator-manual/webhook/), triggers applications refresh only in `argocd` namespace (in namespace where ArgoCD installed).

After some code research I found, that it looks like this can't work as expected.
Problem is in [this code](https://github.com/argoproj/argo-cd/blob/v2.5.4/util/webhook/webhook.go#L213): 
```go
appIf := a.appClientset.ArgoprojV1alpha1().Applications(a.ns)
apps, err := appIf.List(context.Background(), metav1.ListOptions{})
```
Main branch contains same code.

**To Reproduce**
1. Configure ArgoCD to use [applications in any namespace](https://argo-cd.readthedocs.io/en/latest/operator-manual/app-any-namespace/) feature;
2. Create application in not ArgoCD installation namespace (for example defaul);
3. Configure [git webhook](https://argo-cd.readthedocs.io/en/latest/operator-manual/webhook/);
4. Push changes in git;
5. You will see that only applications in ArgoCD installation namespace will be refreshed, others wil be refreshed only by shedule.

**Expected behavior**
[git webhook](https://argo-cd.readthedocs.io/en/latest/operator-manual/webhook/) should refresh applications in any namespace

**Version**

```shell
# argocd version                                                                                                                                                                                              12:13:14 
argocd: v2.5.5+fc3eaec
  BuildDate: 2022-12-16T16:34:36Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.4+86b2dde
  BuildDate: 2022-12-06T19:46:25Z
  GitCommit: 86b2dde8e4bf1187acd2b4294e94451cd104dad8
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Comment by lukma99** [comment]
encountered the same bug today. I would really like to use webhooks for apps in different namesapces, hope this will get fixed :)
