### ISSUE TITLE
Move application sync logic to the controller

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#119]
Synchronizing an application is currently done as a synchronous API request to the API server, which performs the logic in-line. This should instead become asynchronous call, which simply updates the app CRD, and defer the logic to the controller. 

By handling everything through the controller, we eliminate virtually all race conditions, and will simply our logic since everything will go through the same code path. It also will allow our auto-sync feature to work the same way.

In order to force a sync via the API, that API call  could simply translate to setting some `status.syncExpiration` time to 1970-01-01T00:00:00Z.

If consumer really wants a blocking call, they can establish a watch against the app resource to wait until the app becomes synced again.

**Comment by alexmt** [comment]
Working on it

**Comment by jessesuen** [comment]
Fixed.
