### ISSUE TITLE
ArgoCD returns ReferenceError when opening an application

### ISSUE THREAD

**Issue by skeithyoung** [argoproj/argo-cd#11922]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to view manifests on my applications but when opening an application from ArgoCD renders an error page with a stacktrace. The stacktrace is in the Logs heading.

**To Reproduce**

1. Log into ArgoCD.
2. Open an application to view the manifests
3. Instead of rendering the tree and the application details page, ArgoCD renders the error page–screenshot included below.

**Expected behavior**

I would expect ArgoCD to open the detailed Application page, with the associated manifests accessible.

**Screenshots**

![Screen Shot 2023-01-09 at 10 40 18 AM](https://user-images.githubusercontent.com/28600417/211364175-a351f849-73fe-408c-9c85-ad018349b55a.png)

**Version**

```shell
argocd: v2.4.15+05acf7a.dirty
  BuildDate: 2022-10-17T22:52:44Z
  GitCommit: 05acf7a52e377eacfee29c68e3e5e79a172ea013
  GitTreeState: dirty
  GoVersion: go1.19.2
  Compiler: gc
  Platform: darwin/amd64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.6.0+052a5d2
  BuildDate: 2023-01-06T22:52:34Z
  GitCommit: 052a5d2f69aa6bcc61a9a744d1e46e99490fda59
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
ReferenceError: parsed is not defined
    at https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:1649153
    at kh (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:1649261)
    at Jr (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:807467)
    at ya (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:853372)
    at pl (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:846148)
    at dl (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:846073)
    at il (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:843103)
    at https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:794882
    at t.unstable_runWithPriority (<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:869930)
    at Uo (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:794591)
```

**Comment by crenshaw-dev** [comment]
Do you have a (redacted) Application spec?

**Comment by skeithyoung** [comment]
Hi Michael! I'm not sure what you mean. Can you explain?

**Comment by crenshaw-dev** [comment]
The main thing that informs this view is the manifest of the Application you're trying to load. If you could `kubectl get app -o yaml` that manifest and remove any sensitive info, that manifest would help with debugging.

**Comment by skeithyoung** [comment]
Michael I see you linked a patch that is in progress. How would we go about incorporating [#11816](https://github.com/argoproj/argo-cd/pull/11916) once it is out?

We're working on sanitizing a manifest for you at the moment. Thanks for your help!

**Comment by crenshaw-dev** [comment]
@skeithyoung I think we can actually manage without the manifest, since it seems pretty clear that #11816 will fix your issue.

Are you using the `:latest` image? If so, the problem will be solved after we merge the change and you restart+re-pull the latest image.

btw if you're using the `:latest` image in prod, you should switch to a versioned tag. :-)

**Comment by hedeesaa** [comment]
I'm facing the same issue here and both Dex image and argocd image are `latest` version.
