### ISSUE TITLE
Non-Kubernetes/Terraform deployment strategy?

### ISSUE THREAD

**Issue by fikriauliya** [argoproj/argo-cd#1193]
I believe quite some of us prefer to use native cloud services given their availability. For example, rather than maintaining PG ourselves using K8s, some prefer to use Google Cloud SQL or AWS RDS.

For such cases, the typical deployment strategy is using Terraform (although I hope in future it can also be defined in Kubernetes YAML, e.g. `rds-deployment-and-service.yaml`). 

In the cases where we have a mix of Kubernetes YAMLs and Terraform configs, how is the recommended way in ArgoCD? Can ArgoCD apply Terraform config? Or should ArgoCD manage Kubernetes YAML only? If they are meant to be separated, how should we structure our GitOps project?

**Comment by alexmt** [comment]
I would consider using Terraform operator. In this case, Argo CD can be used to push CRD with the terraform script and terraform CRD controller would execute the script and update CRD status with the results.

Here are several implementations of terraform operators:

https://github.com/danisla/terraform-operator
https://github.com/rancher/terraform-operator

**Comment by fikriauliya** [comment]
Seems like OperatorHub is the answer to this?

There is few AWS infra that can be created from K8s manifests:
https://www.operatorhub.io/operator/aws-service-operator.v0.0.1

**Comment by AceHack** [comment]
Any update?

**Comment by damascenorakuten** [comment]
+1

**Comment by pbaezab** [comment]
+1
