### ISSUE TITLE
Transition between pages in dark mode flashes white

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#11938]
https://user-images.githubusercontent.com/350466/190405426-e320b81b-3b50-4bb6-bc45-c35ac62c656c.mov

The transition between pages flashes white, which is really hard on the eyes. I'm hoping it's a relatively easy fix.

_Originally posted by @crenshaw-dev in https://github.com/argoproj/argo-cd/issues/9703#issuecomment-1248045785_

**Comment by jannfis** [comment]
@saumeya Would you like to take a look at this, please?
