### ISSUE TITLE
Issues with Kubernetes API Deprecation warnings

### ISSUE THREAD

**Issue by sidewinder12s** [argoproj/argo-cd#11973]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

```log
W0112 20:10:35.903374       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

A few issues with how the application-controller logs these warnings:

- They are insistent and excessive, consuming large volumes of our logging quota.
- If you have JSON logging enabled, they are not JSON wrapped, screwing up any log parsing you may have setup
- They are not actionable, they do not say what resource or application is throwing the warning.

**To Reproduce**

Use a deprecated API.

**Expected behavior**

These should be properly JSON wrapped, they should be actionable, you should be able to disable this warning.

**Version**

```shell
argocd: v2.5.5+fc3eaec
  BuildDate: 2022-12-16T16:34:36Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.5+fc3eaec
  BuildDate: 2022-12-16T16:10:26Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**

```
W0112 20:10:35.903374       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

**Comment by jannfis** [comment]
I agree, these can be annoying. Seems that the warnings are emitted by Kubernetes' client-go, as described in [this blog post](https://kubernetes.io/blog/2020/09/03/warnings/).

There seems to be a way to [turn them off](https://kubernetes.io/blog/2020/09/03/warnings/#customize-client-handling)
