### ISSUE TITLE
Use 7 characters for `head_short_sha` in PR generator

### ISSUE THREAD

**Issue by fty4** [argoproj/argo-cd#11976]
# Summary

Hello everyone,

I was currently wondering why my workflow was not working as expected and found the problem:

As common like in GitHub UI and git log the short sha of a commit is usually 7 characters long.
Because of that I used the same length of seven in the image tag.
But when the pull request generator created an Argo CD App it was using the [`head_short_sha`](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Pull-Request/#template) and did not find the image.

As described in the documentation the `head_short_sha` is using 8 characters:

> head_short_sha: This is the short SHA of the head of the pull request (8 characters long or the length of the head SHA if it's shorter).

Why was this implemented with #9669 with 8 characters?
In the referenced issue #9668 the proposal also was to use seven instead of eight.

Maybe because in the [git documentation](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Short-SHA-1) you find this section:

> Generally, eight to ten characters are more than enough to be unique within a project. For example, as of February 2019, the Linux kernel (which is a fairly sizable project) has over 875,000 commits and almost seven million objects in its object database, with no two objects whose SHA-1s are identical in the first 12 characters.

Nevertheless I would appreciate to change this to a 7 character hash.

# Motivation

My motivation is to change this because I had an issue because the sha commit hash length was not as expected.
Also it would be nice if it is the same as commonly used.

# Proposal

I have already implemented the change in https://github.com/fty4/argo-cd/commit/487397f8db9e4de7a885dd8442abaf4808a17243 and created this issue because the checklist of a PR an enhancement proposal should be present.

Can I create a PR for this?

**Comment by crenshaw-dev** [comment]
I don't think we can safely change parameters' calculation. We don't know how those parameters are used in current users' applications.

Instead, I'd recommend using [go-templated ApplicationSets](https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/GoTemplate/) to calculate the parameter in precisely the way you need it.

**Comment by ddecrulle** [comment]
I think it's best to follow the 7 character standard. The sooner this change is made, the fewer applications will be impacted

**Comment by crenshaw-dev** [comment]
I'm opposed to _any_ applications being impacted.

If folks really need a 7-char hash and cannot use go-templating, we should introduce `head_short_sha_7`.

**Comment by jsirianni** [comment]
I am running into this right now. I assumed `head_short_sha` would be equal to the output of `git rev-parse --short HEAD`.

I tag my pull request images with the output of `git rev-parse`, and then have argocd deploy the pull request using `head_short_sha`. I was stumped at first when I noticed argocd was consistently getting the tag wrong. Turn outs, its just using the 8 character version while I am tagging with 7.

`head_short_sha_7` would be great, in order to preserve backwards compatibility while also allowing users like OP and myself to continue using our existing tagging process.

**Comment by crenshaw-dev** [comment]
If someone's up for a PR, I'd be happy to review! Should be a pretty simple one.

**Comment by fty4** [comment]
@crenshaw-dev I've created a PR for this issue here - you might have a look.
