### ISSUE TITLE
Adding CONTRIBUTING.md file

### ISSUE THREAD

**Issue by AnishDubey27** [argoproj/argo-cd#11992]
# Summary

If a new contributor finds an issue in the project and wants to make an enhancement, they would have to go through so much documentation before they could actually start to contribute.

# Motivation

If a CONTRIBUTING.md file is present in the project, it will make the task far easier for a new contributor.

# Proposal

We need to add a file CONTRIBUTING.md which contains a step by step guide which a beginner can follow to create a pull request and help the project grow.

Also, I would love to work on this issue.

**Comment by AnishDubey27** [comment]
The idea that I had was to either make some changes into the file you mentioned or to create a new file something like this : https://github.com/akshitagupta15june/Face-X/blob/master/CONTRIBUTING.md
It contains the minute details including making a new Pull Request using cli or even through GitHub Desktop which won't require the contributors to write a single terminal command while making a Pull Request just through using the GUI as most new contributors might not be familiar to the CLI

**Comment by blakepettersson** [comment]
Should be addressed with #14889.
