### ISSUE TITLE
Option to set default view for argocd apps

### ISSUE THREAD

**Issue by codestalkerr** [argoproj/argo-cd#12019]
# Summary

It would be really helpful give option to set config for default UI element. 
For example today the default view is "APPLICATION DETAILS TREE" but there is no way to change that default view to something else with help of configmap or some settings in yaml. (If there is already then please let me know)

# Motivation

Started looking into this because many developers complained that while loading the app view the UI was not responding well and hanging a bit (we have around 1200 different application there). We did try to improve the performance by updating different settings but didnt see much difference. And noticed a nice work around is to change the default view to "APPLICATION DETAILS NETWORK" which loads faster.

# Proposal

Maybe an option in externalArgs or configmap?

**Comment by alexef** [comment]
Wow, I was thinking of the same thing right now, had similar issues in the past days.

This makes even more sense as [view extensions just landed](https://github.com/argoproj/argo-cd/pull/12006).

What I would like to be able to configure is:
- default `view` (built-in or extension)
- default group by option in the `node` view

**Comment by alexef** [comment]
I am also thinking that a different view might make sense on an application basis. So in addition to supporting this in `argocd-cm` maybe we can support it also as an `argoproj.io/Application` metadata annotation?

@alexmt / @rbreeze as you're working on view extensions, what do you think?

**Comment by rbreeze** [comment]
@alexef I agree, this makes sense on a per app basis. Taking a look at the PR

**Comment by shuker85** [comment]
It would be great if we can override for all apps from a argocd-cm param too.It can be tedious to change in case of hundreds apps.

**Comment by crenshaw-dev** [comment]
Closing this since the original ask is done: https://argo-cd.readthedocs.io/en/latest/operator-manual/ui-customization/#default-application-details-view

@shuker85 would you mind opening a new issue for the global setting?
