### ISSUE TITLE
Docs should cover how to respond to `Manifest generation error (cached)`

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#12039]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

`Manifest generation error (cached)` doesn't lead to users being able to fix the error.

**To Reproduce**

1. Migrate from argo-helm argo-cd 5.6.8 (with a old style CMP) to argo-cd 5.7.0 (without properly configuring a replacement CMP)
2. Try to get the CMP to work by setting up a `CMP` for `conf`

**Expected behavior**

* When there's an error about manifest generation (cached), there should be enough information somewhere to explain how to flush the cache (this could be in the form of Documentation, the FAQ, or in the GUI, or probably all of the above).

**Screenshots**

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/2119212/213309689-8457fe5e-456e-4caf-a4c6-7ef13c54a962.png">

**Version**

```shell
{
    "Version": "v2.4.11+3d9e9f2",
    "BuildDate": "2022-08-22T09:13:16Z",
    "GitCommit": "3d9e9f2f95b7801b90377ecfc4073e5f0f07205b",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.1+g5cb9af4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jsoref** [comment]
For people wondering, and as guidance to someone working to fix this:

---

1. Clicking the teeny tiny down arrow next to  `↻ Refresh` will yield a menu:
    ![image](https://user-images.githubusercontent.com/2119212/214083102-169e03c5-d414-43fa-a5be-c6dcc59a261b.png)
2. Clicking `Hard Refresh` on the App will clear any cached content for the app and should give things a chance to reproduce

---

Notes:
1. There should be a tooltip for `Hard Refresh` explaining what it does
2. Any log view that shows a cached warning should include a note explaining how to trigger a hard refresh to clear the cached item.

**Comment by simonfelding** [comment]
agree. this is very confusing, thanks for writing an explanation.

**Comment by x45dev** [comment]
Agree - thank you for posting this! I can't believe how much time I wasted because of this. :(

**Comment by x45dev** [comment]
> For people wondering, and as guidance to someone working to fix this:
> 
> 1. Clicking the teeny tiny down arrow next to  `↻ Refresh` will yield a menu:
>    ![image](https://user-images.githubusercontent.com/2119212/214083102-169e03c5-d414-43fa-a5be-c6dcc59a261b.png)
> 2. Clicking `Hard Refresh` on the App will clear any cached content for the app and should give things a chance to reproduce
> 
> Notes:
> 
> 1. There should be a tooltip for `Hard Refresh` explaining what it does
> 2. Any log view that shows a cached warning should include a note explaining how to trigger a hard refresh to clear the cached item.

Agree - thank you for posting this! I can't believe how much time I wasted because of this. :(

**Comment by ForbiddenEra** [comment]
What about when you're adding a new app and there's no existing app to hard refresh?!

**Comment by mrhankeh9934** [comment]
this doesnt fix it

**Comment by francovp** [comment]
> What about when you're adding a new app and there's no existing app to hard refresh?!

Someone know this? please :(

**Comment by crenshaw-dev** [comment]
`Manifest generation error (cached)` just means that there was an error when generating manifests and that the error message has been cached to avoid runaway retries.

Doing a hard refresh (ignoring the cached error) can overcome transient issues. But if there's an ongoing reason manifest generation is failing, a hard refresh will not help.

**Comment by kareemelkasaby1** [comment]
dears, my argocd fetches the new git sha commit but still reads from the cached manifest, it is non-sense to do hard refresh on every checnge
do you have a way that the changes to be automatically detected by a new manifest? (not manually doing a hard refresh)
