### ISSUE TITLE
Can not change version in documentation

### ISSUE THREAD

**Issue by HknLof** [argoproj/argo-cd#12036]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`. <-- irrelevant

**Describe the bug**
On the documentation website, see below: I expect a dropdown with versions of argocd to appear when clicking `latest ▼`. Dropdown does not appear.

**To Reproduce**
Go to https://argo-cd.readthedocs.io/en/stable and click on the button in the top bar.

**Expected behavior**
I expect a dropdown to appear.

**Comment by shuker85** [comment]
Duplicate of https://github.com/argoproj/argo-cd/issues/11999

**Comment by jannfis** [comment]
Closing as duplicate.
