### ISSUE TITLE
Tree-view: Always show PodGroup  in  replicaset when Child Pod node exist

### ISSUE THREAD

**Issue by ashutosh16** [argoproj/argo-cd#12051]
# Summary

In the Tree View, when the user clicks on the `group node`, the last node shows as a replicaset that groups the same kind of sibling (replicaset). 

This UI experience seems inconsistent. When multiple replicaset nodes exist, it displays node groups of the same kind, in this case replicaset, whereas when only one replicaset node exists, it displays podGroup.

Consistent UI experience should be provided where the user always sees podGroup on replicaset whenever child pods exist.

Current UI - when multiple replicaset nodes exist

<img width="756" alt="Screen Shot 2023-01-19 at 10 35 30 AM" src="https://user-images.githubusercontent.com/11219262/213530964-4a2cd5df-6b4b-4e2b-81ef-aefbf5226742.png">

Current UI - When only one replica set node exists, UI shows pod group.

<img width="781" alt="Screen Shot 2023-01-19 at 10 37 19 AM" src="https://user-images.githubusercontent.com/11219262/213531324-986e0419-e335-41f6-92d8-ef479271b296.png">

The enhancement should expand the replicaset in podGroup view when child pod exists and group the sibling node when no further child node exists

**Comment by keithchong** [comment]
The current behaviour is implemented as designed from point #10 from PR https://github.com/argoproj/argo-cd/pull/8661
The grouped nodes have always taken precedent, but I can see the benefit of special-casing the replicasets and pulling them out as a pod group.

Three RS, but one RS with at least one pod:
<img width="1308" alt="Screen Shot 2023-01-20 at 12 00 38 PM" src="https://user-images.githubusercontent.com/7726022/213761005-8db746ef-5916-49f7-a0ee-2116b55ac26c.png">

...and with Group Nodes enabled:
<img width="1011" alt="Screen Shot 2023-01-20 at 12 00 54 PM" src="https://user-images.githubusercontent.com/7726022/213761206-56d15a87-1a18-4f99-b5e2-e03954f57b33.png">

Note the other situation where only one RS has no associated pods:
<img width="1300" alt="Screen Shot 2023-01-20 at 11 59 12 AM" src="https://user-images.githubusercontent.com/7726022/213761425-d4fc6163-540a-49f1-b907-e5e3affaabaf.png">

...and with Group Nodes enabled:
<img width="991" alt="Screen Shot 2023-01-20 at 11 59 27 AM" src="https://user-images.githubusercontent.com/7726022/213761476-5360b108-c102-4ed7-9c21-eccb9c5daf2c.png">

**Comment by ashutosh16** [comment]
@keithchong  Thanks for looking into it. 
UX seems right to me ( pic 2 & 3). This would be a special case when RS is expanded as podGroup  when child pod exit

**Comment by ashutosh16** [comment]
Verified in my local and changes looks good 
<img width="584" alt="Screen Shot 2023-01-20 at 1 10 42 PM" src="https://user-images.githubusercontent.com/11219262/213806124-7804cb7f-e5c2-48b1-98ac-37c3e3a1de15.png">
