### ISSUE TITLE
`Missing` is too far to the left because 👻  is too narrow

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#12055]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The `Missing` label in `Health Status` is shifted to the left relative to the other labels.

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/argocd/argo-cd?view=list&resource=
2. If the filters sidebar is collapsed, expand it.

**Expected behavior**

Each icon should share a center line and each label should share a left line

**Screenshots**

<img width="1806" alt="image" src="https://user-images.githubusercontent.com/2119212/213577168-6028b1e2-a750-483a-840f-101a92a57d72.png">

![image](https://user-images.githubusercontent.com/2119212/213577893-49c0f172-30da-4717-8171-814be39513a0.png)

**Version**

```shell
{
    "Version": "v2.6.0+584428e",
    "BuildDate": "2023-01-19T17:14:49Z",
    "GitCommit": "584428edaf535258924912a191a97dde8a5c5d3d",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jsoref** [comment]
@shijiadong2022

**Comment by shijiadong2022** [comment]
Thanks @jsoref . I'd like to work on this one and submit a PR later.

**Comment by surajyadav1108** [comment]
We can close this I guess

<img width="199" alt="inline  " src="https://github.com/user-attachments/assets/003dc21b-e6b9-41d1-9974-af9d9d886e4c">
