### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Architha18** [argoproj/argo-cd#12058]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by blakepettersson** [comment]
Don't see any issue here, so closing.
