### ISSUE TITLE
Arrow for currently selected container should not indent container name

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#12063]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I misinterpreted he `>` character as meaning the item below it was a child.

**To Reproduce**

1. Visit a Pod with multiple containers, especially if there are sidecar containers and and init containers
2. Open the info view for the pod
3. Select the logs tab for the pod
4. Click the 🥞 widgets to show the containers

**Expected behavior**

The `>` should be in negative space (i.e. to the left of all of the container names instead of shifting the selected container name to the right)

**Screenshots**

https://cd.apps.argoproj.io/applications/argocd/argo-cd?view=tree&resource=kind%3APod&node=%2FPod%2Fargocd%2Fargocd-dex-server-7ddfd58c9f-w2fv6%2F0&tab=logs

![image](https://user-images.githubusercontent.com/2119212/213781706-e3af0e89-f54b-47fd-8c97-af7764b1096e.png)

**Version**

```shell
{
    "Version": "v2.6.0+61f8876",
    "BuildDate": "2023-01-20T15:12:19Z",
    "GitCommit": "61f8876b992cc740c1902788fca2c02e9a09b758",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by nickorlow** [comment]
Hi maintainers (cc @saumeya  )!

I'm a CS student at the University of Texas at Austin. I'm taking a class focusing on open-source software and virtualization at the moment. One part of the course is making open source contributions. I'd like to work on this issue.

The class requires that we ask the maintainers and get an OK to work on the issue before it can be counted for credit in the class. Would it be possible for me and my partner in the class to work on this issue?

**Comment by saumeya** [comment]
OK, that would be awesome @nickorlow
