### ISSUE TITLE
Make `/settings` only show `help` section if `chatURL` is available

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#12086]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

`help` section of json really shouldn't appear if there's no url..., but it does...

**To Reproduce**

```sh
$ curl 'https://$ARGO_DOMAIN/api/v1/settings' ... | jq .help
{
  "chatText": "Chat now!"
}
```

**Expected behavior**

Only show `help` section if there's a URL.

**Screenshots**

**Version**

```shell
{
    "Version": "v2.6.0+584428e",
    "BuildDate": "2023-01-19T17:14:49Z",
    "GitCommit": "584428edaf535258924912a191a97dde8a5c5d3d",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

**Comment by shin04** [comment]
Hi, I would like to work on this issue, is it okay?

**Comment by jsoref** [comment]
Sure

**Comment by shin04** [comment]
@jsoref  Thank you!

I have one question.
In the bellow part of `util/setting/setting_test.go` , when `ChatURL` and `ChatText` are empty, the default value is expected to be assigned to `ChatText`, is this behavior correct?
In my opinion, when ChatURL and ChatText are empty, ChatText should be empty.

https://github.com/argoproj/argo-cd/blob/master/util/settings/settings_test.go#L650-L658

**Comment by jsoref** [comment]
I'd expect it to be empty, yes.
