### ISSUE TITLE
Clipboard menu isn't easily reachable if log line is very tall

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#12096]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

1. Open a log for a helm chart that generate a really long error for failing to get a chart dependency
2. Enable line wrap in logs view
3. Try to select the log line to copy the message
4. Try to get the menu to do it

**Expected behavior**

I shouldn't have to scroll to show the top of the log line just to click a ⋯ so that I can click the copy item in the menu.

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/214131328-4df82bb3-1ab1-491c-924a-83b330ea4836.png)

I have to scroll to the top of the log line to get the copy item:
![image](https://user-images.githubusercontent.com/2119212/214131717-cc3b7fc7-c889-4f9f-af03-23f9b2571924.png)

**Version**

```shell
{
    "Version": "v2.6.0+584428e",
    "BuildDate": "2023-01-19T17:14:49Z",
    "GitCommit": "584428edaf535258924912a191a97dde8a5c5d3d",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexec** [comment]
the new viewer may have fixed this, please re-open if still issue

**Comment by jsoref** [comment]
Yes, it fixed this in that this ui element no longer exists
