### ISSUE TITLE
Chat Now button has a gradient

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#12090]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The entire ArgoCD UI is flat w/ no gradients, except for the chat now button

**To Reproduce**

1. Configure `help.chatUrl` in the `argocd-cm`
2. Visit an argocd screen

**Expected behavior**

The button should feel consistent w/ other buttons

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/214117904-8192a1f5-9c95-461b-bddf-1e63555f2cab.png)

**Version**

```shell
{
    "Version": "v2.6.0+584428e",
    "BuildDate": "2023-01-19T17:14:49Z",
    "GitCommit": "584428edaf535258924912a191a97dde8a5c5d3d",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by saumeya** [comment]
This change will be in the argo-ui repository

**Comment by 2022H1030042G** [comment]
Hi, I would like to work on this issue, is it available?

**Comment by alexef** [comment]
@2022H1030042G yes, go for it!

**Comment by 2022H1030042G** [comment]
Can you help me with this? I'm new to open source development.

**Comment by saumeya** [comment]
@2022H1030042G - the change will be here - https://github.com/argoproj/argo-ui/blob/master/src/styles/elements/buttons.scss#L237
To work on this you will have to first run argocd locally and then follow the `Local Development` steps here - https://github.com/argoproj/argo-ui (to use the local argo-ui) make the changes and then create a PR in argo-ui and then updated commit id in argocd (see steps here - https://argo-cd.readthedocs.io/en/stable/developer-guide/toolchain-guide/#contributing-to-argo-cd-ui)

**Comment by 2022H1030042G** [comment]
While following the Build and Run steps mentioned here: [https://github.com/argoproj/argo-ui](url), I get the following error when running "yarn start": Failed to parse tsconfig at tsconfig.json: JSON5: invalid character 's' at 1:1

**Comment by saumeya** [comment]
You don't have to run `yarn start` just do the Local Development steps. That repo consists of the UI components and storybooks to check them locally. But you can check them in local development after linking with your local argo-cd

**Comment by 2022H1030042G** [comment]
@saumeya , I followed the Local Development steps, and made changes in the code here: [https://github.com/argoproj/argo-ui/blob/master/src/styles/elements/buttons.scss#L237](url). How do I test it now?

**Comment by saumeya** [comment]
`yalc add argo-ui` in argocd links your local argo-ui. After that just run `make start`

**Comment by 2022H1030042G** [comment]
Alright, I'll try that.

**Comment by 2022H1030042G** [comment]
@saumeya , I have created a PR for it.

**Comment by 2022H1030042G** [comment]
@saumeya, Is there anything else that I need to do?

**Comment by 2022H1030042G** [comment]
Please check the corresponding PR: https://github.com/argoproj/argo-ui/pull/352

**Comment by vipinachar** [comment]
Is this issue resolved or Can I work on this?

**Comment by jsoref** [comment]
I don't _think_ it's resolved, there appears to be a PR which just needed a reviewer... I've poked @crenshaw-dev ...

**Comment by crenshaw-dev** [comment]
PR approved, now we just need to update argo-ui in argo-cd's yarn.lock.

**Comment by agilgur5** [comment]
> PR approved, now we just need to update argo-ui in argo-cd's yarn.lock.

This should have been completed by #16264
