### ISSUE TITLE
Applicationset controller multiple namespace

### ISSUE THREAD

**Issue by speedfl** [argoproj/argo-cd#12107]
# Summary

Currently it is possible to watch multiple namespaces in the application controller. However it is not the case for the applicationset

# Motivation

We have several teams using ApplicationSet.

To make it more secure we have in mind to create an admission webhook which:

- enforces setting the project in the template by rejecting templated project
- allows project based on the namespace (the administrator set the map namespace:projects)

# Proposal

Add an "applicationset-namespaces" option like for the application controller

https://github.com/argoproj/argo-cd/blob/master/cmd/argocd-application-controller/commands/argocd_application_controller.go#L196

**Comment by speedfl** [comment]
I will try to work on this one

**Comment by crenshaw-dev** [comment]
@speedfl gonna close in favor of this, which I think is the same ask: https://github.com/argoproj/argo-cd/issues/10655
