### ISSUE TITLE
cosign public key from the documentation is not available

### ISSUE THREAD

**Issue by maxdanilov** [argoproj/argo-cd#12130]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The `Verification of ArgoCD signatures` web page (https://argo-cd.readthedocs.io/en/stable/operator-manual/signed-release-assets/) has broken [links](https://github.com/argoproj/argo-cd/blob/master/argocd-cosign.pub) to the public cosign key, making the images verification impossible for the end users:

![Screenshot 2023-01-25 at 13 28 05](https://user-images.githubusercontent.com/6655714/214563402-a208b1e9-972e-4265-95ca-969bc6831535.png)

**To Reproduce**

Click on the `public key` or `argocd-cosign.pub` link on https://argo-cd.readthedocs.io/en/stable/operator-manual/signed-release-assets/, it leads to a 404.

**Expected behavior**

The public key for cosign should be publicly available.

**Screenshots**

**Version**

Not applicable.

**Logs**

Not applicable.

**Comment by crenshaw-dev** [comment]
Good catch. It's because I failed to update the `stable` tag after the docs update, so ReadTheDocs is still showing old info.

Updated the tag, waiting on the docs build to finish.

**Comment by crenshaw-dev** [comment]
Docs update is live. Thanks!
