### ISSUE TITLE
Send values to Helm Chart in apps-children from another file in the current repository

### ISSUE THREAD

**Issue by 64J0** [argoproj/argo-cd#12133]
# Summary

Hello people, hope you're good.

In short terms, I would like to be able to manage a Helm Chart values setup in a separate file, other than the one we keep the apps-children YAML file.

# Motivation

In the current approach, in some IDEs (VS Code for example), we don't get all the helper features to deal with YAML syntax when passing the values through the `spec.source.helm.values`. If we were able to create a separate file, which is read by Argo CD to pass the values to the Helm Chart, it would be great, since we would be able to leverage all the IDE features.

# Proposal

How do you think this should be implemented?

I'm not sure. We currently have the `valueFiles`, but it depends on files in the Helm Chart repository, instead of files in the Argo CD configuration setup.

Reference from the docs: [link](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#values-files).

> Values files must be in the same git repository as the Helm chart. The files can be in a different location in which case it can be accessed using a relative path relative to the root directory of the Helm chart.

**Comment by ishitasequeira** [comment]
In case your `valueFile` is in a different repository, you could try using multiple-sources feature starting v2.6 release (not yet released). Then you will be able to access helm charts from one repo and values from another repo.

Doc Reference: https://argo-cd.readthedocs.io/en/release-2.6/user-guide/multiple_sources/

**Comment by 64J0** [comment]
Great, thanks for the tip @ishitasequeira

**Comment by blakepettersson** [comment]
Closing since this feature has been out for a while: https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/
