### ISSUE TITLE
Support partial filtering by name

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#12142]
# Summary

Support partial filters on `name`

# Motivation

I'm trying to filter for all pods that start with `argocd-repo`, e.g. on https://cd.apps.argoproj.io/applications/argocd/argo-cd?view=tree&resource=

# Proposal

How do you think this should be implemented?

Allow `*` to be used as a wildcard:
https://cd.apps.argoproj.io/applications/argocd/argo-cd?view=tree&resource=name%3Aargocd-repo-*

**Comment by alexef** [comment]
@jsoref this is a duplicate of https://github.com/argoproj/argo-cd/issues/11781, let's vote that up instead.
