### ISSUE TITLE
[UI] Improve input style

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1217]
We've got feedback saying that sometimes inputs looks like a delimiter rather than input. We should improve input design to remove confusion.

**Comment by farrellit** [comment]
It's also difficult to focus the input box.  I click on the title; it doesn't focus.  I click on the line; it doesn't focus.  I click somewhere between; it focuses.  

This UI decision might look good to some eyes, but it's frustratingly difficult to use.  

![image](https://user-images.githubusercontent.com/6018542/55639769-c8a97780-578f-11e9-872e-466bc29a5594.png)

**Comment by alexmt** [comment]
Fixed. Now input can be focused by clicking on the label.
