### ISSUE TITLE
Failed to verify token: failed to verify token: oidc: expected audience "argo-cd" got  "argo-cd-cli"

### ISSUE THREAD

**Issue by WojtekTomaszewski** [argoproj/argo-cd#12170]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

With Dex connector configured to use our GHE instance, I am able to login into GUI and SSO login to CLI also looks to be successful but all commands end up with invalid session and failed token validation error.

**Version**

```shell
argocd version
argocd: v2.5.7+e0ee345.dirty
  BuildDate: 2023-01-18T04:28:20Z
  GitCommit: e0ee3458d0921ad636c5977d96873d18590ecf1a
  GitTreeState: dirty
  GoVersion: go1.19.5
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.5.8+bbe870f
```

**Logs**

```
argocd-dex-server-75d9555bc9-bfbmh dex time="2023-01-27T06:38:05Z" level=info msg="login successful: connector \"github\", username=\"xxxxxx\", preferred_username=\"xxxxxx\", email=\"xxxxxx\", groups=[\"xxxxxx:xxxxxx\"]"
```

```
argocd-server-58f7f86d74-8bbqs argocd-server time="2023-01-27T07:15:21Z" level=warning msg="Failed to verify token: failed to verify token: oidc: expected audience \"argo-cd\" got [\"argo-cd-cli\"]"
```

**Comment by flecno** [comment]
I have the same problem with argocd v2.5.8. Downgrading to v2.5.7 works, but security patch from the latest version is then missing.

**Comment by crenshaw-dev** [comment]
I plan to have the fix released in the next 3 hours.
