### ISSUE TITLE
ArgoCD getting crashed. 

### ISSUE THREAD

**Issue by rchinni-mn** [argoproj/argo-cd#12181]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jaideepr97** [comment]
Hi @rchinni-mn could you fill out the details for this issue?

**Comment by rchinni-mn** [comment]
ArgoCD version: v2.5.6+9db2c94

**Comment by blakepettersson** [comment]
Closing due to insufficient information
