### ISSUE TITLE
Store more commit metadata in application revision history

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1219]
The application revision history contains commit sha which was used during deployment. In addition, to the commit sha it is useful to persist more metadata such as:
- commit author
- tags associated with the commit

The metadata will be visible in Argo CD UI and should help user to understand what was deployed.

**Comment by alexec** [comment]
Working.

**Comment by alexec** [comment]
@alexmt I'm adding author and message, but not tags (harder), any reason for tags?

**Comment by alexec** [comment]
@alexmojo, @narg95 , @code0x58 - thoughts?

**Comment by alexec** [comment]
![before-first-sync](https://user-images.githubusercontent.com/1142830/59636978-a4600480-9109-11e9-9f72-a132b8fbfa95.png)
![after-first-sync](https://user-images.githubusercontent.com/1142830/59636984-a6c25e80-9109-11e9-8573-87b4999f3f1d.png)
![sync-status](https://user-images.githubusercontent.com/1142830/59636988-a7f38b80-9109-11e9-8349-d289aa9e8a13.png)
![history](https://user-images.githubusercontent.com/1142830/59636989-a924b880-9109-11e9-85f1-8104e09f37c5.png)

**Comment by alexec** [comment]
So, regarding the solution, we have two options 

(a) Store the meta-data when we execute. This impacts the spec, adding fields that would be null for older apps.
(b) Get the data as needed via an API call. 

This needs to be considered alongside these questions:

(i) Do you want to see the data in the application panel (as per "After First Sync" above)
(ii) Do you need to see it when you select an item open the application history & rollback panel (see below)? Or do you need to see if for every item?

![Screen Shot 2019-06-17 at 17 26 44](https://user-images.githubusercontent.com/1142830/59645119-1b56c680-9125-11e9-8b58-b76a88206ddd.png)

**Comment by alexec** [comment]
Finally, what is actually needed/wanted? 

x) Author
y) Message
z) Tags

**Comment by jpbelanger-mtl** [comment]
Does it make sense to simply link to the commit in github? commit message can be very verbose in some situation and might make the UI harder to display. And since github is already showing all that info, open in a new tab/window might be enough for the usecase.

In our case we have CI doing the commit and the message contains a lot of information about the generation of that commit so a link would have been enough for most of our needs.

**Comment by OmerKahani** [comment]
We are using a different repo for the helm chart, that contains all the app of the team. So one repo has many helm chart from different code repo. The Deploy process is to change to docker image tag and sync. 
It would be nice to have the message in the history (so we can add in the message the commit from the original code repo). And it would be helpful to see it on all the items (and after the first sync), but in this trade-off getting it from the API is better.

**Comment by okapoor** [comment]
This is very useful and will provide much better at-a-glance visibility into deployments and history. I look forward to this feature being released.

**Comment by alexec** [comment]
# App Page
![Screen Shot 2019-06-19 at 17 38 17](https://user-images.githubusercontent.com/1142830/59810264-44a85b80-92b9-11e9-913b-9411030cc33f.png)
# History Page
![Screen Shot 2019-06-19 at 17 38 23](https://user-images.githubusercontent.com/1142830/59810265-44a85b80-92b9-11e9-8583-c2dc1a51e29c.png)
# Tooltip For More Info
![Screen Shot 2019-06-19 at 17 40 20](https://user-images.githubusercontent.com/1142830/59810283-55f16800-92b9-11e9-8f34-8ed932da4024.png)

**Comment by alexec** [comment]
@jpbelanger-mtl I think your idea is neat. How would you deal with private repos?

**Comment by jpbelangerupgrade** [comment]
at the repo CRD definition I would add a addition parameters with replaceable variables:

ie:
`revisionLink: https://github.com/argoproj/argo-cd/commit/${revision}`
`tagLink: https://github.com/argoproj/argo-cd/tree/${tag}`

That would probably fit most private repo that accept the revision/tag in the url. 

So it would be optional that you define or not. And remove the logic of maintaining all the cloud provider config in argo-cd

**Comment by jpbelanger-mtl** [comment]
at the repo CRD definition I would add a addition parameters with replaceable variables:

ie:
`revisionLink: https://github.com/argoproj/argo-cd/commit/${revision}`
`tagLink: https://github.com/argoproj/argo-cd/tree/${tag}`

That would probably fit most private repo that accept the revision/tag in the url. 

So it would be optional that you define or not. And remove the logic of maintaining all the cloud provider config in argo-cd

**Comment by alexec** [comment]
I've realised that this works really well when there's one app in a repo, but when there are multiple apps, then the commit and it's related author and message will most likely relate to another app. 

In this scenario, this data becomes deceptive - a human needs to take a look and make a decision. 

Another option would be to verify that the commit refers to files within the path. 

Hmmm...

**Comment by jpbelanger-mtl** [comment]
That is very true. and unless you start doing some git tree scan to get the latest commit of the folder/file that the argoApp relates to, it will be hard to actually show something that is context based.

But then that's not different from the current commit "hash" shown. It's the commit of the whole repo.

**Comment by narg95** [comment]
A bit late to the conversation :)

In my case our deployments are tagged based, so I had the need to check
also the tags associated to that commit.

That is great!
You are making a great job !

**Comment by anarcher** [comment]
It's a really useful feature when do rollback! :-}  Sometimes, It would be great if argo-rollouts' status(steps?) is displayed in histories.

**Comment by alexec** [comment]
@dthomson25 ☝️ rollouts comment.
