### ISSUE TITLE
Menu items for copy menu in logs aren't of equal width so text doesn't align

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#12199]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Menu items for copy menu in logs aren't of equal width so text doesn't align

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/argocd/argo-cd?view=tree&node=%2FPod%2Fargocd%2Fargocd-application-controller-0%2F0&tab=logs
2. Click a line number
3. Click ⋯

**Expected behavior**

* Each icon should have the same horizontal center/general width
* Each menu item should start at the same horizontal position 

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/215297510-8f8b66b6-6475-4792-a811-cdea862c5e0f.png)

**Version**

```shell
{
    "Version": "v2.6.0+193cf76",
    "BuildDate": "2023-01-28T03:26:14Z",
    "GitCommit": "193cf76e123247b75f04f4d2ca0e82d7950db4cb",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by andrii-korotkov-verkada** [comment]
Seems like line numbers and this functionality were removed altogether.
