### ISSUE TITLE
Before applying resources, run kubectl apply --dry-run to detect issues

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#122]
Before actually performing a `kubectl apply`, we should first do at `kubectl apply --dry-run` to perform basic validation of the manifests. This way, we don't apply a subset of the manifests, only to hit the error midway through the apply, which would leave the app in an inconsistent state.

**Comment by merenbach** [comment]
@jessesuen agreed that a dry run is a good idea as a first step.  As a second step to help ensure atomicity, how sensible would it be to queue up a job to fully revert any and all changes after some period of time, and only cancel that job once all other steps have completed successfully?

**Comment by jessesuen** [comment]
Fixed in 2664db3e4072b96176d286f7a91f03d08e5cc715.

Your feature sounds a lot like automated rollback, which would be a feature in and of itself. I think it's a good idea, but theres enough customization in that logic which would warrant a workflow to handle it.
