### ISSUE TITLE
Need to reload argocd-server config or restart pods after removing data.oidc.config from argocd-cm.

### ISSUE THREAD

**Issue by jameshearttech** [argoproj/argo-cd#12221]
**Describe the bug**

After removing data.oidc.config from argocd-cm argocd-server is not updated. I discovered this when switching from native OIDC to Dex. The Dex config was updated by adding data.dex.config, but the native OIDC was still doing authorization using old data.oidc.config.

**To Reproduce**

Have not attempted to reproduce.

**Expected behavior**

The configuration of argocd-server should be updated after data.oidc.config is removed from argocd-cm through a config reloader or whatever mechanism is in use or the pods should be restarted.

**Screenshots**
![image](https://user-images.githubusercontent.com/67252279/215625568-149fd94c-905c-4bba-b976-8b6ee05072b3.png)
![image](https://user-images.githubusercontent.com/67252279/215625569-29e15e71-3c06-46f6-bb6e-2495a8549259.png)
![image](https://user-images.githubusercontent.com/67252279/215625570-64028e3e-d0a1-41a7-b567-7b8ee3f57c58.png)
![image](https://user-images.githubusercontent.com/67252279/215625572-ce7eb03f-0927-4add-b072-ba07027de487.png)

**Version**

```
$ argocd version
argocd: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:55:00Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.9+e5f1194
  BuildDate: 2023-01-27T23:27:14Z
  GitCommit: e5f1194a6de78cc1124179a4c9bb1ae3484fb77d
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**
* See screenshots.

**Comment by nikos445** [comment]
Almost same issue here... 
I get errors like:  

- `Error while dialing dial tcp: lookup argocd-repo-server argocd`     
- `time="2023-02-06T21:34:38Z" level=warning msg="Failed to save clusters info: dial tcp 10.100.78.107:6379: i/o timeout" argocd`

**Tried**: 
  - Restarting  all pods together.. doesn't fix problem.. 
  - Redeploying...


**TEMPORARY SOLUTION**: 
- I need to restart `argocd-redis` and `argocd-repo-server` in sequence... meaning that
- I need to restart all pods and then restart `redis` after all pods seem healthy and then restart `repo-server` after redis is again healthy.


---

Same issue as this..

 [https://stackoverflow.com/questions/73276522/argocd-transport-error-while-dialing-dial-tcp-lookup-argocd-repo-server](https://stackoverflow.com/questions/73276522/argocd-transport-error-while-dialing-dial-tcp-lookup-argocd-repo-server)

And this... 

[https://stackoverflow.com/questions/70120083/not-able-to-connect-argocd-with-gitlab-repository](https://stackoverflow.com/questions/70120083/not-able-to-connect-argocd-with-gitlab-repository) 

**NOTE**: `IT IS NOT A DNS ISSUE... I Tested and Verified everything 1000%`

### **Also please consider that Redis is seem healthy but it does not respond...**

My ArgoCD Deployment Details:

```
{
    "Version": "v2.6.0+acc554f",
    "BuildDate": "2023-02-06T21:17:26Z",
    "GitCommit": "acc554f3d99010e0353b498a595844b30090556f",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

Kubernetes info:
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jessesuen** [comment]
Hot-reload of configmap changes has been flakey/broken for some time. There [were attempts to fix it](https://github.com/argoproj/argo-cd/pull/9778), but they ended up being insufficient.

Related: https://github.com/argoproj/argo-cd/issues/10707

Workaround is to restart argocd-server pods ATM.

**Comment by drpaneas** [comment]
This issue should be fixed by now, thx to https://github.com/argoproj/argo-cd/pull/12076 being merged.

**Comment by jameshearttech** [comment]
@drpaneas I'll go ahead and close it.

**Comment by blakepettersson** [comment]
I'm not sure #12076 will fix this issue, since that PR is related to reloading of the certificate rather than the reloading of configmaps 🤔
