### ISSUE TITLE
gRPC interceptor logger is not honoring the global logrus loglevel

### ISSUE THREAD

**Issue by rebelthor** [argoproj/argo-cd#1222]
It appears that the gRPC interceptor logger is not honoring the global logrus loglevel, thus not allowing control over its loglevel via the command line parameters.

**Steps to reproduce:**
* start argocd-repo-server with --loglevel warn:
`argocd-repo-server --loglevel warn`
* wait until gRPC logs some info messages:
`time="2019-03-05T08:32:51Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListDir grpc.service=repository.RepositoryService grpc.start_time="2019-03-05T08:32:48Z" grpc.time_ms=2827.676 span.kind=server system=grpc
time="2019-03-05T08:32:51Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListDir grpc.service=repository.RepositoryService grpc.start_time="2019-03-05T08:32:48Z" grpc.time_ms=2863.449 span.kind=server system=grpc
time="2019-03-05T08:32:51Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListDir grpc.service=repository.RepositoryService grpc.start_time="2019-03-05T08:32:48Z" grpc.time_ms=2832.011 span.kind=server system=grpc`

**Expected result:**
gRPC logs shouldn't contain "Info" messages

**Actual result:** 
it is impossible to control loglevel for gRPC logs

**Potential solution:** 
pass the desired loglevel to the log object we give to the interceptor:
https://github.com/argoproj/argo-cd/blob/master/reposerver/server.go#L50

**Comment by jessesuen** [comment]
Fixed with this change:
https://github.com/argoproj/argo-cd/pull/1221/commits/d1dcafe759dbc5609807cd6c7a15c0d0ca2a0d7a

Will be in v0.12

**Comment by jessesuen** [comment]
Fixed
