### ISSUE TITLE
Cannot Sync project, field is immutable with Openshift

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1223]
When trying to sync a namespace with Openshift it appears that Openshift under water creates a project which is based on the same content of the namespace yaml. Because of this the labels which are set by argo als appear on the project resource. Then argo sees this as out of sync. It is not possible to remove the labels from the project since they are bound to the namespace. When trying to remove the label:

  labels:
    app.kubernetes.io/instance: generic-all-cluster

the following message appears:

* metadata.labels[app.kubernetes.io/instance]: Invalid value: "generic-all-cluster": field is immutable, try updating the namespace

So project is set to be pruned in argocd, but this is not correct

I tried to apply the `project` resource also but then also the immutable error occurs because it tries to update the object labels which is not permitted

**Comment by jessesuen** [comment]
I think the resource exclusion feature in v0.12 will help in this situation.

**Comment by jessesuen** [comment]
Duping to https://github.com/argoproj/argo-cd/issues/1224 to group all openshift issues
