### ISSUE TITLE
 parsing time "xxxx+0000" as "2006-01-02T15:04:05Z07:00": cannot parse "+0000" as "Z07:00"

### ISSUE THREAD

**Issue by alexciw** [argoproj/argo-cd#12239]
When synchronization is triggered via webhook, argocd server reports an error. By adding the corresponding log, I found that the error is returned when executing the a.gitlab.Parse method.
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/58928559/216031414-e9fd7cd0-575a-4d1c-9f37-e905861beabe.png">
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/58928559/216031931-f81784b1-a295-4bc0-a80a-28a6909da20d.png">

**Comment by jessesuen** [comment]
Are you saying that Gitlab sends events as `2023-02-09T00:07:57+00:00` but Argo CD expects this it like `2023-02-09T00:07:57Z`? If so this is a real bug.

I do see in gitlab webhook docs they have an example as `2011-12-12T14:27:31+02:00` so I think you are right:
https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#push-events

This may also mean that we never properly supported gitlab webhook events and this is a day zero bug.

Are you interested in contributing the fix?

**Comment by Thedarkmatter10** [comment]
Hii @jessesuen I'm interested to come up with a solution .

**Comment by Thedarkmatter10** [comment]
Hello @jessesuen @xincli  i want to work on that issue
Can I have update.

**Comment by danmanners** [comment]
FYI I'm running into this too after adding a new user and copying the `passwordMtime` from another existing user.
<img width="343" alt="image" src="https://user-images.githubusercontent.com/17593824/220010854-ba70ee04-c928-4cbd-b95f-bcb49dd90d66.png">

**Comment by xincli** [comment]
@Thedarkmatter10 sure

**Comment by 1garo** [comment]
@Thedarkmatter10 you plan to work on it? If not, I would like to try

**Comment by 1garo** [comment]
I could not replicate the problem, feels like it's solved, any update on this?

**Comment by xincli** [comment]
I figured out why: the time passed by our private gitlab webhook is not the time in RFC3339 format.

**Comment by thecooldrop** [comment]
I would like to work on this issue. I am not sure though if this is a bug at all. 

Currently to me this does not seem to be an issue in ArgoCD itself, but rather in the webhooks package. We are merely passing the request which we become from Gitlab to the webhooks package implementation for parsing those requests into objects. It is here that the failure occurs. Also from what I see the request data is not changed in any way, thus for me further reinforcing the idea that this is not intrinsically an issue with ArgoCD.

The best resource on this issue I could find is the comment from Nick Thomas in this https://gitlab.com/gitlab-org/gitlab-foss/-/issues/55644 Gitlab issue, indicating that the timestamps in webhooks should conform to the ISO 8601 format, which to me seems to be the case.

**Comment by thecooldrop** [comment]
> FYI I'm running into this too after adding a new user and copying the `passwordMtime` from another existing user. <img alt="image" width="343" src="https://user-images.githubusercontent.com/17593824/220010854-ba70ee04-c928-4cbd-b95f-bcb49dd90d66.png">

Please refer to my comment above, but for some reason your timestamp is not in ISO 8601 format. Could you provide more information about your configuration?

**Comment by akshat-g-07** [comment]
Hey @xincli,
I can still see the issue open but earlier you mentioned that you figured it out.
Is the issue still open?
If yes, I would like to contribute.

**Comment by xincli** [comment]
I now believe that this is not an issue, but is triggered by the private code repository webhook's time format being inconsistent with argocd. issues should be able to be closed.
