### ISSUE TITLE
Sync status for a pruned entry is inconsistent with normal items

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#12263]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

`Synced` items show 💚 `<type>/<name> unchanged`
`Pruned` items show 🤎 `pruned`

**To Reproduce**

1. Go to an application that needs pruning
2. Click sync
3. Check prune
4. Click sync status
5. scroll down / wait / repeat util you see the item

**Expected behavior**

1. Don't use a ❤️ for pruning (how about using 🗑️ ?)
2. Either always include `<type>/<name>` prefix in the log line or never include it, but don't only sometimes include it.

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/216436381-e614d8c3-c1f2-4496-93d0-95fc8cfcb21a.png)

**Version**

```shell
{
    "Version": "v2.4.11+3d9e9f2",
    "BuildDate": "2022-08-22T09:13:16Z",
    "GitCommit": "3d9e9f2f95b7801b90377ecfc4073e5f0f07205b",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.1+g5cb9af4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by andrii-korotkov-verkada** [comment]
Yeah, I think we should standardize this as something like "configmap unchanged", since the name is already provided in a separate column.

**Comment by jsoref** [comment]
That's perfectly acceptable

**Comment by surajyadav1108** [comment]
Seems reasonable
