### ISSUE TITLE
Side-by-side diff is a bad default for mobile portrait view

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#12277]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Side-by-side diff in mobile portrait view doesn't have anywhere near enough space to be usable 

**To Reproduce**

1. Go to an out of sync resource
2. Scroll down to the area that could show a diff
3. Tap the diff "tab" 

**Expected behavior**

For narrow screens, default to inline view 

**Screenshots**
![Screenshot_20230203-085146](https://user-images.githubusercontent.com/2119212/216620024-0d9e4bcf-f258-46f1-ae57-4b63afafa9f3.png)

**Version**

```shell
{
    "Version": "v2.6.0+584428e",
    "BuildDate": "2023-01-19T17:14:49Z",
    "GitCommit": "584428edaf535258924912a191a97dde8a5c5d3d",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
We don't really claim support for mobile and I'm aware of other basic functionality that does not work on mobile so marking this wont fix.
