### ISSUE TITLE
2.6 RCx:  "Failed to load data" error pops up when clicking options for non deployed elements in argocd UI

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [argoproj/argo-cd#12274]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
In argocd UI, when clicking options for a non deployed item , instead of appearing the menu with [Details|Sync|Delete], it pops up an error with the message "Failed to load data, please try again"
This error only happens with the non deployed elements.

Running the sync command from the top sync button works as expected.

 ##

**To Reproduce**

**Expected behavior**
It should display the standard options menu [Details|Sync|Delete]

**Screenshots**
![Screenshot from 2023-02-03 09-33-00](https://user-images.githubusercontent.com/56038098/216553914-7a28906e-23c8-4915-a7d8-babddd907250.png)

![Screenshot from 2023-02-03 10-33-12](https://user-images.githubusercontent.com/56038098/216564771-1ca5c89c-95ac-4cb0-a2b6-6bbfa7b8daac.png)

![Screenshot from 2023-02-03 09-48-39](https://user-images.githubusercontent.com/56038098/216554206-863cf6a4-db52-4a6e-a189-62c9e9ba9c30.png)

**Version**

```shell
argocd 2.6RCx
```

**Logs**

```
{"error":"ServiceAccount  atlantis not found as part of application atlantis","code":3,"message":"ServiceAccount  atlantis not found as part of application atlantis"}
```

**Comment by jessesuen** [comment]
This seems like a valid bug. Just curious if you know if this is new to Argo CD v2.6 vs. not present in v2.5

**Comment by jessesuen** [comment]
Duplicating to https://github.com/argoproj/argo-cd/issues/12338
