### ISSUE TITLE
Include web server/api server version in web server errors

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#12282]
# Summary

When returning an error that comes from the api side, the web server should include the version of the web server and the version of the api server

# Motivation

I'm deploying an upgrade of ArgoCD from 2.4 to 2.6. The browser has a version of the ArgoCD UI loaded from before the upgrade starts. At some point I get an error:

>  Unable to load data: unknown method ListPlugins for service repository.RepoServerService

It's likely this is because one of the three components (web app in browser, web server, API server) is out of sync. If this information was returned, the web app could compare the two versions with its own and warn. Or even offer to reload if its version doesn't match the web server version

# Proposal

Include web server/api server version in web server errors (in JSON/HTTP headers?)

**Comment by jsoref** [comment]
Probably better phrased as “I’m argocd-server v X, the failure came from argocd-repo-server v Y”

**Comment by jsoref** [comment]
> Probably better phrased as “I’m argocd-server v X, the failure came from argocd-repo-server v Y”

**Comment by jessesuen** [comment]
While I agree that Argo CD UI could do a better job detecting when UI assets change, thereby encouraging users to perform a refresh of their UI, returning server versions as part of error responses is not how we would accomplish this.
