### ISSUE TITLE
RBAC stopped working after upgrading from 2.2.4 to 2.4.16

### ISSUE THREAD

**Issue by vijayrr007** [argoproj/argo-cd#12291]
I've upgraded from 2.2.4 to 2.4.16. After the upgrade, I was able to login using Dex but my RBAC wasn't functioning.

Below id the policy before upgrading.

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  scopes: '[groups, email]'
  policy.csv: |
    p, role:none, *, *, */*, deny
    g, some_group, role:admin

Do I need to change anything in the policy?

```

**Comment by jessesuen** [comment]
This line does not appear valid, so this appears to be your problem. I am not sure how it was working in v2.2 but it probably was unintentionally functioning.

```
p, role:none, *, *, /, deny
```
