### ISSUE TITLE
ArgoCD should be able to pick the Helm values from a different directory otherthan the parent directory

### ISSUE THREAD

**Issue by vsirimalla** [argoproj/argo-cd#12292]
# Summary
By default the application is expecting the overriding helm values.yaml file to be avail at the root level of the repo.

# Motivation
This ability will help in organizing the overriding files nicely.

# Proposal
Either browse through all the files the recursively to choose the right overrides values.yaml or honor the free form entry of the relative values.yaml file.

**Comment by jaideepr97** [comment]
Hi @vsirimalla 
I think you should already be able to do this
have you seen https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#values-files?

**Comment by vsirimalla** [comment]
hi @jaideepr97 
Yes I have tried that. It isn't honoring the file if I hard code like below:

``` yaml
     helm:
      valueFiles:
        - config/myapp-uat/values-myapp.yaml
   ```

It is certainly accepting the *.yaml files that it could find in the root of the directory (where Helm Chart exists) and even prepopulate them in the list when the application is configured from the UI console.

I am using the latest : v2.5.4+86b2dde

**Comment by jessesuen** [comment]
The intended behavior is:

> Values files must be in the same git repository as the Helm chart. The files can be in a different location in which case it can be accessed using a relative path relative to the root directory of the Helm chart.

It is too late to change this behavior -- it would be a breaking change. If you need to access outside, you may use relative paths.

**Comment by vsirimalla** [comment]
I am not sure why this is closed.
Values file is in the same repository as where helm charts is. UI isn't accepting the values from a different directory with in the same repo.

It only works when the values file is at the root directory (along side Chart.yaml

If this is expected to work, I can assert that its not working as expected.

I can create a sample project and show the error.

**Comment by kolesaev** [comment]
This shoud solve:
https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
