### ISSUE TITLE
v2.5.9+e5f1194 - I don't see any pods in my apps

### ISSUE THREAD

**Issue by mmisztal1980** [argoproj/argo-cd#12294]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I've provisioned the latest ArgoCD from HELM via artifacthub and added some applications. I don't see any pods in the tree view. In the pod view I see a "Your application has no pod groups" message. I'm under impression that this is some new feature. But I've failed to find any documentation on "pod groups" and google doesn't return anything of use either.

**To Reproduce**

Provision argo and add ANY application.

**Expected behavior**

I'm expecting to see the pods deployed by argo. They are running, but they are not visible in the UI

**Screenshots**

![image](https://user-images.githubusercontent.com/1357057/216845966-6874bd0b-a154-4a83-a94a-3afbfb06ff0b.png)
![image](https://user-images.githubusercontent.com/1357057/216845979-9d8309c1-d0ce-4cb6-97ae-713e8f254a87.png)

**Version**

```shell
argocd version --server <redacted> --grpc-web
argocd: v2.0.3+8d2b13d.dirty
  BuildDate: 2021-05-27T19:03:20Z
  GitCommit: 8d2b13d733e1dff7d1ad2c110ed31be4804406e2
  GitTreeState: dirty
  GoVersion: go1.16.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.5.9+e5f1194
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexef** [comment]
From the screenshots, I can't see the pods in the Tree view either. Are you sure your deployment has pods? Do they show up in List view?

**Comment by mmisztal1980** [comment]
I'm 100% sure all of my deployments have pods, and they're "ready". They're not showing anywhere. I've noticed there were some UI changes recently

**Comment by alexef** [comment]
(in the tree view) are there any filters enabled? I also don't see any ReplicaSets next to your Deployment object.

**Comment by mmisztal1980** [comment]
@alexef 
![image](https://user-images.githubusercontent.com/1357057/216847366-851fc3a1-b6a3-4643-bac8-10e498eb6b0b.png)
No filters are enabled. No replicasets are showing anywhere. It used to work fine with the old version (I upgraded from HELM Chart v 4.9.16)

**Comment by alexef** [comment]
Do they show with "Show Orphaned" enabled?

**Comment by crenshaw-dev** [comment]
Check the app’s project. Make sure pods are allowed resources for that project.

**Comment by mmisztal1980** [comment]
@crenshaw-dev that worked
![image](https://user-images.githubusercontent.com/1357057/216848116-da3d45bf-287c-4004-b49d-51a9d307fefb.png)

Weird, pods and replicasets were provisioning just fine. 
Is this documented somewhere?

**Comment by crenshaw-dev** [comment]
There was a security vulnerability that let disallowed resources into the resource tree. When you upgraded the chart, you must have left a version that still had the vulnerability.

**Comment by crenshaw-dev** [comment]
I believe this is the one: https://github.com/argoproj/argo-cd/security/advisories/GHSA-2f5v-8r3f-8pww

**Comment by mmisztal1980** [comment]
gotcha, thank you for the input guys
