### ISSUE TITLE
ArgoCD start to DDoS related Helm Repository

### ISSUE THREAD

**Issue by fotto1** [argoproj/argo-cd#12314]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Our ArgoCD Application start to DDoS our Helm Repositories.

For our deployment we use gitops, which uses an app of apps approach to create nearly 64 different ArgoCD Applications. For our gitops we have multiple branches and do multiple deployments on same argocd environment in one AWS EKS Cluster.

We have 32 Deployments means 2048 ArgoCD Applications based on same helm repository + 32 Argo CD Application running as app of apps over gitops.

**To Reproduce**

1. Configure a Gitops Repository with a set of ArgoCD Applications using same Helm Chart Repository and a sync policy of 1 minute.
1. Greate multiple of this ArgoCD Applications by using gitops. 
1. Check access log on Helm Chart Repository (I use jFrog Artifactory), for calls to `index.yaml` File.

**Expected behavior**

After ArgoCD calls always the same `index.yaml` File in the Helm Chart Repository I would expect that it is cached in ArgoCD and used as shared resource between ArgoCD Applications. Not that every single ArgoCD Application calls the index.yaml File itself.

Our `index.yaml` has 20.26 MB x 2048 ArgoCD Applications calling one time per Hour for 12 hours. That makes 20.26 MB x 2048 x 12 = 497.909,76 MB ~= 486,24 GB per Day.

That is what we also see from our access logs in our Helm Repository.

Our expectation is 20,26 MB x 24 x 60 to check file onces per minute which should result in 28,49 GB per day, so that file is cached centrally.

**Version**

```shell
argocd: v2.6.0+acc554f
  BuildDate: 2023-02-06T21:44:18Z
  GitCommit: acc554f3d99010e0353b498a595844b30090556f
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
Handling connection for 8081
Handling connection for 8081
argocd-server: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:30:17Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Comment by jessesuen** [comment]
The feature request makes sense. We need the equivalent of what we are currently doing with `git ls-remote` but for a helm chart repository.

For the implementation, I feel we could cache the index.yaml in redis, and make subsequent requests for index.yaml with the `If-Modified-Since` header. If the response is HTTP 304, then we can use the cache result.

This all presumes jFrog Artifactory supports the `If-Modified-Since` header.

@fotto1 are you open to submitting a fix for this?

**Comment by fotto1** [comment]
@jessesuen sounds like a good proposal. Maybe you have somewhere the link to merge request for the similar change on git repositories.

Can you provide some guidance which classes must be touch to implement the change you proposed?

After that I will check if I can do the change by my own.

**Comment by fotto1** [comment]
Seems also related to the problem described by @hmoravec here https://github.com/argoproj/argo-cd/issues/8698

**Comment by able8** [comment]
We often encounter `helm dependency build` failed timeout after 1m30s. https://github.com/argoproj/argo-cd/issues/3977#issuecomment-1851676924
It would be nice to cache the helm charts.
```
rpc error: code = Unknown desc = Manifest generation error (cached): 'helm dependency build' failed timeout after 3mOs
```

**Comment by fotto1** [comment]
Based on multiple discussion also with my colleague @andrei-gavrila we identified the underlying issue.

Seems argocd use for every helm chart an repo url and a cache. Means every configured application has an owen cache and store a index.yaml file.

https://github.com/argoproj/argo-cd/blob/565aa8e1f5b4ea2ad8380a3347de774f6e0a9920/util/helm/client.go#L105
```golang
type nativeHelmChart struct {
	chartCachePaths argoio.TempPaths
	repoURL         string
	creds           Creds
	repoLock        sync.KeyLock
	enableOci       bool
	indexCache      indexCache
	proxy           string
}
```

This is how the index is retrieved:

https://github.com/argoproj/argo-cd/blob/565aa8e1f5b4ea2ad8380a3347de774f6e0a9920/util/helm/client.go#L239
```golang
if !noCache && c.indexCache != nil {
    if err := c.indexCache.GetHelmIndex(c.repoURL, &data); err != nil && err != cache.ErrCacheMiss {
        log.Warnf("Failed to load index cache for repo: %s: %v", c.repoURL, err)
    }
}

if len(data) == 0 {
    start := time.Now()
    var err error
    data, err = c.loadRepoIndex()
    if err != nil {
        return nil, err
    }
    log.WithFields(log.Fields{"seconds": time.Since(start).Seconds()}).Info("took to get index")

    if c.indexCache != nil {
        if err := c.indexCache.SetHelmIndex(c.repoURL, data); err != nil {
            log.Warnf("Failed to store index cache for repo: %s: %v", c.repoURL, err)
        }
    }
}
```

Unfortunately, this is how it's really retrieved (no helm involvement):

https://github.com/argoproj/argo-cd/blob/565aa8e1f5b4ea2ad8380a3347de774f6e0a9920/util/helm/client.go#L300
```golang
func (c *nativeHelmChart) loadRepoIndex() ([]byte, error) {
	indexURL, err := getIndexURL(c.repoURL)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, indexURL, nil)
	if err != nil {
		return nil, err
	}
	if c.creds.Username != "" || c.creds.Password != "" {
		// only basic supported
		req.SetBasicAuth(c.creds.Username, c.creds.Password)
	}

	tlsConf, err := newTLSConfig(c.creds)
	if err != nil {
		return nil, err
	}

	tr := &http.Transport{
		Proxy:             proxy.GetCallback(c.proxy),
		TLSClientConfig:   tlsConf,
		DisableKeepAlives: true,
	}
	client := http.Client{Transport: tr}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		return nil, errors.New("failed to get index: " + resp.Status)
	}
	return io.ReadAll(resp.Body)
}
```

No helm involvement, see the http.NewRequest(http.MethodGet, indexURL, nil) call and yes that means every helm chart has its own cache.

![MicrosoftTeams-image (10)](https://github.com/argoproj/argo-cd/assets/12606402/5201f75e-9e70-42af-ad95-c46b1145e917)

The original feature commit that enabled caching in argocd (includes an environment variable to configured cache lifetime + the cache is set on the client - eg. 1000 charts, one repo, one client -> one cache) 

https://github.com/argoproj/argo-cd/commit/5889bbb3301ed119a892a640c03f280337ef3961

Not sure why this have been changed but the change explains our problem.
