### ISSUE TITLE
Don't use deprecated kustomize `vars` feature

### ISSUE THREAD

**Issue by james-callahan** [argoproj/argo-cd#12328]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Kustomize has deprecated `vars` and new versions produce a warning when it is used.

`vars:` is currently used in a single place in this repository: `manifests/base/redis/kustomization.yaml`

**To Reproduce**

```
$ kustomize build manifests/base -o /dev/null
# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
``

**Expected behavior**

No warning from `kustomize`

**Comment by jessesuen** [comment]
Is this a request to not update kustomize in Argo CD? If so, you should know Argo CD can support multiple versions of kustomize:

https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml#L227-L229

**Comment by james-callahan** [comment]
> Is this a request to not update kustomize in Argo CD? I

No.
ArgoCD's own kustomize manifests use a deprecated kustomize feature.

**Comment by jessesuen** [comment]
Ah understood. Should have read the description more carefully.
