### ISSUE TITLE
argo-cd 2.6: UI fails to load resource-details sliding panel when resource hasn't been created yet

### ISSUE THREAD

**Issue by jphelton** [argoproj/argo-cd#12338]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I create an argo-cd application with Auto-Sync disabled and then attempt to view the application in the argo-cd UI, I am unable to open either the "resource details slider panel," or the "resource tree node menu".

The cause seems to be missing error checks to the "ListResourceLinks" API in the client code.  Because the resource doesn't exist yet, the API returns a 400 HTTP response, with an error message to the equivalent of:

 ```json
{
    "error":"{kind} {group} {name} not found as part of application {appName}",
     "code":3,
     "message":"{kind} {group} {name} not found as part of application {appName}"
}
```

Relevant Code Links:

*resource details slider bar*
https://github.com/argoproj/argo-cd/blob/master/ui/src/app/applications/components/resource-details/resource-details.tsx#L289

*resource tree node menu*
https://github.com/argoproj/argo-cd/blob/master/ui/src/app/applications/components/utils.tsx#L494

Other API calls will also return a 400 when the resource doesn't exist yet `GetResource` or `ListResourceActions`.  In those cases the UI usually handles this with a `.catch(() => [] as MenuItem[])` or `.catch(() => null)` depending on the context.

**To Reproduce**

1. Create a new application, **with Auto Sync disabled.**
    - In my case I used helm, but any app type should work 
2. Then open the application in the UI and attempt to open the resource details slider bar
3.  You should get an empty panel with the generic error message "Failed to load data, please try again."

**Expected behavior**

* I would expect to see the same behavior that I saw in earlier versions of argo-cd. the resource details slider should open and show an empty manifest, with a health entry of "Missing"

**Screenshots**

#### Resource Tree Node Menu

![current-behavior-resource-tree-node-menu](https://user-images.githubusercontent.com/14790953/217549274-4dd6666c-877b-428b-84ff-7bebf7e1da78.png)

#### Resource Details Sliding Panel
![current-behavior-resource-details-sidebar](https://user-images.githubusercontent.com/14790953/217549384-036f9a6b-7614-4cc6-a579-b7428f791aeb.png)

#### Resource Tree Node Menu
![expected-behavior-resource-tree-menu](https://user-images.githubusercontent.com/14790953/217550280-6bd11607-f1be-4087-8fb2-38d08c3c9e8d.png)

#### Resource Details Sliding Panel
![expected-behavior-resource-details-sidebar](https://user-images.githubusercontent.com/14790953/217549600-994f40c7-3be3-45a7-adf3-08bc60689f03.png)

**Version**

```shell
argocd: v2.6.0+acc554f
  BuildDate: 2023-02-06T21:17:26Z
  GitCommit: acc554f3d99010e0353b498a595844b30090556f
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/12360
