### ISSUE TITLE
project field in 'create application' dialog is confusing

### ISSUE THREAD

**Issue by stevesea** [argoproj/argo-cd#1236]
Trying out v0.12-rc2, and was confused by the UX for the project field on the 'create application' dialog.

It's pre-populated (1st alphabetical?) with a project. When I click it, I only see a single item in the pulldown.  I'd expected it to behave like repository URL / cluster URL fields where those are simple pulldowns of repositories/clusters. 

When I finally noticed that the project field is a text field, I cleared the field and got the full list of projects I expected.

I feel like if the Project field wasn't pre-populated, I would have been less confused. I would have just seen an empty box, and when I clicked the mouse into it I'd have gotten the full list of configured projects.

**Comment by stevesea** [comment]
![screen shot 2019-03-06 at 6 15 26 pm](https://user-images.githubusercontent.com/10570015/53925109-05246f00-403c-11e9-8650-f7abf37f37c4.png)

**Comment by alexmt** [comment]
I agree. I think confusion happens because project input is prefilled with first project and list of suggestions is filtered. Filtering is already disabled in master, removing pre-population.

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd-ui/commit/0850db530fe2ed3dc0f19f1c3e7ee9263066715c. The application creation UX is still far from perfect. Described several improvements in https://github.com/argoproj/argo-cd/issues/1238 . 
@stevesea, please add your comments if you want to improve something else.
