### ISSUE TITLE
display targetVersion of Application in Applications dashboard

### ISSUE THREAD

**Issue by stevesea** [argoproj/argo-cd#1239]
in the tiles/list view of the Applications dashboard, it’d be nice to see a version # for each application. Feels like it’d be a messy problem to show a helm chart’s version or appVersion, or otherwise attempt to figure out container versions in the deployment manifests.

But, could the targetVersion field of the ArgoCD Application CRD be shown? 

my use-case is mostly wanting to use ArgoCD as a CD tool, but also a dashboard for my org to view the current state of an environment. Beyond knowing if things are out-of-sync, it'd be nice to know for the in-sync deployments what versions are deployed for the project. 

i'm picturing us doing promotions by applying a new tag to the manifest repository, then updating the CRD to use the new tag. 

So... if I had a microservice 'myapp', and three ArgoCD projects -- test-myapp, staging-myapp, production-myapp. 

test-myapp might track the master branch.
staging-myapp targetVersion is myapp-v1.0.0
production-myapp targetVersion is myapp-v1.0.0

when QA was happy with a new build and wants to promote to staging, they'd apply a new tag myapp-v1.0.1 to the manifest repository, and update the staging CRD to targetVersion myapp-v1.0.1

**Comment by Oduig** [comment]
This would be my #1 wish for the ArgoCD Dashboard. We are looking to deploy our micro-services as Argo applications, and knowing which version is running makes a difference in terms of inter-service compatibility. Argo could visualize this much, much more transparently than the K8s dashboard does.

A potential alternative: allow adding a user-defined "summary" to each application, which can be any string. We can then use that field to display any information we want on the dashboard as long as it fits in a certain number of characters.

**Comment by alexec** [comment]
Good issue for contribution.

**Comment by alexec** [comment]
Related to #1219.

**Comment by alexec** [comment]
Working.

**Comment by alexec** [comment]
# Tiles 

![tiles](https://user-images.githubusercontent.com/1142830/59648925-93c58380-9135-11e9-89ea-2350000811b7.png)

# Table Large

![table-large](https://user-images.githubusercontent.com/1142830/59648944-a049dc00-9135-11e9-8409-fef7e724a330.png)

# Table Small

![table-small](https://user-images.githubusercontent.com/1142830/59648938-9e801880-9135-11e9-99d9-420f55f0cef3.png)

**Comment by alexec** [comment]
@stevesea - thoughts?

**Comment by stevesea** [comment]
looks good!

**Comment by alexec** [comment]
Fixed in v1.2
