### ISSUE TITLE
go-git is unable to properly handle AWS CodeCommit

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1243]
go-git is unable to clone a AWS code commit repo, failing with:

```
time="2019-03-07T13:42:17Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Intern
al desc = Failed to fetch git repo: reference delta not found" grpc.code=Internal grpc.method=ListDir grpc.service=r
epository.RepoServerService grpc.start_time="2019-03-07T13:34:00Z" grpc.time_ms=497203 span.kind=server system=grpc 
```

Issue appears to be: https://github.com/src-d/go-git/issues/1032

I'll be replacing the go-git fetch implementation with git CLI since go-git is also preventing us from cloning Azure repos.

**Comment by magicmoose** [comment]
I can confirm that jessesuen/argocd:git-fetch-cli-72a494b allows cloning from code commit
