### ISSUE TITLE
Applicationset progressive sync does not proceed

### ISSUE THREAD

**Issue by wmiller112** [argoproj/argo-cd#12459]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have an applicationset using a git generator and the following rolling sync strategy to update one app (the `prerelease`) before the others:
```
- matchExpressions:
    - key: service
      operator: In
      values:
        - prerelease
- matchExpressions:
    - key: service
      operator: NotIn
      values:
        - prerelease
```
The application with the `service:prerelease` label is successfully triggered. Runs its predeploy hook, and the deployment gets updated. Once complete, the prerelease app is healthy, but the remaining apps are not triggered to sync, and sit at "out of sync" indefinitely. Manually triggering a sync action again on the prerelease app re-runs the sync operation, which then successfully triggers the other apps to sync.

I can see the logs in the applicationset controller indicating the expected apps are in the proper steps, but `Application allowed to sync before maxUpdate` for the step2 apps continues to show false even after the step1 app has is healthy

**To Reproduce**

Create an applicationset that uses a git generator and a rolling sync strategy that requires a single application to update before the others

**Expected behavior**

All apps in subsequent sync steps are triggered.

**Version**
v2.6.1+3f143c9

**Logs**
app & appset names truncated/redacted
```
time="2023-02-14T18:17:35Z" level=info msg="Application prerelease has entered Progressing status, updating its ApplicationSet status to Progressing"
time="2023-02-14T18:17:35Z" level=info msg="ApplicationSet <APPSET_NAME> step list:"
time="2023-02-14T18:17:35Z" level=info msg="step 1: [prerelease]"
time="2023-02-14T18:17:35Z" level=info msg="step 2: [app, analytics, metrics]"
time="2023-02-14T18:17:35Z" level=info msg="Application allowed to sync before maxUpdate?: map[app:false, analytics:false, metrics:false]"
time="2023-02-14T18:17:35Z" level=info msg="unchanged Application" app=analytics appSet=<APPSET_NAME>
time="2023-02-14T18:17:35Z" level=info msg="unchanged Application" app=app appSet=<APPSET_NAME>
time="2023-02-14T18:17:35Z" level=info msg="unchanged Application" app=metrics appSet=l<APPSET_NAME>
time="2023-02-14T18:17:35Z" level=info msg="end reconcile" applicationset=argocd/<APPSET_NAME> requeueAfter=3m0s
```
The `allowed to sync` remains false on the subsequent reconciliation

**Comment by wmiller112** [comment]
After trying some tuning or the argo controllers I'm finding sporadic success and wondering if this may be due to the 300s timeout described [Here](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/applicationset/Progressive-Syncs.md), because the prerelease service can take more than 5 min. I've attempted setting the `applicationsetcontroller.default.application.progressing.timeout` parameter to `'600'` in the argocd-cmd-param-cm, and restarting the applicationset controller, but that doesn't seem to have had any effect - the appsets with a first stage taking over 5 min don't proceed

**Comment by riuvshyn** [comment]
same here, looks like `applicationsetcontroller.default.application.progressing.timeout` exists only in manual...

**Comment by wmgroot** [comment]
I need to remove the docs for that parameter, it only existed in the initial version of the Progressive Syncs feature.

It was replaced by logic to detect if an Application 
* is now Healthy
* had a sync that started after the Application entered Pending status from the ApplicationSet controller

This should be more reliable than a timeout, but I've seen some interesting behavior where the timestamp for the AppSet status can be after the Application's timestamp for when the sync started when the AppSet controller was the one to trigger the sync. That's behavior I don't have a good explanation for, but I've added a 10s grace period to try to account for it that should be present in the latest versions of 2.6 and 2.7.

https://github.com/argoproj/argo-cd/pull/13926

**Comment by kastriotdobratiqi** [comment]
We are having the same issue when trying out `ProgressiveSync` rolling sync feature. It is actually having a discrepancy of almost 2 minutes:
![image](https://github.com/argoproj/argo-cd/assets/27708908/32b135e8-7636-4242-b8f4-8288b6c93cf0)
![image](https://github.com/argoproj/argo-cd/assets/27708908/4afe39af-59b7-4679-a223-64c17ded1a28)

The initiation of sync seems to be happening way before it actually changes the state to `Pending`. In this example I have like 300+ apps in the appset, with around 80 apps per step (concurrency 20%).

Doing a manual sync on that `Pending` app, helps this to progress as mentioned above.

ArgoCD version `2.7.13`.

**Comment by wmgroot** [comment]
Oh wow, that's quite a discrepancy in timestamps. Addressing this is going to require identifying the source of that gap, rather than applying a bandaid.

Would it be possible to check the system clocks of the nodes running the applicationset-controller pod and the application-controller pod responsible for an application where this issue is occurring? I think it's possible that a system clock drift between the two could result in the situation we're seeing here, and I think a difference of 2 minutes should be obvious using `timedatectl` at around the same time on each machine.

**Comment by kastriotdobratiqi** [comment]
I have another case with an app stuck in `Pending`, eventhough the discrepancy is less than 10s:
![image](https://github.com/argoproj/argo-cd/assets/27708908/c7198326-5f30-4c51-9af6-e8e9a24e75fe)
![image](https://github.com/argoproj/argo-cd/assets/27708908/da0300d7-d6e9-4acc-b728-64c867b6650c)

The fix is supposed to be applied for 2.7.13. I did the upgrade (from 2.7.1) after the initial step finished and the sync got stuck. It did not continue the sync.

**Comment by wmgroot** [comment]
That one is 1m9s difference in time.

**Comment by kastriotdobratiqi** [comment]
that's true, apologies!

**Comment by wmgroot** [comment]
No worries! Starting to wonder if abandoning the timestamp based approach and verifying some hash is present in the sync trigger reason might be a better way to handle this, since the timestamps seem to be untrustworthy.

**Comment by kastriotdobratiqi** [comment]
Will keep an eye on this and happy to report results in the future. For now will disable using it in the current way as the sync keeps getting stuck. I have it mainly working right in 3 clusters, but the 4th one has these Pending apps.
