### ISSUE TITLE
helm/`valueFiles` is not intuitive

### ISSUE THREAD

**Issue by fivaldi** [argoproj/argo-cd#12451]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`: `v2.1.16+903db5f`

**Describe the bug**

The helm chart `valueFiles` implementation is **non-intuitive** and **non-usable** and **anti-pattern**.

When trying to deploy helm charts with orchestrated/generated ArgoCD apps and value files in the ArgoCD's repository, I added to the `valueFiles` list of two files `['values-something.yaml', 'custom-values-something.yaml']` for a particular app. Very intuitively. Then I found out that:

1. the yaml values files cannot be in the ArgoCD's watched repo => ArgoCD tries to apply them as resources
1. ArgoCD expects these files coming from the helm chart itself. Can somebody explain a usecase for this?
1. When addressing them via an external resource, then how to perform authentication (assuming the values files contain some sensitive information and can not be public)? E.g. when pointing to a git repo, is it enough to have the git repo configured in ArgoCD? How to construct the URL when using git over https?

**Expected behavior**

If I add to the `valueFiles` list of two files `['path/to/values-something.yaml', 'path/to/custom-values-something.yaml']`, I expect ArgoCD to look them up in the ArgoCD repository **itself** and process them **exactly the same way** as it does with inline `values` in the application definition, **incl. secret placeholders** plugin handling.

Or like: ` helm -f path/to/values-something.yaml -f path/to/custom-values-something.yaml ...` relatively to the directory where the ArgoCD application is stored.

This way, DevOps can orchestrate deployments (generate apps incl. values) to a **single ArgoCD repository** with (default/generated) values files  + provide a placeholders (in `custom-values-something.yaml`) for per-deployment overrides and customizations.

Note: When using `values` and `valueFiles` together, it should be mentioned, what has preference. My expectation would  be `values` would be _kind of defaults_ (processed first) and then `valueFiles` would be applied in the order of appearance.

**Screenshots**

**Version**

From API: `v2.1.16+903db5f`

**Logs**

**Comment by kulmated** [comment]
I agree with the part about it being counterintuitive, I also expected the values ​​to be taken from the application repository, but if you understand how ArgoCD works, you know that's not possible.

To achieve what you want to achieve, just use Kustomize helm setup and point Argo to it.

**Comment by crenshaw-dev** [comment]
It's a common confusion.

> relatively to the directory where the ArgoCD application is stored

Argo CD does not know where the Argo CD application is stored. The application is a resource living in Kubernetes. It doesn't know whether it arrived via `kubectl apply`, another Argo CD app, or something else.

> ArgoCD expects these files coming from the helm chart itself. Can somebody explain a usecase for this?

Many users serve Helm charts from their own internal git repositories. So they can add alternative values files, e.g. `values-prod.yaml`.

But many folks want to use a "stock" Helm chart and then reference a git-sourced Helm chart. To solve that problem, we introduced this feature in 2.6: https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/#helm-value-files-from-external-git-repository

**Comment by fivaldi** [comment]
> I agree with the part about it being counterintuitive, I also expected the values ​​to be taken from the application repository, but if you understand how ArgoCD works, you know that's not possible.
> 
> To achieve what you want to achieve, just use Kustomize helm setup and point Argo to it.

I don't like the _use-yet-another-tool_ approach for simple stuff which is kind of expected to work out of the box. And helm + values are kind of basic stuff: `helm install -f ...`. If it was projected to ArgoCD repository (there are GitHub issues/requests for ignoring _ArgoCD non-resources_), I don't see issues for storing values files along with apps. If there are implementation issues blocking this, then it's a different story.

**Comment by fivaldi** [comment]
> It's a common confusion.

Which means that the design is against intuitive usage.. The `valueFiles` naming is not helping at all.

> Argo CD does not know where the Argo CD application is stored. The application is a resource living in Kubernetes. It doesn't know whether it arrived via `kubectl apply`, another Argo CD app, or something else.

> But many folks want to use a "stock" Helm chart and then reference a git-sourced Helm chart. To solve that problem, we introduced this feature in 2.6: https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/#helm-value-files-from-external-git-repository

Ok, the new feature could solve the issue. Thanks! Btw. how does ArgoCD know  about values files changes in the (external) git repo?

**Comment by crenshaw-dev** [comment]
> I don't see issues for storing values files along with apps.

The problem is that an app is not a file in a repo. It's a resource on k8s. The resource (and therefore Argo CD) has no knowledge of if or where you store your application manifest files, or what other files might be stored in the same location.

> The valueFiles naming is not helping at all.

I'm up for considering an alternative name if you have suggestions. :-) 

> How does ArgoCD know about values files changes in the (external) git repo?

Argo CD will check the external git repo for new commits on reconciliation (either triggered by a refresh, reconciliation timeout, or webhook).

**Comment by fivaldi** [comment]
Hope ArgoCD is treating / storing the Applications resource the same way as K8s Secrets are handled, because `values` contain (potentially/typically) sensitive data. Otherwise it's against the K8s security design.

As for the naming: e.g. `valueSources` + explanation what it can contain: supported URI schemes, value files relative paths **within/contained inside of** helm charts  etc.

---

The overall concept is a bit crazy: K8s is essentially an autopilot (Deployments/ReplicaSets / StatefulSets / ... are doing their job in this term), and ArgoCD with auto-sync ON is yet another autopilot on top of the K8s autopilot. I would say auto-sync OFF is the only reasonable usage, just get the information about diffs and apply the desired state manually **when it's really desired**.

**Comment by crenshaw-dev** [comment]
> Hope ArgoCD is treating / storing the Applications resource the same way as K8s Secrets are handled

Argo CD does not store the Application resource, that's Kubernetes' responsibility. 

The Application resource has two fields which may directly contain values: `spec.source.helm.parameters` and `spec.source.helm.values`. Users should understand that directly storing secrets in those fields is different from storing them in Secrets and has different security implications. My opinion is that plaintext secrets should never be present in those fields.

> because values contain (potentially/typically) sensitive data

Even where the Application does not directly contain values, it references sources which, in my opinion, should not contain secrets: i.e git repos, Helm repos, or OCI repos.

> Otherwise it's against the K8s security design.

I don't think Kubernetes has an opinion on what should be present in Helm values. Helm is a project built on top of Kubernetes, not the other way around.

> As for the naming: e.g. valueSources

I'm not sure `valueSources` is clearer than `valueFiles`, but I could be wrong.

> explanation what it can contain

These are the two main places the field is documented: 
1. https://github.com/argoproj/argo-cd/blob/fbb0b99b1ac3361b253052bd30259fa43a520945/docs/operator-manual/application.yaml#L43-L46
2. https://argo-cd.readthedocs.io/en/latest/user-guide/helm/#values-files

I'd definitely be up to review a PR clarifying either of those.

> The overall concept is a bit crazy... ArgoCD with auto-sync ON is yet another autopilot on top of the K8s autopilot

This sounds like potentially a different ticket. But I don't think it's unreasonable. k8s is built on mechanical turtles all the way down to the Von Neumman cycle. But you're not alone in thinking auto-sync doesn't always make sense. It's probably the most often skipped of the four [GitOPs principles](https://opengitops.dev/).

**Comment by fivaldi** [comment]
---
---

"So can we trust the admins still have the skills to control?"
https://youtu.be/LA-WeacusP4?t=2645

**Comment by fivaldi** [comment]
I think the inline `values` should be stored out of the ArgoCD Application resources, in K8s secrets. Once ArgoCD processes the application resource, some hook should remove the `values` from it and save them to a K8s Secret and just reference it in the Application definition. Or even better, it should be done immediately, when the App resource is created  in K8s. That's how I think the security of the secrets in the values shall be handled.

The `valueFiles` is really misleading. If `values` are inline values, the `valueFiles` is kind of expected to be a separate file sitting next to it in the repository, for anybody just coming to ArgoCD and seeing it for the first time and not understanding the details/internals..  Maybe I am affected by helmfile, but I was not the only one confused of the `valueFiles`...

Hope some of the feedback from me was valuable.
