### ISSUE TITLE
Stacktrace in web ui when clicking on application resource that failed to sync

### ISSUE THREAD

**Issue by mynamewastaken** [argoproj/argo-cd#12456]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Stacktrace in web ui when clicking on application resource that failed to sync

**To Reproduce**

- Clicked sync application in web ui
- Failed after a few minutes with `the server could not find the requested resource`
- Click on resource that failed (https://argocd.domain.com/applications/argocd/renovatebot?operation=false&node=batch%2FCronJob%2Frenovate%2Frenovate%2F0&resource=sync%3AOutOfSync)
- Stacktrace 

**Expected behavior**

404 error or some other error handling

**Screenshots**

**Version**

```shell
argocd version
argocd: v2.5.1+504da42
  BuildDate: 2022-11-01T21:36:58Z
  GitCommit: 504da424c2c9bb91d7fb2ebf3ae72162e7a5a5be
  GitTreeState: clean
  GoVersion: go1.18.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.1+3f143c9
```

**Logs**

```
Something went wrong!

Consider submitting an issue here.

Stacktrace:

p@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:1855605
42219/$x/<@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:1859780
render@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:1503169
Hs@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:819397
js@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:819192
ya@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:854673
pl@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:846150
dl@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:846073
il@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:843103
82002/qo/<@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:794882
90362/t.unstable_runWithPriority@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:869930
Uo@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:794591
qo@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:794829
$o@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:794762
Xa@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:839892
enqueueSetState@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:798545
17952/y.prototype.setState@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:976712
t@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:1504139
o@https://argocd.domain.com/main.757a2876c851d00cee17.js:2:1504260
```

I will attempt updates and potentially re-deploying the application; this is more of an informational since it threw up a stracktrace.

**Comment by todaywasawesome** [comment]
@crenshaw-dev suggests this might be related to error handling for how we deal with CRDs being missing.

**Comment by David3310273** [comment]
@mynamewastaken Hi, the link https://argocd.domain.com/applications/argocd/renovatebot?operation=false&node=batch%2FCronJob%2Frenovate%2Frenovate%2F0&resource=sync%3AOutOfSync included in your comment is invalid now, can you show me where did you click to reproduce the bug after seeing the err msg `the server could not find the requested resource` in the UI? thanks!

**Comment by mynamewastaken** [comment]
> @mynamewastaken Hi, the link https://argocd.domain.com/applications/argocd/renovatebot?operation=false&node=batch%2FCronJob%2Frenovate%2Frenovate%2F0&resource=sync%3AOutOfSync included in your comment is invalid now, can you show me where did you click to reproduce the bug after seeing the err msg `the server could not find the requested resource` in the UI? thanks!

I haven't run into this issue again. Could've been timing, could've been fixed in recent upgrades. I'll close it.
