### ISSUE TITLE
On upgrade from 2.3.4 to 2.6.0, I started getting this error for charts stored in CodeFresh Helm Repo

### ISSUE THREAD

**Issue by vkumar85** [argoproj/argo-cd#12483]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I have upgraded argoCD from 2.3.4 to 2.6.0. All application are working OK except the one's , for which , Helm chart is stored in the CodeFresh Helm repository. 

**To Reproduce**

**Expected behavior**

![image](https://user-images.githubusercontent.com/40867872/219264598-c8e040ec-4952-48dc-acf7-713dbce130a5.png)

**Version**

```shell
![image](https://user-images.githubusercontent.com/40867872/219264577-23486505-ca97-4857-bcb9-e8ebb12c8bcd.png)
```

**Logs**

```
ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: could not find protocol handler for: cm
```

**Comment by todaywasawesome** [comment]
@vkumar85 You might want to use your Codefresh support as they would probably help you right away. I'll share this with the CS team there and see if they know what's going on.

**Comment by vkumar85** [comment]
@todaywasawesome , Thanks for the response. I have opened a case with CF support [#16140]

**Comment by blakepettersson** [comment]
Closing since this seems Codefresh specific.
