### ISSUE TITLE
trying to get SSO to work

### ISSUE THREAD

**Issue by aikijitsu** [argoproj/argo-cd#12500]
### Discussed in https://github.com/argoproj/argo-cd/discussions/12494
<div type='discussions-op-text'>

<sup>Originally posted by **aikijitsu** February 16, 2023</sup>
https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/microsoft/#azure-ad-app-registration-auth-using-oidc

I followed the oidc instructions but don't see a sso login button on the login page. What should I look for?
Also tried with Dex. Just trying to get SSO to work.</div>

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd

data:
url: https://myip/login?return_url=https%3A%2F%2Fmyip%2Fapplications 
    oidc.config: |
          name: Azure
          issuer: https://login.microsoftonline.com/mytenantid/v2.0
          clientID: myappregid
          clientSecret: $oidc.azure.clientSecret
          requestedIDTokenClaims:
            groups:
                essential: true
          requestedScopes:
            - openid
            - profile
            - email

**Comment by aikijitsu** [comment]
is there support for this?

**Comment by aikijitsu** [comment]
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd

data:
  policy.default: role:readonly
  policy.csv: |
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, repositories, get, *, allow
      p, role:org-admin, repositories, create, *, allow
      p, role:org-admin, repositories, update, *, allow
      p, role:org-admin, repositories, delete, *, allow
      g, "blah-blah-blah-blah", role:org-admin

**Comment by aikijitsu** [comment]
Does anyone know how to implement this? Followed the instructions in the portal, have created appreg and enterprise apps in aad before.

**Comment by aikijitsu** [comment]
anyone???

**Comment by deadwanderer** [comment]
The part that jumps out to me is your URL in the argocd-cm. It should just be your base URL (https://myip/), as per the configuration docs:

`url: https://argocd.example.com/ # Replace with the external base URL of your Argo CD`

**Comment by aikijitsu** [comment]
Does everything look good with this config?

**Comment by mkilchhofer** [comment]
Could you solve it, @aikijitsu or do you need further help?
