### ISSUE TITLE
Note readiness gate failures in Pod summary UI

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#12515]
# Summary

The Pod summary should show some indication that a readiness gate is failing.

# Motivation

Readiness probes produce events when they fail. Users know to look at the Events tab for those failures. But for readiness gates, you have to dig through the `status` field to figure out what's wrong.

# Proposal

Show a small alert near the top of the Pod summary UI indicating that a readiness gate is failing.

**Comment by Marvin9** [comment]
Is there a difference between readiness gates and probes or same?

**Comment by crenshaw-dev** [comment]
It's a slightly different thing: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-gate
