### ISSUE TITLE
Post selectors broken when using goTemplate: true

### ISSUE THREAD

**Issue by Roshick** [argoproj/argo-cd#12524]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When goTemplate is enabled, the [post selectors](https://argo-cd.readthedocs.io/en/stable/user-guide/application-set/#post-selector-all-generators) do not work anymore.

I assume this problem is caused by the params needing to be prefixed with a dot when goTemplate is active, unfortunately prefixing a selectorKey is impossible as this will fail [during creation](https://github.com/argoproj/argo-cd/blob/master/applicationset/generators/generator_spec_processor.go#L30)  in the library's [validation for the requirements](https://github.com/kubernetes/apimachinery/blob/bfd2aff97e594f6aad77acbe2cbbe190acc93cbc/pkg/util/validation/validation.go#L43)

[This issue will be the exact same problem](https://github.com/argoproj/argo-cd/issues/11664), seeing that goTemplate in this case is also enabled. The assumption that keys with dots are completely unsupported is incorrect, when goTemplate is disabled keys with dots work perfectly fine (just not prefixed).

**To Reproduce**

Simply create an applicationset that uses both goTemplate: true and post selectors, neither version (with or without prefix) will work

**Version**

ArgoCD v2.6.2

**Comment by uzemeltetes-doto** [comment]
I'm also facing this problem, and I cannot disable Go templating, because I use dynamic list generator (v2.7.0rc2):

`          - list:
              elements: []
              elementsYaml: "{{ .components | toJson }}"
`

Someone please look into this bug.

**Comment by m13t** [comment]
So this looks to be that the labels are being filtered out if they contain nested properties and only top-level string key value pairs are being kept.

I’m not overly familiar with the codebase but at a quick glance this looks like for the generator spec function that filters these out, you could simply dot append the keys for nested values rather than discard them.

I’m happy to put a PR in for this assuming there aren’t some wider ramifications I’m unaware of?

**Comment by uzemeltetes-doto** [comment]
This is the error message from ApplicationSet controller when I apply the ApplicationSet manifest above:

`time="2023-05-12T11:32:00Z" level=error msg="error generating application from params" error="error parsing label selector: key: Invalid value: \".componentvalues.cluster.name\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')"`

**Comment by crenshaw-dev** [comment]
I'm not super familiar with how this bug is working under the hood. But it's definitely a bug.  Just an oversight from when we added go templates.  I'd be happy to review any PR that makes it possible/intuitive to select when using go templates.

**Comment by m13t** [comment]
I think it's to do with the structure of the values is different between Go template and old templates.
I can see that Go templates come in as nested maps but without go templates the keys come in to the generators pre-joined with a period. I'm working on a fix to join the keys in the generator spec processor. As these don't need to be dynamic it should be fairly straight forward and result in the same behaviour as non-Go templates.

**Comment by m13t** [comment]
@uzemeltetes-doto no it should work with dots but there's a bug. Working on a fix at the moment.

**Comment by uzemeltetes-doto** [comment]
Unfortunately this still seems to be an issue in v2.8.4:

```
time="2023-10-12T07:32:24Z" level=error msg="error generating application from params" error="error parsing label selector: key: Invalid value: \".testkey\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')" generator="{nil nil nil nil nil nil &MatrixGenerator{Generators:[]ApplicationSetNestedGenerator{ApplicationSetNestedGenerator{List:nil,Clusters:nil,Git:&GitGenerator{RepoURL:https://gitlab.com/doto1/k8s-infra.git,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:clusters/*/*/components/values.yaml,},},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:componentvalues,Values:map[string]string{},},SCMProvider:nil,ClusterDecisionResource:nil,PullRequest:nil,Matrix:nil,Merge:nil,Selector:nil,Plugin:nil,},ApplicationSetNestedGenerator{List:&ListGenerator{Elements:[]JSON{},Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},ElementsYaml:{{ .components | toJson }},},Clusters:nil,Git:nil,SCMProvider:nil,ClusterDecisionResource:nil,PullRequest:nil,Matrix:nil,Merge:nil,Selector:nil,Plugin:nil,},},Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},} nil &LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{LabelSelectorRequirement{Key:.testkey,Operator:Exists,Values:[],},},} nil}"
```

Must use dot prefix because of generator:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://gitlab.com/***/k8s-infra.git
              revision: HEAD
              pathParamPrefix: componentvalues
              files:
              - path: "clusters/*/*/components/values.yaml"
          - list:
              elements: []
              elementsYaml: "{{ .components | toJson }}"
      selector:
        matchExpressions:
        - {key: .testkey, operator: Exists}
```
