### ISSUE TITLE
CreateNamespace=true sync option might cause deletion of the whole namespace

### ISSUE THREAD

**Issue by pdrastil** [argoproj/argo-cd#12539]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When Application resource contains sync option `CreateNamespace=true` and user tries to replace managed resources with force it will lead to deletion of namespace together with all resources in such namespace (including the ones that are not managed by given application). After some investigation I found out that this behaviour is caused by `gitops-engine` that translates options to `syncTask` that is passed to `kubectl replace --force` method. Based on kubectl documentation this combination does "Force replace, delete and then re-create the resource".

Related code:
- https://github.com/argoproj/gitops-engine/blob/3516b3928a06c7d04c200f06beaf04b3c2bef63f/pkg/sync/sync_context.go#L803
- https://github.com/argoproj/gitops-engine/blob/3516b3928a06c7d04c200f06beaf04b3c2bef63f/pkg/sync/sync_context.go#L904

**To Reproduce**

- Create Application with sync option CreateNamespace=true
- Use `kubectl get ns <namespace> --watch` to monitor changes
- Trigger sync via UI with CreateNamespace + Replace + Force options

**Expected behavior**

As stated in Argo CD documentation CreateNamespace=true should be non-destructive operation and namespace is not deleted in this case. If it is intentionally deleted in this scenario it should be documented or there should be extra warning.

**Version**

```shell
v2.5.7+e0ee345
```

**Comment by pdrastil** [comment]
Hi @crenshaw-dev can you please take a look on this?

**Comment by crenshaw-dev** [comment]
@blakepettersson  any thoughts on this? I’d the current behavior meant to be never-delete? If so, do we need to change how the sync task is constructed for this particular use case?

**Comment by blakepettersson** [comment]
Fixed by #13758
