### ISSUE TITLE
Sync problems with Openshift cluster

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1255]
When syncing a service account in argocd (in a Openshift cluster) I get multiple results:
```
argocd app get xxxx | grep -i ServiceAccount
```
![image](https://user-images.githubusercontent.com/9946020/54186684-3b367880-44ac-11e9-836f-68eb2331f129.png)

**Comment by peterbosalliandercom** [comment]
This happens when trying to deploy multiple serviceaccounts to the same namespace. In other words if you create multiple yaml files that have the same content argocd gives this result. I presume that argocd should not process the same yaml again.

**Comment by jessesuen** [comment]
resources which are defined twice has undefined behavior. We have an open issue to emit a warning about this: https://github.com/argoproj/argo-cd/issues/1070

I'll dupe this issue to that one.
