### ISSUE TITLE
Support for rollback in multiple sources

### ISSUE THREAD

**Issue by ankitabhopatkar13** [argoproj/argo-cd#12580]
# Summary

When using the multiple sources beta feature, the `HISTORY AND ROLLBACK` feature is disabled with a tooltip saying it is not supported yet.

It was implemented [here](https://github.com/argoproj/argo-cd/pull/11785).

![Screenshot 2023-02-23 at 09 53 03](https://user-images.githubusercontent.com/22163931/220861338-4fa629d9-c7f7-45e7-91c4-5ecaf2f63506.png)

Opening a new enhancement request as I don't see it open [here](https://github.com/argoproj/argo-cd/issues?q=is%3Aopen+is%3Aissue+label%3Amulti-source-apps) yet.

# Motivation

We want this feature to be able to rollback to previous versions when needed.

**Comment by JorTurFer** [comment]
There is an open PR

**Comment by gavriellan-ma** [comment]
Hi! Any update on if or when the pr will be merged and the fix will be released?

**Comment by Zaheerkhan999** [comment]
Hi,
Any update as this is highly needed.

**Comment by Reyalsorik** [comment]
Hi, we're looking to use this too - thanks!

**Comment by GuerreiroLeonardo** [comment]
For everyone that wants updates on this:
https://github.com/argoproj/argo-cd/pull/14124#pullrequestreview-1578717736
