### ISSUE TITLE
Is there a way to get all the components under single application (including Pods)

### ISSUE THREAD

**Issue by Jim0530** [argoproj/argo-cd#12587]
# Summary

What change you think needs making.

# Motivation

Please give examples of your use case, e.g. when would you use this.
I want to get all Kubernetes components under single application, like the picture down below, I hope to get a list of all the Kubernetes components under one application.
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/48552674/220918161-6c5c0353-63ec-4306-ba77-50f5e9305b53.png">

# Proposal

How do you think this should be implemented?
I hope to find all the pods down below the application, it seems only for deployment information

**Comment by crenshaw-dev** [comment]
Pods should be available, too. Just make sure Pods are allowed for the Application's AppProject.

**Comment by Jim0530** [comment]
i've been using api/v1/applications/{applicationName}/managed-resources, and it turns out that the response only contains service virtuial-service deployment information. there's no pod information.
what do u mean allow application's AppProject

**Comment by Jim0530** [comment]
i've been curious about argocd UI can get a list of all components, what's behind the ui, api ?

**Comment by crenshaw-dev** [comment]
Try looking at api/v1/applications/{applicationName}/resource-tree.

Projects determined what resources are allowed in an app's resource tree: https://argo-cd.readthedocs.io/en/latest/user-guide/projects/

**Comment by Jim0530** [comment]
@crenshaw-dev Thanks for the help, i really appreciate the kindness ur help, and wish you have a good day
