### ISSUE TITLE
Support `app sync --dry-run --revision some-revision` with arbitrary revisions

### ISSUE THREAD

**Issue by pclalv** [argoproj/argo-cd#12592]
# Summary

currently, invocations like this fail with this error:
```sh-session
$ argocd app sync --dry-run --force some-namespace/some-app --revision some-revision
  # WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
  # FATA[0001] rpc error: code = FailedPrecondition desc = Cannot sync to some-revision: auto-sync currently set to master
  #  ELIFECYCLE  Command failed with exit
```

so it would seem that this would only work if `--revision master` were passed, and that this doesn't work with arbitrary revisions.

I would instead like for this command to work more like `app sync --dry-run --local`. as was argued in https://github.com/argoproj/argo-cd/issues/3614: 

>Dry run should not affect the cluster state, so it shouldn't matter what the sync policy is, so this should be allowed.

I'm not sure why `sync --dry-run` without `--local` should be any different.

# Motivation

my Argo apps all auto-sync to my master branch. I'd like to create automation to validate changes before merging them into master, rather than find out after merging my changes into master that there was some silly resource schema validation error.

I would love to be able to do this with `kubectl apply --dry-run=server`, but I find that's not a good approach. I believe that it would be very difficult to do this kind of validation without Argo's help, since Argo automagically injects labels (like `argocd.argoproj.io/instance`) and handles resource conflicts (for example, destroying and recreating Job resources associated with a helm pre-install hook.

# Proposal

the change to allow this to happen probably needs to be made in this function: https://github.com/argoproj/argo-cd/blob/c9d317ac499bc5b211d2e12148051c216f868f11/server/application/application.go#L1627

that function already seems to be aware of the `DryRun` option on the `ApplicationSyncRequest` struct, so it'd be a matter of checking that value in the correct spot.

**Comment by DomineCore** [comment]
I also think this is a very important capability. I want to use the dry-run option to synchronize the application during the PR process, so that I can find problems before the code is merged and decide whether to prevent this merge. But what I don't understand is why it can't be supported in --revision like --local?

**Comment by jhoover4** [comment]
Any movement on this?

**Comment by crenshaw-dev** [comment]
I think I agree that the revision check can be skipped for dry runs. Adding an item to tomorrow's [contributor meeting](https://docs.google.com/document/d/1xkoFkVviB70YBzSEa4bDnu-rUZ1sIFtwKKG1Uw8XsY8/edit) agenda to discuss w/ other maintainers.

**Comment by crenshaw-dev** [comment]
Yep, it's fine to exclude dry runs from the auto-sync safety check. Anyone up for a PR?
