### ISSUE TITLE
cluster add: Provide option to use "internal endpoint" for the remote cluster's apiserver

### ISSUE THREAD

**Issue by adambkaplan** [argoproj/argo-cd#12625]
# Summary

Add an option to `argocd cluster add` which allows ArgoCD to use the "internal" APIServer endpoint that the remote cluster publishes in the `kube-public/cluster-info` ConfigMap.

# Motivation

Many developers use [KinD](https://kind.sigs.k8s.io/) to test locally, and it is particularly useful to test multi-cluster use cases. One of the challenges of this approach is that KinD clusters serve the APIServer in two ways:

1. On an "external" `127.0.0.1` endpoint, with a randomly assigned port. KinD uses this to generate the `kubeconfig` for the cluster on the developer's "host". 
2. On an "internal" endpoint , typically a DNS name that resolves on the `kind` network that is created within the developer's container runtime (Docker or Podman).

The external endpoint is reachable from the developer's host machine, but it is not reachable from within the KinD clusters. The "internal" endpoints are (eventually) reachable because the KinD clusters share the same network.

# Proposal

1. Add a flag option to `argocd cluster add`: `--cluster-endpoint`.
2. Flag accepts the following options: `kubeconfig`, `kube-public`, `internal`:
   1. `kubeconfig` keeps the default behavior, using the rest-endpoint from the kubectl context for the remote cluster.
   2. `internal` replicates the behavior of the `--in-cluster`, treating the current cluster as the "remote" for deployment.
   3. `kube-public` finds the server endpoint that is published in the `kube-public/cluster-info` ConfigMap for the remote cluster.

# Notes

This proposal is similar to a feature in Open Cluster Management's [clusteradm](https://open-cluster-management.io/getting-started/installation/register-a-cluster/) tool. 

In my initial testing with Podman as KinD's container runtime, it can take some time (on the order of minutes) for the DNS records to propagate between the KinD clusters.

**Comment by jannfis** [comment]
After our quick talk yesterday, I was just checking one of my recent k3s installations, and I was wondering if there should be a fourth option: `url:<url>`, which takes `<url>` from the command line as an endpoint, in the case that neither is the right endpoint in the `kubeconfig`, nor is there a `cluster-info` ConfigMap in the `kube-public` namespace.

WDYT?

**Comment by adambkaplan** [comment]
I like that idea - we can discuss semantics of the format in the implementation (ex use an equal sign as a delimeter -  `--cluster-endpoint url=<url>`)

**Comment by MohammedNoureldin** [comment]
Hi, this was marked as completed, but if I am not wrong, this does not include the possibility to pass the URL explicitly as part of the CLI. Right? Do we have to create a new configmap only for the second when we want to add a new cluster? This seems a bit odd. Or do I misunderstand something here?
