### ISSUE TITLE
Azure SSO

### ISSUE THREAD

**Issue by aikijitsu** [argoproj/argo-cd#12638]
Several people are posting about not being able to get SSO working. Is there anyone looking into it? Can someone provide better examples in the documentation if it's not a bug?

**Comment by woehrl01** [comment]
@aikijitsu Azure SSO is working perfectly fine. Maybe instead of just opening a new issue, it would be great to either comment into the dedicated issues, or at least provide a link to all related items in this one?

**Comment by aikijitsu** [comment]
Others seem to be having issues with it as well. Support is a key factor when large enterprises choose a CD tool.

**Comment by aikijitsu** [comment]
![argocd-cm](https://user-images.githubusercontent.com/78279931/222179228-c65ae210-b722-48ee-85a1-0e676c64367b.png)
![argocd-rbac-cm](https://user-images.githubusercontent.com/78279931/222179234-f96ef8f9-8374-4135-9cee-ef87c20f9625.png)
![argocd-secret](https://user-images.githubusercontent.com/78279931/222179275-443264e5-373b-4537-85a8-a9c75d35594c.png)

**Comment by aikijitsu** [comment]
> @aikijitsu Azure SSO in combination with ArgoCD is working perfectly fine. Maybe instead of just opening a new issue, it would be great to either comment into the dedicated issues, or at least provide a link to all related items in this one?

Posted our config below. Do you have any suggestions?

**Comment by aikijitsu** [comment]
Anyone??

**Comment by aikijitsu** [comment]
> @aikijitsu I had this same issue, running the ha-install of v2.6.3. After upgrading to the latest version (v2.6.4) I no longer have any issue. Not sure if it's because of that or because the configmap changes require the server pods to be deleted and recreated.
> 
> The most likely reason nobody is responding to you is that you already have an issue opened about this and when @woehrl01 commented explaining what the best course of action is, you were quite rude to them.

I will keep posting about it until it is fixed. My customer likes Argo but I am happy to direct them to Octopus Deploy because they support their product. I tried deleting the pods after any config changes, did not work. @woehrl01 did not provide anything useful, I was not rude.

**Comment by woehrl01** [comment]
@aikijitsu Octopus Deploy is a great product, if you are "demanding" support I recommend looking for a paid product and not an open-source one with community support.

Maybe I could not provide "anything useful" because your initial post, didn't provide anything useful to help. As I didn't like the tone you are sending, I better use my time for helping others.

**Comment by aikijitsu** [comment]
Unless there is something constructive to share about the code I posted, per the documentation from argo, please feel free to avoid "contributing" to the thread.
