### ISSUE TITLE
ArgoCD got Stuck

### ISSUE THREAD

**Issue by rchinni-mn** [argoproj/argo-cd#12671]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by rchinni-mn** [comment]
Version: v2.6.1+3f143c9

**Comment by rbreeze** [comment]
Can you describe which part of the UI you were attempting to access when this error occurred?

**Comment by rchinni-mn** [comment]
while navigating through the deployed applications.

**Comment by rbreeze** [comment]
Do you have any screenshots? It's difficult to debug this without knowing specifically where in the UI this error may have occurred.

**Comment by winterhalder** [comment]
I am getting a similar error in argo-cd 2.6.6 with the 0.3.0 rollouts extension.

I get it when trying to view the rollouts extension from the "More" page of a rollout.  I'm able to view the rollouts dashboard initially fine... then after a minute - or if I attempt to trigger a "full promotion" or exit the page - I get this error.

<img width="1001" alt="2023-05-03_18-06-59" src="https://user-images.githubusercontent.com/3590310/236061060-c242d02f-f540-414d-9b3a-d8cf5aec30f0.png">

**Comment by winterhalder** [comment]
Here is a video...  I've also reported it to the rollout-extension repo - as I'm not sure if it's ArgoCD itself or the extension... <- I had never seen this behaviour before we installed the rollout extension to try it out...

https://user-images.githubusercontent.com/3590310/236062058-de4fa194-6c02-49e9-a6ef-1beb4df1a041.mp4

**Comment by winterhalder** [comment]
Note - still seeing this issue in ArgoCD 2.7.1 as well...

**Comment by winterhalder** [comment]
Have confirmed this in 2.7.3 as well.

In regards to the argocd-rollout-extension - it appears to be related to the Pods view...

More details here - there's a video at the end of the thread - https://github.com/argoproj-labs/rollout-extension/issues/45

**Comment by winterhalder** [comment]
Update - the new 0.3.1 release of the rollouts extension (potentially combined with Argo 2.7.11) seems to fix this! Woot!

(At least the rollout-related scenario)

(Thank-you kind strangers!)

**Comment by jgwest** [comment]
Appears resolved and/or no additional details provided, depending on comment.
