### ISSUE TITLE
Support for BitBucket Server webhook events

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1269]
It appears that BitBucket server sends different HTTP headers and payload than what bitbucket.com sends, so we don't currently support BitBucket server.

Here are the docs on their payload and headers:

BitBucket Server: https://confluence.atlassian.com/bitbucketserver0515/event-payload-961275434.html?utm_campaign=in-app-help&utm_medium=in-app-help&utm_source=stash#Eventpayload-repositoryevents

BitBucket.com: https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Push

**Comment by alexec** [comment]
You could use polling for this?

**Comment by johnmarcou** [comment]
Webhook module in version v5 now support BitBucket Server:
https://github.com/go-playground/webhooks/pull/63

As far as I know, ArgoCD is using v3 of that module for now.

**Comment by jessesuen** [comment]
We do poll 3 minutes by default already. This feature would just eliminate the 3 minute wait. I recall we could not easily implement this without the support from the webbook library we use. I believe it has since been updated to support bitbucket server, so now it should be pretty straightforward to implement.

**Comment by johnmarcou** [comment]
I am about to PR on this, probably this week.

**Comment by alexec** [comment]
@johnmarcou - brilliant - looking forward to your PR!

**Comment by alexec** [comment]
Merged PR. Dropping in v1.2.
