### ISSUE TITLE
ArgoCD don't change annotations or labels after set managedNamespaceMetadata

### ISSUE THREAD

**Issue by mgfnv9** [argoproj/argo-cd#12697]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrade to new version ArgoCD v2.6.1+3f143c9 , we want to use managedNamespaceMetadata [https://argo-cd.readthedocs.io/en/release-2.6/user-guide/sync-options/#namespace-metadata](url)

For the first time throught ArgoCD I create of annotation or label on kubernetes namespace using new feature managedNamespaceMetadata, I see changes, but after I change annotations or labels in ArgoCD, ArgoCD don't change annotation or labels on kubernetes namespace.
But I see changes in ArgoCD UI in App Details in annotations or labels, I doing hard resfresh but anithing do it, but if I Sync in ArgoCD all be OK, changes commited in namespace

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Argo CD
v2.6.1+3f143c9
```

**Logs**

```

```

**Comment by woehrl01** [comment]
Sounds like a duplicate of #12661

**Comment by mgfnv9** [comment]
> Звучит как дубликат #12661

You're right, this duplicat

**Comment by mgfnv9** [comment]
Duplicate of 
https://github.com/argoproj/argo-cd/issues/11196
