### ISSUE TITLE
CHAT NOW!

### ISSUE THREAD

**Issue by KyleSanderson** [argoproj/argo-cd#12703]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

CHAT NOW!

**To Reproduce**

Install 2.6.3.

**Expected behavior**

No weird balloon at the bottom asking me to chat.

**Screenshots**
![image](https://user-images.githubusercontent.com/1184902/222547578-9d5ff7ec-8e76-4d07-9e49-4a3ecc57bc9c.png)

**Version**
2.6.3

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
Thanks for the report, @KyleSanderson! This is being tracked here: https://github.com/argoproj/argo-cd/issues/12655
