### ISSUE TITLE
ArgoCD custom healthcheck issue 

### ISSUE THREAD

**Issue by jakubtomiak97** [argoproj/argo-cd#12715]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hello!

Seems like there is a bug with custom healthchecks when using wildcard at the beginning.

example which does not work

```
resource.customizations: |
    *.aws.crossplane.io/*:
      health.lua: | 
        ...
```
this works fine

```
resource.customizations: |
    smth.aws.crossplane.io/*:
      health.lua: | 
        ...
```
        
Documentation [link](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#custom-health-checks) with above example.

**To Reproduce**

Add above custom healthcheck to the argocd configmap.

**Expected behavior**

Healthcheck works fine for option number 1.

**Version**

2.6.3

**Comment by reggie-k** [comment]
@jakubtomiak97
Seems like a misdocumentation. 
Can you please confirm that it works for you when surrounded by quotes?
"*. aws.crossplane.io/*"

**Comment by jakubtomiak97** [comment]
@reggie-k yup, that one works. Thanks!
