### ISSUE TITLE
UI Enhancement Proposals Quick Wins

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1274]
Discuss how we might improve the UI to make features more discoverable and help more readily available.

**Comment by igaskin** [comment]
As of `v0.12` the `/applications` page is limited to displaying 2 applications per column with `n` number of rows.  It would be great to allow applications to span the full width of the window, which would be beneficial to dashboards.

Toggling between a compact and detailed view on the `/applications` page could also be useful.

**Comment by chap-dr** [comment]
Is there a reason why clusters are listed by their address (ip's in my case when running GKE clusters) and not their name? 

Would it not make more sense to use the name, perhaps with a link to the cluster details on the application box?

**Comment by alexec** [comment]
> As of `v0.12` the `/applications` page is limited to displaying 2 applications per column with `n` number of rows. It would be great to allow applications to span the full width of the window, which would be beneficial to dashboards.
> 
> Toggling between a compact and detailed view on the `/applications` page could also be useful.

Do you have a specific number of columns you'd like?

**Comment by alexec** [comment]
> r name on applications and in the filter dropdown?

@chap-are you essentially saying you find that filtering by cluster URL is a problem because all your clusters have an IP address that you can't differentiate?

**Comment by chap-dr** [comment]
> > r name on applications and in the filter dropdown?
> 
> @chap-are you essentially saying you find that filtering by cluster URL is a problem because all your clusters have an IP address that you can't differentiate?

Indeed, but since the name column is there, but not used, I thought perhaps someone had made a conscious choice to go with cluster address over name, hence the cryptic way os asking it. but yes, that is what it comes down to for my case.

**Comment by alexec** [comment]
@chap-dr I have created https://github.com/argoproj/argo-cd/issues/1353 for you change.

**Comment by chap-dr** [comment]
Here comes another one, Feel free to tell me off, if this is not the right place for these kinda suggestions.. 

The output of messages gets truncated, Im assuming its to keep the UI layout stable. 

Could it somehow be made expandable, or perhaps just have the full message in the alt text of a message? 

I find my self having to inspect source of page to get the full error message of deployment errors.

**Comment by alexec** [comment]
@chap-dr - thanks for your comments. I want to bring these changes to a close. Any chance I can ask you to raise a new issue and include screenshots so it is easy to identify?

**Comment by alexec** [comment]
merged and complete
