### ISSUE TITLE
Remove "sync" button from UI

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1278]
Billy Yuen suggested that this button should be disabled/remove from the UI under certain conditions. I.e. when you do not want sync to be triggered manually from the UI.

**Comment by jessesuen** [comment]
It doesn't make sense if the API and CLI are allowing it. A UI change would simply be cosmetic and provide zero security benefits. The right way to do this is through RBAC, which is already available but not being used properly in many of our environments.

**Comment by jessesuen** [comment]
Talked with the user, who didn't realize this was possible to do with RBAC.
