### ISSUE TITLE
argo cli should not use os.Getenv("HOME") to find kubeconfig

### ISSUE THREAD

**Issue by rouke-broersma** [argoproj/argo-cd#12850]
https://github.com/argoproj/argo-cd/blob/ab754052c8f01b90c63f0ef0fe6a2632652969c6/pkg/apis/application/v1alpha1/types.go#LL2571C2-L2571C2

The HOME environment variable is not used on all platforms so is not a good cross-platform solution for finding the home dir. I suggest using https://pkg.go.dev/os#UserHomeDir instead. Am I missing something or is this something I could easily contribute?

I found this because of: https://cloud-native.slack.com/archives/C01TSERG0KZ/p1678778975672349 

Please let me now if there's something else going on that make this not an actual problem, or if there's anything I should be mindful of when implementing the improvement.

**Comment by blakepettersson** [comment]
It sounds like a reasonable change IMO, we'd just need to be mindful not to accidentally break anything. From what I can see the only place it's used in the CLI is in [cluster.go](https://github.com/argoproj/argo-cd/blob/master/cmd/argocd/commands/admin/cluster.go#L505)

**Comment by todaywasawesome** [comment]
@rouke-broersma Are you going to make a PR?

**Comment by rouke-broersma** [comment]
> @rouke-broersma Are you going to make a PR?

Hi sorry completely forgot about this. I'm interested in doing this but not sure I can commit to it in the short term. I'll add it to the list in case no one else has picked it up by the time I get there 😅

**Comment by aynp** [comment]
Was a pretty small change, opened a PR for it #14325. Also changed one other location where it was being used.
