### ISSUE TITLE
Deeplink if "field exists" check not working. 

### ISSUE THREAD

**Issue by chap-dr** [argoproj/argo-cd#12851]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

When following the deeplinks example as shown here: https://argo-cd.readthedocs.io/en/stable/operator-manual/deep_links/

The `if: metadata.annotations.splunkhost` check does not work in any way shape for form, Other checks work as expected.

```
  application.links: |
    # pkg.go.dev/text/template is used for evaluating url templates
    - url: https://mycompany.splunk.com?search={{.spec.destination.namespace}}
      title: Splunk
    # conditionally show link e.g. for specific project
    # github.com/antonmedv/expr is used for evaluation of conditions
    - url: https://mycompany.splunk.com?search={{.spec.destination.namespace}}
      title: Splunk
      if: spec.project == "default"
    - url: https://{{.metadata.annotations.splunkhost}}?search={{.spec.destination.namespace}}
      title: Splunk
      if: metadata.annotations.splunkhost
```

**To Reproduce**

Add the example data and an annotation called `splunkhost` to a given application, the link does not show up. 

**Expected behavior**

To be able to follow the code snippets in the docs. 😄 

**Version**

```json
{
    "Version": "v2.6.2+6e02f8b",
    "BuildDate": "2023-02-16T15:05:14Z",
    "GitCommit": "6e02f8b23201b0620a4ff1bce5d38229ba1eb02e",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
argocd-server-b5d96cc8-84blp  server time="2023-03-14T11:41:46Z" level=error msg="errorList while evaluating application deep links, link condition 'metadata.annotations.splunkhost' evaluated to non-boolean value for resource REDACTED"
```

**Comment by chap-dr** [comment]
> @chap-dr the doc is fixed in this PR #13855, the example expected the value to be of boolean type but that was incorrect. The fix is to use `metadata.annotations.splunkhost != ""` as the condition.

Fairly sure i treid this without success, Ill revisit and report back.

**Comment by gdsoumya** [comment]
@chap-dr the example assumes that there are no annotation fields apart from `splunkhost` but if you have multiple annotations then you might need to use `metadata.annotations.splunkhost != nil && metadata.annotations.splunkhost != ""` or `application.metadata.annotations.splunkhost != nil && application.metadata.annotations.splunkhost != ""` if you are using a more recent argocd version.

**Comment by chap-dr** [comment]
> @chap-dr the example assumes that there are no annotation fields apart from `splunkhost` but if you have multiple annotations then you might need to use `metadata.annotations.splunkhost != nil && metadata.annotations.splunkhost != ""` or `application.metadata.annotations.splunkhost != nil && application.metadata.annotations.splunkhost != ""` if you are using a more recent argocd version.
> 
> There may be even better ways to construct the condition by using other operators provided by the package you can take a look at the [documentation](https://expr.medv.io/docs/Language-Definition) to construct the condition according to your needs.

Yea, that makes sense, and that was also my approach to it as i remember it (that is how I would do it when programming) but the only thing i found to work was to test on length

However since I dont know when I will be able to validate my assumptions I'm perfectly fine with leaving this as closed. 😄
