### ISSUE TITLE
FlinkDeployment stuck in Progressing state

### ISSUE THREAD

**Issue by dylanslavin** [argoproj/argo-cd#12862]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When a `FlinkDeployment` resource is in a healthy, running state, it still shows as "Progressing" in the ArgoCD UI. This causes the application health to also be in a "Progressing" state.

This bug is caused by the custom health check for FlinkDeployment resources, committed in PR #9300. The health check is looking for a field that is not present in the `FlinkDeployment` [CRD](https://github.com/apache/flink-kubernetes-operator/blob/main/helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml#L9141-L9156). For more information on this, see **Findings** below.

**To Reproduce**

1. Commit a `FlinkDeployment` to a source-controlled application monitored by ArgoCD
2. Refresh the application in ArgoCD UI
3. `FlinkDeployment` eventually becomes healthy, but status still shows "Progressing" and health details show "Waiting for Flink operator"

**Expected behavior**

`FlinkDeployment` and parent application should both be in a Healthy state.

**Screenshots**

![image](https://user-images.githubusercontent.com/9387870/225107897-70a3c8c5-9e99-44da-ae36-bef03b394c94.png)

**Version**

Couldn't log into the CLI, so here's the version info from the UI.
```shell
{
    "Version": "v2.6.1+3f143c9",
    "BuildDate": "2023-02-08T18:51:05Z",
    "GitCommit": "3f143c9307f99a61bf7049a2b1c7194699a7c21b",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Findings**

My teammates were able to work around this for our use case by adding the below custom health check to our `argocd-cm` configmap.
Possible values for lifecycleState were taken from the [FlinkDeployment CRD](https://github.com/apache/flink-kubernetes-operator/blob/release-1.4.0/helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml#L9247-L9257).
Possible values for jobStatus.state were taken from the [JobStatus enum in Flink's API](https://github.com/apache/flink/blob/master/flink-core/src/main/java/org/apache/flink/api/common/JobStatus.java)
```
    resource.customizations: |
      flink.apache.org/FlinkDeployment:
        health.lua: |
          hs = {}

          if obj.status == nil or obj.status.jobStatus == nil then
            hs.status = "Progressing"
            hs.message = "Waiting for Flink operator"

            return hs
          end

          if obj.status.lifecycleState == "STABLE" 
            and obj.status.jobStatus.state == "RUNNING"
          then
            hs.status = "Healthy"
            hs.message = "Flink deployment is running"
            return hs
          end

          if obj.status.lifecycleState == "SUSPENDED" 
            and obj.status.jobStatus.state == "FINISHED"
          then
            hs.status = "Suspended"
            hs.message = "Flink deployment has been suspended or all jobs have finished running"
            return hs
          end

          if obj.status.lifecycleState == "FAILED" then
            hs.status = "Degraded"
            hs.message = obj.status.error
            return hs
          end

          hs.status = "Progressing"
          -- This will display the same status information as a `kubectl get --watch` command
          hs.message = "Waiting for deployment's lifecycleState/jobStatus.state to be STABLE/RUNNING; currently in " .. obj.status.lifecycleState .. "/" .. obj.status.jobStatus.state .. " state"

          return hs
```

Since I am not a Flink expert, I'm hoping that someone more familiar with Flink can verify whether this approach would work in the general case.

**Comment by yinheli** [comment]
I meet the same issue. work around by `resource.customizations` configuration, app health goes "Healthy".


But the task manager job still "Progressing", although the pod is running.

```
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
```

I guss the pod health check policy cause this. refer: https://github.com/argoproj/gitops-engine/blob/master/pkg/health/health_pod.go#L119

**Comment by fr6nco** [comment]
Struggling with this too. Yes restartpolicy is set to never by the flink operator as shown in the docs too:

"always" for JobManager pod and "never" for TaskManager pod.
The JobManager pod will always be restarted by deployment. And the TaskManager pod should not be restarted.

https://nightlies.apache.org/flink/flink-docs-release-1.13/docs/deployment/resource-providers/native_kubernetes/#pod-template

**Comment by gchait** [comment]
Encountering this as well.
No idea if the issue is in Argo CD or in Flink Operator, but this is the only place I found I can write in since they don't use GitHub for issues, sadly.

**Comment by crenshaw-dev** [comment]
If this is something we can change in a backwards-compatible way, we can add it to the built-in check.

**Comment by jwenz723** [comment]
> Similar to the patch proposed by @dylanslavin , this version only slightly changes what is originally implemented here: https://github.com/argoproj/argo-cd/blob/master/resource_customizations/flink.apache.org/FlinkDeployment/health.lua
> 
> ```
> resource.customizations: |
>   flink.apache.org/FlinkDeployment:
>     health.lua: |
>       health_status = {}
> 
>       if obj.status ~= nil and obj.status.reconciliationStatus ~= nil then
>       if obj.status.reconciliationStatus.state == "DEPLOYED" then
>       health_status.status = "Healthy"
>       return health_status
>       end
> 
>       if obj.status.jobManagerDeploymentStatus == "DEPLOYED_NOT_READY" or obj.status.jobManagerDeploymentStatus == "DEPLOYING" then
>       health_status.status = "Progressing"
>       health_status.message = "Waiting for deploying"
>       return health_status
>       end
> 
>       if obj.status.jobManagerDeploymentStatus == "ERROR" then
>       health_status.status = "Degraded"
>       health_status.message = obj.status.reconciliationStatus.error
>       return health_status
>       end
>       end
> 
>       health_status.status = "Progressing"
>       health_status.message = "Waiting for Flink operator"
>       return health_status
> ```
> 
> In flink-kubernetes-opeator 1.5.0 `status.reconciliationStatus.success` does not exist anymore, but `status.reconciliationStatus.state`, where value `DEPLOYED` indicates everything-up-to-date

This healthcheck worked for me with flink operator version 1.5.0.

As was already stated, the FlinkDeployment CRD in version 1.5.0 has a field named [status.reconciliationStatus.state](https://github.com/apache/flink-kubernetes-operator/blob/be07be7dfee037dec6390d91b24f3ff2f2664e04/helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml#L9306). The `status.reconciliationStatus.state` field has existed since version [1.0.0](https://github.com/apache/flink-kubernetes-operator/blob/fa2cd14da0363ba11ab5c10464d05fa3901edcb4/helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml#L9107). 

The field named `status.reconciliationStatus.success` was removed in [this commit](https://github.com/apache/flink-kubernetes-operator/commit/2204231164bbbe4cfe87e95de54a07290fd95b9f). 

I think it would make sense to update the FlinkDeployment healthcheck to replace `status.reconciliationStatus.success` with `status.reconciliationStatus.state`.
