### ISSUE TITLE
Argo-cd could not obtain helm chart version using range

### ISSUE THREAD

**Issue by mpuch12** [argoproj/argo-cd#12914]
**Describe the bug**

Argo-CD is unable to resolve helm chart version using range (* or 0.0.*). When only available version in repository is 
(0.0.1-SNAPSHOT). After deploying another version (0.0.1) argo resolve version with success to (0.0.1).

**To Reproduce**

Have a helm chart with version 0.0.1-DRAFT
Create Application in Argo-CD UI with helm chart and version like (0.0.*)  or (>=0.0.0)

**Expected behavior**

Submitted application is syncing with (0.0.1-DRAFT) version

**Version**

```shell
argocd: v2.6.4+7be094f
  BuildDate: 2023-03-07T22:48:16Z
  GitCommit: 7be094f38d06859b594b98eb75c7c70d39b80b1e
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2023-03-17T08:27:30Z" level=info msg="received unary call /application.ApplicationService/Create" grpc.method=Create grpc.request.content="%!v(PANIC=String method: reflect.Value.Interface: cannot return value obtained from unexported field or method)" grpc.service=application.ApplicationService grpc.start_time="2023-03-17T08:27:30Z" span.kind=server system=grpc

time="2023-03-17T08:27:30Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec for test is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = constraint not found in index" grpc.code=InvalidArgument grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2023-03-17T08:27:30Z" grpc.time_ms=197.092 span.kind=server system=grpc
```

**Comment by Damian-Truszkiewicz** [comment]
I've eventually managed to get it fixed, but I have to admit, the beginning was pretty puzzling, and it required a fair amount of time and investigation to pinpoint the cause.
