### ISSUE TITLE
ArgoCD Application Stuck at Refresh 

### ISSUE THREAD

**Issue by punyautkalika** [argoproj/argo-cd#12915]
Argocd stuck at refresh frequently .I ma using Argo CD v2.5.11 .
Every time i restart controller pod it fix the issue . I would like to now permanent solution for this and how can i monitor when it get stuck for the precaution.

**Comment by s7an-it** [comment]
same thing on 2.6.5, I see helm repo add run for each app I think this is the root cause

**Comment by punyautkalika** [comment]
can i get any update on this

**Comment by alexdga** [comment]
Same problem here using argocd 2.6.6. Frequently on application refresh, argocd ui gets stucked on loading ... .

**Comment by punyautkalika** [comment]
is there any solution for this

**Comment by Tizull** [comment]
I am also having this issue.

**Comment by alexdga** [comment]
I managed to solve this problem using tcp instead of http from my lb (haproxy) to kubernetes ingress and api.

**Comment by jgwest** [comment]
Duping to 15519, which has more discussion and a better defined problem description.
