### ISSUE TITLE
Application's `spec.syncPolicy.PreserveResourcesOnDeletion` not updated upon change

### ISSUE THREAD

**Issue by stang** [argoproj/argo-cd#12937]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We are currently running argocd `v2.6.2`.

While preparing some maintenance operations, I was trying to figure out how I could _delete an `Application` object, without deleting its child resources_.

The documentation mentions that:
* we can set `.spec.syncPolicy.preserveResourcesOnDeletion: true` in the `ApplicationSet` ([see docs](https://argocd-applicationset.readthedocs.io/en/stable/Controlling-Resource-Modification/#prevent-an-applications-child-resources-from-being-deleted-when-the-parent-application-is-deleted))
* the lifecycle for `Application` and `ApplicationSet` are quivalent ([see docs](https://argocd-applicationset.readthedocs.io/en/stable/Application-Deletion/))

Therefore, I've assumed that I could set `.spec.syncPolicy.preserveResourcesOnDeletion: true` directly in the `Application` object, which is only partially true.

According to my tests:
* if `.spec.syncPolicy.preserveResourcesOnDeletion: true` is set at the time the `Application` is created, it will be taken into account
* however, if the `.spec.syncPolicy.preserveResourcesOnDeletion` field is edited **after** the `Application` is created, it is no longer taken in account

I suspect this is not the expected behavior as it might create confusion for the end user.

**To Reproduce**

1. create a new `Application` without specifying the `.spec.syncPolicy.preserveResourcesOnDeletion` property
2. edit the `Application` to add `.spec.syncPolicy.preserveResourcesOnDeletion: true`
3. delete the `Application`

👉 the child resources of your application will be gone after `step 3.` 👎 

**Expected behavior**

I'd either expect:

* :a: to have the controller honor the same behavior when `.spec.syncPolicy.preserveResourcesOnDeletion: true` is set, regardless of when the property has been set
* or :b: have an explicit error saying that `.spec.syncPolicy.preserveResourcesOnDeletion` is an immutable field

**Screenshots**

N/A

**Version**

```shell
argocd: v2.6.2+6e02f8b
  BuildDate: 2023-02-16T15:05:14Z
  GitCommit: 6e02f8b23201b0620a4ff1bce5d38229ba1eb02e
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

**Comment by rybkin-me** [comment]
Same here. 

I'm trying to delete an applicationset with its applications without deleting their generated child resources, and adding `.spec.syncPolicy.preserveResourcesOnDeletion` doesn't help. Tried to overwrite the `metadata.finalizers` key on application with empty array, still nothing.

**Comment by rybkin-me** [comment]
Found the way to remove finalizers from all applications in argocd namespace:

`kubectl get Application -A -o name | xargs kubectl patch -p '{"metadata":{"finalizers":null}}' --type=merge -n argocd`

But if the application was generated with applicationset -- the finalizer will be restored, thus to delete applicationset without deleting child resources you need to first remove applicationset `kubectl delete applicationset <applicationsetname> --cascade=orphan -n argocd` and then patch all applications to remove finalizers. If you try to recreate applicationset after that finalizers will return (even if you specify `syncPolicy.syncOptions.preserveResourcesOnDeletion=true`)

**Comment by jannfis** [comment]
I think this issue was resolved by https://github.com/argoproj/argo-cd/pull/11462

**Comment by jannfis** [comment]
CLosing this bug. If it persists, please feel free to re-open.

**Comment by leevs** [comment]
We still encounter this issue where it does not get applied after the application is already created.

` 
syncPolicy:
    automated:
        allowEmpty: false
        prune: false
        selfHeal: true
    preserveResourcesOnDeletion: true
`

**Comment by sshafiullah** [comment]
Still not working. ArgoCD version: v2.11.2
`apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset
  namespace: argo-cd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true`

**Comment by switchboardOp** [comment]
this is still an issue ini 2.13.1

![Image](https://github.com/user-attachments/assets/899926c5-1d87-471a-b956-cdaf7795faff)

**Comment by GuyYakobov** [comment]
> Same here.
> 
> I'm trying to delete an applicationset with its applications without deleting their generated child resources, and adding `.spec.syncPolicy.preserveResourcesOnDeletion` doesn't help. Tried to overwrite the `metadata.finalizers` key on application with empty array, still nothing.

were you able to do so? i was thinking maybe put spec.syncPolicy.preserveResourcesOnDeletion only in the template of the applications in the applicationset.yaml and not to the actal applicationset.
