### ISSUE TITLE
Bitbucket support for notifications

### ISSUE THREAD

**Issue by Almenon** [argoproj/argo-cd#12954]
# Summary

What change you think needs making.
Add Bitbucket to notification services

# Motivation

Please give examples of your use case, e.g. when would you use this.
It's unclear when a app is deployed without notification, especially to newcomers. Sometimes edge cases can happen when nothing gets deployed, like if a applicationset is not looking at the target folder.

There's literally dozens of people who use bitbucket! Dozens!

# Proposal

How do you think this should be implemented?
bitbucket PR comment or check.

**Comment by Almenon** [comment]
Workaround: Deploy notifications via slack

**Comment by morey-tech** [comment]
Argo CD Notification Services are provided by [argoproj/notifications-engine](https://github.com/argoproj/notifications-engine). I believe there is the best place to request support for BitBucket or maybe add your support to https://github.com/argoproj/notifications-engine/issues/138
