### ISSUE TITLE
Add controller namespace to .status of Application

### ISSUE THREAD

**Issue by gnunn1** [argoproj/argo-cd#12964]
# Summary

There are use cases where you need to backtrack from the Application object to the controller that is managing it. Prior to Applications in Any Namespace this was trivial since the Application object had to be in the same namespace as the controller however this is no longer the case.

# Motivation

A couple of use cases:

- When building alternative user interfaces and you want to construct a link for the Application to the Argo CD UI
- When troubleshooting Applications being able to map it back to the controller can be very helpful when operating in clusters with many Argo instances.

# Proposal

The application-controller should add a new new field to the .status of the Application indicating the namespace the controller resides in. For example:

```
status:
  **controller-namespace: argocd**
  conditions:
  - lastTransitionTime: "2023-03-22T00:05:23Z"
    ...
  health:
    status: Healthy
  history:
  ...
```

**Comment by ItsKev** [comment]
I would like to have a look at this.
/assign
