### ISSUE TITLE
Resource exclusion keeps resource out of sync and missing

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1296]
With rc4 it shows rolebinding out of sync -> missing, but the resource already exists in the cluster

![image](https://user-images.githubusercontent.com/9946020/54597216-78fc4980-4a36-11e9-8784-d2acd0e28ab3.png)
```
oc get RoleBinding -n demo-acc admin-demo-acc -o yaml
apiVersion: authorization.openshift.io/v1
groupNames:
- petertestgroep
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"authorization.openshift.io/v1","groupNames":["petertestgroep"],"kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"generic-all-cluster"},"name":"admin-demo-acc","namespace":"demo-acc"},"roleRef":{"name":"admin"},"subjects":[{"kind":"Group","name":"petertestgroep"}],"userNames":["dummy"]}
  creationTimestamp: 2019-03-11T13:33:30Z
  labels:
    app.kubernetes.io/instance: generic-all-cluster
  name: admin-demo-acc
  namespace: demo-acc
  resourceVersion: "16594142"
  selfLink: /apis/authorization.openshift.io/v1/namespaces/demo-acc/rolebindings/admin-demo-acc
  uid: 423b13a8-4402-11e9-8a91-0050568a5984
roleRef:
  name: admin
subjects:
- kind: User
  name: dummy
- kind: Group
  name: petertestgroep
userNames:
- dummy
```

I am using the following config for exclusion:

```
  resource.exclusions: |
    - apiGroups:
      - project.openshift.io
      - rbac.authorization.k8s.io
      clusters:
      - '*'
      kinds:
      - '*'
```

**Comment by jessesuen** [comment]
@peterbosalliandercom — the resources you should be excluding are the ones that you are *not* tracking in git, which I think for you would be the openshift resources.

Can you exclude:
- project.openshift.io
- authorization.openshift.io

But not exclude rbac.authorization.k8s.io?

**Comment by peterbosalliandercom** [comment]
Probably this issue has to do with wrong syncing: https://github.com/argoproj/argo-cd/issues/1362

**Comment by peterbosalliandercom** [comment]
The problem here is that we do not want to see excluded resources at all in the UI. Is there a way to get a healthy application without seeing the excluded resources as missing under the tree?

**Comment by peterbosalliandercom** [comment]
this is my exclusion: ```    resource.exclusions: |
      - apiGroups:
        - project.openshift.io
        - authorization.openshift.io
        clusters:
        - '*'
        kinds:
        - '*'
```

**Comment by jessesuen** [comment]
I am going to dupe this to https://github.com/argoproj/argo-cd/issues/1224. We need proper support for openshift and not resource exclusions.
