### ISSUE TITLE
Improvement of Application LIST API Function

### ISSUE THREAD

**Issue by tken2039** [argoproj/argo-cd#12985]
# Summary

- The response time for the Application List API (GET /api/v1/applications) is very slow.
- It appears that the slow response is due to the filtering process based on permissions.
  - Through investigation and verification, it has been discovered that the API response slows down in proportion to the number of Applications and RBAC Policies.
- We would like to make modifications to this API so that it operates more efficiently even in environments where there are a large number of Applications and Policies to manage.

# Motivation

- We are managing over 200 projects and 4,500 applications, but we have been experiencing significant delays in retrieving the application list for some time now.
- We have confirmed that the issue has already been raised in the following discussion, but no improvements have been made yet:
  - <https://github.com/argoproj/argo-cd/discussions/8446>
- We have measured the time for each process and identified the process that caused the problem, so we would like your cooperation in studying countermeasures.

# Problem and Approaches

## The processing that is causing performance issues

- Upon reviewing the Applications List API processing, we found that the [Application filtering process by permission](https://github.com/argoproj/argo-cd/blob/v2.6.6/server/application/application.go#L149-L159) takes up most of the overall processing time.
  - Further investigation revealed that the time-consuming processes were related to the checks to determine if the user has permission to access the corresponding Application and caching the result.
    - However, processing with cached results is very fast.
  - Since the process retrieves all Applications first and filters them based on permissions, the processing time increases with the number of Applications and Policies.
    - In our environment with about 4500+ Applications and 10,000 Policies, it takes more than 60 seconds to complete the process.

### 1. Reduce the Number of Applications Filtered by Permissions

As an example, a detailed approach is described below.

- At the [stage of obtaining the Application from the Informer](https://github.com/argoproj/argo-cd/blob/v2.6.6/server/application/application.go#L141-L145), reduce the number of Applications is obtained.
  - This process depends on the `kubernetes/client-go` package and it seems difficult to perform flexible filtering.
- Filter Applications according to the Role held by the User before performing Enforce by Permissions.
  - However, the Policy settings of the RBAC Config need to follow the [Policy Rule](https://casbin.org/docs/performance#:~:text=Grant%20permissions%20to,681%23issuecomment%2D763801583) recommended by Casbin.
  - By adding this process to the ArgoCD we manage, we have successfully reduced processing time significantly.
- Move [filtering process by the request query](https://github.com/argoproj/argo-cd/blob/v2.6.6/server/application/application.go#L161-L172) to the pre stage of Enforce by Permissions.
  - This is a simple approach. When set the filter on the Web-UI (`/applications` page), the query is added to the API executed on the page. This is not a fundamental solution, but it seems to be sufficient as a temporary measure.

### 2. Improve the Efficiency of Enforce Process

Relevant process: <https://github.com/argoproj/argo-cd/blob/v2.6.6/server/application/application.go#L156-L158>

In fact, [the API for obtaining Clusters with the same Permissions filtering process as mentioned above](https://github.com/argoproj/argo-cd/blob/v2.6.6/server/cluster/cluster.go#L60-L64) has also been taking time to respond due to the reasons stated earlier. Therefore, it is considered that improving the efficiency of this filtering process is the fundamental solution.
On the other hand, this process is complex and a sensitive area regarding Permission, so it seems difficult to fix.

## Conclusion

Please help us to solve this problem.
If you have any innovative approaches, please let us know.

**Comment by crenshaw-dev** [comment]
> Filter Applications according to the Role held by the User before performing Enforce by Permissions

Can you describe this in more depth? How do you filter by the user's role?

> Move [filtering process by the request query](https://github.com/argoproj/argo-cd/blob/v2.6.6/server/application/application.go#L161-L172) to the pre stage of Enforce by Permissions.

I love this. Would you be willing to open a PR?

There's an open PR which seems like it can successfully cut down response time by maybe 70%. https://github.com/argoproj/argo-cd/pull/11884

@zachaller and I looked at that PR and concluded that, which it does speed things up, it 1) introduces quite a bit of complexity, and 2) might get its speed win by throwing more CPUs at an inefficient process - maybe we should work on the process instead.

I suspect that compiling glob patterns may be a significant bottleneck. We could look at caching compiled globs.

**Comment by zachaller** [comment]
@tken2039 Thanks, for the analysis I think this also confirms a bit what me and @crenshaw-dev saw as well and digs into a bit of where the bottlenecks are. I think the parallelization effort is an easier win like @crenshaw-dev mentioned but I do think it slightly hides an inefficient process as well.

I am not opposed to the parrelization PR especially if the complexities fixing the process are more complex, especially in an area related to permissions. I would though be curious on what a fixing the process PR would look like in complexities vs the parrelization efforts.

**Comment by tken2039** [comment]
Thank you for your comment.

> Can you describe this in more depth? How do you filter by the user's role?

In our ArgoCD, we match the Role Name in the Policy with the Project Name.
Therefore, retrieving the User's Role has the same effect as retrieving the projects in which the User participates.
Then, filter applications by the obtained Role Name (=Project Name).

> There's an open PR which seems like it can successfully cut down response time by maybe 70%. https://github.com/argoproj/argo-cd/pull/11884

I once thought about parallelizing the Enforce Process.
However, I thought that controlling the number of goroutine processes when considering multiple simultaneous accesses, etc. would be an issue.

I hope the above PR will discover something answer.

**Comment by reggie-k** [comment]
If going for caching compiled globs,  maybe I should do that  for custom health checks, which now also contain globs (not sure they already introduce slowliness but are constantly growing in number).
