### ISSUE TITLE
Getting errors / page not loading whilst using list view in argocd 

### ISSUE THREAD

**Issue by adityatanwar03** [argoproj/argo-cd#13019]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
@adityatanwar03 can you please add details?

**Comment by todaywasawesome** [comment]
@adityatanwar03 feel free to recreate the issue with details. This doesn't give us enough information to do anything. Closing for now.
