### ISSUE TITLE
Cannot reference sidecar plugin by name

### ISSUE THREAD

**Issue by spykermj** [argoproj/argo-cd#13034]
I'm running ArgoCD 2.6.7 and I also have the problem as described.

I have a repository where the main branch works, but the `demonstrate_name_problem`  branch does not. The only difference can be shown here (the difference is that the broken one tries to reference the sidecar plugin by name).

https://github.com/spykermj/argocd-tanka-plugin/pull/3

The error when it fails is: `rpc error: code = Unknown desc = plugin sidecar failed. couldn't find cmp-server plugin with name tanka supporting the given repository`

Have I missed something in the documentation?

_Originally posted by @spykermj in https://github.com/argoproj/argo-cd/discussions/8216#discussioncomment-5457890_

**Comment by crenshaw-dev** [comment]
When a sidecar plugin config specifies a `spec.version`, the Application's `spec.source.plugin.name` must specify `<plugin name>-<plugin version>`.

Looking at your repo, I think it would be `name: tanka-v1.0`.

Also keep in mind that, if the plugin's config specifies discovery rules, those rules must match in addition to the name matching.

**Comment by spykermj** [comment]
Thank you @crenshaw-dev . That has indeed fixed the problem.
