### ISSUE TITLE
Allow argocd-notifications-controller log level and log format be defined with environment variables

### ISSUE THREAD

**Issue by pre** [argoproj/argo-cd#13039]
# Summary

Currently log format and log level can be changed with environment variables (via ConfigMap argocd-cm) except for argocd-notifications-controller. 

To get log format json and log level warn, argocd-notifications-controller Deployment's command needs to be patched with `--loglevel` and `--logformat`.

Notifications controller: https://github.com/argoproj/argo-cd/blob/5bcd846fa16e4b19d8f477de7da50ec0aef320e5/manifests/ha/install.yaml#L16922

In contrast to eg. applicationset-controller:
https://github.com/argoproj/argo-cd/blob/5bcd846fa16e4b19d8f477de7da50ec0aef320e5/manifests/ha/install.yaml#L16731-L16741

# Motivation

- Settings via the ConfigMap are less error prone than having to define the whole `command`. 
- Other components already support this mechanism. 

# Proposal

How do you think this should be implemented?

With love and care.

**Comment by noaabarki** [comment]
Hi @pre! I'd like to take this one :)

**Comment by pre** [comment]
@noaabarki go ahead

**Comment by pre** [comment]
@noaabarki great job! while at it, could you check that all the argocd components now support these environment variables? Thanks!
