### ISSUE TITLE
Support YAML editor on helm parameter

### ISSUE THREAD

**Issue by chocopowwwa** [argoproj/argo-cd#1305]
i see that argo support overriding helm values and also supporting nested object, but for array of object value, it still print something like

Example of array of object key

Yaml representation:
```
configMap:
- name: string-here
```
Actual Output:
```
[map[name:string-here]]
```

**Comment by alexec** [comment]
@alexmt to provide work-around.

**Comment by alexec** [comment]
@chocopowwwa I'm struggling to understand how to reproduce this. Are you able to provide any steps please?

**Comment by alexec** [comment]
Is this needed due to #1930?

**Comment by chocopowwwa** [comment]
Hi, sorry i didn't explain the issue clearly,
The issue happens on argo-cd web-ui, at details modal on parameters section

Action: i want to edit helm values which is an array of object
Actual: I couldn't edit the value via argo-cd web-ui because the key was parsed to a go object, and printed as a go object (map in this case)

i don't think the issue #1930  were related

Here's another way to reproduce the issue
deploy helm `@stable` `nginx-ingress` and see if your can the `tolations` this parameter via argo-cd web-ui https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L135

**Comment by alexec** [comment]
@chocopowwwa thank you for getting back to me.

I'm struggling to understand how to reproduce this. Can I ask you to list the exact steps and maybe add some screenshots to show the problem please?

**Comment by alexec** [comment]
Ok. I've observed this behaviour for the `nginix-ingress` chart in stable. So it is reproducible. However, the fix is complex and the ability to enter the `values.yaml` file allows you to achieve the same thing. I think we should avoid showing these in the UI.

**Comment by alexec** [comment]
See https://github.com/helm/helm/issues/2547

**Comment by alexec** [comment]
See #2046
