### ISSUE TITLE
ArgoCD App Target Revision drop down transparent, not visible to read

### ISSUE THREAD

**Issue by EdwinPhilip** [argoproj/argo-cd#13067]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
After creating app in argocd, when trying to change the Target revision i.e. choose different branch other than default `HEAD`, the list of branch drop down overlaps with the fields below such as `Path` etc 

looks like the drop down listing branches is transparent and makes not visible to read the branch names properly

**To Reproduce**

After creating app in argocd, Click on `App details` > `Edit` 
Try to change `Target Revision`

**Expected behavior**
The `Target Revision` drop down is visible to read the branch names properly

**Screenshots**
<img width="1479" alt="Screenshot 2023-03-31 at 6 29 58 PM" src="https://user-images.githubusercontent.com/38521046/229128500-c625a75a-855a-4e73-b510-b7410b3b2fdf.png">

**Closer look:**
<img width="1386" alt="Screenshot 2023-03-31 at 6 29 42 PM" src="https://user-images.githubusercontent.com/38521046/229128595-9af2e2c0-a3d4-4ac6-b2c5-4327b405c338.png">

**Version**

```shell
{
    "Version": "v2.6.7+5bcd846",
    "BuildDate": "2023-03-23T14:57:27Z",
    "GitCommit": "5bcd846fa16e4b19d8f477de7da50ec0aef320e5",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Comment by caseyg-ronin** [comment]
Same issue seen on `v2.6.7+5bcd846` and `v2.7.4+a33baa3.dirty`
