### ISSUE TITLE
ArgoCD Projects drop down in UI not filtering like repo or cluster

### ISSUE THREAD

**Issue by EdwinPhilip** [argoproj/argo-cd#13069]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When creating a new app and trying to choose Project, the drop down doesn't filter based on the characters types.
I had to manually scroll down to find the correct Project and choose it

**To Reproduce**
Try to create a new app, choose project, the drop down opens up. Starting typing characters but Projects is not filtered.

**Expected behavior**
Projects drop down filters values based on the input characters

**Screenshots**
<img width="1094" alt="Screenshot 2023-03-31 at 6 50 36 PM" src="https://user-images.githubusercontent.com/38521046/229132527-fc03cbf7-dff1-4a03-9b61-f6547ab32679.png">

**Version**

```json
{
    "Version": "v2.6.7+5bcd846",
    "BuildDate": "2023-03-23T14:57:27Z",
    "GitCommit": "5bcd846fa16e4b19d8f477de7da50ec0aef320e5",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```
I have been upgrading our argocd cluster from 2.3.1 to 2.4.28, then to 2.5.16 and then 2.6.7
I think i started noticing this in 2.5.x and 2.6.x

**Comment by ciiay** [comment]
I'd like to work on this.

**Comment by keithchong** [comment]
@crenshaw-dev , this might be good candidate to cherry pick for the 2.7 release.
