### ISSUE TITLE
App in Any Namespace cross instance leakage

### ISSUE THREAD

**Issue by gnunn1** [argoproj/argo-cd#13077]
Checklist:

* [ X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

If you have multiple Argo CD instances deployed on a cluster and one of them is using Apps in Any Namespace and both have projects with the same name the instance with Apps in Any Namespace will show the Applications associated with the other instances projects. To lay this out more concretely

Instance 1 - Used for cluster configuration
Namespace: openshift-gitops
AppProject: rollouts-demo
Scope: Cluster scoped

Instance 2 - Used for tenants,uses Apps in Any Namespace
Namespace: gitops
AppProject: rollouts-demo
Scope: Cluster scoped

In Instance 2 I can see the application tiles from instance 1 that are associated with that instances `rollouts-demo` AppProject.

Note trying to interact with that these applications fails

**To Reproduce**

1. Deploy two instances of Argo CD in the same cluster with cluster scoping
2. Configure one instance to use Applications in Any Namespace
3. Deploy an identically named AppProject to both instances
4. Deploy applications in each instance associated with their respective AppProject
5. Check the UI and you should see both apps

Changing the AppProject names so they do not match fixes the problem.

**Expected behavior**

Only the apps associated with the current instance of Argo should be shown. 

**Screenshots**
![App-From-Wrong-Instance](https://user-images.githubusercontent.com/9358238/229299290-9dc40b5b-ecfc-46f1-a74e-cfc8bd1a4d63.png)

**Version**

```
argocd: v2.6.7+unknown
  BuildDate: 2023-03-24T01:08:09Z
  GitCommit: 
  GitTreeState: 
  GitTag: 2.6.7
  GoVersion: go1.20.2
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.7+unknown
  BuildDate: 2023-03-21T06:28:12Z
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 1970-01-01T00:00:00Z
  Helm Version: v3.10.0+ge534a5d
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Comment by gr-raphlau** [comment]
I believe we're impacted by this as well (https://github.com/argoproj/argo-cd/discussions/15308) and given that the other argo in the namespace have apps using the `default` project, there isn't a workaround available to us I believe.

**Comment by jannfis** [comment]
The following PR might have fixed this issue: https://github.com/argoproj/argo-cd/pull/14479

**Comment by jannfis** [comment]
My initial tests with versions >= 2.8.0 (which have mentioned PR merged) show that the issue should be solved. It's not been cherry-picked into other releases, yet. 

I'll take care of that.

**Comment by gr-raphlau** [comment]
That's great news, thanks for checking. Is it possible to back-port to 2.5.X too (first release of this feature)? We're a bit behind with upgrades at the moment and that would be very helpful.

**Comment by jannfis** [comment]
@gr-raphlau Unfortunately, 2.5 is EOL since quite a while and won't receive any updates more, including security fixes. 

I would strongly suggest you to upgrade to a more recent release.

**Comment by crenshaw-dev** [comment]
Gonna close for now until we hear back that #14479 didn't do the trick.
