### ISSUE TITLE
Getting error while creating project

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#13129]
### Discussed in https://github.com/argoproj/argo-cd/discussions/12969

<div type='discussions-op-text'>

<sup>Originally posted by **Shubham1406220** March 22, 2023</sup>
argocd proj create dev --file project-dev.yaml

Getting this error while running the command from cli
`FATA[0000] error reading proj from uri: %!w(<nil>) `</div>

**Comment by alexmt** [comment]
Fixed

**Comment by bkimbrough88** [comment]
for those still looking, looks like this was fixed in 2.6 and 2.7 based on what I'm seeing in #13130
