### ISSUE TITLE
Add Sync date to application tile

### ISSUE THREAD

**Issue by lchastel** [argoproj/argo-cd#13141]
# Summary
I would like to have the date of last successful synchronisation on the tile of application.

# Motivation
I have lot of projects that are using argocd.
A user asked when his application was deployed the last time on the different environments.

The current solution is to go in each application and check the date.

# Proposal
I would like to have the date of last synchronisation in the tile of application.
It could be a new field, or maybe it could replace the Creation date (which I think is less needed that the sync date.

In attachment you could see the current display of tiles.
![argocd_application_tiles](https://user-images.githubusercontent.com/44160341/230326994-0a9b5086-0d4d-4397-a8ca-4ccdf4229cea.png)

**Comment by blazehu** [comment]
@lchastel @jgwest  I am new to the community and looking forward to contributing. Can I pick this issue?

**Comment by lchastel** [comment]
@blazehu according to the ticket, @reginapizza already implement it.
It just need to be merge to main repository.

**Comment by blazehu** [comment]
@lchastel ok
