### ISSUE TITLE
ExternalSecret and Secrets not purged when deleting Application via Kubectl

### ISSUE THREAD

**Issue by kevin-kho** [argoproj/argo-cd#13168]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I'm currently using [External Secret Operator](https://github.com/external-secrets/external-secrets/) to manage my secrets. It works completely fine when I create an ArgoCD Application, but if I tear down an Application with Kubectl command, the External Secret and the generated Secrets do not get deleted.

It works fine when tear down the Application with the argocd CLI: `argocd app delete <APPLICATION-NAME>`

**To Reproduce**

1. Bring up an Application via `kubectl apply -f <APPLICATION>.yaml -n application-ns`
2. Wait til everything is sync'd
3. Tear down the application via `kubectl delete -f <APPLICATION>.yaml -n application-ns`
4. Check the ExternalSecrets and Secrets via `kubectl get es -n application-ns` and `kubectl get secrets -n application-ns`
5. The ExternalSecrets and Secrets are still in the NS

**Expected behavior**

The ExternalSecrets and Secrets should no longer exist in the application-ns after tearing down the project with `kubectl delete -f <APPLICATION>.yaml -n application-ns`

**Screenshots**

**Version**
argocd: v2.6.7+5bcd846.dirty
argocd-server: v2.6.7+5bcd846
External Secret Operator: 0.8.1

**Comment by jannfis** [comment]
It seems you don't set resource finalizers on your Application prior to deleting it using kubectl.

Did you check https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/#deletion-using-kubectl ?

**Comment by kevin-kho** [comment]
> It seems you don't set resource finalizers on your Application prior to deleting it using kubectl.
> 
> Did you check https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/#deletion-using-kubectl ?

Thanks! This seemed to solved the issue.
