### ISSUE TITLE
Dex server not using structured/json logging consistently with `--logformat json`

### ISSUE THREAD

**Issue by kaiburjack** [argoproj/argo-cd#13191]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When starting the `argocd-dex` executable with `--logformat json`, then _some_ log outputs are structured/json, while others are not.
In our particular setup, we use [the Argo CD Helm chart in version 5.28.1](https://artifacthub.io/packages/helm/argo/argo-cd) and supply the `--logformat json` [via the `dex.extraArgs` Helm value](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L861) and a `ps` inside of the pod confirms that the `argocd-dex` executable was started accordingly as `/shared/argocd-dex rundex --logformat json`.

We are currently going over all our logs that are erroneously categorized as "errors" by fluentbit/Stackdriver in GCP/GKE, just because they emit log lines in non-json format on stderr. For this, all log output should use structured/json logging.

The log output produced by this is seen below in the "Logs" section. Notably, it contains both structured log output as well as text output. The latter is likely produced by the spawned/started `dex` executable.

It would be nice if using `--logformat json` also applies to the started `dex` program (somehow).

**To Reproduce**

- start the `argocd-dex` component using `rundex --logformat json`
- observe that some log outputs are structured/json while others are not

**Expected behavior**

All log messages output by `argocd-dex` (and sub-processes started by it, notably the `dex` executable) should use structured/json logging consistently such that those log lines can be identified and classified correctly by other external tools like a GCP/GKE-provided fluentbit Log Agent.

**Version**

```shell
argocd: v2.6.7+5bcd846
  BuildDate: 2023-03-23T14:57:27Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified 
```

**Logs**

```
{"built":"2023-03-23T14:57:27Z","commit":"5bcd846fa16e4b19d8f477de7da50ec0aef320e5","level":"info","msg":"ArgoCD Dex Server is starting","namespace":"argocd","time":"2023-04-11T13:20:40Z","version":"v2.6.7+5bcd846"}
{"level":"info","msg":"Generating self-signed TLS certificate for this session","time":"2023-04-11T13:20:40Z"}
{"level":"info","msg":"Starting configmap/secret informers","time":"2023-04-11T13:20:40Z"}
{"level":"info","msg":"Configmap/secret informer synced","time":"2023-04-11T13:20:40Z"}
{"level":"info","msg":"0xc00034c780 subscribed to settings updates","time":"2023-04-11T13:20:40Z"}
time="2023-04-11T13:20:40Z" level=info msg="Dex Version: v2.35.3-dirty, Go Version: go1.19.2, Go OS/ARCH: linux amd64"
time="2023-04-11T13:20:40Z" level=info msg="config issuer: https://argocd.<redacted>/api/dex"
time="2023-04-11T13:20:40Z" level=info msg="config storage: memory"
time="2023-04-11T13:20:40Z" level=info msg="config static client: Argo CD"
time="2023-04-11T13:20:40Z" level=info msg="config static client: Argo CD CLI"
time="2023-04-11T13:20:40Z" level=info msg="config connector: google"
time="2023-04-11T13:20:40Z" level=info msg="config skipping approval screen"
time="2023-04-11T13:20:40Z" level=info msg="config refresh tokens rotation enabled: true"
time="2023-04-11T13:20:40Z" level=info msg="keys expired, rotating"
time="2023-04-11T13:20:41Z" level=info msg="keys rotated, next rotation: 2023-04-11 19:20:41.062843144 +0000 UTC"
time="2023-04-11T13:20:41Z" level=info msg="listening (telemetry) on 0.0.0.0:5558"
```

**Comment by riteshnanda09** [comment]
Those logs are from identity service server `dexidp/dex` . Looking at code looks logging flags from argocd-dex executable are not passed to dex server, but config for dex server can be specified in configmap `argocd-cm` in `dex.config` object.


```yaml
dex.config: |
    logger:
      level: debug
      format: json
    connectors:
      - type: saml
     ...
```

**Comment by nlamirault** [comment]
confirmed it works fine as @riteshnanda09 said.
