### ISSUE TITLE
allow for parameters in configuration plugins

### ISSUE THREAD

**Issue by timothyjlaurent** [argoproj/argo-cd#1323]
The custom plugins add greater flexibility to the argo deployments, however there are situations where additional prarameters to the plugin would be helpful.

In our case we have a helm chart that lives alongside application code. For deploying, we would like to be able to pull the chart to the deployment repo, `helm template`, and then use kustomize to render the final yaml.

To accomplish this we could use environment variables eg `CHART_GIT_REPO`, `CHART_PATH`, and `GIT_REVISION` declared in the Application yaml file that the plugin would be able to access and could be used to perform the above steps.

**Comment by jessesuen** [comment]
We should allow user defined env vars, in addition to ARGOCD_ env vars.

**Comment by alexec** [comment]
See https://github.com/argoproj/argo-cd/issues/1705.

**Comment by alexec** [comment]
Fixed in v1.2
