### ISSUE TITLE
SSO with Keycloak using 16.x

### ISSUE THREAD

**Issue by antikilahdjs** [argoproj/argo-cd#13237]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

Hello everybody, I am trying configure the ArgoCD in the v2.5.7 version and my keycloak is 16. I am trying follow many guides and the documentation https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/ but not success.
I have many OIDC configured in my environment and all works good, I am not use the keycloak with TLS or SSL because it is internal and at this moment is not necessary. Apparently Argo forcing to use HTTPS. I am using Ingress just for Argo but I guess it not cause issues about that.

**To Reproduce**
1 - Install the Helm using the values:
  oidc.config:
      ----
      name: Keycloak
      issuer: https://<hostname>/auth/realms/xxxx
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes: ["openid","profile","email","groups"]
   
2 - My Ingress

kind: Ingress
      apiVersion: networking.k8s.io/v1
      metadata:
        name: argocd-server
        namespace: argocd-gitops
        labels:
          app.kubernetes.io/component: server
          app.kubernetes.io/instance: argocd-server
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: argocd-server
          app.kubernetes.io/part-of: argocd
          helm.sh/chart: argo-cd-5.16.9
        annotations:
          meta.helm.sh/release-name: argocd-server
          meta.helm.sh/release-namespace: argocd-lab
          nginx.ingress.kubernetes.io/backend-protocol: http
          nginx.ingress.kubernetes.io/force-ssl-redirect: 'false'
          nginx.ingress.kubernetes.io/server-snippet: >-
            gzip on;gzip_vary on;gzip_types  application/json  application/javascript
            text/css  application/vnd.api+json;
      spec:
        ingressClassName: nginx
        rules:
          - host: deploy.xxxxx.com
            http:
              paths:
                - path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: argocd-server
                      port:
                        number: 80
**Expected behavior**

The error related with the screenshoot

**Screenshots**

![image](https://user-images.githubusercontent.com/33559260/232089461-39a02793-391f-4961-a1f8-7c5196a4f906.png)

**Version**

```shell
quay.io/argoproj/argocd:v2.5.7
```

**Logs**

Not exist a log with error 

   time="2023-04-14T14:33:40Z" level=info msg="ArgoCD API Server is starting" built="2023-01-18T02:23:39Z" 
   commit=e0ee3458d0921ad636c5977d96873d18590ecf1a namespace=argocd-labport=8080 version=v2.5.7+e0ee345
  
   time="2023-04-14T14:33:40Z" level=info msg="Starting configmap/secret informers"
  
   time="2023-04-14T14:33:40Z" level=info msg="Configmap/secret informer synced"
  
   time="2023-04-14T14:33:40Z" level=info msg="Creating client app (argocd)"
  
   time="2023-04-14T14:33:40Z" level=info msg="argocd v2.5.7+e0ee345 serving on port 8080 (url: https://xxxxx, tls: false, 
   namespace: argocd-lab, sso: true)"
  
   time="2023-04-14T14:33:40Z" level=info msg="Enabled application namespace patterns: argocd-lab"
  
   time="2023-04-14T14:33:40Z" level=info msg="0xc000f08180 subscribed to settings updates"
  
   time="2023-04-14T14:33:40Z" level=info msg="Starting rbac config informer"
  
   time="2023-04-14T14:33:40Z" level=info msg="RBAC ConfigMap 'argocd-rbac-cm' added"
  
   time="2023-04-14T14:43:40Z" level=info msg="Alloc=21264 TotalAlloc=135870 Sys=86420 NumGC=11 Goroutines=94"
  
   time="2023-04-14T14:53:40Z" level=info msg="Alloc=28635 TotalAlloc=209728 Sys=87188 NumGC=16 Goroutines=94"
  
   time="2023-04-14T14:53:51Z" level=info msg="received unary call /version.VersionService/Version" grpc.method=Version 
   grpc.request.content= grpc.service=version.VersionService grpc.start_time="2023-04-14T14:53:51Z" span.kind=server 
   system=grpc
  
   time="2023-04-14T14:53:51Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Version 
   grpc.service=version.VersionService grpc.start_time="2023-04-14T14:53:51Z" grpc.time_ms=5.519 span.kind=server 
   system=grpc
  
   time="2023-04-14T15:02:42Z" level=info msg="Initializing OIDC provider (issuer: http://xxxxx/auth/realms/xxxx)"
  
   time="2023-04-14T15:03:40Z" level=info msg="Alloc=22995 TotalAlloc=293019 Sys=88212 NumGC=22 Goroutines=99"
  
   time="2023-04-14T15:13:40Z" level=info msg="Alloc=20145 TotalAlloc=370125 Sys=88980 NumGC=27 Goroutines=96"
  
   time="2023-04-14T15:23:40Z" level=info msg="Alloc=21861 TotalAlloc=446209 Sys=89492 NumGC=32 Goroutines=96"
  
   time="2023-04-14T15:33:40Z" level=info msg="Alloc=23090 TotalAlloc=522711 Sys=90004 NumGC=37 Goroutines=96"
  
   time="2023-04-14T15:43:40Z" level=info msg="Alloc=19470 TotalAlloc=600819 Sys=90004 NumGC=42 Goroutines=96"
  
```

**Comment by Nello-Angelo** [comment]
i have the same problem
