### ISSUE TITLE
Best effort controller watch on resources (instead of resource inclusions/exclusions)

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#13239]
# Summary

The resource inclusions/exclusions feature in Argo CD allows the controller to opt-out of managing resources that a user decides Argo CD should not manage. A common use case for this feature is to disallow Argo CD to read/write Secrets because Secrets are managed by another mechanism (e.g. ExternalSecret/SealedSecret). A second use cases is to configure Argo CD ignore high churn/high volume resources or very populous resources like crossplane ProviderConfigUsage in order to improve performance or reduce clutter in the UI:

```yaml
- apiGroups:
  - '*.crossplane.io'
  kinds:
  - ProviderConfigUsage
```

As an alternative to using resource inclusions/exclusions, the controller can be improved to perform **_best effort_** list/watch of resources after initial API discovery. For each resource group/kind that it is denied access to, it simply will treat it like a resource exclusion

# Motivation

Resource inclusions/exclusion is useful feature, but is a friction point for administrators because:
1. the configurations need to be coordinated with the actual RBAC given to the controller (e.g. the configuration needs to be duplicated)
2. it's awkward to configure different clusters with different inclusions/exclusions
3. it's not a canonical way to manage RBAC. In fact it's not truly an RBAC feature since it's not actually removing any privilege to the controller.

# Proposal

The implementation for this might be quite simple. During controller startup, after API discovery, attempt the list/watch on a group/kind as usual. But if we encounter that our access forbidden, simply accept that and move on. Currently the controller will not proceed until it can start its watch against all group/kinds according to inclusions/exclusions.

NOTE that this feature would not deprecate resource inclusions/exclusions, because sometimes it's simply easier or acceptable to exclude resources but still use the built-in ClusterRole.

**Comment by gdsoumya** [comment]
Have added a proposal for the same proposal raised https://github.com/argoproj/argo-cd/pull/13479

**Comment by jessesuen** [comment]
Completed
