### ISSUE TITLE
v2.7 Logs UI unusable under certain conditions

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#13266]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

A user is trying v2.7.0-rc1 and their logs UI looks like the following:

<img width="1937" alt="image" src="https://user-images.githubusercontent.com/12677113/232579462-41385a17-781c-4ee9-b7a1-80c22cf588a2.png">

**To Reproduce**

It's 100% reproducible for this user, however I was unable to reproduce it with a dummy example app.

The user was running a modified version of this image: `paulbouwer/hello-kubernetes:1.10`

Tested on both chrome and safari.

**Version**

v2.7.0-rc1

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
Polled a bunch of other users and and it does appear to affect many of them though to a lesser degree (only two scrollbars).

![image](https://user-images.githubusercontent.com/12677113/232855610-519645ca-3ef8-4b53-b0b7-814484fd91a7.png)

It appears to be affected when the OS or browser decides to display horizontal scrollbars and can be reproduced easily by enabling `Always` option. That said, the bug is even seen on Brave browser on Linux.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/12677113/232854847-f0a20049-d2bd-4cbf-97c6-fefdeb74124d.png">

However, it does even affect users who set this option to `Automatically`. 

@alexec did you encounter this during the log view revamp?

**Comment by alexec** [comment]
Question - are they using Safari or Chrome?

**Comment by jessesuen** [comment]
One more reproduction note. It seems I can briefly reproduce it by:
1. making the window smaller
2. scrolling to the bottom of the frame

At that point, double scrollbars will show (but then disappear for me/persist for others)

**Comment by alexec** [comment]
The problem is that some logs lines are wider than 4096px. I will fix.
