### ISSUE TITLE
Rollback UI is not showing correct ksonnet parameters in preview

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1326]
The UI is presenting some incorrect information when previewing what ksonnet parameters were used in the rollback. Currently it is showing the values of `ks param list` instead of `ks param list --env ENVNAME`. This will cause users to be confused about what is going to be synced when they roll back.

**Comment by alexmt** [comment]
@alexec , sorry did not notice you've assigned it. PRs are ready: https://github.com/argoproj/argo-cd/pull/1464, https://github.com/argoproj/argo-cd-ui/pull/111
