### ISSUE TITLE
Unable to delete resource via API calls

### ISSUE THREAD

**Issue by lboutin-mwm** [argoproj/argo-cd#13272]
**Bug description**

When trying to delete a Deployment using any API call, I get the error "Deployment  audio-analysis-staging not found as part of application audio-analysis-staging"

It's worth noting that there is no such error when using a CLI call

```shell
argocd app delete-resource audio-analysis-staging --kind Deployment --auth-token $AUTH_TOKEN
INFO[0000] Resource 'audio-analysis-staging' deleted
```

**Bug reproduction**

Any API call will do, either via POSTMAN or curl, other resources don't work either, even when explicitly using data returned by a list managed resources call

```shell
curl --location --request DELETE 'https://url/api/v1/applications/audio-analysis-staging/resource?resourceName=audio-analysis-staging&version=139697372&kind=Deployment' \
--header 'Authorization: Bearer token'
```

**Expected behavior**

Deletion of the resource

**Screenshots**

POSTMAN screenshot

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/131047426/232602712-b30edf2a-b225-4ecf-a100-dbcc4b395e02.png">

**Version**

```shell
argocd: v2.6.7+5bcd846.dirty
  BuildDate: 2023-03-23T17:30:29Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.6.7+5bcd846
```

**Comment by lboutin-mwm** [comment]
After some trial and error I've been able to make it work, it's probably not a bug more so than a lack of doc on the API so if anyone's having a similar problem, here's the solution:
 

When using the delete-resource cli command, it looks like only the name and kind of the resource are required to find the resource so `argocd app delete-resource $NAME --kind $KIND` will be sufficient

When using the DeleteResource API, while only `resourceName`, `kind` and `version` are _required_ to get an answer, it looks like adding the `namespace` (and `group` when applicable) query parameters is necessary to properly identify the resource


You can find the value of the `version` (and optionally `group`) to use for each resource in the `apiVersion` field of the resource

- `apiVersion: apps/v1` -> group=apps&version=v1
- `apiVersion: autoscaling/v2beta2` -> group=autoscaling&version=v2beta2
- `apiVersion: v1` -> version=v1 (`group` query parameter is not required)

**Comment by PGPAWAN** [comment]
Thank you for your response.. This really helped me.

`curl -X DELETE -H "Authorization: Bearer $ARGOCD_AUTH_TOKEN"  "$ARGOCD_SERVER/api/v1/applications/<applicationName>/resource?resourceName=<resourceName>&group=<groupname>&kind=<kind>&namespace=<namespace>&name=<resourceName>"`

**Comment by yiscasar** [comment]
I tried to use it as describe in the above comment:
`curl -X DELETE -H "Authorization: Bearer $access_token" "https://amyargo.com/api/v1/applications/my-app/resource?kind=ConfigMap&resourceName=my-cm&namespace=my-ns&version=v1"`
and got:
`Invalid content type`

**Comment by ghiagio** [comment]
> I tried to use it as describe in the above comment: `curl -X DELETE -H "Authorization: Bearer $access_token" "https://amyargo.com/api/v1/applications/my-app/resource?kind=ConfigMap&resourceName=my-cm&namespace=my-ns&version=v1"` and got: `Invalid content type`

I was in the same situation (HTTP error 415). I added "Content-Type: application/json" to my headers and it worked
