### ISSUE TITLE
Cannot set a --header flag whose value contains a :

### ISSUE THREAD

**Issue by bh-tt** [argoproj/argo-cd#13274]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I wish to set an Origin header for argocd to allow state-changing requests to pass our CSRF origin filter. I have tried `argocd --header 'Origin: https://argocd.example.com' --grpc-web app sync some-app`, but argocd splits the headers on `:`. The result is `Origin: https` header instead of the entire header.

**To Reproduce**
Try to send any request to argocd with a header value containing `:`. 

**Expected behavior**
The CLI `--header` option should allow for any header value to be set. A separator value like `:` should at least have an escape option so it is not interpreted.

Aside from that, the `--header` option appears to be ignored unless the `--grpc-web` option is also added.  https://github.com/argoproj/argo-cd/issues/4918 has the same issue, but I think the related MR only fixes the problem in the `login` subcommand.

**Version**

```shell
[bh@tlrd1 231 ~]$ argocd version
argocd: v2.5.2+148d8da
  BuildDate: 2022-11-07T17:06:04Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.7
  Compiler: gc
  Platform: linux/amd64
```
Server version is not really relevant here, as this is a bug in the client.
**Logs**

```
Paste any relevant application logs here.
```

**Comment by Bogay** [comment]
The problem is when `--grpc-web` enabled, the code which parse header strings assume that headers do not contain `:`.
https://github.com/argoproj/argo-cd/blob/7825821c1cda17b809e44b66cc5980fecf28af4f/pkg/apiclient/grpcproxy.go#L128-L133

#9375 had fixed that, let `argocd` accept headers contain `;`. But gRPC proxy did not use `parseHeader`, it's still broken. I think use `parseHeader` can fix that,

**Comment by bh-tt** [comment]
I have no experience with gRPC so I don't think I can make a pull request for that client. Could someone else take a look at this probably 10-minute fix?
