### ISSUE TITLE
Cannot create app from local file

### ISSUE THREAD

**Issue by muenchdo** [argoproj/argo-cd#1327]
I'm trying to create an app from a local file:
```
argocd app create team --file manifest.yaml --dest-server https://kubernetes.default.svc --dest-namespace default
```
This gives the following error:
```
FATA[0000] rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: spec.source.repoURL and spec.source.path are required
```
According to the usage output, if `file` is set, `repo` and `path` should be ignored.

**Version Info:**
```
argocd: v0.12.0+cd4bb25
  BuildDate: 2019-03-22T19:59:10Z
  GitCommit: cd4bb2553d4d3b9a8ba808adbd65c15ce11d9cfa
  GitTreeState: clean
  GoVersion: go1.11.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v0.12.0+cd4bb25
  BuildDate: 2019-03-22T19:58:47Z
  GitCommit: cd4bb2553d4d3b9a8ba808adbd65c15ce11d9cfa
  GitTreeState: clean
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Comment by alexmt** [comment]
Looks like this behavior is reproducible only if repoURL and path are missing in `manifest.yaml` . In this case error is valid. The `--repo` and `--path` flags are ignored and values are expected to be in `manifest.yaml` .

**Comment by mvpmvh** [comment]
Am I understanding this issue correctly? Once this bug is fixed, we'll be able to have argocd run a gitops workflow locally using a local directory of k8s manifests vs having to pull them from a remote git repo?

**Comment by muenchdo** [comment]
@alexmt I'm not quite sure what you mean by that. Do I need to add `repoURL` and `path` to the Kubernetes manifests of my application, e.g. Deployment? Or should I pass an ArgoCD application resource manifest here? If so, I just seemed to have misunderstood the usage of the CLI :)

**Comment by alexmt** [comment]
@muenchdo `manifest.yaml` is supposed to have application manifest (similar to https://github.com/argoproj/argo-cd/blob/master/docs/application.yaml ). If `repoURL` and `path` fields are missing in manifest then app creation should fail. 

@mvpmvh , we are planning to support the local directory. Please check this issue: https://github.com/argoproj/argo-cd/issues/839

**Comment by muenchdo** [comment]
Alright, then I will close this issue. Thanks for your support!
