### ISSUE TITLE
argo cli should be able to show all apps of an appset

### ISSUE THREAD

**Issue by kosta** [argoproj/argo-cd#13309]
# Summary

argo cli should be able to show all apps of an appset

# Motivation

After changing an appset, I want to use the argocd cli to verify all apps of that appset are synced.

Currently, you can do this using (replacing `appset-name` with the name of your appset):

```
argocd app list -o json | jq --raw-output '.[] | select(.metadata.ownerReferences[0].name=="appset-name") | .metadata.name'
```

A simpler way would be nice.

# Proposal

Either:
* `argocd appset get <name>` should show all Applications owned by it
* `argocd app list` should accept a flag `--appset <appset-name>` to filter the output

**Comment by ericblackburn** [comment]
> An easier way would be to add the label `argocd.argoproj.io/appset-instance=app-set-name` on all apps. Then we could easily filter by running
> 
> ```
>   argocd app list -l argocd.argoproj.io/appset-instance=app-set-name
> ```

This is not a good idea. K8s resource object names can often be more than 63 characters.  This broken the ability to use Argo 2.8 and  https://github.com/argoproj/argo-cd/issues/15282 was opened as a request to fix this blocking regression.

**Comment by ericblackburn** [comment]
AppSets keep an array of the applications they manage in status.applicationStatus on the k8s object. Labels should be unnecessary to make and argo cli call for this.
