### ISSUE TITLE
'OTLP Partial Success: empty message' spam

### ISSUE THREAD

**Issue by burningalchemist** [argoproj/argo-cd#13341]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Latest versions (v2.6.7, v2.7.x) of ArgoCD are still using `v1.11.1` version of opentelemetry libs, which contains a bug causing lots of useless messages in the log:

```
2023/04/25 07:19:32 OTLP partial success: empty message (0 spans rejected)
```

The main issue is the amount of these log messages affecting the logging backends. It was [fixed](https://github.com/open-telemetry/opentelemetry-go/pull/3438) and included in the following patch [release](https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.11.2) `v1.11.2`. As a mitigation, we exclude this message on the logging solution side with a filter.

**To Reproduce**

1. Configure `--otlp-address` to enable sending traces to the available tracing backend;
2. Check logs. 

**Expected behavior**

As per this issue (https://github.com/open-telemetry/opentelemetry-go/issues/3432) the log message is not needed.

The suggestion is to bump up the dependency from `v1.11.1` to `v1.11.2` to avoid any OTLP surprises.

**Version**

```shell
{
    "Version": "v2.6.1+3f143c9",
    "BuildDate": "2023-02-08T18:51:05Z",
    "GitCommit": "3f143c9307f99a61bf7049a2b1c7194699a7c21b",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

P.S. There's a closed [dependabot PR](https://github.com/argoproj/argo-cd/pull/11790) already, but I'm happy to provide a PR as well if needed. 👍

Thanks! :)

**Comment by HafidzEvermos** [comment]
we don't have any description here as to why it's marked as completed?

**Comment by burningalchemist** [comment]
Hey @HafidzEvermos, I remember the library was eventually updated, so it stopped being a problem.
