### ISSUE TITLE
Missing `argocd_redis_request_total` metric

### ISSUE THREAD

**Issue by nabadger** [argoproj/argo-cd#13415]
**Describe the bug**

The metric `argocd_redis_request_total` is not appearing post-upgrade of argocd. 

I've migrated from `2.4.x` to `2.7.0`.

I can see that the metric still exists in the code still, but I no longer see this metric being output.

This is utilizing the official helm chart (`v5.30.1`) which is installing redis locally.

I have verified that the argocd components are talking to the redis instance using `MONITOR` ( https://redis.io/commands/monitor/ ) - i.e. I see output here when I visit the argocd UI.

I have also port-forwarded to the controller-metric svc to confirm that other metrics are available at `/metrics`  (they are, but there's no `redis_*` ones appearing.

**To Reproduce**

Check if the `argocd_redis_request_total` metric increases when communicating with Redis

**Expected behavior**

The `argocd_redis_request_total` metric should increase

**Comment by nabadger** [comment]
I should add, we use a custom plugin using the new sidecar approach, so wondering if this would have an impact?

**Comment by ericblackburn** [comment]
We are seeing the same thing, on 2.7.3

Missing that we know of

- argocd_application_controller.argocd_redis_request_duration.sum
- argocd_application_controller.argocd_redis_request_total
- argocd_repo_server.argocd_redis_request_duration_seconds.sum

Basically, the application controller and repo server stopped reporting redis metrics.

**Comment by joshuabezaleel** [comment]
just updated to 2.7.9, encountering this as well. got no data at all for all of the dashboard under the redis section from the argo grafana community dashboard. is there any workaround that we can use for the metrics to appear so as not to wait for the upstream change and next release cycle? 🤔 
<img width="1431" alt="Screen Shot 2023-07-31 at 14 19 39" src="https://github.com/argoproj/argo-cd/assets/7043511/876d1a87-f1b9-4b37-a8f6-72a7c49dd281">

**Comment by emirot** [comment]
I m encountering the same issue any solution found ?
