### ISSUE TITLE
select container to view log UI it's not update.

### ISSUE THREAD

**Issue by sureenart** [argoproj/argo-cd#13410]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

After upgrade argocd to version 2.7.0 when select container to view log UI it's not update correct container log. 

![image](https://user-images.githubusercontent.com/125337032/235585192-5d387e26-6b73-4c7f-9aa9-31ea9dd1fdb5.png)

**To Reproduce**

**Expected behavior**

update correct container log. 

**Version**

```shell

    "Version": "v2.7.0+c592219.dirty",
    "BuildDate": "2023-05-02T00:14:18Z",
    "GitCommit": "c592219140e5f48b6849f3f9a8f7aed6047d54fa",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
@alexec have time to look?

**Comment by rouke-broersma** [comment]
Can confirm, this doesn't work for us on 2.7 either.
