### ISSUE TITLE
argocd-application-controller: can not retrieve list of objects using index : Index with name namespace does not exist

### ISSUE THREAD

**Issue by papanito** [argoproj/argo-cd#1345]
I am using lastest `argo-cd` 12.0 and have seen the following error in the logs of `argocd-application-controller`

```go
time="2019-04-01T09:18:39Z" level=info msg="Starting configmap/secret informers"
time="2019-04-01T09:18:39Z" level=info msg="Configmap/secret informer synced"
time="2019-04-01T09:18:39Z" level=info msg="Application Controller (version: v0.12.0+ae41425) starting (namespace: argocd)"
time="2019-04-01T09:18:39Z" level=info msg="0xc000592540 subscribed to settings updates"
time="2019-04-01T09:18:39Z" level=info msg="Start watch clusters"
W0401 09:18:39.421182       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0401 09:28:21.267686       1 reflector.go:270] github.com/argoproj/argo-cd/util/settings/settings.go:260: watch of *v1.ConfigMap ended with: too old resource version: 46879845 (46880801)
time="2019-04-01T09:28:39Z" level=info msg="Alloc=3853 TotalAlloc=12428 Sys=70590 NumGC=9 Goroutines=79"
W0401 09:33:51.275817       1 reflector.go:270] github.com/argoproj/argo-cd/util/settings/settings.go:260: watch of *v1.ConfigMap ended with: too old resource version: 46881967 (46882100)
time="2019-04-01T09:38:39Z" level=info msg="Alloc=3731 TotalAlloc=12797 Sys=70590 NumGC=14 Goroutines=79"
W0401 09:39:56.284179       1 reflector.go:270] github.com/argoproj/argo-cd/util/settings/settings.go:260: watch of *v1.ConfigMap ended with: too old resource version: 46883160 (46883459)
W0401 09:46:21.293100       1 reflector.go:270] github.com/argoproj/argo-cd/util/settings/settings.go:260: watch of *v1.ConfigMap ended with: too old resource version: 46884444 (46884702)
time="2019-04-01T09:48:39Z" level=info msg="Alloc=3755 TotalAlloc=13264 Sys=70590 NumGC=19 Goroutines=79"
W0401 09:53:10.301704       1 reflector.go:270] github.com/argoproj/argo-cd/util/settings/settings.go:260: watch of *v1.ConfigMap ended with: too old resource version: 46885664 (46886015)
time="2019-04-01T09:58:39Z" level=info msg="Alloc=3759 TotalAlloc=13653 Sys=70590 NumGC=24 Goroutines=79"
time="2019-04-01T09:59:21Z" level=info msg="Completed watch clusters"
W0401 10:01:56.310717       1 reflector.go:270] github.com/argoproj/argo-cd/util/settings/settings.go:260: watch of *v1.ConfigMap ended with: too old resource version: 46886951 (46887685)
W0401 10:07:44.334623       1 reflector.go:270] github.com/argoproj/argo-cd/util/settings/settings.go:260: watch of *v1.ConfigMap ended with: too old resource version: 46888622 (46888786)
time="2019-04-01T10:08:39Z" level=info msg="Alloc=3844 TotalAlloc=14088 Sys=70590 NumGC=29 Goroutines=76"
W0401 10:13:08.342333       1 reflector.go:270] github.com/argoproj/argo-cd/util/settings/settings.go:260: watch of *v1.ConfigMap ended with: too old resource version: 46889729 (46889804)
time="2019-04-01T10:18:39Z" level=info msg="Alloc=3744 TotalAlloc=14450 Sys=70590 NumGC=34 Goroutines=76"
W0401 10:19:39.346571       1 reflector.go:270] github.com/argoproj/argo-cd/util/settings/settings.go:260: watch of *v1.ConfigMap ended with: too old resource version: 46890759 (46891388)
W0401 10:27:19.353286       1 reflector.go:270] github.com/argoproj/argo-cd/util/settings/settings.go:260: watch of *v1.ConfigMap ended with: too old resource version: 46892401 (46893063)
```

It's not really clear what are the consequences of this error.

I have two `bitbucket` repos configure:
- https://bitbucket.intra/scm/test/helm.git
- https://bitbucket.intra/scm/test/kube.git

I am using default cluster... 
- https://kubernetes.default.svc

... and `default` project without modifications

I don't have any application setup yet, due to #1344

**Comment by jessesuen** [comment]
I think this error may be benign.

**Comment by alexmt** [comment]
I'm pretty sure this error is just a warning from the watch library, similar to ` watch of <resourceNAme> ended with: too old resource version`. Closing it, please feel free to reopen if you see any issue related to this warning message

**Comment by jerryhu1234** [comment]
I am using lastest v1.3.0-rc2 and have seen the following error in the logs of argocd-repo-server
//////////////////////////////
W1025 09:05:38.592624       1 listers.go:77] can not retrieve list of objects using index : Index with name namespace does not exist
W1025 09:05:43.100006       1 listers.go:77] can not retrieve list of objects using index : Index with name namespace does not exist
time="2019-10-25T09:05:43Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = Application.argoproj.io \"helloworld\" is invalid: []: Invalid value: map[string]interface {}{\"apiVersion\":\"argoproj.io/v1alpha1\", \"kind\":\"Application\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2019-10-25T09:05:43Z\", \"generation\":1, \"name\":\"helloworld\", \"namespace\":\"argocd\", \"uid\":\"9f998f38-f706-11e9-b5e2-4a3e7fa309d9\"}, \"spec\":map[string]interface {}{\"destination\":map[string]interface {}{\"namespace\":\"argocd\", \"server\":\"https://kubernetes.default.svc\"}, \"project\":\"production\", \"source\":map[string]interface {}{\"kustomize\":map[string]interface {}{\"namePrefix\":\"prod-\"}, \"path\":\"v2/overlays/prod/domestic/servicea/\", \"repoURL\":\"git@github.com:jerryhu1234/kustomize.git\", \"targetRevision\":\"HEAD\"}}, \"status\":map[string]interface {}{\"health\":map[string]interface {}{}, \"summary\":map[string]interface {}{}, \"sync\":map[string]interface {}{\"comparedTo\":map[string]interface {}{\"destination\":map[string]interface {}{}, \"source\":map[string]interface {}{\"repoURL\":\"\"}}, \"status\":\"\"}}}: validation failure list:\nstatus.sync.comparedTo.source.path in body is required" grpc.code=InvalidArgument grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2019-10-25T09:05:34Z" grpc.time_ms=8483.246 span.kind=server system=grpc
time="2019-10-25T09:06:03Z" level=info msg="k8s application watch event channel closed"
time="2019-10-25T09:06:03Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=Watch grpc.service=application.ApplicationService grpc.start_time="2019-10-25T09:04:11Z" grpc.time_ms=111977.64 span.kind=server system=grpc

**Comment by alexec** [comment]
See https://github.com/coreos/prometheus-operator/issues/1694
