### ISSUE TITLE
Enable gzip compression in Redis by default

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#13458]
# Summary

[Compressing stuff in Redis](https://github.com/argoproj/argo-cd/blob/8c5af34eaf3918fbe14ec2ea768d9e82835b6e3a/docs/operator-manual/argocd-cmd-params-cm.yaml#L18) saves a lot of network traffic and memory. The feature has been tested in large environments for a while. I think it's time to make it default.

# Motivation

Saves money, serves our users better.

# Proposal

Flip the default to `gzip` instead of `none`.

**Comment by rumstead** [comment]
<img width="1887" alt="Screenshot 2023-09-01 at 3 18 20 PM" src="https://github.com/argoproj/argo-cd/assets/37445536/dd4270bf-9563-4b46-af73-594a7dbdfaa7">

Love this change
