### ISSUE TITLE
Support filtering on configured/unchanged in sync status

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#13457]
# Summary

What change you think needs making.

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/2119212/235197753-c56aca74-e7cc-4191-8d34-4f7dbe28fba1.png">

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/2119212/235197692-7f4c530b-9680-4dd7-84dc-429fda003c5b.png">

# Motivation

There are dozens of items in this view, and most of them are `unchanged`

# Proposal

`configured` and `unchanged` should be filterable values -- whether that's using an existing column or being promoted to a new column is an implementation detail.

**Comment by andrii-korotkov-verkada** [comment]
Sounds good. I think we need to be a bit careful when using message contents, e.g. if some resource has "configured" in its name, but seems like a solvable problem.

**Comment by aali309** [comment]
I will look into this.
