### ISSUE TITLE
One repo for all internal tools but keeping namespaces separated is possible?

### ISSUE THREAD

**Issue by mfabricanti** [argoproj/argo-cd#13455]
Hey guys,

I'm trying to solve an issue we have here to deploy some internal tools (not the public apps), to multiple clusters/namespaces faster.

I don't know if this is possible with Argo, but the behavior I'm trying to achieve is this:

**Whatever I commit inside a root folder (let's call it: namespace-a root folder), it uses the folder name as the namespace in the manifests.**

Example:
-----
- Root Folder -->> Here I will create an Argo App pointed to the root ("/") folder of the git repository (linked to a specific cluster)
    - Folder: namespace-a
        - Subfolder: tool-a
            - File: deploy.yaml --> apply to the cluster as "kubectl apply -f deploy.yaml -n namespace-a"
    - Folder: namespace-b
        - Subfolder: tool-a
            - File: deploy.yaml --> apply to the cluster as "kubectl apply -f deploy.yaml -n namespace-b"
 (but the file is the same as above)
-----

Do you think this behavior is achievable in any way?

Thanks in advance

**Comment by torfjor** [comment]
You should be able to template this with an `ApplicationSet` where `spec.destination.namespace` becomes `{{path[0]}}` (or `{{first .path}}` if you're using the Go template syntax).
