### ISSUE TITLE
Switching from RC to stable branch breaks application controller deployment

### ISSUE THREAD

**Issue by daanemanz** [argoproj/argo-cd#1346]
I'm using Kustomize to deploy Argo CD in our environment, and recently switched from using the rc6 branch to the stable branch in our `kustomization.yaml`:

Before
```yaml
bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v0.12.0-rc6
```

After
```yaml
bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=release-0.12
```

When I update my deployment, I get an error:
```
The Deployment "argocd-application-controller" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

This seems related to https://github.com/argoproj/argo-cd/pull/1315, which is the only PR touching the deployment strategy between the last RC tag and the stable release.

**Comment by alexmt** [comment]
Hello @daanemanz . This is expected. The 'Recreate' type was added to controller deployment after RC6. Please use instructions from release notes to upgrade: from https://github.com/argoproj/argo-cd/blob/master/CHANGELOG.md#label-selector-changes-dex-server-rename

**Comment by daanemanz** [comment]
Closing issue; resolved using the instructions from the release notes.
