### ISSUE TITLE
argocd-dex-server crashloopbackoff

### ISSUE THREAD

**Issue by GarinKartes** [argoproj/argo-cd#13471]
**Describe the bug**

When deploying 2.7.0 and 2.7.1 upgrading from 2.6.7 the argocd-dex-server enters a crashloopbackoff state

**To Reproduce**

deploy argocd 2.7.0 or 2.7.1 using helm

**Expected behavior**

the new argocd-dex-server pod is able to start and serve traffic

**Screenshots**

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/18622408/236501556-165905c2-9d49-40ed-a370-d1ddd64de754.png">

**Version**
Upgrading from 2.6.7 yo 2.7.0 or 2.7.1

**Logs**
Only log I can find is from the COPYUTIL container
```
cp: target '/shared/argocd-dex' is not a directory
```

**Comment by WoodProgrammer** [comment]
Is there any update around there ?

**Comment by WoodProgrammer** [comment]
I upgraded chart version to this one : version: 5.31.0, it worth to try. The issue on my local just fixed .

**Comment by brsolomon-deloitte** [comment]
Seeing this error today on ArgoCD chart 5.32.1, app version v2.7.1, the `copyutil` initContainer logs for `deployment/argocd-dex-server`, which leads to a CrashBackOffLoop.

**Comment by itsSaad** [comment]
I was also having the problem. But in my case I was installing the latest version of helm chart and then unknowingly downgrading at a later point.

**Comment by chrisduong** [comment]
Hi @GarinKartes, I had faced the same problem when upgrading the chart from 5.16.x to 5.34.1.

For some unknown reason, ArgoCD create the wrong deployment manifest for Dex. It is supposed to have `args` flag only

```
initContainers:
        - args:
            - /bin/cp
            - '-n'
            - /usr/local/bin/argocd
            - /shared/argocd-dex
```

But it contained the `commands` flag also, which caused the problem.

Delete the Dex deployment, and resync again will fix the problem.

**Comment by kenlasko** [comment]
I have the exact same issue as the previous posters with a fresh installation of the 5.34.5 Helm chart. I have an existing 6 month old deployment that is working fine on 5.34.5

Unlike @chrisduong, I was unable to delete the commands: from my manifest. I ended up downgrading to 5.28.0 (picked somewhat at random), which ended up working fine.  I then upgraded back to 5.34.5 and all appears good.

**Comment by exsplashit** [comment]
Had the exact same case upgrading from 5.9.1 to 5.33.1, @chrisduong 's solution worked for me. Thank you!

**Comment by martivo** [comment]
Experiencing similar issue with argo-cd chart 5.46.2. I am making a clean install. Have reproduced it several times now. First time dex container remains in crashloopbackoff until I delete the dex-server pod. Seems to be initContainer issue. It also has the command block in the dex-server deployment.
```
      initContainers:
      - command:
        - /bin/cp
        - -n
        - /usr/local/bin/argocd
        - /shared/argocd-dex
```

**Comment by rouke-broersma** [comment]
> Experiencing similar issue with argo-cd chart 5.46.2. I am making a clean install. Have reproduced it several times now. First time dex container remains in crashloopbackoff until I delete the dex-server pod. Seems to be initContainer issue. It also has the command block in the dex-server deployment.
> 
> ```
>       initContainers:
>       - command:
>         - /bin/cp
>         - -n
>         - /usr/local/bin/argocd
>         - /shared/argocd-dex
> ```
> 
> The weird part is that it does not happen every time. Seems more likely when the cluster has just been created and the CRDs are also being installed.

5.34 and newer is supposed to have the command block instead of the args block. It was changed in the chart itself:

https://github.com/argoproj/argo-helm/commit/6593901daf722c10f9b089a078cd9a7f88c1c2a5

**Comment by jgwest** [comment]
Helm chart issue in argo-helm repo
