### ISSUE TITLE
patch-resource API

### ISSUE THREAD

**Issue by adparvum** [argoproj/argo-cd#13478]
I am trying to patch a resource that was deployed with the Kubernetes yaml only (ie no Helm, Jsonette, etc) via the rest API. When I submit a request see example below.

```
curl --location 'https://argocd.mydomain.example/api/v1/applications/asdf/resource?resourceName=guestbook-ui&kind=Deployment&appNamespace=test&patchType=application%2Fmerge-patch%2Bjson&version=app%2Fv1' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <REDACTED>' \
--data '"{ "spec": { "replicas": 0 }}"'
```

I get the following error:
```
{
    "error": "permission denied",
    "code": 7,
    "message": "permission denied"
}
```

Argocd version:  v2.6.7+5bcd846

I am able to patch the patch the resource via the cli with:
```
❯ argocd app patch-resource asdf --resource-name guestbook-ui --namespace test --kind Deployment --patch '{ "spec": { "replicas": 1 }}'                                                               
```

**Comment by headyj** [comment]
Same here @adparvum , did you find a workaround?

**Comment by crenshaw-dev** [comment]
Make sure you're specifying the correct values for `namespace` and `appNamespace`. 

`namespace` is where the resource you're trying to patch resides. 

`appNamespace` is where the Application resides. You can omit that parameter if the app is in the same namespace as the argocd controller.

**Comment by headyj** [comment]
OK I found the issue, but it wasn't related to namespace.  I was using UpdateSpec (http://localhost:8080/swagger-ui#operation/ApplicationService_UpdateSpec) but I should have use Patch (http://localhost:8080/swagger-ui#operation/ApplicationService_Patch)

That said I still don't understand why I was having permission denied with UpdateSpec

**Comment by crenshaw-dev** [comment]
I think you've encountered a different issue from @adparvum. They're trying to patch a resource while you're trying to patch an Application.

**Comment by aenshin-pp** [comment]
> That said I still don't understand why I was having permission denied with UpdateSpec

because it should be PUT instead of POST?
https://cd.apps.argoproj.io/swagger-ui#operation/ApplicationService_UpdateSpec
