### ISSUE TITLE
ApplicationSet cluster generator scoped to `AppProject`

### ISSUE THREAD

**Issue by JorTurFer** [argoproj/argo-cd#13525]
# Summary

I'd like to have an option in the generator to limit the result of the generator to the available clusters to the project. 

# Motivation

In our case, we have a platform team who manages the ArgoCD installation for different products. Currently, each business product is an `AppProject` with some different k8s clusters scoped to them. To improve the process of spinning up new clusters, we use `ApplicationSet` with cluster generator for all the workloads, and depending on the workload type, we use different selectors.

The problem with this use case is that we have to rely on the selectors given by development teams, and that can produce mistakes. For example, imagine that we have 2 `AppProject` with 2 clusters (scoped) per `AppProject`:
 
- P1-prod
	- labels: 
		- project: p1
		- env: prod
- P1-tst
	- labels: 
		- project: p1
		- env: tst
- P2-prod
	- labels: 
		- project: p2
		- env: prod
- P2-tst
	- labels: 
		- project: p2
		- env: tst

Currently, the `ApplicationSet` use something like:

```yaml
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          project: px
          env: xxx
```

The problem as I have said is that we need to rely on the labels all the time, and if one developer removes the `project` from the label selector, they will create an `Application` in a cluster where they don't have access (they have access limited to their own projects). As the `ApplicationSet` doesn't have any project limiting (and it makes sense too), we don't have any built-in mechanism to limit the clusters where the `ApplicationSet` will be applied, ignoring the RBAC. 

If the generator has an option to limit the results to available clusters for the `AppProject` (excluding scoped clusters from other `AppProject`), we will have an extra security check, improving the multi-tenancy with this safety net, because clusters inside the `AppProject` A can't be accessed by the `ApplicationSet` for the `AppProject` B.

This doesn't only solve misconfigurations, it also prevents from unexpected behaviors. As each team is owner of their clusters, they can use their own labels/annotations for each cluster. Although we have standardized some labels, other labels cloud be different between clusters, and they can match with other clusters unexpectedly. 

The last but not least, and `AppProject` is an entity inside ArgoCD which can have scoped resources, this option could delegate in the `AppProject` the selection of the resources, based on the already registered resources.

# Proposal

How do you think this should be implemented?

I see the powerful tool that is `ApplicationSet` for deploying things across anything, so I'd not attach the `ApplicationSet` to a specific `AppProject`, but I'd add an option in the cluster generator to limit the results based on the project.

I think that we can achieve it, adding an optional field to the spec:

```yaml
spec:
  generators:
  - clusters:
      project: demo-project #optional
      selector:
        ...
```

We could add the filter as part of [`GenerateParams`](https://github.com/argoproj/argo-cd/blob/master/applicationset/generators/cluster.go#LL64).

# Alternative Proposal

Other option (more complicated) is storing the (account) owner of the `ApplicationSet` and generate the clusters result based on the owner available clusters. The problem with this use case is I don't see how to do this for OIDC users.
For local users it's doable because the user is always there, but with OIDC users I haven't explored it... 

If you think that this second way is better, I can explore it deeper.

I think that this alternative option doesn't break the option of deploying something everywhere because an admin has access to all the places, but a user doesn't

**Comment by JorTurFer** [comment]
BTW, I'm willing to implement the feature if you think that is feasible

**Comment by blakepettersson** [comment]
Could an alternative option instead for the application controller to set a default project label when adding a cluster secret with `argocd cluster add ...` (or when creating a secret directly)? If we were to have a project label like `argocd.argoproj.io/app-project`, we could then use a standard label selector without any changes to the cluster generator API. What do you think about that?

**Comment by JorTurFer** [comment]
It could be a good solution because we could prevent misconfiguration during cluster registration. 
The other part can be done my our own side as part of our pipelines, ensuring that the label selector is always set 😄 

Do you want me to open a PR with that change?

**Comment by JorTurFer** [comment]
I think that [this proposal](https://github.com/argoproj/argo-cd/pull/13633) meets the requirements in a better way:
