### ISSUE TITLE
Cannot delete ArgoCDExtension (endless pending deletion state)

### ISSUE THREAD

**Issue by egobude** [argoproj/argo-cd#13522]
Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**

I have installed an ArgoCDExtension via the AppOfApps Pattern and tried to delete it. The Extension is now in OutOfSync and an endless pending deletion state. I'm not sure how to get rid of it. 

Live Manifest:

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"argoproj.io/v1alpha1","kind":"ArgoCDExtension","metadata":{"annotations":{},"finalizers":["extensions-finalizer.argocd.argoproj.io"],"labels":{"argocd.argoproj.io/instance":"apps"},"name":"argo-rollouts","namespace":"argo-cd"},"spec":{"sources":[{"web":{"url":"https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.0/extension.tar"}}]}}
  creationTimestamp: '2022-12-05T10:07:32Z'
  deletionGracePeriodSeconds: 0
  deletionTimestamp: '2023-03-24T11:49:00Z'
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
  generation: 2
  labels:
    argocd.argoproj.io/instance: apps
  name: argo-rollouts
  namespace: argo-cd
  resourceVersion: '1356621652'
  uid: 53ae4c7c-3fe0-4c1e-ae5e-98097a886cdf
spec:
  sources:
    - web:
        url: >-
          https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.0/extension.tar

```

**To Reproduce**

Not sure how to reproduce it. I just applied the manifest and try to delete it.

**Expected behavior**

Extension will be deleted when i remove the application from ArgoCD.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/397376/3b4ed7a1-0846-49dd-8991-76f437f9d641)

![image](https://github.com/argoproj/argo-cd/assets/397376/8be5acdd-b0a2-4438-a16c-e774717e5c87)

**Version**

```shell
argocd: v2.4.11+3d9e9f2.dirty
  BuildDate: 2022-08-22T12:47:26Z
  GitCommit: 3d9e9f2f95b7801b90377ecfc4073e5f0f07205b
  GitTreeState: dirty
  GoVersion: go1.19
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.7.1+5e54351.dirty
  BuildDate: 2023-05-02T16:35:40Z
  GitCommit: 5e543518dbdb5384fa61c938ce3e045b4c5be325
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1.
```

**Comment by egobude** [comment]
Any ideas how i can delete it manually so i have a clean application state again?

**Comment by peter-hst** [comment]
same here

**Comment by Shrooblord** [comment]
The finalizer
```
finalizers:
    - extensions-finalizer.argocd.argoproj.io
 ```
 indicates this resource should not be deleted yet; i.e. it's waiting for something else to be deleted before it's allowed to go away itself. Sometimes Kubernetes resources get stuck because nothing properly clears the finalizer. If you're sure all underlying resources have been deleted, you can get rid of the finalizer using `kubectl edit` or by patching the file directly:
 ```
kubectl patch ArgoCDExtension argo-rollouts  -p '{"metadata": {"finalizers": null}}' --type merge
kubectl delete ArgoCDExtension argo-rollouts
```

P.S.
I am currently experiencing never-ending finalizers for the `argo-rollouts` extension specifically, myself, too. May find out why later. I'll post again if I do.

**Comment by egobude** [comment]
@Shrooblord That worked, thank you :)
