### ISSUE TITLE
Unnecessary application refresh on update event cause high CPU usage on controller

### ISSUE THREAD

**Issue by agaudreault-jive** [argoproj/argo-cd#13534]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

TLDR; When a kubernetes resource watched by argo-cd is updated (whenever `resourceVersion` changes), argo-cd will receive an update event and trigger a refresh of the owner applications, if any. Resources that are updated frequently by controllers, such as ExternalSecret, will always have a new `resourceVersion` when information in the `status` field, such as `lastRefreshTime`, `lastEvaluation`, `reconciledAt` are updated. Although the resources are different, these fields should not cause a refresh in argo-cd. A refresh will cause a reconcile operation and even if the diffing evaluates to no changes, it consumes a lot of CPU.

**More details**

The cache from the [argoproj/gitops-engine](https://github.com/argoproj/gitops-engine) only store the `resourceVersion` and does not store the actual resource (except for crds). When a watch event is received, the cache will call OnResourceUpdated handler with the old and new object whenever the `resourceVersion` is updated, but the handler will not be able to do any relevant comparison because the old [Resource](https://github.com/argoproj/gitops-engine/blob/ed70eac8b7bd6b2f276502398fdbccccab5d189a/pkg/cache/resource.go#L14) object does not contain the previous version of the object.

When the argocd OnResourceUpdated handler [receives an event](https://github.com/argoproj/argo-cd/blob/4484ce855834d606b0778a252f69e82034e05592/controller/cache/cache.go#L463), it will simply [trigger/queue](https://github.com/argoproj/argo-cd/blob/4484ce855834d606b0778a252f69e82034e05592/controller/appcontroller.go#L366) a refresh for the application, eventually causing a [reconcile](https://github.com/argoproj/argo-cd/blob/4484ce855834d606b0778a252f69e82034e05592/controller/appcontroller.go#L1529).

This causes a lot of reconciliation for the same application and high CPU usage on both the controller and the repo-server.

**To Reproduce**

1. Update a resource deployed with argoCD by changing a value every 10 seconds (do not change a value that will cause an OutOfSync).
2. Observe the reconcile operation being performed every 10 seconds.

**Expected behavior**

ArgoCD cache should be configurable to ignore certain fields to be evaluated when there is a watch event received. Even if the resourceVersion has changed, the cache should compare the actual objects and if no relevant changes are detected, it should update the cache with the new version **without** triggering the OnResourceUpdated handler.

To save memory, a hash of the manifest with excluded fields could be stored in the `Resource` object.
To configure the cache, 
- argocd could have an additional list of [ResourceIgnoreDifferences](https://github.com/argoproj/argo-cd/blob/4484ce855834d606b0778a252f69e82034e05592/pkg/apis/application/v1alpha1/types.go#LL88C6-L88C31) to ignore fileds before computing the hash.
- Have Lua scripts similar to the [health customization](https://github.com/argoproj/argo-cd/tree/master/resource_customizations) that would receive the object manifest and return the manifest to hash.

**Other considered solution/mitigation**

- Use the new `argocd.argoproj.io/skip-reconcile: "true"` annotations
  - This will block all the reconcile for an application and does not fix the issue.
- Add a new annotation `argocd.argoproj.io/ignore-resource-update: "true"` on each resource that we do not want to trigger a reconcile for the application they belong to
  - This will require the users to add that annotations on multiple objects, probably with MutationWebhook, and adds a lot of burden on the ArgoCD users. It also ignores a resource completely instead of ignoring only certain fields
- Expose configuration for the list of [ignoredRefreshResources](https://github.com/argoproj/argo-cd/blob/4484ce855834d606b0778a252f69e82034e05592/controller/cache/cache.go#L301) 
  - This will ignore a resource completely instead of ignoring only certain fields.

**Screenshots**

Log analysis of which resource update are causing frequent applications refresh (test instance with no load)
![image](https://github.com/argoproj/argo-cd/assets/47184027/547b074e-508b-4eb0-b349-34364bcefbb2)

Total number of App reconciliations (60m) when `timeout.reconciliation: 3m` and expected value should be 20. (test instance with no load)
<img width="1919" alt="image" src="https://github.com/argoproj/argo-cd/assets/47184027/b453ffc7-c989-4a82-9ecb-1687d3c7b4f4">

Total number of reconciliations (15m) when `timeout.reconciliation: 5m` and expected value should be around 3. (instance with real load)
<img width="1913" alt="image" src="https://github.com/argoproj/argo-cd/assets/47184027/6039d853-3538-428d-ba74-bbb66592380b">

ArgoCD many application refresh and reconciliation, but no sync.
<img width="1857" alt="image" src="https://github.com/argoproj/argo-cd/assets/47184027/dead0f56-7e32-4f31-b994-5e5aa50086e8">

ArgoCD application refresh per controller
<img width="1919" alt="image" src="https://github.com/argoproj/argo-cd/assets/47184027/b48418cf-ef84-4da8-9cd9-2d0577b0a993">

ArgoCD constant high cpu usage on controller with the most reconcile load
<img width="1851" alt="image" src="https://github.com/argoproj/argo-cd/assets/47184027/8d4c6f45-34f0-49e5-9ccc-222cc8db15a1">

**Version**

```shell
argocd-server: v2.5.2+148d8da
  BuildDate: 2022-11-07T16:42:47Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**

```
Paste any relevant application logs here.
```

Related to #9014

**Comment by todaywasawesome** [comment]
@agaudreault-jive lets discuss in [sig-scalability](https://docs.google.com/document/d/1etHn3EDJN1KLvVKhLKFl634DMlJbfSFjtZoQopEt5Rw/edit).

**Comment by agaudreault-jive** [comment]
@csantanapr thanks for the suggestion to use pprof to find out which method use CPU. I did the following step to produce the flamegraph below
- `kubectl port-forward argocd-application-controller-0 8082`
- `curl "http://localhost:8082/debug/pprof/profile?seconds=900" > ./argocd-application-controller-0.Profile`
- Install https://graphviz.org/download/
- Run `go tool pprof -http=: ./argocd-application-controller-0.Profile`

We can see that the root method using the most CPU is `processAppRefreshQueueItem`, which is the processing method executed after an item has been enqueued caused by a watched resource. So I believe that adding a mechanism to avoid calling this method on unnecessary watched resource updates will improve argo-cd performance.

The method [`IterateHierarchy`](https://github.com/argoproj/gitops-engine/blob/b4dd8b8c3976d03f9928a393c2447830a3ef7449/pkg/cache/cluster.go#LL854C29-L854C29) could be improved as well if possible to improve the reconcile operation overall speed.

<img width="1753" alt="image" src="https://github.com/argoproj/argo-cd/assets/47184027/7e3c136f-eda4-43b5-b730-4ec08ba45bb2">
<img width="1843" alt="image" src="https://github.com/argoproj/argo-cd/assets/47184027/84f3aac4-4369-4010-a506-acd62b691754">
