### ISSUE TITLE
ConfigManagement Plugins as sidecars documentation page won't open

### ISSUE THREAD

**Issue by bolatov** [argoproj/argo-cd#13567]
# Summary

On the upgrading page, it is said that [argocd-cm plugins (CMPs) are deprecated](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.4-2.5/#argocd-cm-plugins-cmps-are-deprecated) and forwards to the page which suggests to [install the CMPs as sidecars](https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/). However, the page won't show anything. 

# Motivation

I'd like to upgrade my ArgoCD version from v2.4 --> v2.5 and following the documentation on this page https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.4-2.5. 

# Proposal

Please, fix the documentation page https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/

**Comment by shuker85** [comment]
Closing this as the page now says:
[This page has been moved to the operator manual](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/)
