### ISSUE TITLE
Reword `now refreshing` progress dialog

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#13566]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When you trigger a refresh applications task, the progress screen is confusing

**To Reproduce**

1. Go to /applications
2. Click `Refresh Apps`
3. Click `All`
4. Select `Hard`
5. Click `Refresh`

**Expected behavior**

* `Starting` should be `Refreshing applications

Either
* `Refreshed X of Y applications` -- if X is the number of applications that have been refreshed
* `Refreshing X of Y applications` -- if X is the number of applications that are currently refreshing (this seems unlikely, but the current text is ambiguous)

**Screenshots**

<img width="620" alt="image" src="https://github.com/argoproj/argo-cd/assets/2119212/662df236-b42a-4c0c-86ed-286297440e61">
<img width="301" alt="image" src="https://github.com/argoproj/argo-cd/assets/2119212/b948b821-020f-4062-9a9c-5e6e3c8ed7f1">

<img width="673" alt="image" src="https://github.com/argoproj/argo-cd/assets/2119212/b73a52d8-f147-4f68-9dae-af83fba57209">

![image](https://github.com/argoproj/argo-cd/assets/2119212/3ba3c3ef-a9fd-42db-af2c-5b7b468eb1e1)

**Version**

```shell
{
    "Version": "v2.8.0+d4714f3.dirty",
    "BuildDate": "2023-05-11T09:05:12Z",
    "GitCommit": "d4714f34cab5717457335bf3c8379e370d0b9119",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.7",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by HassanTanveer** [comment]
Hey, can you assign this issue to me?
