### ISSUE TITLE
Change group/grouped visualization

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#13565]
# Summary

The number of objects in a group should be shown on the group tile and the hover hint text should be terser

# Motivation

I shouldn't have to hover over an ℹ️ to find out how many objects are in a collapsed tile
The hint shouldn't tell me the kind of object when the tile itself tells me exactly that

# Proposal

How do you think this should be implemented?

### Current behavior

<img width="401" alt="image" src="https://github.com/argoproj/argo-cd/assets/2119212/fe7179ba-ae8d-4b65-9272-9d575a38843e">

#### Proposed

<img width="764" alt="image" src="https://github.com/argoproj/argo-cd/assets/2119212/7294f995-05d4-4b12-a23d-55575e4da298">

**Comment by ahmadniaz** [comment]
@jsoref I would like to work on this issue. Can you assign this task to me?

**Comment by vipinachar** [comment]
Hi @jsoref , Can you please assign this issue to me, I would like to work on this.

**Comment by jsoref** [comment]
@vipinachar: just create a PR, don't worry about assignment.
