### ISSUE TITLE
ArgoCD token is not revoked when logout.

### ISSUE THREAD

**Issue by GeorgiDimv** [argoproj/argo-cd#13593]
Hello I am using ArgoCD v2.6.7+5bcd846 with OIDC configured. The problem I am facing is when I logout the session token provided from my IDP is not revoked immediately but It is still valid until the expiration time is hit. 

Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD token is not revoked when logout.

**To Reproduce**

1. Log in ArgoCD 
2. Get argocd.token
3. Logout from ArgoCD
4. Send post request to "https://ARGOCDURL/api/v1/applications" using the token from step 2.

You will see that it returns status 200 while we want status 401

**Expected behavior**

Token to be invalid and to give status 401 unauthorized. 

**Version**

```shell
v2.6.7+5bcd846
```

**Comment by maartengo** [comment]
Did you find a solution to this problem @GeorgiDimv ?
