### ISSUE TITLE
Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.X.X.X:8081: i/o timeout"

### ISSUE THREAD

**Issue by bharathsat** [argoproj/argo-cd#13644]
Hi Team 

Describe the issue:
when i tried to create the appset using `argocd appset create` app creation was success from the command output, But i could see the timeout error in the coditions field. The ip 172.x.x.x:8081 is nothing but argocd-repo-server service cluster-ip.

` "[{ErrorOccurred child generator returned an error on parameter generation: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.x.x.x:8081: i/o timeout" 2023-05-18 12:40:33 +0530 IST True ApplicationGenerationFromParamsError}]" `
 
even thought the destination cluster added successfully i couldn't create appset using CLI or through kubectl deploy.

Steps i used before i execute the `argocd appset create` command.
1. Logged in to the kubernetes cluster where the argocd installed to get the argocd admin password.
2. Logged in to Argocd server
    `argocd login example_argocd.com`
3. Configured the external kubernetes cluster to get the external cluster context by running cluster config command
     `cluster config --cluster external_cluster_id`
4. Now adding the external cluster to argocd server with below command.
      `argocd cluster add --name external_cluster external-cluster-app-to-deploy/huoeivununvowvoub --label project=testing`
5. Adding git repo to the argocd
    `  argocd repocreds add https://example.github.com/reponame --github-app-enterprise-base-url https://example.github.com/api --upsert --username "$GHE_USERNAME"`
6. Creating project 
      ```argocd proj create test
      argocd proj allow-cluster-resource test -l allow '*' '*'
      argocd proj add-source test https://example.github.com/reponame.git
      argocd proj add-destination test https://externalclusterendpoint:443 test
7. creating appset
    ` argocd appset create examplegitappset.yaml --upsert`
    
    


Argocd cli version i used `argocd: v2.5.5+fc3eaec.dirty`

**Comment by patrickacioli** [comment]
It's an error with network policy `argocd-repo-server-network-policy`. If you delete this resource, everything will be works. 

-> Maybe you need to change the redis 
```yaml
images:
  - name: redis
    newTag: 6.2.4
```

**Comment by silveiralexf** [comment]
> argocd-repo-server-network-policy

just adding to the comment from @patrickacioli, one may reference the required change to the network policy below:
- https://github.com/argoproj/argo-cd/blob/52ffd7df4dd2c08b3dcf75dafd71ba194148f0f0/manifests/base/repo-server/argocd-repo-server-network-policy.yaml#L24
