### ISSUE TITLE
[UI] Highlight the current replicaset of a deployment 

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1367]
A useful UI feature would be if we could somehow indicate the "current" replicaset of a deployment. 

For example, given the following resource tree, we could somehow highlight the ReplicaSet which is related to the current target state of the deployment:

![image](https://user-images.githubusercontent.com/12677113/55520143-c16b5800-562f-11e9-9b24-ca062c3549a9.png)

Currently, the experience is to click through all ReplicaSets until we come across the one with the highest revision annotation:

```
metadata:
  annotations:
    deployment.kubernetes.io/revision: 'N'
```

We should make this flexible enough to work for CRDs that have similar concepts, e.g.: Argo Rollouts.

**Comment by alexec** [comment]
This is a neat feature and it'd be great to get community contribution on it.

**Comment by alexec** [comment]
I've interpreted this as "make it quicker and easier to find the current replica-set". I've labeled the resource with the revision. Thoughts?

![Screen Shot 2019-06-21 at 14 10 07](https://user-images.githubusercontent.com/1142830/59951646-6b3bd300-942e-11e9-9447-7ad433f35934.png)

**Comment by alexec** [comment]
![Screen Shot 2019-06-21 at 17 36 04](https://user-images.githubusercontent.com/1142830/59957229-1f4b5700-944b-11e9-9406-318243836e94.png)
