### ISSUE TITLE
[UI] applications view blows up when user does not have `get projects` permissions

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1368]
The UI gets a blank screen when viewing `/applications` when a user does not have `GET` privileges on *any* projects.

**Comment by jessesuen** [comment]
Perhaps the projects filter should be based on the current set of applications returned in the list, rather than a query to the projects API.

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-cd-ui/commit/f5833da4cdffee52282573396bc1396564495fb1
