### ISSUE TITLE
Allow Prometheus to scrape metrics by default

### ISSUE THREAD

**Issue by claire-fletcher** [argoproj/argo-cd#13688]
# Summary

ArgoCD exposes prometheus metrics, however our prometheus instance does not pick these up without having prometheus scrape labels, e.g.:

```
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9000"
```
Adding these labels by default could reduce additional configuration needs.

# Motivation

Currently every deployment/statefulset, where useful metrics are exported, needs to be patched with the prometheus scrape labels. This change would allow the additional configuration needed to get metrics working to be reduced, with fewer patches.

# Proposal
Add these labels to the kubernetes YAML in the argocd-repo-server, argocd-server, argocd-application-controller, argocd-notifications-controller, and any others if there are relevant metrics not noted in the documentation.

Alternatively, adding the information on what configuration is needed to retrieve the metrics as "Scraped at the argocd-metrics:8082/metrics endpoint" etc. in the documentation implies they will be scraped already with no additional configuration. Although, if this did actually happen for anyone's prometheus instance I would love to know the config!

**Comment by jaideepr97** [comment]
@claire-fletcher is this requirement specific to your prometheus instance, or does it apply to any generic prometheus instance?

**Comment by claire-fletcher** [comment]
I was under the impression that this would work for most instances of Prometheus but looking into it that could be a false assumption. I am unsure how adding it would interact with alternative methods such as using the prometheus operator service monitor etc. Happy to close this and keep the additional config specific to our instance so others can do the same!

**Comment by jaideepr97** [comment]
Yes, I was going to say I don't think I've had to use those specific labels when working with our prometheus instance 

> Happy to close this and keep the additional config specific to our instance
Thanks, I will go ahead and close it then
