### ISSUE TITLE
When view log it shown loading page long time.

### ISSUE THREAD

**Issue by sureenart** [argoproj/argo-cd#13711]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When view log on container it always shown Loading page .

**To Reproduce**

When view log on container it always shown Loading page . for more information on argocd we have almost ~150 apps.

**Expected behavior**

Show correct log .

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/125337032/5a22b839-75e5-4b0e-9708-4ff9bfa40cf9)

**Version**

```shell
➜ argocd version
argocd: v2.6.1+3f143c9.dirty
  BuildDate: 2023-02-08T22:18:08Z
  GitCommit: 3f143c9307f99a61bf7049a2b1c7194699a7c21b
  GitTreeState: dirty
  GoVersion: go1.19.5
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.7.2+cbee7e6.dirty
  BuildDate: 2023-05-12T13:43:26Z
  GitCommit: cbee7e6011407ed2d1066c482db74e97e0cc6bdb
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

Log on that time seem like ok.
```
time="2023-05-24T04:29:27Z" level=info msg="received streaming call /application.ApplicationService/PodLogs" grpc.method=PodLogs grpc.request.content="name:\"dev-xxxx\" namespace:\"xxxx-dev\" podName:\"xxxx-78bbf77c97-pmc9s\" container:\"xxxx\" sinceSeconds:0 tailLines:1000 follow:true appNamespace:\"argocd\" " grpc.service=application.ApplicationService grpc.start_time="2023-05-24T04:29:27Z" span.kind=server system=grpc
time="2023-05-24T04:29:27Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=PodLogs grpc.service=application.ApplicationService grpc.start_time="2023-05-24T04:29:27Z" grpc.time_ms=8.906 span.kind=server system=grpc

**Comment by tooptoop4** [comment]
@sureenart does it stay saying 'loading' forever? or do the logs always show up after 10 seconds?

**Comment by sureenart** [comment]
@tooptoop4 it’s shown forever log not show anymore.

**Comment by sureenart** [comment]
@tooptoop4  got error 503 when loading pod log .
![image](https://github.com/argoproj/argo-cd/assets/125337032/f98c60d3-afef-46a6-b68b-3334bcea7893)

**Comment by alexec** [comment]
So maybe two issues here

1. Shows loading long time.
2. Does not show error.

**Comment by alexec** [comment]
"503 Service Unavailable" means server cannot cope. Does 503 appear in the Argo CD logs?

**Comment by sureenart** [comment]
@alexec  thanks for your response. I found issue on api gateway . right now it's work!

**Comment by alexec** [comment]
Ok, I close issue.
