### ISSUE TITLE
Support for missingkey=error in ApplicationSets with goTemplate: true

### ISSUE THREAD

**Issue by raxod502-plaid** [argoproj/argo-cd#13731]
# Summary

Currently, ArgoCD does not offer any customization of the [options used for Go templating](https://pkg.go.dev/text/template#Template.Option):

https://github.com/argoproj/argo-cd/blob/5e543518dbdb5384fa61c938ce3e045b4c5be325/applicationset/utils/utils.go#L234

It would be nice if it were possible to set a key on the ApplicationSet spec that would customize the `missingkey` option.

# Motivation

We find that it is easy to forget to set a key in the cluster generator, or there is a typo that leads to the wrong key being set. This results in the use of that key in the appset manifest being expanded to null or an empty string, which is usually not what we want. If we could tell ArgoCD to abort on a templating error we would catch issues earlier rather than potentially after they are already deployed.

# Proposal

I would suggest a new key at the top level of the appset spec, next to `goTemplate`, which lists options to be passed to the template engine, in the same format as [the underlying function](https://pkg.go.dev/text/template#Template.Option). This ensures that work is not needed to keep up with new options that are added to Go.

If there are security concerns, we can add an allowlist for the supported options.

The existing behavior would remain the same as the default behavior would be to pass no extra options, which is what happens today.

**Comment by crenshaw-dev** [comment]
This makes a lot of sense, I'd gladly review a PR to make this change.

**Comment by raxod502-plaid** [comment]
@crenshaw-dev I've created https://github.com/argoproj/argo-cd/pull/13733 to implement this feature. I've added passing unit tests although I haven't deployed the fork to a cluster to test in practice. The only thing missing from the contribution checklist is the feature status, should this field be marked as alpha?
