### ISSUE TITLE
Error view instead of blank page in UI

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1375]
Now any JS error crashes UI and user is seeing an empty screen. Instead, UI should show view with an explanation of what happened and instructions to file a bug. Instructions should include stack trace, UI version and link to github create issue. Preferrably link should include parameters to prepopulate bug in github ui.

**Comment by alexmt** [comment]
This can be implemented with help of  [error-boundaries](https://reactjs.org/docs/error-boundaries.html) react feature.

**Comment by mateimicu** [comment]
This sounds nice, we just his a UI problem and can't seem to figure out what the problem is.
