### ISSUE TITLE
Surface replica set health to tree view

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1376]
Before you start work, is this a real problem for customers? We have one incident where the status was buried. Are there more?

See https://github.com/argoproj/argo-cd/issues/1358

**Comment by alexmt** [comment]
ReplicaSet is rendered in the tree view already. Can you clarify what do you mean?

**Comment by alexec** [comment]
https://github.com/argoproj/argo-cd/issues/1382
