### ISSUE TITLE
API server goroutine leak

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1381]
We have a slow but steady goroutine leak happening in the API server:

![image](https://user-images.githubusercontent.com/12677113/55597035-71a89180-5700-11e9-9e4a-56b3f1ebfc69.png)

**Comment by alexec** [comment]
Probably day-0 bug.

**Comment by alexec** [comment]
Investigating.

**Comment by alexec** [comment]
Ok. So attaching some debugging code and running `make test-e2e` makes the number of goroutines increase. I think this may likely include the leak.

**Comment by alexec** [comment]
Useful link https://medium.com/golangspec/goroutine-leak-400063aef468

**Comment by alexec** [comment]
Maybe in `NewFilteredApplicationInformer` and `NewFilteredAppProjectInformer`.

**Comment by alexec** [comment]
![Screen Shot 2019-04-12 at 11 45 29](https://user-images.githubusercontent.com/1142830/56059466-fa36bb80-5d18-11e9-992b-42ac427915f6.png)

**Comment by alexec** [comment]
http://localhost:6060/debug/pprof/goroutine?debug=1

starts at 97 routines
