### ISSUE TITLE
ArgoCD - Creating New App - Destination Cluster URL/Name Drop down not working

### ISSUE THREAD

**Issue by jayyzhao** [argoproj/argo-cd#13813]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD v2.7.3 and v2.7.2 we have noticed that in the '+ New App' page under the destination and selecting Name instead of URL does not take effect.  

**To Reproduce**

1. Open ArgoCD to home page 
2. Click 'New App'
3. Scroll down to Destination
4. try and change the right hand side dropdown from URL to Name

**Expected behavior**

Upon clicking 'Name', it should take effect and be able to search based on cluster name instead of cluster ip. 

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/2725204/13046fdc-8fc4-4f75-afb5-1036969dac54)

**Version**

v2.7.3 & v2.7.2

**Comment by Conrimaceogain** [comment]
I can confirm that this is still an issue in Argo CD v2.7.5.

**Comment by slammajamma28** [comment]
This is an issue in v2.7.6 as well
