### ISSUE TITLE
Unsafe_Use_Of_Target_blank

### ISSUE THREAD

**Issue by kpu32167** [argoproj/argo-cd#13820]
Hi.  
We have found an issue in argo source code  in version v2.5.17 (Unsafe_Use_Of_Target_blank).
https://github.com/argoproj/argo-cd/blob/c06f954730928a2a739e8c1276e9f24738d932a3/ui/src/app/applications/components/pod-logs-viewer/pod-logs-viewer.tsx#LL262C71-L262C71
Can you fix this issue by adding  rel='noopener noreferrer' to link ?

**Comment by crenshaw-dev** [comment]
I believe the check is a false-positive, because the link doesn't open an external site. But no harm in adding the attribute.

**Comment by todaywasawesome** [comment]
Agreed.

@kpu32167 this is an easy PR if you want to open it, we'll merge it.

**Comment by aakankshabhende** [comment]
@crenshaw-dev @todaywasawesome I would like to work on this issue. Could you please assign me this?
