### ISSUE TITLE
OutOfSync from Job

### ISSUE THREAD

**Issue by aquarelacs-arthur-rosa** [argoproj/argo-cd#13851]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

We are having the following problem, we have a yaml job in github being replicated to an eks in aws, but the job has TTL rules, after a certain period, it deletes itself, causing an outOfSync in ArgoCD, is there any solution for our case ?

We managed to pass the Job to deployment, if there is no other solution, being a deployment, we could use the name Prefix, possibly solving the case, could you help me?

1 - Create a Job, and put TTL on the Job
2- use ArgoCD
3- with that, an OutOfSync will be generated soon

That it replicated and did not generate OutOfSync

![image](https://github.com/argoproj/argo-cd/assets/133425456/b8fcc8d3-0a6c-4f51-bcaf-5de177c74653)

```shell
argocd: v2.4.7+81630e6
  BuildDate: 2022-07-18T21:38:56Z
  GitCommit: 81630e6d5075ac53ac60457b51343c2a09a666f4
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.7.1+5e54351.dirty
```

**Logs**

```
I don't have logs
```

**Comment by ebuildy** [comment]
well there is some good posts about this already:

https://github.com/argoproj/argo-cd/discussions/7984 can be a good start.
