### ISSUE TITLE
argocd CLI RBAC validation doesn't work on actions

### ISSUE THREAD

**Issue by davidham** [argoproj/argo-cd#13911]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
The `argocd admin settings rbac can` command does not work on `action` actions.

**To Reproduce**
1. Create a policy file called test.csv with the following content: 
    ```csv
    p, role:engineer, applications, action/*, */*, allow
    ``` 
2. With the CLI, run this command:
    ```
    argocd admin settings rbac can role:engineer action/apps/Deployment/restart applications --policy-file test.csv
    ```

CLI returns:
```
FATA[0000] error in RBAC request: 'action/apps/Deployment/restart' is not a valid action name 
```
**Expected behavior**
CLI should return `Yes` based on the given policy file, or `No` if the policy doesn't allow it. The example action is one of the built in [resource customizations](https://github.com/argoproj/argo-cd/tree/master/resource_customizations/apps/Deployment/actions/restart).

**Version**

```shell
$ argocd version
argocd: v2.7.3+e7891b8
  BuildDate: 2023-05-24T15:51:26Z
  GitCommit: e7891b899a35dca06ae94965ea5ae2a86b344848
  GitTreeState: clean
  GoVersion: go1.19.9
  Compiler: gc
  Platform: darwin/arm64
```

**Comment by jjtroberts** [comment]
We're experiencing a similar issue:
` p, role:infrastructureengineer, applications, action/argoproj.io/Rollout/restart, dev/*, allow`

Running the cli returns:
`argocd admin settings rbac --policy-file argocd-rbac-cm.yaml can role:infrastructureengineer action/argoproj.io/Rollout/restart applications 'dev/my-service'
FATA[0000] error in RBAC request: 'action/argoproj.io/Rollout/restart' is not a valid action name`
