### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1395]
Please add any comments about teething problems with https://argoproj.github.io/argo-cd/ to this issue.

**Comment by johnmarcou** [comment]
Hello,

https://argoproj.github.io/argo-cd/operator-manual/security/#cluster-rbac
Bullet points (1. and 2.) are on the same line.

https://argoproj.github.io/argo-cd/operator-manual/metrics/#dashboards
Dashboard Json link is broken. https://argoproj.github.io/argo-cd/examples/dashboard.json

The redis helm chart link is broken here: https://argoproj.github.io/argo-cd/user-guide/application_sources/#random-data

https://argoproj.github.io/argo-cd/user-guide/best_practices/#leaving-rroom-for-imperativeness
Typo on Rroom to room

Thank you for this website, it's great!

**Comment by alexec** [comment]
Weird formatting on this page:

https://argoproj.github.io/argo-cd/developer-guide/

**Comment by alexec** [comment]
Broken link:

https://argoproj.github.io/argo-cd/developer-guide/api-docs/
