### ISSUE TITLE
Support for weighted resource hooks: `helm.sh/hook-weight`

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1396]
There is a need to perform a phased rollout of multiple deployments where deployment B needs to be deployed only **after** deployment B is fully ready.

Typically this use case is solved by defining an init container in deployment B, which queries its dependency (deployment A) to be up. However, there are some scenarios where init containers are unable to solve the problem.

For example, one scenario is that deployment B should not start until deployment A is running with same version of deployment B. An init container performing a version check would not help here because deployment A may be running with multiple replicas, and could potentially be returning a mix of versions, when deployment A is performing a rolling update.

Depended on by #355.

**Comment by jessesuen** [comment]
Reference on helm hook weights:
https://github.com/helm/helm/blob/master/docs/charts_hooks.md#writing-a-hook

When we implement this, we need to additionally honor helm weights

**Comment by alexec** [comment]
```yaml
  annotations:
    "argoproj.io/hook-weight": "-5"
```

**Comment by alexec** [comment]
@jessesuen I've implemented weight hooks, but I don't think they actually solve your problem 😠 . It does move us towards better Helm support mind you.

You want waves of roll out. I'm going to speak to @dthomson25 about this.

**Comment by alexmt** [comment]
@alexec , replied in PR

**Comment by alexec** [comment]
Closing this issue and replacing.

**Comment by jessesuen** [comment]
Reopening because I don't agree `argoproj.io/sync-wave` is the right syntax, and I think it's important to be consistent in concept and implementation with helm `hook-weights`, especially since we plan to map the helm-hook weights to this feature

**Comment by alexec** [comment]
I think we keep this open for Helm hook support.
