### ISSUE TITLE
Misleading Readiness Gate error in Argo CD UI

### ISSUE THREAD

**Issue by leoluz** [argoproj/argo-cd#13972]
**Describe the bug**

Argo CD now provides a new error in the UI instructing the user that there is a problem with the Readiness Gates (See screenshot below). The logic in the UI validates the existence of a readiness gate in the Pod spec without a related condition in the status field. However this error is misleading as pods that are marked with readiness gates will always have a moment where this condition is not met and errors are often being displayed. If the controller responsible for updating the readiness gate is overloaded or just slow, the Pod won't have a related condition created for a while. It will eventually create the condition and the situation will be normalized. Users are confused with this new UI thinking that there is an actual problem with their application.

Suggestion:
- Change the UI logic to just show the message when all container statuses are marked as ready and we still don't have the readiness gate condition created
- Change the UI and make it display a warning message instead of an error message.

**Screenshots**

![readinessgate_error](https://github.com/argoproj/argo-cd/assets/44989/0d6bf3db-cd17-408c-8dd3-25e9339b7f3b)

**Version**

Argo CD 2.7.2

**Comment by crenshaw-dev** [comment]
By my reading of the docs, even if the readiness gate statuses are set, but they are set to `False`, we cannot infer that they are "failed." They simply aren't ready. So we should report the status neutrally, without implying that there is some error or failure.

**Comment by Marvin9** [comment]
Makes sense. I will reiterate on readiness gates UI to avoid premature checks and report warning instead of error.
