### ISSUE TITLE
adding private clusters 

### ISSUE THREAD

**Issue by esn89** [argoproj/argo-cd#13987]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Adding GKE clusters with private IPs such as: 10.123.123.123 (which is routable within our organization) doesn't seem to work and throws:

```
argocd cluster add gke_private_cluster_1 --plaintext --insecure
WARNING: This will create a service account `argocd-manager` on the cluster referenced by context gke_private_cluster_1 with full cluster level privileges. Do you want to continue [y/N]? y
FATA[0001] Failed to create service account "argocd-manager" in namespace "kube-system": Post "https://10.123.123.123/api/v1/namespaces/kube-system/serviceaccounts": tls: failed to verify certificate: x509: certificate signed by unknown authority 
```

Interestingly enough, in my kube config of `~/.kube/config`:

```
at ~/.kube/config 
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/me/personal-cert-chain.pem
    server: https://10.123.123.123
  name: gke_private_cluster_1
  ```
  
  I can use `kubectl` just fine without having any cert issues, because I have specified the CA.  I am wondering: **does ArgoCD have any way for me to pass in a certificate authority so that I can add a private cluster?**

**To Reproduce**

Add the GKE info:
`gcloud container clusters get-credentials gke_private_cluster_1 --region us-central1 --project my-gcp-project`
`kubectl config get-contexts -o name`
`argocd cluster add gke_private_cluster_1 --plaintext --insecure`

**Expected behavior**

I expect it to add successfully with the plaintext and insecure flag.

**Version**

```shell
argocd: v2.7.4+unknown
  BuildDate: 2023-06-06T13:39:21Z
  GitCommit: 
  GitTreeState: clean
  GoVersion: go1.20.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.7.4+a33baa3.dirty
  BuildDate: 2023-06-05T19:00:34Z
  GitCommit: a33baa301fe61b899dc8bbad9e554efbc77e0991
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
time="2023-06-10T17:39:45Z" level=error msg="finished unary call with code Unknown" error="Invalid hostname in request: https://10.123.123.123" grpc.code=Unknown grpc.method=CreateCertificate grpc.service=certificate.CertificateService grpc.start_time="2023-06-10T17:39:45Z" grpc.time_ms=4.948 span.kind=server system=grpc
```

**Comment by jannfis** [comment]
Hi. The problem is that your certificate authority refers to a file. The kubeconfig gets submitted as-is to Argo CD's workloads, and it doesn't have this file.

Your best bet is to replace the reference to a file in `certificate-authority` with a base64 encoded version of the root certificate.

**Comment by esn89** [comment]
I will give that a try. thank you.

**Comment by shuker85** [comment]
@esn89 did the suggestiong work for you ?

**Comment by esn89** [comment]
Yes, it worked.  Thank.s

**Comment by onlw** [comment]
> 是的，它起作用了。谢谢

请问如何做的啊
