### ISSUE TITLE
Set kustomize image parameter through CLI

### ISSUE THREAD

**Issue by brushmate** [argoproj/argo-cd#1400]
When we run branch builds of our projects we would like to start the produced artifacts in Argo CD in order to run integration tests against them. We planned to use the Argo CD CLI from our Jenkins to start the applications and delete them after running the tests. We mostly use Kustomize v2 in our projects and during branch builds we need to set its `images` field. I noticed that you can specify it in the web UI but not in the CLI.

It would be great if we could use a flag similar to `--nameprefix`. Another option would be to generalize the `--parameter` flag to support not only Helm.

**Comment by alexec** [comment]
Hi @brushmate,

Have you considered using `argocd app patch`? I think you'd need something like

```bash
argocd app patch kustomize-guestbook --patch '[{"op": "add", "path": "/spec", "value": {"kustomize": {"images": ["gcr.io/heptio-images/ks-guestbook-demo:0.3"]}}}]'
```

I can't give you the exact answer as you'll probably need to experiment with this.

**Comment by brushmate** [comment]
Thank you for the advice @alexec! I got it working with th following:

    argocd app patch my-app --patch '[{"op":"replace","path":"/spec/source/kustomize","value":{"images":["my-registry/my-image:my-tag"]}}]'

**Comment by alexec** [comment]
Great to hear! Do you want me to close this issue?

**Comment by brushmate** [comment]
Do you know if there are plans to support setting the image tag directly in the `argocd app create` command? Elsewise you can just close the issue.
