### ISSUE TITLE
Argo-cd & Argo-events

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-cd#1401]
Is it possible to use Argo-cd & Argo-events together ?

**Comment by alexec** [comment]
Hi @emichaf - generally the answer is a firm "yes", but are you able to provide a bit more context? For example, what are you looking to do?

**Comment by emichaf** [comment]
Hi @alexec, I'm would like to start sync activities based on incoming stream event on ex. RabbitMQ!

**Comment by alexec** [comment]
Probably the easiest way to invoke `argocd` from third-party apps is using the CLI. E.g. 

~~~bash
argo app sync myapp
~~~

You'd need to create an app to bridge that. 

Argo CD also has an API. Read more here: https://argoproj.github.io/argo-cd/developer-guide/

**Comment by emichaf** [comment]
The cli argocd is not available for windows, can i use cli argo instead ?

**Comment by alexec** [comment]
Sorry - I realize there was an error in my comment, you need to use the `argocd` CLI.

If you are on Windows, then you'll need to look into the API.

**Comment by emichaf** [comment]
answered
