### ISSUE TITLE
not able to see logs

### ISSUE THREAD

**Issue by sasikalaeveuser** [argoproj/argo-cd#14036]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by tooptoop4** [comment]
@sasikalaeveuser what version?
screenshot of issue?
