### ISSUE TITLE
Argocd app Sync with Prune, Force and Replace on UI on version v2.5.1+504da42 starts deleting the app after some time

### ISSUE THREAD

**Issue by ashish-dua** [argoproj/argo-cd#14041]
Checklist:

[- ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
[- ] I've included steps to reproduce the bug.
[ -] I've pasted the output of argocd version.

We are trying to sync to sync on 8-10 applications with Prune, Force and Replace since revision needed to be changed for entire application. while doing the same Applications after synched in this process and after certain time interval ; All those applications are getting deleted on their own, We have this issue coming on atleast 2 clusters where argocd is deployed

**Comment by shuker85** [comment]
@ashish-dua v2.5 is EOL'ed now. Do you still have this issue ?
