### ISSUE TITLE
Application deletion might get stuck 

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1406]
**Describe the bug**
Sometimes application deletion might get stuck. Based on the description it looks like the k8s cache is stale. 

**To Reproduce**
There are no clear steps to reproduce. Looks like the issue might happen for very large application.

**Expected behavior**
The application should be deleted without any issues.

**Comment by magicmoose** [comment]
this seems similar to #1329

**Comment by alexmt** [comment]
Looks like the issue is solved
