### ISSUE TITLE
Helm values leak on argocd UI - app details parameters tab

### ISSUE THREAD

**Issue by ebuildy** [argoproj/argo-cd#14065]
# Summary

Make possible to 100% never leak (UI, CLI, cache ...) values of an argocd helm application.

# Motivation

We put passwords / token inside "./secure/values.yaml" protected by git-crypt. I know there is a ton of plugins (sops/helm-secret) to do this, but at the end, this is the same.

Everything is fine, but I see on argocd UI, all values are shown from the "app details parameters" tab ! 

Okay our argocd is not public, under auth etc... but I am really comfortable with it.

# Proposal

1. Hide parameters if key is "password" / "token" / "secret", a simple regpex could do the trick
2. Make configurable to hide the parameters tab
3. We must never put secure data inside values.yaml

**Comment by b47on** [comment]
This is a problem that stops us from giving the developers access to ArgoCD - they must not be able to see the secrets.
We (devops team) would love the devs to be able to access the ArgoCD UI and see the status and structure of the application, but secops won't allow that until this problem is solved.

**Comment by crenshaw-dev** [comment]
I'm not sure I understand how blocking values access in the Argo CD UI would be an effective security control.

If the user has update access to either the Application resource or to the chart templates themselves, they could direct the secret value into some portion of the manifests which makes the value visible, e.g. an annotation.

In case it's not obvious how that would be done with Application update access, I think the attacker could do something like this:

```yaml
kind: Application
spec:
  source:
    helm:
      values: |
        deployment:
          annotations:
            pwned: '{{.Values.secret}}'
```

If I recall correctly, Helm will template the secret value into the `deployment.annotations.pwned` field.

**Comment by ebuildy** [comment]
@crenshaw-dev there is a big difference between "ho I see the secret in HTML" and "ho I had to write a template to see the secret".

Also, I notice argocd UI dont display secret content:

<img width="368" alt="Capture d’écran, le 2023-07-28 à 11 14 22" src="https://github.com/argoproj/argo-cd/assets/1219817/b842a2ee-21c5-4995-9763-632733ff0a73">

So it make sense to do the same for all UI components isnit?

**Comment by b47on** [comment]
> I'm not sure I understand how blocking values access in the Argo CD UI would be an effective security control.
> 
> If the user has update access to either the Application resource or to the chart templates themselves, they could direct the secret value into some portion of the manifests which makes the value visible, e.g. an annotation.

That is correct. But in order to do so, developer would need to commit to source control such a change - which is accountable and we are able to monitor such changes (f.e. pull requests with changes to helm charts other then image versions add devops member as required reviewer)

As @ebuildy commented, this is very similar to how argo UI displays secrets - why not be consistent about it?

**Comment by bitnik** [comment]
Hello, we are also interested in this feature. Is there any workaround you would recommend?

**Comment by ebuildy** [comment]
Well we have "disable" the route / content with a proxy, I can do a PR if I am sure it will be merged?

**Comment by crenshaw-dev** [comment]
I think I'm still opposed to this change. Argo CD shouldn't be handling secrets at all. It's architected from the ground up assuming it will not be managing secrets. Hiding them in the UI is a band-aid at best.

I know it's a heavy lift, but long-term public Helm charts should probably stop accepting secrets in values and instead rely on secret refs. Users should switch to using on-cluster secrets operators.

**Comment by crenshaw-dev** [comment]
I feel like it would be net-negative. Putting secrets in Helm values in Argo CD is already a bad idea from a security perspective. Using things like regex to find and hide secrets is very error-prone, and I think it would offer a false sense of security.

**Comment by ebuildy** [comment]
I am totally agreed, 

But there is the reality, everybody is not expert on k8s but can use argocd, can make mistake.

**Comment by bitnik** [comment]
Thank you for your inputs! After also reading more about it, I see that we should improve how we handle secrets and use only references.

Btw there is another problem with having secrets in values: they are visible in logs of "argocd repo server" pod.

**Comment by crenshaw-dev** [comment]
Argo CD repo-server logs are often persisted outside Argo CD's interface, so secrets should not ever go into logs. Since Argo CD was never designed to handle secrets in Helm values, it logs those values. There are many such examples of Argo CD not being designed to handle secrets in this way.

**Comment by ebuildy** [comment]
Sure I understand, I have to spread the good word within my team ^^

I am closing this issue.
