### ISSUE TITLE
ArgoCD operator

### ISSUE THREAD

**Issue by shraddhabp** [argoproj/argo-cd#14074]
Checklist:

* [* ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ *] I've included steps to reproduce the bug.
* [ *] I've pasted the output of `argocd version`.

**Describe the bug**

After install ArgoCD using Operator, Application and Cluster show errors for many such resources and the namespace added in the cluster
failed to sync cluster https://172.21.0.1:443: failed to load initial state of resource Service: services is forbidden: User "system:serviceaccount:gm4c-devops-factory:argocd-gm4c-argocd-application-controller" cannot list resource "services" in API group "" in the namespace "dev"

**To Reproduce**

1. Install the ArgoCD Operator in a single Namespace on OpenShift
2. Creat an instance of ArgoCD using the steps given here-
https://argocd-operator.readthedocs.io/en/latest/usage/basics/
3. Once the instance is Available, set  the spec:server:  route: enabled: true 
4. Access ArgoCD on the Route created.
5. Login to the ArgoCD using admin 
6. Add namespace dev to the in-cluster
7. Add Git repository
8. Create an application, choose namespace dev
9. Application shows multiple error messages  as in the screenshot 
10. Cluster show error as in the screenshot

**Expected behavior**

The application should not show errors.
The Cluster should show a connected status

**Screenshots**

 
<img width="966" alt="image" src="https://github.com/argoproj/argo-cd/assets/92920391/71d48cb6-45c5-4eae-a432-c127dbf80c79">
<img width="1156" alt="image" src="https://github.com/argoproj/argo-cd/assets/92920391/bd12a7e4-a806-4626-b8df-0df4f98fd3aa">

**Version**

```shell
$ argocd version
argocd: v2.5.4+86b2dde
  BuildDate: 2022-12-06T19:46:25Z
  GitCommit: 86b2dde8e4bf1187acd2b4294e94451cd104dad8
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified           
$
```

**Logs**

```
failed to sync cluster https://172.21.0.1:443: failed to load initial state of resource DaemonSet.apps: daemonsets.apps is forbidden: User "system:serviceaccount:gm4c-devops-factory:argocd-gm4c-argocd-application-controller" cannot list resource "daemonsets" in API group "apps" in the namespace "dev"
```

**Comment by jaideepr97** [comment]
Hi @shraddhabp Argocd-operator is a separate project, please feel free to raise this issue against that project here: https://github.com/argoproj-labs/argocd-operator/

Closing this one
