### ISSUE TITLE
Use latest build for the notifications-engine

### ISSUE THREAD

**Issue by shivamgupta211-fx** [argoproj/argo-cd#14127]
# Summary
Currently the [Master Branch's go.mod](https://github.com/argoproj/argo-cd/blob/master/go.mod#L14) is pointing to the [older revision](https://github.com/argoproj/notifications-engine/commit/f754726f03dac2577f38e0b054d8243a1712934b) of argocd notifications

Due to this, the notification component is lacking the latest features which are present in the [newer revision](https://github.com/argoproj/notifications-engine/commit/2bb2fcd19af2788a9c527f3b7a7b80e24dbdb46b)

# Motivation
Not able to implement PagerDutyV2 feature in argocd notifications

# Proposal
Update the go.mod and push the newer build for the helm chart.

**Comment by pasha-codefresh** [comment]
@shivamgupta211-fx do you want to contribute it? i can help with delivery

**Comment by shivamgupta211-fx** [comment]
Hi, @crenshaw-dev @pasha-codefresh 
I've raised a PR for the fix. Please have a look.

**Comment by pasha-codefresh** [comment]
Thank you @shivamgupta211-fx
