### ISSUE TITLE
ComparisonError when using Umbrella charts

### ISSUE THREAD

**Issue by EppO** [argoproj/argo-cd#1412]
**Describe the bug**
With Argocd v0.12.0, a new ArgoCD app using an umbrella Chart (Helm Chart having other Helm Charts dependencies) throws:
```
ComparisonError  rpc error: code = Unknown desc = Error: open /tmp/helm713078773/repository/cache/stable-index.yaml: no such file or directory
```

**To Reproduce**
1. Create a helm Chart with other charts as dependencies (like prometheus-operator, which has also dependencies)
2. Add Custom Helm Chart repo to ArgoCD configmap if using private Helm Chart repository
3. Create a ArgoCD app
4. See ComparisonError error

**Expected behavior**
App should sync normally. 

**Additional context**
I use Chartmuseum inside the same kubernetes cluster that runs argo and the app I'm trying to deploy.

repo-server logs:
```
time="2019-04-09T01:31:03Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListDir grpc.service=repository.RepoServerService grpc.start_time="2019-04-09T01:31:02Z" grpc.time_ms=348.93 span.kind=server system=grpc
time="2019-04-09T01:31:03Z" level=info msg="getfile cache hit: ce02459a54ae890699dfb4532d75cad5e1cf4455/Chart.yaml"
time="2019-04-09T01:31:03Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetFile grpc.service=repository.RepoServerService grpc.start_time="2019-04-09T01:31:03Z" grpc.time_ms=44.027 span.kind=server system=grpc
time="2019-04-09T01:31:03Z" level=info msg="listdir cache hit: ce02459a54ae890699dfb4532d75cad5e1cf4455/./*.yaml"
time="2019-04-09T01:31:03Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListDir grpc.service=repository.RepoServerService grpc.start_time="2019-04-09T01:31:03Z" grpc.time_ms=40.238 span.kind=server system=grpc
time="2019-04-09T01:31:03Z" level=info msg="getfile cache hit: ce02459a54ae890699dfb4532d75cad5e1cf4455/Chart.yaml"
time="2019-04-09T01:31:03Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetFile grpc.service=repository.RepoServerService grpc.start_time="2019-04-09T01:31:03Z" grpc.time_ms=38.354 span.kind=server system=grpc
time="2019-04-09T01:31:03Z" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:https://mygitlab/helm-charts/infra-stack.git,Path:.,TargetRevision:HEAD,ComponentParameterOverrides:[],Helm:nil,Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,}/ce02459a54ae890699dfb4532d75cad5e1cf4455"
time="2019-04-09T01:31:03Z" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:https://mygitlab/helm-charts/infra-stack.git,Path:.,TargetRevision:HEAD,ComponentParameterOverrides:[],Helm:nil,Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,}/ce02459a54ae890699dfb4532d75cad5e1cf4455"
time="2019-04-09T01:31:03Z" level=info msg="helm init --client-only --skip-refresh"
time="2019-04-09T01:31:03Z" level=info msg="helm template . --name infra-stack --namespace infra"
time="2019-04-09T01:31:03Z" level=error msg="`helm template . --name infra-stack --namespace infra` failed: Error: found in requirements.yaml, but missing in charts/ directory: prometheus-operator, heapster, kubernetes-dashboard, nginx-ingress\n"
time="2019-04-09T01:31:03Z" level=info msg="helm repo add chartmuseum http://chartmuseum.infra.svc.cluster.local:8080"
time="2019-04-09T01:31:03Z" level=info msg="helm dependency build"
time="2019-04-09T01:33:11Z" level=error msg="`helm dependency build` failed: Error: open /tmp/helm352689188/repository/cache/stable-index.yaml: no such file or directory\n"
time="2019-04-09T01:33:11Z" level=error msg="finished unary call with code Unknown" error="Error: open /tmp/helm352689188/repository/cache/stable-index.yaml: no such file or directory" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2019-04-09T01:31:03Z" grpc.time_ms=128057.984 span.kind=server system=grpc
```

**Comment by EppO** [comment]
I tried to do myself the `helm dependency build` and `helm template` inside the kubernetes cluster and it worked fine. 

I noticed I ran into the same issue into another cluster running on v0.11.2, which was working very well before and for a long time. Looking at the repo-server, `/tmp` was huge: 59G. Clearing the helm cache cleared also the error on v0.11.2. There might be an issue on the automatic pruning of the cache. 
Regarding v.12.0, it is a brand new cluster so cache was empty.

**Comment by alexec** [comment]
@EppO have you added your Helm repositories to the configuration?

https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#helm-chart-repositories

**Comment by alexmt** [comment]
I believe ticket description stays repo was added:

> 2. Add Custom Helm Chart repo to ArgoCD configmap if using private Helm Chart repository

Checked the helm related code. Argo CD creates new temp directory on every yaml generation but don't deleted it afterwards. I think this explains why `/tmp` directory keeps grooving. 

I could not reproduce issue using following sample app https://github.com/alexmt/argocd-example-apps/blob/test/helm-dependency/requirements.yaml. 

argocd-cm config map:

```
  helm.repositories: |
    - url: https://argoproj.github.io/argo-helm
      name: argo
```

app creation command:
```
argocd app create --name test --repo https://github.com/alexmt/argocd-example-apps --dest-server https://kubernetes.default.svc --dest-namespace default --path ./helm-dependency --revision test
```

@EppO  Is there any chance you can try it in your environment?

**Comment by EppO** [comment]
Maybe I forgot one important piece of information: my cluster doesn't have direct Internet connectivity. So I can't add Helm or Git repos from Internet. Is the helm client relies on the stable helm repo (that gets configured by default)?? That would explain why it expects something it can't get. Thing is, it was working fine in 0.11.2. It seems something changed regarding that in 0.12.
I can try to mirror Argo CD git and helm repos inside our network and give it a try with your example apps.

**Comment by alexmt** [comment]
Thanks for additional information! 

The similar issue was described in https://github.com/argoproj/argo-cd/issues/786 . The solution was to run `helm dependency build` only if `helm template` fails due to missing dependency. 

Your case is slightly different since chart has dependency.  I cannot understand how it was working in v0.11 . It seems like `helm dependency build` fails when stable repo is not accessible even if chart don't depend on it.

The only difference in v0.12 is now helm have access to environment variables:
https://github.com/argoproj/argo-cd/commit/e8deeb26225170a814170e7e21f8eae9a12f2d2e#diff-ee2739924bee7883b04663b5be1ecb87

Trying to test it locally.

**Comment by wiadam** [comment]
Hi,
I'm working with @EppO on this pb and based on @alexmt comment I added stable repo in the argocd-cm.yaml to point to our chartmuseum within our cluster (as we have all the stable charts published in our chartmuseum).
So I extended like below:
```
data:
  helm.repositories: |
    - url: http://chartmuseum.infra.svc.cluster.local:8080
      name: stable
    - url: http://chartmuseum.infra.svc.cluster.local:8080
      name: chartmuseum
```
And it did the trick :)
Now argocd is able to proceed.

So I suggest you enrich documentation to indicate that stable repo needs to be defined

Thanks

**Comment by alexmt** [comment]
Great. I was looking for the right solution for clusters without internet access. Overriding `stable`repo in configuration is the simplest one! Will add it into FAQ https://github.com/argoproj/argo-cd/blob/master/docs/faq.md

Thank you!

**Comment by EppO** [comment]
Thanks for your help!
I think there is a underlying issue regarding the growing helm cache in the /tmp though. 
Are all the helm repositories defined in the configmap stored locally inside the argocd repo server? All the helm chart stable repo and ours combined are not that big, we're far from the 50GB.
Do you want me to open another issue about that?

**Comment by alexmt** [comment]
Just created the issue https://github.com/argoproj/argo-cd/issues/1446 . Sending PR with FAQ update

**Comment by EppO** [comment]
Can close this one now
