### ISSUE TITLE
Include application name in the badge SVG

### ISSUE THREAD

**Issue by danielsiwiec** [argoproj/argo-cd#14162]
# Summary

I'd like to propose to optionally include the project name in the badge SVG.

# Motivation

Similar to [GitHub badges](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge), it would be convenient if the Argo badges also included the project name (optionally). This would let the badge be displayed without additional labels

# Proposal

Similar to the optional revision information (`?revision=true`) the name could be displayed with (`?displayName=true`, since `name` is already used)

**Comment by danielsiwiec** [comment]
If there's an agreement around the usefulness of this enhancement, I'll be happy to submit a PR.

**Comment by hameno** [comment]
I'd like to have this or a configurable label.
I want to setup the badges on gitlab and if you want to show multiple environments which are deployed using different apps you just see a bunch of badges without names

**Comment by danielsiwiec** [comment]
@hameno that's pretty much my use case exactly

**Comment by crenshaw-dev** [comment]
I'd happily review/merge.  :-)
