### ISSUE TITLE
WebSocket connection for terminal is closed due to lack of keepalives

### ISSUE THREAD

**Issue by erhudy** [argoproj/argo-cd#14191]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The WebSocket functionality used for the interactive terminal does not currently include any sort of keepalive. Because of this, if Argo is behind a load balancer that times out idle connections, the terminal will eventually stop working after being idle for long enough and need to be restarted.

I have a patch ready already that I have tested in my environment and found that it solves the problem - this issue is for bookkeeping purposes.

**To Reproduce**

In my case I have Argo running behind an ALB in AWS, where the default timeout is 60 seconds. If I open a terminal to a pod and leave it alone for 60+ seconds, it will silently stop working and the Argo CD server logs a WebSocket error on the other side. Doing something to keep activity going (e.g. printing something in a loop) prevents it from being closed.

**Expected behavior**

Terminal should remain open and functional until closed by the user.

**Screenshots**

**Version**

2.7.6 (exists in all prior versions with the terminal functionality as well)

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
Fixed with https://github.com/argoproj/argo-cd/pull/14192
