### ISSUE TITLE
Merge UI into main code base

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1421]
**Is your feature request related to a problem? Please describe.**

The `argo-cd-ui` codebase is separate. This makes a lot of extra work when making changes that affect both the backends and the frontend (e.g. branching). 

We can better link up changes to issues.

This would also enable simpler tooling

**Describe the solution you'd like**

Merge the tree of `argo-cd-ui` into this code base AND maintain the Git history:

https://saintgimp.org/2013/01/22/merging-two-git-repositories-into-one-repository-without-losing-file-history/

**Describe alternatives you've considered**

Do nothing. This has benefits. No up-front work. Can make UI changes without green backend builds.

**Additional context**

Pros:

* Only one PR per change. 
* Changes can be more easily correlated and therefore reviewed.
* Changelog can be generated from commits/issues. Very clear what is in each release, no human error.
* Can automate UI tests in the same pipeline as backend.

Cons:

* Historial. "We actually went out of our way to keep these things separate. "
* Separation is cleaner and prevents bloat in the respective repositories. 
* Allows us to create UI only fixes without having to build the backend.
* Cannot revert merge easily.

**Comment by jessesuen** [comment]
We actually went out of our way to keep these things separate. While I understand the overhead of using the correct commits in each repo. I feel the separation is cleaner and prevents bloat in the respective repositories. It also allows us to create UI only fixes without having to build from the backend.

**Comment by alexec** [comment]
I get that. @alexmt wants tests in UI. I think I would be more productive to merge the two repos.
