### ISSUE TITLE
environment-specific

### ISSUE THREAD

**Issue by loveisall1995** [argoproj/argo-cd#14251]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ishitasequeira** [comment]
@loveisall1995 was this created by-mistake? If not, can you add details to this bug?
