### ISSUE TITLE
Filter on Argoappset from main Application UI

### ISSUE THREAD

**Issue by twanbeeren** [argoproj/argo-cd#14285]
# Summary

It would be very helpful to filter on applicationset in my Argo UI. It only shows all my applications now which are hundreds so its hard to navigate my applicationset

# Motivation

It only shows all my applications now which are hundreds so its hard to navigate my applicationset. The applicationset is rolled out part of an application.

# Proposal

I've used labels before but had to manually add the labels to the applications where my applicationset is part of. 

![image](https://github.com/argoproj/argo-cd/assets/36261352/b29bf9a6-592a-4e59-98a4-14d57dd3cd90)
![image](https://github.com/argoproj/argo-cd/assets/36261352/b6f2b233-e9cd-44a4-960c-e53db5965865)

![image](https://github.com/argoproj/argo-cd/assets/36261352/e91905ff-d20f-4111-9f42-0bcd1fd192fd)

On the image above there is an option to filter on Kind: ApplicationSet

but I would prefer to filter on Kind: ApplicationSet from this menu below

![image](https://github.com/argoproj/argo-cd/assets/36261352/c3b74bff-9ac7-4ec9-99e9-ace664eb003b)

**Comment by crenshaw-dev** [comment]
I think this resolves part of your request: https://github.com/argoproj/argo-cd/pull/13456

I believe the rest of the request is covered by this: https://github.com/argoproj/argo-cd/issues/7352

The current plan is to put AppSets in Settings, since they're currently an admin-level feature.

**Comment by ericblackburn** [comment]
> I think this resolves part of your request: #13456
> 
> I believe the rest of the request is covered by this: #7352
> 
> The current plan is to put AppSets in Settings, since they're currently an admin-level feature.

Note #13456 is a blocking bug addition. Let's avoid depending on it pending the outcome of the request to fix it https://github.com/argoproj/argo-cd/issues/15282

Labels based on k8s resource object names is bound to fail because labels have a different character restriction.

**Comment by jgwest** [comment]
Duping to https://github.com/argoproj/argo-cd/issues/7352, as, based on Michael's comment above, that is all that remains for this.
