### ISSUE TITLE
ui error on 'copy logs to clipboard'

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-cd#14309]
![Screen Shot 2023-07-02 at 10 54 35 am](https://github.com/argoproj/argo-cd/assets/33283496/3babb9c2-da94-4077-b6aa-764efece31e0)

version is 2.7.6

error is ```undefined is not an object (evaluating 'e.getData')```

**Comment by crenshaw-dev** [comment]
Can you try in 2.7.7? I believe a fix was pushed.

**Comment by crenshaw-dev** [comment]
Closing for now with the assumption that this was fixed.

**Comment by tooptoop4** [comment]
2.7.7 works
