### ISSUE TITLE
Auth expiry redirects don't respect basehref

### ISSUE THREAD

**Issue by arnarg** [argoproj/argo-cd#1430]
**Describe the bug**
When using the `--basehref` flag to change the uri prefix redirects to the login page on token expiration do not include the prefix.

**To Reproduce**
1. Change basehref to `/argocd/`.
2. Login using SSO.
3. Wait for token to expire.
4. Get redirected to `/auth/login` instead of `/argocd/auth/login`.

**Expected behavior**
Get redirected to `/argocd/auth/login`.

**Additional context**
I've only had it happen with SSO but I think it should happen with the admin user as well.

**Comment by alexec** [comment]
PR merged.
