### ISSUE TITLE
feat: upgrade dexIDP from 2.36.0 -> 2.37.0

### ISSUE THREAD

**Issue by venkatamutyala** [argoproj/argo-cd#14305]
# Summary

It looks like a new version of dexIDP just got released. I think the effort level would be low to have this project updated to the latest version: https://github.com/dexidp/dex/releases/tag/v2.37.0

Currently, argo-cd appears to be running on 2.36.0

# Motivation

There are a lot of dependency version updates in 2.37.0, and I imagine one or more of them would help ensure the argo-cd dex implementation remains patched with the latest security and stability updates.

# Proposal

I think this is as simple as doing a find and replace of: `dex:v2.36.0` to `dex:v2.37.0` and then seeingwhat breaks. (:

**Comment by crenshaw-dev** [comment]
> and then seeingwhat breaks.

I like the way you think.  😁

Yep, let's do this. We should cherry-pick the upgrade back to all currently-supported Argo CD versions.

**Comment by venkatamutyala** [comment]
@crenshaw-dev I created a PR here: https://github.com/argoproj/argo-cd/pull/14310 . I'm unclear on how to do this for all versions. Does the cherry-pick-bot do it automatically or do I need to do something on my end?

**Comment by crenshaw-dev** [comment]
The cherry pick bot generally does all the work. It'll comment on the PR if it fails.

**Comment by venkatamutyala** [comment]
I _think i did this right_. Please let me know if you need any additional changes.

**Comment by venkatamutyala** [comment]
@crenshaw-dev I'm closing this out since releases the recent releases include these changes.
