### ISSUE TITLE
Display health of applications that are part of other apps

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1433]
**Is your feature request related to a problem? Please describe.**

When you create an app-of-apps, the health of the child apps are not displayed in the view of the parent app. 

**Describe the solution you'd like**

Health should be displayed.

**Describe alternatives you've considered**

Do nothing.

**Additional context**

Nope.

**Comment by alexmt** [comment]
This can be implemented using custom health check for `argoproj.io/Application` CRD
