### ISSUE TITLE
Bump #9678

### ISSUE THREAD

**Issue by asaf400** [argoproj/argo-cd#14335]
https://github.com/argoproj/argo-cd/issues/9678

The issue has been open for more then a year now, with no end in-sight.
It's a CORE FEATURE of ArgoCD which is malfunctioning in a spectacular fashion,
an array? that's what creates this issue!

Frankly it makes ArgoCD looks like it's still on v0.9.
furthermore, the issue is NOT documented on the docs site where a new user might be able to steer clear of the issue:
https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/
https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs

While it's off course easy to type and criticize, 
I am sorry that I'm not a golang developer, and so my ability to jump into ArgoCD issues is limited, so is my time..

**Comment by crenshaw-dev** [comment]
Frustration heard and understood. tbh this issue wasn't on my radar, so I appreciate the bump. I'll close this now and focus on the existing issue. Thanks!
