### ISSUE TITLE
Badges for build status

### ISSUE THREAD

**Issue by shrivardhan92** [argoproj/argo-cd#1435]
**Is your feature request related to a problem? Please describe.**
Need to display build status of a project as a badge or as a tag 

**Describe the solution you'd like**
Would like to have Jenkins like endpoint to access build status. Essentially an Argo CD endpoint like `https://build.xyz.com/buildStatus?job=<job-name>`

**Describe alternatives you've considered**
Alternatively I could work with a solution that makes use of the underlying Jenkins to get the job status. 

Example: [Jenkins Badge](http://i.ytimg.com/vi/clQEdNdOBm0/hqdefault.jpg)

**Comment by alexec** [comment]
do you mean sync status (are we out of sync with Git?), sync operation status (did the last sync work) or health (is my app working)?

**Comment by simster7** [comment]
You can currently get the application status with the following API `/api/v1/applications/{name}`. It should contain all the information above and more: https://github.com/argoproj/argo-cd/blob/1c6bb4386f18362df23ec3c71c799587eae7fae4/pkg/apis/application/v1alpha1/types.go#L217-L229

Would this suffice as a "tag" or are you requesting embeddable badges specifically? @alexmt Could you share what the desired enhancement here is?

**Comment by alexec** [comment]
Something like this @simster7 ?

https://www.youtube.com/watch?v=clQEdNdOBm0

**Comment by alexec** [comment]
Fixed in #1812. Well done @naynasiddharth!
