### ISSUE TITLE
Improve SLSA verification command in the docs

### ISSUE THREAD

**Issue by laurentsimon** [argoproj/argo-cd#14431]
The documentation https://argo-cd.readthedocs.io/en/stable/operator-manual/signed-release-assets/ shows how to verify the releases of argo-cd. The example commands using cosign https://argo-cd.readthedocs.io/en/stable/operator-manual/signed-release-assets/#verification-of-container-image-attestations don't properly verify the source repository of the build, and only verify the builder.

I would like to send a PR to improve the examples, as well as provide examples using slsa-verifier (already mentioned in the docs but does not have verification commands).

Thank you!

**Comment by crenshaw-dev** [comment]
I'd definitely welcome a PR!

**Comment by laurentsimon** [comment]
See https://github.com/argoproj/argo-cd/pull/14437
