### ISSUE TITLE
argocd-cm old-style plugins fail on v2.7.7

### ISSUE THREAD

**Issue by Velyks** [argoproj/argo-cd#14432]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Trying to use any plugins defined in the old-style way in argocd-cm fails with an "unable to find plugin" error.

**To Reproduce**

Define a custom plugin in the old argocd-cm style (built/mounted into argocd image) and attempt to use it in an application in ArgoCD v2.7.7

**Expected behavior**

The plugin runs and generates some resources

**Screenshots**

**Version**
Sorry, can't get argocd cli to connect as its a test instance networked stupidly.

```json
{
    "Version": "v2.7.7+4650bb2.dirty",
    "BuildDate": "2023-07-05T19:42:32Z",
    "GitCommit": "4650bb2817c3c81405f40cf77e93ef2b5fb275fb",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
time="2023-07-10T15:51:41Z" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = failed to populate plugin app details: failed to detect CMP for app: couldn't find cmp-server plugin with name argocd-deploy supporting the given repository" grpc.code=Unknown grpc.method=GetAppDetails grpc.service=repository.RepositoryService grpc.start_time="2023-07-10T15:51:41Z" grpc.time_ms=391.89 span.kind=server system=grpc
```

**Comment by crenshaw-dev** [comment]
I think this only affects the Parameters tab in the UI. Otherwise, the plugin should work fine.

**Comment by jgwest** [comment]
Fixed by linked PR
