### ISSUE TITLE
argo ignores sync-wave

### ISSUE THREAD

**Issue by SnoozeFreddo** [argoproj/argo-cd#14442]
I have two apps deployed with argo v2.7.6

One of them uses the rabbitmq operator:

> 
> apiVersion: rabbitmq.com/v1beta1
> kind: RabbitmqCluster
> metadata:
>     name: rabbit
>     annotations:
>       argocd.argoproj.io/sync-wave: "-1"
> spec:
>   replicas: 1
>   override:
>     statefulSet:
>       spec:
>         template:
>           metadata:
>             annotations:
>               argocd.argoproj.io/sync-wave: "-1"

 Therefore the pod has the label sync-wave -1 and the STS as well. A second pod is not annotated and the expected behavior is to have a argoproc.sync-wave value of 0. 

However while my rabbitmq STS and Pod are still not in the healthy state but rather have the spinning loading wheel, argocd already starts deploying the app with the value of 0.

What am i doing wrong?

**Comment by christianh814** [comment]
Syncwaves are dependent on health checks. It [doesn't look like RabbitmqCluster have health checks defined](https://github.com/argoproj/argo-cd/tree/master/resource_customizations)

Have you created a [custom health check](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#custom-health-checks)?

**Comment by SnoozeFreddo** [comment]
Hello and thank you. 

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
```
The sync wave is on the statefull set. That means argocd won't look into the created resources by the CDR, right? 


That's the Rabbit CDR
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
```
therefore i should patch argocd like that:

```

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.customizations: |
    rabbitmq.com/v1beta1/RabbitmqCluster:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
```

Sadly it didn't work out of the box, which means i gotta learn lua, right? 

Another question arised:

My CDR rabbitmq.com/v1beta1/RabbitmqCluster immediately transits to the state healthy. Does that mean the sync wave won't notice that the RabbitMQ STS ain't ready yet?

**Comment by alexymantha** [comment]
> Does that mean the sync wave won't notice that the RabbitMQ STS ain't ready yet?
Yes. Since the sync waves depend on the health checks, if your resource shows up as healthy the next wave will proceed.
