### ISSUE TITLE
dex CrashLoopBackOff - /shared/argocd-dex: no such file or directory

### ISSUE THREAD

**Issue by HSoulat** [argoproj/argo-cd#14452]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Argocd DEX pod crash due to missing file / directory. 
`Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/shared/argocd-dex": stat /shared/argocd-dex: no such file or directory: unknown`

**To Reproduce**

argocd-dex-server include an empty-dir volume. 
```
      volumes:
      - emptyDir: {}
        name: static-files
```

**Expected behavior**

file or directory should exist, or usage should be removed from argocd-dex-server deployment.

**Version**

```
argocd-server: v2.6.12+52497ce
  BuildDate: 2023-07-05T19:43:11Z
  GitCommit: 52497ce0fb35a637f0de2f373c708be9affbae0a
  GitTreeState: clean
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Comment by Angelin01** [comment]
If you are using the Helm Chart, this PR may help you: https://github.com/argoproj/argo-helm/pull/2161

In our case, the init container that copies the `/shared/argocd-dex` file was being killed. Increasing the resources for the copy util to about 144Mi was enough to stop crashes consistently.

**Comment by HSoulat** [comment]
I'm deploying argocd with [install-ha](https://github.com/argoproj/argo-cd/blob/master/manifests/ha/install.yaml) manifest. I've not found any cpu/memory boundaries in.
