### ISSUE TITLE
Argocd exeption after upgrade

### ISSUE THREAD

**Issue by yuvalsc** [argoproj/argo-cd#14571]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
Closing for lack of details. Edit and then tag me, and I'll reopen.
