### ISSUE TITLE
ArgoCD Horizontal Scrollbar only available once bottom of screen reached.

### ISSUE THREAD

**Issue by reefland** [argoproj/argo-cd#14588]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

The horizontal scrollbar is not available in Firefox until you reach the very bottom of the screen.

Previous closed issue #8298 describes this happening before.

**To Reproduce**

1. Open a large application with ArgoCD UI
2. There will not be horizontal scrollbar available
3. The vertical scrollbar cannot be used to get down to the bottom of screen
4. Have to use mouse scroll wheel to get to the bottom for horizontal scrollbar to be available
5. Then use vertical scroll bar again to go back up to see what you are looking for
6. Horizontal scrollbar remains available

If you select a different application, the horizontal scrollbar is gone and have to use the steps above to get it back.

**Expected behavior**

Expect a horizontal scroll be to be available, whenever the application does not fit within the current window size.

**Screenshots**

No horizontal scrollbar available:
![image](https://github.com/argoproj/argo-cd/assets/16230914/75f55892-f7d5-4702-b6af-2a6aa2a0d626)

Cannot use vertical scrollbar, this is as far as it will go:
![image](https://github.com/argoproj/argo-cd/assets/16230914/52241d0d-8dd1-4414-ad73-9303df99d421)

Use mouse scroll wheel to reach the bottom, now I have scroll bar:
![image](https://github.com/argoproj/argo-cd/assets/16230914/1696e167-5533-4aef-8598-96632a17aaad)

**Version**

```shell
argocd-server: v2.7.7+4650bb2.dirty
  BuildDate: 2023-07-05T19:42:32Z
  GitCommit: 4650bb2817c3c81405f40cf77e93ef2b5fb275fb
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

Firefox:  115.0.2 (64-bit), Manjaro KDE.

**Comment by jgwest** [comment]
Tested and it appears resolved, and likewise the linked PR claims it has been fixed.
