### ISSUE TITLE
"argocd admin export" only exports ArgoCD apps from the same namespace as where ArgoCD is deployed

### ISSUE THREAD

**Issue by krikeri** [argoproj/argo-cd#14596]
Hello all,

I tried to do a backup of ArgoCD using the "argocd admin export" command as described in the document: https://argo-cd.readthedocs.io/en/stable/operator-manual/disaster_recovery/

I was able to run the backup successfully but I noticed that the backup file only contained ArgoCD apps that were deployed in the same namespace as where ArgoCD is deployed.

Does the command "argocd admin export" also support exporting ArgoCD apps from other/all namespaces https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/?

Thank you in advance!

**Comment by mars-esther** [comment]
i am also facing the same issue . Can someone please help on this

**Comment by ilia-medvedev-codefresh** [comment]
Will take a shot at it in the next couple of days
