### ISSUE TITLE
Sync Qs

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-cd#1461]
I'm evaluating  Argo-cd and wonder:

How is the sync diff handling performed,  if I use several Helm value files and 1 helm chart. Each app specifies the value file to be used. Is the diff based on value file and chart vs k8s deployments for each app?

Why is synced hash visible for repo updates which is not impacting the deployment (ex other files like source code)

**Comment by alexec** [comment]
hi @emichaf, 

Are you mixing your app source code (e.g. Java or Node files) with your deployment scripts?

**Comment by emichaf** [comment]
Yes, mixing source cod with k8s manifest files in the same repo!

**Comment by alexec** [comment]
Though so! We recommend you have one repo for source and one for the deployment configuration. I could go into detail, but it was documented, so here's the link:

https://argoproj.github.io/argo-cd/user-guide/best_practices/#separating-config-vs-source-code-repositories

Diff is actually based on the manifests generated by the tool. Kustomize, Helm, etc all just generate manifests based on the input files. I don't have docs for how this works (sorry).

**Comment by emichaf** [comment]
Ok, thnx!

**Comment by emichaf** [comment]
Hi @alexec, is it possible to sync changes via Helm charts in HELM repository like Chart museum or Artifactory or similar, ie. not only GIT repo ?

**Comment by alexec** [comment]
Not yet. First-class Helm support is targeted for 1.2

**Comment by alexec** [comment]
I think Q is answered. I maybe wrong. Please re-open if I am.
