### ISSUE TITLE
Incorrect Kubernetes metadata shown about applications

### ISSUE THREAD

**Issue by lindhe** [argoproj/argo-cd#14622]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The Argo CD UI displays incorrect information. It seems to think that my application `foo` has the labels and annotations of another application (see screenshots below). This is, however, not the case in reality. If I inspect the deployed resources using `kubectl`, I see that they have the intended labels.

**To Reproduce**

1. Install an application `foo`
2. Install Argo CD itself as the application `argocd`
3. That's it, I think.

**Expected behavior**

I expect the UI to show me the same information as Kubernetes knows about.

**Screenshots**

<img width="448" alt="Screenshot 2023-07-20 172831" src="https://github.com/argoproj/argo-cd/assets/7773090/1bac7ea2-5975-41bf-8312-f3cf63b2143a">

<img width="665" alt="Screenshot 2023-07-20 173758" src="https://github.com/argoproj/argo-cd/assets/7773090/3796a7b8-9d55-4fec-b915-98f786453a0e">

**Version**

```
argocd: v2.7.7+4650bb2
  BuildDate: 2023-07-05T20:02:35Z
  GitCommit: 4650bb2817c3c81405f40cf77e93ef2b5fb275fb
  GitTreeState: clean
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.7.7+4650bb2.dirty
  BuildDate: 2023-07-05T19:42:32Z
  GitCommit: 4650bb2817c3c81405f40cf77e93ef2b5fb275fb
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

I'm not familiar enough yet with Argo to know which logs are relevant. Point me in the right direction and I'll try to help.

**Comment by crenshaw-dev** [comment]
> the labels and annotations of another application

I'm not sure what you mean by this. Looking at that annotation, I see that the metadata.name ("foo") matches the app's name. What did you expect to see instead?

**Comment by lindhe** [comment]
It's particularly the labels `app.kubernetes.io/instance=argocd`, `app.kubernetes.io/managed-by=argocd` and `app.kubernetes.io/version=2.7.7` that  bothers me. Those are the labels I've set for my application `argocd`, not for `foo`.

And the `kubectl.kubernetes.io/last-applied-configuration` also shows what's clearly the `argocd` applications's last applied configuration, not `foo`'s.

**Comment by lindhe** [comment]
I tried upgrading to `2.7.8` and it seems to have the same behavior.

**Comment by lindhe** [comment]
Alright, I'm clearly the idiot here. I was thinking that "App details" would show me details about the _resources_ I've defined in my application. That's obviously not the case. It's showing me details about the `Application` resource. 🤦 

_NEVER MIND ME._ I'm closing this. Thanks for replying anyway. 🙃

**Comment by crenshaw-dev** [comment]
No worries! Feel free to reopen if you wanna describe UI changes which would things more clear. :-)
