### ISSUE TITLE
Application Details Page.

### ISSUE THREAD

**Issue by eslam-adel92** [argoproj/argo-cd#14697]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
v2.8.0+dea3848.dirty
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by blakepettersson** [comment]
Unless you have any details about whatever issue you're having, I'll close this issue
