### ISSUE TITLE
Health icon is too low

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#14708]
**Describe the bug**

The green hearth is too low and doesn't align well with the adjacent text.

![image](https://github.com/argoproj/argo-cd/assets/350466/676637ed-2fc6-432e-88f8-247ea8aab9d2)

**Version**

2.7.6

**Comment by ashinsabu3** [comment]
@crenshaw-dev Let me know if this fix is good enough. https://github.com/argoproj/argo-cd/pull/14852
The positioning seems fine now and I've added a screenshot too.
