### ISSUE TITLE
Automatically detect applications in a repository and create/sync them

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1470]
**Is your feature request related to a problem? Please describe.**

I'd like to be a be able to get a large number of applications installed quickly.

**Describe the solution you'd like**

The idea here is to bootstrap a cluster from a single repository. A controller automatically detects applications within a repository, along with any configuration needed, and automatically creates and syncs them.

**Describe alternatives you've considered**

You can create an app-of-apps, i.e. an app that simply describes other apps, but does not appear to be incredibly portable. It would be good to review this approach. 

**Additional context**

Nope.

**Comment by alexmt** [comment]
Similar idea is described here: https://github.com/argoproj/argo-cd/issues/1431 

I would be nice to have CRD which uses argocd-repo api and creates applications CRDs

**Comment by alexec** [comment]
See #1766
