### ISSUE TITLE
RBAC valid but login shown blank page without applications

### ISSUE THREAD

**Issue by vanlongme** [argoproj/argo-cd#14717]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

- I have set valid rbac policy:
```yaml
  p, role:appops, applications, get, *, allowx
  p, role:appops, applications, update, *, allow
  p, role:appops, applications, action/*, *, allow
  p, role:appops, clusters, get, *, allow
  p, role:appops, projects, get, *, allow
  p, role:appops, applicationsets, get, *, allow
  p, role:appops, repositories, get, *, allow
  p, role:appops, certificates, get, *, allow
  p, role:appops, accounts, get, *, allow
  p, role:appops, gpgkeys, get, *, allow
  p, role:appops, logs, get, */*, allow
  p, role:appops, exec, create, */*, allow
  g, userx, role:apo
policy.default: ''
```
But after userx logged into argocd, no application appear, but still see Projects, Repositories, Account,....
After change: "policy.default" value to "role:readonly" that work as expected
**To Reproduce**
- Set **argocd-rbac-cm** value to same above

**Expected behavior**

- RBAC working without need to set fallback "policy.default" value, users that have assigned to role can have enough permissions. Users without any role assigned still able to login but did not see anything

**Screenshots**

- Application did not show:
![image](https://github.com/argoproj/argo-cd/assets/30171328/38cf54b2-bdbb-4465-8df7-402f32b8a375)
- Other resource that allow from policies attach still can see:
![image](https://github.com/argoproj/argo-cd/assets/30171328/df03e5da-1640-4263-bcdc-01c90ab42af8)
- After change default.policy to "role:readonly", application shown:
![image](https://github.com/argoproj/argo-cd/assets/30171328/6cf3bb37-5433-40a8-8037-06ba86186798)

**Version**

```shell
argocd: v2.7.4+a33baa3.dirty
  BuildDate: 2023-06-05T23:26:55Z
  GitCommit: a33baa301fe61b899dc8bbad9e554efbc77e0991
  GitTreeState: dirty
  GoVersion: go1.20.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.7.9+0ee33e5.dirty
  BuildDate: 2023-07-24T17:42:11Z
  GitCommit: 0ee33e52dd1f1bb944488584fc6f854b929f1180
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Comment by KevinBonilla** [comment]
Looks like I'm running into this issue as well, for a few weeks now I've been trying to understand why my setup (Dex, Azure SSO) was acting inconsistent. I've created some test scenarios and validated that certain group policies don't work with some AD groups and I have no idea why.

rbac policy:
```
    policy.csv: |
      p, role:dev, applications, get, dev-project/*, allow 
      p, role:dev, applications, sync, dev-project/*, allow
      p, role:dev, logs, get, dev-project/*, allow
      p, role:sysops, applications, get, */*, allow
      p, role:sysops, applications, delete, *, allow
      p, role:sysops, applications, sync, */*, allow
      p, role:sysops, logs, get, */*, allow
      p, role:sysops, repositories, get, */*, allow
      p, role:sysops, projects, get, */*, allow
      p, role:sysops, clusters, get, */*, allow      
      p, role:qa, applications, get, */*, allow
      p, role:qa, applications, sync, */*, allow
      p, role:qa, logs, get, */*, allow
      g, QA, role:qa
      g, SysOps, role:readwritesync
      g, DevOps, role:admin
      g, Software Development, role: dev
```

Since I'm apart of the DevOps group by default I inherit the admin policy which works fine. What did not work or was inconsistent was the roles `dev` and `sysops` For my testing I removed my AD group `DevOps` and created a test AD group called `Argo-testing`. 

Test 1:
- Remove DevOps from admin policy
- For the AD group `SysOps`, replace with `Argo-testing` ad group for testing. See if we still see applications
	- Result: we see the applications. Works.

Test 2: 
- Remove DevOps from admin policy
- For the AD group `Software Development`, replace with `Argo-testing` for testing. See if we only see dev apps.
	- Result: we don't see the dev apps
	- Weird result because a group member verified this policy works, he was able to see dev project applications
	
Test 3: 
- Adding policy.default 'role:readonly'
- Remove DevOps from admin policy
- Retest Test 2:
	- Result: Applies default readonly policy. Subject unable to see desired policy.

Version: Currently using a build off @mmerrill3's work using kubelogin. (Works great btw). https://github.com/argoproj/argo-cd/pull/10700
```
{
    "Version": "v2.8.0+7e9b206.dirty",
    "BuildDate": "2023-06-19T14:18:03Z",
    "GitCommit": "7e9b206b6ad33c20be072092de96732fd47e7658",
    "GitTreeState": "dirty",
    "GoVersion": "go1.20.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.12.0+gc9f554d",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

**Comment by crenshaw-dev** [comment]
@vanlongme at a glance, I see a couple potential issues.

```csv
p, role:sysops, projects, get, */*, allow
```

Projects never have `/` in them. I think you want just `*` instead of `*/*.

```csv
g, Software Development, role: dev
```

There's a stray space before `dev`.

**Comment by KevinBonilla** [comment]
> @vanlongme at a glance, I see a couple potential issues.
> 
> ```
> p, role:sysops, projects, get, */*, allow
> ```
> 
> Projects never have `/` in them. I think you want just `*` instead of `_/_.
> 
> ```
> g, Software Development, role: dev
> ```
> 
> There's a stray space before `dev`.

Think you meant to tag me :)

Thanks for catching that stray space in `dev`. That seems to have resolved my issue with the `dev` AD group. Didn't even catch that smh.

After fixing the issue with my `project` policy for role: sysops it looks like it resolved my issue with sysops. Thank you @crenshaw-dev !

@vanlongme after reviewing your rbac policy I see your `g` is looking for role: `apo`
```
g, userx, role:apo
```
But the policy you have been referring to is `appops`. So it should be: 
```
g, userx, role:appops
```

**Comment by jgwest** [comment]
Resolved based on issue comments.
