### ISSUE TITLE
Failed to watch *v1.Secret , Failed to watch *v1.ConfigMap , 

### ISSUE THREAD

**Issue by Qasim-Aziz** [argoproj/argo-cd#14722]
hello i am using argocd from many years. but found issue when i reinstall argocd on same cluster. 

digital ocean kubernetes 1.24.12 version kubernetes . argocd 2.7.7 

facing issue on arogcd server in crash loop with error 

`Trace[45630876]: ---"Objects listed" error:the server was unable to return a response in the time allotted, but may still be processing the request (get secrets) 60004ms (11:37:10.817)
Trace[45630876]: [1m0.004189781s] [1m0.004189781s] END
E0726 11:37:10.817955       8 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: the server was unable to return a response in the time allotted, but may still be processing the request (get secrets)
W0726 11:37:17.405515       8 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1.ConfigMap: the server was unable to return a response in the time allotted, but may still be processing the request (get configmaps)
I0726 11:37:17.405591       8 trace.go:205] Trace[358820169]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167 (26-Jul-2023 11:36:17.399) (total time: 60005ms):
Trace[358820169]: ---"Objects listed" error:the server was unable to return a response in the time allotted, but may still be processing the request (get configmaps) 60005ms (11:37:17.405)
Trace[358820169]: [1m0.005825771s] [1m0.005825771s] END
E0726 11:37:17.405878       8 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: the server was unable to return a response in the time allotted, but may still be processing the request (get configmaps)
W0726 11:39:08.581638       8 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1.Secret: the server was unable to return a response in the time allotted, but may still be processing the request (get secrets)
I0726 11:39:08.581728       8 trace.go:205] Trace[1583310708]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167 (26-Jul-2023 11:38:08.576) (total time: 60005ms):
Trace[1583310708]: ---"Objects listed" error:the server was unable to return a response in the time allotted, but may still be processing the request (get secrets) 60005ms (11:39:08.581)
Trace[1583310708]: [1m0.00546145s] [1m0.00546145s] END
E0726 11:39:08.581745       8 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: the server was unable to return a response in the time allotted, but may still be processing the request (get secrets)
W0726 11:39:08.651648       8 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1.ConfigMap: the server was unable to return a response in the time allotted, but may still be processing the request (get configmaps)
I0726 11:39:08.651723       8 trace.go:205] Trace[714795827]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167 (26-Jul-2023 11:38:08.647) (total time: 60004ms):
`

also on argocd-application-controller-0 error 

`E0726 11:47:29.359093       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: the server was unable to return a response in the time allotted, but may still be processing the request (get secrets)
W0726 11:47:30.694020       7 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1.ConfigMap: the server was unable to return a response in the time allotted, but may still be processing the request (get configmaps)
I0726 11:47:30.694080       7 trace.go:205] Trace[2073389167]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167 (26-Jul-2023 11:46:30.690) (total time: 60003ms):
Trace[2073389167]: ---"Objects listed" error:the server was unable to return a response in the time allotted, but may still be processing the request (get configmaps) 60003ms (11:47:30.694)
Trace[2073389167]: [1m0.003355723s] [1m0.003355723s] END
E0726 11:47:30.694100       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: the server was unable to return a response in the time allotted, but may still be processing the request (get configmaps)
W0726 11:48:43.219086       7 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1alpha1.Application: the server was unable to return a response in the time allotted, but may still be processing the request (get applications.argoproj.io)
I0726 11:48:43.219461       7 trace.go:205] Trace[1905142951]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167 (26-Jul-2023 11:47:43.215) (total time: 60003ms):
Trace[1905142951]: ---"Objects listed" error:the server was unable to return a response in the time allotted, but may still be processing the request (get applications.argoproj.io) 60003ms (11:48:43.219)
Trace[1905142951]: [1m0.003617065s] [1m0.003617065s] END
E0726 11:48:43.219584       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Application: failed to list *v1alpha1.Application: the server was unable to return a response in the time allotted, but may still be processing the request (get applications.argoproj.io)
W0726 11:48:43.931689       7 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1.Secret: the server was unable to return a response in the time allotted, but may still be processing the request (get secrets)
I0726 11:48:43.931768       7 trace.go:205] Trace[1090891264]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167 (26-Jul-2023 11:47:43.927) (total time: 60004ms):
Trace[1090891264]: ---"Objects listed" error:the server was unable to return a response in the time allotted, but may still be processing the request (get secrets) 60004ms (11:48:43.931)
Trace[1090891264]: [1m0.004144078s] [1m0.004144078s] END
E0726 11:48:43.931788       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: the server was unable to return a response in the time allotted, but may still be processing the request (get secrets)
`

**Comment by Qasim-Aziz** [comment]
any help appreciated @gpaul @farcaller @telmich @pacoguzman

**Comment by farcaller** [comment]
Is your apiserver overloaded with too many objects to track? Do you get a similar issue while listing secrets with kubectl?

**Comment by Qasim-Aziz** [comment]
with basic setup i have deployed approx 19 micro services . with kubectl get secrets i am able to get secrets. there is no issue. 

my this setup approx running from last 2 years. but suddenly argo server failing with this issue and i just uninstall argocd and deployed again but same issue still there . i am also worry about my prod cluster but on prod till now it seems fine. !

**Comment by Qasim-Aziz** [comment]
! issue fixed, this issue was related to kubenetes version i have upgraded to 1.24.12 to 1.24.16 and issue fixed , 

closing comment @farcaller thanks you to point me on issue !
