### ISSUE TITLE
FATA[0000] stream read failed: rpc error: code = NotFound desc = cluster "https//kubernetes.default.svc" not found after creating argocd application from yaml file

### ISSUE THREAD

**Issue by anthonyoride** [argoproj/argo-cd#14752]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Hi, i have noticed that whenever i create a new argocd application using yaml file, it fails to sync with my git repo and i always get the error below:

FATA[0000] stream read failed: rpc error: code = NotFound desc = cluster "https//kubernetes.default.svc" not found.

How everything works fine when i create an argocd application from the UI. 

**To Reproduce**

workflow.yml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akumfb-backend-wc
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  ****
    targetRevision: HEAD
    path: akumfb-backend/overlays/dev
  destination:
    server: https//kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

**Expected behavior**

application should sync with git repository.

Any help will be appreciated. Thanks

**Comment by crenshaw-dev** [comment]
Looks like you're missing a colon in the server URL:

```diff
- server: https//kubernetes.default.svc
+ server: https://kubernetes.default.svc
```

**Comment by anthonyoride** [comment]
Yeah that was the issue. its working perfectly now. crazy how i didn't spot it. how silly of me. thanks alot i really appreciate

**Comment by crenshaw-dev** [comment]
Helps to have extra eyes. You bet!
