### ISSUE TITLE
argocd console does not show the argocd application with same name in different namespaces.

### ISSUE THREAD

**Issue by aparnavodapalli** [argoproj/argo-cd#14766]
Hi,

I am using argocd version 2.6.13 and I have argocd application apps in different namespaces.
And in argocd console visualization it does not render the application correctly. It shows the application correctly first and immediately switches to application in argocd namespace

Regards,
Aparna

**Comment by jannfis** [comment]
Can't reproduce this issue with a recent build. It might have been fixed meanwhile.
