### ISSUE TITLE
Investigate what users might want for 1st class notifications

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1480]
Try and find out what people want/need when events (e.g. out-of-sync or sync failure) happen with Argo CD (e.g. Slack message, Github comment)

**Comment by dbachrach** [comment]
There is a small lag time between when we merge a PR into our cluster repo and when argo has fully rolled out the change and all health checks are live. It would be useful to get a slack notification that a sync is complete (even better if it can reference the commit name of what was just rolled out).

**Comment by alexec** [comment]
See also:

* https://github.com/argoproj/argo-cd/issues/879
* https://github.com/argoproj/argo-cd/issues/1091

**Comment by alexec** [comment]
Also, in Argo Workflows, email/Slack integration:

* https://github.com/argoproj/argo/issues/298

**Comment by alexec** [comment]
Existing event based mechanisms:

* https://blog.powerupcloud.com/kubernetes-event-notifications-to-a-slack-channel-part-v-a9634b39db8f
* https://github.com/wongnai/kube-slack

**Comment by alexec** [comment]
One questions in what type of message you want?

* Slack
* Email (which can proxy to other services e.g. PageDuty)
* Github Status

Another question, who is the recipient?

* Channel
* Individual
* The commit author

**Comment by jselleck** [comment]
I echo Argo workflow call - make this easy.
nats publisher - with ability to set connection info and subject.

Notification content with a message template and variable (go template?) placeholders would be nice.

**Comment by alexec** [comment]
I’m not familiar with NATS. Does it support things like Slack out of the box?

**Comment by jselleck** [comment]
Nats is a k8s native messaging service - somewhat like rabbit mq.  https://nats.io/  It’s integral to the Argo events implementation.  With a notification one could fire off an event and workflow or pickup the notification by a subscriber for additional processing.

**Comment by jselleck** [comment]
You could potentially send all notifications to nats and build subscriber notifiers for all platforms needing support....   that would limit your notify code to one format.

**Comment by alexec** [comment]
Is there a way to publish select K8S events to NATS, and then another app that would subscribe to those events and send them as messages to Slack?

Is it possible to simply document the set-up I wonder?

**Comment by jselleck** [comment]
I suppose you could use Argo events to watch for those and have it trigger Argo workflow for sending to slack.

**Comment by alexec** [comment]
@sarabala1979 has been working on a generic solution for this. I'll close this now.

**Comment by alexec** [comment]
https://github.com/argoproj-labs/argo-kube-notifier

**Comment by alexmt** [comment]
https://argoproj-labs.github.io/argocd-notifications/
