### ISSUE TITLE
argocd diff <app> shows no diff after adding labels or annotations to live manifest manually.

### ISSUE THREAD

**Issue by SamirMarin** [argoproj/argo-cd#14838]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Argocd does not show the application as out of sync when I manually edit the live manifest. I've seeing this issue happen when I edit annotations or labels, adding new labels or annotations. After making the changes to the live manifest, I can see that it has been updated with my edits, when I look at the desired manifest I can also see that the edits are not there. However, when I look at the diff tab, ArgoCD does not show any diff, even though live manifest and desired manifest are different (I've attached images for reference).

I notice the exact same behaviour when I run the command from the command line

```
argocd app diff <argocd_app> --grpc-web
```

even though the live manifest and and desired manifest are different there is no diff outputted

**To Reproduce**
Deploying the argocd application via an applicationset using git generator

```
...
spec:
  generators:
  - git:
      files:
      - path: apps/nats/dev/dev/config.yaml
      repoURL: https://github.com/1047games/gitops-repo
      revision: HEAD
...
```

**Expected behavior**

I would expect to see a diff showing the addition of labels or annotations to the resource.

**Screenshots**

<img width="709" alt="Screen Shot 2023-07-31 at 10 28 51 PM" src="https://github.com/argoproj/argo-cd/assets/7634552/1230d1d7-2f3e-4bae-bbe8-4fb0f13b73e0">

<img width="725" alt="Screen Shot 2023-07-31 at 10 29 05 PM" src="https://github.com/argoproj/argo-cd/assets/7634552/6cfd9a26-0c54-47b5-929f-b6b0fc6be163">

<img width="1115" alt="Screen Shot 2023-07-31 at 10 29 31 PM" src="https://github.com/argoproj/argo-cd/assets/7634552/fba254a5-82ee-4f4a-ad37-cb46558fde6c">

**Version**

```shell
argocd: v2.7.3+e7891b8.dirty
  BuildDate: 2023-05-24T15:49:47Z
  GitCommit: e7891b899a35dca06ae94965ea5ae2a86b344848
  GitTreeState: dirty
  GoVersion: go1.20.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.7.9+0ee33e5.dirty
  BuildDate: 2023-07-24T17:42:11Z
  GitCommit: 0ee33e52dd1f1bb944488584fc6f854b929f1180
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Comment by agaudreault-jive** [comment]
I am pretty sure this is expected. ArgoCD will merge the desired state and the actual Kubernetes manifest. So your manifest running in the cluster can have more fields than what is defined in Argo. This is necessary for k8s operators, object mutation, etc.

If there are some fields you explicitly don't want to be set, I think you can set them to either `null` or `{}` in your git state (to validate). For annotations and labels. it is likely, not possible since Argo itself needs to add values.

**Comment by SamirMarin** [comment]
> I am pretty sure this is expected. ArgoCD will merge the desired state and the actual Kubernetes manifest. So your manifest running in the cluster can have more fields than what is defined in Argo. This is necessary for k8s operators, object mutation, etc.
> 
> If there are some fields you explicitly don't want to be set, I think you can set them to either `null` or `{}` in your git state (to validate). For annotations and labels. it is likely, not possible since Argo itself needs to add values.

Ah, I see. So, the idea is that Argo CD, due to its operational requirements, needs to be able to add values to labels and annotations. Hence, if it were to show diffs for these values, especially ones it adds itself, it could potentially lead to a lot of unnecessary diff noise? If this is the case, I understand the current behavior and it does make sense. Thanks for your explanation. We can consider this issue resolved and close this ticket.

**Comment by SamirMarin** [comment]
@agaudreault-jive following up, I understand this expected behaviour, but I'm curious why we don't attempt to differentiate between edits made directly either with kubeclt edit or directly on argo gui and those made by k8s operators, object mutation etc? That way argo would still show the diff/out of sync for the manual edits made by kubectl edit or directly on argo gui? Is this just no possible to do? or it would be to complicated to handle and differentiate?

**Comment by agaudreault-jive** [comment]
I think it might be possible to only consider updated fields by some manager configured globally. 

And the users could configure ignoreDifferences on their applications to negate that effect if required.

I'll reopen the issue as an enhancement because I don't think it's possible with the current configs.

**Comment by SamirMarin** [comment]
> I think it might be possible to only consider updated fields by some manager configured globally.
> 
> And the users could configure ignoreDifferences on their applications to negate that effect if required.
> 
> Can you reopen the issue as an enhancement because I don't think it's possible with the current configs.

@agaudreault-jive that would be great if this is possible as an enhancement. Thanks! I don't think I have the permissions to reopen the issue though, I don't see the reopen button at the bottom.

**Comment by SamirMarin** [comment]
@agaudreault-jive I opened up a new [issue](https://github.com/argoproj/argo-cd/issues/15116) as an enhancement since I was unable to reopen this one
