### ISSUE TITLE
Documenting setting up private repos

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1484]
**Is your feature request related to a problem? Please describe.**

As a user, I struggle to correctly configure private repositories.

**Describe the solution you'd like**

Clear documentation.

**Comment by sungy2014** [comment]
when i try to add private gitlab repo, the argocd-repo-server shows the error below:


time="2019-04-19T13:22:31Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2019-04-19T13:22:29Z" grpc.time_ms=1545.068 span.kind=server system=grpc
