### ISSUE TITLE
hard to view the complete error message on SyncFailed

### ISSUE THREAD

**Issue by stevesea** [argoproj/argo-cd#1486]
**Describe the bug**
On Sync failure, the error message is truncated in the UI. It'd be nice if I could hover over it for the full message, or if it was multi-line text.

in the UI, i see `Warning: kubectl apply should be used on resource created by e...`

As I wrote this issue... I realize when I double-click select all of the text field  and cntrl-C, the entire error message gets added to the clipboard.

The full error message is : Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply The Deployment "pdf-service" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"release":"test-pdf-service", "app":"pdf-service"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

**To Reproduce**
1. attempt to sync a manifest in a way that breaks things... In my case, I was changing selector labels in subsequent manifests

**Expected behavior**
It'd be nice to have a tooltip on hover that showed the full error.

**Screenshots**
![Screen Shot 2019-04-17 at 5 50 40 PM](https://user-images.githubusercontent.com/10570015/56328092-9a864900-613a-11e9-9415-372ad549260d.png)

**Comment by jessesuen** [comment]
workaround i discovered. triple click the message. copy and paste to a text editor.

Also the CLI will not crop the message.

**Comment by alexec** [comment]
This will be fixed in v1.0.03

**Comment by alexec** [comment]
Was not fixed. Working.

**Comment by alexec** [comment]
# Sync Status Small

![sync-status-small](https://user-images.githubusercontent.com/1142830/59649611-26ffb880-9138-11e9-96c1-4c3d5c2f81ad.png)

# Sync Status Large

![sync-status-large](https://user-images.githubusercontent.com/1142830/59649624-30892080-9138-11e9-9f50-40464d59e647.png)

**Comment by alexec** [comment]
@stevesea ☝️

**Comment by stevesea** [comment]
having it in a tooltip looks good. Can the user still triple-click the message to select it and copy into the clipboard?

**Comment by alexec** [comment]
Yes.
