### ISSUE TITLE
Missing ca-file flag when adding private helm oci repository 

### ISSUE THREAD

**Issue by kmakma** [argoproj/argo-cd#14877]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
I have a [Harbor](https://goharbor.io/), which is self-hosted, has a self-signed certificate and neither Harbor nor ArgoCD are connected to the internet. The self-signed certificate is in the argocd-tls-certs-cm.

Trying to connect to a Harbor project helm repository fails with a certificate error. 

The `--ca-file` flag for the `helm registry login` in ArgoCD was removed in #11100 / #11540. 
Since the `--ca-file` flag is now present in helm version v3.12 ([stable helm docs](https://helm.sh/docs/helm/helm_registry_login/)) it should be added back again to Argo CD.

**To Reproduce**

Easiest to replicate in one of the argo pods

Required: self-signed Harbor and the self-signed cert added to the argocd-tls-certs-cm ConfigMap.

The `argocd repo add` fails because of a certificate error with helm:
```
argocd@argocd-server-xyz-xyz:~$ argocd repo add my.registry.com/project --name private-repo --enable-oci --type helm --username user --password pw
Password: 
FATA[0006] rpc error: code = Unknown desc = error testing repository connectivity: `helm registry login my.registry.com/project --username ****** --password ******` failed exit status 1: WARNING: Using --password ****** the CLI is insecure. Use --password-stdin.
time="2023-08-03T06:40:26Z" level=info msg="Error logging in to endpoint, trying next endpoint" error="Get \"https://my.registry.com/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
Error: Get "https://my.registry.com/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
The `helm registry login` to a Harbor project doesn't work without a cert or with the `--insecure` flag
```
argocd@argocd-server-xyz-xyz:~$ helm registry login my.registry.com/project --username user --password pw
INFO[0005] Error logging in to endpoint, trying next endpoint  error="Get \"https://my.registry.com/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
Error: Get "https://my.registry.com/project/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority

argocd@argocd-server-xyz-xyz:~$ helm registry login my.registry.com/project --username user --password pw --insecure
Error: insecure registry my.registry.com/project is not valid: invalid host "my.registry.com/project"
```
And most important it works to the project with the `--ca-file` flag using the mounted self-signed certificate:
```
argocd@argocd-server-xyz-xyz:~$ helm registry login my.registry.com/project --username user --password pw --ca-file /app/config/tls/my.registry.com
Login Succeeded
```
The login also works to Harbor itself without a project and with the `--insecure` flag (`helm registry login my.registry.com --username ... --insecure`)

**Expected behavior**

Argo CD is able to add a repo to a project of a private helm oci registry/Harbor running with self-signed certificates.

**Version**

```shell
argocd: v2.8.0-rc5+eee1a8a
  BuildDate: 2023-07-19T17:34:51Z
  GitCommit: eee1a8add29c0a0f7e7955534ad1963e4c949e14
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.8.0-rc5+eee1a8a
  BuildDate: 2023-07-19T17:34:51Z
  GitCommit: eee1a8add29c0a0f7e7955534ad1963e4c949e14
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

<!-- **Logs**

```
Paste any relevant application logs here.
``` -->

**Comment by fletch3555** [comment]
Adding support for this.  It's the one feature holding me back from fully implementing helm charts.

If there's anything I can do to help this along, please let me know.

**Comment by augeivv** [comment]
We have the same problem or situation here. We also use Harbor in-house with custom certificates.
We are depending on the bug fix here.

**Comment by fletch3555** [comment]
@crenshaw-dev.  Apologies for the direct tag, I'm sure you're quite busy.

Is there anything we can do to help push this along or otherwise prioritize the work for this?  I'm not comfortable enough with Go to have the confidence to make the change (and trust that I did it right), but the code-spelunking that I did do makes it seem like it shouldn't be too difficult of a change to make.  I'm willing to give it a shot if someone can point out any likely "gotchas" or otherwise point me in the right direction.

**Comment by sabre1041** [comment]
@fletch3555 @crenshaw-dev i plan on looking into this issue either this week or next in order to put together a resolution

**Comment by fletch3555** [comment]
@sabre1041 I think it should be as simple as reverting the changes in the PR linked above.  I tried doing so a couple days ago but couldn't get my local environment working to test it.

**Comment by sabre1041** [comment]
@fletch3555 no worries. I have a bunch of development to work on over the holiday period so it will be good to tackle a few issues all at once

**Comment by sabre1041** [comment]
@fletch3555 @kmakma submitted #14877 to not only resolve this issue, but identified missing logic to manage mutual TLS when pulling the chart

**Comment by fletch3555** [comment]
Quick work my good sir!
