### ISSUE TITLE
Implement whitelist option analogous to `resource.exclusions`

### ISSUE THREAD

**Issue by daanemanz** [argoproj/argo-cd#1490]
**Is your feature request related to a problem? Please describe.**
We're using Rancher to proxy requests to our Kubernetes clusters, which means all our Kubernetes operations use a single URL as endpoint. This could easily overwhelm Rancher when ArgoCD tracks child resources of resources that it manages itself (e.g. a secret created by another resource).

**Describe the solution you'd like**
There's an option to exclude resources from being tracked by ArgoCD by using `resource.exlusions` in the `argocd-cm` configmap. This will work well only if you don't have a lot of child resources being created. A "whitelist" option such as `resource.inclusions` would be helpful if you don't know in advance what the child resources will be (or don't care what they are).

**Describe alternatives you've considered**
I've considered listing all resources I don't want to be tracked in `resource.exclusions` but when managing a lot of resources that might be a daunting task.

**Additional context**
It would be extra helpful if there would be an option to only include managed resources _by default_, maybe even with a keyword such as

```
apiVersion: v1
data:
  resource.inclusions: |
    - kinds:
      - managed_only
kind: ConfigMap
```

**Comment by alexec** [comment]
You’ve got a good handle on this issue, have you considered contributing a change?

**Comment by alexmt** [comment]
Done. Thanks yo @simster7
