### ISSUE TITLE
aws eks with alb ingress grpc problem

### ISSUE THREAD

**Issue by Matrix-Zhang** [argoproj/argo-cd#14916]
[as the slack messages ](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1691109441356559)

**Comment by Matrix-Zhang** [comment]
i got in trouble with aws eks alb ingress configuration for HTTP2/GRPC,

I have follow the [Ingress Configuration Docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/) to working on it , but still not work without --grpc-web option (if with, is ok)

argocd-grpc service with annotation "[alb.ingress.kubernetes.io/backend-protocol-version](http://alb.ingress.kubernetes.io/backend-protocol-version)", "HTTP2", the target group is unhealthy

argocd-grpc service with annotation "[alb.ingress.kubernetes.io/backend-protocol-version](http://alb.ingress.kubernetes.io/backend-protocol-version)", "GRPC", the target group is healthy, but still not work correctly

`WARNING: server certificate had error: EOF. Proceed insecurely (y/n)? y`

i'm sure i have issue the certificate for my argocd's domain with AWS ACM service

How to fix that?

**Comment by tyrken** [comment]
Think this can be closed - I worked with the OP on Slack to fix the order of the paths in the ingress spec so the argocd-server-grpc one was first, which did the same in the ALB listener rules.  He then hit a certificate issue but hopefully that's unrelated & fixed (no response since last suggestion).

**Comment by Matrix-Zhang** [comment]
> 

he is me, i was waiting reply here....
