### ISSUE TITLE
how to add private gitlab repo?

### ISSUE THREAD

**Issue by sungy2014** [argoproj/argo-cd#1493]
when i try to add private gitlab repo, the argocd-repo-server shows the error below:

time="2019-04-19T13:14:22Z" level=error msg="finished unary call with code Unknown" error="invalid pkt-len found" grpc.code=Unknown grpc.method=ListDir grpc.service=repository.RepoServerService grpc.start_time="2019-04-19T13:14:22Z" grpc.time_ms=82.741 span.kind=server system=grpc

**Comment by alexec** [comment]
Are you able to provide repo steps please?

**Comment by alexec** [comment]
Try this new guide: v]https://argoproj.github.io/argo-cd/user-guide/private-repositories/

**Comment by sungy2014** [comment]
problem solved
thanks for the new guide
