### ISSUE TITLE
auto prune not working for normal sync

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-cd#14951]
in my app yaml i have
syncPolicy:
  automated:
    prune: true

in my cronwf yaml (that is not in git and only manually applied) i have
annotations:
argocd.argoproj.io/sync-options: Prune=true

but when running this cli: /argocd-linux-amd64 app sync myapp --assumeYes

the cronwf is not being pruned, my assumption is regular sync should prune them without needing to pass --prune flag into cli since both yamls mention pruning

version 2.7.10

**Comment by jgwest** [comment]
Argo CD will only prune resources that it deployed.
