### ISSUE TITLE
ArgoCD fail to Sync IF it fail to resolve AzureDevOps somtimes and cause app to Break till it reslove dev.azure.com again

### ISSUE THREAD

**Issue by iamraj007** [argoproj/argo-cd#14956]
Checklist:

* [Yes ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ Yes] I've included steps to reproduce the bug.
* [ Yes] I've pasted the output of `argocd version`.

**Description of bug**
ArgoCD is not able to resolve AzureDevOps Pvt repo sometime and cause app break and go in Unknown state 

Sometime Application auto sync or Sync by user in UI result in app going in Unknown state and in APP CONDITIONS: Error
 Application conditions:  ComparisonError dial tcp: lookup dev.azure.com on 10.0.0.10:53: server misbehaving
So it means ArgoCD is not able to resolve dev.azure.com (sometime only)

The access is setup correctly with secret (just to rule-out this issue) also its working most of time with git clone done by Argocd.  
```
apiVersion: v1
kind: Secret
data:
  password: AzureDevOpsPATwithCorrectAccess==
  url: FullAzureDevOpsPvtRepoURL=
  username: UserName==
```
Error from Argo UI (on Sync): 
rpc error: code = Unknown desc = Get "https://myprojectname@**dev.azure.com**/myprojectname/manifests/_git/manifests/info/refs?service=git-upload-pack": dial tcp: lookup dev.azure.com on 10.0.0.10:53: server misbehaving

Unable to sync: error resolving repo revision: rpc error: code = Unknown desc = Get "https://myprojectname@dev.azure.com/myprojectname/manifests/_git/manifests/info/refs?service=git-upload-pack": dial tcp: lookup dev.azure.com on 10.0.0.10:53: server misbehaving

IF prune is set to true like below and Sync fail (to match repo state) ArgoCD will delete some component (in my case few k8 resource) and cause Outage to app overall .  
```
syncPolicy:
  automated:
          prune: true
```

**To Reproduce**
I created a Public AKS (can be any k8 cluster)
Setup ArgoCD with helm ver: argocd: v2.4.14+029be59
Setup a Pvt repo in Azure DevOps and create a PAT with access.
Create secret in argocd namespace 
Create any Argo Application from that repo 
Now observe Sync will fail sometime and cause issue in LIVE APP :( 
 

**Expected behavior**
It is expected that ArgoCD will sync (with sync window every 3 min) and sync app from Git/AzureDevOps pvt repo and update each time. Though it fail once in 5 time with AzureDevOps not been respolved and rest of the time it work very well.

Though this work with no issue at all with GitHub pub repo.

Note some of Argo Application in question have some component have minor issue but that should not impact this. No matter how many times we apply
**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/47947075/580fb924-f905-4761-b1ad-baa259e16d9c)

![image](https://github.com/argoproj/argo-cd/assets/47947075/004a5f3e-5a4e-40fc-90b5-98dd422707f8)
![image](https://github.com/argoproj/argo-cd/assets/47947075/d8205536-cc3b-42bb-b193-e88d401853ba)

**Version**

```shell
$  argocd version
argocd: v2.4.14+029be59
  BuildDate: 2022-10-05T17:37:30Z
  GitCommit: 029be590bfd5003d65ddabb4d4cb8a31bff29c18
  GitTreeState: clean
  GoVersion: go1.18.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
```
time="2023-08-08T12:37:54Z" level=warning msg="finished unary call with code FailedPrecondition" error="rpc error: code = FailedPrecondition desc = error resolving repo revision: rpc error: code = Unknown desc = Get \"https://myprojectname@dev.azure.com/myprojectname/manifests/_git/manifests/info/refs?service=git-upload-pack\": dial **tcp: lookup dev.azure.com on 10.0.0.10:53: server misbehaving**" grpc.code=FailedPrecondition grpc.method=Sync grpc.service=application.ApplicationService grpc.start_time="2023-08-08T12:37:46Z" grpc.time_ms=8037.499 span.kind=server system=grpc



time="2023-08-08T14:02:52Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = Failed to fetch default: `git fetch origin --tags --force --prune` failed exit status 128: fatal: unable to access 'https://dev.azure.com/myprojectname/manifests/_git/manifests/': Could not resolve host: dev.azure.com" grpc.code=Internal grpc.method=RevisionMetadata grpc.service=application.ApplicationService grpc.start_time="2023-08-08T14:02:44Z" grpc.time_ms=8041.514 span.kind=server system=grpc
time="2023-08-08T14:02:56Z" level=warning msg="finished unary call with code FailedPrecondition" error="rpc error: code = FailedPrecondition desc = error resolving repo revision: rpc error: code = Unknown desc = Get \"https://myprojectname@dev.azure.com/myprojectname/manifests/_git/manifests/info/refs?service=git-upload-pack\": dial tcp: lookup dev.azure.com on 10.0.0.10:53: server misbehaving" grpc.code=FailedPrecondition grpc.method=Sync grpc.service=application.ApplicationService grpc.start_time="2023-08-08T14:02:48Z" grpc.time_ms=8031.701 span.kind=server system=grpc


```

**Comment by rumstead** [comment]
Can you share the application controller logs where it performed the sync and prune?

**Comment by iamraj007** [comment]
> Can you share the application controller logs where it performed the sync and prune?

It turn out one of the app have update coredns and added some on prem ip to DNS resolve.... So in my case it was config issue from user side.

Any one else facing such issue should check coredns cm in kube-system ns first. 
$ kubectl get cm coredns -n kube-system

@rumstead for checking on this.

**Comment by piggy2303** [comment]
in my case, i slove by adding hostaliases [detail how to add](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/) with ip and domain of private github repo
to deployment argocd-server and argocd-repo-server
