### ISSUE TITLE
latest version argocd cli v2.8.0 doesn't support --values-literal-file and send null or blank helm values for both argocd app create and argocd app set commands

### ISSUE THREAD

**Issue by hetpats** [argoproj/argo-cd#14967]
Checklist:

* [ yes] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [yes ] I've included steps to reproduce the bug.
* [ yes] I've pasted the output of `argocd version`.
Argocd version : v2.4.8+844f79e
Argocd Cli : 2.7.11, 2.7.8 (Working fine) 2.8.0 (NOT WORKING)
Argocd cli 2.8.0 doesn't look like its backward compatible with argocd version 2.4.8 or argocd cli 2.8.0 has bug.

We have a working cicd pipeline which uses argocd cli to update deployments on eks cluster the main logic to update the app is using --values-literal-file to pass values files for our helm chart below is the code that works till argocd cli v 2.7.11 but we upgrade argocd cli to 2.8.0 and it send null or blank values to the application in argocd.
Here is the command we use to update Helm values of application in argocd.

**argocd app create XXXX --repo https://git.XXX/myrepo.git --revision develop --dest-namespace xxx --path cd/helm/xx-chart/ --values-literal-file cd/helm/values/xx-xx-xx-xx.yaml --sync-policy none --sync-option PrunePropagationPolicy=foreground --sync-option PruneLast=true --dest-server https://xx.gr7.xx.eks.amazonaws.com --revision-history-limit 1 --project xxx**

we also tried app set command to update the values file using  --values-literal-file cd/helm/values/xx-xx-xx-xx.yaml 
**argocd app set XXXX --values-literal-file f.yaml** 

Both the above commands while using argocd  CLI 2.8.0 , it passed blank or null to the application .

Argocd cli 2.8.0 --values-literal-file option send blank or null data to application running on argo cd ui v 2.4.8, it should send the values that we pass not null or blank.

**To Reproduce**
You can reproduce the error by running app create or app set using --value-literal-file using argocd cli version  2.8.0 
To make this work run the same command using any version equal or lower then 2.7.11

** we currently cannot update the argo cd version just yet but will do so in coming weeks .

All application we tested 5 + apps exhibited same issues with argod cli 2.8.0

**Expected behavior**
Applications Helm values file should be updated using app create or app set (cli v2.8.0 fails to do so using --value-literal-file option)

We expect the values to be populated as shown in diag below.
**Screenshots**
**The command executes fine with no errors in output**  but in the background it passes null or blank values file to the app in argo cd causing app to fail sync process

![image](https://github.com/argoproj/argo-cd/assets/47161379/9a659b89-6ed3-412c-8b8f-5a2c9dac3c27)

screen shot is from cli that works(2.7.11 or lower cli), VALUES come up blank when using cli 2.8.0.

**Version**
Argocd version : v2.4.8+844f79e
Argocd Cli : 2.7.11, 2.7.8 (Working fine) 2.8.0 (NOT WORKING)

```shell
Paste the output from `argocd version` here.
Argocd UI version : v2.4.8+844f79e

argocd version --client output:
argocd: v2.8.0+804d4b8
  BuildDate: 2023-08-07T19:41:16Z
  GitCommit: 804d4b8ca6bc4c2cf02c5c971aa923ec5b8623f0
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
Nothing come up in the logs as error, just stats that app was updated successfully
```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
Can you post your application manifest before and after (redacted as necessary)?

**Comment by hetpats** [comment]
> Can you post your application manifest before and after (redacted as necessary)?

![image](https://github.com/argoproj/argo-cd/assets/47161379/c4fd118d-06a1-45cc-965f-a5b13cae47d9)

**Comment by todaywasawesome** [comment]
@hetpats Wait, so you're using Argo CD CLI 2.8 with Argo CD 2.4? I don't think that's supported, you would want to use the cli to match the Argo CD version.

Also 2.4 isn't supported anymore.

**Comment by hetpats** [comment]
That was it , we changed the version to match the cli and its fixed. 
Thank you
