### ISSUE TITLE
Argocd-notifications-cm configuration overwrite on each update

### ISSUE THREAD

**Issue by zatu22** [argoproj/argo-cd#15016]
Propose an enhancement to address the notification configuration overwrite.

# Summary

Prevent overwriting of notification configuration during update installations.

# Motivation

Currently, with each update installation, the notification configuration is being overwritten. This behavior leads to the loss of user-defined notification settings, causing inconvenience and potential disruptions in the notification workflow. This enhancement aims to address this issue and ensure that user-customized notification settings persist across updates.

# Proposal

Option 1: Mechanism that checks the existence of the notification configuration before performing an update installation.

Option 2: Introduce the `argocd-notifications-cm` as a separate resource within the [Catalog Template](https://github.com/argoproj/argo-cd/blob/master/notifications_catalog/install.yaml). Users can then apply this resource independently using kubectl.

**Comment by crenshaw-dev** [comment]
Can you clarify what you mean by "Catalog Template"?

**Comment by zatu22** [comment]
> Can you clarify what you mean by "Catalog Template"?

Yes sure, I mean this one: notifications_catalog/install.yaml

The thought was that this template alone would be sufficient for anyone who wanted a notification, and that it could be taken out of install.yaml and this would avoid overwriting the configuration every time argo-cd get updated.

**Comment by crenshaw-dev** [comment]
Ah, sure. Are you using Kustomize to install the Argo CD manifests? If so, you can add that catalog as a patch in an overlay and avoid it getting blown away when you upgrade.

**Comment by zatu22** [comment]
I use kubectl directly for the installation and upgrade.

**Comment by crenshaw-dev** [comment]
You'll need to switch to Kustomize or some other tool. The nature of `kubectl apply` is that it updates cluster state to match the manifests. If the manifests don't include your patches, the patches will be missing from the cluster state.
