### ISSUE TITLE
Multiple Source Application Not Deploying the Changes automatically

### ISSUE THREAD

**Issue by NatarajanR** [argoproj/argo-cd#15032]
We are currently using 2.6 version of Argo CD. I was exploring  https://argo-cd.readthedocs.io/en/release-2.6/user-guide/multiple_sources/ . With that were are seeing this https://github.com/argoproj/argo-cd/issues/2789#issuecomment-1380878128 issue where we have to manually refresh the app post pushing the changes. Has it been fixed or do we have any feature to track this issue?

**Comment by crenshaw-dev** [comment]
@NatarajanR which 2.6 patch version? There have been bug fixes in that series.

**Comment by crenshaw-dev** [comment]
In my opinion, we shouldn't call it stable until there's robust UI and CLI support. We currently don't have the resources to make either of those happen short-term, so I don't have an ETA for you.

I'm also aware of some high-git-usage issues related to multi-source apps which may be general enough to block considering the feature "stable."

But that said, many people use the feature in production without UI/CLI support and without major issues.

**Comment by NatarajanR** [comment]
@crenshaw-dev okay thanks. Could you please let me know in which version the above mentioned issue has got fixed?

**Comment by crenshaw-dev** [comment]
2.6.3 included https://github.com/argoproj/argo-cd/pull/12576, which may fix the issue. But tbh I'd just go ahead to 2.6.13.

**Comment by NatarajanR** [comment]
@crenshaw-dev  thank you very much. Tried with 2.6.13, it is working as expected

**Comment by crenshaw-dev** [comment]
Awesome, glad it's working now!
