### ISSUE TITLE
ArgoCD i/o timeout with API Server

### ISSUE THREAD

**Issue by whitleykeith** [argoproj/argo-cd#15061]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Our ArgoCD instance has recurring issues when syncing larger Apps due to i/o timeouts (screenshot below has error message)

The IP is our K8s API Server, which is managed by Azure (AKS). We don't have much visibility into the health of the API Server, but I haven't seen any issues with regular `kubectl` requests even when Argo is having issues with syncs. This includes direct calls to the resource ArgoCD might be timing out on. 

This happens the most frequently with our largest App, which has around ~60 resources and ~20 child applications (only one degree of App of Apps), and usually occurs on the namespace auto-creation option, specifically the ArgoCD namespace (even though we have this enabled on the other child apps as well). This also happens occasionally on smaller apps not part of the above application, but less frequently.

I've tried setting `ARGOCD_K8S_TCP_TIMEOUT` as an environment variable in the application controller, as that [seems to be the config](https://github.com/argoproj/argo-cd/blob/bfaac2b5ac4b96c8af8158902c1b086f7ced7389/pkg/apis/application/v1alpha1/cluster_constants.go#L26) I need to tune to increase the timeout. However, I still see the same error with the timeout being ~30s

This can happen consecutively to the point where sync retries are exhausted and the sync fails, even if the manifests get synced. 

**To Reproduce**

Reproducing the actual error is pretty difficult and our config repo is internal so I can't share that. Generally the steps to reproduce would be:

1. Set `ARGOCD_K8S_TCP_TIMEOUT` to something other than the default 30 seconds
2. (somehow) Force a K8s API Server request to take longer than 30 seconds
3. See that the timeout occurs at 30 seconds

**Expected behavior**

ArgoCD would not timeout on these calls

`ARGOCD_K8S_TCP_TIMEOUT` would configure the timeout appropriately

**Screenshots**

![Image](https://github.com/argoproj/argo-cd/assets/21354274/a88991dc-a7af-401b-8fc2-44a08bc70e80)

**Version**

```shell
argocd: v2.7.11+ec195ad.dirty
  BuildDate: 2023-08-07T14:40:17Z
  GitCommit: ec195adad84c61c6151d553b9fdce3c258b1325d
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

N/A

**Comment by sharninder** [comment]
@whitleykeith So did you solve this by increasing the outbound IPs/ports per node ? We're also seeing this issue in our cluster but I can't figure out the correct metric to identify if its the exact problem. Did you also decrease the idle timeout from the default of 30 minutes ?

**Comment by whitleykeith** [comment]
@sharninder Yep, that was the fix! We didn't change the timeout, just went from the default 1 IP to 10 IPs with 1024 ips/node which is what aligned with our max cluster size of 512.

We had issues with detection as well. This issue plagued us for months and frustrated me so much I went through the Azure Support Troubleshooting workflow (If you're also on AKS, you can go to the resource in the Azure Portal and I think it's at the bottom of the list on the left). As one of the first steps it did some analysis step and said a specific node was having SNAT port exhaustion, and that was the node the application controller was on.

**Comment by sharninder** [comment]
Aah thank you. I can see the SNAT exhaustion message now. Its annoying that Azure doesn't have basic metrics front and centre and one has to hunt for them.

**Comment by wilsonwang371** [comment]
@whitleykeith BTW, you said changing ARGOCD_K8S_TCP_TIMEOUT will not take effect. Did you find the actual place to change this timeout?

**Comment by jenting** [comment]
> @whitleykeith BTW, you said changing ARGOCD_K8S_TCP_TIMEOUT will not take effect. Did you find the actual place to change this timeout?

@wilsonwang371 
I configured in the application controller statefulset, not sure if it's the right place or not.

**Comment by vivekthangathurai** [comment]
@sharninder where do you see the SNAT exhaustion message  ?
