### ISSUE TITLE
Prune resources in reverse order of syncwave during sync

### ISSUE THREAD

**Issue by svghadi** [argoproj/argo-cd#15074]
# Summary

Sync-waves allow users to manage resource creation order. However, pruning resources during sync currently doesn't follow the reverse order of creation, leading to incomplete cleanup.

This proposal aims to improve the pruning process during sync by introducing reverse order handling similar to application deletion introduced in #3959.

# Motivation

Certain scenarios require resource deletion in the reverse order of their creation. Few such use-cases are mentioned in #12376. 

# Proposal

Below proposed implementation is based on discussions from #12376. Most of below change will be in `gitops-engine` repository.

1. **Reordering Logic**: Implement reordering mechanism in gitops-engine so that during sync, higher wave resources marked for pruning are removed first.
2. **Wait for Deletion**: Add a check to wait for pruned resource to be actually deleted from the cluster during sync before moving to next wave. If performance impact due to wait is a concern, it can be introduced as an opt-in behaviour.

**Comment by sambonbonne** [comment]
I don't know if this would be relevant but as the *wait for deletion* should be opt-in, maybe the *reordering logic* could be opt-in too or opt-out? It would allow parallel removing of resources if sync waves can be ignored in some use cases.
