### ISSUE TITLE
`argocd app sync APPNAME --revision ...` doesn't seem to work

### ISSUE THREAD

**Issue by titilambert** [argoproj/argo-cd#1512]
**Describe the bug**
Hello,
when I run `argocd app sync APPNAME` everything works perfectly
but if I run `argocd app sync APPNAME --revision 661ea9c5b33ac03bd9ac6f426e2ba065c269694c`, where `661ea9c5b33ac03bd9ac6f426e2ba065c269694c` is not the latest commit of the branch followed by Argo, nothing changes.

**To Reproduce**
1. Run `argocd app sync APPNAME --revision 661ea9c5b33ac03bd9ac6f426e2ba065c269694c`

**Expected behavior**
We want to see argo change the deployment based on the asked revision.
If I run `argocd app get APPNAME` the sync is with the latest commit ...

**Screenshots**

**Additional context**

**Comment by alexec** [comment]
Ok. I think I can suggest an alternative way to achieve this. Patch the application. This would be something **like**:

```bash
argocd app patch APPNAME --patch '[{"op": "update", "path": "spec.source.revision", "value": "661ea9c5b33ac03bd9ac6f426e2ba065c269694c"}]'
```

You'd need to get the exact JSON patch syntax correct. 

Warning! I've made some assumption about what you want here.

**Comment by alexec** [comment]
Note - I'm not saying there's not a bug, just trying to provide a work-around.

**Comment by titilambert** [comment]
@alexec Thanks ! I also tried that without success but with this command line:
```
argocd app patch APPNAME --patch '[{"op": "update", "path": "spec/source/targetRevision", "value": "661ea9c5b33ac03bd9ac6f426e2ba065c269694c"}]'
```
Is my path not correct ?!
Thanks for your help !

**Comment by alexmt** [comment]
@titilambert 

I think the command should be changed to:

```
argocd app patch APPNAME --patch '[{"op": "replace", "path": "/spec/source/targetRevision", "value": "661ea9c5b33ac03bd9ac6f426e2ba065c269694c"}]'
```

Note: this command will change app `targetRevision` to new sha, but it won't perform actual deploy. You need to run `argocd app sync APPNAME` to deploy updated revision

**Comment by alexmt** [comment]
Seems like this is answered.  @titilambert please feel free to reopen.
