### ISSUE TITLE
Introduce `--insecure-skip-tls-verify` option for self-signed HTTP git URLs

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1513]
**Describe the bug**
It is impossible to connect repositories using HTTP git url if git server uses self-signed certificate.

**To Reproduce**
1. Try to connect repo using `argocd repo add https://<url> --username <username> --password <password> --insecure-ignore-host-key`
2. The connection fails if server uses self signed cert: `x509: cannot validate certificate for <host> because it doesn't contain any IP SANs`

**Expected behavior**
Repository should be successfully connected.

**Comment by jessesuen** [comment]
This bug is invalid. `--insecure-ignore-host-key` only apply to SSH host keys and does not make sense in the context of https URLs / x509 errors.

For https URLs, the solution is to supply the self-signed certificates of the repo-server and api-server. Otherwise we can decide to introduce an `--insecure-tls-skip-verify` flag, so that self-signed certificates to https git repos are accepted. 

I will convert this bug to an enhancement for that request.

**Comment by gabrielcalderon** [comment]
@jessesuen Having a way to add insecure https git repos would be great. In my case, I don't use argocd cli at all. Another option could be to add a field for pasting your CA in ArgoCD UI's when adding a git repo. That's the way Rancher-UI handles custom CA's for pipelines.

**Comment by alexec** [comment]
See https://github.com/argoproj/argo-cd/pull/1805

**Comment by alexmt** [comment]
PR is in progess

**Comment by alexmt** [comment]
Done!

**Comment by pvgbabu** [comment]
> Describe the bug
> It is impossible to connect repositories using HTTP git url if git server uses self-signed certificate.
> To Reproduce
> Steps to reproduce the behavior:
> 
> Try to connect repo using argocd repo add https://<url> --username <username> --password <password> --insecure-ignore-host-key
> The connection fails if server uses self signed cert: x509: cannot validate certificate for <host> because it doesn't contain any IP SANs
> 
> Expected behavior
> Repository should be successfully connected.
@alexmt 
Is this issue resolved , If say could you please let us know how to use --insecure-skip-tls-verify  option in kfp.containers._container_builder
Thanks for your help
