### ISSUE TITLE
Application controller memory leak 

### ISSUE THREAD

**Issue by tomjohnburton** [argoproj/argo-cd#15148]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Just observing the resource usage for the application controller reveals a potential memory leak. At some point, the logs just stop.

**To Reproduce**

Deploy ArgoCD latest version. 

**Expected behavior**

No memory leak.

**Screenshots**

<img width="870" alt="Screenshot 2023-08-22 at 11 32 52" src="https://github.com/argoproj/argo-cd/assets/39559415/039b8e53-25a1-4cb4-8768-3e97163a192d">

**Version**

```shell
{
    "Version": "v2.8.0+804d4b8",
    "BuildDate": "2023-08-07T14:25:33Z",
    "GitCommit": "804d4b8ca6bc4c2cf02c5c971aa923ec5b8623f0",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**
Seeing a lot of the following logs

```
argocd-application-controller-0 application-controller {"level":"info","msg":"Alloc=218457 TotalAlloc=7342845364 Sys=669006 NumGC=64417 Goroutines=697","time":"2023-08-22T08:45:02Z"}
argocd-application-controller-0 application-controller {"level":"info","msg":"Alloc=222369 TotalAlloc=7345913723 Sys=669006 NumGC=64436 Goroutines=697","time":"2023-08-22T08:55:02Z"}
argocd-application-controller-0 application-controller {"level":"info","msg":"Alloc=321144 TotalAlloc=7348923090 Sys=669006 NumGC=64454 Goroutines=697","time":"2023-08-22T09:05:02Z"}
argocd-application-controller-0 application-controller {"level":"info","msg":"Alloc=167841 TotalAlloc=7351995234 Sys=669262 NumGC=64474 Goroutines=697","time":"2023-08-22T09:15:02Z"}
argocd-application-controller-0 application-controller {"level":"info","msg":"Alloc=311410 TotalAlloc=7355039331 Sys=669262 NumGC=64492 Goroutines=697","time":"2023-08-22T09:25:02Z"}
```

**Comment by alexmt** [comment]
Seeing it is prod as well. Compared two memory dumps and found this:

<img width="516" alt="image" src="https://github.com/argoproj/argo-cd/assets/426437/c8046b9e-e67f-463f-a04d-62ca929d35a7">

It is very similar to this issue: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2413

Probably we are incorrectly using open-telemetry interceptor.

**Comment by alexmt** [comment]
We did upgrade otel libraries in 2.8 https://github.com/argoproj/argo-cd/pull/13798

**Comment by alexmt** [comment]
It looks like this is the culprit: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4226 .  Preparing PR to re-use interceptors

**Comment by tomjohnburton** [comment]
Thanks for the quick fix!
