### ISSUE TITLE
Mismatch between documentation and API (CRD) for `AppProject`

### ISSUE THREAD

**Issue by lindhe** [argoproj/argo-cd#15153]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In [the documentation for `AppProjects`](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#projects), it says (bold emphasis is mine):

> `destinations` reference to clusters and namespaces that applications within the project can deploy into **(don't use the `name` field, only the `server` field is matched)**.

But `kubectl explain` says that it's a valid field:

```console
$ kubectl explain appproject.spec.destinations.name
KIND:     AppProject
VERSION:  argoproj.io/v1alpha1

FIELD:    name <string>

DESCRIPTION:
     Name is an alternate way of specifying the target cluster by its symbolic
     name
```

Something is wrong, either in the documentation or in the CRD.

**To Reproduce**

n/a

**Expected behavior**

Consistent descriptions in documentation and API.

**Screenshots**

n/a

**Version**

n/a

**Logs**

n/a

**Comment by crenshaw-dev** [comment]
Thanks for the report! The docs are incorrect, explain is correct. Do you have time to open a PR?

**Comment by lindhe** [comment]
Great! I'll fix that!

**Comment by lindhe** [comment]
BTW: Does the name field also support wildcards? I.e. it's valid with both `foo-bar` and `foo-*` and `*`?

**Comment by crenshaw-dev** [comment]
It does!
