### ISSUE TITLE
Extending managedFieldsManagers Support to the ignoreResourceUpdates Configuration in ArgoCD

### ISSUE THREAD

**Issue by uriariel** [argoproj/argo-cd#15151]
### Summary
Extend the functionality of the `ignoreResourceUpdates` flag to support `managedFieldsManagers`, similar to how `ignoreDifferences` supports this feature.

### Motivation
The `ignoreDifferences` field in resource customizations has been beneficial in cases where fields are dynamically adjusted by in-cluster controllers such as VPA and HPA. This flag currently supports the `managedFieldsManagers` configuration, allowing users to specify which controller's changes to ignore.

However, with the current setup, if a user wishes to ignore changes based on resource updates without affecting the diffing from the Git repository, they lack the granularity and specificity provided by the `managedFieldsManagers` functionality in the `ignoreDifferences` flag.

To bring uniformity and offer more granular control to users, we propose extending the `managedFieldsManagers` support to the `ignoreResourceUpdates` flag.

### Proposal
1. Enhance the `ignoreResourceUpdates` configuration to support the `managedFieldsManagers` field.
2. Allow users to specify a list of managers (e.g., `vpa-controller`, `hpa-controller`) for which changes should be ignored under `ignoreResourceUpdates`.
3. Update the ArgoCD documentation to reflect this new addition, providing examples to assist users in understanding and implementing this feature.

### Example Configuration:
```yaml
ignoreResourceUpdates:
  - jsonPointers:
      - /spec/replicas
    managedFieldsManagers:
      - hpa-controller
```

### Benefits
- **Granularity**: Users can now be specific about which controller's changes to ignore during resource updates, offering better control over sync behavior.
- **Consistency**: By having similar functionalities available for both `ignoreDifferences` and `ignoreResourceUpdates`, the user experience becomes more intuitive and consistent.
**it should be noted that the documentation does not specify that this feature doesn't exist, but rather even implies its existence, so its crucial to note the lack of its existence in the documentation for now **
- **Enhanced GitOps**: This proposal ensures that ArgoCD continues to support genuine GitOps workflows, especially in environments where in-cluster resources are dynamically adjusted by controllers.

**Comment by uriariel** [comment]
Its was my original intention when I've opened another issue: #15094

**Comment by agaudreault-jive** [comment]
I think you might be confusing the behavior of  `ignoreResourceUpdates` with a `ignoreDifferences` that applies on the cluster updates. `ignoreResourceUpdates` will ignore resource events received by the kubernetes controller watch. At this moment, the application that the resource belongs to is unknown. We would need to load the specific application setting configuration and this complexity will decrease the performance improvement added by this feature.

If the performance impact is small, adding the possibility to configure the managedFieldsManagers on the server configuration would be a nice improvement if a use case warrants it.

> **Consistency**: By having similar functionalities available for both ignoreDifferences and ignoreResourceUpdates, the user experience becomes more intuitive and consistent.

ignore resource updates and ignore differences are fundamentally different. While they both have a similar way of configuring them with resource customization in the server configuration, they solve two distinct problems. 

> **Enhanced GitOps**: This proposal ensures that ArgoCD continues to support genuine GitOps workflows, especially in environments where in-cluster resources are dynamically adjusted by controllers.

I think https://github.com/argoproj/argo-cd/issues/15094 better describes a good implementation to ignore the difference on cluster updates which seems to be the need here. With that implementation, I am not sure supporting `managedFieldsManagers` in `ignoreResourceUpdates` becomes relevant.
