### ISSUE TITLE
branch_slug in ApplicationSet PR generator truncates too far

### ISSUE THREAD

**Issue by whitelancer** [argoproj/argo-cd#15163]
Hi there, I've noticed an issue with the `branch_slug` in the PR ApplicationSet generator that I'm hoping we can address. Since the library is using the Go slug library ("github.com/gosimple/slug") the default behavior is to have EnableSmartTruncate enabled/on. This creates a lot of problems when trying to generate unique branch names from long branches, such as:
```
	slug.MaxLength = 50
	urlSlug := slug.Make("feature/123reallylong/name/herethatmustbe/truncated/soon/orelseitwillblow/up")
	fmt.Println(urlSlug)
```
```
feature-123reallylong-name-herethatmustbe
```
And a bigger issue with a branch that only contains one slash (or hyphen):
```
	urlSlug = slug.Make("feature/123reallylongnameherethatmustbetruncatedsoonorelseitwillblowup")
	fmt.Println(urlSlug)
```
```
feature
```

When trying to use branch_slug to generate a container image name, this becomes a major problem especially in the second example. Here is what I expect and is more repeatable for other tools:
```
	slug.EnableSmartTruncate = false
	slug.MaxLength = 50
	urlSlug := slug.Make("feature/123reallylong/name/herethatmustbe/truncated/soon/orelseitwillblow/up")
	fmt.Println(urlSlug)
```
```
feature-123reallylong-name-herethatmustbe-truncate
```

```
	slug.EnableSmartTruncate = false
	urlSlug = slug.Make("feature/123reallylongnameherethatmustbetruncatedsoonorelseitwillblowup")
	fmt.Println(urlSlug)
```
```
feature-123reallylongnameherethatmustbetruncatedso
```

The simplest fix would be to disable smart truncate in the go library.  I realize this may cause problems with existing params, but it's impossible to generate unique branch slugs when using smart truncate.

For instance, these all give back `feature` as the slug.
```
slug.EnableSmartTruncate = true
slug.MaxLength = 50
fmt.Println(slug.Make("feature/reallylongnamethatwillbetruncatedbecauseitistoolong"))
fmt.Println(slug.Make("feature/isanotherreallylongnamethatwillbetruncatedbadly"))
fmt.Println(slug.Make("feature/shouldbedifferentbutitalsoisnottruncatedcorrectly"))
```

**Comment by crenshaw-dev** [comment]
Cross-linking my answer from another thread: https://github.com/argoproj/argo-cd/issues/10622#issuecomment-1688778275
