### ISSUE TITLE
How to actually deploy anything at all?

### ISSUE THREAD

**Issue by gabrielcalderon** [argoproj/argo-cd#1516]
Using latest argocd release with **Rancher 2.2.2** in a local VM (Ubuntu Bionic 18.04 LTS Server) with my own local network trusted certs/ca.

**The releases state to just run:**

```
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v0.12.2/manifests/install.yaml
```

But in reality that's just enough to get ArgoCD to work. After that I had to create an ingress rule with very specific annotations to get by the SSL through, else I was getting HSTS errors all over the place, even when choosing the HTTP port. Why are these very specific annotations not provided by default?

After that, most of the examples in https://github.com/argoproj/argocd-example-apps require to have Persistent Volumes, why make examples with persistent volumes? This is painful specially in bare-metal, local k8s clusters.

**Test**
I tried deploying everything using straight kubectl instead of the YAML from the manifest folder. This resulted in everything getting created (service, roles, etc) but i get this error deploying any app from the argocd-examples/blue-green folder.

> Rollout.argoproj.io "" not found

**Tested/Worked**
* helm-workload
* helm-dependencies

**Comment by alexec** [comment]
hi @gabrielcalderon sorry to hear you having trouble getting set-up. You might want to check out the operator manual for details the set-up instructions:

https://argoproj.github.io/argo-cd/operator-manual/

The blue-green example is broken, @dthomson25 might be able to help, or you could ask in the Slack room.
