### ISSUE TITLE
Add `sourceNamespaces` field to the Projects UI

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#15196]
# Summary

The Projects edit page in the UI doesn't include the `sourceNamespaces` field. We should add that field.

# Motivation

Apps-in-any-namespace is a popular feature. Full UI support is good.

# Proposal

Just add a little section at the bottom of the Project UI to allow viewing/setting the sourceNamespaces field. Ideally, only show the field if apps-in-any-namespace is enabled.

**Comment by villisco** [comment]
+1 

Just stumbled onto this also when trying to configure the "app-in-anynamespace".
Took time to understand that UI has no appropriate field to configure this.

**Comment by jdvgh** [comment]
I'd like to work on this.
Can I just grab this issue?
