### ISSUE TITLE
High CPU usage in 2.8.0 in application controller

### ISSUE THREAD

**Issue by akselleirv** [argoproj/argo-cd#15220]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I upgrade from version v2.7.10 to v2.8.0 I have large increase CPU and memory usage as seen in the screenshot below. 

**Screenshots**

Resource usage:

You can see the downgrade from v2.8.0 to v.2.7.10 around 11:00 which results in a large decrease of resource usage.

The application controller:
![image](https://github.com/argoproj/argo-cd/assets/52233080/87ac00b3-ab9b-4321-af76-c5beb19904fc)

Nothing major changes in the other pods:
![image](https://github.com/argoproj/argo-cd/assets/52233080/13ed54b6-e282-4e1f-8a2e-9391575d02e8)

Argo metrics:
![image](https://github.com/argoproj/argo-cd/assets/52233080/a3f73e23-e575-41a1-915b-5cf11f904bc5)

**Version**

```shell
v2.8.0
```

**Logs**

I've looked through the logs, but yet to find any hints of what the cause could be.

Here is a pprof profile of the application-controller: [argocd-application-controller-1.Profile.zip](https://github.com/argoproj/argo-cd/files/12429051/argocd-application-controller-1.Profile.zip)

Let me know if you need any more information.

**Comment by leoluz** [comment]
Thank you for the great details in your issue (pprof helps a lot)!
Analyzing the graph below, Argo CD is mainly doing diff calculation for your apps. Your cache is probably invalidated in 2.8 if you are using ignore diffs. Can you confirm if you have many apps with ignore diffs configuration? This was a bug in previous versions (https://github.com/argoproj/argo-cd/issues/12610).

In your case, I suspect that once the cache is rebuilt the CPU will stabilize. We are running 2.8 in several instances and didn't notice a general increase in CPU.
 
<img width="736" alt="pprof-graph" src="https://github.com/argoproj/argo-cd/assets/44989/5ed02f8f-2c21-407b-b480-cfa3f0490551">

**Comment by akselleirv** [comment]
The left view is the CPU usage and the right view is the log lines. When the new version is rolled out then a the high CPU usage starts, and it logs these warnings pasted below.


![image](https://github.com/argoproj/argo-cd/assets/52233080/ed539ec9-5c14-4cc8-b1f5-de2e089fdddd)


Logs: 

```
2023-08-25 11:22:41.186 | W0825 09:22:41.186328       6 warnings.go:70] unknown field "status.sync.comparedTo.ignoreDifferences"  
2023-08-25 11:22:41.186 | W0825 09:22:41.186305       6 warnings.go:70] unknown field "status.controllerNamespace"
```

The `ignoreDifferences` error might the related to the high CPU usage as you indicated in your comment regarding previous issues.

**Comment by akselleirv** [comment]
Found the issue! The problem was that the CRDs was not installed thus related in the log output.
