### ISSUE TITLE
Installation error, argocd repo server cannot run

### ISSUE THREAD

**Issue by Harris1024** [argoproj/argo-cd#15238]
The argocd repo server error message is as follows

time="2023-08-25T06:02:40Z" level=info msg="Generating self-signed TLS certificate for this session"
time="2023-08-25T06:02:40Z" level=info msg="Initializing GnuPG keyring at /app/config/gpg/keys"
time="2023-08-25T06:02:40Z" level=info msg="gpg --no-permission-warning --logger-fd 1 --batch --gen-key /tmp/gpg-key-recipe1448474064" dir= execID=50e2d
time="2023-08-25T06:02:46Z" level=error msg="`gpg --no-permission-warning --logger-fd 1 --batch --gen-key /tmp/gpg-key-recipe1448474064` failed exit status 2" execID=50e2d
time="2023-08-25T06:02:46Z" level=info msg=Trace args="[gpg --no-permission-warning --logger-fd 1 --batch --gen-key /tmp/gpg-key-recipe1448474064]" dir= operation_name="exec gpg" time_ms=6023.6767709999995
time="2023-08-25T06:02:46Z" level=fatal msg="`gpg --no-permission-warning --logger-fd 1 --batch --gen-key /tmp/gpg-key-recipe1448474064` failed exit status 2"

**Comment by Harris1024** [comment]
NAME                   STATUS   ROLES    AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
k8s-cicd-10-12-19-41   Ready    worker   381d   v1.19.8   10.12.19.41   <none>        CentOS Linux 7 (Core)   3.10.0-1160.45.1.el7.x86_64   docker://20.10.8

**Comment by crenshaw-dev** [comment]
I don't think this is solved yet (I believe it's very environment-specific), but I do know that there are some duplicate and/or related issues: https://github.com/argoproj/argo-cd/issues?q=is%3Aissue+is%3Aopen+%22failed+exit+status+2%22

**Comment by Harris1024** [comment]
Thank you. I modified the argocd repo server deployment in install.yaml, resolved
seccompProfile:
Type: Unconfined
