### ISSUE TITLE
Argo CD should enqueue apps with AddRateLimited instead of Add

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#15233]
**Describe the bug**

An Application might be very busy/churny and enqueued/reconciled in a hot loop. This could happen for a variety of reasons. For example, the typical case is when a child resource (e.g. Pod) might change state. Whenever a child resource changes, we follow its ownership references up the chain to determine the managed resource & Application associated with the child resource. Then we enqueue the app in order to reconcile it (and reassess app health/sync, etc...).

Sometimes, often due to a misbehaving 3rd party controller ([in my case, it was the argo-rollout controller](https://github.com/argoproj/argo-rollouts/issues/2982)), Argo CD will reconcile the app in an infinite loop, e.g. several hundreds of times per minute. This causes a number of problems:

1. The app view UI can become usable. When an app or resource tree is constantly being updated, clicking on resources in the UI is very slow, and the browser seems to be doing a lot of CPU intensive work dealing with the application stream
2. We simply reconcile the app way too much than necessary. In my case, there was no meaningful change to the app (health or sync status). But the controller was too busy doing no-op reconciliations, causing unnecessary CPU load.

After reviewing the code, even though we do use [`workqueue.RateLimitingInterface`](https://github.com/argoproj/argo-cd/blob/dd49e228fd9f7dc10ea2f14d04cd35e97a914845/controller/appcontroller.go#L100), we don't make use of `AddRateLimited`:

https://github.com/argoproj/argo-cd/blob/dd49e228fd9f7dc10ea2f14d04cd35e97a914845/controller/appcontroller.go#L781-L782

**To Reproduce**

A misbehaving controller that updates a child resource in a loop (e.g. in https://github.com/argoproj/argo-rollouts/issues/2982) will cause the parent app to get reconciled several hundreds of times per minute:

**Expected behavior**

The application controller needs to protect itself from bad/busy applications by rate limiting single apps in the workqueue. This can only happen if we switch from `Add` to `AddRateLimited`.

**Version**

v2.7

**Comment by crenshaw-dev** [comment]
I'm curious how the win from this might compare to those from ignoreResourceUpdates fine-tuning. I think they're complementary, but I love an easy W.

**Comment by jessesuen** [comment]
The two features are complimentary. Though I think it will lessen the need for users to tune `ignoreResourceUpdates` (which is a good thing).

The benefit here is that we get natural protection (for all resources) with, I think no degradation in UX. In the happy path, we will reconcile apps just as fast as before (since rate limiter would not kick in). But in the problematic path (hot loops), we at least won't flood the controller with unnecessary no-op reconciles.


 I would guess that add

**Comment by jannfis** [comment]
I'm not sure about the semantics of the rate limiting here, e.g. what does it mean to `Add`  and item in a rate-limited queue? It was not really clear from the documentation at https://pkg.go.dev/k8s.io/client-go/util/workqueue. 

Does it mean:

* `Add()` is blocking for the rate limit, or
* the items added to the queue are processed in a rate-limited manner?

I would assume it's the latter, but in our particular case, that might just end up with a queue congestion anyway. If there's a flood of refresh requests for the same application added to the queue will either end up blocking legitimate other refresh requests - what it would solve is a high churn in CPU, imho.

So we'd probably need per-application rate-limited refresh queues, instead of a global queue for all apps? Or can you configure rate limiting in a programmatic way, e.g. inspect the item added to the queue and then apply specific rate limiting options?

**Comment by jessesuen** [comment]
The library supports both global and per-item rate limiting. If you see [`DefaultControllerRateLimiter()`](https://pkg.go.dev/k8s.io/client-go/util/workqueue#DefaultControllerRateLimiter):

> DefaultControllerRateLimiter is a no-arg constructor for a default rate limiter for a workqueue. It has both overall and per-item rate limiting. The overall is a token bucket and the per-item is exponential

Note that we currently instantiate with the DefaultControllerRateLimiter helper:

```golang
		appRefreshQueue:               workqueue.NewNamedRateLimitingQueue(workqueue.DefaultControllerRateLimiter(), "app_reconciliation_queue"),
		appOperationQueue:             workqueue.NewNamedRateLimitingQueue(workqueue.DefaultControllerRateLimiter(), "app_operation_processing_queue"),
		projectRefreshQueue:           workqueue.NewNamedRateLimitingQueue(workqueue.DefaultControllerRateLimiter(), "project_reconciliation_queue"),
		appComparisonTypeRefreshQueue: workqueue.NewRateLimitingQueue(workqueue.DefaultControllerRateLimiter()),
```

> what does it mean to Add and item in a rate-limited queue?

This is my understanding:
* Normal `workqueue.Interface` does not have any rate limiting. So any call to Add() immediately queues it for reconciling. 
* Rate limited `workqueue.RateLimitingInterface` has all of the normal `workqueue.Interface` methods, but additionally introduces `AddRateLimited()` and others like `Forget()` to reset rate limiting.
* If you only ever call `Add()` there's zero benefit to using `workqueue.RateLimitingInterface` since it acts just like `workqueue.Interface`
* If you call `AddRateLimited()`, the call returns immediately (just like `AddAfter()`), but the actual call to `Add()` will be potentially delayed, depending on your rate-limiting parameters.

Note that this change may be more involved than just switching from `Add()` to `AddRateLimited()`. I think this interface was mainly meant to prevent failure storms. Because they instruct you to call `Forget()` in order to reset the rate limiting once an error is cleared. But in our case, the app was actually reconciling successfully, but just too much.

**Comment by jannfis** [comment]
The per-item rate limiting sounds interesting, but I'm still trying to find out what per-item actually means. Or rather, what _item_ means in this context.

I'd really wish for some kind of rate-limiting that is able to consider Argo CD specific "things" and could ensure kind of fairness or QoS in scheduling in a multi-tenant system, for example:

* I would like to rate limit the processing of items in the operation queue according to their AppProject (or any property within the AppProject)
* I would like to rate limit the processing of items in the operation queue started by any given user (e.g. who initiated the sync operation)

I know this is vastly expanding the scope of the initial idea (which, btw, I totally support) but I just wanted to throw that in the room.

**Comment by agaudreault-jive** [comment]
I think it would be important in the implementation to add some sort of user feedback to let them know that their Application sync is being rate-limited. It could be a field in the status of the Application with visual feedback similar to the Shared resource warning.

Giving users feedback will allow them to fix the underlying issue that might exist. Otherwise, they will likely live with a reduced sync performance for their Application ad vitam aeternam.
