### ISSUE TITLE
Allow ApplicationSets in any namespace without setting allowed-scm-providers

### ISSUE THREAD

**Issue by tculp** [argoproj/argo-cd#15246]
# Summary
Currently, if you try to enable the "ApplicationSets in any namespace" feature, you must set the `allowed-scm-providers` config, otherwise you get an error. However, not setting that field should work and perhaps just print a warning that no scm providers are enabled.

I am using ArgoCD v2.8.1.

# Motivation

I don't want any scm providers to be allowed, so I have to set the `allowed-scm-providers` field to a dummy URL. An empty string did not work.

# Proposal

Default an unset `allowed-scm-providers` as assuming that no SCM providers are allowed.

**Comment by crenshaw-dev** [comment]
Instead of interpreting and empty `--allowed-scm-providers` to mean "allow none" (a breaking change), I recommend we introduce a new `--disable-scm-generator` flag to improve the UX.

**Comment by tculp** [comment]
That would work too
