### ISSUE TITLE
Nested Refresh dropdown does not work on Application Details page

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1524]
**Describe the bug**
The application node dropdown menu has 'Refresh' item which also includes dropdown. It is impossible to expand 'Refresh' item dropdown.

**To Reproduce**
1. Go to any application detail page
2. Click on Application node dropdown menu
3. Try to expand nested dropdown menu

**Expected behavior**
The nested dropdown should be successfully expanded.

![image](https://user-images.githubusercontent.com/426437/56690192-bd13e700-6691-11e9-9316-14cc3eb349c9.png)

**Comment by jsoref** [comment]
Is the dropdown supposed to be the same as the top thing?
![image](https://user-images.githubusercontent.com/2119212/92808341-ab67d800-f389-11ea-9614-20229590b1af.png)

**Comment by ciiay** [comment]
@jsoref Comparing the dropdown menu items and the top bar menu items, it looks this Refresh button in the dropdown menu should do the same thing as the top bar button does. I'd like to work on this. Thank you!

cc @alexmt

**Comment by ciiay** [comment]
I have debugged this issue and I found out that if I remove this line it will fix the bug and I have tested all dropdown functionalities on all pages as far as I'm aware of. Could you explain if this line is needed and if I can safely remove it? Thanks!
`dropDownOpened.next(this);`

https://github.com/argoproj/argo-ui/blob/e81faeb971180151796ab5aeca8e8740ed4a3578/src/components/dropdown/dropdown.tsx#L115
