### ISSUE TITLE
auto submission

### ISSUE THREAD

**Issue by aamer59** [argoproj/argo-cd#15254]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by blakepettersson** [comment]
I'll close this issue for now, if there is an issue feel free to add more info and reopen.
