### ISSUE TITLE
"Create Job" action doesn't add `jobTemplate.spec` from CronJob to created Job's `spec`

### ISSUE THREAD

**Issue by kodzimo** [argoproj/argo-cd#15259]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

As expected from the action, it should create a Job from CronJob as it does `kubectl create job --from=<CRON_JOB_NAME>` command. But all of a sudden I noticed, that Jobs, created by the action, don't have appropriate `jobTemplate.spec`, while Jobs, created by `kubectl create job --from=<CRON_JOB_NAME>` - do have.
In my example, I was trying to set `ttlSecondsAfterFinished` to `jobTemplate.spec`, and noticed unexpected behavior. Maybe the reason is the 50th sting in [action.lua file](https://github.com/argoproj/argo-cd/blob/master/resource_customizations/batch/CronJob/actions/create-job/action.lua)

**To Reproduce**

Add `ttlSecondsAfterFinished` to CronJob's `jobTemplate.spec` and trigger the action "Create Job". You will see no `ttlSecondsAfterFinished` in created Job's `spec`.

**Expected behavior**

Created by the action "Create Job" Job should be the same as created by `kubectl create job --from=<CRON_JOB_NAME>`

**Screenshots**

No screenshots attached.

**Version**

```shell
v2.8.0+804d4b8
```

**Logs**

```
No logs added.
```

**Comment by crenshaw-dev** [comment]
Would either of you be up for modifying https://github.com/argoproj/argo-cd/blob/master/resource_customizations/batch/CronJob/actions/create-job/action.lua and submitting a PR? Should be pretty straightforward to set up a new [test](https://github.com/argoproj/argo-cd/blob/master/resource_customizations/batch/CronJob/actions/action_test.yaml) for the problematic case.

**Comment by kodzimo** [comment]
> Would either of you be up for modifying https://github.com/argoproj/argo-cd/blob/master/resource_customizations/batch/CronJob/actions/create-job/action.lua and submitting a PR? Should be pretty straightforward to set up a new [test](https://github.com/argoproj/argo-cd/blob/master/resource_customizations/batch/CronJob/actions/action_test.yaml) for the problematic case.

Yes, I'll try to contribute appropriate modification.

**Comment by kodzimo** [comment]
@crenshaw-dev, is there any doc with branch naming rules, etc. ?

**Comment by kodzimo** [comment]
@crenshaw-dev modification to lua script is done. But I'm little confused 'bout tests: does it really should be the new test?
Seems like `TestLuaResourceActionsScript` test from `custom_actions_test.go` has necessary functionality, but it works not as expected (again 😅). Is it correct to expect (according to [action_test.yaml](https://github.com/argoproj/argo-cd/blob/master/resource_customizations/batch/CronJob/actions/action_test.yaml)), that in `TestLuaResourceActionsScript` [job.yaml](https://github.com/argoproj/argo-cd/blob/master/resource_customizations/batch/CronJob/actions/testdata/job.yaml) must be compared to generated by lua script Job's manifest ?

**Comment by SergeyLadutko** [comment]
@crenshaw-dev

> @crenshaw-dev modification to lua script is done. But I'm little confused 'bout tests: does it really should be the new test? Seems like `TestLuaResourceActionsScript` test from [custom_actions_test.go](https://github.com/argoproj/argo-cd/blob/master/util/lua/custom_actions_test.go) has necessary functionality, but it works not as expected (again 😅). Is it correct to expect (according to [action_test.yaml](https://github.com/argoproj/argo-cd/blob/master/resource_customizations/batch/CronJob/actions/action_test.yaml)), that in `TestLuaResourceActionsScript` [job.yaml](https://github.com/argoproj/argo-cd/blob/master/resource_customizations/batch/CronJob/actions/testdata/job.yaml) must be compared to generated by lua script from [cronjob.yaml](https://github.com/argoproj/argo-cd/blob/master/resource_customizations/batch/CronJob/actions/testdata/cronjob.yaml) Job's manifest ?

Can you answer the question above?

**Comment by SergeyLadutko** [comment]
@crenshaw-dev 
I think this one is ready for review

**Comment by crenshaw-dev** [comment]
Hey! Sorry I missed your question. Yep, I think you're correct. Just gotta have input and then match output against the expected job.
