### ISSUE TITLE
argocd app set xxx -p image.tag=xxx doesn't work when app has multiple resource

### ISSUE THREAD

**Issue by islet5** [argoproj/argo-cd#15273]
i edit my app like this:
one repo for helm chart, another repo for values.yaml

![image](https://github.com/argoproj/argo-cd/assets/9824473/9f584963-793f-4a91-9cc7-491a6d6cdae4)

then the cmd "argocd app set ai-assistant-test -p image.tag=xxx" doesn't work anymore
![image](https://github.com/argoproj/argo-cd/assets/9824473/cd2dc0f2-3c74-430b-8736-5e26dcd21fef)

is there anyway i can still use cmd to update parameters?
![image](https://github.com/argoproj/argo-cd/assets/9824473/0daa6220-a28f-4818-be5a-6aec6a3718a0)

**Comment by blakepettersson** [comment]
Duplicate of #12318
