### ISSUE TITLE
Application in any namespace: Terminal not showing

### ISSUE THREAD

**Issue by speedfl** [argoproj/argo-cd#15281]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using application in any namespace it is not possible to open a terminal when using a namespace as prefix.

**To Reproduce**

```
p, proj:teamone:admins, applications, create,    teamone/teamone-argocd/*, allow # Working to create app
p, proj:teamone:admins, applications, action/*, teamone/teamone-argocd/*,  allow # Working if I execute an action on a resource
p, proj:teamone:admins, applications, update, teamone/teamone-argocd/*, allow # Working if I update a resource
p, proj:teamone:admins, logs, get, teamone/teamone-argocd/*,  allow # Working if I get logs
p, proj:teamone:admins, exec, create, teamone/teamone-argocd/*, allow # Not working
```

When running:

https://argocd.mydomain.com/api/v1/account/can-i/exec/create/namespace/podname it returns:

```json
{"value":"no"}
```

https://argocd.mydomain.com/api/v1/account/can-i/logs/get/namespace/podname it returns:

```json
{"value":"yes"}
```

**Expected behavior**

Can I must resturn true

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/23298035/32c280a3-9530-4e62-a1b9-be86a8beaae5)

**Version**

```shell
{
    "Version": "v2.7.11+ec195ad.dirty",
    "BuildDate": "2023-08-07T14:40:17Z",
    "GitCommit": "ec195adad84c61c6151d553b9fdce3c258b1325d",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

Same in 2.8.1

**Logs**

```
N/A
```

**Additional**

It seems that logs has a special treatment. However in the can-i I don't see the `appNamespace` like in all requests sent.

**Comment by jannfis** [comment]
Potentially, the `logs` requests succeeds because RBAC enforcement on logs is [not enabled](https://github.com/argoproj/argo-cd/blob/339072f910017fc49585a06c66efa05f43fd958d/server/account/account.go#L140-L142)?

The `can-i` endpoint potentially does not support a namespace designation yet.

**Comment by pasha-codefresh** [comment]
I just run it locally and it works as expected, you just forget to pass one more argument in your request, 

http://localhost:8080/api/v1/account/can-i/exec/create/cf/cf-argocd/guestbook-ui-56c646849b-94g42d

this is example that works for me. 

This is RBAC config

` p, role:user, exec, create, cf/cf-argocd/*, allow  `


It works, because request itself support any subresource, you can see it here

`	rpc CanI(CanIRequest) returns (CanIResponse) {
		option (google.api.http).get = "/api/v1/account/can-i/{resource}/{action}/{subresource=**}";
	}
`

where subresource is plaintext string

Let me know if you have additional questions
