### ISSUE TITLE
ArgoCD creates cronjob with default paramethers

### ISSUE THREAD

**Issue by EsDmitrii** [argoproj/argo-cd#15284]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hi! 
I noticed that when I trigger cronjob via ArgoCD, it creates job with default `jobTemplate.spec` values.
See this `kubectl explain cronjob.spec.jobTemplate.spec`
When I trigger it via kubernetes, all works well.

I researched and found that lua script is the root cause of this issue: https://github.com/argoproj/argo-cd/blob/master/resource_customizations/batch/CronJob/actions/create-job/action.lua#L50-L54
There are no lines to configure whole `jobTemplate.spec`. There are only two lines that configures `deepCopy(obj.spec.jobTemplate.spec.template.metadata)` and `deepCopy(obj.spec.jobTemplate.spec.template.spec)`.
I'm not a pro in lua and I don't know syntax, but I know that this is the root cause:)

**To Reproduce**
1. Create cronjob and check that you defined `jobTemplate.spec`:
<img width="334" alt="264266303-bd3d3dc0-ba26-4ecf-b9bb-26ed568f0bad" src="https://github.com/argoproj/argo-cd/assets/124890665/51fa1881-a2bd-4f85-b7d0-f6607968eaa3">\
2. Trigger cronjob via ArgoCD:
<img width="291" alt="264266317-be537ea4-6d78-4444-b25e-afc8d728adef" src="https://github.com/argoproj/argo-cd/assets/124890665/6bf0f5f1-c4dd-40e3-b20a-6d5d54ed6b71">\
![image](https://github.com/argoproj/argo-cd/assets/124890665/689a68fe-421f-4927-895e-2406d5cb3323)\
3. Check created job:
<img width="490" alt="264266322-eb2e2983-a026-4283-b684-c6f283338fc5" src="https://github.com/argoproj/argo-cd/assets/124890665/029ff60b-65b6-48db-b60a-9a584b2b5e18">\
It doesn't contain our custom `jobTemplate.spec` paramethers:
<img width="309" alt="264266325-0ffbdf1c-90e0-44d1-a789-3a4a114170ea" src="https://github.com/argoproj/argo-cd/assets/124890665/f6684e59-3e37-47af-9d3d-d3afdb7d87e1">\

**Expected behavior**

`jobTemplate.spec` in job defined the same as in cronjob.

**Version**

```json
{
    "Version": "v2.8.1+2bc94af",
    "BuildDate": "2023-08-22T20:08:23Z",
    "GitCommit": "2bc94af7bd081bc4682c2c6dc005f6336c754c2b",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**
No relevant logs, you can see all stuff on screenshots.

**Comment by afrancis101** [comment]
This issue looks like it was resolved in #15259
