### ISSUE TITLE
argocd-application-controller using deprecated PodSecurityPolicy API

### ISSUE THREAD

**Issue by syphernl** [argoproj/argo-cd#15352]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

For all GKE clusters in our GCP projects, we got a warning that ArgoCD is using an API that is deprecated and will be removed in v1.25.

It is calling `/apis/policy/v1beta1/podsecuritypolicies` and this originates from useragent `argocd-application-controller/v0.0.0 (linux/amd64) kubernetes/$Format`.

Google links has a list of [Kubernetes 1.25 deprecated APIs](https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-25#podsecuritypolicy) which mentions that this API has been deprecated since v1.21 and is no longer served in v1.25.
They have documented [a few alternatives to PodSecurityPolicy](https://cloud.google.com/kubernetes-engine/docs/deprecations/podsecuritypolicy).

**To Reproduce**

Run GKE v1.24 (on GCP).

**Expected behavior**

No deprecated API's being used.

**Screenshots**

**Version**

v2.8.2+dbdfc71

**Logs**

**Comment by shepely** [comment]
Hey @syphernl 👋 
Looks like a duplicate of https://github.com/argoproj/argo-cd/issues/12382.
