### ISSUE TITLE
SSO Login Button in UI

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#154]
The front end should query the new /api/v1/settings endpoint and display an SSO button on the login page, based on the following rules:

1. if there are no connectors, do not show the SSO button
2. if there is only *one* SSO connector, the button should be something like "Login via XXXXX", where XXXXX is the name of the connector (e.g. GitHub)
3. if there is *more* than one connector, the button should say something like "SSO Login". 

Clicking on the link should direct the browser to the page `/auth/login`, which begins the OAuth2 flow.

The reason for the difference between option 2 and 3 is: if there is only one IdP connector, dex has logic to automatically redirect and we know in advanced which connecter it uses (because there is only one). If there is more than one connector, the user will hit a page presenting the different login options.

Example of /api/v1/settings:
```
{
  "url": "https://argocd.example.com",
  "dexConfig": {
    "connectors": [
      {
        "name": "Intuit GitHub",
        "type": "github"
      }
    ]
  }
}
```

**Comment by alexmt** [comment]
Implemented
