### ISSUE TITLE
Sync waves

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1544]
**Is your feature request related to a problem? Please describe.**

> There is a need to perform a phased rollout of multiple deployments where deployment B needs to be deployed only after deployment B is fully ready.

> Typically this use case is solved by defining an init container in deployment B, which queries its dependency (deployment A) to be up. However, there are some scenarios where init containers are unable to solve the problem.

> For example, one scenario is that deployment B should not start until deployment A is running with same version of deployment B. An init container performing a version check would not help here because deployment A may be running with multiple replicas, and could potentially be returning a mix of versions, when deployment A is performing a rolling update.

**Describe the solution you'd like**

Be able to state the wave that a resource should be deployed in. Do not start wave N until wave N-1 is healthy.

```yaml
  annotations:
    "argocd.argoproj.io/sync-wave": "1"
```

**Describe alternatives you've considered**
Weights.

**Additional context**

https://github.com/argoproj/argo-cd/issues/1396

**Comment by jessesuen** [comment]
I reopened https://github.com/argoproj/argo-cd/issues/1396 and prefer to use consistent terminology with helm hook-weights.
