### ISSUE TITLE
Continuous TLS Handshake Issues with Argo Workflow/CD when syncing

### ISSUE THREAD

**Issue by cristinamudura** [argoproj/argo-cd#15442]
During syncing processes with Argo Workflow/CD, we are consistently facing TLS handshake issues. This disrupts our ability to keep workflows and other resources up-to-date, thereby affecting overall operational efficiency.

Argo Version: 5.19.5
Kubernetes version: 1.25.6 

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

Symptoms Observed:

- Frequent TLS handshake error messages specifically during the syncing operations.

**To Reproduce**

- Initiate a sync operation either from the Argo UI or the CLI.
- Observe the TLS handshake errors in the Argo server logs or the logs of the affected service during syncing attempts.
- Try accessing any resource that relies on the syncing mechanism in Argo.

**Screenshots**
![Screenshot 2023-09-11 at 16 40 42](https://github.com/argoproj/argo-cd/assets/80831066/5b8e6aa7-8246-453a-9694-9b532e666492)

**Version**

```shell
5.19.5
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by cedric-appdirect** [comment]
By any chance are you using Azure? We just upgraded our cluster to 1.27 and are now experiencing this issue around 400 times a day. There is an issue open here for tracking: https://github.com/Azure/AKS/issues/3047 .

@jannfis I haven't tried with an increase timeout, but it seems that the connection that are in timeout are never going to succeed. Is there a possibility to configure a number of retry with a sleeping period in between? From reading argo code, I think it is ARGOCD_K8SCLIENT_RETRY_MAX and ARGOCD_K8SCLIENT_RETRY_BASE_BACKOFF. Is it possible to have it sanely wait for another minute before retrying? Is there any potential side effect you can think of?

**Comment by jgwest** [comment]
Original question has been answered, for subsequent feature requests feel free to open a new issue.

**Comment by ebuildy** [comment]
> By any chance are you using Azure? We just upgraded our cluster to 1.27 and are now experiencing this issue around 400 times a day. There is an issue open here for tracking: [Azure/AKS#3047](https://github.com/Azure/AKS/issues/3047) .
> 
> @jannfis I haven't tried with an increase timeout, but it seems that the connection that are in timeout are never going to succeed. Is there a possibility to configure a number of retry with a sleeping period in between? From reading argo code, I think it is ARGOCD_K8SCLIENT_RETRY_MAX and ARGOCD_K8SCLIENT_RETRY_BASE_BACKOFF. Is it possible to have it sanely wait for another minute before retrying? Is there any potential side effect you can think of?

yeah we are seeing this all the time with AKS :-/ looks like a network route issue sometime, dont know yet how to fix it, any luck on ur side?

**Comment by cedric-appdirect** [comment]
The environment variable have had no impact in reducing the problem. We had actually increase the retry attempt of our workflow themself. It does help, but there is still edge case when the Kubernetes call happen and it isn't covered by the workflow retry logic.

**Comment by ebuildy** [comment]
> The environment variable have had no impact in reducing the problem. We had actually increase the retry attempt of our workflow themself. It does help, but there is still edge case when the Kubernetes call happen and it isn't covered by the workflow retry logic.

Sure, I am pretty sure this is routing issue, so waiting more dont help, I am gonna try a full private AKS cluster
