### ISSUE TITLE
[web-ui] indicate if application has "auto sync" enabled on the Applications view

### ISSUE THREAD

**Issue by villisco** [argoproj/argo-cd#15503]
# Summary

Currently the ArgoCD web UI Applications view "_/applications_" only shows the info icons **Healthy + Synced** for each app.
There seems to be **no fast way to distinguish visually which apps are being auto synced** and which are not.

You must check each applications detailed view to get this info.

# Motivation

It's critical to distinguish which apps are pulling changes automatically and which are not.
Showing this info explicitly on the UI Applications view provides better overview for the users.

# Proposal

Options to improve the view:
1) Add third icon to the Status that shows if auto sync is enabled or disabled.
example: grayed out icon if auto sync disabled. Green if enabled (similar to other icons).
2) After the Synced icon add text "(auto)" if auto sync enabled or "(manual)" if auto sync disabled.
3) Add "sync_mode" label to all applications so they can be filtered by labels. 
Update this label when sync mode is changed between auto/manual. 
In the UI quick filters list add "Sync Mode: auto, manual" (similar to "SYNC STATUS: Synced, OutOfSync" filter list)

**Comment by blakepettersson** [comment]
Isn't this covered with #11357?

**Comment by villisco** [comment]
Your correct. 

Didn't notice this until now - the end of menu is hidden from visible view! 
Can be closed then I think.
