### ISSUE TITLE
Badge not found when app name contains a dot

### ISSUE THREAD

**Issue by pepe9012** [argoproj/argo-cd#15507]
**Describe the bug**

Application badge is not found, if app name contains dot (`.`).

Should be related to the changes in v2.8.4 https://github.com/argoproj/argo-cd/pull/15468

**To Reproduce**

1. Use argocd v2.8.4
2. Create `Application` which containes dot (`.`) in it's name, e.g.: `test.app`
3. Call `https://ARGOCD_URL/api/badge?name=test.app&revision=true` (answer will be 400 not found)

**Expected behavior**

Application name can contains dots, and badge will work as it did in previous releases.

**Version**

v2.8.4

**Comment by KouWakai** [comment]
In the change made in https://github.com/argoproj/argo-cd/pull/15468, it now throws an error if the Application name contains dots.

This change is implemented at line 119 of [argo-cd/server/badge/badge.go](https://github.com/argoproj/argo-cd/blob/21672a2a8373adca5cc0203b09d5f65521928d58/server/badge/badge.go#L119). 

https://github.com/argoproj/argo-cd/blob/21672a2a8373adca5cc0203b09d5f65521928d58/server/badge/badge.go#L119
The parameter name is validated using NameIsDNSLabel to ensure it adheres to the DNS 1123 label specification.
If the name contains dot,it returns `[must not contain dots]`

However, as @pepe9012  mentioned, Application names can contain dots, which does not adhere to the DNS specification.

**Comment by zeusal** [comment]
Hello,

Sorry for writing here, but I have ArgoCD v2.10.7+b060053 and I have APPs of APPs with the following structure:

Root APP called: test-app -> https://ARGOCD_URL/api/badge?name=test-app&revision=true
First child APP called: test-app.hello-world -> https://ARGOCD_URL/api/badge?name=test-app.hello-world&revision=true -> 400 status code

Then, when I try to access the label of the root app I see it, but in the child APP, I can't see it.
