### ISSUE TITLE
Container Image URL name does not fit into tooltip

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1552]
**Describe the bug**
Container Image URL name does not feet into tooltip

**To Reproduce**
1. Deploy an application which has a deployment with long image name.
2. Move mouse over the pod which uses long image url
3. The image url does not fit into the tooltip

![image](https://user-images.githubusercontent.com/426437/57045388-4a22e700-6c22-11e9-9546-cd15a31fe065.png)

**Comment by alexec** [comment]
I don't think we should fix this.

**Comment by alexmt** [comment]
Tooltip is going to fit standard libraries from dockerhub, but won't fit urls of apps of our biggest customer (intuit). So for intuit this bug almost defeat any tooltip benefits.

**Comment by alexec** [comment]
There's another issue here. When the node is updated, the tip is deleted. I've never thought this tip was prominent enough. I'm wondering if we should move it to the pull-over. Thoughts?

**Comment by alexec** [comment]
Note to self - this appears to be a bug it Tippy.js, long tips work fine, unless they have '/' in them maybe?
