### ISSUE TITLE
Adding a private repository with non-git user fails

### ISSUE THREAD

**Issue by pbrit** [argoproj/argo-cd#1555]
**To Reproduce**
Steps to reproduce the behaviour:

`$ argocd repo add ssh://john@john-server.org:29418/project  --ssh-private-key-path private.key --insecure-ignore-host-key`

**Actual behaviour**
```
FATA[0001] ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
**Expected behaviour**
The repository is created in `ArgoCD`

**Comment by alexec** [comment]
@pbrit - looks like you're working on a fix?

**Comment by alexmt** [comment]
I think https://github.com/argoproj/argo-cd/pull/1556 is supposed to fix it
