### ISSUE TITLE
CLI not working on (Alpine) Linux

### ISSUE THREAD

**Issue by brushmate** [argoproj/argo-cd#1561]
**Describe the bug**
When I run the Argo CD CLI on Alpine Linux I get the error message `user: Current not implemented on linux/amd64` and the program exits.

**To Reproduce**

    $ docker run -it --rm alpine:latest
    / # wget -O argocd https://{argocd}/download/argocd-linux-amd64
    / # chmod +x argocd
    / # ./argocd
    FATA[0000] user: Current not implemented on linux/amd64

**Expected behavior**
CLI works on Alpine Linux.

**Comment by alexmt** [comment]
hello @brushmate ,

The workaround is to set `USER` env variable. E.g. `export USER=argocd` . This is a common issue for golang apps, `user.Current` does not work if cgo is disabled and cgo has to be disabled to work on alpine.
