### ISSUE TITLE
UI: badges url not containing namespace with "Applications in any namespace"

### ISSUE THREAD

**Issue by villisco** [argoproj/argo-cd#15655]
**Describe the bug**

The badge url generated under "**App Details**" view does not include the "**&namespace=**" parameter when using the "**Applications in any namespace**" setup with ArgoCD.

Badge "Not Found" label is shown when app is deployed to other namespace than the default "argocd".

PS. 
Backend part was fixed by issue https://github.com/argoproj/argo-cd/issues/15351.
This added the support for "**&namespace=**" parameter in badge url.

**To Reproduce**

1. Configure "Applications in any namespace":
    - Set ArgoCD tracking method to **annotation+label**.
    - Add RBAC **ClusterRole + ClusterRoleBinding**

2. Deploy application to namespace other than argocd.

   Example: **testnamespace/app1**

    ```
    kind: Application
    metadata:
        name: app1
        namespace: testnamespace
    ```

3. Check the generated badge url in UI under "**App Details**" view.\
It still shows "Not Found" because **&namespace=** parameteri is not included in the url.

**Expected behavior**

Generated working url should be:
```
<argocd_base_url>/api/badge?name=app1&namespace=testnamespace&revision=true
```

**Version**

v2.8.4

**Comment by crenshaw-dev** [comment]
Changes needed: 
1. Add new `appNamespace` (string) and `nsEnabled` (bool) params here: https://github.com/argoproj/argo-cd/blob/b40d8cb55eaf656ea18195055e220f8d726eefca/ui/src/app/shared/components/badge-panel/badge-panel.tsx#L9C14-L9C24
2. Pass `props.app.metadata.namespace` as `appNamespace` here: https://github.com/argoproj/argo-cd/blob/b40d8cb55eaf656ea18195055e220f8d726eefca/ui/src/app/applications/components/application-summary/application-summary.tsx#L592
3. Add `const useAuthSettingsCtx = React.useContext(AuthSettingsCtx);` to the top of the `ApplicationSummary` component and pass `useAuthSettingsCtx?.appsInAnyNamespaceEnabled` as the `nsEnabled` param into `BadgePanel` component
4. If `nsEnabled` is true [here](https://github.com/argoproj/argo-cd/blob/b40d8cb55eaf656ea18195055e220f8d726eefca/ui/src/app/shared/components/badge-panel/badge-panel.tsx#L22), add `&namespace={appNamespace}` to the constructed query string

**Comment by asapekia** [comment]
I would like to work on this issue. Please assign this to me.
