### ISSUE TITLE
Is it possible to run argocd on ARM ? 

### ISSUE THREAD

**Issue by Leletir** [argoproj/argo-cd#1565]
Hello,

Is it possible to run argocd on ARM ? 

Thank you!

**Comment by alexec** [comment]
Um, what is ARM? Do you mean the processor chipset? If so, Argo CD uses Docker and is written in Golang, so if they work on ARM, then Argo CD works on ARM.

**Comment by Leletir** [comment]
Oh yes sorry, ARM the processor architecture.
It depends on a lot of things, I don't know for Golang, it depends on what is inside the dockerfile, for example the MySQL docker image could not run on ARM processor.
I will check.

**Comment by alexec** [comment]
Please re-open if you have more questions.
