### ISSUE TITLE
(AppSet) recording "unchanged Application" events to k8s overloads ETCD

### ISSUE THREAD

**Issue by ericblackburn** [argoproj/argo-cd#15659]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When an application set doesn't change, the reconcile process still calls applicationset_controller.createOrUpdateInCluster and emits the following event to the k8s cluster

```
unchanged Application "application-generated-by-appset"
```

This uses ETCD as a info DB for non-actions and when using ApplicationSets at large scale, this causes extreme pressure on ETCD. Across our Argo N argo instances, we've added 3,000 AppSets and plan for at least 6,000 more.  Just for those 3k, the ETCD DB jumped up 2GB due to the perpetual logging of "unchanged Application events.

![image](https://github.com/argoproj/argo-cd/assets/17929572/ab5ad92d-b545-4009-8253-eecbc65497ac)

For example, one appset that hasn't changed in 12 days has emitted the event 5,000+ times (or every 3 minutes due to default polling)

```
5459 unchanged: unchanged Application  "application-generated-by-appset"
Events emitted by the applicationset-controller seen at 2023-09-25 16:15:02 +0000 UTC since 2023-09-13 14:14:50 +0000 UTC
```

**To Reproduce**

1. Deploy an Argo AppSet that generates an Argo App
2. Don't change anything after deployed
3. See that every 3 minutes  the unchanged event is logged for the appset.  This can be seed by using `kubectl describe appset applicationsetNameHere` which will result in

```
Events:
  Type    Reason     Age                     From                       Message
  ----    ------     ----                    ----                       -------
  Normal  unchanged  3m47s (x5498 over 12d)  applicationset-controller  unchanged Application "application-generated-by-appset"

```

**Expected behavior**

ApplicationSets should be K8s safe for default behaviors. This means not using ETCD has a noop info logging source. Only report to k8s about problems or changes instead.

**Version**
v2.7.11+ec195ad.dirty

But this is in the master branch too

**Logs**
The k8s events emitted are also mirrored in the logs

```
time="2023-09-25T18:00:58Z" level=info msg="unchanged Application" app=application-generated-by-appset appSet=applicationSetNameHere
time="2023-09-25T18:00:58Z" level=info msg="end reconcile" applicationset=argo-cd/applicationSetNameHere requeueAfter=3m0s
```

**Comment by ericblackburn** [comment]
Working on a quick fix now

**Comment by crenshaw-dev** [comment]
Yep, definitely feels like we should skip events for "unchanged." Maybe even move the log line to `debug` level.

**Comment by ericblackburn** [comment]
Yep, I'll make the PR move the log to debug level.

**Comment by ericblackburn** [comment]
Working on this with PR https://github.com/argoproj/argo-cd/pull/15660

**Comment by rumstead** [comment]
We should close this since the PR was merged?

**Comment by ericblackburn** [comment]
> We should close this since the PR was merged?

Sorry, just closed it. Thank you for the reminder.
