### ISSUE TITLE
Release version job failed for 2.9.0-rc1

### ISSUE THREAD

**Issue by omegion** [argoproj/argo-cd#15669]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

- GH action job has failed for `2.9.0-rc1`: https://github.com/argoproj/argo-cd/actions/runs/6305755886
- The runner complains:
```
System.IO.IOException: No space left on device
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by omegion** [comment]
@crenshaw-dev FYI 🙇🏼

**Comment by 34fathombelow** [comment]
@omegion We are pushing a fix in our CI, we should have the release hopefully sometime today.

**Comment by omegion** [comment]
@34fathombelow great, thnx 🙇🏼
