### ISSUE TITLE
kustomize access to private repo

### ISSUE THREAD

**Issue by kwladyka** [argoproj/argo-cd#1567]
**Describe the bug**
Kustomize doesn't have access to private repository for overlays.

**To Reproduce**
kustomize.yaml
```
bases:
- git@github.com:kwladyka/foo/argocd/clusters/base
```

Error:
`Unable to generate manifests in argocd/cluster/staging: rpc error: code = Unknown desc = Error: loadResMapFromBasesAndResources: couldn't make ldr for`

**Expected behavior**
Kustomize can use ssh keys added by `argocd repo add git@github.com:kwladyka/foo.git --ssh-private-key-path github_private`

**Comment by kwladyka** [comment]
Hint: https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#service-account
tektoncd can be good example of solution for access

**Comment by alexec** [comment]
Interesting, we do not have this feature yet. Not clear how to implement this to me. Probably needs some investigate.

**Comment by kwladyka** [comment]
I read it somewhere, but I can't find it now.

tektocd mount content to right places in HOME directory in container, so git and docker can read it as usually.

**Comment by jessesuen** [comment]
@kwladyka we do support kustomize remote bases to private git repos, but the current limitation is that they:

1. are https repos and not ssh repos
2. are coming from the same repo as the child repo.

A proper solution to support SSH, will likely involve taking the ssh keys from `repository.credentials` configmap (new in v1.0), and making all of those SSH keys available in the repo-server during checkout

**Comment by kwladyka** [comment]
@jessesuen 

To be clear to avoid confusion: you are not supporting **private** git repos, but **public** in `bases` in `kustomization.yaml` file.

You support private repositories in argo-cd to pull private git repo, but not in kustomize bases.

**Comment by alexec** [comment]
This will be fixed in v1.1
