### ISSUE TITLE
I can't remove Application with error

### ISSUE THREAD

**Issue by kwladyka** [argoproj/argo-cd#1568]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3903726/57199186-77ea9180-6f7c-11e9-9989-0d78cffda108.png)

![image](https://user-images.githubusercontent.com/3903726/57199180-64d7c180-6f7c-11e9-8e63-fd94eefde9ae.png)

This happen after delete. I can't remove the Application.

**To Reproduce**
Add resource which fail not adding any resources.

**Expected behavior**
Delete works.

**Comment by alexec** [comment]
It looks like it cannot find the application path inside your repo. I tried to access your repo myself, but I cannot get it to work. Can you please share your repo?

**Comment by kwladyka** [comment]
I think the issue was: Application was created with 0 resources, because of bad kustomize.yaml definition. Probably argocd doesn't predict situation with 0 resources.

This repo is already fixed and puss with --force, so  it wouldn't help.

**Comment by alexec** [comment]
Does this relate to not having the diagnostic output in the UI (only the pods logs)?

**Comment by kwladyka** [comment]
Not sure what stay behind this error in argocd. If source of this error is from kubectl there should be way to see it.

But this time it looks like a argocd issue to not know what to do when deleting cascade when there is 0 resources in application.

**Comment by alexec** [comment]
Legit bug. I plan to fix this as part of  https://github.com/argoproj/argo-cd/issues/1544.

**Comment by alexmt** [comment]
Cascade delete fails because app controller fails to get the list of these resources. I think right to fail but it should be done in a more user-friendly matter. e.g. suggest deleting with cascade false.

**Comment by kwladyka** [comment]
I think it should just delete it ;)

**Comment by alexec** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/1611

**Comment by alexmt** [comment]
Controller don't depend on cache any more to do the deletion. Now even if repo is unavailable controller deletes app resources and deletes the app.

**Comment by shineirvin** [comment]
@kwladyka how did you solved it ? I'm experiencing the same issue.

**Comment by kwladyka** [comment]
Not sure if it is the same issue then. My was about cascade. I don't remember to be honest. I don't experience this issue anymore.
