### ISSUE TITLE
Add ResourceTree functionality for AppSet

### ISSUE THREAD

**Issue by reggie-k** [argoproj/argo-cd#15697]
# Summary

A ResourceTree on the AppSet is needed, similarly to the one existing for Applications, to enable AppSet support in the UI. 
The AppSet resource tree is basically the apps that have an ownerRef of the AppSet, similar to the resource tree returned for app-of-apps. 

# Motivation

To be able to display the AppSet natively in the UI, treating it like an app-of-apps with regard to it's resource tree. 

# Proposal

This is the implementation for app resource tree:
https://github.com/argoproj/argo-cd/blob/3557ec57dc87b2570cf9beaaf8b07bb419883a45/server/application/application.go#L1379

The only resources in the tree for AppSet should be apps.
The implementation should go here :

https://github.com/argoproj/argo-cd/blob/master/server/applicationset/applicationset.go

Here is where the API ResourceTree endpoint for AppSet should probably be:

https://github.com/argoproj/argo-cd/blob/3557ec57dc87b2570cf9beaaf8b07bb419883a45/server/applicationset/applicationset.proto

For possibly future implementation (leaving it here so we don't forget, if it would indeed be needed, will open a separate issue for that):
_After further discussion with @crenshaw-dev 
The CRD of AppSet needs to change to contain the Resources field in the status, similarly to Application. 
The AppSet controller should populate this new field, with the apps that the AppSet generates, in a format similar to the one that the Application controller is populating._

**Comment by crenshaw-dev** [comment]
Quick note: unlike with the App resource tree, where we pull the fully-constructed, multi-level tree off Redis, we should be able to retrieve all the child Applications directly from the ApplicationSet's `status` field.

**Comment by alexymantha** [comment]
I'm curious about the last comment:
> The CRD of AppSet needs to change to contain the Resources field in the status

ApplicationSet CRD already has a similar field:
https://github.com/argoproj/argo-cd/blob/672c1278ae4e91c8b5e98297560556b90cf5f5eb/pkg/apis/application/v1alpha1/applicationset_types.go#L720C11-L720C11
That seems only to be used by the progressive sync feature for now but it could make sense to move it outside of the progressive sync and use it for this as well. That would also allow the ResourceTree to also have the status of the progressive sync if we want to integrate it to the AppSet UI as discussed here: https://github.com/argoproj/argo-cd/issues/14463

**Comment by reggie-k** [comment]
Thanks for noticing!
Yes, it seems that the ResourceSatus[] and the ResourceTree are two distinct things, though they are related eventually to display the Application (and soon the AppSet) resource tree along with the status of those resources in the UI.

Let's do nothing about ResourceSatus[] at the backend side for now, and focus on ResourceTree, and after I would use this new AppSet ResourceTree functionality in the UI, I would be able to understand more whether we need something additional for the ResourceSatus[].

So let's use the field you have suggested.

**Comment by alexymantha** [comment]
I agree Hosts is irrelevant for the ApplicationSetTree but I also think that the OrphanedNodes do not make sense in this case. If we use the status of the AppSet to find its children as we discussed, then we have no way of knowing if there are orphan Applications since the AppSet is only aware of its children. 

I also don't think showing orphan applications brings a lot of value, so I think the ApplicationSetTree only needs the normal Nodes. We could still go with the AbstractTree but it would only have Nodes

I have a draft PR with that implementation here: https://github.com/argoproj/argo-cd/pull/15741

**Comment by reggie-k** [comment]
Firstly, now I see that the new Nodes field is being returned for AppSet!
Secondly, it seems that the ResourceStatus[] is needed on the AppSet, similarly to how it exists on the App - there are many UI side references to this array, looks like I cannot get to display the resource tree without the ResourceStatus[] (I can partially construct it on client side making the assumption it is an array of Application resources, but doing that without getting this information from the backend seems wrong).

**Comment by reggie-k** [comment]
Looks like the Kind and the Group are missing on the ResourceStatus[] resources on the AppSet GET API, other than that I was finally able to display the AppSet resource tree while mocking those two missing fields ,attaching screenshot, so great overall progress! Thank you @alexymantha for all the work you have put into the missing backend functionality.
![image](https://github.com/argoproj/argo-cd/assets/19544836/0ae6055f-864b-48f5-836d-95a167816b3f)
