### ISSUE TITLE
Add examples to commands' `--help` output

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#15690]
# Summary

The Argo CD CLI has a lot of commands for which we provide no example in the `--help` output.

# Motivation

Examples are awesome.

# Proposal

For each item in this checklist, add an `Example` field. See already-checked items for inspiration.

In some cases, the code itself may provide sufficient information to write some examples. For other commands, you may have to read through [the docs](https://argo-cd.readthedocs.io/en/stable/) to find or create examples.

**Note**: When you open your PR, run `make clidocsgen` to make sure docs are updated to include your new examples!

- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd-server/commands/argocd_server.go#L74
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/util/app_test.go#L177
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd-k8s-auth/commands/argocd_k8s_auth.go#L12
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd-k8s-auth/commands/aws.go#L41
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd-k8s-auth/commands/azure.go#L26
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd-k8s-auth/commands/gcp.go#L26
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/completion.go#L197
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/relogin.go#L26
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app_actions.go#L38
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app_actions.go#L58
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app_actions.go#L136
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/logout.go#L17
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/projectwindows.go#L22
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/projectwindows.go#L41
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/projectwindows.go#L78
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/projectwindows.go#L125
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/projectwindows.go#L163
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/projectwindows.go#L204
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/projectwindows.go#L253
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/applicationset.go#L45
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/applicationset.go#L67 (https://github.com/argoproj/argo-cd/pull/15808)
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/applicationset.go#L116
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/applicationset.go#L187
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/applicationset.go#L230
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/repocreds.go#L24
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/repocreds.go#L71
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/repocreds.go#L184
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/repocreds.go#L231
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/settings_rbac.go#L75
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/settings_rbac.go#L101
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/settings_rbac.go#L208
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/settings.go#L153
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/settings.go#L292
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/settings.go#L344
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/settings.go#L410
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/settings.go#L460
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/settings.go#L506
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/settings.go#L539
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/settings.go#L583
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/app.go#L45
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/app.go#L70
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/app.go#L150
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/app.go#L238
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/repo.go#L28
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/repo.go#L70
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/admin.go#L44
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/cluster.go#L44
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/cluster.go#L491
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/cluster.go#L530
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/dashboard.go#L23
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/project_allowlist.go#L41
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/project.go#L25
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/project.go#L47
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/project.go#L142
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/bcrypt.go#L16
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L58
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L117
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L317
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L401
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L648
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L717
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L977
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L1195
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L1330
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L1499
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L1617
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L2327
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L2381
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L2463
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L2546
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app.go#L2571
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/repo.go#L25
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/repo.go#L79
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/repo.go#L226
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/repo.go#L278
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/repo.go#L322
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app_resources.go#L33
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app_resources.go#L97
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/app_resources.go#L253
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/context.go#L21
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/cluster.go#L43
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/cluster.go#L84
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/cluster.go#L223
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/cluster.go#L288
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/cluster.go#L361
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/cluster.go#L466
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/cluster.go#L495
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/gpg.go#L21
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/gpg.go#L42
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/gpg.go#L72
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/gpg.go#L109
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/gpg.go#L140
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/cert.go#L24
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/cert.go#L63
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/cert.go#L147
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/cert.go#L217
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/cert.go#L268
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/account.go#L32
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/account.go#L57
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/account.go#L143
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/account.go#L186
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/account.go#L243
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/account.go#L286
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/account.go#L359
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/account.go#L397
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L39
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L88
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L118
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L151
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L189
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L239
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L276
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L320
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L365
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L411
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L486
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L563
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L603
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L646
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L811
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project.go#L848
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project_role.go#L29
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project_role.go#L56
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project_role.go#L93
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project_role.go#L140
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project_role.go#L176
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project_role.go#L225
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project_role.go#L290
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project_role.go#L341
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project_role.go#L389
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project_role.go#L424
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project_role.go#L469
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/project_role.go#L500
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/login.go#L46
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/root.go#L37
- [ ] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd-dex/commands/argocd_dex.go#L31

Note: I generated the list with this command...

```bash
find ./cmd -name '*.go' -print | xargs grep -n -r '&cobra.Command{' | sed "s/^./- [ ] https:\/\/github.com\/argoproj\/argo-cd\/tree\/$(git rev-parse --short HEAD)/" | sed 's/\.go:/\.go#L/' | awk -F: '{print $1":"$2}' | pbcopy
```

**Comment by rohitkbc** [comment]
Hi 👋 @crenshaw-dev, Can I work on some of these items?

**Comment by Ratangulati** [comment]
Hi 👋 @crenshaw-dev, I would like to work on some of these.

**Comment by crenshaw-dev** [comment]
@rohitkbc and @Ratangulati go for it! Anyone is welcome to pick this up and run with it. Just remember to do what @dttung2905 did, and mention this issue in your PR. :-)

**Comment by mcaci** [comment]
Hi all, I'd like to contribute to this issue and I created a small PR to understand if I got every step correctly (not only the change but also the steps to do the contribution). I hope it helps!

**Comment by sagarwala** [comment]
@crenshaw-dev I have picked the example for context command and added a PR. Please review. Thank you!

**Comment by kokikathir** [comment]
Hi @crenshaw-dev I have added examples for "app action" command in PR [https://github.com/argoproj/argo-cd/pull/15822](https://github.com/argoproj/argo-cd/pull/15822).

**Comment by chiranjeevir-git** [comment]
Hi @crenshaw-dev i have added example for "argocd relogin" command in PR https://github.com/argoproj/argo-cd/pull/15823

**Comment by chiranjeevir-git** [comment]
Hi @crenshaw-dev i have added example for "argocd relogin" command in a new PR https://github.com/argoproj/argo-cd/pull/15839
Closed the old PR  https://github.com/argoproj/argo-cd/pull/15823
please review, Thank you !.
