### ISSUE TITLE
Provide ability to hide defined annotations in ArgoCD web UI

### ISSUE THREAD

**Issue by pasha-codefresh** [argoproj/argo-cd#15693]
**Issue Description**

We have configured our cluster to run with Docker pull secrets, which creates a secret for each service account (dockercfg).

Normally, ArgoCD hides all secret data using `diff.HideSecretData`, including the annotation `last-applied-configuration` ([source](https://github.com/argoproj/gitops-engine/blob/master/pkg/diff/diff.go#L897)).

However, when using pull secrets, the `dockercfg` secret creates an annotation `openshift.io/token-secret.value` that contains the service account’s access token.

**Request**

It would be great to have the ability to define a list of annotations that should not be shown in the ArgoCD web UI on the system level. This feature would improve security and privacy for users who are working with secrets and annotations in ArgoCD.

**Comment by crenshaw-dev** [comment]
Related: https://github.com/argoproj/argo-cd/issues/5201

**Comment by crenshaw-dev** [comment]
A $100 bounty is available for whoever implements this feature!

* Bounty details: https://github.com/argoproj/argo-cd/pull/15699/files
* Docs to claim a bounty: https://argo-cd.readthedocs.io/en/latest/proposals/feature-bounties/#creating-a-bounty

This is our first feature bounty, so please be patient as we work through the bugs in our system. :-)

**Comment by svghadi** [comment]
Hi @pasha-codefresh , @crenshaw-dev , I have PRs up to implement this functionality. Could you review them? Thanks. 
https://github.com/argoproj/gitops-engine/pull/577 
https://github.com/argoproj/argo-cd/pull/18216

**Comment by svghadi** [comment]
Hi @crenshaw-dev, the feature implementation is completed. Thanks @pasha-codefresh & @agaudreault for reviews. How do I claim the bounty?

**Comment by crenshaw-dev** [comment]
@svghadi apologies for the delay! We'll work with you to get the bounty paid out. :-)
