### ISSUE TITLE
argocd-server crash constantly

### ISSUE THREAD

**Issue by kwladyka** [argoproj/argo-cd#1569]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3903726/57220327-33520b00-6ffb-11e9-88be-ffaaf4b1f804.png)

**To Reproduce**
Not sure. I just installed it from official doc and I have this issue regularly from time to time.
Probably it happen when I load UI?

I have no idea how I can get more interesting logs from argocd.

**Expected behavior**
Not crash.

**Comment by alexmt** [comment]
I'm pretty sure this is environmental issue. The /healthz verifies that api server can connect to kubernetes which hosts Argo CD. Which kubernetes are you using?

**Comment by kwladyka** [comment]
From time to time I have also issues to load Applications in UI. It is trying endless load them. I think it is connected with this issue.

I have also issue with CLI, but I have this fancy error "html/text" returned but it doesn't show what really is returned.

```
minikube version
minikube version: v1.0.0
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alexec** [comment]
@kwladyka is this still an issue for you please?

**Comment by kwladyka** [comment]
I had this issue all the time when I was using minikube, but I am not doing this anymore. I am running Argo CD on GCP now.

**Comment by kwladyka** [comment]
Oh I am not sure, but it could be maybe about not enough memory for minikube. But I am totally not sure. I didn't pay attention to it.

**Comment by alexec** [comment]
Ok, let me know if you think we can close this, or if we should leave it.

**Comment by kwladyka** [comment]
We can close it, BUT
it can be useful to check it and describe in documentation for new Argo CD users. If it appear in default minikube settings it should be mentioned in the doc.

But I think it is not priority for project itself, more for the doc, but I didn't see anybody else to have this issue. So for now I close it, but feel free if you want to open it.
