### ISSUE TITLE
bug: api clients with GrpcWeb=true constantly gets too_many_pings error for requests taking >80s

### ISSUE THREAD

**Issue by phanama** [argoproj/argo-cd#15707]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

On our in-house platform, we are using the `apiclient` with `GrpcWeb: true` to talk to our ArgoCD server via http1.1.

We recently noticed frequent `ENHANCE_YOUR_CALM` with `too_many_pings` errors in our client logs when trying to `watch()` application status.

At first, we thought it had something to do with our sidecar proxy's retry mechanism (our client app runs in k8s pod and we use istio) and argocd's grpc keepalive timeouts, but we realized it shouldn't make sense to get this http2 error as we use GrpcWeb/http1.1.

Then, we noticed that the error comes from requests which took exactly 80s after they were first sent. Our timeout setting is far higher from 80s, so it should have come from something else.

We then saw this [PR](https://github.com/argoproj/argo-cd/pull/9922) which added keepalive settings on the client and server to guard against the same error message after four pings (now it's exactly 20s * 4 = 80s). We found that the same client setting was not brought to the apiclient's [grpc-web implementation](https://github.com/argoproj/argo-cd/blob/28ef0961b34f098eb6b7631ecc65f0a3a42ff85f/pkg/apiclient/grpcproxy.go#L113).

This explains the http2 error after 80s, and that it actually comes from the apiclient itself, not the argocd server.

**To Reproduce**

We managed to consistently reproduce this by fronting our argocd client with a faulty http proxy injecting >80s delay.
To make this repeatable, I made a mock test with delay injection [here](https://github.com/phanama/argo-cd/issues/3). The test consistently fails after ~80s.

**Expected behavior**

The apiclient should not get `too_many_pings` error when using `GrpcWeb=true` calling long-running request.

**Screenshots**

N/A

**Version**

We are not using argocd cli to talk to the server, but the go client library.
Here's from our `go.mod`:

```go
require(
    ...
    github.com/argoproj/argo-cd/v2 v2.7.9
    ...
)
```

**Logs**

Here's the log from our argocd client:

```json
{"level":"error","error":"rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: \"too_many_pings\""}
```

**Comment by ashutosh16** [comment]
+1
