### ISSUE TITLE
ArgoCD delivers only 2 Metrics in Prometheus

### ISSUE THREAD

**Issue by diegoballen** [argoproj/argo-cd#15719]
**Describe the bug**

Hello dear community,
I installed the ArgoCD Helm Chart 5.41.2 in an AKS cluster (Kubernetes 1.26.6.).  Prometheus identified successfully all the ArgoCD metric Endpoints. All of them are up and running.  However, only 2 metrics of an Endpoint are published (Controller, port 8082): "argocd_app_info" and "argocd_app_reconcile". There are no ArgoCD metrics in all other Endpoints.

**To Reproduce**

Unfortunately, I cannot tell which steps to follow to reproduce this issue. ArgoCD was simply installed in our environment.

**Expected behavior**

I expect to see all the metrics as indicated in:
https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/30594594/3a86b2e4-a58d-4af7-8a12-227bae870ae9)

**Comment by rogerogers** [comment]
https://argo-cd.readthedocs.io/en/stable/getting_started/#creating-apps-via-ui

Perhaps you should follow the document to create an application first.

**Comment by diegoballen** [comment]
@rogerogers ,
thank you for your answer. All the Applications defined are working properly. 
ArgoCD has been installed a couple of times and I have not seen any changes in the the metrics behavior.

Regards, 

Diego

**Comment by rogerogers** [comment]
![image](https://github.com/argoproj/argo-cd/assets/40619032/55894043-faa9-4dd8-a701-bef72c4677cd)

Try to use the latest version, and works fine for me

**Comment by jgwest** [comment]
Not able to reproduce
