### ISSUE TITLE
ArgoCD v2beta2/horizontalpodautoscalers deprecated & removed in K8s v1.26

### ISSUE THREAD

**Issue by syphernl** [argoproj/argo-cd#15711]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Similar to #12382, ArgoCD is calling the `/apis/autoscaling/v2beta2/horizontalpodautoscalers` API which is deprecated and will be removed in v1.26.
More details on this deprecation/removal can be found on the [docs](https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-26#horizontalpodautoscaler-126)

This can be resolved by using `autoscaling.apiserver.k8s.io/v2` instead (available since v1.23).

**To Reproduce**

See above

**Expected behavior**

No errors / blocked K8s upgrades

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/639906/2ced7af1-3aa0-43a3-a160-4a94878199f4)

**Version**

v2.8.4+c279299

**Comment by crenshaw-dev** [comment]
@syphernl if it's alright with you, let's consolidate the discussion on https://github.com/argoproj/argo-cd/issues/12382
