### ISSUE TITLE
Cannot upgrade from v0.11 to v0.12

### ISSUE THREAD

**Issue by jpresky** [argoproj/argo-cd#1571]
**Describe the bug**
I am using argocd to manage argocd as described here:
https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#manage-argo-cd-using-argo-cd

I was using v0.11.2 and wanted to upgrade to v0.12.3. 

I changed 
bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v0.11.2 
to 
bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v0.12.3

I got an error:
time="2019-05-06T16:14:07Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to generate manifests in __thirdparty/argocd: rpc error: code = Unknown desc = Error: loadResMapFromBasesAndResources: SemiResources: loadResMapFromBasesAndResources: SemiResources: loadResMapFromBasesAndResources: couldn't make target for ../base: json: unknown field \"images\"" grpc.code=InvalidArgument grpc.method=UpdateSpec grpc.service=application.ApplicationService grpc.start_time="2019-05-06T16:14:03Z" grpc.time_ms=3889.618 span.kind=server system=grpc

So I saw this ticket:
https://github.com/argoproj/argo-cd/issues/1180

To summarize that ticket, the new manifests uses the "images:" field which is supported in Kustomize2 which argo supports in v0.12

So i ran kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml to update argo to latest.

Now all argo components are running v0.12.3 but I still get the error with the images. I did not expect that to happen running ArgoCD 0.12.3. Is 

**To Reproduce**
Manage Argo Using Argo and install version v0.11.2
Upgrade Argo by pointing to v0.12.3

Argo will not accept the change because it does not have Kustomize2.

After running
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

ArgoCD still will not evaluate v0.12.3 even though it should have Kustomize2.

**Expected behavior**
I would think that after upgrading to v0.12.3 the ArgoCD would be able to interpret Kustomize2 and manage itself

Is there an upgrade guide from getting from v0.11 to v0.12?

**Comment by alexec** [comment]
This error is related to Kustomize 1 vs 2. Argo CD supports both in v0.12. You must make sure you have the `apiVersion/kind` fields in your `kustomize.yaml` as Argo CD will use Kustomize 1 if they are missing. Can you please confirm this is the case?

**Comment by jpresky** [comment]
Yes that was it. Thank you!

I had to add the first 2 lines to my kustomization.yaml

kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v0.12.3
