### ISSUE TITLE
ArgoCD cli error during argocd app sync

### ISSUE THREAD

**Issue by renperez-cpi** [argoproj/argo-cd#15739]
2023/09/30 00:06:09 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".
time="2023-09-30T00:06:09Z" level=fatal msg="rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: \"too_many_pings\""
Error: Process completed with exit code 20.

ArgoCD Version: v2.8.0+804d4b8
ArgoCD Cli: 
argocd: v2.8.4+c279299
  BuildDate: 2023-09-13T19:43:37Z
  GitCommit: c[27](https://github.com/ChargePoint/demo-app/actions/runs/6358562745/job/17270993666#step:6:28)9299[28](https://github.com/ChargePoint/demo-app/actions/runs/6358562745/job/17270993666#step:6:29)104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64

**Comment by renperez-cpi** [comment]
@crenshaw-dev can you please help with this issue?

**Comment by rumstead** [comment]
https://github.com/argoproj/argo-cd/issues/15656 related?

**Comment by renperez-cpi** [comment]
@crenshaw-dev yes sir, thank you

**Comment by renperez-cpi** [comment]
@crenshaw-dev how do i use this env in argocd CLI ARGOCD_GRPC_KEEP_ALIVE_MIN

**Comment by okgolove** [comment]
@renperez-cpi probably something like `export ARGOCD_GRPC_KEEP_ALIVE_MIN=5m`
On the other hand, in my case this settings didn't help.

**Comment by renperez-cpi** [comment]
@okgolove yeah i tried it and it didn't help
