### ISSUE TITLE
Remove support for kustomize 1 entirely

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1573]
**Is your feature request related to a problem? Please describe.**

Most developers are using K2 these days, and getting confused because we auto-detect Kustomize based on whether or not there are the `apiVersion/kind` fields in `kustomization.yaml`. 

How can we default this correctly?

**Describe the solution you'd like**

TBD

**Describe alternatives you've considered**

TBD

**Additional context**

* https://github.com/argoproj/argo-cd/issues/1085
* https://github.com/argoproj/argo-cd/issues/1571

**Comment by jessesuen** [comment]
Rather than trying to support both / work on making kustomize 2 the default, I propose we just begin deprecation process for kustomize v1, including removing the UI and spec fields specific to v1.
