### ISSUE TITLE
Add cluster to argocd failed with i/o timeout

### ISSUE THREAD

**Issue by javad2157** [argoproj/argo-cd#15746]
Checklist:

*  I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
*  I've included steps to reproduce the bug.
*  I've pasted the output of `argocd version`.

**Describe the bug**
I use argocd command line to add k8s cluster to argocd in the same LAN and it was ok and i have no problem.
but when i want to add cluster to argocd from another network i have got below error. 
I'm sure that have access to port 6443 of k8s cluster from machine that i ran argocd in that.

**To Reproduce**

#argocd cluster add kubernetes-admin@kubernetes --insecure --grpc-web --name cluster3 --kubeconfig config

**Expected behavior**
expect to add cluster successfully.

**Screenshots**
with same LAN between cluster and argocd i am ok and get this 
![image](https://github.com/argoproj/argo-cd/assets/89399278/24147cb7-d135-40cb-a5b1-0e8ca215f4d7)
but when i want to add k8s cluster from another network i have got this error
![image](https://github.com/argoproj/argo-cd/assets/89399278/e2daf8f1-a2a1-4c8c-9aec-887c705993b2)
this is while i have access to port 6443 of k8s cluster and i am sure about this.

**Version**

```shell
argocd: v2.8.4+c279299
  BuildDate: 2023-09-13T19:43:37Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.8.3+77556d9
  BuildDate: 2023-09-07T16:05:43Z
  GitCommit: 77556d9e64304c27c718bb0794676713628e435e
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0```
```
**Logs**
```
time="2023-09-30T07:11:33Z" level=error msg="finished unary call with code Unknown" error="Get \"https://192.168.x.x:6443/version?timeout=32s\": dial tcp 192.168.x.x:6443: i/o timeout" grpc.code=Unknown grpc.method=Create grpc.service=cluster.ClusterService grpc.start_time="2023-09-30T07:11:03Z" grpc.time_ms=30003.412 span.kind=server system=grpc
time="2023-09-30T07:17:17Z" level=error msg="finished unary call with code Unknown" error="Get \"https://192.168.x.x:6443/version?timeout=32s\": dial tcp 192.168.x.x:6443: i/o timeout" grpc.code=Unknown grpc.method=Create grpc.service=cluster.ClusterService grpc.start_time="2023-09-30T07:16:47Z" grpc.time_ms=30005.527 span.kind=server system=grpc
time="2023-09-30T07:18:01Z" level=error msg="finished unary call with code Unknown" error="Get \"https://192.168.x.x:6443/version?timeout=32s\": dial tcp 192.168.x.x:6443: i/o timeout" grpc.code=Unknown grpc.method=Create grpc.service=cluster.ClusterService grpc.start_time="2023-09-30T07:17:31Z" grpc.time_ms=30005.031 span.kind=server system=grpc
time="2023-09-30T07:20:28Z" level=info msg="Alloc=11081 TotalAlloc=24353 Sys=37757 NumGC=7 Goroutines=95"
time="2023-09-30T07:23:26Z" level=error msg="finished unary call with code Unknown" error="Get \"https://192.168.x.x:6443/version?timeout=32s\": dial tcp 192.168.x.x:6443: i/o timeout" grpc.code=Unknown grpc.method=Create grpc.service=cluster.ClusterService grpc.start_time="2023-09-30T07:22:56Z" grpc.time_ms=30004.004 span.kind=server system=grpc
time="2023-09-30T07:26:18Z" level=error msg="finished unary call with code Unknown" error="Get \"https://192.168.x.x:6443/version?timeout=32s\": dial tcp 192.168.x.x:6443: i/o timeout" grpc.code=Unknown grpc.method=Create grpc.service=cluster.ClusterService grpc.start_time="2023-09-30T07:25:48Z" grpc.time_ms=30004.271 span.kind=server system=grpc
time="2023-09-30T07:30:08Z" level=error msg="finished unary call with code Unknown" error="Get \"https://192.168.x.x:6443/version?timeout=32s\": dial tcp 192.168.x.x:6443: i/o timeout" grpc.code=Unknown grpc.method=Create grpc.service=cluster.ClusterService grpc.start_time="2023-09-30T07:29:38Z" grpc.time_ms=30005.676 span.kind=server system=grpc

**Comment by shuker85** [comment]
This sounds like a firewall issue, Can you re-check if ArgoCD cluster can access the other one ?

**Comment by javad2157** [comment]
> This sounds like a firewall issue, Can you re-check if ArgoCD cluster can access the other one ?

I think so too, But I did not find any event that proves this. I checked the traffic with tcpdump and also check the firewall in path between argocd cluster and kubernetes cluster and find nothing. everything was normal and no packet was dropped.
As i said argocd can connect to kubernetes cluster in the same network but i did not re-check that with other network.
I re-check and inform you.

**Comment by lovi88** [comment]
Hi everyone, I have the same issue. Were there any resoulution?

 The context is reachable via kubectl, but when the cluster add command it running we get the following error: 
 .\argocd.exe cluster add docker-desktop --insecure
WARNING: This will create a service account `argocd-manager` on the cluster referenced by context `docker-desktop` with full cluster level privileges. Do you want to continue [y/N]? y
time="2024-02-16T05:39:43-08:00" level=info msg="ServiceAccount \"argocd-manager\" already exists in namespace \"kube-system\""
time="2024-02-16T05:39:43-08:00" level=info msg="ClusterRole \"argocd-manager-role\" updated"
time="2024-02-16T05:39:43-08:00" level=info msg="ClusterRoleBinding \"argocd-manager-role-binding\" updated"
time="2024-02-16T05:40:14-08:00" level=fatal msg="rpc error: code = DeadlineExceeded desc = Get \"https://192.168.43.140:6443/version?timeout=32s\": dial tcp 192.168.43.140:6443: i/o timeout"

**Comment by Ravitejareddykamidi** [comment]
Any solution for  above issue? iam facing same issue while adding from terraform and argocd cli as well

**Comment by cerna14** [comment]
Si estas usando 2 subnets debes permitir el tráfico desde el k8s cluster1 al k8s cluster2 network manager por medio la security list, para la reglas de ingress

**Comment by frodood** [comment]
how did yourl fix it?
