### ISSUE TITLE
argocd-dex crashes into crashloopbackoff with exit code 139 SIGSEGV

### ISSUE THREAD

**Issue by rouke-broersma** [argoproj/argo-cd#15786]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

argocd-dex crashes with exit code 139 SIGSEGV intermittently. We've observed this about 1-2 times a week for the last 4 weeks.

**To Reproduce**

It happens intermittently on multiple of our clusters, and it only happens once every several days. We unfortunately don't know how to reproduce this behavior, it usually happens in the middle of the night. Dex stays in a crashloopback until we restart the deployment or delete the pod recreating the pod. The existing pod stays broken for some reason.

Our dex deployment manifest is available here: https://github.com/rouke-broersma/argocd-dex-repro/blob/main/dex-deployment.yaml

If needed I can supply more manifests from our argocd deployment.

**Expected behavior**

No random crashes :)

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/3595932/b9541aed-a2dd-4f9b-8030-30392da328f5)

![image](https://github.com/argoproj/argo-cd/assets/3595932/e1b52cb4-ec1c-4e5e-94ef-ac97910a2f9b)

**Version**

```json
{
    "Version": "v2.8.4+c279299",
    "BuildDate": "2023-09-13T19:12:09Z",
    "GitCommit": "c27929928104dc37b937764baf65f38b78930e59",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

Unfortunately we have no logs at the time of these crashes and I think it's interesting that it's crashing with SIGSEGV.

**Comment by rumstead** [comment]
Do you have resource limits set on the container? Any memory pressure or cpu throttling?

**Comment by rouke-broersma** [comment]
> Do you have resource limits set on the container? Any memory pressure or cpu throttling?

We have resource limits but we monitor and alert on node pressure and such and there is no indication that there is a problem. I would also then expect an OOMKILL. It also mostly happens during the night when the clusters are virtually unused. During the day the clusters see heavy use, especially on argo itself, and dex does not crash.

If it were resource constraint related I would expect that it resolves itself after the crash, however dex keeps crash looping until the pod is recreated, either by deleting the failed pod or by doing a restart of the deployment.

**Comment by gjkamstra** [comment]
We ran into the same thing and resolved it by increasing the memory request and limit to 104 and 128mb.

**Comment by jgwest** [comment]
Closing as without logs, or reproduction steps, or widespread by other users, absent any counter evidence it is an upstream dex or cluster-specific issue.
