### ISSUE TITLE
argo-cd issue

### ISSUE THREAD

**Issue by janakajm** [argoproj/argo-cd#15784]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by todaywasawesome** [comment]
No info :(

**Comment by janakajm** [comment]
ohh Not copied the issue , I apologies to it and if I got that error I will log
