### ISSUE TITLE
argocd cluster add failed with status code 403 

### ISSUE THREAD

**Issue by zillani** [argoproj/argo-cd#15788]
Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to add a target cluster using argocd CLI, & first I am able to login to the argocd server from the CLI,

```
argocd login --insecure argocd.my-cluster.local --username argocd --grpc-web --password mypassword123                             'argocd:login' logged in successfully
Context 'argocd.my-cluster.local' updated

```
After successful login, argocd  is failing to add the cluster, below is the command we executed, 

` argocd cluster add kubernetes-admin@cluster2   --name my-cluster   --server 10.10.11.224:6443   --in-cluster=false   --kubeconfig /home/zillani/.kube/config`

gives the below response,
```
INFO[0001] ServiceAccount "argocd-manager" already exists in namespace "kube-system"
INFO[0001] ClusterRole "argocd-manager-role" updated
INFO[0001] ClusterRoleBinding "argocd-manager-role-binding" updated
FATA[0001] rpc error: code = Unknown desc = POST https://10.10.11.224:6443/cluster.ClusterService/Create failed with status code 403

```

**To Reproduce**

**Expected behavior**

Argocd should add the target cluster. 

**Version**

I tried on both argocd server versions **v2.8.3** and **v2.3.1**

```shell
argocd: v2.8.4+c279299
  BuildDate: 2023-09-13T19:43:37Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64
  
argocd-server: v2.3.1+b65c169
  BuildDate: 2022-03-10T22:51:09Z
  GitCommit: b65c1699fa2a2daa031483a3890e6911eac69068
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

No logs were found for cluster add.

**Comment by RashRAJ** [comment]
@zillani ever got a workaround to this?

**Comment by limberger** [comment]
I Have this same issue or bug!!!
