### ISSUE TITLE
Argo CD server should not generate SSH certificate if started in insecure mode

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1581]
**Describe the bug**
The `argocd-server` generates self signed certificate even if started in insecure mode. This does not work well if `tls.crt`/`tls.key` kets of  `argocd-secret` are erased by some automation (e.g. cert manager): 
1. `argocd-server` notice that key is missing it generates new one
2. the key got deleted by cert-manager
3. go to 1.

**Comment by pbrit** [comment]
@alexmt I guess you meant "TLS certificate" in the title.

**Comment by alexmt** [comment]
Fixed
