### ISSUE TITLE
argocd app wait parent-app --sync --health is inaccurate 

### ISSUE THREAD

**Issue by nicholasmturner** [argoproj/argo-cd#15830]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I run the run the `argocd app wait --sync --health` command against my parent app (app of apps deployment) it reports all healthy and synced and then lists child apps as being healthy and synced when in fact the child apps can have a sync status of `OutofSync` or health status of `Missing`  or `Progressing`. The  output of `argocd app list` and `kubectl get applications` shows the correct status

**To Reproduce**

Deploy an app of apps environment and force a child app to be `OutofSync` or a health status which is not `Healthy` then issue the `argocd app wait --sync --health` command against the parent app and compare the output to that of the `argocd app list` and `kubectl get applications` commands

**Expected behavior**

`argocd app wait --sync --health`  should report degraded or outofsync if a child app is not 'Healthy' or 'Synced' and list the child app with the correct state

**Screenshots**

See logs

```shell
argocd: v2.8.3+77556d9
  BuildDate: 2023-09-07T17:39:16Z
  GitCommit: 77556d9e64304c27c718bb0794676713628e435e
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.8.3+77556d9
  BuildDate: 2023-09-07T17:39:16Z
  GitCommit: 77556d9e64304c27c718bb0794676713628e435e
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.8.2+g6e3701e
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0

```

% argocd app wait --core argocd/myapps --sync --health --timeout 1 

Name:               argocd/myapps
Project:            myapps
Server:             https://kubernetes.default.svc
Namespace:          argocd
URL:                omitted
Repo:               omitted
Target:             main
Path:               myapps
Helm Values:        values.yaml
SyncWindow:         Sync Allowed
Sync Policy:        Automated (Prune)
Sync Status:        Synced to main (b06cb42)
Health Status:      Healthy

GROUP        KIND         NAMESPACE  NAME                                           STATUS  HEALTH   HOOK  MESSAGE
argoproj.io  Application  argocd     argocd/myapp1                            Synced  Healthy        application.argoproj.io/myapp1
argoproj.io  Application  argocd     argocd/myapp2                            Synced  Healthy        application.argoproj.io/myapp2
argoproj.io  Application  argocd     argocd/myapp3                            Synced  Healthy        application.argoproj.io/myapp3
argoproj.io  Application  argocd     argocd/myapp4                            Synced  Healthy        application.argoproj.io/myapp4
argoproj.io  Application  argocd     argocd/myapp5                            Synced  Healthy        application.argoproj.io/myapp5
argoproj.io  Application  argocd     argocd/myapp6                            Synced  Healthy        application.argoproj.io/myapp6
argoproj.io  Application  argocd     argocd/myapp7                            Synced  Healthy        application.argoproj.io/myapp7
argoproj.io  Application  argocd     argocd/myapp8                            Synced  Healthy        application.argoproj.io/myapp8

% argocd app list
NAME               CLUSTER                         NAMESPACE     PROJECT      STATUS     HEALTH    TARGET
argocd/myapp1       https://kubernetes.default.svc  argocd        myapps       Synced     Healthy   main
argocd/myapp2       https://kubernetes.default.svc  auth-config   myapps       OutOfSync  Healthy   main
argocd/myapp3       https://kubernetes.default.svc  kube-system   myapps       Synced     Healthy   main
argocd/myapp4       https://kubernetes.default.svc  kube-system   myapps       Synced     Healthy   main
argocd/myapp5       https://kubernetes.default.svc  cert-manager  myapps       Synced     Healthy   main
argocd/myapp6       https://kubernetes.default.svc  kube-system   myapps       Synced     Healthy   main
argocd/myapp7       https://kubernetes.default.svc  cert-manager  myapps       Synced     Healthy   main
argocd/myapp8       https://kubernetes.default.svc  cloudhealth   myapps       Synced     Healthy   main

% kubectl get applications
NAME                                            SYNC STATUS   HEALTH STATUS
argocd/myapp1                                          Synced        Healthy
argocd/myapp2                                          OutOfSync     Healthy
argocd/myapp3                                          Synced        Healthy
argocd/myapp4                                          Synced        Healthy
argocd/myapp5                                          Synced        Healthy
argocd/myapp6                                          Synced        Healthy
argocd/myapp7                                          Synced        Healthy
argocd/myapp8                                          Synced        Healthy

```
Paste any relevant application logs here.
```

**Comment by jgwest** [comment]
This is expected behaviour, and a known issue with the app of apps pattern (among others, and described elsewhere). ApplicationSets came about due to issues like this.
