### ISSUE TITLE
"Follow logs, automatically showing new logs lines" and "Automatically scroll to the bottom when new content appears" not working

### ISSUE THREAD

**Issue by kaushikvira** [argoproj/argo-cd#15848]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

"Follow logs, automatically showing new logs lines" and "Automatically scroll to the bottom when new content appears" not working in 2.9.0-rc2 but works in 2.8.2

<img width="1053" alt="image" src="https://github.com/argoproj/argo-cd/assets/6678622/394fd58d-b757-41ef-a809-b9b831680d25">

Here is the full discussion on the issue

**To Reproduce**
Click on any Pod Got to Logs and Click the 2 button shown in the above screenshot. 

1

**Expected behavior**

Log scroll to the bottom the screen to move as a new log appears 

**Screenshots**
<img width="1053" alt="image" src="https://github.com/argoproj/argo-cd/assets/6678622/6591fa48-26a5-41fe-a3b0-e63ebeb61d86">

**Version**
2.9.0-rc2

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by keithchong** [comment]
Hi @crenshaw-dev @ashutosh16 , I went back to the original commit that introduced the new button (to automatically scroll to the bottom) but I don't see any difference in behavior. It's possible in 2.8.2 the log view always scrolled to the bottom, and that's why we needed the buttons in the first place, so that you are still able to view the contents from where you were.

**Comment by keithchong** [comment]
I see the correct behavior now.  @ciiay , what do you think about this?  I see the issue after this change was introduced: https://github.com/argoproj/argo-cd/pull/15506

Without the change, when you click on the "Automatically scroll to the bottom..." button, it jumps to the bottom of the log.  With the 15506 change, it does not, and it does not follow when there are new lines.

**Comment by ciiay** [comment]
I'll raise a PR to fix this issue.
