### ISSUE TITLE
Unnecessary cluster liveStateCache.GetVersionsInfo() lock contention

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#15850]
**Describe the bug**

On an extremely busy cluster, we noticed an increase in `git_ms` time:

<img width="1240" alt="image" src="https://github.com/argoproj/argo-cd/assets/12677113/937601d1-9104-4747-89a3-4dfc8c2e90d8">

At first, I suspected the repo server was the bottleneck. But when investigating repo-server stats, the `GenerateManifests` calls were quick, and the `argocd_repo_pending_request_total` gauge was low. And so repo-server stats did not correlate with the increase in git_ms time.

It turns out `git_ms` was misleading. After further breaking it down by `getRepoObjs stats` log output. It turns out all the time was spent in `helm_ms`.

<img width="1599" alt="image" src="https://github.com/argoproj/argo-cd/assets/12677113/784c4dc3-b4ff-47b0-b5c5-24ca5903c723">

Looking at the code, `helm_ms` is really just querying liveStateCache to get API version and resources information in order to pass it to the `helm template` command:

https://github.com/argoproj/argo-cd/blob/a1245885fedb2bb057e20b4c3c7fef2780c0e99f/controller/state.go#L149

```golang
	ts.AddCheckpoint("build_options_ms")
	serverVersion, apiResources, err := m.liveStateCache.GetVersionsInfo(app.Spec.Destination.Server)   // The only reasonable explanation of where time is being spent.
	if err != nil {
		return nil, nil, fmt.Errorf("failed to get cluster version for cluster %q: %w", app.Spec.Destination.Server, err)
	}
	conn, repoClient, err := m.repoClientset.NewRepoServerClient()
	if err != nil {
		return nil, nil, fmt.Errorf("failed to connect to repo server: %w", err)
	}
	defer io.Close(conn)

	manifestInfos := make([]*apiclient.ManifestResponse, 0)
	targetObjs := make([]*unstructured.Unstructured, 0)

	// Store the map of all sources having ref field into a map for applications with sources field
	refSources, err := argo.GetRefSources(context.Background(), app.Spec, m.db)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to get ref sources: %v", err)
	}

	for i, source := range sources {
		if len(revisions) < len(sources) || revisions[i] == "" {
			revisions[i] = source.TargetRevision
		}
		ts.AddCheckpoint("helm_ms")
```

However, the `liveStateCache.GetVersionsInfo()` currently needs a read lock of the liveStateCache. Going deeper, we see:

```golang
func (c *liveStateCache) GetVersionsInfo(serverURL string) (string, []kube.APIResourceInfo, error) {
	clusterInfo, err := c.getSyncedCluster(serverURL) // this gets the cluster lock, but not
	if err != nil {
		return "", nil, fmt.Errorf("failed to get cluster info for %q: %w", serverURL, err)
	}
	return clusterInfo.GetServerVersion(), clusterInfo.GetAPIResources(), nil
}
```

Finally, we can get to where we think the problem is:

```golang
// GetAPIResources returns information about observed API resources
func (c *clusterCache) GetAPIResources() []kube.APIResourceInfo {
	c.lock.RLock()
	defer c.lock.RUnlock()

	return c.apiResources
}
```

c.apiResources is a list. Lists are safe for read access (we will not get the equivalent of `concurrent map writes`). 
~Furthermore, the way we update the API resources is with a full replacement.~
EDIT: actually we do modify the list in-place.

Alex and I feel the lock being used in GetAPIResources() is unnecessarily contributing to lock contention to the cluster cache and can be removed.

**To Reproduce**

Hard to reproduce. Needs busy cluster such that objects are being written to live state cache, causing this call to slow down.

**Expected behavior**

git_ms should not be affected by liveStateCache

**Version**

```shell
Argo CD v2.6
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
If there aren't already docs for those log metrics, that could maybe be part of the fix PR 😇

**Comment by jessesuen** [comment]
The root cause was because of a continued increase in resource objects in the cluster:

<img width="1724" alt="image" src="https://github.com/argoproj/argo-cd/assets/12677113/54b411a9-8e4b-4f0f-a7f5-dbb8f1e35fed">

This aligns with my expectations for the fix because:
* as resources are churning/creating, controller is constantly inserting objects into liveStateCache, which acquires the mutex
* the reconciliation tries to access the mutex (unnecessarily) in order to get apiResources information for the `helm template` request

**Comment by sidewinder12s** [comment]
Any idea when that gitops-engine change will get shipped in ArgoCD? It appears this commit is what is in ArgoCD 2.9.1: https://github.com/argoproj/gitops-engine/commit/b0fffe419a0f0a40f9f2c0b6346b752ed6537385
