### ISSUE TITLE
Integration tests is unstable

### ISSUE THREAD

**Issue by naruse666** [argoproj/argo-cd#15868]
**Describe the bug**
Actions link: https://github.com/argoproj/argo-cd/actions/workflows/ci-build.yaml

Integration tests is often failed. but it's can be success to Rerun jobs.
and not always failed to same version.

it should be asap fix for contributors.

**Expected behavior**
No need for rerun

**Failed Test**
Fortunately, failed is same test and output same logs every times.

Func: TestNamespacedDisableManifestGeneration

Logs: 
`app_management_ns_test.go:2461` is [here](https://github.com/argoproj/argo-cd/blob/master/test/e2e/app_management_ns_test.go#L2461).
```
    app_management_ns_test.go:2461: 
        	Error Trace:	/home/runner/work/argo-cd/argo-cd/test/e2e/app_management_ns_test.go:2461
        	            				/home/runner/work/argo-cd/argo-cd/test/e2e/fixture/app/consequences.go:47
        	            				/home/runner/work/argo-cd/argo-cd/test/e2e/app_management_ns_test.go:2460
        	Error:      	Not equal: 
        	            	expected: "Kustomize"
        	            	actual  : "Directory"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-(v1alpha1.ApplicationSourceType) (len=9) "Kustomize"
        	            	+(v1alpha1.ApplicationSourceType) (len=9) "Directory"
        	            	 
        	Test:       	TestNamespacedDisableManifestGeneration
```

I'm not familiar with this test, but why do you think it's happen?

**Comment by crenshaw-dev** [comment]
I haven't had time to look into it. But can confirm, this test flakes often.
