### ISSUE TITLE
improve docs referencing k3d

### ISSUE THREAD

**Issue by francRang** [argoproj/argo-cd#15884]
# Summary
Given that the latest k3d version is `v5.6.0`, it seems like the following piece of the docs are badly redacted:
https://github.com/argoproj/argo-cd/blob/master/docs/developer-guide/toolchain-guide.md?plain=1#L207-L211
IMHO, the example k3d command should be using the latest flags `--k3s-arg` and `'--disable=traefik@server:*', while the "disclaimer" at the bottom of the `k3d` command should explain how for versions earlier than `v5.0.0`, the flags should be  `--k3s-server-arg` and `'--disable=traefik'` respectively. This is to avoid confusion and to try to make the docs be as relevant for current versions of tools used as possible.

# Motivation

When I was installing ArgoCD on my local k3d cluster, this led to a bit of confusion and had to replace the command with the given flags for the latest k3d version.

# Proposal

I suggest the following change:

START
```
k3d cluster create my-cluster --wait --k3s-arg '--disable=traefik@server:*' --api-port $IP:6550 -p 443:443@loadbalancer
```
!!!note
For k3d versions less than v5.0.0, the example command flags `--k3s-arg` and `'--disable=traefik@server:*'` should change to `--k3s-server-arg` and `'--disable=traefik'`, respectively. 
END
Enclosing the "disclaimer" so that the user understands this might or might not apply to them, depending on their situation. Doing this to stay consistent with other parts of the documentation where slight variations of X/Y process are highlighted with a `!!!note`. E.g:
- https://github.com/argoproj/argo-cd/blob/master/docs/developer-guide/toolchain-guide.md?plain=1#L35-L36
- https://github.com/argoproj/argo-cd/blob/master/docs/developer-guide/toolchain-guide.md?plain=1#L236-L237

**Comment by nikzayn** [comment]
@francRang I would like to take this up.!

/assign
