### ISSUE TITLE
AppSet degraded on v2.9.0-rc2- "" is invalid: patch: Invalid value

### ISSUE THREAD

**Issue by shuker85** [argoproj/argo-cd#15900]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'd deployed an upgrade from v2.8.3 to v2.9.0-rc2 (custom build image), and the appsets turned into degraded state.

**To Reproduce**

ApplicationSet: https://gist.github.com/shuker85/787faba4ad3818370a49b5f0b0603095 (it did not fit also in the max comment size here) , but we've `serverSideApply: true`

This was working fine on v2.8.3
**Expected behavior**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
@alexmt I suspect that this is associated with the change from `Update` to `Patch`: https://github.com/argoproj/argo-cd/pull/15514

**Comment by shuker85** [comment]
`git revert 21672a2a8373adca5cc0203b09d5f65521928d58` and build from that fixes the issue for me

**Comment by alexmt** [comment]
working on it!
