### ISSUE TITLE
Introduce KeptnWorkloadVersion CRD support instead KeptnWorkloadInstance

### ISSUE THREAD

**Issue by odubajDT** [argoproj/argo-cd#15922]
# Summary

Keptn CRD `KeptnWorkloadInstance` was renamed in `KeptnWorkloadVersion` in `lifecycle.keptn.sh/v1alpha4`. It would be awesome if this change can be reflected also in ArgoCD 

# Motivation

Keep supported ArgoCD resources up-to-date with the latest CRDs from Keptn project

# Proposal

Instead of supporting `KeptnWorkloadInstance` CRD of version `lifecycle.keptn.sh/v1alpha2` ArgoCD should support `KeptnWorkloadVersion` of version `lifecycle.keptn.sh/v1alpha4`.

**Comment by crenshaw-dev** [comment]
Should we continue to support the old name, for folks who aren't the new name yet?

**Comment by odubajDT** [comment]
> Should we continue to support the old name, for folks who aren't the new name yet?

I guess yes, thanks for the feedback!

**Comment by mowies** [comment]
We have new version of almost all Keptn CRDs by now, I think we need to update a few more things now.
I will create a new ticket to update the versions :)
