### ISSUE TITLE
Create secrets with password for local users

### ISSUE THREAD

**Issue by slawekww** [argoproj/argo-cd#15923]
# Summary

ArgoCD supports local users even if SSO is enabled and it is great.
Once `admin` user wants to be disabled and replaced by another user,
it is not possible to retrieve initial password for custom user.
The only option is to login as `admin` to argocd CLI and update-password.
Once `admin` user is disabled, it is not possible to do it.

# Motivation

Once admin user is replaced with another user,
it should be possible to retrieve its password from secret like it is for admin user.
It would improve security of ArgoCD, do not expose `admin` user and use custom admin user.

# Proposal

Create secret like ` argocd-initial-${user}-secret` with initial password. It could be optionally as parameter to account like:
`accounts.alice.secret: "true"`

**Comment by trexx** [comment]
It maybe a bit more gitops friendly to be able to manage local users without resorting to a cli tool.

**Comment by elouanKeryell-Even** [comment]
I would like to have this feature too

my team's use-case: automate creation of local service accounts for certain specific tasks

**Comment by talha-naeem1** [comment]
+1, it would be really awesome if we can automate creation of local accounts along with setting up their passwords

**Comment by awx-fuyuanchu** [comment]
You can set the password of the user in secret`argocd-secrets`. Is that what you need?

**Comment by slawekww** [comment]
I want to have it automated by adding `accounts.alice.secret: "true"` to config instead of modify k8s secret `argocd-secret`.
Could modification of  k8s secret `argocd-secret` be managed by argoCD itself?

Please note that goal is to replace default user `admin` with different name.

**Comment by crenshaw-dev** [comment]
My understanding of the use cases:
* automate password generation
* disable admin account and update password from a non-admin account

I think the former is a bad idea and the latter is possible today.

Using Argo CD to generate the initial password and store it means Argo stores the password as plaintext. It's safer/better to generate the password, save it in a password manager, store the hash with Argo, and discard your plaintext copy. If Argo CD generates the plaintext password, Argo CD can't discard it because it doesn't know when you've safely stored it elsewhere.

Disabling the admin account is possible, because you can grant a new account permissions to update passwords:

```
p, admin-with-a-different-name, accounts, update, *, allow
```

Argo CD isn't a password manager, and it shouldn't be used as such. Whenever possible, we should store a hash instead of a plaintext password.

**Comment by slawekww** [comment]
Thank you. In this case, lets close this feature request.

**Comment by saulrobe** [comment]
Kind of what @theblop said, it would be very useful to set the passwords for local users to reference a secret. Right now I can set the password of a local user in the secret cm. So in the helm chart values I am passing in something like
```
configs:
  secret:
    extra:
      accounts.bob.password: $2a$10...
  cm:
    accounts.bob: login,apiKey
    ...
```
and this works for setting the password for a local user. But, it is not idea to save the values as that is insecure. It would be great if I could reference a secret similar to how you can in other areas of the configuration. For example,
```
configs:
  secret:
    extra:
      accounts.bob.password: $bob-secret-name:password
  cm:
    accounts.bob: login,apiKey
    ...
```
where this would get set the password to the value found in the secret named bob-secret-name under the password key.

As of today this is not working. I am using the helm chart 8.1.3 which deploys argocd version 3.0.11.

This would be more gitops friendly as it is safe to store the secret name but not the value itself in the values.yaml. So, today I have to manually run the argocd cli to set a password of the local accounts if I spin up argocd or add a new local account.

I am not sure if this is the intent of this issue. If so, can we reopen this? If not, I guess another request can be submitted, or you can point me to one if it already exists. 

Thanks!
