### ISSUE TITLE
Promote via GUI

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-cd#1593]
Any plans to add Promote feature in Argo-cd GUI?

Example: to promote canditates in "dev branch" to "stage branch" for deployment manifest repo !!

**Comment by alexec** [comment]
I don't believe this is on our roadmap. You'd execute a promotion typically using your CI tool (e.g. Jenkins) by committing to you production config repo.

Maybe this is useful reading? https://argoproj.github.io/argo-cd/user-guide/best_practices/

**Comment by dgreene1** [comment]
@emichaf, may I ask what tool you ended up using for promotions?
