### ISSUE TITLE
Argo-cd synchronisation hangs when using PreSync hooks

### ISSUE THREAD

**Issue by DimitarKapashikov** [argoproj/argo-cd#1594]
**Describe the bug**
When PreSync hooks are used argo-cd synchronisation hangs. Log message : 
Stopping after PreSync phase due to modifications to hook resource state application=jobs

**To Reproduce**
1. Go to https://github.com/DimitarKapashikov/kapashikov_test/tree/master/job
2. Click on Create a new application in argo-cd
3. Scroll down to Sync application
4. See error CRDs are no synched , synchronisation hangs

**Expected behavior**
CRDs are installed

**Screenshots**
![Screen Shot 2019-05-09 at 15 51 34](https://user-images.githubusercontent.com/11851533/57454962-b29d4400-7272-11e9-85d1-95b628f26563.png)
![Screen Shot 2019-05-09 at 15 51 22](https://user-images.githubusercontent.com/11851533/57454966-b4ff9e00-7272-11e9-83ea-0240b572013f.png)

**Additional context**

**Comment by alexec** [comment]
Looks legit.

**Comment by kingjpc** [comment]
I have also hit this bug. Initial investigation points to ClusterRole/ClusterRoleBinding as they do not have a namespace assigned to them in kube and it appears that argo sets namespaces to a default one if its not present in the base Yaml.

**Comment by alexec** [comment]
Upcoming changes to how apps are synced might fix this issue.

**Comment by DimitarKapashikov** [comment]
I have tested with the latest release, the issue still persists.

**Comment by alexec** [comment]
Can you please try with 1.1.0-rc1?

**Comment by DimitarKapashikov** [comment]
Hi,

I have tried with 1.1.0-rc1, but the issue still persist, see screenshot.

Regards,
Dimitar

![Screen Shot 2019-06-19 at 12 08 33](https://user-images.githubusercontent.com/11851533/59752636-4c510b80-928b-11e9-9c1e-b093aa8cffe6.png)

**Comment by alexec** [comment]
Investingating.

**Comment by alexec** [comment]
Hi - @DimitarKapashikov are you able to give a bit of context on why you're doing this please?

You may find that removing the namespace from the object fixes this.

**Comment by DimitarKapashikov** [comment]
Hi @alexec I am trying to automate the installation of cert manager in one chart. In order to do it, I need a job which sets the label on the namespace cert-manager before applying the other resources.
https://docs.cert-manager.io/en/latest/getting-started/install/kubernetes.html

**Comment by alexec** [comment]
Thank you. This is fixed in v1.1.
