### ISSUE TITLE
Flaky unit test TestHandleDeleteEvent_CacheDeadlock

### ISSUE THREAD

**Issue by leoluz** [argoproj/argo-cd#15955]
[This PR](https://github.com/argoproj/argo-cd/pull/14780) (https://github.com/argoproj/argo-cd/pull/14780) introduced a new unit test to validate that the fix was addressing the problem. However the unit test is randomly failing with:

```
=== Failed
=== FAIL: controller/cache TestHandleDeleteEvent_CacheDeadlock (0.00s)
    cache_test.go:192: EnsureSynced has obtained lock on gitops-engine
    cache_test.go:202: 
        	Error Trace:	/home/runner/work/argo-cd/argo-cd/controller/cache/cache_test.go:202
        	Error:      	Not equal: 
        	            	expected: "PASSED"
        	            	actual  : "DEADLOCKED -- Invalidate could not obtain lock on gitops-engine"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-PASSED
        	            	+DEADLOCKED -- Invalidate could not obtain lock on gitops-engine
        	Test:       	TestHandleDeleteEvent_CacheDeadlock
        	Messages:   	DEADLOCKED -- Invalidate could not obtain lock on gitops-engine

DONE 3996 tests, 5 skipped, 1 failure in 695.223s
make: *** [Makefile:402: test-race-local] Error 1
Error: Process completed with exit code 2.
```
[Example build with failing test](https://github.com/argoproj/argo-cd/actions/runs/6503312144/job/17663677408?pr=15938)

**Comment by leoluz** [comment]
fyi @nromriell

**Comment by nromriell** [comment]
I did have some concerns about that test, primarily because it had to be extremely specific to reproduce the exact condition inside a linear test case

I can remove the test as it did serve its purpose in proving the case, although it is interesting that there is a condition causing it to fail
