### ISSUE TITLE
Support for verification of git SSH commit signatures

### ISSUE THREAD

**Issue by wiktor-k** [argoproj/argo-cd#16007]
# Summary

Currently, ArgoCD [supports verification of GPG signatures](https://github.com/argoproj/argo-cd/issues/2492) but ever since that was introduced git added support for a simpler scheme: [SSH signatures](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-signature-verification). 

git SSH signatures are now widely supported by GitHub, Gitlab, Gitea, (not mentioning the git tooling itself which introduced that).

# Motivation

In some sensitive environments, signing of Git commits using digital signatures and only considering the signed ones might be a security requirement. Moreover git allows specifying [allowedSignersFile](https://docs.gitlab.com/ee/user/project/repository/signed_commits/ssh.html#verify-commits-locally) that defines which keys are authorized to sign commits for the repo (there's no need for any additional special format for authorizations).

# Proposal

I've checked the [issue which discusses GPG signatures](https://github.com/argoproj/argo-cd/issues/2492) and I think it would be even simpler: no additional certificates/public keys are to be managed since SSH signatures contain the public keys that issued them. One thing to additionally store would probably be the [`allowed_signers` file](https://man7.org/linux/man-pages/man1/ssh-keygen.1.html#ALLOWED_SIGNERS).

In [my repositories](https://github.com/wiktor-k/ssh-signing) I store that file inside the repo, so that introducing new keys can be only done using existing keys, but others may have different preferences: for example using one centralized `allowed_signers` file.

**Comment by hex-m** [comment]
OpenSSH supports physically protected SSH-keys by using a [FIDO authenticator](https://man.openbsd.org/ssh-keygen#FIDO_AUTHENTICATOR). FIDO authenticators are common and well supported by now - more so than devices supporting the "OpenPGP card"-standard.

This feature would make it easier to use hardware-protected private keys and thus would increase the practical security for many users.

**Comment by wiktor-k** [comment]
This sounds like a duplicate of https://github.com/argoproj/argo-cd/issues/8733 that you've linked so I'm going to close this one.

> FIDO authenticators are common and well supported by now - more so than devices supporting the "OpenPGP card"-standard.

Yes, they are also significantly cheaper than OpenPGP Card devices. (Agreed with everything else, obviously!)
