### ISSUE TITLE
Endpoints not ignored by ArgoCD Application Controller

### ISSUE THREAD

**Issue by sidewinder12s** [argoproj/argo-cd#16023]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

The resource exclusion docs seem to indicate that `Endpoints` should be excluded/not presented and tracked in ArgoCD: https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#resource-exclusioninclusion

I am still seeing them in our ArgoCD UI however.

I've generally been chasing down Application controller perf issues that seem to be rooted in extremely active clusters cause excessive reconciliation triggering. A few of the items that seem to trigger it are Endpoints, EndpointSlices, DaemonSet updates largely driven by cluster autoscaling.

**To Reproduce**

Deploy a service with endpoints, check UI for endpoints object

**Expected behavior**

Services should not be tracking the endpoint object.

It appears adding endpoints explicitly to `resource.exclusions` has them ignored by ArgoCD.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/1393426/4e760960-338a-46d4-9f16-105893e15f1a)

**Version**

```shell
argocd: v2.7.14+a40c95a
  BuildDate: 2023-09-07T17:39:29Z
  GitCommit: a40c95a6383baa0d9f670586a5c295021f59337c
  GitTreeState: clean
  GoVersion: go1.19.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.7.14+a40c95a.dirty
  BuildDate: 2023-09-07T16:50:47Z
  GitCommit: a40c95a6383baa0d9f670586a5c295021f59337c
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

References:

https://github.com/argoproj/gitops-engine/pull/469
https://github.com/argoproj/argo-cd/issues/8175

**Comment by agaudreault** [comment]
Added to 3.0 milestone with https://github.com/argoproj/argo-cd/issues/20013 to change the default **configurable** settings. The current behavior is expected not to exclude Endpoints by default, but doc was not up-to-date.
