### ISSUE TITLE
[UI] Refresh button from table and card view

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1606]
I often need to refresh a bunch of apps from the table or card view. We have Sync and Delete but not Refresh.

**Comment by alexec** [comment]
@jessesuen I've done an implementation using normal refresh - do you want option for hard refresh?

**Comment by jessesuen** [comment]
> @jessesuen I've done an implementation using normal refresh - do you want option for hard refresh?

Don't think hard refresh is necessary.
