### ISSUE TITLE
Documentation on missing Applications is not clear

### ISSUE THREAD

**Issue by ls-julien-deruere** [argoproj/argo-cd#16067]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

This part of the documentation is unclear, both sentences are saying contrary  meaning.

> All endpoints of the Applications API accept an optional project query string parameter. If the parameter is specified, and the specified Application does not exist, or if the Application does exist but is not in the given project, the API will return a 404 error.

> If the project query string parameter is specified, and the Application does not exist, the API will return a 403 error. This is to prevent leaking information about the existence of Applications to users who do not have access to them.

Can be found here:

https://argo-cd.readthedocs.io/en/stable/developer-guide/api-docs/#how-to-avoid-403-errors-for-missing-applications

**Comment by Priyanshuthapliyal2005** [comment]
Can you assigned this issue to me.

**Comment by Priyanshuthapliyal2005** [comment]
can you review it again sir @crenshaw-dev
