### ISSUE TITLE
Got error while deploy on listed cluster which connection status successful

### ISSUE THREAD

**Issue by continuum-vikrant-tyagi** [argoproj/argo-cd#1607]
**Describe the bug**
We have added different kuberenetes cluster and it's status successful in Argo-CD UI. but while deploying guestbook application on that cluster facing error related to user.

User "system:serviceaccount:default:default"

ComparisonError
volumeattachments.storage.k8s.io is forbidden: User "system:serviceaccount:default:default" cannot list volumeattachments.storage.k8s.io at the cluster scope

we have created a new service account on the other cluster and pass the bearer token.

Please help!!

**Comment by alexmt** [comment]
Looks like credentials has a token which belongs to account without admin permissions. By default argocd tries to monitor all cluster resources. If you don’t want to prevent access to some resources when you can use a resource exclusion setting: https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#resource-exclusion

**Comment by alexmt** [comment]
Closing issue since described behavior is expected as correct

**Comment by continuum-vikrant-tyagi** [comment]
well it works with default user token, not with the new user having admin privilege.

how we can say argo-cd to execute with custom user not with the default one?
