### ISSUE TITLE
Cannot select different container on logs page in v2.8 in Firefox

### ISSUE THREAD

**Issue by noahburrell0** [argoproj/argo-cd#16083]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Upon opening and mousing over the container dropdown on the pod logs page, you will be unable to select a different container.

The issue appears to be present in all 2.8.x versions, but is not in 2.7.x. It only seems to affect Firefox. I am using Firefox v118.0.2, but I'm not sure if it effects other versions.

**To Reproduce**

Create an application that deploys a pod with multiple containers. Go to the logs page in Firefox and try to select a different container from the dropdown.

**Expected behavior**

Clicking on another container should allow you to view the logs for that container.

**Screenshots**

![](https://i.imgur.com/kh2RItN.gif)

**Version**

```shell
argocd: v2.8.4+c279299.dirty
  BuildDate: 2023-09-13T20:25:25Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: dirty
  GoVersion: go1.21.1
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.8.4+c279299
  BuildDate: 2023-09-13T19:12:09Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Comment by Jared0430** [comment]
This is still happening as of v2.10.2, tested in Firefox 123.0.1 and Floorp (Firefox fork) 11.10.5

One thing I've noticed is if you disable the "Follow logs automatically" feature, you can then change container without issue

**Comment by lsq645599166** [comment]
It seems fixed in https://github.com/argoproj/argo-cd/pull/19856
