### ISSUE TITLE
Add new metrics

### ISSUE THREAD

**Issue by mikel-m** [argoproj/argo-cd#16094]
Hi,

I'm trying to obtain some metrics from ArgoCD related, for example, to retrieving application synchronization time. I've noticed that such metrics are not available. Could additional metrics like application synchronization time be added to ArgoCD?

**Comment by rumstead** [comment]
Is the reconcile bucket metric too coarse?

**Comment by mikel-m** [comment]
My idea is to gather as much information as possible about the deployment of an application in ArgoCD to create my own dashboard in Grafana with that information. So, for example, I found it interesting to know how long it takes for an app to synchronize, but I don't know how to obtain those kinds of metrics.

**Comment by leoluz** [comment]
We already have the `argocd_app_reconcile` metric as [documented here](https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/). Keep in mind that adding the application name as part of the metrics label will crash prometheus for users with thousands of ArgoCD applications.

**Comment by leoluz** [comment]
Closing this for now. Reopen if you want to discuss further.
