### ISSUE TITLE
Improve Kustomize 2 parameters UI

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1609]
**Is your feature request related to a problem? Please describe.**

The Parameters tab of Kustomize 2 apps should be as usable as Kustomize 1. With kustomize 1 UI user can quickly see the images and have simple UI to change image tags. With Kustomize 2 user seeing nothing in view mode, unless images are overridden. In edit mode UI only provides text input to override image.

**Describe the solution you'd like**
The view mode should be similar to Kustomize 1. Edit mode should allow using Kustomize 2 features ( e.g. set new name )

![image](https://user-images.githubusercontent.com/426437/57640442-6cdcc600-7567-11e9-990a-f2074ae3cf06.png)

![image](https://user-images.githubusercontent.com/426437/57640479-7c5c0f00-7567-11e9-8297-a357635f0c96.png)

**Comment by alexec** [comment]
I'm not sure about this. It brings a LOT of logic into the UI. It was an explicit decision to dumbly pass the images to kustomize, to keep the code simple while making sure no power was abstracted away.

**Comment by alexmt** [comment]
Apparently there is not so much logic, just two functions: parse and format: https://github.com/argoproj/argo-cd-ui/pull/125/files#diff-15133e3112f57e4790c0b0773d329c66R14

The rest of changes are UI related. I think it worth support it because it really increases usabilty of UI for kustomize apps.

**Comment by alexmt** [comment]
Implemented

**Comment by alexec** [comment]
I've added milestone.
