### ISSUE TITLE
bug(ui): Resource Kind NodeGroup is not aligned

### ISSUE THREAD

**Issue by speedfl** [argoproj/argo-cd#16097]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using a resource Kind NodeGroup (ie: ACK Controller NodeGroup), the UI is adding an extra 25px padding top

The issue come from the fact that any object suffixed by `--nodegroup` has an extra 25px

https://github.com/argoproj/argo-cd/blob/5d3bdb5bd01cd3836db4ae3172bbd2630c7a51c3/ui/src/app/applications/components/application-resource-tree/application-resource-tree.scss#L153

https://github.com/argoproj/argo-cd/blob/5d3bdb5bd01cd3836db4ae3172bbd2630c7a51c3/ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx#L744

Issue that introduce this feature: https://github.com/argoproj/argo-cd/issues/12089

**To Reproduce**

Deploy the ACK controller EKS: https://github.com/aws-controllers-k8s/eks-controller/tree/main

Create a resource NodeGroup

**Expected behavior**

Must be aligned

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/23298035/2f3fd386-6548-494a-bd88-1af0256a2e3b)

**Version**

All

**Comment by cclp94** [comment]
I'll prepare a PR for this. I think in renderResourceNode we could add a new css class for resource nodes  only that overwrites the padding

**Comment by keithchong** [comment]
I'm wondering if we can just get rid of the nodegroup style from the scss file, since it seems to only affect the _nodegroup_ resource kind. 

cc @ashutosh16

**Comment by speedfl** [comment]
Node group is also used to group the nodes like pod group I guess

**Comment by cclp94** [comment]
I finally had the time to deep into this. I think @keithchong is right. A "Grouped Node" would pass by another function `renderGroupedNodes` which doesn't add the `'application-resource-tree__node--' + node.kind.toLowerCase(),` class like the `renderResourceNode` does. Therefore, it looks safe to just remove it.
