### ISSUE TITLE
Document all available fields in example applicationset.yaml

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#16095]
# Summary

The [example applicationset.yaml](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/applicationset.yaml) does not contain all possible fields. It should be complete, like [application.yaml](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml).

# Motivation

Seeing everything in one file is much easier than digging through docs.

# Proposal

Dig through the [ApplicationSet docs](https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/) and add every available field to the applicationset.yaml file linked above.

**Comment by crenshaw-dev** [comment]
@prashantrewar feel free to dive in, we generally don't fuss with the assignment system on smaller tasks. :-)

**Comment by akagami-harsh** [comment]
can i give it a try
