### ISSUE TITLE
API  POST /v1/repo should trim whitespaces before saving username

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#161]
Users often save username with new line character. API should trim whitespaces to avoid confusion

**Comment by merenbach** [comment]
Sounds like a pernicious bug!  `util/cli/cli.go#PromptCredentials` trims whitespace currently from both ends of usernames.  I'm also having trouble reproducing with a command-line supplied username.  If we can find out more about the CLI version and environments involved, we may be able to track this down more easily.

**Comment by alexmt** [comment]
@jessesuen mentioned that argocli had a bug and was creating username with a new line. @merenbach can you please implement trimming on API side in case some still uses old argocli?
