### ISSUE TITLE
Change ApplicationSets generators docs to use go templates

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#16109]
# Summary

The ApplicationSet docs currently use fasttemplates by default. The new standard is go templates.

# Motivation

Fasttemplate support will be removed in Argo CD 3.0.

# Proposal

Go through all the generators' pages here: https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Generators/

Switch all examples to show go templates, according to the migration guide: https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/GoTemplate/#migration-guide

**Comment by KunalSin9h** [comment]
working on it

**Comment by KunalSin9h** [comment]
@crenshaw-dev i have open a draft pr which i will incrementally update the docs upon approval, can you review it.

**Comment by crenshaw-dev** [comment]
@KunalSin9h that's looking amazing, thank you! Feel free to mark as ready for review whenever.

**Comment by KunalSin9h** [comment]
@crenshaw-dev i have done every generators, can you review it
