### ISSUE TITLE
Argo doesn't recongize diffs from kubectl edit

### ISSUE THREAD

**Issue by cchanley2003** [argoproj/argo-cd#1613]
**Describe the bug**
 Not sure if this is a bug or feature but if I kubectl edit  a deployment by adding a new environment variable ( this maybe true of annotations/labels etc) Argo CD doesn't recongized it as a difference
**To Reproduce**
1. kubectl edit deployment/app
2. Add a new environment variable
3. :wq

**Expected behavior**
Would expect argo to say out of sync, instead says in-sync
**Screenshots**

**Version**

```shell
v0.12.0+cd4bb25
```

**Logs**

```
None
```

**Comment by alexmt** [comment]
This behavior is expected. Argo CD follows the same logic is `kubectl diff` and report differences only if field value conflicts with value defined in git or in `last-applied-configuration` annotation. This allows to leave room for automation such as replicas etc: https://argoproj.github.io/argo-cd/user-guide/best_practices/#leaving-room-for-imperativeness
