### ISSUE TITLE
Improve diff support for resource requests/limits

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1615]
The following diff is a common problem with CRDs. Argo CD reports the following as OutOfSync:

![image](https://user-images.githubusercontent.com/12677113/57735789-a93d1e80-765a-11e9-83ee-74c65db5777c.png)

![image](https://user-images.githubusercontent.com/12677113/57736163-de963c00-765b-11e9-95af-cbe109acdec7.png)

The reason is because the resources field uses IntOrString data type and what gets marshalled is inconsistent with what is in git.

We should see what we can do to auto-detect resource limits/requests equivalences and ignore these differences.

**Comment by jessesuen** [comment]
Here are the different cases on how resource.Quantity get's normalized:
```
Case 1:
        resources:
          requests:
            cpu: 1
        resources:
          requests:
            cpu: '1'
        resources:
          requests:
            cpu: 1000m

  Normalized to: '1'

Case 2:
        resources:
          requests:
            cpu: 100m
        resources:
          requests:
            cpu: '0.1'
        resources:
          requests:
            cpu: 0.1

  Normalized to: 100m

Case 3:
        resources:
          requests:
            memory: 3Gi
        resources:
          requests:
            memory: 3072Mi

  Normalized to 3Gi

Case 4:
        resources:
          requests:
            memory: '3072'
        resources:
          requests:
            memory: 3072

  Normalized to '3072'
```

**Comment by jessesuen** [comment]
Not fixed

**Comment by alexec** [comment]
What are you thoughts on solving this @jessesuen ?
