### ISSUE TITLE
Synchronization triggers both PostSync and SyncFail events even on successful sync

### ISSUE THREAD

**Issue by pasha-codefresh** [argoproj/argo-cd#16177]
When synchronizing an application with the server-side apply, it has been observed that both the `PostSync` and `SyncFail` events are triggered, even when the application sync is successful. This issue appears to be related to the way ArgoCD executes a dry run before each synchronization, utilizing the `DryRunClient` based on the `applyObject` function inside `sync_context.go`. The problem arises from the fact that the `DryRunClient` is ignored inside `apply.go` due to the following code:

```
helper := resource.NewHelper(info.Client, info.Mapping).
    DryRun(o.DryRunStrategy == cmdutil.DryRunServer).
    WithFieldManager(o.FieldManager).
    WithFieldValidation(o.ValidationDirective)
```

**Steps to Reproduce:**

To reproduce this issue, follow these steps:

1. Add hooks to your repository.

1. Perform a synchronization from the UI with the "dry run" and "server-side apply" options enabled.

**Comment by anuragtamrakar** [comment]
That's great, Kudos!

**Comment by crenshaw-dev** [comment]
Reopening since we need an argo-cd PR to bump the gitops-engine version. :-)

**Comment by pasha-codefresh** [comment]
@crenshaw-dev i still didnt open pr for update gitops engine :) doing it now
