### ISSUE TITLE
[appset in any namespace] ApplicationSet with same name in different namespaces conflict

### ISSUE THREAD

**Issue by speedfl** [argoproj/argo-cd#16207]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When creating two ApplicationSet with same name in two different source namespaces. The name conflict in the applicationset-controller and the source namespace for the application is not taken into account resulting in infinite loop deleting child applications and re-triggering reconcile loop. Logs attached

Quick fix: Ensure there are no name conflicting

**To Reproduce**

- Activate [appset in any namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Appset-Any-Namespace/)
- Create two appset in different namespace with different behavior with same name

**Expected behavior**

**Screenshots**

**Version**

```json
{
    "Version": "v2.8.4+c279299",
    "BuildDate": "2023-09-13T19:12:09Z",
    "GitCommit": "c27929928104dc37b937764baf65f38b78930e59",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}

```

**Logs**

```
time="2023-11-01T15:44:12Z" level=info msg="Deleted application" app=my-app-one appSet=my-application-set
time="2023-11-01T15:44:12Z" level=info msg="created Application" app=my-app-one appSet=my-application-set
time="2023-11-01T15:44:13Z" level=info msg="unchanged Application" app=my-app-one appSet=my-application-set
```

**Comment by speedfl** [comment]
Looking at the code it seems that owner reference is not working with Namespace:
https://github.com/kubernetes-sigs/controller-runtime/blob/edb7fe9c520ef2eb5e7d54ded35734bd9a10d71d/pkg/controller/controllerutil/controllerutil.go#L75

Continuing my investigation. Maybe a simple error in the applicationset conditions if conflict name are found could be a suitable solution

**Comment by speedfl** [comment]
After looking deeper it seems that `createInCluster` and `deleteInCluster` are not taking into account appset namespace:

- `createInCluster`: https://github.com/argoproj/argo-cd/blob/51b4b20211580e79bfb853f9779be510787311bf/applicationset/controllers/applicationset_controller.go#L719
- `deleteInCluster`: https://github.com/argoproj/argo-cd/blob/51b4b20211580e79bfb853f9779be510787311bf/applicationset/controllers/applicationset_controller.go#L766

Looking at the other impacts

**Comment by reedjosh** [comment]
https://github.com/argoproj/argo-cd/issues/16114

**Comment by speedfl** [comment]
Looking at the code I don't think `createOrUpdate` will cause issues as it relies on ObjectKeyFromObject‎ which is using namespace and name. 
I will write an integration test to validate the fix for `createInCluster` and `deleteInCluster`. Purpose of the fix is to use the objectKey for the maps

**Comment by speedfl** [comment]
I reproduced a sample usecase that can be run locally using `make start-local`.
Looking now at the fix.

https://github.com/speedfl/argocd-example-apps/tree/feature/appset-name-conflict/appset-name-conflict

**Comment by speedfl** [comment]
I tested a fix. I will push an MR soon

**Comment by speedfl** [comment]
The fix has been tested locally. Having some issues in writting e2e. Continuing my investigation

**Comment by speedfl** [comment]
I added an e2e test. It was not so easy to update the environment to support another external namespace. 
I let reviewers take a look to it
