### ISSUE TITLE
Add flag to disable auto launching browser for SSO

### ISSUE THREAD

**Issue by jashandeep-sohi** [argoproj/argo-cd#16208]
# Summary

Add a flag `--sso-launch-browser` that can disable the current behavior of auto launching a browser to complete the SSO flow.

# Motivation

I'm using multiple browsers (with multiple profiles) for different environments (Github accounts, etc). With the current behavior of just using the system default browser, I'm not able to complete the SSO flow with correct account. I'd like to be able to just copy-paste the URL to the appropriate browser window and complete the flow manually.

# Proposal

Add a flag that can enable (default) or disable launching the browser at https://github.com/argoproj/argo-cd/blob/51b4b20211580e79bfb853f9779be510787311bf/cmd/argocd/commands/login.go#L327C11-L327C11

**Comment by slammajamma28** [comment]
I'm interested in this feature as my current work setup always launches a browser with an account that is not configured for ArgoCD access. Would prefer to copy and paste the auth URL into the proper browser with the correct user.

When can we expect to see it in a release?
