### ISSUE TITLE
Anonymous readOnly access to WebUI

### ISSUE THREAD

**Issue by mcserbak** [argoproj/argo-cd#1620]
I'm looking into avoiding usage of a separate authorization path for access to ArgoCD CRs via the k8s API and the web UI (I see roadblocks on the way to integrating our current deployment strategy of ArgoCD with our SSO provider).

I'd like to rely fully on the k8s authentication flow.

This use-case seems to be covered by https://github.com/argoproj/argo-cd/issues/1283, however it would be nice to provide the visualization of changes the WebUI provides to the dev teams.

Thus, I'm looking for a way to provide anonymous read only access to the WebUI.

**Comment by alexec** [comment]
@mcserbak I'd like to check - all you're after is a read-only view?

**Comment by mcserbak** [comment]
An unauthenticated read-only access.

**Comment by alexec** [comment]
@jessesuen I'd like to get your thoughts on this. There's a lot of community up-votes.

**Comment by alexec** [comment]
Regression testing comments:

* Enabled locally, and used private browsing to compare the experience
* https://localhost:8080/applications - none of the apps are listed
* https://localhost:8080/settings/repos - can't see configured repos.
* https://localhost:8080/settings/certs - get the error  "Unable to load data: permission denied: certificates, get,"
* https://localhost:8080/settings/clusters - blank page, no errors in the console.
* https://localhost:8080/settings/projects - blank page.
* https://localhost:8080/help - ok
* https://localhost:8080/download/argocd-linux-amd64 - ok
* https://localhost:8080/swagger-ui - ok
* create app:
  * cannot see clusters - ok
  * submitting gets 'Unable to create application: permission denied: applications, create, default/demo' - as expected

**Comment by alexec** [comment]
@alexmt - re-opening issue so we can discus

**Comment by alexec** [comment]
Ok, so the issue was my set-up, the following RBAC makes everything work as expected:

```
data:
  policy.default: role:readonly
```

**Comment by alexec** [comment]
* Create repo - denied
* Delete repo - denied
* Add TLS cert - denied
* Add SSH know host - denied
* Remove cert - denied
* Add a cluster - timeout
* Remove a cluster - denied
* New app - denied
* Sync app - denied
* Delete app - denied
