### ISSUE TITLE
Shared resource warning for two argoCd applications that are deploying resources to different clusters and application names are different

### ISSUE THREAD

**Issue by NearchPasipou** [argoproj/argo-cd#16213]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have one argoCD deployment.

In this argoCD I have two argoCD applications:
One named "myapp-cluster1" and the other "myapp-cluster2"
The resources of those application are deployed on different clusters, but are otherwise identical (desired manifest is the exact same).
The resources are not namespaced (global resources)

One of those global resources is producing a shared resource warning:

SharedResourceWarning
LicenseKey/default is part of applications argocd/myapp-cluster1 and myapp-cluster2

and they produce a diff of (argocd.argoproj.io/instance: <the name of the app>)

**To Reproduce**
One argoCD
Two argoCD apps, app name is different, identical resources, deploy on different clusters

**Expected behavior**
Expected behavior is not to have the resource warning since the resource is deployed on different clusters.

**Screenshots**

**Version**
{
    "Version": "v2.6.7+5bcd846",
    "BuildDate": "2023-03-23T14:57:27Z",
    "GitCommit": "5bcd846fa16e4b19d8f477de7da50ec0aef320e5",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jgwest** [comment]
@NearchPasipou can you provide YAML output for the two resources that Argo CD has identified as being in conflict, and also the Argo CD Application YAML that deploy those resources?
