### ISSUE TITLE
Support GitLab Groups as Git Repositories in ArgoCD

### ISSUE THREAD

**Issue by abelhoula** [argoproj/argo-cd#16231]
# Summary

Support GitLab Groups as Git Repositories in ArgoCD.

# Motivation
Organizations and users commonly organize their Git repositories under GitLab groups for improved management and organization. This feature would enhance ArgoCD's usability for such users by enabling the direct management of repositories within GitLab groups.

# Proposal

ArgoCD should be enhanced to support GitLab groups as Git repositories with the following changes:

* URL Support: ArgoCD should recognize and support GitLab group URLs in the format https://gitlab.com/group-name/**.

* Repository Discovery: Use GitLab's API to list repositories under the specified group and present them for user configuration in ArgoCD.

# Benefits:

* Simplifies management for users by allowing them to manage multiple repositories within a group using a single GitLab group URL.
* Aligns ArgoCD with common GitLab repository organization practices.

**Comment by rouke-broersma** [comment]
Perhaps I'm understanding the question wrong, but doesn't this already exist using repository credential templates?
See: https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#credential-templates

**Comment by abelhoula** [comment]
Thank you so much for your prompt response and the helpful suggestion!
