### ISSUE TITLE
ApplicationSet controller says allowed-scm-providers is required even if `applicationsetcontroller.allow.scm.providers` is false

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#16240]
If `applicationsetcontroller.allow.scm.providers` is `"false"`, there's no need for `allowed-scm-providers` to be set.

**Comment by juliuszjaksa** [comment]
I think has been fixed by update in documentation: 
https://github.com/argoproj/argo-cd/commit/5ffbca4cce5e305cff3d31f913906e35040e111b

Correct name of the property is `applicationsetcontroller.enable.scm.providers`
