### ISSUE TITLE
ArgoCD triggers a refresh for all apps in same repo when webhook has empty commit

### ISSUE THREAD

**Issue by aminedj** [argoproj/argo-cd#16255]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.
* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.

**Describe the bug**

I am using a monorepo to store plain yaml manifests, every ArgoCD Application points to a specific folder in the monorepo (same  spec.source.repoURL)

I have a GitLab webhook setup on my monorepo and all the ArgoCD application have the following annotation to only trigger a refresh on the paths present in the commit 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  annotations:
    # resolves to the 'guestbook' directory
    argocd.argoproj.io/manifest-generate-paths: .
```

When a Gitlab payload is posted with an empty commit like this (payload truncated to only show relevant `commits` object):
```json
"commits": [
    {
      "id": "ddeae3fcb09c0d",
      "message": "empty commit\n",
      "title": "empty commit",
      "timestamp": "2023-11-06T20:01:41+00:00",
      "url": "https://gitlab.com/xxxxxxxx/-/commit/ddeae3fcb09c0d",
      "author": {
        "name": "xxxxxxx",
        "email": "[REDACTED]"
      },
      "added": [

      ],
      "modified": [

      ],
      "removed": [

      ]
    }
  ],
  "total_commits_count": 1,
```

ArgoCD will trigger a refresh for all apps from the repo and will not honor the `argocd.argoproj.io/manifest-generate-paths: .` annotation

**To Reproduce**

- Have at least 2 Applications with the  `argocd.argoproj.io/manifest-generate-paths: .`  annotation with the same spec.source.repoURL
- Make an empty commit on on the Gitlab repo triggering a webhook payloads
- ArgoCD will refresh both Apps not honoring the `argocd.argoproj.io/manifest-generate-paths: .`  annotation

**Expected behavior**

ArgoCD should only trigger a sync if the path is present in the `commits` payload object

**Version**

```shell
argocd: v2.8.5+85025e1
  BuildDate: 2023-10-28T00:13:42Z
  GitCommit: 85025e1dcb683b192ea3599de0b0a196d64c94a7
  GitTreeState: clean
  GoVersion: go1.20.10
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.8.4+ebab8ec
  BuildDate: 2023-10-30T19:24:59Z
  GitCommit: ebab8ec6259a6997fa3f310cddc539cb0c76b442
  GitTreeState: clean
  GoVersion: go1.20.10
  Compiler: gc
  Platform: linux/amd64
  ExtraBuildInfo: {Vendor Information: Red Hat OpenShift GitOps version: v1.10.1}
  Kustomize Version: v5.1.0 unknown
  Helm Version: v3.12.1+g1b5d1f0
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Comment by robinlieb** [comment]
Hi @aminedj,
I added a PR which should fix this issue. 
The behaviour you observed was defined a couple years back as the default behaviour. I agree with you that your proposal would be the better solution. Maybe @alexmt still knows if there was a reason to make this the default behaviour?
Generally speaking, since this is changing the behaviour of the webhook functionality, it would probably make sense to release that one as a feature and not as a bug.

**Comment by agaudreault** [comment]
There was a fix to make sure this is the expected behavior. I think changing the behavior to support empty commit is a new enhancement. It will be important to differentiate between an empty commit and a SCM provider that does not support the list of changes in the webhook payload.

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and let us know if the issue is still present, please?
