### ISSUE TITLE
Global repo credentials doesn't work unless repo is listed

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1625]
The new `repository.credentials` feature doesn't appear to work, unless the repo is listed in the `repositories` section of the config. It fails with:

`Unable to create application: application spec is invalid: InvalidSpecError: No credentials available for source repository and repository is not publicly accessible: authentication required`

When repository credentials are configured for a domain or org, Argo CD should be able to deploy from any repo in that domain or org provided that the credentials work, without having to enter the repo in `repositories` list.

**Comment by alexec** [comment]
Working.

**Comment by alexec** [comment]
This is fixed in v1.1.

**Comment by jessesuen** [comment]
And v1.0.1

**Comment by alexec** [comment]
Added to v1.0.1
