### ISSUE TITLE
Add support for adding Jsonnet TLA arguments to ArgoCD CLI

### ISSUE THREAD

**Issue by iremmats** [argoproj/argo-cd#1626]
**Is your feature request related to a problem? Please describe.**
We are trying to dynamically create applications for each Pull Request created. To do that we need to create applications in ArgoCD based on our templates in Jsonnet and override the docker image tag and possibly other values. Right now ArgoCD supports TLA and extVar arguments but the only way to set them is to create the app manifest. Similar values for Helm and Ksonnet is supported by the CLI.

**Describe the solution you'd like**
I would like to be able to do this (pseudo syntax)
argocd app create -name myapp -type jsonnet --tla-parameteroverrides param1=value1,param2=value2 
 

**Describe alternatives you've considered**
An alternative is to use jsonnet to create the application manifest and then run argocd app create -f manifest.json

**Comment by alexec** [comment]
This looks great for a community contribution

**Comment by alexec** [comment]
You could probably do this cleanly using the “app patch” command.

**Comment by lcostea** [comment]
I can take a look and work on this, I have a pretty good idea on how to add those additional parameters. So please assign it to me.

**Comment by lcostea** [comment]
I added an example of a jsonnet that can use top level arguments. And I plan to use it for an e2e test once I add the option on the cli - actually the code is done, working on the test now. 
@alexec maybe you can take a look at the PR on the examples repo https://github.com/argoproj/argocd-example-apps/pull/30

**Comment by alexec** [comment]
Cool. Thank you @lcostea
