### ISSUE TITLE
Overriding Parameter won't work in ArgoCD Application which is configured from ApplicationSet

### ISSUE THREAD

**Issue by kworkbee** [argoproj/argo-cd#16276]
Checklist: 

- [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [X] I've included steps to reproduce the bug.
- [X] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD provides [Parameter Overrides](https://argo-cd.readthedocs.io/en/stable/user-guide/parameters/) feature, but it won't work when the application is configured from `ApplicationSet`.

**To Reproduce**

- Configure an `Application` from `ApplicationSet`.
- Override parameters through UI App Details.

**Expected behavior**

- Parameters must be overriden.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/18034626/081496a6-1c8c-492d-9609-ff88e4296ed3)
![image](https://github.com/argoproj/argo-cd/assets/18034626/770ec27c-78f8-4513-b78d-04f744525d59)

**Version**

The issue found in both the existing version and the latest version.

```shell
argocd-server: v2.9.0+9cf0c69
  BuildDate: 2023-11-06T04:43:50Z
  GitCommit: 9cf0c69bbe70393db40e5755e34715f30179ee09
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

```shell
argocd-server: v2.7.3+e7891b8.dirty
  BuildDate: 2023-05-24T15:05:34Z
  GitCommit: e7891b899a35dca06ae94965ea5ae2a86b344848
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
````

**Logs**

None

**Comment by rumstead** [comment]
In 2.9 there is the ability to ignore differences. https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Controlling-Resource-Modification/#ignore-certain-changes-to-applications

**Comment by kworkbee** [comment]
When the source of the individual application created through ApplicationSet is watching values.yaml in the Helm chart, it is still impossible to change the individual properties of values.yaml in the individual application, despite `ignoreApplicationDifferences`.

**Comment by rumstead** [comment]
What about using `helmParameters` instead?

**Comment by kworkbee** [comment]
@rumstead Are you talking about overriding to 'spec.source.helm.parameters' in ApplicationSet? But I don't think that's the fundamental answer if it's not using UI.

**Comment by rumstead** [comment]
You can change and ignore the individual parameters using `helmParamaters` which would allow you to make imperative changes via the UI.

**Comment by darren-recentive** [comment]
I had this problem and realized I was setting the incorrect `Expression` because the docs are incorrect.
https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#ignore-certain-changes-to-applications

does not work
```
spec:
    ignoreApplicationDifferences:
        - jqExpressions:
              - .spec.source.helm.parameters
```

works
```
spec:
    ignoreApplicationDifferences:
        - jqPathExpressions:
              - .spec.source.helm.parameters
```

Using ArgoCD `2.9.1`

**Comment by Belorus** [comment]
Doesn't work for me as well.
Both server & cli - 2.9.2

I added 
```
spec:
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.source.helm.parameters
```

After that `argocd app set binsponsorship.stg.app1  -p a=b`
If i keep UI open - override label blinks on the application and disappears.
Also in Events tab i see `ci_user updated application spec`

**Comment by crenshaw-dev** [comment]
@Belorus make sure your AppSet CRD is up to date, otherwise the new ignoreApplicationDifferences field will be completely dropped. 

The docs fix has been cherry-picked and will go out with 2.9.3.

**Comment by kworkbee** [comment]
Hi, @crenshaw-dev. It still doesn't work. The version 2.9.0 is in use, and CRD is not changed even though it is up to date, so please check it.

**Comment by krancour** [comment]
I am seeing the exact same problem with v2.9.3 and `.spec.source.kustomize.images`

**Comment by krancour** [comment]
> I am seeing the exact same problem with v2.9.3 and `.spec.source.kustomize.images`

I stand corrected. Not seeing this issue after all. My problem was something else entirely. 🤦‍♂️

**Comment by kworkbee** [comment]
@crenshaw-dev PTAL

**Comment by kworkbee** [comment]
![image](https://github.com/argoproj/argo-cd/assets/18034626/5920c14a-ac9e-400e-8b66-e3f5dfc7a3f9)
![image](https://github.com/argoproj/argo-cd/assets/18034626/3cead43f-b77c-4898-9371-03a33801a141)

@crenshaw-dev After upgrading to version 2.9.3, I tried to override a certain helm parameter, but it seemed to be changing and was restored to its original state.

```yaml
kind: ApplicationSet
spec:
  ignoreApplicationDifferences:
    - name: helm
      jqPathExpressions:
        - .spec.source.helm.parameters
```
Is there a problem with the YAML definition? Or let me know if there's anything I'm missing.

PTAL, Thanks ;)

**Comment by blakepettersson** [comment]
I bumped into the same error using 2.10.7 and 2.11.3. Will dig further to see why that is.

**Comment by blakepettersson** [comment]
Nope, this is not the case - this was something occurring only when I did this from Kargo. I could not otherwise repro this with `app set`, `kubectl apply` nor from the UI.

**Comment by bmalynovytch** [comment]
```
  ignoreApplicationDifferences:
  - jqPathExpressions:
    - .spec.source.helm.parameters
    - .spec.source.helm.values
    - .spec.sources[] | .helm.parameters
    - .spec.sources[] | .helm.values
  ```

Works like a charm 👍

**Comment by kworkbee** [comment]
@bmalynovytch Sorry for the late response. I just tried it and it works well :)
@andrii-korotkov-verkada Yes, Let me close it.
