### ISSUE TITLE
Multiple Sources workflow in the GUI is broken when using OCI repo for Helm and GitLab repo for override yaml files

### ISSUE THREAD

**Issue by lk-1984** [argoproj/argo-cd#16286]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

My goal is to create an application from Helm chart which is in ACR (OCI repo) in Azure and then use yaml override files from GitLab to provide the values for the Helm chart.

Don't worry, it really works!

But, it cannot be created without modifying the yaml directly when working on this in the GUI.

**To Reproduce**

1. Start creating application
2. Add the Helm chart information and others
3. Add another repo? Not possible, must go into the YAML definition
4. Add object into the "sources" array with ref, repoUrl and targetRevision as GitLab repo
5. Add the ref into the "sources" repository helm.valueFiles (array) and add the value files as elements for the array
6. Click save and see how the values files are available in the "HELM" section
7. Click create
8. Application is created, but it does not have ANY resources?!
9. Click the application, go to "manifest" and MOVE the helm chart object from "source" object, into "sources" array as an element. OH don't forget to add the missing "targetRevision" from the GitLab repo object
10. Save
11. Now you have an application with Helm repo (OCI, in my case) and GitLab

**Expected behavior**

As an user I would have expected to have a proper GUI workflow for setting up this kind of application instead of this mess.

**Screenshots**

Cannot really give without blurring basically everything as this is work related and I don't have time now to create a dummy example.

**Version**

```shell
argocd version
argocd: v2.9.0+9cf0c69
  BuildDate: 2023-11-06T04:43:50Z
  GitCommit: 9cf0c69bbe70393db40e5755e34715f30179ee09
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.9.0+9cf0c69
  BuildDate: 2023-11-06T04:43:50Z
  GitCommit: 9cf0c69bbe70393db40e5755e34715f30179ee09
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.11.1+g293b50c
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ishitasequeira** [comment]
@lk-1984, multiple sources does not have a complete UI support yet. Applications with multiple sources are editable only in the YAML mode.

Also, you can provide multiple sources using the `sources` field only. when you specify the `sources` field, Argo CD will ignore the `source` (singular) field. Please see the documentation https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/ for more details.

**Comment by lk-1984** [comment]
I see, well hopefully this will be added soon as this is very much welcomed new feature.
