### ISSUE TITLE
ArgoCD application continuously syncing in every 5 second

### ISSUE THREAD

**Issue by sumitsingh306** [argoproj/argo-cd#16290]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm just trying to deploy Kubernetes resource using "kubectl apply -f file.yaml" through ArgoCD and follow this documents https://argo-cd.readthedocs.io/en/stable/user-guide/sync-kubectl/  .  Though ArgoCd application is Healthy and Synced but every 5 sec syncing is running. I really don't understand this is problem or normal behavior .

**To Reproduce**

Just added one more application in apps. 

**Expected behavior**

Once synced and healthy then don't run syncing in very 5 second.  There is no sync schedule or any things. 

**Screenshots**

**Version**

```shell
![image](https://github.com/argoproj/argo-cd/assets/45307895/b5b8f800-a997-4e06-899b-6b15405497d9)

```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by sumitsingh306** [comment]
ArgoCD version = v2.7.7+4650bb2.dirty

**Comment by tukak** [comment]
Maybe some resources are being changed by the cluster and ArgoCD, the app gets out of sync and ArgoCD syncs that again?
Try to turn off self heal and auto sync of the application and see if some resource gets modified after manual sync. Then you can ignore the difference via `ignoreDifferences`

**Comment by sumitsingh306** [comment]
Hi @tukak  Thank you for time to look into this issue. There is no resource getting changed by cluster, all resource have same time stamped when they created in cluster. I disabled the auto sync and self heal but still it syncing in every 5 sec.

**Comment by jgwest** [comment]
Can you provide argo CD logs and more detailed reproduction steps?

**Comment by jgwest** [comment]
Closing as no response from reporter.
