### ISSUE TITLE
Use 8 characters for ARGOCD_APP_REVISION_SHORT variable in build environment

### ISSUE THREAD

**Issue by n0nvme** [argoproj/argo-cd#16293]
# Summary

Build variable `ARGOCD_APP_REVISION_SHORT` which was introduced in #14926 is 7 symbols long. This is GitHub UI default, but GitLab's default is 8 characters. Also `short_sha` template var in [SCM-Provider Generator](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-SCM-Provider/#template) also 8 symbols long. See related discussion in #11976 

# Motivation
I want to implement workflow where container image tag equals to the git short sha (similar to [this](https://stackoverflow.com/questions/69139198/argocd-gitops-where-the-image-tag-for-each-pod-is-always-the-git-commit-hash/) SO question). GitLab CI builds image with tag equals  to `CI_COMMIT_SHORT_SHA` [predefined variable](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html) which is 8 symbols long, but without SCM generator I can't create app that use 8 symbol short sha as image tag

# Proposal
I see 2 possible ways: 
- Change `ARGOCD_APP_REVISION_SHORT` to 8 chars and add `ARGOCD_APP_REVISION_SHORT_7` for similarity with SCM generator. Breaking change
- Provide a new `ARGOCD_APP_REVISION_SHORT_8` build env variable. It shouldn't break anything

**Comment by jhoover4** [comment]
Wow great! Yeah just having the env var _8 would be enough for me 😅

**Comment by mXtone** [comment]
@crenshaw-dev Hey, when can we expect of adding such variable. It's very crucial for us.

**Comment by cherrot** [comment]
I would be nice to support Bash substitution like `${ARGOCD_APP_REVISION:0:7}`

**Comment by crenshaw-dev** [comment]
I'd welcome a PR!

> I would be nice to support Bash substitution like ${ARGOCD_APP_REVISION:0:8}

That's a much more involved change. If you're using a CMP, you can interpret the provided env vars using whatever system you like. If not, you're stuck with the relatively simple substitution available in the Application spec. I think supporting arbitrary shell work would be well beyond the scope of what we want to provide via that interface.
