### ISSUE TITLE
Applicationset applicationsSync doesn't work as expected

### ISSUE THREAD

**Issue by vl-kp** [argoproj/argo-cd#16318]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Enable applicationsSync to create-delete in the applicationSet(and enable automated prune and selfHeal for application), once it is synced, the application is enabled auto prune and self-heal, i tried to click the button and disable automated in the application, since the applicationSet should not modify the application again, this is expected to be successful, but it is not 

**To Reproduce**
Set applicationsSync to create-delete on applicationSet
Enable application template automated prune and selfHeal on applicationSet
Try to disable the automate on the application manually

**Expected behavior**
Since applicationSet applicationsSync is  create-delete, it should not sync with/update the application again after creation

**Screenshots**
![image](https://github.com/argoproj/argo-cd/assets/128127889/a13c84f7-151b-4c33-9ba9-52a918492363)

**Version**

```shell
v2.9.0+9cf0c69
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by mikutas** [comment]
At the controller-level  [if 'policy' is set, it is not possible to override it at applicationSet level](https://github.com/argoproj/argo-cd/blob/43fe01a113c35db31c3110c03d5f3be344a43ecb/cmd/argocd-applicationset-controller/commands/applicationset_controller.go#L247).
The controller-level policy can be set via ConfigMap or controller's argument.

**Comment by vl-kp** [comment]
> At the controller-level [if 'policy' is set, it is not possible to override it at applicationSet level](https://github.com/argoproj/argo-cd/blob/43fe01a113c35db31c3110c03d5f3be344a43ecb/cmd/argocd-applicationset-controller/commands/applicationset_controller.go#L247). The controller-level policy can be set via ConfigMap or controller's argument.

Thanks for the heads up, i do find `applicationsetcontroller.policy: sync` in the config map, let me fix it
