### ISSUE TITLE
argocd admin dashboard - FATA[0002] cannot find pod with selector: [app.kubernetes.io/name=]

### ISSUE THREAD

**Issue by williammpe** [argoproj/argo-cd#16323]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When the argocd CLI version was updated to 2.9.0, an error occurred when running the command `argocd admin dashboard`, whereas it was working fine in version 2.8.6.

**To Reproduce**

1. Download version 2.9.0 of the argocd CLI using Curl.
    a. `curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v2.9.0/argocd-linux-amd64`
2. Install the downloaded binary.
    a. `sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd && rm argocd-linux-amd64`
3. run `argocd admin dashboard`

**Result**
```shell
FATA[0002] cannot find pod with selector: [app.kubernetes.io/name=] - use the --{component}-name flag in this command or set the environmental variable (Refer to https://argo-cd.readthedocs.io/en/stable/user-guide/environment-variables), to change the Argo CD component name in the CLI 
```

**Expected behavior**

> Argo CD UI is available at http://localhost:8080

**Screenshots**

![argocd-error-dashboard](https://github.com/argoproj/argo-cd/assets/73968707/206fd1f1-9377-47c2-97aa-0f81fa835cce)

**Version**

```shell
argocd: v2.9.0+9cf0c69
  BuildDate: 2023-11-06T05:01:52Z
  GitCommit: 9cf0c69bbe70393db40e5755e34715f30179ee09
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
```

**Comment by mikutas** [comment]
https://github.com/argoproj/argo-cd/pull/14605/files#diff-170ef34ea6636f7c5461828e058b61f2e4e53f6f90d761e07be2fa1637d9eaf6L113

**Comment by alexmt** [comment]
Got the same error. Will work on the fix and cherry-pick into affected versions.
