### ISSUE TITLE
Dark mode delete dialog white on white

### ISSUE THREAD

**Issue by eric-engberg** [argoproj/argo-cd#16366]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

The delete dialog in dark mode is now white text on white background.  Not sure what version broke this (just upgraded from 2.7.7 to 2.9.1)

**To Reproduce**

Install argocd 2.9.1
Turn on dark mode
Click to delete a resource.

**Expected behavior**

The background and text should not be the same color

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and let us know if the issue is still present, please?

**Comment by eric-engberg** [comment]
I upgraded a long time ago but forgot about this ticket and never realized it was fixed.  Closing this out
