### ISSUE TITLE
Join the CD Foundation

### ISSUE THREAD

**Issue by Oduig** [argoproj/argo-cd#1637]
Comparing various CD solutions, we came across the CD foundation: https://cd.foundation/about/faq/

The intention of this foundation seems to be to develop new standards for CD. Current members on https://github.com/cdfoundation/toc

It would be great if ArgoCD could be a part of this movement as a free & open source CD tool, and an opportunity for Argo to get a direct line to the big players in this market.

**Comment by Oduig** [comment]
Anyone to chime in?

**Comment by alexec** [comment]
Interesting https://thenewstack.io/the-continuous-delivery-foundation-gets-a-reality-check/

**Comment by edlee2121** [comment]
FYI, we've submitted Argo to the CNCF instead of CDF.
https://github.com/argoproj/argo-cd/issues/2163
