### ISSUE TITLE
argocd cli `--server-side-generate` causes "app path does not exist" error

### ISSUE THREAD

**Issue by Manuelraa** [argoproj/argo-cd#16374]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Using `--server-side-generate` does not work and causes an error instead.
Normal diff does work.
Adding e.g. `--local-repo-root ./ --local-include '*'` does not help

**To Reproduce**

```
$ argocd --loglevel debug app diff argocd/00-argocd --local ./kubernetes-config/envs/cluster-dev/argocd --server-side-generate
FATA[0000] rpc error: code = Unknown desc = failed to get app path: kubernetes-config/envs/cluster-dev/argocd: app path does not exist
```

**Expected behavior**

`argocd app diff --server-side-generate` should work. Or in case it is an user error it should be documented how the `--local*` parameters should be set.

**Screenshots**

N/A

**Version**

```shell
$ argocd version
argocd: v2.9.1+58b04e5
  BuildDate: 2023-11-14T15:40:46Z
  GitCommit: 58b04e5e11d007b0518853029ff7612c24a2eb35
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.9.1+58b04e5
  BuildDate: 2023-11-14T15:08:20Z
  GitCommit: 58b04e5e11d007b0518853029ff7612c24a2eb35
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

Can't find any

**Comment by Manuelraa** [comment]
I have figured it out. When using `--server-side-generate` the `--local` parameter is expected to be the root of the repo. (Full not relative! Just `.` doesn't work)
Therefore following command will work assuming I'm in the root of my repo. `argocd app diff argocd/00-argocd --server-side-generate --local $PWD`

**Comment by scubbo** [comment]
Thanks for reporting the solution! What a confusing (and undocumented!) choice to have `--local` accept `.` without `--server-side-generate`, but reject that path _with_ that flag.

**Comment by JuniorJPDJ** [comment]
Thank you very much for this issue, I'd never find the solution without that..
