### ISSUE TITLE
ui: increase contrast on error popup

### ISSUE THREAD

**Issue by ethanmdavidson** [argoproj/argo-cd#16375]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The error notification popup has low contrast, which makes it difficult to read. 

**To Reproduce**

1. Open argo web UI
2. Attempt an action that you don't have permission to do
3. Observe low-contrast text on red popup in lower righthand corner.

**Expected behavior**

Contrast should be higher, to meet accessibility standards.

**Screenshots**

The error popup in question:

![image](https://github.com/argoproj/argo-cd/assets/1311998/bf9d5c3d-338f-4450-ada0-8938a2b5d208)

**Version**

```json
{
    "Version": "v2.8.0+804d4b8",
    "BuildDate": "2023-08-07T14:25:33Z",
    "GitCommit": "804d4b8ca6bc4c2cf02c5c971aa923ec5b8623f0",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

Similar issue: https://github.com/argoproj/argo-cd/issues/5408

**Comment by Gladdstone** [comment]
I attempted to recreate this issue in the release mentioned, but have not found a situation where a missing permission generates a popup of this particular color scheme. Could you detail an action that generates this particular popup?

**Comment by ethanmdavidson** [comment]
@Gladdstone this popup can be triggered by attempting to delete a resource, when you don't have permission to delete it.

Here's more info, though I'm not sure if it's relevant
- we're authenticated with [OpenID Connect plus Google Groups using Dex](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/#openid-connect-plus-google-groups-using-dex)
- we are using RBAC, but we haven't configured any groups yet, so I believe all users are just getting `role:readonly`

**Comment by Gladdstone** [comment]
The problem appears to be that some areas are passing an additional [ErrorNotification](https://github.com/argoproj/argo-ui/blob/5ff344ac9692c14dd108468bd3c020c3c75181cb/src/components/error-notification.tsx) component in spots where the component wishes to bubble up additional messages to the ui. This is a bit of an inconsistency in the behavior of the ui code. I might suggest integrating the message handling as an optional prop for the [Notification](https://github.com/argoproj/argo-ui/blob/5ff344ac9692c14dd108468bd3c020c3c75181cb/src/components/notifications/notifications.tsx) component and then ending or phasing out use of the redundant component. Played with it locally and would be happy to pr the ui repo as well as the relevant changes for this issue.

**Comment by agaudreault** [comment]
I tried to reproduce using the latest version available at https://cd.apps.argoproj.io/. 
I cannot reproduce. Please reopen if you have the same behavior on the latest version.

<img width="372" alt="image" src="https://github.com/argoproj/argo-cd/assets/47184027/f5e17091-731a-4e6f-b5a9-c9b6aa2a7ece">
