### ISSUE TITLE
PerconaXtraDBCluster healthcheck fails when error state

### ISSUE THREAD

**Issue by filiprafaj** [argoproj/argo-cd#16396]
Hi, the healthcheck for _pxc.percona.com/PerconaXtraDBCluster_ fails when the cluster is in _error_ state throwing
`<string>:30: bad argument #1 to concat (table expected, got nil)`

I guess, this can be fixed by changing `obj.status.messages` -> `obj.status.message` here:
https://github.com/argoproj/argo-cd/blob/61abc805731962cfd20159c315d8ed436870b0e7/resource_customizations/pxc.percona.com/PerconaXtraDBCluster/health.lua#L30

I have tested this change using `resource.customizations`  in `argocd-cm` _ConfigMap_ and it works as expected.

**Comment by crenshaw-dev** [comment]
@filiprafaj can you open a PR with the fix and a test?
