### ISSUE TITLE
Pod logs horizontal scroll is per line instead of all lines

### ISSUE THREAD

**Issue by maartengo** [argoproj/argo-cd#16411]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Scrolling in the log view of pods/deployments/etc. only scrolls per line, instead of all lines together. This is similar to what happened in https://github.com/argoproj/argo-cd/issues/14387.

**To Reproduce**

1. Start a pod that logs multiple long lines (redis does this)
2. Open the pod logs in Argo
3. Try to scroll horizontally

**Expected behavior**

I expect a horizontal scroll bar, and for all logs to scroll simultaneously instead of individually.

**Screenshots**

https://github.com/argoproj/argo-cd/assets/46345801/98183b9b-7976-4019-85b4-5a640e1ac49e

**Version**

```
{
    "Version": "v2.9.1+58b04e5",
    "BuildDate": "2023-11-14T15:08:20Z",
    "GitCommit": "58b04e5e11d007b0518853029ff7612c24a2eb35",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by maartengo** [comment]
@ciiay could you take a look at this bug? I think that your change from https://github.com/argoproj/argo-cd/commit/30e06d6d4a8647a2a1401968755e0c89ec2687f8 broke horizontal scrolling, but I'm not well versed enough in front-ends to see what went wrong.

**Comment by maartengo** [comment]
I took another look at the commit I linked, but it seems more likely that this commit caused the issue; https://github.com/argoproj/argo-cd/commit/795f2256cdd708fe20e9dcf9844da377c01a161c

**Comment by crenshaw-dev** [comment]
I can reproduce this in 2.9.1.

**Comment by ciiay** [comment]
Got it, I will take a look at this issue when I'm back in new year.

**Comment by alexec** [comment]
I noticed this yesterday myself and found it … unintuitive. Not like a normal log viewer.

I’m only commenting to help hint that it’s a real issue.

**Comment by Sineaggi** [comment]
Can we get a test for this so it doesn't break again?

**Comment by jgwest** [comment]
Yi's PR had merged.
