### ISSUE TITLE
Provide an option to ignore dependents resources update which are created a resource tracked by argocd

### ISSUE THREAD

**Issue by kahoulei** [argoproj/argo-cd#16415]
# Summary

Currently, we can ignore the resources by specifying a list of `jsonPointers` or `jsonExpression` in `resource.customizations.ignoreResourceUpdates` field of the `argocd-cm` configmap. It works great if we want to ignore the resources update that we want to track. 

However, there is a case that we want to ignore the dependents resources creation. For example, we want to ignore the `Job` and `Pod` resources which are created by `CronJobs`. This is because if someone has a lot of CronJobs and the schedules are very frequent, it will waste a lot of CPU cycle as application controller will trigger the update very frequently.

# Motivation

Our argocd is managing 700+ Kubernetes clusters and each cluster is deploying around 50+ CronJobs. These CronJobs schedule a new Job/Pod for every 1 minute. Because of this, argocd uses a lot of CPU cycle whenever there is a new Job/Pod created by those cronjob. 

We would like to add option to ignore this as our Job/Pod task are very short lived and they only do low priority tasks such as logging and reporting tasks.

# Proposal

Currently, argocd application controller will skip the ignore resources check if the dependent resources are new resources ([reference code](https://github.com/argoproj/argo-cd/blob/master/controller/cache/cache.go#L521)). That is, new resources will always trigger update.

I propose to have an option provided from ConfigMap for the dependent resource to be ignored. 

If this proposal makes sense to the community, I am happy to submit a PR for this change. 

Thanks a lot!

**Comment by crenshaw-dev** [comment]
Ignoring updates in non-top-level resources was nontrivial, which is why @agaudreault-jive didn't include it in the original feature. I'd recommend getting his input on the implementation strategy.

**Comment by kahoulei** [comment]
@crenshaw-dev Thanks for your input. 

If I understand correctly, there was a plan to ignore dependents resources? If that's the case I can start working on a PR. I will tag you and @agaudreault-jive when it is ready.

**Comment by agaudreault-jive** [comment]
I would have liked to be able to ignore them, but running the code on all resources being watched in the cluster was consuming more memory than the reconcile itself. This is why the orphan resources and "non-top-level" resources are not filtered. 

My idea to solve this issue was to add the tracking annotation to any resources that end up being part of an application, even if they are not top-level. This way we would also save some CPU time to always recompute the dependent resources. (maybe only a hard refresh should re-evaluate all the applications resources)

**Comment by kahoulei** [comment]
@agaudreault-jive thanks for your input.

I had a similar thought by introducing a new tracking option. For the non-top-level resources, I thought currently we are already searching the parent whether it is belonged to the argocd app or not in [here](https://github.com/argoproj/argo-cd/blob/master/controller/cache/cache.go#L544)?

I was thinking to do something like below in the same function call

```
		for _, r := range []*clustercache.Resource{newRes, oldRes} {
			if r == nil {
				continue
			}
			
			// getAppNonRecurisve is a new function that we just look for the current resouce whether it has the tracking annotation
			currentResourcesAppName := getAppNonRecurisve(namespaceResources)
			
			// this is already recursively looking up the parent whether it belongs to the argo-cd app
			app := getApp(r, namespaceResources)
			
			// new logic to use the new tracking annotation
			if app != "" && currentResourcesAppName == "" {
			   parent = getParent(namespaceResources)
			   if parent.IgnoreChildResourcesUpdate() {
			       skipChildResourceUpdate = true
			   }
			}
			
			if app == "" || skipAppRequeuing(r.ResourceKey()) || skipChildResourceUpdate {
				continue
			}
			toNotify[app] = isRootAppNode(r) || toNotify[app]
		}
```

(again, if I am totally off track please guide me to the right direction :) )

**Comment by agaudreault-jive** [comment]
I don't think of any reason why it would not work. Although
- I assume `IgnoreChildResourcesUpdate` is only based on the resource kind and would need to be configured in the app or server settings.
- You cannot really do ignore difference there because oldRes/newRes object does not have the full manifest in cache.
- Even with this code, the manifest hash will not be generated for untracked resources (causing the behavior of this issue)

**Comment by weikinhuang** [comment]
Hi, is there any update on this issue?

**Comment by kahoulei** [comment]
@weikinhuang I got sidetracked and I just resume to work on it.

**Comment by ronaknnathani** [comment]
This request seems to have been mentioned in more than 1 issue:
* https://github.com/argoproj/argo-cd/issues/15594
* https://github.com/argoproj/argo-cd/issues/9558#issuecomment-2095809680
* https://github.com/argoproj/argo-cd/issues/9819#issuecomment-1705477558
* https://github.com/argoproj/argo-cd/issues/15612

It'd be good to link them all so folks can find it easily and see there's work being done in https://github.com/argoproj/argo-cd/pull/18343.
