### ISSUE TITLE
Add a setting to disable requiring delete confirmation typing the resource name: Are you sure you want to delete ... ?

### ISSUE THREAD

**Issue by erikschul** [argoproj/argo-cd#16422]
# Summary

When deleting some resources, the user is required to type the name. It makes sense that beginners may make a mistake that can lose data, but for someone who knows what they're doing, it's annoying to have to copy-paste the name each time.

Make it possible to disable requiring the typing of a resource name:

<img width="1008" alt="image" src="https://github.com/argoproj/argo-cd/assets/128804597/093a5f5b-85de-4bf0-8225-6f4ac014f8c6">

The confirmation dialog is fine. To be even more optimal, change the radiobuttons (Foreground delete...) into buttons, so fewer clicks are required.

If you want to be really sharp, make it possible to CTRL+Mouse click a resource to foreground delete it. (key combination and action could be configurable in settings).

# Motivation

There are many situations where a deployment can get stuck or out of sync.
When an ImagePullBackoff happens, but you want to restart immediately. When changing a secret/configmap, but this isn't reflected in the deployment, and so on.

**Comment by crenshaw-dev** [comment]
I think all the use cases described can be handled with the "Restart" action, which iirc doesn't require a prompt.

**Comment by jgwest** [comment]
Dupe of #6206

**Comment by fstr1ng** [comment]
I've created small extention for Chrome to autocopy resource name in confirmation dialogue for this issue:
https://github.com/fstr1ng/argocd-chrome-extention
