### ISSUE TITLE
HTTP API should allow JWT to be passed via Authorization header

### ISSUE THREAD

**Issue by larslevie** [argoproj/argo-cd#1642]
It is currently necessarily to pass the auth JWT via a session cookie in order to interact with the Argo CD HTTP API. IMO this is not typical. Instead (or in addition) the HTTP API should accept the auth JWT via an `Authorization` header. E.g. `Authorization: Bearer <token>`. This will, at least partially, mitigate #1103.

Switching to header-only will introduce problems with API calls sent from HTML `link` hrefs, because the browser will send the session cookie in those instances, but not set the `Authorization` header. Again in my opinion, that is a fairly non-standard way to interact with an HTTP API. For that use case, I would suggest accepting the JWT via a query param instead.

**Comment by alexec** [comment]
Will this work this OIDC implicit flows?

**Comment by alexec** [comment]
I feel like the underlying issue is using JWTs as session tokens:

https://logrocket.com/blog/jwt-authentication-best-practices/

**Comment by alexec** [comment]
https://hptechblogs.com/using-json-web-token-react/

**Comment by alexec** [comment]
https://auth0.com/blog/jwt-authentication-with-observables/

**Comment by alexec** [comment]
https://books.google.com/books?id=OLZTDwAAQBAJ&pg=PA159&lpg=PA159&dq=rxjs+authorisation+bearer&source=bl&ots=HogFPWp2Bk&sig=ACfU3U2e-i5WU8AAgr16A3o7sGS1cyqcEw&hl=en&sa=X&ved=2ahUKEwiHuJGagYHkAhVPrp4KHV9BDC8Q6AEwDnoECAkQAQ#v=onepage&q=rxjs%20authorisation%20bearer&f=false

**Comment by alexec** [comment]
Ok. So it looks feasible. We will need to store the token in local storage and then add the token in `argo-ui/../requests.ts`

```js
function initHandlers(req: superagent.Request) {
    req.on('error', (err) => onError.next(err));
    const token = localStorage.getItem('token');
    if (token !== null) {
        req = req.auth(token, {type: 'bearer'});
    }
    return req;
}
```
Cookies are set in two places. (1) `odic.go/HandleCallback` (which will need to change to pass to a new page that will store the token in `localStorage`. (2) `server.go/translateGrpcCookieHeader` (not sure what this does).

**Comment by alexec** [comment]
https://www.codesd.com/item/http-authorization-header-in-eventsource-server-sent-events.html

**Comment by alexec** [comment]
@jessesuen I'd like to push back onto the backlog. It hasn't had many votes. What I will do is document my findings.

**Comment by alexec** [comment]
I've pushed `alexec/bearer` with some code changes.

**Comment by alexec** [comment]
This will appear in v1.3
