### ISSUE TITLE
Cannot delete app that is already in operation

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1644]
**Describe the bug**

An app can be running an operation (i.e. sync) when a request comes in to delete it. 

**To Reproduce**

1. Create an app.
2. Sync it.
3. Corrupt the app so it gets stuck in sync.
4. Delete the app.
5. Observe app does not delete.

**Expected behavior**

The app should delete, or suitable error message.

**Version**

1.0.0

**Additional context**

**Comment by alexec** [comment]
OK. So the workaround is to forcibly delete the broken resource.

```bash
-n argocd-e2e-ns-uwirf delete pod hook --force --grace-period 0
```

**Comment by gevalter** [comment]
I'm currently with v1.1.1, this solution does not work :(
