### ISSUE TITLE
UI: Header too big.

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-cd#16442]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

After updating to v2.9.X the header is too big and overlays the upper part of the application details view, as seen in the screenshot. It is the same for me in Safari and Chrome on MacBook.

**To Reproduce**

Open argo-cd in web browser.

**Screenshots**

<img width="1432" alt="Screenshot 2023-11-24 at 10 54 40" src="https://github.com/argoproj/argo-cd/assets/50194881/d8a1dcad-f12b-425a-b311-e79af903d348">

**Version**

2.9.2. But it was the same with 2.9.1.

**Comment by jlandowner** [comment]
I met the same issue with Macbook 13-inch display with the default resolusion 1440 x 900.
I found this issue occers with the browser zoom 100% ~ 110%, but not occers under 90% or over 125% .

**Comment by JessieTeng89** [comment]
Hi all,
Could you please assign this bug to me? I will create a PR to fix it.
Thanks!

**Comment by JessieTeng89** [comment]
As checked in latest version of ArgoCD, this issue was resolved in https://github.com/argoproj/argo-cd/pull/16223.

**Comment by nice-pink** [comment]
Solved in #16223
