### ISSUE TITLE
OIDC with RBAC not functioning

### ISSUE THREAD

**Issue by Timoses** [argoproj/argo-cd#1645]
**Describe the bug**
External OIDC provider is used as described [here](https://argoproj.github.io/argo-cd/operator-manual/sso/#existing-oidc-provider). Adjusting the RBAC policy or simple setting `policy.default: role:admin` does not appear to be working correctly.
The user can successfully login to argocd UI via OIDC provider, but then has no priviledges at all (e.g. can not see existing applications, can not create applications).
The argocd-server log shows the correct claims (`sub`, `groups`, ...) when the user logs in or tries to perform an action.

**To Reproduce**
1. Create argocd resource file with `source/kustomization.yaml`
```
bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=release-1.0
```
and `kustomize build source > source/argocd.yaml`
2. Kustomize: https://gist.github.com/Timoses/adb2117626ce0c302c78e813c0edb269
3. `kubectl port-forward svc/argocd-server 8080:443`
4. Browse to `https://localhost:8080` and click `Login with Keycloak` (if on login screen)
5. Login is successful, but no priviledges are granted to the user (despite `policy.default: role:admin`).

**Expected behavior**
User has priviledges as `role:admin`.

**Version**
1.0

```shell
argocd: v1.0.0+c74ca22
  BuildDate: 2019-05-16T20:03:24Z
  GitCommit: c74ca22023cbee245cb83fb23224978fbe23703c
  GitTreeState: clean
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.0.0+c74ca22
  BuildDate: 2019-05-16T20:04:21Z
  GitCommit: c74ca22023cbee245cb83fb23224978fbe23703c
  GitTreeState: clean
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

```
time="2019-05-24T08:18:29Z" level=info msg="received unary call /repository.RepositoryService/ListApps" grpc.method=ListApps grpc.request.claims="{\"acr\":\"0\",\"aud\":\"argocd\",\"auth_time\":1558683891,\"azp\":\"argocd\",\"email\":\"my_user@company.com\",\"exp\":1558686756,\"groups\":[\"admins\"],\"iat\":1558685856,\"iss\":\"https://sso.int:8443/auth/realms/kubernetes\",\"jti\":\"c1fb83e2-efd0-48bd-b82d-ab9cfce5ae0e\",\"nbf\":0,\"nonce\":\"NQaZUgwamZ\",\"preferred_username\":\"my_name\",\"s_hash\":\"HPNHBcidwvzVkr4PD86e8w\",\"session_state\":\"c75adb96-d4c2-4
eef-9e2a-42711a7ecec8\",\"sub\":\"aba5318f-fdb8-4975-bfcb-76adf2c28c3e\",\"typ\":\"ID\"}" grpc.request.content="repo:\"t\" revision:\"HEAD\" " grpc.service=repository.RepositoryService grpc.start_time="2019-05-24T08:18:29Z" span.kind=server system=grpc        
time="2019-05-24T08:18:29Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied: repositories, get, t" grpc.code=PermissionDenied grpc.method=ListApps grpc.service=repository.RepositoryService grpc.st
art_time="2019-05-24T08:18:29Z" grpc.time_ms=3.085 span.kind=server system=grpc
```

**Additional context**
Not sure what else to try. Could using `localhost` as `url` be a problem?

**Comment by jessesuen** [comment]
It was pointed out that you have the rbac rules (policy.csv, policy.default) in argocd-cm instead of argocd-rbac-cm. This is why this is not working. Please change the following line to:

https://gist.github.com/Timoses/adb2117626ce0c302c78e813c0edb269#file-overlays-argocd-cm-rbac-yaml-L5
```
  name: argocd-rbac-cm

```
