### ISSUE TITLE
Auto-sync support for kustomize remote git bases

### ISSUE THREAD

**Issue by tafkam** [argoproj/argo-cd#1646]
**Is your feature request related to a problem? Please describe.**

Auto-sync uses the git commit-SHA of the kustomize repository/overlay defined in the ArgoCD Application CR.

Lets say you use kustomize to split your application into different git repositories for different access-rights:

- deployment-resources (deployments, statefulsets, services, etc.)
- application-config (configmap, kustomize image newName+newTag)
- application-secrets

Kustomize (by-design) can not replace the image and tags in a referenced base. In this use-case you have to point your ArgoCD application to the the application-config repository as kustomize "root". ( kustomize references: https://github.com/kubernetes-sigs/kustomize/issues/803 and https://github.com/kubernetes-sigs/kustomize/issues/915 )

ArgoCD is now using the commit-SHA of the application-config repository, and doesn't autosync any changes in the deployment-resources or application-secrets repositories.

**Describe the solution you'd like**

Create a hash for the whole yaml created by kustomize build, and use that hash to track changes for kustomize auto-sync applications.

Alternative solution sticking to git commit hashes (IMHO bloated and with more problems following):
- User defines all Kustomize git repositories in the ArgoCD configuration (cumbersome, if you use (feature-)branches/refs in Kustomize bases)
- ArgoCD cross references the configured repositories with the Kustomize base definition
- track repository commit hashes for all Kustomize bases in ArgoCD 

**Additional context**
Somehow ArgoCD is aware of changes in kustomize remote-bases with it's git polling procedure, but the changes won't be applied in auto-sync since the commit hash of the kustomize root didn't change.

**Comment by alexec** [comment]
Interesting. Argo CD uses the SHA to determine whether an auto-sync needs to occur. This would be a pretty fundamental change. 

As a (not great) workaround, you could trigger empty commits to the main repository when the bases changes.

**Comment by tafkam** [comment]
The extra-step for a empty commit (with fulfilling requirements for that commit, e.g. matching a regex-pattern for a existing ticket number in the commit message) is more work than clicking sync in the ArgoCD UI 🤡

**Comment by jessesuen** [comment]
We actually outline this very issue in our best practices, and recommend *against* having remote bases that can change meaning:
https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/best_practices.md#ensuring-manifests-at-git-revisions-are-truly-immutable

Basically, when you start using remote bases which can change meaning, GitOps starts to lose its value since the manifests at the commit SHA are no longer truly immutable. Things like rollback will no longer work properly.

Argo CD actually can handle changes to remote bases via force refresh. Force refresh invalidates the cached YAML for that application. However, force refresh is not done as part of Argo CD's three-minute polling interval since that would get very expensive. NOTE that we cache manifests for 1 day, so after 24 hours Argo CD would in fact detect the difference in the remote base.

**Comment by tafkam** [comment]
I agree that changing remote bases can be an issue, and that the remote bases should be using the ref parameter. Though I don't think the described best practices for public git repositories apply fully to the use-case with on-premise git repositories, which don't have changing upstreams, have defined repository pull-request/merge workflows and defined access rights (e.g. to reduce the domain of people having access to sensitive database credentials, read 4 of https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/best_practices.md#separating-config-vs-source-code-repositories ).

The argument that rollbacks won't work with remote bases doesn't apply to the auto-sync use-case, as described in https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/auto_sync.md#automated-sync-semantic auto-sync doesn't support rollbacks anyways. 

Comparing between the best-practice paradigms "separation of access" and "immutable git source" I give "separation of access" more weight, since I define who has access to the repositories, and with that I trust (or ensure) that those users know what they are doing in that repository. Hence I'm OK with auto-sync changes.

Beside the mentioned use-case for splitting up deployment, app-configuration and secret repositories, a auto-sync option for kustomize would help manage large number of namespaces and namespace-configurations(service accounts, rbac, secrets), where you have to rollout the same resources (like docker pull secrets, git ssh keys, certificates) into a large number, but not necessarily all namespaces. Without using a remote base, either some users get unintended access to the secrets, or you have to define the secrets for each and every namespace a second time in another repository, since Kustomize (and ArgoCD) doesn't allow to define multiple namespaces in one application. This also denies the option to have some users create namespaces for testing purposes with a pre-defined set of default settings and secrets.
Having to manually sync dozens, even hundreds of namespace configurations for a single changed docker pull secret, or changed tls certificate or certificate authority is a chore. (Disclaimer: I'm fully aware that there are easier and safer methods to push secrets into kubernetes.)

Having (and propagating) best practices is a good thing, until you can't apply them well. Having OPTIONS for those fringe cases would be helpful.
(having a application setting for always using force-refresh would also be nice 😉)

**Comment by alexec** [comment]
You can now reduce the `--repo-cache-expiration` option as documented in https://argoproj.github.io/argo-cd/operator-manual/high_availability/ and your charts will update more often.
I've labelled this as workaround/wontfix. Please try out the new flag and see if it works for you.
