### ISSUE TITLE
More friendly error message when label value is nil to improve userability

### ISSUE THREAD

**Issue by cbl315** [argoproj/argo-cd#16473]
# Summary

In `repo-server`, when label is nil, there manifest generation would be failed and will got below error message in UI:
```text
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = failed to set app instance tracking info on manifest: failed to set app instance label: failed to get labels from target object apps/v1, Kind=Deployment /rgo-product-ingestion-service: .metadata.labels accessor error: contains non-string key in the map: <nil> is of the type <nil>, expected string
```

The error message is not friendly, could we point out which label is nil in error message? Like 
```text
... the value of label <key1> is nil from target object apps/v1, Kind=Deployment /rgo-product-ingestion-service...
```

# Motivation
Imporve userability

# Proposal

Change the error message to 

```text
... the value of label <key1> is nil from target object apps/v1, Kind=Deployment /rgo-product-ingestion-service...
```

**Comment by crenshaw-dev** [comment]
The error message is actually incorrect. The value is nil, not the key.

I've submitted a PR to fix the message in the upstream library: https://github.com/kubernetes/kubernetes/pull/118989

The PR has been merged. We'll get the new error message when we upgrade our k8s libraries to >= 1.28.

**Comment by cbl315** [comment]
Sounds good, thanks for the quick reply. :-)
