### ISSUE TITLE
Unable to load data: error getting cached app managed resources: dial tcp: lookup argocd-redis on 172.20.0.10:53: no such host

### ISSUE THREAD

**Issue by engineerakki** [argoproj/argo-cd#16517]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading Argo to 2.7.0, we cannot load App diff in the UI due to the following error:

`Unable to load data: error getting cached app managed resources`

It seems Argo source-code has a hardcoding of using `argocd-redis` as the redis url and it does pick any other redis service name
I had to manually create a new redis svc with the name `argocd-redis` in my cluster to fix this problem

![Screenshot 2023-12-04 at 09 23 57](https://github.com/argoproj/argo-cd/assets/6374744/e2fc32aa-177b-48da-9b37-cf57815a21f8)

**To Reproduce**

- 1.) Upgrade Argo from 2.6 to 2.7, 
   2.) Have an OurOfSync app,
   3.) Try to view App Diff from the UI.

This potentially will be affect newer argo versions too.

**Expected behavior**

Argo should connect to redis svc and show app diff in the UI.

**Version**

```shell

v2.7.0+c592219.dirty
```

**Comment by jgwest** [comment]
Can you:
- provide specific steps on how you installed Argo CD
- whether or not it is reproducible with a fresh install

**Comment by jgwest** [comment]
Closing as no response from reporter.

**Comment by pkazi** [comment]
In my case, redis was disabled via helm installation. Make sure redis is enabled for argocd.
```
argo-cd:
  redis:
    enabled: true
```
