### ISSUE TITLE
[bug] not enough hardware in cluster, no UI error, issue after add hardware to cluster

### ISSUE THREAD

**Issue by kwladyka** [argoproj/argo-cd#1652]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3903726/58432917-1322e280-80b5-11e9-97d9-b6050984cba2.png)

![image](https://user-images.githubusercontent.com/3903726/58432919-17e79680-80b5-11e9-96b8-28db49ab7523.png)

I had not enough resources in cluster. It should turn into red error.

**To Reproduce**
Assign more resources, than cluster have.

**Expected behavior**
Mark as red error.

**Version**

v1.0.0.

---
Connected bug to this issue:
after add CPU / memory to k8s cluster (by add new higher tier node and remove old one), argo cd doesn't sync Applications. I have to click manually sync on Applications.

**Comment by alexmt** [comment]
Argo CD uses the same logic as `kubectl rollout status ...` to check if deployment if progressing, health or degraded. I think in this case deployment might not have `progressingDeadlineSeconds` field or it has very long number. Once deadline is reached then deployment and application will be marked as degraded. @kwladyka can you please check if `progressingDeadlineSeconds` is set?

**Comment by kwladyka** [comment]
I have no longer this cluster and situation. It should always happen when there is not enough CPU / MEM in cluster for resources.

**Comment by alexmt** [comment]
Verified that Argo CD switches app into a degraded state after deployment unable to reach a healthy state after `progressingDeadlineSeconds` expires. It looks like health assessment is functioning, so closing the ticket. Please feel free to reopen .

**Comment by kwladyka** [comment]
Hmm so why it didn't work for me? How long did you wait?

**Comment by kwladyka** [comment]
What I am trying to issue here is: as a user I need feedback from Argo CD my deployment failed, because not enough CPU / MEM. But Argo CD show it blue instead of red. Maybe it is not technical mistake and there is no error, because there is no health / degraded state. But it is UI / usability bug by providing confusing information. Blue processing when there is not enough CPU / MEM in cluster.
