### ISSUE TITLE
Inconsistent Health of cert-manger.io/Certificate

### ISSUE THREAD

**Issue by chr15murray** [argoproj/argo-cd#16523]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The health of a cert-manager.io/certificate is not always consistent within ArgoCD when Issuing and Ready states both exist. This occurs because the Ready: False state may come first or second in the status conditions.

**To Reproduce**

Create a certificate manifest for cert-manager to handle.  Most of the time it will show 'progressing' in ArgoCD but occasionally it will show a degraded state. 

**Expected behavior**

When a status for 'Issuing' exists I expect the health to show 'progressing' instead of degraded. This can occur if the 'Ready' status appears first in the statuses.

Example Degraded

status:
  conditions:
    - lastTransitionTime: '2023-12-01T11:15:28Z'
      message: Issuing certificate as Secret does not exist
      observedGeneration: 1
      reason: DoesNotExist
      status: 'False'
      type: Ready
    - lastTransitionTime: '2023-12-01T11:15:28Z'
      message: Issuing certificate as Secret does not exist
      observedGeneration: 1
      reason: DoesNotExist
      status: 'True'
      type: Issuing
  nextPrivateKeySecretName: certtest-81-vg977
Example Issuing

status:
  conditions:
    - lastTransitionTime: '2023-12-01T11:15:28Z'
      message: Issuing certificate as Secret does not exist
      observedGeneration: 1
      reason: DoesNotExist
      status: 'True'
      type: Issuing
    - lastTransitionTime: '2023-12-01T11:15:28Z'
      message: Issuing certificate as Secret does not exist
      observedGeneration: 1
      reason: DoesNotExist
      status: 'False'
      type: Ready
  nextPrivateKeySecretName: certtest-82-f4r27

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

I do not have api access to ArgCD to run this.  Version is `v2.9.2+c5ea5c4`
**Logs**

```
Paste any relevant application logs here.
```

**Comment by blakepettersson** [comment]
Resolved with #16520
