### ISSUE TITLE
See all resources which are not deployed by argo cd

### ISSUE THREAD

**Issue by kwladyka** [argoproj/argo-cd#1653]
**Is your feature request related to a problem? Please describe.**
I don't know if there are legacy resources in k8s.
It can happen by bugs / people mistakes / etc.
I would like to control what is in cluster what I don't want to be there. I want to have gitops 1:1 without surprise, but I need some kind of verification of it. Legacy things always happen in long time perspective.

**Describe the solution you'd like**
UI view which will show me all resources not deployed by argo cd. The best with connections between by arrows. Some kind of cluster resources view but showing what is expected to be there and what is not expected to be there.

**Describe alternatives you've considered**
CLI can return it in my console.

**Comment by alexec** [comment]
There is a plan to provide a namespace view to address the issue of answering "what resources are not managed by Argo CD"?

**Comment by kwladyka** [comment]
I would like to see not namespace, but whole cluster and then filter to namespace.

I am not sure but flux has notifications if detect resources which are not defined in gitops. So it is a watcher something appear in cluster, which I don't think should be there. It can happen if somebody add it manually.
