### ISSUE TITLE
Improve CI job stability

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#166]
ArgoCD job often fails because build is taking too much time or because of network issues ( `go get` sometimes  fails). We might add more resources and add retry logic to CI workflow.

**Comment by jessesuen** [comment]
One thing that will help, is if we don't split our build into different containers for different make targets. We should just combine make targets where we can.

**Comment by jessesuen** [comment]
Fixed in 7348553897af89b9c4366f2d445dd2d96fe4d655
