### ISSUE TITLE
Add user info in Argo CD history UI

### ISSUE THREAD

**Issue by leoluz** [argoproj/argo-cd#16612]
# Summary

In Argo CD UI, it would be useful to have in the history panel the information of the user who triggered the sync.

# Motivation

Better visibility of who/what is triggering Argo CD Syncs

# Proposal

Identify the possibility to add additional information in the history panel in Argo CD UI of the user that triggered the sync.
See image:
![image](https://github.com/argoproj/argo-cd/assets/44989/23a61aca-1986-43d5-b09e-896eb970f673)

**Comment by robinlieb** [comment]
@leoluz I added a PR which implements that enhancement.

**Comment by leoluz** [comment]
@robinlieb Awesome! Thank you. 
We just cut the 2.10 branch so this will probably go in 2.11.

**Comment by abdennour** [comment]
Thanks guys!
