### ISSUE TITLE
Webhook url regexp doesn't support "user" for http/https schemas

### ISSUE THREAD

**Issue by messiahUA** [argoproj/argo-cd#16622]
Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**

webhook processing doesn't match repo URL that have "user" specified for http and https schemas

**To Reproduce**

1. create an application or applicationset with repo url in the format: https://user@example.com/repo
2. configure or send git webhook request with the same url
3. check the debug logs of argo-server that state that url does not match

**Expected behavior**

repo url in format `http(s)://user@example.com/repo` should match

**Version**

```shell
argocd: v2.8.6+6f7af53BuildDate: 2023-11-01T15:05:10Z
GitCommit: 6f7af53bea9ebc9e9eadd47fc43b671ef91c0586
GitTreeState: clean
GoVersion: go1.20.10
Compiler: gc
Platform: linux/amd64
```

Same regexp is present in the master branch.

**Logs**

```
time="2023-12-15T13:36:03Z" level=debug msg="https://user@some.example.com/org/project/_git/repo does not match (?i)^(http://|https://|[a-zA-Z0-9_\\.][a-zA-Z0-9_\\.-]{0,30}[a-zA-Z0-9_\\.\\$-]?@|ssh://([a-zA-Z0-9_\\.][a-zA-Z0-9_\\.-]{0,30}[a-zA-Z0-9_\\.\\$-]?@)?)some\\.example\\.com(:[0-9]+|)[:/]org/project/_git/repo(\\.git)?$"
```

the problem is here:
https://github.com/argoproj/argo-cd/blob/2f22a690e706c7c7746d6569d22aa345f7005362/util/webhook/webhook.go#L325
https://github.com/argoproj/argo-cd/blob/2f22a690e706c7c7746d6569d22aa345f7005362/applicationset/webhook/webhook.go#L220

user is specified for ssh, but not for http and https

**Comment by robinlieb** [comment]
Hi @messiahUA, can you check if duplicate of #15700?

**Comment by messiahUA** [comment]
@robinlieb yes, indeed, it is.
