### ISSUE TITLE
Improved docs around Private Helm Repos

### ISSUE THREAD

**Issue by domenicbove** [argoproj/argo-cd#16673]
# Summary

After much digging thru the docs, I found that there is a way to configure authentication into a helm repo: https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#helm-chart-repositories

This is under the "Declarative Setup" section... There's no mention of it in the "Helm" section: https://argo-cd.readthedocs.io/en/stable/user-guide/helm/

Even when searching the docs for Helm authentication, nothing comes up

# Motivation

Make the product easier to use!

# Proposal

Probably just add a section in the Helm docs and link to the secret

Thanks!

**Comment by surajyadav1108** [comment]
\assign
