### ISSUE TITLE
Not able to connect to argo-server

### ISSUE THREAD

**Issue by kalpanathanneeru21** [argoproj/argo-cd#16683]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
I am using argocd image version v1.8.2 since long time but from last few days when ever I access argocd cluster list or even argocd version command also throwing below error

**FATA[0000] rpc error: code = Internal desc = transport: received the unexpected content-type "text/plain; charset=utf-8"**

After upgrading the argocd binary to v2.0.0, this problem no longer occurs.

**To Reproduce**

go version
go version go1.20.11 darwin/amd64
curl -sSL -o argocd-darwin-amd64 https://github.com/argoproj/argo-cd/releases/download/v1.8.2/argocd-darwin-amd64 sudo install -m 555 argocd-darwin-amd64 /usr/local/bin/argocd
argocd version

**Expected behavior**
```

% argocd version                 
argocd: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:02:21Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
WARN[0001] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
argocd-server: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:05:50Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.13.2+g2a2fb3b
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Version**

```shell
% argocd version --loglevel debug
argocd: v1.8.2+94017f2
  BuildDate: 2021-01-10T05:42:03Z
  GitCommit: 94017f2c8d97588d4aa2213713a71d51005ed62d
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: darwin/amd64
DEBU[0000] Auth token no longer valid. Refreshing
FATA[0000] rpc error: code = Internal desc = transport: received the unexpected content-type "text/plain; charset=utf-8"
```

**Comment by jgwest** [comment]
The argocd CLI version should match the argocd server version, any other is not supported (it will likely still work, but you would be expected to move up if you hit any bugs).
