### ISSUE TITLE
argocd uninstall should not remove CRD by default

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#167]
Currently `argocd uninstall` removes CRD. This is a problem in clusters is running two or more ArgoCD installations in different namespaces. We need to add `--prune` flag to deleted CRD. By default CRD should not be deleted.

**Comment by jessesuen** [comment]
Agree with this -- I was thinking the same thing. It could additionally prompt user to decide if to delete the CRD and all app instances.
