### ISSUE TITLE
chore: Preventing runnings jobs when updating documentation

### ISSUE THREAD

**Issue by Aym3nTN** [argoproj/argo-cd#16705]
# Problem Statement

When updating documentation files (Markdown files, ***.md**), there is no need to trigger the execution of certain GitHub Actions jobs, such as tests, as these changes don't impact the application's functionality.

# Proposed Solution

Modify the GitHub Actions pipeline configuration to exclude running jobs when changes are made to Markdown files. This can be achieved by adding a `paths-ignore` section to the `on: <push|pull_request>` configuration.

# Expected Benefits

- Preventing the execution of unnecessary jobs on documentation changes optimizes resource usage in the CI/CD pipeline.
- Faster documentation fix feedback.
- CI/CD jobs will be triggered only for changes that directly impact the application's logic, reducing noise and improving clarity.

**Comment by todaywasawesome** [comment]
Great idea!

**Comment by Aym3nTN** [comment]
@todaywasawesome thanks :D What file extensions should we include in this MR other than Markdown files?
