### ISSUE TITLE
cant create new app

### ISSUE THREAD

**Issue by rosscdh** [argoproj/argo-cd#1671]
**Describe the bug**
When simply adding a new git repo to argo-cd via the ui as well as cli

I get
```
 rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to determine app source type: rpc error: code = Unknown desc = 'git ls-files --full-name -z -- //*.yaml' failed: fatal: //*.yaml: '//*.yaml' is outside repository
```

seems related to https://github.com/argoproj/argo-cd/blob/5515b8ce9ddd2133c4b49c01d771122e5738ee39/util/argo/argo.go#L166 or several lines below... however I am not sure which aspect is missing.

**To Reproduce**
1. try integrate https://github.com/rosscdh/hellopy.git

**Expected behavior**
argo-cd performs its tasks

**Screenshots**
<img width="386" alt="Screen Shot 2019-06-03 at 13 19 54" src="https://user-images.githubusercontent.com/397106/58804094-4adbde00-8611-11e9-940d-d4b87eba8d4f.png">

**Version**

```shell
 argocd version
argocd: v1.0.1+5fe1447.dirty
  BuildDate: 2019-05-28T17:28:05Z
  GitCommit: 5fe1447b722716649143c63f9fc054886d5b111c
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.0.1+5fe1447.dirty
  BuildDate: 2019-05-28T17:27:38Z
  GitCommit: 5fe1447b722716649143c63f9fc054886d5b111c
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

```
argocd app create hellopy \
  --repo https://github.com/rosscdh/hellopy.git \
  --path / \
  --dest-server https://kubernetes.default.svc \
  --dest-namespace default
FATA[0001] rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to determine app source type: rpc error: code = Unknown desc = 'git ls-files --full-name -z -- //*.yaml' failed: fatal: //*.yaml: '//*.yaml' is outside repository
```

**Comment by rosscdh** [comment]
Appears to REQUIRE the setting of a kustomize prefix... but "i dont wanna set a prefix, for this . app deployment"

**Comment by rosscdh** [comment]
I can remove the `dev-` kustomize prefix when i edit the project....

**Comment by alexmt** [comment]
Hello @rosscdh . The `--path` is supposed to be a relative path. Please use `.` if you want to use the whole repo.

**Comment by rosscdh** [comment]
Hi there thanks for the response.. not the path.. but the customize
prefix... it must be specified on create.. which is not correct as not all
deployments will have a prefix.

**Comment by alexmt** [comment]
I could not reproduce kustomize prefix issue. Run this command and it worked fine on 1.0.1 .
```
argocd app create hellopy \                                                                                          
  --repo https://github.com/rosscdh/hellopy.git \
  --path "." \
  --dest-server https://kubernetes.default.svc \
  --dest-namespace default
```

Can you please describe steps to reproduce kustomize prefix issue ?

**Comment by rosscdh** [comment]
Thanks for the pointer seems to have been the "/" as you said sorry to be contrary!

**Comment by alexmt** [comment]
Thank you for confirming!
