### ISSUE TITLE
ArgoCD RBAC possibilities to deny sync if flagged with --force

### ISSUE THREAD

**Issue by oliabent** [argoproj/argo-cd#16710]
### Discussed in https://github.com/argoproj/argo-cd/discussions/16709

<div type='discussions-op-text'>

<sup>Originally posted by **oliabent** December 27, 2023</sup>
Hi all, I am exploring ArgoCD RBAC possibilities and can’t find if we can deny sync with --force a flag in a particular role. I can deny sync  (just not allow) the same for delete resources directly (for example StatefulSet). But when I run sync --force it still deletes resources that need to be recreated. Can someone help?</div>

**Comment by todaywasawesome** [comment]
RBAC generally supports and limits verbs, not the options for those verbs. So there's no way to set a rule around using `--force`

**Comment by oliabent** [comment]
@todaywasawesome Thanks a lot for your answer! Closing this one.
