### ISSUE TITLE
UI error message layout issue

### ISSUE THREAD

**Issue by mason-liu** [argoproj/argo-cd#16745]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
Error message popup cannot be displayed properly

**To Reproduce**

1. At project level, add new role
2. Grant "get" to all resources under the related app
3. Project --> edit --> save

**Expected behavior**
Error message should be displayed properly, at least all the text should be visible

**Screenshots**
![image](https://github.com/argoproj/argo-cd/assets/13536982/7de4d28d-d098-4309-b19b-82e0e64521e2)

**Version**
appVersion: v2.9.3
```shell

argocd: v2.5.1+504da42.dirty
  BuildDate: 2022-11-02T01:24:38Z
  GitCommit: 504da424c2c9bb91d7fb2ebf3ae72162e7a5a5be
  GitTreeState: dirty
  GoVersion: go1.19.3
  Compiler: gc
  Platform: darwin/amd64
WARN[0002] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
argocd-server: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:05:50Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.13.2+g2a2fb3b
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

```

```

**Comment by JessieTeng89** [comment]
Hi, 
Can you assign it to me? I would like to work on this issue and create a PR later.

**Comment by JessieTeng89** [comment]
As checked, this is an issue related to argo-ui project, I have created an issue https://github.com/argoproj/argo-ui/issues/512, will fix it there
