### ISSUE TITLE
UI banner empty when permanent and no explicate bannerposition

### ISSUE THREAD

**Issue by igaskin** [argoproj/argo-cd#16740]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
The optional UI banner does not appear if there is no explicate value set for `ui.bannerposition`.

Possibly related to this PR: https://github.com/argoproj/argo-cd/pull/14623

**To Reproduce**
Set the following in the argocd-cm

_does work_
```
data:
  ui.bannercontent: reproduce banner bug
  ui.bannerpermanent: "true"
  ui.bannerposition: top  
  ```
  
<img width="1512" alt="Screenshot 2024-01-03 at 4 04 31 PM" src="https://github.com/argoproj/argo-cd/assets/5673097/ededa2bc-1916-4290-96d2-262621cfd4cc">

  
_does not work_
```
data:
  ui.bannercontent: reproduce banner bug
  ui.bannerpermanent: "true"
  ```
  
<img width="1512" alt="Screenshot 2024-01-03 at 4 03 46 PM" src="https://github.com/argoproj/argo-cd/assets/5673097/105e68a9-0bf5-4483-97c5-2eac1dfe7b85">

**Expected behavior**

**Screenshots**

**Version**

```shell
argocd version
argocd: v2.6.3+e05298b.dirty
  BuildDate: 2023-02-27T15:43:43Z
  GitCommit: e05298b9c6ab8610104271fa8491f019fee3c587
  GitTreeState: dirty
  GoVersion: go1.20.1
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.10.0-rc1+d919606
  BuildDate: 2023-12-18T20:45:12Z
  GitCommit: d9196060c2d8ea3eadafe278900e776760c5fcc6
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.13.2+g2a2fb3b
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by keithchong** [comment]
This appears to be a regression. In the sample config [here](https://github.com/argoproj/argo-cd/blob/c29f6da00cabc46238652bd10c589955a1c4a976/docs/operator-manual/argocd-cm.yaml#L312), the default behavior was such that if the bannerposition was not specified, the content would appear in the the banner at the top of the page.
