### ISSUE TITLE
syncPolicy is always out of sync when defined empty

### ISSUE THREAD

**Issue by bumarcell** [argoproj/argo-cd#16758]
**Describe the bug**

Currently, when deploying an Application with empty syncPolicy, it seems as if the application controller ignores it and doesn't add it to the deployed object, which then leads to a diff of missing `syncPolicy: {}` on the Application

**To Reproduce**

Deploy an Application with empty syncPolicy:
spec.syncPolicy: {}

**Expected behavior**

Application is deployed with empty syncPolicy

**Version**

```shell
argocd-server: v2.9.3+6eba5be
```

**Comment by donflavour** [comment]
@bumarcell how did you manage to fix that issue?

**Comment by bumarcell** [comment]
Not really solved, just ignored 
I guess you could simply remove empty syncPolicy from your code
