### ISSUE TITLE
`api/v1/settings` endpoint exposes password policy publicly 

### ISSUE THREAD

**Issue by svghadi** [argoproj/argo-cd#16775]
**Describe the bug**

The `passwordPattern` field in `api/v1/settings` endpoint's response exposes the password policy publicly. Shouldn't this information be protected behind authentication? IMO, it's a bit concerning to make this information available without authentication unless it's required by design. 

The `passwordPattern` field was introduced in `settings` api in #7071 to enforce password complexity for password reset. As far as I know, the password reset option is only available to authenticated users. Is there a specific reason to keep it open?

**Logs**
Reproducer: Hit `<argocd-url>/api/v1/settings` endpoint via curl or browser

```bash
$ curl https://cd.apps.argoproj.io/api/v1/settings | jq
{
  "url": "https://cd.apps.argoproj.io",
  .........
  "passwordPattern": "^.{8,32}$",
  ..........
}
```

**Version**

```shell
master/latest
```

**Comment by jgwest** [comment]
@svghadi `cd.apps.argoproj.io` doesn't require auth, AFAICT, have you tried on another cluster?

**Comment by svghadi** [comment]
Same behavior with other clusters 😕 . 

API call to my private cluster.
```json
$ curl https://<#########>/api/v1/settings | jq
{
  "url": "https://<#########>",
  "dexConfig": {
    "connectors": [
      {
        "name": "OpenShift",
        "type": "openshift"
      }
    ]
  },
  "appLabelKey": "app.kubernetes.io/instance",
  "resourceOverrides": {
    "apiextensions.k8s.io/CustomResourceDefinition": {
      "ignoreDifferences": "jqPathExpressions: null\njsonPointers:\n- /status\n- /spec/preserveUnknownFields\nmanagedFieldsManagers: null\n",
      "ignoreResourceUpdates": "jqPathExpressions: null\njsonPointers: null\nmanagedFieldsManagers: null\n"
    }
  },
  "googleAnalytics": {},
  "kustomizeOptions": {
    "BuildOptions": "",
    "BinaryPath": ""
  },
  "help": {},
  "passwordPattern": "^.{8,32}$",
  "trackingMethod": "label"
}
```

**Comment by svghadi** [comment]
The issue has been addressed in recent security fix. 
https://github.com/argoproj/argo-cd/security/advisories/GHSA-87p9-x75h-p4j2
