### ISSUE TITLE
ArgoCD stops syncing application for multiple EKS clusters

### ISSUE THREAD

**Issue by davidlcan** [argoproj/argo-cd#16824]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We recently upgraded ArgoCD from `2.4.3` to `2.9.3`. This issue may exist in older version. But we at least met this issue twice after upgrading. I did more investigation for the recent issue.

We have more than 40 EKS clusters managed by an ArgoCD instance, which also manages itself. We find that an application
in a managed cluster is not synced after the PR is merged. After more investigation, I find that all applications in 4 EKS clusters
stopped syncing for around 1 day based on the log.

I find that `Refreshing app status` is recorded in the log before an application is synced based on the [code](https://github.com/argoproj/argo-cd/blob/54f1572d46d8d611018f4854cf2f24a24a3ac088/controller/appcontroller.go#L1680). From the attached graph, we can find that the application for all 4 clusters stopped syncing at around the same time period.

![image](https://github.com/argoproj/argo-cd/assets/105251379/f24efa1b-1d5f-4f78-bdbc-23647f5c6eb1)

But I can not find more clue on why it stopped syncing based on the log. 

I tried to manually sync the application through ArgoCD UI. But it does not help. The syncing resumed after I killed the `argocd-application-controller` pods.

Do you know what can bring this kind of issue? Is it possible to detect when similar issue happens so that we can take action quickly? Thanks for your help.

**To Reproduce**

We are not sure how to recreate this issue. But it happened twice in the last couple weeks.

**Expected behavior**

The applications in all clusters are synced continuously.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
The output of `argocd version` is below. But we do use the 2.9.3 argocd `Image:  xxx.dkr.ecr.us-east-1.amazonaws.com/mirror/quay.io/argoproj/argocd:v2.9.3`.

```
% argocd version                                
argocd: v2.5.9+e5f1194.dirty
  BuildDate: 2023-01-28T01:35:55Z
  GitCommit: e5f1194a6de78cc1124179a4c9bb1ae3484fb77d
  GitTreeState: dirty
  GoVersion: go1.19.5
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.5.9+e5f1194.dirty
  BuildDate: 2023-01-28T01:35:55Z
  GitCommit: e5f1194a6de78cc1124179a4c9bb1ae3484fb77d
  GitTreeState: dirty
  GoVersion: go1.19.5
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.9.2+g1addefb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by rumstead** [comment]
Your argocd-server doesn't look to be using the `v2.9.3` image.

```
❯ docker run --rm quay.io/argoproj/argocd:v2.9.3 argocd version
time="2024-01-29T15:04:38Z" level=fatal msg="Argo CD server address unspecified"
argocd: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:05:50Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/arm64
```

**Comment by davidlcan** [comment]
Hi @rumstead , our argocd-server is the v2.9.3 image. If I run `argocd version` after I connect to the pod, it shows the right version like below.

```
$ kubectl exec --stdin --tty argocd-server-c8b79bb87-bbc59 -n argocd -- sh
Defaulted container "server" out of: server, argocd-extensions
$ pwd
/home/argocd
$ argocd version
argocd: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:05:50Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified           
```

**Comment by reggie-k** [comment]
I see that there are multiple clusters your ArgoCD manages, so this might be related to scale and performance tuning.
If the version issue is out of the way, meaning if you are certain about the upgrade taking place successfully and that you run 2.9.3, the following may be helpful to tune ArgoCD for scale:
Observe ArgoCD metrics in Grafana dashboard.
https://argo-cd.readthedocs.io/en/release-2.9/operator-manual/high_availability/
also, `controller.operation.processors` might need to be tuned.

**Comment by davidlcan** [comment]
Thanks for the input. I am not sure whether it's a performance issue since ArgoCD only stopped syncing 4 managed EKS clusters while other managed EKS clusters can still be synced.

We have upgraded to a newer version and nobody reported similar issue recently. Probably we can close this issue for now.
