### ISSUE TITLE
Argo CD openapi validation spec is incomplete

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1687]
**Describe the bug**

The openapi validation spec generated by https://github.com/kubernetes-sigs/controller-tools is incomplete. We should switch to controller-gen binary, to generate the CRD definition. It provides validation for all fields of the resource, which we were missing before, allowing a controller to be brought down by a single bad manifest.

**Version** v1.0.1

**Comment by alexec** [comment]
Nasty.

**Comment by jessesuen** [comment]
Correction: we are not yet on `github.com/kubernetes-sigs/controller-tools`. We are currently using `github.com/ant31/crd-validation` and need to switch to `github.com/kubernetes-sigs/controller-tools` to get the complete spec.

**Comment by jessesuen** [comment]
This is how it was done for rollouts: https://github.com/argoproj/argo-rollouts/commit/a6aa76deb615c0b6c06a5dea2e539beb86893e64

**Comment by alexmt** [comment]
Fixed

**Comment by alexec** [comment]
In this in v1.2?

**Comment by alexmt** [comment]
yes
