### ISSUE TITLE
Job is not removed from cluster even though it was removed from manifests

### ISSUE THREAD

**Issue by pre** [argoproj/argo-cd#16895]
Removing a Job resource from the Application's manifests does not remove that Job from the cluster even with `prune:true`.

A Job with Hooks was created earlier. At a later point in time, the Job was removed from the Application.
The Job still has the ArgoCD Application's metadata, but it's not removed from the cluster with sync and prune:true. 

Application appears as Healthy instead of OutOfSync.

ArgoCD v2.8.3

<img width="1336" alt="image" src="https://github.com/argoproj/argo-cd/assets/63895/e400c155-3394-4371-897a-3b4df74c05a4">

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    batch.kubernetes.io/job-tracking: ''
    kubectl.kubernetes.io/last-applied-configuration: xyxxy
  creationTimestamp: '2023-11-30T17:12:17Z'
  generation: 1
  labels:
    argocd.argoproj.io/instance: xyzzy
    job: component-set-sync
  name: component-set-sync
  namespace: xyzzy
  resourceVersion: '335653876'
  uid: 8c18ca78-8e1b-4e60-9440-fd53dc0c865b
spec:
  activeDeadlineSeconds: 1800
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  [..]
status:
  completionTime: '2023-11-30T17:12:42Z'
  conditions:
    - lastProbeTime: '2023-11-30T17:12:42Z'
      lastTransitionTime: '2023-11-30T17:12:42Z'
      status: 'True'
      type: Complete
  ready: 0
  startTime: '2023-11-30T17:12:17Z'
  succeeded: 1
  uncountedTerminatedPods: {}
```

**Comment by crenshaw-dev** [comment]
Hook removal is managed independently of manifest removal. https://argo-cd.readthedocs.io/en/latest/user-guide/resource_hooks/#hook-deletion-policies

**Comment by pre** [comment]
Ah, you're correct! I have  `BeforeHookCreation`, but `HookSucceeded` would be desired in my case. Thank you!
