### ISSUE TITLE
Notification controller should show errors on info/error, not only on debug level

### ISSUE THREAD

**Issue by kroustou** [argoproj/argo-cd#16891]
# Summary
If there is a misconfiguration on the service, it's helpful to be able to see it in  the logs.

In our case, we did not ship any triggers nor templates, but the logs only showed one message per app, like this:

```
Trigger on-health-degraded result: []
```

Until we switched to debug level and we saw this:
 
```
{"level":"debug","msg":"Failed to execute condition of trigger on-health-degraded: trigger 'on-health-degraded' is not configured","resource":"argocd/dev-awseuw1-test-krishnan-2-serverless-argo-workflows","time":"2024-01-16T09:02:32Z"}
```

# Motivation
If there is anything wrong with the configuration of the service, it's easy enough to spot the issue, and also set up alerting around  it.

# Proposal
The specific message/messages like the above should be ERROR level logs. I can open a PR, just wanted to make sure it's the desired implementation

**Comment by hckrbaba** [comment]
Hello @alexmt 
I would like to take up this issue!
