### ISSUE TITLE
Error in subapp lock other app synch

### ISSUE THREAD

**Issue by mysiki** [argoproj/argo-cd#16900]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Hey,

I have an Application (deploy by AppSet) which deploy sub application and sub applicationSets. When one of the sub failed, the master application give a 'ComparisonError' and stop to synch the other app. 

Error message `ComparisonError: error setting app health: failed to get resource health for "Application" with name "aws-fcs-dev-app-orwecom-develop-shared" in namespace "argo": <string>:8: attempt to index a non-table object(nil) with key 'match' stack traceback: <string>:8: in main chunk [G]: ?`

trying to graph it : 

```
        |------- SUB APP 02
APP01>  |------- SUB APP 03
        |------- SUB APP 04 (app set in my case) 
``` 

So first synch of APP01 create all subApp. 

After, if any SUB APP failed, APP01 stop apply / synch the other. If I do some change of SUB APP 04 argocd see it (diff panel show the new manifest) but never apply it. Event if I synch only the SUB APP 04. 

![2024-01-17_12h40_34](https://github.com/argoproj/argo-cd/assets/19509977/3925c16c-1ef5-4118-bd75-30d3357d7345)

APP 01 file look like : 

```
└── Chart                                  
    ├── Chart.yaml                            APP 01
    ├── templates
    │   ├── application.yaml              SUB APP 04
    │   ├── licenceServer.yaml           SUB APP 02
    │   └── shared.yaml                    SUB APP 03
    └── values.yaml
```

The only workaround is to delete application with error and resynch. But need to dot it each time !  

**To Reproduce**

Create helm chart than deploy 3 Argo Application. In one of the application, do an error, like target an invalid values file. 

**Expected behavior**

Apply all the helm template event if one is KO

**Screenshots**

Error in SUB APP 03

![2024-01-17_12h40_42](https://github.com/argoproj/argo-cd/assets/19509977/f1ef9e03-d480-4485-9d0a-70acaf09353e)

Diff in SUB APP 04 never apply, only apply when I delete the fail app (SUB APP 03)

![2024-01-17_15h22_39](https://github.com/argoproj/argo-cd/assets/19509977/bb630e65-ade0-4dc0-838c-c0ddb0fce75d)

**Version**

```shell
argocd: v2.8.4+c279299
  BuildDate: 2023-09-13T19:43:37Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.9.1+58b04e5
  BuildDate: 2023-11-14T15:08:20Z
  GitCommit: 58b04e5e11d007b0518853029ff7612c24a2eb35
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

Argocd cli synch 

```
argocd app sync aws-fcs-dev-wrp-orwecom-develop
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
TIMESTAMP                  GROUP              KIND       NAMESPACE                  NAME                          STATUS    HEALTH         HOOK  MESSAGE
2024-01-17T12:40:50+01:00  argoproj.io  ApplicationSet        argo  aws-fcs-dev-appset-orwecom-develop-tenants  OutOfSync  Healthy
2024-01-17T12:40:50+01:00  argoproj.io  Application           argo  aws-fcs-dev-app-orwecom-develop-ls            Synced   Degraded
2024-01-17T12:40:50+01:00  argoproj.io  Application           argo  aws-fcs-dev-app-orwecom-develop-shared        Synced   Unknown

Name:               argo/aws-fcs-dev-wrp-orwecom-develop
Project:            production
Server:             https://925F8230EF5F9560D73A8514E78E32BE.gr7.eu-west-1.eks.amazonaws.com
Namespace:          argo
URL:                https://argo.aws-cd.internal.forterro.com/applications/aws-fcs-dev-wrp-orwecom-develop
Repo:               https://gitlab.forterro.com/forterro-apps/inventories/inventory-orwecom.git
Target:             develop
Path:
SyncWindow:         Sync Allowed
Sync Policy:        Automated (Prune)
Sync Status:        OutOfSync from develop
Health Status:      Degraded

Operation:          Sync
Sync Revision:
Phase:              Error
Start:              2024-01-17 12:40:50 +0100 CET
Finished:           2024-01-17 12:40:51 +0100 CET
Duration:           1s
Message:            ComparisonError: error setting app health: failed to get resource health for "Application" with name "aws-fcs-dev-app-orwecom-develop-shared" in namespace "argo": <string>:8: attempt to index a non-table object(nil) with key 'match'
stack traceback:
        <string>:8: in main chunk
        [G]: ?

GROUP        KIND            NAMESPACE  NAME                                        STATUS     HEALTH    HOOK  MESSAGE
argoproj.io  Application     argo       aws-fcs-dev-app-orwecom-develop-ls          Synced     Degraded
argoproj.io  Application     argo       aws-fcs-dev-app-orwecom-develop-shared      Synced     Unknown
argoproj.io  ApplicationSet  argo       aws-fcs-dev-appset-orwecom-develop-tenants  OutOfSync  Healthy
FATA[0008] Operation has completed with phase: Error
```

**Comment by mysiki** [comment]
seems to be link to my lua rules ...

**Comment by pablords** [comment]
I have the same error. how did you solve it?

**Comment by alikhil** [comment]
Library functions are not supported during the runtime of custom Lua checks. That's why there was an error when `string.match` function was used
