### ISSUE TITLE
issue with branch_slug in the pull request generator

### ISSUE THREAD

**Issue by krisdock** [argoproj/argo-cd#16931]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

the branch slug should be cleaned to not include dots. as specified in the k8s documentation [here](https://github.com/argoproj/argo-cd/issues/10622), label names should:

>contain at most 63 characters
contain only lowercase alphanumeric characters or '-'      <<<<<<
start with an alphabetic character
end with an alphanumeric character

pull_request.go is cleaning "_" to "-", but not addressing "." and this causes issues down the line when trying to create a k8s namespace based on this.

**To Reproduce**

create an applicationset using the pull request generator and add the appropriate label to a pr on a branch with a "." in the name, which applies pretty widely to tags/releases

**Expected behavior**

"." should be cleaned to "-"

**Version**

```shell
argocd: v2.8.4+c279299.dirty
  BuildDate: 2023-09-13T20:25:25Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: dirty
  GoVersion: go1.21.1
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.7.3+e7891b8.dirty
  BuildDate: 2023-05-24T15:05:34Z
  GitCommit: e7891b899a35dca06ae94965ea5ae2a86b344848
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Comment by ShubhamRasal** [comment]
why did you closed the without any answer or finding related to this?
