### ISSUE TITLE
Performance improvements/optimizations desperately needed

### ISSUE THREAD

**Issue by tdevopsottawa** [argoproj/argo-cd#16939]
# Summary

Argo's web UI is an atrocious platform when it comes to bloat & poor performance. It's almost completely unusable to people with slower network connections (note that there's billions of people in the world who don't have any access to fast internet), and even on my fairly high performance PC loading things in the UI regularly causes my browser to use 100% of CPU and RAM. Please focus some resources on optimizing the product and making it usable.

**Comment by keithchong** [comment]
Hi @tdevopsottawa , would you be able to provide some more details in your situation? If you have the browser's developer tools enabled, check the Network, Performance or Memory tabs.  This might help shed some light on where to focus first. Also, how many applications, associated resource nodes, etc. do you have? Any screenshots will help too.
