### ISSUE TITLE
Add the ability to scale the application-set controller more.

### ISSUE THREAD

**Issue by tomelliot16** [argoproj/argo-cd#16945]
# Summary

- Have the ability to scale up max reconciles larger then 100
- Have the ability to raise qps and burst for kubernetes api.

# Motivation

- We are running into scale issues 

# Proposal

- Raise the maxReconciles max to 500 in the application-set-controller bin arg 
- Add qps and burst as args to the application-set-controller bin

**Comment by blakepettersson** [comment]
I know that @JorTurFer was interested in working on this, pending first profiling the Appset controller to see where the actual bottlenecks are (see #16594).

**Comment by JorTurFer** [comment]
Yeah, I've it on my TODOs list, but currently there are too many things on my plate... 😢
