### ISSUE TITLE
Conflict between ArgoCD and MongoDB Operator during deletion process

### ISSUE THREAD

**Issue by yadamovych** [argoproj/argo-cd#16958]
**Describe the bug**

During the deletion process of an ArgoCD application that deploys a Helm chart from an OCI repository, a conflict occurs. This Helm chart contains a custom resource MongoDBCommunity, which creates MongoDB clusters and configurations via the MongoDB operator. However, when I initiate the deletion of the ArgoCD application, it attempts to delete all child resources. The MongoDB operator, not understanding why the child resources are disappearing, recreates them. This results in a conflict.

**To Reproduce**

1. Deploy a Helm chart from an OCI repository using ArgoCD. This Helm chart should contain the MongoDBCommunity custom resource.
2. Initiate the deletion of the ArgoCD application.
3. Observe that the MongoDB operator recreates the child resources that ArgoCD is trying to delete.

**Expected behavior**

I expect the ArgoCD application and all its child resources to be deleted without conflict.

**Version**

v2.9.3

**Logs**

Mongodb operator:
```
2024-01-23T15:45:04.895Z	ERROR	controllers/replica_set_controller.go:464	Could not create or patch the service: Operation cannot be fulfilled on services "mongodb-svc": the object has been modified; please apply your changes to the latest version and try again	{"ReplicaSet": "dev2/mongodb"}
github.com/mongodb/mongodb-kubernetes-operator/controllers.(*ReplicaSetReconciler).ensureService
	/workspace/controllers/replica_set_controller.go:464
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.Reconcile
	/workspace/controllers/replica_set_controller.go:150
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227
2024-01-23T15:45:04.895Z	INFO	controllers/mongodb_tls.go:40	Ensuring TLS is correctly configured	{"ReplicaSet": "dev2/mongodb"}
2024-01-23T15:45:04.896Z	INFO	controllers/mongodb_tls.go:83	Successfully validated TLS config	{"ReplicaSet": "dev2/mongodb"}
2024-01-23T15:45:04.896Z	INFO	controllers/replica_set_controller.go:299	TLS is enabled, creating/updating CA secret	{"ReplicaSet": "dev2/mongodb"}
2024-01-23T15:45:04.953Z	INFO	controllers/replica_set_controller.go:303	TLS is enabled, creating/updating TLS secret	{"ReplicaSet": "dev2/mongodb"}
2024-01-23T15:45:05.016Z	DEBUG	controllers/replica_set_controller.go:404	Enabling TLS on an existing deployment, the StatefulSet must be updated first	{"ReplicaSet": "dev2/mongodb"}
2024-01-23T15:45:05.017Z	INFO	controllers/replica_set_controller.go:335	Creating/Updating StatefulSet	{"ReplicaSet": "dev2/mongodb"}
2024-01-23T15:45:05.104Z	INFO	controllers/replica_set_controller.go:340	Creating/Updating StatefulSet for Arbiters	{"ReplicaSet": "dev2/mongodb"}
2024-01-23T15:45:05.209Z	DEBUG	controllers/replica_set_controller.go:350	Ensuring StatefulSet is ready, with type: RollingUpdate	{"ReplicaSet": "dev2/mongodb"}
...
2024-01-23T15:47:30.506Z	ERROR	controllers/mongodb_status_options.go:104	Error deploying MongoDB ReplicaSet: error getting StatefulSet: StatefulSet.apps "mongodb" not found
github.com/mongodb/mongodb-kubernetes-operator/controllers.messageOption.ApplyOption
	/workspace/controllers/mongodb_status_options.go:104
github.com/mongodb/mongodb-kubernetes-operator/pkg/util/status.Update
	/workspace/pkg/util/status/status.go:25
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.Reconcile
	/workspace/controllers/replica_set_controller.go:201
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227
```

**Comment by gbrown-axoni** [comment]
I'm encountering the same issue - ArgoCD tries to delete the `StatefulSet` created by a `MongoDBCommunity` resource before deleting the actual mongo resource, so the statefulset is recreated over and over again and Argo never finishes deleting the application.

**Comment by yadamovych** [comment]
I was able to solve an issue where deploying MongoDBCommunity manifest separately worked by using additional annotations for Argocd to configure PrunePropagationPolicy and preserveResourcesOnDeletion. Here's the code snippet: 

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PrunePropagationPolicy=orphan,preserveResourcesOnDeletion=true,SkipDryRunOnMissingResource=true
  name: ${mongodb_name}
  namespace: ${namespace}
```

However, this approach did not work when MongoDBCommunity was part of a Helm chart. It appears that the Argocd Helm plugin does not read resource annotations for Argocd configs.

**Comment by yadamovych** [comment]
I've investigated this problem and found that it is more related to the MongoDB Operator, which doesn't handle foreground deletion correctly.

ArgoCD uses Kubernetes finalizers to manage the deletion of resources. By default, ArgoCD waits for all child resources to be deleted before it removes the finalizer from the parent resource, ensuring that the entire hierarchy of resources is deleted properly. This is known as foreground deletion. However, if the MongoDB Operator does not handle this process correctly, it can lead to the issues described.

Proposed Solution:
The issue can be easily fixed by adding background finalizers to the ArgoCD application. This allows the parent resource to be deleted immediately while the child resources are deleted in the background.

Here is the configuration to add background finalizers:

```yaml
Copy code
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-chart-with-mongodb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
```
By using this configuration, the deletion process should work as expected without encountering issues with the MongoDB Operator.
