### ISSUE TITLE
Argocd 2.8.4 Upgrade: ApplicationSet having Git Generator is is not able to sync with Git code and shows desired manifest as blank

### ISSUE THREAD

**Issue by ashish-dua** [argoproj/argo-cd#16989]
(https://argoproj.github.io/community/join-slack). -->

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
GIT version:2.34.1 in Argocd applicationset controller

Argocd 2.8.4 Upgrade: ApplicationSet having Git Generator  is not able to sync with Git code and shows desired manifest as blank Because of it ; It is not able to take Desired manifest from Github repo; Looks like git fetch and git checkout operations are not working at all
ApplicationSet with Git generator doesn't seem to be working with plugin derived from sidecar. Affected Aplicationset worked with GitGenerator having helm:valueFiles in Argocd 2.5 but not working with Argocd 2.8.4

**To Reproduce**
:
1) Upgrade Argocd from 2.5.1 to 2.8.4
2) Introduced --plain-text in argocd applicationset controller pod args to disable tls communication from argocd-repo-server
3) Restart Argocd applicationset controller pod
4) Argocd 2.8.4 Upgrade: ApplicationSet having Git Generator with Helm value files is not able to sync with Git code and shows desired manifest as blank Because of it ; It is not able to take Desired manifest from Github repo; Looks like git fetch and git checkout operations are not working at all

**Expected behavior**
ApplicationSet having Git Generator with Helm value files should be  able to sync with Git code and should be able to deploy Applicationset on its own synching with Git repositary

Sample ApplicationSet having problem syncing with Github repo in Argocd 2.8:

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: xyz
  namespace: argocd
  labels:
    argocd.appset.io/instance: "xyz"
spec:
  generators:
  - git:
      repoURL: https://github.com/McK-Internal/xyz.git
      revision: HEAD
      directories:
      - path: clusters/*
  template:
    metadata:
      name: "xyz-{{path.basename}}"
    spec:
      syncPolicy:
        automated:
          prune: true
      project: default
      source:
        repoURL: https://github.com/McK-Internal/xyz.git
        targetRevision: HEAD
        path: xyz/abc
        helm:
          # Release name override (defaults to application name)
          valueFiles:
          - ../../clusters/base/applications.yaml
          - ../../clusters/base/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argued

**Screenshots**
<img width="1440" alt="image" src="https://github.com/argoproj/argo-cd/assets/86287790/70b84afe-e6e0-4da1-92ef-d2b2360183e3">

**Version**

```shell
Argocd 2.8.4
```

**Logs**
time="2024-01-29T12:26:09Z" level=error msg="error generating application from params" error="rpc error: code = Unimplemented desc = unknown method GetGitDirectories for service repository.RepoServerService" generator="{nil nil &GitGenerator{RepoURL:https://github.com/argoproj/argo-cd.git,Directories:[]GitDirectoryGeneratorItem{GitDirectoryGeneratorItem{Path:applicationset/examples/git-generator-files-discovery/*,Exclude:false,},},Files:[]GitFileGeneratorItem{},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{},} nil nil nil nil nil nil nil}"
time="2024-01-29T12:26:09Z" level=error msg="error generating params" error="rpc error: code = Unimplemented desc = unknown method GetGitDirectories for service repository.RepoServerService" generator="&{0xc0011fa5c0}"
time="2024-01-29T12:26:09Z" level=error msg="error generating application from params" error="rpc error: code = Unimplemented desc = unknown method GetGitDirectories for service repository.RepoServerService" generator="{nil nil &GitGenerator{RepoURL:https://github.com/McK-Internal/xyz.git,Directories:[]GitDirectoryGeneratorItem{GitDirectoryGeneratorItem{Path:clusters/x/*,Exclude:false,},},Files:[]GitFileGeneratorItem{},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{},} nil nil nil nil nil nil nil}"

time="2024-01-25T10:27:05Z" level=info msg="manifest cache hit: &ApplicationSource

**Comment by ashish-dua** [comment]
Please update in case of argocd 2.8.4 upgrade; nothing has been updated.

**Comment by mmerrill3** [comment]
Another thing to check is what version of the repo server is running?  This commit introduced that grpc method for GetGitDirectories on the repo server.  If the repo server is older, than I wouldn't expect the API to be available.  https://github.com/argoproj/argo-cd/commit/a695aa866529f4499cc017325a6068f6b1b15566.  This looks to be in version 2.8.0 and greater only.

**Comment by mmerrill3** [comment]
@ashish-dua, is this still an issue for you?

**Comment by jgwest** [comment]
Closing as no response from reporter. Feel free to open a new issue with details if the issue is still reproducible.
