### ISSUE TITLE
Repo Server continually pulling for missing Helm Chart

### ISSUE THREAD

**Issue by baileydoestech** [argoproj/argo-cd#16994]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Since upgrading to 2.9.5 (from 2.8.7) we are seeing large CPU usage and memory growth on the repo-server as shown below:

![image](https://github.com/argoproj/argo-cd/assets/3185073/ec51f22d-8a1d-49f1-be26-5998e1af9f0d)

This appears to be caused by a missing helm chart in our on-premise registry, previously this would error (as expected) but had no material impact on the repo server. However, in the latest release it seems that the repo server is constantly pulling for the helm chart (hammering the CPU) and potentially writing to memory which would account for the growth. 

We see errors in the logs every second, note that the `tmp` location is changing every time:

**To Reproduce**

- Upgrade to latest ArgoCD 2.9.5
- Delete a helm chart from source registry that is used within an application

**Expected behavior**

I would still expect this to fail as before in earlier releases but have some sort of back-off logic and then stop pulling for the chart until manually triggering a sync again (same behavior as pre 2.9)

**Version**

```shell
argocd: v2.9.5+f943664
  BuildDate: 2024-01-19T17:57:57Z
  GitCommit: f9436641a616d277ab1f98694e5ce4c986d4ea05
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
2024-01-26T08:23:38.267061993Z stderr F time="2024-01-26T08:23:38Z" level=error msg="finished unary call with code Unknown" error="`helm pull --destination /tmp/86152499-576f-484a-93b6-df40c56a5548 --version 3.12.0-f.6.pr-248-590ced --repo https://packages/repository/XXXX --ca-file /app/config/tls/packages` failed exit status 1: Error: chart \"XXXX\" version \"3.12.0-f.6.pr-248-590ced\" not found in https://packages/repository/XXXX" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2024-01-26T08:23:37Z" grpc.time_ms=811.746 span.kind=server system=grpc
```

**Comment by aryasoni98** [comment]
@baileydoestech Can i work on this issue .

**Comment by schmel** [comment]
Same problem. Repo server creates many folders in /tmp directory and does not clean them up. After some time, the free inodes runs out.
```
argocd@argocd-repo-server-54bff895cc-p9qh9:~$ find /tmp -mindepth 1 -type d | wc -l
244271
```
after ~ 5 minutes: 
```
argocd@argocd-repo-server-54bff895cc-p9qh9:~$ find /tmp -mindepth 1 -type d | wc -l
244327
```

**Comment by baileydoestech** [comment]
@aryasoni98 was this something you had a chance to look at? We are still still the issue in latest ArgoCD

**Comment by ilia-medvedev-codefresh** [comment]
I'm working on it. Will submit a fix for the excessive folder creation in the upcoming day or 2.
