### ISSUE TITLE
v2.10.0-rc4:  controller is configured to ignore cluster https://kubernetes.default.svc

### ISSUE THREAD

**Issue by ssh-sky** [argoproj/argo-cd#17016]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

I was previously running v2.10.0-rc1 in HA mode and with lates upgrade it failed to sync apps

in Settings -> Clusters 2 out of 3 clusters went to missing Connection and Version info.
I've tried `Invalidate Cache` and deleting the `argocd.argoproj.io/refresh` annotation, but upon retrying sync they went away again.

**Expected behavior**

**Screenshots**

**Version**

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ssh-sky** [comment]
I've reverted back to `v2.10.0-rc1` as a workaround.

**Comment by blakepettersson** [comment]
Perhaps @akram has an idea?

**Comment by amontalban** [comment]
We are having this issue after ArgoCD was updated today:

```{
    "Version": "v2.10.0+2175939",
    "BuildDate": "2024-02-06T14:28:43Z",
    "GitCommit": "2175939ed6156ddd743e60f427f7f48118c971bf",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.0+g3fc9f4b",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

**Comment by nobbs** [comment]
Running into the same issue - basically not able to manage any applications running in-cluster / `kubernetes.default.svc`.

**Comment by YGwen** [comment]
We are having this issue as well with v2.10.0 - 
![image](https://github.com/argoproj/argo-cd/assets/5558278/a0962f9d-b321-417c-a63c-01083ae789be)

**Comment by nistei** [comment]
We are having the same issue for multiple clusters with v2.10.0. Our local cluster is working but some others are not:
```
error getting cluster: controller is configured to ignore cluster https://some-other-cluster.com:6443
```

For now, I rolled back to v2.9.5.

**Comment by solidnerd** [comment]
We are also facing the same issue and set also `cluster.inClusterEnabled: "true"`

**Comment by sambonbonne** [comment]
We face the same issue, not with the `in-cluster` cluster but with two clusters we configured with `Secrets`. Those were working fine until we upgraded to `2.10.0`.

**Comment by crenshaw-dev** [comment]
Has anyone narrowed it down further than 2.10.0-rc1 - 2.10.0-rc3? That's pretty narrow, but knowing the exact version would be awesome!

**Comment by nistei** [comment]
2.10.0-rc1 no problems
2.10.0-rc2 the issue occurs
![image](https://github.com/argoproj/argo-cd/assets/1652722/f8ac42ef-92e5-4c26-839d-e42a1f3f7f95)

**Comment by nistei** [comment]
https://github.com/argoproj/argo-cd/commit/a6d8c924eee8e1a30128377f3f59e70d48a89c2d looks suspicious and is between rc1 and rc2

**Comment by CarpathianUA** [comment]
+1

**Comment by hfiorillo** [comment]
+1

**Comment by tonyschak** [comment]
+1

**Comment by crenshaw-dev** [comment]
Let's go with thumbs-ups on the original post instead of plus-ones from now. Thanks for the confirmations!

**Comment by shyukri** [comment]
https://github.com/argoproj/argo-cd/issues/17124 maybe a duplicate

**Comment by brunodeoliveiramacedo** [comment]
Looks related to this [PR](https://github.com/argoproj/argo-cd/pull/15237/files#diff-f5220d702bcabf138f16d7b8e08375d96145a6073941f07df3a5801264ad5442R49)

**Comment by akram** [comment]
Hi @ssh-sky 

do you also have in your logs:
```
The cluster %s has no assigned shard.
```

can you enable debug on the `application-controller` log and look for lines similar to
```
Checking if cluster %s with clusterShard %d should be processed by shard %d"
```

**Comment by crenshaw-dev** [comment]
Anyone who is using the default sharding (or no sharding) setup, can you thumbs-up this comment? 

Just trying to determine if this issue is limited to folks who have opted into non-default sharding strategies.

**Comment by jetersen** [comment]
@crenshaw-dev we use the sharding setup from argocd helm repo 🤔 With Statefulset, 3 replica. Two Argo CD Server and 3 Redis replica and using haproxy for load balancing.

**Comment by woehrl01** [comment]
Can someone please confirm that setting the ENV `ARGOCD_CONTROLLER_SHARD` to `-1` on the controller acts as a workaround to fix that issue?

**Comment by MrTolerant** [comment]
Helm values:
```
controller: 
   env:
      - name: ARGO
         value: "-1"
```
Workaround works, thank you @woehrl01

**Comment by crenshaw-dev** [comment]
Is 2.10.1 working for y'all? 

Seems like maybe not. https://github.com/argoproj/argo-cd/issues/17257

**Comment by llavaud** [comment]
> Is 2.10.1 working for y'all?
> 
> Seems like maybe not. #17257

ok for me !

**Comment by aviveiro** [comment]
@crenshaw-dev - do you know of any other workaround besides updating to 2.10.1? I posted in the linked resolved issue as well but am looking for any insight here - thank you in advance!
