### ISSUE TITLE
Add kubernetes v1.29 to the ci github actions

### ISSUE THREAD

**Issue by csantanapr** [argoproj/argo-cd#17030]
# Summary

Update the github action https://github.com/argoproj/argo-cd/blob/master/.github/workflows/ci-build.yaml#L365

# Motivation

Kubernetes v1.29 was released on December 2023, and ArgoCD 2.10 is about to be release it would be good to have this in our test matrix to claim support.

# Proposal

Update the github actions to add v1.29, but I would not  remove 1.25 just yet. Upstream kubernetes doesn't support 1.25 but there are cloud providers that support this version in their managed offerings

**Comment by d1egoaz** [comment]
Hello @shyukri @crenshaw-dev 

Is [this](https://github.com/argoproj/argo-cd/pull/17050) changed intended to be part of a future release, or something is off that it's not updating the compatibility matrix in https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#tested-versions

As of today, March 6, 2024:

`stable`:
https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#tested-versions
<img width="300" alt="image" src="https://github.com/argoproj/argo-cd/assets/950087/0599b5ac-d7da-41e3-9fa3-a5187987f192">


`latest`:
https://argo-cd.readthedocs.io/en/latest/operator-manual/installation/#tested-versions
<img width="300" alt="image" src="https://github.com/argoproj/argo-cd/assets/950087/e07e5c54-912f-40ac-ae9e-efcff814cbac">


Additionally, when I click on the latest I see this message:

<img width="800" alt="image" src="https://github.com/argoproj/argo-cd/assets/950087/15088b8c-c24c-4e2b-abed-ee53cde2ac54">

It's still referencing `2.9.x` as it's the one in Github releases with the `latest` label.
<img width="234" alt="image" src="https://github.com/argoproj/argo-cd/assets/950087/a03d7ed4-00a4-4e07-9151-2e81dd8aa4f3">

However, the latest release in the releases section is
[v2.10.2](https://github.com/argoproj/argo-cd/releases/tag/v2.10.2)

Isn't `2.10.x` the latest official release?
