### ISSUE TITLE
[ui bug] healthy or not

### ISSUE THREAD

**Issue by kwladyka** [argoproj/argo-cd#1710]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3903726/59116826-b3e28f00-894c-11e9-9fd0-5f15511762b4.png)

auth-provider-tls
![image](https://user-images.githubusercontent.com/3903726/59116911-e68c8780-894c-11e9-8cf0-a5595a80255e.png)

Everything looks ok. In all possible places I don't see any errors but I see this degraded icons on resources like on screenshoot.

Oh interesting, after about 5-10 minutes icons changed from degraded to healthy. But it was confused.

**To Reproduce**
I don't know. I started cluster from 0 node to 1 node and added this `auth` Application in the meantime.

**Expected behavior**
Right icons.

**Version**

```shell
argocd version
argocd: v1.0.1+5fe1447.dirty
  BuildDate: 2019-05-28T17:28:05Z
  GitCommit: 5fe1447b722716649143c63f9fc054886d5b111c
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.0.1+5fe1447.dirty
  BuildDate: 2019-05-28T17:27:38Z
  GitCommit: 5fe1447b722716649143c63f9fc054886d5b111c
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Comment by alexec** [comment]
an app even one degrade resource should be degraded

**Comment by alexec** [comment]
maybe a cache issue?

**Comment by kwladyka** [comment]
I have no idea and I didn't know how to debug / get more useful info.

**Comment by alexec** [comment]
I'd like to see if this happens again so we can repro. If it does happen, try a refresh then a hard refresh. If that helps, then it maybe cache issue.

**Comment by kwladyka** [comment]
This happen just after refresh.

**Comment by alexmt** [comment]
Only top-level resources contribute to the application health status. The expectation is that resource controller watches child resources and set status to the parent resourcse which can be interpretated as health or unhealty (e.g. Deployment might produce unhealthy pods but it does not mean that deployment is not going to be healty eventually)

**Comment by alexmt** [comment]
So I think this is working as expected.

**Comment by kwladyka** [comment]
Hmm but this resources had no errors in events in Argo CD UI.

**Comment by kwladyka** [comment]
But anyway I would like to see something is wrong with my Application even if it is about lower level resources.

**Comment by alexmt** [comment]
This would require to repeat the health check logic of each controller, but this is impossible. Deployment is a good example: pod might get evicted, oom killed and but application stays healthy because replicaset just reschedules pods. Only if pods keep crashing controller deployment marks deployment as degraded. 

Unless Ingress gets annotated by the controller which produced unhealthy certs we cannot reliably assume that ingress is unhealthy.
