### ISSUE TITLE
Typo in message "Shared resouce found"

### ISSUE THREAD

**Issue by komapa** [argoproj/argo-cd#17113]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

https://github.com/argoproj/argo-cd/blob/d494d3a3311050f36a7ebaa9d816d560a3f73a31/controller/sync.go#L106

**To Reproduce**

Have a shared resource

**Expected behavior**

`Shared resource found`

**Version**

2.9.3

**Comment by soravkumarsharma** [comment]
I would like to work on this issue
