### ISSUE TITLE
Provide a warning when updating a CRD with an invalid value

### ISSUE THREAD

**Issue by nandinisingh759** [argoproj/argo-cd#17135]
**Describe the bug**

When updating a CR with a field that was not present in the CRD, `kubectl apply` throws a `strict decoding error: unknown field`. However, argo-cd allows a sync of the new field on the CR but, the field is not actually preserved in the live state. 

**To Reproduce**
- Create a CustomResource -> edit the CR to add in a garbage field and `kubectl apply` the new CR --> you should get a `strict decoding error: unknown field`
- Through argoCD UI edit the manifest to include the garbage value and sync it --> this won't cause any issue but when you refresh the app the value will have been removed 

**Expected behavior**
It would be good to have a warning through the UI when adding in a field that does not exist in the CRD. I found where I believe Kubernetes does the validation of the CR [here](https://github.com/kubernetes/kubernetes/blob/11b974043604f5ccbeb6e5e62e1d9edcf00bc336/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/objectmeta/coerce.go#L111). So we can try to replicate that behavior in Argo.

**Screenshots**
![Screenshot 2024-01-31 at 1 57 16 PM](https://github.com/argoproj/argo-cd/assets/40529546/8fffab5b-31b9-418d-904e-923b04c21de8)

![Screenshot 2024-01-31 at 1 57 43 PM](https://github.com/argoproj/argo-cd/assets/40529546/ee47f0a2-abda-4385-a3a8-b4db617c41ee)

![Screenshot 2024-01-31 at 1 58 43 PM](https://github.com/argoproj/argo-cd/assets/40529546/5fddc7fc-01a8-4ba4-8b18-b4a28b98a6a0)
![Screenshot 2024-01-31 at 1 59 12 PM](https://github.com/argoproj/argo-cd/assets/40529546/132b26e5-4184-4265-8668-45614c04cc7a)

**Version**
```shell
argocd: v2.8.0+804d4b8.dirty
  BuildDate: 2023-08-07T15:16:09Z
  GitCommit: 804d4b8ca6bc4c2cf02c5c971aa923ec5b8623f0
  GitTreeState: dirty
  GoVersion: go1.20.7
  Compiler: gc
  Platform: darwin/arm64
```

**Comment by jgwest** [comment]
> However, argo-cd allows a sync of the new field 

Are you using skip dry run, which is commonly used on CRDS? https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
