### ISSUE TITLE
Applicationset CRD is missing parameter descriptions

### ISSUE THREAD

**Issue by isaacnboyd** [argoproj/argo-cd#17147]
# Summary

The ApplicationSet CRD is missing almost all parameter descriptions under `applicationset.spec`. I propose that we fill these out. Fortunately there will be a lot of carryover from the Application CRD. 
```
kubectl explain applicationset
kubectl explain applicationset.spec
kubectl explain applicationset.spec.template.spec
```

# Motivation

I am a faithful `oc/kubectl explain` user and I was disappointed to see the lack of descriptors under the applicationset spec. 

# Proposal

I would like to create a pull request with descriptors for the ApplicationSet and the parameters under ApplicationSet.spec. If a maintainer of this project believes this to be a valuable contribution, please assign this issue to me and I will start working on a PR. 

Thank you,
-Isaac

**Comment by jgwest** [comment]
[This was actually intentional](https://github.com/argoproj/argo-cd/blob/7e80f1e8e59da2701c87e97b6bda4c64345a90e2/hack/gen-crd-spec/main.go#L53), as the `CustomResourceDefinition` for `ApplicationSet` CRD that was being generated was too large (hitting max K8s resource size limit).

**Comment by isaacnboyd** [comment]
> [This was actually intentional](https://github.com/argoproj/argo-cd/blob/7e80f1e8e59da2701c87e97b6bda4c64345a90e2/hack/gen-crd-spec/main.go#L53), as the `CustomResourceDefinition` for `ApplicationSet` CRD that was being generated was too large (hitting max K8s resource size limit).

Interesting. This is [the commit you linked](https://github.com/argoproj/argo-cd/commit/569a2a6bc609ed6cea6f907bf42411a58fbd43eb). Was this the change you meant to link? It looks like this is about removing an AppProject field. Asking for clarification, I'm not familiar with this code. 

I see how  the fields under `applicationset.spec.template.spec` could become large and redundant. Is there a way we can reduce the size of the CRD by only filling out the applicationset specific fields under `applicationset.spec.*` and not `applicationset.spec.template.*`

**Comment by jgwest** [comment]
Ah, sorry, the line was 2 lines below the one I linked: https://github.com/argoproj/argo-cd/blob/7e80f1e8e59da2701c87e97b6bda4c64345a90e2/hack/gen-crd-spec/main.go#L58

`gen-crd-spec` generates the ARgo CD CRDs using controller-gen (as per usual), then modifies the generate YAML resources after the fact. In this case, it recursively removes the description field from ApplicationSet CRDs.

**Comment by jgwest** [comment]
https://github.com/argoproj/argo-cd/issues/10836
