### ISSUE TITLE
Stable docs site not yet updated for v2.10

### ISSUE THREAD

**Issue by glasser** [argoproj/argo-cd#17164]
ArgoCD v2.10 was released a few days ago, and the [stable tag](https://github.com/argoproj/argo-cd/releases/tag/stable) was updated, but the readthedocs site hasn't been updated yet. Does something special have to happen to make this happen?

Notably, the [link in the release notes to upgrade instructions](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/overview/) hasn't been updated yet to include the v2.9 to v2.10 instructions, which seems confusing! It's there in [latest](https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/overview/) at least but that may be harder to find.

**Comment by crenshaw-dev** [comment]
Good catch! I just pushed the tag.

We need to automate that process, but haven't had a chance yet.

**Comment by glasser** [comment]
Great — just to note, it hasn't updated yet for me but maybe there's a longer delay than 45 minutes? (It did look like the stable tag in this repo had already been pushed before I filed the issue, but maybe you mean a different tag or a different place?)

**Comment by crenshaw-dev** [comment]
Hm. I'm running a manual ReadTheDocs build, maybe that will clear it up. Might not play nice with tag force-pushes?

**Comment by glasser** [comment]
Looks good now!
