### ISSUE TITLE
Example config maps not linked in docs

### ISSUE THREAD

**Issue by thechubbypanda** [argoproj/argo-cd#17196]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The file https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cm-yaml/ is not linked anywhere in the docs from what I can tell. There is also no mention of how to use/edit things regarding the manifest installation configuration generally. As someone new to Kubernetes, it took me a while to figure out that there were config maps that I had to edit.

**To Reproduce**

https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cm-yaml/ is not linked in the file tree on the docs site

**Expected behavior**

A configuration page should exist

**Screenshots**

**Version**

```shell
2.10.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jgwest** [comment]
It's linked from https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/

**Comment by thechubbypanda** [comment]
Ah I see now... I got very confused as at the top of that page, it mentions applications and projects, not configuring argocd itself...
