### ISSUE TITLE
Argo App Problema v2.9.5

### ISSUE THREAD

**Issue by davidfalconego** [argoproj/argo-cd#17212]
Checklist:

* [yes ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ yes] I've included steps to reproduce the bug.
* [ yes] I've pasted the output of `argocd version`.

**Describe the bug**

ARGOCD version HA 2.9.5
Gitlab Monorepo (at least 200 apps running from there in argocd)
There are others apps using the same cluster, ns, gitlab on that argocd server that are running well.

After upgrading to version HA 2.9.5 some fo my argocd apps (not all) keeps on a SYNC ERROR with this message

**ComparisonError: Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = FailedPrecondition desc = Failed to unmarshal** 

some logs from argocd-repo-server POD 

time="2024-02-14T17:03:24Z" level=info msg="manifest error cache hit: &ApplicationSource{RepoURL:MY URL GITLAB,Path: MY PATH ON GITLAB,TargetRevision:MY BRANCH,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,Ref:,}/fc0460d36d97d1a005777d532893b4f8782f07f1"
time="2024-02-14T17:03:24Z" level=error msg="finished unary call with code Unknown" error="Manifest generation error (cached): rpc error: code = FailedPrecondition desc = Failed to unmarshal \"MY APP DEPLOYMENT YAML\": <nil>" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2024-02-14T17:03:24Z" grpc.time_ms=116.552 span.kind=server system=grpc

**To Reproduce**

Upgrade to version HA 2.9.5

**Expected behavior**

So i try deleting those argocd app and do again the deployment via argocd app but the previous message from logs and via WEB UI shows up everything i hit CREATE

**Version**

argocd-server: v2.9.5+f943664
  BuildDate: 2024-01-19T17:57:57Z
  GitCommit: f9436641a616d277ab1f98694e5ce4c986d4ea05
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.13.2+g2a2fb3b
  Kubectl Version: v0.24.17
  Jsonnet Version: v0.20.0

**Logs**

some logs from argocd-server

time="2024-02-14T18:47:39Z" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = error setting up git client and resolving given revision: Unable to resolve 'H' to a commit SHA" grpc.code=Unknown grpc.method=ListApps grpc.service=repository.RepositoryService grpc.start_time="2024-02-14T18:47:38Z" grpc.time_ms=582.457 span.kind=server system=grpc
time="2024-02-14T18:47:41Z" level=info msg="received unary call /repository.RepositoryService/GetAppDetails" grpc.method=GetAppDetails grpc.request.content="source:<repoURL:\"GITLAB REPO URL\" path:\"FILE GITLAB \" targetRevision:\"MY BRANCH\" chart:\"\" ref:\"\" > appName:\"APP NAME \" appProject:\"PROJECT\" " grpc.service=repository.RepositoryService grpc.start_time="2024-02-14T18:47:41Z" span.kind=server system=grpc
time="2024-02-14T18:47:42Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetAppDetails grpc.service=repository.RepositoryService grpc.start_time="2024-02-14T18:47:41Z" grpc.time_ms=492.883 span.kind=server system=grpc

```

**Comment by jgwest** [comment]
@davidfalconego can you reproduce the problem, then provide Pod logs from application-controller and repo-server Pods?
