### ISSUE TITLE
ArgoCD manifest for v2.10.1 is still using images from v2.10.0

### ISSUE THREAD

**Issue by debunn** [argoproj/argo-cd#17210]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
I've upgraded my development environment of ArgoCD to use the manifest for the newly released `v2.10.1` release, however I noticed that my images were still using the `v2.10.0` (partially broken) release.

A snippet of my `kustomization.yaml` file:
```
resources:
  - https://github.com/argoproj/argo-cd//manifests/ha/cluster-install/?ref=v2.10.1
```

**To Reproduce**
Run a `kustomize build` with a configuration similar to the snippet above

**Expected behavior**
The image versions being used should match the specific ref being used - in this case `v2.10.1`, but are instead `v2.10.0`

**Screenshots**

**Version**
v2.10.1
```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
Summary:  this seems to be an issue with the image version being specified in the `base` HA manifest here:
https://github.com/argoproj/argo-cd/blob/v2.10.1/manifests/ha/base/kustomization.yaml#L15

**Comment by crenshaw-dev** [comment]
Ah, apologies, I missed a step in the release process. Fix coming!

**Comment by debunn** [comment]
Thanks Michael!  The [a79e0ea](https://github.com/argoproj/argo-cd/commit/a79e0eaca415461dc36615470cecc25d6d38cefb) commit seems to have done the trick.  A hard refresh of my ArgoCD Application for development picked up the right image tag, and a purge of my Docker image caching server for `v2.10.1` got it showing the right version in the Argo UI as well:  `v2.10.1+a79e0ea`.

Thanks again - I think this issue is good to close!

**Comment by crenshaw-dev** [comment]
Thanks for catching it and for testing the fix. Cheers!
