### ISSUE TITLE
Application List only showing two apps per row since 2.10

### ISSUE THREAD

**Issue by mtslzr** [argoproj/argo-cd#17220]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We are running Argo CD in Azure, and recently upgraded from 2.9.5 to 2.10.1. Prior to the upgrade, Argo would show three applications per row (on a 1680x1050 MacBook Air screen, for reference). After the upgrade, the application list is now only two-wide:

<img width="1388" alt="two-wide" src="https://github.com/argoproj/argo-cd/assets/6003715/717c233d-19a9-464a-afa7-830e8fb01545">

In the CSS console of the browser (tested in multiple browsers), disabling `display: flex` (which is still set to `display: flex` just from another field) seems to fix it:

<img width="1382" alt="three-wide" src="https://github.com/argoproj/argo-cd/assets/6003715/76aa989c-1659-4972-8a4b-fec3ae3fac4b">

I have checked the changelogs and didn't see anything related to CSS. I have disabled any custom CSS (we use some custom colors) and that did not change anything. Was not sure if something changed, if this is intentional, or if there is an easy way to revert the default application list back to the previous tile sizes (three wide).

**To Reproduce**

1. Run Argo CD 2.9.x
2. Upgrade to 2.10.x

**Expected behavior**

I expected the application layout to remain the same, or to have found information about a change in layout.

**Screenshots**

Three wide (old layout from 2.9, done via CSS console in 2.10):

<img width="1382" alt="three-wide" src="https://github.com/argoproj/argo-cd/assets/6003715/76aa989c-1659-4972-8a4b-fec3ae3fac4b">

Two wide (new layout in 2.10):

<img width="1388" alt="two-wide" src="https://github.com/argoproj/argo-cd/assets/6003715/717c233d-19a9-464a-afa7-830e8fb01545">

**Version**

```shell
❯ argocd version
argocd: v2.10.1+a79e0ea.dirty
  BuildDate: 2024-02-14T22:23:04Z
  GitCommit: a79e0eaca415461dc36615470cecc25d6d38cefb
  GitTreeState: dirty
  GoVersion: go1.21.7
  Compiler: gc
  Platform: darwin/arm64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.10.1+a79e0ea
  BuildDate: 2024-02-14T17:37:43Z
  GitCommit: a79e0eaca415461dc36615470cecc25d6d38cefb
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.0+g3fc9f4b
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**

N/A

**Comment by EugeneLugovtsov** [comment]
same for me. argocd v2.10.1

**Comment by AnubhavSabarwal** [comment]
How did you change the argocd logo, can you please share the configuration

**Comment by alexmt** [comment]
@rpelczar do you think this is related to your PR https://github.com/argoproj/argo-cd/pull/16140 ?

If yes I would say this is a regression. The intention was to only fix tile height

**Comment by FutureMatt** [comment]
We seem to be hit by this too, but instead all of our tiles fill the whole width so we just get one tile per line.

<img width="1489" alt="Screenshot 2024-02-28 at 09 36 14" src="https://github.com/argoproj/argo-cd/assets/43476243/f818378a-f3c6-48cc-bfc7-074917d92d9f">

**Comment by rpelczar** [comment]
@alexmt It might be related. I can't reproduce this on my local, but I will remove legacy CSS classes that may be causing this issue.
