### ISSUE TITLE
Erro Argocd

### ISSUE THREAD

**Issue by thdblinux** [argoproj/argo-cd#17234]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by reggie-k** [comment]
Hi, can you provide details for this, if still relevant, or close the issue otherwise?

**Comment by andrii-korotkov-verkada** [comment]
No response, closing.
