### ISSUE TITLE
Sync plan

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#17240]
# Summary

Something that’s always bugged me is that, when I’m about to sync an app, I’m never quite sure what is about to happen. I want the UI to show me a pop-up that hints at what will happen. 

I’ve suggested before that sync should be a 3 step process (#8511) but really, that’s a technical solve to an unimportant problem. 

Yet I close my eye and cross my fingers whenever I sync.

Am I the only person that has this issue?

# Motivation

Whenever I sync.

# Proposal

Using code?

**Comment by vanny96** [comment]
Hey @alexec, I was wondering what a `plan` would provide that the App Diff does not? From my understanding, looking at the App Diff would allow you to see exactly what is being changed ahead of time and then decide to either execute it or not.

On the other end, I was thinking that maybe an "approval" system could possibly be interesting. If enabled, this system would disable the sync option until the "approvals quota" is met. 

To elaborate a bit further:
- Configuration: It would be part of the SyncPolicy (e.g. `spec.syncPolicy.requiredApprovals: 2`)
- Behaviour (if enabled):
  - On an application detail page, a new piece of information is displayed showing how many approvals have been given and how many are required
  - The Sync button is disabled until the number of approvals meets the quota
  - The **"App Diff"** button is renamed to a **"Review"** button
  - Upon clicking on the Review button, the App Diff will be shown and an option to approve it will be given

Let me know it sounds too different from what you had in mind and, in that case, how what you had in mind would expand on top of the current App Diff functionality!

**Comment by crenshaw-dev** [comment]
>  I was wondering what a plan would provide that the App Diff does not?

+1, what info do you want to see? Sync waves, hooks, etc.? Or literally just the diff?

> On the other end, I was thinking that maybe an "approval" system could possibly be interesting.

imo, approval belongs pre-commit (e.g. PR approval). Otherwise you're introducing intentional drift, which undercuts the advantages of GitOps. We should take advantage of SCM interfaces/tools instead of re-implementing them in Argo CD.

**Comment by crenshaw-dev** [comment]
Closing because it's unclear what "plan" means. If it's an approval mechanism, imo that belongs in git.
