### ISSUE TITLE
`ARGOCD_APP_REVISION_SHORT` not resolving

### ISSUE THREAD

**Issue by seddarj** [argoproj/argo-cd#17278]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Setting `$ARGOCD_APP_REVISION_SHORT` as a helm parameter override in an Application doesn't seem to resolve properly. Setting the same parameter to `$ARGOCD_APP_REVISION` does correctly resolve.

**To Reproduce**

* Deploy a simple Application using a helm chart
* Set a helm parameter to `$ARGOCD_APP_REVISION`
* The diff should show the full commit ID of the `targetRevision`
* Update the helm parameter to `$ARGOCD_APP_REVISION_SHORT`
* The diff doesn't show the first 7 characters of the commit ID

**Expected behavior**

We expect the `$ARGOCD_APP_REVISION_SHORT` environment variable to resolve in the same way `$ARGOCD_APP_REVISION` does as both are documented as part of the [Build Environment](https://argo-cd.readthedocs.io/en/release-2.9/user-guide/build-environment/).

**Screenshots**

When using `$ARGOCD_APP_REVISION` we see the following diff:
<img width="397" alt="Screenshot 2024-02-22 at 12 14 17" src="https://github.com/argoproj/argo-cd/assets/16181119/6edf5d7b-2c21-41d2-b66f-f99698182c3e">

But when using `$ARGOCD_APP_REVISION_SHORT`, there is no diff (as we have a default value in case that particular parameter is empty) but we should be seeing the first 7 characters of the commit ID in the above diff.

**Version**
```json
{
    "Version": "v2.9.6+ba62a0a",
    "BuildDate": "2024-02-02T19:17:57Z",
    "GitCommit": "ba62a0a86d19f71a65ec2b510a39ea55497e1580",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.13.2+g2a2fb3b",
    "KubectlVersion": "v0.24.17",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

**Comment by seddarj** [comment]
We updated to 2.10.1 and we're seeing the same issue. Here's the version we're running now:
```json
{
    "Version": "v2.10.1+a79e0ea",
    "BuildDate": "2024-02-14T17:37:43Z",
    "GitCommit": "a79e0eaca415461dc36615470cecc25d6d38cefb",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.0+g3fc9f4b",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

**Comment by ilia-medvedev-codefresh** [comment]
@seddarj can you please provide an example with a public chart where it doesn't work for you? I tried to reproduce it and ARGOCD_APP_REVISION_SHORT was correctly resolved when set under `helm.parameters`

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and let us know if the issue is still present, please?

**Comment by seddarj** [comment]
@andrii-korotkov-verkada @ilia-medvedev-codefresh Sorry for the delayed response. I can confirm that it's working as expected on Argo 2.12 over here. Thanks for looking into this 🙏
