### ISSUE TITLE
Diff errors when using Server-side apply 

### ISSUE THREAD

**Issue by 0xDones** [argoproj/argo-cd#17358]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After setting `ServerSideApply=true` for all the applications, many of them started presenting diff errors and ArgoCD wasn't able to determine their status anymore. It used to work without ServerSideApply. I added a couple of issues that are related to this same functionality. 

```log
Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from live resource: .spec.podReplacementPolicy: field not declared in schema
```

**To Reproduce**

Enable Server-Side Apply

**Expected behavior**

Handle the diff properly. Most solutions presented on the other issues are workarounds unfortunately 😢 

**Screenshots**

**Version**

- Chart Version: `6.2.3`
- ArgoCD Version: `v2.9.5`, `v2.10.1`
- K8s Version (EKS): 1.29

**Logs**

```log
Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from live resource: .spec.podReplacementPolicy: field not declared in schema
```

**Related**

- https://github.com/argoproj/argo-cd/issues/13585
- https://github.com/argoproj/argo-cd/issues/15176
- https://github.com/argoproj/argo-cd/issues/16640

**Comment by refl3ction** [comment]
> Have you tried to enable the [server-side diff](https://argo-cd.readthedocs.io/en/latest/user-guide/diff-strategies/#server-side-diff) ?

You are a hero, sir. Enabling this fixed my issue.

**Comment by yevon** [comment]
I was getting the same issue, i will try that also!

**Comment by refl3ction** [comment]
@leoluz I'm not sure, the solution proposed here caused another issue #17568 , I think this should be investigated further.

**Comment by JustinLex** [comment]
Server-side diff also seems to create issues with automated sync for me. It seems to get confused about manual changes made via kubectl, and then forces an "self-heal" behavior, even though I have self-heal disabled. It doesn't seem to be a universal solution.

**Comment by ptr1120** [comment]
I am also having this issue with 

> Failed to compare desired state to live state: failed to perform pre-diff normalization: error building typed results: error creating typedLive: errors: .spec.podReplacementPolicy: field not declared in schema .status.terminating: field not declared in schema

when adding my Job manifest. 

Enabling server-side-diff is not an option to me due to several  "runtime error: invalid memory address or nil pointer dereference" bugs I had with this setting (see also https://github.com/argoproj/argo-cd/issues/18548).

Any workaround to get a Job synced with ArgoCd?

**Comment by ajay0988** [comment]
Getting the issue after using below configuration in argo application while syncing 

`Failed to compare desired state to live state: failed to calculate diff: error calculating server side diff: serverSideDiff error: error running server side apply in dryrun mode for resource Prometheus/xyz-prometheus: failed to create typed patch object (monitoring/xyz-prometheus; monitoring.coreos.com/v1, Kind=Prometheus): errors: .spec.storage.volumeClaimTemplate.selector: field not declared in schema .spec.automountServiceAccountToken: field not declared in schema`

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
```

```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
```

FYI @crenshaw-dev @leoluz 

Argo Version:- 2.13.3

**Comment by kquinsland01** [comment]
@ajay0988, I had the same issue:

> `Failed to compare desired state to live state: failed to calculate diff: error calculating server side diff: serverSideDiff error: error running server side apply in dryrun mode for resource Prometheus/xyz-prometheus: failed to create typed patch object (monitoring/xyz-prometheus; monitoring.coreos.com/v1, Kind=Prometheus): errors: .spec.storage.volumeClaimTemplate.selector: field not declared in schema .spec.automountServiceAccountToken: field not declared in schema`

Even after setting server side diff to true.
Turns out there's a typo: https://github.com/helm/charts/issues/9288#issuecomment-737812089

As soon as I removed `selector:{}` I was good to go.
