### ISSUE TITLE
Helm do not delete application

### ISSUE THREAD

**Issue by AndreCbrera** [argoproj/argo-cd#17386]
**Describe the bug**

Hello there ! I'm trying to deploy and delete the application from ArgoCD, this is my path to deploy the application using helm.

![image](https://github.com/argoproj/argo-cd/assets/38178990/dcf4611e-8958-4127-8334-4fc01eeb581f)

When I execute **helm uninstall release-name** ArgoCD delete the application but the resources on k8s still deployed.

**To Reproduce**

As you can see, I install the release and comprobe the app and then delete the applications but the resources still deployed

![image](https://github.com/argoproj/argo-cd/assets/38178990/ee14a7dc-2667-4620-a585-e87e1b3ffdce)

**Version**

```shell
{
    "Version": "v2.9.3+6eba5be",
    "BuildDate": "2023-12-01T23:05:50Z",
    "GitCommit": "6eba5be864b7e031871ed7698f5233336dfe75c7",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.13.2+g2a2fb3b",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}

```

May I need to apply an annotations argocd finalizers in the resources in the yaml files ?

Thanks for your help

**Comment by jdomag** [comment]
Isn't that well described in the docs? 
https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/
