### ISSUE TITLE
`Windows` in Settings>Projects is not an intuitive name for `Sync Windows`

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#17405]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

A normal person who sees `windows` isn't going to guess that they refer to `sync windows` outside a context that explicitly includes `sync`, and the projects view doesn't have `sync` anywhere.

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/settings/projects/default
2. Click `WINDOWS`

**Expected behavior**

Tabs should have names that reasonably predict what they do

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/2119212/04852582-e3dc-4bc0-9420-a8cde1a9f65f)

![image](https://github.com/argoproj/argo-cd/assets/2119212/f36b1778-3c3d-42ca-902a-1214adf81487)

**Version**

```shell
{
    "Version": "v2.9.0+891d089",
    "BuildDate": "2024-02-26T19:13:21Z",
    "GitCommit": "891d08930470675c8851909254b0b5bd45eb79f0",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.1+ge8858f8",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}

```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by surajyadav1108** [comment]
So you are suggesting it should be "sync windows" instead.

**Comment by jsoref** [comment]
Yes.
