### ISSUE TITLE
CLI : add sync policy option `manual` for app create command to make it similar to options provided in Web console

### ISSUE THREAD

**Issue by anandf** [argoproj/argo-cd#17447]
# Summary

In argocd app create command, currently the following `--sync-policy` options are supported - `none/auto/automatic/automated`. But in web console, there is no `none` option, and instead we just have a sync policy called manual. By having a sync policy option called `manual` in CLI, users can get a unified experience when using CLI/Web console. When specifying the option `manual` keep the behaviour same as specifying `none` to ensure backwards compatability.

With this change none/manual and auto/automatic/automated will become valid options for `--sync-policy`

When listing applications via CLI, currently we display the Sync Policy as `<none>` instead we can show this to `Manual` (we still display `NONE` in web console and that needs to be changed to `Manual` as well`)

# Motivation

Give a unified experience for customers creating an argo application in Web Console (UI) and CLI.

# Proposal
Changes required in  `cmd/util/app.go` 
- in the switch case, match for `none` and `manual` similar to how it is done for `auto/automatic/automated`
`cmd/argocd/commands/app.go` 
- in the summary creation, when there is no sync policy set, we are returning a string called `<none>`, instead we can return `Manual`. 
- correct the documentation where automated option is not mentioned.
- include manual option in the documentation.
`ui/src/app/applications/components/application-summary/application-summary.tsx`
- fix the web console string `NONE` to `Manual` in the summary page. Same as what the user provided during the app create step.
 
<img width="1403" alt="Screenshot 2024-03-08 at 12 51 01 PM" src="https://github.com/argoproj/argo-cd/assets/6103351/2dfa343e-30f7-404e-8033-55f8a6870d5c">

**Comment by todaywasawesome** [comment]
Great idea.

**Comment by anirudhsudhir** [comment]
I'd like to work on this issue.

**Comment by anirudhsudhir** [comment]
Hello! I'd like to work on this issue.

**Comment by surajyadav1108** [comment]
> Hello! I'd like to work on this issue.

@anirudhsudhir go ahead you don't need someone to  assign you for good first issues.

**Comment by anirudhsudhir** [comment]
I've made the necessary changes. Please do review the PR.

**Comment by anandf** [comment]
Thanks @anirudhsudhir for working on this. Appreciate your efforts and congrats on your contribution to ArgoCD.

**Comment by anirudhsudhir** [comment]
It was a wonderful experience working on this issue, thank you very much!

**Comment by Knickkennedy** [comment]
Hello, it appears that this issue has already been merged, could it be closed?

**Comment by mgurrie** [comment]
@anandf I am interested on contributing to this project. Is there an issue I can be assigned?

**Comment by anandf** [comment]
Issue fixed by https://github.com/argoproj/argo-cd/pull/17459. Closing this issue.
