### ISSUE TITLE
Impossible to delete Application or Add a label 

### ISSUE THREAD

**Issue by jlainez76** [argoproj/argo-cd#17449]
Hello, 
Version, Argocd 2.10.2 

Context: 

- When we try to delete an application in Argocd with GUI, and click on the button "Delete", nothing happens ! 
- When i try to add a labels in GUI, i have the error "Unable to save changes: can't convert null to object" 

Investigation 
I have checking logs, see nothing 
That runs with CLI 
I have delete namespace and redeploy

I don't understand

**Comment by todaywasawesome** [comment]
@jlainez76 Do you see any errors in your browser console? Since it works in the CLI, it sounds like something happening in the browser.

**Comment by reggie-k** [comment]
Thanks for updating about the root cause.
