### ISSUE TITLE
Azure DevOps Auth Failure

### ISSUE THREAD

**Issue by cartyc** [argoproj/argo-cd#1745]
Bug:
I am doing a test deploy with a repo in Azure DevOps and I get the following Error when I go to create the application.
```
  Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in /: rpc error: code = Internal desc = Failed to fetch git repo: 'git fetch origin --tags --force' failed: fatal: Authentication failed for 'https://repo@dev.azure.com/org/project/_git/repo/'
```
The odd part is that I added the repository in settings > repositories and it is saying the connection status is `successful`.
 
**To Reproduce**

Add Azure Devops Repository in settings > repositories.

Create application in default project using the new repository. This should result in an Auth failure.

**Expected behavior**
I expect this would behave in a similar manner to when I add a repository from github and Argo will begin to deploy the application.

**Version**
1.0.1

**Logs**

```
Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in /: rpc error: code = Internal desc = Failed to fetch git repo: 'git fetch origin --tags --force' failed: fatal: Authentication failed for 'https://repo@dev.azure.com/org/project/_git/repo/'
```

**Have you thought about contributing a fix yourself?**
Yes but not sure where to begin

**Comment by alexec** [comment]
1. Do you have other apps connected successfully?
1. Can you tell me which tool you're using? Helm? Kustomize? Other?
1. Are you using username + password authentication? Or SSH private key?

**Comment by cartyc** [comment]
I have connected to some in the past but those were not private accounts, just using username + password auth right now. Deploying just standard k8s YAML.

I'm thinking it might be something to do with having MFA enabled on the account. Will try with a private ssh next to see if that works.

**Comment by alexec** [comment]
Are you using Kustomize or Helm or ... please?

**Comment by cartyc** [comment]
Sorry thought I wrote that down, just plain k8s YAML no Helm or Kustomize.

**Comment by alexec** [comment]
ok,l let me know how it goes

**Comment by cartyc** [comment]
Tried the username/password login with github and it also failed (I have MFA turned on in both Github and Azure DevOps). Tried SSH with Azure DevOps and it failed, but it succeeded with Github so for that I think it's just a matter of baking the key into Argo like the Docs recommend.

As for the username/password I suspect it's MFA that is causing the failure.
