### ISSUE TITLE
argo delete kubernetes' service stuck by finalizer 'foregroundDeletion', when change sync 'foreground' -> 'background'

### ISSUE THREAD

**Issue by penglongli** [argoproj/argo-cd#17465]
Argo sync application with `prune: true`, it will prune some objects. 

First, the application set the sync policy as: 
```
PrunePropagationPolicy=foreground
```
So the service which need pruned will be in stuck with 
```
apiVersion: v1
kind: Service
metadata:
  name: test
  deletionTimestamp: "2024-03-11T11:00:00"
  finalizers:
  - foregroundDeletion
```

Changed application sync to background and trigger re-sync. **Expected effect: kubectl delete resource background**
```
PrunePropagationPolicy=background
```
But it was not as expected, and the resource was not triggered to be deleted in the background.

## PruneObject

https://github.com/argoproj/gitops-engine/blob/v0.7.3/pkg/sync/sync_context.go#L934
```
// Skip deletion if object is already marked for deletion, so we don't cause a resource update hotloop
deletionTimestamp := liveObj.GetDeletionTimestamp()
if deletionTimestamp == nil || deletionTimestamp.IsZero() {
	err := sc.kubectl.DeleteResource(context.TODO(), sc.config, liveObj.GroupVersionKind(), liveObj.GetName(), liveObj.GetNamespace(), sc.getDeleteOptions())
	if err != nil {
		return common.ResultCodeSyncFailed, err.Error()
	}
}
```

We originally used the`foreground` strategy to trigger the deletion action. This strategy results in the `deletionTimestamp` not nil.
So kubectl not delete resource again.

**Comment by andrii-korotkov-verkada** [comment]
@jenting, what's the ArgoCD version you have?

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and let us know if the issue is still present, please?

**Comment by penglongli** [comment]
@andrii-korotkov-verkada This issue is a GC bug in lower versions of kubernetes (<=1.18.x). Please close the issue first.

https://github.com/kubernetes/kubernetes/issues/90692
