### ISSUE TITLE
CLI: add flag `--set-finalizer` to `argocd admin app generate-spec`

### ISSUE THREAD

**Issue by MaximeD** [argoproj/argo-cd#17479]
# Summary

When creating an application using `argocd app create`, it is possible to add a flag `--set-finalizer` (defined in [cmd/argocd/commands/app.go](https://github.com/argoproj/argo-cd/blob/dc242da748447a58569375b4f2ac329c33b36073/cmd/argocd/commands/app.go#L198)). However, if we are using the command `argocd admin app generate-spec` to generate the manifest, we [don’t have a flag `--set-finalizer`](https://github.com/argoproj/argo-cd/blob/dc242da748447a58569375b4f2ac329c33b36073/cmd/argocd/commands/admin/app.go#L121-L126).

As a consequence it is not possible to generate a manifest file with the following metadata:

```yaml
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
```

# Proposal

Add the flag `--set-finalizer` to `argocd admin app generate-spec`.

If that makes sense, I can work on a PR to provide it.

**Comment by KyriosGN0** [comment]
hi, can i work on this ?
