### ISSUE TITLE
ArgoCD operator version 0.7.0 is not compatible with ArgoCD 2.9.2 because of CRDs

### ISSUE THREAD

**Issue by popalav** [argoproj/argo-cd#17561]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD operator version 0.7.0 is not compatible with ArgoCD 2.9.2 because of CRDs.
[The ArgoCD operator 0.7.0](https://github.com/argoproj-labs/argocd-operator/releases/tag/v0.7.0) has the CRD manifests compatible with the ArgoCD version 2.6, but we were upgrading the ArgoCD to 2.9.2.

We are using managedNamespaceMetadata in our appCatalogs. The new ArgoCD 2.9.2 version outputs a new status entry for the usage of this one, but this new status output is not compatible with the CRDs from the ArgoCD 2.6, which comes with ArgoCD operator 0.7.0.

argocd-application-controller, which checks the Application custom resource, gives an error that this is an unknown field, and that's why all our Applications that use managedNamespaceMetadata goes into a sync loop forever.

**To Reproduce**

Deploy ArgoCD 2.9.2 and ArgoCD Operator 0.7.0 and try to use "managedNamespaceMetadata"

**Expected behavior**

We should not see any error regarding unknown field "status.controllerNamespace".

**Version**

```shell
{
    "Version": "v2.9.2+c5ea5c4",
    "BuildDate": "2023-11-20T17:18:26Z",
    "GitCommit": "c5ea5c4df52943a6fff6c0be181fde5358970304",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.13.2+g2a2fb3b",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}

```

**Logs**
This is from application-controller pods:

```
W0318 15:43:07.413757 1 warnings.go:70] unknown field "status.controllerNamespace"
```

**Comment by peschmae** [comment]
This should probably be a argocd-operator ticket and not argocd.

Additionally, I'd recommend sticking to ArgoCD versions that are supported by the operator you are using, eg. Operator 0.8.0 would support ArgoCD 2.8.3, and the upcoming 0.9.0 release, will support ArgoCD 2.9

**Comment by popalav** [comment]
Thank you for your quick response!
