### ISSUE TITLE
Default cipher values are invalid for newer versions of go.

### ISSUE THREAD

**Issue by joshrwolf** [argoproj/argo-cd#17571]
This is not a bug with a current release, and I'm happy for it to be reclassified as such!

This is simply a proposed (hopefully simple) fix for a future problem that will arise when the project upgrades the version of go used to build.

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Default cipher values are invalid for newer versions of go.

**To Reproduce**

Build with newer versions of go.

**Expected behavior**

N/A

**Screenshots**

N/A

**Version**

N/A

**Logs**

```
level=fatal msg="error retrieving TLS cipher suites: invalid cipher suite specified: TLS_RSA_WITH_AES_256_GCM_SHA384"
```

**Comment by ashinsabu3** [comment]
Is the fix for this is any argocd version yet? @alexmt

**Comment by skumsi** [comment]
We upgraded to Argocd v2.12.3 from v2.11.1 and are seeing this same error in logs for the argocd-server and argocd-repo-server. Both the pods are currently stuck in a CrashLoopBackOff state unable to start up successfully? Is there a workaround for fixing this? @alexmt If not to which version can we downgrade to resolve this? 

> $ kubectl logs argocd-server-574b8bbbc9-m9xzf -n argocd --previous
Defaulted container "argocd-server" out of: argocd-server, install-oneagent (init)
time="2024-09-10T21:56:08Z" level=warning msg="Could not parse '1h0m0s' as a duration string from environment ARGOCD_SERVER_CONNECTION_STATUS_CACHE_EXPIRATION"
time="2024-09-10T21:56:08Z" level=warning msg="Could not parse '3m0s' as a duration string from environment ARGOCD_SERVER_OIDC_CACHE_EXPIRATION"
time="2024-09-10T21:56:08Z" level=warning msg="Could not parse '24h0m0s' as a duration string from environment ARGOCD_SERVER_LOGIN_ATTEMPTS_EXPIRATION"
time="2024-09-10T21:56:08Z" level=warning msg="Could not parse '1h0m0s' as a duration string from environment ARGOCD_APP_STATE_CACHE_EXPIRATION"
time="2024-09-10T21:56:08Z" level=warning msg="Could not parse '24h0m0s' as a duration string from environment ARGOCD_DEFAULT_CACHE_EXPIRATION"
time="2024-09-10T21:56:08Z" level=warning msg="Could not parse '24h0m0s' as a duration string from environment ARGOCD_DEFAULT_CACHE_EXPIRATION"
time="2024-09-10T21:56:08Z" level=info msg="ArgoCD API Server is starting" built="2024-08-27T11:57:48Z" commit=6b9cd828c6e9807398869ad5ac44efd2c28422d6 namespace=argocd port=8080 version=v2.12.3+6b9cd82
time="2024-09-10T21:56:08Z" level=fatal msg="error retrieving TLS cipher suites: invalid cipher suite specified: TLS_RSA_WITH_AES_256_GCM_SHA384"

**Comment by ashinsabu3** [comment]
@skumsi as a workaround, i just set this in all the configmaps that are refered to by argo workloads 
ARGOCD_TLS_CIPHERS=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

**Comment by xlanor** [comment]
> @skumsi as a workaround, i just set this in all the configmaps that are refered to by argo workloads ARGOCD_TLS_CIPHERS=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

Can confirm this works. Operator manual needs to be updated.
