### ISSUE TITLE
CLI errors on SSO login when Chrome 123 receives the redirect

### ISSUE THREAD

**Issue by lauren-hinge** [argoproj/argo-cd#17587]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

&nbsp;

**Describe the bug**

Chrome's new version, 123 (specifically tested on `123.0.6312.59`), does not play nice with receiving an SSO redirect from our SAML provider.

Previous versions of chrome, as well as various chromium browsers and safari, seem unaffected.

The SAML auth succeeds, dex logs a successful sign-in, but when localhost is receiving the redirect, the browser displays a `ERR_CONNECTION_REFUSED`, and the CLI output is:

```
Opening browser for authentication
Performing authorization_code flow login: https://<our argo url>/api/dex/auth?access_type=offline&client_id=argo-cd-cli&code_challenge=<code_challenge>&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups+offline_access&state=<state>
Authentication successful
FATA[0003] token contains an invalid number of segments
``` 

&nbsp;

**However, there is a workaround within Chrome!**

Hopefully this sheds some light on the underlying cause. This _may_ suggest it's just a bug within chrome, but I still wanted to post this in case it's a new pattern that the CLI needs to work itself around (or if anyone else is running into this)!

In Chrome's Flags -> [chrome://flags/](chrome://flags/)

<img width="745" alt="image" src="https://github.com/argoproj/argo-cd/assets/129104953/af8dce72-7789-4f92-9ada-8f8a14d41d71">

&nbsp;

Setting that flag to `Disabled` seems to bypass the issue and **restore normal functionality** on Chrome 123!

-----

&nbsp;

**To Reproduce**

- Wire up a working setup with dex pointing to a SAML provider
- Switch to Chrome `123.0.6312.59` (latest stable as of writing) 
- `argocd login --sso <your argo url>`

&nbsp;

**Expected behavior**

SSO login should be received and parsed for a valid token

&nbsp;

**Version**

```shell
argocd: v2.9.3+6eba5be.dirty
  BuildDate: 2023-12-02T00:37:14Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: dirty
  GoVersion: go1.21.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:05:50Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.13.2+g2a2fb3b
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

With debug, no token shown (with the chrome flag set, or with other browsers, a token is present in the `Token:` log):
```
argocd login --sso <our argo url> --loglevel debug
DEBU[0000] OIDC Configuration:
DEBU[0000]   supported_scopes: [openid email groups profile offline_access]
DEBU[0000]   response_types_supported: [code]
Opening browser for authentication
Performing authorization_code flow login: https://<our argo url>/api/dex/auth?access_type=offline&client_id=argo-cd-cli&code_challenge=<code_challenge>&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups+offline_access&state=<state>
DEBU[0001] Listen: localhost:8085
DEBU[0002] Callback: /auth/callback?code=<code>&state=<state>
Authentication successful
DEBU[0002] Callback: /auth/callback?code=<code>&state=<state>
DEBU[0003] Token:
DEBU[0003] Refresh Token:
FATA[0003] token contains an invalid number of segments
```

**Comment by FabioAntunes** [comment]
I'm also encountering this issue, but I'm using Arc. Unfortunately, the solution provided regarding disabling the flag doesn't seem to work.

```
Arc Version 1.35.0 (47750)
Chromium Engine Version 123.0.6312.59
```

**Comment by lauren-hinge** [comment]
Looks like it WAS a chrome issue!

* [issue where it was being tracked](https://issues.chromium.org/issues/330364341)
* [commit fixing it](https://chromium.googlesource.com/chromium/src/+/945fa7960ae4946679f09f537132b7999ebcdf0f)
* [stable channel release](https://chromereleases.googleblog.com/2024/03/stable-channel-update-for-desktop_26.html)

chrome `123.0.6312.87` has hit stable channel, contains the fix, and works for me with all flags unset!
