### ISSUE TITLE
Logging into ArgoCD using kubectl

### ISSUE THREAD

**Issue by alnsantosh** [argoproj/argo-cd#1760]
Is there a way to login without using ArgoCD CLI i.e.,Is there a way (declarative way) to login.

argocd login <ARGOCD_SERVER>

**Comment by alexmt** [comment]
Argo CD can be managed directly using `kubectl`: https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/ . Does it answer your question?

**Comment by alnsantosh** [comment]
Thanks for the quick reply.
I am new to DevOps and ArgoCD and was trying to understand the declarative setup. It would be great if you can direct me towards any examples that I can see so that my understanding over the declarative setup gets much better.

So far, I have installed ArgoCD into my Kubernetes cluster. I want to use yams config files to login, deploy any app and sync the changes (without using any ArgoCD command line tool for any of the mentioned steps). 
Hope my question makes sense to you

**Comment by alexmt** [comment]
All of argo cd settings including applications, projects etc are stored as k8s CRD, secret or config map. So instead of using argocd CLI/UI you can create the same object using `kubectl` (assuming you have direct cluster access).

E.g. to create an application you can run `argocd app create <name> ...` or `kubectl create app -f <pathtoapp.yaml>` . Good example with more explanations is available at https://github.com/stevesea/argocd-helm-app-of-apps-example

**Comment by alnsantosh** [comment]
> All of argo cd settings including applications, projects etc are stored as k8s CRD, secret or config map. So instead of using argocd CLI/UI you can create the same object using `kubectl` (assuming you have direct cluster access).
> 
> E.g. to create an application you can run `argocd app create <name> ...` or `kubectl create app -f <pathtoapp.yaml>` . Good example with more explanations is available at https://github.com/stevesea/argocd-helm-app-of-apps-example

Thanks for directing me towards the example. 
I was wondering if there is any way to skipping the ArgoCD login. If not, please let me know a way to login ArgoCD using yaml config file(declaratively) without using ArgoCD CLI. 

Do I have to use argocd-secret.yaml for that. If yes, please direct me towards an example if possible.

**Comment by alexmt** [comment]
Argo CD supports access tokens. Using [project and roles](https://argoproj.github.io/argo-cd/user-guide/projects/) you can create token and pass it to argocd cli:

```ARGOCD_TOKEN=<token> <ARGOCD_SERVER>=<hostname> argocd app list```

**Comment by alexmt** [comment]
@alnsantosh please feel free to reopen if needed or ask questions on slack: https://argoproj.github.io/community/join-slack
