### ISSUE TITLE
I cannot see whole name of resource in config map

### ISSUE THREAD

**Issue by LadaVarga** [argoproj/argo-cd#17600]
### Discussed in https://github.com/argoproj/argo-cd/discussions/17585

<div type='discussions-op-text'>

<sup>Originally posted by **LadaVarga** March 21, 2024</sup>
Hello,
Have you changed something recently in ArgoCD UI, I cannot see the whole name of name of the configmap in configmap view? We use version v2.10.3+0fd6344. I definitely use that table pretty heavily and I was able to the almost whole name of the resource.
![2024-03-21 16_58_49-_ Channel_ team-software-delivery - Procore Technologies, Inc - Slack](https://github.com/argoproj/argo-cd/assets/22859476/0165352b-4de3-4a46-9d4e-db81096ed0d6)
Thanks</div>

We are probable upgraded, but it can't see whole name of the column, it is really annoying.

**Comment by sunyeongchoi** [comment]
I will check this issue and reflect improvements :)

**Comment by y-elip** [comment]
Hello.
Any progress with it? 
This UI issue making work experience with /?resource page pretty annoying
