### ISSUE TITLE
Make external url's printed as list instead of one line

### ISSUE THREAD

**Issue by Hronom** [argoproj/argo-cd#17679]
# Summary

Right now [external url's](https://argo-cd.readthedocs.io/en/stable/user-guide/external-url/) on application details page under `URL's` section printed in one line:

I would like to see them printed same as urls in `links` section:
![image](https://github.com/argoproj/argo-cd/assets/429993/3d19b254-60ea-4bc7-9ce4-98f1a7a41669)

So if you have several [external url's](https://argo-cd.readthedocs.io/en/stable/user-guide/external-url/) they will be printed like this:
```
https://example.com https://example2.com https://example3.com
```

Expected to see instead a list:
```
* https://example.com 
* https://example2.com 
* https://example3.com
```

# Motivation

External urls created from resources that annotated in special way, potentially this resources can be inside helm and urls can be generated using all power of template in helm - this have more advantages over `links` and templating available there(example where links fail https://github.com/argoproj/argo-cd/issues/17552)

This is very useful especially when you use Argo CD application `details` page to show details about microservice, like have links to the metrics, logs etc.

And having them as list(same as `links`) will increase readability when you have several of them.

**Comment by Killpit** [comment]
That'd be a really good addition to ArgoCD, otherwise, the code can be cluttered.

**Comment by JessieTeng89** [comment]
I will work on it and create a PR later

**Comment by Hronom** [comment]
@JessieTeng89 it will be good if you can also take this one https://github.com/argoproj/argo-cd/issues/17680 they will work really nice together

**Comment by Hronom** [comment]
Hello, @jsolana and @pasha-codefresh do you have sense when it will be released?

**Comment by Hronom** [comment]
When it will be released? It closed long time ago and PR merged to master https://github.com/argoproj/argo-cd/pull/18768, but it still not present in latest version?

Small change that helps a lot, but it delayed a lot, I'm a little frustrated and confused here. Seems like issue in the process of how Argo CD manage changes...
