### ISSUE TITLE
Incorrect Cacheing With Matrix Generator and webhook

### ISSUE THREAD

**Issue by mattbrandman** [argoproj/argo-cd#17719]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When using a matrix generator of file and list to generate a set of apps from a JSON file it appears that there is some cache that is being used and I have to wait 3-10 minutes for a new entry in the JSON file to become a new app

**To Reproduce**
Deploy a generator using the file -> list matrix strategy. Update the file and see that a new app does not come in immediately

**Expected behavior**
With webhook or hard refresh a new app is generated immediately

**Screenshots**

**Version**

```shell
argocd:v2.10.5
```

**Comment by jgwest** [comment]
@mattbrandman Can you provide an example `ApplicationSet` CR which illustrates/reproduces the problem?

**Comment by mattbrandman** [comment]
I had an extra slash in my
