### ISSUE TITLE
CONNECTION STATUS is Failed with repository has stale branch as default branch in GitLab.

### ISSUE THREAD

**Issue by laiminhtrung1997** [argoproj/argo-cd#17765]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The `CONNECTION STATUS` is always `Failed` when the repository has the `default` branch as a `stale` branch.

**To Reproduce**

Add a repository to ArgoCD following the [docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repositories)

**Expected behavior**

The `CONNECTION STATUS` is `Successful`.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/68812829/c49e9f47-341c-4b1c-b395-8e52b98dce04)

**Version**

```shell
v2.10.4
```

**Logs**

```
time="2024-04-07T08:01:45Z" level=error msg="finished unary call with code Unknown" error="error testing repository connectivity: Unable to resolve 'HEAD' to a commit SHA" grpc.code=Unknown grpc.method=TestRepository grpc.service=repository.RepoServerService grpc.start_time="2024-04-07T08:01:44Z" grpc.time_ms=1216.34 span.kind=server system=grpc
```

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and tell us if the issue is still present, please?

**Comment by laiminhtrung1997** [comment]
The issue is not present anymore. I will close this issue.
