### ISSUE TITLE
Minor docs typo: "uncomment the second element"

### ISSUE THREAD

**Issue by lindhe** [argoproj/argo-cd#17767]
Here the docs talks about uncommenting "the second element":

https://github.com/argoproj/argo-cd/blob/cbafc13bddb814f6d3666fd27fd9150a237d0590/docs/operator-manual/applicationset/Generators-List.md?plain=1#L35

But there are no elements that are commented out in the example:

![image](https://github.com/argoproj/argo-cd/assets/7773090/4a3f0dbe-eb3f-4532-9859-9cc77a558c2c)

**Comment by Killpit** [comment]
What do you mean by the second element?

**Comment by lindhe** [comment]
I'm just citing the docs: 

> If we wanted to add a second environment, we could uncomment the second element and the ApplicationSet controller would automatically target it with the defined application.

I'm guessing it refers to elements in `.spec.generators[0].list.elements`, but it's unclear.
