### ISSUE TITLE
missing replace in go.mod

### ISSUE THREAD

**Issue by erma07** [argoproj/argo-cd#17771]
Because of the breaking conflicts from the new dependency versions some replacements need to be added:
replace (
k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20220803164354-a70c9af30aea
google.golang.org/protobuf => google.golang.org/protobuf v1.32.0
)

**Comment by jannfis** [comment]
Not sure what you want to tell us here, can you please elaborate?

**Comment by erma07** [comment]
> Not sure what you want to tell us here, can you please elaborate?

I am using argocd api in my repository and it has now started to fail building because some of the argocd dependencies have been updated. After adding these lines to go.mod it started to build again. The problem is that argocd doesnt compile with protobuf 1.33.0 and with the latest kube-openapi - breaking changes from those two argocd dependencies.
