### ISSUE TITLE
argocd retry reconciliation loop? (Viktor Farcic's argocd is broken devopstoolkit video)

### ISSUE THREAD

**Issue by lknite** [argoproj/argo-cd#17776]
# Summary

Viktor Farcic created a video pointing out a "bug" in argocd requiring the use of 'argocd waves' due to use cases where resources appear but deployments are not retried:  https://www.youtube.com/watch?v=t1Fdse-F9Jw

Today I wondered if it might be useful to create a controller which watches for these type of "stuck" scenarios and restarts them, causing another attempt as described in the video.  But, then I thought, this feels like a band-aid, (similar to how argocd waves feels) and if its already going to be added to argocd then it'd be better to just wait.

# Motivation

I'm experiencing several instances as described in the video with scripting deploying a new cluster and several apps & addons all at once.  I'm about to adjust the order of my scripts & add 'argocd waves' as needed to get rid of the chicken & egg scenarios resulting in "stuck" deployments.

However, this is all work that should be not be required, everything appears which is needed, its just that argocd doesn't bother retrying.

Is the video just wrong?  Is there already an option which can be enabled, which just isn't enabled by default?

I can describe my situation in detail, but I suspect the video would do a better job.

# Proposal

I would expect argocd to use a reconciliation loop as described in the video.

# Architecture
Currently running 2.9.3, going to update to 2.10.6 today.

**Comment by jannfis** [comment]
Are you looking for something like the sync retry feature?

You can configure it at `.spec.syncPolicy.retry`, please refer to https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/ for more information.

The feature is a little underdocumented, sorry about that.

**Comment by blakepettersson** [comment]
I highly recommend reading [this blog post](https://akuity.io/blog/application-dependencies-with-argo-cd/) from @christianh814
