### ISSUE TITLE
Fix Snyk report generation script

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#17785]
The script that generates Snyk reports for the docs doesn't seem to handle versions > 2.9 (probably due to poor version number parsing or sorting somewhere).

We should fix it to handle recent versions.

https://github.com/argoproj/argo-cd/blob/master/hack/snyk-report.sh

**Comment by rumstead** [comment]
It could be as easy as changing the GNU `sort` from `sort -g` to `sort -V`. If these look like the correct order I can submit a PR after a few tests. 

```
❯ git tag -l | sort -V | tail -n 10
v2.10.0-rc3
v2.10.0-rc4
v2.10.0-rc5
v2.10.1
v2.10.2
v2.10.3
v2.10.4
v2.10.5
v2.10.6
v2.11.0-rc1
```

```
❯ git tag -l | sort -g | tail -n 10                                                       
v2.9.1
v2.9.11
v2.9.2
v2.9.3
v2.9.4
v2.9.5
v2.9.6
v2.9.7
v2.9.8
v2.9.9
```

**Comment by rumstead** [comment]
Here is a dump of the versions it would've scanned.

```
❯ hack/snyk-report.sh
master v2.11.0-rc1 v2.10.6 v2.9.11 v2.8.15 
```
