### ISSUE TITLE
Migration utility for 0.3 to 0.4

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#178]
There will be some breaking changes from 0.3 to 0.4:

1. [x] repository secret names are normalized
2. [x] app destination is mandatory
3. [ ] i would like to rename the `recentDeployments` field to `history`:

```
RecentDeployments []DeploymentInfo     `json:"recentDeployments" protobuf:"bytes,2,opt,name=recentDeployment"`
```
to:
```
History []DeploymentInfo     `json:"history" protobuf:"bytes,2,opt,name=history"`
```
Need to implement some throwaway utility to perform some of the data transformations

**Comment by merenbach** [comment]
Working on this now

**Comment by merenbach** [comment]
@jessesuen how can we best approach this last one?  Is it something where Argo CD could have two identical fields simultaneously and keep them in sync?  Alternatively, how would it be to rename the field, but not its JSON name?

I can definitely add a filed rename to the migration utility and submit a PR for that, too, if that's still the best option.

**Comment by jessesuen** [comment]
@merenbach i think we can just lose history for now. I don't think item 3 is very important since these are just dev environments right now. we still have git history to fall back on for sync purposes.
