### ISSUE TITLE
Argo CD drops new K8s v1.13+ fields during deploy/comparison

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1781]
The way Argo CD performs comparison of objects is that it remarshals the object to to a concrete type, which normalizes all fields and allows us to do an apples-to-apples comparison. This allows us to normalize things like different representations of resource cpu/memory (e.g. 100m vs. 0.1). 

The problem with unmarshal the git manifests to a concrete type is: **_the concrete type we unmarshal to, is dependent on the go-client version that is imported by Argo CD_**. Currently we are using the go-client associated with Kubernetes 1.12, and are behind by two releases.

What this means, is Argo CD will **_drop_** any new fields introduced in K8s v1.13+ on the floor, and what Argo CD deploys may not actually reflect what is in git.  For this scenario to happen, Argo CD would need to be deploying resources containing new fields not present in the v1.12 type definitions. For example, in v1.14, Kubernetes introduced `enableServiceLinks` into the pod template. Since our v1.12 pod template type definition of the go-client does not know about this field, Argo CD will deploy a version of the pod which is **_missing_** this field after the process of remarshalling.

The solution is that when deploying objects, we should not touch the user's manifests in any shape or form. We may still remarshal object for comparison purposes, but if we do not keep up with the kubernetes version, we will miss detection of changed fields.

**Comment by jessesuen** [comment]
I think an attempt to fix this is:
1. Remove call to Remarshal from repo-server, and only call it in CompareAppState()
2. Update K8s libraries so that we are on v1.14, so that we can still use remarshaling to do comparisons, but at least we will not drop fields when performing the comparison.

**Comment by alexec** [comment]
Leave this with me.

**Comment by alexmt** [comment]
We might consider implementing https://github.com/argoproj/argo-cd/issues/805

**Comment by alexec** [comment]
Separate issues? How do you plan to support 1.12 and 1.13 at the same time?
