### ISSUE TITLE
Kustomize v2.1.0 support

### ISSUE THREAD

**Issue by zodiac12k** [argoproj/argo-cd#1783]
Kustomize v2.1.0 is released today!
I'm very expecting to use this version of kustomize in argocd.
Argocd is the best continuous delivery tool for me.

**Comment by alexec** [comment]
A great one for community contribution.

**Comment by alexec** [comment]
Change needed here: https://github.com/argoproj/argo-cd/blob/master/Dockerfile#L72

**Comment by jessesuen** [comment]
To really benefit from kustomize v2.1, we also need: https://github.com/argoproj/argo-cd/issues/1789

I think the two issues can come in at the same time.

**Comment by jessesuen** [comment]
Fixed
