### ISSUE TITLE
Replace Redis with ValKey

### ISSUE THREAD

**Issue by hairmare** [argoproj/argo-cd#17892]
# Summary

Redis Inc announced that they are changing Redis'  license to the source available BUSL license [here](https://redis.com/blog/redis-adopts-dual-source-available-licensing/) which is in violation of [CNCF policy](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md) and does not align with the Argo Projects values.

The BSD-3-Clause licensed Redis OSS code has now been forked as [ValKey](https://valkey.io/) in an effort hosted by the Linux Foundation.

After ValKey's first [generally available (GA) release and stable release](https://valkey.io/blog/update/2024/04/valkey-7-2-5-out/) it is time to start replacing Redis.

Prior to this issue, the change was discussed here: https://github.com/argoproj/argo-cd/discussions/17599

# Motivation

Taking swift action when this kind of change happens in our supply chain is a the core of upholding our opensource values.

# Proposal

I propose to write a Argo CD enhancement proposal in `docs/proposals/valkey.md` to further detail this architecture decision and to then implement it by replacing the manifests in [manifests/base/redis](https://github.com/argoproj/argo-cd/tree/3a46e8c1c7dc20911cb5d87ade8ced26c766e273/manifests/base/redis) along with proper documentation to communicate this change.

**Comment by hairmare** [comment]
I'd be happy to give writing an enhancement proposal a go, feel free to assign me and prove any pointer if there is anything i missed or should specifically be addressed for this case.

**Comment by hairmare** [comment]
i put together a draft in #17904 and i hope it's not to ranty, any feedback is appreciated

**Comment by hairmare** [comment]
i mentioned this effort in the ValKey discussion boards as well: https://github.com/orgs/valkey-io/discussions/340

**Comment by joebowbeer** [comment]
Also see https://github.com/argoproj/argo-cd/tree/master/manifests/ha/base/redis-ha

**Comment by todaywasawesome** [comment]
Closing in favor of #17970 thank you @hairmare for opening this issue!
