### ISSUE TITLE
argocd-util enhancements

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#179]
argocd-util needs the following to make maintenance easier:
1. admin password reset
2. export of settings and data
3. import of settings and data

**Comment by merenbach** [comment]
@jessesuen how does the admin password reset differ from invoking `argocd install --config-superuser` a second time?

**Comment by merenbach** [comment]
@jessesuen what settings/info need to be included in the export?

**Comment by merenbach** [comment]
Superseded by #213
