### ISSUE TITLE
Padding error with system level extensions

### ISSUE THREAD

**Issue by Jont828** [argoproj/argo-cd#17929]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I'm developing a system level extension and I'm having an issue where there's a `sb-page-wrapper` class that has a padding of 230px that shifts my extension to the left as shown in this picture. I'd like to have my extension be able to use the space right next to the black nav bar on the left.

![image](https://github.com/argoproj/argo-cd/assets/17480384/426ea630-c75d-4052-ab66-b5fd35f4cce1)

There's also another div with style `.cd-layout--extension .cd-layout__content--sb-expanded` that has `padding-left: 230px` as well, which leads me to believe there's a bug where we're accidently applying the padding twice.

![image](https://github.com/argoproj/argo-cd/assets/17480384/d7064d27-fb38-4a0e-bc29-73853bbc55a9)

**To Reproduce**

Create a system level extension with some text to see that it does renders with extra padding from the left.

**Expected behavior**

I would like to have my content rendered next to the side bar with no extra padding so that I can use all of the space provided like this:

![image](https://github.com/argoproj/argo-cd/assets/17480384/6c5b242d-3e5b-41b3-a50e-effb2d230729)

**Screenshots**

**Version**
Note that I'm developing using `make start-local` off of master branch.

```shell
argocd: v2.10.2+unknown
  BuildDate: 2024-03-04T01:58:25Z
  GitCommit:
  GitTreeState:
  GitTag: 2.10.2
  GoVersion: go1.22.0
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by Jont828** [comment]
I believe we should be able to fix this just by deleting [this block](https://github.com/argoproj/argo-cd/blob/67e6c6cf942b3134729d4014f9a78dfa5289cb97/ui/src/app/shared/components/layout/layout.scss#L44-L53) which renders the extra padding for extensions.

**Comment by david-wu-octopus** [comment]
Hey all, I've just put up a PR to fix this bug
