### ISSUE TITLE
[metrics] git ls-remote failure counter

### ISSUE THREAD

**Issue by ebuildy** [argoproj/argo-cd#17956]
# Summary

Relate to https://github.com/argoproj/argo-cd/issues/15658, be able to monitor if git ls-remote fail, use case: if git branch dont exist any more.

# Motivation

We would like to be able to detect wrong app config, wrong git branch.

# Proposal

As the good job done at https://github.com/argoproj/argo-cd/pull/15657, I propose a new metric `argocd_git_lsremote_fail_total` or a new label `status` for existing metric `argocd_git_request_total`.

**Comment by Jack-R-lantern** [comment]
Please assign me

**Comment by ebuildy** [comment]
> @ebuildy [#15657 (comment)](https://github.com/argoproj/argo-cd/pull/15657#issuecomment-2074882760)
> 
> Oh, I noticed your mention. Is it okay if I implement that issue?

hey @Jack-R-lantern go for it! didnt spend time on it. Thanks you
