### ISSUE TITLE
Update documentation to confirm ArgoCD 2.10 compatibility with EKS 1.29

### ISSUE THREAD

**Issue by DitmirSpahiu** [argoproj/argo-cd#17967]
Hello ArgoCD Team,

During a recent discussion on the ArgoCD community Slack channel, I confirmed  that ArgoCD version 2.10 is compatible with Amazon EKS version 1.29. However, I noticed that the official documentation does not currently reflect this information.

**Context and Justification:**
This update is crucial as it directly affects deployment decisions for users operating within AWS EKS environments. Clear documentation helps prevent any ambiguity about version compatibility, enhancing user trust and decision-making.

**Details from the Conversation:**
The compatibility confirmation was made on 25/4/2024 in the #argo-cd on Slack by Alan Clucas & Carlos Santana, where it was stated that version 2.10 has been successfully tested with EKS 1.29.

**Suggested Change:**
I propose that the documentation be updated to include a note or a version compatibility table entry confirming that ArgoCD 2.10 supports EKS 1.29. This could be placed in the section detailing system requirements or version compatibilities.

**Impact of Change:**
By updating the documentation, we can ensure that all users are aware of the supported versions and can plan their deployments accordingly. This small change will greatly enhance the user experience and confidence in using ArgoCD for their CI/CD needs.

Thank you for considering this enhancement to the documentation. I am happy to help with drafting the update if needed.

Best regards,

Ditmir Spahiu

**Comment by d1egoaz** [comment]
The latest (v2.11) version https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/ doesn't mention support to Kubernetes v1.29.x
<img width="812" alt="image" src="https://github.com/argoproj/argo-cd/assets/950087/96c773a3-dc14-4011-a812-77f79d9681a1">


However the test matrix has it:
https://github.com/argoproj/argo-cd/blob/v2.11.0/.github/workflows/ci-build.yaml#L407
```
    strategy:
      fail-fast: false
      matrix:
        k3s-version: [v1.29.1, v1.28.6, v1.27.10, v1.26.13, v1.25.16]
```

It'll be great to have the official docs updated.

Thanks

**Comment by christianh814** [comment]
The official docs already state this

https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#tested-versions
https://argo-cd.readthedocs.io/en/stable/operator-manual/tested-kubernetes-versions/

Can this issue be closed?

**Comment by DitmirSpahiu** [comment]
Yeap .

It can be closed .

Many Thanks!
