### ISSUE TITLE
bash autocompletion

### ISSUE THREAD

**Issue by edwinpjacques** [argoproj/argo-cd#1798]
**Is your feature request related to a problem? Please describe.**

argocd has a rich command line interface, but it's hard to use because bash completion is not available.

**Describe the solution you'd like**

bash completion should work for all basic commands including:
1. suggestions for valid commands
1. suggestions for all flags that are appropriate to the command
1. provide lists of valid choices whenever possible (for instance, projects, roles, etc.)

**Have you thought about contributing yourself?**

Yes, and I am already writing the PR to fix this.

**Comment by edwinpjacques** [comment]
Resolved in PR #1803

**Comment by alexec** [comment]
Fixed for v1.2
