### ISSUE TITLE
Bump kustomize version to at least 5.3.x

### ISSUE THREAD

**Issue by rolandkool** [argoproj/argo-cd#18052]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Kustomize versions 5.3 and up include new parameters that can be used with helm templates that use the helm `.Capabilities.APIVersions.Has` function. It would become possible to extend the `kustomize.buildOptions` with the new `--helm-api-versions` kustomize parameter to pass in API versions that exist in the cluster. The current bundled version, 5.2.1, does not have this option yet.

**Version**

2.10.9

**Comment by rolandkool** [comment]
Similar issue but using helm template directly instead of helm through kustomize: https://github.com/argoproj/argo-cd/issues/3594
and https://github.com/argoproj/argo-cd/issues/5202

**Comment by heyleke** [comment]
this got fixed in https://github.com/argoproj/argo-cd/pull/18556
