### ISSUE TITLE
当我使用clewd的时候出现了无法读取.null中memberships的错误

### ISSUE THREAD

**Issue by lingyinyumo** [argoproj/argo-cd#18064]
_Clewd:_
TypeError: Cannot read properties of null (reading 'memberships')
    at Server.onListen (D:\demo\clewd\clewd.js:277:82)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
) {
  [stack]: "TypeError: Cannot read properties of null (reading 'memberships')\n"
 +
    '    at Server.onListen (D:\\demo\\clewd\\clewd.js:277:82)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues
:95:5)',
  [message]: "Cannot read properties of null (reading 'memberships')"
}

**Comment by wanghong230** [comment]
This issue is not actionable without any detail or steps to reproduce. Please reopen and add more details if you have any.

Also, we don't have the knowledge of Clewd. It seemed to be a Clewd project issue instead.
