### ISSUE TITLE
Automatically create namespace with application

### ISSUE THREAD

**Issue by basvandenbrink** [argoproj/argo-cd#1809]
**Is your feature request related to a problem? Please describe.**
Currently, when an application is created using Argo CD and the namespace does not exist, the synchronization of that application fails with the error `Error from server (NotFound): namespaces "<namespace>" not found`. I am then forced to use kubectl to create the namespace.

**Describe the solution you'd like**
I would like Argo CD to automatically create non-existing namespaces when I create an application.

**Comment by alexec** [comment]
Could you add the namespace manifest to the application?

**Comment by basvandenbrink** [comment]
Thanks for the tip. Adding a namespace manifest works. However, I have to hard code the namespace name in the manifest. Is there also a way to choose the namespace using the web ui and then let Argo CD create the namespace?

**Comment by jessesuen** [comment]
While I agree it would be a convenient feature, we need to be careful with auto-creation of namespaces:

* the option needs to comply with project constraints -- i.e. if the project does not permit Namespaces to be created, then just because application has this option ticked, should not allow it to be created.

* there are some corner cases with auto-namespace deletion (if created with an application). The obvious logic would be to delete the namespace if it was created with the app. However, the question becomes how should it behave when there are other objects in the namespace (possibly created by different apps, or created out-of-band from Argo CD). A point of reference would be to see how Helm handles this.

**Comment by basvandenbrink** [comment]
True, that feature can be a little bit dangerous. For me, adding a namespace manifest with a hard-coded name is sufficient. Do you want to keep this open for the discussion about auto-creating namespaces with user-definied names?

**Comment by alexec** [comment]
Could you use Helm or Kustomize to parameterise the namespace?

**Comment by basvandenbrink** [comment]
Thanks for the tip. Creating a file named `namespace.yaml` in the templates directory of the Helm chart with the following content works for me.

```
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
```

Disadvantage is that I would have to modify the chart (which is not possible in most cases). But for me, the alternatives mentioned in the comments are sufficient.

**Comment by PaulVanStaden** [comment]
So to be sure the recommendation is that namespaces should either be part of the helm chart or should be handled externally in contrast with the CI/CD tool taking care of it

**Comment by mnaser** [comment]
Is there any chance this can be revisited with the addition of native Helm applications with ArgoCD 1.3?

**Comment by benjamin-tucker** [comment]
Creating the namespace would be cool, just pointing out it is a slippery slope. We'll want annotations on it next for KIAM.

**Comment by james-callahan** [comment]
e.g. If I'm trying to deploy a new application; who should create the namespace for it (and when?)

At the moment, to have an project create namespace needs permissions to create arbitrary namespaces: could this be narrowed? (so that e.g. a project with permissions in namespace `foo` can only create/modify the namespace `foo`)

**Comment by basvandenbrink** [comment]
Because of the recent discussions, I have reopened the issue.

**Comment by blairham** [comment]
would it be possible to use argo workflow here to create the namespace? I too would like to have the namespace created if it didn't exsit and removed upon delete

**Comment by k** [comment]
Putting it in as a manifest doesn't work well when there are presync hooks in the Application, because then the Namespace has to be a PreSync hook.

**Comment by jurgenweber** [comment]
I just make a different release using the raw chart that has all my namespaces in it.

ezymode.

**Comment by amazingandyyy** [comment]
Hi, I need to create a configmap before my presync job run, seems like the same issue as here, any ideas?

**Comment by Exodus** [comment]
For those getting here through google search, it's possible to create a namespace as part of the Application CRD:

```
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

Check [ArgoCD Application CRD](https://argoproj.github.io/argo-cd/operator-manual/application.yaml)

**Comment by JoKuebler** [comment]
> 

Is there also a way to delete the namespace when removing the manifest? Pruning enabled seems to leave the namespace intact.

**Comment by ozbillwang** [comment]
@Exodus 

Is the feature ready or not?

```
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
 ```

I still get error that it can't automatically create the namespace

```
Error from server (NotFound): error when creating "application.yaml": namespaces "pproject-1" not found
```

**Comment by Exodus** [comment]
> @Exodus
> 
> Is the feature ready or not?
> 
> ```
>   syncPolicy:
>     syncOptions:
>       - CreateNamespace=true
> ```
> 
> I still get error that it can't automatically create the namespace
> 
> ```
> Error from server (NotFound): error when creating "application.yaml": namespaces "pproject-1" not found
> ```

Yes, that's correct. If you're having issues with it, there's an ArgoCD Slack Channel in the CNCF Slack, there you could get help with support in the #argo-cd channel. You may want to check what version, post your applications yaml definition there, there might be something wrong with the syntax. Review the application.yaml that I link to in my previos post.

**Comment by vikas027** [comment]
> I still get error that it can't automatically create the namespace

Hey Bill,

Long time ;) 

I just tried the same with version `v2.9.3`, works like a charm.

**Comment by caiocsgomes** [comment]
If you reached here, know that I was for days trying to do this work on the latest version. Then I saw this last comment about `v2.9.3` and decided to try it. I can confirm it works in this version. There is something wrong in the latest version.

**Comment by fatsolko** [comment]
it works
v2.12.0+ec30a48

**Comment by wethinkagile** [comment]
Why is this possible via UI and not via switch from CLI?
