### ISSUE TITLE
Collect test coverage from e2e tests

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#18130]
# Summary

Today we only collect coverage from unit tests. We should also collect coverage from e2e tests.

# Motivation

It would be helpful to get a clearer idea of our complete coverage.

# Proposal

New go versions support collecting coverage from running code. We could collect profiles from each of the components and merge them all with the unit coverage data. https://tip.golang.org/doc/go1.20#cover

**Comment by crenshaw-dev** [comment]
Looks like combining the outputs of the various tests won't be prohibitively difficult. https://dustinspecker.com/posts/go-combined-unit-integration-code-coverage/

**Comment by rumstead** [comment]
Generating the coverage wasn't too bad, added a draft PR. Now we just need to combine the unit test coverage.out with the e2e coverage and upload it.
