### ISSUE TITLE
Cannot load data of Clusters in UI. "Failed to load data, please try again." - message appear, "Unable to load data: Not Found" - message pop up.

### ISSUE THREAD

**Issue by laiminhtrung1997** [argoproj/argo-cd#18140]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Cannot load data of clusters in UI.
The error message shows up - "Failed to load data, please try again."
The error message pops up - "Unable to load data: Not Found"

**To Reproduce**
1. Open UI
2. Click Settings
3. Click Clusters
4. Click any cluster that has shown up.

**Expected behavior**
The UI can load the data of any cluster.

**Screenshots**
![image](https://github.com/argoproj/argo-cd/assets/68812829/1a316edc-68e4-40b2-a058-dbf8078f3c55)
![image](https://github.com/argoproj/argo-cd/assets/68812829/74f100b6-1fde-423e-89b5-c97fc3a241fd)

**Version**
v2.10.4

**Logs**
```
time="2024-05-09T08:39:56Z" level=debug msg="Checking if cluster https://xxxxxxxxxxxxxxxxxxxxxx.gr7.region.eks.amazonaws.com with clusterShard 0 should be processed by shard 0"
time="2024-05-09T08:39:56Z" level=debug msg="Checking if cluster https://kubernetes.default.svc with clusterShard 0 should be processed by shard 0"
time="2024-05-09T08:39:56Z" level=debug msg="Successfully saved info of 2 clusters"
```

**Comment by romanperesypkin** [comment]
Hi

I had similar issue
In my case I have istio with path normalization.
Either istio or smth in the middle transforming uri from
`https://your.domain/api/v1/clusters/https%3A%2F%2Fkubernetes.default.svc?id.type=url`  into
`https://your.domain/api/v1/clusters/https:/kubernetes.default.svc?id.type=url`
Notice single slash in `https:/kubernetes`

I got to debug ArgoCD's api-server to find it. 'debug' mode does not show that server received http request and did not find url. I added Istio VirtualService to modify uri back before passing it to Argo CD server

**Comment by laiminhtrung1997** [comment]
The issue does not occur in my environment. I will close this.

**Comment by tbernacchi** [comment]
My argo-cd was running behind a proxy using nginx-ingress on `/argocd`. I've migrated all my ingresses to Gateway API resources using `HTTPRoute` and now my UI it's broken with the same original issue. Any ideas?

<img width="1313" alt="Screenshot 2024-12-12 at 17 45 30" src="https://github.com/user-attachments/assets/0b7e0e97-3117-4ec6-93f2-8c643ef0ad76" />

**Comment by sidiyer20** [comment]
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/95eed562-0427-4970-aa43-e48cee5981a5" />
getting the same error in argocd v2.14.5  with ha-installation.

I am using aws alb to route the request to argo-server.

Its not able to process this url from UI

<img width="1202" alt="Image" src="https://github.com/user-attachments/assets/1aa2f9f5-862b-4d65-96ab-6c63e3036bf6" />

But when i am making req to argo-server with same url using curl, from an worker instance I am able to get the output.

<img width="1036" alt="Image" src="https://github.com/user-attachments/assets/3eb109bd-8fe9-4c72-b4c3-74ac7c4dc113" />

**Comment by pbnsh** [comment]
In case someone else is using envoy gateway and stumbles on this, see workaround (ClientTrafficPolicy, escapedSlashesAction) in https://github.com/envoyproxy/gateway/issues/4848.

**Comment by tbernacchi** [comment]
[UPDATE] - All good here. I've update to `v2.14.10+5feb8c2`. [See](https://github.com/argoproj/argo-cd/issues/20790#issuecomment-2669143997)

**Comment by O5ten** [comment]
> In case someone else is using envoy gateway and stumbles on this, see workaround (ClientTrafficPolicy, escapedSlashesAction) in [envoyproxy/gateway#4848](https://github.com/envoyproxy/gateway/issues/4848).

Thank you so much, this was exactly what solved my problem.
