### ISSUE TITLE
argocd events don't show app sync revision for multi-source apps

### ISSUE THREAD

**Issue by gdsoumya** [argoproj/argo-cd#18169]
**Describe the bug**

When using multi source apps, the k8s event logs do not show the commit revision being synced to in the event message. Shows up as `Initiated automated sync to ''`

Possible issue in this [part](https://github.com/argoproj/argo-cd/blob/653fc8da1f9c48cef535ff15e6ac7b5f795c9dae/controller/appcontroller.go#L1926) of the code which only considers `desiredCommitSHA` and not `desiredCommitSHAsMS`.

**To Reproduce**

- Create a multi-source app, or even a single source app but use the `sources` field to declare the source.
- Enable auto sync for the app
- When the app auto syncs to a new revision, you should see k8s events with message `Initiated automated sync to '' ` which is missing the revision hash.

**Expected behavior**

The sync revision hash should show up in the argocd events.

**Version**

v2.10.6

**Comment by onee-only** [comment]
Hi @gdsoumya. I would like to work on this.

How do you want the format to be when it is multi source app?
Would it be okay to just join `desiredCommitSHAsMS` with `, `?
