### ISSUE TITLE
Allow to add cluster with service account token

### ISSUE THREAD

**Issue by wanghong230** [argoproj/argo-cd#182]
If user has created the service account with proper privileges, argo-cd could allow the user to add the cluster with it by skipping the role, service account creation.

**Comment by JazminGonzalez-Rivero** [comment]
hello @wanghong230 ! can we sync up to get the full context of this ticket? I see that if we run "cluster add" but the appropriate service account is already created we get an output such as 

![image](https://user-images.githubusercontent.com/1447492/42599019-cadbe4de-8512-11e8-8598-247796c9b9f4.png)
 where the service account is acknowledged to already have been created. 

was this along the lines of what you were suggesting or did you mean to have a passable field to the cli that would allow for arbitrarily named service accounts?

**Comment by jessesuen** [comment]
Wontfix. ArgoCD will continue to have cluster-admin privileges and will not operate using a collection of limited service account tokens.
