### ISSUE TITLE
Add more timing information into reconciliation log

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [argoproj/argo-cd#18217]
# Summary

There's a log "Reconciliation completed" that includes some timing information, like `git_ms` and `patch_ms`. However, quite often the total time `time_ms` is several times larger than a sum of existing breakdowns, indicating that some slow steps are not being timed. It would be great to have a more detailed breakdown.

# Motivation

Have a more detailed breakdown of time spent on reconciliation.

# Proposal

Add more timing tracking, perhaps using `TimingStats` and its `addCheckpoint`.

**Comment by shenyutong10086** [comment]
I am working on it

**Comment by andrii-korotkov-verkada** [comment]
This can be overlapping with https://github.com/argoproj/argo-cd/issues/18923, may be not needed anymore.
