### ISSUE TITLE
Github Enterprise SSH Key

### ISSUE THREAD

**Issue by marcb1** [argoproj/argo-cd#1824]
We use github enterprise, and run into SSH errors when the argo server tries to clone the git repo via SSH.

We run a script that does something along the lines of:
```
kubectl exec -ti argocd-repo-server -- bash -c \
 "mkdir -p ~/.ssh && ssh-keyscan -H  github-enterprise-host > ~/.ssh/known_hosts"
```

The `known_hosts` is not persisted when the pods restart. Was wondering if anyone figured out a better way to do this?

**Comment by alexec** [comment]
Please refer to https://argoproj.github.io/argo-cd/user-guide/private-repositories/

**Comment by marcb1** [comment]
thank you!
