### ISSUE TITLE
Argocd manifest diff shows no differences even though image was updated and desired is different then live.

### ISSUE THREAD

**Issue by abhay-apella** [argoproj/argo-cd#18254]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Argocd is not updating the live manifest to the desired manifest even though there is a update to the spec image tag. Our environment is:
1. Make a commit to git, create a PR and merge to main.
2. We build the container and then upload it to our artificatory.
3. We use argocd-image-updater to update using [digest strategy](https://argocd-image-updater.readthedocs.io/en/stable/#features)
4. The desired manifest gets updated and correctly reflects the new image digest.

However, even though we can manually check and see the Live and Desired manifests:
Desired:
```
spec:
      containers:
        - args:
             ...
          image: >-
            us-central1-docker.pkg.dev/<our artifact repo>:main@sha256:39491a679c6b1d8e02ba5c9674ff2b3a371a566bf4f49743e52430d44878de70
```

Live:
```
spec:
      containers:
        - args:
             ...
          image: >-
            us-central1-docker.pkg.dev/<our artifact repo>:main@sha256:7ac98a97c4473f4505e8cf6f760650b62d17f3466192dbc51da7d04edd366d5e
```

However, the diff of the manifests shows as empty. The other odd thing is that we apply the same set of configuration across multiple apps and our setup consistently works.
In this case we see:
1. Logs from argocd-image-updater that it attempted to deploy the new version
2. We see the Live manifest being mostly updated with the correct new labels and variables that we set.
3. The spec.containers.image is still the old tag.

We also tried to:
1. To disable `RespectIgnoreDifferences`, which worked the first time to get the image to update but not subsequent times. Our ignore configuration is: 
```
metadata:
  annotations: {}
syncPolicy:
  syncOptions:
    - "CreateNamespace=true"
    - "RespectIgnoreDifferences=true"
``` 
```
ignoreDifferences:
  - group: networking.istio.io
    kind: VirtualService
    jqPathExpressions:
      - >-
        .spec.http[].route[] | select(.destination.host |
        match("stable|canary")) | .weight
```
2. Manually set values through argocd image updater and through argocd which would not trigger manifest updates.

The only consistent way we can get the deployment to work is to delete the deploy in argocd and then get it to update the deployed image.

Reading this: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/ it seems it should be merging the updates but it is not consistent. This also did not seem to be the issue: https://github.com/argoproj/argo-cd/issues/14838

**To Reproduce**
We are not sure how to reproduce this consistently.

**Expected behavior**

We would expect diff to show the desired manifest updates and then be applied to the live manifest globally as it does not occur in all of our apps, but does occur on these steps:
1. Make a commit to git, create a PR and merge to main.
2. We build the container and then upload it to our artificatory.
3. We use argocd-image-updater to update using [digest strategy](https://argocd-image-updater.readthedocs.io/en/stable/#features)
4. The desired manifest gets updated and correctly reflects the new image digest.

**Screenshots**

**Version**
We apply 2.10.5 on cluster install.
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.5/manifests/ha/install.yaml

**Logs**

```
Paste any relevant application logs here.
```

**Comment by todaywasawesome** [comment]
@abhay-apella does it catch the diff if you do a hard refresh manually? I suspect you're having an issue with the cache.

**Comment by abhay-apella** [comment]
> @abhay-apella does it catch the diff if you do a hard refresh manually? I suspect you're having an issue with the cache.

We also tried clicking refresh, sync, and attempted manually updating values supplied. It only updated when we manually changed the spec.containers.image value or deleted the deploy. Would there be another thing to try to check if its a caching issue?

**Comment by stephaneetje** [comment]
Hello, we are having the same problem after upgrading from helm chart version 6.7.18 to 6.8.1.
Clicking on Hard refresh does make argocd see the diff to sync, without manually doing a hard refresh, changes on image tag are never seen.

**Comment by abhay-apella** [comment]
Hi, 
We are going to try to upgrade to 2.11.2 to see if its resolved there. Was there any updates on the root cause? Alternatively is there any place we could take a look at to begin to see why this issue is caused?

Thanks!

**Comment by twonds** [comment]
An upgrade to 2.11.3 did not change the behavior. We still see a bug where the live and desired manifest are different but considered in sync. A hard refresh does not resolve it.

**Comment by FuriousGopher** [comment]
Hello guys.
My ArgoCD version is v2.11.3+3f344d5
and i have trhe same issue
this is my Argocd manifest file 

`---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-application-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: armaa/de_k8s:development
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: development
    argocd-image-updater.argoproj.io/git-repo: git@github.com:dtf/dedge.git
    argocd-image-updater.argoproj.io/git-path: argocd/environments/development
spec:
  project: default
  source:
    repoURL: 'https://github.com/def/dge'
    targetRevision: development
    path: 'argocd/environments/development'
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true`
      
      Maybe somebody can help ?

**Comment by FuriousGopher** [comment]
In Argocd Gui i can see what my main deployment comteiner see new Doker image Digest but dont update pods

**Comment by javydekoning** [comment]
I seem to have the same issue on 2.11.3

**Comment by twonds** [comment]
We have discovered the specific issue causing our problem. The cluster also runs argo rollouts and there was an argocd configmap configuration for ignore differences on Rollouts:

```
resource.customizations.ignoreDifferences.all: |
    group: argoproj.io
    jsonPointers:
      - /spec/template/spec/containers/0/image
      - /spec/template/metadata/labels
    kind: Rollout
```

This should have only affected Rollout resources but it seems it also affected Deployments.

**Comment by twonds** [comment]
Closing this since it was a misconfiguration https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#system-level-configuration
