### ISSUE TITLE
Add kafkaConnector and KafkaBridge custom healthchecks for strimzi custom resources 

### ISSUE THREAD

**Issue by lenglet-k** [argoproj/argo-cd#18271]
# Summary
Add additional strimzi custom resource health checks, including:

KafkaConnector
KafkaBridge

# Motivation

 it would be great to have support for managing these custom resource out of the box with Argo CD.

# Proposal

Review the PR (once I make it) with additional custom resource healthchecks for the above-mentioned strimzi resources.

**Comment by csantanapr** [comment]
Thank you @lenglet-k this is great contribution to have
