### ISSUE TITLE
tls errors when pulling image, onprem harbor oci helm & image repo, local certificate authority

### ISSUE THREAD

**Issue by lknite** [argoproj/argo-cd#18273]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In the past it worked just to mount the the ca.crt into the /etc/ssl/certs path, but this stopped working so I went ahead and added the cert k.home.net via the gui. If I exec into a pod and run 'openssl s_client' they all show 'Verification: OK', yet not able to pull.

**To Reproduce**

1. create helm chart and store in local harbor oci repo, tls certs generated using cert-manager w/ local certificate authority
2. create image and store in local harbor repo (the helm chart includes multiple helm chart dependencies, each of those references an image in the repo)
3. add local certificate authority public cert 'k.home.net' to argocd via gui
4. k apply applicationset which defines source as the helm chart in the onprem harbor oci repo
5. watch as images fail to pull

**Expected behavior**

normal deployment of helm chart and associated images

**Version**

```shell
v2.11.0+d3f33c0
```

**Logs**

```
$ openssl s_client -debug -showcerts -CAfile /app/config/tls/k.home.net -connect harbor.vc-prod.k.home.net:443 | grep Veri
depth=1 CN = k.home.net
verify return:1
depth=0 
verify return:1
Verification: OK
Verify return code: 0 (ok)
```

```
pod/list-controller-blocks-8bb466d6c-hrb79   0/1     ImagePullBackOff   0          16h
pod/list-api-blocks-7cf455b9d-8cv25          0/1     ImagePullBackOff   0          15m
pod/list-api-lists-6c66d94ddc-tcmqp          0/1     ImagePullBackOff   0          16h
pod/list-www-58bcd759ff-fpkqz                0/1     ImagePullBackOff   0          16h
pod/list-controller-lists-555bd74fb7-9ncb5   0/1     ImagePullBackOff   0          16h
pod/list-websocket-7fcf75bb9d-flpft          0/1     ImagePullBackOff   0          16h
```

```
Failed to pull image "harbor.vc-prod.k.home.net/list/api-blocks:0.0.9": failed to pull and unpack image "harbor.vc-prod.k.home.net/list/api-blocks:0.0.9": failed to resolve reference "harbor.vc-prod.k.home.net/list/api-blocks:0.0.9": failed to do request: Head "https://harbor.vc-prod.k.home.net/v2/list/api-blocks/manifests/0.0.9": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
![image](https://github.com/argoproj/argo-cd/assets/92187614/e0ca81f6-755e-4b5f-b2c9-4d300f648df4)

from my local linux box:
```
$ docker pull harbor.vc-prod.k.home.net/list/api-blocks:0.0.9
0.0.9: Pulling from list/api-blocks
4abcf2066143: Pull complete 
891ce9574a73: Pull complete 
e425669e0253: Pull complete 
d01aebfa4c88: Pull complete 
4f4fb700ef54: Pull complete 
eb21768a585e: Pull complete 
Digest: sha256:efc8eb477445c0a9d9335cabc6d907a324c1f3ea73af4282c20ac6758464f702
Status: Downloaded newer image for harbor.vc-prod.k.home.net/list/api-blocks:0.0.9
harbor.vc-prod.k.home.net/list/api-blocks:0.0.9
```

**Comment by lknite** [comment]
@sabre1041 Is this issue possibly a missed use case related to your fix?  https://github.com/argoproj/argo-cd/pull/16656

**Comment by sabre1041** [comment]
@lknite the issue that you are facing is unrelated to Argo CD as the errors are coming from the underlying container runtime that is attempting to retrieve the container image that is specified (most likely) by the manifests associated within Argo CD. Additional configurations need to be made within the container runtime level which is outside the scope of Argo CD.

**Comment by lknite** [comment]
I'm trying to understand ... the "over-all" helm chart contains other helm charts like so:
```
$ cat Chart.yaml 
apiVersion: v2
name: list
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "1.0"

# trigger - a
dependencies:
- name: postgresql
  version: 15.1.0
  repository: oci://registry-1.docker.io/bitnamicharts
- name: nats
  version: 1.1.10
  repository: https://nats-io.github.io/k8s/helm/charts/
- name: api-blocks
  version: 0.0.9
  repository: oci://harbor.vc-prod.k.home.net/list-charts
```

And the 'api-blocks' chart has the usual template files one would expect, which includes a deployment.yaml with the image:
```
$ find ./chart/
./chart/
./chart/values.yaml
./chart/templates
./chart/templates/deployment.yaml
./chart/templates/ingress.yaml
./chart/templates/service.yaml
./chart/Chart.yaml
```

The template is being resolved as expected:
```
      containers:
      - image: {{.Values.image.repository}}/{{.Chart.Name}}:{{.Values.image.tag}}
        name: {{.Release.Name}}-{{.Chart.Name}}
```

When you speak of the underlying container runtime, that sounds like cri that kubernetes is using (rather than the deprecated docker).  So, if I'm understanding correctly, it sounds like argocd can only go "one level deep", yet if you look above at the 3 dependencies in that helm chart the first two install ok 'postgresql' and 'nats', so I would expect 'api-blocks' to install just the same?

**Comment by lknite** [comment]
Oh!  I got it!  Thank you!
