### ISSUE TITLE
Upgrade guide misses entry for v2.11

### ISSUE THREAD

**Issue by corneliusroemer** [argoproj/argo-cd#18279]
**Describe the bug**

The docs don't have an entry for upgrade from 2.10 to 2.11 (the latest release)

**To Reproduce**

Go to https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/overview/

<img width="1563" alt="Brave Browser 2024-05-19 17 49 44" src="https://github.com/argoproj/argo-cd/assets/25161793/78a9abd6-4786-474c-9355-3b86b2e263a6">

**Comment by Fluder-Paradyne** [comment]
https://github.com/argoproj/argo-cd/blob/2dd5cd8b9a2312adcb6f6150f2b0aeef93fb8285/docs/operator-manual/upgrading/overview.md?plain=1#L40-L43

The entries are already present in master, I think maintainer have to deploy the docs site once again

**Comment by RafaelBroseghini** [comment]
looks like this was taken care as part of https://github.com/argoproj/argo-cd/pull/17893

**Comment by crenshaw-dev** [comment]
Looks like it was only a partial fix. Put up a PR to finish the fix.

**Comment by agaudreault** [comment]
I can confirm that the doc exists https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.10-2.11/
