### ISSUE TITLE
Add support Kubernetes v1.30

### ISSUE THREAD

**Issue by csantanapr** [argoproj/argo-cd#18281]
# Summary

Update test matrix to include Kubernetes v1.30

# Motivation

Support latest version of Kubernetes

# Proposal

- Wait for k3s official release that support v1.30 here https://github.com/k3s-io/k3s/releases
**Update tests:**
- https://github.com/argoproj/argo-cd/blob/master/.github/workflows/ci-build.yaml#L409
- https://github.com/argoproj/argo-cd/blob/release-2.11/.github/workflows/ci-build.yaml#L407
- https://github.com/argoproj/argo-cd/blob/release-2.10/.github/workflows/ci-build.yaml#L365
- https://github.com/argoproj/argo-cd/blob/release-2.9/.github/workflows/ci-build.yaml#L364
**Update docs:**
- https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/tested-kubernetes-versions.md
- https://github.com/argoproj/argo-cd/blob/release-2.11/docs/operator-manual/tested-kubernetes-versions.md
- https://github.com/argoproj/argo-cd/blob/release-2.10/docs/operator-manual/tested-kubernetes-versions.md
- https://github.com/argoproj/argo-cd/blob/release-2.9/docs/operator-manual/tested-kubernetes-versions.md

**Comment by sivchari** [comment]
Hi @csantanapr 
I opened the pull-request to update Kubernetes v1.30.1, thanks.
https://github.com/argoproj/argo-cd/pull/18288

**Comment by Jack-R-lantern** [comment]
The issue appears to be resolved in this [PR](https://github.com/argoproj/argo-cd/pull/19654).
The issue should be closed
