### ISSUE TITLE
Make it easier to understand what the application diffs are

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1831]
**Is your feature request related to a problem? Please describe.**

A nice feature of `kapp` is that it prints what it's about to do before it does it. It'd be nice to see what sync is going to do before 

**Describe the solution you'd like**

Display UI screen showing the plan before it is applied.

**Comment by jessesuen** [comment]
Isn't this just our dry-run feature?

**Comment by alexec** [comment]
This is more - would this be a nice feature. You can get an idea of what will happen when you sync by looking at the diffs, but it might be nice to explicitly state what this would be. 

I don't think dry-run works like that?

**Comment by jessesuen** [comment]
So a UI preview pane to show the diffs as an aggregate before invoking any operation (similar to a github PR)? If yes, I think that would be useful. Currently I click around on each OutOfSync, but it's a lot of clicking

**Comment by alexec** [comment]
Yeah, don't know what the solution is.

**Comment by alexec** [comment]
Actually, I like the idea of a big diff.

**Comment by OmerKahani** [comment]
The big diff is nice, just like the github PR. currently one can do it with the cli: argocd app diff

Also can be a good feature, to know if the change will cause recreate of pods, for example in the case of deployment. this probably should be a feature of kubectl

**Comment by alexec** [comment]
While it seems like it should be easy, creating a plan is challenging as (1) the chef is the app controller, and (2) there are many ingredients to the plan:

* the current state of the app
* is it a "selective sync"?
* is the sync strategy "apply" or "hook?
* it any operation started?
* are any object degraded or healthy?
* revision
* operation start date
* what permissions the user has

The code for generating diffs, creating sync tasks, and then executing them is quite coupled.

I this generating a plan would be time consuming development.
