### ISSUE TITLE
Please allow disabling application spec in events 

### ISSUE THREAD

**Issue by michalrysavy-ext95730** [argoproj/argo-cd#18310]
# Summary

Hello all,

I found out [this change - app spec in events](https://github.com/argoproj/argo-cd/pull/16416) and I believe it would be better to have this functionality switchable. 

Please make a possibility to switch it off.

# Motivation

We have two troubles with some application teams and if both problems concern the same application, [this functionality](https://github.com/argoproj/argo-cd/pull/16416) will have significant impact to etcd size.

Problems are:
* some applications have huge spec in `Application` resource because of java truststores (for example) in values - in this case the values size is about 100-200kB
* some applications, especially in dev environments, have long-term issues in `Application` resource or in Helm chart which cause synchro loops and huge amount of events (thousands per an hour)

If one application had both problems at the same time, this functionality could actually cause 8000 events, each 200kB in size - in total 1.5GiB in etcd.

# Proposal

It would be great to make a switch in `argocd-cm` `ConfigMap`.

**Comment by tooptoop4** [comment]
agree, really need https://github.com/argoproj/argo-cd/issues/18205

**Comment by jannfis** [comment]
I created #16416 for reverting the original PR.
