### ISSUE TITLE
2.11.0 -> 2.11.1 changed the Registry for Redis and HAProxy from Docker to Amazon ECR breaking Cosign verification

### ISSUE THREAD

**Issue by avo-sepp** [argoproj/argo-cd#18327]
**Describe the bug**

A recent patch modified the Container Registry used for both Redis and HAProxy. This changed the Registry source from Docker to an Amazon ECR. 

Those of us using Cosign to validate the registry source were blocked from upgrading. Because the new Redis version includes an authentication change, it prevented the new Argo from interfacing with Redis. Effectively bringing ArgoCD down and requiring a reinstall. We use ArgoCD to sync ArgoCD, but because ArgoCD went down it had to be manually installed again with kustomize.

Why was the registry changed from Docker to Amazon ECR? Can this be included in the change log more clearly, since it is a breaking change for Cosign users?

**To Reproduce**

Cosign is enabled and performing image registry validation for Redis and HAProxy

**Expected behavior**

Upgrading from 2.11.0 -> 2.11.1 should upgrade cleanly. 

**Screenshots**

**Version**

argocd: v2.11.0+d3f33c0
  BuildDate: 2024-05-07T18:31:19Z
  GitCommit: d3f33c00197e7f1d16f2a73ce1aeced464b07175
  GitTreeState: clean
  GoVersion: go1.22.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.11.1+9f40df0
  BuildDate: 2024-05-21T13:55:56Z
  GitCommit: 9f40df0c29eca7e45a73f802f033dfd1ed0068e3
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0

**Comment by avo-sepp** [comment]
https://github.com/argoproj/argo-cd/blob/8dff209cba4044ec8d0ff8ec32dd79bded7bafaf/manifests/ha/install.yaml#L22943

Line where change occurred. There are a few lines for HAProxy and Redis in this file that were all changed. You can search `ecr.aws` to find the changes.

**Comment by avo-sepp** [comment]
Also worth noting that the non-ha installs still use Docker Hub for HAProxy and Redis. This change only affects HA installers. Sort of a weird thing I noticed. Why use two registry sources?

**Comment by avo-sepp** [comment]
Thank you Michael! That makes a lot of sense.

**Comment by crenshaw-dev** [comment]
@avo-sepp could you check https://github.com/argoproj/argo-cd/pull/18329 and let me know if the language of the third paragraph makes sense?

**Comment by avo-sepp** [comment]
Looks good. I would suggest using the word Policy for Cosign. Something like "make sure your Image Validation policy includes the AWS ECR as an approved registry"

**Comment by crenshaw-dev** [comment]
Pushed with that additional language! lmk if you'd like me to add you as a co-author, I'd just need an email to include in the commit message.  :-)

**Comment by FranAguiar** [comment]
It's possible to override the registry for the haproxy image? I would like to download it from my private registry

**Comment by dmpe** [comment]
The issue is again present in the HA version of 2,12 release @crenshaw-dev https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.0/manifests/ha/install.yaml. In non ha version, everything seems to be ok.

**Comment by crenshaw-dev** [comment]
@dmpe I believe the change is expected in 2.11 and is documented in the upgrade notes.

**Comment by dmpe** [comment]
Indeed you are right, it is there https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.11-2.12/ however someone forgot to include a link from 2.11 to 2.12 on the sidebar :) Thanks

![image](https://github.com/user-attachments/assets/7edcc82a-b7a8-45f9-a4bf-85d049bc425a)

**Comment by crenshaw-dev** [comment]
Oh, good catch. If you have time for a PR to fix that, it would be appreciated!
