### ISSUE TITLE
Allow downloading of argocd binaries directly from API server

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#184]
Someone should be able to login to ArgoCD UI and get the binaries from there.

**Comment by merenbach** [comment]
@jessesuen are these fat binaries or do we need one per architecture?

**Comment by jessesuen** [comment]
We need one for linux-amd64 and one for darwin-amd64. The work here is copying it to the assets directory in the init container and agreeing with ArgoCD UI on where to find it.

**Comment by jessesuen** [comment]
Alex agreed to add download links to github release pages. No need to bundle it inside the server image.

**Comment by alexmt** [comment]
Implemented
