### ISSUE TITLE
The pod log view dark mode toggle fails to set the log background to dark when activated

### ISSUE THREAD

**Issue by MuriukiPM** [argoproj/argo-cd#18405]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The pod log view background remains white regardless of whether dark mode toggle is activated or not.

**To Reproduce**

1. Deploy argocd and access any pod logs on the UI
2. Click the Dark Mode toggle to activate dark mode on the pod log view

**Expected behavior**

If I activate dark mode for pod logs view, the background for the logs should go dark.

**Screenshots**

<img width="792" alt="Screenshot 2024-05-24 at 18 40 16" src="https://github.com/argoproj/argo-cd/assets/61582128/a999c1e4-2cc1-4ae9-8579-cc3db62aaddb">

**Version**
Running the argocd helm chart with argocd version 2.11.0 
```shell
$ argocd version
argocd: v2.11.0+d3f33c0
  BuildDate: 2024-05-07T16:01:41Z
  GitCommit: d3f33c00197e7f1d16f2a73ce1aeced464b07175
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

**Comment by agaudreault** [comment]
Seems fixed by the PR above.
