### ISSUE TITLE
Version upgrade with `kubectl apply` overwrites deployment, removing `--insecure` flag, causing ingress to fail

### ISSUE THREAD

**Issue by corneliusroemer** [argoproj/argo-cd#18427]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I've configured argocd ingress with traefik as described in the docs, adding the `--insecure` flag

>The API server should be run with TLS disabled. Edit the argocd-server deployment to add the --insecure flag to the argocd-server command

https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#traefik-v22

When I upgrade argocd to a newer version, e.g. 
```
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.2/manifests/install.yaml
```

the `--insecure` argument is deleted, causing ingress to fail by ending up in an infinite redirect loop.

**To Reproduce**

1. Install argocd
2. Edit the deployment as described above, adding `--insecure` to the argocd-server` deployment
3. Upgrade argocd with `kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.2/manifests/install.yaml`
4. Observe the deployment

**Expected behavior**

Edits of argocd-server deployment are not overwritten when upgrading.

If this is intended behaviour, then the traefik config docs should mention that the edits won't be persisted.

**Comment by corneliusroemer** [comment]
Apparently customizations like this are never persisted, so this is in a sense intended behaviour. This Stackoverflow answer outlines how to make upgrade-resilient changes: https://stackoverflow.com/a/71692892/7483211

**Comment by agaudreault** [comment]
That is correct, this is the intended behavior of `kubectl apply`. If you need to change the default manifest of ArgoCD, you should use Kustomize or Helm to persist your changes as code, then deploy them.

You can see a basic example of an ArgoCD deployment with Kustomize here https://github.com/argoproj/argoproj-deployments/tree/HEAD/argocd or you can take a look at the helm chart here https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
