### ISSUE TITLE
Incorrect conversion between integer types

### ISSUE THREAD

**Issue by martin-nolan-2020** [argoproj/argo-cd#18432]
Incorrect conversion of an integer with architecture-dependent bit size from strconv.ParseInt to a lower bit size type int32 without an upper bound check.

**Comment by martin-nolan-2020** [comment]
I will work on this issue

**Comment by mbaldessari** [comment]
Dupe of https://github.com/argoproj/argo-cd/issues/18435 ?

**Comment by jsoref** [comment]
https://github.com/argoproj/argo-cd/issues/18435#issuecomment-2365408891
