### ISSUE TITLE
Useless regular-expression character escape

### ISSUE THREAD

**Issue by Nanmozhi22** [argoproj/argo-cd#18431]
The escape sequence '\.' is equivalent to just '.', so the sequence may still represent a meta-character when it is used in a regular expression.

js/useless-regexp-character-escape

File name :  ui/src/app/applications/components/application-summary/edit-notification-subscriptions.tsx

**Comment by Nanmozhi22** [comment]
I will work on this issue

**Comment by davidlj95** [comment]
I think this can be closed as per #18551 #18901 :)
