### ISSUE TITLE
Incorrect conversion between integer types 

### ISSUE THREAD

**Issue by Anu-MT** [argoproj/argo-cd#18435]
This issue is the codeql error in controller/sharding/sharding.go in line no: 120.
Rule: 'go/incorrect-integer-conversion'
Incorrect conversion of an integer with architecture-dependent bit size from strconv.ParseInt to a lower bit size type uint32 without an upper bound check.

**Comment by Anu-MT** [comment]
Hi, I am working this issue. please assign me

**Comment by matankila** [comment]
fixed in [ISSUE #18436]

**Comment by jsoref** [comment]
This is a false positive. I spoke with people from GitHub's security lab to confirm.
