### ISSUE TITLE
Migrate the Grafana dashboard (Angular deprecation)

### ISSUE THREAD

**Issue by marcofranssen** [argoproj/argo-cd#18447]
# Summary

Migrate the Grafana dashboard to not use (Deprecated) AngularJS anymore.

# Motivation

https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

# Proposal

https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

**Comment by tylerauerbeck** [comment]
I think this is a duplicate of #18433 and is potentially resolved by #18434

**Comment by marcofranssen** [comment]
Aaarf, sorry for that, I should have done a better search before submitting this. Thanks for this update.
