### ISSUE TITLE
Add name and labels in cluster metrics

### ISSUE THREAD

**Issue by flbla** [argoproj/argo-cd#18452]
# Summary

Some cloud providers (like AWS) generate random server endpoint something like uuid.eks.amazonaws.com
so it makes difficult to find the cluster with this metrics argocd_cluster_connection_status metrics, as there is only the server endpoint.

I would like a human readable name for argocd_cluster_connection_status metrics and also be able to get the labels of the clusters.

# Motivation

Same as summary

# Proposal

```
argocd_cluster_connection_status{k8s_version="",labels="",name="in-cluster",server="https://kubernetes.default.svc"} 0
argocd_cluster_connection_status{k8s_version="",labels="environment=dev",name="dev-cluster-01",server="https://abcd01:443"} 0
```

**Comment by surajyadav1108** [comment]
Similar :https://github.com/argoproj/argo-cd/issues/17870

**Comment by flbla** [comment]
Hi @surajyadav1108, okay sorry I didn't find it before 
I created a PR to fix it
Could you please review it? Thanks

**Comment by surajyadav1108** [comment]
> Hi @surajyadav1108, okay sorry I didn't find it before I created a PR to fix it Could you please review it? Thanks

no need to sorry i was just mentioning it for the reviewers, my own dev-setup has some problems as of now it will get reviewed soon no worries 🚀

**Comment by agaudreault** [comment]
Closing as duplicate.
