### ISSUE TITLE
feat: support fish completion

### ISSUE THREAD

**Issue by Sn0rt** [argoproj/argo-cd#18483]
# Summary

new feature for fish completion.

for now. ArgoCD support bash, zsh. actually the fish is popular shell too (i am a fish shell user).

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

add the fish completion

reference: https://github.com/argoproj/argo-workflows/issues/13127

**Comment by Jack-R-lantern** [comment]
This issue has been resolved Please close
