### ISSUE TITLE
Add proxy support to kustomize build operations

### ISSUE THREAD

**Issue by the-technat** [argoproj/argo-cd#18487]
# Summary

Inherit the proxy settings from repo-creds into the kustomize build function(s) so that not only pulling the repo is done via proxy but also builing of the kustomize code (since kustomize might pull other git resources via proxy).

# Motivation

We @swisspost are using GH in combination with a cluster behind a corporate proxy. To reach GH from Argo CD we have created a repo-cred matching our GH org, specifying the proxy to use in the repo-cred. If developers specify git repositories in their kustomize `resources`, kustomize won't be able to pull these, since the specified proxy is only used when pulling the initial repo containing the kustomize code but not to build kustomize afterwards.

# Workaround

Of course we can add the proxy using `HTTP_PROXY`/`HTTPS_PROXY` to the repo-server, but then it would be available to all applications unconditionally and we consider this to be too risky. 

# Proposal

First-class proxy support was added in #6286, passing the proxy from the repo-creds struct down to helm commands. A similar approach could be added to kustomize as well (might require refactoring the kustomize code a bit since there's no central wrapper for cmd.Exec that could be used to inject this).

In case the enhancement gets accepted @swisspost is willing to contribute this feature.

**Comment by agaudreault** [comment]
I think the feature makes sense, especially since it is available in Helm already. Feel free to open a PR and contribute 👍
