### ISSUE TITLE
ArgoCD fails to fetch latest git repository updates

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#185]
`git fetch origin` has failed with following error

```
remote: Counting objects: 153, done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 153 (delta 84), reused 129 (delta 84), pack-reused 21
Receiving objects: 100% (153/153), 59.28 KiB | 3.12 MiB/s, done.
Resolving deltas:  89% (76/85), completed with 32 local objects.
fatal: pack has 9 unresolved deltas
fatal: index-pack failed
```

Result of  `git status`: 

``
``

**Comment by merenbach** [comment]
@alexmt what version of Git is being run here?

**Comment by alexmt** [comment]
Good point @merenbach ! I've reproduced it while running argocd locally. I have` git version 2.16.1 `

**Comment by merenbach** [comment]
@alexmt couple follow-ups:

  * Is this reproducible with a raw Git command, or only when Argo CD fetches?
  * What repo(s) are at issue in your tests?
  * is there any more information if the `-v` or `--verbose` flag is specified for `git fetch`?

**Comment by alexmt** [comment]
Encountered another git fetch issue:

```
+ /argocd app create --name dev-cc8....

time="2018-05-21T20:07:53Z" level=fatal msg="rpc error: code = Unknown desc = 'git checkout --detach origin/HEAD' failed: error: Your local changes to the following files would be overwritten by checkout:"

script returned exit code 1
```

**Comment by tomjohnburton** [comment]
Don't know if related but I am getting this error now for just one of my repos,
```
 time="2020-06-05T13:24:32Z" level=fatal msg="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Internal desc = Failed to fetch git repo: `git fetch origin --tags --force` failed exit status 128: error: index-pack died of signal 9\nfatal: index-pack failed"
```

**Comment by Starslider** [comment]
i got the same error today with 1.6.0 

time="2020-06-18T12:22:37Z" level=error msg="`git fetch origin --tags --force` failed exit status 128: error: index-pack died of signal 9\nfatal: index-pack failed" execID=CfUaX

**Comment by jannfis** [comment]
Hey @tomjohnburton and @Starslider - since signal 9 is most likely sent by OOM killer, are you maybe running into an OOM condition?
