### ISSUE TITLE
CreateApp Bug

### ISSUE THREAD

**Issue by emreaslantas0** [argoproj/argo-cd#18509]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by surajyadav1108** [comment]
😕

**Comment by tooptoop4** [comment]
0 details @emreaslantas0

**Comment by christianh814** [comment]
@emreaslantas0 Can you please provide more information?

**Comment by agaudreault** [comment]
Please re-open with details as needed,
