### ISSUE TITLE
`argocd proj role add-group PROJECT ROLE-NAME GROUP-NAME`

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1851]
A team was trying to automate the addition and removal of OIDC groups to a project role. Turns out this is lacking from the CLI. 

We need:
```
argocd proj role add-group PROJECT ROLE-NAME GROUP-NAME
argocd proj role remove-group PROJECT ROLE-NAME GROUP-NAME
```

**Comment by jessesuen** [comment]
If we had https://github.com/argoproj/argo-cd/issues/1852, then we would have been able to workaround the limitation, but since we don't, they were unable to automate this easily, and had to resort to using the API directly

**Comment by alexec** [comment]
oddly, `NewProjectRoleRemoveGroupCommand` already exists but does not appear to be bound

**Comment by alexec** [comment]
boom! don't work
