### ISSUE TITLE
main-xxx.js brokein in ArgoCD v2.11.3 / Chart 7.1.2 (Your browser does not support JavaScript) 

### ISSUE THREAD

**Issue by mmisztal1980** [argoproj/argo-cd#18527]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I've deployed the latest version of ArgoCD to our private environment. Configured `global.domain` and ingress to access the UI.
Upon navigating to the UI I got a blank page stating:

The above result has been reproduced on 2 different machines, under Chrome an FireFox

**To Reproduce**

- deploy the latest version of AgoCD 
- attempt to access the UI
- 
**Expected behavior**

- I'm expecting to see the UI

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/1357057/b5dcc597-16db-4f61-a80b-9b1d356d2e99)

**Version**

```shell
argocd@argo-argocd-server-66665f8786-2vdq6:~$ argocd version
argocd: v2.11.3+3f344d5
  BuildDate: 2024-06-06T08:42:00Z
  GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

N/A

**Comment by mmisztal1980** [comment]
The contents of the main JS bundle appear to be invalid:
![image](https://github.com/argoproj/argo-cd/assets/1357057/242d07f4-80b3-4f57-a436-566804c50cb3)

**Comment by jannfis** [comment]
I cannot reproduce this on a fresh install of Argo CD 2.11.3:

![image](https://github.com/argoproj/argo-cd/assets/3942683/cd160ecd-c40e-4409-b144-917a30ba2b3a)

**Comment by mmisztal1980** [comment]
@jannfis do you know the location of the bundle in the container? I'll verify the image contents

**Comment by mmisztal1980** [comment]
I've tried this with a stock image again - same result. I'm wondering if there's something missing in my chart values...

**Comment by jannfis** [comment]
@mmisztal1980 Stupid question, but have you tried with a different browser, in incognito mode or deleting the browser cache yet?

**Comment by mmisztal1980** [comment]
yes, I've managed to access the UI via `kubectl port-fowrard` so I've verified it's there. Now I'm looking for differences between chart v5.x and v7.x which I might have missed

**Comment by mmisztal1980** [comment]
Fixed. There have been changes in the chart structure which broke our ingress.
