### ISSUE TITLE
Application status panel height dumping

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1855]
**Describe the bug**
The application status panel height jumping after clicking sync button

**To Reproduce**
1. Navigate to any app
2. Click sync button
3. See attached gif

![Screen Recording 2019-07-02 at 12 06 56 AM](https://user-images.githubusercontent.com/426437/60491410-952a9c00-9c5d-11e9-941b-06a51193d472.gif)

**Comment by alexec** [comment]
Jumping? Not dumping?

**Comment by alexmt** [comment]
@alexec you are right :)
