### ISSUE TITLE
clarify scp-provider appset-in-any-namespace secrets considerations

### ISSUE THREAD

**Issue by jkleinlercher** [argoproj/argo-cd#18560]
# Summary

 I read through https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Appset-Any-Namespace/#scm-providers-secrets-consideration and because of this warning about the secret for a SCM Provider I though this provider searches for this secret in the argocd namespace. However, I noticed today that this secret must be placed in the same namespace as the appset, so I ask myself if this warning "By allowing ApplicationSet in any namespace you must be aware that any secrets can be exfiltrated using scmProvider or pullRequest generators." is really accurate since you can only get secrets from your "own" namespace.
Or do I miss something here?

If not, I propose that in the documentation this gets clarified, that only secrets in this special namespace can get exposed, which is actually a namespace exactly for this team?

# Motivation

Then the risks for appset-in-any-namespace with SCMs gets clearer

# Proposal

Adding infos that since secrets for the SCM provider need to get placed in the dev-teams namespace where the appset gets created and the secret probably also gets created by this dev-team, the problem is not that high.

**Comment by christianh814** [comment]
This is a good question. @alexmt or @blakepettersson , do you know if "appset in any namespace" can retrieve  secrets outside of it's namespace? I want to say "no" but I'm not 100% sure.

**Comment by agaudreault** [comment]
The secrets location used by the generators depends on which generator is used. For Git, Cluster, ClusterDecisionResource and Plugin generators, it will use secrets in the controller namespace. For Pull Request and SCM, it will use secrets based on the ApplicationSet namespace. 

That means the application-controller will require permission to get these secrets in external namespaces. If someone can Create/Update an appset in namespace X, and appSet is configured to allow namespace X, that users has the permissions to get the secret through an appset. The user can specify an existing repo-creds secret, and use a malicious api server to collect the authentication information. That is why `ARGOCD_APPLICATIONSET_CONTROLLER_ALLOWED_SCM_PROVIDERS` should be configured to trusted api configuration.

I agree that the documentation should be updated to clarify the meaning of "exfiltrated".

**Comment by thecooldrop** [comment]
I would like to work on this issue.
