### ISSUE TITLE
ArgoCD ships with Golang 1.18.1 which contains a large number of CVEs.

### ISSUE THREAD

**Issue by peadarom** [argoproj/argo-cd#18595]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.

**Describe the bug**

ArgoCD ships with a version of Golang that is a few years old - version 1.18.1 and that version contains lots of CVEs.

**Details**
ArgoCD ships with a version of Golang that is a few years ago - version 1.18.1 and that version contains lots of CVEs. Scanners such as XRAY are able to detect lots of CVEs in the latest version of ArgoCD, whereas Snyk is unable to because Snyk is presently unable to detect issues with the Go Standard Library.

I have read your security notice regarding scanners and CVEs, but I believe you may not know about these ones because Snyk doesn't have the capability to detect issues with the Go Standard Library, which is why I am bringing this to your attention.

**To Reproduce**

Scan ArgoCD with XRAY using `jf docker scan quay.io/argoproj/argocd:v2.10.12` to see the results.

**Expected behavior**

Go is bumped to the latest version.

**Screenshots**

![Screenshot 2024-06-11 at 12 54 29 PM](https://github.com/argoproj/argo-cd/assets/95654589/9b3e7af6-86e8-4e10-8558-809e9632fe18)

**Comment by thecooldrop** [comment]
Hello @christianh814 I would like to work on this issue.

**Comment by christianh814** [comment]
@thecooldrop Yes, feel free to work on this!

**Comment by peadarom** [comment]
Thank you!!

**Comment by jannfis** [comment]
The latest version of Argo CD 2.10 branch is built with [Go 1.21.3](https://github.com/argoproj/argo-cd/blob/cb6f5ac8b8c08ce26cce08b8a1bd2144034bd79b/Dockerfile#L7)

Not sure where your scanner results come from, but I believe it's a false positive.

**Comment by thecooldrop** [comment]
Looking at Dockerfile and go.mod file in release 2.10 branch it seems that 1.21 version of go is used.

I will try to replicate the issue with xray scanner soon and will get back to you

**Comment by crenshaw-dev** [comment]
I think it's because of an old version of git-lfs, which is built with an old version of go.

**Comment by crenshaw-dev** [comment]
https://github.com/argoproj/argo-cd/issues/18723

**Comment by agaudreault** [comment]
Closing as duplicate of #18723 and #18278 ?
