### ISSUE TITLE
Implement graceful shutdown in all Argo CD components

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#18642]
Procfile sets GOCOVDIR for five Argo CD components. But only one (applicationset-controller) shuts down gracefully enough for code coverage data to be produced. In other words, go writes a covmeta file, but not a covcounters file (the file that actually contains coverage info). So today we get partial code coverage info for e2e tests.

The task is to do two things for the remaining four components: 1) implement graceful shutdown and 2) [add the component's gocov directory to the e2e reporting CI](https://github.com/argoproj/argo-cd/blob/master/.github/workflows/ci-build.yaml#L367-L371).

- [x] applicationset-controller
- [x] controller
- [ ] api-server ([WIP](https://github.com/argoproj/argo-cd/pull/15938))
- [x] repo-server
- [x] notification

Exactly what "graceful shutdown means" may vary by component. Concretely, I think it means we need to listen to shutdown signals and end all running goroutines. But the "graceful" part depends on what's running.

**Comment by leehosu** [comment]
Hello, I'm working on the controller part. I'm going to post PR soon.

**Comment by leehosu** [comment]
I'll fix the argocd-application-controller, I'll upload the PR soon.

**Comment by leehosu** [comment]
@crenshaw-dev Hi, crenshaw! 
Please check https://github.com/argoproj/argo-cd/pull/19368. 
If you have any problems, please let me know.

**Comment by andrii-korotkov-verkada** [comment]
Only one left, or was it fixed too?
