### ISSUE TITLE
Git Revision not found when trying to create applicationset from git 

### ISSUE THREAD

**Issue by rmehta2974** [argoproj/argo-cd#18643]
I have following application 
-------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager-deploy-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com/xxx/xxx-xxxx-v2.git
    targetRevision: az-528-1
    path: cluster/deployment/non-prod/apps/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy: {}

----

**which reads the repo and configuration correctly** 

but I have application set  in the search path cluster/deployment/non-prod/apps/cert-manager/cert-manager.yaml

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-multicluster-list2
  namespace: argocd
spec:
  generators: 
    - matrix:
        generators:
  
          - git:
              repoURL: git@github.com/xxx/xxx-xxxx-v2.git
              revision: az-528-1
              directories:
                - path: cluster/deployment/non-prod/apps/cert-manager/*

          - list:
             elements:
              - cluster: dev0-ccp-aks
                namespace: cert-manager
                server: https://xxxx.xxxx.xxx
                targetRevision: v1.13.2
                valuesFile: dev0-ccp-aks-values.yaml
              - cluster: management
                namespace: cert-manager
                server: https://kubernetes.default.svc
                targetRevision: v1.13.2
                valuesFile: management-values.yaml
  template:
    metadata:
      name: cert-manager-{{cluster}}
    spec:
      project: default
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: "{{targetRevision}}"
        helm:
          valueFiles:
            - cluster/argocd/non-prod/apps/cert-manager/common-values.yaml
            - cluster/argocd/non-prod/apps/cert-manager/{{valuesFile}}
      destination:
        namespace: "{{namespace}}"
        server: "{{server}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

Now above code gives following error

error failed to get params for first generator in matrix generator: child generator returned an error on parameter generation: error generating params from git: error getting directories from repo: error retrieving Git Directories: rpc error: code = Internal desc = unable to resolve git revision : repository not found

Here is output of argocd repo list

**Comment by rmehta2974** [comment]
sorry here is output of repo list

C:\caption-health\ops-saas-v2-1\cluster>\users\rmeht\argocd repo list
TYPE  NAME         REPO                                    INSECURE  OCI    LFS    CREDS  STATUS      MESSAGE  PROJECT
git   ops-saas-v2  git@github.com:baylabs/ops-saas-v2.git  false     false  false  false  Successful           default

**Comment by christianh814** [comment]
I don't understand what you're trying to do.

This config 

```
      - git:
          repoURL: git@github.com/xxx/xxx-xxxx-v2.git
          revision: az-528-1
          directories:
            - path: cluster/deployment/non-prod/apps/cert-manager/*
```

Means take very directory in `cluster/deployment/non-prod/apps/cert-manager/` and create an app out of it...yet you're setting...

```
valueFiles:
- cluster/argocd/non-prod/apps/cert-manager/common-values.yaml
```

What what's in that directory and what are you trying to do? it seems like you might be using an incorrect generator but we won't know for sure unless you tell us what you're trying to do

**Comment by rmehta2974** [comment]
I have multiple applications in this folder ,cluster/deployment/non-prod/apps/, I want to deploy them as application sets and each application is getting deployed to different cluster , but these are mostly helm charts with few them homegrown.

Each cluster is env specific and has specific values for helm. cert-manager is one such application , with value files stored in github at this location - cluster/argocd/non-prod/apps/cert-manager/common-values.yaml
- cluster/argocd/non-prod/apps/cert-manager/{{valuesFile}}

**Comment by agaudreault** [comment]
@rmehta2974 Can you edit your issue and format it with [markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) ? I think this will help understand your issue with more clarity.

**Comment by rmehta2974** [comment]
Thank you , I found the problem, for some reason, I had added git repo with a particular project. So, even if all the project allowed source repo *, it would not accept the repo , as repo itself was configured for default project

Deleted repo and recreated with  project field =null

**Comment by bitsnacker** [comment]
@rmehta2974 thanks, that worked for me!
