### ISSUE TITLE
Improved docs for security set-up

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1866]
**Is your feature request related to a problem? Please describe.**

Users regularly ask questions about RBAC, SSO and general authn and authz issues. It would be good if the docs helped more.

**Describe the solution you'd like**

Some make it easier to understand.

**Comment by stgarf** [comment]
Argo has been mostly a breeze but because of the myriad SSO providers the exact setup required is quite obtuse to get right for everyone.
I have been tinkering with Okta SAML and OIDc logins and if I get either/ both of them working I'll definitely open a PR.
