### ISSUE TITLE
Unable to install fresh on OKD 4.15

### ISSUE THREAD

**Issue by EdwardCooke** [argoproj/argo-cd#18696]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I'm unable to apply the `manifest/install.yaml` file to a brand new OKD 4.15 cluster.

The redis deployment doesn't meet the default security context constraint requirements in OKD

**To Reproduce**

Login to cluster as admin user (kubeadmin)
Execute the following
```
kubectl create ns argocd
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.3/manifests/install.yaml
```

**Expected behavior**

It would apply and start

**Version**

```shell
4.11.3
```

**Logs**
From `kubectl get pods`
```
NAME                                               READY   STATUS                       RESTARTS      AGE
argocd-application-controller-0                    0/1     CreateContainerConfigError   0             28s
argocd-applicationset-controller-65bb5ff89-gdckq   1/1     Running                      0             28s
argocd-dex-server-6f898cbd9-2f9fr                  0/1     Error                        2 (24s ago)   28s
argocd-notifications-controller-64bc7c9f7-8m7bs    1/1     Running                      0             28s
argocd-repo-server-74d5f58dc5-4wqh4                0/1     CreateContainerConfigError   0             28s
argocd-server-5b86767ddb-b7475                     0/1     CreateContainerConfigError   0             28s
```

From `kubectl get deployments`
```
NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
argocd-applicationset-controller   1/1     1            1           4m25s
argocd-dex-server                  0/1     1            0           4m25s
argocd-notifications-controller    1/1     1            1           4m25s
argocd-redis                       0/1     0            0           4m25s
argocd-repo-server                 0/1     1            0           4m25s
argocd-server                      0/1     1            0           4m25s
```

From `kubectl describe replicasets.apps argocd-redis-5df55f45b7`
```
Name:           argocd-redis-5df55f45b7
Namespace:      argocd
Selector:       app.kubernetes.io/name=argocd-redis,pod-template-hash=5df55f45b7
Labels:         app.kubernetes.io/name=argocd-redis
                pod-template-hash=5df55f45b7
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 2
                deployment.kubernetes.io/revision: 1
Controlled By:  Deployment/argocd-redis
Replicas:       0 current / 1 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/name=argocd-redis
                    pod-template-hash=5df55f45b7
  Service Account:  argocd-redis
  Init Containers:
   secret-init:
    Image:           quay.io/argoproj/argocd:v2.11.3
    Port:            <none>
    Host Port:       <none>
    SeccompProfile:  RuntimeDefault
    Command:
      argocd
      admin
      redis-initial-password
    Environment:  <none>
    Mounts:       <none>
  Containers:
   redis:
    Image:      redis:7.0.14-alpine
    Port:       6379/TCP
    Host Port:  0/TCP
    Args:
      --save

      --appendonly
      no
      --requirepass $(REDIS_PASSWORD)
    Environment:
      REDIS_PASSWORD:  <set to the key 'auth' in secret 'argocd-redis'>  Optional: false
    Mounts:            <none>
  Volumes:             <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                From                   Message
  ----     ------        ----               ----                   -------
  Warning  FailedCreate  8s (x14 over 49s)  replicaset-controller  Error creating: pods "argocd-redis-5df55f45b7-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .initContainers[0].runAsUser: Invalid value: 999: must be in the ranges: [1000790000, 1000799999], provider restricted-v2: .containers[0].runAsUser: Invalid value: 999: must be in the ranges: [1000790000, 1000799999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
```

**Comment by christianh814** [comment]
I believe the "Red Hat" way to install Argo CD is to use the [Argo CD Operator](https://argocd-operator.readthedocs.io/en/latest/install/olm/#operator-install)

But I'll let @ishitasequeira @jannfis or @sabre1041 take a look in case they have a workaround.

**Comment by sabre1041** [comment]
@christianh814 @EdwardCooke A couple areas to unpack here

1. @EdwardCooke The issue that you are facing is that OpenShift's default security posture does not allow the use of fixed UID's which aligns to the failures that you are seeing
2. The Argo CD Operator, as @christianh814 has the best supportability for an OpenShift/OKD perspective. However, most of the available Argo CD installation methods can be used to install on OpenShift (with some considerations in mind). For example, Kustomize can be used in combination with the raw manifests or the [Helm chart](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/) to customize the resources for deployment on OpenShift
3. It is challenging for any project with the adoption that Argo CD has attained to have a fully compatible deployment on every platform and operating environment. OpenShift is just one example. But other environments might make use of policies that inhibit the use of Argo CD (such as Validating/Mutating Webhooks). @EdwardCooke If there is a hard requirement of the Redis image to use a fixed UID, you could look to leverage an alternative source with better support for randomized UID's as OpenShift's default security expects

**Comment by agaudreault** [comment]
Closing as this is a provider platform specific issue. If you need to change the default manifest of ArgoCD to conform to your cluster/provider restrictions, you can use Kustomize or Helm to configure the default manifest, then deploy them.

You can see a basic example of an ArgoCD deployment with Kustomize here [argoproj/argoproj-deployments@HEAD/argocd](https://github.com/argoproj/argoproj-deployments/tree/HEAD/argocd?rgh-link-date=2024-06-21T21%3A40%3A43Z) or you can take a look at the helm chart here [argoproj/argo-helm@main/charts/argo-cd](https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd?rgh-link-date=2024-06-21T21%3A40%3A43Z)
