### ISSUE TITLE
Containers in pods with native sidecars don't show as "ready"

### ISSUE THREAD

**Issue by adamwilner** [argoproj/argo-cd#18725]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
In the tree view, pods with one or more [native sidecars](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/) show all containers as not ready i.e. 0/2, even if they are. 

**To Reproduce**
Define a Deployment with at least one container set up as a [native sidecar](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/) and sync. When synced none of the containers in any of the resulting pods will appear ready.

**Expected behavior**
Pods in the tree view would show that containers are ready if they are.

**Screenshots**

Argocd
<img width="375" alt="image" src="https://github.com/argoproj/argo-cd/assets/68298326/bc105765-6c31-4a11-a6da-688187bfc2d0">

Kubectl
<img width="816" alt="image" src="https://github.com/argoproj/argo-cd/assets/68298326/5a16482e-34f8-49dd-8a32-04b1cf05f236">

**Version**

```shell
v2.11.3+3f344d5
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by booleanbetrayal** [comment]
Would love to have native sidecar support working in ArgoCD as that K8s feature would simplify a few things in our manifests. Wouldn't mind trying a stab at contributing either, but not sure the best place to start looking into this. Is this downstream of some healthcheck code, etc?

**Comment by Hronom** [comment]
Pretty important thing if you use popular service meshes like Istio. Otherwise it display wrong information.

**Comment by linghaoSu** [comment]
could I take this?

**Comment by alexef** [comment]
go for it. here is the corresponding similar issue in Kubernetes Dashboard (with attached PR): https://github.com/kubernetes/dashboard/issues/9299
checking where in ArgoCD code we have a similar logic

**Comment by alexef** [comment]
this is actually here: https://github.com/argoproj/argo-cd/blob/master/controller/cache/info.go#L310 @linghaoSu let me know if you need help with the PR

**Comment by blevz** [comment]
Any updates on this?  We are getting bitten pretty badly by this
