### ISSUE TITLE
Expose ArgoCD version in metrics

### ISSUE THREAD

**Issue by Pionerd** [argoproj/argo-cd#18731]
# Summary

Expose the ArgoCD version in the metrics endpoint.

# Motivation

We would like to show the version of ArgoCD of different clusters in Grafana dashboards. Currently only the used Go version is exposed (`go_info{version="go1.21.9"} 1`), we would love to see something similar for the ArgoCD version.

# Proposal

Proposed metric:
`argocd_info{version="v2.11.3"} 1`

**Comment by omerap12** [comment]
I can take this on 💪
