### ISSUE TITLE
Dark Mode: Collapsed sections color is white

### ISSUE THREAD

**Issue by Sayrus** [argoproj/argo-cd#18742]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When a property in the summary overflows, the section is collapsed by default. The white color is hardcoded [here](https://github.com/argoproj/argo-cd/blob/1aeed6a6b19cbb7cdbfbce7fda69f54944e45603/ui/src/app/shared/components/expandable/expandable.scss#L16).

On the white theme, there is no gradient overflow indicator and only the arrow is used.

**To Reproduce**

1. Any component with several annotations will show a collapsed section.
2. Open the component summary

**Expected behavior**

Either:
1. Gradient fades to dark gray rather than white
2. No gradient (But that may impact other components who rely on the white gradient)

Using `light-argo-gray-2` gives the following:
![image](https://github.com/argoproj/argo-cd/assets/22404472/f3e69a3f-829f-4fcf-9bb8-e06ff30f63d6)
![image](https://github.com/argoproj/argo-cd/assets/22404472/9f5e9288-eba7-401a-8b28-e4705ac0bcb2)

Disabling the gradient gives the following:
![image](https://github.com/argoproj/argo-cd/assets/22404472/9acaa6b1-b352-4140-ab09-07b924408ec2)

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/22404472/22003f98-c6ee-4c71-97dd-b69112234c3c)
![image](https://github.com/argoproj/argo-cd/assets/22404472/a804eb28-cb99-41ac-9f36-3ebe54f23826)

**Version**

```shell
argocd-server: v2.10.9+c071af8
  BuildDate: 2024-04-30T15:53:28Z
  GitCommit: c071af808170bfc39cbdf6b9be4d0212dd66db0c
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.3+gf03cc04
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**

N/A

**Comment by surajyadav1108** [comment]
I would say to keep the gradient as white but increase the gray percentage 

<img width="514" alt="Screenshot 2024-06-21 103720" src="https://github.com/argoproj/argo-cd/assets/91555602/0c8c5bc6-7768-40ad-900f-b938335601ee">

wdyt @Sayrus

**Comment by shijiadong2022** [comment]
I'd like to work on this one.

**Comment by shijiadong2022** [comment]
@surajyadav1108 can you share the reason to keep the gradient as white? It looks still not a clean UI with the change. Any concerns if we remove the gradient background for both light and dark theme?

**Comment by surajyadav1108** [comment]
> @surajyadav1108 can you share the reason to keep the gradient as white? It looks still not a clean UI with the change. Any concerns if we remove the gradient background for both light and dark theme?

It is a highlight for the dropdown, and since it is a shared component, removing it might not be ideal. However, if you prefer it removed, then please do so specifically for this part

**Comment by shijiadong2022** [comment]
Thanks. I will keep the gradient as white as it is a shared component.
