### ISSUE TITLE
how to fix?

### ISSUE THREAD

**Issue by DOLONG9** [argoproj/argo-cd#18753]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by agaudreault** [comment]
Closing due to missing details. Feel free to add details and re-open.
