### ISSUE TITLE
GUI not parsing map values properly

### ISSUE THREAD

**Issue by RGPosadas** [argoproj/argo-cd#1877]
**Describe the bug**
Mappings are not being parsed properly when taken from the GUI.

**Example**
Say we have this yaml file, and I want to modify the hostname:
```
app-name:
  ingress:
    hosts:
    - name: example.com
      path: /
```

The way to edit this through the ArgoCD CLI is:
`argocd app set app-name -p app-name.ingress.hosts[0].name=new-example.com`

However that is not currently possible using the ArgoCD GUI.
Modifying the parameters from `[map[name:example.com path:/]]` (which was generated by ArgoCD) to `[map[name:new-example.com path:/]]` results in
```
rpc error: code = Unknown desc = Error: render error
range can't iterate over `[map[name:new-example.com path:/]]`
```
Not modifying that specific parameter runs well. Only when it is modified does it give that error.

**Comment by alexec** [comment]
Not sure this is the correct way to use this command, example would be

```
  -p, --parameter stringArray             set a parameter override (e.g. -p guestbook=image=example/guestbook:latest)
```

**Comment by RGPosadas** [comment]
The CLI command works fine, the equivalent way to do it through the GUI does not work however, and gives the error stated above

**Comment by alexec** [comment]
ah - I get it. Good one for community contribution.
