### ISSUE TITLE
ApplicationSet controller fail with v1alpha1.AppProject: appprojects.argoproj.io is forbidden error

### ISSUE THREAD

**Issue by pasha-codefresh** [argoproj/argo-cd#18829]
Error: W0626 15:42:39.415329       7 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.6/tools/cache/reflector.go:229: failed to list *v1alpha1.AppProject: appprojects.argoproj.io is forbidden: User "system:serviceaccount:argocd:argocd-applicationset-controller" cannot list resource "appprojects" in API group "argoproj.io" in the namespace "argocd"

Version is: v2.13.0+dafb37c

**Comment by T1-leiyang** [comment]
need to add list verbs for appprojects to the Role or ClusterRole of the argocd-applicationset-controller, and so far there are only get

**Comment by pasha-codefresh** [comment]
I probably will close this one, as long as it repro only in one environment, and it is working fine locally and on other cluster

**Comment by jsolana** [comment]
I can reproduce the same issue with [this example](https://github.com/jsolana/argocd-applications/tree/master)

Im using:

- kind version 0.22.0
- Argocd 2.12.0-rc2
- Kubernetes: Client Version: v1.29.2,  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3, Server Version: v1.29.2

To reproduce the issue:

```console
kind create cluster
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.0-rc2/manifests/install.yaml

# cloning https://github.com/jsolana/argocd-applications.git
# cd argocd-applications

kubectl apply -f manifests/hello-applicationset.yml
```

**Comment by jsolana** [comment]
Super thanks!
