### ISSUE TITLE
Possible race condition with Kustomize, cron jobs and config maps

### ISSUE THREAD

**Issue by nickjj** [argoproj/argo-cd#18837]
**Describe the bug**

I've noticed that about 10% of our app deployments end up with an outcome where we have a cron job that gets stuck due to `"configmap not found"` with an error of `CreateContainerCconfigError`. The solution for now is to delete the job that gets spawned by Kubernetes which then kicks off a new job with the correct config map.

I'm not 100% on the root cause but I believe it's related to this:

- I'm using Kustomize which generates uniquely named config maps such as `myapp-abc123`
- The Argo CD app is configured to sync with `prune: true` as well as `PruneLast=true`
- We deploy our app which ends up having a config map named something like `myapp-abc123`
- We have cron jobs running at various intervals, one of which runs for ~15min many times per day
- If we deploy our app while that cron job is either scheduled to be run or maybe running, we end up with a new config map of let's say `myapp-xyz123`
- Argo CD syncs everything and prunes everything that's old, including `myapp-abc123`
- The cron job spawns a new job with `myapp-abc123` and that doesn't exist anymore so we get the error

**Expected behavior**

The cron job gets updated to spawn jobs with the new config map so this error doesn't happen.

**Version**

I'm opening this issue on a different device from where I ran the version command, but this has been happening with many different versions since I started using Argo CD. I'm currently running Argo CD `v2.10.5` with Kustomize `v5.2.1`.

**Logs**

Beyond the error messages posted above, Kubernetes does throw `TooManyMissedTimes` error events on the cron job which makes sense since the job fails in a loop until we delete it.

**Workarounds**

- Take a human action and manually delete the job
- Maybe annotate the config map to not get pruned but then we're going to end up with dozens or even hundreds of old config maps that we would need to clean up by hand?
  - Is there a way to limit this to let's say keep the last 5 or 10 config maps and prune them?
  - This also doesn't seem ideal because if the old config map gets loaded it might have stale values (we use this config map to store non-secret environment variables)

What would need to be configured or adjusted to fix this in a bullet proof way? Thanks.

**Comment by christianh814** [comment]
@nickjj Are you using a Pre or Post sync hook for the CronJob or is it part of the normal Sync?

**Comment by nickjj** [comment]
It's part of a normal sync.

**Comment by nickjj** [comment]
It may be worth pointing out the config map has a sync-wave value of -30. I wanted to make sure the config map gets updated before everything else since other resources (jobs, deployments, etc.) depend on it. After that SealedSecrets has -20 and everything else has the default value.

**Comment by crenshaw-dev** [comment]
> The cron job spawns a new job with myapp-abc123 and that doesn't exist anymore so we get the error

How is it possible for the CronJob to still reference `myapp-abc123` instead of the new `myapp-xyz123`? Is there that large a time gap between the sync waves so that a new Job is triggered based on the not-yet-synced CronJob?

**Comment by nickjj** [comment]
> How is it possible for the CronJob to still reference myapp-abc123 instead of the new myapp-xyz123?

I'm not sure how it's possible. Maybe it has to do with how it's scheduled? We have around 12 cron jobs and this one cron job is the only one where this happens but it's configured the same way as the others. The only difference is this cron job happens to run for ~15 minutes and runs every 30 minutes. 

The time gap is quite small. It usually takes 1-3 second to progress to the point where new pods based on deployments and jobs are coming up.

**Comment by crenshaw-dev** [comment]
How does the CronJob reference the ConfigMap?

**Comment by nickjj** [comment]
In the same way as the deployment and other jobs:

```yaml
envFrom:
- configMapRef
    name: "hello-world-app"
```

In this case the config map is just a new line separated list of environment variables.

In the `kustomization.yaml` for each app I use this:

```yaml
configMapGenerator:
- behavior: "merge"
  envs:
  - ".env"
  name: "hello-world-app"
```

**Comment by crenshaw-dev** [comment]
So Kustomize is responsible for making sure the generated names match.

I think we need a clearer picture of the exact scenario that's producing the mismatch between the Job spec and the existing ConfigMap. Argo CD's responsibility ends at applying the specified manifests. The conditions which produce the mismatch are what we need to understand and resolve.

**Comment by nickjj** [comment]
Here's a few screenshots in order of when it happened recently. Sorry for the small font size on some of them. Let's just say Outlook and OneDrive are bad and resized them when I emailed them from work to my personal machine. Fortunately the text is still readable (barely).

But this demonstrates how the `CronJob` references the new config map ID but both the `Job` and `Pod` it spawned do not.

The new deployment has a new config map suffix starting with `-gcd` where as the old deployment was `-962`.

The only things I've partially redacted are names of certain resources since it would show my employer's company name and some of the things we're doing based on the cron job name.

#### ConfigMap: new

![00-config-map-new](https://github.com/argoproj/argo-cd/assets/813219/65302828-0b60-4467-9c02-cf5ee95c85fe)

#### Pod: config map error

![01-pod-config-map-error](https://github.com/argoproj/argo-cd/assets/813219/58438329-0e5f-4471-afb8-291746a367c9)

#### Pod: summary error

![02-pod-summary-error](https://github.com/argoproj/argo-cd/assets/813219/e2250f82-ea3c-4cce-9426-5d4b33e08d9b)

#### Pod: events error

![03-pod-events-error](https://github.com/argoproj/argo-cd/assets/813219/ed112cbb-4ae0-4dfc-b73f-2486d949e580)

#### CronJob: manifest

![04-cronjob-manifest](https://github.com/argoproj/argo-cd/assets/813219/5e253a1f-594b-47d9-9fec-63d0c778ae68)

#### Job: manifest

![05-job-manifest](https://github.com/argoproj/argo-cd/assets/813219/7be8959f-ee27-4055-ba70-b0bbce6918a6)

#### Job: stuck progessing due to failing pod

![06-job-stuck-progressing-due-to-failing-pod](https://github.com/argoproj/argo-cd/assets/813219/0f8688ad-3e65-4860-b775-7fe393d2b45f)

#### Pod: manifest

![07-pod-manifest](https://github.com/argoproj/argo-cd/assets/813219/4fa67068-bafc-4770-8bec-ec272bca534d)

**Comment by crenshaw-dev** [comment]
The system as designed is stateful. The ConfigMap, because of the randomized name, is effectively ephemeral. So the Job (which may persist after the ephemeral ConfigMap is deleted) depends on state which may change.

You'll need to either make the Job not depend on the ephemeral resource, or build something to clean up the problematic Jobs.

Is it actually necessary to use a generated name for the ConfigMap? Could the name instead be static?

**Comment by nickjj** [comment]
The job requires the config map because it spawns a pod with environment variables that are necessary for the workload to be completed.

The generated config map name was helpful for letting Kubernetes its values were changed. For example if we changed an environment variable and pushed that, Argo CD picks up the change and any new resources that reference it automatically got re-deployed. If we use a static name, from what I remember that re-deployment doesn't occur automatically because Kubernetes doesn't know it changed.

Any suggestions on an event based automated way to auto-delete failing jobs?

**Comment by nickjj** [comment]
#13642 was a suggestion to allow for static configs and have auto-rollouts but it got closed with a recommendation to use a third party tool. This feels like a pretty common use case to have a cron job that references a config map. Any possibility of this issue being investigated again?

I actually use the checksum approach for secrets because we have a custom CLI tool to interact with the secrets which updates the checksum values as needed but the ConfigMap story is much different because it's just a plain text file on disk that exists in the repo. Ideally you'd want to update that file, commit and push it. Having a developer have to go in and update a dozen checksum annotations wouldn't be a good outcome IMO.

**Comment by crenshaw-dev** [comment]
Do you need already-running Jobs to pick up the new config, or just new Jobs spawned by the CronJob after syncing?

If the latter, you should be able to use a static ConfigMap name. New Jobs will pick up the newly-synced ConfigMap as soon as they're spawned.

**Comment by nickjj** [comment]
The same config map used by the cron jobs is used by our main deployment which is a web app. In our case it's kind of related.

I suppose the outcome I'm looking for is it to work in a way where it doesn't get itself into a failure state. If a cron job triggered a job which triggered a pod and it's currently running, I'm not sure why deploying a new version of our app will cause the pod to fail with the config map error when it's already running with the old one.

In theory shouldn't the pod that's already being running have everything it needs to continue running even if the old config map got pruned by Argo CD?

**Comment by crenshaw-dev** [comment]
> The same config map used by the cron jobs is used by our main deployment which is a web app.

I'd recommend using something like Reloader for the Deployment. Or you could split the config into two ConfigMaps: one with name randomization to trigger the Deployment restart, and the other without name randomization for the CronJob to use.

Right now, you have two resources with very different runtime behavior depending on the same ConfigMap. In one case, an ephemeral ConfigMap is fine (and even preferable if you want a quick-and-easy restart mechanism), and in the other case, an ephemeral ConfigMap is unacceptable because stateful resources (Jobs) depend on the ConfigMap persisting.

> I'm not sure why deploying a new version of our app will cause the pod to fail with the config map error when it's already running with the old one.
> 
> In theory shouldn't the pod that's already running have everything it needs to continue running even if the old config map got pruned by Argo CD?

Because the Job doesn't load the ConfigMap, the Pod does. If the Job needs to retry for some reason, it will spawn a new Pod, and the Pod will not be able to load the now-deleted ephemeral ConfigMap.

You'd hit the same problem if a a new Pod belonging to an old RepliaSet depended on an ephemeral ConfigMap. Imagine you deploy a new image, and the Deployment spins up a new ReplicaSet which fails with an ImagePullBackoff. If a Pod belonging to the old ReplicaSet were evicted, a new one would be spun up, and the new Pod would fail to load the now-deleted ephemeral Pod.

Randomized ConfigMap names is just a bad way to force workload restarts. Other tools exist because a more elegant solution is actually necessary.

**Comment by nickjj** [comment]
> If the Job needs to retry for some reason, it will spawn a new Pod, and the Pod will not be able to load the now-deleted ephemeral ConfigMap.

That's the interesting part. The job didn't need to retry, it was happily running before the new deployment.

> I'd recommend using something like Reloader for the Deployment.

Thanks. I'll check into this and only have it enabled for the deployment.

**Comment by crenshaw-dev** [comment]
> The job didn't need to retry, it was happily running before the new deployment.

That is weird. The Pod events don't make sense to me. Why was the image pulled so many times? And why was it so long from the initial pull attempt until the first successful pull? Was the referenced ConfigMap deleted in that ~10min window?

**Comment by nickjj** [comment]
It's hard to say why it was pulled that much. Maybe each time K8s re-tried, it re-pulled? Right now a job is running successfully and the pod shows 1 pull with 1 container start. This job pretty much never fails, it runs a lot to pickup new work.

Initial pull vs successful pull is likely due to it being in a stuck state for a while. After I took all of the screenshots I manually deleted the job which fixed everything. I didn't manually delete the ConfigMap, Argo CD must have pruned it after the app was synced successfully.

**Comment by crenshaw-dev** [comment]
It's also odd that they're are more container failure events than ConfigMap error events. I wonder if there was an initial failure after the image was finally pulled and if the container restart triggered the ConfigMap reload which failed due to the ConfigMap having been pruned. 

It's difficult to reconstruct the events. But either way, it's dangerous to leave dangling references to an ephemeral resource.

**Comment by nickjj** [comment]
Is there anything at the K8s level that would trigger the job / pod to restart even if it didn't fail?

**Comment by crenshaw-dev** [comment]
Nothing I can think of off-hand... but glancing at the Job spec in the screenshot, I realize it's got a lot of functionality I've never used.

**Comment by crenshaw-dev** [comment]
I do think the 10min gap between first pull and run is plenty of time to trigger the race condition, even without a container restart.

**Comment by nickjj** [comment]
Most of the options are the default. I've set `ConcurrencyPolicy: "forbid"` on the `CronJob` and the `Job` only has a backoff of 3 and to restart on failure, the rests are default.

We've never had this fail other than during a deployment, for like 2 years.

I'm not sure what would cause the 10min gap where between first pull and first run. The image being pulled is the official curl image. We have other cron jobs using the same image and they finish in a few seconds end to end.

**Comment by crenshaw-dev** [comment]
With the 3 retries configured, it's possible the container fails sometimes,  but has never exceed the 3 retry threshold.

A failed run/failure/retry isn't the only thing that may introduce sufficient time to trigger the race condition. The slow pull is another. Basically anything that adds time between "reference broken by resource prune" to "failed use of dangling reference" can trigger the race condition. 

I'm going to go ahead and close the issue since Argo CD is behaving correctly. Eliminating the possibility of dangling references is outside the scope of Argo's purpose, which is to apply declarative config. Occasional failures are an inherent part of a declarative, eventually-consistent system. If the failures caused by dangling references to the ephemeral ConfigMap are unacceptable, then you'll need to rework how that config is referenced to make thebdangling reference less likely. 

Happy to keep brainstorming here, just closing for bookkeeping purposes.

**Comment by nickjj** [comment]
Thanks. I may just configure Argo CD not to prune the config maps and have a mental note to clean them up every quarter. That would at least bypass needing to run another tool (Reloader) in our cluster and be responsible for its configuration and updates.

**Comment by crenshaw-dev** [comment]
Yeah, that's probably easiest. And I bet there are generic ttl controllers that can clean them up for you and avoid the memory item.

**Comment by nickjj** [comment]
You mean something like this, https://github.com/TwiN/k8s-ttl-controller? Looks like 1 more thing to install and configure tho.

I wonder how much memory will be used if ~50-75 old config maps were sitting around. Most of them have about 10kb of data. Do you know offhand if they all sit in memory somewhere?

**Comment by crenshaw-dev** [comment]
Yep, exactly like that. Indeed, another thing to maintain. 

They'll all sit around in etcd. 50 ConfigMaps should be no big deal. The most annoying part will be your app being forever OutOfSync.

**Comment by nickjj** [comment]
Hmm, I didn't know it would be forever OutOfSync.

I was going to follow this comment's first code block: https://github.com/argoproj/argo-cd/issues/1629#issuecomment-499253376

It looks like there's also https://github.com/argoproj/argo-cd/issues/1636 which is open but for almost 5 years.

**Comment by crenshaw-dev** [comment]
Ah that's a good idea.

Not sure I love #1636, we'd have to be in the business of understanding every way in which one resource can reference another resource. Seems like a lot of work for low value, and fairly risky.

**Comment by tri-bao** [comment]
@nickjj did you solve this issue somehow? We have the same problem as yours

**Comment by nickjj** [comment]
Nope, none of the solutions seemed ideal. Having things out of sync or using unofficial 3rd party tools wasn't worth the trade off.
