### ISSUE TITLE
CronJob "Create Job" may render too long Job names

### ISSUE THREAD

**Issue by reiniertimmer** [argoproj/argo-cd#18846]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When starting a Job from a CronJob in the ArgoCD UI, the Job is created by appending the date string `%Y%m%d%H%M` to the CronJob `.metadata.name`.

(See https://github.com/argoproj/argo-cd/blob/master/resource_customizations/batch/CronJob/actions/create-job/action.lua#L39)

This adds **13** characters to the `CronJob` name to create the `Job` object. However, according to the Kubernetes [CronJob spec](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/), when Kubernetes creates a `Job` from a `CronJob`, it will only add **11** characters, so the `CronJob` can be up until **52** characters long.

When creating a `Job` through ArgoCD UI "Create Job" option will produce the following error:

```
Unable to execute resource action: Job.batch "***-202406281143" is invalid: [metadata.labels: Invalid value: "***-202406281143": must be no more than 63 characters, spec.template.labels: Invalid value: "***-202406281143": must be no more than 63 characters]
```

Which makes sense, when the `CronJob` is 52 characters long, ArgoCD will create a `Job` with a name of 65 characters long, which will produce the above error.

**To Reproduce**

* Create an Application in ArgoCD that creates a `CronJob`, with a name of length 51-52
* Manually create a Job from that CronJob using the UI

![image](https://github.com/argoproj/argo-cd/assets/7985301/1da6f544-97b7-4da7-afe1-943ae072da2a)

This will show the above error.

**Expected behavior**

A Job will be started from the CronJob immediately with a correct name.

**Recommendations**

Replacing `%Y` (4-digit year) in the date format to `%y` (2-digit year), will create a Job with CronJob name +11 characters (which is conveniently _exactly_ within spec).

So, changing:

* `%Y%m%d%H%M` to
* `%y%m%d%H%M`

in the following file: https://github.com/argoproj/argo-cd/blob/master/resource_customizations/batch/CronJob/actions/create-job/action.lua#L39

**Version**

(server version only, commandline not available)

```json
{
    "Version": "v2.11.3+3f344d5",
    "BuildDate": "2024-06-06T08:42:00Z",
    "GitCommit": "3f344d54a4e0bbbb4313e1c19cfe1e544b162598",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.9",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.4+g81c902a",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

**Comment by crenshaw-dev** [comment]
Seems like a safe, reasonable change. Wanna open a PR?

**Comment by crenshaw-dev** [comment]
Since it's kind of an edge case, let's ship it 2.13 and add a release note, just in case people are depending on the current format.

People can always override the action if they need the fix sooner.

**Comment by christianh814** [comment]
I wonder if having the date in the Job "matters"...meaning, what if we switched to a UUID format? Just a thought. But I agree to maybe not change it right away.

**Comment by reiniertimmer** [comment]
> Seems like a safe, reasonable change. Wanna open a PR?

Hi @crenshaw-dev yes, I can make a PR for this
