### ISSUE TITLE
Add `discovery.k8s.io/EndpointSlice` to `ignoredRefreshResources` to skip app requeueing

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [argoproj/argo-cd#18857]
# Summary

Currently `/Endpoints` are skipped when trying to trigger a reconciliation ([link](https://github.com/argoproj/argo-cd/blob/e6a034995cba56cd5c3d10c224b24e2e1c28456c/controller/cache/cache.go#L334-L336)). I think `discovery.k8s.io/EndpointSlice` should be added to the list as well for the same reasons. Also, `skipResourceUpdate` should be done after `skipAppRequeuing` check for optimization.

# Motivation

Do an additional optimization to reduce reconciliations. Other resources like pods would already trigger reconciliations when there are relevant updates.

# Proposal

Just update the dictionary of `ignoredRefreshResources` mentioned above to include the entry for `discovery.k8s.io/EndpointSlice`

**Comment by AnkurManna** [comment]
If approved, I'm willing to provide the PR.

**Comment by AnkurManna** [comment]
Please review https://github.com/argoproj/gitops-engine/pull/596, as only after merging this i will be able to use these changes in argo-cd repo like https://argo-cd.readthedocs.io/en/stable/developer-guide/dependencies/ for the final pr.
