### ISSUE TITLE
waiting for healthy state post sync

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1886]
**Describe the bug**
Synchronization is waiting indefinitely 

![image](https://user-images.githubusercontent.com/9946020/60728239-1e80ed80-9f40-11e9-98a9-402caba591be.png)

**To Reproduce**
If we cannot reproduce, we cannot fix! Steps to reproduce the behavior:

**Expected behavior**
synchronization to finish

**Screenshots**

**Version**
1.0.2

**Logs**

```
Paste any relevant application logs here.
```

**Comment by peterbosalliandercom** [comment]
it seems that sync failes and the synchronization does not come healthy, so this waits indefinitely

**Comment by peterbosalliandercom** [comment]
Maybe a timeout would be needed here.

**Comment by alexec** [comment]
one of the resources did not apply correctly? do you have logs?
