### ISSUE TITLE
Syncwaves at the application level

### ISSUE THREAD

**Issue by jon-walton** [argoproj/argo-cd#1888]
**Is your feature request related to a problem? Please describe.**
We use the "application of applications" approach to deploying our clusters. When we deploy a new cluster, multiple applications are syncing simultaneously. This can cause sync failures due to cross-application dependencies.

For example:

nginx-ingress attempts to create a `kind: ServiceMonitor`, however that kind doesn't exist until prometheus-operator has synced the crd for the `ServiceMonitor`. The nginx-ingress application goes into a failed state and seems to require manual intervention to continue syncing

**Describe the solution you'd like**
Similar to syncwaves, it would be helpful to define an order for initially syncing a group of new applications

**Comment by alexec** [comment]
I think the annotation will work at the application level too.

**Comment by jon-walton** [comment]
I just deployed a new cluster and sync waves worked as expected on application objects. Thanks
