### ISSUE TITLE
Argo Sync Error Log is not showing exact error when YAML manifest is malformatted

### ISSUE THREAD

**Issue by prsrus216** [argoproj/argo-cd#18886]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Argo Sync is failing when there is malformatted  YAML Manifest file, But the Argo Error is not clear on which YAML and which Line is causing the issues, Rather below error shown on Argo UI which is confusing as the Error describes that this is Repo authentication issues which is not true as other apps working fine with same repo credentials. 

Argo Sync Error Log:

ComparisionError: Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = NOAUTH Authentication required.

Error was clearly stating the YAML issues in previous Argo version 2.9.1 and these Error Logging changed after the recent Argo Upgrade to v2.10.9.

**To Reproduce**

1. Update any YAML manifest  file with indentation issues or wrong data type
2. Apply the malformatted YAML file
3. Expect Sync failure and observe the Error message.

**Expected behavior**

Expecting Argo must show the exact YAML format issues on which file/line the syntax issues. 

**Screenshots**

<img width="1053" alt="Screenshot 2024-07-02 at 9 08 09 AM" src="https://github.com/argoproj/argo-cd/assets/152336744/322c2300-5b81-4bf6-838f-931fc54700a7">

**Version**

ArgoCD v2.10.9

**Comment by crenshaw-dev** [comment]
The error you're seeing indicates that the Argo CD repo-server is unable to connect to Redis, because Redis is now configured with password protection. 

I'd recommend restarting your repo-server and doing a hard refresh to re-attempt manifest hydration.

If that fails with the same error message, you'll need to analyze why the REDIS_PASSWORD environment variable on the repo-server isn't being populated.

**Comment by prsrus216** [comment]
Thank You  @crenshaw-dev  for the response. Argo is working fine with Redis and all other 100+ apps synced without any issues with same repo creds. Which ever the apps having some YAML  indentation or value data type issues, Argo is not able to  templating it correctly and hence reporting Authentication error rather showing that YAML syntax issues.

**Comment by crenshaw-dev** [comment]
This is strange for another reason: Redis password protection wasn't enabled until Argo CD 2.10.10.

How are you installing Argo CD?

Can you post the output of this?

```shell
kubectl get deployment argocd-redis -oyaml | yq '.spec'
```

**Comment by prsrus216** [comment]
I have reverted the ArgoCD to v2.9.2 which was my previous stable version which is now printing the error log correctly in the UI when YAML/parameter value issues are there. 

I can upgrade the Argo to v2.10.9 again and can update the redis manifest config here.

**Comment by crenshaw-dev** [comment]
I'm unable to reproduce the bug in 2.10.9.

![image](https://github.com/argoproj/argo-cd/assets/350466/0432d2ba-47de-47b6-91f4-8a717c37b296)


```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "18886"
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: "18886"
    repoURL: https://github.com/crenshaw-dev/argocd-example-apps
    targetRevision: HEAD
```

**Comment by prsrus216** [comment]
I have tried capturing the error log in both versions. I have configured Redis in HA running with 2 replicas behind HA proxy.

Argo v2.9.2:

Here is the Argo Error in v2.9.2 when the required YAML is not found.
<img width="1318" alt="Screenshot 2024-07-02 at 4 14 58 PM" src="https://github.com/argoproj/argo-cd/assets/152336744/7f450fbd-c6ec-4e3a-a02d-3866179c7d42">

Now, i have upgraded to v2.10.9 and I see the below error log for the same app.
<img width="1318" alt="Screenshot 2024-07-02 at 4 25 20 PM" src="https://github.com/argoproj/argo-cd/assets/152336744/3ea58084-566e-4e37-a159-16a59bf36abb">

Few other screenshots from another app which is showing the same error in AppConditions

Sync Error is showing fine this time but the AppCondition still showing like Authentication issues:

<img width="1318" alt="Screenshot 2024-07-02 at 4 24 24 PM" src="https://github.com/argoproj/argo-cd/assets/152336744/3cb99415-e537-475e-9633-a5e8da90f853">
<img width="1324" alt="Screenshot 2024-07-02 at 4 32 50 PM" src="https://github.com/argoproj/argo-cd/assets/152336744/082aad26-29c6-4915-a7fe-a61b1622e32b">

Below screenshot shows that all other 800+ apps synced fine.
<img width="151" alt="Screenshot 2024-07-02 at 4 30 53 PM" src="https://github.com/argoproj/argo-cd/assets/152336744/fa654a9c-73f3-4f5c-9885-ff700f12ef17">

**Comment by prsrus216** [comment]
@crenshaw-dev Thank You for the explanation and details. I have now upgraded to v2.11.4 and that got fixed the issues.
