### ISSUE TITLE
appset: Error `informer is not a kubernetes informer` when controller generate applications

### ISSUE THREAD

**Issue by dacofr** [argoproj/argo-cd#18905]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I think that a regression as been introduced since `2.11.3`. Now, when I run locally the appset controller, each time an application is created/updated I got this message : `informer is not a kubernetes informer` coming from [updateCache](https://github.com/argoproj/argo-cd/blob/master/applicationset/controllers/applicationset_controller.go#L552)

```
func (r *ApplicationSetReconciler) updateCache(ctx context.Context, obj client.Object, logger *log.Entry) {
	informer, err := r.Cache.GetInformer(ctx, obj)
	if err != nil {
		logger.Errorf("failed to get informer: %v", err)
		return
	}
	// The controller runtime abstract away informers creation
	// so unfortunately could not find any other way to access informer store.
	k8sInformer, ok := informer.(k8scache.SharedInformer)
	if !ok {
		logger.Error("informer is not a kubernetes informer")
		return
	}
	if err := k8sInformer.GetStore().Update(obj); err != nil {
		logger.Errorf("failed to update cache: %v", err)
		return
	}
}
```

I haven't knowledge with controller-runtime, but when I run locally on master branch vs commit in 2.11.2, I see that something change in cache implementation : `multiNamespaceCache` vs `informerCache`. Maybe a clue #17491 .

**To Reproduce**

- Create an AppSet, example https://github.com/dacofr/hello-appset/blob/main/appset.yaml 
- Watch logs

If you continue by updating appset spec, each time an application is created or updated, we have an error.

**Expected behavior**

No error log !

**Version**

Running locally based on this commit : b96be4c5e4b44d684182444bc403936ff8505470

**Logs**

```
INFO[0029] generated 3 applications                      applicationset=argocd/hello-appset generator="{&ListGenerator{Elements:[]JSON{{[123 34 110 97 109 101 115 112 97 99 101 34 58 34 100 101 118 34 125]},{[123 34 110 97 109 101 115 112 97 99 101 34 58 34 115 116 103 34 125]},{[123 34 110 97 109 101 115 112 97 99 101 34 58 34 112 114 100 34 125]},},Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},ElementsYaml:,} nil nil nil nil nil nil nil nil nil}"
ERRO[0029] informer is not a kubernetes informer         app=argocd/dev applicationset=argocd/hello-appset
INFO[0029] created Application                           app=argocd/dev applicationset=argocd/hello-appset
ERRO[0029] informer is not a kubernetes informer         app=argocd/stg applicationset=argocd/hello-appset
INFO[0029] created Application                           app=argocd/stg applicationset=argocd/hello-appset
ERRO[0029] informer is not a kubernetes informer         app=argocd/prd applicationset=argocd/hello-appset
INFO[0029] created Application                           app=argocd/prd applicationset=argocd/hello-appset
INFO[0029] end reconcile                                 applicationset=argocd/hello-appset requeueAfter=0s
INFO[0029] generated 3 applications                      applicationset=argocd/hello-appset generator="{&ListGenerator{Elements:[]JSON{{[123 34 110 97 109 
```

**Comment by uthark** [comment]
I'm observing this error after upgrading to 2.12.0 from 2.11.7.

**Comment by tbronchain** [comment]
I can confirm the issue happens on 2.12.0, but resolved after downgrading to 2.11.7, on multiple argo deploments.

**Comment by Supporterino** [comment]
Same here 2.12.0 introduces the error and reverting to 2.11.7 removes the error message and the thus related high load of the container

**Comment by bhvishal9** [comment]
Observing the same issue as soon as I upgraded to 2.12.0.

**Comment by Alwinius** [comment]
Same for us, but we cannot downgrade because 2.12.0 fixes some major issues we had in Kubernetes 1.30

**Comment by crenshaw-dev** [comment]
Thanks for the confirmations, all! If you're affected, please thumbs-up the issue. If you have additional details about the issue, please comment.

**Comment by nobbs** [comment]
Still happening in v2.12.1.
