### ISSUE TITLE
Add more logs and/or duration fields to existing logs to give more visibility into slow reconciliations

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [argoproj/argo-cd#18923]
# Summary

There's some logging for different steps taken during reconciliation, as well as some duration fields on "Reconciliation completed" log entries. However, they aren't enough to tell where the slowness may be coming from.

# Motivation

Sometimes reconciliation takes 30+ min and it's unclear why. Logs don't give enough info.
<img width="1259" alt="Screenshot 2024-07-03 at 11 38 01 AM" src="https://github.com/argoproj/argo-cd/assets/137232734/05d8c370-943d-4d47-b265-eaa4b965bd74">
<img width="409" alt="Screenshot 2024-07-03 at 11 38 22 AM" src="https://github.com/argoproj/argo-cd/assets/137232734/3f7d89f8-c3a8-43e0-83c4-c0a182f14211">

# Proposal

Add more log entries through different steps of reconciliation and/or add more timing/duration information to "Reconciliation completed".

**Comment by crenshaw-dev** [comment]
Very strongly in favor of this. We also need documentation about these different metrics.

**Comment by andrii-korotkov-verkada** [comment]
@crenshaw-dev, I've sent a PR. There are a lot of metrics being added though and I've followed function names to name most of those. What's the best way to write a documentation for these? Should it be oriented at people who'd read the controller code, or should it also appeal to people who won't?

**Comment by andrii-korotkov-verkada** [comment]
Already discovered slowness/optimization opportunity! https://github.com/argoproj/argo-cd/issues/18929
