### ISSUE TITLE
Intermittent status code 429 when using AWS CodeCommit repositories

### ISSUE THREAD

**Issue by essh** [argoproj/argo-cd#1895]
**Describe the bug**
I'm seeing intermittent `status code: 429` errors in the repository server logs (example in the logs section below) when using AWS CodeCommit repositories. When this happens the web ui will show "Unknown" with a spinner in the sync status field until it corrects itself again in the future. I assume CodeCommit rate limiting is being triggered as documented at https://docs.aws.amazon.com/codecommit/latest/userguide/troubleshooting-ae.html#troubleshooting-ae3.

At the moment we have ~25 apps defined in each Argo CD deployment and have 3 clusters polling using the default interval.

**Expected behavior**
Should be able to use CodeCommit without hitting default rate limits.

**Version**

```shell
argocd: v1.1.0-rc2+e275621.dirty
  BuildDate: 2019-06-21T23:24:09Z
  GitCommit: e2756210d90a9f7c8671a4bf00005577ae8f5573
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.1.0-rc1+46550e0
  BuildDate: 2019-06-14T18:27:01Z
  GitCommit: 46550e009bfe4525cd6399a631ded8c9eb34f02e
  GitTreeState: clean
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

```
time="2019-07-09T05:43:52Z" level=error msg="finished unary call with code Unknown" error="unexpected client error: unexpected requesting \"https://git-codecommit.us-west-2.amazonaws.com/v1/repos/k8s-config/info/refs?service=git-upload-pack\" status code: 429" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2019-07-09T05:44:51Z" grpc.service=repository.RepoServerService grpc.start_time="2019-07-09T05:43:51Z" grpc.time_ms=1033.693 span.kind=server system=grpc
```

**Comment by alexec** [comment]
This is not configurable currently. We'll be fixing in v1.2.

**Comment by essh** [comment]
Was this supposed to be closed? What thoughts do you have on configuration options in 1.2 that will be able to avoid this issue?

**Comment by alexmt** [comment]
I guess @alexec closed it as a duplicate of https://github.com/argoproj/argo-cd/issues/1399 . This will allow disabling git pulling

**Comment by essh** [comment]
Ok, that will workaround the issue for some users I guess but ideally we would like polling to work even if it means things are a little more spaced out with jitter or caching (all our configuration is in a single repo) instead of disabling polling completely.

**Comment by alexmt** [comment]
Just sent PR which adds Prometheus metrics with number of git queries. This will allow us to collect concrete numbers.

We've identified one use case which might cause a lot of unnecessary `git ls-remote` queries: argocd reconciles application ( which includes one `git ls-remote`  ) every time when top level live resource changes. This might happen very frequently in some applications (e.g. deployment get a lot of updates during rolling update, some CRDs are changing constantly etc). Next is PR will remove need to run `git ls-remote` in such cases. 

We are hoping that along with metrics we can quickly prove if implemented improvement is good enough and probably can find more ways to reduce number of interactions with git .

**Comment by spencergilbert** [comment]
@alexmt do you have ref for the "next pr" to remove the git ls-remote call for some cases? It looks like we've been hitting a similar 429 error problem with Gitlab, not necessarily all on the argo side, but as we're using gitlab kubernetes executors for ci in our cluster as well.
