### ISSUE TITLE
Applications are turning into UNKNOWN state showing "NOAUTH Authentication required" in v2.11 but refresh will fix the issues. 

### ISSUE THREAD

**Issue by prsrus216** [argoproj/argo-cd#18954]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

After the update from ArgoCD 2.10.9 to 2.11.0 the sync trigger on webhook from Bitbucket does not work anymore.

v2.11.4 Release Logs stating that this issues is fixed. but I still see the same behavior in 2.11.4 as well.

Link to the PR: https://github.com/argoproj/argo-cd/commit/07880f3c1d3313f27922cdd693e5505d843387b0 

**To Reproduce**

1. Install ArgoCD 2.11 version
2. Deploy a Application and setup repo credentials for authenticate
3. Verify that the sync is working and application is deployed
4. Wait for some time and Application turn into UNKNOWN state showing "NOAUTH Authentication required" on next webhook trigger.
5. Refresh the application from Argo UI that detect the changes and sync works fine with a refresh.

**Expected behavior**

Without manual refresh sync should work  automatically.

**Screenshots**

Application synced correctly:

<img width="1324" alt="Screenshot 2024-07-05 at 9 49 03 AM" src="https://github.com/argoproj/argo-cd/assets/152336744/46f43c8f-f606-4a0e-b796-c9061354159e">

After some time it started showing UNKNOWN state when next webhook trigger to sync

<img width="1324" alt="Screenshot 2024-07-05 at 9 48 43 AM" src="https://github.com/argoproj/argo-cd/assets/152336744/7aeb307c-3f2c-4f63-b42a-9514bd82d575">

<img width="1324" alt="Screenshot 2024-07-05 at 9 48 31 AM" src="https://github.com/argoproj/argo-cd/assets/152336744/fb7214b2-126e-4990-b57b-0e540ebfca36">

Manual refresh from UI fixed the issues

<img width="1324" alt="Screenshot 2024-07-05 at 9 49 03 AM" src="https://github.com/argoproj/argo-cd/assets/152336744/e85252e5-60ef-44c8-8d3f-22af18323c33">

**Version**

argocd-server: v2.11.4+e1284e1
  BuildDate: 2024-07-02T19:17:02Z
  GitCommit: e1284e19e03c9abab2ea55314b14b1e0381c4045
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0

**Logs**

repo-server time="2024-07-05T13:59:17Z" level=error msg="finished unary call with code Unknown" error="NOAUTH Authentication required." grpc.code=Unknown grpc.method=GenerateManifest g │
│ rpc.service=repository.RepoServerService grpc.start_time="2024-07-05T13:59:17Z" grpc.time_ms=0.353 span.kind=server system=grpc

**Comment by crenshaw-dev** [comment]
The message indicates a failure to connect to Redis. I think there are a couple possibilities: 1) an old repo-server pod hasn't been updated to the latest Argo CD version and isn't sending Redis creds or 2) a momentary connection failure has been cached.

Check your repo-server pods to make sure they're all running 2.11.4.

If that's not the problem, try restarting your Redis install to blow away the cache (there will be a temporary performance impact while the cache rebuilds).

**Comment by prsrus216** [comment]
@crenshaw-dev  Thank You for the explanation. I have fixed REDIS PASSWORD param and now its working fine. This issue is now resolved.
