### ISSUE TITLE
AnyNamespace Multi ArgoCD Instance WildCard Application Resource Monitoring Overlap

### ISSUE THREAD

**Issue by ArthurVardevanyan** [argoproj/argo-cd#19016]
Here is a PR with my attempt at solving the below scenario: https://github.com/argoproj/argo-cd/pull/19017

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Two Cluster Wide ArgoCD Instances are present on a given cluster.

1 For Managing the Cluster and its resources. 
1 For Tenants of the Cluster to manage their resources. 

Second Tenant ArgoCD uses the application in any namespace feature.

The issue is, when using `*` for the selector, due to there being an unkown number of namespaces.  That second instance tries to all scan and reconcile the applications already managed by the first instance. 

**To Reproduce**
Example of the cluster config.
https://github.com/ArthurVardevanyan/HomeLab/blob/main/kubernetes/argocd/base/argocd.yaml

Example of a tenant config:
https://github.com/ArthurVardevanyan/HomeLab/blob/main/kubernetes/argocd/apps/argocd-apps.yaml#L14-L18
For the moment in the example above, the namespaces are explicitly defined. However on larger environments, we will require `*`

**Expected behavior**

I would expect ArgoCD to be aware of an application/object is already monitored by another instance, and not monitor it.

However, a simpler solution would be an exclude namespace list option.

**Version**
2.11.2: https://github.com/ArthurVardevanyan/HomeLab/blob/main/kubernetes/argocd/apps/argocd-apps.yaml#L57

**Comment by jannfis** [comment]
Implemented by https://github.com/argoproj/argo-cd/pull/19017
