### ISSUE TITLE
sync only all outofsync items option

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1902]
**Is your feature request related to a problem? Please describe.**
When syncing a large project all items are 'dry-run't' under water what uses a lot of time. It would be great if one could select an option to only process the out of sync items. I can do it now one by one with partial sync but that is time consuming. An option to do partial sync for the outofsync items only would be of great help

**Comment by alexec** [comment]
A great one for community contribution.

**Comment by Rayyis** [comment]
Should it be a new sync type performed server side, and possible to select when creating new applications? Or just a button in the UI to select all out of sync items before triggering a sync manually?
