### ISSUE TITLE
When I edit yaml file the app UI, getting this error.

### ISSUE THREAD

**Issue by vjsandu** [argoproj/argo-cd#19025]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by surajyadav1108** [comment]
no info?

**Comment by vjsandu** [comment]
No Info, the bug report page directly brogue me here

**Comment by dhruvang1** [comment]
Please look at other issues and update this issue with all the mentioned sections like "Describe the bug", "To Reproduce", etc. How do you expect anyone else to understand your problem without any other details?

**Comment by andrii-korotkov-verkada** [comment]
Closing as there are no updates. Please, open a new issue with more info if still needed.
