### ISSUE TITLE
Explicit 'readOnly: false' applied to 'mountPath' causes perpetual out-out-sync

### ISSUE THREAD

**Issue by jadedeane** [argoproj/argo-cd#19038]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

'readOnly: false' within a 'mountPath' fails to sync.

**To Reproduce**

Use Cilium's Helm chart within an Argo CD app, and sync.

Observed within Cilium 1.15.7 per [issue](https://github.com/cilium/cilium/issues/33162#issuecomment-2225987802), when using their [chart](https://github.com/cilium/cilium/tree/v1.15.7/install/kubernetes/cilium).

**Expected behavior**

Installation and sync of resources.

**Screenshots**

![Screenshot 2024-07-12 at 10 52 16 AM](https://github.com/user-attachments/assets/ace9a3e8-0a1c-4864-a5e7-8823d4ddb640)

**Version**

```shell
❯ argocd version
argocd: v2.11.4+e1284e1
  BuildDate: 2024-07-02T23:16:22Z
  GitCommit: e1284e19e03c9abab2ea55314b14b1e0381c4045
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.11.4+e1284e1
```

**Logs**

```
Paste any relevant application logs here.
```

https://github.com/cilium/cilium/blob/v1.15.7/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L292
https://github.com/cilium/cilium/blob/v1.15.7/install/kubernetes/cilium/templates/spire/agent/daemonset.yaml#L72
https://github.com/cilium/cilium/blob/v1.15.7/install/kubernetes/cilium/templates/cilium-envoy/daemonset.yaml#L187

**Comment by crenshaw-dev** [comment]
Are you using either server-side apply or server-side diff?

**Comment by jadedeane** [comment]
> Are you using either server-side apply or server-side diff?

Default, server-side diff. 

Ah, I see where you were going with this. Change to 'server-side apply' per  [docs](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#server-side-apply) did the trick. Thanks, @crenshaw-dev

**Comment by igorivan** [comment]
The issue is closed, but we are experiencing the same problem in v2.12.0+ec30a48
Please advice?

**Comment by igorivan** [comment]
The issue is closed, but I used server-side diff per [docs](https://argo-cd.readthedocs.io/en/latest/user-guide/diff-strategies/#server-side-diff) within the Cilium app, and it didn't work
My ArgoCD version is v2.12.0+ec30a48
Please advice?
