### ISSUE TITLE
hydrator: handle `sourceHydrator` fields from webhook

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#19070]
The webhook currently handles the `source` field. But we need to trigger hydration when a commit is pushed to `sourceHydrator.drySource.targetRevision`.

Currently we trigger hydration in the refresh queue. I think we should add a new annotation to use `refresh-hydrator` to trigger a new hydration.

**Comment by daengdaengLee** [comment]
This issue seems to be resolved, so I think it's okay to close it.
