### ISSUE TITLE
hydrator: add unit tests for new git client functions

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#19071]
We've added 5 new methods to the git client:

```go
	// SetAuthor sets the author name and email in the git configuration.
	SetAuthor(name, email string) (string, error)
	// CheckoutOrOrphan checks out the sync branch. If the branch does not exist, it creates an orphan branch.
	CheckoutOrOrphan(branch string, submoduleEnabled bool) (string, error)
	// CheckoutOrNew checks out the target branch. If the branch does not exist, it creates an empty branch based
	// on the sync branch.
	CheckoutOrNew(branch, base string, submoduleEnabled bool) (string, error)
	// RemoveContents removes all files from the git repository.
	RemoveContents() (string, error)
	// CommitAndPush commits and pushes changes to the target branch.
	CommitAndPush(branch, message string) (string, error)
```

All these should be unit-tested.

- [x] SetAuthor(name, email string) (string, error)
- [x] CheckoutOrOrphan(branch string, submoduleEnabled bool) (string, error)
- [x] CheckoutOrNew(branch, base string, submoduleEnabled bool) (string, error)
- [x] RemoveContents() (string, error)
- [x] CommitAndPush(branch, message string) (string, error)

**Comment by daengdaengLee** [comment]
Hello, @crenshaw-dev.
I added one unit test for your code. Please review this.
Thanks!

**Comment by crenshaw-dev** [comment]
@daengdaengLee are you going to add more tests? If so I can assign this issue to you!

**Comment by daengdaengLee** [comment]
@crenshaw-dev Sure! I'll add other tests as well. Thanks!

**Comment by crenshaw-dev** [comment]
Done, thanks @daengdaengLee and @juwon8891!!!

If you all are up for more tasks, please take a look here: https://github.com/orgs/argoproj/projects/33

Or if you don't see any tickets that sound good, I'll try to write up some more.
