### ISSUE TITLE
UI - Dark theme background on Application Details panel page

### ISSUE THREAD

**Issue by shijiadong2022** [argoproj/argo-cd#19094]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

1, Change system to Dark Theme in Settings page
2, Go to Applications page
3, Select one of the applications
4, Click DETAILS to view application details panel page
5, Notice the background of Annotation 

![image](https://github.com/user-attachments/assets/c8e3b237-2592-442b-9740-f4ec4b93f9be)

**Expected behavior**

![image](https://github.com/user-attachments/assets/5d3e198b-d1f9-4231-a015-f1f3e9662cd8)

**Comment by shijiadong2022** [comment]
I am working on a fix and will submit a PR soon

**Comment by surajyadav1108** [comment]
Duplicate #18742

**Comment by shijiadong2022** [comment]
@alexmt in issue #18742 the suggested solution is to increase the gray percentage. It seems to me that we can also remove the background setting in expandable.scss without any impact to both light and dark theme. 
        background: linear-gradient(to bottom, rgba(255,255,255,0) 0%,rgba(255,255,255,1) 100%);
Any recommendation on which solution works better for this case?
