### ISSUE TITLE
Argo UI for Rollout has no Promote button and action

### ISSUE THREAD

**Issue by huayangdu** [argoproj/argo-cd#19105]
# Summary

Argo UI Extension has no Promote Button, also find that there is no action on argo cd for it. https://github.com/argoproj/argo-cd/tree/master/resource_customizations/argoproj.io/Rollout/actions

# Motivation

Now I am using Rollout with one manual decision step with several pause duration. But I find that on latest argo cd, it doesn't support Promotion action, it only has PromotionFull which will skip my remaining pauses after hitting that button. So why not add an action for that, I think it's the basic command. Of course an option solution is that I can do that with command line to promote or use command line dashboard with promote button.
![image](https://github.com/user-attachments/assets/7d86a2c1-340c-40e5-a0d1-76941a29bcab)

# Proposal

Add an action and support for UI

**Comment by JessieTeng89** [comment]
Hi @huayangdu 
I think the promote you mentioned is called "Resume" in UI, with Rollout Canary strategy, you can click Resume button to promote to next step, can you try it?

**Comment by huayangdu** [comment]
Oh, I find it, i am not sure why it doesn't match latest name. It seems not updated for 4 years.
