### ISSUE TITLE
UI - Select arrow icon was hidden in create application page

### ISSUE THREAD

**Issue by JessieTeng89** [argoproj/argo-cd#19134]
If you open `create application` page, and change to `Plugin` view, you can see the Name select arrow icon was hidden
![image](https://github.com/user-attachments/assets/2779654f-f4c0-4292-9eff-8b0a82f101de)

**Comment by JessieTeng89** [comment]
I will create a PR to fix it.

**Comment by keithchong** [comment]
I see this problem too.
