### ISSUE TITLE
UI - Dark mode is not working in full screen log page

### ISSUE THREAD

**Issue by JessieTeng89** [argoproj/argo-cd#19135]
Steps to reproduce the issue:
1. Open argo-cd sample https://cd.apps.argoproj.io
2. Enable Dark mode in Preference page
3. Open this app https://cd.apps.argoproj.io/applications/argocd/argo-events?resource=
4. See Logs in EventBus with name `default` 
5. Click `Show logs in fullscreen in a new window` button to see logs in full screen

The Dark mode is not enabled properly:
![image](https://github.com/user-attachments/assets/eaec5b87-744e-44e6-9e59-942b6bb39bc3)

**Comment by JessieTeng89** [comment]
I will create a PR to fix it

**Comment by keithchong** [comment]
Thanks Jessie. I can reproduce this too.
