### ISSUE TITLE
Application details sends dozen on API queries to load revision metadata

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1915]
**Describe the bug**
Application details sends dozen on API queries to load revision metadata

**To Reproduce**

1. Navigate to any app details page
2. See attached screenshot

 ![Screen Shot 2019-07-10 at 3 58 44 PM](https://user-images.githubusercontent.com/426437/61010601-c37a3c80-a32b-11e9-8bd8-c4803f146bf2.png)

**Comment by alexec** [comment]
huh - glab I cache this in the back end, but still - too many

**Comment by alexec** [comment]
oh - is this a problem with the application summary page (max 2 queries) or the history page (small finite number of queries)?

**Comment by alexmt** [comment]
As we discussed offline it is ok to load metadata, since we have up to 10 history items. We should not load history info unless history panel is opened. Updated the PR accordingly.
