### ISSUE TITLE
rpc error: code = Unknown desc = error testing repository connectivity: repository "" cannot be initialized: repo URL is invalid

### ISSUE THREAD

**Issue by jeremyyang15** [argoproj/argo-cd#19159]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I am using Docker Desktop Kubernetes to do some testing with Argocd.
I successfully setup the ArgoCD service in argocd namespace, I also added one github private repo and a public repo (https://github.com/bukurt/argocd) in Argocd, which I could see connection status is successful.
I used https:// protocal with username and github token.
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/91ca3009-237a-4dea-ab52-b319ab663d88">

From the UI interface, I am able to create an app for both repo successfully.
<img width="589" alt="image" src="https://github.com/user-attachments/assets/b37d4ead-4aff-4cda-855d-5f2d36713d58">

However, when I am using argocd cli to create the same app, it fails.
Even the yaml file generated from the UI interface didn't work.

**To Reproduce**
1. Setup argocd as per above description
2. Setup the repository in UI interface or cli as below
argocd repo add https://github.com/your-org/private-repo.git --username your-github-username --password <your-token>
3. kubectl port-forward svc/argocd-server -n argocd 8080:443
4. argocd app create local-argocd-test.yaml

**Expected behavior**

The argocd app could be created successfully from the cli.

**Screenshots**

<img width="1435" alt="image" src="https://github.com/user-attachments/assets/e9a4c629-9c61-41cb-a20a-0453b3691290">

`➜  argocd argocd app create local-argocd-test.yaml
FATA[0000] rpc error: code = InvalidArgument desc = application spec for local-argocd-test.yaml is invalid: InvalidSpecError: repository not accessible: repo client error while testing repository: rpc error: code = Unknown desc = error testing repository connectivity: repository "" cannot be initialized: repo URL is invalid `

the local-argocd-test.yaml is attatched.
[local-argocd-test.yaml.zip](https://github.com/user-attachments/files/16344112/local-argocd-test.yaml.zip)

**Version**

➜  argocd argocd version
argocd: v2.11.6+089247d
  BuildDate: 2024-07-22T16:59:06Z
  GitCommit: 089247df0f15e64813d00a2d1271a2095feecad4
  GitTreeState: clean
  GoVersion: go1.22.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.5.8+bbe870f
  BuildDate: 2023-01-25T16:17:52Z
  GitCommit: bbe870ff5904dd1cebeba6c5dcb7129ce7c2b5e2
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0

**Logs**

**Comment by akitson-primed** [comment]
I'm having the same issue.  Did you find a solution?
