### ISSUE TITLE
notifications controller not included in core install

### ISSUE THREAD

**Issue by cawolf** [argoproj/argo-cd#19163]
# Summary

When [installing ArgoCD core](https://argo-cd.readthedocs.io/en/latest/operator-manual/core/) only, you are not able to make use of the notifications controller, but this is not docuemented on the [notifications overview](https://argo-cd.readthedocs.io/en/latest/operator-manual/notifications/) or in the [core architecture diagram](https://argo-cd.readthedocs.io/en/latest/operator-manual/core/#architecture). Additionally, core install users are not able to easily add the notification controller to their installation, because there is no recommended way of doing so.

# Proposal

The documentation needs to show that the notifications controller is only available in the "full" install, not the core install.

Depending on your plans on supporting the core install, it might be helpful for core install users to have an easy way to add the notifications controller to their installation.

**Comment by juwon8891** [comment]
It's merged
