### ISSUE TITLE
UI: EndpointSlices should use the same icon as Endpoint objects

### ISSUE THREAD

**Issue by ChristianCiach** [argoproj/argo-cd#19178]
# Summary

The UI of Argo-CD uses a specialized icon for legacy "Endpoint" objects, but uses a generic icon for EndpointSlices:

![grafik](https://github.com/user-attachments/assets/47e72385-af79-4704-ad85-bade521dd5ab) 

# Motivation

EndpointSlices are stable since Kubernetes 1.21 and Kubernetes creates these objects by default for services since at least this version. Since these objects are ubiquitous now, Argo-CD should treat them with the same importance as Endpoint objects.

# Proposal

EndpointSlices are essentially supercharged Endpoints with very similar semantics. Argo-CD should just re-use the icon it already uses for Endpoints.

**Comment by JessieTeng89** [comment]
I will create a PR to update this

**Comment by pasha-codefresh** [comment]
Thank you @JessieTeng89 @mg5566 for your contribution. We didnt merge second PR, because it is duplication, thank you both for effort done
