### ISSUE TITLE
Repo URL in application summary page will not open a new tab

### ISSUE THREAD

**Issue by JessieTeng89** [argoproj/argo-cd#19183]
Repo URL in application summary page will not open a new tab like other links.
<img width="1416" alt="image" src="https://github.com/user-attachments/assets/f3448d22-56e1-4218-bf63-409c6841981f">

**Comment by JessieTeng89** [comment]
I will create a PR to fix it

**Comment by surajyadav1108** [comment]
Hey @JessieTeng89 if you agree can I take this up? 😅
