### ISSUE TITLE
unhandled exception returns exit code 0

### ISSUE THREAD

**Issue by pluqueTheLuxe** [argoproj/argo-cd#1922]
step to reproduce are not quite clear but here's my log with set -x

```
2019-07-11T15:04:03.8855197Z + argocd login --insecure example.com --username admin --password argocd-server-57c786cbf6-wqsj5
2019-07-11T15:04:04.1167848Z time="2019-07-11T15:04:04Z" level=fatal msg="rpc error: code = Internal desc = transport: received the unexpected content-type \"text/html\""
2019-07-11T15:04:04.1168148Z + '[[' 0 '==' 0 ]]
```

What is quite clear though, is that exit code must not be 0. It makes automation of ArgoCD unusable

**Comment by simster7** [comment]
To use this command you need to be an instance of ArgoCD on the domain specified, in this case `example.com`. This is failing because `example.com` is not an Argo CD instance (it is only meant as a placeholder), so it's returning an HTML request instead, which is unreadable to the cli.

If you want to host your own Argo CD instance follow the directions here: https://argoproj.github.io/argo-cd/getting_started/

**Comment by pluqueTheLuxe** [comment]
`example.com` is just for obfuscate our real domain name ;)

The problem still exists with our real domain

**Comment by jannfis** [comment]
> To use this command you need to be an instance of ArgoCD on the domain specified, in this case `example.com`. This is failing because `example.com` is not an Argo CD instance (it is only meant as a placeholder), so it's returning an HTML request instead, which is unreadable to the cli.

I think what @pluqueTheLuxe means is, that the CLI does not exit with an exit code != 0 in case of failure, which is used in scripts (or likewise, any automation tool) to decide whether the operation was successful or not. 

Should be an easy fix however.

**Comment by simster7** [comment]
Hmm, locally it does:
```
$ argocd login --insecure example.com --username admin --password argocd-server-57c786cbf6-wqsj5; echo $?
FATA[0000] rpc error: code = Internal desc = transport: received the unexpected content-type "text/html"
1
```

**Comment by simster7** [comment]
@pluqueTheLuxe Is your issue with the exit code or with reaching your ArgoCD instance?

**Comment by jannfis** [comment]
@simster7 You are right - tested here locally, exit code is 1 as well.

**Comment by pluqueTheLuxe** [comment]
let me come back to you guys @simster7 and @jannfis ... I got some weird issue here with vsts ... it exits with 1 also when I do it locally

**Comment by pluqueTheLuxe** [comment]
ok my bad...I was running 

```
docker run -i test_img sh <<EOF
argocd ...
if  [[ $? != "0" ]]...
EOF
```
 but as a newbie in linux I missed the `\` in front of the `$` in the heredoc :|
