### ISSUE TITLE
Warning during secret diffing

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1923]
**Describe the bug**
Following warning is printed during secret diffing:

```
WARN[0022] Could not unmarshal to object of type /v1, Kind=Secret: illegal base64 data at input byte 0 
```

The warning pollutes `argocd app diff` output. The error happens during secret re-marshaling. This is not a problem now, but might be a problem in a future if secret get a field which require remarshaling .

**To Reproduce**
1. Deploy any app which has secret
2. Sync in and run `argocd app diff`
3. See warning message which makes it difficult to read command output

**Version**: v1.1.0

**Comment by jessesuen** [comment]
The fix is to use `+` instead of `*` when redacting secrets, as `+` is a valid base64 character
