### ISSUE TITLE
Allow `argocd app wait` to continue if a specified number of replicas satisfy

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-cd#1924]
**Is your feature request related to a problem? Please describe.**

For some resources with multiple replicas that also have long and non-uniform startup times, it would be useful to allow `argocd app wait` to continue if a specified minimum number of said replicas satisfy its condition.

**Describe the solution you'd like**

Adding a flag to `argocd app wait` that specifies the minimum number of replicas of the resource that need to be healthy for it to continue. For example, if our app has 4 replicas and we only want 2 of them to be healthy before the command continues we could call a command such as `argocd app wait APPNAME --resource RESOURCE --health --threshold 2`

The `threshold` value could be an integer to indicate a minimum number of replicas or a number in (0, 1) (e.g. 0.5) to indicate a percentage of replicas.

**Have you thought about contributing yourself?**

Yes, I would implement this feature myself.

**Comment by simster7** [comment]
@alexec @jessesuen Any thoughts on this?

**Comment by alexec** [comment]
Could you workaround using a custom health check?

**Comment by simster7** [comment]
A workaround for this for Rollouts is `previewReplicaCount`s: https://github.com/argoproj/argo-rollouts/blob/master/docs/features/bluegreen.md#previewreplicacount

Since the original intention of this issue was waiting for pods during a rollout, this can be closed for now.
