### ISSUE TITLE
Helm chart not getting deployed when using AppSet Git Generator Concept on WSL2

### ISSUE THREAD

**Issue by iamgauravpande** [argoproj/argo-cd#19279]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have ArgoCD `v2.11.5+c4b283c` deployed on a Microk8s cluster running on WSL2 environment . Able to use Concept of Application Set having below structure:

- Top Level App(Application Object) that targets a ApplicationSet Object.
- Application Set Object using Git generator files concept to deploy a `tenant` in this case helm chart onto microk8s cluster.

For some reason everything works until ApplicationSet Object meaning in my `argocd` namespace i can see `app` and `appset` objects created on Microk8s cluster  but the tenant(helmchart) is not getting deployed for some reason , and iam not able to figure out !

**To Reproduce**

- Clone this repo: https://github.com/iamgauravpande/wsl2-microk8s-lab 
- Deploy only the Top Level app manifest located under: `observability/top-level-app`
- Above will automatically deploy AppSet as well located under: `observability/applicationset`

**Expected behavior**

I should see on ArgoCD UI an Application , Appset and my tenant/helm chart as application deployed. 

**Screenshots**

**NO Helm chart application deployed:** 

![image](https://github.com/user-attachments/assets/443a9c35-4b8e-4d35-a6fd-f0ff7e707d74)

**Version**

`v2.11.5+c4b283c`

**Comment by lamadome** [comment]
All looks fine, the error is the fact that you named the file config,json and not config.json (a comma instead of a dot) inside this directory
https://github.com/iamgauravpande/wsl2-microk8s-lab/blob/main/observability/tenant-discovery/tenant/grafana/

rename the file and it works

**Comment by iamgauravpande** [comment]
Apologies in creating invalid issue. Thanks for the help !
