### ISSUE TITLE
Logs for deployment or container have `.txt` extension instead of `.log`

### ISSUE THREAD

**Issue by rajattrt** [argoproj/argo-cd#19271]
When deploying applications or containers using ArgoCD, the generated log files are saved with a `.txt` extension instead of the expected `.log` extension. This can lead to confusion and inconsistency in log management practices, as `.log` is the standard extension for log files. 

**To Reproduce**
- Navigate to the ArgoCD web UI.
- Go to the deployed application's details, select logs and then select download logs .
- Check the logs generated for the deployment process.

**Expected behavior**

Log files should be saved with a .log extension to adhere to standard log file naming conventions.

**Version**
Argo CD
v2.11.0+d3f33c0

**Comment by crenshaw-dev** [comment]
Concretely, what's the negative impact of using .log? In general I think "following conventions" is good, but I'm not sure it's enough to justify changing the current behavior (which someone somewhere might depend on).

**Comment by rajattrt** [comment]
In my opinion, switching to the .log format enhances the user experience, improves tool compatibility, aligns with industry standards, and has no real downsides.

While some systems or users might currently depend on the .txt format, the advantages of switching to .log outweigh this. Many users, including myself, likely rename the file to .log before consuming or accessing it. This change will simplify workflows and make life easier. Additionally, IDEs like VS Code can parse .log files better, making them easier to read compared to .txt files.

I have captured an example below that illustrates the difference between .log and .txt files and the impact it has.

<img width="1509" alt="Screenshot 2024-07-27 at 8 25 51 PM" src="https://github.com/user-attachments/assets/777711ef-9e47-4c35-ac15-bfa4286cd0d8">

Thanks for considering this!

**Comment by crenshaw-dev** [comment]
Sweet, the highlighting alone sells me tbh. Want to just add a quick note to the 2.12-2.13 upgrades page in your PR, just in case anyone relies on the current extension?

**Comment by rajattrt** [comment]
Super! I added a note around it in the docs.
