### ISSUE TITLE
hydrator: unit test file writers

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#19303]
The hydrator produces three kinds of files: metadata, readme, and manifest.yaml.

All those files are constructed by this code: https://github.com/argoproj/argo-cd/blob/62ff4093e8939f1e0758804749be1bf3966eb1b8/commitserver/commit/hydratorhelper.go

That code needs unit tests.

**Comment by crenshaw-dev** [comment]
@juwon8891 do you have time to write a test for `WriteForPaths`?

Also are you up for more testing work? I can write up some more issues for hydrator testing that's needed.

**Comment by juwon8891** [comment]
Sure! I hope I can help you.
