### ISSUE TITLE
can't unzip gzip compressed values from redis cache

### ISSUE THREAD

**Issue by aborilov** [argoproj/argo-cd#19306]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
can't use tools to unzip compressed redis values(zcat/gunzip/gzip etc)
```
redis-cli --no-auth-warning -D "" -a password --raw get "cluster|info|http://cluster-test:8001|1.8.3.gz" |zcat
zcat: (stdin): unexpected end of file
```

**To Reproduce**

turn on gzip compression for redis(on by default), application controller will add cluster info into redis, try to unzip value with zcat

```
redis-cli --no-auth-warning -D "" -a password --raw get "cluster|info|http://cluster-test:8001|1.8.3.gz" |zcat
zcat: (stdin): unexpected end of file
```

**Expected behavior**

we should be able to unzip value without problems
```
redis-cli --no-auth-warning -D "" -a password --raw get "cluster|info|http://cluster-test:8001|1.8.3.gz" | zcat | jq .cacheInfo.resourcesCount

402
```

**Version**

```shell
argocd version
argocd: v2.11.6+089247d
  BuildDate: 2024-07-22T14:17:58Z
  GitCommit: 089247df0f15e64813d00a2d1271a2095feecad4
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/arm64
```

**Comment by crenshaw-dev** [comment]
How does this bug affect the redis-cli but doesn't cause issues for Argo CD components using the Redis cache? If the value is corrupted for the CLI, shouldn't it be corrupted for everyone?

**Comment by aborilov** [comment]
in the code we are using `json.NewDecoder.Decode` and it works because Decode read by chunks, but tools like `zcat` don't do that, that's my understanding of the problem.

**Comment by crenshaw-dev** [comment]
I see... without a super clear idea of why the current behavior seems to work in some cases but not others, I think I'd want the PR to have a test to reproduce the issue and demonstrate that calling `Close()` fixes it.

**Comment by aborilov** [comment]
> I see... without a super clear idea of why the current behavior seems to work in some cases but not others, I think I'd want the PR to have a test to reproduce the issue and demonstrate that calling `Close()` fixes it.

added simple test that fails without `Close` call

https://github.com/argoproj/argo-cd/pull/19307/commits/ec773578d77d66a539a8077309b5b91f31db2f81
