### ISSUE TITLE
hydrator: produce metrics on getting git creds user info

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#19300]
Before the hydrator pushes a commit, it tries to get "user info" (i.e. name and email) from the git credentials.

For GitHub, getting the user info involves making a few GitHub API calls.

We should make sure there's a histogram metric for the seconds elapsed getting user info. Labels should include "repoURL" and "credential type" (ssh, github app, etc.).

The code is here: https://github.com/argoproj/argo-cd/blob/62ff4093e8939f1e0758804749be1bf3966eb1b8/commitserver/commit/commit.go#L143

**Comment by Jack-R-lantern** [comment]
This issue has been resolved and should be closed.

**Comment by crenshaw-dev** [comment]
Thanks @Jack-R-lantern!
