### ISSUE TITLE
App-of-apps: sync child apps

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1932]
**Is your feature request related to a problem? Please describe.**

When you manually sync an app-of-apps, the child apps are synced, but their resources are not synced unless auto-sync is configured. 

However, you may not want to set auto-sync.

**Describe the solution you'd like**

Either:

* Always sync child apps if the parent is synced.
* Have a flag to sync child apps.

**Comment by alexec** [comment]
@alexmt FYI

**Comment by stevesea** [comment]
I'd like a flag that says to sync child apps. 

Or, when I'm in a parent Application I can click on the actions for one of its child Applications and tell it to sync, possibly cascading down into its children.

**Comment by OmerKahani** [comment]
We also like the flag option. In specific we want to use argocd to manage all the applications in the cluster include the infrastructure ones (Istio, Prometheus...), this way the when we boot-start a new cluster, we just install argocd, apply the app of apps, and sync all the apps.

We don't want to use auto-sync, because we want to control the time of the sync. so a flag will be greate, this way we can mark the flag only on the first time we apply the app of apps and get al the to cluster up in one command.

**Comment by thejmazz** [comment]
Flag! In combination with sync-waves would be a really nice way to bootstrap new cluster, for example deploy logging and metrics stack in wave 1, only continue (e.g. on to ingress controller(s)) once those child-apps in wave 1 are healthy.

**Comment by jessesuen** [comment]
There's a couple of use cases here, each are equally valid.

1. create the application object, but do not sync
2. create the application object, auto-sync all and future changes
3. create the application object, sync only during initial creation, but not afterwards

Item 3 is not supported at the moment, but I agree with the use case. I do think that this is just a new option in the syncPolicy. So at the risk of adding more bloat to the spec, supporting this might look something like:

```yaml
spec:
  syncPolicy:
    onCreate: true      
```

> Always sync child apps if the parent is synced.
I think this violates use case 1

> Have a flag to sync child apps.
This will not work in the declarative config

**Comment by jessesuen** [comment]
The trick with this, is how to determine that app is freshly created, and has never attempted synced. The best heuristic for this is if `status.operationState` is nil. 

Note that relying on `status.operationState == nil` (as opposed to some formal lifecycle state stored in status), would mean if initial sync failed for whatever reason, we would still not attempt a second sync.

I think we may eventually need to implement a lifecycle state machine, if we ever hope to support
https://github.com/argoproj/argo-cd/issues/355

**Comment by thejmazz** [comment]
FWIW my current approach is set nested apps to autosync, but with a more scoped revision, to a commit or tag. if to a branch, not HEAD,develop,etc, but a branch created specifically for that app/namespace/cluster

**Comment by alexec** [comment]
Would a command to sync by labels sort this out? It would be versatile.

Sync all child apps:

```
argocd app sync -l app.kubernetes.io/instance=my-app
```

**Comment by alexec** [comment]
### List applications

```
Usage:
  argocd app list [flags]

Examples:
  # List all apps
  argocd app list

  # List apps by label, in this example we waiting for apps that are children of another app (aka app-of-apps)
  argocd app list -l app.kubernetes.io/instance=my-app
```

### Sync an application to its target state

```
Usage:
  argocd app sync [APPNAME... | -l selector] [flags]

Examples:
  # Sync an app
  argocd app sync my-app

  # Sync multiples apps
  argocd app sync my-app other-app

  # Sync apps by label, in this example we sync apps that are children of another app (aka app-of-apps)
  argocd app sync -l app.kubernetes.io/instance=my-app
```

### Wait for an application to reach a synced and healthy state

```
Usage:
  argocd app wait [APPNAME.. | -l selector] [flags]

Examples:
  # Wait for an app
  argocd app wait my-app

  # Wait for multiple apps
  argocd app wait my-app other-app 
  
  # Wait for apps by label, in this example we waiting for apps that are children of another app (aka app-of-apps)
  argocd app wait -l app.kubernetes.io/instance=apps
```

**Comment by alexec** [comment]
https://github.com/argoproj/argo-cd/issues/1673

**Comment by beck3905** [comment]
I know this is an old closed issue, but is this capability only available using the ArgoCD CLI? I am using kubectl with `operation` to sync my parent application from my CI/CD pipeline. Is there a way to sync the child applications that way too? What about in the UI?
