### ISSUE TITLE
Extend Duration of  Tooltip for Clipboard Copy Action

### ISSUE THREAD

**Issue by Gaic4o** [argoproj/argo-cd#19373]
https://github.com/user-attachments/assets/13ef535f-2965-4f1b-82a6-3e5ba2b27fc3

# Summary

The tooltip that appears when hovering over the copy icon next to the name field (e.g., "workflow-controller-configmap") currently disappears too quickly after showing the `Copied!` message. This can cause confusion for users who might not notice whether the text was successfully copied to the clipboard.

# Motivation

When copying important configuration names or IDs using the copy icon, it’s crucial for users to have clear feedback that the operation was successful. A tooltip that disappears too quickly may cause users to doubt if the action was completed successfully, leading them to double-check or repeat the action unnecessarily. By extending the duration of the `Copied!` tooltip, users will have a better confirmation experience, reducing confusion and improving the overall usability of the interface.

# Proposal

Introduce a setTimeout function to extend the visibility of the "Copied!" tooltip message to 2-3 seconds. This adjustment will ensure that users have sufficient time to see the confirmation, thereby improving the user experience and reducing potential confusion.

There may be another way, but I think you can apply setTimeout to make the tooltip appear longer. What do you think? If it's okay, I'd like to try making it.
I would like to edit it myself and post a PR.

**Comment by olivia-zh-xm** [comment]
I will work on this issue. The root cause is not the display duration

**Comment by olivia-zh-xm** [comment]
Working in Progress

**Comment by Gaic4o** [comment]
@olivia-zh-xm  Oh, I've been working on this issue since yesterday. Have you spent a lot of time on this issue?

**Comment by olivia-zh-xm** [comment]
@Gaic4o I've completed the change, and will raise PR soon
