### ISSUE TITLE
Cannot login with new install per instructions in Getting Started docs

### ISSUE THREAD

**Issue by mojochao** [argoproj/argo-cd#1938]
**Describe the bug**

I cannot login as admin user with admin password as instructed when installed.

**To Reproduce**

My cluster is an EKS cluster running Kubernetes 1.13.
My client is running on a macOS Mojave host

1. Follow steps 1-3 in Getting Started guide (https://argoproj.github.io/argo-cd/getting_started/)
2. Try to login as indicated in step 4
3. Observe `FATA[0024] rpc error: code = Unauthenticated desc = Invalid username or password` in output

**Expected behavior**
I expected to be logged in and able to update the admin password as retrieved by:

```
$ kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server -o name | cut -d'/' -f 2
argocd-server-7c7c748648-vrpqd
```

**Version**

```shell
argocd: v1.0.2+e0bd546.dirty
  BuildDate: 2019-06-14T17:15:36Z
  GitCommit: e0bd546a07818ec06a27c2b3033454e3eb1c4152
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: darwin/amd64
FATA[0000] Argo CD server address unspecified
```

**Logs**

I see this repeated in the logs.
```
time="2019-07-15T17:05:45Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = Invalid username or password" grpc.code=Unauthenticated grpc.method=Create grpc.service=session.SessionService grpc.start_time="2019-07-15T17:05:45Z" grpc.time_ms=65.603 span.kind=server system=grpc
```

**What have I tried**

I thought perhaps the docs were stale, so I went and checked out the actual contents of the secret.

```
$ kubectl get secret -n argocd argocd-secret -o yaml
apiVersion: v1
data:
  admin.password: JDJhJDEwJGpkdlR3djV6ZkFMM3V6SUpMejFwR2Uza3FLVHVZb0dqa0V0elc5S0I4WkE4RDJJN0RIWjJ1
  admin.passwordMtime: MjAxOS0wNy0xMVQyMDowMDoyOFo=
...
```
Using this instead of the pod name was not successful either.

Has anyone else run into this problem?  It seems so early in to be running into this, so I feel I must be doing something wrong, but don't see anything pointing to a particular step gone bad.

Many thanks in advance for any advice on how to get past this.  I really like what I've seen from the Argo CD docs and videos, and would like to join in on all the fun!

**Comment by alexmt** [comment]
The password is auto set to name of the first argocd pod. If pod get recreated for some reason, then password stays the same. You can regenerate password using following instructions: https://argoproj.github.io/argo-cd/faq/#i-forgot-the-admin-password-how-do-i-reset-it

**Comment by mojochao** [comment]
That was indeed the problem.  Following those instructions solved it.

Many thanks!
