### ISSUE TITLE
Dark mode in source edit popup, the selected tag color is not clear to read.

### ISSUE THREAD

**Issue by sxt90128** [argoproj/argo-cd#19394]
**Describe the bug**

In dark mode source edit popup, when user add a selected chips the tag color is not clear to read.

**Expected behavior**

The selected color should be more clear for user to read

**Screenshots**

<img width="960" alt="image (12)" src="https://github.com/user-attachments/assets/a7a65de2-e777-4d60-9dce-e4776cee4490">

```

**Comment by olivia-zh-xm** [comment]
I will work on this issue.

**Comment by thisishwan2** [comment]
I solved that issue, can I open PR for this issue?
