### ISSUE TITLE
Delete Icon color  in edit application page is inconsistent with dark mode

### ISSUE THREAD

**Issue by olivia-zh-xm** [argoproj/argo-cd#19395]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
In Darkmode, when edit application, the color for delete icon is not obvious and consistent

**To Reproduce**
Enable "Dark mode", go to an application, click "DETAILS", in SUMMARY tab, click "EDIT", the delete icon for "ANNOTATIONS" is colored in black, which is not visible and inconsistent.

**Expected behavior**
Expect to change the color to align with other icons

**Screenshots**

<img width="944" alt="image" src="https://github.com/user-attachments/assets/d86710ab-c9d3-4d59-aeea-a880f29c4523">

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by sxt90128** [comment]
I will fix this.

**Comment by andrii-korotkov-verkada** [comment]
@sxt90128, can this be closed?

**Comment by andrii-korotkov-verkada** [comment]
It seems so.
