### ISSUE TITLE
Argo CLI does not support proxy when adding repocred

### ISSUE THREAD

**Issue by wangli1030** [argoproj/argo-cd#19391]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Argo CLI does not support proxy when adding repocred

**To Reproduce**

It does not have proxy option

**Expected behavior**

Argo CLI should have proxy option when adding repocred

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by mhaoda** [comment]
I'm going to fix it and raise a PR.

**Comment by nitishfy** [comment]
We can close this issue now.

cc @christianh814
