### ISSUE TITLE
Long sync error messages are truncated in UI

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1942]
When kubectl apply fails and spits out a message, this message is truncated in the UI. 

![image](https://user-images.githubusercontent.com/12677113/61244259-a7491780-a6fe-11e9-935e-d54da44045af.png)

This needs be displayed clearly.

**Comment by alexec** [comment]
This could be mitigated by column widths, or we could add a tooltip.

**Comment by dave08** [comment]
Or an expanding entry...

**Comment by alexec** [comment]
Easy one for community contribution - JavaScript only.

**Comment by jessesuen** [comment]
Why not wordwrap?

**Comment by alexec** [comment]
![Screen Shot 2019-07-24 at 17 18 53](https://user-images.githubusercontent.com/1142830/61836878-247b3780-ae37-11e9-8106-e9096ae38c2f.png)
We already have a tooltip.

**Comment by dave08** [comment]
Tooltip is not as good for errors that need googling, since there's no way to copy it... but it's certainly better than what we have now!
