### ISSUE TITLE
Error message "Unable to load data: key is missing" is confusing

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1944]
**Describe the bug**

Confusing error message `Unable to load data: key is missing` is shown on application details page if app info is missing in the cache. Instead of showing meaningless message UI should trigger app refresh. Usually, the error is reproducible if the controller is no functioning properly and therefore cache is not populated. Refresh should trigger reconciliation loop and either populate the cache or reveal real issue.

**To Reproduce**
1. Create new app
2. Break controller, e.g. scaledown controller deployment to 0. Restart redis to get rid of cache
3. Click on any app node
4. See the error

**Version**: v1.2.0

**Comment by k** [comment]
How do you fix this issue when you run into it?

**Comment by henrymori-pepsico** [comment]
Facing the same issue on GKE. Image attached. Cluster/ArgoCD was running fine for weeks. My guess is an auto-upgrade on GKE has thrown the cache out of sync. Forcefully deleting all ArgoCD pods hasn't helped unfortunately.

**Version:** 1.0.2

![image](https://user-images.githubusercontent.com/53585882/64553811-f40c3180-d2ee-11e9-91d8-63d59f1ab166.png)

**Comment by olivierlemasle** [comment]
I'm hitting this issue very frequently. Does that mean the controller is unstable?

**Comment by alexmt** [comment]
I believe error is happening frequently after upgrade or if you loose redis server and all cache is gone. 

The controller populates cache on every application reconciliation which happens every 3 minutes by default. It appears that first redis client request fails after redis restart. So cache is not populated during first reconciliation and cache is missing for 2 cycles. 

Sent PR implements graceful handling of redis restart and missing cache error. https://github.com/argoproj/argo-cd/pull/2454

**Comment by FelixRodriguezJara** [comment]
Hello,

I have a CD implemented with Argo and I am facing issues with redis when running it locally in minikube. When I click on "app diff", information is not displayed.  I have removed all redis related configuration from the argocd server and repo server (sentinel) as well as scaled down the redis deployment to have 0 replicas, expecting this to fix the problem, but Argo still tries to connect to the cache and it fails because of a timeout. Is there any flag I can set up to disable it completely?

Thank you very much.

Kind regards.

**Comment by AbdoulRahimBarry** [comment]
Hello,

I encounter the problem, when I click on the object I have this error Unable to load data: cache: key is missing
How to solve this problem?

Thanks for your help

**Comment by samof76** [comment]
I have the same issue!

**Comment by AbdoulRahimBarry** [comment]
Hello @samof76 

I was able to solve the problem by deleting the redis pod, the deployment automatically recreated a new pod and it continues to work

But I don't know if this is the right way

**Comment by iakpabio** [comment]
Solved by Sync - select Prune, Force, and Replace options to recreate the pods or application. You may want to de-select any ingress or namespace resources so you are not stuck or deleting all your resources in the namespace.

**Comment by abdennour** [comment]
Rollout all deployment/statefulset of argocd. `kubectl -n $ns rollout restart $(kubectl  -n $ns get deploy -o name)`
That's fix the same issue which happen for us after a downgrade (I mean after `helm -n $ns rollback argocd`)

**Comment by rahul-captionh** [comment]
I have same issue and try everything mentioned above, but no changes, issue continues

**Comment by vl-kp** [comment]
v2.7.2+cbee7e6.dirty
tried all above, but still same
tried to delete the application and re-sync, still same

**Comment by rahul-captionh** [comment]
you should go to all your deployment and statefulset  and fix it to same version 2.7.2
