### ISSUE TITLE
hydrator(ui): refresh revision metadata in hydrator panel

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#19493]
The source hydrator panel contains dry commit metadata.

When the hydrator is refreshed, and a new commit is handled, the metadata still shows the info for the old commit.

This video demonstrates the problem:

https://github.com/user-attachments/assets/423fdfac-320f-495b-a5b0-91d591d19d29

The "comment" field should say "Two replicas".

<img width="279" alt="image" src="https://github.com/user-attachments/assets/ff2bcba4-e050-4674-a250-07c80921183c">

**Comment by Jack-R-lantern** [comment]
The issue appears to be resolved in this [PR](https://github.com/argoproj/argo-cd/pull/19580).
The issue should be closed
