### ISSUE TITLE
The ArgoCD v2.12.0 doesn't work with tag tracking

### ISSUE THREAD

**Issue by jackalbsd** [argoproj/argo-cd#19495]
Hello.

Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**

Unfortunately, after we did upgrade from version v2.8.3 to v.2.12.0 the tag tracking doesn't work anymore.

**To Reproduce**

This configuration doesn't work anymore

``` sources:
    - repoURL: https://github.com/org/repo
      path: .
      targetRevision: "0.41.36" 
```

**Expected behavior**

The Sync status is expected to be - **Sync OK**

**Version**

```shell
{
  "app.kubernetes.io/component": "server",
  "app.kubernetes.io/instance": "argocd",
  "app.kubernetes.io/managed-by": "Helm",
  "app.kubernetes.io/name": "argocd-server",
  "app.kubernetes.io/part-of": "argocd",
  "app.kubernetes.io/version": "v2.12.0",
  "helm.sh/chart": "argo-cd-7.4.1",
  "pod-template-hash": "75d8977c45"
}


```

**Logs**

```
{"error":"error parsing version for tag: Version segment starts with 0","grpc.code":"Unknown","grpc.method":"GenerateManifest","grpc.service":"repository.RepoServerService","grpc.start_time":"2024-08-12T13:03:37Z","grpc.time_ms":613.995,"level":"error","msg":"finished unary call with code Unknown","span.kind":"server","system":"grpc","time":"2024-08-12T13:03:37Z"}
```

Thank you for the help

**Comment by jackalbsd** [comment]
I would like to share a small update from my side.

If you use commit hash there will be no issue.
![2024-08-13 09 03 57](https://github.com/user-attachments/assets/b9222fa5-48bb-4f02-9057-9e580c6c1f13)

**Comment by ChristianCiach** [comment]
The only relevant code change between v2.8.3 and v2.12.0 seems to be:

* https://github.com/argoproj/argo-cd/pull/17566

But it's still strange, because the added unit tests explicitly test versions with a starting zero.

**Comment by jackalbsd** [comment]
Yes, I found this PR when I tried to find something that could help me to solve this issue.

I am going to do some test. I will post updates here.

**Comment by migueleliasweb** [comment]
I'm hitting something similar where my app in Argo defined in a central repo but points to another repo for its source. The tag is being tracked correctly but the UI links the tag anchor to the "parent" repo instead of the repo of the app itself.

Argo's functionality itself isn't broken (afaik) but the UI points to the wrong location when clicking on the tag link.

**Comment by jackalbsd** [comment]
Hello.
I checked version v.2.11.7

```
{
    "Version": "v2.11.7+e4a0246",
    "BuildDate": "2024-07-24T09:33:49Z",
    "GitCommit": "e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.4+g81c902a",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

and it works
<img width="1015" alt="Screenshot 2024-08-19 at 16 48 35" src="https://github.com/user-attachments/assets/2ee5b993-7641-4cd9-9404-78cedd24e197">

**Comment by migueleliasweb** [comment]
Thanks for testing v2.11.7 @jackalbsd. 

From the comment of @ChristianCiach , our issue seems related to users with certain semver tags. My revision has the format ` v1.23-build-123+env-name `.

I'll try to isolate that code and test to check if there are cases where certain revisions end up breaking something.
