### ISSUE TITLE
Allow to exclude specific resources from diff targets

### ISSUE THREAD

**Issue by kk-mats** [argoproj/argo-cd#19507]
# Summary

To calculate diff between resources of live state and repository, argocd should not fetch resources in blacklist.

# Motivation

I'm trying to use argocd with a remote k8s cluster which is managed by my company's infra group.
Due to company's policy, app team can have serviceaccounts with very limited permissions.

I want to excude resources that are not permitted to access by the serviceaccount but I cannot find a way to do so.
I found resource whitelist/blacklist but they seemed for different requirement.

For instance, even though I have added `extensions.dashboard.tekton.dev` to the blacklist, I still saw the following error message in diff tab.

`
Unable to load data: error getting cached app managed resources: ComparisonError: Failed to load live state: failed to get cluster info for "<>": error synchronizing cache state : failed to sync cluster : failed to load initial state of resource Extension.dashboard.tekton.dev: extensions.dashboard.tekton.dev is forbidden: User "<>" cannot list resource "extensions" in API group "dashboard.tekton.dev" in the namespace ";ComparisonError: Failed to load target state: failed to get cluster version for cluster "<>": failed to get cluster info for "<>": error synchronizing cache state : failed to sync cluster <>: failed to load initial state of resource Extension.dashboard.tekton.dev: extensions.dashboard.tekton.dev is forbidden: User "<>" cannot list resource "extensions" in API group "dashboard.tekton.dev" in the namespace "<>"
`

# Proposal

Currently argocd needs to fetch live state of any resources for diff even they are contained in blacklist.
I would like to request to change this behaviour to not fetching live state of resources in blacklist.

**Comment by crenshaw-dev** [comment]
I think this might be what you're looking for: https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#auto-respect-rbac-for-controller

**Comment by kk-mats** [comment]
Thabk you for checking my request.
Unfortunatelly, after setting `strict` to the option, I still get the same errors.

Here is the current cluster setup:
- Local k8s cluster on Docker Desktop: Where argocd is running with full access serviceaccount
- Remote k8s cluster on on-premise DC: Where argocd on local cluster should deploy projects. serviceaccount with limited permissions are available due to company's policy.

Can `respectRBAC` check permissions of serviceaccount being used to connect the remote cluster?

**Comment by kk-mats** [comment]
I noticed I forgot to restart application-controller statefulset after updating respectRBAC.
It works fine once they got restarted.
Thank you so much.
