### ISSUE TITLE
PR got check failed and blocked by License Compliance check

### ISSUE THREAD

**Issue by JessieTeng89** [argoproj/argo-cd#19546]
I have 4 PRs go check failed and blocked by License Compliance check, can anyone tells me how to resolve it, appreciate it.
https://github.com/argoproj/argo-cd/pull/19450
https://github.com/argoproj/argo-cd/pull/19468
https://github.com/argoproj/argo-cd/pull/19505
https://github.com/argoproj/argo-cd/pull/19532

**Comment by pasha-codefresh** [comment]
@JessieTeng89 thank you for reporting this. This check is optional and it is not blocking ability to merge

**Comment by JessieTeng89** [comment]
> @JessieTeng89 thank you for reporting this. This check is optional and it is not blocking ability to merge

Thanks, got it, I will close this issue.

**Comment by JessieTeng89** [comment]
@pasha-codefresh 
One of the PR was merged, appreciate it if you could help to review the other ones
Thanks
