### ISSUE TITLE
Add additional websocket tests

### ISSUE THREAD

**Issue by reggie-k** [argoproj/argo-cd#19550]
# Summary

The websocket functionality for pod exec needs further unit testing and e2e testing.

# Motivation

Currently only the surrounding functionality is being tested (such as permission validation, testing server connection, etc)

# Proposal
Unit tests for read and write:
https://github.com/argoproj/argo-cd/blob/master/server/application/websocket.go#L163
https://github.com/argoproj/argo-cd/blob/master/server/application/websocket.go#L213

New e2e tests are also needed.

The PR for this should be prefixed with `test: `

**Comment by nitishfy** [comment]
I'd like to take this up.

**Comment by nitishfy** [comment]
Hi, I'd like to take this up. Can you provide me answers for a couple of questions here:

1.  How can I test the websocket functionality for pod exec locally? Has this documented somewhere?
2. We are required to add the unit tests for the above functions you've added in the issue description, correct?
