### ISSUE TITLE
Request OIDC groups claim if groups scope is not supported

### ISSUE THREAD

**Issue by sboschman** [argoproj/argo-cd#1956]
**Is your feature request related to a problem? Please describe.**
Not all OIDC providers support a groups scope (like OneLogin and Microsoft) and do not return the groups claim as part of the ID token. Still, these OIDC providers might support a custom 'groups' claim if explicitly instructed to do so.

**Describe the solution you'd like**
Based on the OIDC config it is possible to check whether or not the OIDC provider supports the groups scope. If the groups scope is not supported, add an explicit 'groups' claim request for the ID token.

**Comment by alexec** [comment]
@jessesuen this is your area of expertise?

**Comment by jpresky** [comment]
I was trying to set up OneLogin as an IDP for ArgoCD today but was unsuccessful.

If I am interpreting this issue and #1957 correctly, does this mean OneLogin OIDC will not work with ArgoCD until an explicit 'groups' claim request is supported?

**Comment by sboschman** [comment]
@jpresky OIDC with Okta, OneLogin and Microsoft should work, as these three support a custom 'groups' scope. The change #1956 / #1957 is for other OIDC providers which do not support such a custom/special groups scope.

From the OneLogin docu (https://developers.onelogin.com/openid-connect/scopes):
> Our OIDC implementation supports a special groups scope that provides role or group information for a user.

**Comment by jpresky** [comment]
Thanks. I misunderstood your initial comment. I was able to get Onelogin to work with ArgoCD.
