### ISSUE TITLE
Argo CD UI: Sync Only Missing and/or OutOfSync

### ISSUE THREAD

**Issue by stgarf** [argoproj/argo-cd#1961]
<img src="https://github.com/argoproj/argo/raw/38c4def7fb100e954757649553db8c04ea64f318/argo-logo600.png" align="right" width="100" height="auto"/>
<br/>

**Is your feature request related to a problem? Please describe.**
Yes. In the UI I'm often frustrated when I only want to sync `missing` or `out of sync` resources and I have to _manually select_ only the `missing` or `out of sync` ones in the UI.

**Describe the solution you'd like**
In addition to the `All` / `None` javascript selection options links (in the sync UI) there should be a `Missing` and/or `OutOfSync` javascript link that selects only "missing" or "out of sync" resources.

![Screen Shot 2019-07-19 at 10 33 31 AM](https://user-images.githubusercontent.com/1694002/61554441-ceab2780-aa11-11e9-90a3-2bcc203e71e6.png)

**Have you thought about contributing yourself?**
Maybe if I have time outside of my required day job activities :)

**Comment by jessesuen** [comment]
Makes sense to me.

**Comment by alexec** [comment]
This would be a great one for community contribution. You'd only need to know Javascript+React as I don't think this has backend changes.

**Comment by stgarf** [comment]
Great!

**Comment by alexec** [comment]
Comment on this ticket. Selective syncs do not get recording in the history for rollback.
