### ISSUE TITLE
Connection to external k8s Cluster failes with "Unable to connect to cluster: specifying a root certificates file with the insecure flag is not allowed"

### ISSUE THREAD

**Issue by Sicaine** [argoproj/argo-cd#1965]
Hi,

i installed argocd on my local [k3s](https://github.com/rancher/k3s/blob/master/README.md) cluster and trying to add a kubernetes cluster from digital ocean. in-cluster works fine, the external cluster shows the error message:

***Unable to connect to cluster: specifying a root certificates file with the insecure flag is not allowed***

My k8s endpoint for digital ocean is the following: https://e776a539-12a4-477e-820f-9204e899e35c.k8s.ondigitalocean.com/ (so you can see what certificate we are talking about).

I configured my cluster through this (with filled out data):
```
apiVersion: v1
kind: Secret
metadata:
  name: do-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: main
  server: <url>
  config: |
    {
      "bearerToken": "<authentication token>",
      "tlsClientConfig": {
        "insecure": true,
        "caData": "<cadata>"
      }
    }
```

If i do not set it to **"insecure": true** it will complain that the cluster certificate authority is not trusted.

The only thing i could find which sounds similiar is this bug description: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/189 but otherwise im lost. I checked the corresponding ~/.kube/config but it wasn't configured as stated.

**How to reproduce**
- install k3s
- install argocd on k3s
- add external digital ocean cluster through Secret

![argocdscreenshot](https://user-images.githubusercontent.com/717768/61596399-70459b00-ac03-11e9-9989-bd0e82a0db0e.png)

**Comment by jannfis** [comment]
Hi,

I believe this is because you specify `caData` and it probably contains the CA for your K8S endpoint.

Your options would be:
1. Remove `caData` field and leave `insecure` to true
2. Get correct data for `caData` and leave `insecure` to false (or remove it all together)

Since `caData` is a public datum anyway, would you mind sharing what you used as data there?

**Comment by jannfis** [comment]
Oh just to clarify, the `caData` is **not** your client certificate used to connect to the K8S API endpoint. So if you put that data in the `caData` field, please do not share it, of course.

**Comment by Sicaine** [comment]
So i took the caData from the .kube/config file i get directly from digital ocean. The base64 encoded data looks like this:

```
"caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHhPVEExTVRneApOVEkwTXpGYUZ3MHpPVEExTVRneE5USTBNekZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEUU9pa1FwVExVVVEvUm1lR01DdlJvcnJNbzNUR3o1ck02VGh1Rk9BR0NiNEdVNHlPYQovVXhpM3JpOGZHNXNCQ1c2RkU2bGx3eDlFRkE4T0ZMT2ZEUWtVbVI5cGdsQmpaOHhFQlB3SUFwNDArTS81TU9HCkRSWDlhcERQajlkNThRU1IxS25HQ0p3eWdnMXZtSGRUQXNiVU52ZG42ZGtOZVlsbHFsSWhvMjlIbjl0K3ppUFoKVGpvZXJnNzlwSHk2VFdkWVhENUoxL0VQcmZ0TU1GUFBieHhMNGpCZDY2SkFkbXZqZnlMekp0RGVYYnRvM08wbgpXSjFnUE04R0JleDZ0Y2RNRHRnTHY2di9iK1llUklZVnZKWHM5ejc0VHMwaW5UUERTclVJUjFHSmt5MGZSTVFaCmxBMlJtZUIyWHhvcTZ2SWtzL2NUSWxhN20xUlZzMzJWT3hiSkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNURS9ralVneUV3WTNOUUV0UApSdGxJNU9MSzRqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFZR1RDUU1wMW1FKzRYVG0xbklVWFYrRjYvdWlYCmhzdFN1cktpRitRWUUyQlBVbEExeG1BN3NSN3N6YUltU2RYVW1tMmdjSEJld2F0dktLYS9lc3h6OFlNZ1RITFkKVmszdGxPdVowUmdCQjRyOTRLL1VwTSs2QmxQNm1HbE44UGtXSDlnQnltS3FDV2lvb0tCTGwrSU5sbGNuZWFiUwp0cDQ1MmxsVndvK0NIT0JhVGo5NmVjNmJMSG5xNDZ2QXdDOWhKS1VZaVlKVW1aZHZyTG8zK0tnRzJ1TmJGQ20zClh5aHU1ZlV6bTBXVy9oT24yRVJWaVlIb2xFenQ2S2RKbDBMNHhBK0xtR2wwM25pbXlYc0tGY0lNbFhlVS8zKzgKcCs0TEdhNGtydDd0bzFhaFRHcDNxaDM2OWxSYVFRdVMwNnRmUFp3a28vbzdCTEREcnIvRUkrWXhRUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
```

If i just remove this field, i do get another error message: ***error: specifying a root certificates file with the insecure flag is not allowed***

**Comment by jannfis** [comment]
OK, so the data in the `caData` is valid after all, I can validate the connection to your K8S endpoint using the data after base64 decoding it and saving the PEM in `~/docean.crt`:

```
curl --cacert ~/docean.crt https://e776a539-12a4-477e-820f-9204e899e35c.k8s.ondigitalocean.com/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```
Does it work with `insecure: true` and no `caData` parameter at all?

**Comment by Sicaine** [comment]
I can't apply it when i leave out caData parameter:  **error: specifying a root certificates file with the insecure flag is not allowed**

**Comment by jannfis** [comment]
How do you apply it? Using `kubectl` directly on the cluster or using self-managed ArgoCD?

I'm asking because the error message you described is generated in the K8S API itself, and I believe ArgoCD passes the `tlsClientConfig` data in a verbatim way to the K8S API. And the K8S API doesn't like both `insecure` and `caData` to be set together and throws an error.

**Comment by Sicaine** [comment]
I apply only the secret directly through kubectl (k3s kubectl). I haven't installed this bitnami git secret thing.

Not sure exactly about your sentence with verbatim/argo. Should it work if i apply it manually or if argocd would do it?

**Comment by jannfis** [comment]
Sorry, what I ment was, that I would expect `kubectl` ignoring the contents of this secret when you edit it (except for general syntax issues).

So just to get it straight if I understood you correctly:
- You use `kubectl apply -f yoursecret.yaml` to apply a YAML with `insecure: true` and which contains no  `caData` field
- `kubectl` spits out the error message you mentioned above

Is that correct?

**Comment by jannfis** [comment]
On another thought, have you tried deleting the secret and re-creating with just one of `caData` or `insecure` set?

**Comment by Sicaine** [comment]
Uh ah :-) my bad sry! The error message from kubeapi was through a change i did to the k3s .kube/config while playing around with the issue.

Your suggestion works! \o/

Tx!

**Comment by Sicaine** [comment]
So is this behavior now different to kubectl and therefore not a bug? Should i close it? Should i recreate it with a description as it validates certificates different?

**Comment by jannfis** [comment]
Hm, I'm unsure whether this qualifies as a valid bug to be honest. The question it boils down to is imho, does the connection from ArgoCD to your K8S cluster works when you either
- set `insecure` to `false` or
- populate `caData` with the correct contents of your remote K8S API server

in the `tlsClientConfig` part of the cluster config secret. 

Specifying both is apparantly not allowed by the K8S client API and you finally resolved your main issue by editing your kubectl's `config` after all, I think?

**Comment by Sicaine** [comment]
True but you checked the caData as well as i. Its the exact thing from .kube/config.

But i guess you will become aware if something similiar happens again anyway. I will just close the ticket.

Tx again for your help :)
