### ISSUE TITLE
Add a label explaining what filters are for in the left panel

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [argoproj/argo-cd#19699]
# Summary

The filters on the left panel may apply to applications or resources, depending on what view we are in. It's not obvious that filters context changes when we go to a specific application, so it's better to add a label telling what filters are for (applications, resources).
![Screenshot 2024-08-27 at 8 06 50 AM](https://github.com/user-attachments/assets/511899a8-5850-435b-a7c4-7c51d9ee8f9f)
![Screenshot 2024-08-27 at 8 06 56 AM](https://github.com/user-attachments/assets/ec1e273c-f19b-46b9-8c29-1c470393e037)

# Motivation

Based on a feedback of UI engineer new to Argo it wasn't obvious what the filters are for and that they change when the view changes. It's better to make it more clear what the filters are for.

# Proposal

Put a label above the filters with a text like "Application Filters" or "Resource Filters". The text may have a line below it.

**Comment by crenshaw-dev** [comment]
Or "Resource sync status"

**Comment by crenshaw-dev** [comment]
@rbreeze thoughts?

**Comment by JessieTeng89** [comment]
I can work on this enhancement if we got the decision how to change.

**Comment by andrii-korotkov-verkada** [comment]
@JessieTeng89, maybe we can just add a label below "Documentation" with something like "Application filters" or "Resource filters"? I can bring this up again with Argo maintainers.

**Comment by surajyadav1108** [comment]
I will add these
