### ISSUE TITLE
Arbitrary file access during archive extraction ("Zip Slip")

### ISSUE THREAD

**Issue by McGon-Fid** [argoproj/argo-cd#19710]
While working on argo I came across a codeql issue which can be addressed easily. It's a zip slip issue - details here:

codeql issue:
rule - go/zipslip
severity - error
level - high

Summary: Arbitrary file access during archive extraction ("Zip Slip")

Unsanitized archive entry, which may contain '..', is used in a file system operation.
Unsanitized archive entry, which may contain '..', is used in a file system operation.
Unsanitized archive entry, which may contain '..', is used in a file system operation.

**Comment by jsoref** [comment]
I believe this is a false positive and I've filed https://github.com/github/codeql/issues/17573 about it.
