### ISSUE TITLE
Performing automated syncs on daily basis

### ISSUE THREAD

**Issue by alnsantosh** [argoproj/argo-cd#1971]
Is it possible to do automated syncs on daily or weekly basis (eg: using some sort of cron job to do the syncs) by using only Kubectl commands (without using Argo CLI)

**Comment by alexec** [comment]
There is not built in feature for this. You could set-up a Jenkins job to do this.

**Comment by alnsantosh** [comment]
@alexec Thank you for the quick response. 
I am new to dev ops. I would really appreciate if you could direct me towards an example or could Gove an elaborate explanation so that I can get better understanding .

**Comment by alexec** [comment]
Please try:

https://argoproj.github.io/argo-cd/

And, as you'll need to use the CLI:

```
argocd --help
```

**Comment by alnsantosh** [comment]
Please let me know if there is a way to sync the application using Kubectl commands (or applying some yams configs) instead of using ArgoCD CLI. I am looking for a way to sync without using ArgoCD CLI.

**Comment by alexec** [comment]
Sorry. There is no way to sync without using CLI or UI.

**Comment by alnsantosh** [comment]
In order to use UI, I am using localhost:8080. Please let me know the way to get an external IP so that everyone in the network can access the UI page

**Comment by alexec** [comment]
Do you still need help please?
