### ISSUE TITLE
Update contributing guide to support Git LFS

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1974]
**Is your feature request related to a problem? Please describe.**

It is no longer possible to build Argo CD locally using the guide's instructions because you must install Git LFS.

**Describe the solution you'd like**

Update the guide.

**Comment by alexec** [comment]
@jannfis thoughts?

**Comment by alexec** [comment]
Might be good to list when you'd use LFS too.

**Comment by jannfis** [comment]
> Might be good to list when you'd use LFS too.

I'm unsure if I get what you mean by this

**Comment by alexec** [comment]
I wasn't clear why you'd ever use this. I thought - _"surely your configs would always be small files" but I see that you might want to add `.tar` files
