### ISSUE TITLE
Argo CD do not sync properly once the annotation is removed

### ISSUE THREAD

**Issue by nitishfy** [argoproj/argo-cd#19756]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

A strange bug that I came across just now while trying to play with [manifest path annotation](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#manifest-paths-annotation). This is how my project structure look like for the setup
```
manifests:
- dev
  - deploy.yaml
- staging
  - deploy.yaml
- prod
  - deploy.yaml
 ```
In my Argo CD application manifest, I set the recurse:true` that means all the resources in the sub-directory will be in sync. Now, my resources are in sync with the git repo. Now, I go ahead and add an annotation to the Argo CD application [argocd.argoproj.io/manifest-generate-paths](http://argocd.argoproj.io/manifest-generate-paths): ./prod  that makes sure that the sync will only happen whenever i make changes to the deployment file in the prod and not anywhere in my manifests folder. I apply the manifest and try to update the replica of the staging deployment, and as expected, it doesn't update (why? because of the annotation). Here is when things goes interesting - I add a deployment file in my manifests folder, something like manifests/deployment.yaml  and as expected when pushed to master, the deployment didn't get created (why? because of the annotation since we have specified argo to only sync when changes are made in the prod).
Now I remove the annotation and apply the changes again. Ideally, since our annotation has been removed, the deployment that was created in the manifests folder should automatically be created, but it doesn't.

**To Reproduce**

1. Set Up a Git Repository with the Required Structure:

```
manifests/
├── dev/
│   └── deploy.yaml
├── staging/
│   └── deploy.yaml
└── prod/
    └── deploy.yaml
```
Ensure each deploy.yaml file has a basic Kubernetes deployment definition.

2. Create an Argo CD Application with recurse: true:

3. Create an Argo CD application manifest (e.g., argocd-app.yaml) with the following configuration:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<your-repo-url>'
    targetRevision: master
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    directory:
      recurse: true
```
Apply this manifest to Argo CD to create the application:

```
kubectl apply -f argocd-app.yaml
```
Ensure all resources from manifests/dev, manifests/staging, and manifests/prod are synchronized with the Argo CD application.

4. Add the` argocd.argoproj.io/manifest-generate-paths Annotation`:

5. Update the Argo CD application manifest to include the annotation:

```
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ./prod
```
Apply the updated manifest:

```
kubectl apply -f argocd-app.yaml
```
Verify that Argo CD is only syncing resources under manifests/prod.

6. Make a change to the `manifests/staging/deploy.yaml file` (e.g., change the number of replicas). Verify that the change does not trigger a sync in Argo CD (as expected due to the manifest-generate-paths annotation).

7. Add a New Deployment in the manifests Directory:

8. Add a new deployment file, `manifests/deployment.yaml`, with a basic Kubernetes deployment definition. Verify that the new deployment is not created in the cluster (again, as expected due to the annotation).

9. Remove the argocd.argoproj.io/manifest-generate-paths annotation from the Argo CD application manifest. Apply the updated 
```
kubectl apply -f argocd-app.yaml
```

At this point, the new deployment `(manifests/deployment.yaml`) should automatically be created since the annotation has been removed, and recurse: true is still enabled.

**Expected behavior**

 The new deployment `(manifests/deployment.yaml`) should automatically be created since the annotation has been removed, and recurse: true is still enabled.

**Screenshots**

![image](https://github.com/user-attachments/assets/bc03e142-a992-485f-83c5-b4c40fc38e30)
![image](https://github.com/user-attachments/assets/b42ad338-db93-4f26-89e2-123834453447)

**Version**

```shell
argocd: v2.11.7+e4a0246
  BuildDate: 2024-07-24T10:10:59Z
  GitCommit: e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb
  GitTreeState: clean
  GoVersion: go1.21.12
  Compiler: gc
  Platform: linux/amd64
```

**Comment by agaudreault** [comment]
To summarize, everything works as expected, but when you remove the annotations, you wonder why your application does not pick up the changes. 

The reason is because your Application already detected that the commit X did not contains any relevant changes when X was made. Now, you remove the annotations. The Application will not re-evaluate the commit X again. 

I believe you can do a hard refresh to re-evaluate the commit X so it picks up the changes.
