### ISSUE TITLE
Members of a group bound to a role should be able to generate tokens for that role

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1977]
If a user is bound to a project role through an OIDC group, then the user should be able to generate a token for that role. This is true even if the user does not have "update" permissions to the project.

This solves a problem of developer teams not having sufficient self-service permissions to the project. e.g. it would allow operators/admins to provision projects for the developer, assign them with an admin-like role for the project, but still allow the developer to generate tokens to act on behalf of that role (for automation purposes).

**Comment by jessesuen** [comment]
Whoever is fixing this should also fix this bug in the code:

```golang
func (s *Server) DeleteToken(ctx context.Context, q *project.ProjectTokenDeleteRequest) (*project.EmptyResponse, error) {
	if err := s.enf.EnforceErr(ctx.Value("claims"), rbacpolicy.ResourceProjects, rbacpolicy.ActionDelete, q.Project); err != nil {
		return nil, err
	}
```

Deleting a token does not require project delete permissions. It requires the same privileges as token generation.

**Comment by simster7** [comment]
I can work on this!

**Comment by alexec** [comment]
@simster7 have you started on this please?

**Comment by simster7** [comment]
Haven't started yet, but planning on working on it. If someone takes this on beforehand just let me know!

**Comment by alexec** [comment]
working on this now

**Comment by alexec** [comment]
I'm at a bit of a loss as to how to implement this. We changing this security constraint to allow users who how the project role in their OIDC role to create. I can't see a similar example in the code, so I think this is something like:

```golang
	user := getAuthenticatedUser(ctx)
	hasRole := s.enf.HasRoleForUser(user, q.Role)
	if !hasRole {
		return nil, fmt.Errorf("user does not have the role %s", q.Role)
	}
```
