### ISSUE TITLE
Option to disable swagger-ui endpoint

### ISSUE THREAD

**Issue by svghadi** [argoproj/argo-cd#19780]
# Summary

Provide a option to disable the authenticated `/swagger-ui` endpoint which serves the api documentation.

# Motivation

Api docs are served on `<argocd-url>/swagger-ui` endpoint without authentication. Even though these docs are the same across different Argo CD instances and don't pose a security risk when exposed, some of the users are interested is disabling it. 

# Proposal

Make the endpoint configurable via a `argocd-cm` configmap key (eg: `disableSwaggerUI: true`) or a cli argument to `argocd-server` (eg: `--disable-swagger-ui`)

**Comment by crenshaw-dev** [comment]
Any reason not to just disable it at the ingress?

**Comment by svghadi** [comment]
Not specifically, I didn’t consider that approach. I was looking for a simpler solution.

**Comment by crenshaw-dev** [comment]
Fair. I'm in favor of fewer options in Argo CD if possible, but if we need it we need it.  🙂

**Comment by svghadi** [comment]
Copying comment(https://github.com/argoproj/argo-cd/discussions/16791#discussioncomment-10541742) from related [discussion](https://github.com/argoproj/argo-cd/discussions/16791) for code reference 
> [pasha-codefresh](https://github.com/pasha-codefresh)
> Unfortunately no, but should be pretty easy to support it
> 
> https://github.com/argoproj/argo-cd/blob/a0a5a186d970063919e7b4d6e942e60cf43f6de7/server/server.go#L1076

**Comment by andrii-korotkov-verkada** [comment]
@svghadi, do you still need the option?

**Comment by svghadi** [comment]
It would be good to have this option.

**Comment by crenshaw-dev** [comment]
If there's no pressing need, and if network rules can generally solve the problem, I'd rather avoid adding Argo CD code for this relative edge case.

**Comment by svghadi** [comment]
Understood. That sounds reasonable. I'll reopen the issue if there’s a pressing need from users in the future.

**Comment by svghadi** [comment]
Understood. That sounds reasonable. I'll reopen the issue if there’s a pressing need from users in the future."

**Comment by crenshaw-dev** [comment]
@anilreddy103 we could probably add code on the server to send that. Can you open a new issue? Or even better, PR? 🙂

**Comment by anilreddy103** [comment]
Created the issue: https://github.com/argoproj/argo-cd/issues/22877
Unfortunately, I do not know go lang to raise a PR.

**Comment by yafeiaa** [comment]
> 创建了问题：[#22877](https://github.com/argoproj/argo-cd/issues/22877) 不幸的是，我不知道如何使用 go lang 来提出 PR。

@anilreddy103 I've submitted a PR to add the X-Frame-Options header to the Swagger UI endpoint. This should address the security concern raised by your security team. You can find the PR here: #23082

The implementation adds the X-Frame-Options header with value "DENY" to prevent clickjacking attacks. Let me know if you have any questions or if there's anything else you'd like me to explain. https://github.com/argoproj/argo-cd/actions/runs/15158916682/job/42620250043?pr=23082

**Comment by hariyedlapalli** [comment]
> If there's no pressing need, and if network rules can generally solve the problem, I'd rather avoid adding Argo CD code for this relative edge case.

@crenshaw-dev we are running on OpenShift using Routes, not Ingress. Since Ingress is not used in our setup, this cannot be blocked at the Ingress level.
