### ISSUE TITLE
Specifying namespace for plugin generator in Akuity managed Argo instance

### ISSUE THREAD

**Issue by kushagra-saxena-exa** [argoproj/argo-cd#19796]
# Summary

When using Application Set Plugin generator in a local running argo instance, It works seamlessly since the configuration configmap for the plugin generator is created in same namespace as the instance and hence applicationset controller is able to find it. 
However in case of akuity managed argocd instance, the argo instance is running on control plane managed by akuity. So, I am unable to create any configmap there for the plugin generator configuration and hence the applicationset controller is unable to find it and it doesn't work at all.

# Motivation

I was working on some application deployment and planning to use my custom wrote plugin to provide the list of applications to create.
So, with my custom plugin in place, I can have my deployment configuration changed to helm or kustomize just be changing the applicationset spec.

# Proposal

I think that the namespace can be passed with plugin generator configuration in Applicationset definition and applicationset controller should look for the configmap in the same namespace.
So, we can have be placing the configmap in any namespace and passing the value in the plugin generator spec definition.

How do you think this should be implemented?

**Comment by reedjosh** [comment]
I'd also like to piggy-back that RBAC + ApplicationSets in any namespace + the current configmap model does not work.
