### ISSUE TITLE
UI goes haywire when you create a new project, with a previously created project still syncing

### ISSUE THREAD

**Issue by ggeldenhuis** [argoproj/argo-cd#19819]
{
    "Version": "v2.12.3+6b9cd82",
    "BuildDate": "2024-08-27T11:57:48Z",
    "GitCommit": "6b9cd828c6e9807398869ad5ac44efd2c28422d6",
    "GitTreeState": "clean",
    "GoVersion": "go1.22.4",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.4.2 2024-05-22T15:19:38Z",
    "HelmVersion": "v3.15.2+g1a500d5",
    "KubectlVersion": "v0.29.6",
    "JsonnetVersion": "v0.20.0"
}

I can fairly reliably recreate the problem.

1. Create a new application ( Using the UI )
2. Whilst the application is syncing create another application by clicking on "+NEW APP"
3. As you type the name of application, the UI starts typing on its own and goes into a loop preventing you from doing anything

The only way out of this is to close the window and create a new window.

I am using Google Chrome Version 128.0.6613.85 on Mac 14.6.1 (23G93)

This only appears to happen if the previously created application is still syncing if it has finished syncing then the UI does not misbehave.

**Comment by ggeldenhuis** [comment]
It also appears to happen when you type the path name. In our case we have a a few different kustomize paths and if mistype and type a few times the UI then gets in the same endless loop as described above.

**Comment by rcfja** [comment]
I'm experiencing this same issue.

**Comment by surajyadav1108** [comment]
seems like a debounce state issue in the form 🤔

**Comment by keithchong** [comment]
I can reproduce this problem.  This should be fixed by https://github.com/argoproj/argo-cd/pull/19717, which was cherry picked (https://github.com/argoproj/argo-cd/pull/20508) back to the 2.12 branch, and likely will be in the 2.12.7 release.

**Comment by blakepettersson** [comment]
Should be fixed with 2.12.7
