### ISSUE TITLE
Upgrading to v2.12.x causes charts to sync back and forth between older versions

### ISSUE THREAD

**Issue by trevorlauder** [argoproj/argo-cd#19827]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Upgrading to any `v2.12.x` release causes our applications to claim they are out of sync and sync back to old versions of the chart and then back to the new one (this happens in seconds), sometimes it goes several versions into the past.  Each time you click refresh it just seems to pick a random version to sync with.  This happens in 3 out of 4 clusters, the only difference with the one that isn't experiencing the issue is it's deploying the chart based on the commit and the ones with the issue are deploying based on a tag.  The charts are synced from GitLab using HTTPS.

**To Reproduce**

Upgrade from `v2.11.x` to any `v2.12.x` release.

**Expected behavior**

Charts should not be flapping versions back to older releases randomly.

**Screenshots**

**Version**

```shell
argocd: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T12:18:06Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.22.6
  Compiler: gc
  Platform: linux/arm64
argocd-server: v2.12.3+6b9cd82

```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by andrii-korotkov-verkada** [comment]
Seems like it may be a caching issue on the repo server. What's your app refresh timeout (if configured to be different from default 3 min)? Do you have webhooks setup to trigger app refresh immediately?

**Comment by trevorlauder** [comment]
I'll also mention that I can click refresh as many times as I want right after each other and on v2.11.x it doesn't flap between versions at all.  If I do that on v2.12.x or wait for it to refresh manually, it flaps back and forth.

**Comment by andrii-korotkov-verkada** [comment]
Just to check, are you running in HA mode? If so, are your Redis instances stable, i.e. not restarting often?

**Comment by trevorlauder** [comment]
> Just to check, are you running in HA mode? If so, are your Redis instances stable, i.e. not restarting often?

Yes, there are 3 Redis instances running and they are stable.

I don't think this has anything to do with caching, the behavior is only seen on our instances that use version tags.  The one using git commits for the target revision works just fine with v2.12.x.  It feels like it gets confused as to which tag is the latest.

**Comment by andrii-korotkov-verkada** [comment]
Ah, sorry I'm not that familiar with tags logic, only have experience with target revision. I may try to investigate still.

**Comment by andrii-korotkov-verkada** [comment]
Do you update those target revisions periodically? I usually just use HEAD or a branch name.

**Comment by trevorlauder** [comment]
Yes, the tags are used to control which version is deployed to a given environment so they are updated as specific versions of the chart are promoted to each environment.  They have been working just fine for over 2 years and I've kept our clusters pretty current with each version of Argo CD.  v2.12.x is the first version to have this issue.
