### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by cleybersilva** [argoproj/argo-cd#19873]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by cleybersilva** [comment]
Bug

**Comment by crenshaw-dev** [comment]
Please add details
