### ISSUE TITLE
Regression in network view

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1989]
This view shows as disconnected, but should be connecting the service to ingress.

![image](https://user-images.githubusercontent.com/12677113/61753489-5cfe1100-ad64-11e9-94ed-63f32dab45bf.png)

Not sure if UI or backend bug

**Comment by alexmt** [comment]
Ah, it is UI indeed regression. Fix: https://github.com/argoproj/argo-cd/pull/2001

If 1.2 testing a lot of time we might consider creating patch release 1.1.2

**Comment by gfernandez1988** [comment]
we are experiencing this issue, traffic flows from the ingress to the svc but argocd shows them as disconnected
![imagen](https://user-images.githubusercontent.com/30290450/143212978-9d403811-00b2-4035-8bee-7f721e629187.png)
k8s version: 1.19.13
argocd version: v2.1.7+a408e29

**Comment by cxsimon** [comment]
+1 on this one

**Comment by gfernandez1988** [comment]
> +1 on this one, linked #8741 what version has the fix?

solved by upgrading to v2.2.4
be careful with the configmaps storing the repository connections, they newer version didn't recognised them and we had to reconect them manually

**Comment by graipher** [comment]
Seeing it again:
![Unbenannt](https://user-images.githubusercontent.com/984262/181179421-2852deb3-349e-4e5f-881e-4401032fd3e0.png)

k8s version: 1.21
argocd version: v2.4.0+91aefab
