### ISSUE TITLE
The sync status of the application and git is stuck at unknown due to an error in the repo server

### ISSUE THREAD

**Issue by derekcha** [argoproj/argo-cd#19920]
Checklist:

* [V] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [V] I've included steps to reproduce the bug.
* [V] I've pasted the output of `argocd version`.

**Describe the bug**

I tried upgrading from ArgoCD chart 7.3.11 to 7.4.4. However, after the upgrade, when I accessed ArgoCD, the sync status of all applications was stuck in Unknown status.
So I checked the log of argocd repo server, and the error log was output as below.

I thought it was a problem with the 7.4.4 chart only, so I upgraded to 7.5.2, but the same problem occurred. I think the same problem occurred when the Application Version became v2.12.X.

**To Reproduce**

1. Upgrade argo-cd to helm 7.4.4 version
2. Check argocd

**Expected behavior**

Normal sync status with git repository is tracked.

**Screenshots**
<img width="1635" alt="스크린샷 2024-09-11 오후 5 41 50" src="https://github.com/user-attachments/assets/c6fa5eed-d845-4441-8970-3882e7a4f7b7">

**Version**

```shell
v2.12.1
```

**Logs**
```
time="2024-09-11T08:39:26Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Check grpc.service=grpc.health.v1.Health grpc.start_time="2024-09-11T08:39:26Z" grpc.time_ms=0.018 span.kind=server system=grpc
time="2024-09-11T08:39:27Z" level=error msg="finished unary call with code Unknown" error="authentication required" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2024-09-11T08:39:24Z" grpc.time_ms=2215.417 span.kind=server system=grpc
time="2024-09-11T08:39:27Z" level=error msg="finished unary call with code Unknown" error="authentication required" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2024-09-11T08:39:27Z" grpc.time_ms=210.566 span.kind=server system=grpc
time="2024-09-11T08:39:28Z" level=error msg="finished unary call with code Unknown" error="authentication required" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2024-09-11T08:39:24Z" grpc.time_ms=3215.644 span.kind=server system=grpc
time="2024-09-11T08:39:29Z" level=error msg="finished unary call with code Unknown" error="authentication required" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2024-09-11T08:39:26Z" grpc.time_ms=3214.31 span.kind=server system=grpc
time="2024-09-11T08:39:29Z" level=error msg="Failed to get git client for repo https://github.com/dunamu-fd/kubekube-dev: authentication required"
time="2024-09-11T08:39:29Z" level=error msg="finished unary call with code Unknown" error="failed to get git client for repo https://github.com/{My Repository}" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2024-09-11T08:39:28Z" grpc.time_ms=1303.294 span.kind=server system=grpc
```

**Comment by alesz** [comment]
check if your repo secret contains project key or application is assigned to different project than referenced in secret

**Comment by blakepettersson** [comment]
Indeed, as alesz says it could be a permutation of #19587

**Comment by derekcha** [comment]
@alesz @blakepettersson 
I looked at the advice and links you gave and fixed the problem by modifying the secret containing the repo information (removing the project specification part). Thanks.
