### ISSUE TITLE
Improve frontend diff algorithm to better handle changes (whitespace and non-whitespace) within a line

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#19969]
# Summary

Replace the diff library with one that's better at handling diffs.

# Motivation

Some people complain about whitespace in diffs making changes hard to read, e.g.:
* https://github.com/argoproj/argo-cd/issues/8561
* often lines are fairly long and changes are hard to see

# Proposal

Replace the current diff engine (which appears to be purely line based) with one that's able to do substring comparisons.

Here's a current example from https://cd.apps.argoproj.io/applications/argocd/argo-cd?view=tree&resource=&node=%2FConfigMap%2Fargocd%2Fargocd-redis-ha-configmap%2F0:
![image](https://github.com/user-attachments/assets/5e340e67-29c4-427f-9041-cebcfcb742eb)

GitHub's can at least highlight words that have changed in a line, and the Visual Studio Code version 

Here's Visual Studio Code's diff:
<img width="632" alt="image" src="https://github.com/user-attachments/assets/5e7d8432-c4fc-435d-bbfd-be7bb01347b1">

**Comment by linghaoSu** [comment]
could I take this?

**Comment by jsoref** [comment]
Sure
