### ISSUE TITLE
Show pod names state should be applied when logs popped out

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#20012]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Log options aren't applied to newly popped out full screen logs view.

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/argo-cd?resource=kind%3APod&podSortMode=topLevelResource&node=apps%2FStatefulSet%2Fargocd%2Fargocd-redis-ha-server%2F0&tab=logs
2. Activate `Show pod names` <img width="183" alt="image" src="https://github.com/user-attachments/assets/1b23d98b-3576-4662-8167-c77285a086f8">
    <img width="1356" alt="image" src="https://github.com/user-attachments/assets/4aefcd0a-6056-45e3-8c01-40dff4ddec4d">
3. Activate `Show logs in fullscreen in a new window` <img width="285" alt="image" src="https://github.com/user-attachments/assets/826a4e71-0f0c-4a8f-ac55-8f0a4769549f">

**Expected behavior**

`Show pod names` should be active in the logs full screen in the new window

**Screenshots**

https://cd.apps.argoproj.io/applications/argocd/argo-cd/argocd/redis/logs?podName=&group=apps&kind=StatefulSet&name=argocd-redis-ha-server
<img width="1674" alt="image" src="https://github.com/user-attachments/assets/67cdb301-726c-4195-93ed-af3e7a7dd10d">

**Version**

```shell
{
    "Version": "v2.11.0+1cffa15",
    "BuildDate": "2024-04-18T08:51:13Z",
    "GitCommit": "1cffa15f0ddecbc241d572e316ea20920fdfdb65",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.9",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.3+gf03cc04",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

```
```

**Comment by linghaoSu** [comment]
Hi, I fixed the [issue](https://github.com/argoproj/argo-cd/pull/20022) of opening the log page in full screen without the viewPodName, but I'm also seeing a lot of other settings

1. such as viewTimestamp, do I need to fix that?
2. and viewPodNames is currently taken from the query of the url, while wrap is taken from the preference, is it necessary to be consistent  🤔.

**Comment by jsoref** [comment]
I'd certainly prefer for all of them to be applied.

**Comment by linghaoSu** [comment]
Hi, I've taken all the configurations from the url query parameter of the log view and synced them to the query of the url when it's updated.

1. when using the fullscreen button, take these configurations with you
2. share the url with the same configuration as the current url.

Now that the pr is ready to be reviewed, could you please review it to see if it meets expectations?
https://github.com/argoproj/argo-cd/pull/20022
