### ISSUE TITLE
Ellipsis menu for pod logs opens a loading thing and then disappears

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#20034]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Ellipsis menu for pod logs opens a loading thing and then disappears (it also can't be triggered again w/o reloading the page...)

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/argocd/argo-cd?view=pods&node=%2FPod%2Fargocd%2Fargocd-application-controller-0&tab=logs
2. Click the ellipsis near the upper right corner:
     <img width="59" alt="image" src="https://github.com/user-attachments/assets/ec87dbd3-cbbd-4114-be1e-5e3847d16ac8">

**Expected behavior**

* Probably a menu with menu items
* Alternatively no button to click if there's nothing to show...

**Screenshots**

This shows up momentarily and then runs away:

<img width="163" alt="image" src="https://github.com/user-attachments/assets/e4e4a656-c33e-47c7-8a00-d1ea76c2d3b0">

**Version**

```shell
{
    "Version": "v2.11.0+1cffa15",
    "BuildDate": "2024-04-18T08:51:13Z",
    "GitCommit": "1cffa15f0ddecbc241d572e316ea20920fdfdb65",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.9",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.3+gf03cc04",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by linghaoSu** [comment]
It seems like there is a request to know if there is an action available, maybe it would be better to get the actionable options when opening the pod details page, and then provide the trigger button for this menu if there is an actionable option available?

<img width="1586" alt="image" src="https://github.com/user-attachments/assets/dc7be5f8-25f0-46a9-92a7-73836d542f77">

**Comment by CefBoud** [comment]
@jsoref  @linghaoSu 
I have attempted to bring a fix to this issue in https://github.com/argoproj/argo-cd/pull/20051. Please let me know what you think.
