### ISSUE TITLE
Add a confirmation box for sync button action

### ISSUE THREAD

**Issue by anyflow** [argoproj/argo-cd#20060]
# Summary 
It would be helpful to have an option for a confirmation box to appear when pressing the Sync button.

# Motivation
Even when using GitOps, the Sync button is frequently used. Given the nature of GitOps, which handles all modifications including deletions and additions, the Sync operation is as risky as deletion. As a result, even a small human error can cause significant issues.

# Proposal
Similar to deletion, I propose that a confirmation box appears for Sync. By default, there would be no confirmation box, but having the option to enable it would ensure backward compatibility.

**Comment by crenshaw-dev** [comment]
Maybe this should be limited to cases where we know the sync will cause a deletion or a replacement? And maybe a checkbox is too much friction, maybe a red warning message would be sufficient.

**Comment by anyflow** [comment]
@surajyadav1108 You're correct. I wonder why I've thought it is a single step - maybe confused with refresh button.
