### ISSUE TITLE
Version 129.0.6668.59 error in google chrome when using argocd

### ISSUE THREAD

**Issue by Evandro-Cruz** [argoproj/argo-cd#20073]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by nitishfy** [comment]
can you provide more details about the error you're getting along with steps to reproduce it?

**Comment by blakepettersson** [comment]
Closing until there's more info on what the actual issue is.
