### ISSUE TITLE
Docs: Show Latest Version First in ArgoCD Documentation Version List

### ISSUE THREAD

**Issue by nueavv** [argoproj/argo-cd#20098]
# Summary
The current version selection in the ArgoCD documentation lists versions in alphabetical order. It would be more user-friendly to have the latest version listed at the top, ensuring that users can easily find and select the most recent version.

# Proposal
The version selection should be modified to sort versions in descending order based on release date. This change will ensure that the latest version is always displayed at the top, making it easier for users to navigate and access the most relevant documentation.

<img width="99" alt="스크린샷 2024-09-25 오후 5 16 28" src="https://github.com/user-attachments/assets/af7a5660-5df8-46b5-8cbf-ab0ca8e2f578">

**Comment by agaudreault** [comment]
This makes sense, as long as the default selection is "stable". I also see that 2.1x is not in the correct order in your proposal screenshot.
