### ISSUE TITLE
Theme support auto mode

### ISSUE THREAD

**Issue by linghaoSu** [argoproj/argo-cd#20105]
# Summary

The Appearance Settings theme supports 'Auto mode, which will follow the OS theme settings.

# Motivation

Wants the theme to be set automatically and to automatically change to a darker colour at night like the OS theme.
[related comment](https://github.com/argoproj/argo-cd/issues/4722#issuecomment-1252583106)

# Suggestions

Browsers have matchMedia to help use listen to OS theme changes

**Comment by bianbbc87** [comment]
That's a good idea, and I want to contribute to this issue 😃

**Comment by linghaoSu** [comment]
> That's a good idea, and I want to contribute to this issue 😃

@bianbbc87  I've implemented a pr for this enhancement. 🤔

https://github.com/argoproj/argo-cd/pull/20080
