### ISSUE TITLE
Go module proxy contains phantom v2.13.0 release, breaking Go imports

### ISSUE THREAD

**Issue by busser** [argoproj/argo-cd#20102]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The Go module proxy, proxy.golang.org, contains version `v2.13.0` of the `github.com/argoproj/argo-cd/v2` module, but the Github repository does not. When we try to download the latest version of the module, the Go module proxy provides `v2.13.0`. This version has issues with its dependencies, so importing it breaks builds. Going around the Go module proxy yields the latest version in the repo, `v2.12.3`.

This phantom version breaks any workflow that uses `go get` or `go mod tidy` to fetch the latest version of the module.

Pure speculation, but I assume the `v2.13.0` tag existed at some point, the Go module proxy cached it, and the tag was later deleted. There may be an issue with the release process.

**To Reproduce**

Attempting to download the latest version of the `github.com/argoproj/argo-cd/v2` module fails:

```terminal
# exit code 1
$ go get github.com/argoproj/argo-cd/v2
go: github.com/argoproj/argo-cd/v2@upgrade (v2.13.0) requires k8s.io/apiextensions-apiserver@v0.31.2: reading k8s.io/apiextensions-apiserver/go.mod at revision v0.31.2: unknown revision v0.31.2
```

Attempting the same operation without the Go module proxy succeeds:

```terminal
# no output, exit code 0
$ GOPROXY=direct go get github.com/argoproj/argo-cd/v2
```

My `GOPROXY` environment variable is not overwritten, so uses the default value:
```terminal
$ go env GOPROXY
https://proxy.golang.org,direct
```

**Expected behavior**

I expected this command to succeed:

```sh
go get github.com/argoproj/argo-cd/v2
```

**Screenshots**

N/A

**Version**

N/A

**Logs**

N/A

**Comment by pasha-codefresh** [comment]
Unfortunately it was human mistake during release. Here no easy way to resolve it . Monday, Nov. 4, 2024 we will release 2.13.0 and it will be resolved

**Comment by pasha-codefresh** [comment]
Release 2.13 is out, should not be an issue anymore. Sorry for inconvenience
