### ISSUE TITLE
Documentation for upgrading ArgoCD & breaking changes in master/latest

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#2016]
**Is your feature request related to a problem? Please describe.**

Currently, there is no straight-forward instructions for someone following `argocd:latest` on what needs to be changed in order to get things up & running. 

A good example on such confusion is PR #1807, which has introduced required changes to `argocd-server` and `argocd-repo-server` pods - namely, the need for volume mounting two newly introduced `ConfigMap` objects to them. If you use `argocd:latest` image for your deployments without adapting manifests, things will not work correctly.

**Describe the solution you'd like**

I think a central document which contains a list of all breaking changes in `master` or `argocd:latest` image since the latest release would be very helpful. I'm unsure whether the `Changelog` should be used for that, since it currently doesn't track master. And this proposal is only about breaking changes. The contents of the breaking changes document could then be taken into the `Changelog` upon a new version is released.

Contribution docs should also be updated so that it is clear that if a PR introduces a breaking change, it should be documented.

**Comment by alexec** [comment]
we should automate all of this

**Comment by jannfis** [comment]
Hm. So PRs that were merged would need some machine parseable information on that. And what if such docs change after a PR, how to update them?
Don't understand me wrong, I'm all for automation. But I think this is a use-case for manual maintenance. Its contents could then be taken to a release's Changelog in an automated manner.

**Comment by alexmt** [comment]
I think this is addressed by https://github.com/argoproj/argo-cd/commit/28dd7167d026d68ee743068ed5028fa300f450a9#diff-88b3974048e76cd9759114e94b0dc4dc . @jannfis , please free to reopen the issue if necessary
