### ISSUE TITLE
Self heal exponential delay increase

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#20172]
# Summary

Argo CD makes 5 seconds delay between auto-sync attempts. The delay duration might be configured using `controller.self.heal.timeout.seconds` field of `argocd-cmd-params-cm` ConfigMap. It is proposed to support configuring exponential delay increase.

# Motivation

The delay between attempts is required to prevent unnecessary sync attempts when Out-Of-Sync status is caused by invalid manifests/unexpected K8S controller behavior [etc](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/). Increasing timeout helps avoid unnecessary controller CPU usage/K8S API server requests but affects end user experience.

The exponential timeout increase would provide both: good user experience and good controller performance. 

# Proposal

Introduce `controller.self.heal.timeout.backoff.factor` `controller.self.heal.timeout.backoff.maxseconds` fields in  `argocd-cmd-params-cm` ConfigMap. If set the new fields and `controller.self.heal.timeout.seconds` should be used to configure exponential timeout increase between auto-sync attempts.

It is proposed to avoid adding new fields and calculate number of attempts based on time since last sync attempt:

```math
n = \log_2 \left( \frac{T_{cumulative}}{T_0} + 1 \right)
```

**Comment by CefBoud** [comment]
@alexmt I gave this a shot in https://github.com/argoproj/argo-cd/pull/20238. I would love to get your thoughts on it and especially on https://github.com/argoproj/argo-cd/pull/20238/files#r1789173694. 
Thank you in advance!
