### ISSUE TITLE
argocd.argoproj.io/refresh annotation added to cluster secret when invalidating cache but is not removed by applicationset controller

### ISSUE THREAD

**Issue by windrammer** [argoproj/argo-cd#20179]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When invalidating cache through the ArgoCD UI, the argocd.argoproj.io/refresh annotation is added to the cluster secret with a timestamp of when the cache invalidation was requested. According to the [DOCS](https://argo-cd.readthedocs.io/en/stable/user-guide/annotations-and-labels/) this annotation should be removed from the secret when the cache is refreshed but it is not. It also looks like this is an annotation that should be added to applications with value of either "normal" or "hard" and not a timestamp and the docs are referring to applications and not clusters.

**To Reproduce**

In the cluster where argocd is deployed, run:
kubectl describe secret -n argocd cluster-ID-OF-CLUSTER
Check the annotations for the argocd.argoproj.io/refresh and verify that it is not there.

Go to the argocd UI click settings -> Clusters > the cluster you checked in previous step and click on "Invalidate cache"

Go back to terminal and in the cluster where argocd is deployed, run:
kubectl describe secret -n argocd cluster-ID-OF-CLUSTER
And the argocd.argoproj.io/refresh  annotation should be there with a timestamp from when the invalidate cache-button was pressed. This annotation is not removed and will stay there indefinitely.

**Expected behavior**

Either annotation should not be added to cluster secrets or the annotation should be removed by the controller.

**Screenshots**
N/A

**Version**

argocd version
argocd: v2.11.2+25f7504
  BuildDate: 2024-05-23T15:31:09Z
  GitCommit: 25f7504ecc198e7d7fdc055fdb83ae50eee5edd0
  GitTreeState: clean
  GoVersion: go1.22.3
  Compiler: gc
  Platform: darwin/arm64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.12.0+ec30a48
  BuildDate: 2024-08-05T13:25:54Z
  GitCommit: ec30a48bce7a60046836e481cd2160e28c59231d
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.2 2024-05-22T15:19:38Z
  Helm Version: v3.15.2+g1a500d5
  Kubectl Version: v0.29.6
  Jsonnet Version: v0.20.0

Let me know if you need anything from me or if more info is needed.

**Comment by nueavv** [comment]
Based on the code review, it appears that the annotations being added is part of the normal cache invalidation process, indicating that the cache invalidation request was successfully made. I'm wondering if there are any issues beyond the annotation not being removed. If there is any other problem, please provide more details, and I can investigate further.

**Comment by windrammer** [comment]
I have not noticed any other problems other than a bit of confusion as argocd.argoproj.io/refresh is used for both triggering a refresh and showing when the last refresh was done depending on which resource the annotation is on.

**Comment by agaudreault** [comment]
The annotation `argocd.argoproj.io/refresh` is meant to be set on the Application resource. This is what the documentation is for. so annotations like `argocd.argoproj.io/refresh: hard` or `argocd.argoproj.io/refresh: normal` will be removed by the application controller.

The annotations on the cluster Secret has the same name, but is a totally different one. It is an internal annotation not meant to be used by the end user. The annotation is used to persist information in the secret, because a custom status cannot be used on the Secret resource type.
