### ISSUE TITLE
Not able to see the logs in argo cd

### ISSUE THREAD

**Issue by poojaambali** [argoproj/argo-cd#20209]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by nitishfy** [comment]
Please provide more details about the issue you're facing.

**Comment by poojaambali** [comment]
<img width="960" alt="image (1)" src="https://github.com/user-attachments/assets/ff82694b-259a-4f84-8058-a6825d609f4d">

**Comment by blakepettersson** [comment]
Duplicate of #20321
