### ISSUE TITLE
Incorrect pluralization on resources that end with an S (Rules, ClusterRules, etc.)

### ISSUE THREAD

**Issue by otherguy** [argoproj/argo-cd#20210]
**Describe the bug**

Resources that end on an `s` (`Rules`, `ClusterRules`, etc.) are incorrectly pluralized when these resources are grouped.

![CleanShot 2024-10-03 at 09 50 55@2x](https://github.com/user-attachments/assets/6502785e-7408-46aa-badc-7ab63c550bdc)

![CleanShot 2024-10-03 at 09 53 31@2x](https://github.com/user-attachments/assets/c71e32f2-5b1a-410e-b1da-d0462ec3494e)

**To Reproduce**

Create multiple `Rules`, `ClusterRules` or other resources where their `kind` ends on an `s`.

```
apiVersion: monitoring.googleapis.com/v1
kind: Rules
```

**Expected behavior**

The plural should still be `Rules` or `ClusterRules`. 

**Version**

```
    "Version": "v2.12.4+27d1e64",
    "BuildDate": "2024-09-26T06:36:13Z",
    "GitCommit": "27d1e641b6ea99d9f4bf788c032aeaeefd782910",
    "GitTreeState": "clean",
    "GoVersion": "go1.22.4",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.4.2 2024-05-22T15:19:38Z",
    "HelmVersion": "v3.15.2+g1a500d5",
    "KubectlVersion": "v0.29.6",
    "JsonnetVersion": "v0.20.0"
```

**Comment by JessieTeng89** [comment]
Hi there,
Please assign this to me, I will create a PR to fix it.
Thanks

**Comment by nitishfy** [comment]
For me, it does display it correctly
![image](https://github.com/user-attachments/assets/b52b15b9-f705-4cea-a352-7b745332f5d8)

**Comment by otherguy** [comment]
> For me, it does display it correctly ![image](https://private-user-images.githubusercontent.com/86051118/374087271-b52b15b9-f705-4cea-a352-7b745332f5d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTAxODksIm5iZiI6MTcyODI4OTg4OSwicGF0aCI6Ii84NjA1MTExOC8zNzQwODcyNzEtYjUyYjE1YjktZjcwNS00Y2VhLWEzNTItN2I3NDUzMzJmNWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA4MzEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNWYxODY3ZjAwNmIyN2JhMjEwYWY5YmRmMzA4MzZlODZlYTc3MzUxODYwYTU5MjE1YTI0MDhlZTAwMjJmNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kpyO_o7p31O9vc0Xzprssk1Mmp2189nqbwxU-gr4wI0)

These are single resources. Create a second resource of the same type in the same ArgoCD application to see the issue.

**Comment by nitishfy** [comment]
> These are single resources (i.e. one resource of type `Rules`). Create a second resource of the same type in the same ArgoCD application to see the issue.

![image](https://github.com/user-attachments/assets/36f0d35d-48d9-406b-8fd4-b5d9c5fb60ee)

**Comment by otherguy** [comment]
If you compare it to my screenshot in the bug report, you will notice that it shows 2 single resources for you, whereas it shows them grouped for me.

Displaying a single resource is not an issue, the grouped/stacked pluralization is.

**Comment by agaudreault** [comment]
@otherguy @JessieTeng89 feel free to open a PR in draft and associate it to this issue when you start working on it.

**Comment by yashrtalele** [comment]
@agaudreault Is anyone working on this issue. If not can you assign it to me.

**Comment by otherguy** [comment]
Nice, thank you @yashrtalele !
