### ISSUE TITLE
Support dry-run sync from UI

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#2021]
See https://github.com/argoproj/argo-cd/issues/798

**Comment by chancez** [comment]
Related, it would be amazing to dry-run sync from the CLI with local manifests when an app has automatic sync enabled. Currently you cannot use local sync when automatic sync policy is enabled, even if it's a dry-run.

**Comment by andrii-korotkov-verkada** [comment]
Dry run from UI is now supported.
![Screenshot 2024-11-15 at 4 38 32 AM](https://github.com/user-attachments/assets/170539a8-ebbf-457d-b574-f1cb9425771f)
