### ISSUE TITLE
ArgoCD kubernetes compatibility table in docs not updating after v2.11

### ISSUE THREAD

**Issue by Hadlock** [argoproj/argo-cd#20223]
Documentation should show the compatibility chart of ArgoCD version vs Kubernetes release. Since ArgoCD v2.11 the new rows are being added for v2.12 and v2.13 but they are empty.

This issue mentions the creation of the table
https://github.com/argoproj/argo-cd/issues/12276
The pull request (merged) to add this feature circa 2023
https://github.com/argoproj/argo-cd/pull/14180

**To Reproduce**

Browse to https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#tested-versions and scroll to the bottom to view the table

**Expected behavior**

The table should include completed rows with version numbers, e.g. `v1.30, v1.29, v1.28, v1.27, v1.26` , `v1.31,v1.30,v1.29, v1.28, v1.27` etc

**Screenshots**

![Screenshot 2024-10-03 at 5 09 59 PM](https://github.com/user-attachments/assets/c24a9225-b1e0-4ffa-8f00-6f9c44d2f9ca)

**Version**

stable

**Logs**

n/a

**Comment by owanio1992** [comment]
add doc link [tested-kubernetes-versions](https://github.com/argoproj/argo-cd/blob/v2.12.4/docs/operator-manual/tested-kubernetes-versions.md)

2.12 is missing

**Comment by agaudreault** [comment]
l'll take a look and make sure the release process is up-to-date

**Comment by Hadlock** [comment]
Thank you!
