### ISSUE TITLE
WebUI - don't close the "new application" editor when clicking outside of it

### ISSUE THREAD

**Issue by mhazan01** [argoproj/argo-cd#20285]
# Summary

When you have the new app panel open to edit the said app and you click outside of that panel, it closes the editor without saving.

# Motivation

when creating a new app through the webui

# Proposal
don't close the editor panel or ask for confirmation before closing and discarding changes ?

**Comment by 2003Aditya** [comment]
@mhazan01 @saumeya What if we create a temporary save state that stores the new app form for a specific time period, allowing the user to make changes or complete it later?

**Comment by saumeya** [comment]
This is definitely a good problem to solve as it would improve experience, 
Yes @2003Aditya that would be the approach, to persist the form data for sometime in the local storage. I was also looking at this library if it could be of any use - https://www.npmjs.com/package/react-hook-form-persist

**Comment by 2003Aditya** [comment]
@saumeya   I tried to save data in local storage, but how can the user see the saved form? What should I do?

**Comment by andrii-korotkov-verkada** [comment]
I think we can solve this problem by adding a mouse click handler, which checks if the app creation window is open and warns that changes would be discarded and only processes the click if the user confirms.

**Comment by surajyadav1108** [comment]
Although having a save state might be a more user-friendly approach, for simplicity, I think just a warning before closing the panel would be sufficient.
