### ISSUE TITLE
Release Versions are not sorted in the documentation.

### ISSUE THREAD

**Issue by jaehanbyun** [argoproj/argo-cd#20289]
# Summary
The current documentation site for Argo CD displays release versions in an unsorted manner.

![스크린샷 2024-10-08 오후 10 09 43](https://github.com/user-attachments/assets/a58b85e6-f20a-4cd5-82ca-732b0d5be03a)

# Motivation
Proper sorting will improve user experience by providing a clear structure for accessing different releases.

# Proposal
Update the logic responsible for displaying release versions on the documentation site to ensure they are sorted in ascending numerical order.

**Comment by linghaoSu** [comment]
It seems this issue has been fixed in this PR: https://github.com/argoproj/argo-cd/pull/20181/files.

**Comment by jaehanbyun** [comment]
> It seems this issue has been fixed in this PR: https://github.com/argoproj/argo-cd/pull/20181/files.

I checked it, Thanks!

**Comment by linghaoSu** [comment]
o n l

**Comment by linghaoSu** [comment]
Oops! This fix only works when the browser's language is set to English.

**Comment by linghaoSu** [comment]
https://github.com/argoproj/argo-cd/pull/20181/files#diff-9dded3ea5cb0de3f54e11ec05ce0490920e01776e604a2f8c25d8f65845c55a7R84

This line hardcodes `version`, but in other languages, MkDocs uses i18n, so it won't sort properly.

**Comment by jaehanbyun** [comment]
@linghaoSu As you mentioned, when I change the browser language settings, the sorting does not work properly. May I work on addressing this issue?

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/a29361e0-4632-4672-8f7a-4dd4ecccfdce">
