### ISSUE TITLE
Old `gitops-engine` version in ArgoCD 2.12.4 with non-compliant parser prevents pods with `appArmorProfile` defined from being deployed

### ISSUE THREAD

**Issue by efbicief** [argoproj/argo-cd#20290]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The version of `gitops-engine` used in ArgoCD 2.12.4 does not include `appArmorProfile` in the schema for `securityContext`. This results in anything using this feature under Kubernetes 1.30+ (in which `appArmorProfile` became a full feature and old app armor annotations were deprecated) being rejected by ArgoCD.

The version of `gitops-engine` in use in ArgoCD 2.12.4 is [v0.7.1-0.20240714153147-adb68bcaab73](https://github.com/argoproj/argo-cd/blob/v2.12.4/go.mod#L14) ([commit](https://github.com/argoproj/gitops-engine/commit/adb68bcaab73a18c454caae4c744d932ee83670f)), whereas the version of `gitops-engine` in use in ArgoCD 2.13.0-rc3 is [v0.7.1-0.20240905010810-bd7681ae3f8b](https://github.com/argoproj/argo-cd/blob/v2.13.0-rc3/go.mod#L13C2-L13C72) ([commit](https://github.com/argoproj/gitops-engine/commit/bd7681ae3f8b432aa688daf2b8358efd9914888e)). This issue is fixed in 2.13.0-rc3.

I would like to request that the fix linked above which is applied in 2.13.0-rc3 is backported to 2.12.

**To Reproduce**

I came across this issue [when deploying Cilium](https://github.com/cilium/cilium/blob/b069e301e6f19f0d1b5129e29be3f3c1c81313b4/install/kubernetes/cilium/templates/cilium-nodeinit/daemonset.yaml#L50-L58), which when under Kubernetes 1.30+ makes use of `appArmorProfile` in a DaemonSet, `cilium-node-init`. I got the following error:
```
Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from live resource: .spec.template.spec.securityContext.appArmorProfile: field not declared in schema
```
Note that an [issue was filed on the Cilium project](https://github.com/cilium/cilium/issues/35046), in which it was concluded that [this is an ArgoCD issue](https://github.com/cilium/cilium/issues/35046#issuecomment-2379781349).

**Expected behavior**

The DaemonSet is able to deploy, since it matches the Kubernetes 1.30 API spec.

**Version**
From an instance under which there is no error:
```
argocd: v2.11.7+e4a0246
  BuildDate: 2024-07-24T10:10:59Z
  GitCommit: e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb
  GitTreeState: clean
  GoVersion: go1.21.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.13.0-rc3+ec60abd
  BuildDate: 2024-10-07T13:33:09Z
  GitCommit: ec60abd4d810a2070930be09a4754ca73dd8be18
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

From an instance under which there is an error:
```
argocd: v2.11.7+e4a0246
  BuildDate: 2024-07-24T10:10:59Z
  GitCommit: e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb
  GitTreeState: clean
  GoVersion: go1.21.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.11.3+3f344d5
  BuildDate: 2024-06-06T08:42:00Z
  GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

I don't have a 2.12.4 instance running right now, since I upgraded it to v2.13.0-rc3 to confirm that the rc release contains a fix that could be backported.

**Comment by crenshaw-dev** [comment]
@efbicief are any of these workarounds possible for you? https://argo-cd.readthedocs.io/en/latest/faq/#how-do-i-work-around-the-issue

I wish the solution were as simple as "update gitops-engine." As you discovered, we currently hard-code the schema for a particular k8s version in gitops-engine. If we backport a newer schema, we risk prematurely dropping fields that have been removed in newer k8s versions. 

Long-term I think we need a way to avoid hard-coding this schema entirely.

**Comment by efbicief** [comment]
Thanks for your quick response!
That makes sense. I'll see if any of those workarounds work for me.

**Comment by efbicief** [comment]
Enabling server-side diff seems to have helped. Thanks again!
