### ISSUE TITLE
User Profile Page

### ISSUE THREAD

**Issue by servo1x** [argoproj/argo-cd#2031]
**Is your feature request related to a problem? Please describe.**
Feature request.

**Describe the solution you'd like**
It would be nice to have a user profile page for debugging sso / oidc / rbac.

For example displaying the loggedin user roles, the returned claims from oidc, viewing the sub, etc.

**Comment by alexec** [comment]
good one for community contribution

**Comment by alexec** [comment]
This is available in v1.3.
