### ISSUE TITLE
Argocd CLI appset returns no values

### ISSUE THREAD

**Issue by moserke** [argoproj/argo-cd#20343]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

The argocd cli returns no results for application sets, even though many exist in the cluster.  My user is a `role:admin` and has full permssions.  Adding a `--loglevel debug` offers no deeper insight

**To Reproduce**

`argocd appset list -N argo-cd` returns simply

```
argocd appset list
NAME  PROJECT  SYNCPOLICY  CONDITIONS  REPO  PATH  TARGET
```

However looking with kubectl one can see there are many that exist

```
kubectl -n argo-cd get applicationsets | wc -l
 40
```

Navigating to `https://<server>/api/v1/applicationsets` in a web browser also returns all of the appsets in the cluster.  It seems to be a disconnect about the cli directly.

**Expected behavior**

I would expect to see the 40 ApplicationSets that exist in the cluster

**Version**

```shell
argocd: v2.10.5+335875d
  BuildDate: 2024-03-28T16:12:55Z
  GitCommit: 335875d13e018bed6e03873f4742582582964745
  GitTreeState: clean
  GoVersion: go1.21.8
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.10.5+335875d
  BuildDate: 2024-03-28T15:02:45Z
  GitCommit: 335875d13e018bed6e03873f4742582582964745
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.3+gf03cc04
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Comment by crenshaw-dev** [comment]
I'm not able to reproduce this on `master`. What's the output for `argocd account can-i get applicationsets '*'`?

**Comment by moserke** [comment]
Interestingly it says no:
```
argocd account can-i get applicationsets '*'              
no
```

However so does applications:
```
argocd account can-i get applications '*'   
no
```

Yet
```
argocd app list | wc -l
421
```

So I can get applications even though it says I can't.

**Comment by moserke** [comment]
Ah your comment pointed me in the right direction!  We were leveraging SSO and our claim was not including groups so I was not actually being bound to admin.  This explains why the browser worked but not the cli as they are using different client apps in Okta.  

I appreciate the help!  thanks!
