### ISSUE TITLE
Error message "another operation is already in progress" when syncing resources via rest API

### ISSUE THREAD

**Issue by yhussainmiax** [argoproj/argo-cd#20372]
When trying to sync multiple resources concurrently via the rest api, I notice that most of them error out with a http 400 "another operation is already in progress".   If I run them serially one at a time they seem to succeed

argocd version
----------------
argocd: v2.4.7+81630e6
  BuildDate: 2022-07-18T21:38:56Z
  GitCommit: 81630e6d5075ac53ac60457b51343c2a09a666f4
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64

Sample http request body of failing invocation:

requestBody {
  "dryRun": false,
  "prune": false,
  "revision": "develop",
  "strategy": {
    "hook": {
      "force": false
    }
  },
  "syncOptions": {
    "items": [
      "CreateNamespace=true"
    ]
  },
  "resources": [
    {
      "group": "batch",
      "kind": "Job",
      "name": "some-job",
      "namespace": "bsx-bsd-staging",
      "status": "OutOfSync",
      "version": "v1",
      "health": {
        "status": "Missing"
      }
    }
  ]
}

**Comment by rumstead** [comment]
Do you see this issue in a more recent version of Argo CD, 2.4 is very old.

**Comment by agaudreault** [comment]
This is the current expected behavior. Argo does not support executing multiple sync in parallel and queueing sync. You can use https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_app_wait/ to validate if a sync is in progress before triggering another one.
