### ISSUE TITLE
Support `helm.sh/hook: test-success/failure`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#2038]
See #355.

**Comment by jessesuen** [comment]
Helm test hooks are only used through a `helm test` command. I don't think we have use for this and would recommend closing this.

**Comment by NotAndD** [comment]
But what if I want to exec a manual test after I applied the Chart / I updated something and sync the application? I think it would be pretty useful if argo-cd supported starting a test hook manually from its interface.

I know that helm test is not that used, but it's a way to execute manual Jobs only when needed and under the supervision of who starts them.
