### ISSUE TITLE
ssh connect in appset failed

### ISSUE THREAD

**Issue by Nello-Angelo** [argoproj/argo-cd#20411]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
```
  conditions:
    - lastTransitionTime: '2024-10-16T22:40:59Z'
      message: >-
        error generating params from git: error getting directories from repo:
        error retrieving Git Directories: rpc error: code = Internal desc =
        unable to resolve git revision : error creating SSH agent: "SSH agent
        requested but SSH_AUTH_SOCK not-specified"
      reason: ApplicationGenerationFromParamsError
      status: 'True'
      type: ErrorOccurred
    - lastTransitionTime: '2024-10-16T22:40:59Z'
      message: >-
        error generating params from git: error getting directories from repo:
        error retrieving Git Directories: rpc error: code = Internal desc =
        unable to resolve git revision : error creating SSH agent: "SSH agent
        requested but SSH_AUTH_SOCK not-specified"
      reason: ErrorOccurred
      status: 'False'
      type: ParametersGenerated
    - lastTransitionTime: '2024-10-16T22:40:59Z'
      message: >-
        error generating params from git: error getting directories from repo:
        error retrieving Git Directories: rpc error: code = Internal desc =
        unable to resolve git revision : error creating SSH agent: "SSH agent
        requested but SSH_AUTH_SOCK not-specified"
      reason: ApplicationGenerationFromParamsError
      status: 'False'
      type: ResourcesUpToDate
```

**To Reproduce**

i have internal gitlab and adding a repo with ssh private key is Successful

**Expected behavior**

create apps using appset

**Screenshots**

**Version**

```shell
v2.12.4+27d1e64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by Nello-Angelo** [comment]
<img width="1109" alt="Screenshot at Oct 17 01-49-51" src="https://github.com/user-attachments/assets/c2a014fb-77b8-4ad7-913c-acb3c99b952c">

but when i create app using application it`s correct

**Comment by nitishfy** [comment]
can you provide a good description about this issue and steps to reproduce it locally?

**Comment by Nello-Angelo** [comment]
try to setup gitlab with valid https cert, install argocd the latest version, create repo with test charts, try to connect with https and ssh, and setup appset yaml and watch

i am also tring to test this moment on test gitlab (not gitlab of company) and want test with it and if i get the same, so, may be there is a bug

**Comment by Nello-Angelo** [comment]
we also can watch in discord if you want

**Comment by Nello-Angelo** [comment]
I want to remind you that this problem is only with appset

**Comment by Nello-Angelo** [comment]
i got the same error but now i tried using https connect, this error i get in gitlab of my company and in my test gitlab with valid cert from cert manager 

```
  conditions:
    - lastTransitionTime: '2024-10-17T15:25:07Z'
      message: >-
        error generating params from git: error getting directories from repo:
        error retrieving Git Directories: rpc error: code = Internal desc =
        unable to resolve git revision : authentication required
      reason: ApplicationGenerationFromParamsError
      status: 'True'
      type: ErrorOccurred
    - lastTransitionTime: '2024-10-17T15:25:07Z'
      message: >-
        error generating params from git: error getting directories from repo:
        error retrieving Git Directories: rpc error: code = Internal desc =
        unable to resolve git revision : authentication required
      reason: ErrorOccurred
      status: 'False'
      type: ParametersGenerated
    - lastTransitionTime: '2024-10-17T15:25:07Z'
      message: >-
        error generating params from git: error getting directories from repo:
        error retrieving Git Directories: rpc error: code = Internal desc =
        unable to resolve git revision : authentication required
      reason: ApplicationGenerationFromParamsError
      status: 'False'
      type: ResourcesUpToDate
     ```

**Comment by Nello-Angelo** [comment]
i dont understand why application deploy apps correct but appset give me this behavior

**Comment by 34fathombelow** [comment]
Hello @Nello-Angelo Can you please check the [upgrade notes](https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.11-2.12/#cluster-secret-scoping-changes) in our docs.  There were some recent changes to cluster secrets which I believe you may be experiencing.   Basically just remove the `project` field from your repository credentials or create a repo cred for each project.

**Comment by Nello-Angelo** [comment]
@34fathombelow sorry i dont understand please give me detailed example

**Comment by Nello-Angelo** [comment]
i tried to use argo with version before 2.10 and got the same result

**Comment by Nello-Angelo** [comment]
i deleted project and this work now

**Comment by sysadmin-exe** [comment]
Hmmm.. this also happened to me. Removed the projects and the Applicationset creates the application. But the applications failed because of the missing project so I added the project again and it looks okay. 
I am using SSH for auth.
