### ISSUE TITLE
"SYNC" and "DETAILS" buttons disabled on UI for multi source applications

### ISSUE THREAD

**Issue by MairaTariq16** [argoproj/argo-cd#20445]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
"SYNC" and "DETAILS" disabled for applications which have `spec.sources` instead of `spec.source`

**To Reproduce**

1. Create an application with `spec.sources` instead of `spec.source`
2. ArgoCD UI shows grey-out (disabled) buttons for "SYNC" and "DETAILS"

**Expected behavior**
These buttons should not be disabled

**Screenshots**
<img width="1203" alt="Screenshot 2024-10-18 at 3 12 13 PM" src="https://github.com/user-attachments/assets/12170cfd-ea30-4892-a62d-14786baca9e4">

**Version**
argocd: v2.12.5+85be9a4
  BuildDate: 2024-10-17T20:46:21Z
  GitCommit: 85be9a4f22981ac18b3b0438f4df84f36ea32236
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64

**Comment by YonierGomez** [comment]
I have the same problem, how to solve it?

**Comment by blakepettersson** [comment]
There is none apart from downgrading to 2.12.4, sorry about that 😞 There'll be a 2.12.6 which will have the proper fix.

**Comment by crenshaw-dev** [comment]
Get it while it's hot! https://github.com/argoproj/argo-cd/releases/tag/v2.12.6
