### ISSUE TITLE
ApplicationSet git generator `git fetch` error，with `Host key verification failed`

### ISSUE THREAD

**Issue by ivan-cai** [argoproj/argo-cd#20531]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.
v2.12.4 

**Describe the bug**

`message: “error failed to get params for first generator in matrix generator:
child generator returned an error on parameter generation: error generating
params from git: error retrieving Git files: rpc error: code = Internal desc
= unable to checkout git repo git@git.xxxx.cn:xxx/xxxx.git
with revision xxxx pattern envprd/*/config.json:
failed to initialize repository resources: rpc error: code = Internal desc =
Failed to fetch default: `git fetch origin --tags --force --prune` failed exit
status 128: Host key verification failed.\r\nfatal: Could not read from remote
repository.\n\nPlease make sure you have the correct access rights\nand the
repository exists.“`

How can I fix it？

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

v2.12.4

**Logs**

```
Paste any relevant application logs here.
```

**Comment by blakepettersson** [comment]
Sounds like a permutation of #19585? Have you seen the [release notes](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.11-2.12/#cluster-secret-scoping-changes)?

**Comment by blakepettersson** [comment]
Will close this for now, feel free to comment on #19585 if it hasn't been resolved, or comment in this issue if it's somehow distinct from that one.
