### ISSUE TITLE
Login failed using SAML when user has more than 200 groups assigned

### ISSUE THREAD

**Issue by yhemi** [argoproj/argo-cd#20599]
Checklist:

* [V] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [V] I've included steps to reproduce the bug.
* [V] I've pasted the output of `argocd version`.

**Describe the bug**

When a user tries to login using SAML and is assigned to more than 200 groups. the user receives "Login failed" error message

**To Reproduce**

1. Create a user that has more than 200 SAML groups
2. Configure argocd to work with SAML
3. Login using SAML
4. You will get "Login failed" error message
5. remove 50 groups from that user
6. relogin and it will work

**Expected behavior**
Expected behaviour is that login with SAML will work regardless of the number of groups the user is assigned to

**Screenshots**

![image](https://github.com/user-attachments/assets/e1afeec3-f8ef-4b56-95e8-e82853a0b93f)

**Version**

```shell
v.2.12.6
```

**Logs**
`{
    "level": "error",
    "msg": "Failed to authenticate: no attribute with name \"Group\": [
http://schemas.microsoft.com/identity/claims/tenantid
http://schemas.microsoft.com/identity/claims/objectidentifier
http://schemas.microsoft.com/identity/claims/displayname
http://schemas.microsoft.com/claims/groups.link
http://schemas.microsoft.com/identity/claims/identityprovider
http://schemas.microsoft.com/claims/authnmethodsreferences
http://schemas.microsoft.com/ws/2008/06/identity/claims/wids
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
email]",
    "time": "2024-10-30T14:19:20Z"
}`
```
Paste any relevant application logs here.
```

**Comment by rq3dm4** [comment]
We have the same issue with one user that is member of 130 groups

{"level":"error","msg":"Failed to authenticate: no attribute with name \"Group\": [http://schemas.microsoft.com/identity/claims/tenantid http://schemas.microsoft.com/identity/claims/objectidentif │
│ ier http://schemas.microsoft.com/claims/groups.link http://schemas.microsoft.com/identity/claims/identityprovider http://schemas.microsoft.com/claims/authnmethodsreferences http://schemas.microsoft.com/ws/2 │
│ 008/06/identity/claims/wids email]","time":"2024-11-05T13:53:44Z"}

**Comment by yhemi** [comment]
thanks @rq3dm4, it worked.

**Comment by andrii-korotkov-verkada** [comment]
@yhemi, can this be considered resolved?

**Comment by yhemi** [comment]
@andrii-korotkov-verkada yes, thanks.

**Comment by vaibyy** [comment]
Hi , In my case I am able to login but I cannot see anything in argo UI. We just migrated to entra ID and got this issue . Looks like user is part of more than 100 groups 

<img width="955" height="637" alt="Image" src="https://github.com/user-attachments/assets/3f266f32-53fe-4241-8693-65faae7e0342" />
