### ISSUE TITLE
Show an info about the last commit(s) which actually affects a given application

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [argoproj/argo-cd#20592]
# Summary

Get an info about latest commit(s) modifying application source(s) path(s).

# Motivation

Right now the commit displayed may be irrelevant to the actual commit that makes changes to the application.

# Proposal

Repo server should query latest commit from the application path(s) and the UI should display it on top of the page, maybe in one of the sync sections or a new section.

**Comment by andrii-korotkov-verkada** [comment]
This is complementary to https://github.com/argoproj/argo-cd/issues/20586

**Comment by todaywasawesome** [comment]
Duplicate of #17280 - @pasha-codefresh has built an Application Change Revision controller to resolve this. It's been in testing for a bit with some people using it and will be released publicly soon.

**Comment by seanorama** [comment]
@pasha-codefresh any word on the controller being shared publicly? Would love to see it. We are doing all sorts of hacks to achieve this.
