### ISSUE TITLE
[Regression] [ArgoCD 2.12.1 to 2.12.6] UI malfunction when creating new application - the "Create" window pops backup after the application is created

### ISSUE THREAD

**Issue by aarontams** [argoproj/argo-cd#20606]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
This is a regression from ArgoCD 2.11.9. Tested all 2.12.1 to 2.12.6 and got the same UI issue.

When creating a new application from the UI, the Create window never goes away even the application is already created. It is just very annoying and misleading for end user. It is not a blocker, but I think a lot of users will feel the pain.

When creating 
**To Reproduce**
- from the UI
- click `New App` button
- click `EDIT AS YAML`
- add the application yaml 
- clicke `Save` button
- click `Create` button
- the `Create` window will close and then immediately reopened
- the only way to close/hide that `Create` Window is to click outside of it

After that, you can search the newly created app.

**Expected behavior**
This is a regression, I expect the `Create` window will be closed without popping up again.

**Screenshots**

<img width="1212" alt="image" src="https://github.com/user-attachments/assets/6fbe3e06-ad48-4625-99b6-6df9392d0fa8">

**Version**
All 2.12.1 to 2.12.6

**Comment by todaywasawesome** [comment]
Seeing the same issue.

**Comment by blakepettersson** [comment]
I think this is fixed with #20507

**Comment by aarontams** [comment]
Hey @blakepettersson 
Do you know when 2.12.7 and the corresponding helm will release?
Thx

**Comment by crenshaw-dev** [comment]
2.12.7 is out

**Comment by aarontams** [comment]
Thanks. It is exciting news.

**Comment by aarontams** [comment]
BTW: For helm release https://github.com/argoproj/argo-helm/blob/argo-cd-7.6.12/charts/argo-cd/Chart.yaml is the latest for 2.12.x
Any idea when the new helm chart will be out for argocd 2.12.7?

**Comment by blakepettersson** [comment]
@aarontams you'll have to ask the maintainers of argo-helm. In any case you should be fine by setting `image.tag` to `2.12.7` in the Helm values.
