### ISSUE TITLE
Cannot add list to "valuesObject" in Application manifest

### ISSUE THREAD

**Issue by AllYouZombies** [argoproj/argo-cd#20615]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to add a new Application in UI.
Selected "Edit as YAML", added "valuesObject" with values containing lists. Just like this:

```
...
  helm:
    valuesObject:
      api:
        additionalPlugins:
          - >-
            https://example.com/some/file.zip
      gateway:
        additionalPlugins:
          - >-
            https://example.com/some/file.zip
...
```

After I press "Save", an error occurs in UI.

But, if I pass values like this:

```
...
          - https://example.com/some/file.zip
...
```

it saves a value with `>-`.

**To Reproduce**

Add an Application with Helm chart and pass a `valuesObject` that contains a list. Just like I showed above.

**Expected behavior**

**Screenshots**

**Version**

```shell
v2.12.3+6b9cd82
```

```shell
v2.12.6+4dab5bd
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
The change looks weird, but Argo CD hasn't actually changed the contents of the list. It's just used a different (but equivalent) YAML format.

**Comment by crenshaw-dev** [comment]
Closing because I think the behavior is correct. Let me know if I'm missing anything.

**Comment by AllYouZombies** [comment]
> Closing because I think the behavior is correct. Let me know if I'm missing anything.

Behavior may be correct, but UI throws an error.

So I cannot use some apps in ArgoCD because of this error:

1. I add list like this:
...
          - https://example.com/some/file.zip
...

2. It gets "refactored" like this:
...
  helm:
    valuesObject:
      api:
        additionalPlugins:
          - >-
            https://example.com/some/file.zip
      gateway:
        additionalPlugins:
          - >-
            https://example.com/some/file.zip
...

3. When I change some value in UI, it throws an error
4. GitOps doesn't work correctly with this behavior since ArgoCD says that my app isn't syncronized
