### ISSUE TITLE
Upgrade to Kustomize v3.1

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#2068]
v3.1 is out. Might as well update to it instead of v3.0 for Argo CD v1.2

Also we should remove kustomize v1 support

**Comment by alexec** [comment]
I don't think we should include this in v1.2. We're currently on feature freeze and this is could be a big piece of work.

**Comment by alexec** [comment]
See https://github.com/argoproj/argo-cd/pull/2072
