### ISSUE TITLE
ArgoCD cli always sends GOMAXPROCS log message to STDERR

### ISSUE THREAD

**Issue by jmf-mordis** [argoproj/argo-cd#20690]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Issue only present in the argocd cli 2.13.0, tested on `argocd-darwin-arm64` and `argocd-linux-amd64`

All argocd cli commands I tried send to STDERR this kind of message:

```shell
2024/11/07 10:21:35 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
```

If you check that the STDERR of your argocd cli command is empty in your CI/CD, this new version produces always an issue because it always sends this message to STDERR, you can only rely on the status code from now on. I don't think that this a relevant message to send to STDERR.

 I think that it is not an expected change, checking [this code](https://github.com/argoproj/argo-cd/blob/17c412e3f387457caf16457066dc854941532195/cmd/util/app.go#L97) and [this PR](https://github.com/argoproj/argo-cd/pull/20069/files).
 
 Setting the GOMAXPROCS env variable doesn't fix the issue, it just makes the argo cli send this other message to STDERR:
 
```shell
GOMAXPROCS=12 argocd version
2024/11/07 10:57:35 maxprocs: Honoring GOMAXPROCS="12" as set in environment
 ```

**To Reproduce**

Just invoking an `argocd version`, `argocd app list` or an `argocd app diff` is enough to reproduce the issue.

```shell
argocd app list
2024/11/07 10:52:34 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
```

**Expected behavior**

STDERR of the argocd cli is empty then there is no relevant error. (I don't consider the `GOMAXPROCS` logs a relevant error).

**Screenshots**

**Version**

(The issue is also in the argocd version )

```shell
 argocd version                                                                                                                                                                          2 ✘ 
2024/11/07 10:54:02 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
argocd: v2.13.0+347f221
  BuildDate: 2024-11-04T12:29:51Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.22.8
  Compiler: gc
  Platform: darwin/arm64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by Andrew-Jayne** [comment]
Also able to replicate

If anyone thinks that it is the OhMyZsh Plugin it is just argoCD CLI itself, 


```shell
➜  ~ argocd version
2024/11/07 20:30:46 maxprocs: Leaving GOMAXPROCS=14: CPU quota undefined
argocd: v2.13.0+347f221
  BuildDate: 2024-11-04T15:31:13Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.2
  Compiler: gc
  Platform: darwin/arm64
FATA[0000] Argo CD server address unspecified           
➜  ~ argocd
2024/11/07 20:30:55 maxprocs: Leaving GOMAXPROCS=14: CPU quota undefined
```

**Comment by pasha-codefresh** [comment]
https://github.com/argoproj/argo-cd/pull/20069

**Comment by ishitasequeira** [comment]
Fix has been merged.
