### ISSUE TITLE
appNamespace=undefined

### ISSUE THREAD

**Issue by Hronom** [argoproj/argo-cd#20699]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading from `2.12.0` to `2.13.0` we found that resources show progress status when it's already healthy.
This means UI can't get actual status from Argo CD server.

If we hit button `Refresh` or `Hard refresh` - not helps.

If we do regular refresh of window in browser - only after this it helps to get actual state.

I see error in developer console of browser
![image](https://github.com/user-attachments/assets/9453cfb3-be86-41e4-9a8e-ca80089d67bd)

For some reason it's doing calls to:
```
appNamespace=undefined
```

**To Reproduce**

Upgrade to `2.13.0` version

**Expected behavior**

No error

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by Hronom** [comment]
Found that version `2.12.0` doing calls to `appNamespace=`

**Comment by tkukushkin** [comment]
It seems it is connected with http path. If I open /applications/argocd/<name> with specifying application namespace, instead of /applications/<name> without namespace, it works.

**Comment by Hronom** [comment]
@andrii-korotkov-verkada please can you add someone to check, it actually blocks UI from getting actual state of app. So it may show it out of sync, but app already in healthy state. 

More on this hit refresh button in UI not helps.

Will be cool if fix can be included `2.13.1`

**Comment by gustavo-maxmilhas** [comment]
Im getting the same problem, argocd v2.13.0

![image](https://github.com/user-attachments/assets/d830e4dd-4217-442c-bdf7-3f011219e804)

I think i figured out when it happens.
When i select the application through the text field (search text field) and click the application to go into it, the error happens.
If i click directly on the application box and go into it, the error doesnt happen.

It seems to be an issue with the application search text input.

Acessing from here will start the error:
![image](https://github.com/user-attachments/assets/d5cb9659-88a4-469f-9fbf-5eb4453af741)

**Comment by Hronom** [comment]
If you click in UI on the application within list of all apps e.g. `/applications` it navigates you to the page where the error from the description is thrown, so there is no valid workaround more on that the refresh button stops working.

This needs to be fixed ASAP otherwise Argo CD from `2.13.0` not usable anymore.

**Comment by Hronom** [comment]
This is still a major issue for us that makes Argo CD of version `2.13.0` not usable, since search bar this is what we usually use. I believe for other too, then you have a lot of apps

**Comment by andrii-korotkov-verkada** [comment]
I can reproduce on a build from a recent master. Interestingly, these 403 start appearing after the page is loaded and keep coming in continuously.

**Comment by andrii-korotkov-verkada** [comment]
It might be this commit https://github.com/argoproj/argo-cd/commit/3658f8ec3785cd9980f5165bee4534c6d58ed266
