### ISSUE TITLE
Applications in unknown state for too many minutes, timeouts on repo server

### ISSUE THREAD

**Issue by lcostea** [argoproj/argo-cd#2070]
**Describe the bug**
After a change done in the repo that ArgoCD is watching, the applications fall into Unknown state.
The error that we see in the front UI is:
```rpc error: code = DeadlineExceeded desc = context deadline exceeded```
We are using helm with umbrella charts from a private chartmuseum.  
In the repo server logs we see the helm dependency error, and that's the only error we see (logs are below in the logs section).
We also see several timeouts when calling the repo server, some calls take a lot of time, more than 3 minutes.

**To Reproduce**
1. Put a new image tag inside a helm value file, inside a folder in a git repo that argocd is watching
2. ArgoCD notices the new commit in the git repo and starts the sync process: gets the content, it can see it is a helm folder, tries to do helm template and gives the error with chart dependency not found
3. All the helm stuff is being done (I can see it in the logs): helm init, helm repo add, helm dep build - no errors here
4. This is repeated every 3 minutes, without argocd to be able to sync the cluster state. Usually gets better after 8-10 retries, sometimes faster, while one time it took 3 hours.
I am also worried about some of the calls to the repo server taking as long as 200 seconds. While the majority is under 5 miliseconds, some take way too much and they are usually around the logs of unknown state.

**Expected behavior**
Make the sync without going into unknown state.

**Version**

```shell
argocd: v1.0.0-rc3+7c09221
  BuildDate: 2019-05-09T16:57:47Z
  GitCommit: 7c09221f7c3794c4d37428f804ef6bc382e9dd54
  GitTreeState: clean
  GoVersion: go1.11.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.1.0+c48712d.dirty
  BuildDate: 2019-07-22T22:11:10Z
  GitCommit: c48712d988320b7dbe6eb6b478a225cc6c385248
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

```
time="2019-08-01T08:03:29Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GenerateManifest grpc.request.deadline="2019-08-01T08:04:29Z" grpc.service=repository.RepoServerService grpc.start_time="2019-08-01T08:03:29Z" grpc.time_ms=0.98 span.kind=server system=grpc
time="2019-08-01T08:03:34Z" level=info msg="helm template . --namespace ****** --name microservice -f values.yaml -f image.yaml" dir="/tmp/git@gitlab.com:private_repo_here" execID=1Kxlm
time="2019-08-01T08:03:34Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GenerateManifest grpc.request.deadline="2019-08-01T08:01:14Z" grpc.service=repository.RepoServerService grpc.start_time="2019-08-01T08:00:14Z" grpc.time_ms=200333.14 span.kind=server system=grpc
time="2019-08-01T08:03:34Z" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:git@gitlab.com:private_repo_here,Path:staging/company/microservice,TargetRevision:master,Helm:&ApplicationSourceHelm{ValueFiles:[values.yaml image.yaml],Parameters:[],ReleaseName:microservice,},Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,}/9ed649a30a7ee8880515a76f866f383a46c85f67"
time="2019-08-01T08:03:34Z" level=info msg="git fetch origin --tags --force" dir="/tmp/git@gitlab.com:private_repo_here" execID=ktQqT
time="2019-08-01T08:03:36Z" level=info msg="git checkout --force 9ed649a30a7ee8880515a76f866f383a46c85f67" dir="/tmp/git@gitlab.com:private_repo_here" execID=QenE3
time="2019-08-01T08:03:36Z" level=info msg="git clean -fdx" dir="/tmp/git@gitlab.com:private_repo_here" execID=eMCdn
time="2019-08-01T08:03:36Z" level=info msg="git rev-parse HEAD" dir="/tmp/git@gitlab.com:private_repo_here" execID=mD4mX
time="2019-08-01T08:03:36Z" level=info msg="helm init --client-only --skip-refresh" dir="/tmp/git@gitlab.com:private_repo_here/staging/company/microservice" execID=RK479
time="2019-08-01T08:03:36Z" level=info msg="helm template . --namespace ******** --name microservice -f values.yaml -f image.yaml" dir="/tmp/git@gitlab.com:private_repo_here/staging/company/microservice" execID=F3S8f
time="2019-08-01T08:03:36Z" level=error msg="`helm template . --namespace ******* --name microservice -f values.yaml -f image.yaml` failed exit status 1: Error: found in requirements.yaml, but missing in charts/ directory: microservice" execID=F3S8f
time="2019-08-01T08:03:36Z" level=info msg="helm repo add --username *** --password *** private_chartmuseum http://url_to_chartmuseum.com" dir="/tmp/git@gitlab.com:private_repo_here/staging/company/microservice" execID=pAQNx
time="2019-08-01T08:03:36Z" level=info msg="helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/" dir="/tmp/git@gitlab.com:private_repo_here/staging/company/microservice" execID=JOwDp
time="2019-08-01T08:03:37Z" level=info msg="helm repo add bitnami https://charts.bitnami.com" dir="/tmp/git@gitlab.com:private_repo_here/staging/company/microservice" execID=hhOHL
time="2019-08-01T08:03:38Z" level=info msg="helm dependency build" dir="/tmp/git@gitlab.com:private_repo_here/staging/company/microservice" execID=uSGTt
time="2019-08-01T08:03:39Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GenerateManifest grpc.request.deadline="2019-08-01T08:04:39Z" grpc.service=repository.RepoServerService grpc.start_time="2019-08-01T08:03:39Z" grpc.time_ms=3.856 span.kind=server system=grpc
```

**Have you thought about contributing a fix yourself?**

Yes, done it before and I will do it again.

If you want to get involved, check out the 
[contributing guide](https://github.com/argoproj/argo-cd/blob/master/docs/CONTRIBUTING.md), then reach out to us on [Slack](https://argoproj.github.io/community/join-slack) so we can see how to get you started.

**Comment by alexec** [comment]
This has got the recent timeout code in it (v1.1) which should cap exec's at 90s (thought if you have multiple execs in a request then this can be longer than 90s obvs)

**Comment by alexec** [comment]
this is specifically an issue with Helm? or any tool?

**Comment by lcostea** [comment]
Seems like something related to helm, it is a helm directory it is trying to apply, but I can't find anything wrong with it
this exec timeout, this is called from the repo server, right? So you think there is a helm command (or some other command) that takes more than 90s?
What about the call from api server to repo server, isn't it by default giving timeout at 60s?

**Comment by alexmt** [comment]
Repo server processes only one manifest generation request per repo. So if repo has too many applications then you might get a queue of requests which depends on the same repo. In this case you can increase the number of repo servers.

**Comment by lcostea** [comment]
we have 17 apps in that repo, on that specific branch, it is the biggest we have
thanks, I will increase the number of repo servers and see what happens

**Comment by dimitarKiryakov** [comment]
We had the same problem, because we are using a private repo which is in network restricted landscape. The reason was because the helm chart had requirments.yaml. Despite that the charts were in local folder in the repo, helm by default is making call to the public chart repository. In our case since we are in private enviroment this hidden call of helm gets timeout each time it is executed and your error appeared. In order to overcome that we had to copy dependent charts in chart directory of the main chart.  I am not sure if your scenario with private or restricted network is the same.

**Comment by lcostea** [comment]
After increasing the number of repo server pods the issue didn't appear anymore. Also this is already documented in the documentation, scaling up section: https://argoproj.github.io/argo-cd/operator-manual/high_availability/#scaling-up 
So because I don't see any other actions we could take I am going to close the issue

**Comment by frankvandekerkhof** [comment]
it's a bug
