### ISSUE TITLE
Cannot add rancher-managed cluster using rancher-supplied kubectl

### ISSUE THREAD

**Issue by trondhindenes** [argoproj/argo-cd#20733]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
We have 3 kubernetes clusters:
- mgmt cluster running Rancher. Rancher endpoint is available on the internet
- argocd cluster (running argocd). ArgoCD has ingress enabled, and is available on the internet.
- app cluster. This cluster is added to Rancher. It is not directly available on the internet, but we can access it using Rancher as a "kubectl proxy". When downloading the kubecontext from rancher, the server url will be something like `https://rancher.domain.com/k8s/clusters/c-m-rs4hv9xr`

I can successfully log in to ArgoCD using the argocd cli. When I'm trying to add "app cluster" to ArgoCD using the "rancher-supplied" kubecontext I run something like this:
`cluster add app-cluster --kubeconfig app-cluster-downloaded-from-rancher.yaml --cluster-endpoint kubeconfig -y --upsert --grpc-web --argocd-context myargocdcluster.domain.com`

The error I'm getting is:
```
INFO[0000] ServiceAccount "argocd-manager" already exists in namespace "kube-system" 
INFO[0000] ClusterRole "argocd-manager-role" updated    
INFO[0000] ClusterRoleBinding "argocd-manager-role-binding" updated 
FATA[0093] rpc error: code = PermissionDenied desc = {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-rs4hv9xr\" is forbidden: User \"system:unauthenticated\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope: Azure does not have opinion for this user.","Cause":null,"FieldName":""} 
```
This error comes from the argocd _server_ attempting to make a request to Rancher on a non-valid path as path of cluster registration.

Right before the error, we can see the folling traffic in the ingress controller logs on the rancher cluster, all of which seem to originate from the argocd server
```
GET","RequestPath":"/k8s/clusters/c-m-rs4hv9xr/api/v1/namespaces/kube-system/serviceaccounts/argocd-manager
GET","RequestPath":"/k8s/clusters/c-m-rs4hv9xr/api/v1/namespaces/kube-system/secrets/argocd-manager-token-xsh2d"
GET","RequestPath":"/k8s/clusters/c-m-rs4hv9xr/api/v1/namespaces/kube-system/secrets/argocd-manager-token-xsh2d
GET","RequestPath":"/k8s/clusters/c-m-rs4hv9xr/version?timeout=32s
```
The last of these requests fail with a 403, and the registration fails.

At first I suspected that the error might be in `k8s.io/client-go`,. I tested by creating a rudimentary client to read server versions using that client, and it works fine against a Rancher-supplied kubeconfig when calling `Discovery().ServerVersion()`:

Also tested that `kubectl version` against a rancher-managed cluster works fine. 
```
Kubernetes host: https://rancher.domain.com/k8s/clusters/c-m-rs4hv9xr
Kubernetes version: v1.30.4
```

This last call (the one that's failing) is the first call originating from the argocd-server, the prior ones come directly from the client. The calls from the client are using whatever user was konfigured in the supplied kubeconfig, while the one from the server attempts to use the provisioned service account. I suspect this is where something fails.

**To Reproduce**
I realize this one is difficult to reproduce, as it involves 3 clusters although I guess it can be done with one, as long as one avoids using cluster-internal urls.

**Expected behavior**

The cluster registration should go through

**Screenshots**

**Version**

```shell
argocd-server: v2.12.6+4dab5bd
  BuildDate: 2024-10-18T17:39:26Z
  GitCommit: 4dab5bd6a60adea12e084ad23519e35b710060a2
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.2 2024-05-22T15:19:38Z
  Helm Version: v3.15.2+g1a500d5
  Kubectl Version: v0.29.6
  Jsonnet Version: v0.20.0
```

**Logs**
Error logged by rancher-server after having received the 403 from rancher
```
argocd-central-server-5f4dc4d7b-8cm5s server time="2024-11-09T22:35:31Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = {\"Code\":{\"Code\":\"Forbidden\",\"Status\":403},\"Message\":\"clusters.management.cattle.io \\\"c-m-rs4hv9xr\\\" is forbidden: User \\\"system:unauthenticated\\\" cannot get resource \\\"clusters\\\" in API group \\\"management.cattle.io\\\" at the cluster scope: Azure does not have opinion for this user.\",\"Cause\":null,\"FieldName\":\"\"}" grpc.code=PermissionDenied grpc.method=Create grpc.service=cluster.ClusterService grpc.start_time="2024-11-09T22:35:31Z" grpc.time_ms=195.445 span.kind=server system=grpc

```

**Comment by andrii-korotkov-verkada** [comment]
> GET","RequestPath":"/k8s/clusters/c-m-rs4hv9xr/version?timeout=32s
> If ArgoCD needs to read the server version, the correct url would be /k8s/clusters/c-m-rs4hv9xr/version, given a kubeconfig server path of https://rancher.domain.com/k8s/clusters/c-m-rs4hv9xr

I'm a bit confused, the request path matches the url you call correct. Should it be a full url instead?

**Comment by trondhindenes** [comment]
Oh crap you're right. I was way too tired yesterday. So why is this failing....
I'll go over everything and doible-check it now

**Comment by trondhindenes** [comment]
So after enabling full header logging in the ingress controller I could see what was happening, and that the first request to attempt jwt auth was failing. Turns out Rancher has a setting for this, and its disabled by default: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/jwt-authentication.
So, not a bug in ArgoCD after all. Hope someone else finds this useful :-)
