### ISSUE TITLE
App resources table view looks odd

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#2073]
**Describe the bug**

Even if app resources/namespace have very long names the table looks empty. Status icons takes around 20% of the column:

![Screen Shot 2019-08-01 at 10 49 27 AM](https://user-images.githubusercontent.com/426437/62315474-37e75d80-b44a-11e9-8bc3-b219992160c6.png)

We need to either fallback to limited width or add more information to the table.

**Comment by alexec** [comment]
what size screen are you using - looks huge?

**Comment by alexmt** [comment]
15 inch laptop. Here is example of an with 'real-life' long names:

<img width="1657" alt="Screen Shot 2019-08-01 at 3 02 01 PM" src="https://user-images.githubusercontent.com/426437/62330410-780c0780-b46d-11e9-8053-93523dc3fc5b.png">

**Comment by alexec** [comment]
that looks OK to me - what am I missing?

**Comment by alexmt** [comment]
For some reason, we are using only 11 columns instead of 12. So there is empty space after Status column. Status column is too wide for large screen.

**Comment by alexmt** [comment]
Fixed
