### ISSUE TITLE
Add support for passing --skip-schema-validation to help

### ISSUE THREAD

**Issue by dmosesson** [argoproj/argo-cd#20771]
# Summary

Add the ability to skip helm schema validation in helm template (pass `--skip-schema-validation` when argo uses `helm template`)

# Motivation

When running offline clusters, using helm charts that refer to external schemas for validation is very challenging. Projects historically have had to chose between chose between providing a schema for those with internet connectivity (usually to something like kubernetesjsonschema.dev) to aid in debugging and breaking those without an internet connection.

Since Helm 3.16, helm has a new flag for `helm template`, `--skip-schema-validation` that can be used to fix this issue for those of us that have clusters with no internet connectivity.

# Proposal

The most straightforward way to implement this would be to create a new property in the `Application` CRD that would be modelled after the `skipCRDs` property that passes `--skip-schema-validation` to the helm template command.

Alternatively, there could be a list property that allows passing arbitrary helm template parameters to the command. This would be more flexible, but might come with some around passing either flags that are controlled in other ways (like the skipCRDs flag).

**Comment by crenshaw-dev** [comment]
I'd be in favor of a `skipSchemaValidation` field.

**Comment by andrii-korotkov-verkada** [comment]
Should this be a property on application sources?

**Comment by dmosesson** [comment]
Yes, it was added under the helm properties under source/s

**Comment by andrii-korotkov-verkada** [comment]
Some PRs trying to upgrade helm https://github.com/argoproj/argo-cd/pull/20678, https://github.com/argoproj/argo-cd/pull/20650
