### ISSUE TITLE
[Documentation] - Version upgrade docs missing from sidebar after 2.10-2.11

### ISSUE THREAD

**Issue by schlags** [argoproj/argo-cd#20770]
# Summary

We seem to be missing the v2.11-2.12 upgrading document from the sidebar, but it is present in the body of the upgrading Overview.

To someone viewing the upgrade docs from a high level, it looks like v2.12 is not yet documented with the upgrade notes.

<img width="1072" alt="image" src="https://github.com/user-attachments/assets/a0068ec0-9daf-4c52-81dd-4f1935149476">

# Motivation

Avoid confusion with those looking to the docs for upgrade notes, and only seeing a 2.11 option from a high level.

# Proposal

I looked into my fork to try and make this sidebar item show up, but it doesn't seem obvious where things are/are not included for the sidebar, are we at a limit of the sidebar items that can automatically render there?

**Comment by andrii-korotkov-verkada** [comment]
Can you link the page you are viewing, please?

**Comment by schlags** [comment]
You bet. Just navigate to the stable version in the picker at the top:

https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/overview/

And you'll see 2.11 -> 2.12 in the overview, but the sidebar only includes up to 2.10 -> 2.11

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/329bebf4-c0a6-421e-a83b-fb498e4e0f9f">

**Comment by schlags** [comment]
Switching the picker to `latest` or `release-2.12` fixes the issue.

**Comment by andrii-korotkov-verkada** [comment]
Those seem to be auto-generated, since searching for "v2.10 to 2.11" only returns this file https://github.com/argoproj/argo-cd/blob/6d8d32f170c9db33cd34029cc554afeb335a5faf/docs/operator-manual/upgrading/2.11-2.12.md and similar for others. We are probably looking at some UI fix that needs to be cherry-picked. Let me try to find it.

**Comment by andrii-korotkov-verkada** [comment]
Can't find that :(

**Comment by schlags** [comment]
Yeah I messed around on my fork a bunch and couldn't find a reason this wasn't rendering. Odd

**Comment by blakepettersson** [comment]
This seems to have been fixed since #20657
