### ISSUE TITLE
multiple project were deploy on same namespace with shared pv and pvc

### ISSUE THREAD

**Issue by wqbbs911** [argoproj/argo-cd#20779]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
we have multiple projects were deployed in same namespace (like Front-end:ctms-argotest-web-dev and back-end:ctms-argotest-core-provider-dev ),  them used one shared pvc and pv , i noticed a behaviour with the sync process , if we synced ctms-argotest-web-dev ,  ctms-argotest-core-provider-dev  will become OutOfSync  , and if we synced ctms-argotest-core-provider-dev, synced ctms-argotest-web-dev  will become OutOfSync .
when it happended , i checked pv and pvc detail, looks like kargo changed the labels  , i think this is root issue:
![image](https://github.com/user-attachments/assets/2a59b86d-7442-45f9-b708-ae6b2960da83)

![image](https://github.com/user-attachments/assets/6665960b-e23b-4cec-b33a-46d6ee7254c7)

Is there any way to solve this problem ?

**To Reproduce**

deploy two or more projects in same namespace and they use same pvc

**Expected behavior**
All projects show Synced

**Screenshots**

**Version**

```shell
argocd: v2.12.3+6b9cd82
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by Mangaal** [comment]
I'm trying to better understand the issue you're encountering. You have multiple ArgoCD applications deployed in the same namespace, and they share a Persistent Volume (PV) and Persistent Volume Claim (PVC). When you sync one of the applications, the other application gets marked as "OutOfSync." It seems like the issue may be related to how ArgoCD is managing the shared resources, possibly altering the labels on the PV/PVC during synchronization, which causes the second application to detect a mismatch in state.

**Comment by Mangaal** [comment]
To avoid conflicts between applications that share a Persistent Volume (PV) or Persistent Volume Claim (PVC).
Create a dedicated ArgoCD application specifically for managing shared resources.
