### ISSUE TITLE
Support setting Helm string parameters using CLI/UI

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#2078]
**Is your feature request related to a problem? Please describe.**
The v1.2 Argo CD version introduced support to force ambiguously-typed values to be strings. This feature is available only in declaratively defined apps. We need to add CLI/UI support.

**Describe the solution you'd like**

```
argocd app set <appName> --helm-parameter param1=hello --helm-parameter-string param2=true
```

**Comment by alexec** [comment]
```
      --set stringArray          set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --set-file stringArray     set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
```

**Comment by alexec** [comment]
I suggest `--helm-set` and `--helm-set-string`.

**Comment by tomcruise81** [comment]
How does this accommodate `--set-file`?

**Comment by alexec** [comment]
@tomcruise81 - no - but might be a work-around. If you were interested in `set-file` would you be interested in submitting a PR?

**Comment by tomcruise81** [comment]
@alexec - started work on https://github.com/argoproj/argo-cd/pull/2752

**Comment by musabmasood** [comment]
Do have support for this in `application.yaml` as declarative setup?
