### ISSUE TITLE
serverSideDiff error when removing block from spec.containers[] in Helm chart

### ISSUE THREAD

**Issue by thecosmicfrog** [argoproj/argo-cd#20792]
Checklist:

* [y] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [y] I've included steps to reproduce the bug.
* [y] I've pasted the output of `argocd version`.

**Describe the bug**

I am seeing an error in Argo CD when upgrading a Helm chart from one version to another. The only difference between the Helm chart versions is that the new version removes the `resources` block from `spec.template.spec.containers[0]` in the `Deployment` object. I have noticed that removing other blocks (e.g. `env`) results in the same issue (so it is not just a `resources` problem).

The specific error is:

```
Failed to compare desired state to live state: failed to calculate diff: error calculating server side diff: serverSideDiff error: error removing non config mutations for resource Deployment/test-app: error reverting webhook removed fields in predicted live resource: .spec.template.spec.containers: element 0: associative list with keys has an element that omits key field "name" (and doesn't have default value)
```

<br>

Additional details:

* The **sync options** we have enabled are just `ServerSideApply=true`.
* For **compare options**, `ServerSideDiff` is enforced on the server side by setting `controller.diff.server.side: true` in the `argo-helm` chart values.
* After a certain period of time (indeterminate - a few minutes?), the app status goes to **Healthy/Synced/Sync OK**, which initially suggests it "fixed itself", however, you then notice that the "Last Sync" version is still the old Helm chart version. Then, clicking **Refresh** will re-trigger the error to appear. Triggering a manual **Sync** appears to _**actually**_ fix the issue.

<br>

**To Reproduce**

I have built a Helm chart to reproduce this, with two versions (`0.0.1` and `0.0.2`). Updating will not work, as you will see.

* Prerequisites:
    * Argo CD installed to the `kube-system` namespace.
    * Server-side diff enabled (`controller.diff.server.side: true`).
    * Another namespace created called `bug` (to host the k8s objects).

* Create a file called `application.yaml` to represent our Argo CD `Application` object:
   ```yaml
   apiVersion: argoproj.io/v1alpha1
   kind: Application
   metadata:
     name: test-app
   spec:
     project: default
     source:
       repoURL: https://thecosmicfrog.github.io/helm-charts/
       path: .
       targetRevision: 0.0.1  # Baseline chart version:
                              # https://github.com/thecosmicfrog/helm-charts/tree/0.0.1/charts/test-app
       helm:
         releaseName: test-app
       chart: test-app
     destination:
       server: https://kubernetes.default.svc
       namespace: bug
     syncPolicy:
       automated:
         prune: true
         selfHeal: true
       syncOptions:
         - ServerSideApply=true
     revisionHistoryLimit: 10
   ```

* Apply this to the cluster:
 `kubectl apply -n kube-system -f application.yaml`

* Pods should come up without issue and everything should be correctly synced - as expected for a simple `Deployment`.

* Update `application.yaml` to bump the Helm chart to the new version:
   ```diff
   apiVersion: argoproj.io/v1alpha1
   kind: Application
   metadata:
     name: test-app
   spec:
     project: default
     source:
       repoURL: https://thecosmicfrog.github.io/helm-charts/
       path: .
   -   targetRevision: 0.0.1  # Baseline chart version:
   -                          # https://github.com/thecosmicfrog/helm-charts/tree/0.0.1/charts/test-app
   +   targetRevision: 0.0.2  # New chart with `spec.template.spec.containers[0].resources` block removed:
   +                          # https://github.com/thecosmicfrog/helm-charts/compare/0.0.1...0.0.2
       helm:
         releaseName: test-app
       chart: test-app
     destination:
       server: https://kubernetes.default.svc
       namespace: bug
     syncPolicy:
       automated:
         prune: true
         selfHeal: true
       syncOptions:
         - ServerSideApply=true
     revisionHistoryLimit: 10
   ```

* Apply this to the cluster:
 `kubectl apply -n kube-system -f application.yaml`

<br>

**Expected behavior**

The new chart version should install without error, as it is such a straightforward change (`resources` block removed from `containers[0]` block).

<br>

**Actual behavior**

**Sync Status** enters an _**Unknown**_ state with the new chart version, and **App Conditions** displays _**1 Error**_. That error is:

```
Failed to compare desired state to live state: failed to calculate diff: error calculating server side diff: serverSideDiff error: error removing non config mutations for resource Deployment/test-app: error reverting webhook removed fields in predicted live resource: .spec.template.spec.containers: element 0: associative list with keys has an element that omits key field "name" (and doesn't have default value)
```

The only way to seemingly complete the update is to _**manually sync**_, which works without issue. We have **Auto Sync** enabled, so I'm not sure why that does not resolve the issue.

<br>

**Screenshots**

* Argo CD UI after applying chart `0.0.2`:

   ![Screenshot 2024-11-13 at 17 31 24](https://github.com/user-attachments/assets/552346e4-0856-443c-95c1-40c68a0a878a)

<br>

* Several (5-ish?) minutes later - with no intervention from me - error "appears" to be resolved... but note the versions are not matching between both sync fields:

   ![Screenshot 2024-11-13 at 17 38 01](https://github.com/user-attachments/assets/7d213b6a-79dc-4251-92d6-b7e8aad72baa)

<br>

* Then, clicking **Refresh**...

   ![Screenshot 2024-11-13 at 17 40 17](https://github.com/user-attachments/assets/0561e2b0-f597-46fb-b8cc-bfd05ef96834)

<br>

* ...results in the same _**1 Error**_ outcome as before...

   ![Screenshot 2024-11-13 at 17 41 49](https://github.com/user-attachments/assets/056f9b7d-fc28-4aeb-855b-d60e77c649b5)

<br>

* ...and the Pods present on the cluster are still from the "old" (`0.0.1`) chart version:

   ![Screenshot 2024-11-13 at 17 42 29](https://github.com/user-attachments/assets/3f3a4bdb-8702-42f4-be30-0f7241031e0a)

<br>

* The only way to fix is to manually **Sync**:

   ![Screenshot 2024-11-13 at 17 59 30](https://github.com/user-attachments/assets/5267d1aa-7316-4931-b8ff-a44a92304199)

<br>

* Which finally brings the app into sync at `0.0.2`:

   ![Screenshot 2024-11-13 at 18 02 42](https://github.com/user-attachments/assets/0f2f083c-3625-40d8-a80f-5e5993c80936)

<br>

**Version**

```shell
2024/11/13 14:23:55 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
argocd: v2.13.0+347f221
  BuildDate: 2024-11-04T15:31:13Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.2
  Compiler: gc
  Platform: darwin/arm64
WARN[0001] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.13.0+347f221
  BuildDate: 2024-11-04T12:09:06Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

<br>

**Logs**

```
Failed to compare desired state to live state: failed to calculate diff: error calculating server side diff: serverSideDiff error: error removing non config mutations for resource Deployment/test-app: error reverting webhook removed fields in predicted live resource: .spec.template.spec.containers: element 0: associative list with keys has an element that omits key field "name" (and doesn't have default value)
```

Let me know if the above is enough information to reproduce the issue.

Thanks for your time - Aaron

**Comment by thecosmicfrog** [comment]
@andrii-korotkov-verkada Yes, of course. You can find the chart here:
https://github.com/thecosmicfrog/helm-charts/tree/main/charts%2Ftest-app

There are also corresponding Git tags for `0.0.1` and `0.0.2`.

**Comment by andrii-korotkov-verkada** [comment]
When this happens, can you looks at the current vs desired manifest, please?
It's probably a bug in removing webhook fields for comparison (unless you actually have a webhook in the cluster that does it), but worth a shot.

**Comment by thecosmicfrog** [comment]
@andrii-korotkov-verkada The diff seems to be in a bit of a "confused" state from my viewing. See screenshots below.

* **Live Manifest** for the `Deployment` object shows the `resources` block, as expected.

<img width="1302" alt="Screenshot 2024-11-14 at 14 49 02" src="https://github.com/user-attachments/assets/7f770231-0e7b-4f0a-879c-d9483ea7c260">

<br><br>

* **Desired Manifest** is missing the `resources` block (again, as expected).

<img width="1178" alt="Screenshot 2024-11-14 at 14 49 32" src="https://github.com/user-attachments/assets/c70449c8-4b08-4055-b6ed-6eeb7d2c3019">

<br><br>

* But, the **Diff** tab is completely blank.

<img width="1288" alt="Screenshot 2024-11-14 at 14 46 44" src="https://github.com/user-attachments/assets/e7ae5de5-57ea-4c28-9d18-9b70f4f11fe4">

<br><br>

I hope that helps. Let me know what additional information I can provide.

**Comment by andrii-korotkov-verkada** [comment]
Can you copy-paste whole manifests, please? Sorry for bugging you, it's just I'm looking for things out of line and need full manifests to check that.

**Comment by andrii-korotkov-verkada** [comment]
Hm, I don't see anything obviously wrong at the moment.

**Comment by thecosmicfrog** [comment]
> Hm, I don't see anything obviously wrong at the moment.

Indeed. Notably, setting `IncludeMutationWebhook=true` in the **SyncOptions** appears to resolve the issue, but this doesn't seem like it should be necessary for such a simple change (removal of a block from `containers[]`)? Hence why I'm hesitant to proceed with setting that flag.

Are you able to reproduce on your side? I believe the instructions and charts I provided should be enough to do so, but please advise if I can provide anything else.

**Comment by andrii-korotkov-verkada** [comment]
One more thing - do you have mutating webhooks setup in the cluster?

**Comment by thecosmicfrog** [comment]
We have three MutatingWebhooks:

* `aws-load-balancer-webhook`
* `pod-identity-webhook`
* `vpc-resource-mutating-webhook`

As I understand it, all are a part of Amazon EKS and AWS Load Balancer Controller.

**Comment by thecosmicfrog** [comment]
Hi @andrii-korotkov-verkada. I have some additional information which should help you in finding the root cause of this.

I use Argo Rollouts for most of my applications (thus I use `Rollout` objects instead of `Deployment`). But the original error  was triggered for an app using a `Deployment` and thus is what I used in my reproduction Helm charts.

Out of curiosity, I decided to see if the same error would trigger when using `Rollout`. I figured it would, since that is mostly a drop-in replacement for `Deployment` but, to my surprise, it seems to work without issue!

Please see my latest chart versions:
* `0.3.1`: This chart is essentially the same as `0.0.1`, but using a `Rollout` instead of a `Deployment`.
* `0.3.2`: This is `0.3.1` with the `resources` block removed from `spec.template.spec.containers[0]`.

See the code for [0.3.1](https://github.com/thecosmicfrog/helm-charts/tree/0.3.1) and [0.3.2](https://github.com/thecosmicfrog/helm-charts/tree/0.3.2) here. I had to add two very basic `Service` objects as this is required by Argo Rollouts, but you can likely just ignore them.

The chart artifacts are built and uploaded as before, so you can simply update `spec.source.targetRevision` in the `application.yaml` file I provided in the original post and `kubectl apply`.

I hope this helps.

Thanks - Aaron

**Comment by andrii-korotkov-verkada** [comment]
I can see that various probes are being modified as well, like readiness probe, i.e. live manifest has extra fields comparing to the target one.

Also, `terminationMessagePath: /dev/termination-log` and `terminationMessagePolicy: File` are in live state, but not in the target state.

Do you know what adds those?

**Comment by thecosmicfrog** [comment]
@andrii-korotkov-verkada The probe changes are coming from Kubernetes defaults:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes

i.e. the default `periodSeconds` is 10`; the default `successThreshold` is `1`, etc.

The same for `terminationMessagePath` and `terminationMessagePolicy` - these are Kubernetes defaults, per:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#deployment-v1-apps

**Comment by andrii-korotkov-verkada** [comment]
I see. At this point, I don't know what can be the issue. I'd suggest trying to get a minimal repro, i.e. remove fields from the spec until it starts working normally.

**Comment by thecosmicfrog** [comment]
@andrii-korotkov-verkada I'm not sure what else I can remove here - I feel the chart I provided (a single `Deployment` object) was pretty minimal?

Our real applications are significantly more complex, so I already trimmed down as much as I could, going for this "single Deployment echo-server" example.

One thing that I know fixes the issue is setting `IncludeMutationWebhook=true` in the `Application`'s **compare-options**, per:
https://argo-cd.readthedocs.io/en/latest/user-guide/diff-strategies/#mutation-webhooks

But it's unclear to me why this fixes the issue. From a pure and simple perspective, why would removing a field from a `Deployment` break Argo's sync engine?

I note many similarities with this open issue: https://github.com/argoproj/argo-cd/issues/17568. The reporter is seeing the same error, word-for-word. The error itself doesn't even seem to make sense (it's complaining that `containers[0]` doesn't have a `name` field, but it does.

Thanks for your help!

**Comment by andrii-korotkov-verkada** [comment]
I see. I'll give a shot to reading the code for removing webhook mutations and try to find bugs there

**Comment by thecosmicfrog** [comment]
Thanks @andrii-korotkov-verkada - I've given it an approval from an end user's perspective. Not sure that carries much weight though 🙂

**Comment by andrii-korotkov-verkada** [comment]
Try adding `scheme: HTTP` to your probes.

**Comment by andrii-korotkov-verkada** [comment]
Looking at https://github.com/argoproj/gitops-engine/blob/847cfc9f8b200e96a70b591a68b9fb385cf2ce56/pkg/diff/diff.go#L204, I wonder if we should get managed fields from both predicted and actual live resource instead of just predicted, given this comment https://github.com/argoproj/gitops-engine/blob/847cfc9f8b200e96a70b591a68b9fb385cf2ce56/pkg/diff/diff.go#L252-L253. @leoluz, @crenshaw-dev, thoughts as code authors?

**Comment by thecosmicfrog** [comment]
> Try adding scheme: HTTP to your probes (though probably that's not it).

Same result, unfortunately. New charts (`0.4.1` and `0.4.2`) released with `scheme: HTTP` added:
https://github.com/thecosmicfrog/helm-charts/tree/0.4.1/charts/test-app
https://github.com/thecosmicfrog/helm-charts/tree/0.4.2/charts/test-app

**Comment by andrii-korotkov-verkada** [comment]
Also, the parameter `manager` there is passed but unused.

**Comment by andrii-korotkov-verkada** [comment]
I may have found an issue. When the object to merge is computed, it may lack a name field, e.g.
```
&{map[metadata:map[annotations:<nil> creationTimestamp:2022-09-18T23:50:25Z generation:1 resourceVersion:7492752 uid:731f7434-d3d9-47fa-b179-d9368a84f7c9] spec:map[progressDeadlineSeconds:600 revisionHistoryLimit:10 strategy:<nil> template:map[metadata:map[creationTimestamp:<nil>] spec:map[containers:[map[livenessProbe:map[failureThreshold:3 successThreshold:1 timeoutSeconds:1] terminationMessagePath:/dev/termination-log terminationMessagePolicy:File]] dnsPolicy:ClusterFirst restartPolicy:Always schedulerName:default-scheduler securityContext:<nil> terminationGracePeriodSeconds:30]]] status:<nil>]}
```

Good news is I have a test to repro and would hopefully have a fix soon.

**Comment by andrii-korotkov-verkada** [comment]
Meh, this seems like something structured-merge-diff library needs to fix.

**Comment by thecosmicfrog** [comment]
@andrii-korotkov-verkada Exciting news! I've followed the PR and look forward to it being merged. Thank you for your help here!

**Comment by andrii-korotkov-verkada** [comment]
I've also posted on Kubernetes Slack in the respective channel and tagged whom seems to be the maintainer based on commits.

**Comment by thecosmicfrog** [comment]
Hi @andrii-korotkov-verkada. Thanks for the discussion on today's contributor call.

Am I correct in my understanding that you are waiting on further discussion with the `structured-merge-diff` maintainers? And, failing any progress on that side, you will aim to merge your fix on the Argo CD side as a workaround? Just so I'm clear.

Thanks again.

**Comment by andrii-korotkov-verkada** [comment]
We are waiting for them, yes. There's a volunteer to look into this at the moment. I'm not sure a workaround would get merged unless they really push back hard.

**Comment by leoluz** [comment]
@thecosmicfrog @andrii-korotkov-verkada  Structured-merge-diff PR with the fix is now merged:
https://github.com/kubernetes-sigs/structured-merge-diff/pull/275

**Comment by leoluz** [comment]
@thecosmicfrog The fix is in this PR:
https://github.com/argoproj/argo-cd/pull/20842
Auto-merge is enabled. Will you be able to validate this build in your environment?

**Comment by thecosmicfrog** [comment]
@leoluz Great news, thanks! I'm using `argo-helm` to install and configure Argo CD. Are there any release of that chart I can use, or instructions on how to build my own? Apologies - am away from my dev machine at the moment.

**Comment by andrii-korotkov-verkada** [comment]
@thecosmicfrog, I usually use `make image` and create docker manifests as well, and then upload it in whatever format the company uses (AWS ECR in our case).

**Comment by leoluz** [comment]
Reopening and waiting for @thecosmicfrog to confirm if the issue is addressed in current `master`

**Comment by thecosmicfrog** [comment]
Thanks @leoluz @andrii-korotkov-verkada - will probably be tomorrow before I can check. Will report back ASAP.

**Comment by thecosmicfrog** [comment]
Hi @andrii-korotkov-verkada @leoluz. Great news. I have tested three previously-failing applications and they are now working as expected! No more errors related to server-side diff and the applications sync up correctly.

I just wanted to express my thanks to you for working on this. It's been a great experience and I hugely appreciate it.

Side question - do you know when this new image will be released in `argo-helm`?

I'll go ahead and close the issue now. All the best! 🙂

**Comment by andrii-korotkov-verkada** [comment]
You are welcome!

**Comment by leoluz** [comment]
> Side question - do you know when this new image will be released in argo-helm?

@thecosmicfrog This fix is going to be part for Argo CD 2.14.

**Comment by thecosmicfrog** [comment]
@leoluz Fantastic, thanks!

**Comment by toni-rib-skydio** [comment]
I just ran into this trying to upgrade KEDA with argocd. Is there an update on when 2.14 is going to be released where this would be fixed?

**Comment by thecosmicfrog** [comment]
@toni-rib-skydio 2.14 is released 🙂
