### ISSUE TITLE
argocd cluster add Failed

### ISSUE THREAD

**Issue by chominnn** [argoproj/argo-cd#20884]
i'm using haproxy for Multi master node K8s Cluster
But can't finding the haproxy when I add the argo cluster.
So I tried entering the ip address of haproxy as --server option, but it still gets an error.

root@master01:~# argocd cluster add kubernetes-admin@kubernetes
WARNING: This will create a service account `argocd-manager` on the cluster referenced by context `kubernetes-admin@kubernetes` with full cluster level privileges. Do you want to continue [y/N]? y
INFO[0001] ServiceAccount "argocd-manager" already exists in namespace "kube-system" 
INFO[0001] ClusterRole "argocd-manager-role" updated    
INFO[0001] ClusterRoleBinding "argocd-manager-role-binding" updated 
FATA[0001] rpc error: code = Unknown desc = Get "https://haproxy:6443/version?timeout=32s": dial tcp: lookup haproxy on 10.96.0.10:53: no such host 

root@master01:~# argocd cluster add kubernetes-admin@kubernetes --server 211.39.158.60
WARNING: This will create a service account `argocd-manager` on the cluster referenced by context `kubernetes-admin@kubernetes` with full cluster level privileges. Do you want to continue [y/N]? y
INFO[0001] ServiceAccount "argocd-manager" already exists in namespace "kube-system" 
INFO[0001] ClusterRole "argocd-manager-role" updated    
INFO[0001] ClusterRoleBinding "argocd-manager-role-binding" updated 
FATA[0001] Failed to establish connection to 211.39.158.60:443: dial tcp 211.39.158.60:443: connect: connection refused

**Comment by andrii-korotkov-verkada** [comment]
What's your argocd cli and server version?

**Comment by chominnn** [comment]
> argocd cli와 서버 버전은 무엇인가요?

root@master01:~# argocd version
argocd: v2.7.5+a2430af
  BuildDate: 2023-06-16T15:00:03Z
  GitCommit: a2430af1c356b283e5e3fc5bde1f5e2b5199f258
  GitTreeState: clean
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.11.3+3f344d5
  BuildDate: 2024-06-06T08:42:00Z
  GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0


---

argocd

**Comment by andrii-korotkov-verkada** [comment]
Where is haproxy located? Can you curl it normally from the cluster ArgoCD is deployed in?
