### ISSUE TITLE
Cluster name selection is not working in New Application. Only cluster URL is working for Destination section.

### ISSUE THREAD

**Issue by motmot84** [argoproj/argo-cd#20961]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

By default, the dropdown selection for URL or Name in the Destination section for New Application does not work. Only URL is working until you click Edit as YAML and then enter any character in the `name` field and hit Save. This will go back to the UI and now the default selection for the dropdown is now Name and you can see in the field dropdown the cluster names defined in the Cluster page.

**To Reproduce**

1. Create a new Application
2. Scroll down to Destination section
3. Select Name in the dropdown. Nothing Happens
4. Select an existing cluster destination URL and then select Name in the dropdown. Field clears up and displays an error message "Cluster URL is required"
5. Click Edit As YAML and update the `name` field with any character (ex. `name: '.'`) and then hit Save
6. Destination is now defaulting to cluster name and can be selected.
7. Delete the selected cluster name in the field and it will revert again back to URL and it won't be change again to Name until you Edit As YAML again.

**Expected behavior**

Destination dropdown when clicking field should change depending on selection of URL or Name.

**Screenshots**

![image](https://github.com/user-attachments/assets/4b06aceb-c217-46c8-9b0a-2461d14dbf8b)
![image](https://github.com/user-attachments/assets/462586e0-3082-4447-a0c0-93bcf6c41515)
![image](https://github.com/user-attachments/assets/96edd34e-ff5f-48ce-b3dc-68b39225ec22)
![image](https://github.com/user-attachments/assets/cd564349-f8a8-4975-baec-c3142df07918)

**Version**

```shell
argocd: v2.12.4+27d1e64
  BuildDate: 2024-09-26T06:58:55Z
  GitCommit: 27d1e641b6ea99d9f4bf788c032aeaeefd782910
  GitTreeState: clean
  GoVersion: go1.22.7
  Compiler: gc
  Platform: windows/amd64
time="2024-11-26T21:35:01+08:00" level=warning msg="Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web."
argocd-server: v2.13.1+af54ef8
  BuildDate: 2024-11-20T15:58:16Z
  GitCommit: af54ef8db5adfa77a08d4d05b1318a2198084c22
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Comment by lsq645599166** [comment]
Sorry, the bug was involved in my pr https://github.com/argoproj/argo-cd/pull/19717. I resolve it in the https://github.com/argoproj/argo-cd/pull/20970

**Comment by motmot84** [comment]
> Sorry, the bug was involved in my pr #19717. I resolve it in the #20970

Nice and quick fix! 👍 

I'll just wait for it to be merged and released. Thank you!

**Comment by PoojaTulaskar** [comment]
Adding to above issue in 2.13 version, while new deployment of application in argocd, after selecting project scope repo url, branches not visible in dropdown.
 
When we are adding repos in project scope while deploying new service target revision not visible, but can be visible if we remove the repos from project scope.
 
Project scope private repos:
 I added the private repo in argocd with and without project.
 
argocd repo add <repo_url> --username --password --project default
argocd repo add <repo_url> --username --password

![image](https://github.com/user-attachments/assets/b8e8c89e-ac9b-4558-8043-1c83d45609af)
 
Both repos are visible in ArgoCD UI with successful connection status.
 
Wanted to deploy application using the repo which is project scope, but after selection of repo url, revision not showing in UI. Refer screenshot attached.
 
![image](https://github.com/user-attachments/assets/e934ed4c-7725-4e14-8ad0-15d6686cb8ab)
 
Also same tried with repo without project scope, then we are able to see the revision. Refer screenshot attached
 
![image](https://github.com/user-attachments/assets/5dd50e0e-1b63-499b-aae0-ea71308ec69a)

Here is the github issue raised for same - https://github.com/argoproj/argo-cd/issues/20937
