### ISSUE TITLE
DOC: improve Sync Window documentation

### ISSUE THREAD

**Issue by Sebast1aan** [argoproj/argo-cd#20971]
### Describe the bug
A Sync Window currently seems to be attached to an application in case it matches with either one of following fields:
- applications
- namespaces
- clusters

I was instead expecting the conditions to be chained together, such as:
`match(application.name, applications) and match(application.namespace, namespaces) and match(application.cluster, clusters)`

Assuming [this](https://github.com/argoproj/argo-cd/blob/7f6340f653ae95b4f7433967c00717b3921843df/pkg/apis/application/v1alpha1/types.go#L2551) is the relevant function, it is instead doing:
`match(application.name, applications) or match(application.namespace, namespaces) or match(application.cluster, clusters)`

The result is thus that if you have a wildcard ('*') value for one of these fields, any application matches with the given Sync Window.

Can this behavior be made more explicit in the [documentation](https://argo-cd.readthedocs.io/en/stable/user-guide/sync_windows/)?

**Comment by thecooldrop** [comment]
I would like to work on this issue.

**Comment by Sebast1aan** [comment]
This one can be closed thanks to the doc improvements of @thecooldrop in #21093
