### ISSUE TITLE
SSH known hosts entry cannot be deleted if contains shell pattern in name

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#2099]
**Describe the bug**
If SSH known hosts were added that contain shell glob pattern in the hostname (such as `[localhost]:2222`, which is perfectly fine to specify a host:port combination for ssh), the entry cannot be easily removed from the database. For CLI, it can be removed using a workaround, using the UI it is not possible at all.

**To Reproduce**
1. Add an entry with port, such as:
    ```
    $ echo "[localhost]:2222 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG2t7Tcavp5oUqbbSwEKRaGwEq94b8BFK16AEBbgRCTp" | argocd cert add-ssh --batch
    Enter SSH known hosts entries, one per line. Press CTRL-D when finished.
    Successfully created 1 SSH known host entries
    ```
1. Try to remove it
   ```
   $ argocd cert rm '[localhost]:2222'
   No certificates were removed (none matched the given patterns)
   ```
   UI just fails silently.

1. Removal is possible using CLI and escaping glob characters in hostname
   ```
   $ argocd cert rm '\[localhost\]:2222'
   Removed cert for '[localhost]:2222' of type 'ssh' (subtype 'ssh-ed25519')
   ```

**Expected behavior**
- Removal of entry without having to escape glob patterns would be possible.
- Removal within UI would be possible

**Have you thought about contributing a fix yourself?**

Will supply a fix soon.

**Comment by alexec** [comment]
@jannfis was this fixed by a PR? I can't see to find it.

**Comment by jannfis** [comment]
No, there is no PR yet, I'm still busy with #2101. BUT I also noticed that this bug isn't present until #2101 is merged, because submitting such a hostname is not possible before the change is introduced. I stumbled upon the fact that known hosts for the E2E tests could not be submitted (because E2E-test's SSH server is listening on non-standard port). 

Weird situation indeed :-)

**Comment by jannfis** [comment]
OK, above statement is not quite true - before commit https://github.com/argoproj/argo-cd/commit/2742ead047b811e37d569ede0b93dd1984ce74e9 it was possible to add such a hostname, it is not possible since that commit (and made possible again after #2101 is merged). So this bug report is something like, inbetween.

**Comment by jannfis** [comment]
@alexec There goes: #2113
