### ISSUE TITLE
applicationSet managedNamespaceMetadata not get getting updated

### ISSUE THREAD

**Issue by josemachado97** [argoproj/argo-cd#21041]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After a application set being created if I change the ApplicationSet.Spec.SyncPolicy.ManagedNamespaceMetadata to add some labels to the namespace, the change takes place on the ApplicationSet level but doesn't get propagated to the Application. Saw a similar issue but on the Application level: [#issue 12661](https://github.com/argoproj/argo-cd/issues/12661)

**To Reproduce**

Deploy an ApplicationSet with some labels under ApplicationSet.Spec.SyncPolicy.ManagedNamespaceMetadata, then update the labels and apply the manifest again, the ApplicationSet is updated but the Application doesn't inherits the labels.

**Expected behavior**

The namespace should get the updated metadata.

**Screenshots**

**Version**

```shell
argocd: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T11:57:48Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
```

**Comment by crenshaw-dev** [comment]
Does the Application CR get updated with the new field's contents, or does the update not even make it that far?

**Comment by josemachado97** [comment]
it doesn't make it that far

**Comment by crenshaw-dev** [comment]
Is the field completely missing from the Application CR, or is it present and just hasn't been updated?

**Comment by josemachado97** [comment]
completely missing, if it's a new label is not present, if it's a existent one (from the creation of the ApplicationSet) the value
 doesn't get updated

**Comment by crenshaw-dev** [comment]
Wild guess, but I think maybe either your Application or ApplicationSet CRD is out of date and simply doesn't have that field, so it's being dropped on apply. Check whether your CRDs are up to date. An easy way would be to just manually create an Application with that field and then do a `kubectl get appset -oyaml` to see if the field disappeared.

**Comment by crenshaw-dev** [comment]
> if I change something other than managedNamespaceMetadata it gets updated normally

I'm not sure how that rules out stale CRDs. The failure would be at the field level. So updating something besides that field would not trigger the stale CRD issue.

But the fact that Blake encountered it too likely means it wasn't a stale CRD. Can you link the Slack thread?

**Comment by josemachado97** [comment]
https://cloud-native.slack.com/archives/C01TSERG0KZ/p1733143363686709

**Comment by blakepettersson** [comment]
Oh, I tested this again and this does actually work for me. I thinking I just missed to sync the changes after applying changes to the `managedNamespaceMetadata`.

**Comment by blakepettersson** [comment]
@josemachado97 can you supply an example manifest where this doesn't work?

**Comment by josemachado97** [comment]
@crenshaw-dev you are right, my ApplicationSet CRD is missing that field, how can I fix that? and why when it's the first, the appset creation this field is not created?

**Comment by josemachado97** [comment]
applied the newest Appset CRD, and it's showing on the Appset but is not propagating to the Application
