### ISSUE TITLE
Add `argo app ensure-healthy` cli

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#211]
The  `argo app ensure-healthy <app-name> --timeout <timeout>` should wait until application is empty. If application does not reach health state within specified timeout the command should return error code and print reason to stderr

**Comment by jessesuen** [comment]
Some requirements:
* I think ensure-healthy should be more generic to support waiting for synced only, health only or both. Therefore lets use the command `argo app wait <appname> --sync-only` or `argo app wait <app> --health-only`
*  would like for a way for the CLI to emit state changes as things change. That is, if some component switches from healthy to degraded, or vice versa, we should emit some progress.
* Progress can be additionally displayed by understanding total number of healthy resources over total resources.
