### ISSUE TITLE
Application 404s on names with periods

### ISSUE THREAD

**Issue by servo1x** [argoproj/argo-cd#2114]
**Describe the bug**
When creating an application with dots in its name: `cluster.namespace.application`, the route `my.argo.cd/applications/cluster.namespace.application` 404s, while `my.argo.cd/applications/cluster-namespace-application` works correctly.

**To Reproduce**
1. Create an application with dots in its name.
2. Go the direct application url and observe it 404s.

**Expected behavior**
Dots should be supported assuming Kubernetes naming convention is allowed:

>By convention, the names of Kubernetes resources should be up to maximum length of 253 characters and consist of lower case alphanumeric characters, -, and ., but certain resources have more specific restrictions.

Unless it's expected to be alphanumeric and dashes only?

**Version**

```shell
argocd-server: v1.1.2+567fcc3.dirty
  BuildDate: 2019-07-30T17:47:02Z
  GitCommit: 567fcc33140ec93051fdf8d0af7ea404deb64f20
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Comment by alexec** [comment]
@servo1x do you have a workaround at the moment please?

**Comment by servo1x** [comment]
@alexec Our current workaround is to either deal with the 404s or rename to use dashes. Both which are not ideal... The html5 routing works fine though.

I think the issue is this line:

https://github.com/argoproj/argo-cd/blob/7d86b51246503f9a082359efffb5649bf8b046f3/server/server.go#L666

Where the dots end up making the server try to serve a file.

Generally single page applications would redirect any 404 back to the index.html. Maybe we just add a condition for paths starting with `applications/*` to serve `index.html`?

**Comment by simster7** [comment]
I'll investigate a fix for this
