### ISSUE TITLE
Docs: clearer distinction between 'argocd repo' and 'argocd repocreds'

### ISSUE THREAD

**Issue by Sebast1aan** [argoproj/argo-cd#21199]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The [argocd command reference](https://argo-cd.readthedocs.io/en/latest/user-guide/commands/argocd/) lists these 2 commands:
- [argocd repo](https://argo-cd.readthedocs.io/en/latest/user-guide/commands/argocd_repo/) - Manage repository connection parameters
- [argocd repocreds](https://argo-cd.readthedocs.io/en/latest/user-guide/commands/argocd_repocreds/) - Manage repository connection parameters

Can the distinction between these 2 be made clearer? The former seems to be used for linking single repositories, while the latter generates the repository credential templates that can be used by multiple repositories. Based on the documentation alone, it's not clear when to use which one.

**Screenshots**
![image](https://github.com/user-attachments/assets/7ff97e7b-30ef-4d6f-ae59-336134531c40)

![image](https://github.com/user-attachments/assets/5091558d-0e88-4c79-92b2-8b834261b186)

![image](https://github.com/user-attachments/assets/5a30af04-3366-4050-ac4b-31c8f8d79095)

**Comment by surajyadav1108** [comment]
we can have this overview for "Repository Credentials" as a suggestion
https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repository-credentials
