### ISSUE TITLE
Need Windows argocd cmd

### ISSUE THREAD

**Issue by davidbIQ** [argoproj/argo-cd#2121]
Having just the homebrew option for the argocd in the getting started section isn't great.
For windows and for linux there should be matching options for those as from what I can tell you're not going very far without argocd...  kuberneties has a nice cli and it would be nice to have a similar cli for argocd for both windows and windows subsystem for linux.

**Comment by alexec** [comment]
Interesting. We've not had this asked for before.

**Comment by lcostea** [comment]
I know that on Windows side sig-cli is working pretty hard to make apps like kubectl and kustomize work well and not to break compatibility. 
Main effort needs to be put into a suite of tests running argocd cli on a windows node that verify main features are working correctly for each new release. I guess first we need to check that the ci (CircleCI, right?) tool supports windows nodes.
I can provide some help in this direction, I have been developing and doing release engineering on windows for many years.

**Comment by davidbIQ** [comment]
Hi All,

Thought I’d provide a bit of an update, I installed the windows subsystem, and got the agrocli working within there ok.  I wasn’t thinking initially of windows containers but I agree that would be a good copath as we are investigating windows containers currently for our big .NET apps.  I was looking to connect to azure linux containers from a windows powershell cli by using argocd 😊.

Thanks much,
David

**Comment by alexec** [comment]
I think it'd be great if someone from the community could contribute this.

**Comment by tomcruise81** [comment]
I didn't go so far as to get the entire Makefile working on Windows, but I **was** able to get the CLI building on Windows under Cygwin with `make`.

1. Similiar to https://github.com/cloudflare/gokey/pull/23/files, I had to convert instances of `syscall.Stdin` to `int(os.Stdin.Fd())`
2. When running in Cygwin, the go build command doesn't like cygpaths. As such, the Makefile's `DIST_DIR` was changed to `DIST_DIR=./dist`

With these small changes, the binary was able to be built.

A more full-featured, cross-platform build approach might be something along the lines of https://github.com/kubernetes/kubernetes/tree/master/build

**Comment by m86194** [comment]
> Interesting. We've not had this asked for before.

Just shows that coorporations (where developers for other reasons have to run Windows instead of Linux) have begun using Argo-CD.    This is a milestone.

**Comment by keylowgee** [comment]
Can confirm - work at a corporation where ~90% of developers are using windows. Would really like to implement this [KubeCon demos were amazing] but not having a windows cli will be a deal breaking issue.

**Comment by c0ffeec0der** [comment]
Add choco repository : https://chocolatey.org/packages/argocd/1.6.1

Still auth, waith for couple hours

Related issue : https://github.com/argoproj/argo-cd/issues/3482
