### ISSUE TITLE
UI ISSUE

### ISSUE THREAD

**Issue by devopsbyraham** [argoproj/argo-cd#21216]
WHILE  WORKING WITH ARGOCD UI IS STOPPING UNEXPEXTED

**Comment by rumstead** [comment]
@devopsbyraham can you fill out the bug report template and provide more information

**Comment by keithchong** [comment]
When you initiate creating an issue, the template is provided where you fill in the bug details. So, closing this for now, but feel free to re-open when you are able to provide more information about your issue.
