### ISSUE TITLE
Add configurable help link to every page

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#2124]
We might get better engagement from users by having a "chat" style link on each page that can be configured to point the user to appropriate chat room and help resources.

**Comment by alexec** [comment]
https://designbunk.com/screens/22-demo-dialogue-chat-box

**Comment by alexec** [comment]
https://www.npmjs.com/package/react-chat-popup

**Comment by alexec** [comment]
https://www.npmjs.com/package/react-floating-action-button

**Comment by stgarf** [comment]
food for thought: some people might not want/not allow their browsers or Argo in their cluster to make external connections to third parties.

**Comment by alexec** [comment]
Back-ported to v1.2
