### ISSUE TITLE
Add repo credentials management to CLI and UI

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#2136]
**Is your feature request related to a problem? Please describe.**
Repository credentials is a very handy feature in ArgoCD to connect multiple repositories using the same set of credentials. Alas, this feature is currently only available by modifying the `argocd-cm` ConfigMap object directly, i.e. using declarative setup of ArgoCD. 

**Describe the solution you'd like**
The CLI and UI should provide basic CRUD abilities for managing repository credentials, i.e. for the CLI:

1. list all configured credential sets - i.e. `argocd creds list`
1. configure a new or update existing credential set - i.e. `argocd creds add` (also providing `--upsert`)
1. delete credential set - i.e. `argocd creds rm`

About the command name, I'm unsure whether `cred` or `creds` would be the right thing. Everything else is in singular form (`repo`, `cert`, `app`), but credentials itself is already plural (i.e. there is no *credential* but always *credentials*), so I'd think `creds` would be the right command name. However, as I'm not a native English speaker, I'm not quite sure if this holds true.

For the web UI, credential management could be incorporated into the Settings page.

**Have you thought about contributing yourself?**
I'd implement this enhancement end-to-end if it is something we want to have.

**Comment by alexec** [comment]
Good point. No UI was ever developed for this, and it may result in the feature being under-used.

@jessesuen - thoughts?

**Comment by jannfis** [comment]
I have thought a bit more about this issue, and I was coming up with the following idea:

- We will not introduce an own command for repo creds, i.e. no `argocd creds` or similar command
- Instead, we introduce a new switch `--creds` to the `argocd repo` sub-commands, such as `list`, `add` and `rm` which specifies that operations are to be performed on a credentials template instead of a real repository configuration.
- Same could go for the web UI by introducing either a check box `Save as repository credentials` or by having a button next to `Create repo` reading `Create repo credentials`

I think this will simplify things greatly, and would not require lots of possibly duplicate code in the front-ends. We could reuse existing `RepoService` API, extending it to evaluate the new switch and have it decide whether to perform the operation on a repository, or on the repository template.

What do you think from a usability viewpoint about this?

**Comment by alexec** [comment]
I think that sounds like a plan.

@jessesuen can we bring this into v1.4?
