### ISSUE TITLE
https://hub.docker.com/r/argoproj/argocd-ui/tags has no v1.2.0-rc1 Tag

### ISSUE THREAD

**Issue by cobexer** [argoproj/argo-cd#2137]
**Describe the bug**
https://hub.docker.com/r/argoproj/argocd-ui/tags has no v1.2.0-rc1 Tag

**To Reproduce**
1. Go to https://hub.docker.com/r/argoproj/argocd-ui/tags
2. See no v1.2.0-rc1 Tag

**Comment by jannfis** [comment]
The ArgoCD UI has been integrated into the main ArgoCD image (i.e. `argoproj/argocd`) for v1.2.0, and as such, the `argocd-ui` image is now deprecated.

@alexmt Is that something that should be mentioned in the release notes maybe?

**Comment by alexec** [comment]
@cobexer - can I ask what you need the old UI images for please?

**Comment by cobexer** [comment]
I was looking for the ui image because I wanted to deploy the RC version and used the yaml from the documentation ( https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml ) which in some places also talks about version 1.2 ( https://argoproj.github.io/argo-cd/user-guide/private-repositories/ ) so I assumed the I can just update the image version and am ready to go with version 1.2 RC1

Thanks for the quick response!

**Comment by alexec** [comment]
Np. You should be able to use https://hub.docker.com/r/argoproj/argocd/tags
