### ISSUE TITLE
Fix `TestHookDeleteBeforeCreation`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#2141]
**Describe the bug**

`TestHookDeleteBeforeCreation` is intermittently failing on CI. I believe that this this might be a real issue related to race conditions.

**Comment by alexec** [comment]
My hypothesis is that there are two concurrent syncs causing this test to fail, and that could also appear in prod. 

This test is different to other tests and we delete and then apply a resource in the same step operation (i.e. we delete the resource then immediately re-create it). 

To prove myself wrong I set about trying to understand how we do locking for syncs (I'm working on the assumption we don't want one app to be synced concurrently). So where's the code that blocks a sync if the app is already syncing?

**Comment by alexec** [comment]
I think my hypothesis is wrong.

**Comment by alexmt** [comment]
Test is still failing :( https://circleci.com/gh/argoproj/argo-cd/4185?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by alexec** [comment]
pft
