### ISSUE TITLE
multiple changes to k8s deployment

### ISSUE THREAD

**Issue by marcb1** [argoproj/argo-cd#2144]
We have `HPA` added to our deployment. When the HPA scales a deployment, it also updates the `replicas` count field in the deployment.

This seems to introduce an issue if `argocd app patch` is running while the HPA is updating the`replicas` field. 

The following error is thrown:
```
local() encountered an error (return code 1) while executing '/usr/local/bin/argocd app patch test_app --patch '[{"path": "/spec/source/kustomize", "value": {"images": ["gcr.io/test_app:b2d921c80768f49089fa85a7dd3a31a25e4181c3"]}, "op": "replace"}]' --grpc-web
Unable to update test_app version; argo patch returned an error
Error deploying test_app
time="2019-08-12T16:15:37-04:00" level=fatal msg="rpc error: code = Unknown desc = Operation cannot be fulfilled on applications.argoproj.io \"test_app\": the object has been modified; please apply your changes to the latest version and try again"
```

My guess is that we can't edit a deployment at the same time that an HPA is scaling and editing the replica count of a deployment.

Is it possible to retry patch operations in the argo controller if a change is being made to the deployment. Not sure what the best way to solve this would be.

The most simple solution is to add retry logic in our automation that invokes `argocd app patch`, but I just wanted to get a second opinion.

**Comment by alexec** [comment]
This is a known issue with HPA, work-around:

https://argoproj.github.io/argo-cd/user-guide/diffing/

**Comment by alexmt** [comment]
I agree updates should be retried. Fixed by https://github.com/argoproj/argo-cd/pull/2852
