### ISSUE TITLE
1.2.0-rc1 - Authentication Required error in Repo Server

### ISSUE THREAD

**Issue by micahlmartin** [argoproj/argo-cd#2152]
After upgrading from 1.1.2 to 1.2.0-rc1 I am seeing the following error in the `argocd-repo-server`:

```
time="2019-08-14T17:39:51Z" level=error msg="finished unary call with code Unknown" error="authentication required" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2019-08-14T17:40:51Z" grpc.service=repository.RepoServerService grpc.start_time="2019-08-14T17:39:51Z" grpc.time_ms=27.79 span.kind=server system=grpc
```

**Comment by alexec** [comment]
Hi, @micahlmartin I'm trying to understand if this is related to changes for private repositories (i.e. ones that require SSH certs, username/password, or TLS client cert. 

Is your repo "private"?

**Comment by micahlmartin** [comment]
@alexec yes it's a privately hosted bitbucket.

**Comment by alexec** [comment]
What tool are you using? Helm? Kustomize?

**Comment by micahlmartin** [comment]
@alexec Some helm and some just plain rendered manifests.

**Comment by micahlmartin** [comment]
@alexec just curious, did the format of the `argocd-cm` configmap change at all? Possibly the way the repositories are loaded?

**Comment by micahlmartin** [comment]
I had to delete all the secrets and confimaps and then redeploy the manifests. This magically seemed to fix the issue.

**Comment by jannfis** [comment]
@micahlmartin What changed with the ConfigMaps is, that they require special annotation in form of a label now, `app.kubernetes.io/part-of: argocd`, so that they will be used by ArgoCD.

**Comment by alexec** [comment]
@alexmt @jessesuen think we should watch this one. Breaking change?

**Comment by eric-isakson** [comment]
This bit me today while upgrading from an older version where we had just done the install without any additional configuration and got this message:

time="2019-08-21T16:41:21Z" level=fatal msg="configmap "argocd-cm" not found"

I had copied the manifest at https://argoproj.github.io/argo-cd/operator-manual/argocd-cm.yaml and edited it to my needs. It does not have the annotations.

It looks like the doc was partially updated but not the declarative example files and some examples on the page. You can see the labels mentioned here in the part labeled "A complete example.":

https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#repository-credentials

If you search that page for: name: argocd-cm

You will find several examples that are missing the labels.

Adding both labels got me up and running again.

**Comment by alexmt** [comment]
Nice catch. Added labels to docs as well: https://github.com/argoproj/argo-cd/pull/2187
