### ISSUE TITLE
Flag to auto-sync even on sync failure

### ISSUE THREAD

**Issue by sjtindell** [argoproj/argo-cd#2156]
**Is your feature request related to a problem? Please describe.**
I'd like to create some application definitions before a cluster comes up, then when it is up, they will be automatically deployed. But the first time the app-of-apps is created, it fails to sync, then skips future auto-syncs.

time="2019-08-15T00:47:17Z" level=warning msg="Skipping auto-sync: failed previous sync attempt to 36fcab9b1a6b30cac3b1087cbfac3ead0353ec88" application=platform-app-of-apps

**Describe the solution you'd like**
I should be able to create the app-of-apps, and it should repeatedly try to sync (even if it fails every time) until the cluster is up, at which point it will succeed.

Also wondering, how often should ArgoCD sync if an application fails to sync? Does it retry right away? Can I set some time until it tries again?

**Comment by alexec** [comment]
You could use self-heal setting in v1.2

**Comment by alexec** [comment]
https://argoproj.github.io/argo-cd/user-guide/auto_sync/

**Comment by sjtindell** [comment]
Here is my manifest

`project: default
source:
  repoURL: '<internal-repo>'
  path: argo-apps
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd
syncPolicy:
  automated:
    prune: true
    selfHeal: true
`
and on all the applications under my app-of-apps I have the following set as well

`  syncPolicy:
    automated:
      prune: true
      selfHeal: true
`
but after the first sync fails I don't see any more attempts to sync even after waiting 10+ minutes. I see in that document it says

> Automatic sync will not reattempt a sync if the previous sync attempt against the same commit-SHA and parameters had failed.

Does that mean if it fails once it won't attempt it again unless I change the code in Git?

**Comment by alexec** [comment]
Can you please check your version?

**Comment by sjtindell** [comment]
Thanks for your time.

Here is the version output
```argocd: v1.1.2+e94999b
  BuildDate: 2019-08-14T22:13:43Z
  GitCommit: e94999b07d8448e044f35a08f4bfd77e5d1a016a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.1.2+e94999b
  BuildDate: 2019-08-14T22:12:27Z
  GitCommit: e94999b07d8448e044f35a08f4bfd77e5d1a016a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1```

Is what I'm seeing not expected behavior? Should it be attempting to re-sync? The install was done using the latest vanilla install from the manifests dir. Then I deploy a single cluster resource (another external cluster) definition, my single repo definition, and my app-of-apps definition.

The app-of-apps objects get created in Cluster1, where argo is running, and then their sub-apps get deployed to Cluster2.

When Cluster2 is up already and reachable, the app-of-apps and sub-apps all deploy with no problems and sync fine the first time. But if that cluster is not up, and the first sync fails, it looks like it never retries.

**Comment by alexec** [comment]
Can you try it out?

**Comment by sjtindell** [comment]
My mistake I see you mentioned 1.2 but I thought I was using the latest. Definitely, will test and report back thanks.

**Comment by sjtindell** [comment]
It works perfectly. Thank you for suggesting the latest, and thanks to whoever put this into the latest.

I setup both the cluster and apps definition on Cluster1 Argo, and they were in Failed and Unknown  state respectively. After 3 days I got Cluster2 working. Almost the moment that Cluster2 became reachable the Cluster object when to Successful state, and the apps deployed! Very cool stuff.
