### ISSUE TITLE
Support "transformations" on a manifest

### ISSUE THREAD

**Issue by edude03** [argoproj/argo-cd#2157]
**Is your feature request related to a problem? Please describe.**
At my company, we use multiple ways to generate kubernetes manifests such as jsonnet, helm, dhall, nix-kubernetes and of course, handwriting them.

One frustration I have is that while all these systems generate kubernetes manifests, there isn't a way currently for me to take all these manifests and add a label to every ingress for example. 

Kustomize, of course, solves this problem, but there isn't a way currently to apply kustomize to each of these systems without writing an argo plugin for each combination. 

**Describe the solution you'd like**
To solve this problem, I propose that argocd support a `transformation` layer, allowing users to define a transformation plugin to run after the chart is generated for example

```
source:
  helm:
    parameters: {}
  transform:
    kustomize:
      overlays:
         - path/to/overlay.yaml
```

This would also make it easy for users to customize `off the shelf` helm charts while still getting upstream changes. 

**Have you thought about contributing yourself?**

Open Source software thrives with your contribution. It not only gives skills you might not be able to get in your day job, it also looks amazing on your resume. 

If you want to get involved, check out the 
[contributing guide](https://github.com/argoproj/argo-cd/blob/master/docs/CONTRIBUTING.md), then reach out to us on [Slack](https://argoproj.github.io/community/join-slack) so we can see how to get you started.

**Comment by edude03** [comment]
See https://github.com/argoproj/argo-cd/issues/1784 as well, which seems to be suggesting something similar.

**Comment by alexec** [comment]
@alexmt @jessesuen another ask for built-in post-processing.

**Comment by alexec** [comment]
I think this is an **eschewed feature**. 

## Rational

This can be achieved using a custom plugin.
