### ISSUE TITLE
Join the CNCF to help gain mind share and publicity

### ISSUE THREAD

**Issue by clintberry** [argoproj/argo-cd#2163]
**Is your feature request related to a problem? Please describe.**
Flux announced their acceptance as a sandbox project to CNCF: https://www.weave.works/blog/flux-joins-the-cncf-sandbox
I feel like argocd has similar goals, but in its current state argocd is a much better project. 

**Describe the solution you'd like**
I'd love to see adoption speed up with some publicity and help from CNCF.

**Have you thought about contributing yourself?**
This is a decision made by the org that owns argocd

**Comment by grahamhayes** [comment]
I think that the [CDF](https://cd.foundation/) is a better fit for Argo than the CNCF

**Comment by alexec** [comment]
Joining CNCF is underway.

**Comment by edlee2121** [comment]
FYI, Argo proposal has been officially submitted to the CNCF and we've scheduled a presentation with SIG App Delivery before consideration by the TOC.

https://github.com/cncf/toc/pull/299
