### ISSUE TITLE
"invalid cookie, longer than max length 4093"

### ISSUE THREAD

**Issue by jaxxstorm** [argoproj/argo-cd#2165]
**Describe the bug**
The current size limit of the JWT token is 4093, which is prohibitive for orgs using SSO with large group memberships.

This seems to have been brought up in #1103 and was then closed with the fix being to display a warning. This doesn't really help those of us with large orgs trying to configure SSO that need to use dex

**To Reproduce**
Configure dex with an SSO provider with a large number of groups returned
Attempt to login

**Expected behavior**
User can login

**Version**
v1.1.2

**Comment by alexec** [comment]
This is a known issue. 

> You likely are part of many groups and have gone over the 4KB limit which is set for cookies.
> You can get the list of groups by opening developer tools -> network
> click log in
> find the call to <argocd_instance>/auth/callback?code=<random_string>
> You will see a cookie argocd.token
> Take the cookie value check the length, you can use https://mothereff.in/byte-counter
> You can decode the token at https://jwt.io/
> That will provide the list of teams, that you can remove yourself from.

This will be fixed in #2134

**Comment by alexec** [comment]
See #1103

**Comment by alexec** [comment]
v1.3 contains a fix to mitigate this issue, by compressing the cookie. We don't plan to provide a complete fix for this at this time.
