### ISSUE TITLE
Omitting repoURL for Applications in the same repository

### ISSUE THREAD

**Issue by bencompton** [argoproj/argo-cd#2171]
Is there currently a way to point applications to a path in the same repo without specifying a `repoURL`?

For example, I would like to be able to create an initial Application of Applications via the CLI or initial manifest, and then have all Applications in the repository only specify a path and not a `repoURL`. When a `repoURL` is not specified, the URL from the top-level parent Application would be used.

In my case, I am replicating repos from GitHub enterprise to AWS CodeCommit (k8s cluster in AWS can't access corporate network), with  auto-generated repository names and SSH credentials, and the repo URL is subject to change, especially since it needs to contain the AWS SSH key id. Of course, templating the `repoURL` is one way to address this issue, but it would be simpler if Argo CD assumed the top-level parent applications's URL when `repoURL` is omitted.

**Comment by alexec** [comment]
Not as far as I know. You could use a templating tool to do this.
