### ISSUE TITLE
Resource action equivalent to `kubectl rollout restart`

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#2177]
**Is your feature request related to a problem? Please describe.**

A common feature request is to be able to restart all pods of a deployment. This is basically the new `kubectl rollout restart` feature in kubectl v1.15:

https://github.com/kubernetes/kubernetes/pull/76062/files

**Describe the solution you'd like**

A new resource action should be introduced for deployments, "restart", which mimics the behavior of `kubectl rollout restart`, which essentially sets an timestamp annotation on `spec.template.metadata.annotations`, `kubectl.kubernetes.io/restartedAt` to current timestamp.

**Comment by alexec** [comment]
v1.4?

**Comment by malinafong** [comment]
@jessesuen  the CG team will need this feature right after 3rd Tax Peak. The timeline for 3rd Tax Peak is 10/31 . Can we commit to a timeline of the month mid November?  Please advise.
