### ISSUE TITLE
Config management plugin environment variable UI/CLI support

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#2203]
**Is your feature request related to a problem? Please describe.**
Config management plugins support parameterizing using environment variables. Hoverwer it is impossible to configure env variable using CLI/UI

**Describe the solution you'd like**
User should be able to specify env variables using UI and CLI.

**Comment by alexec** [comment]
This might be a dup.

**Comment by yujunz** [comment]
Is it fixed in master branch now? I was just hit by this problem.

**Comment by yujunz** [comment]
```
rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to generate manifests in ***/helmfile: rpc error: code = Unknown desc = `/bin/sh -c helmfile --selector name=${HELMFILE_SELECTOR_NAME:-${ARGOCD_APP_NAME}} template --skip-deps` failed exit status 1: in ./helmfile.yaml: Malformed label: name=. Expected label in form k=v or k!=v
```

It seems environment variable is not parsed when editing in CLI.

**Comment by tylerauerbeck** [comment]
@alexec  Looking at the merged PR it seems this is supported in the UI. Are there any docs on how to do this via the CLI? 

For example `argocd app create...` ?

**Comment by caryyu** [comment]
I'm also interested in how env-vars can be passed through `argocd app create`, hope anyone else here can refer a link

**Comment by yujunz** [comment]
See https://github.com/argoproj/argo-cd/pull/4923/files for CLI support
