### ISSUE TITLE
Command `argocd account update-password` is broken

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#2205]
**Describe the bug**
The `argocd account update-password` is broken. Command fails trying to use entered password as a username.

**To Reproduce**
1. Try to update password using `argocd account update-password` 
2. Enter valid current password and any new password
3. See command fails with error message `Cannot update password for [new-password]`

**Expected behavior**
Command should successfully update password

**Comment by jaypipes** [comment]
The `argocd account update-password` CLI command is working for me on 1.1.2:

```
jaypipes@thelio:~$ argocd account update-password
*** Enter current password: 
*** Enter new password: 
*** Confirm new password: 
Password updated
jaypipes@thelio:~$ argocd version
argocd: v1.1.2+567fcc3.dirty
  BuildDate: 2019-07-30T17:45:54Z
  GitCommit: 567fcc33140ec93051fdf8d0af7ea404deb64f20
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.1.2+567fcc3.dirty
  BuildDate: 2019-07-30T17:47:02Z
  GitCommit: 567fcc33140ec93051fdf8d0af7ea404deb64f20
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

Are there any errors in the server side you can see?

I presume you are logged in and have an active session, yes? Otherwise you'd get a "no session information" error returned.

**Comment by alexmt** [comment]
False alarm :) I was trying to execute `argocd account update-password` using SSO user credentials and command failed correctly.
