### ISSUE TITLE
user with project scoped full permission cannot set parameter from argocd web ui

### ISSUE THREAD

**Issue by wsbmilk** [argoproj/argo-cd#2225]
**Describe the bug**
user with project scoped full permission cannot set parameter from argocd web ui
user with root permission can set it.

**To Reproduce**
1. select application
2. click on parameters tab
3. cannot see parameters from helm values file.

**Screenshots**
role:
![image](https://user-images.githubusercontent.com/12369552/63904670-6e61c980-ca44-11e9-898e-c24b0a6a51ce.png)

bug:
![image](https://user-images.githubusercontent.com/12369552/63904729-97825a00-ca44-11e9-8e2d-0d1dc2152d0e.png)

**Version**
v1.1.0

**Comment by alexec** [comment]
Hi, I think anyone who might investigate would need to ask for more repro details. Are you able to provide logs, the version of Argo CD you're using please?
