### ISSUE TITLE
Other install methods? 

### ISSUE THREAD

**Issue by andloh** [argoproj/argo-cd#2226]
Hi, 

Have you provided other install metodes for this? 
I would really like to have some docker-compose files ready to go. 

Then you can install argo on a separate mgmt box, and connect dev, test, qa, and prod clusters.

**Comment by alexec** [comment]
You can install from Helm if you like.

**Comment by AsjadLFC** [comment]
@alexec @andloh I want to use docker compose as a deployment method. do we have a workaround?

**Comment by ebuildy** [comment]
I agree, for dev, I am wondering why `docker-compose` is not used instead of Procfile?
