### ISSUE TITLE
Add email notification feature

### ISSUE THREAD

**Issue by eroji** [argoproj/argo-cd#2227]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem, but it looks like currently there is no means of configuring email notifications in ArgoCD. This would be an awesome feature to have I feel.

**Describe the solution you'd like**
To have some sort of email notification feature per application/project/cluster so that when a sync/rollback action is performed, automatic or manual, an email is sent to a set of recipients configured. I imagine you'd could set the email notification at each level, and you can set the lower resource to inherit notification configuration of the higher one. I think this makes a lot of sense, so that both automatic and manual deployments so interest party can see that the deployment/rollback took place.

**Comment by alexec** [comment]
This can be done using an Argo Labs project:

https://github.com/argoproj-labs/argo-kube-notifier

**Comment by eroji** [comment]
Taking a look. However, I assume you could potentially do something like the rule in argo-kube-notifier using Prometheus and AlertManager. It would be nice to have this built into the Argo's UI/CLI/API though.

**Comment by alexec** [comment]
Please take a look at #2414 to see how we do this for Slack.

**Comment by eroji** [comment]
@alexec I tried looking at the argo-kube-notifier, however it does not appear to meet our needs. First we are not using Slack, so setting it up as a notifier does not apply. Furthermore, the email notifier seem to require username and password to set up, which for internal email relay, we are not setting up with any credentials.

**Comment by alexec** [comment]
See:

* https://github.com/ibiqlik/argocd-slack-notification
* https://github.com/ibiqlik/argocd-github-status

For examples of using hooks to do this.
