### ISSUE TITLE
CONTRIBUTING documentation outdated

### ISSUE THREAD

**Issue by jlpedrosa** [argoproj/argo-cd#2231]
**Describe the bug**
Documentation in CONTRIBUTING is outdated/incorrect and does not build the project correctly

**To Reproduce**
```
rm -rf ~/go;
export GOPATH=~/go
export PATH=$PATH:$GOPATH/bin
go get -u github.com/argoproj/argo-cd
OUTPUT: package github.com/argoproj/argo-cd: no Go files in /Users/jopedros/go/src/github.com/argoproj/argo-cd
cd ~/go/src/github.com/argoproj/argo-cd
make dep
OUTPUT:  make: *** No rule to make target `dep'.  Stop. 
# I assumed the new target is dep-ensure
make dep-ensure
OUTPUT:  dep ensure -no-vendor
make
OUTPUT:  find /Users/jopedros/go/src/github.com/argoproj/argo-cd -name debug.test | xargs rm -f
CGO_ENABLED=0 go run vendor/github.com/gobuffalo/packr/packr/main.go build -v -i -ldflags '-X github.com/argoproj/argo-cd/common.version=1.1.2 -X github.com/argoproj/argo-cd/common.buildDate=2019-08-30T11:03:49Z -X github.com/argoproj/argo-cd/common.gitCommit=21bc70be05ae15c15fcd385b97ceefb7d8ac12ac -X github.com/argoproj/argo-cd/common.gitTreeState=clean -extldflags "-static"' -o /Users/jopedros/go/src/github.com/argoproj/argo-cd/dist/argocd ./cmd/argocd
stat vendor/github.com/gobuffalo/packr/packr/main.go: no such file or directory
make: *** [cli] Error 1
```

**Expected behavior**
Build to take place

**Version**
commit 21bc70be05ae15c15fcd385b97ceefb7d8ac12ac (HEAD -> master, origin/master, origin/HEAD)

**Comment by k** [comment]
Yeah and what's weird if you do `make dep-ensure` the build with `make` fails with:

```
find /Users/kbambridge/go/src/github.com/argoproj/argo-cd -name debug.test | xargs rm -f
CGO_ENABLED=0 go run vendor/github.com/gobuffalo/packr/packr/main.go build -v -i -ldflags '-X github.com/argoproj/argo-cd/common.version=1.1.1 -X github.com/argoproj/argo-cd/common.buildDate=2019-08-31T17:00:18Z -X github.com/argoproj/argo-cd/common.gitCommit=8544bef56b8bee19e73a71b2d10ccd64156dd72c -X github.com/argoproj/argo-cd/common.gitTreeState=dirty -extldflags "-static"' -o /Users/kbambridge/go/src/github.com/argoproj/argo-cd/dist/argocd-server ./cmd/argocd-server
stat vendor/github.com/gobuffalo/packr/packr/main.go: no such file or directory
```

**Comment by jannfis** [comment]
You can do the following as workaround for the non-working `make dep`:
```
go get -u github.com/gobuffalo/packr/packr
dep ensure -vendor-only
```
Afterwards, you should be able to build ArgoCD. I guess the documentation got slightly out-of-date when the `codegen` step was Dockerized.

**Comment by k** [comment]
Do I need to run `go get -u github.com/gobuffalo/packr/packr`?

I just tried running `dep ensure` and then make and it appears to be working.

Also it appears to be installing docker... whoa

**Comment by jannfis** [comment]
Ah right, just had a look at the Makefile - if `packr` isn't found in your `$PATH`, it will `go run` it from the source in `vendor/`

As for installing docker, it is probably a build-time dependency for some other build-time dependency. No worries about it being _installed_ on your system, I'd say it has downloaded the _source code_ to your `vendor/` directory :)

**Comment by alexec** [comment]
This is hard to fix without being new to the project. If you can provide a PR with any fixes you think are needed, we can merge it.
