### ISSUE TITLE
Brew installs macOS binaries on Linux

### ISSUE THREAD

**Issue by myniva** [argoproj/argo-cd#2241]
**Describe the bug**
If you try to install the Argo CD CLI tools on Linux with Linuxbrew, it installs the macOS (Darwin) binaries.

**To Reproduce**
1. Install brew on Linux https://docs.brew.sh/Homebrew-on-Linux
2. Add the argoproj tap: `brew tap argoproj/tap`
3. Install the argocd CLI tool: `brew install argoproj/tap/argocd` 

The log output looks like this:

```
brew install argoproj/tap/argocd
==> Installing argocd from argoproj/tap
==> Downloading https://github.com/argoproj/argo-cd/releases/download/v1.1.2/argocd-darwin-amd64
######################################################################## 100.0%
🍺  /home/linuxbrew/.linuxbrew/Cellar/argocd/1.1.2: 3 files, 52.7MB, built in 1 minute 1 second
```

**Expected behavior**
The Linux binaries should be installed instead.

**Version**

```shell
$ brew info argocd
argoproj/tap/argocd: stable 1.1.2
GitOps Continuous Delivery for Kubernetes
https://argoproj.io
/home/linuxbrew/.linuxbrew/Cellar/argocd/1.1.2 (3 files, 52.7MB) *
  Built from source on 2019-09-03 at 14:06:26
From: https://github.com/argoproj/homebrew-tap/blob/master/argocd.rb
```

**Comment by mcristina422** [comment]
Looks like there is a PR open adding this feature https://github.com/argoproj/homebrew-tap/pull/4

**Comment by alexec** [comment]
PR merged. Please can you try it out and let us know the outcome?

**Comment by jessesuen** [comment]
TIL there is homebrew on linux.

**Comment by myniva** [comment]
Works perfectly! Thanks for fixing that so quickly 👍
