### ISSUE TITLE
SNI support is not implemented and creates a redirect loop with the nginx ingress controller

### ISSUE THREAD

**Issue by taharah** [argoproj/argo-cd#2246]
**Describe the bug**

When following the documentation to share a single port for HTTPS and gRPC via the nginx ingress controller, you need to enable SSL pass through. However, SSL pass through requires the use of SNI, which is not currently implemented in.

**To Reproduce**

1. Deploy nginx ingress controller with SSL pass through enabled.
2. Deploy Argo CD.
3. Create an Ingress resource by following [https://argoproj.github.io/argo-cd/operator-manual/ingress/#kubernetesingress-nginx](https://argoproj.github.io/argo-cd/operator-manual/ingress/#kubernetesingress-nginx).
4. Attempt to go to Argo via your browser and you will end up in a redirect loop. 

**Expected behavior**

I would expect SSL pass through to properly work and not create a redirect loop.

**Version**

v1.1.2

**Logs**

From the nginx ingress controller in debug mode:

```
2019/09/04 17:45:51 [info] 475#475: *4363 [lua] certificate.lua:57: call(): obtained hostname is nil (the client does not support SNI?), falling back to default certificate, context: ssl_certificate_by_lua*, client: 127.0.0.1, server: 0.0.0.0:442
```

**Have you thought about contributing a fix yourself?**

Yes, the TLS configuration [[1](https://github.com/argoproj/argo-cd/blob/master/util/settings/settings.go#L794-L808)] needs to simply allow the property `ServerName` to be set either via the configuration file or just default to the host of the given URL. Let me know what would be the desired solution and I can put together a PR.

Thank you! 

\[1\] https://github.com/argoproj/argo-cd/blob/master/util/settings/settings.go#L794-L808

**Comment by alexec** [comment]
hi @taharah - are you interested in submitting a PR for this bug please?

**Comment by taharah** [comment]
Yes, I'm more than happy to submit the relevant changes. I just wanted to get consensus on whether or not this should be exposed to end-users as a configuration setting or just use the host from the URL already available in the settings (this could also be the default if the desire is to expose the setting to end-users).

**Comment by alexec** [comment]
the settings URL should be the correct one to use

**Comment by taharah** [comment]
Adding for reference incase others run into a similar issue.

My traffic flow is as follows:

```
ALB -> nginx -> ArgoCD
```

I work in a regulated environment, and as such, require end-to-end encryption. Additionally, I am trying to terminate TLS at the ALB with a "real" certificate so browsers and the like are happy, then just use self-signed certificates the rest of the way. Apparently, AWS strips all of the SNI headers from the original request when it re-encrypts the traffic to the backend(s). I've tested with both an NLB and ELB, which both had the same outcome (the only way to preserve the SNI headers is to use TCP and not terminate TLS at the edge). Without the SNI headers nginx sees the hostname as a nil value, which ultimately causes the SSL passthrough to fail. At which point, nginx falls back to terminating TLS and attempting to route the traffic "normally". Since I do not set any additional annotations it tries sending the traffic to the backend as HTTP, and hence, the redirect loop.

**Comment by himanshu1380** [comment]
@taharah were you able to find a solution for this? I am still facing this with AWS ALB
