### ISSUE TITLE
Repository should belong to a Project

### ISSUE THREAD

**Issue by augabet** [argoproj/argo-cd#2251]
Today, we use RBAC and OIDC to manage users rules. RBAC are provionned by a custom operators that we build, depending on LDAP groups. As we cannot predict the name of the Git repository, we have that rule ( p, role:project-name-production, repositories, *, *, allow). It implies that all users can list/add/delete repo, or add repo in their own project.

We would like to restrict repository by project, so the user bound to OIDC groups only can list/create/update/delete repository belonging to a project. 

Also we would like to be able to add a repo with the JWT token created for a project role.

I would be happy to discuss and contribute on that topic.

**Comment by alexec** [comment]
Sounds like a good use case. Have you should about contributing a PR?

**Comment by alexec** [comment]
I hope everyone who up-voted this don't all work for the same company...

**Comment by alexec** [comment]
@jessesuen FYI

**Comment by lcostea** [comment]
@alexec I can start working on this, if nobody else started

**Comment by alexec** [comment]
Can we please get some samples of the RBAC rules you'd create for his enhancement?

**Comment by yydzhou** [comment]
Is there any update regarding this issue? @lcostea

**Comment by alexmt** [comment]
I think we should work on it in v1.9 . @jessesuen any objections?

**Comment by olevitt** [comment]
This would be really great. We face the same issue at my org, isolation between projects is close to perfect except permissions on repositories not being tied to a project.  
I would be happy to discuss and help on this subject although I have close to zero `go` programming knowledge but I may help on the react / UI side.

**Comment by augabet** [comment]
Hello, is there news regarding this issue ?

**Comment by alexmt** [comment]
Proposal has been accepted: https://github.com/argoproj/argo-cd/blob/master/docs/proposals/project-repos-and-clusters.md

**Comment by alexmt** [comment]
Implemented! Thanks to @pasha-codefresh
