### ISSUE TITLE
Option to perform K8s v1.16 server-side apply

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#2267]
Kubernetes v1.16 supports the ability server-side apply. A huge benefit of server-side apply is that it which will support strategic merge patching of CRDs. I imagine that many users will want to do server side applies for this reason alone.

We need a way to configure Argo CD to support server-side applies. This option probably needs to be configured globally -- I don't see a reason to have this granular to an application. It also needs to decide to do this based on the version of the cluster. In other words, we cannot attempt server-side applies for kubernetes clusters < 1.16.

Related to this is the ability to do server-side dry runs:
https://github.com/argoproj/argo-cd/issues/804

**Comment by kwiesmueller** [comment]
Hey there,
this came up in a GitHub search for Server-Side Apply.
If you encounter any problems while implementing Server-Side Apply or need help doing so, feel free to ping us (wg-api-expression) on the Kubernetes Slack or just ping me here.
https://kubernetes.slack.com/archives/C0123CNN8F3

**Comment by jutley** [comment]
I'd love to see Argo CD support server-side apply.

We have a use case I don't see discussed much. We leverage mutating webhooks to provide lots of valuable default configuration for our Kubernetes users. An issue with this is that when running `kubectl apply`, the mutation will not take place if there is no difference between the desired and live states (I believe kubectl doesn't try to apply the patch in this case). However, when running `kubectl apply --server-side`, the mutations are always applied.

Our users primarily interact with Kubernetes through ArgoCD. Without Argo CD supporting server-side apply, there is no way apply these mutations unless the resource actually has some new desired state.

**Comment by rouke-broersma** [comment]
@jessesuen this has recently become very relevant due to kube prometheus stack having too large CRDs for the last-applied-configuration field. We can currently not update kube prometheus stack with argocd because of this. This would be fixed with server-side apply iirc. See: https://github.com/prometheus-community/helm-charts/issues/1500

**Comment by EppO** [comment]
server-side apply hit GA with 1.22, it would be neat that Argo CD embraces it like Flux did. Having to add manually an annotation on one of the helm chart's CRD is really painful

**Comment by christianh814** [comment]
Circling back on this as this has come up again from our end users.

**Comment by sathieu** [comment]
Proposal: https://github.com/argoproj/gitops-engine/pull/363

I think the only needed fix in the argocd repo is to bump the deps and of course documentation.

**Comment by leoluz** [comment]
For reference, this is the proposal for implementing SSA in ArgoCD:
https://github.com/argoproj/argo-cd/pull/8812
