### ISSUE TITLE
We need rollback beyond 10 deployment

### ISSUE THREAD

**Issue by sumitnagal** [argoproj/argo-cd#2285]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
We want two solutions, 
one where we can have this value (how many deployments could be visible ) 
Second one, keep the last 2 successful deploy builds.

**Have you thought about contributing yourself?**
Yes

Open Source software thrives with your contribution. It not only gives skills you might not be able to get in your day job, it also looks amazing on your resume. 

If you want to get involved, check out the 
[contributing guide](https://github.com/argoproj/argo-cd/blob/master/docs/CONTRIBUTING.md), then reach out to us on [Slack](https://argoproj.github.io/community/join-slack) so we can see how to get you started.

**Comment by alexec** [comment]
Interesting. I think this would be a good one for community contribution. This is currently hard-coded to 10, here's where we'd need to change it:

https://github.com/argoproj/argo-cd/search?l=Go&q=RevisionHistoryLimit

**Comment by alexmt** [comment]
Size is limited because the whole history is stored in application status. To fix we would have to introduce another CRD ( e.g. ApplicationOperation ) and use it to load history. We definitely should discuss design before implementing it.

**Comment by alexec** [comment]
@sumitnagal are you able to provide more details of the use case please?

**Comment by sumitnagal** [comment]
When many developers are working on given code base , and their code has been merged to master, it first go for deployment. Integration Test usually happens later for deployment validation. Now is a team is making 11 check-ins today, everything we deploy on qa environment cause 10 deployment to be rejected. now if we want to restore to a working copy of yesterday work, we don't have that avalilble for roll back.  Ideally if we keep this configurable or keep at-least last 3 successful deployment would be nice.

**Comment by alexec** [comment]
What about truncating to 10, but always keeping 1 successful deployment?

**Comment by alexec** [comment]
We don't know the status of a revision at sync time. It only becomes available later on.

**Comment by alexec** [comment]
@sumitnagal would only having successful entries in the history work for you? There is a simple solution you can use today if so.

**Comment by sumitnagal** [comment]
Yes , that solution work for me. if there is last successful build available.

**Comment by alexec** [comment]
I've spoken to @jessesuen about this. We do not store unsuccessful syncs in the history. However, a sync is considered successful if we're able to apply all the resource - even if they do not get to healthy state. Unless, you have any sync hooks or sync waves. 

If you create a `PostSync` hook that always exist successfully, then the history will only contain successful syncs, e.g.

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSuccessful
  name: ok
spec:
  containers:
    - command:
        - "true"
      image: "alpine:latest"
      imagePullPolicy: IfNotPresent
      name: main
  restartPolicy: Never
```

This works if you do not need to keep unsuccessful syncs in the history.

Can you please try this out?

**Comment by anarcher** [comment]
I think this feature is useful to me. :-) To configure reversion history size
