### ISSUE TITLE
Client Side error coming when adding .git in REPO url

### ISSUE THREAD

**Issue by sumitnagal** [argoproj/argo-cd#2286]
**Describe the bug**

When Adding New Application "Repository URL" value if we keep with git and we have Path variable define, we see unable to create application., spec is invalid. this error will stick and won't go even when change the value of repo without git. FYI, I am using https endpoint.

**To Reproduce**

If we cannot reproduce, we cannot fix! Steps to reproduce the behavior:

1. Go to 'ArgoCD UI'
2. Click on 'New Application'
3. Scroll down to 'Provide all value along with REPO with .git extn'
4. Provide the path "Assume you have path"

**Example**

Fork https://github.com/argoproj/argocd-example-apps and add an example that exhibits the bug.

THIS IS THE BIGGEST THING YOU CAN DO TO GET YOUR ISSUE LOOKED AT QUICKLY

**Expected behavior**
We should prompt error or we can ignore the .git and add the Application. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2490216/64655028-d965b580-d3df-11e9-9a38-2d7c7211e949.png)

**Version**
Latest but using UI

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Have you thought about contributing a fix yourself?**
Yes 

Open Source software thrives with your contribution. It not only gives skills you might not be able to get in your day job, it also looks amazing on your resume. 

If you want to get involved, check out the 
[contributing guide](https://github.com/argoproj/argo-cd/blob/master/docs/CONTRIBUTING.md), then reach out to us on [Slack](https://argoproj.github.io/community/join-slack) so we can see how to get you started.

**Comment by alexec** [comment]
Can you please tell me about your RBAC set-up? 
Does this work without `.git`?

**Comment by sumitnagal** [comment]
If you do without .git things are working, but the problem comes with .git. I have shared this to Bala also. I have steps to reproduce If you want I can put those values or screenshot.
