### ISSUE TITLE
Name suffix option

### ISSUE THREAD

**Issue by imranismail** [argoproj/argo-cd#2301]
An option to specify the name suffix for kustomize apps.

I'm curious as to why name prefix was introduced but not name suffix.

**Comment by jessesuen** [comment]
> I'm curious as to why name prefix was introduced but not name suffix.

reason is because kustomize added name suffix feature after we added kustomize support, and we never kept up with the available CLI commands introduced in kustomize

**Comment by alexec** [comment]
Will be in v1.4
