### ISSUE TITLE
Badge response does not contain cache control header

### ISSUE THREAD

**Issue by greenstatic** [argoproj/argo-cd#2317]
**Describe the bug**
The badge response does not contain a cache control header field thereby allowing GitHub's CDN (Fastly) to cache the badge image. This results in the badge being stale and pretty much useless until cache invalidation at Fastly.

**To Reproduce**
Add badge URL to a GitHub README.md file and start using Argo CD to change the badge status. Observe on your README.md as the badge does not update.

**Expected behavior**
Badge HTTP response to return cache control header, e.g. `Cache-Control: private, no-store`.

See [discussion regarding GitHub content caching](https://github.com/github/markup/issues/224) regarding badge images.

And Fastly's [recommendation](https://docs.fastly.com/en/guides/cache-control-tutorial).

**Version**
Argo CD server: v1.2.1

**Have you thought about contributing a fix yourself?**
Sure, if I get a green light from the maintainer.

**Comment by alexec** [comment]
you have a green light to proceed!
