### ISSUE TITLE
Inconsistent sync result from UI and CLI

### ISSUE THREAD

**Issue by yujunz** [argoproj/argo-cd#2321]
**Describe the bug**

Sync from UI results in success while status still in OutOfSync.

Sync from CLI will fail with errors

**To Reproduce**

1. Go to one application
2. Click on 'Sync'
3. Wait for synchronization finishes
4. No error but status remains OutOfSync
5. Run `argocd app sync ...` from CLI, got error result and UI last event changed to sync failed.

**Example**

N/A

**Expected behavior**

Sync should fail in UI as well as CLI

**Screenshots**

<img width="709" alt="Screen Shot 2019-09-17 at 2 17 05 PM" src="https://user-images.githubusercontent.com/6813397/65016420-d2e2bb00-d956-11e9-9329-135d3eddb699.png">

**Version**

Custom build based on https://github.com/argoproj/argo-cd/commit/d2af2faa52aa99218b1e4f432e6396768d7915a4

```shell
argocd: v1.2.0+674978c
  BuildDate: 2019-09-04T21:27:44Z
  GitCommit: 674978cd587701b39e81fce6d5c960b6d76d5882
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.1.2+67d8f43
  BuildDate: 2019-09-17T05:53:35Z
  GitCommit: 67d8f430ef3f6b7046c94f3e783289a99d4ea97e
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

```
Message:            one or more synchronization tasks completed unsuccessfully

GROUP                      KIND                NAMESPACE    NAME                     STATUS     HEALTH   HOOK     MESSAGE
...
batch                      Job                 experiments  experiments-createdbext  Error               PreSync  failed to delete resource: jobs.batch "experiments-createdbext" not found
batch                      Job                 experiments  experiments-createdb     Succeeded           PreSync  job.batch/experiments-createdb created
                           Service             experiments  experiments              Synced     Healthy
                           ServiceAccount      experiments  experiments-certutil                Unknown
extensions                 Deployment          experiments  experiments              OutOfSync  Healthy
...
```

**Have you thought about contributing a fix yourself?**

Yes

**Comment by alexec** [comment]
Have you tried to click refresh in the UI?

**Comment by yujunz** [comment]
Pressing `Refresh` does not make any changes.

**Comment by alexmt** [comment]
Both CLI and UI are supposed to render `status` field of application CRD. Can you try running `argocd app wait <appName> --sync` ?  It should trigger exact same code which renders application status as `argocd app sync <appName>`. 

I'm trying to understand why sync operation failed. This error message looks like a bug: `failed to delete resource: jobs.batch "experiments-createdbext" not found`. @yujunz can you please share hook annotations of `experiments-createdbext` ?

**Comment by alexmt** [comment]
I believe sync failed because of a bug in syncing logic. The controller tries to delete the resource and fails if resource deletion takes a lot of time. Sent PR which fixes it: https://github.com/argoproj/argo-cd/pull/2458

**Comment by yujunz** [comment]
Sorry for the late reply. Hope it helps.

> can you please share hook annotations of `experiments-createdbext` ?

```
helm.sh/hook: pre-install,pre-upgrade
helm.sh/hook-weight: "4"
helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
```

**Comment by alexec** [comment]
I think that @alexmt has fixed this. @alexmt do you intend to back-port the fix?

**Comment by alexec** [comment]
Is this still a problem please?

**Comment by yujunz** [comment]
I haven't test the latest release. Close for now. Will reopen if it appears again.
