### ISSUE TITLE
Please provide SHA256SUMS for releases

### ISSUE THREAD

**Issue by philippeckel** [argoproj/argo-cd#2323]
**Is your feature request related to a problem? Please describe.**
It is common practice for projects to release hash sums to check data integrity.

**Describe the solution you'd like**
SHA sums are provided for each release.

**Have you thought about contributing yourself?**

The developers should release hash sums.

If you want to get involved, check out the 
[contributing guide](https://github.com/argoproj/argo-cd/blob/master/docs/CONTRIBUTING.md), then reach out to us on [Slack](https://argoproj.github.io/community/join-slack) so we can see how to get you started.

**Comment by alexec** [comment]
Can you please provide example?

**Comment by eyulf** [comment]
@alexec Using SHA256 checksums to validate downloads is a fairly common practice in general.

Examples include:
- https://github.com/fluxcd/flux2/releases/tag/v0.26.1
- https://github.com/helm/helm/releases/tag/v3.8.0
- https://github.com/kubernetes/kubernetes/releases/tag/v1.23.3

More Information:
- https://techdocs.akamai.com/download-ctr/docs/verify-checksum
- https://docs.hak5.org/hc/en-us/articles/360049922674-How-to-verify-the-SHA256-checksum-of-a-downloaded-file
- https://www.openoffice.org/download/checksums.html
- https://vitux.com/how-to-verify-download-in-ubuntu-with-sha256-hash-gpg-key/
- https://null-byte.wonderhowto.com/how-to/use-sha-256-hash-verify-your-downloads-havent-been-modified-0179566/
- https://www.linuxshelltips.com/verify-sha256-checksum-of-file-in-linux/
