### ISSUE TITLE
Mixed applications when multiple ArgoCD has applications with same name

### ISSUE THREAD

**Issue by iremmats** [argoproj/argo-cd#2352]
**Describe the bug**

Two argocd instances in the same cluster having applications named the same can interfere with eachother.

**To Reproduce**

Have two argocd instances in one cluster.
Make sure the application-controller has cluster read rights.
Create an application x in both argocd instances. Let these applications point to different folders in a git repo. /app-a and /app-b

**Example**

https://github.com/iremmats/argocd-example-apps/tree/master/bug

**Expected behavior**

I expect being able to have applications named the same thing in two separate argocd instances in the same cluster.

**Screenshots**
Before sync - argocd instance one
<img width="684" alt="Screenshot 2019-09-24 18 23 21" src="https://user-images.githubusercontent.com/4477046/65531203-aa7c3300-def9-11e9-85cc-cfde5ca9966d.png">

Before sync - argocd instance two
<img width="687" alt="Screenshot 2019-09-24 18 23 31" src="https://user-images.githubusercontent.com/4477046/65530906-1ad68480-def9-11e9-87fd-3d7e55900f4d.png">

The first app/screenshot should only have special-config-a.

**Version**

We are running 1.2.1.

**Logs**

Struggling to find good logs.
SyncError
Failed sync attempt to 4725993215bdce6a1e7be9c5807ca3648fc6de9c: one or more synchronization tasks are not valid

From application controller:
time="2019-09-24T19:16:36Z" level=info msg="Comparing app state (cluster: https://cluster:443, namespace: app-b)" application=app-a
time="2019-09-24T19:16:36Z" level=info msg="manifest cache hit: &ApplicationSource{RepoURL:git@github.com:our-repo/app-b,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,}/4725993215bdce6a1e7be9c5807ca3648fc6de9c"
W0924 19:16:36.638113       1 listers.go:77] can not retrieve list of objects using index : Index with name namespace does not exist
time="2019-09-24T19:16:36Z" level=info msg=syncing application=app-a isSelectiveSync=false skipHooks=false started=false
time="2019-09-24T19:16:36Z" level=info msg="adding resource result, status: 'SyncFailed', phase: '', message: 'namespace app-a is not permitted in project 'app-a''" application=app-a kind=ConfigMap name=special-config-a namespace=app-a phase=Sync

Note here that this application "app-a" is deployed to app-b namespace, not app-a.

time="2019-09-24T19:16:36Z" level=info msg="Updating operation state. phase: Running -> Failed, message: '' -> 'one or more synchronization tasks are not valid'" application=app-a

**Have you thought about contributing a fix yourself?**

Open Source software thrives with your contribution. It not only gives skills you might not be able to get in your day job, it also looks amazing on your resume. 

If you want to get involved, check out the 
[contributing guide](https://github.com/argoproj/argo-cd/blob/master/docs/CONTRIBUTING.md), then reach out to us on [Slack](https://argoproj.github.io/community/join-slack) so we can see how to get you started.

**Comment by alexec** [comment]
This sounds like what would happen if have two Argo CD instances managing the same apps.

**Comment by kumarpramod** [comment]
Having the same issue when creating two different applications to be deployed in different clusters on same argocd.

I also have multiple argocd in the same cluster.

**Comment by jannfis** [comment]
I think you need to set `application.instanceLabelKey` to a unique value in each ArgoCD instance, because both ArgoCD instances will use the same instance label key by default. The instance label is applied to resources managed by ArgoCD, and is then used to figure out which resources need to be considered further.

Please see https://argoproj.github.io/argo-cd/operator-manual/argocd-cm.yaml for an example (at the very bottom).

**Comment by kumarpramod** [comment]
@jannfis Thanks. Adding `application.instanceLabelKey` works fine.

**Comment by sharadhirao** [comment]
Hi @alexec, we are planning to run 2 argocd which are two Argo CD instances in different bare metal regions managing the same apps. For now, we are not facing any issues. Is it because of the leader-elect process?
We are deploying the same configuration from both clusters. Is that the reason my application is working properly?
