### ISSUE TITLE
Using CURL to get Status of projects/applications - no session information

### ISSUE THREAD

**Issue by jsiegele** [argoproj/argo-cd#2356]
Hi! We are currently trying to obtain information about our projects / applications via the API (ala status) by using curl.
Our starting point is of course <ARGOCD_Server>/swagger-ui.

When creating a session like this:

```
export ARGOCD_SERVER = "https://argocd.xxx"
curl -k $ ARGOCD_SERVER/api/v1/session -d $ '{"username": "admin", "password": "l ... 7"}'
```

and if we use the Token like this:

```
curl -k -H "Authorization: Bearer $ARGOCD_TOKEN" $ARGOCD_SERVER/api/v1/applications
```

We get as response 401: "no session information"

We use this doku (but seems to be under construction): https://argoproj.github.io/argo-cd/developer-guide/api-docs/. 
It probably seems to fail on this issue: https://github.com/argoproj/argo-cd/issues/1642

Is there an example of using Curl that has already been successfully tested?

By the Way: `/swagger-ui#operation/CreateToken` - is the "expiresIn" really of the type string? i got the error, that a int64 is expected.

Thanks!

Version Information:
```
curl -k $ ARGOCD_SERVER / api / version
{"Version":"v1.2.0+674978c","BuildDate":"2019-09-04T21:27:17Z","GitCommit":"674978cd587701b39e81fce6d5c960b6d76d5882","GitTreeState":"clean","GoVersion":"go1.12.6","Compiler":"gc","Platform":"linux/amd64","KsonnetVersion":"0.13.1"}
```

**Comment by alexec** [comment]
Hmmm. What version are you running? #1642 is a v1.3 feature

**Comment by jsiegele** [comment]
We run Version v1.2.0+674978c

**Comment by alexec** [comment]
You need to use `Cookie: argocd.token=$ARGOCD_TOKEN`. Docs probably should state this.

**Comment by alexec** [comment]
Try this: https://github.com/argoproj/argo-cd/pull/2365/files

**Comment by jsiegele** [comment]
Thanks for the diff of the Doku .. right now the online documentation seams to point to the 1.3 Version: https://argoproj.github.io/argo-cd/developer-guide/api-docs/

**Comment by jsiegele** [comment]
@alexec Thank you: This works fine for me:
curl $ARGOCD_SERVER/api/v1/applications --cookie "argocd.token=$ARGOCD_TOKEN"

Please can someone review the documentation: https://argoproj.github.io/argo-cd/developer-guide/api-docs/

By the Way: /swagger-ui#operation/CreateToken - is the "expiresIn" really of the type string? i got the error, that a int64 is expected.
