### ISSUE TITLE
Argo CD Slack invite link not working

### ISSUE THREAD

**Issue by syst0m** [argoproj/argo-cd#2357]
**Describe the bug**

The Slack invite link here is no longer active:
https://argoproj.github.io/argo-cd/SUPPORT/

Clicking on the link redirects to:
https://argoproj.slack.com/join/shared_invite/enQtMzExODU3MzIyNjYzLTA5MTFjNjI0Nzg3NzNiMDZiNmRiODM4Y2M1NWQxOGYzMzZkNTc1YWVkYTZkNzdlNmYyZjMxNWI3NjY2MDc1MzI

```This invite link is no longer active.```

**To Reproduce**
Click on the Slack invite link on the SUPPORT section of the Argo CD website.

**Example**

...

**Expected behavior**

Join the Argo CD Slack channel from the invite link.

**Screenshots**

...

**Version**

...

**Logs**

...

**Have you thought about contributing a fix yourself?**
...

**Comment by alexec** [comment]
Huh. Works for me. Anyway, try this

https://join.slack.com/t/argoproj/shared_invite/enQtMzExODU3MzIyNjYzLWUxZDYyODIyYzY3N2RjOWMyNDA4NmFjMTNkMTE1ODI2OGY3MzgyMWFmMmY3N2UzNWRmOWFmMGY4NTBhZGQxYWY

**Comment by syst0m** [comment]
The link you sent works.
Thanks!

**Comment by alexmt** [comment]
thank you for now about expired link! Updated https://argoproj.github.io/community/join-slack . It should work now too.

**Comment by pdufault** [comment]
I tried the link provided above on September 27th, unfortunately I received this error:
```
This invite link is no longer active.
Please check with the person who shared it with you to see if there's a new link available.
```

Is it possible to have this Slack invite link regenerated?

Thank you in advance.

**Comment by alexec** [comment]
Try http://bit.ly/gitops-slack

**Comment by alexec** [comment]
Try this one https://join.slack.com/t/argoproj/shared_invite/enQtODMxNTg3OTA3Nzk0LTg5NDQ3YjRhYzNkMGZkMTEzN2IyZDQ2ZDI3ZTc1NmYxYzIyOGVlNjFmMjA3MDI2YWZlNTdlNzNmMjBhM2VlMDU

**Comment by pdufault** [comment]
Thank you! That worked.
