### ISSUE TITLE
Argocd v1.2.2 not starting!

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-cd#2358]
Running 

kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v1.2.2/manifests/install.yaml

but the argocd-server will not start, log from POD:

time="2019-09-25T11:38:24Z" level=info msg="Configmap/secret informer synced"
2019/09/25 11:38:24 [Model:]
2019/09/25 11:38:24 m.m: g(r_sub, p_sub) && keyMatch(r_res, p_res) && keyMatch(r_act, p_act) && keyMatch(r_obj, p_obj)
2019/09/25 11:38:24 g.g: _, _
2019/09/25 11:38:24 r.r: sub, res, act, obj
2019/09/25 11:38:24 p.p: sub, res, act, obj, eft
2019/09/25 11:38:24 e.e: some(where (p_eft == allow)) && !some(where (p_eft == deny))
2019/09/25 11:38:24 [Policy:]
2019/09/25 11:38:24 [p :  sub, res, act, obj, eft :  []]
2019/09/25 11:38:24 [g :  _, _ :  []]
2019/09/25 11:38:24 [Role links for: g]
time="2019-09-25T11:38:24Z" level=info msg="argocd v1.2.2+1aaf76f serving on port 8080 (url: , tls: true, namespace: argocd, sso: false)"
time="2019-09-25T11:38:24Z" level=info msg="0xc00007f020 subscribed to settings updates"
time="2019-09-25T11:38:24Z" level=info msg="Starting rbac config informer"
time="2019-09-25T11:38:24Z" level=info msg="RBAC ConfigMap 'argocd-rbac-cm' added"
W0925 11:46:43.297337       1 reflector.go:289] github.com/argoproj/argo-cd/util/settings/settings.go:454: watch of *v1.ConfigMap ended with: too old resource version: 116163430 (116166848)
W0925 11:46:50.421295       1 reflector.go:289] github.com/argoproj/argo-cd/util/rbac/rbac.go:221: watch of *v1.ConfigMap ended with: too old resource version: 116163430 (116166909)
time="2019-09-25T11:48:24Z" level=info msg="Alloc=7896 TotalAlloc=22484 Sys=70592 NumGC=11 Goroutines=117"
W0925 11:53:14.303437       1 reflector.go:289] github.com/argoproj/argo-cd/util/settings/settings.go:454: watch of *v1.ConfigMap ended with: too old resource version: 116177058 (116177161)
W0925 11:55:55.428318       1 reflector.go:289] github.com/argoproj/argo-cd/util/rbac/rbac.go:221: watch of *v1.ConfigMap ended with: too old resource version: 116177073 (116182083)
time="2019-09-25T11:58:24Z" level=info msg="Alloc=7684 TotalAlloc=26979 Sys=70592 NumGC=16 Goroutines=117"
W0925 12:00:35.323329       1 reflector.go:289] github.com/argoproj/argo-cd/util/settings/settings.go:454: watch of *v1.ConfigMap ended with: too old resource version: 116188599 (116190327)
W0925 12:02:23.434539       1 reflector.go:289] github.com/argoproj/argo-cd/util/rbac/rbac.go:221: watch of *v1.ConfigMap ended with: too old resource version: 116192253 (116193611)
W0925 12:07:24.332694       1 reflector.go:289] github.com/argoproj/argo-cd/util/settings/settings.go:454: watch of *v1.ConfigMap ended with: too old resource version: 116200494 (116202019)
time="2019-09-25T12:08:24Z" level=info msg="Alloc=7709 TotalAlloc=31607 Sys=70592 NumGC=21 Goroutines=117"
W0925 12:11:42.440697       1 reflector.go:289] github.com/argoproj/argo-cd/util/rbac/rbac.go:221: watch of *v1.ConfigMap ended with: too old resource version: 116203782 (116208874)

**Comment by alexmt** [comment]
Hello @emichaf , this is strange. I don't see any error in logs. Can you please share more information?

I guess `kubectl describe pod argocd-server-<hash>` should have all information.

**Comment by emichaf** [comment]
Argocd version v1.2.2 not working. Tried v1.2.0 via Helm chart 0.5.4 and it's working directly!

**Comment by alexec** [comment]
Is this still an issue?
