### ISSUE TITLE
App Creation Requires Namespace Even When Repo Contains Only Global Custom Resources

### ISSUE THREAD

**Issue by dgoodwin** [argoproj/argo-cd#2360]
**Describe the bug**

When deploying an Argo "Application" which only contains global custom resources, the CLI appears to require a namespace to be specified, which is slightly confusing when there is no specific namespace in play.

**To Reproduce**

 1. Configure a git repository with sub-directory containing your application yaml, in this case only a global custom resource. Example: https://github.com/dgoodwin/openshift4-gitops/blob/master/console/console.yaml
 1. Attempt to add an Argo Application for this repo and directory: `argocd app create console-config --repo https://github.com/dgoodwin/openshift4-gitops.git --path=console --dest-server=https://kubernetes.default.svc`

**Expected behavior**

Application created.

**Screenshots**

```
$ argocd app create console-config --repo https://github.com/dgoodwin/openshift4-gitops.git --path=console --dest-server=https://kubernetes.default.svc
FATA[0000] rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Destination server and/or namespace missing from app spec
```

**Version**

```shell
$ argocd version                                                     (argocd/api-dgoodwin-dev-new-installer-openshift-com:6443/system:admin/argocd)
argocd: v1.2.0+674978c
  BuildDate: 2019-09-04T21:26:04Z
  GitCommit: 674978cd587701b39e81fce6d5c960b6d76d5882
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.2.2+1aaf76f
  BuildDate: 2019-09-24T19:20:30Z
  GitCommit: 1aaf76f2303507479a9087e35be2b813eef316f2
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Have you thought about contributing a fix yourself?**

Yes.

**Comment by alexec** [comment]
Can you just use default or kube-system namespaces?

**Comment by dgoodwin** [comment]
You can use any namespace to workaround the issue. 

Should it be a required parameter all the time? I was fairly confused when I first saw it and immediately afraid that I wasn't going to be able to deploy this global config.
