### ISSUE TITLE
failed to update sync policy after deletion of repo

### ISSUE THREAD

**Issue by dontreboot** [argoproj/argo-cd#2363]
**Describe the bug**

After a repo is related, I am no longer able to update sync-policy anymore. I'd also like set auto-prune off as well

**To Reproduce**

If we cannot reproduce, we cannot fix! Steps to reproduce the behavior:

1. delete a repo
2. update sync-policy via argocd cli for an app that is associated with the rep
```
argocd app set istio-installation --sync-policy=none
FATA[0000] rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: repository not accessible: error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"
```

**Expected behavior**

Even though a repo is deleted, updating sync policy should still go through. For example, turning off auto-prune or updating sync policy from automatic to none.

**Screenshots**

**Version**

```shell
argocd: v1.2.1+a6a394b
  BuildDate: 2019-09-12T17:16:32Z
  GitCommit: a6a394ba93a2a56981a45b9395e245e5210eaa35
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.2.1+a6a394b
  BuildDate: 2019-09-12T17:16:02Z
  GitCommit: a6a394ba93a2a56981a45b9395e245e5210eaa35
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
Paste the output from `argocd version` here.
```

**Comment by alexec** [comment]
If you delete the repo, then it is not possible to interact with the app. Manual intervention is needed.

**Comment by dontreboot** [comment]
> If you delete the repo, then it is not possible to interact with the app. Manual intervention is needed.

 I have auto-prune set to true before I delete repo for the app. How can I turn it off now?

**Comment by alexec** [comment]
try `kubectl edit app APPNAME`?

**Comment by dontreboot** [comment]
Thanks. That works!
