### ISSUE TITLE
After Setting up SSO, argocd-secret falls out of sync

### ISSUE THREAD

**Issue by jpresky** [argoproj/argo-cd#2367]
**Describe the bug**

When SSO is setup, the instructions suggest to add a secret to argocd to refer to the clientSecret:
https://argoproj.github.io/argo-cd/operator-manual/sso/#existing-oidc-provider

> Any values which start with '$' will look to a key in argocd-secret of the same name (minus the $), to obtain the actual value. This allows you to store the clientSecret as a kubernetes secret.

After this value is added, if one is "Managing Argo CD Using Argo CD": https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#manage-argo-cd-using-argo-cd

Then the secret falls out of sync. See Screenshot below
![Screen Shot 2019-09-26 at 4 48 20 PM](https://user-images.githubusercontent.com/20145266/65724515-9281ec00-e07e-11e9-80b7-9933c2b7110f.png)

Now if a developer is trying to update argocd and updates the entire application instead of just the resource, argocd will go into a weird state. I basically had to do this:
https://github.com/argoproj/argo-cd/issues/998

It would be much better if adding the SSO secret did not cause the secret to go out of sync. 

I am confused as to why it doesn't go out of sync after immediately applying the secret since the secret is populated after argocd starts up. Ex: 
https://github.com/argoproj/argo-cd/blob/master/manifests/base/config/argocd-secret.yaml (there is no data in there)

**To Reproduce**

1. Manage ArgoCD using Argo CD (Kustomize install)
2. What I did was copy out argocd-secret using 

> kubectl get secret -n argocd -o yaml argocd-secret > argocd-secret.yaml

3. Add the SSO Secret to the file

>   oidc.onelogin.clientSecret: XXXXXXXXXX

4. 

> kubectl apply -f argocd-secret.yaml
5. Secret is now out of sync

**Expected behavior**

argocd-secret should not fall out of sync when adding a SSO secret 

**Version**

ArgoCD 1.1.2

Thanks ArgoCD Team!!!

**Comment by alexec** [comment]
Can you work-around this by ignoring the `/data` path? See https://argoproj.github.io/argo-cd/user-guide/diffing/

**Comment by nate-marshall** [comment]
@jpresky Did you use the work-around that @alexec suggested or did you find a different way of fixing this? I am running into this using the `OIDC (without Dex) to Azure AD` in https://argoproj.github.io/argo-cd/operator-manual/user-management/microsoft/

**Comment by jpresky** [comment]
I havent tried what alexec suggested. 

It is just left unsync'ed and my team knows not to sync that secret.... (not an ideal situation).
I don't see why the work around alexec proposed shouldn't work though. I really should get around to trying it.

**Comment by dctrwatson** [comment]
In ArgoCD 1.8.1 I added to stop this from happening:
```
  ignoreDifferences:
    - kind: Secret
      name: argocd-secret
      namespace: argocd
      jsonPointers:
        - /spec/data
        - /metadata/annotations
        - /metadata/selfLink
```

I'm not sure why `argocd-secret` needs this but `argocd-notifications-secret` does not though

**Comment by jpresky** [comment]
I am finally upgrading to 1.8.1 and it looks fixed for me. Is there something I am missing?

**Comment by dctrwatson** [comment]
> I am finally upgrading to 1.8.1 and it looks fixed for me. Is there something I am missing?

Pretty sure it's something on my application if it's fixed for you

**Comment by jpresky** [comment]
Alright I am going to close this issue out since it is resolved for me
