### ISSUE TITLE
OpenShift route always OutOfSync

### ISSUE THREAD

**Issue by cooktheryan** [argoproj/argo-cd#2370]
**Describe the bug**

OpenShift routes currently always stay in a constant out of sync status. This is due to the ingress objects. For example, if you were wanting to save a route within Git you could specify ingress: [] and then OpenShift would handle the definitions of the assets. What I think needs to happen is that Argo just ignores values under either status or ingress as the items are subject to change and cannot easily be managed. If we just ignored the fields similar to some of the ignores that are done with deployments and load balancer services we should be ok.

**To Reproduce**

1. Using an OpenShift environment deploy these assets https://github.com/cooktheryan/blogpost in Argo CD

2. Run a sync

3. See that the route always stay in an out of sync state

This is the value that exists within the OpenShift environment once the route is applied. 

```
  ingress:	
    - conditions:	
        - lastTransitionTime: '2019-09-27T15:07:34Z'	
          status: 'True'	
          type: Admitted	
      host: httpd-simple-app.apps-crc.testing	
      routerCanonicalHostname: apps-crc.testing	
      routerName: default	
      wildcardPolicy: None
```
The difficult thing is that we wouldn't want to store those values as is in git because the transaction time and potentially other fields could be subject to change

**Expected behavior**

Validate that the object exists but ignore everything under status:
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"route.openshift.io/v1","kind":"Route","metadata":{"annotations":{"openshift.io/host.generated":"true"},"creationTimestamp":null,"labels":{"app":"httpd","app.kubernetes.io/instance":"simple-app"},"name":"httpd","namespace":"simple-app","selfLink":"/apis/route.openshift.io/v1/namespaces/simple-app/routes/httpd"},"spec":{"host":"httpd-simple-app.apps-crc.testing","port":{"targetPort":8080},"subdomain":"","to":{"kind":"Service","name":"httpd","weight":100},"wildcardPolicy":"None"},"status":{"ingress":[]}}
    openshift.io/host.generated: 'true'
  creationTimestamp: '2019-09-27T15:07:34Z'
  labels:
    app: httpd
    app.kubernetes.io/instance: simple-app
  name: httpd
  namespace: simple-app
  resourceVersion: '452870'
  selfLink: /apis/route.openshift.io/v1/namespaces/simple-app/routes/httpd
  uid: 88de0f14-e138-11e9-93e2-0a580a8000d3
spec:
  host: httpd-simple-app.apps-crc.testing
  port:
    targetPort: 8080
  subdomain: ''
  to:
    kind: Service
    name: httpd
    weight: 100
  wildcardPolicy: None
**status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-09-27T15:07:34Z'
          status: 'True'
          type: Admitted
      host: httpd-simple-app.apps-crc.testing
      routerCanonicalHostname: apps-crc.testing
      routerName: default
      wildcardPolicy: None**
```

**Version**

```shell
argocd: v1.2.0-rc2+5571cf1
  BuildDate: 2019-08-21T15:47:33Z
  GitCommit: 5571cf133323f1c864472480c56e03e9ff3da0b3
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.2.2+1aaf76f
  BuildDate: 2019-09-24T19:20:30Z
  GitCommit: 1aaf76f2303507479a9087e35be2b813eef316f2
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Comment by jannfis** [comment]
Hi @cooktheryan , have you considered instructions from https://argoproj.github.io/argo-cd/user-guide/diffing/ to just have ArgoCD ignore the differences in the `ingress/conditions` path?

**Comment by cooktheryan** [comment]
This could be closed. By adding the following to the route definition in YAML the object will create and not state in an OutOfSync state.
```
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
```

**Comment by bcjarrett** [comment]
This was still the first hit on Google for me, so here was my solution. Thanks to @jannfis for pointing me in the right direction.

```
# Helm chart values I used which propagate to, or can be manually added to configmap "argocd-cm.data"
configs:
  cm:
    resource.customizations.ignoreDifferences.route.openshift.io_Route: |
      jqPathExpressions:
      - '.status.ingress'
```
