### ISSUE TITLE
Creating an application from Helm repository should select "Helm" as source type

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#2378]
**Describe the bug**

When you create an application from a Helm repository in the web UI, the source type should be automatically set to "Helm", not "Git", in the application creation dialogue. 

**To Reproduce**

1. Add a Helm repository to repositories, i.e. https://kubernetes-charts.storage.googleapis.com/
1. In web UI, navigate to "Settings" -> "Repositories"
1. Find the Helm repository, click on the 3 vertical dots right to it and select "Create Application"
1. You'll be taken to the Application Creation dialogue, the source type "Git" is pre-selected instead of Helm and you have to manually select "Helm" as source type

**Example**

Not required - can be reproduced without any actual application.

**Expected behavior**

Source type set to "Helm" when application is being created from a Helm repository.

**Screenshots**

![image](https://user-images.githubusercontent.com/3942683/65818609-52a03d80-e213-11e9-82df-dbb20c512d98.png)

![image](https://user-images.githubusercontent.com/3942683/65818646-a90d7c00-e213-11e9-809a-23d0db938349.png)

**Version**
HEAD as from today.

**Comment by alexmt** [comment]
Working on it

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/2409
