### ISSUE TITLE
Can't create Applications in GUi and CLI

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-cd#2384]
**Describe the bug**

Installed ArgoCD via:

kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v1.2.2/manifests/install.yaml

Trying to create Application via GUI & ArgoCD CLI, but gettting the error msg:

_Unable to create application: the server does not allow this method on the requested resource (post applications.argoproj.io)_

**Comment by alexmt** [comment]
Hello @emichaf , I suspect it might be environment specific issue (same for https://github.com/argoproj/argo-cd/issues/2358) . Which kubernetes version are you using?

**Comment by emichaf** [comment]
I'm using **K8S v1.13.5**, argo, argo-events is running ok, but argocd is not working!

The argocd-server log:
time="2019-10-01T06:42:14Z" level=info msg="Alloc=8683 TotalAlloc=2569774 Sys=70848 NumGC=2647 Goroutines=119"
W1001 06:48:04.578142       1 reflector.go:289] github.com/argoproj/argo-cd/util/settings/settings.go:458: watch of *v1.Secret ended with: too old resource version: 130611314 (130637923)
W1001 06:48:24.950358       1 reflector.go:289] github.com/argoproj/argo-cd/util/rbac/rbac.go:221: watch of *v1.ConfigMap ended with: too old resource version: 131495569 (131499006)
W1001 06:48:39.996413       1 reflector.go:289] github.com/argoproj/argo-cd/util/settings/settings.go:454: watch of *v1.ConfigMap ended with: too old resource version: 131497534

**Comment by emichaf** [comment]
Argocd version v1.2.2 not working. Tried v1.2.0 via Helm chart 0.5.4 and it's working directly!

**Comment by alexmt** [comment]
It might be an issue with Helm chart. This is maintained by the community and might be not up to date. Will try to reproduce issue tomorrow morning

**Comment by asim0984** [comment]
Looking for help to resolve below issue in my ArgoCD instance while trying to create an application via ArgoCD GUI deployed on argocd namespace.
Error:
W1004 12:32:07.729508 1 listers.go:77] can not retrieve list of objects using index : Index with name namespace does not exist
time="2019-10-04T12:32:07Z" level=error msg="finished unary call with code Unimplemented" error="rpc error: code = Unimplemented desc = the server does not allow this method on the requested resource (post applications.argoproj.io)" grpc.code=Unimplemented grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2019-10-04T12:32:04Z" grpc.time_ms=3584.089 span.kind=server system=grpc

ArgoCD version: 1.2.0

[user@node ~]$ kubectl describe pod argocd-server-7c5b6f9b6b-smc9d -n argocd
Name: argocd-server-7c5b6f9b6b-smc9d
Namespace: argocd
Priority: 0
Node: hostname/IP
Start Time: Fri, 04 Oct 2019 14:40:59 +0200
Labels: app.kubernetes.io/name=argocd-server
pod-template-hash=7c5b6f9b6b
Annotations:
Status: Running
IP: IP
Controlled By: ReplicaSet/argocd-server-7c5b6f9b6b
Containers:
argocd-server:
Container ID: docker://aa2c3144d377c9b8309997b5ff3a241eba0caac9269ed975ca0cb44f66f74dbc
Image: url:9999/argoproj/argocd:v1.2.0
Image ID: docker-pullable://url:9999/argoproj/argocd@sha256:c846cae9188254867e75a5029a777f3b7c09a986dac959c7cceb293446feed38
Ports: 8080/TCP, 8083/TCP
Host Ports: 0/TCP, 0/TCP
Command:
argocd-server
--insecure
--staticassets
/shared/app
--sentinel
argocd-redis-ha-announce-0:26379
--sentinel
argocd-redis-ha-announce-1:26379
--sentinel
argocd-redis-ha-announce-2:26379
--sentinelmaster
argocd
State: Running
Started: Fri, 04 Oct 2019 14:41:02 +0200
Ready: True
Restart Count: 0
Liveness: http-get http://:8080/healthz delay=3s timeout=1s period=30s #success=1 #failure=3
Readiness: http-get http://:8080/healthz delay=3s timeout=1s period=30s #success=1 #failure=3
Environment:
Mounts:
/app/config/ssh from ssh-known-hosts (rw)
/app/config/tls from tls-certs (rw)
/var/run/secrets/kubernetes.io/serviceaccount from argocd-server-token-6nnk4 (ro)
Conditions:
Type Status
Initialized True
Ready True
ContainersReady True
PodScheduled True
Volumes:
static-files:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit:
ssh-known-hosts:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: argocd-ssh-known-hosts-cm
Optional: false
tls-certs:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: argocd-tls-certs-cm
Optional: false
argocd-server-token-6nnk4:
Type: Secret (a volume populated by a Secret)
SecretName: argocd-server-token-6nnk4
Optional: false
QoS Class: BestEffort
Node-Selectors:
Tolerations: node.kubernetes.io/not-ready:NoExecute for 300s
node.kubernetes.io/unreachable:NoExecute for 300s
Events:

**Comment by alexec** [comment]
@emichaf is your question answered? Can I close please?

**Comment by asim0984** [comment]
My issue is not fixed.Can I get a solution

**Comment by tomjohnburton** [comment]
I got this issue while using the argo helm chart.
Installation works fine but when going to create an app I get the error
```
the server does not allow this method on the requested resource (post applications.argoproj.io)
```
Any ideas?
