### ISSUE TITLE
application-controller doesn't deal with rm/add same cluster gracefully (x509 unknown)

### ISSUE THREAD

**Issue by drewboswell** [argoproj/argo-cd#2389]
When adding a new cluster with either insecure or with a custom certificate, it does not work. The server fails to connect.

To reproduce, use a kubeconfig with a custom cert or just with tls skip verify, or the --insecure flag on the argocd cli. The cluster added, will be in error witht he following error:

```
Unable to connect to cluster: Get https:/something.something.com:6443/version?timeout=1s: x509: certificate signed by unknown authority
```

**Version**

```shell
argocd: v1.2.2+1aaf76f
  BuildDate: 2019-09-24T19:19:32Z
  GitCommit: 1aaf76f2303507479a9087e35be2b813eef316f2
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.2.2+1aaf76f
  BuildDate: 2019-09-24T19:20:30Z
  GitCommit: 1aaf76f2303507479a9087e35be2b813eef316f2
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1

```

**Logs**

```
Unable to connect to cluster: Get https:/something.something.com:6443/version?timeout=1s: x509: certificate signed by unknown authority
```

**Comment by alexec** [comment]
You need to add the correct certificates to your request.

**Comment by drewboswell** [comment]
Lol. Ok. I get. But hilarious sarcasm side, in version's prior to 1.2.0 I was able to use the kubectl config files without trouble.

My config file contains the cert. And beside that even when you select I don't care it still throws a F.U. 

Can someone non dismissive look at this?

**Comment by alexmt** [comment]
The argocd image has `argocd-util` binary which can help debugging cluster credentials. The simplest way to use it is to ssh into any argocd pod:

Save kubeconfig to local file:
```
kubectl exec -it <argocd-pod-name> bash # ssh into any argocd server pod
argocd-util kubeconfig https://<cluster-url> /tmp/config --namespace argocd # generate your cluster config
```

can point kubectl kubeconfig and try to use it:

```
KUBECONFIG=/tmp/config kubectl get pods # test connection manually
```

@drewboswell hope it helps

**Comment by drewboswell** [comment]
Hi, so I've pinpointed this problem a little more.

The application-controller does not deal with a delete and add of a cluster gracefully.

Scenario:
A full cluster resinstall has happened, so the certificate has changed but none of the other details. Cluster name and coordinates stay the same.
1. delete cluster in argocd
2. add cluster back to argocd (certificate will be different)

Unless we perform an application-controller delete, argo refused to connect due to "certificate" problems.

**Comment by alexmt** [comment]
thank you for update @drewboswell !

**Comment by alexec** [comment]
I'm going to investigate this.

**Comment by alexec** [comment]
Looking at your use case, you actually want to update the cluster's credentials and are doing (I'm assuming) `argocd cluster rm` then `argocd cluster add`) to achieve this. The removal of the cluster is working, but the adding is not working. 

I'm going to see if this can be repo'd by adding `docker-for-desktop`, trashing the certificate, and then trying to remove/add it.

**Comment by alexec** [comment]
OK, I've repo'd the bug as follows (and this shows how you can workaround this by replacing the CA cert manually). 

Argo CD stores clusters in secrets named `cluster-${host}-${randInt}`, so you can fix/break them by editing that secret.

Create a cluster from local context: `argocd cluster add docker-for-desktop`
Get the underlying secret: `kubectl get secret cluster-kubernetes.docker.internal-904396332 -o yaml`. 
Decode the `data.config` field from base 64 into JSON (security note - be cautious of using any online convertors for this - some exfiltrate secrets). In that decode document,  the `caData` field contains your CA cert, again base 64 encoded. Replace this field with your new cert (base 64 encoded obvs). Use `k edit secret cluster-kubernetes.docker.internal-904396332` to update the `data.config` field.

Run `argocd cluster list` and you should see `certificate signed by unknown authority`.
Try to remove using `argocd cluster rm docker-for-desktop`. Appears to work, but..
Run `k get secrets` to see that the secret has not been deleted.

**Comment by alexec** [comment]
@drewboswell 

I've now investigated and need more information from you to verify my hypothesis.

Facts:

* Adding and removing clusters by the CLI use different parameters `argocd cluster add CONTEXT` vs `argocd cluster rm SERVER`. E.g. you run `argocd cluster add docker-for-desktop` to add the cluster, but `argocd cluster rm https://kubernetes.docker.internal:6443` to remove it.
* `argocd cluster rm` is idempotent and if the cluster does not exist, it returns exit code 0.

I can verify this hypothesis if you can tell me exactly the commands you use. 

Thank you.

**Comment by drewboswell** [comment]
yes we used the cli add/rm commands. And I have found it odd that they take different identifiers to perform the actions.

However, I just want to underline the fact that if I delete the controller, when it re-spawns everything works as expected. Maybe it is some sort of caching problem inside the application controller?

**Comment by alexec** [comment]
Thank you @drewboswell. I also found it odd. The CLI docs actually need to be updated IMHO to make this clear. 

What I don't have for this issue, and really need to investigate, is the precise repro steps.

Are you able to provide a step-by-step example please? Or does the above example match what you're doing?

**Comment by alexmt** [comment]
I think I know how to reproduce it. Working on it
