### ISSUE TITLE
Make App diff configMapGenerator aware

### ISSUE THREAD

**Issue by moensch** [argoproj/argo-cd#2397]
**Is your feature request related to a problem? Please describe.**
We are using kustomize and `configMapGenerator` in a fair few places, including the automatic "hash suffix" feature.
In Argo CD in the diff, it always shows this as a "removed file" and an "added file" instead of a diff.
I understand Argo CD literally shows the right stuff (because a brand new resource is being created).

For example, I have this in my `kustomization.yaml`:
```
configMapGenerator:
- name: aws-iam-authenticator
  namespace: kube-system
  files:
    - configs/config.yaml
```
Whenever `config.yaml` changes, a resource like `aws-iam-authenticator-57k69g6486` is being deleted, and a new one like `aws-iam-authenticator-97t26c544m` is created.

**Describe the solution you'd like**
It would be cool if it could somehow "understand" that this came from a `configMapGenerator` and show a nice side-by-side diff off the two resources (even though they have different names).

**Have you thought about contributing yourself?**
Yes - mostly logging to get input from others and if a solution to this is even feasible.

**Comment by alexec** [comment]
Does this help? 

https://argoproj.github.io/argo-cd/user-guide/compare-options/#ignoring-resources-that-are-extraneous

**Comment by alexmt** [comment]
I think we were planning to solve the exact same issue by https://github.com/argoproj/argo-cd/issues/1636 . @jessesuen , can you please confirm if this is right?

**Comment by alexmt** [comment]
I think @alexec is right. The `compare-options: IgnoreExtraneous` should keep app in sync status. And GC of old config maps is supposed to be solved by #1636 

https://github.com/argoproj/argo-cd/issues/1629#issuecomment-499253376

**Comment by kplimack** [comment]
👍

**Comment by gaeljw** [comment]
I'm not sure the suggestions above solve the initial issue/question which (in my understanding) is more about the visual diff in ArgoCD UI.

`IgnoreExtraneous` flag would just ignore the old resource in the diff but still show a new resource. What we'd like is that the UI is "smarter" and display the actual diff between old resource and new resource as if it was the same resource even though technically on Kubernetes these really are 2 different resources.

**Comment by flojon** [comment]
Would be nice to have something similar to how git detects renamed files when showing diff.
