### ISSUE TITLE
Maintenance window meaning is confusing

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#2398]
**Describe the bug**

The maintenance window project field allows restricting auto / manual sync for the application. I think it might be confusing for some users.

I expected an opposing meaning: maintenance enables syncing and syncing is prohibited outside of the maintenance window. 

To solve the confusion can we rename the maintenance window to something else? For example, spinnaker has 'restricted execution windows' https://www.spinnaker.io/guides/tutorials/codelabs/safe-deployments/#adding-an-execution-window-to-deployment-pipelines .

**Comment by alexmt** [comment]
@adamjohnson01 what do you think? or is it just me understanding meaning of the maintenance window incorrectly?

**Comment by adamjohnson01** [comment]
@alexmt, I think that you are right. It is confusing. I think that perhaps the logic needs to be reversed and renamed to sync windows?

**Comment by adamjohnson01** [comment]
Something like this

![Screenshot 2019-10-02 at 17 43 25](https://user-images.githubusercontent.com/12121539/66063905-3f0b1480-e53c-11e9-9bb6-c100c8c3acb7.png)

![Screenshot 2019-10-02 at 17 44 29](https://user-images.githubusercontent.com/12121539/66064637-ae353880-e53d-11e9-93b4-925268a6975f.png)

**Comment by alexmt** [comment]
This is a great idea. I was thinking to just rename to clarify the meaning but adding the `kind` field is much better.

**Comment by alexmt** [comment]
@adamjohnson01 do you think you will have time to work on it this month? We were hoping to test and release 1.3 by the end of the October.

**Comment by adamjohnson01** [comment]
@alexmt, I will try and have it done in the next couple of days.

**Comment by alexec** [comment]
@alexmt can we close this?
