### ISSUE TITLE
compare-options annotation don't appear to work v1.2.0

### ISSUE THREAD

**Issue by spencergilbert** [argoproj/argo-cd#2427]
**Describe the bug**
compare-options annotation doesn't appear to be working, I have another cluster running off of HEAD and will see if i have the same experience there.

**Example**
```❯ kubectl get pvc data-logging-kafka-0 -oyaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
    pv.kubernetes.io/bind-completed: "yes"
    strimzi.io/delete-claim: "false"
  creationTimestamp: "2019-09-10T16:51:36Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    optoro.io/appname: logging-stack
    strimzi.io/cluster: logging
    strimzi.io/kind: Kafka
    strimzi.io/name: logging-kafka
  name: data-logging-kafka-0
  namespace: logging
  resourceVersion: "40894293"
  selfLink: /api/v1/namespaces/logging/persistentvolumeclaims/data-logging-kafka-0
  uid: 222f8651-ace1-42fb-a712-6ebe633095ae
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem
  volumeName: pvc-222f8651-ace1-42fb-a712-6ebe633095ae
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  phase: Bound
```

**Expected behavior**
Based on https://github.com/argoproj/argo-cd/pull/1680/files I expect I should be able to have ArgoCD not be grumpy about these PVCs by annotating them.

**Screenshots**
![Screenshot from 2019-10-07 12-57-22](https://user-images.githubusercontent.com/11903873/66332682-4860fc00-e903-11e9-860e-cf8caf4e0f76.png)

**Version**
argocd:v1.2.0

**Comment by alexec** [comment]
Interesting. What happens when you sync - are they pruned? Or are they ignored?

**Comment by spencergilbert** [comment]
It looks like it tries to prune them, it looks like Strimzi provides some protection on the PVC through the `strimzi.io/delete-claim: "false"` annotation

**Comment by spencergilbert** [comment]
@alexec are there any other logs or resource config I can grab to troubleshoot this?

**Comment by alexec** [comment]
I was looking and I can't see any code issue. I can see `    argocd.argoproj.io/sync-options: Prune=false` is in your YAML, but not in the screenshot.

Can you double check that is actually on the manifest please?

If that is the case, can you get the lines from logs from the application controller that contant the app name?

**Comment by spencergilbert** [comment]
Yep, I'll look tomorrow - I had taken the screenshot prior to noticing the prune=false option and trying that as well.

**Comment by spencergilbert** [comment]
![image](https://user-images.githubusercontent.com/11903873/66672760-06022c80-ec2d-11e9-9dd1-36855faff6cc.png)

logs look innocuous:
```

Oct 11, 2019 @ 13:53:28.165 | time="2019-10-11T17:53:28Z" level=info msg="Update successful" application=logging-stack
-- | --

  | Oct 11, 2019 @ 13:53:28.165 | time="2019-10-11T17:53:28Z" level=info msg="Reconciliation completed" application=logging-stack fields.level=1 time_ms=305.665277


Oct 11, 2019 @ 13:53:27.860 | time="2019-10-11T17:53:27Z" level=info msg="copying credentials" credUrl="git@gitlab.com:optoro" repoURL="git@gitlab.com:optoro/infrastructure/helm-charts/logging-stack.git"
-- | --

  | Oct 11, 2019 @ 13:53:27.860 | time="2019-10-11T17:53:27Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: logging)" application=logging-stack

  | Oct 11, 2019 @ 13:53:27.859 | time="2019-10-11T17:53:27Z" level=info msg="Update successful" application=logging-stack

  | Oct 11, 2019 @ 13:53:27.859 | time="2019-10-11T17:53:27Z" level=info msg="Reconciliation completed" application=logging-stack fields.level=1 time_ms=325.73494600000004

  | Oct 11, 2019 @ 13:53:27.859 | time="2019-10-11T17:53:27Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=logging-stack

**Comment by alexec** [comment]
Can I check - are you just deleting the resource, or are you deleting the whole app. In the second case I can see that we don't check `Prune=false`.

**Comment by alexec** [comment]
Do you have a Slack handle and we can chat about this.

**Comment by spencergilbert** [comment]
yep, im in the argo slack as sgilbert

**Comment by alexec** [comment]
Hey. What is the overall app status? Is it in-sync? I can't see in your screenshot.

**Comment by alexmt** [comment]
Also could you please check sync operation result to see if controller tried to delete PVC or not

**Comment by spencergilbert** [comment]
![image](https://user-images.githubusercontent.com/11903873/66677387-7ca42780-ec37-11e9-9829-4618d3b199c1.png)

The app shows as Healthy, Sycned, and last sync successful - the PVCs show 'STATUS
 OutOfSync (requires pruning)'

huh - maybe this is just a UI bug, i just synced all - it succeeded, and i dont see any logs where it tried to delete teh PVC, the status still shows that it "requires pruning"

**Comment by alexec** [comment]
This is what we expected - the UI shows that it needs pruning, but it will not be pruned in a sync. 

We're thinking of fixing the UI.

**Comment by spencergilbert** [comment]
Ahh, gotcha - ok then we can close this, outcome works for me - and i can set expectations, i do think and :+1: on hiding it in the UI.

Thanks guys!
