### ISSUE TITLE
Rollback should disable autosync

### ISSUE THREAD

**Issue by estahn** [argoproj/argo-cd#2441]
**Is your feature request related to a problem? Please describe.**

Doing a rollback via the UI will return the following error message:
```
Unable to rollback application: rollback cannot be initiated when auto-sync is enabled
```

This is counter-intuitive for an end-user as he will now go into app-settings and disable auto-sync. A one-click rollback now becomes a more complicated endeavour. 

**Describe the solution you'd like**

Clicking rollback via the UI should include all the actions required to execute the rollback, e.g. disable auto-sync.

**Have you thought about contributing yourself?**

Yes.

**Comment by alexec** [comment]
Good idea. This could be a UI only change and therefore a good one for community contribution. I think the change would be around here:

https://github.com/argoproj/argo-cd/blob/master/ui/src/app/applications/components/application-deployment-history/application-deployment-history.tsx#L53

**Comment by estahn** [comment]
@alexec I think this is also required in the CLI. At the moment you will have to disable sync policy via `argocd app set <app> --sync-policy none` before doing a rollback.

**Comment by alexec** [comment]
CLI changes could probably be done here:

https://github.com/argoproj/argo-cd/blob/f6545cd56ae0cbdbc40b4cf57db190d06217ccef/cmd/argocd/commands/app.go#L1298

**Comment by adamjohnson01** [comment]
@estahn, are you planning on implementing this?

**Comment by adamjohnson01** [comment]
@alexec , as far as I can tell rollbacks are only ever initiated by a user. Would it not be better to make changes here instead of both the ui and the cli?

https://github.com/argoproj/argo-cd/blob/73590e1a3982501865577c2a2c9ec8794391b813/server/application/application.go#L989

**Comment by estahn** [comment]
@adamjohnson01 I would like to, I'm just short on time at the moment. If anyone else wants to go ahead don't wait for me :)

**Comment by adamjohnson01** [comment]
@alexec, for the cli we could add a disable-autosync flag to the rollback command. 

The UI has a pop up asking if you are sure you want to rollback. How about adding a warning that autosync will be disabled if you rollback as you already have to click rollback then ok? In our experience we have only ever used rollback when there is an issue and we want to revert as quickly as possible.

**Comment by alexec** [comment]
I still think this should be UI only - in the pop-up you could have a button to disable it.

**Comment by adamjohnson01** [comment]
Sure, I will move it to the UI. I just meant I was not sure that the extra button was required.

**Comment by alexmt** [comment]
I don't have very strong opinion about it but I would still keep most of the logic on server side.

Not 100% sure we should let user ability to keep auto-sync, but to archive it I would add `keepAutoSync` field to ApplicationRollbackRequest proto and use that flag to disable or enable auto-sync on server side.

https://github.com/argoproj/argo-cd/blob/5abe863ea9a103a9ce3165f200e8b0f1b0828dcc/server/application/application.proto#L92-L97
