### ISSUE TITLE
`argocd login` UX improvements

### ISSUE THREAD

**Issue by estahn** [argoproj/argo-cd#2442]
**Is your feature request related to a problem? Please describe.**

Running `argocd login` fails because we need to run it with a couple of arguments, e.g. `argocd login --grpc-web --sso argocd.foobar.com`. This is annoying as you have to keep the parameters in mind and possibly educate users across the organisation.

**Describe the solution you'd like**

The CLI should take the config available at `~/.argocd/config` and use it as default. All arguments are already present in this file, except `sso`. `sso: true` would need to be added to the config.

**Have you thought about contributing yourself?**

Yes.

**Comment by alexec** [comment]
does `ARGOCD_OPTS=--grpc-web argocd login` work?

**Comment by estahn** [comment]
@alexec It doesn't, because the usage is `argocd login SERVER [flags]`. But it also doesn't work if I do `ARGOCD_OPTS=--grpc-web argocd login argocd.foobar.com` because `--sso` is missing.

**Comment by estahn** [comment]
@alexec No, it does not :)

I can have a look implementing it if something like this would be accepted.
