### ISSUE TITLE
Add target/current revision to status badge

### ISSUE THREAD

**Issue by drewboswell** [argoproj/argo-cd#2445]
It would be very useful to have the target version displayed in the status-badge. That way you know relative to what the application is (un)synced and (un)healthy.

Current info: {health} | {sync status}
Proposal: {health} | {sync status} | {target revision}

It might also be worth having a separate badge containing both current revision and target revision.

**Comment by alexec** [comment]
Good one for community contribution.

**Comment by alexec** [comment]
I don't believe the PR closes this issue.

**Comment by milesarmstrong** [comment]
Hi @alexec, I'm taking a look at this issue for a first contribution, and I'm curious why https://github.com/argoproj/argo-cd/pull/1844 moved away from an SVG generated in Go to the SVG asset with regex replacements, can you shed any light?

**Comment by alexmt** [comment]
hello @milesarmstrong , we switched to svg + regex to get a better looking badge.

It was too difficult to generate nice SVG using only golang, so I've created a better SVG image using image editor, exported image as SVG and use regex to inject sync/health status in the fly.

**Comment by milesarmstrong** [comment]
I've been looking at https://github.com/badges/shields for inspiration.

The general format of badges I've seen seems to be that the left-hand part is static (explaining what the badge displays) and the right-hand part is the dynamic part.

How would you feel about extending the badge functionality to provide 3 separate badges
- Sync Status
- Health Status
- Revision

**Comment by milesarmstrong** [comment]
I decided not to go down that route, and figured out a way to optionally add it to the existing badge.

See #3128

**Comment by drewboswell** [comment]
This is cool! What do you think about using the target revision in stead? That way if you use something like tags, it is more readable. (v1.1.0 for example)

**Comment by milesarmstrong** [comment]
I agree that would probably be more useful! I chose the short commit SHA because it's a predictable width when rendered in a monospace font, which makes it much easier to fit into the SVG.

I think if we wanted to use arbitrarily wide tags (and have them readable) we'd need to reconsider how we're generating the SVG.

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-cd/commit/85a746f861c3fbfd42f5db3ea6e01aa2d67b1e5b
