### ISSUE TITLE
JSON/YAML output of `argocd app actions list <appName>` is incorrect

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#2460]
**Describe the bug**

The JSON/YAML formatted output of `argocd app actions list <appName>` command is incorrect

**To Reproduce**

1. Configure an application which resources have any action.
2. Run `argocd app actions list <appName> -o=yaml` or `argocd app actions list <appName> -o=json`

JSON output:
```
{
  "\tService\trollouts-demo": null,
  "\tService\trollouts-demo-preview": null,
  "argoproj.io\tRollout\trollouts-demo": [
    {
      "name": "argoproj.io/Rollout/resume"
    }
  ],
  "extensions\tIngress\trollouts-demo": null
}
```

YAML output:

```
"\tService\trollouts-demo": null
"\tService\trollouts-demo-preview": null
"argoproj.io\tRollout\trollouts-demo":
- name: argoproj.io/Rollout/resume
"extensions\tIngress\trollouts-demo": null
```

**Expected behavior**

YAML and JSON output should be consistent with text formatted output:
```

GROUP        KIND     NAME           ACTION                      AVAILABLE
argoproj.io  Rollout  rollouts-demo  argoproj.io/Rollout/resume  false
```

Expected JSON:
```
[{
  "group": "argoproj.io",
  "kind": "Rollout",
  "name": "rollouts-demo",
  "action": "argoproj.io/Rollout/resume",
  "available": false
}]
```
Expected YAML:
```
---
- group: argoproj.io
  kind: Rollout
  name: rollouts-demo
  action: argoproj.io/Rollout/resume
  available: false
```

**Comment by alexmt** [comment]
@simster7 , since you are working on actions do you want to pick up this one too?

**Comment by simster7** [comment]
@alexmt Yup! I’ll take this one as well

**Comment by alexec** [comment]
can I propose a new way to do these?

We don't have a good way to test this marshalling and it is always tightly coupled to the CLI.

Is there anyway to extract this into a common interface/utility?

**Comment by alexmt** [comment]
I've added the proposed output in the description. I think we have this bug because actions is not the first-class object. There is no data structure which can be marshaled into json
