### ISSUE TITLE
Need Argo Operator

### ISSUE THREAD

**Issue by edlee2121** [argoproj/argo-cd#2462]
**Is your feature request related to a problem? Please describe.**
An Argo operator would provide a standard way to install and manage the lifecycle of Argo CD. RedHat OpenShift uses operators to manage K8s applications.
https://docs.openshift.com/container-platform/4.1/applications/operators/olm-what-operators-are.html

**Describe the solution you'd like**
https://github.com/operator-framework
https://operatorhub.io/getting-started

**Comment by alexec** [comment]
Would this replace other installation methods?

**Comment by edlee2121** [comment]
Anyone from RedHat interested in contributing this? :-)

**Comment by dgoodwin** [comment]
@edlee2121 sure no problem https://github.com/jmckind/argocd-operator :)

We just found out this existed yesterday, written by someone in operator enablement team. Hopefully this provides a good starting point, if not a full implementation.

**Comment by alexec** [comment]
This is written by John MeKenzie at RedHat (https://github.com/jmckind).

**Comment by jmckind** [comment]
Hey, just saw this. :) Definitely interested to see how we can use what I did as a starting point for a fully supported operator.

**Comment by disposab1e** [comment]
Wrote a small guide.. perhaps you're interested in.

https://github.com/disposab1e/argocd-operator/blob/argo-cd-crc-macos/guides/install_with_crc_macos.md

**Comment by alexec** [comment]
Thank you for replying @jmckind. We've not come up with a list of use cases for the operator yet. I wondered if you know what you were looking for?

**Comment by disposab1e** [comment]
And one more guide with Minikube.

https://github.com/disposab1e/argocd-operator/blob/argo-cd-minikube-macos/guides/install_with_minikube_macos.md

**Comment by siamaksade** [comment]
Upgrades of ArgoCD itself are also interesting

**Comment by blaise-sumo** [comment]
Well, @jmckind , @alexec ,
Whoever this guy is:
https://argocd-operator-helm.readthedocs.io/en/latest/
I vote we support him. The docs are very nicely put together.

**Comment by edlee2121** [comment]
Exists now.

**Comment by wtam2018** [comment]
It is currently a argoproj-labs project https://github.com/argoproj-labs/argocd-operator.
