### ISSUE TITLE
Render application label through kustomize instead of replacing after

### ISSUE THREAD

**Issue by KarstenSiemer** [argoproj/argo-cd#2466]
Hello,

by default when argocd is used with kustomize, it sets the instance label as the application name.
The problem here is that is does this after the kustomization was rendered.
e.g https://github.com/argoproj/argo-cd/blob/16e645b2685e61b9df8ac69e19881d87c007cabf/reposerver/repository/repository.go#L332
> kube.SetAppInstanceLabel(target, q.AppLabelKey, q.AppLabelValue)

This potentially causing errors when users are utilizing variables inside kustomize where they are doing operations on that label or with the value of that label.
This could be avoided by rendering the application label with kustomize in the first place.
All operations would stay valid 

at the time this can be avoided by using the commonLabel feature introduced here:
https://github.com/argoproj/argo-cd/commit/b645589ed597edd17957f87371c909d5717f84de

Yet, i think, i would be more favorable to do it right in the first place

**Comment by alexec** [comment]
Hi - can you please provide repro steps?

**Comment by KarstenSiemer** [comment]
1. Have a base with a commonLabel for instance label e.g. app.kubernetes.io/instance=test
2. Take the value of the instance label and save it to var inside kustomization:
```
vars:
- name: INSTANCE
  objref:
    apiVersion: v1
    kind: Service
    name: taskmanager
  fieldref:
    fieldpath: metadata.labels[app.kubernetes.io/instance]
```
3. Use that variable in a crd, for example a selector inside a servicemonitor from prometheus-operator.
```
selector:
    app.kubernetes.io/test: $(INSTANCE)
```
4. When rendered via kustomize build, inside that selector there will be the value 'test'
5. When now consumed by argocd, the  app.kubernetes.io/test label does not have the variable of $(INSTANCE) in it but now test.
6. Argocd replaces the value 'test' of the instance label with the application name.
7. The value of app.kubernetes.io/test does not have the actual value of the instance label any more.

**Comment by alexec** [comment]
Thank you Karl.

Argo CD uses a label, by default `app.kubernetes.io/instance`, to identify what resources comprise the app. Therefore if the tool uses that label as well, a conflict occurs. Changing the code to not apply this if the tool has applied it already would mean that Argo CD could not reconcile the app - it would not be able to know which resources comprise it.

You can change the label used from it's default value by following these instructions:

https://argoproj.github.io/argo-cd/faq/#why-is-my-app-out-of-sync-even-after-syncing

Alex

See also #1482.
