### ISSUE TITLE
Add a Kubernetes operator for ArgoCD

### ISSUE THREAD

**Issue by siamaksade** [argoproj/argo-cd#2468]
**Is your feature request related to a problem? Please describe.**
Installing ArgoCD on k8s clusters involved multiple steps
* Depending on HA/non-HA installation, different `install.yaml` should be used
* Pre-configure roles might be required for the installation
* Ingress configurations might be needed

Furthermore when a new release of ArgoCD appears, there are no clear upgrade paths available. 

**Describe the solution you'd like**

Operators, as defined in [Kubernetes docs](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/), _aims to capture the key aim of a human operator who is managing a service or set of services_. Creating an operator for ArgoCD (ArgoCD Operator), would allow automating the steps involved in installation and upgrades of ArgoCD on Kubernetes clusters. After installing the ArgoCD Operator on a Kubernetes cluster, users would be able to create a CR in their namespace which would captures the information needed for installing ArgoCD, for example: 

```yaml
apiVersion: operator.argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: my-argocd
spec:
  targetNamespace: argocd
  ha: "false"
  ingress: "true"
```

The ArgoCD Operator would consume the `ArgoCD` CR and install ArgoCD in the target namespace. The operator would then be able to perform more complex day-2 operations on ArgoCD as needed. The simplest of these operations could be upgrade to newer versions.

[Operator Framework](https://github.com/operator-framework/getting-started) is a toolkit that simplifies creating operators but generating the skeleton and boilerplate code needed to get started.

There is a growing ecosystem of operators that are being created for Kubernetes and are published to https://www.operatorhub.io

There is also a guide for creating operators published there:
https://operatorhub.io/getting-started

**Comment by siamaksade** [comment]
@alexec ah, yes. it's the same :)

**Comment by edlee2121** [comment]
Any devs from RedHat interested in contributing this :-)

**Comment by alexec** [comment]
Should maybe support HPA? #2559
