### ISSUE TITLE
Intermittent unknown state.

### ISSUE THREAD

**Issue by phenri00** [argoproj/argo-cd#2472]
**Describe the bug**

We added a second repository(https) which we have two applications from two branches. The state switches from OutOfSync(expected) to Unknown intermittent every 5-10 minutes. If we manually sync the application will go from unknown to OutOfSync, and then later on back and forth. 

Health status: ok
Synchronization: ok
 
Error message:

ComparisonError rpc error: code = Unknown desc = Get  https://xxx.com/xxx.git/info/refs?service=git-upload-pack: read tcp 10.1.10.1:56682->(git repo ip) :443: read: connection reset by peer

We also have another repository with one branch and ~10 applications, all syncs just fine.

According to gitlab(self hosted) server logs we are getting ~5 GET request per second for this repo, all which returns 200 OK. 

**Version**

argoproj/argocd:v1.2.2 and argoproj/argocd:v1.2.3

**logs**

argocd-repo-server:

time="2019-10-11T13:02:17Z" level=error msg="finished unary call with code Unknown" error="Get https://url.repo.git/info/refs?service=git-upload-pack: read tcp 10.1.96.6:47106->IP: read: connection reset by peer" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2019-10-11T13:03:17Z" grpc.service=repository.RepoServerService grpc.start_time="2019-10-11T13:02:17Z" grpc.time_ms=93.565 span.kind=server system=grpc

**Comment by jannfis** [comment]
Hm, `connection reset by peer` sounds weird in that context. Are we talking a large repository, i.e. with some binary files in it maybe? Can you find out how long it takes between the request coming in and the unexpected termination?

**Comment by phenri00** [comment]
Ok to close. Have not seen this issue in later versions of ArgoCD.

**Comment by mateustanaka** [comment]
Hi @phenri00, I'm facing the same problem with version v1.6.1+1. What did you do to fix it?

**Comment by paulliss** [comment]
> later versions of ArgoCD.

same problem!

**Comment by mmerickel** [comment]
I’ve also been experiencing this since deploying argocd over the last couple weeks on versions 2.4.0 through 2.4.3. The behavior is exactly as @yingchi1994 described. All of the traffic is in a single aws vpc and our self-hosted gitlab has been very reliable. I have to think there is a race condition or bad timeout in argocd. The only other thought is that we deploy several app-of-apps repos where multiple configs come from the same repo. All of the apps are using git over ssh. 

I tried turning on auto scaling with at least 2 repo servers and 2 argocd servers but it didn’t help.

**Comment by yiyan-wish** [comment]
@mmerickel We also use app-of-apps repos, and the unknown state occur frequently. 
Dose your problem solved?

**Comment by mmerickel** [comment]
Unfortunately this is still an issue even with 2.4.6. I think #9739 only solved it for TLS and not for ssh. Clicking refresh again on an app in the unknown state fixes the problem every single time for me.

**Comment by mmerickel** [comment]
I opened https://github.com/argoproj/argo-cd/issues/9981 to have this tracked by an open ticket.
