### ISSUE TITLE
Deployed application resources should be annotated

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#25]
Deployed application resources should be annotated with a label which has application name and application revision. This allows displaying following additional information about the application: a version of each deployed resource, unexpected resources (e.g. resources which are deployed but not defined in the specification)

- [x] Add application and revision labels to resources
- [ ] Populated 'unexpected' resources while comparing target and live states
- [ ] Render 'unexpected' resources and resource revision in web ui

**Comment by alexmt** [comment]
working on it

**Comment by alexmt** [comment]
Item 'Add application and revision labels to resources' had been implemented

**Comment by jessesuen** [comment]
Closing this issue and using issue #104 to track unexpected resources.
