### ISSUE TITLE
"argocd app sync --resource" prints stale status

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#2519]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The "argocd app sync" prints stale sync status. After sync is completed the final command status shows resource in OutOfSync state.

**To Reproduce**

1. Try syncing one resource of any app using "argocd app sync <appName> --resource" command
2. The command is successfully completed but prints synced resource status as OutOfSync

**Expected behavior**

The final output should include final sync status.

**Version**

```shell
v1.3.0-rc1
```

**Comment by simster7** [comment]
I'll take this one unless you already started on it @alexmt?

**Comment by alexec** [comment]
I've just started look into this.

**Comment by alexec** [comment]
While you are at it - can I please ask you to add an example of syncing as specific resource to the CLI example? E.g.

```
# Sync a specific resource
  argocd app sync my-app --resource 'extensions:Deployment:my-deployment'
```

**Comment by simster7** [comment]
You got it!
