### ISSUE TITLE
Variable substitution not working as expected

### ISSUE THREAD

**Issue by jaykay** [argoproj/argo-cd#2539]
**Describe the bug**

When substituting a variable in `argocd-cm` with $-notation as stated in the [docs](https://argoproj.github.io/argo-cd/operator-manual/sso/) an extra line break  and `|` is added which causes the error

```
time="2019-10-22T14:53:36Z" level=error msg="Failed to authenticate: oidc: failed to get token: oauth2: cannot fetch token: 401 Unauthorized
Response: {
  \"error\": \"invalid_client\",
  \"error_description\": \"Unauthorized\"
}" 

```

**To Reproduce**
use variable substitution with $ and see the generated config in the pod or see the logs of dex server pod

**Expected behavior**

Authentication should work with variable substitution as stated in the docs.

**Screenshots**

**Version**
```
argocd: v1.2.0+674978c
  BuildDate: 2019-09-04T21:26:04Z
  GitCommit: 674978cd587701b39e81fce6d5c960b6d76d5882
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.2.3+de7003f
  BuildDate: 2019-10-01T20:05:11Z
  GitCommit: de7003f530dbe0a8d49e2572b575a333ac7d803c
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

With $ substition
```
time="2019-10-22T14:53:22Z" level=info msg="connectors:\n- config:\n    [...]    clientSecret: |\n      mySecret\n    hostedDomains:[...]
```

When directly inserted into `argocd-cm`

```
time="2019-10-22T14:58:18Z" level=info msg="connectors:\n- config:\n    [...]    clientSecret: mySecret\n 
```

Notice ` clientSecret: |\n      mySecret\n` and `clientSecret: mySecret\n`

Sidenote: The feature of variable substitution seems a little undermined if the whole config is logged to stdout without masking the substituted fields... Seems like a security issue to me. Should I open another issue for that?

**Comment by jannfis** [comment]
Most likely, you have base64 encoded your client secret using `echo yoursecretdata | base64` when configuring in `argocd-secret`, which added the extra line break. At least, I have seen this mistake often :) If that's the case, can you replace your secret with `echo -n yoursecret | base64` and try again?

Regarding the log, we already have issue #2536 for that (and a fix just came in).

**Comment by jaykay** [comment]
@jannfis `-n` for the win... It was exactly like you pointed out. Thanks
