### ISSUE TITLE
RBAC not supporting team name with space in it

### ISSUE THREAD

**Issue by MrShaddix** [argoproj/argo-cd#2540]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug
**What happened**:
Trying to add a github team with a space in the team, ie, "Team Name"

`apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow

    g, ORG:TEAMNAME, role:org-admin #works!
    g, ORG:Team Name, role:org-admin #does not work`

**What you expected to happen**:
`ORG:Team Name` should have admin access and they do not. I've tried this in many variations (single quotes, double quotes, dashes for spaces, etc)
**How to reproduce it (as minimally and precisely as possible)**:
Attempt to add a github team who's name contains a space
**Anything else we need to know?**:

**Environment**:
- Argo version: v1.1.2
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
Kuberclt version 1.15

**Comment by simster7** [comment]
Hmm I am so far not able to reproduce this. Can you provide me with what actions you are doing that lead to this? Are you running a specific CLI command? What's the error you see/how do you know it's not working?

**Comment by MrShaddix** [comment]
With my github team name set as, "Team Name" I can access ArgoCD but I get a 'permission denied' warning when attempting to sync a repo. This tells me I have the default read-only access.
When I change my github team name to, "TeamName" and do the same sync, the project is synced as expected. So the rbac is working and I have admin rights.

I believe the issue when my Github team name has a space in the name, argocd's rbac does not read it correctly and lumps it into the default (read only) access group. 

The rbac configmap is being updated/applied via our Jenkins worker. I'm querying the configmap to verify that the changes are applied each time. I then logout and log back in via github sso to argocd.

Thanks!

**Comment by MrShaddix** [comment]
Okay, I found the problem, our 'ArgoCD-dex-server' was caching the configmap which prevented us from seeing the changes. This can be closed - thanks!
