### ISSUE TITLE
Unset a Kustomize Override

### ISSUE THREAD

**Issue by stgarf** [argoproj/argo-cd#2546]
Checklist:

* [x] ~I've included steps to reproduce the bug.~
* [x] ~I've pasted the output of `argocd version`.~

**Describe the bug**

There doesn't seem to be a way to remove a Kustomize override via the `argocd` command line.
I've tried various invocations of `argocd app unset`, `argocd app patch`, and `argocd app set` to no avail. See [this thread](https://argoproj.slack.com/archives/CASHNF6MS/p1571709794323600) for the latest in my comical misadventures.

**To Reproduce**

1. Set an override from the command line (or using the UI -- pick your poison).
1. Try to remove the override using the `argocd` command line tool.
1. ...
1. Profit!!1

**Expected behavior**

A clear and easy way to remove the Kustomize override.

```shell
$ argocd app patch $app --patch '[{"op": "remove", "path": "/spec/source/kustomize/images"}]'
$ argocd app set $app --kustomize-image=docker.someplace.net/someplace/node-problem-detector="" 
```

**Version**

```shell
$ argocd version
argocd: v1.2.3+de7003f
  BuildDate: 2019-10-01T20:05:41Z
  GitCommit: de7003f530dbe0a8d49e2572b575a333ac7d803c
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.2.3+de7003f
  BuildDate: 2019-10-01T20:05:11Z
  GitCommit: de7003f530dbe0a8d49e2572b575a333ac7d803c
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Comment by alexec** [comment]
So there's an ugly workaround?

**Comment by stgarf** [comment]
> So there's an ugly workaround?

@alexec Not without using the UI to remove the override from each application, AFAICT :(

**Comment by simster7** [comment]
I can look into this one, @alexec

**Comment by alexec** [comment]
@stgarf it sounds like you've a good understanding of this issue. Would you be interested in working on it? This code change for the CLI would be here:

https://github.com/argoproj/argo-cd/blob/a0f39034182e4a82f53bb5ce684e4e0d45bcb1c8/cmd/argocd/commands/app.go#L740

**Comment by stgarf** [comment]
I'll will try to see what I can do... sorry no promises!

>

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-cd/pull/3289
