### ISSUE TITLE
PostSync Hook not triggered when syncing from UI

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#2547]
With 1.2.2 syncing does not trigger postsync hook. 
when selecting sync button without doing a selective sync it shows in the controller log:
isSelectiveSync=true skipHooks=true
it should be false....
![image](https://user-images.githubusercontent.com/9946020/67404053-11514280-f5b3-11e9-8aa1-bc1801ba1d73.png)

When selecting out-of-sync first then all it seems to work, but this is not expected. It is expected that a default sync should apply a post sync hook. (or am I wrong here?)
![image](https://user-images.githubusercontent.com/9946020/67404116-2a59f380-f5b3-11e9-9ebb-e9ddae4defd3.png)

**Comment by alexec** [comment]
I'll investigate this.

**Comment by alexmt** [comment]
I think it is already fixed: https://github.com/argoproj/argo-cd/commit/1374107bead51467b5b1c1cb3693171a8c6e40f7#diff-21e985d69cd20980449fad47abb28b20 . 

Currently fix is only in 1.3

**Comment by alexec** [comment]
Back port?

**Comment by alexec** [comment]
Also - `TestPostSyncHookSuccessful` is failing on `release-1.2`

**Comment by alexec** [comment]
OK. Backported to v1.2.4.
