### ISSUE TITLE
Helm Chart update available

### ISSUE THREAD

**Issue by estahn** [argoproj/argo-cd#2552]
# Summary

Show a badge or some other visual signal that an app has a newer helm chart available.

# Motivation

We're currently using `helm whatup` ([plugin](https://github.com/bacongobbler/helm-whatup)) to check if charts have newer versions available. Since we're migrating everything to ArgoCD this will be unavailable to us.

The community is constantly improving helm charts and it's hard to stay on top of these changes manually.

# Proposal

Either some badge or another visual signal that a newer version is available.

**Comment by alexec** [comment]
Do you want to show new version in the UI? Or would you like to track patch updates?

**Comment by estahn** [comment]
@alexec That is a great question. My feature request was only for the UI to show something. The current process I follow is:

- disable "auto sync"
- adjust to the new version
- check diff

I'm happy with only the UI change.

**Comment by alexec** [comment]
The Git equivalent would be to have the `targetRevision` be the branch name and we track that. Git Helm equivalent would be to use some kind of version range:

https://helm.sh/docs/chart_best_practices/#versions

If your app was auto-sync you'd automatically upgrade.

Thoughts?

**Comment by alexec** [comment]
Implemente in v1.4.
