### ISSUE TITLE
argocd DeadlineExceeded when adding a new app

### ISSUE THREAD

**Issue by dontreboot** [argoproj/argo-cd#2553]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I was able to successfully add a repo; however, when I tried to add an app, I got the following error:
```
$ argocd repo add git@bitbucket-internal.int.x.com:7999/k8sc/demo.git  --ssh-private-key-path ~/.ssh/id_rsa_argocd --loglevel debug
repository 'git@bitbucket-internal.int.x.com:7999/k8sc/demo.git' added
 $ argocd repo list
REPO                                                                  INSECURE  LFS    USER  STATUS      MESSAGE
git@bitbucket-internal.int.x.com:7999/k8sc/demo.git  false     false  -     Successful
$argocd app create demo   --dest-namespace demo   --dest-server https://kubernetes.default.svc   --repo git@bitbucket-internal.int.x.com:7999/k8sc/demo.git --path "."   --sync-policy automated   --revision test
```

The snippet of logs from argocd-repo-server:
```
time="2019-10-23T22:00:16Z" level=info msg="git fetch origin --tags --force" dir="/tmp/git@bitbucket-internal.int.x.com:7999_k8sc_demo" execID=mYJht
time="2019-10-23T22:01:46Z" level=error msg="`git fetch origin --tags --force` failed timeout after 1m30s" execID=mYJht
time="2019-10-23T22:01:46Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = Failed to fetch git repo: `git fetch origin --tags --force` failed timeout after 1m30s" grpc.code=Internal grpc.method=ListDir grpc.request.deadline="2019-10-23T22:01:16Z" grpc.service=repository.RepoServerService grpc.start_time="2019-10-23T22:00:16Z" grpc.time_ms=90082.28 span.kind=server system=grpc
```

I was able to manually run `git clone` from argocd-repo-server container without issues:
```
$ date; git clone ssh://git@bitbucket/k8sc/demo.git; date
Thu Oct 24 01:11:03 UTC 2019
Cloning into 'demo'...
Warning: Permanently added the RSA host key for IP address '[10.180.51.143]:7999' to the list of known hosts.
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 21 (delta 5), reused 0 (delta 0)
Receiving objects: 100% (21/21), done.
Resolving deltas: 100% (5/5), done.
Thu Oct 24 01:11:05 UTC 2019
$ hostname
argocd-repo-server-5599d9bbd6-psbxx
```

**To Reproduce**

n/a this may be specific to my environment

**Expected behavior**

able to add app for existing repos

**Screenshots**

**Version**

```shell
argocd: v1.2.1+a6a394b
  BuildDate: 2019-09-12T17:16:32Z
  GitCommit: a6a394ba93a2a56981a45b9395e245e5210eaa35
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.2.4+ad7a69a
  BuildDate: 2019-10-23T20:06:50Z
  GitCommit: ad7a69a79883b7767cbeb88ca9a36d28277bd4ab
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Comment by dontreboot** [comment]
This is the manifest I used to deploy argocd
[manifest.txt](https://github.com/argoproj/argo-cd/files/3765228/manifest.txt)

**Comment by alexec** [comment]
You're app timeout after 90s when trying to fetch from Git. This maybe a temporary, but if not, it suggest that either (a) you have a slow Git provider or more likely (b) a large repository in Git. 

Can you please confirm the size of your repository?

You can also try setting `ARGOCD_EXEC_TIMEOUT` on the repo server's deployment. E.g. `ARGOCD_EXEC_TIMEOUT=3m`

Alex

**Comment by dontreboot** [comment]
> You're app timeout after 90s when trying to fetch from Git. This maybe a temporary, but if not, it suggest that either (a) you have a slow Git provider or more likely (b) a large repository in Git.
> 
> Can you please confirm the size of your repository?

It's about 100k. When I manually ran `git clone` from the repo-server container, it finished within seconds
```
argocd@argocd-repo-server-5cd9587478-tv2lr:~$ date; git clone ssh://git@bitbucket-internal.int.x.com:7999/k8sc/demo.git; date
Fri Oct 25 21:50:35 UTC 2019
Cloning into 'demo'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 21 (delta 5), reused 0 (delta 0)
Receiving objects: 100% (21/21), done.
Resolving deltas: 100% (5/5), done.
Fri Oct 25 21:50:35 UTC 2019
argocd@argocd-repo-server-5cd9587478-tv2lr:~$ du -sh demo
100K	demo
argocd@argocd-repo-server-5cd9587478-tv2lr:~$ ls demo/
echoserver.yaml
```
> 
> You can also try setting `ARGOCD_EXEC_TIMEOUT` on the repo server's deployment. E.g. `ARGOCD_EXEC_TIMEOUT=3m`
> 

I just tried the 3m timeout. It still failed which was expected as it's not a slow bitbucket repo. btw, how do I re-produce the problem that repo-server is seeing with `git`.


> Alex

**Comment by dontreboot** [comment]
It is weird that manual run of `git clone` inside the repo server container works fine

**Comment by alexec** [comment]
can you please run `git fetch origin --tags --force` in `/tmp/git@bitbucket-internal.int.x.com:7999_k8sc_demo`?

**Comment by dontreboot** [comment]
I know what the problem is now. my repo in argocd is `git@bitbucket-internal.int.x.com:7999/k8sc/demo.git` and that's not right. It should've been `ssh://git@bitbucket-internal.int.x.com:7999/k8sc/demo.git`. Without the`ssh://` part in front of the repo url, git thinks `7999` is  part of the path not the port override.

Btw, what does argocd check before showing "Successful" status for a repo? I wonder why when my repo was added, it was showing "Successful" status even though it probably couldn't pull it from the repo.

**Comment by jannfis** [comment]
Hm, probably a discrepancy in URL parsing between `argocd-server` and `argocd-repo-server`, this is a bug. Thank you for letting us know, @dontreboot !

I will open an issue for that and fix it.

**Comment by jannfis** [comment]
Issue: #2576 
Can this bug be closed then?

**Comment by dontreboot** [comment]
> Issue: #2576
> Can this bug be closed then?

Thanks for looking into the issue!
