### ISSUE TITLE
Add a wait function on deletion

### ISSUE THREAD

**Issue by JGroselle** [argoproj/argo-cd#2555]
# Summary

When we delete an application, we need a way to wait for this application's resources to be deleted.
`argocd app wait <app>` and `argocd app wait <app> --operation` do not check the box.

# Motivation

During application deletion, it often takes some time to delete all the kubernetes resources managed by it.
It could be very useful to add a wait function to wait for deletion.

# Proposal

- Add`argocd app delete --wait <app>`
- Add `argocd app wait --delete <app>`
- Add in `argocd app wait <app>`
- Add in `argocd app wait <app> --operation`

**Comment by alexec** [comment]
Good on for community contribution.

**Comment by adamjohnson01** [comment]
I am happy work on this.

**Comment by yidongw** [comment]
Is it done?

**Comment by phoenix-bjoern** [comment]
@adamjohnson01 and @pasha-codefresh developed code for this feature but it seems their PRs never have been merged.
Any chance to finish the work to release the feature?

**Comment by phoenix-bjoern** [comment]
While `argocd app wait` doesn't wait for app removal simply check the list of apps. As a workaround you can use this line bash command:

```until ! $(argocd app list -N ${APP_NAMESPACE} -o name | grep -qx ${APP}); do echo "ArgoCD Application still exists..."; sleep 5; done```

**Comment by omerap12** [comment]
Hey, Is this issue still open for contributions? @alexec @blakepettersson

**Comment by pasha-codefresh** [comment]
Hey @omerap12 , feel free to contribute it

**Comment by colbymelvin** [comment]
Isn't this resolved by https://github.com/argoproj/argo-cd/pull/16733 ?

**Comment by phoenix-bjoern** [comment]
Works for me: `argocd app wait --delete` exits when the app is removed in ArgoCD. Thanks @MichaelMorrisEst !
IMHO the ticket can be closed.
