### ISSUE TITLE
Add the ability to deploy many time the same application

### ISSUE THREAD

**Issue by JGroselle** [argoproj/argo-cd#2556]
# Summary

The application name is cluster-wide. and not related to a project.
So if we want to deploy two times the same application, we cannot.

# Motivation

If projects are linked to environments (development, staging, etc.) we should be able to deploy app01 in each project. But with the actual configuration, it is impossible.
Application URL is like `argocd.example.com/applications/app01`

# Proposal

Application URL could be `argocd.example.com/project01/app01`
Where `project01` is the project name.

**Comment by JGroselle** [comment]
Today as a workaround we prefix application name by project name.

**Comment by alexec** [comment]
Dup of #1673?

**Comment by JGroselle** [comment]
@alexec yes, regarding this answer https://github.com/argoproj/argo-cd/issues/1673#issuecomment-529666940 it is a duplicate.
The title confused me, sorry for that.

**Comment by alexec** [comment]
Closed as dup.
