### ISSUE TITLE
Sync wave documentation should mention native object ordering

### ISSUE THREAD

**Issue by mark-rushakoff** [argoproj/argo-cd#2566]
[Over in Argo Slack](https://argoproj.slack.com/archives/CASHNF6MS/p1572028896013400), I asked about typical usage in sync waves -- do people generally put everything related to one resource in the same wave, or do they use fine-grained individual waves for config maps, services, and so on?

Jesse helpfully explained that Argo already handles native object ordering. I suppose that was obvious in hindsight but it didn't occur to me before I anticipated that I had to set a sync wave on every single resource in my application.

The sync wave documentation should elaborate on the use case more, to clarify that you would typically only need to set waves for deployments, stateful sets, and so on.

**Comment by alexec** [comment]
@mark-rushakoff - fancy making the change? You can use this URL to edit the page:

https://github.com/argoproj/argo-cd/edit/master/docs/user-guide/sync-waves.md

**Comment by christianh814** [comment]
Doesn't this section explain it? https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/#how-does-it-work

IMHO, I believe the doc does a good job at explaining this currently.

**Comment by christianh814** [comment]
Closing this since [the docs explains ordering](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/#how-does-it-work).
