### ISSUE TITLE
Integrate OpenShift OAuth Server for Argo CD SSO

### ISSUE THREAD

**Issue by disposab1e** [argoproj/argo-cd#2574]
# Summary

Make it possible to host ArgoCD on OpenShift 4.2 and use the OpenShift OAuth server for Argo CD authentication. As far as I can see dex does nor provide this possibility.

# Motivation

Running Argo CD and authenticate against the OpenShift internal OAuth server will give a more streamlined user experience.

**Comment by tylerauerbeck** [comment]
Looks like this is linked in the other issues, but not here. 

https://blog.openshift.com/openshift-authentication-integration-with-argocd/

**Comment by disposab1e** [comment]
@tylerauerbeck thx!! Already availbale [here](https://github.com/disposab1e/argocd-operator-helm)

**Comment by alexmt** [comment]
Bundled dex has been upgraded. Now default Argo CD installation supports Openshift SSO integration.
