### ISSUE TITLE
UI incorrectly mark resources as `Required Pruning`

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#2577]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

There are two cases when UI incorrectly mark resources as `requires pruning`:
- if repo server goes down after app is deployed then all live objects marked as `requires pruning`
- if resource requires pruning but annotated with `sync-options: Prune=false`. 

**To Reproduce**

1. Deploy and app
2. Stop repo server
3. See all resources marked as `requires pruning`.

**Expected behavior**

**Screenshots**

**Version**

```shell
1.3.0-rc1
```

**Comment by alexec** [comment]
I'm not 100% sure about the second one. The annotation specifically refers to what should happen during sync. Not what should happen during comparison. 

Solution is to add `resource.HasAnnotationOption(liveObj, common.AnnotationSyncOptions, "Prune=false")` at line 412 in `state.go` (that func should probably be extracted to at `resource.Prune(..)` func.
