### ISSUE TITLE
Color or shape code for  K8s object types

### ISSUE THREAD

**Issue by Tazminia** [argoproj/argo-cd#2583]
# Summary

When viewing a deployed application, many objects have different types and yet the same icons:

- endpoints, persistent volume claims, statefulset, ingress and replicasets
- deployments, services

This makes it harder to see elements unless you use the filtering options to view only some type of object (pods or services for example)

# Motivation

When viewing deployments of applications with many kubernetes objects, the graph would be more readable if we have different shapes or colors for each kubernetes object type.

# Proposal

I think we should have either of the following for each different object type:

- Different shapes
- Different colors
- Different icons

**Comment by Tazminia** [comment]
I am running v1.2.3 that I installed a few weaks ago using as explained [here](https://github.com/argoproj/argo-cd/blob/master/docs/getting_started.md)
```
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
```

If I understand [#2349](https://github.com/argoproj/argo-cd/pull/2349) was included in v1.3, so I should try to upgrade argocd

**Comment by alexec** [comment]
Hi @Tazminia this is available in v1.3.

**Comment by Tazminia** [comment]
@alexec is there a recommended way to upgrade to a newer version ? is there any documentation on the upgrade procedure ?

**Comment by alexec** [comment]
v1.3 is not GA yet, so if you're running in a production system, then you should wait until it is.

**Comment by alexec** [comment]
Can I close this please?

**Comment by Tazminia** [comment]
Yes of course.
