### ISSUE TITLE
Argo CD in the DigitalOcean Marketplace

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#2585]
# Summary

Put Argo CD into the Digital Ocean marketplace.

# Motivation

> Hey Alex, 
> 
> A lot of developers have been requesting an Argo CD solution stack since we just recently released Kubernetes integration into the DigitalOcean Marketplace, we would love to get ArgoCD listed.  To give you an idea, we've made it super easy to submit with these two steps:
> GitHub Pull Request here: https://github.com/digitalocean/marketplace-kubernetes
> Solution Submission Form here: https://forms.gle/KxvFjoqi3ZQWCUUf6
> It would be great to catch up and answer any questions you may have. Please put some time that is convenient for you here: REDACTED
> 
> Best,
> Danny

# Proposal

See above.

**Comment by alexmt** [comment]
Argo CD is on marketplace https://marketplace.digitalocean.com/apps/argo-cd
