### ISSUE TITLE
Remove transitive dependency on packr

### ISSUE THREAD

**Issue by moensch** [argoproj/argo-cd#2592]
Checklist:

As discussed here: https://argoproj.slack.com/archives/CASHNF6MS/p1572407437084900?thread_ts=1556732320.124600&cid=CASHNF6MS

**Describe the bug**

The current use of `packr` makes it a transitive dependency for anyone trying to develop against `github.com/argoproj/argo-cd/pkg/apiclient` directly

**To Reproduce**

1. Make a program importing `github.com/argoproj/argo-cd/pkg/apiclient`

2. Run `dep ensure`

3. Compile and run your program

Returns error:
```
panic: stat _vendor_path_/github.com/argoproj/argo-cd/assets/builtin-policy.csv: no such file or directory

goroutine 1 [running]:
github.com/sendgrid/argocd-helper/vendor/github.com/argoproj/argo-cd/util/assets.init.0()
	/Users/ssuter/go/src/github.com/sendgrid/argocd-helper/vendor/github.com/argoproj/argo-cd/util/assets/assets.go:19 +0x2de
```

**Expected behavior**

The program should succeed

**Screenshots**

n/a

**Version**

`1.2.5`

```shell
Paste the output from `argocd version` here.
```

**Comment by alexmt** [comment]
Working on it
