### ISSUE TITLE
UI application tiles should reflect corresponding app health status when presync hooks are running

### ISSUE THREAD

**Issue by oboukili** [argoproj/argo-cd#2596]
Checklist:

* [*] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**

When a presync hook is running, the applications overview tiles does not reflect the "progressing" application state (tile color + status attribute)

Upon synchronization, an application may have one or several argocd presync hooks. Whereas entering the application tab (/applications/someapp endpoint) displays the "progressing" status correctly when a presync hook is running, the applications overview tiles however (/applications) only show the progressing state (blue color + status attribute) when a non-hook application managed resource is synchronizing. When you have long presync hooks (data model training for instance), you can be led into thinking that nothing is happening, this can be confusing.

**To Reproduce**

Declare a long or neverending presync hook (sleep 3600 pod for example). Initiate an application synchronization, notice the applications overview panel does not reflect the "progressing" status, whereas the application tab does.

**Expected behavior**

When a presync hook is running, the applications overview tiles should reflect the "progressing" application state (tile color + status attribute)

**Version**

```shell
argocd: v1.3.0+73590e1
  BuildDate: 2019-10-27T09:21:03Z
  GitCommit: 73590e1a3982501865577c2a2c9ec8794391b813
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
```

**Comment by alexec** [comment]
Can repro by running `TestPreSyncHookSuccessful`.

**Comment by alexec** [comment]
App health is calculated by:

https://github.com/argoproj/argo-cd/blob/master/util/health/health.go#L32-L52

If there are resources that have yet to be applied, then they are missing and this bubbles up into the app's overall health.

**Comment by alexmt** [comment]
I think this is UI only issue. I'm pretty sure sync operation status should not influece app health status. For example if app is already in sync the syncing process is no-op. In this case it would be wrong to change status to progressing and then back to healthy/degraded. 

Instead of making backend changes I would change applications-table.tsx and applications-tiles.tsx. Right now these two pages choose color based on health and sync status. We need ti take into account operation status as well.

**Comment by alexec** [comment]
After discussion:

- Hooks should not affect app health.
- Operation state should appear in the apps tile and table views. See PR.

**Comment by oboukili** [comment]
Thank you very much!
