### ISSUE TITLE
Upgrade kustomize from v3.1.0 to v3.2.1

### ISSUE THREAD

**Issue by hongymagic** [argoproj/argo-cd#2609]
# Summary

Current installed version of `kustomize` in `argocd-repo-server` is version 3.1.0. This proposal is to upgrade it to version 3.2.1.

# Motivation

From reading changelogs and commits, there does not seem to be any breaking changes between the 2. And there has been significant bug fixes since version 3.1.0:

- [v3.1.0..v3.2.0][1]
- [v3.2.0..v3.2.1][2]

# Proposal

My hope is that it is as simple as upgrading the `KUSTOMISE_VERSION` in `hack/installers/install-kustomize-linux.sh`.

Any tests, integrations tests that break as a result of this should be fixed.

IF any additional tests are required, should be tested. But AFAIK, this should be a maintainence release.

[1]: https://github.com/kubernetes-sigs/kustomize/compare/v3.1.0...v3.2.0
[2]: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.2.1

**Comment by hongymagic** [comment]
This upgrade fixes a particular bug I am dealing with, where kustomize patches, namesaces and overrides are causing this particular bug using v3.1.0 but all good in v3.2.0+ (have not tested in v3.3.0):

```
Error: merging from generator &{0xc0000b2ba0 0xc00057dfa0 { } {map[] map[] false} {{argocd argocd-cm merge {[kustomize.buildOptions=--reorder legacy] [argocd/repositories] [] }}}}: id resid.ResId{Gvk:gvk.Gvk{Group:"", Version:"v1", Kind:"ConfigMap"}, Name:"argocd-cm", Namespace:"argocd"} does not exist; cannot merge or replace
```

**Comment by hongymagic** [comment]
Friendly ping @jessesuen ! I've read through the change logs and it seems okay, I've not had any issues with 3.2.0 thus far. I have compiling projects like `kube-prometheus`, `metallb` (and `argocd`) using 3.2.0 and complex base hierarchies. This bug is stopping me from deploying ArgoCD to our cluster at the moment so if you could take a look that would great.

What is the release process for ArgoCD? I'm happy to point to master temporarily, but would like to use a tag if possible in our clusters.

**Comment by jessesuen** [comment]
>  This bug is stopping me from deploying ArgoCD to our cluster at the moment so if you could take a look that would great.

FYI, you can always override the kustomize version with a volume mount. It's intended for users to be able to pick their own toolchain. I cherry picked this into v1.3 branch which we will be releasing soon.
