### ISSUE TITLE
Unable to add a private Google Source Repository with SSH

### ISSUE THREAD

**Issue by imranzunzani** [argoproj/argo-cd#2611]
The approach to add a private GSR is not working while following these steps

1) Generate an SSH key pair
2) Register the public key in the GSR repo
3) Add the private key to the argocd using the following command:

`argocd repo add '<gmail id without @gmail.com suffix>@source.developers.google.com:2022/p/<project_id>/r/<repo_name>' --ssh-private-key-path "~/.ssh/id_rsa" --insecure-ignore-host-key`

Error:
`FATA[0000] rpc error: code = Unknown desc = ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

server version - v1.2.4
cli version - v1.2.5

**Comment by jannfis** [comment]
Have you tested the access manually, i.e. using `ssh yourid@source.developers.google.com -p 2022`? The error message usually indicates that the server didn't accept your public key for the account you specified (or the account doesn't exist).

I'm not familiar with GSR, but their documentation states you should use the full mail address (i.e. `yourname@gmail.com`) and not just the local part as username.

**Comment by imranzunzani** [comment]
The full mail address doesn't work with the `argocd repo add` command.

`FATA[0000] rpc error: code = Unknown desc = dial tcp: lookup gmail.com@source.developers.google.com: no such host`

Is there an 'escape sequence' to be used here?

**Comment by jannfis** [comment]
Oops. I guess then we hit a real bug here. Probably we don't support usernames with an `@` in it right now, because everything after the first `@` in the URL is interpreted as hostname.

You could try to use URL encoding for the username (i.e. use `%40` instead of `@` and see whether that works). Since I'm about to work on SSH URL parsing anyway for #2576 I might take a look at this as well.

**Comment by imranzunzani** [comment]
@jannfis,
Would you be assigning this bug to you then, as part of #2576?
