### ISSUE TITLE
Add a Get Repo command to see if Argo CD has a repo

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-cd#2618]
# Summary
Argo CD should have a Get Repo API endpoint that allows a user to specify a repo that they are interested in and have Argo CD return information on that repo.

# Motivation

In order to build automation on top of Argo CD, external systems need to know if a specific repo exists in Argo CD. As a workaround, for now, an external system can run the list command, but that system has to process the list to see if a specific repo exists.

# Proposal

How do you think this should be implemented?

A get endpoint should be added to the https://github.com/argoproj/argo-cd/blob/master/server/repository/repository.proto similar to https://github.com/argoproj/argo-cd/blob/master/server/application/application.proto#L221-L224 and then implemented in https://github.com/argoproj/argo-cd/blob/master/server/repository/repository.go

**Comment by jannfis** [comment]
What do you think should be outputted by `repo get` command when the repository does not have credentials configured but uses a repository template? Just a hint on the credentials template (i.e. "uses credentials from `url`" or should it resolve the values from the template?

**Comment by samkeet** [comment]
@jannfis Given that the application spec has `repoURL` in the `get application` output, it will be useful to have a reverse mapping of `repo` -> `list of applications`

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-cd/pull/3523
