### ISSUE TITLE
Repository type should be mandatory for repo add command in CLI

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#2622]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

With v1.3 first-class support of Helm, each repository has a `type` nominator to specify whether it's a Git or a Helm repo. The `repo add` command of the CLI has a corresponding switch, but this switch is not mandatory and not specifying the type has weird side-effects (i.e. assuming Helm repository for SSH URLs, which are not supported).

**To Reproduce**

Helm assumes HTTPS URL:

```bash
$ argocd repo add root@127.0.0.1:2222/app/git/repos/test --ssh-private-key-path test/fixture/testrepos/id_rsa --insecure-ignore-host-key
FATA[0000] rpc error: code = Unknown desc = parse root@127.0.0.1:2222/app/git/repos/test: first path segment in URL cannot contain colon 
```
Helm does not support explicit `ssh` protocol:
```bash
$ argocd repo add ssh://root@127.0.0.1:2222/app/git/repos/test --ssh-private-key-path test/fixture/testrepos/id_rsa --insecure-ignore-host-key
FATA[0000] rpc error: code = Unknown desc = Get ssh://root@127.0.0.1:2222/app/git/repos/test/index.yaml: unsupported protocol scheme "ssh" 
```
However, neither Git nor Helm is the dedicated default:
```bash
$ argocd repo add | grep -- --type
      --type string                         type of the repository, "git" or "helm"
```

**Expected behavior**

Either the `--type` switch for `repo add` should be mandatory, or the default should be noted in the usage. If defaulting, the default should be `git` for backwards compatibility. If mandatory, maybe it should be a prepended argument instead of a switch, i.e. `argocd add repo <type> <url>` - this is open for discussion.

**Screenshots**

**Version**

```shell
argocd: v1.3.0+a0d758a.dirty
  BuildDate: 2019-10-31T20:57:15Z
  GitCommit: a0d758a571e6de819119b4e97bd42f0722d63bc3
  GitTreeState: dirty
  GoVersion: go1.12.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexec** [comment]
It should probably be backwards compatible - so default to `git`
