### ISSUE TITLE
unable to connect private gitlab to the argocd

### ISSUE THREAD

**Issue by daparthi001** [argoproj/argo-cd#2640]
argocd repo add <reponame> --username gitlab-deploy--password <>
FATA[0000] rpc error: code = Unknown desc = unexpected client error: unexpected requesting "https://<gitlab-url>/info/refs?service=git-upload-pack" status code: 301

**Comment by Havilland** [comment]
I ran into the same problem.

ArgoCD Version is v1.4.2+48cced9

What I tried to do:
Connect a private GitLab Repository using a deploy token in the web ui.

ArgoCD gives the same Error as described by @daparthi001 . I tried to access the link and a Authentication window popped up. It seems that ArgoCD isn't able to process a 301 response.

Here is the corresponding line from the logs:
time="2020-03-02T15:01:34Z" level=error msg="finished unary call with code Unknown" error="unexpected client error: unexpected requesting \"https://xxx/xxx/xxx-argocd/info/refs?service=git-upload-pack\" status code: 301" grpc.code=Unknown grpc.method=Create grpc.service=repository.RepositoryService grpc.start_time="2020-03-02T15:01:34Z" grpc.time_ms=27.441 span.kind=server system=grpc

**Comment by jannfis** [comment]
Hi, I think I've noticed that with Gitlab, you have to append the `.git` suffix to your repository URLs, otherwise Gitlab will send you the 301 redirect you are seeing.

Also, I think ArgoCD is correct in not following the redirect for various reasons, mainly security. Can you try appending `.git` to your repository, so instead of `https://gitlab.example.com/your/repo`, use `https://gitlab.example.com/your/repo.git`?

**Comment by Sicaine** [comment]
I had the same issue right now after upgrading from argocd 1.0 to 1.4 using gitlab and not the .git url.

Not sure if i would have found this issue as quickly as i did without this github issue :-)

**Comment by borzozoo** [comment]
I added .git but still not working for me.  what you see below is from the  pod when I click on connect:

time="2020-10-19T21:04:11Z" level=error msg="finished unary call with code Unknown" error="unexpe
ent error: unexpected requesting \"https://git.blah.blahhhhh/uip-devops.git/info/refs?se
t-upload-pack\" status code: 400" grpc.code=Unknown grpc.method=Create grpc.service=repository.Re
Service grpc.start_time="2020-10-19T21:04:11Z" grpc.time_ms=34.003 span.kind=server system=grpc

**Comment by gajus** [comment]
Adding `.git` fixed the issue. Would be really nice get a user-friendlier error for this.

**Comment by tuananh** [comment]
a nicer error message would be much appreciated :)

**Comment by adamzhoul** [comment]
what if we add a format check before passing to GitLab?

**Comment by pixelsoccupied** [comment]
Also ran into "status code: 301"...but In my case it worked after updating to `https` (it was "http") in `.spec.source.repoURL`

**Comment by Gulnur-Altan** [comment]
I've  had the same err for reconnect to ArgoCD ,but nobody mentioned about "saving credentials as a template" ,saved it and it works
