### ISSUE TITLE
Documentation about best practices

### ISSUE THREAD

**Issue by eugenekurasov** [argoproj/argo-cd#2648]
# Summary
Hi, I think need improve best practices, because after read I have a more question than in beginning.
https://argoproj.github.io/argo-cd/user-guide/best_practices/

# Motivation
You are recommend separate code repository and configs. But this will be created more difficult steps. 
You will be have cross-project dependency.

* `For example, you likely do not want to trigger a build if you simply wish to bump the number of replicas in a Deployment spec. ` - Change of count of replicas can down all system. Only code owner have knowledge about how many replicas are available to be run.
And if you will be have few repositories with with different code owners they should be have access to "shared repository" with all configs.  But 4 paragraph say it's shpuld be two different roles. 
* `Separation of access. The developers who are developing the application, may not necessarily be the same people who can/should push to production environments, either intentionally or unintentionally ` - I agree that should be different roles, but is can be same people. `Separation of access` -  you should have information about code base for prepare manifest for deploy. Or part of manifest it's should be with code base?

# Proposal

I proposal separate best practices for monorepo, multi-repos, etc.

Thanks.

**Comment by alexec** [comment]
What about this draft? https://blog.argoproj.io/5-gitops-best-practices-d95cb0cbe9ff

**Comment by eugenekurasov** [comment]
Hi, @alexec your article its better :+1: 

You tell for separate code base and manifest, so you should have role like "release" manager. 
But why it's should be one person? Why you can't do release on git tags? You can limit rules for create tags for some person who have knowledge of code base and infrastructure. And you can release and update with *one* commit, without cross dependency project. 

I just think that approaches can be different and sometimes it’s not worth sharing responsibility?

I am agree if you have few projects with some dependency on each other, and then be more easy create new repository for control by release. But knowledge how many resources needed and rules scales should be more closer to code. If your repository its application, to application its code + manifests

Thanks.

**Comment by alexec** [comment]
No problem.
