### ISSUE TITLE
Support for the custom health checks for the new cert-manager API

### ISSUE THREAD

**Issue by binoue** [argoproj/argo-cd#2667]
# Summary

Argocd has custom health checks for Issuer and Certificate resource of cert-manager.
Starting with cert-manager v0.11.0, the API group and version of these CRDs are changed as shown [here](https://github.com/jetstack/cert-manager/releases).
Therefore, it would be nice to have custom health checks for the new cert-manager API.

# Motivation

To behave in the same way for cert-manager v0.11.0 or higher.

# Proposal

Create cert-manager.io directory in resource_customizations, copy the contents of cert-manager.k8s.io directory, then fix apiVersion.

**Comment by jannfis** [comment]
Sounds legit. Do you want to submit a PR?

**Comment by binoue** [comment]
> Sounds legit. Do you want to submit a PR?

Thank you for your suggestion! Yes, I want to submit a PR.
I will make a PR soon.

**Comment by dnascimento** [comment]
@binoue  👍 could you also share how are you installing cert-manager using Argo? I'm having issues

**Comment by binoue** [comment]
@dnascimento 

> @binoue 👍 could you also share how are you installing cert-manager using Argo? I'm having issues

No problem! If you give me more detail about your issue, I may help you more.
Our way of installing cert-manager by using ArgoCD is in [this repository](https://github.com/cybozu-go/neco-apps)
