### ISSUE TITLE
CLI - Can not delete a specified context

### ISSUE THREAD

**Issue by masa213f** [argoproj/argo-cd#2668]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Cannot delete the context specified in the command-line option.

```shell
# 2 contexts exists.
$ argocd context
CURRENT  NAME                        SERVER
*        argocd.hoge.example.com     argocd.hoge.example.com
         argocd.piyo.example.com     argocd.piyo.example.com

# Try to delete a context.
$ argocd context argocd.piyo.example.com --delete
Switched to context 'argocd.piyo.example.com'

# Cannot delete just switch.
$ argocd context
CURRENT  NAME                        SERVER
         argocd.hoge.example.com     argocd.hoge.example.com
*        argocd.piyo.example.com     argocd.piyo.example.com
```

**Expected behavior**

Delete the specified context. Because the help says as below:

```shell
$ argocd context -h
...
Flags:
      --delete   Delete the context instead of switching to it
```

**Version**

```shell
$ argocd version
argocd: v1.2.5+d8eb382.dirty
  BuildDate: 2019-11-08T09:08:37Z
  GitCommit: d8eb382e6ede3be94f3cfb6b4d46e03e28b1c4e3
  GitTreeState: dirty
  GoVersion: go1.13.3
  Compiler: gc
  Platform: windows/amd64
```

**Comment by jannfis** [comment]
I have looked at the code and this seems to be a long-standing bug that happened during refactoring of CLI to use Cobra CLI library. Should be easily fixable by replacing `deletePresentContext` with `delete` at https://github.com/argoproj/argo-cd/blob/0ff2533ba0cce0c6cdec323e1a5b323c4e310cc6/cmd/argocd/commands/context.go#L41 and then remove the old code blob starting at https://github.com/argoproj/argo-cd/blob/0ff2533ba0cce0c6cdec323e1a5b323c4e310cc6/cmd/argocd/commands/context.go#L33

Are you in for a PR?

**Comment by oke-py** [comment]
`argocd context --delete` only works when `len(args) == 0`.
https://github.com/argoproj/argo-cd/blob/0ff2533ba0cce0c6cdec323e1a5b323c4e310cc6/cmd/argocd/commands/context.go#L40

It works fine as below.
```
$ cat ~/.argocd/config
contexts:
- name: argocd.example.com:443
  server: argocd.example.com:443
  user: argocd.example.com:443
- name: localhost:8080
  server: localhost:8080
  user: localhost:8080
current-context: localhost:8080
servers:
- server: argocd.example.com:443
- plain-text: true
  server: localhost:8080
users:
- auth-token: vErrYS3c3tReFRe$hToken
  name: argocd.example.com:443
  refresh-token: vErrYS3c3tReFRe$hToken
- auth-token: vErrYS3c3tReFRe$hToken
  name: localhost:8080

$ argocd context
CURRENT  NAME                    SERVER
         argocd.example.com:443  argocd.example.com:443
*        localhost:8080          localhost:8080

$ argocd context --delete
Context 'localhost:8080' deleted

$ argocd context
CURRENT  NAME                    SERVER
*        argocd.example.com:443  argocd.example.com:443
```

It should delete current context even if some arguments are given?
Whether or not, it may need refactoring.

**Comment by masa213f** [comment]
@jannfis @oke-py 
Thank you for your replay.

I fixed it. https://github.com/argoproj/argo-cd/pull/2669
Please check the behavior.
