### ISSUE TITLE
From scratch / distroless containers

### ISSUE THREAD

**Issue by bencompton** [argoproj/argo-cd#2676]
# Summary

Use a distroless container instead of Debian Slim as the base container for Argo CD. Not sure if Argo CD is 100% statically compiled and if ‘FROM scratch’ would be an option, but if not, Google’s [distroless containers](https://github.com/GoogleContainerTools/distroless) is the next best thing.

# Motivation

The reduced attack surface would be great—especially for people exposing Argo CD publicly. Argo CD is typically quite privileged within a cluster, so the consequences of a successful attack would be dire. While not having a package manager or shell is inconvenient for troubleshooting, it would be equally inconvenient for hackers. ;)

# Proposal

Use ‘FROM scratch’ or a Google [distroless container](https://github.com/GoogleContainerTools/distroless) as ‘argocd-base’ instead of ‘debian-slim’.

**Comment by jannfis** [comment]
We have thought about that in the past, but ArgoCD has to support the use of custom plugins and tooling and therefore most likely require a more-or-less complete Linux runtime in its containers.

Please refer to discussions in https://github.com/argoproj/argo-cd/issues/2425

**Comment by bencompton** [comment]
One idea to consider would be having both distroless and debian-slim options. People who want the minimal attack surface could use the distroless option, and those requiring more custom plug-ins could use the debian-slim option.  The distroless containers are also based on Debian, but it’s possible there could be other issues outside of custom plugin use.

**Comment by alexec** [comment]
I believe you should be able to build you’re own distroless containers if you need them, but bear in mind that most of the tools installed will require some kind of base (Helm. Kustomize, Git, Untar etc)

**Comment by bencompton** [comment]
Without Git, Helm, etc., Argo CD is not very useful, so it doesn’t appear that a distroless base will be a viable option for the most part. Thanks for the feedback! I’ll go ahead and close this issue.
