### ISSUE TITLE
Sending HTTP request using PATCH verb to REST API results in connection reset

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#2677]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Sending a HTTP request using the PATCH verb, the connection gets closed unexpected by the API server without any trace why.

**To Reproduce**

You can use curl to reproduce, below example is against local `argocd-server` listening on port 8081 in insecure mode:

```shell
$ curl -d '{}' -v -XPATCH http://127.0.0.1:8081/api/v1/session
*   Trying 127.0.0.1:8081...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> PATCH /api/v1/session HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/7.65.3
> Accept: */*
> Content-Length: 2
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 2 out of 2 bytes
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

```

**Expected behavior**

Server should send back appropriate error message, such as `HTTP 405 - Method not allowed` or even better `HTTP 501 - Not implemented` if we don't support `PATCH` verb at all.

**Version**
Build from latest master:

```shell
argocd-server: v1.3.0+ac6413c.dirty
  BuildDate: 2019-11-09T12:16:35Z
  GitCommit: ac6413c63668a8850605c06f235e473e907303f7
  GitTreeState: dirty
  GoVersion: go1.12.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: vdev-2019-05-15T19:48:06+0200
  Kustomize Version: Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T18:11:16Z GoOs:linux GoArch:amd64}
  Helm Version: v2.13.1
  Kubectl Version: v1.15.2

```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jannfis** [comment]
After a little more research, this happens to any verbs apparently unknown to `argocd-server`, so if I use arbitrary ones:
```
$ curl -v -XPAQ http://127.0.0.1:8081/api/version
*   Trying 127.0.0.1:8081...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> PAQ /api/version HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

$ curl -v -XMYVERB http://127.0.0.1:8081/api/version
*   Trying 127.0.0.1:8081...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> MYVERB /api/version HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```
Appropriate response from a "good" HTTP server:
```
$ curl -v -XMYVERB http://www.google.com
*   Trying 172.217.18.4:80...
* TCP_NODELAY set
* Connected to www.google.com (172.217.18.4) port 80 (#0)
> MYVERB / HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 405 Method Not Allowed
< Content-Type: text/html; charset=UTF-8
< Referrer-Policy: no-referrer
< Content-Length: 1591
< Date: Sun, 10 Nov 2019 18:01:42 GMT
```

**Comment by sledigabel** [comment]
had the same issue.
```
curl --request PATCH -L -k ${URL}/api/v1/applications/myappdemo-main2 -H "Authorization: Bearer $TOKEN" --data '{ "name": "myappdemo-main2", "patchType": "merge", "patch": { "spec": { "source": { "targetRevision": "master" } } } }' -v -H "Content-Type: application/json"
*   Trying 192.168.64.131...
* TCP_NODELAY set
* Connected to 192.168.64.131 (192.168.64.131) port 31763 (#0)
> PATCH /api/v1/applications/myappdemo-main2 HTTP/1.1
> Host: 192.168.64.131:31763
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3N2NkMGMwMC0wNjRlLTQ3ZWMtODYzZS03NGFiY2JkNTBkMGQiLCJpYXQiOjE1OTY0OTEwNjMsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTU5NjQ5MTA2Mywic3ViIjoiYWRtaW4ifQ.weaiue66vmEaTWIprSNBTriO01Qsc9VOMBzoVoDs8Dc
> Content-Type: application/json
> Content-Length: 118
>
* upload completely sent off: 118 out of 118 bytes
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

Swagger seems to document the PATCH verb for "Patch an application"
https://localhost:8080/swagger-ui#operation/Patch

**Comment by echoboomer** [comment]
This is still a problem and is stopping development of some internal processes that rely on the usability of the ArgoCD API. Are there any updates on this at all?

**Comment by Conrimaceogain** [comment]
Hi all, has anyone had a chance to take a look at this? I'm running into this issue myself and the workaround @Kyle-sandeman-mrdfood mentions works for our non-HA deploy of Argo CD, but not for our HA deploy, even after ~25k API calls in about a minute.

**Comment by Orenus** [comment]
errrrrrr......
When invoking the PATCH from Postman - it works ok! job done.

my code OR any of the Podmans exported codes (curl, axios, wget etc...) same socket hang up!!!!
Mystery that a too high price (few hours head banging + tcpdump + grpc logging)

**Comment by naimo84** [comment]
Any updates on this? I'm trying to patch the targetRevision of an app.

As @Orenus said: curl, postman, nodejs... nothing is working. 

```
PATCH /argocd/api/v1/applications/app HTTP/1.1
Host: 10.1.9.30:32007
Authorization: Bearer TOKEN
Content-Type: application/json
Content-Length: 127
{
  "name": "app",
  "patch": "{ \"spec\": { \"source\": { \"targetRevision\": \"dev\" } } }",
  "patchType": "merge"
}
```

I can't use the argocd-cli in my scenario, so what can i do?

```
[k8sdev@k8smaintenace argocd]$ argocd version
argocd: v1.7.14+92b0237
  BuildDate: 2021-03-03T18:37:29Z
  GitCommit: 92b02379b980da45c6b9249f56e1114f294f2d8e
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.5+4c94d88
  BuildDate: 2021-07-22T20:52:31Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
```

**Comment by Orenus** [comment]
@naimo84 seems that currently it is not resolved and there is not other choice than invoking the cli...

**Comment by farvour** [comment]
I, too, am experiencing this issue. Why does the ArgoCD CLI behave differently with patch? I didn't profile it, but I suspect it's just re-pushing the entire spec for the PUT of spec Update instead of PATCH? Otherwise, my CLI would be failing I imagine, since I'm hitting the same endpoint for that...

**Comment by Conrimaceogain** [comment]
> I, too, am experiencing this issue. Why does the ArgoCD CLI behave differently with patch? I didn't profile it, but I suspect it's just re-pushing the entire spec for the PUT of spec Update instead of PATCH? Otherwise, my CLI would be failing I imagine, since I'm hitting the same endpoint for that...

The CLI is likely talking via GRPC, instead of regular HTTP calls where this issue crops up.

**Comment by mslee89** [comment]
I have the same problem.

The following is the version of ArgoCD that I use.
```
$ argocd version
argocd: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
```

And I can't call ArgoCD API using CURL commands.
```
$ curl -v -XPATCH http://argo-cd-argocd-server/api/v1/applications/nginx -H "Authorization: Bearer $TOKEN"  -H "Content-Type: application/json" -d payload
*   Trying 10.233.4.13:80...
* Connected to argo-cd-argocd-server (10.233.4.13) port 80 (#0)
> PATCH /api/v1/applications/nginx HTTP/1.1
> Host: argo-cd-argocd-server.argocd.svc.k8s-prod
> User-Agent: curl/7.74.0
> Accept: */*
> Authorization: Bearer 
> Content-Type: application/json
> Content-Length: 7
> 
* upload completely sent off: 7 out of 7 bytes
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

Has anyone solved this problem yet?

**Comment by mmerrill3** [comment]
I think this is probably b/c there is no PATCH method in matchers.go from https://github.com/soheilhy/cmux/blob/v0.1.5/matchers.go#L46-L55.

It used when the listener for https is created for the argoCD server.

**Comment by jannfis** [comment]
@mmerrill3 Good catch! That may indeed be the reason. Would you care to test it out and potentially submit a PR?

**Comment by mmerrill3** [comment]
sure, maybe this weekend.

**Comment by mmerrill3** [comment]
I was able to setup a test to reproduce this in e2e testing, will issue a PR shortly

```
time="2023-07-15T13:38:35Z" level=fatal msg="Patch \"http://localhost:8080/api/v1/applications/test-patch-http\": read tcp 127.0.0.1:42250->127.0.0.1:8080: read: connection reset by peer"
FAIL	github.com/argoproj/argo-cd/v2/test/e2e	28.874s
FAIL
+ report
+ set -eux -o pipefail
+ go-junit-report
make: *** [Makefile:419: test-e2e-local] Error 1
make: *** [test-e2e] Error 2
```

**Comment by mmerrill3** [comment]
@jannfis , PR is out with e2e test, it works now.
