### ISSUE TITLE
No rule to make target `dev-builder-image'

### ISSUE THREAD

**Issue by oke-py** [argoproj/argo-cd#2680]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

No rule to make target `dev-builder-image' in Makefile.
```
make dev-builder-image
make: *** No rule to make target `dev-builder-image'.  Stop.
```

**To Reproduce**

```
git clone https://github.com/argoproj/argo-cd.git
cd argo-cd
dep ensure
make dev-builder-image
```

**Expected behavior**

execute `make dev-builder-image` successfully.

**Screenshots**

**Version**

```shell
argocd version
argocd: v1.2.5+85f62df
  BuildDate: 2019-10-29T00:07:08Z
  GitCommit: 85f62dff9e3de5a2ee80e9350c897923f59b7e85
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
FATA[0000] token contains an invalid number of segments argocd version
argocd: v1.2.5+85f62df
  BuildDate: 2019-10-29T00:07:08Z
  GitCommit: 85f62dff9e3de5a2ee80e9350c897923f59b7e85
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
FATA[0000] token contains an invalid number of segments 
```

**Logs**

```
```

**Comment by jannfis** [comment]
This is actually a discrepancy between the documentation and the reality: The correct target is `dev-tools-image`, not `dev-builder-imager`

**Comment by oke-py** [comment]
Thanks. It works. I'll submit a PR for this.
