### ISSUE TITLE
1.3.0-rc4 ui oauth flow only completes after second attempt

### ISSUE THREAD

**Issue by jon-walton** [argoproj/argo-cd#2681]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We have oauth configured against the microsoft provider. Since 1.3.0-rc2 (we didn't try rc1), when a user logs in via the oauth provider, they are returned to the login page again. If the user clicks "Login with Microsoft" for a second time, the login completes.

**To Reproduce**

We have the following dex configuration:

```yaml
  dex.config: |
    connectors:
      - type: microsoft
        id: microsoft
        name: Microsoft
        config: ...
```

- The browser cache, cookies, local storage are cleared
- Navigate to `https://argo-server/login`
- Click "Login via Microsoft"
- Complete the Microsoft oauth flow

The user is sent back to `https://argo-server/login`

- Click "Login via Microsoft"

The user is now sent to `https://argo-server/applications`

**Expected behavior**

- User clicks "Login with Microsoft"
- User completes oauth flow and is redirect back to ArgoCD
- User sees the applications page

**Version**

```shell
argocd: v1.3.0-rc3+e0de330
  BuildDate: 2019-10-29T19:43:40Z
  GitCommit: e0de3300d23d559ae1248749e1c351bda684c013
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.3.0-rc4+5937150
  BuildDate: 2019-11-04T06:27:50Z
  GitCommit: 593715038c35506c80edc01a6f684c6cbe12f385
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.1.0
  Helm Version: v2.12.1
  Kubectl Version: v1.14.0
```

**Comment by alexmt** [comment]
Thank you for reporting this issue! It was fixed yesterday as part of this bug:https://github.com/argoproj/argo-cd/issues/2659 .
