### ISSUE TITLE
Cert-manager: 

### ISSUE THREAD

**Issue by dnascimento** [argoproj/argo-cd#2684]
**Describe the bug**
While installing cert-manager, I get: **kubectl failed signal: killed**

**To Reproduce**
```
helm fetch jetstack/cert-manager
helm template
kubectl apply -f namespace.yaml
kubectl apply -f crds.yaml
kubectl apply -f template/
```

Non of the entries is created when synchronised but they can all be created if synchronised manually one by one

**Expected behavior**

To have all components created

**Screenshots**

**Version**
1.2.5

[exception.txt](https://github.com/argoproj/argo-cd/files/3828330/exception.txt)

**Comment by jannfis** [comment]
Can you please share a little more details about this issue and how to reproduce with ArgoCD please?
