### ISSUE TITLE
Running `make lint` fails

### ISSUE THREAD

**Issue by oke-py** [argoproj/argo-cd#2687]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Running `make lint` fails.

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

```
$ cd argo-cd
$ make lint
```

**Expected behavior**

It should return lint result.

**Screenshots**

**Version**

```shell
$ argocd version
argocd: v1.2.5+85f62df
  BuildDate: 2019-10-29T00:07:08Z
  GitCommit: 85f62dff9e3de5a2ee80e9350c897923f59b7e85
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
FATA[0000] token contains an invalid number of segments 
```

**Logs**

```
$ make lint
golangci-lint --version
golangci-lint has version v1.21.0 built from (unknown, mod sum: "h1:HxAxpR8Z0M8omihvQdsD3PF0qPjlqYqp2vMJzstoKeI=") on (unknown)
golangci-lint run --fix --verbose
INFO [config_reader] Config search paths: [./ /Users/naoki/go/src/github.com/argoproj/argo-cd /Users/naoki/go/src/github.com/argoproj /Users/naoki/go/src/github.com /Users/naoki/go/src /Users/naoki/go /Users/naoki /Users /] 
INFO [config_reader] Used config file .golangci.yml 
INFO [lintersdb] Active 13 linters: [deadcode errcheck goimports gosimple govet ineffassign staticcheck structcheck typecheck unconvert unparam unused varcheck] 
INFO [loader] Go packages loading at mode 575 (deps|exports_file|files|compiled_files|name|types_sizes|imports) took 7.083785074s 
ERRO Running error: context loading failed: no go files to analyze 
INFO Memory: 77 samples, avg is 68.9MB, max is 68.9MB 
INFO Execution took 7.516450034s                  
make: *** [lint] Error 5
```

**Comment by alexec** [comment]
The lint tool is exiting with code 5. This hasn’t happened before and is therefore most likely an issue running ‘ golangci-lint run --fix --verbose ’ on your machine. You don’t need this tool to develop code. Most IDEAs will lint correctly does you, or you can wait for CI is report any errors and manually fix them.

**Comment by oke-py** [comment]
ok, thanks.
