### ISSUE TITLE
Unable to apply cluster-install manifest using branch `release-1.3` but `v1.3.0-rc4` works

### ISSUE THREAD

**Issue by deinspanjer** [argoproj/argo-cd#2690]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I have been working with a kustomize that deploys ArgoCD RC2 and RC3 the past few weeks.  It was using the following bases:
`  - github.com/argoproj/argo-cd//manifests/cluster-install?ref=release-1.3`

When I tried to bootstrap a new local cluster this morning, it failed with the following error message:
```
➜  kubectl apply -k dev/local/infrastructure/argoproj/argocd
error: AccumulateTarget: AccumulateTarget: AccumulateTarget: AccumulateTarget: AccumulateTarget: rawResources failed to read Resources: Load from path ./application-controller failed: './application-controller' must be a file (got d='/private/var/folders/xs/w98xrptd01z61bndsfy8l9zr0000gp/T/kustomize-417304681/manifests/base/application-controller')
```
After some experimentation, I discovered that it was specifically that branch. If I install using the tag `v1.3.0-rc3` or `v1.3.0-rc4` it applies fine.

**To Reproduce**

1. start with a fresh k8s cluster
1. create a kustomization.yaml file containing `bases:   - github.com/argoproj/argo-cd//manifests/cluster-install?ref=release-1.3`
1. attempt to apply that kustomize
1. change the ref to `v1.3.0-rc4`
1. attempt to apply the kustomize again

**Expected behavior**

Installing via the branch should behave the same as the versioned tag

**Version**

```shell
argocd: v1.3.0-rc2+4a360cf
  BuildDate: 2019-10-23T01:32:12Z
  GitCommit: 4a360cf9f4b4a6a7639dfcaf31644acf6e53858a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
```
I will try updating the client to rc3 or rc4, but since I'm not invoking the argocd client and the server isn't yet installed, I don't believe this is related to the issue.

**Comment by alexec** [comment]
v1.3.0-rc5 (and therefore ‘release-1.3’) is planned to include an upgrade to Kustomize 3 by default. This includes the installation charts. It’s a holiday today, so it won’t be addressed today. 

In the meantime. Your workarounds are:

* Use the raw YAML manifests (unless you’re using Kustomize features such as ‘nameprefix’ that would prevent you)
* Use Kustomize 3 to install. Hey - you’ll need to upgrade anyway eh?
* Pin to rc4.

**Comment by deinspanjer** [comment]
@alexec Okay.  Thanks for the follow-up (on a holiday no less!)

Does the upgrade to Kustomize 3 mean that we cannot expect to be using kubectl to bootstrap the argocd install anymore since kubectl is using an older version of Kustomize?

When you mention using the raw YAML manifests, does that involve first copying them locally since you can't refer to remote files in the `resources:` section or is there some better way?

**Comment by alexec** [comment]
Neither. I’m just trying to unblock people until a solution is agreed.

**Comment by deinspanjer** [comment]
Great, thanks for the clarification. :)

**Comment by alexec** [comment]
@deinspanjer can you please state the version of kubectl you're using?

**Comment by alexec** [comment]
After chatting with the core team, I'm not sure we plan to change this. It's really tough to support every single different installation method, and we provide a set of fully-formed manifests as mentioned in the getting started guide that should meet most needs. If not, there's the community Helm charts that are highly configurable.

**Comment by deinspanjer** [comment]
I'm using kubectl 1.14 which is the version that pairs up with k8s included in Docker for Mac and what we are deploying in AWS EKS clusters.

So is the intention to remove support for the *-install manifests entirely?  The steps to reproduce I gave above are following the recommended process for self-bootstrapping argocd documented here: https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#manage-argo-cd-using-argo-cd

It felt like there was just some weird difference between the branch for `release-1.3` and the tag for `v1.3.0-rc4` that caused this error to happen if you point at the release branch instead of the RC.

**Comment by alexec** [comment]
@jessesuen ☝️

**Comment by wardyu** [comment]
I am also having an issue with this. I am using `github.com/argoproj/argo-cd//manifests/cluster-install?ref=stable` as my base in kustomize
If i change stable to 1.2.4, all is well which i believe was the previously tagged stable.

**Comment by genebean** [comment]
@wardyu if I understand correctly, right now this is a known thing. Your current choices are to use a newer version of `kustomize` or switch to helm. There’s a working chart at https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexec** [comment]
Back-ported to v1.3 (for v1.3.2)
