### ISSUE TITLE
UI Error - History & Rollback button - v1.3.0-rc5

### ISSUE THREAD

**Issue by gevalter** [argoproj/argo-cd#2694]
Checklist:

**Describe the bug**

History & Rollback stopped working with HTTP error - v1.3.0-rc5

**To Reproduce**

Upgrade to v1.3.0-rc5

**Expected behavior**

HTTP error when opening the History & Rollback button

**Comment by alexec** [comment]
Can you please include the error message?

**Comment by alexec** [comment]
@gevalter this works for me. Can you please provide more information?

* Error message you see.
* Screenshot of history/rollback pane if you're using the UI - CLI args if you're using that.

**Comment by gevalter** [comment]
Also happening in v1.3.0, this error shows in all apps after pressing the history and rollback button:

![image](https://user-images.githubusercontent.com/42349824/68753009-f2bbf580-060c-11ea-9ac2-6a5c2db420e4.png)

When i click on the revision to see more details, I get this error:
![image](https://user-images.githubusercontent.com/42349824/68753091-13844b00-060d-11ea-9e5e-34a1bc0aefcb.png)

I'm able to rollback, so I guess it's UI problem

**Comment by alexec** [comment]
Did you delete your git history or use force push on the repo?

**Comment by gevalter** [comment]
No, actually when i'm downgrading back to v1.2.2 everything is back to normal, so I don't think it's deleted history problem and we never do force pushes.

**Comment by alexec** [comment]
Thank you. We could really do with more information on how to repro this.

**Comment by gevalter** [comment]
After redeploying using the latest chart, problem solved. i guess it was because i had the old ui image in the yaml at the argocd-server deployment.
