### ISSUE TITLE
Third party sites can trick users into interacting with the application

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#2706]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
During a security pentest on our cluster the following finding was reported on Argo:

Third party websites can trick end users into performing interaction with the
application without their knowledge or consent. This is possible because the
application can be included in frames from other (malicious) domains. Once a victim
visits such a domain, actions are performed in the targeted web application by
invisible layers. This technique is commonly known as Clickjacking.

**To Reproduce**

The following steps can be used to verify that the application can be loaded in a
frame:
1. Log in to the application.
2. Create a new HTML file and paste the following in it:
````
<div style="position: relative">
 <iframe src="https://argocd.domain.com/applications"
style="width: 800px; height: 600px"></iframe>
 <div style="position: absolute; background: gold; padding: 10px; top:
487px; left: 358px">
 <h1>&larr; Click here</h1>
 </div>
 <div style="position: absolute; background: gold; padding: 10px; top:
304px; left: 102px">
 <h1>&larr; Click here</h1>
 </div>
</div>
````
3. Open the file.
The application is displayed in a frame. The yellow boxes with text are part of the
containing page, showing that the page can be visually altered.
![image](https://user-images.githubusercontent.com/9946020/68744743-9699a700-05f5-11ea-80a8-d68ade1d188a.png)

Recommendation
 Include or update the Content-Security-Policy header to include the frameancestors directive. Specify none to disable framing, self to allow from the
originating domain only, or specific domains to be whitelisted.
 Add an X-Frame-Options header to each server response. Use DENY as value if
framing is not required, and SAMEORIGIN to whitelist the originating domain.

**Version**

```shell
all versions
```

**Comment by jannfis** [comment]
With the `X-Frame-Options` header now in place, do we still need the `Content-Security-Policy`. Since the policy can become quite complex, how do we want to the user to control it? Or do we want this controllable at all, except of having users deliberately disable it? Any opinions on this, @alexmt or @jessesuen?

**Comment by peterbosalliandercom** [comment]
Any news on this?

**Comment by harikrongali** [comment]
@zachaller can you comment on the ticket? I will assign it to you. 

@crenshaw-dev / @jannfis can we close the ticket?

**Comment by zachaller** [comment]
@harikrongali  yup

**Comment by crenshaw-dev** [comment]
Yep, I think Zach's PR covers everything that was discussed here.
