### ISSUE TITLE
Wrong installation commands in GitHub release notes v1.3.0

### ISSUE THREAD

**Issue by olivierlemasle** [argoproj/argo-cd#2709]
**Describe the bug**

On GitHub, release v1.3.0's Quickstart contains indications to deploy Argo CD, with version 1.3.0-rc1, such as:

    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v1.3.0-rc1/manifests/install.yaml

Cf: https://github.com/argoproj/argo-cd/releases/tag/v1.3.0

**Expected behavior**

Right instructions are:

    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v1.3.0/manifests/install.yaml

**Comment by alexec** [comment]
Fixed now?

**Comment by olivierlemasle** [comment]
@alexec Yes, thanks!
