### ISSUE TITLE
Helm value files outside of chart path

### ISSUE THREAD

**Issue by wecger** [argoproj/argo-cd#2715]
# Summary

Till now ArgoCD was able to access Helm value files outside of the chart folder itself (by relatively addressing the path with ../). Starting with version v1.3.0 (after https://github.com/argoproj/argo-cd/pull/2452) this is not possible anymore. Therefore version 1.3.0 is not backwards compatible when you use this feature. You have to modify your config or repo ordering.

# Motivation

Being able to address files outside of the chart folder, but inside the repository would be helpful.

# Proposal

Right now the value file is always addressed relatively to the chart folder (path option of the application). Maybe its possible to introduce an option to work relatively to the repository (instead of path) for the value files. This might satisfy security concerns and allow current repo structures.

**Comment by simster7** [comment]
Currently working on a flag to allow for more lenient path traversal enforcement as described in https://github.com/argoproj/argo-cd/pull/2452#issuecomment-553430386 and subsequent comments

**Comment by Va1** [comment]
so, eventually, was the flag added and is it possible to specify value files from outside of the chart dir now?

docs still say that it is impossible and it does not seem to work for me

**Comment by Va1** [comment]
sorted it out, nevermind.

paths to the values files should be relative not to the repo root, but to the specified chart root. i believe, this should be indicated in documentation (right now it says that the subject feature doesn't exist – https://argoproj.github.io/argo-cd/user-guide/helm/).

**Comment by juanroldan1989** [comment]
Got the same issue, the solution I found in the docs is: https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
