### ISSUE TITLE
Contribution pre-requisites requires invalid version of kustomize

### ISSUE THREAD

**Issue by oke-py** [argoproj/argo-cd#2717]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Contribution pre-requisites requires invalid version of kustomize.

> kustomize version ;# must be v3.10.x

However, latest version is v3.4.0. It might be v3.1.x?

**To Reproduce**

n/a

**Expected behavior**

require existent version

**Screenshots**

**Version**

n/a

**Logs**

n/a

**Comment by alexec** [comment]
Good point. Fancy submitting a PR to correct this?
