### ISSUE TITLE
OIDC project role binding is not working

### ISSUE THREAD

**Issue by imranismail** [argoproj/argo-cd#2723]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

OIDC project role is not enforced for user

**To Reproduce**

dex.config
```yaml
connectors:
- type: github
  id: github
  name: Github
  config:
    teamNameField: slug
    clientID: $dex.github.clientId
    clientSecret: $dex.github.clientSecret
    orgs:
    - name: acme
```

project
```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  creationTimestamp: "2019-11-15T09:55:18Z"
  generation: 5
  name: oauth
  namespace: argocd
  resourceVersion: "172944"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/appprojects/oauth
  uid: 07eaad35-078e-11ea-b3a0-0669f88e6f4e
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  roles:
  - groups:
    - org:team
    name: no-access
    policies:
    - p, proj:oauth:no-access, applications, *, oauth/*, deny
  sourceRepos:
  - https://github.com/kfit-dev/app-defs.git
```

**Expected behavior**

A user in org:team shouldn't be able to do anything with applications under oauth project

**Comment by alexec** [comment]
Could I ask you to double check your config against:

https://argoproj.github.io/argo-cd/operator-manual/rbac/

**Comment by imranismail** [comment]
@alexec this isn't the RBAC role but the project role.

**Comment by thatsmydoing** [comment]
Do your groups reflect properly in
```
argocd account get-user-info
```
on the web ui, you can click the profile link in the sidebar to check.

We've had issues where we had to specify the `teams` parameter in the dex config before they were applied to our users. See https://github.com/dexidp/dex/blob/master/Documentation/connectors/github.md

**Comment by imranismail** [comment]
@thatsmydoing yes, I can see the group claims listed in the account which the role should be bound to in the format of `(org):(team)` and we set the same group in the `.spec.roles[0].groups` in the same format: `(org):(team)`

**Comment by imranismail** [comment]
This now works
