### ISSUE TITLE
Can't use `DNS-1123` compliant app name when creating project role

### ISSUE THREAD

**Issue by imranismail** [argoproj/argo-cd#2724]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I managed to create an app with the name `component.environment.detail` but when I tried to assign a project role with the full app name; I get an error toast saying it's not valid.

**To Reproduce**

- Create an app name like `component.environment.detail`
- Create a project role in argocd ui with the following policy:
`p, proj:default:no-access, applications, *, default/component.environment.detail, deny`
- Fill up the required fields
- Submit
- An error toast slides in with an error saying invalid app name

**Expected behavior**

The validation should be the same as when you try to create an application.

**Logs**

```
Unable to edit project: invalid policy rule 'p, proj:oauth:no-access, applications, *, oauth/hydra.staging.main, deny': object must be of form 'oauth/*' or 'oauth/<APPNAME>', not 'oauth/hydra.staging.main'
```

**Comment by alexec** [comment]
See #2723

**Comment by alexec** [comment]
This error in returned by https://github.com/argoproj/argo-cd/blame/2e523bfb9333f3e68027748179055a77df24b708/util/project/util.go#L130 written by @jessesuen . While the fix looks straight forward (check against DNS regexp), I'd like @jessesuen to chip in with any insights an to why it might be as it is today.

**Comment by alexec** [comment]
@imranismail in the meantime, are you able to work around using '-' instead of '.' in the names?
