### ISSUE TITLE
a bug or config err

### ISSUE THREAD

**Issue by ermazi** [argoproj/argo-cd#2732]
**Describe the bug**
there are hundreds of applications managed in one argo-cd.sometime, i cannot get application detailed info from argo-cd ui.
is there any limitation? like qps or burst?

i found that kube client qps & burst config are defined as constants, should it be configurable?

**Log**
rpc call timeout

**Other Info**
version: 1.1.2

**Comment by blakepettersson** [comment]
Closing since this is likely not relevant any more.
