### ISSUE TITLE
How to get bearerToken for connection to external k8s Cluster

### ISSUE THREAD

**Issue by zhiqli** [argoproj/argo-cd#2735]
```
apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: mycluster.com
  server: https://mycluster.com
  config: |
    {
      "bearerToken": "<authentication token>",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64 encoded certificate>"
      }
    }

```
How to get `bearerToken` for connection to external k8s Cluster？

And `caData`, `certData`, `keyData` is corresponding to `certificate-authority-data`, `client-certificate-data`, `client-key-data` in kubeconfig?

**Comment by alexec** [comment]
Does this help?

https://argoproj.github.io/argo-cd/operator-manual/security/#external-cluster-credentials

**Comment by zhiqli** [comment]
@alexec According to the document you sent, the configuration is successful, thank you。
