### ISSUE TITLE
Target Revision truncated

### ISSUE THREAD

**Issue by genebean** [argoproj/argo-cd#2736]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The values shown for the target revision seems to be truncated when viewing it but not when editing it. It seems that this happens after 7 characters

**To Reproduce**

create a branch named argocd130 and set that as the value of the target revision.

**Expected behavior**

The entire branch name should show without hitting edit.

**Screenshots**

View mode:

![app-details-view](https://user-images.githubusercontent.com/966789/69071452-ec0bf480-09f7-11ea-97ae-081cf7afd106.png)

Edit mode:

![app-details-edit](https://user-images.githubusercontent.com/966789/69071451-ec0bf480-09f7-11ea-80df-5d9f2b3b830f.png)

**Version**

This happens when installing version 1.3.0 via helm.

**Comment by alexec** [comment]
Fixed in v1.4
