### ISSUE TITLE
Argo CD should specify numeric USER in dockerfiles to support pod security policies

### ISSUE THREAD

**Issue by chrisbulgaria** [argoproj/argo-cd#2746]
Small thing - but we want to make Argo CD perfect :)
When specifying a Pod Security Policy  MustRunAsNonRoot Argo CD  pods fail to start 

"Error: container has runAsNonRoot and image has non-numeric user (argocd), cannot verify user is non-root" 

This can be be worked around by changing the deployment descriptors, but would be better to fix this in the Dockerfiles I think.
Reference: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups

**Comment by alexec** [comment]
Thank you @chrisbulgaria  - would you be interested in submitting a PR?

**Comment by chrisbulgaria** [comment]
Yes - will do.

**Comment by fckbo** [comment]
I just add this issue

**Comment by KaiReichart** [comment]
[PSPs are being deprecated](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/), maybe this can be dropped now

**Comment by crenshaw-dev** [comment]
I think this is the thing we needed to do, and we did it? https://github.com/argoproj/argo-cd/blob/254f3b69aef1ea261e25aca680248df126239b1d/Dockerfile#L41

lmk if I'm wrong.  :-)
