### ISSUE TITLE
How to configure ignoreDifferences for replica count?

### ISSUE THREAD

**Issue by eroji** [argoproj/argo-cd#2748]
I can't find any information on how to configure the ignoreDifferences option. I came across this issue https://github.com/argoproj/argo-cd/issues/1075, but the example given to add into the configmap does not seem to work. I am using kustomize and HPA, and applications with sync enabled will constantly try to undo replica count changes made by the HPA.

**Comment by alexec** [comment]
Does this help?

https://argoproj.github.io/argo-cd/user-guide/diffing/

**Comment by eroji** [comment]
Yes thank you!
