### ISSUE TITLE
Add helm --set-file support

### ISSUE THREAD

**Issue by tomcruise81** [argoproj/argo-cd#2751]
# Summary

With https://github.com/helm/helm/pull/3758, helm added the ability to import files via the `--set-file` argument. This allows files _outside_ of the chart directory to be referenced and used via a chart.

# Motivation

We utilize an enterprise-wide chart that has extensive vetted logic. The chart is provided with a values,yaml file and additionally with config map and secrets files via the helm `--set-file` argument. These are application specific and housed in an external config repository (Spring Cloud Config).

# Proposal

This should be implemented in a manner similar to https://github.com/argoproj/argo-cd/issues/2078.

**Comment by tomcruise81** [comment]
This is still relevant. The pull request is waiting on review by @alexmt.

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/2752. Thank you @tomcruise81 !
