### ISSUE TITLE
How to disable tls for the purpose of own tls termination on tls proxy ?

### ISSUE THREAD

**Issue by sokoow** [argoproj/argo-cd#2753]
**Describe the bug**

Hey, maybe this is the right place for this : https://github.com/argoproj/argo-helm/issues/168

**To Reproduce**

Install argo-cd and try to splice it with letsencrypt over for example trafik reverse proxy

**Comment by alexec** [comment]
Does this help?

https://argoproj.github.io/argo-cd/operator-manual/ingress/

**Comment by sokoow** [comment]
Nope, sorry it doesn't @alexec :/

**Comment by rocketspacer** [comment]
By default the ingress forward traffic to ArgoCD using HTTP
You can change it to HTTPS but then the Ingress is not happy with ArgoCD self-signed cert.

**Comment by bbl** [comment]
Are there any workarounds for this? 
We are using TLS termination on a separate ingress controller, all certs are managed there, hence we don't want to share any certs with ArgoCD. 
Passthrough with self-signed autogenerated certs on ArgoCD leads to browser alerts. 
Is there any particular reason why we don't have optional TLS on the ArgoCD side? Why does the app care about the infrastructure layer?

**Comment by eshaffer321** [comment]
My issue was I had TLS termination at the load balancer and then all traffic was sent over http to argo cd. Argo CD doesn't like that and expects traffic to be on 443. The workaround is to use the --insecure flag. In the helm chart I used here it is on of the first things in the repo 🤦 . RTFM

**Comment by maaft** [comment]
Could you please elaborate where exactly you used the `--insecure` flag ?

**Comment by daywalked** [comment]
@maaft, it is best described here: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/

> The API server should be run with TLS disabled. Edit the argocd-server deployment to add the --insecure flag to the argocd-server command, or simply set server.insecure: "true" in the argocd-cmd-params-cm ConfigMap [as described here](https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/additional-configuration-method/). Given the argocd CLI includes the port number in the request host header, 2 Mappings are required.

The context is around ingress configuration, so it goes through the different providers, but it still being relevant. The reference to "server.insecure: true" is talking about helm values, if you are using that. The --insure flag is if you are using the CLI (see: https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/argocd-server/)
