### ISSUE TITLE
Remove `latest` from UI

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#2757]
# Summary

We should `latest` in the UI for Git apps that are on `HEAD`. 

# Motivation

The link is broken and it's unclear.

# Proposal

Remove the term `latest` from the code.

**Comment by alexmt** [comment]
+1 I was about to file a bug for the same

**Comment by alexec** [comment]
I've fixed in a PR with more changes. That would be for v1.4. Do you think we want to back-port just the "latest" changes to v1.3? @alexmt
