### ISSUE TITLE
Issues with github authentication with Argo-ha setup

### ISSUE THREAD

**Issue by chiragthaker** [argoproj/argo-cd#2763]
We are running argocd ha setup and here is our kustomization file : 

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- patches/argocd-application-controller-deployment.yaml
- patches/argocd-repo-server-deployment.yaml
- patches/argocd-server-deployment.yaml
- patches/argocd-dex-server-deployment.yaml
- patches/argocd-cm.yaml
- patches/argocd-server-service.yaml
- patches/argocd-rbac-cm.yaml
- patches/argo-secret.yaml

resources:
- github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=v1.3.0
- resources/argocd-namespace.yaml
- resources/argocd-server-ingress.yaml
- resources/github-secret.yaml

images:
- name: argoproj/argocd
  newTag: v1.3.0

I am trying to acheive authentication via my github repos however i am getting failed constantly and have no clue whatsoever

Here is the error i see : 

time="2019-11-25T13:47:26Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = no session information" grpc.code=Unauthenticated grpc.method=List grpc.service=cluster.ClusterService grpc.start_time="2019-11-25T13:47:26Z" grpc.time_ms=0.065 span.kind=server system=grpc

We are kinda blocked with this  as no one can go in right now

**Comment by alexec** [comment]
Hi @chiragthaker ,  we don't currently support install via Kustomize, instead we provide plain YAML. There are also community maintained charts. I understand that a number of people want to do this, so perhaps someone in the community can help.

You may also wish to read https://argoproj.github.io/argo-cd/operator-manual/security/ and https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#clusters

**Comment by chiragthaker** [comment]
We can close this , i managed to fix it myself

**Comment by mhaddon** [comment]
> We can close this , i managed to fix it myself

[xkcd](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)
