### ISSUE TITLE
cluster connection status failed but connection works fine. 

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#2764]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When adding a cluster it says failed for the connection status.In argo it is possible to use the cluster without any problems

**To Reproduce**

1. argocd cluster add <context>
2. sync application

**Expected behavior**

Successful connection

**Screenshots**

![image](https://user-images.githubusercontent.com/9946020/69555728-edaf5c80-0fa3-11ea-8cf6-1715e1fa538d.png)

**Version**

```shell
1.3.0
```

**Comment by alexec** [comment]
Cluster status is cached, so it maybe that it's showing a cached result, so it may just take time (24h?) to update. If it's not solved tomorrow, the this is probably a bug.

**Comment by alexec** [comment]
Mind you, we should update https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#manage-argo-cd-using-argo-cd.

**Comment by alexmt** [comment]
Looks like #2945 describes the same problem.
