### ISSUE TITLE
Add Logs Subcommand to `argocd app`

### ISSUE THREAD

**Issue by dmizelle** [argoproj/argo-cd#2769]
# Summary

The `app` subcommand for the ArgoCD CLI should itself have a `logs` subcommand so that users can get logs from the command line.

# Motivation

We don't give developers `kubectl` access to anything other than our development cluster. They're pretty used to doing a `kubectl logs -f` on the command line when in this cluster. However, once they are running on QA or PROD, they lose access.

We do ship the logs to Splunk, but anyone who has ever used it has found that its rather lacking for "realtime" tailing of logs.

Currently, developers will use the ArgoCD UI to look at logs for pods, but some have noted that during an emergency, it'd be nice to look at the logs using the `argocd` CLI utility from their terminal.

# Proposal

Disclaimer: I already wrote code for this, and was about to submit a PR until I saw that enhancement proposals are now a thing. :)

I'm a little new to GRPC, but what I've done is added a subcommand to `argocd app`, that calls `ResourceTree`, loops through all pods, and starts goroutines to tail the logs (or just write the current logs to stdout if `-f` is not passed to the command).

Using fields from `ApplicationPodLogsQuery`, options are passed in from the `cobra.Command` to set things such as `appName`, `podName`, `Namespace`, `Follow`, etc.

It works rather well right now, but definitely could use some code review if the community thinks its a good idea. Like I said, really green on the GRPC (and even goroutine/concurrency front)

**Comment by alexec** [comment]
@dmizelle sounds like a good idea. I'd suggest it should probably be like:

```
argocd app logs APPNAME  --group .. --kind ... --resource-name ...
```

To be consistent with `argocd app patch-resource`. Also, should be familiar to people using `kubectl logs`, so flags should be the same.

**Comment by dmizelle** [comment]
Currently, here's the help text:

```
Show logs for a pod in an application

Usage:
  argocd app logs APPNAME [flags]

Flags:
  -f, --follow                 Follow log entries. Interrupt to cancel
  -h, --help                   help for logs
  -n, --namespace string       Namespace the pod lives in
  -r, --resource-name string   Name of the resource to get logs for
  -l, --tail-lines int         Number of lines to show (default 100)
```

I can definitely add `--group` and `--kind`, with it defaulting to Pod.

What I'm doing right now is looking up all pods that have a `parentRef` of the specific resource name.

In this way, I was working under the thought that not really anything else I can think of besides Pods have logs, so the kind is limited to things such as:

* DaemonSet
* ReplicaSet
* Deployment
* etc...

So if someone were to run

```
argocd app logs foo-bar-qa -n foo-bar -r baz-bang -f
```

it would show them any logs from a deployment/daemonset/replicaset named foo-bar.

Does that sound like relatively okay idea?

**Comment by dmizelle** [comment]
Ah, I think the reason why I defaulted to Pods was because that the protobuf for doing loggy-looking things only references pods:

https://github.com/argoproj/argo-cd/blob/5abe863ea9a103a9ce3165f200e8b0f1b0828dcc/server/application/application.proto#L329-L333

**Comment by alexec** [comment]
Good point. No need for kind.

**Comment by alexec** [comment]
Or group.

**Comment by dmizelle** [comment]
I'm probably going to put a PR in after Thanksgiving as I still need to
write docs for it, but I'll respond on this issue if any other community
members have questions :)

**Comment by adzuci** [comment]
@dmizelle I'm skimmed your open PR and am not sure how much help I could be, but this would be a great feature!  Any chance you're still working on it?

**Comment by dmizelle** [comment]
Hey, sorry about the delay! Life has been kind of crazy since the New Year.

I occasionally check out the branch and try and crack through the testing request that was put into the PR but end up running out of time.

I think I'm going to bug my employer about giving me a little time to get it finished asteams have requested it and are aware of my PR. Plus, we're avid users of ArgoCD.

**Comment by johnmarcou** [comment]
Hi guys! When we argocd app wait  an app, it would be nice to be able to print the log of the degraded component at the timeout.

For now, we have the CI building and deploying on new commit. Sometime, the new code make the Deployment to crashloop. The argocd app wait is finally timeout, and print:
...
apps                     Deployment      myns     myapp                    Synced     Degraded           deployment.apps/myapp configured
...
time="2020-05-27T05:54:28Z" level=fatal msg="application 'myargoapp' health state has transitioned from Progressing to Degraded"

Would be nice if we could add a --verbose  to get the `kubectl logs [DEGRADED_PODS]`.

Or may be something like this?
`argocd app wait APP || argocd app logs APP --state degraded`

**Comment by aweis89** [comment]
Any update on this, would love to start using this feature

**Comment by harshitasao** [comment]
Hi, @alexec @dmizelle . Is this issue still open for contribution? I'd like to try.

**Comment by crenshaw-dev** [comment]
@harshitasao I believe this has been implemented: https://argo-cd.readthedocs.io/en/latest/user-guide/commands/argocd_app_logs/

Someone let me know if I'm wrong, and I'll reopen.
