### ISSUE TITLE
Add Jaeger instrumentation 

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#2772]
# Summary

In v1.3.0 we've seen maybe a 2x performance degradation. Jaeger may have been a way to prevent this.

# Motivation

We would like to avoid performance problems now and in the future.

# Proposal

Using the Jaeger APIs. We should log both internal and external systems:

* Requests to Kube API.
* Kubectl
* Shell Exec.

**Comment by hairmare** [comment]
related issue: https://github.com/argoproj/argo-cd/issues/4972
