### ISSUE TITLE
Add webhook support for Bitbucket server with ssh

### ISSUE THREAD

**Issue by klamkma** [argoproj/argo-cd#2773]
# Summary

Webhook for bitbucket server only supports http.
https://github.com/argoproj/argo-cd/blob/257c27677abf71e1bb0a35d475f1c2cc407deac6/util/webhook/webhook.go#L118
```			
if link["name"] == "http" {
    webURL = link["href"].(string)
    break
}
```
But in our case the payload sent in webhook is:
```
"links": {
    "clone": [{
	"href": "ssh://git@xxxx.git",
	"name": "ssh"
   }],
   [...]
```
So webURL is empty and in the logs we get "Ignoring webhook event".

# Motivation

Webhook for Bitbucket server does not work for ssh authentication.

**Comment by alexec** [comment]
Would you like to submit a PR for this please?

**Comment by eSamS** [comment]
#3036

**Comment by magnusaxelqvist** [comment]
ETA on this one?

**Comment by jannfis** [comment]
@magnusaxelqvist It's in the RC of v1.5.0 already. Feel free to test it.
