### ISSUE TITLE
Docs SSO RBAC Scopes Param

### ISSUE THREAD

**Issue by nouseforaname** [argoproj/argo-cd#2782]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

https://github.com/argoproj/argo-cd/blob/bbfb96cb0161b1d11cbbc334fb33eb1158b2c075/docs/operator-manual/argocd-rbac-cm.yaml#L27-L29
scopes Param from example rbac configmap is not mentioned in docs. I was debugging our Okta groups not getting mapped to policies and noticed that without setting **scopes : '[Groups]'** the group mappings would fail. The issue itself maybe related to our Okta Settings but I thought it would be good to let people know that this may be necessary. Interestingly, after checking with Okta Team, I was told that the scope indeed got created with the value **groups** not **Groups**. 

**To Reproduce**

Docs Issue

**Expected behavior**

Docs be precise

**Version**
Current Master

**Comment by alexec** [comment]
Would you like to raise a PR to fix this?

**Comment by DhanashriPalodkar** [comment]
@alexec  Has anyone fixed this bug? This looks more related to docs which @nouseforaname mentioned in a much descriptive way, are there any complications that came on its way while solving it which could be looked to solve the issue?
