### ISSUE TITLE
Error: index out of range when Chart.yaml is at root of git repo

### ISSUE THREAD

**Issue by moensch** [argoproj/argo-cd#2796]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When setting up an `Application` to install a helm chart from a git repo, where `Chart.yaml` is at the root of the repository, the following error is yielded:

```
level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to generate manifests in .: rpc error: code = Internal desc = runtime error: index out of range" grpc.code=InvalidArgument grpc.method=Update grpc.service=application.ApplicationService grpc.start_time="2019-12-02T23:39:08Z" grpc.time_ms=1105.718 span.kind=server system=grpc
```

Note that this is a regression from `v1.3.0` (steps to reproduce succeed on `v1.3.0` but fail on `v1.3.1`)

**To Reproduce**

Make a new Application with this spec:

```yaml
project: default
source:
  repoURL: 'https://github.com/moensch/foochart.git'
  path: .
  targetRevision: master
  helm:
    valueFiles:
      - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
```

Attempt to synchronize the app and notice the `index out of range` error in the `status` field.

**Expected behavior**

Application should be created

**Screenshots**

n/a

**Version**

```shell
argocd: v1.3.1+962fb84
  BuildDate: 2019-12-02T21:22:26Z
  GitCommit: 962fb84fbaca8327a92c7a210d3b183a0fee632e
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.3.1+962fb84
  BuildDate: 2019-12-02T21:21:59Z
  GitCommit: 962fb84fbaca8327a92c7a210d3b183a0fee632e
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**

```
level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to generate manifests in .: rpc error: code = Internal desc = runtime error: index out of range" grpc.code=InvalidArgument grpc.method=Update grpc.service=application.ApplicationService grpc.start_time="2019-12-02T23:39:08Z" grpc.time_ms=1105.718 span.kind=server system=grpc
```

**Comment by moensch** [comment]
It looks like this issue got introduced here: https://github.com/argoproj/argo-cd/pull/2716

This here works:
```golang
subtracted := SubtractRelativeFromAbsolutePath("/argocd-example-apps/helm-guestbook/env/guestbook/env", "./)
```

This here yields the error:
```golang
subtracted := SubtractRelativeFromAbsolutePath("/argocd-example-apps/helm-guestbook/env/guestbook/env", ".")
```

**Comment by alexec** [comment]
@simster7 fancy looking into this one please?

**Comment by simster7** [comment]
Looking

**Comment by simster7** [comment]
Of course the one edge case I didn't happen to make a test for comes up 🙃

https://github.com/argoproj/argo-cd/blob/addf397b538362cd2cc5678dd50e1f299f5c1e13/util/security/path_traversal_test.go#L37

Will submit a PR momentarily

**Comment by alexec** [comment]
Back-ported to v1.3

**Comment by moensch** [comment]
Thank you for the super quick turn-around! Will you be cutting a `1.3.2` release soon with this fix? My concern is that since `.` is put into the spec by the UI and not by a human editing the application spec, this issue will pop up more often.

**Comment by simster7** [comment]
@moensch In case you missed it, [1.3.2 is out now](https://github.com/argoproj/argo-cd/releases/tag/v1.3.2)!
