### ISSUE TITLE
UI Graph hides project resources that become owned by other resources

### ISSUE THREAD

**Issue by rudoi** [argoproj/argo-cd#2798]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have a repo that contains a all the yaml required to set up a MachineDeployment for [Cluster API](https://github.com/kubernetes-sigs/cluster-api). There are four objects in the repository:
- MachineDeployment
- KubeadmConfigTemplate
- 2x AWSMachineTemplate 

When looking at the project in Argo, the UI shows the MachineDeployment very briefly, and then it disappears. Screenshots below show the before and after (kinda).

I believe the cause of this is the fact that the Cluster API controller will set an OwnerRef on the MachineDeployment, because the MachineDeployment needs to be owned by a Cluster object. Argo's first pass at displaying objects seems to look at the objects in the repository, but subsequent passes filter out things with ownerRefs. 

https://github.com/argoproj/argo-cd/blob/89b33a14429da65aabcaa67fb5697ee923d35c61/ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx#L331

Reproduction steps and screenshots are for a much simpler Application that contains a single pod.

**To Reproduce**

1. Connect https://github.com/rudoi/a-single-pod.git. 
2. Create an Application for the above and Sync. 
3. Over to the command line:
```bash
// we're gunna set the pod's owner to be the default namespace, so we need the uid
export DEFAULT_NS_UID=$(kubectl get ns default -o json | jq -r '.metadata.uid')

kubectl patch po/hello -p "{\"metadata\": {\"ownerReferences\": [{\"name\": \"default\", \"kind\": \"namespace\", \"apiVersion\": \"v1\", \"uid\": \"${DEFAULT_NS_UID}\"}]}}"
```

Instantly gone! Deleting the ownerRef brings it back immediately into view.

**Expected behavior**

I would expect the UI to always show objects in the repository, even if they become owned by other resources. Furthermore, I think it'd be awesome to follow the ownership tree in the other direction when that happens.

**Screenshots**

Before
<img width="1353" alt="Screen Shot 2019-12-03 at 8 10 25 AM" src="https://user-images.githubusercontent.com/12792264/70068683-4fc02100-15a5-11ea-9dbf-dd885ea063ae.png">

After
<img width="1210" alt="Screen Shot 2019-12-03 at 8 15 45 AM" src="https://user-images.githubusercontent.com/12792264/70068793-8007bf80-15a5-11ea-93f5-e393f956505f.png">

**Version**

```shell
argocd: v1.3.0+9f8608c
  BuildDate: 2019-11-13T01:51:29Z
  GitCommit: 9f8608c9fcb2a1d8dcc06eeadd57e5c0334c5800
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.3.0+9f8608c
  BuildDate: 2019-11-13T01:51:00Z
  GitCommit: 9f8608c9fcb2a1d8dcc06eeadd57e5c0334c5800
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Comment by sethp-nr** [comment]
👋 I worked with @rudoi to identify this bug and am hoping to put together a PR soon. Besides the UI-side root finding above that filters out managed resources that gain an ownership ref, I notice that the "IterateHierarchy" has no mechanism to return parents, only children. https://github.com/argoproj/argo-cd/blob/257c27677abf71e1bb0a35d475f1c2cc407deac6/controller/appcontroller.go#L296-L298

I think there's two approaches to take (not mutually exclusive):

1. Change the UI to recurse starting from the managed resources (the nodes with edges to the Application) instead of finding parent-less nodes to start recursion
2. Change the server to walk the tree in both directions by enabling IterateHierarchy to surface parents as well as children (possibly including making the Application node in the UI more visually distinct)

At this point my preference is leaning towards "both," though I'd be glad to hear your thoughts.

**Comment by alexec** [comment]
@alexmt ☝️

**Comment by sethp-nr** [comment]
I've been thinking some more about this choice, and I've come to this question:

- Should the Application always be the "leftmost" node in the graph, or is it better for Argo to show where the App-managed resources "fit in" to an existing hierarchy?

In the CAPI use-case I think either is OK – it would be nice to have the Cluster object that parents the things most folks are going to be managing visible, but that's as deep as the rabbit hole goes. So we'd end up with 

```
< Cluster > -\
    < App >  -- < MachineDeployment> -- ...
```
For some of our other CRD use-cases, though, the tree will extend a bit in both directions as we transition certain git-ops resources into control of a higher-level operator. In that case the picture would look more like:

```
< MyDbCluster > -- < MyDbServer > -- < MachineDeployment> -- ...
                          < App > -/  
```

If we choose to do 1, then we fix this issue without changing the existing "leftmost" behavior. If we do 2, then we'll fix this issue by introducing roots on the same level as or to the "left" of the App node. If we do 1 & 2, then we don't change the existing UI visualization, but do make the full hierarchy available to other API users.
