### ISSUE TITLE
ArgoCD drift detection - Question

### ISSUE THREAD

**Issue by kodelint** [argoproj/argo-cd#2799]
How does [ArgoCD](https://github.com/argoproj/argo-cd) does drift detection on the end state? Say I used a git repo to deploy an app to `K8S`, which exposes the service to `LoadBalancer`. Once the sync happens on [ArgoCD](https://github.com/argoproj/argo-cd) the application gets deployed and the endpoint is accessible using LoadBalancer. Now somebody with access to AWS Console goes and changes the security group rule for the `LoadBalancer`. Whitelisted `CIDR` is not part of the security Group anymore. How does ArgoCD catches this drift and puts the desirable state which is in the git back to the deployment

Is it something [ArgoCD](https://github.com/argoproj/argo-cd) helps us with? Please advise

**Comment by alexec** [comment]
Does this help?

https://argoproj.github.io/argo-cd/operator-manual/architecture/
