### ISSUE TITLE
More Detailed Installation Instructions for CLI

### ISSUE THREAD

**Issue by danielhelfand** [argoproj/argo-cd#2800]
# Summary

Under the getting started section, the [CLI installation instructions](https://github.com/argoproj/argo-cd/blob/master/docs/getting_started.md#2-download-argo-cd-cli) are great for Mac users but lacking for other operating systems. 

There should be more detailed instructions for downloading the CLI across various operating systems to achieve a similar experience to what Mac users have with brew. If Argo CD has other package manager installation options (e.g. `yum`, `dnf`, `choco`, etc.), then those options should be listed. 

# Motivation

Being able to install the CLI without needing to think much about it. 

# Proposal

Have a section for each operating system and provide detailed instructions about installing the CLI.

**Comment by alexec** [comment]
Would you like to submit a PR for this?

**Comment by danielhelfand** [comment]
@alexec Sure! More than happy to. Are any other package managers besides `brew` available at this time?
