### ISSUE TITLE
Argocd autosync with cron schedule to enable nightly synchronizations

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#2804]
# Summary

We want to auto sync but only when people aren't working, for instance to update plugins in jenkins amongst other things

# Motivation

No disturbances for developers 

# Proposal

Maybe add a cron schedule to enable auto sync?

**Comment by alexec** [comment]
You should be able to use Sync Windows feature for Thai?

**Comment by alexmt** [comment]
I think this is covered by sync windows features. @peterbosalliandercom please let us know if this is not enough
