### ISSUE TITLE
v1.3.x: RBAC applications get permission now shows error in UI

### ISSUE THREAD

**Issue by wecger** [argoproj/argo-cd#2805]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using RBAC permissions in ArgoCD v1.3.x and only having permissions ```applications, get```, then an error is now shown in the UI: 
```
Unable to load data: permission denied:
projects, get, <here your project name>
```

**To Reproduce**

- Setup an ArgoCD v1.3.x installation
- use RBAC to limit an user to ```applications, get, */*, allow``` permissions
- do NOT grant ```projects, get, *, allow``` permission 
- Log in to UI and look at the application granted access to via RBAC

**Expected behavior**

UI shows no error while displaying the application (worked fine up to v1.2.5)

**Version**

```shell
argocd-server: v1.3.2+unknown
  BuildDate: 2019-12-04T07:22:09Z
  GitCommit:
  GitTreeState: clean
  GoVersion: go1.13
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.3 GitCommit:f8412aa3d39f32151525aff97a351288f5a7470b BuildDate:2019-10-08T23:30:25Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Comment by alexec** [comment]
I've looked at this and this it might be due to the new sync windows feature. You must have repocet get permission to view this, and I think this would disrupt the UI.

To help confirm this hypothesis can I please request:

* The URL you see the error on and a screenshot of that page.
* The output of `kubectl -n argocd get cm argocd-rbac-cm -o yaml`

As a workaround - you can give that users the projects/get permission.

**Comment by wecger** [comment]
Hi Alexec,

the recommended workaround works fine to get rid of the error message (but I had to grant permissions which did not exist before).

Regarding the information you asked for:
- URL the error was shown on: https://<domain>/applications/<applicationname>-nonprod-1
- Regarding the rbac file: I allowed myself to remove all lines not concerning the affected account
```
  policy.csv: |
    p, role:<projectname>-view, projects, get, <projectname>, allow
    p, role:<projectname>-view, applications, get, <projectname>/*, allow
    p, role:<projectname>-view, applications, sync, <projectname>/*, allow
    p, role:<projectname>-view, applications, action/resume, <projectname>/*, allow
    p, role:<projectname>-view, applications, action/restart, <projectname>/*, allow
    g, <githubOrgUnit>:<githubTeam>, role:<projectname>-view
  policy.default: ""
```
- Screenshot is attached (hopefully)

**Comment by alexec** [comment]
Thank you very much for that data. I think this is a UI only error. We have a backlog of work, so as a work-around exists, then I'm not sure we should fix it today. Perhaps we should show a better error message.

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/3456
