### ISSUE TITLE
Question: API way to trigger a global refresh?

### ISSUE THREAD

**Issue by eroji** [argoproj/argo-cd#2824]
Is it currently possible to trigger a refresh for all applications via API? I am trying to build ArgoCD into the a pipeline and I want it to refresh right away when I update the deployment repo, ideally without having to know what the respective application is called in ArgoCD.

**Comment by jessesuen** [comment]
This is the purpose of the webhook feature. Can you leverage that?

**Comment by eroji** [comment]
@jessesuen This this should work! Can you clarify what the difference between webhook.bitbucket.uuid and webhook.bitbucketserver.secret is?
