### ISSUE TITLE
argocd app edit fails when EDITOR has arguments

### ISSUE THREAD

**Issue by cabrinha** [argoproj/argo-cd#2833]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The interactive CLI editor does not support an editor command with flags or options.

**To Reproduce**

Set your $EDITOR to use flags/options:

`vim -t` ... `emacsclient -t`

**Expected behavior**

I expect the interactive editor to launch successfully.

**Screenshots**

**Version**

```shell
$ argocd version
argocd: v1.3.2+a5a65cd
  BuildDate: 2019-12-03T21:32:47Z
  GitCommit: a5a65cdfe7c43fd1e3beada202d80c19bc50bd40
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.3.2+a5a65cd
  BuildDate: 2019-12-03T21:32:18Z
  GitCommit: a5a65cdfe7c43fd1e3beada202d80c19bc50bd40
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**

```
FATA[0000] fork/exec /Applications/Emacs.app/Contents/MacOS/bin/emacsclient -t: no such file or directory
```

**Comment by alexec** [comment]
Good buy report. Do you want to submit a PR to fix this please?

**Comment by cabrinha** [comment]
I've created a PR here: https://github.com/argoproj/argo-cd/pull/2843

It's my first attempt as I'm still in the process of learning Go 😅 

I'm having some issues testing it because I'm used to go modules on go1.13.x

```
$ dep ensure
root project import: /Users/scabrinha/devel/argo-cd is not within any GOPATH/src
$ export GOPATH=$GOPATH:/Users/scabrinha/devel/argo-cd
$ dep ensure
root project import: /Users/scabrinha/devel/argo-cd is not within any GOPATH/src
```
