### ISSUE TITLE
  Unable to load data: redis: all sentinels are unreachable

### ISSUE THREAD

**Issue by thanhpd-teko** [argoproj/argo-cd#2862]
- Create argocd from this base https://github.com/argoproj/argoproj-deployments (change domain + change base to github.com/argoproj/argo-cd//manifests/cluster-install?ref=release-1.3)
- Go the the ui
- Got error when click into any resource
![image](https://user-images.githubusercontent.com/47600586/70629411-88729100-1c5c-11ea-9ca9-b3c9577ad222.png)
Please help.

**Comment by jessesuen** [comment]
Closing. We switched to redis-ha with haproxy. This may have been environment specific issue.
