### ISSUE TITLE
Webhook does not work when ssh URL have a custom port

### ISSUE THREAD

**Issue by popkirby** [argoproj/argo-cd#2866]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When an application is registered with a SSH URL with custom port, server does not auto-sync the application after the webhook.

https://github.com/argoproj/argo-cd/blob/0a5023d08e6eb78de510180ead2c630518112518/util/webhook/webhook.go#L162
Maybe adding port part here solve this problem? 
 
**To Reproduce**

1. Register an application with a SSH URL with custom port like: `ssh://git@git.my-company.com:12345/org/repo.git`, and configure auto-sync
2. Register webhook
3. Push to the application repository and fire the webhook
4. Nothing happens

**Expected behavior**

Auto-sync triggers after the webhook.

**Version**

```shell
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:48:19Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:47:48Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**

After webhook triggers:
```
time="2019-12-12T06:35:35Z" level=info msg="Received push event repo: https://git.my-company.com/org/repo, revision: master, touchedHead: true"
time="2019-12-12T06:35:35Z" level=debug msg="ssh://git@git.my-company.com:12345/org/repo.git does not match"
```

**Comment by alexec** [comment]
Would you like to submit a PR to fix?
