### ISSUE TITLE
[UI] Application conditions on application details page

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#287]
Application details page should have information about application `conditions`. Currently one condition is supported: `DeletionError`

**Comment by merenbach** [comment]
@jessesuen I have a WIP PR in at https://github.com/argoproj/argo-cd-ui/pull/4.  I don't believe the UX is done yet.  Interested in how this should look vis-à-vis possibility of multiple conditions, or how labels should be applied (casing, etc.).

**Comment by alexmt** [comment]
I'm proposing following UI:
- add one more sections status panel on application details page. Panel should have number of info/warning/error conditions. 
<img width="1157" alt="1" src="https://user-images.githubusercontent.com/426437/42065532-3c8dfa0e-7af0-11e8-85ff-2af698ef9b97.png">
- if user clicks on conditions summary section then sliding panel should be shown with list of conditions.

This user conditions would be more visible and user would notice warnings/errors sooner

**Comment by alexmt** [comment]
The main motivation is to make clear that application is in an invalid state and some user action required.
