### ISSUE TITLE
[UI] Support app force delete in UI and CLI

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#288]
ArgoCD API supports `force` parameter to force app deletion. We need to support that flag in ArgoCD UI and CLI

**Comment by jessesuen** [comment]
I think when alex said force, he meant the `cascade` feature, which we already have support for. There is no `force` flag to a delete request.

**Comment by merenbach** [comment]
Noting here that it appears that the CLI already does cascading deletion by default, so this looks like a UI-only PR.
