### ISSUE TITLE
RBAC for argocd project

### ISSUE THREAD

**Issue by chiragthaker** [argoproj/argo-cd#2881]
Hi We want to apply RBAC at project level in argocd , so here is my use case

1. Only allows users in github teams x to make all changes in argo project x applications 
2. Users in github team y should not be able to even view apps inside project x
3. I want to acheive this via declarative definetion .

So basically i want to disallow all users by default to see all apps residing in different projects but only allow to operate the apps inside their team argocd project apps.

Argocd version : 1.3.x
RBAC via : Github teams

Please assist.

**Comment by OmerKahani** [comment]
You can do this using: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-rbac-cm.yaml
