### ISSUE TITLE
[CLI] misleading docs for `--helm-set`

### ISSUE THREAD

**Issue by davidkarlsen** [argoproj/argo-cd#2883]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

`--helm-set` docs say:
--helm-set stringArray              Helm set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)

however, comma-separated values are not parsed, you need multiple --helm-set args

**To Reproduce**

set values with `--helm-set somekey1=someval1,somekey2=someval2` - it will fail

**Expected behavior**

Should match help description.

**Screenshots**

N/A

**Version**

```shell
argocd version
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:48:19Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:47:48Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexec** [comment]
Would you like to correct the docs with a PR?

**Comment by davidkarlsen** [comment]
☝️ ignore that PR - it was for another issue
