### ISSUE TITLE
Use neutral colors in network view, not red and green

### ISSUE THREAD

**Issue by rdelpret** [argoproj/argo-cd#2892]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Network view uses different colors to show unique paths between services and ingresses, using the colors red and green are misleading to the untrained eye and may suggest that the ingress is unhealthy or healthy. I spoke to alexander on slack and he said this seems like a reasonable request. 

**Screenshots**

![image](https://user-images.githubusercontent.com/16977200/71033523-702fc580-20e5-11ea-95ee-42e266a27910.png)

**Comment by AceHack** [comment]
I don't understand the colors

**Comment by rsoika** [comment]
I agree with @rdelpret . The colors are very confusing. Better use  green or blue only

**Comment by puddinman** [comment]
++ to @rdelpret. Very confusing, would be nice to add some documentation around this too.

**Comment by kcheemz** [comment]
Confusing :)

**Comment by asaorgad** [comment]
I suggest that the colors will change depending on the data traffic between the services
