### ISSUE TITLE
[UI] - commit message shown as (m.message} on mouse hover

### ISSUE THREAD

**Issue by paidem** [argoproj/argo-cd#2896]
Checklist:

* [+] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [+] I've included steps to reproduce the bug.
* [+] I've pasted the output of `argocd version`.

**Describe the bug**

In UI when hovering over latest commit, the popup shows (m.message} , which seems like a bug.
There should me {m.message} and a message should be rendered.

**To Reproduce**

Hover mouse over last commit message 

**Expected behavior**

Commit message is rendered in popup

**Screenshots**

![argo-cd-bug](https://user-images.githubusercontent.com/1897546/71095593-8d33c980-21b5-11ea-8dd5-e905b3430cce.png)

**Version**

```shell
argocd: v1.3.5+3e150df
  BuildDate: 2019-12-09T21:13:03Z
  GitCommit: 3e150df0ede862c476d2ad0b90717ae00a890551
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:47:48Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**

```
none
```

**Comment by alexmt** [comment]
thank you @paidem !
