### ISSUE TITLE
TLS and authentication support on API Server

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#29]
Need TLS support for the API server with initial basic auth for the admin user.

**Comment by merenbach** [comment]
@alexmt regarding the above, is this just a matter of opening an HTTPS listener and setting up basic HTTP authentication for that?

**Comment by merenbach** [comment]
Issue status update: We now have `argocd install` superuser config (with password hashing into a K8s secret) on `master`.  Now I believe we can focus on the actual login logic, login session management, etc.  I'm beginning work on that now.

**Comment by merenbach** [comment]
Working on authentication support now.

**Comment by merenbach** [comment]
Issue status update: With #84 merged, auth is not yet enabled by default.  Once the Web frontend supports authentication, and any relevant tweaks are made to the backend, this issue may be resolved.

**Comment by merenbach** [comment]
We've merged #84 and now we have the opportunity to work on auth from the Web frontend. cc @alexmt

**Comment by merenbach** [comment]
Update: #100 is out to fix a couple bugs I introduced.

**Comment by merenbach** [comment]
@jessesuen proposing we close as supplanted by #91.

**Comment by jessesuen** [comment]
Agree
