### ISSUE TITLE
Include sub and and iat (for project tokens) in PermissionDenied message

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#2914]
When a project token not exist in the project, and it is used to perform an API request, there is a generic PermissionDenied error returned back. The server should return back some non-sensitive information about the claims, such as the `sub` or `iat` so that the token being used can be identified from pipelines.

I spent a good amount of time debugging a PermissionDenied problem only to discover the token in question was deleted.

I think the logic should be:
* always include JWT `sub` in the PermissionDenied error message
* if PermissionDenied is from a project token, also include `iat` so that it can be traced to a role

Alternatively, or additionally, we could also consider giving a different error message when the token doesn't even exist in the project.

**Comment by rachelwang20** [comment]
Closing - Implementation in https://github.com/argoproj/argo-cd/pull/3850
