### ISSUE TITLE
Allow aliases for removing resources in argocd-cli

### ISSUE THREAD

**Issue by vadasambar** [argoproj/argo-cd#2921]
# Summary
`argocd` cli should allow either of `rm`, `del` or `delete` to remove/delete resources. 

# Motivation
Some of the resources in argocd-cli use `rm` to remove things (e.g. `cluster`) while others use `delete` (e.g. `app`). It is a little difficult to remember when to use `rm` and when to use `delete`. 

# Proposal
Adding aliases so that either of the `rm`, `delete` or `del` would remove the resource through argocd-cli would mean that the user would not have to remember which resource needs the command `argocd <resource> rm` and which resource needs `argocd <resource> delete`. 

How do you think this should be implemented?
`cobra` already provides `Aliases` for commands. We can leverage that to add aliases for existing commands.

**Comment by alexmt** [comment]
Closing based on a conversation in PR
