### ISSUE TITLE
Add age of pod / resource to resource summary page

### ISSUE THREAD

**Issue by rdelpret** [argoproj/argo-cd#2928]
# Summary

I think that it would be helpful to see how long a resource has existed in the cluster in its current revision / state much like kubectl displays resource age when using the get verb.

# Motivation

Time passed since last deployment is available in the history / rollback tab but I think seeing the age of all resources would be helpful 

# Proposal

Perhaps expose overall age in the resource summary as well as time since last update (age starts when a resource is first applied to the cluster, time since last update would be the last time something about that resource changed via argocd)

![image](https://user-images.githubusercontent.com/16977200/71596854-f0572180-2b0e-11ea-92f4-2c31b9f1ef60.png)

**Comment by taisho6339** [comment]
If [This PR](https://github.com/argoproj/gitops-engine/pull/87) is approved, I will create an new Pull Request for this issue immediately.

**Comment by tetchel** [comment]
From above, it looks like this is complete

**Comment by reginapizza** [comment]
Closing this as it's already been completed, looks like PR just didn't link to it and automatically close it.
