### ISSUE TITLE
send logs to splunk

### ISSUE THREAD

**Issue by matancarmeli7** [argoproj/argo-cd#2934]
HI! i saw that you have dashboard xml example for splunk. I don't find a way to connect argo-cd to my splunk, can you guide me how can i  connect it?

Thanks

**Comment by alexmt** [comment]
Hello @matancarmeli7,

Are you referring to https://github.com/argoproj/argo-cd/blob/master/examples/dashboard.json ? This is Grafana dashboard, not splunk dashboard. If you already have Grafana you then you can import Dashboard from file using `+` -> `Import`

**Comment by matancarmeli7** [comment]
hey @alexmt, thanks for responding
I'm actually referring to this dashboard: https://github.com/argoproj/argo-cd/wiki/Splunk
think there is way to connect Argo to Splunk? It seems there is something i just cant find anything but this dashboard.

**Comment by alexmt** [comment]
Oh, I see. The slunk log forwarding is not really Argo CD specific. It should be done at the cluster level. I found this project by splunk: https://github.com/splunk/splunk-connect-for-kubernetes .
