### ISSUE TITLE
Latest released argocd CLI does not work with --sso on Linux

### ISSUE THREAD

**Issue by wojciechka** [argoproj/argo-cd#2956]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When running on Linux (Ubuntu 16.04 in my case), running `argocd login --sso` fails after the OAuth happens with an error that connection was rejected.

This was already fixed by #2564 in October 2019, but this was not backported to `v1.3` branch. The https://github.com/argoproj/argo-cd/blob/release-1.3/cmd/argocd/commands/login.go#L262 is still `open.Run` instead of `open.Start`.

**To Reproduce**

Download the v1.3.6 Linux-x64 binary and try to log in to ArgoCD using any SSO. After logging in to the SSO itself, the redirect to `http://localhost:8085/auth/callback...` returns connection refused error.

**Expected behavior**

Be able to log in to ArgoCD using SSO.

**Version**

Output of `argocd version`:

```
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:46:45Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
```

**Comment by wojciechka** [comment]
I've found a work around for the issue. After a successful OAuth sign in and seeing the error, simply copy the destination URL (`http://localhost:8085/auth/callback...`), close the entire browser and then re-open a browser with the previously copied URL (`http://localhost:8085/auth/callback...`).

**Comment by blakepettersson** [comment]
Closing since this is pretty old
