### ISSUE TITLE
Sync Apps "No App Selected" when name container "."

### ISSUE THREAD

**Issue by drewboswell** [argoproj/argo-cd#2962]
**Describe the bug**
When using a "." in the applications.argoproj.io instance name, sync apps doesn't work.

**To Reproduce**
1. Create a applications.argoproj.io that contains a "." example: "test.something"
2. Got to argo's : "/applications"
3. Select "Sync apps"
4. select "test.something"
5. sync
result -> thinks you didn't select anything

**Expected behavior**

Should be able to select app, and sync.

**Version**

```shell
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:46:45Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
Does not produce logs, neither in the backend, nor in the browser console or network tab.

**Comment by alexmt** [comment]
thank you for bug repo @drewboswell ! PR with the fix: https://github.com/argoproj/argo-cd/pull/2983

**Comment by drewboswell** [comment]
Thanks @alexmt  for getting that done so quickly, it'll help a lot. Any idea when it will make its way into a release?

**Comment by drewboswell** [comment]
oh it looks like it is already. never mind ;)
