### ISSUE TITLE
Blacklisted namespaced resources on project does not work in alicloud

### ISSUE THREAD

**Issue by i300543** [argoproj/argo-cd#2969]
argocd version v1.1.2

**Describe the bug**

the blacklisted namespaced resources setting on argocd project does not seem to work in alicloud

**To Reproduce**

create application using argo in alicloud,
add a resource kind to blacklist,
apply several instances of blacklisted resource in target namespace

**Expected behavior**

blacklisted resources are not shown in the list, and ignored for sync purposes

**Screenshots**
![image](https://user-images.githubusercontent.com/11046606/72221011-41c7cd80-355f-11ea-80fb-1b9bf981a402.png)
![image](https://user-images.githubusercontent.com/11046606/72221079-df230180-355f-11ea-96eb-aa14e2f01638.png)
![image](https://user-images.githubusercontent.com/11046606/72221115-1db8bc00-3560-11ea-9bce-5f241da966a4.png)

**Version**

```shell
root@17b967f5847a:/# argocd version
argocd: v1.1.2+567fcc3.dirty
  BuildDate: 2019-07-30T17:45:54Z
  GitCommit: 567fcc33140ec93051fdf8d0af7ea404deb64f20
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.1.2+567fcc3.dirty
  BuildDate: 2019-07-30T17:47:02Z
  GitCommit: 567fcc33140ec93051fdf8d0af7ea404deb64f20
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

-

**Comment by alexmt** [comment]
The described behavior is working as expected. The blacklisted resources restrict which resources can be deployed by an application but still visible in the user interface. 

If Argo CD hides such resources then it might create a false impression that the application is successfully deployed and confuse the user. So I think it is better to show the resource to make it clear that resource is not deployed. Does it make sense @i300543 ?

**Comment by i300543** [comment]
i thought blacklisted resource means this resource kind is completely ignored by argo for sync purposes, and even even if it is created by 3rd party (e.g. application we are deploying) it is ignored by argocd, and does not change the application state to 'not synced'

If you say this is not the purpose of this configuration, is there another way for me to configure argo to ignore resources of a specific kind ?
my use-case is as follows:
we deploy velero in our cluster (open source for backing up and restoring k8s resources (yamls)
we also create a 'schedule'(crd) which automatically creates 'backups'(crds) every 10 minutes.
as those backup crds are not part of the original installation, and do not exist in github, argo shows them as unsynced.
we want argo to ignore those generated crds for sync purposes completely. is there a way for us to achieve this ?

Thanks

**Comment by i300543** [comment]
also when configured on aws based cluster the behavior is different - those 'backup' crd instances do not show up on argocd ui like they do in alicloud.
i would expect the behavior to be consistent across different cloud providers

**Comment by alexmt** [comment]
Sorry @i300543 , I completely forgot to reply.
The Argo CD should try to sync resources only if the resource manifest is in Git or was deployed by Argo CD earlier and then deleted from Git. 

Do CRD instances have `http://app.kubernetes.io/instance`?  Argo CD uses that label to mark resources deployed by Argo CD: https://argoproj.github.io/argo-cd/faq/#why-is-my-app-out-of-sync-even-after-syncing. If this is the case then you could remove that label as a workaround.

**Comment by i300543** [comment]
yes those resources have the label:
app.kubernetes.io/instance: velero
it seems that your workaround fixes the issue with the conflicting label:
adding:
"application.instanceLabelKey": "argocd.argoproj.io/instance"
to argocd-cm configmap, and then syncing the application resolves the issue:
 https://argoproj.github.io/argo-cd/faq/#why-is-my-app-out-of-sync-even-after-sync

Thank you !

**Comment by HumairAK** [comment]
Hrmm, we've just hit a similar issue, where we have restricted an argocd project from deploying cluster resources, but the team has these cluster resources as part of their kustomization in their repos. Their application will not deploy and report the same errors as above: "Resource X is not permitted in project Y" 

> If Argo CD hides such resources then it might create a false impression that the application is successfully deployed and confuse the user.  

What if the user could change this at the application level like with [ignoreDifferences](https://argoproj.github.io/argo-cd/user-guide/diffing/#application-level-configuration)? For example something like: 

```
  ignoreResources:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: example-role  # optional
```
Then the list of resources being filtered is tracked and made clear in the application manifest itself.

**Comment by jgwest** [comment]
Alex has addressed the primary concerns of this issue, additional feedback can be moved into a separate enhancement, if still required.
