### ISSUE TITLE
call argocd-server from client - navigating auth

### ISSUE THREAD

**Issue by ryandawsonuk** [argoproj/argo-cd#2982]
We'd like to be able to call the argocd server APIs from a programmatic client. I see that the argocd CLI does this but the auth looks a bit tricky to navigate, partly because the password grant flow isn't supported. I guess this is a [dex question in general](https://github.com/kubeflow/kfctl/issues/140) but any pointers on how best to do this would be much appreciated.

**Comment by ryandawsonuk** [comment]
We might go with putting in our own auth gateway and using `--disable-auth`

**Comment by alexmt** [comment]
hello @ryandawsonuk , 

You might use project role access token: https://argoproj.github.io/argo-cd/user-guide/projects/#project-roles . The token might be created via UI/CLI. I hope this helps.

**Comment by ryandawsonuk** [comment]
This works great thanks
