### ISSUE TITLE
AgoApp that syncs to a list of clusters

### ISSUE THREAD

**Issue by reggie-k** [argoproj/argo-cd#2986]
# Summary

It might be nice, when managing multiple clusters, for k8s manifests that are identical among different k8s target clusters, if an Argo App could sync to a list of specified clusters instead of a single one

# Motivation

To reduce the amount of Argo Apps on the source cluster. When a certain state needs to be replicated to multiple target clusters, it seems redundant to create one more app that points to, potentially, the same git repo, just to change the cluster field. 

# Proposal

The app should sync to a list of clusters, the list should be enabled on the project too. Perhaps a separate status icon is needed, to indicate that sync to one of the clusters failed. I guess that an option to sync only to one of the clusters in the list should exist. Meaning, the filter that exists today, where I can sync all, none, or only out of sync resources, has to have an option to sync to one or some of the target clusters of the app.

**Comment by OmerKahani** [comment]
Hi, this seems like a dup for: https://github.com/argoproj/argo-cd/issues/1673
@reggie-k does issue 1673 describe the same thing?

**Comment by reggie-k** [comment]
Thanks, indeed. I overlooked it. Too bad it's not in the roadmap.

**Comment by jessesuen** [comment]
Duping to https://github.com/argoproj/argo-cd/issues/1673. This will be addressed with ApplicationSets.
