### ISSUE TITLE
fetch repo timeout

### ISSUE THREAD

**Issue by volodyad** [argoproj/argo-cd#2991]
I have tried repo from gitlab

repo server logs show an error 
time="2020-01-17T10:25:19Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = Failed to fetch git repo: `git fetch origin --tags --force` failed timeout after 1m30s" grpc.code=Internal grpc.method=ListApps grpc.request.deadline="2020-01-17T10:16:41Z" grpc.service=repository.RepoServerService grpc.start_time="2020-01-17T10:15:41Z" grpc.time_ms=578054.25 span.kind=server system=grpc
time="2020-01-17T10:25:19Z" level=info msg="git fetch origin --tags --force" dir="/tmp/https:__gitlab.repoPath" execID=kuwEy

Repo is quiet old, and have lots of data so it might take some time to download it.
Can I increase timout interval somewhere in settings?

**Comment by volodyad** [comment]
Deplicate of https://github.com/argoproj/argo-cd/issues/2553

**Comment by crenshaw-dev** [comment]
I believe @Gnote3 fixed this by setting `ARGOCD_EXEC_TIMEOUT`. I'm going to open a PR to get that env var better documented.
