### ISSUE TITLE
Circular Application path always shows as degraded.

### ISSUE THREAD

**Issue by dmayle** [argoproj/argo-cd#2995]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When you have two different Application objects, each of which is managing the other's Application, then argo-cd thinks that both are in a degraded state, even though neither is.

It may sound like an unusual setup, but I'm bootstrapping my cluster.  My argo-cd application contains the "App of Apps" root, and the root contains the definition for the argo-cd application.  This way, all I have to manually install is the argo-cd application, and the rest builds itself up.

**To Reproduce**

It's super simple to setup with one repository and two subpaths like so:
```
~/repo
├── first
│   ├── resources.yaml
│   └── second-application.yaml
└── second
    ├── other_resources.yaml
    └── first-application.yaml
```

**Expected behavior**

Ideally, argo-cd would be able to safely detect the loop (by marking apps and choosing not to redescend), but if you want to declare this as non-supported, I would understand that choice.

**Version**

```shell
penguin:~$ argocd version
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:46:45Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:47:48Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Comment by TomHellier** [comment]
I'm having the same problem, I'm using the argocd helm chart and the additionalApplications to deploy an app-of-apps which also includes the argocd that I'm deploying.

https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml#L472

I think this should be supported behaviour because it follows neatly on from the app-of-apps to have a bootstrappable app-of-apps.

**Comment by TomHellier** [comment]
Relates to following issues:
* https://github.com/argoproj/argo-cd/issues/1533

Relates to following PRs:
* https://github.com/argoproj/argo-cd/pull/1954
* https://github.com/argoproj/argo-cd/pull/1547
* https://github.com/argoproj/argo-cd/pull/1608

It doesn't look like an easy fix, I guess how far is reasonable to traverse to find a loop, I suggest one level is probably enough to solve our problem.

```
argocd -> app-of-apps -> argocd
   |                       |
   --------------<----------
```
And I'd imagine we only want to ignore the degraded status if they are both degraded (and no other child resources of both Applications are).
