### ISSUE TITLE
set KUBE_VERSION and KUBE_API_VERSIONS env variables for custom plugins

### ISSUE THREAD

**Issue by travisghansen** [argoproj/argo-cd#2997]
# Summary

Set the `ENV` vars so plugins can have access to the required data during rendering processes.

# Motivation

I'm building a custom `helmfile` integration which invokes `helm` behind the scenes. To sanely invoke the commands I'll need access to the data that's appropriate to a given cluster.

# Proposal

Just set the vars in the execution environment of the `init` and `generate` phases.

**Comment by mayzhang2000** [comment]
This is fixed in https://github.com/argoproj/argo-cd/pull/3318

**Comment by travisghansen** [comment]
@mayzhang2000 thanks!
