### ISSUE TITLE
Label apps with commit ID

### ISSUE THREAD

**Issue by matancarmeli7** [argoproj/argo-cd#3001]
# Summary

Label apps with commit ID.

# Motivation

Im looking to monitor my deployments statuses over multiple clusters from my main Splunk.
Labeling each app with the current commit id that it's deployed from, will help noting which are up to date and which are not from my main monitoring console.

# Proposal

You already save the commit id in the Argo side, so i suggest adding that as a label to the deployment.

**Comment by redbaron** [comment]
Commit id is available in build environment (https://argoproj.github.io/argo-cd/user-guide/build-environment/) , anything but Kustomize can make use of it.

**Comment by jgwest** [comment]
Based on comment, this appears in addressed in all environment where that is possible.
