### ISSUE TITLE
UI with multiple SSO provider render one button and name it with first provider found 

### ISSUE THREAD

**Issue by rayanebel** [argoproj/argo-cd#3009]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
Hello everyone,
I deployed `argocd 1.4` on an Openshift cluster and I've configured multiple SSO provider: One to login with Github and another to login with Openshift.

Now, when we save this configuration and we refresh argocd ui I have only one button `Login with Github` and when I clicked on it I'm redirected to dex and here I can choose my authentication provider.

```bash
apiVersion: v1
data:
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: XXXXXXXXXXXXXX
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: XXXXXXXXXXXX
      - type: openshift
        id: openshift
        name: OpenShift
        config:
          issuer: https://XXXXXXXXXXXXXXXXXXXX:443
          clientID: system:serviceaccount:eb-cicd-eu-dev-axa-ebp-fr:argocd-dex-server
          clientSecret: $dex.openshift.clientSecret
          redirectURI: https://XXXXXXXXXXXXXXXX/api/dex/callback
          insecureCA: true
  url: https://xxxxxxxxxxxx
kind: ConfigMap
metadata:
  creationTimestamp: "2019-12-19T15:44:06Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argocd-1.3.6
  name: argocd-cm
```

**To Reproduce**

* Deploy argocd 1.4
* Configure at least two SSO provider
* Refresh argocd UI

**Expected behavior**

One global button called `SSO Login` which will redirect to dex or one button per provider configured.

**Screenshots**

<img width="1280" alt="screen-1" src="https://user-images.githubusercontent.com/15887095/72820260-f30ce880-3c6e-11ea-8529-f4ae1cd93ae2.png">
<img width="1280" alt="screen-2" src="https://user-images.githubusercontent.com/15887095/72820261-f30ce880-3c6e-11ea-983b-eddced898d31.png">

**Version**

```shell
argocd: v1.4.0-rc1+5af52f6
  BuildDate: 2020-01-13T17:23:04Z
  GitCommit: 5af52f66988ad8fa0d6b977d7f5aedcdb9f5a521
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.0+2d02948
  BuildDate: 2020-01-18T05:55:02Z
  GitCommit: 2d029488aba6e5ad48b2a756bfcf43d5cb7abcee
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**

No logs.

**Comment by jannfis** [comment]
@rayanebel Can this issue be closed with your PR merged now?

**Comment by alexmt** [comment]
I'm pretty sure we can close it.
