### ISSUE TITLE
v1.4 SSH credential template not working

### ISSUE THREAD

**Issue by lanmarti** [argoproj/argo-cd#3016]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Trying to add a credential template for SSH repositories seems to fail.

I've replaced our companies github url with [enterprise github] and the name of the github organization I'm trying to add repos from with [organization] in the code below.

The help page for `argocd repocreds` states:
```
# Add credentials with SSH private key authentication to use for all repositories under https://git.example.com/repos
  argocd repocreds add https://git.example.com/repos/ --ssh-private-key-path ~/.ssh/id_rsa
```
this results in:
```
$ argocd repocreds add https://[enterprise github]/[organization-name]/ --ssh-private-key-path ~/.ssh/argo
FATA[0000] --ssh-private-key-path is only supported for SSH repositories.
```

Assuming the help page is incorrect, I tried using the SSH url instead, as one would when adding a single repo. An error gets thrown because of the '@':
```
$ argocd repocreds add git@[enterprise github]:[organization] --ssh-private-key-path ~/.ssh/argo
FATA[0000] rpc error: code = InvalidArgument desc = Secret "repo-git@[enterprise github]:[organization]-3092902216" is invalid: metadata.name: Invalid value: "repo-git@[enterprise github]:[organization]-3092902216": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
Leaving out the `git@` part:
```
$ argocd repocreds add [enterprise github]:[organization] --ssh-private-key-path ~/.ssh/argo
FATA[0000] --ssh-private-key-path is only supported for SSH repositories.
```

**Expected behavior**

A template that causes ArgoCD to automatically uses the given private key when fetching repos of the specified organization.

**Version**

```shell
argocd: v1.4.0+2d02948
  BuildDate: 2020-01-18T05:53:00Z
  GitCommit: 2d029488aba6e5ad48b2a756bfcf43d5cb7abcee
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.4.0+2d02948
  BuildDate: 2020-01-18T05:55:02Z
  GitCommit: 2d029488aba6e5ad48b2a756bfcf43d5cb7abcee
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Comment by jannfis** [comment]
You are right, the example of the `repocreds add` command is wrong for the SSH example, will fix that ASAP, thank you for bringing it up!

As for the error you encounter with the correct SSH URL (i.e. `git@...`), can you please try using a "qualified" SSH URL, i.e. "ssh://git@yourgithub/yourorg" instead of `git@yourgithub:yourorg` and check if that does work? I suspect you are using a non-standard SSH port, and specify that in the scp-style URL (which is not allowed). Is that correct?

The error message you see comes from K8s API when it tries to create the secret for your credential template, and the `git@` string should definitely not part of it. The error message says `Secret "repo-git@[enterprise github]:[organization]-3092902216" is invalid`, but the secret's name should rather be `repo-[organization]-3092902216` instead.

I have just tried it locally with both variants (`git@...` and `ssh://git@...`), and for me, both work.

**Comment by lanmarti** [comment]
As you suggested, I can add the repo credentials if I prefix it with 'ssh://' and change the ':' to '/'. It appears that when creating apps, the repo's relying on this template have to be added in the exact same way, e.g. `ssh://git@foo.bar/org/repo.git`.
In contrast, when `repo add`ing a single repo at a time and using those repo's in apps, I can use the more common format, e.g. `git@foo.bar:org/repo.git`, both when registering the repo as well as when referring to it in the app. From my ignorant point of view it's a bit weird that `repocreds add` seems to handle the URLs differently than `repo add`.

Thank you!

**Comment by lanmarti** [comment]
> I suspect you are using a non-standard SSH port, and specify that in the scp-style URL (which is not allowed). Is that correct?

I do think our github is on port 22 (standard SSH), but this is far from my area of expertise. Our BitBucket uses a custom port, but there we automatically get the fully quailified URL (e.g. ssh://git@your.github:[custom-port]/your.org/repo.git ). It seems github by default uses an scp-like syntax for its clone links. Is it somehow possible that `repo add` can process those, but `repocreds add` can not?

**Comment by jannfis** [comment]
Thanks for the response @lanmarti and I'm glad that at least the workaround works for you. There is #2576, but I guess its scope/effect is unfortunately much further than initially thought.

I think we can all agree upon that `repo add` and `repocreds add` as well as `--repo` parameter for `app create` should treat all URLs completely the same, but do not currently. I will investigate further. Meanwhile, would you mind providing me the exact URL string you have passed to `repocreds add` that did not work? I understand this might be sensitive information and you don't want to have it up on a public issue in GitHub, but maybe we can find another way, i.e. a private Gist or something along these lines?

**Comment by lanmarti** [comment]
I have created a private gist and mentioned you. Please let me know if you are unable to find it, or if you need any other information from me.

**Comment by jannfis** [comment]
Thanks a lot, I have received it and can also reproduce the issue now. Nothing wrong at all with your connection string. 

I guess it boils down to a trailing slash, i.e. using `git@github.com:argoproj` will error, while `git@github.com:argoproj/` will work just fine. Depending on that trailing slash, the string seems to be parsed differently.

**Comment by alexmt** [comment]
Nice workaround @jannfis !
