### ISSUE TITLE
Disable admin login

### ISSUE THREAD

**Issue by dontreboot** [argoproj/argo-cd#3019]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
This is not really a bug. I'd like to know if it's possible to disable admin login via argocd configmap updates and re-enable if needed. We have SSO setup for argocd so it's very rare for people to use the admin account. Having admin access available could lead to potential unintended access.

**To Reproduce**

n/a

**Expected behavior**

See **Describe the bug**

**Screenshots**

**Version**
All

**Comment by jannfis** [comment]
I imagine you could set `admin.password` in `argocd-secret` to some invalid value, effectively disabling logins via the admin account.

**Comment by dontreboot** [comment]
> I imagine you could set `admin.password` in `argocd-secret` to some invalid value, effectively disabling logins via the admin account.

Thanks for the suggestion. btw, what is the significance of admin.passwordMtime?

**Comment by jannfis** [comment]
@dontreboot The `admin.passwordMtime` field contains the timestamp of when the current admin password was set. All JWT tokens issued before this timestamp will become invalid and have to be re-issued.
