### ISSUE TITLE
Enable code coverage

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo-cd#302]
Add regression tests for Argo CD server, and CLI. All changes need to be backwards compatible and regression tests should be available to prove backwards compatibility.

**Comment by jessesuen** [comment]
Blocked by cluster which can store s3 artifacts

**Comment by jessesuen** [comment]
Investigate https://coveralls.io/

**Comment by merenbach** [comment]
@jessesuen status update: it looks as though Travis CI is the preferred method of integration for Coveralls.io.
