### ISSUE TITLE
Opening in new tab bad key binding on Linux

### ISSUE THREAD

**Issue by lbenedetto** [argoproj/argo-cd#3020]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I couldn't figure out how to open applications in a new tab, but found this issue saying that it was Cmd+Click on a Mac.

https://github.com/argoproj/argo-cd/issues/732

Ctrl + Click wasn't working for me in Linux Mint on Vivaldi browser.
However, Windows Key + Click does work, sort of.

It can only be used to open a single new tab, and each subsequent click just re-navigates that tab.

Worse of all though, every time I use Windows Key + Click, it opens up the Linux start menu, and I have to then click back into the browser.

Can this be changed to a more sensible binding? Like ctrl+click, or even just middle click like on every other website.

**To Reproduce**

Windows Key + Click on an application on Linux.

**Expected behavior**

Should open 1 new tab for each application clicked, and not open the start menu.

**Version**

```shell
argocd: v1.4.0+2d02948
  BuildDate: 2020-01-18T05:53:00Z
  GitCommit: 2d029488aba6e5ad48b2a756bfcf43d5cb7abcee
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.4.0+2d02948
  BuildDate: 2020-01-18T05:55:02Z
  GitCommit: 2d029488aba6e5ad48b2a756bfcf43d5cb7abcee
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Comment by jannfis** [comment]
@lbenedetto This should be included in one of the next builds, either in `latest` or in `1.4.3`

**Comment by alexmt** [comment]
@jannfis just FYI. You PR in argo-ui library was merged: https://github.com/argoproj/argo-ui/commit/dfb546b760e259d8960f0d4408f94981602bc18d

We need to update the dependency in argo-cd. The ` yarn add https://github.com/argoproj/argo-ui.git` would do it.

**Comment by jannfis** [comment]
Ah thanks @alexmt - just saw that it's pinned to a commit SHA. I was wrongly assuming that next builds will automatically update the dependency. Just sent #3038 with an update to `yarn.lock` :)
