### ISSUE TITLE
Support cluster creation from UI

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#303]
We would like to support cluster creation from UI and not just CLI. Currently CLI will install the serviceaccount, role, role-binding to the managed cluster, but in order to support this from UI, we need to move this logic server side.

The ClusterCreateRequest will need a new field which takes a kubeconfig as a string. This kubeconfig is used temporarily to just to install the argocd-manager account, and thrown away at the end of the request.

**Comment by alexmt** [comment]
Two PRs are resolving issue:

https://github.com/argoproj/argo-cd/pull/425
https://github.com/argoproj/argo-cd-ui/pull/19

Additional we need to try to improve https://github.com/coreos/dex/issues/1263 . Once dex ticket is resolved we will get better login error message.

**Comment by merenbach** [comment]
@jessesuen what does installing/deleting the argocd-manager account look like?  Does this need to be done prior to testing the cluster RESTConfig in cluster#Create?

**Comment by jessesuen** [comment]
Spoke with @alexmt. We agreed on adding a new API method in the ClusterService to handle this style of cluster creation. The method and request object would be:

```
message ClusterCreateFromKubeConfigRequest {
	string kubeconfig = 1;
	string context = 2;
}

// ClusterService 
service ClusterService {

	// CreateFromKubeConfig installs the argocd-manager service account into the cluster specified in the given kubeconfig and context
	rpc CreateFromKubeConfig(ClusterCreateFromKubeConfigRequest) returns (github.com.argoproj.argo_cd.pkg.apis.application.v1alpha1.Cluster) {
		option (google.api.http) = {
			post: "/api/v1/clusters-kubeconfig"
			body: "*"
		};
	}
```

The logic which is currently happening in the CLI, would instead go to the handler of this new endpoint.
