### ISSUE TITLE
Applications do not get deleted

### ISSUE THREAD

**Issue by isabo-lola** [argoproj/argo-cd#3041]
Checklist:

[ *] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
[ *] I've included steps to reproduce the bug.
[ *] I've pasted the output of `argocd version`.

**Describe the bug**

Whenever an application gets deleted with "cascade delete" from the UI some components get stuck in terminating/deletion state and the whole application hungs with the "deletion" status. Some specific K8s objects that have inconsistent behaviour upon deletion are PVCs, Routes and Secrets. 

**To Reproduce**

Create an application with multiple components and delete it with cascade delete. 

**Expected behavior**

The application gets deleted along with resources associated with it. 

**Screenshots**

**Version**

```shell
argocd: v1.4.1+f8721a7
  BuildDate: 2020-01-22T23:00:03Z
  GitCommit: f8721a73609611dd481886a78f4b7ce16ef8747b
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

ArgoCD is deployed and is deploying applications inside an Openshift 3.11 cluster.

**Comment by jessesuen** [comment]
Please check deletion timestamp on the resources. If it is set, then argo cd has done it's job and it's now waiting for the resource to disappear from the cluster, which is environmental.

**Comment by alexmt** [comment]
@isabo-lola , let us know please if @jessesuen suggestion helped.

**Comment by Ognian** [comment]
I think I hit the same issue:
I'm deploying bitnami keycloak in k3s (on k3os). When deleting the app everything is got deleted except the pvc.
metadata.deletionTimestamp is NOT set on the pvc...
