### ISSUE TITLE
Using the suggested HA tweaks for application controller causes repo server to consume much more memory and cpu

### ISSUE THREAD

**Issue by carlosjgp** [argoproj/argo-cd#3048]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Unexpected resource consumption increase on the `argo-repo-server` after tweaking the parameters suggested on for HA deployments on [ArgoCD documentation](https://argoproj.github.io/argo-cd/operator-manual/high_availability/)

**To Reproduce**

We deploy ArgoCD using HA manifests provided on this repository
https://github.com/argoproj/argo-cd/blob/v1.4.2/manifests/ha/namespace-install.yaml

We currently have 200 apps (and growing) and we are experiencing some slowness on the time commit to deploy (at least perceived slowness I don't have metrics for this)

After applying the changes suggested for HA deployments on [ArgoCD documentation](https://argoproj.github.io/argo-cd/operator-manual/high_availability/) we have experienced a high memory and CPU usage from the `argocd-repo-server` component after finding a balance

Specifically `--status-processors=50` and `--operation-processors=25` as you mentioned on
> controller uses two separate queues to process application reconciliation (milliseconds) and app syncing (seconds). Number of queue processors for each queue is controlled by --status-processors (20 by default) and --operation-processors (10 by default) flags. Increase number of processors if your Argo CD instance manages too many applications. For 1000 application we use 50 for --status-processors and 25 for --operation-processors

We also apply this `--repo-server-timeout-seconds=300` and `replicas: 10`
> The manifest generation typically takes the most time during reconciliation. The duration of manifest generation is limited to make sure controller refresh queue does not overflow. The app reconciliation fails with Context deadline exceeded error if manifest generating taking too much time. As workaround increase value of --repo-server-timeout-seconds and consider scaling up argocd-repo-server deployment.

**Expected behavior**

Load increased on `application-server` as the parameters tweaked are only meant to affect this "monolithic" component but not on the `repo-server` component (or document the impact of tweaking these parameters for other components 

**Screenshots**

Repo server performance impact

CPU usage
![cpu-usage](https://user-images.githubusercontent.com/1277613/73367878-08ee5f00-42a8-11ea-8838-8c491e970b3b.png)

Memory usage
![memory-usage](https://user-images.githubusercontent.com/1277613/73367903-10ae0380-42a8-11ea-988d-4fe4b6e8e4eb.png)

**Version**

```shell
docker run --rm argoproj/argocd:v1.4.2 argocd version
time="2020-01-29T15:09:10Z" level=fatal msg="Argo CD server address unspecified"
```
From the ArgoCD UI
```
v1.4.2+48cced9
```

**Logs**

Not sure which logs could be relevant here... let me know if you are interested in any component or all of them

**Comment by jessesuen** [comment]
It's expected if controller workers increase, the repo server load will also increase. We have tunables in the repo-server to implicitly limit memory by limiting the number of concurrent fork/execs that happen inside the repo-server. See documentation:

https://argoproj.github.io/argo-cd/operator-manual/high_availability/#argocd-repo-server
```
argocd-repo-server fork/exec config management tool to generate manifests. The fork can fail due to lack of memory and limit on the number of OS threads. The --parallelismlimit flag controls how many manifests generations are running concurrently and allows avoiding OOM kills.
```
