### ISSUE TITLE
argocd-dex-server degrades to Init:CrashLoopBackOff

### ISSUE THREAD

**Issue by shelby-moore** [argoproj/argo-cd#3070]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

argocd-dex-server degrades to Init:CrashLoopBackOff after it has been deployed. Additionally, login via SSO starts to fail with a "unknown app state PvWcoRrgCV". It's unclear whether the two are related.

**To Reproduce**

1. Deploy the latest stable HA manifests:
```
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v1.4.2/manifests/ha/install.yaml
```

2. Modify the argocd-cm configmap with a SAML connector. I used Okta.

3. Wait for awhile. These two issues manifest in under an hour. 

**Expected behavior**

argocd-dex-server stays in a Running state and login via SSO works.

**Version**

```shell
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:48:19Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**

From the argocd-dex-server copyutil container logs:

```
cp: cannot create regular file '/shared/argocd-util': Text file busy
```

From the argocd-server logs:

```
level=error msg="Failed to set app state: READONLY You can't write against a read only replica."
```

If I delete one of the argocd-redis-ha-server pods SSO will start to work again; however argocd-dex-server remains in Init:CrashLoopBackoff

**Comment by shelby-moore** [comment]
Spent some time investigating the init container crashing - restarts of it will break, as the command it runs on start up is:

`cp /usr/local/bin/argocd-util /shared`

This file will already exist if the init container has already been run. I've submitted a PR with a suggested fix (https://github.com/argoproj/argo-cd/pull/3136). This PR changes the command so it does not clobber over the file if it already exists:

`cp -n /usr/local/bin/argocd-util /shared`

Note this is definitely not related to the `unknown app state` login with SSO issue also documented in this Github issue. I'll take a look at that as well.

**Comment by alexmt** [comment]
Closing issue since it was fixed by https://github.com/argoproj/argo-cd/pull/3136 

@shelby-moore , let me know if I'm missing something please.
