### ISSUE TITLE
Question about webhook

### ISSUE THREAD

**Issue by eroji** [argoproj/argo-cd#3089]
I'm following the documentation on https://argoproj.github.io/argo-cd/operator-manual/webhook/ with a on-prem BitBucket server. I did not set up a secret as the documentation states that it's optional. However, it doesn't seem to work. Calling the /api/webhook endpoint does not trigger an immediate refresh on Argo end.

**Comment by reggie-k** [comment]
Please see #2803. I plan to work on this but still don't know the time frame. We also use gitlab in our org, so meanwhile I moved the bitbucket repo Argo listens to to gitlab

**Comment by eroji** [comment]
@reggie-k thank you for the confirmation. I came up with a workaround that seems to fit my usecase. I wrote this as Flask endpoint to proxy calls to our registry and ArgoCD. BitBucket sends a POST request, whereas GET can also trigger the refresh.

```
def get_argocd_token():
    u = "%s/api/v1/session" % argocd_endpoint
    h = {"Content-Type": "application/json"}
    d = {"username": argocd_user, "password": argocd_pass}
    r = requests.post(url=u, headers=h, data=json.dumps(d), verify=False)
    return r.json()['token']

@app.route('/argocd/refresh/<app>', methods=["GET", "POST"])
def argocd_refresh(app):
    h = {"Authorization": "Bearer %s" % get_argocd_token(), "Content-Type": "application/json"}
    if app == "all":
        u = "%s/api/v1/applications" % argocd_endpoint
        r = requests.get(url=u, headers=h, verify=False)
        for a in r.json()['items']:
            u = "%s/api/v1/applications/%s?refresh" % (argocd_endpoint, a['metadata']['name'])
            r = requests.get(url=u, headers=h, verify=False)
        return jsonify({'refreshed' : 'all'})
    else:
        u = "%s/api/v1/applications/%s?refresh" % (argocd_endpoint, app)
        r = requests.get(url=u, headers=h, verify=False)
        return r.json()
```
