### ISSUE TITLE
Can't apply --label in CLI app create

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-cd#3090]
Trying to add labels via:
   argocd app create myapptest .... --label mylabel=test

But no labels are added to the K8S objects!

-l, --label stringArray                  Labels to apply to the app

**Comment by jannfis** [comment]
What version of ArgoCD are you using and what do you expect? 

The label is only added to the application resource, not to the resources created by the app:

```shell
$ argocd app create guestbook -l foo=bar --repo https://github.com/argoproj/argocd-example-apps --path guestbook --dest-namespace guestbook --dest-server https://kubernetes.default.svc
application 'guestbook' created
$ kubectl get applications.argoproj.io guestbook -o yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2020-02-07T13:51:23Z"
  generation: 2
  labels:
    foo: bar
  name: guestbook
  namespace: argocd
  ...
```

**Comment by emichaf** [comment]
Ok Thnx for the info!

**Comment by rosscdh** [comment]
+1 i would expect the labels to be applied to all resources as well (in fact this is really useful for kustomize deployments as it lets you define certain dynamic values)
