### ISSUE TITLE
Just created JWT token removed after clicking Update 

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-cd#3091]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When a user creates a JWT token through the project UI and then clicks the update button, the update request sent by the UI doesn't have the newly created token in the payload. As a result, the new JWT token is invalidated. Additionally, when the user clicks the project again, the old invalidated JWT token is shown again. Also, we should information on what users should provide to the  

**To Reproduce**

1. Create a role within a project
1. Create a JWT token
1. Click the Update button to update the project
1. Click the role again to see the invalidated token

**Expected behavior**

1. Clicking Update doesn't remove the newly created JWT token
1. Clicking the role doesn't show the token again
1. The expires at textbox has information on what users need to provide

**Comment by ciiay** [comment]
@dthomson25 Could you confirm if this issue still exists? I tried to reproduce it, after clicking update button, the JWT token still shows up.
