### ISSUE TITLE
Disaster Recovery export fails with permission denied loading kube config

### ISSUE THREAD

**Issue by kdubkris** [argoproj/argo-cd#3094]
**Error Message**
```
Error loading config file \"/home/argocd/.kube/config\": open /home/argocd/.kube/config: permission denied
```

**Bug Description**
 A permission error results from following the instructions found in the [docs on disaster recovery export](https://argoproj.github.io/argo-cd/operator-manual/disaster_recovery/) 
See the example below.  

The permission error seems to be from within the container that it cannot access its own kube config.  I'm assuming that is supposed to be populated from the host system's kube config, but I'm honestly not sure where it is getting that info from.

I had a buddy confirm my finding and he got the same behavior.

**To Reproduce**

Simply run the command found in the example.  You'll obviously need the docker daemon running, the ability to use the argo cli, etc

**Expected behavior**

A file should appear in my working directory named argobackup.yaml

**Example**

```
➜  ~ docker run -v ~/.kube:/home/argocd/.kube --rm argoproj/argocd:v1.3.6 argocd-util export > argobackup.yaml

time="2020-02-07T22:58:40Z" level=fatal msg="Error loading config file \"/home/argocd/.kube/config\": open /home/argocd/.kube/config: permission denied"
```
**Version**
```
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:46:45Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:47:48Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Comment by kdubkris** [comment]
I figured this out.  The volume was mounted under user 1000, while the argocd user runs as user 999.  Adding the flag `--group-add 1000` resolved the issue for me, though I'm sure there are other methods that would work.  I suggest the documentation on disaster recovery be updated to include this.

**Comment by tanvir-appveen** [comment]
> I figured this out. The volume was mounted under user 1000, while the argocd user runs as user 999. Adding the flag `--group-add 1000` resolved the issue for me, though I'm sure there are other methods that would work. I suggest the documentation on disaster recovery be updated to include this.

I'm using port-forwarding to access argocd. This didn't work for me.

**Comment by sh3llf1sh** [comment]
May not be the best solution, but if you just want a working solution you can use:

`docker run -v ~/.kube:/root/.kube --rm --user root -t argoproj/argocd:$VERSION argocd-util export > backup.yaml`

**Comment by benjaminxie** [comment]
This is the command that finally worked for me

`docker run -v ~/.kube:/home/argocd/.kube -u <host uid>:<host gid> --rm -e KUBECONFIG=/home/argocd/.kube/config quay.io/argoproj/argocd:$VERSION argocd admin export -n argocd > backup.yaml`

Setting `--user` to the owner id and group id for .kube (should be the same as host) and setting the `KUBECONFIG` environment variable aren't necessary if you're using Docker for Mac because it'll take measures to avoid these mounted file permission issues, but otherwise you need to.

Setting the user to root (`--user root`) also worked.
