### ISSUE TITLE
Enhancement Proposal (UI): provide docs to sync policy options present in create application panel. 

### ISSUE THREAD

**Issue by Elgarni** [argoproj/argo-cd#3098]
# Summary

_What change you think needs making._

When creating an app through the UI, sync policy has two options: `Prune Resources` and `Self Heal`. These options are not meaningful enough, and further docs will be useful if available in the UI panel.

Also `Self Healing` is not detailed in the use guide. So adding a docs section for that will be helpful.
 
# Motivation

Whoever is getting started with Argo CD will not be familiar with these terminology, and it can be misunderstood. 

# Proposal

_How do you think this should be implemented?_

Proposed solution: Add help icons next to each option.

This is the original panel:

<img width="748" alt="Screen Shot 2020-02-09 at 4 33 18 AM" src="https://user-images.githubusercontent.com/34614644/74094649-cb82a080-4af5-11ea-8895-9c1792848cf1.png">

After adding the help icons, it will look like this:

<img width="571" alt="Screen Shot 2020-02-09 at 4 35 12 AM" src="https://user-images.githubusercontent.com/34614644/74094680-2b794700-4af6-11ea-8856-ca82a046aece.png">

`prune resources` help icon text:

<img width="571" alt="Screen Shot 2020-02-09 at 4 35 53 AM" src="https://user-images.githubusercontent.com/34614644/74094683-346a1880-4af6-11ea-8cc4-0b965b8e8dfe.png">

`self heal` help icon text:

<img width="571" alt="Screen Shot 2020-02-09 at 4 36 03 AM" src="https://user-images.githubusercontent.com/34614644/74094684-37fd9f80-4af6-11ea-8d33-0400a656a7a0.png">

I also think the user guide should have further details about `Self Healing`. The following section can be added:

> ## Automatic Self-Healing
> By default, changes that are made to the live cluster will not trigger automated sync. To enable automatic sync when the live cluster's state deviates from the state defined in Git, run:
> ```bash
> argocd app set <APPNAME> --self-heal
> ```
> Or by setting the self heal option to true in the automated sync policy:
> ```yaml
> spec:
>   syncPolicy:
>     automated:
>       selfHeal: true

If curious to see code, check it out here https://github.com/Elgarni/argo-cd/tree/ui-add-docs-in-create-applications-panel

**Comment by Elgarni** [comment]
@jannfis @alexec Any thoughts on this?

**Comment by alexmt** [comment]
@Elgarni , I 100% agree with the proposal. 

Looks like you've implemented the changes already :) Could you please send a pull request?

**Comment by jannfis** [comment]
I also think this would be a good idea, @Elgarni :+1:
