### ISSUE TITLE
Limit the set of namespaces search for project resources to those list as destinations of the project.

### ISSUE THREAD

**Issue by klfgit** [argoproj/argo-cd#3102]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Argo currently searches all namespace in a cluster when looking for resources associated with an App.  It should only search the namespaces listed as destination of the project to which the App belongs. 

**To Reproduce**

1. Create two namespaces A and B.
2. Create an Argo project with A listed as on of its destination
3. Create an App that deploys a configMap to A.
4. Sync the app to the cluster.
5. Use kubectl to dump the config map from A. ```kubectl get configmap [name] -o yaml > [name].yaml```
6. Update the namespace then apply the configMap to namespace B.

After step 6 Argo will mark the App create in step 3 as out of sync.  Attempting to sync the App will fail with an error indicating the that configMap in namespace B could not be deployed to namespace A.

**Expected behavior**

Argo should not have associated the configMap from namespace B with the App running in namespace A because namespace B is not one of the destination for the project to which the App belongs.

**Version**

```argocd version
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:04:04Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:47:48Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Comment by klfgit** [comment]
Any updates on this?

**Comment by mayzhang2000** [comment]
I can reproduce this issue with v1.3.6.
Tried with latest code v1.6 this issue is fixed.
