### ISSUE TITLE
Add security contacts to GitHub repo

### ISSUE THREAD

**Issue by Eriner** [argoproj/argo-cd#3105]
# Summary

Add a security contacts file to this repo, as well as other repos within the argoproj org, and possibly to the website. For an example, see Kubernetes: https://github.com/kubernetes/kubernetes/blob/master/SECURITY_CONTACTS

# Motivation

Will let researchers know who to reach out to, and the preferred method of communicating sensitive issues that may require private (non-GitHub Issue) reporting.

**Comment by jannfis** [comment]
There is a list of security contacts at https://argoproj.github.io/argo-cd/operator-manual/security/#reporting-vulnerabilities, but I do agree that it's not very obvious to find. 

Getting this information into a file residing in the top level of the repo, with a link to above page would be a good thing imho.
