### ISSUE TITLE
Enhancement proposal : Helm repo add to support --insecure-skip-verify

### ISSUE THREAD

**Issue by pramod0310** [argoproj/argo-cd#3113]
### Summary
Adding helm repo does not support insecure options, as supported while adding git repository.

### Motivation
Many of the self-hosted helm repositories like harbor etc would be using self-signed certs. It would be a helpful option.

### Proposal
The addition of helm repo should also support the insecure-skip-verify option to skip cert verification.

**Comment by alexmt** [comment]
This is already supported in CLI: `argocd  ... --insecure-skip-server-verification`

The checkbox is missing in UI.

**Comment by pramod0310** [comment]
@alexmt I tried using --insecure-skip-server-verification for helm charts but does not have any effect only for git it works fine.

**Comment by thirdeyenick** [comment]
This is because the insecure option is not passed to the Helm client [here](https://github.com/argoproj/argo-cd/blob/3911cd48ca6c19c0cbdf6d512a7aa5da726aaf36/util/argo/argo.go#L136). It is only passed if the type of the repo is 'git'.

**Comment by alexmt** [comment]
PR https://github.com/argoproj/argo-cd/pull/3420 partially addresses this issue.  However, helm CLI itself does not have --insecure flag. So above PR will allow adding repository but it still will be impossible to use charts from the repo (`helm repo add` will fail) . 

The `--insecure-skip-tls-verify` flag was [added](https://github.com/helm/helm/pull/7254) to helm last month but still not released (checked both helm v2.16.6 and v3.1.2). 

Lets keep ticket open and wait for helm release.

**Comment by alexmt** [comment]
@mayzhang2000 lets keep it open until we upgrade to the helm 3.20 which adds `--insecure-skip-tls-verify` flag support. The helm release was published last week so we can work on it now: https://github.com/helm/helm/releases/tag/v3.2.0
