### ISSUE TITLE
cluster add: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by savujevi** [argoproj/argo-cd#3116]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

Hello developers,

I know this a local problem and no bug, but do you have a hint how to avoid on "cluster add" a check of certificate ?

Thank you for your help.

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

**Version**

argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.5.0+a1afe44
  BuildDate: 2020-02-06T21:15:31Z
  GitCommit: a1afe44066fcd0a0ab90a02a23177164bbad42cf
  GitTreeState: clean
  GoVersion: go1.13.7
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0

**logs**
level=error msg="finished unary call with code Unknown" error="REST config invalid: Get https://xxx.local.xxxxx:443/version?timeout=32s:  x509: certificate signed by unknown authority" grpc.code=Unknown grpc.method=Create grpc.service=cluster.ClusterService grpc.start_time="2020-02-12T12:12:17Z" grpc.time_ms=15.194 span.kind=server system=grpc

**Comment by savujevi** [comment]
I have solved it.
I have added our crt to the image and it works.

`ADD ./xx.crt /usr/local/share/ca-certificates
RUN update-ca-certificates`

**Comment by rsvancara** [comment]
How did you manage to solve this?  I tried adding a certificate to the image and it does not work for me.  Can you provide more details?

**Comment by savujevi** [comment]
I have written an Dockerfile which depends on the original image. In this dockerfile I add the commands which you can see in the previous comment.
