### ISSUE TITLE
argo-cd git submodule is using SSH auth instead of HTTPs

### ISSUE THREAD

**Issue by chartotu19** [argoproj/argo-cd#3118]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I added a new Git application(using HTTPs authenication) to argo-cd, this git repo had a submodule in it. The submodule's url was using SSH (git@github.com). Application creation failed with an error message:

```
Unable to create application: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Internal desc = Failed to checkout 2678262d622e6cb94afb78510879ca4c33f2a96e: `git submodule update --init --recursive` failed exit status 1:
```
I changed submodule url to use https://github.com and pushed it to my git repo. The problem still persists.

The Github personal token I use has access to both the git repos (projecta, projectb).

**To Reproduce**

1. create 2 git repos. projecta and projectb. 
2. add projectb as a submodule to projecta ( using ssh url . git@github.com) 
3. Register projecta as a GIT application using HTTPs auth
4. Try to create an application
5. change submodule url (https://github.com) and commit to projectb
6. Try to create an application.

**Expected behavior**

**Screenshots**

**Version**

```shell
v1.4.2+48cced9
```

**Logs**

```
time="2020-02-12T18:31:06Z" level=info msg="received unary call /application.ApplicationService/Create" grpc.method=Create grpc.request.claims="{\"iat\":1581531178,\"iss\":\"argocd\",\"nbf\":1581531178,\"sub\":\"admin\"}" grpc.request.content="application:<TypeMeta:<kind:\"\" apiVersion:\"\" > metadata:<name:\"test\" generateName:\"\" namespace:\"\" selfLink:\"\" uid:\"\" resourceVersion:\"\" generation:0 creationTimestamp:<0001-01-01T00:00:00Z> clusterName:\"\" > spec:<source:<repoURL:\"https://github.com/company/projecta.git\" path:\"sample_path\" targetRevision:\"feature/argo_cd_helm2\" directory:<recurse:true jsonnet:<> > chart:\"\" > destination:<server:\"https://kubernetes.default.svc\" namespace:\"app_namespace\" > project:\"app\" > status:<sync:<status:\"\" comparedTo:<source:<repoURL:\"\" path:\"\" targetRevision:\"\" chart:\"\" > destination:<server:\"\" namespace:\"\" > > revision:\"\" > health:<status:\"\" message:\"\" > sourceType:\"\" summary:<> > > " grpc.service=application.ApplicationService grpc.start_time="2020-02-12T18:31:06Z" span.kind=server system=grpc

time="2020-02-12T18:31:07Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Internal desc = Failed to checkout 4b29ae0795c2f1216953080e4eca6f3f8d80ce70: `git submodule update --init --recursive` failed exit status 1: Cloning into '/tmp/https:__github.com_company_projecta/projectb'...\ngit@github.com: Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nfatal: clone of 'git@github.com:company/projectb.git' into submodule path '/tmp/https:__github.com_company_projecta/projectb' failed\nFailed to clone 'projectb'. Retry scheduled\nCloning into '/tmp/https:__github.com_company_projecta/projectb'...\ngit@github.com: Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nfatal: clone of 'git@github.com:rubikloud/projectb.git' into submodule path '/tmp/https:__github.com_company_projecta/projectb' failed\nFailed to clone 'projectb' a second time, aborting" grpc.code=InvalidArgument grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2020-02-12T18:31:06Z" grpc.time_ms=1271.596 span.kind=server system=grpc
```

**Comment by jannfis** [comment]
Hi @chartotu19,

it seems that Git still tries to checkout the submodule using the SSH URL, at least when interpreting the log excerpt you have pasted.

What steps did you perform to change the submodule URL in your parent repository?

**Comment by fayak** [comment]
Hi,

I have the same issue, and I simply changed my .gitmodules to put https instead of ssh

**Comment by diranged** [comment]
Hey.. we're seeing this bug as well. Any chance we can get any traction on it? What can I do to help provide details @fayak ?

**Comment by diranged** [comment]
@jannfis any chance we can get some eyes on this?

**Comment by jannfis** [comment]
Can you please provide proper reproduction steps?

**Comment by diranged** [comment]
Honestly - after troubleshooting this again, I can't quite reproduce it.. I do have other issues with gitsubmodules not working for us (namely that our developers use SSH to do all checkouts, but we have Argo configured to do HTTP checkouts through a Github "App")... so I think I just need to re-think our use of submodules here at all. :/

**Comment by rubenssoto** [comment]
Hello Guys,

Im having the same problem,
I have a repo that has a submodule when I tried the first time I got the error:
Unable to create application: Unsuccessful HTTP response

when I tried the second time:
 fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. fatal: clone of 'git@github.com:company_name/terraform.git' into submodule path

Anyone could help me?

**Comment by jajaislanina** [comment]
Exhuming this one as i have same but opposite case. 
My .gitmodules file is using `git@github.com:org/repo-name.git` format, yet ArgoCD is trying to fetch the repo using https and complains about the missing Username.
Parent repo is configured using ssh auth and template credentials are stored in argocd already.

```
level=error msg="finished unary call with code Internal" 
error="rpc error: code = Internal desc = Failed to checkout fa3216d4239e94aa93dad271a32af42e847e1ee2: 
`git submodule update --init --recursive` failed exit status 1: 
Cloning into '/tmp/git@github.com_silly_platipus_frontend-service-config/templates'...
fatal: could not read Username for 'https://github.com': No such device or address
fatal: clone of 'https://github.com/silly-platipus/helm-template-master.git' into submodule path '/tmp/git@github.com_silly_platipus_frontend-service-config/templates' failed

```

**Comment by jontambi** [comment]
Hi. Similar problem here with Azure Repos. Using ssh-key shows following error:
time="2022-06-14T20:06:33Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = Failed to fetch default: `git fetch origin --tags --force` failed exit status 128:Unable to negotiate with 20.41.6.2 port 22: no matching host key type found. Their offer: ssh-rsa\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists." grpc.code=Internal grpc.method=ListApps grpc.service=repository.RepositoryService grpc.start_time="2022-06-14T20:06:31Z" grpc.time_ms=1455.161 span.kind=server system=grpc

Is a fresh installation of ArgoCD 2.4.0 Stable
- Setting Repository using ssh-key, connection is success
- Trying to use that Git Connection in Application shows the error above.

**Comment by hamedbrd** [comment]
Hi guys, when do you think we can get this fix?
