### ISSUE TITLE
Support ARM architecture

### ISSUE THREAD

**Issue by xUnholy** [argoproj/argo-cd#3120]
# Summary

I would like to request support for ARM architecture, both 32Bit and 64Bit.

# Motivation

Currently doing a lot of opensource work using Raspberry Pi 4b's to build a Kubernetes cluster. I would love to use ArgoCD if it has support for the architecture types. 

Raspberry Pi's currently using armv7l architecture

# Proposal

docker has an experimental buildx cli that might be an easy solution, although seeing as ArgoCD is Golang compiling cross-architecture should not be too difficult.

**Comment by petrilaakso** [comment]
@phillebaba build arm images and those are working fine. I'd like to see these in official project as well. Check this out https://github.com/argoproj/argo-cd/issues/2167

**Comment by phillebaba** [comment]
@xUnholy as @petrilaakso states I have already cross compiled ArgoCD for ARM with buildx, and I have been running it for the last 6 months without any issues. My suggestion is that we try to keep the discussion to the already existing issues as to not create separate tracks.

**Comment by xUnholy** [comment]
@phillebaba awesome work, any progress in merging your efforts upstream so I don't need to change my images to the ones you've built?

**Comment by phillebaba** [comment]
So i guess I need to sit down and make my changes compatible with the current build tools, but I have not really gotten any response from the maintainers whether they would accept my changes or not. So I will have to get a bit more engaged and figure out who to talk to. 

ArgoCD may want to go the same way as Flux where it is possible to compile for other architectures but they don't have official builds.
