### ISSUE TITLE
Silent failure when applying bad annotations

### ISSUE THREAD

**Issue by carsonoid** [argoproj/argo-cd#3122]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The apply will silently fail if the annotations on a resource are invalid. Any other changes to the resource get applied, but the annotations will not be updated as expected.

**To Reproduce**

Attempt to apply any resource with a bad annotation.

Ex annotation with an unquoted integer in a string field:
```
metadata:
  annotations:
   my-deploy-id: 201152744
```

**Expected behavior**

The apply should result in an error.

**Version**

```
v1.4.2+48cced9
```

**Comment by alexmt** [comment]
I'm pretty sure this happens due to bug in kubectl: https://github.com/kubernetes/kubernetes/issues/59113 . Seems like it was fixed in v1.17. Argo CD uses v1.16 now.

**Comment by carsonoid** [comment]
That's great! Thanks for the fast response. Should we just keep the ticket open until Argo-CD starts using a version of kubectl with the fix?

**Comment by alexmt** [comment]
I agree, it makes sense to keep ticket open until we upgraded to v1.17 and confirm that issue is resolved.
