### ISSUE TITLE
Integrate with Grafana Tanka

### ISSUE THREAD

**Issue by sh0rez** [argoproj/argo-cd#3124]
(**Disclaimer**: I am the maintainer of Tanka)

## Summary

Given that this project supported `ksonnet` until it was defunct, I think it would be cool to add support for https://github.com/grafana/tanka, which aims to be the spiritual successor.  
Many requests for integrating with popular CD tooling have reached us, and looking at Argo, it seems like it could be especially smooth here.

## Motivation

Tanka, just like `ksonnet` did, uses Jsonnet for configuring Kubernetes. In contrast to plain `.jsonnet` files, we aim to massively enhance the development flow for, by providing the `show`, `diff` and `apply` workflow.

GitOps however is not (yet?) covered by Tanka itself, and as it appears there are very cool projects in this ecosystem which could be used for that instead. The core concepts of Argo seem to be a perfect fit for our own design ideas, as they seamlessly connect to the workflow:

| Tanka only | Tanka + Argo |
|-|-|
| * hack on Jsonnet | * hack on Jsonnet
| * `show` the yaml | * `tk show` the yaml
| * `diff` to verify | * `tk diff` to vefify
| * `apply` to k8s | * `git commit && git push`
| | * ArgoCD manages application lifecycle |

Having first class support for Tanka would ease the adoption process of Argo for our users, but also provide existing Argo `ksonnet` users a maintained and curated platform to switch to.

## Proposal

I'd be very happy to help with the implementation / do it myself. The `tk show` operation can be used to obtain a YAML representation of the objects, which should be sufficient for Argo's needs.

#### Type of integration
Because Tanka and Argo are both implemented in Go, our `github.com/grafana/tanka/pkg/tanka` package could be used, to directly integrate Tanka into Argo, without having to ship any precompiled binaries along it.

This library is what powers the `tk` binary, is functionally equivalent and mimics the CLI in terms of API design, yet providing more flexibility.

WDYT?

**Comment by nhuray** [comment]
Hi Grafana Team,

I'm surprised no one commented that issue. 

I personally think a Tanka integration will bring value to ArgoCD considering Ksonnet is no longer supported.

### My use case

I would like to use Tanka and ArgoCD to manage Grafana dashboards (dashboard as code) and prometheus alerts. 

For that I would like to use the [kubernetes-monitoring mixin project](https://github.com/kubernetes-monitoring/kubernetes-mixin) and the Tanka library in order to create `ConfigMap`s for dashboards and `PrometheusRule`s for alerts. (this project define jsonnet files to create the dashboards and rules but doesn't wrap them in Kubernetes objects)

I'm aware the Helm chart for prometheus-operator already do that but in a very hacky way ([using python scripts](https://github.com/helm/charts/tree/master/stable/prometheus-operator/hack))

Finally once my rules and dashboards are working well in local (minikube) I would like to deploy them using ArgoCD.

Thanks for your time to consider that issue

Nicolas

**Comment by ThirtyThirds** [comment]
Hello,
Any chance that this will be considered?

**Comment by sgs00** [comment]
That would be great. Is there any way to engage a core developer in this conversation?

**Comment by seuf** [comment]
I Think it's possible to use Tanka with Argocd thanks to [plugins](https://argoproj.github.io/argo-cd/user-guide/config-management-plugins/)
Just create a custom image with tk binary inside and use it for your apps.

**Comment by ghostsquad** [comment]
Before I learned of Tanka, I did something very similar using the `jsonnet -m` flag. Which, when the result of the jsonnet compilation returns an object, jsonnet takes each key in the object and writes the _value_ of that key to a file, with the name of the file being the key (minus extension).

The meat of the script is here:

```bash
jsonnet_tla_strs=()
if tla_str_vars=$(env | $GREP "^JSONNET_TLA_STR__"); then
    debug "found JSONNET_TLA_STR__ vars"
    while IFS='' read -r line; do jsonnet_tla_strs+=("$line"); done < <(echo "${tla_str_vars}" | $AWK -F'__' '{print $2}')
fi

jsonnet_tla_codes=()
if tla_code_vars=$(env | $GREP "^JSONNET_TLA_CODE__"); then
    debug "found JSONNET_TLA_CODE__ vars"
    while IFS='' read -r line; do jsonnet_tla_codes+=("$line"); done < <(echo "${tla_code_vars}" | $AWK -F'__' '{print $2}')
fi

tmp_files_list_file="${my_temp_dir}/jsonnet_files_list.txt"
# I have to wordsplit below
# as it passes option name and option values (that must be separate) to jsonnet
# shellcheck disable=SC2068
$JSONNET \
    ${jsonnet_tla_strs[@]/#/--tla-str } \
    ${jsonnet_tla_codes[@]/#/--tla-code } \
    -m "${repo_dir}" "${deployment_dir}/environments/${workspace}/${workspace}.jsonnet" \
    > "${tmp_files_list_file}"

files=()
while IFS='' read -r line; do files+=("$line"); done < "${tmp_files_list_file}"

for i in "${files[@]}"
do
    :
    yq r -P "${i}" | cat "${deployment_dir}/do-not-edit-header.txt" - > "${i}.yml"
    rm -f "${i}"
done
```

The pattern actually stems from https://github.com/coreos/kube-prometheus

Happy to adopt Tanka, if it makes this pattern easier to deploy!

Before finding this issue, I was thinking I had to write my own plugin to accomplish this.
https://argoproj.github.io/argo-cd/user-guide/config-management-plugins/

as @seuf says, write a plugin for this. It would awesome if there was an official or "community official" plugin for Tanka.

Would it be valuable to provide the community with said plugin? I could create a repo for this (similar to how ConcourseCI does resources https://github.com/concourse/concourse/wiki/Resource-Types)

Maybe this would be the start of a plugin index for ArgoCD?

**Comment by ghostsquad** [comment]
It seems that plugins don't support "extra args" like other "native" renders do. Example:

https://argoproj.github.io/argo-cd/user-guide/jsonnet/
```
argocd app create APPNAME \
  --jsonnet-ext-str 'app=${ARGOCD_APP_NAME}' \
  --jsonnet-tla-str 'ns=${ARGOCD_APP_NAMESPACE}'
```

vs

https://argoproj.github.io/argo-cd/user-guide/config-management-plugins/
```
argocd app create <appName> --config-management-plugin <pluginName>
```

It seems that pass-thru args are not supported, but need to be.

**Comment by Moulick** [comment]
If argo supported Tanka, that would be so awesome. We need to fill the void left by ksonnet and this fills it nicely

**Comment by xvzf** [comment]
👍 as well! Would be great. We're already using something similar with Tanka locally and Argo managing the cluster. Would be great to see these combined!

**Comment by fbaier-fn** [comment]
+1

**Comment by v1k7g85** [comment]
+1

**Comment by nabadger** [comment]
+1 on this too.

**Comment by jessebye** [comment]
Cross-posting my comment from this issue: https://github.com/argoproj/argo-cd/issues/3688#issuecomment-731453739

With a plugin and a custom dockerfile, you can use Tanka pretty easily in Argo CD! Not sure if this could be made more "official" somehow, either through documentation or code changes. I'm happy to contribute either way.

**Comment by alexmt** [comment]
Hello everyone. Argo CD maintainer here. Sorry for ignoring this enhancement proposal for so long. We've learned that it is really difficult to provide first-class config management tools support and especially difficult to keep up with changes and deal with breaking changes. Another concern is growing Argo CD image size - every tool is an additional binary that makes Argo CD image bigger. 


Instead of adding first-class support of more tools we are trying to improve the existing [config management plugins](https://github.com/argoproj/argo-cd/issues/5293)  feature so that it provides first-class user experience. 

Please take a look at the proposal and share your thoughts.

**Comment by jsmcnair** [comment]
For anyone who finds this thread and is wondering how to implement this, I found the following blog article very useful when setting up tanka as a plug-in for ArgoCD.

https://hodovi.cc/blog/gitops-argocd-and-tanka/

**Comment by raynix** [comment]
@jsmcnair nice one. I followed your blog post and [got my tanka working as well](https://raynix.info/archives/4014). Thanks for sharing.

**Comment by zephyros-dev** [comment]
> For anyone who finds this thread and is wondering how to implement this, I found the following blog article very useful when setting up tanka as a plug-in for ArgoCD.
> 
> https://hodovi.cc/blog/gitops-argocd-and-tanka/



> @jsmcnair nice one. I followed your blog post and [got my tanka working as well](https://raynix.info/archives/4014). Thanks for sharing.

The instructions here still works but with a caveat: The environments variables in the application now come with a `ARGOCD_ENV_` prefix. .i.e: to use `TK_ENV` in the application, the command should be: `tk show environments/${ARGOCD_ENV_TK_ENV} --dangerous-allow-redirect`

**Comment by James-Riordan** [comment]
This is still a very much needed feature 3 years later!

**Comment by crenshaw-dev** [comment]
2.6 will introduce some [additional UI integration for config management plugins](https://github.com/argoproj/argo-cd/pull/9216), and we plan to continue to invest in config management plugins features. I anticipate a robust third-party plugin will be how Argo CD achieves Tanka support.

It's possible that some company/org will commit to writing and maintaining first-class Tanka support in Argo CD. But until that happens, plugins will be the way forward.

**Comment by crenshaw-dev** [comment]
fwiw, I see someone has written up a plugin for Tanka. I'm not sure how full-featured it is. https://www.gregmalkov.dev/devops/argocd-tanka/

**Comment by ghostsquad** [comment]
making sure this issue doesn't get lost! Here's a comment for 2023. I'll be back in a few months to make one for 2024. 😂

**Comment by komapa** [comment]
> making sure this issue doesn't get lost! Here's a comment for 2023. I'll be back in a few months to make one for 2024. 😂

Beat you to it. Here's a comment for 2024.

**Comment by raynix** [comment]
Just in case, here's [my updated way to integrate tanka with ArgoCD](https://raynix.info/archives/4565) in 2024(after ArgoCD 2.8).

**Comment by a244591052** [comment]
@raynix I would like to ask, what is the approximate refresh latency for using TK CMP?

**Comment by raynix** [comment]
> @raynix I would like to ask, what is the approximate refresh latency for using TK CMP?

Hi I assume the question is how long does it take to refresh the application in argoCD which uses TK ConfigManagementPlugin? Well my app is relatively simple - just a few wordpress + redis k8s deployment so the refresh is almost instant.

**Comment by crenshaw-dev** [comment]
Closing for now as CMPs are expected to be the way to use Tanka in Argo CD, at least short-to-medium term. Feel free to continue discussing here though!
