### ISSUE TITLE
Allow for larger cookies

### ISSUE THREAD

**Issue by davidkarlsen** [argoproj/argo-cd#3126]
# Summary

I'm debugging the SSO integration. We have rather a lot of claims due to wide group-memberships (and no filtering capabilities in auth0 - at least not easy). So in order to introspect the token I turned off compression: https://github.com/argoproj/argo-cd/blob/master/util/jwt/zjwt/zjwt.go#L25 so that it can easily be opened in JWT debugging tools.
This however leads to exceeding the max cookie size:
https://github.com/argoproj/argo-cd/blob/master/util/http/http.go#L23 has a hardcoded max-size for cookies.

Could this limit become configurable through an env-var, with fallback to the current default?

# Motivation

Be able to debug SSO/OIDC integrations - which is always a pain.

# Proposal

Read env-var and fallback to current default if undefined.

**Comment by davidkarlsen** [comment]
Related: https://github.com/argoproj/argo-cd/issues/2085

**Comment by jannfis** [comment]
Hi @davidkarlsen, I think most HTTP clients would choke on cookies larger than 4k bytes, so having a configurable limit on the authentication cookie in ArgoCD exceeding 4k would make little sense and probably create more problems than what it's trying to solve.

Would it be sufficient for your use case to have a convinient way to uncompress the token after it has been received by your client, i.e. on the command line?

**Comment by davidkarlsen** [comment]
Mmm, good point: https://www.quora.com/What-Is-The-Maximum-Size-Of-Cookie-In-A-Web-Browser
But being able to debug better is good.
Also https://github.com/argoproj/argo-cd/issues/2085 is maybe the ultimate solution since quite a number of uses could mean a lot of claims/groups -> large cookie.

**Comment by jannfis** [comment]
Hi @davidkarlsen, meanwhile to debug your cookies you can use the following simple shell script I hacked together for converting a compressed JWT to a standard, uncompressed JWT in order to pass it to the debugging tool of your choice. Sorry, bash shell only.

```bash
#!/bin/bash
# Only works with bash due to arrays, no other shells supported
IFS="." read -ra token
echo
if test ${#token[@]} -eq 3; then
  echo "Output: ${token[0]}.${token[1]}.${token[2]}"
elif test ${#token[@]} -eq 4; then
  if test "${token[0]}" != "zJWT/v1"; then
    echo "Magic number for zJWT not found, found '${token[0]}' instead." >&2
    exit 1
  fi
  uncompressedPayload=$(echo "${token[2]}" | base64 -id -w 0 2>/dev/null | gunzip -c | base64 -w 0)
  echo "Output: ${token[1]}.$uncompressedPayload.${token[3]}"
else
  echo "Invalid input, not a valid JWT or ZJWT token" >&2
fi
```

**Comment by davidkarlsen** [comment]
Great - thanks a lot - I'll close this issue then.
