### ISSUE TITLE
Enable password-protected Redis

### ISSUE THREAD

**Issue by samuelmak** [argoproj/argo-cd#3130]
# Summary

Enable password-protected Redis

# Motivation

We would like to enable password auth of Redis so that the information is protected.

# Proposal

Can we inject the password from kubernetes secret into Redis and Argo CD server so that they can communicate with a password protected channel?

**Comment by alexmt** [comment]
Hello @samuelmak ,

This is available but not documented. The password should be  specified in `REDIS_PASSWORD` env variable in `argocd-application-controller`, `argocd-server` and `argocd-repo-server` deployments. Sending PR with the docs changes

**Comment by BenManifold** [comment]
Is there any way to set this password using a secret instead of an environment variable? Passwords as env-vars violates our infosec compliance guidelines.

**Comment by BenManifold** [comment]
> Hello @samuelmak ,
> 
> This is available but not documented. The password should be specified in `REDIS_PASSWORD` env variable in `argocd-application-controller`, `argocd-server` and `argocd-repo-server` deployments. Sending PR with the docs changes

We really need a way to mount the password as a secrets file so we're not just skywriting in env vars all over the place

**Comment by LesleyDebes** [comment]
@alexmt Are there directions on how to pass the REDIS_PASSWORD environment correctly so that the Redis instance is password protected?  Our team has been able to successfully set this environment variable in the various deployments listed above but it is not having any affect on the Redis password.  It is still unprotected.

**Comment by nzin-appdirect** [comment]
Hi @LesleyDebes , I think it is because the haproxy is not setup to pass an AUTH token.
i.e.
in particular in https://github.com/argoproj/argo-cd/blob/d511fb8deb50c2c86babe215e1d5105f59699cb0/manifests/ha/base/redis-ha/chart/upstream.yaml#L343
we should have a 
```
      tcp-check send AUTH <yourredispassword>\r\n
      tcp-check expect string +OK
      tcp-check send PING\r\n
      tcp-check expect string +PONG
      tcp-check send SENTINEL\ get-master-addr-by-name\ argocd\r\n
      tcp-check expect string REPLACE_ANNOUNCE0

```

**Comment by SnoozeFreddo** [comment]
Would also need some instructions for non HA version.

The docs just reference this issue but what's the solution to store it as a secret?

**Comment by todaywasawesome** [comment]
Closed by https://github.com/argoproj/argo-cd/commit/f1a449e83ee73f8f14d441563b6a31b504f8d8b0
