### ISSUE TITLE
Add pod's age in node display or tooltip

### ISSUE THREAD

**Issue by nurinamu** [argoproj/argo-cd#3141]
# Summary

Similar issue with #2928. If age is displayed on resource tree's pod node without any click, it would be helpful.

# Motivation

Sometimes pod's age is very useful information to find specific pods. However it is very hard to find it on ArgoCD UI without clicking each pod. I did always find the pod's hash name on cli and check UI. It is little inconvenient.

# Proposal
<img width="297" alt="스크린샷 2020-02-20 오후 7 14 28" src="https://user-images.githubusercontent.com/1445542/74924495-f0d8ae00-5415-11ea-97a7-668e806f6dba.png">

Thanks.

**Comment by taisho6339** [comment]
If [This PR](https://github.com/argoproj/gitops-engine/pull/87) is approved, I will create an new Pull Request for this issue immediately.

**Comment by nurinamu** [comment]
@taisho6339 Thank you!!
