### ISSUE TITLE
Allow full ConfigMap synchronization rather than patching

### ISSUE THREAD

**Issue by mark-rushakoff** [argoproj/argo-cd#3142]
# Summary

When we have a ConfigMap that Argo synchronizes, and we later remove a key from that ConfigMap in our git repository: it appears that Argo synchronizes the ConfigMap, but the key we removed in our git repository is still present in the live ConfigMap in the target cluster. 

I believe that this is due to Argo doing an effective `kubectl patch` operation rather than `kubectl apply`, but I am not certain.

# Motivation

We sometimes use a ConfigMap to specify environment variables for a pod, using `envFrom: {configMapRef: {name: 'foo' }}`.  On at least two separate occasions, we have had minor incidents due to removing a key from a ConfigMap with the expectation that the environment variable would be removed from the pod spec, only to eventually discover that the key we removed from our definition of the ConfigMap, was still present in the ConfigMap inside the cluster.

This has been surprising behavior. I believe this also implies that synchronizing the Argo App would result in a different state depending on the values in the live ConfigMap prior to synchronizing.

# Proposal

Ideally the ConfigMap would always be hard-synchronized, so that the live ConfigMap is exactly the same as what is committed in git.

If that breaks compatibility guarantees, the next best option for us would be an annotation like `argoproj.io/always-overwrite-configmap: true` to indicate that ConfigMaps should be completely synchronized. My strongest preference would be to use that annotation on an AppProject, and then on an Application, and least preferably directly on the ConfigMap.

**Comment by alexmt** [comment]
Hello @mark-rushakoff , 

I think https://github.com/argoproj/argo-cd/issues/2730 describes exact same issue and should cover your use case. The https://github.com/argoproj/argo-cd/issues/2730 suggests introducing an ability to use `kubectl replace` instead of `kubectl apply` for some resources. 
Let's use https://github.com/argoproj/argo-cd/issues/2730 to track the implementation
