### ISSUE TITLE
The app diff UI button includes temporary resources from hooks

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-cd#3143]
**Describe the bug**
If a user clicks the app diff button with an application with hooks, those hooks show up as resources that need to be removed. This behavior is misleading as users think their app is out of sync, but it's actually healthy.

**To Reproduce**
1. Create an app with a hook
1. Sync it
1. Click the app diff button

**Expected behavior**
If an application with hook is synced, no resources should appear on the app diff page.

**Comment by ciiay** [comment]
@dthomson25 Hi, I tried to reproduce this issue, after application is synced up, the Diff button is disabled. Could you confirm if it's ok to close this issue? Thanks!

**Comment by vroldanbet** [comment]
We see the same phenomenon when resources have Helm hooks. The `App Diff` button shows the resource as being removed (marked in red) when in fact is not going to be changed at all. This will only show up if there is any other resource that has an actual diff. Once the sync is completed, the `App Diff` button is greyed out.
