### ISSUE TITLE
github dex oauth2 not working: server response missing access_token

### ISSUE THREAD

**Issue by toonsevrin** [argoproj/argo-cd#3149]
I setup dex github according to the tutorial (using port-forward, so the redirect url is localhost:8080/...)

Whenever I press login with Github I get the following error:
`Failed to authenticate: github: failed to get token: oauth2: server response missing access_token`

Can anyone provide some debugging steps?

**Comment by toonsevrin** [comment]
Seems like I was running an older version of argo-cd, fixed.

**Comment by pmcjury** [comment]
@toonsevrin  I'm getting this same issue. I'm on argocd 1.4.2 . Was there anything else to this beside upgrading? 

```Failed to authenticate: github: failed to get token: oauth2: server response missing access_token```

**Comment by pmcjury** [comment]
nm. The issue was with base64 the secret. It requires “-n” when doing so. Without it the secret has a new mine and is invalid

**Comment by toonsevrin** [comment]
For any other people that get this issue: Please make sure your secrets are properly encoded (and do not end on a new line!

For linux this means you will have to do: 
```
printf <secret> | base64
````

 instead of `echo <secret> | base64`

**Comment by safe2008** [comment]
> For any other people that get this issue: Please make sure your secrets are properly encoded (and do not end on a new line!
> 
> For linux this means you will have to do:
> 
> ```
> printf <secret> | base64
> ```
> 
> instead of `echo <secret> | base64`

@toonsevrin

 How to solve this issue?

**Comment by brandon-piner-aruba** [comment]
also make sure that the secret has the  argocd label:

```yaml
      labels:
        app.kubernetes.io/part-of: argocd
```

**Comment by maxvt-tonal** [comment]
If you use a non-default namespace for Argo, older versions don't have a way to specify it for Dex.

I had to patch it in:

```
spec:
  template:
    spec:
      containers:
        - name: dex-server
          command:
          - /shared/argocd-dex
          - rundex
          - --namespace
          - your-namespace
```
