### ISSUE TITLE
Dex + SSO login does not work if Argo CD is behind reverse proxy with a different base href

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#3163]
**Describe the bug**

The SSO login using dex does not work  if Argo CD is behind reverse proxy with a different base href

**To Reproduce**

1. Setup argocd as described at https://argoproj.github.io/argo-cd/operator-manual/ingress/#ui-base-path
2. Configure SSO using dex as described at https://argoproj.github.io/argo-cd/operator-manual/sso/#dex
3. Try to login

**Expected behavior**

Login fails with 404 error

**Version**

```shell
v1.4.3
```

**Comment by jannfis** [comment]
Related: #3137

I also think that the base href option is inherently broken right now. I never understood why it existed, if it's just the UI that is affected, and `/api` stays at the root path. IMHO, we should think about ways to move everything to a specific context root.

**Comment by gpaul** [comment]
Likely fixed by: https://github.com/argoproj/argo-cd/pull/3164

**Comment by alexmt** [comment]
@gpaul actually I found it while testing  #3164 . Seems like SSO flow is broken now if basehref is set. Sent a PR with the fix: https://github.com/argoproj/argo-cd/pull/3165

**Comment by alexmt** [comment]
@jannfis I'm not very happy with basehref as well. Right now it can be used only if proxy, that runs in front of Argo CD also rewrites URL (https://argoproj.github.io/argo-cd/operator-manual/ingress/#ui-base-path).

It would be much easier if server actually serve UI and API with if it is configured to use non-root  URL path. Some users already rely on `--basehref` flag. Probably we should deprecate it and introduce new flag that has better behavior?

**Comment by alexmt** [comment]
Just for reference. The `basehref` was introduced to support kubeflow users: https://github.com/kubeflow/kubeflow/issues/2005#issuecomment-447139592

So if we introduce new flag we still need to keep `basehref` for kubeflow

**Comment by jannfis** [comment]
OK, thanks for the clarification @alexmt - and sure thing that basehref should be kept for backwards compat.

**Comment by alexmt** [comment]
@gpaul I did not realize you had PR for this bug already. Looking at https://github.com/argoproj/argo-cd/pull/3164

**Comment by alexmt** [comment]
Apparently PRs complement each other :) Merged https://github.com/argoproj/argo-cd/pull/3164

**Comment by gpaul** [comment]
:-)
