### ISSUE TITLE
Error on Sync: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by brunopadz** [argoproj/argo-cd#3170]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm using ArgoCD [Docker image](https://hub.docker.com/r/argoproj/argocd) containing argocd cli to use on my CI process (which runs on DroneCI). Whenever I try to sync an app, it returns the following error:

```
time="2020-02-28T19:39:47Z" level=fatal msg="rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR"
```

I'm using the following environment variables in order to authenticate the CLI:

`ARGOCD_SERVER=myargo.tld`
`ARGOCD_OPTS=--grpc-web`
`ARGOCD_AUTH_TOKEN=JWT_TOKEN`

**To Reproduce**

Pull the image and try to run a sync.

**Expected behavior**

It should sync the app as expected.

**Screenshots**

N/A

**Version**

Output from docker container:

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:04:04Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.3.2+a5a65cd
  BuildDate: 2019-12-03T21:32:18Z
  GitCommit: a5a65cdfe7c43fd1e3beada202d80c19bc50bd40
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**

It doesn't generate any logs from argocd-server.

**Comment by jannfis** [comment]
Hi @brunopadz, although the client should be downward compatible, can you please try to use a matching client version, i.e. same version of your argocd-server (v1.3) and see if that works for you?

**Comment by brunopadz** [comment]
Hey @jannfis, just tried with v1.3.2 and no luck. :/

Here's the log output from Drone
```
v1.3.2: Pulling from argoproj/argocd
--
2 | Digest: sha256:f19df6cef7ac5265fc347f232f889adbac5ca413be8e7598c4bcdbb8d1b8a1be
3 | Status: Downloaded newer image for argoproj/argocd:v1.3.2
4 | + argocd --grpc-web app sync ameno-dev
5 | time="2020-02-29T19:13:46Z" level=fatal msg="rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR"
```

**Comment by brunopadz** [comment]
Just an additional info, I upgraded ArgoCD to v1.4.2 and still getting the same error.

For the sake of debugging, I've installed ArgoCD CLI directly in DroneCI runner host and it runs fine too. 
I've also tried running the docker image in this host and it runs fine, which is really weird, since Drone does exactly the same I'm doing.
