### ISSUE TITLE
Description of non-cascade command is incorrect

### ISSUE THREAD

**Issue by m3y** [argoproj/argo-cd#3173]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When executing the non-cascade command described on the following page, cascade delete is performed.
https://argoproj.github.io/argo-cd/user-guide/app_deletion/

In the following FAQ, there is explanation
I want to update the documentation
https://argoproj.github.io/argo-cd/faq/#ive-deletedcorrupted-my-repo-and-cant-delete-my-app

**To Reproduce**
Execute the following command
```
argocd app delete APPNAME
```

**Expected behavior**
`--cascade` default value is true

**Screenshots**
Sorry, omitted

**Version**

```shell
argocd: v1.4.0+2d02948
  BuildDate: 2020-01-18T05:55:41Z
  GitCommit: 2d029488aba6e5ad48b2a756bfcf43d5cb7abcee
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**
Sorry, omitted

**Comment by jannfis** [comment]
Closed via  #3174
