### ISSUE TITLE
argocd application connection http2.StreamError

### ISSUE THREAD

**Issue by xingmin860818** [argoproj/argo-cd#3186]
Checklist:

* [ *] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

my argocd application suddenly become unavalibale , there two same errors in Application Conditions shows: Stream error http2.StreamError{StreamID:0x4d, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.

my argocd server and kubernetes not in the same cloud zone . 

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

**Version**

argocd 1.3.0
**Logs**

```
Paste any relevant application logs here.
```

**Comment by apetrovYa** [comment]
I and my team faced the same error on 3 different Argo apps. 
The error code was the same as yours @xingmin860818.

To fix, we restarted the ArgoCD controller and everything healed itself.

**Comment by jgwest** [comment]
Appears resolved, no recent reports on Slack or GitHub. Feel free to post here if still an issue.
