### ISSUE TITLE
Default password is not set to pod name

### ISSUE THREAD

**Issue by travis-sobeck** [argoproj/argo-cd#3187]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

Clean install of latest version (3/3/2020) per https://argoproj.github.io/argo-cd/getting_started/
Unable to log in with default 'admin' and pod name, I get Unauthenticated desc = Invalid username or password.  I even tried https://github.com/argoproj/argo-cd/blob/master/docs/faq.md#i-forgot-the-admin-password-how-do-i-reset-it and still didn't work

**To Reproduce**
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
set-up ingress (this works)
kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server -o name | cut -d'/' -f 2
argocd login <ARGOCD_SERVER>

**Expected behavior**

expect to login

**Screenshots**

**Version**

```shell
 image: argoproj/argocd:v1.4.2

```

**Logs**

```
XXXXX:~$ argocd login grpc.argocd.localhost 
WARNING: server certificate had error: x509: certificate is valid for ingress.local, not grpc.argocd.localhost. Proceed insecurely (y/n)? y
Username: admin
Password: 
FATA[0007] rpc error: code = Unauthenticated desc = Invalid username or password
```

**Comment by NormJohnIV** [comment]
Can you provide details on how you fixed this issue? I am having the exact same problem

**Comment by travis-sobeck** [comment]
@NormJohnIV Since I terminate SSL at the ingress, after the initial deployment, I  patched it to run as --insecure as the next line in my scirpt
kubectl patch deploy argocd-server -n argocd -p '[{"op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--insecure"}]' --type json
This spins up a new pod/container with the patched setting and a new name, however the password is still set to the original pods name.  recycling the pods doesn't change the password.
So make sure you get the pod name right away.

**Comment by vinaynaidu07** [comment]
@NormJohnIV What if the pod is recreated and the previous pod name is not available?How to reset it ?
