### ISSUE TITLE
Failed helm fetch call prints sensitive information in logs

### ISSUE THREAD

**Issue by shelby-moore** [argoproj/argo-cd#3188]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Failed `helm fetch` calls log out the username and password in plain text in the logs of the argocd-repo-server. The same error message shows in the output of `argocd app get <APP_NAME>` for the application the helm fetch failed for.

**To Reproduce**

In my case the grpc call to helm repository is failing with the error `failed signal: killed`, which triggers the print of the full helm fetch command, including the username and password.

**Expected behavior**

The username and password are redacted in the logs and in the output of `argocd app get <APP_NAME>`

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Comment by shelby-moore** [comment]
Looks like this is caused by the error being bubbled up but not redacted in 

https://github.com/argoproj/pkg/blob/master/exec/exec.go#L109-L111

and https://github.com/argoproj/pkg/blob/master/exec/exec.go#L116-L118 ?

If this seems right, let me know and I'll submit a fix.

**Comment by alexmt** [comment]
Hello @shelby-moore ,

Thank you for reporting this bug. I did not have a chance to reproduce it yet but I think you are right. Looks like there is an edge case where error text is not reducted. 

PR would be really appreciated.

**Comment by shelby-moore** [comment]
Thoughts on https://github.com/argoproj/pkg/pull/15 ?
