### ISSUE TITLE
Switch to Go Modules from Go Dep

### ISSUE THREAD

**Issue by matthyx** [argoproj/argo-cd#3194]
# Summary

Migrate argo-cd repo to Go Modules.

# Motivation

https://github.com/golang/go/wiki/Modules
> In Go 1.14, module support is considered ready for production use, and all users are encouraged to migrate to modules from other dependency management systems.

This migration will speed up builds thanks to caching, and provide more flexibility by moving away from `$GOPATH`.

# Proposal

https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support

`$ go mod init` should be sufficient to migrate the information found in `Gopkg.lock`.
However, it might be wise to `$ export GO111MODULE=on` in the scripts if users keep their git repo inside `$GOPATH`.

I can test that on my side, and open a PR.

**Comment by ciiiii** [comment]
How about the progress?

**Comment by d-kuro** [comment]
I tried to work on this, but it didn't work.
Code generation scripts are vendor-depends, thats complex.
https://github.com/argoproj/argo-cd/pull/3562

There are also pull requests that other people have done work on.
https://github.com/argoproj/argo-cd/pull/2327

**Comment by matthyx** [comment]
@d-kuro can you describe your problems, maybe other people would like to give it a go?
