### ISSUE TITLE
argocd clusterrole and binding 

### ISSUE THREAD

**Issue by chiragthaker** [argoproj/argo-cd#3197]
argocd-manager-role ( clusterrole) has too wide permission when we add an external cluster which means it practically can do anything. Is there a way if we can limit this clusterrole like something custom as per our needs .
We want to add a cluster with our custom clusterrole rather then argo-cli overriding customrole everytime to ( *) when we add a new external cluster.

how do you cater this ?

**Comment by jannfis** [comment]
Hi @chiragthaker, just a few days ago we merged https://github.com/argoproj/argo-cd/pull/3184 into master branch that will allow you to specify a pre-existing (and pre-authorized) service account in the remote cluster to use for ArgoCD connections. It will most likely be part of v1.5 release.

**Comment by alexmt** [comment]
Just want to add more to @jannfis suggestion. After creating the service account with limited permissions you can use [resource inclusions/exclusions](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#resource-exclusioninclusion) or cluster namespace mode ( `argocd cluster add --namespace <myNamespace> ...` ) to configure set of resource that argocd tries to manage.
