### ISSUE TITLE
Unable to login with CLI - following initial setup

### ISSUE THREAD

**Issue by richstokes** [argoproj/argo-cd#3201]
```
Internal desc = transport: received the unexpected content-type "text/plain; charset=utf-8"
```

When following https://argoproj.github.io/argo-cd/getting_started/  -- step 4.

I am able to login with the Web interface..

**Comment by richstokes** [comment]
Looks like its this issue https://github.com/argoproj/argo-cd/issues/2580

Would be good to have a note about that in the docs. Fairly frustrating following guides that are incorrect/missing key pieces of info :-)

**Comment by todaywasawesome** [comment]
No longer an issue.
