### ISSUE TITLE
Add timezone option in Sync Window

### ISSUE THREAD

**Issue by amitpd** [argoproj/argo-cd#3204]
# Summary

Add timezone to Sync Window to handle daylight savings.

# Motivation

For distributed team working across multiple geographies, if two sync windows of duration 2 hrs need to be added, one for IST (Kolkata, India) and another for EST timezone, it needs to be converted to UTC. Let's assume, the sync window starts at 10AM local time for both the timezones, the sync window schedule can be converted to UTC as below.
30 4 * * *
0 15 * * *

When daylight savings starts, the first sync window is still good since daylight savings is not implemented in IST. However, the second sync window will then become active from 11 AM EST time, which is an hour late.

As of now, someone has to reconfigure the sync windows right before daylight savings kicks in.

# Proposal

Add an option in UI to take timezone as input.
The backend server should convert the sync window with respective timezone to UTC to analyze if it is active or not.
The backend server should have the intelligence to consider daylight savings while converting it to UTC.
For backward compatibility, all existing sync windows timezone should be considered as UTC

**Comment by DoumLaberge** [comment]
I wonder on wich datetime the sync windows are based, because I've passed the env  
       - name: TZ
          value: "America/Montreal"
to all container, but the sync windows continue tu be based on UTC.  The server/application-controller/repo-server pods are in my timezone, but the enabled/disabled fonctions of the sync windows continue to compare the UTC time with the settings..  Very strange.

**Comment by rouke-broersma** [comment]
Sync windows are hard-coded to UTC AFAIK.
