### ISSUE TITLE
cascade delete option is ticked by default , want to have it unticked by default for us.

### ISSUE THREAD

**Issue by chiragthaker** [argoproj/argo-cd#3205]
When you delete app in ARGOCD cascade delete option is by default ticked which can be fatal as it delete resources too from the cluster . Do anyone know how to make default untick when you delete the app from ArgoCD and then choose cascade deletion ok if we really want resources from the cluster to be deleted too.
We use apps-in-apps and want this to be disabled by default.

**Comment by resamaraschi** [comment]
Also interested in this feature. I think the default behavior should rather be removing the application from ARGO CD only. I think one wants to easily remove the whole application only in a test environment cluster and but not in a PROD cluster. Thanks

**Comment by LelandSindt** [comment]
I got bit by this today (entirely my fault for not paying attention). 

May I suggest that the `Cascade` option be checked based on the presence/absence of
```
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
```

https://argoproj.github.io/argo-cd/user-guide/app_deletion/

@lelandsindttouchnet

**Comment by keithchong** [comment]
@alexmt, should the CLI's default be changed to false as well?

**Comment by jannfis** [comment]
> @alexmt, should the CLI's default be changed to false as well?

IMHO, I would wish for the CLI to behave as follows:

- If cascade is set to true, ask the user whether he really wants to delete the application and all of its resources
- For automation, either a `--force` or `--yes` option should specify to skip a dialogue like above and assume yes on the answer

**Comment by alexmt** [comment]
I really like your suggestion @jannfis . And pseudo terminal check is a nice workaround to prevent breaking existing automation.

**Comment by keithchong** [comment]
Hi @alexmt, please assign this to me.

**Comment by jannfis** [comment]
> Hi @alexmt, please assign this to me.

Done.

**Comment by keithchong** [comment]
Here is a screenshot of the new prompt.  The cascade checkbox will remain checked by default.

![Screen Shot 2020-12-07 at 12 10 02 PM](https://user-images.githubusercontent.com/7726022/101400905-8c50e780-389f-11eb-9f9f-1a15e0dd97e6.png)

**Comment by rbreeze** [comment]
@keithchong @chiragthaker was this fixed by #4994 ?

**Comment by alexmt** [comment]
This is fixed now. Popup message explains the danger of cascade deletion and ask user to type the app name.

**Comment by benjamin-bergia** [comment]
Hi,

sorry to come back on this but it looks like on v2.5.x this is back to the original behavior (cascade by default).
Is there any way to define on applicationsets and application that deletion shouldn't be cascading by default in the current version? Is removing the finalizer effective and the recommended way to go? I manage my applicationsets with argocd itself so I can really pass CLI options.
