### ISSUE TITLE
ArgoCD Sync Waves should be followed during app deletion

### ISSUE THREAD

**Issue by whitleykeith** [argoproj/argo-cd#3211]
# Summary

When deleting an application, Argo should maintain sync waves during deletion at follow the reverse order for deletion.

i.e. I have a application that deploys manifest A at phase 0 and manifest B at phase 1. When deleting the application, it should delete B first and then A. 

# Motivation

When deploying applications that have an Operator + Custom Resource, we want the deletion to delete the Custom Resource, the operator, and then the CRD. Currently doing this can cause a hang on deletion since sometimes the operator will get deleted first. 

# Proposal

Sync waves should be following in reverse order during deletion, i.e. delete phase 3 -> phase 2 -> phase 1.

**Comment by raiviskrumins** [comment]
Having the same issue
