### ISSUE TITLE
Helm 3 pull timeout for stable repo

### ISSUE THREAD

**Issue by jessebye** [argoproj/argo-cd#3229]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
Trying to install a Helm chart from the stable repo (https://kubernetes-charts.storage.googleapis.com) results in a timeout:

```
time="2020-03-12T19:21:39Z" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:https://kubernetes-charts.storage.googleapis.com,Path:,TargetRevision:2.10.0,Helm:&ApplicationSourceHelm{ValueFiles:,Parameters:HelmParameter{},ReleaseName:,Values:image:\n  pullPolicy: Always\nnodeSelector:\n  ec2.amazonaws.com/type: core\ntolerations:\n  - key: \"dedicated\"\n    operator: \"Equal\"\n    value: \"core\"\n    effect: \"NoSchedule\"\nresources:\n  requests:\n    memory: \"256Mi\"\n    cpu: \"125m\"\n  limits:\n    memory: \"512Mi\"\n    cpu: \"250m\"\n,FileParameters:HelmFileParameter{},},Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,Chart:metrics-server,}/2.10.0"
time="2020-03-12T19:21:39Z" level=info msg="helm pull --destination /tmp/helm200834011 --version 2.10.0 --repo https://kubernetes-charts.storage.googleapis.com metrics-server" dir="/tmp/https:__kubernetes-charts.storage.googleapis.com" execID=UY9bz
time="2020-03-12T19:22:10Z" level=error msg="`helm pull --destination /tmp/helm200834011 --version 2.10.0 --repo https://kubernetes-charts.storage.googleapis.com metrics-server` failed signal: killed" execID=UY9bz
time="2020-03-12T19:22:10Z" level=error msg="finished unary call with code Unknown" error="`helm pull --destination /tmp/helm200834011 --version 2.10.0 --repo https://kubernetes-charts.storage.googleapis.com metrics-server` failed signal: killed" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2020-03-12T19:22:39Z" grpc.service=repository.RepoServerService grpc.start_time="2020-03-12T19:21:39Z" grpc.time_ms=30896.03 span.kind=server system=grpc
```

**To Reproduce**
1. Add the stable repo to Argo CD using repo URL https://kubernetes-charts.storage.googleapis.com. Note that the repo shows a connection status of "Successful."
2. Create an application from this repo, such as `metrics-server`.
3. Receive an error in the UI, and see the above message in the `argocd-repo-server` logs.

**Expected behavior**

The chart should have been installed successfully.

**Screenshots**

n/a

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.5.0+e13bb79
  BuildDate: 2020-03-11T17:10:19Z
  GitCommit: e13bb795782d4448408d870816c1696441b6b58b
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0
```

**Logs**

n/a

**Comment by jannfis** [comment]
Hi @jessebye, do you allow the `argocd-repo-server` direct access to the Internet? This looks like a bit like a network issue to me, where the connection from `argocd-repo-server` to the repository is blocked somewhere.

The connection status for the repository is generated by `argocd-server`, so might not necessarily reflect on repo server's situation. Thinking about it, it might be a good idea to change this and get connection status from repo server directly. 

Manual execution `helm pull` from within ArgoCD container works fine:
```
argocd@e2b927c249a5:~$ mkdir /tmp/helm200834011
argocd@e2b927c249a5:~$ helm pull --destination /tmp/helm200834011 --version 2.10.0 --repo https://kubernetes-charts.storage.googleapis.com metrics-server
argocd@e2b927c249a5:~$ echo $?
0
argocd@e2b927c249a5:~$ helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**Comment by jessebye** [comment]
Just found that this was due to setting the resource limits too aggressively. I had uncommented the defaults in the helm values.yaml [here](https://github.com/argoproj/argo-helm/blob/664829aa2472973ef2c5acdacf8507b88e35cd44/charts/argo-cd/values.yaml#L618) but those aren't enough resources to do operations like pulling the chart.

**Comment by jessebye** [comment]
I created this PR to help fix this for anyone else: https://github.com/argoproj/argo-helm/pull/264
