### ISSUE TITLE
Add Two-factor authentication

### ISSUE THREAD

**Issue by momoYB** [argoproj/argo-cd#3257]
# Summary

ArgoCD supports basic authentication with user/password. Missing support for **Two-factor Authentication** could lead to cluster compromise in case of user password leakage.

# Motivation

User/password protection for administration tools is not enough as a password could leak, could be weak, could be reused, etc. and in such case, an attacker could use the Argo and compromise the landscape.

# Proposal

Introduce **2FA** as an authentication method for Argo.

**Comment by jessesuen** [comment]
We do not intend to extend the local account feature past its current capabilities for basic username/password login and API keys. The primary intended mode is for Argo CD to integrate with SSO providers, which can enforce MFA as part of the OAuth2 exchange.
