### ISSUE TITLE
Ignore gke-resource-quotas in orphaned resources monitoring

### ISSUE THREAD

**Issue by paveq** [argoproj/argo-cd#3259]
# Summary

Orphaned resources monitoring should ignore "gke-resource-quotas", which is automatically created by GKE control plane.

# Motivation

Orphaned resources warning is less useful, if there's always warning about gke-resource-quotas

# Proposal

Ignore GKE auto-generated resource:
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gke-resource-quotas

```

**Comment by jessesuen** [comment]
We now have exceptions feature for orphaned resource monitoring:

https://argoproj.github.io/argo-cd/user-guide/orphaned-resources/#exceptions
