### ISSUE TITLE
Config management plugin with name 'helm-secrets' is not supported.

### ISSUE THREAD

**Issue by srehmanproov** [argoproj/argo-cd#3267]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

FATA[0002] rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Destination server and/or namespace missing from app spec;InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = Config management plugin with name 'helm-secrets' is not supported.

**To Reproduce**

Setup argocd to GKE cluster
Add application via argocd app create dev  --repo https://github.com/xxx/xxx.git  --dest-server https://xxx-4xxxx443 --config-management-plugin helm-secrets

`FATA[0002] rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Destination server and/or namespace missing from app spec;InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = Config management plugin with name 'helm-secrets' is not supported`
**Expected behavior**
Should create app with helm secrets

**Screenshots**

NA

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.16.1
  Kubectl Version: v1.14.0
```

**Logs**

```
FATA[0002] rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Destination server and/or namespace missing from app spec;InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = Config management plugin with name 'helm-secrets' is not supported.
```

**Comment by alexmt** [comment]
Hello @srehmanproov ,

I assume the `helm-secrets` plugin is configured. Do you have two configure plugins in the configuration? If yes then most likely you are seeing this bug : https://github.com/argoproj/argo-cd/issues/3058 . The fix is available in It is fixed in 1.5-rc1 release.

**Comment by srehmanproov** [comment]
@alexmt helm-secrets  is configured in repo server and ready to be used. I have only one plugin installed.

**Comment by alexmt** [comment]
can you please share config map path that contains plugin definition. Just want to check if something is missing

**Comment by srehmanproov** [comment]
`kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-cm
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: {{ .Values.server.name }}
data:
{{- toYaml .Values.server.config | nindent 4 }}
data: 
  configManagementPlugins: |
    - name: helm-secrets
      generate:
        command: ["/bin/sh", "-c"]
        args: [" GOOGLE_APPLICATION_CREDENTIALS=gcp-app-cred-volume helm secrets template -f ../../helm/helm_var/dev/values.yaml -f ../../helm/helm_var/dev/secrets.yaml -f ../../helm/helm_var/dev/resource_values.yaml -f ../../helm/helm_var/values.yaml -f ../../helm/helm_var/secrets.yaml --name $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE . > tmp.yaml && sed '$d' tmp.yaml && rm tmp.yaml"]`

**Comment by alexmt** [comment]
Look like the `data` field is duplicated. 

```
data:
{{- toYaml .Values.server.config | nindent 4 }}
data: 
...
```

So second occurrence that contains `configManagementPlugins` is ignored.

**Comment by srehmanproov** [comment]
@alexmt `data:
{{- toYaml .Values.server.config | nindent 4 }}
    configManagementPlugins: |
      - name: helm-secrets` 

I was getting yaml error `Unable to create application: error converting YAML to JSON: yaml: line 1: did not find expected '-' indicator`
 so I tried to work around by adding another data. But seems its working on UI i can see helm-secret as plugin.

**Comment by alexmt** [comment]
thank you for confirming! So, the ticket can be closed, right?

**Comment by srehmanproov** [comment]
yes sure
