### ISSUE TITLE
Question: does argo-cd allows to work in pull architecture?

### ISSUE THREAD

**Issue by avielb** [argoproj/argo-cd#3268]
# Summary
 
I would like if argo-cd support the ability to auto update charts based on polling mechanism instead of pushing (webhooks).  
# Motivation
My motivation is to have the ability to deploy argo-cd in a k8s cluster and have it polling an SCM location or artifact repository and based on new releases use it to auto upgrade k8s resources / helm charts within the cluster

Please give examples of your use case, e.g. when would you use this.
AFAIK the current argo-cd flow is:
### Current flow
a change is pushed to github -> new release is created -> webhook sent to a cluster -> agent listens on new releases -> pulling and deploying newer version

### Example of the flow that I am talking about
a change is pushed to github -> new release is created <- agent listens on new releases -> pulling and deploying newer version
# Proposal

**Comment by alexmt** [comment]
Hello @avielb , 

Argo CD already supports Github pulling. By default, controller check repository every 3 minutes and push updates to the cluster if auto-sync is enabled.  The Webhook notification is optional and only required to detect changes quicker. 

The artifact repository monitoring is not implemented yet. This feature had been requested earlier: https://github.com/argoproj/argo-cd/issues/1648

**Comment by avielb** [comment]
thanks @alexmt for the quick answer. 
what about image registry, does it have the ability to poll for image registry changes?
