### ISSUE TITLE
--insecure flag not working 

### ISSUE THREAD

**Issue by siqusoft** [argoproj/argo-cd#3270]
trying to terminate at ALB  but  argocd-server  keep redirecting to https while the --insecure flag is set..on the deployement.

**Comment by alexmt** [comment]
Hello @siqusoft ,

Can you share argocd-server deployment spec?

**Comment by alexmt** [comment]
Just in case, here is an instance that uses --insecure flag and don't trigger redirect. https://cd.apps.argoproj.io/applications/argo-cd?node=apps%2FDeployment%2Fargocd%2Fargocd-repo-server%2F0

**Comment by siqusoft** [comment]
Thanks @alexmt!  i added alb.ingress.kubernetes.io/ssl-passthrough: "true" and it is working
