### ISSUE TITLE
Update to jsonnet v1.15.0

### ISSUE THREAD

**Issue by tehho** [argoproj/argo-cd#3277]
# Summary
Update to jsonnet v1.15.0

# Motivation
Using jsonnet std.member(arr, x) to check if arr contains x, released in v1.15.0

# Proposal
Not sure where this is included but i guess in the application controller or repo server

**Comment by jessesuen** [comment]
This should just be an update to our library dependency because we use https://github.com/google/go-jsonnet/releases. Contributions welcome!
