### ISSUE TITLE
--insecure flag ignore when adding cluster

### ISSUE THREAD

**Issue by BrentonWatt** [argoproj/argo-cd#3281]
**Describe the bug**

I'm trying to add an external cluster, using the argocd cluster add command. My cluster is an EKS cluster and lives in provisioned environment that I don't have much control over, as such an endpoint that argo seems to be using, the API Server Endpoint that EKS provisions, is not accessible normally, if I curl the endpoint 

```curl -vi https://NOT-THE-REAL-ENDPOINT.yl4.eu-west-X.eks.amazonaws.com/version```

I will get the same TLS error that argo gets, however, if I add the --insecure flag to my request then all is fine. If I add the --insecure flag to the argo command I get the same error.

FATA[0013] rpc error: code = Unknown desc = REST config invalid: Get https://NOT-THE-REAL-ENDPOINT.yl4.eu-west-X.eks.amazonaws.com/version?timeout=32s: net/http: TLS handshake timeout

It appears that the --insecure flag is either being ignore or I misunderstand the use of it in this context.

**Expected behavior**

When adding the --insecure flag, I expect argo to attempt to go through the entire process with --insecure behaving the same as it would in the curl environment

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.1+f8721a7
  BuildDate: 2020-01-22T22:59:33Z
  GitCommit: f8721a73609611dd481886a78f4b7ce16ef8747b
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**

```
FATA[0013] rpc error: code = Unknown desc = REST config invalid: Get https://NOT-THE-REAL-ENDPOINT.yl4.eu-west-x.eks.amazonaws.com/version?timeout=32s: net/http: TLS handshake timeout
```

**Comment by alexmt** [comment]
Hello @BrentonWatt , the `--insecure` is a global flag that disabled TLS between CLI and argocd server. 

Are you able to access cluster locally (e.g. does kubectl get pods work) ?

**Comment by BrentonWatt** [comment]
@alexmt Yes I am able to access the cluster locally.

**Comment by alexmt** [comment]
Very likely target cluster API server is not accessible from the Argo CD pod. I would recommend to ssh into the pod and try to connect manually using the same kubeconfig and kubectl.

**Comment by alexmt** [comment]
@BrentonWatt please lets use [slack](https://argoproj.github.io/community/join-slack) to troubleshot it.

**Comment by thomathom** [comment]
what was the solution?

**Comment by amaadilyas** [comment]
could you provide the solution?

**Comment by cdanmar** [comment]
Yes please, this is the first Google result for this issue

**Comment by axw703** [comment]
I was able to get around this by adding `insecure-skip-tls-verify: true` to my kubeconfig.

```YAML
apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://example.com:6443
    insecure-skip-tls-verify: true
