### ISSUE TITLE
Syncing apps incorrectly states "app synced", but this is not true

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#3286]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The popup for syncing many apps text is incorrect:

![Screen Shot 2020-03-25 at 9 47 49 AM](https://user-images.githubusercontent.com/1142830/77562903-d4e58380-6e7d-11ea-874a-1c68c7e3ba97.png)

**To Reproduce**

1. Click 'Sync App'
2. Sync some apps.

**Expected behavior**

Should really say something like "1/82 apps now syncing"

**Screenshots**

See above.

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.5.0+ab80a81.dirty
  BuildDate: 2020-03-19T20:03:22Z
  GitCommit: ab80a8126bebc681c0da17645181eeb25622155c
  GitTreeState: dirty
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0
```

**Logs**

```
N/A
```

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/3385
