### ISSUE TITLE
Badges do not work properly in App-of-Apps deployments

### ISSUE THREAD

**Issue by rbkaspr** [argoproj/argo-cd#3287]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

Using ArgoCD v1.5.0-rc1

**Describe the bug**
When using status badges on an application deployed using an App-of-Apps pattern, badges for the applications deployed by the main app will return 500 errors when browsing their image URLs. On the backend, argocd-server dumps multiple invalid memory address or nil pointer reference errors

**To Reproduce**
Enable status badges in ArgoCD

Deploy an App of Apps deployment similar to the example found here: https://github.com/argoproj/argocd-example-apps/tree/master/apps

Go to the App Details page for one of the child apps and copy the URL

Attempt to view the image URL in another tab

**Expected behavior**

See the badge image with the current sync status of the app

**Observed behavior**

502 error in the browser
*invalid memory address or nil pointer reference* in the application logs

**Version**

```shell
v1.5.0-rc1+3684a10
```

**Comment by alexmt** [comment]
Thank you! nice catch
