### ISSUE TITLE
Config management plugin with name ... is not supported (LOCAL SYNC)

### ISSUE THREAD

**Issue by AdamPodolski** [argoproj/argo-cd#3293]
**Describe the bug**

After updating the argocd-cm config map with the new plugin definition (the generate method) and creating an application with the --config-management-plugin flag, each way of syncing the app with the local manifests (by the --local flag) results in the error below:

"FATA[0000] Config management plugin with name ... is not supported."

**To Reproduce**

1. Create a repo (ssh connection) in the default project.
2. Create an app in the default project (with the repo assigned).
3. Update the argocd-cm config map, providing a new plugin definition.
4. Run: argocd app sync APP_NAME --local PATH_TO_YOUR_MANIFESTS

**Expected behavior**

A successful synchronization of the app, without any errors.

**Version**

It doesn't work (the same error) with the 1.4.2 either.
```shell
argocd: v1.5.0-rc1+3684a10
  BuildDate: 2020-03-20T22:40:14Z
  GitCommit: 3684a103327c67d84d0c68fce86d31091331b727
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.0-rc1+3684a10
  BuildDate: 2020-03-20T21:24:20Z
  GitCommit: 3684a103327c67d84d0c68fce86d31091331b727
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0
```

**Comment by alexmt** [comment]
@mayzhang2000 , this might be a good next ticket

**Comment by mayzhang2000** [comment]
Fixed in https://github.com/argoproj/argo-cd/pull/3326
