### ISSUE TITLE
need update help examples about account can-i

### ISSUE THREAD

**Issue by haoshuwei** [argoproj/argo-cd#3309]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

`argocd account can-i` examples issue.

**To Reproduce**
```
$ argocd account can-i
Can I

Usage:
  argocd account can-i ACTION RESOURCE SUBRESOURCE [flags]

Examples:

# Can I sync any app?
argocd account can-i sync applications '*'

# Can I update a project?
argocd account can-i update projects 'default'

# Can I create a cluster?
argocd account can-i create cluster '*'

Actions: [clusters projects applications repositories certificates]
Resources: [get create update delete sync override]
```

```
$ argocd account can-i create cluster '*'
FATA[0000] rpc error: code = InvalidArgument desc = [clusters projects applications repositories certificates] does not contain cluster
```

**Expected behavior**

```
$ argocd account can-i create clusters '*'
yes
```

**Version**

```shell
argocd: v1.5.0-rc2+f9f1bda
  BuildDate: 2020-03-26T05:16:16Z
  GitCommit: f9f1bdaabe86d7daedcf1679d6cbc8cda2a16d3d
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: darwin/amd64
```

**Comment by jannfis** [comment]
Closed via #3310
