### ISSUE TITLE
Creating app with plug as an option does not work unmarshal manifest: error

### ISSUE THREAD

**Issue by srehmanproov** [argoproj/argo-cd#3311]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
Create a simple app and specify a plugin either with UI or CLI. As soon as create is pressed this error appears.
Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in helm/dev: rpc error: code = Unknown desc = Failed to unmarshal manifest: error unmarshaling JSON: json: cannot unmarshal string into Go value of type map[string]interface {}

**To Reproduce**

Create a simple app
Add plugin as helm-secrtets. Plugin is installed and registered as expected.
Pressing create or sending command to create app with cli returns error message.

**Expected behavior**

App should be created.
**Screenshots**

Fails to create app.
**Version**

```shell
Paste the output from `argocd version` here.
```
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexmt** [comment]
Resolve in a slack conversation https://argoproj.slack.com/archives/CASHNF6MS/p1585593711189500?thread_ts=1585585361.174500&cid=CASHNF6MS

**Comment by ramapalani** [comment]
Can you also add the resolution here?

**Comment by srehmanproov** [comment]
So for me issue was if you are using plugin like helm secrets, you can add helm in same yaml file.
