### ISSUE TITLE
[Feature request] Pause and Resume

### ISSUE THREAD

**Issue by BlackMix** [argoproj/argo-cd#3317]
# Summary
![](https://i.imgur.com/KCrwTCD.png)

# Motivation
The idea I have is this one of the image, I'm doing it manually but it would be interesting to have this option right on the card
I will study the source code a little to understand how it works, I think it will not be difficult to do this

# Proposal
What do you think about adding a deploy pause/resume button functioning as a scale --replicas=0/?
the idea can save the previous state of the replicas the total that the deploy used, so when you give the resume the replicas will be the same

**Comment by musabmasood** [comment]
We were thinking about this too wondering why you closed this. We sometimes need to pause sync (or override sync policy) for manually checking stuff.
