### ISSUE TITLE
First-class support for JK

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#3322]
# Summary

Support [JK](https://jkcfg.github.io/#/) in a first-class way similar to Helm/Kustomize/Jsonnet.

# Motivation

JK is a small tool for generating configuration files. Why would you use this instead of existing tools? 

* Can scale define 100s of environments with slight differences (unlike Kustomize which become unwieldy quickly).
* Can patch existing resources (unlike Helm).
* 1st class support for YAML (unlike Jsonnet).
* Just plain Javascript syntax which means almost zero to learn and you get IDE auto-completion for free (unlike Jsonnet/Kustomize/Helm).

My initial experience of JK was considerably more positive that these existing tools - with a much shorter lead time between using the tool for the first time and being productive.

What not a custom tool?

You need to be able to define parameters as JK does not support environment variables. You could map environment variables to parameters.

JK is also quite simple, so the cost of integration would be low (thought as tools mature ... cost goes up).

# Proposal

How do you think this should be implemented?

**Comment by alexec** [comment]
@alexmt I'm thinking the big barrier to doing this with a custom tool is the lack of parameters for a custom tool. I wonder if we could have a way to specify parameters?

**Comment by squaremo** [comment]
It would be great to see support for `jk` in ArgoCD.
We can be accommodating with respect to the integration -- for example, on how environment variables are passed to the runtime.
Perhaps a good thing to start with would be to get `jk` working as a plugin, then we can see what the tricky bits are.

**Comment by alexmt** [comment]
I would like to ask for feedback for this proposal: https://github.com/argoproj/argo-cd/issues/5293 . The idea is that we improve config management plugins so that it provides first-class like experience. Let me know what you think please

**Comment by blakepettersson** [comment]
Seems like this should be possible with a [CMP](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/) nowadays.
