### ISSUE TITLE
argocd-cli sso login basehref [impossible]

### ISSUE THREAD

**Issue by zeph** [argoproj/argo-cd#3334]
**Describe the bug**
I can't provide on the CLI an fqdn/path address to login via SSO
(it seems that it has been designed without having in mind `basehref` might be used)

**To Reproduce**

- move ArgoCD to a subpath on a shared domain abc.corp.com/argocd
- mod the Deploy resource of argocd-server-controller adding `basehref` as `/argocd`
- all works great, until you decide to SSO login on CLI, there is no parameter for `/argocd`

**Expected behavior**

That I can provide either the absolute https:// address, or the fqdn/path or an extra parameter
...and login successfully

**Version**
I have the latest rc1 from 1.5.0 (both client and server)

**Comment by zeph** [comment]
nevermind, there is no need to go into such setup... quite an edge case

**Comment by cyrus-mc** [comment]
@zeph Sorry to resurrect this issue but why was there no need for this?

I have my ArgoCD instance exposed at URL https://services.xxx.xxx/argocd. When trying to use the CLI either to login or simply use option `get` with a defined token if I specify services.xxx.xxx/argocd for the server option it fails with

```
dial tcp: lookup services.xxx.xxx/argocd: no such host
```

I don't see any options to specify the sub-path when making the call.
