### ISSUE TITLE
Helm deployments don't evaluate `.Capabilities.APIVersions.Has` correctly

### ISSUE THREAD

**Issue by carlosjgp** [argoproj/argo-cd#3374]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Helm conditional render using `.Capabilities.APIVersions.Has` is not evaluated correctly or at least the rendered manifest makes me think that

**To Reproduce**

Deploy Grafana chart `5.0.4` or higher on a Kubernetes cluster `1.17.x` or older (no `networking.k8s.io/v1beta1` API)

[Grafana ingress](https://github.com/helm/charts/blob/master/stable/grafana/templates/ingress.yaml#L6) is rendered as `networking.k8s.io/v1beta1` on a `1.13` K8s cluster

**Expected behavior**

Manifest is rendered as `extensions/v1beta1`

**Screenshots**

N/A

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:04:04Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jannfis** [comment]
Hi @carlosjgp - I think the feature has been introduced in v1.5.0 as part of Helm Integration Enhancements - please see https://github.com/argoproj/argo-cd/releases/tag/v1.5.0

**Comment by alexmt** [comment]
I think we can close it. v1.4.2 does not support APIVersions . Feature was introduced in 1.5.0 . @carlosjgp please let us know if you see the same issue in 1.5
