### ISSUE TITLE
How to add Google Cloud Source Repo to ArgoCD hosted in GKE?

### ISSUE THREAD

**Issue by Rajeskumar** [argoproj/argo-cd#3379]
I have argoCD running in GKE and I want to add my Cloud Source Repo to the argocd.

Workload Identity is setup in GKE cluster for argoCD pod to talk to other Google Cloud components.
Added git credential helper script command to the argoCd pod as well as added gcloud in PATH. git config --global credential.'https://source.developers.google.com'.helper gcloud.sh

I was able to git clone the CloudSource repo into argoCD-server pod if ran kubectl exec into the pod.

How to add my Google Cloud Source repo to ArgoCD repositories list? Tried https connection using repo URL without a username and pwd and its not working.

How ArgoCD internally connect to the Repo URL we provide? Does it access via any REST API?

How can I make use of a Service Account to connect any Repo?

**Comment by jannfis** [comment]
Hi @Rajeskumar, I'm afraid that authentication methods other than specified at https://argoproj.github.io/argo-cd/user-guide/private-repositories/#credentials are not supported yet.

**Comment by Rajeskumar** [comment]
Thanks for the response @jannfis . Is there any changes/features in work in progress to support using Git Credential helper script got get the credentials to connect to a repo? or is it a new feature request?

**Comment by jannfis** [comment]
Hi @Rajeskumar, there was someone else trying to connect a repository using AWS IAM credential helper in #3291. 

I think maybe a feature request to implement GKE and AWS could be good to see if there's more people wanting that.

**Comment by Rajeskumar** [comment]
@jannfis Thanks for the response. I'll close this ticket for now. Hope the new feature gets implemented soon.

**Comment by Rajeskumar** [comment]
Reopening for clarifications:
@jannfis , you did mentioned in #3291 that we can make use of  `git-ask-pass.sh` to supply credentials to git via `GIT_ASKPASS`.

I have updated `git-ask-pass.sh` with gcloud script to fetch access-token to be passed in the password. But whenever i tried adding the repo, it still failing because of authentication failure. So I doubt the GIT_ASKPASS env variable is referred when creating the repo.

When ArogCD uses `GIT_ASKPASS` to fetch the creds ?
Can we create a repo without providing username, password and also certificates, either through argocd-cli or UI?

**Comment by Rajeskumar** [comment]
Reopening for Clarification:
@jannfis as per you comment on #3291, argocd-repo-server uses `git-ask-pass.sh` to fetch the creds for the repo. I have updated the script. 
Is there anyway to test `repo-server` connection to repo separately?

argocd-server (API server) uses go-git to connect to the repo.
Does `go-git` supports `credentials-helpers` to connect to repo?

**Comment by Rajeskumar** [comment]
Found out go-git doesnt support credentials-helper. 
Also, I have customized argocd code base to support my use case to connect to cloud source repo.

**Comment by AlfredHudson** [comment]
@Rajeskumar Can you share your code, we are having the same issue trying to connect Argocd from GKE to GCP Source Repo. 

We don't have the ability to use GServiceAcount keys so it is possible maybe with WorkloadIdentity to grant acces to Source repo with KSA/GSA binding?

**Comment by erdenayates** [comment]
Is there any new update about Google Cloud Source Repositories and ArgoCD connections?

**Comment by alexef** [comment]
@erdenayates yes, this will ship in 2.6 https://github.com/argoproj/argo-cd/issues/7534

**Comment by erdenayates** [comment]
hello @alexef 
thank you for the information
is there any documentation for that GCP and ArgoCD connection?
I have pasted service account private key and repository url but gives error
![gcp-argocd-2](https://user-images.githubusercontent.com/71449664/215891841-f423c3c1-3c62-4d24-9eb3-3b96d6e8b731.png)

![gcp-argocd](https://user-images.githubusercontent.com/71449664/215891369-6c5fe3f5-8bcc-4cc9-9c5a-d8e1750967d8.png)

**Comment by erdenayates** [comment]
after v2.6.2 release, everything seems clear and working fine @alexef 

https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#google-cloud-source
