### ISSUE TITLE
Follow tail of logs

### ISSUE THREAD

**Issue by tehho** [argoproj/argo-cd#3382]
# Summary

Add a checkbox in pod logs that allows you to toggle "--tail=0" on/off

# Motivation

If i follow a log of a long running pod i get all the logs from start.
When i need to check latest logs it would be nice to have an option for --tail=0 or --tail=$(YourNumberHere) to get only the latest logs

# Proposal

kubectl logs have the --tail=$(YourNumberHere), should be easy to have this in gui some how

**Comment by jgournet** [comment]
In addition to this feature, it would be great if this option (or an additional option?) could also disable the auto-refresh of the LOGS tab in argocd.
When the logs are long, it is impossible to scroll through them as the auto refresh will kick in and reset the whole page.
Either argocd should happen logs, or have an option to stop the refresh if needed

**Comment by jessesuen** [comment]
This will be available in v1.9
