### ISSUE TITLE
argocd-application-controller unexpectedly exit 

### ISSUE THREAD

**Issue by wayne-beep** [argoproj/argo-cd#3395]
version: v1.1.2+567fcc3.dirty

**Describe the bug**

argocd-application-controller unexpectedly exit with code 2 

**Logs**
goroutine 2999493 [sync.Cond.Wait, 35 minutes]:
sync.runtime_notifyListWait(0xc0229f5300, 0x7f7000000000)
	/usr/local/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc0229f52f0)
	/usr/local/go/src/sync/cond.go:56 +0x92
golang.org/x/net/http2.(*pipe).Read(0xc0229f52e8, 0xc0055c4000, 0x200, 0x200, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/pipe.go:64 +0x8a
golang.org/x/net/http2.transportResponseBody.Read(0xc0229f52c0, 0xc0055c4000, 0x200, 0x200, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/transport.go:1739 +0x95
encoding/json.(*Decoder).refill(0xc000bd5b80, 0xc0009da4f8, 0xc0009da4e8)
	/usr/local/go/src/encoding/json/stream.go:159 +0x102
encoding/json.(*Decoder).readValue(0xc000bd5b80, 0x0, 0x0, 0x171fee0)
	/usr/local/go/src/encoding/json/stream.go:134 +0x222
encoding/json.(*Decoder).Decode(0xc000bd5b80, 0x173b180, 0xc024621780, 0x1, 0x203004)
	/usr/local/go/src/encoding/json/stream.go:63 +0x78
k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc00456b740, 0xc0009f1000, 0x400, 0x400, 0x50, 0x38, 0x38)
	/go/src/k8s.io/apimachinery/pkg/util/framer/framer.go:150 +0x292
k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc022281f40, 0x0, 0x1b687e0, 0xc0101bdd80, 0xc0009da601, 0xc0009da6e8, 0x4898d6, 0xc022281188, 0x1b81401)
	/go/src/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go:77 +0x89
k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc024621760, 0x1a12e70, 0x0, 0x0, 0x0, 0xc016677e60, 0x0)
	/go/src/k8s.io/client-go/rest/watch/decoder.go:49 +0x7c
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc00456b770)
	/go/src/k8s.io/apimachinery/pkg/watch/streamwatcher.go:93 +0x136
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
	/go/src/k8s.io/apimachinery/pkg/watch/streamwatcher.go:60 +0x9f

**Comment by alexmt** [comment]
Hello @wayne-beep ,

The issue was fixed in 1.2:  https://github.com/argoproj/argo-cd/issues/1685

**Comment by ermazi** [comment]
@alexec if i rebuild argocd v1.1.2, will it be fixed?
