### ISSUE TITLE
Need complete audit trail

### ISSUE THREAD

**Issue by edlee2121** [argoproj/argo-cd#340]

**Comment by jessesuen** [comment]
Two things to do here:

1. A gRPC interceptor should be added to log all API server requests with details about the authenticated user and relevant parameters of the request. Ideally this would be done in a generic way. This may be possible using the reflect package to check for known fields (e.g. name, server).

2. Application controller should start emitting K8s events on everything that happens to an application (e.g. sync completed, presync failed, etc...)

**Comment by alexmt** [comment]
working on it
