### ISSUE TITLE
argocd repo add = Unimplemented desc = unknown method CreateRepository"

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-cd#3417]
argocd version: v1.2.0

Can add the repo via argocd GUI, but need to do it in CI pipeline via argocd cli.

argocd repo add $URL --username $USERNAME --password $PSW --insecure

returns level=fatal msg="rpc error: code = Unimplemented desc = unknown method CreateRepository"

**Comment by jannfis** [comment]
As a workaround, please use CLI from same version as your server.
