### ISSUE TITLE
Make default argo cd admin password more secure

### ISSUE THREAD

**Issue by edlee2121** [argoproj/argo-cd#3422]
# Summary

Currently, we use the argo cd pod name as the initial default admin password. The pod name, however, is visible to anyone who can enumerate pods in the argo cd namespace.

# Motivation

N/A

# Proposal

Store a randomly generated password as a secret in the argo cd namespace.
For convenience, the secret can be automatically deleted when the initial admin password is changed.

**Comment by jannfis** [comment]
I will take on this after 1.8 has been branched out.

**Comment by iam-veeramalla** [comment]
Hi @jannfis, I am happy to help on this. Have you already considered any approach for this?

**Comment by jannfis** [comment]
Hi @iam-veeramalla - oops, I've just right now seen your offer for help. Thank you for this offer! Unfortunately, I've seen it too late and just hacked the appropriate code today and created a PR #5138. But I would very much appreciate your review and input!
