### ISSUE TITLE
Make it harder to brute force passwords

### ISSUE THREAD

**Issue by edlee2121** [argoproj/argo-cd#3423]
# Summary

Today, we immediately return the results of a login attempt. This allows attackers to quickly retry failed attempts in an effort to guess the password.

Also, today, the time taken to respond is different depending on whether a usernames exists or not, allowing the attacker to guess whether a userid is valid.

# Motivation

N/A

# Proposal

We should wait a fixed time, say one second, from the time at which the request was received, before returning the result. Waiting from the time at which the request was received, ensures that we don't leak any information due to different code paths being exercised in response to the validity of the username or password.

For extra credit, we may want to increase the delay after each consecutive unsuccessful login attempt

**Comment by jannfis** [comment]
This is supposed to be implemented by #3404 - please take a look at the PRs description whether it's fine for us.

**Comment by edlee2121** [comment]
A second issue is that the time taken to respond is different depending on whether a usernames exists or not, allowing the attacker to guess whether a userid is valid. I was thinking that if we always add a delay and the delay starts from the time at which the logon request was received, it would address both issues.

**Comment by jannfis** [comment]
You are right. To prevent guessing of account names, I think we should introduce a notable but also random delay before any credential is actually checked. 

Probably a value between 0.5s and 1s should be OK to fuzz the time for execution of code paths between existing and non-existing accounts.

What do you think, @edlee2121?

**Comment by alexmt** [comment]
@jannfis here is the solution suggested by  @Eriner : https://github.com/argoproj/argo-cd/pull/3437 

Does it looks good to you?

**Comment by jannfis** [comment]
@alexmt I think that depends whether the costs of the hashing function is the same for strings of arbitrary length. If there is an observable timing difference in hashing string "a" as compared to string "for_consistent_response_time", I think we would have won nothing.

I'm not sure, but I thought the costs for creating a `bcrypt` hash is *also* dependent on the length of the password input, so that computing would become more expensive with a longer password (but I might be wrong here).

**Comment by alexmt** [comment]
@jannfis did a quick research about time-based user enumeration attacks. All articles I've found suggest introducing a random delay. So I agree with you suggestion.

**Comment by jannfis** [comment]
@alexmt After a little thinking, I was coming up with the idea that maybe a combination of both methods would be the best. Calculate cryptographic hash for non-existing user (but from the supplied password, not a static string as to not introduce another timing vector) and then a random delay, to cover up any possible differences in the code path.

**Comment by Eriner** [comment]
> I think that depends whether the costs of the hashing function is the same for strings of arbitrary length.

This should always be the case for bcrypt, as the cost is based on real-world time, not a multiplicative iteration count. In addition, the bcrypt provider in Argo calls the following bcrypt function:
```
// CompareHashAndPassword compares a bcrypt hashed password with its possible
// plaintext equivalent. Returns nil on success, or an error on failure.
func CompareHashAndPassword(hashedPassword, password []byte) error {
	p, err := newFromHash(hashedPassword)
	...omitted for brevity...
	if subtle.ConstantTimeCompare(p.Hash(), otherP.Hash()) == 1 {
		return nil
	}

```

A suggestion for preventing brute force, if there have been >5 (or whatever value you're comfortable with) failed login attempts, flip a bit and lock the account until time.Now().Add(rand*time.Second), where rand is an int between 30 and 180. An account which is locked should always return a 401 unauthenticated regardless of if the submitted password hash matches or not. It should still compute the hash, and should not short-circuit until the end of the function where it checks account lock status.

There is no need to provide any additional feedback about accounts being locked, simply failing the authentication is sufficient. If feedback is provided about accounts being locked, then accounts that do not exist must be able to be locked (as not to introduce a user enumeration vulnerability).

**Comment by Eriner** [comment]
I say this because simply delaying the response after a login attempt just adds artificial time to the response -- it would do nothing to stop an attacker from queueing lots of requests and just waiting the 1s to read the response.

**Comment by jannfis** [comment]
Thank your for this food for thoughts, @Eriner - much appreciated. 

> I say this because simply delaying the response after a login attempt just adds artificial time to the response -- it would do nothing to stop an attacker from queueing lots of requests and just waiting the 1s to read the response... Unless there's a user-tied sync.Mutex, but that seems really hacky to me.

This makes total sense, I agree. But imho, account lockouts would provide quite a surface for DoS attacks, if the attacker knows any of the target usernames. A legitimate user would not have any possibility to unlock their account while it is under attempt of a brute-force attack. A limit on concurrent login attempts for the same user would not make sense, I agree. This would provide a similar DoS surface as locking the user acount, as it'd be basically the same during an attack.

I'm unsure whether we should lock the account without providing the legitimate user with a possibility to unlock it. Or we decide, that once we are in such a situation, we'd need someone with administrative permissions on the K8s cluster anyway.

So the main question open for discussion is, whether it's ok for us that we completely lock user accounts that are under active attack?

**Comment by Eriner** [comment]
> Or we decide, that once we are in such a situation, we'd need someone with administrative permissions on the K8s cluster anyway.

I vote this way. If someone is attacking your CI/CD system, that's probably something you'd want to deal with right away as a cluster operator.

> So the main question open for discussion is, whether it's ok for us that we completely lock user accounts that are under active attack?

It should be obvious, but I vote yes, though I suggest providing a configuration toggle to disable the on-by-default account locking, as well as a configurable option for the number of failed attempts before temporary account lockout. That way the choice is ultimately left up to the operator but we establish a more secure default.

**Comment by Eriner** [comment]
```go
type LoginOptions struct {
	LockoutDisabled            bool     // default: false
	LockoutAfterFailedAttempts int      // default: 10
	LockoutExclusions          []string // ex: []string{"admin"}
}
```

**Comment by edlee2121** [comment]
My preference is to keep it simple and avoid locking accounts, which could be disruptive to users and requires establishing organizational processes for unlocking accounts.

I'd like to combine a few of the earlier suggestions. Always hash and add random delay between .5 and 1 seconds from the **time at which the request was received**.

Also, limit the maximum number of concurrent login attempts across all users to N. No queuing of login requests.
