### ISSUE TITLE
Expose cascade option for application delete in HTTP API

### ISSUE THREAD

**Issue by thatsmydoing** [argoproj/argo-cd#3428]
# Summary

Currently, you can turn off cascade delete in the `argocd` CLI which uses the GRPC API, but this is not exposed when going by HTTP.

# Motivation

When building a service that interfaces with argocd via the HTTP API. This can be worked around by using GRPC instead but that's non-trivial most of the time. Alternatively, one can delete it via the kubernetes API but that requires separate authentication and the RBAC isn't as rich.

# Proposal

Allow passing a `cascade` parameter for application deletes.

**Comment by jannfis** [comment]
This is already possible, as the web UI uses the HTTP RESTful API as well. 

I think the query parameters are just not exposed in the swagger file - I've seen that this is the case for all DELETE verbs on all resource endpoints. The reason for this is beyond my knowledge, it might even be a bug in the swagger generator we use. I will do some more research.

In the meanwhile, you should be able to use cascade delete by simply passing a `?cascade=true` query parameter to your `DELETE` call on the application resource.

**Comment by thatsmydoing** [comment]
Oh, I see. I hadn't actually tried since it wasn't in the swagger file. That's good to know.
