### ISSUE TITLE
Getting permission Denied application destination is not permitted in project

### ISSUE THREAD

**Issue by JazminGonzalez-Rivero** [argoproj/argo-cd#343]
Looks like the default project is not working as expected. 

I did the regular getting started setup and I get the following error. 

![image](https://user-images.githubusercontent.com/1447492/42118412-c286e0cc-7bb7-11e8-8859-fd7e511a5a65.png)

**Comment by jessesuen** [comment]
This is blocking me. Working on a fix.

**Comment by alexmt** [comment]
@jessesuen Unless you are already done here is PR: https://github.com/argoproj/argo-cd/pull/345
