### ISSUE TITLE
/usr/local/bin/argocd: line 1: Not: command not found

### ISSUE THREAD

**Issue by jasvinder-tp** [argoproj/argo-cd#3430]
I have jenkins docker image, above I am installing argocd, to run argocd for deployment through jenkins:

ARGOCD steps in Docker file:

# Setup ARGOCD
RUN VERSION=$(curl --silent "https://api.github.com/repos/argoproj/argo-cd/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
RUN curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/$VERSION/argocd-linux-amd64
RUN chmod +rwx /usr/local/bin/argocd
RUN chown jenkins /usr/local/bin/argocd
RUN mkdir /home/jenkins/.argocd/
COPY files/config /home/jenkins/.argocd/config

In jenkins docker, it has:
jenkins@1a066664d4c3:/usr/local/bin$ ls -ltr argocd
-rwxr-xr-x 1 jenkins staff 9 Apr 16 11:23 argocd

Error: 
jenkins@1a066664d4c3:/usr/local/bin$ argocd
/usr/local/bin/argocd: line 1: Not: command not found

My Docker ubuntu version:

jenkins@1a066664d4c3:/usr/local/bin$ cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by jannfis** [comment]
Hi @jasvinder-tp, it's very clear that this is an issue with your toolchain, not with ArgoCD. It seems that your download of the argocd binary does not work. I will close this issue.

**Comment by Chabane** [comment]
same issue
how did you please fix the issue @jasvinder-tp ?

**Comment by jasvinder-tp** [comment]
It was permission issue to user, which try to run argocd bin, change source image of "Debian GNU/Linux 9 (stretch)" to other, then working fine

**Comment by lunyi** [comment]
@jasvinder-tp  I have same issue, and I use Ubuntu 18.04. how do i fix the issue ?

**Comment by jabz-eks** [comment]
hello there,

I am still facing the same issue. could you please let us know how did yuo resolve this issue?

+ cat /etc/os-release /etc/system-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)

**++ argocd login *************  --username admin --password *****  --insecure
/usr/local/bin/argocd: line 1: $'\r': command not found
/usr/local/bin/argocd: line 2: html: No such file or directory
/usr/local/bin/argocd: line 3: head: No such file or directory
/usr/local/bin/argocd: line 4: meta: No such file or directory**

**Comment by tschale** [comment]
@jabz-eks Did you open the file under `/usr/local/bin/argocd`? I figured out that it contained `Not found`... I replaced `$VERSION` in the curl command with the actual value, bash seemingly didn't substitute it correctly...
