### ISSUE TITLE
error unmarshaling JSON: unknown connector type "openshift"

### ISSUE THREAD

**Issue by sharif-rahman** [argoproj/argo-cd#3436]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

The problem is related to connection 
iam trying  OpenShift Authentication Integration with ArgoCD

**To Reproduce**
```
Dex-Server Service account Setting:
  annotations:
    serviceaccounts.openshift.io/1oauth-redirecturi.argocd: >-
      http://argocd-ocp-argocd.apps.cluster-9030.9030.sandbox205.opentlc.com/api/dex/callback

```
```
kind: ServiceAccount
apiVersion: v1
metadata:
name: argocd-dex-server
namespace: ocp-argocd
selfLink: /api/v1/namespaces/ocp-argocd/serviceaccounts/argocd-dex-server
uid: cbf0a43f-5616-4bb4-9eff-adb8ce28a548
resourceVersion: '2002430'
creationTimestamp: '2020-04-17T10:22:00Z'
labels:
app.kubernetes.io/component: dex-server
app.kubernetes.io/name: argocd-dex-server
app.kubernetes.io/part-of: argocd
annotations:
serviceaccounts.openshift.io/oauth-redirecturi.argocd: 'http://argocd-ocp-argocd.apps.cluster-9030.9030.sandbox205.opentlc.com/api/dex/callback'
```

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**
Redirect after the Login is done
ArgoCD Login Page --> Redirect (Openshift Login Page) --> Return back to ArgoCD

**Version**
```
argocd version: v1.5.2
quay.io/dexidp/dex:v2.21.0
```

**Logs**

```
error parse config file /tmp/dex.yaml: error unmarshaling JSON: unknown connector type "openshift"
```

**Comment by jannfis** [comment]
Hi @sharif-rahman, according to Dex release notes, OpenShift support was first introduced with `v2.22.0` (refer to https://github.com/dexidp/dex/releases/tag/v2.22.0), while ArgoCD yet bundles `v2.21.0`. 

Updating bundled Dex to latest version is planned, see #3339

I'm closing this bug as invalid, please follow the enhancement request above and re-open this issue if OpenShift support fails when Dex has been upgraded.

**Comment by sharif-rahman** [comment]
Thanks for your update. if thats the problem then why the Basic argocd version: v1.5.2 document examplains to use dex:v2.21.0?

**Comment by absynth76** [comment]
> Thanks for your update. if thats the problem then why the Basic argocd version: v1.5.2 document examplains to use dex:v2.21.0?

I completely agree, look here: https://argocd-operator.readthedocs.io/en/stable/reference/argocd/#dex-example
documentation should be updated at least
