### ISSUE TITLE
Add exceptions list for Orphaned resources.

### ISSUE THREAD

**Issue by neilharris123** [argoproj/argo-cd#3450]
# Summary

It would be useful to be able to add some resources which ArgoCD considers orphaned to an exception list so that warnings are not received for known resources that ArgoCD considers orphaned. 

# Motivation

There are certain helm charts that deploy resources that for some reason do not come under the umbrella of being part of the Application in ArgoCD. 

There are also things like tokens that appear as orphaned resources. 

The orphaned resources warning gives many false positives and having an exception list would provide a method for users to pick and choose which resources should be ignored.

**Comment by Purneau** [comment]
Another use case: 
The tls secrets generated by cert-manager for our ingresses are also placed in the app's namespace. ArgoCD reports them as orphaned as well, while we think this is a regular pattern.

**Comment by rachelwang20** [comment]
Closing - implement in #3922 and #3900
