### ISSUE TITLE
Filter pod logs by log level

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#3455]
# Summary

Provide a way filter of pod logs.

# Motivation

The pod logs view can show too many resources, but I just want to see errors

# Proposal

In the UI.

**Comment by alexmt** [comment]
@alexec do you suggest filtering lines using regex or stderr vs stdout?

Kubernetes does not support separating stderr from stdout. https://github.com/kubernetes/kubernetes/issues/28167

**Comment by alexec** [comment]
A cheap solution - just show lines with the word "error" in it.
