### ISSUE TITLE
Status panel the text overflows.

### ISSUE THREAD

**Issue by martinjaimem** [argoproj/argo-cd#3459]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When the status panel has an item that is too big to enter in the box then the text overflows.

**To Reproduce**

One way of reproducing this would be having a 13 inch screen and a deployer email signature too big (see screenshot)

**Expected behavior**

The description should not overflow the box

**Screenshots**

<img width="340" alt="Screen Shot 2020-04-21 at 22 35 55" src="https://user-images.githubusercontent.com/50113670/79931091-81386c80-8420-11ea-8c7a-a551b3301c8b.png">

**Version**

```shell
v1.4.2+48cced9
```

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/3460

**Comment by alexmt** [comment]
It appears that UI needs a little more work. In addition to hidden overflow we need to increase toolbar height, overwise even single line commits don't fit.

**Comment by rbreeze** [comment]
Looks like this was addressed and overflowing text is now hidden with ellipses: 

<img width="355" alt="Screen Shot 2020-07-27 at 6 26 47 PM" src="https://user-images.githubusercontent.com/6250584/88608485-bdd6be00-d036-11ea-881e-2f9d44e76a37.png">
