### ISSUE TITLE
Sorely missed features in application files

### ISSUE THREAD

**Issue by cyrilcros** [argoproj/argo-cd#3469]
# Summary

ArgoCD is a very nice project with a good GUI but misses some obvious features due to misguided security concerns.

# Motivation

I wanted to switch from flux / helm-operator to argo-cd but there are major issues which I think could be fixed relatively easily, which do not occur with my previous set up. I also wasn't able to make pull requests (on ubuntu 18.04: `make codegen` fails due to permission issues on `/tmp`).

# Proposal

- Applications don't use Helm value files outside the desired helm chart repository for "security reasons" (but accept random URLs, or values within the Application file...). This is unfortunate because value files within public chart repositories are typically nothing more than reasonable defaults to be replaced for your own use case. 
Any yaml file should be valid, and you should be able to access them from the repository where the application file lives. I shouldn't have to copy my value files inside an Application or create a new chart pulling an existing chart as a dependency, as other users seem to do.
[I suspect this could be done by simply removing this test](https://github.com/argoproj/argo-cd/blob/05f5a7992370c54309f99c8cb4e16cd2c027463d/reposerver/repository/repository.go#L267)

- The [cluster bootstrapping](https://argoproj.github.io/argo-cd/operator-manual/cluster-bootstrapping/) doesn't work as advertised at all. It only allows for modification of a single destination namespace and will block modification of other namespaces for "security reasons". 
That's rather useless. If I wanted to restrict namespace access I would use RBAC/the kubeconfig file I supply to argocd, not argocd itself.

- I can't put any application file in the root of a Github repository. Argocd refuses to accept an empty 'path', even if I do want to synchronize everything within a repository.

**Comment by jannfis** [comment]
Hi @cyrilcros - can you please elaborate a little more?

1. The restriction to not let you Helm values files from an arbitrary location is not to "protect" your Helm application, but to prevent Helm reading arbitrary files from outside the scope it should. Keep in mind that ArgoCD possibly manages applications from more than one tenant, so your application should be confined from other applications managed in the system, and especially some possible more or less confidential data the other repos might contain. The file system of the repo-server is one important part in this confinement. I agree tho, that it is mislabeled as "security" feature, whereas it should be just considered "good practice".

2. I don't see what you mean? Where do the instructions in this document restrict you to anything?

3. Try using `.` as value for th path, this will let you use the repo's top level directory as source.

As for the permissions error you get during `make codegen`, can you please be a little more concise?

**Comment by cyrilcros** [comment]
1. Alright, but could you consider a Gitops pattern where I have an application ressource file in a Git repo that deploys some public helm chart, and my value files somewhere in the same repo, maybe with a different path? That doesn't seem to work. That also matters if you follow a logic where you need to switch between multiple `env-specific-values.yaml` files.

2. Let's say I have some apps that targets different namespaces within a cluster: appA : argocd -> namespaceA, appB : argocd -> namespaceB. Both work fine in isolation. I can create an 'app-of-apps' that deploys appA and appB using Application ressource files, but I will need to specify a target namespace for my 'app-of-apps'. The other app will get a `namespace/namespaceX unchanged` status. 
Syncing child apps does not change this. The docs avoid that issue by considering example apps deployed from and to the argocd namespace. 

3.  That worked out, thanks.

Local dev: all steps work until `make codegen`.

`> make codegen`
`docker run --rm -it --name argocd-test-client -u 1000 -e HOME=/home/user -e GOPATH=/go -e ARGOCD_E2E_K3S= -e GOCACHE=/tmp/go-build-cache -e ARGOCD_LINT_GOGC=20 -v /home/cyril/go/src:/go/src:delegated -v /home/cyril/.cache/go-build:/tmp/go-build-cache:delegated -v /home/cyril/.kube:/home/user/.kube:delegated -v /tmp:/tmp:delegated -w /go/src/github.com/argoproj/argo-cd argoproj/argocd-test-tools:v0.2.0 bash -c "make codegen-local"`
` go generate ./util/argo/...`                                                                                                                                                                     `failed to initialize build cache at /tmp/go-build-cache: mkdir /tmp/go-build-cache/00: permission denied   `     
`util/argo/normalizers/knowntypes_normalizer.go:17: running "go": exit status 1` 
`make: *** [Makefile:132: gogen] Error 1  `
`Makefile:151: recipe for target 'codegen' failed`
`make: *** [codegen] Error 2 `

`> sudo -E make codegen`
`/bin/sh: 1: go: not found    `                                                                                                                                                                   `docker run --rm -it --name argocd-test-client -u 0 -e HOME=/home/user -e GOPATH=/go -e ARGOCD_E2E_K3S= -e GOCACHE=/tmp/go-build-cache -e ARGOCD_LINT_GOGC=20 -v /src:/go/src:delegated -v /home/cyril/.cache/go-build:/tmp/go-build-cache:delegated -v /home/cyril/.kube:/home/user/.kube:delegated -v /tmp:/tmp:delegated -w /go/src/github.com/argoproj/argo-cd argoproj/argocd-test-tools:v0.2.0 bash -c "make codegen-local"      `
`make: *** No rule to make target 'codegen-local'.  Stop`
`Makefile:151: recipe for target 'codegen' failed  `                                                                                                                                              `make: *** [codegen] Error 2 `     `

**Comment by jannfis** [comment]
>  Alright, but could you consider a Gitops pattern where I have an application ressource file in a Git repo that deploys some public helm chart, and my value files somewhere in the same repo, maybe with a different path? That doesn't seem to work. That also matters if you follow a logic where you need to switch between multiple `env-specific-values.yaml` files.

If your values files reside in the same Git repository as your chart, this should be no problem. Considering a repository structure like the following
```
chart/
  Chart.yaml
env-dev/
  values-dev.yaml
env-int/
  values-int.yaml
```
You should be able to use values file `../env-dev/values-dev.yaml` . This obviously only works, when the chart you are about to install is stored in Git. 

>  Let's say I have some apps that targets different namespaces within a cluster: appA : argocd -> namespaceA, appB : argocd -> namespaceB. Both work fine in isolation. I can create an 'app-of-apps' that deploys appA and appB using Application ressource files, but I will need to specify a target namespace for my 'app-of-apps'. The other app will get a `namespace/namespaceX unchanged` status.
>        Syncing child apps does not change this. The docs avoid that issue by considering example apps deployed from and to the argocd namespace.

I'm not sure whether I understood you correctly. 

All `Application` resources need to reside in the `argocd` namespace, this is a limitation by design. So the parent application's namespace is set to `argocd`. This is not the final target namespace for the actual resources installed by the child applications, however. The `Application` objects for the children can then specify any other namespace (allowed by their associated `AppProject` constraints) where to install their specific resources. 

So consider app-of-apps pattern:

```
parent-app: (type Application, installed in ns: argocd, target ns: argocd)
  child-app-1 (type Application, installed in ns: argocd, target ns: namespaceA)
    resources-of-child1 (type various, installed in ns: namespace A)
  child-app-2 (type Application, installed in ns: argocd, target ns: namespaceB)
    resources-of-child2 (various types, installed in ns: namespace B)
```

I hope that clarifies it a bit.

> Local dev: all steps work until `make codegen`.
> 
> `> make codegen`
> `docker run --rm -it --name argocd-test-client -u 1000 -e HOME=/home/user -e GOPATH=/go -e ARGOCD_E2E_K3S= -e GOCACHE=/tmp/go-build-cache -e ARGOCD_LINT_GOGC=20 -v /home/cyril/go/src:/go/src:delegated -v /home/cyril/.cache/go-build:/tmp/go-build-cache:delegated -v /home/cyril/.kube:/home/user/.kube:delegated -v /tmp:/tmp:delegated -w /go/src/github.com/argoproj/argo-cd argoproj/argocd-test-tools:v0.2.0 bash -c "make codegen-local"`
> ` go generate ./util/argo/...` `failed to initialize build cache at /tmp/go-build-cache: mkdir /tmp/go-build-cache/00: permission denied `
> `util/argo/normalizers/knowntypes_normalizer.go:17: running "go": exit status 1`
> `make: *** [Makefile:132: gogen] Error 1 `
> `Makefile:151: recipe for target 'codegen' failed`
> `make: *** [codegen] Error 2 `
> 
> `> sudo -E make codegen`
> `/bin/sh: 1: go: not found ` `docker run --rm -it --name argocd-test-client -u 0 -e HOME=/home/user -e GOPATH=/go -e ARGOCD_E2E_K3S= -e GOCACHE=/tmp/go-build-cache -e ARGOCD_LINT_GOGC=20 -v /src:/go/src:delegated -v /home/cyril/.cache/go-build:/tmp/go-build-cache:delegated -v /home/cyril/.kube:/home/user/.kube:delegated -v /tmp:/tmp:delegated -w /go/src/github.com/argoproj/argo-cd argoproj/argocd-test-tools:v0.2.0 bash -c "make codegen-local" `
> `make: *** No rule to make target 'codegen-local'. Stop`
> `Makefile:151: recipe for target 'codegen' failed ` `make: *** [codegen] Error 2 ` `

It seems you have either previously build some Go code as another user (root, via sudo), using your user's environment or the directory didn't exist before it was created (this could be a bug). The permission error is most likely in `/home/cyril/.cache/go-build` (because that's what is mounted to the Docker container at `/tmp/go-build-cache`). To fix this, you can `sudo chown -R cyril /home/cyril/.cache/go-build` and re-run `make codegen`. Gonna fix the Makefile to ensure this won't happen and add some more information to the contribution docs. Thanks for noticing!

**Comment by cyrilcros** [comment]
- for the chart this is still a bit of an inconvenience but there are workarounds
- the app of app patterns does work like you said, argocd -> argocd -> whatever
- `make codegen` works again, thanks

I will see if I can add a few lines in your doc to document those solutions ("." root path, your app of app pattern description).
Thanks again for your help, I will close this.
