### ISSUE TITLE
argocd cli v1.0.0 not working

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-cd#3471]
Argocd cli v1.0.0 not working.

Using argocd server: argocd-server: v1.1.0-rc3+7c0fd90.dirty

error msg for argocd cmds:
user: Current not implemented on linux/amd64

**Comment by alexmt** [comment]
Hello @emichaf ,

This is known golang issue: https://github.com/golang/go/issues/6376 . The workaround is to set `USER` environment variable. (for example ` export USER=argocd `)
