### ISSUE TITLE
`argocd cluster rm rubbish` succeeds with exit code 0, should fail?

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#3476]

**Comment by chetan-rns** [comment]
Looks like the server doesn't return an error when the cluster secret is not found [here](https://github.com/argoproj/argo-cd/blob/89ee234634c10312d2fcb74c30e9d590fe01d4ff/util/db/cluster.go#L251). Can returning an error(`eg. Unable to find cluster: rubbish`) solve this issue? I'm happy to work on it
