### ISSUE TITLE
argocd-utils import command needs pruning

### ISSUE THREAD

**Issue by viveksatasiya** [argoproj/argo-cd#3478]
Hello,

I deployed a new argocd release using helm chart. After deployment of argocd, I added a new repository using argocd UI. Then I tool a backup of yaml files using argocd-utils export command as described in disaster recovery page in the documentation. I got the backup yaml file.

After that, when I try to import argocd backup files taken using argocd-export command, I got the following response.

`/ConfigMap argocd-ssh-known-hosts-cm needs pruning
/Secret repo-1660342773 needs pruning
/Secret argocd-secret needs pruning
argoproj.io/AppProject default needs pruning
/ConfigMap argocd-rbac-cm needs pruning
/ConfigMap argocd-tls-certs-cm needs pruning
/ConfigMap argocd-cm needs pruning`

Am I making any mistake while importing the backup files?
 
Please help.

Thanks in advance.

**Comment by allej** [comment]
Hi,
this is probably just a documentation issue. When running the import as documented:
`docker run -v ~/.kube:/home/argocd/.kube --rm argoproj/argocd:$VERSION argocd-util import - < backup.yaml`,
then docker does _not_ read anything from stdin. The import command gets an empty file to work with. Therefore, all resources will be pruned.
The corrected docker call should include the `-i` flag for interactive mode:
`docker run -i -v ~/.kube:/home/argocd/.kube --rm argoproj/argocd:$VERSION argocd-util import - < backup.yaml`

**Comment by jannfis** [comment]
@viveksatasiya Going to close this issue because I think it is resolved by the updated command, also documentation was updated to reflect this (#3710) - if problem persists, please re-open this issue.
