### ISSUE TITLE
CLI: allow --server to point to an alternative base URL

### ISSUE THREAD

**Issue by gpaul** [argoproj/argo-cd#3483]
# Summary

I run ArgoCD at a custom Base URL. This works well in the UI as I can start the argocd-server with the `--base-url=/foo/bar` option. However, it is not possible to use the CLI to communicate with a server at an alternative base URL as the --server flag is assumed to be of the format `example.com:port`, and not `example.com:port/foo/bar`.

Today, the workaround I've landed on is to use the --port-forward option and then connect to localhost:8080/. This is unfortunate as it requires the user to to have the `pods/portforward` privilege to the argocd namespace, which is far more privilege than I want to provide.

# Motivation

The summary provides the motivation: I rely heavily on the CLI and would like to use it to manage my ArgoCD instance, which is rooted at a base URL of "/foo/bar".

# Proposal

TBD

**Comment by gpaul** [comment]
Some of the open questions are:
- How would this interact with the gRPC client?
- How would this interact with the CLI login flow?

**Comment by gpaul** [comment]
I am reasonably confident that I would be able to dedicate effort to the implementation of this feature.

**Comment by alexmt** [comment]
Hello @gpaul , 

That was implemented today morning :) https://github.com/argoproj/argo-cd/pull/3475 : CLI getting ` --grpc-web-root-path` flag which includes root path. I did not think about saving path into argocd config so user don't have to specify it with each commend. Adding request to PR to support it

**Comment by gpaul** [comment]
Oh! Cool!

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-cd/pull/3475
