### ISSUE TITLE
Automation/human error protections during auto-sync

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#3484]
# Summary

Auto-sync + resource pruning should have so protection mechanism to avoid deleting resources by mistake.

# Motivation

The auto-sync + pruning enables seamless pure GitOps workflow however might be dangerous in production.

Here are some examples:

* https://github.com/argoproj/argo-cd/issues/3473 - automation deleted app yamls
* https://twitter.com/cobexer/status/1230192616987381761 user deleted yamls by mistake
* https://github.com/argoproj/argo-cd/issues/2573 - potentially argocd bug 

# Proposal

* Simplest protection is to refuse to delete resources if application suddenly got 0 resources. 
* Another option is to let user define the max number of resources that could be deleted by auto-sync.

**Comment by test-account-0** [comment]
Maybe something like `terraform plan`?

**Comment by test-account-0** [comment]
For now this protection is weird. I have to copy more applications to the same directory for synchronization to move forward.
Or I can remove stuff manually. But I think it misses the point of gitops.

**Comment by test-account-0** [comment]
Can I disable this protection?
