### ISSUE TITLE
Is is possible to use 'path' in 'argocd repo add'?

### ISSUE THREAD

**Issue by AceHack** [argoproj/argo-cd#3489]
We have a huge repo and would like to only point to one directory and do a sparse checkout of git so it does not clone the whole repo.  Is this possible?

**Comment by phs** [comment]
The bundled `git` binary appears to be version `2.20.1` in image `argoproj/argocd:v1.7.8`.

At the very least, this git is too old to support `--sparse`, it seems it would need to at least be `2.25`.

**Comment by groodt** [comment]
Any updates on this? Would we be willing to at least bump the git version?

**Comment by groodt** [comment]
I've confirmed that the git version is actually new enough to support sparse checkout (2.30.2)

```
root@472d1603c823:/tmp# git --version
git version 2.30.2
root@472d1603c823:/tmp# git init -b main
Initialized empty Git repository in /tmp/.git/
root@472d1603c823:/tmp# git sparse-checkout init
root@472d1603c823:/tmp#
```

**Comment by groodt** [comment]
This issue seems related (and probably would address the issue here) https://github.com/argoproj/argo-cd/issues/11198

I think we can close this issue and follow the other one.

**Comment by crenshaw-dev** [comment]
Let's consolidate the discussion of sparse checkout here: https://github.com/argoproj/argo-cd/issues/11198
