### ISSUE TITLE
UI blank after github authentication

### ISSUE THREAD

**Issue by jasvinder-tp** [argoproj/argo-cd#3493]
I have create a config map to authenticate with github, but after login with github, UI dashboard is blank, no existing projects and application showing...

Login with github successfully, but dashboard is blank, existing projects and app created by admin user.

argocd-cm.yaml as below:

➜  /atom cat argocd-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # policy.default: role:readonly
  accounts.alice: apiKey, login
  # disables user. User is enabled by default
  accounts.alice.enabled: "false"
  url: https://argocd.arthur.abc.com
  statusbadge.enabled: 'true'
  dex.config: |
    connectors:
      # GitHub example
      - type: github
        id: github
        name: GitHub
        config:
          clientID: YT&^%$#dd3d1ff389b7f5
          clientSecret: 1ea706be750#########
          orgs:
          - name: jasvinder
            teams:
            - devops-core
            - devops

  policy.csv: |
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, certificates, get, *, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, accounts, get, *, allow

    p, role:admin, applications, create, */*, allow
    p, role:admin, applications, update, */*, allow
    p, role:admin, applications, delete, */*, allow
    p, role:admin, applications, sync, */*, allow
    p, role:admin, applications, override, */*, allow
    p, role:admin, applications, action/*, */*, allow
    p, role:admin, certificates, create, *, allow
    p, role:admin, certificates, update, *, allow
    p, role:admin, certificates, delete, *, allow
    p, role:admin, clusters, create, *, allow
    p, role:admin, clusters, update, *, allow
    p, role:admin, clusters, delete, *, allow
    p, role:admin, repositories, create, *, allow
    p, role:admin, repositories, update, *, allow
    p, role:admin, repositories, delete, *, allow
    p, role:admin, projects, create, *, allow
    p, role:admin, projects, update, *, allow
    p, role:admin, projects, delete, *, allow
    p, role:admin, accounts, update, *, allow

    g, role:admin, role:readonly
    g, admin, role:admin

    p, role:ds-admin, applications, get, ds-admin/*, allow
    p, role:ds-admin, applications, override, ds-admin/*, allow
    p, role:ds-admin, applications, update, ds-admin/*, allow
    p, role:ds-admin, applications, action, ds-admin/*, allow
    p, role:ds-admin, clusters, get, *, allow
    p, role:ds-admin, repositories, get, *, allow

    g, tokopedia:devops, role:ds-admin
    g, tokopedia:devops-core, role:admin
    g, tokopedia:devops, role:readonly

**Comment by jannfis** [comment]
Hi, I'd suggest this is not a bug and that the error is in your RBAC configuration or group/organisation mapping from Dex.

Can you please check the user information in the UI (from the left navigation pane), it should display the groups associated with your logged in user.
