### ISSUE TITLE
Ignore extra objects dynamically created in same namespace

### ISSUE THREAD

**Issue by supasteev0** [argoproj/argo-cd#3498]
# Summary

We currently use [Velero](https://github.com/vmware-tanzu/velero) to manage backups in our cluster.
In order to do that, we create a Schedule object in the velero namespace, with our backup configuration. The schedule object is managed via argocd in a dedicated backup application.
When Velero triggers a backup, it creates a Backup object in the same namespace.
Once the Backup object is created, the application becomes Out Of Sync and the Backup object appears as "requires pruning", which obviously is very dangerous, as we never want to delete this object.

I could not find a way to tell Argo to ignore an entire object kind in the Argo application itself.
I tried to use the **ignoreDifferences** property, but this seems to only allow ignoring specific attributes of an object, and not the whole object itself.

I also found out about the **argocd.argoproj.io/compare-options: IgnoreExtraneous** annotation, but there is no way to add any annotation to the objects created by Velero.

I think it would be very useful to have the possibility to ignore specific object kinds in argo configuration, rather than relying on a configuration in objects not managed by argo.
Something very similar to **ignoreDifferences**, but without any pointer on the attribute level could do the trick.

What are your thoughts on this improvement ?

**Comment by jessesuen** [comment]
For the Backup object to be considered part of an Application (and thus OutOfSync needing pruning), it would have to have done two things:

1. carry over the injected tracking label of the `Schedule` object to the `Backup` object
2. *not* add itself as an owner of object that it creates.

Is the behavior of Valero that it carries forward *all* annotations of the parent object without adding itself as a parent?

**Comment by jessesuen** [comment]
I see that it is. Looks like we've had an issue for this. Currently the solution is to tell Argo CD to ignore these objects completely.

https://github.com/argoproj/argo-cd/issues/1472

**Comment by supasteev0** [comment]
Thank you for the quick answer.

Looks like I've completely missed this part of the documentation about resource exclusion !
Just tried it and it works indeed.

As stated in #1472, I also think it would be a nice feature to be able to configure this at the application level.
