### ISSUE TITLE
CrashLoopBackOff: invalid configuration: no configuration has been provided

### ISSUE THREAD

**Issue by gymlt** [argoproj/argo-cd#3507]
Hi guys,

I'm trying to deploy ArgoCD on premises. Our K8S cluster is in a isolate zone and does not have access to the Internet. It can access our private repos only.

I took the latest ArgoCD manifest - v1.5.2, updated image paths with our private repo, added imagePullSecrets.

Images pulled sucessfully, however  argocd-application-controller, argocd-dex-server and argocd-server don't start.

What I'm doing wrong?

> kubectl -n argocd get pods
> NAME                                             READY   STATUS             RESTARTS   AGE
> argocd-application-controller-64b6d6fd6c-j8llz   0/1     CrashLoopBackOff   3          115s
> argocd-dex-server-6db486c9f9-bt6vs               0/1     CrashLoopBackOff   3          115s
> argocd-redis-8c568b5db-w4vnr                     1/1     Running            0          115s
> argocd-repo-server-6b57b5545-62s45               1/1     Running            0          115s
> argocd-server-db9c8bccf-swc2z                    0/1     CrashLoopBackOff   3          115s

Logs:

> kubectl -n argocd logs argocd-application-controller-64b6d6fd6c-j8llz
> time="2020-04-29T05:28:09Z" level=fatal msg="invalid configuration: no configuration has been provided"
> 
> kubectl -n argocd logs argocd-dex-server-6db486c9f9-bt6vs
> time="2020-04-29T05:28:36Z" level=fatal msg="invalid configuration: no configuration has been provided"
> 
> kubectl -n argocd logs argocd-server-db9c8bccf-swc2z
> time="2020-04-29T05:28:43Z" level=fatal msg="invalid configuration: no configuration has been provided"

> kubectl -n argocd describe pod argocd-application-controller-64b6d6fd6c-j8llz
> Name:         argocd-application-controller-64b6d6fd6c-j8llz
> Namespace:    argocd
> Priority:     0
> Node:         node.node/10.108.218.35
> Start Time:   Wed, 29 Apr 2020 07:27:25 +0200
> Labels:       app.kubernetes.io/name=argocd-application-controller
>               pod-template-hash=64b6d6fd6c
> Annotations:  <none>
> Status:       Running
> IP:           10.140.71.88
> IPs:
>   IP:           10.140.71.88
> Controlled By:  ReplicaSet/argocd-application-controller-64b6d6fd6c
> Containers:
>   argocd-application-controller:
>     Container ID:  cri-o://a90daf1b1c84959e9de0bc44ac7a0d448d867e4e91ff53b914d9c83bee8e402a
>     Image:         private.repo/argoproj/argocd:v1.5.2
>     Image ID:      private.repo/argoproj/argocd@sha256:ebaa82eb629d8fcc4a23659d1f6602ab64db4f5e13b9146f4742247593af9697
>     Port:          8082/TCP
>     Host Port:     0/TCP
>     Command:
>       argocd-application-controller
>       --status-processors
>       20
>       --operation-processors
>       10
>     State:          Waiting
>       Reason:       CrashLoopBackOff
>     Last State:     Terminated
>       Reason:       Error
>       Exit Code:    1
>       Started:      Wed, 29 Apr 2020 07:43:55 +0200
>       Finished:     Wed, 29 Apr 2020 07:43:55 +0200
>     Ready:          False
>     Restart Count:  8
>     Liveness:       http-get http://:8082/healthz delay=5s timeout=1s period=10s #success=1 #failure=3
>     Readiness:      http-get http://:8082/healthz delay=5s timeout=1s period=10s #success=1 #failure=3
>     Environment:    <none>
>     Mounts:
>       /var/run/secrets/kubernetes.io/serviceaccount from argocd-application-controller-token-vj5g4 (ro)
> Conditions:
>   Type              Status
>   Initialized       True 
>   Ready             False 
>   ContainersReady   False 
>   PodScheduled      True 
> Volumes:
>   argocd-application-controller-token-vj5g4:
>     Type:        Secret (a volume populated by a Secret)
>     SecretName:  argocd-application-controller-token-vj5g4
>     Optional:    false
> QoS Class:       BestEffort
> Node-Selectors:  <none>
> Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
>                  node.kubernetes.io/unreachable:NoExecute for 300s
> Events:
>   Type     Reason     Age                  From                                          Message
>   ----     ------     ----                 ----                                          -------
>   Normal   Scheduled  <unknown>            default-scheduler                             Successfully assigned argocd/argocd-application-controller-64b6d6fd6c-j8llz to node.node
>   Normal   Pulling    15m (x4 over 16m)    kubelet, node.node  Pulling image "private.repo/argoproj/argocd:v1.5.2"
>   Normal   Pulled     15m (x4 over 16m)    kubelet, node.node  Successfully pulled image "private.repo/argoproj/argocd:v1.5.2"
>   Normal   Created    15m (x4 over 16m)    kubelet, node.node  Created container argocd-application-controller
>   Normal   Started    15m (x4 over 16m)    kubelet, node.node  Started container argocd-application-controller
>   Warning  BackOff    118s (x74 over 16m)  kubelet, node.node  Back-off restarting failed container

**Comment by jannfis** [comment]
Hi @gymlt - it looks a lot liket a permission issue within your K8s cluster, i.e. a missing ServiceAccount or RBAC roles.

Do you by any chance have installed the cluster wide setup with a non-cluster-admin account? Or do you have network policies in place that would forbid the pods communicating with the outside? The Pods that are crashing need access to the K8s API of your cluster.
