### ISSUE TITLE
SSO login failure due to restricted access gives obtuse dex error page

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#351]
If a user attempts to login to ArgoCD, and they are not a member of the allowed groups configured in the dexConfig, they get an obtuse error which is simply the Dex error page. Its unclear to the user that they are not allowed to login because they are not members of an appropriate group. We should present a better page.

The difficulty is that we run a reverse proxy to dex, so we will essentially need to intercept all dex responses and redirect to our own error page when we detect this condition.

**Comment by alexmt** [comment]
working on it

**Comment by alexmt** [comment]
Two PRs are resolving issue:

* https://github.com/argoproj/argo-cd/pull/425
* https://github.com/argoproj/argo-cd-ui/pull/19

Additional we need to try to improve https://github.com/coreos/dex/issues/1263 . Once dex ticket is resolved we will get better login error message.
