### ISSUE TITLE
Restrict ciphers list for TLS connection

### ISSUE THREAD

**Issue by EppO** [argoproj/argo-cd#3510]
# Summary

Currently, Argo CD allows selecting the min/max version for TLS connection to the Argo CD server, but it still does offer weak ciphers.
Here is an example with `--tlsminversion "1.2"` on argocd-server:
```
TLSv1.2:
|     ciphers:
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
```

# Motivation

Modern, more secure cipher suites should be preferred to old, insecure ones. Being able restrict the cipher suites offered during the TLS handshake reduces the surface attack. CBC and 3DES are both considered weak ciphers nowadays.

# Proposal

Either take an opinionated approach and disable weak ciphers, or allow users to provide the ciphers whilelist/blacklist.

**Comment by jannfis** [comment]
You brought up a good point there. I think there's still lot of work to do in the TLS domain (also on the "internal" endpoints, #3389).

My preferred approach to this would be the combination of your two proposals: Have an opinionated default of allowed & proposed ciphers according to latest information (i.e. https://cipherlist.eu has some good resources on what's great & what's not), and then provide the user to override this default with a list of ciphers of their choice, i.e. when they have other requirements.

**Comment by jannfis** [comment]
Hi @EppO, I just submitted a PR #3524 - please have a look if this would fully implement your proposal.

**Comment by EppO** [comment]
Strong defaults and ability to provide a custom list, I couldn't have hoped for more :)
Thanks a lot, really appreciated

**Comment by ira-gordin-sap** [comment]
> Strong defaults and ability to provide a custom list, I couldn't have hoped for more :) Thanks a lot, really appreciated

TLS_RSA_WITH_AES_256_GCM_SHA384 is a weak cipher.
