### ISSUE TITLE
Address Snyk findings

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#3511]

**Comment by alexmt** [comment]
@alexec  can you add more details please ?

**Comment by alexec** [comment]
I meant "Snyk".

**Comment by jannfis** [comment]
I'm preparing pull requests to upgrade node dependencies to their latest allowed versions, both in argo-ui and argo-cd. 

I guess since argo-ui will also affect (at least) Argo workflows too, we should test its UI against the PR to argo-ui as well.

**Comment by jannfis** [comment]
https://github.com/argoproj/argo-ui/pull/61
