### ISSUE TITLE
[UI] resource names are almost always truncated

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#352]
Unless you have like a 10 character resource name, chances are your resource name is going to be truncated in the UI. To make matters worse, K8s appends manifest hashes and random characters to resources which generally means all pod names end up getting truncated. 

In general, I think our UI components uses more real-estate than they really need -- I think the UI can make the resource boxes wider, and the font much smaller, to show more usable information.

**Comment by alexmt** [comment]
Fixed
