### ISSUE TITLE
Use UID number rather than username in Dockerfile

### ISSUE THREAD

**Issue by wdullaer** [argoproj/argo-cd#3520]
# Summary
Set a numeric user in the docker file, rather than the `argocd` username.

# Motivation
Kubernetes will reject the pod if the security context does not allow to run as root, because it can't validate that a named user isn't root.
See: https://github.com/kubernetes/kubernetes/pull/56503

I know you can overwrite the uid with a securityContext directive, but it'd be nice if this worked out of the box.

# Proposal
Change https://github.com/argoproj/argo-cd/blob/master/Dockerfile#L78
to
```
USER 999
```

**Comment by jannfis** [comment]
We already have a PR for this: #3108

**Comment by jannfis** [comment]
And there is #2746

**Comment by wdullaer** [comment]
Nice to see it's already on the radar.
I did do a search through the issues, but apparently not thorough enough.

I'll be following the PR :-)
