### ISSUE TITLE
Multiple errors 

### ISSUE THREAD

**Issue by jrcjoro** [argoproj/argo-cd#3521]
$ argocd version
argocd: v1.5.2+c2c19f4
  BuildDate: 2020-04-15T16:41:59Z
  GitCommit: c2c19f42ad78ed7a6fb70e86aed117be484feb50
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.2+c2c19f4
  BuildDate: 2020-04-15T16:43:12Z
  GitCommit: c2c19f42ad78ed7a6fb70e86aed117be484feb50
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0

For Ingress 'Progressing' problem, I have done this:
$ kubectl get cm argocd-cm -n argocd -oyaml
apiVersion: v1
data:
  repositories: |
...
  resource.customizations: |-
    extensions/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Ingress Ready"
        return hs
kind: ConfigMap
...

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Error description:

- Deployment HEALTH stuck in 'Progressing' after successful deployment

- errors in argocd-server logs:
time="2020-04-30T09:44:49Z" level=error msg="finished unary call with code Unknown" error="application refresh deadline exceeded" grpc.code=Unknown grpc.method=ManagedResources grpc.service=application.ApplicationService grpc.start_time="2020-04-30T09:44:43Z" grpc.time_ms=6234.365 span.kind=server system=grpc

- ArgoCD does not return manifests or respond to actions, deployments has to be removed with --cascade=false

Argocd has been installed this way:
kubectl create namespace argocd

kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v1.5.2/manifests/install.yaml

curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/download/v1.5.2/argocd-linux-amd64

kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "NodePort"}}

~$ kubectl get nodes
NAME                 STATUS   ROLES    AGE   VERSION
k8s-master           Ready    master   20h   v1.18.2
k8s-node0   Ready    <none>   20h   v1.18.2
k8s-node1   Ready    <none>   20h   v1.18.2

$ kubectl get svc -n argocd
NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
argocd-dex-server       ClusterIP   10.100.56.166    <none>        5556/TCP,5557/TCP            16h
argocd-metrics          ClusterIP   10.101.249.245   <none>        8082/TCP                     16h
argocd-redis            ClusterIP   10.110.156.182   <none>        6379/TCP                     16h
argocd-repo-server      ClusterIP   10.111.162.239   <none>        8081/TCP,8084/TCP            16h
argocd-server           NodePort    10.104.88.160    <none>        80:30951/TCP,443:32189/TCP   16h
argocd-server-metrics   ClusterIP   10.97.205.189    <none>        8083/TCP                     16h

**Comment by jrcjoro** [comment]
K8s Platform:
 $ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by jannfis** [comment]
> For Ingress 'Progressing' problem, I have done this:
> $ kubectl get cm argocd-cm -n argocd -oyaml
> apiVersion: v1
> data:
> repositories: |
> ...
> resource.customizations: |-
> extensions/Ingress:
> health.lua: |
> hs = {}
> hs.status = "Healthy"
> hs.message = "Ingress Ready"
> return hs
> kind: ConfigMap

Please use `k8s.networking.io/Ingress` as resource type, since new versions of K8s have moved the resource to that API.

I suspect your other issues in combination with your `NodePort` setup for the `argocd-server` service. Please revert back to `ClusterIP` and see if the problems persist.

**Comment by jrcjoro** [comment]
I changed back to default ClusterIP type:
$ kubectl get svc -n argocd
NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
argocd-dex-server       ClusterIP   10.102.242.75    <none>        5556/TCP,5557/TCP   33m
argocd-metrics          ClusterIP   10.107.217.83    <none>        8082/TCP            33m
argocd-redis            ClusterIP   10.97.235.5      <none>        6379/TCP            33m
argocd-repo-server      ClusterIP   10.96.101.161    <none>        8081/TCP,8084/TCP   33m
argocd-server           ClusterIP   10.101.135.119   <none>        80/TCP,443/TCP      33m
argocd-server-metrics   ClusterIP   10.102.119.53    <none>        8083/TCP            33m

I also changed argocd-cm configmap:
apiVersion: v1
data:
  repositories: |
  ...
  resource.customizations: |-
    k8s.networking.io/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Ingress Ready"
        return hs
kind: ConfigMap

Errors:
- After deployment STATUS and HEALTH are missing:
ftp-server          https://kubernetes.default.svc  default    default                  Auto-Prune  <none>      git@github.com:Valuecode/forsante-k8s.git  staging/Ftp-server          
rabbitmq            https://kubernetes.default.svc  default    default                  Auto-Prune  <none>      git@github.com:Valuecode/forsante-k8s.git  staging/Rabbitmq            
redis               https://kubernetes.default.svc  default    default                  Auto-Prune  <none>      git@github.com:Valuecode/forsante-k8s.git  staging/Redis-copy          
sftp-server         https://kubernetes.default.svc  sftp       default                  Auto-Prune  <none>      git@github.com:Valuecode/forsante-k8s.git  staging/Sftp-server

- deployments were not completed, so they are not running in cluster. 

This deployment does not include Ingresses.

**Comment by jrcjoro** [comment]
I edited argocd-cm configmap after installing https://raw.githubusercontent.com/argoproj/argo-cd/v1.5.2/manifests/install.yaml before doing any deployments.

**Comment by jannfis** [comment]
Can you please post your complete `argocd-cm` ConfigMap (with private parts redacted)? Also, can you please post them in a Markdown codeblock, it's way better readable this way.

**Comment by jrcjoro** [comment]
```

apiVersion: v1
data:
  repositories: |
    - sshPrivateKeySecret:
        key: sshPrivateKey
        name: repo-2704953759
      type: git
      url: git@github.com:Valuecode/forsante-k8s.git
  resource.customizations: |-
    k8s.networking.io/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Ingress Ready"
        return hs
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"repositories":"- sshPrivateKeySecret:\n    key: sshPrivateKey\n    name: repo-2704953759\n  type: git\n  url: git@github.com:Valuecode/forsante-k8s.git\n","resource.customizations":"k8s.networking.io/Ingress:\n  health.lua: |\n    hs = {}\n    hs.status = \"Healthy\"\n    hs.message = \"Ingress Ready\"\n    return hs"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2020-04-30T11:15:41Z","labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/part-of":{}}}},"manager":"kubectl","operation":"Update","time":"2020-04-30T11:15:41Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:repositories":{}}},"manager":"argocd-server","operation":"Update","time":"2020-04-30T11:44:32Z"}],"name":"argocd-cm","namespace":"argocd","resourceVersion":"197854","selfLink":"/api/v1/namespaces/argocd/configmaps/argocd-cm","uid":"3d21763e-55ca-4970-a75d-c3c90dd7c1ce"}}
  creationTimestamp: "2020-04-30T11:15:41Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:repositories: {}
    manager: argocd-server
    operation: Update
    time: "2020-04-30T11:44:32Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:resource.customizations: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
    manager: kubectl
    operation: Update
    time: "2020-04-30T11:46:14Z"
  name: argocd-cm
  namespace: argocd
  resourceVersion: "198098"
  selfLink: /api/v1/namespaces/argocd/configmaps/argocd-cm
  uid: 3d21763e-55ca-4970-a75d-c3c90dd7c1ce

```

**Comment by jannfis** [comment]
Hi @jrcjoro, I think it would be good if you could [join slack](https://argoproj.github.io/community/join-slack) to get support from the community for this issue.

**Comment by jrcjoro** [comment]
@jannfis There hasn't been any comments on my issue in project slack channel.

**Comment by SystemZ** [comment]
I have similar problems with non-HA `v1.5.4+36bade7`. I used `v1.3.2` before without issues.

`argocd-server`
```
time="2020-05-08T23:08:53Z" level=error msg="finished unary call with code Unknown" error="application refresh deadline exceeded" grpc.code=Unknown grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2020-05-08T23:08:13Z" grpc.time_ms=39996.15 span.kind=server system=grpc
time="2020-05-08T23:08:53Z" level=error msg="finished unary call with code Unknown" error="application refresh deadline exceeded" grpc.code=Unknown grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2020-05-08T23:08:13Z" grpc.time_ms=39996.344 span.kind=server system=grpc
time="2020-05-08T23:09:26Z" level=info msg="client watch grpc context closed"
time="2020-05-08T23:09:26Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=Watch grpc.service=application.ApplicationService grpc.start_time="2020-05-08T23:08:26Z" grpc.time_ms=60032.93 span.kind=server system=grpc
time="2020-05-08T23:09:26Z" level=info msg="k8s application watch event channel closed"
```

`argocd-application-controller`
```
W0508 22:55:20.307339       1 reflector.go:299] github.com/argoproj/argo-cd/util/settings/settings.go:645: watch of *v1.Secret ended with: too old resource version: 12082613367 (12083003395)
W0508 22:56:00.312605       1 reflector.go:299] github.com/argoproj/argo-cd/controller/appcontroller.go:414: watch of *v1alpha1.AppProject ended with: too old resource version: 12082640789 (12083017552)
time="2020-05-08T23:03:30Z" level=info msg="Alloc=30805 TotalAlloc=21909034 Sys=892332 NumGC=1853 Goroutines=402"
time="2020-05-08T23:03:37Z" level=info msg="updated 'grafana' operation (phase: Running)"
time="2020-05-08T23:03:37Z" level=info msg="Initialized new operation: {&SyncOperation{Revision:4950b2404e4f2da549142cf611d11531e00b7a15,Prune:false,DryRun:false,SyncStrategy:&SyncStrategy{Apply:nil,Hook:&SyncStrategyHook{SyncStrategyApply:SyncStrategyApply{Force:false,},},},Resources:[]SyncOperationResource{},Source:nil,Manifests:[],SyncOptions:[],} {admin false}}" application=grafana
time="2020-05-08T23:03:37Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=grafana
time="2020-05-08T23:13:30Z" level=info msg="Alloc=20785 TotalAlloc=21938404 Sys=892332 NumGC=1858 Goroutines=407"
W0508 23:18:44.311571       1 reflector.go:299] github.com/argoproj/argo-cd/controller/appcontroller.go:414: watch of *v1alpha1.AppProject ended with: too old resource version: 12083017552 (12083479725)
```

Workaround for "unstuck" is
```
kubectl -n argocd delete pod/argocd-application-controller
```

**Comment by jrcjoro** [comment]
Are problems related to argocd-cm changes? If so, what is correct way to change argocd behaviour with Ingress deployments not being stuck in 'progressing'?

**Comment by jrcjoro** [comment]
I got this functioning with argocd 1.5.5 and by adding restart of argocd Pods.
