### ISSUE TITLE
ArgoCD doesn't handle malformed yaml files gracefully

### ISSUE THREAD

**Issue by andoriyu** [argoproj/argo-cd#3527]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD Application with auto-sync and pruning enabled. Someone checked in malformed yaml - indentations was wrong. ArgoCD silently-ish ignored that error and pruned the resources since it wasn't in "new state".

By silently ignored I mean the issue was only visible in logs and not in dashboard.

**To Reproduce**

 - Create ArgoCD application with auto-sync and auto-prune enabled
 - Add resources
 - "break" the yaml file
 - see resources get wiped 

**Expected behavior**

ArgoCD would not try to apply such changes if yaml file is malformed.

**Version**

```shell
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:46:45Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:47:48Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**

```
error: error parsing kafka.yaml: error converting YAML to JSON: yaml: line 207: did not find expected key
```

**Comment by todaywasawesome** [comment]
Closed with #2267
