### ISSUE TITLE
GitHub 'stable' tag points to v1.5.0 and not latest stable version

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#3532]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Current `stable` tag in ArgoCD GitHub repository points to v1.5.0, while it should point to v1.5.2. Whenever someone uses a `stable` reference (i.e. fetches https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml), they will fetch v1.5.0.

**To Reproduce**

Have a look at https://github.com/argoproj/argo-cd/tree/stable

**Expected behavior**

`stable` tag in GitHub should point to latest stable version (currently v1.5.2)

**Comment by alexmt** [comment]
Thank you @jannfis ! Fixed
