### ISSUE TITLE
Setting "revision history limit" errors in UI 

### ISSUE THREAD

**Issue by spencergilbert** [argoproj/argo-cd#3534]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Setting a revision history limit (App Details > Edit > REVISION HISTORY LIMIT) and saving generates the following error in the UI:

`Unable to save changes: json: cannot unmarshal string into Go struct field ApplicationSpec.spec.revisionHistoryLimit of type int64`

**To Reproduce**
Editing the following Application manifest via the UI causes this error for me every time:
`apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: grafana
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://kubernetes-charts.storage.googleapis.com/
    targetRevision: 5.0.*
`

**Expected behavior**

By my understanding it should set the revision limit without erroring

**Screenshots**

![Screenshot from 2020-05-01 17-15-40](https://user-images.githubusercontent.com/11903873/80842695-45479900-8bd0-11ea-92ac-a5ea22c20aad.png)

**Version**

```shell
v1.5.2+c2c19f4
```

**Comment by demon** [comment]
Confirmed as of v1.5.3+095c5d6 as well.

**Comment by vyckou** [comment]
v1.5.5+0fdef48 too

**Comment by perriea** [comment]
Always in 1.7.10, any news ?

**Comment by alexmt** [comment]
Fix is on the way :) https://github.com/argoproj/argo-cd/pull/5035
