### ISSUE TITLE
Suppress out of synch differences 

### ISSUE THREAD

**Issue by asanami** [argoproj/argo-cd#3536]
# Summary

We currently use vault for secrets management, which means that the secrets defined in the yaml get mutated on deployment.  ArgoCD then always warns that the application is out of synch.  Is it possible to suppress these type of differences

![Screenshot 2020-05-04 at 09 21 07](https://user-images.githubusercontent.com/5146269/80947702-9cc05180-8de8-11ea-8630-42ea922f322a.png)

# Motivation

Ensures out-of-synch aren't ignored.

**Comment by sfynx** [comment]
This could be useful: https://argoproj.github.io/argo-cd/user-guide/diffing

**Comment by todaywasawesome** [comment]
> This could be useful: https://argoproj.github.io/argo-cd/user-guide/diffing

Answered here.
