### ISSUE TITLE
argocd-dex-server metrics connection refused

### ISSUE THREAD

**Issue by lanmarti** [argoproj/argo-cd#3538]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I updated from 1.4.2 to 1.5.3 earlier today and am now noticing that the metrics endpoint (port 5558) of the argocd-dex-server is unreachable (this might have been present in earlier versions too, only noticed it now). The 'metrics' documentation does not mention anything about the dex-server metrics, only argocd specific component are mentioned (https://argoproj.github.io/argo-cd/operator-manual/metrics/). Is this endpoint supposed to be reachable, if not, why is it defined in the service?

**Expected behavior**

A reachable endpoint with prometheus metrics or, alternatively, no metrics port defined in the argocd-dex-server service.

**Version**

```shell
argocd: v1.4.0+2d02948
  BuildDate: 2020-01-18T05:53:00Z
  GitCommit: 2d029488aba6e5ad48b2a756bfcf43d5cb7abcee
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.3+095c5d6
  BuildDate: 2020-05-02T04:21:47Z
  GitCommit: 095c5d616b1cb39f87e8f7a54cabea2643e1c99a
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Comment by jannfis** [comment]
Hi @lanmarti,

I cannot reproduce this on a v1.5.3 (which was also upgrade from v1.4 recently):

```
$ argocd version
argocd: v1.5.3+095c5d6
  BuildDate: 2020-05-02T04:19:50Z
  GitCommit: 095c5d616b1cb39f87e8f7a54cabea2643e1c99a
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.3+095c5d6
  BuildDate: 2020-05-02T04:21:47Z
  GitCommit: 095c5d616b1cb39f87e8f7a54cabea2643e1c99a
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0

$ kubectl get svc argocd-dex-server
NAME                TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                      AGE
argocd-dex-server   ClusterIP   10.96.29.1   <none>        5556/TCP,5557/TCP,5558/TCP   195d

$ kubectl get svc argocd-dex-server -o json | jq '.spec'
{
  "clusterIP": "10.96.29.1",
  "ports": [
    {
      "name": "http",
      "port": 5556,
      "protocol": "TCP",
      "targetPort": 5556
    },
    {
      "name": "grpc",
      "port": 5557,
      "protocol": "TCP",
      "targetPort": 5557
    },
    {
      "name": "metrics",
      "port": 5558,
      "protocol": "TCP",
      "targetPort": 5558
    }
  ],
  "selector": {
    "app.kubernetes.io/name": "argocd-dex-server"
  },
  "sessionAffinity": "None",
  "type": "ClusterIP"
}

$ nc -vz 10.96.29.1 5558
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 10.96.29.1:5558.
Ncat: 0 bytes sent, 0 bytes received in 0.02 seconds.

```
Is your `argocd-dex-server` pod properly running, i.e. have you SSO configured?

**Comment by lanmarti** [comment]
Hi @jannfis,

no configuration has been done for the dex-server. The eventual end goal is to set up SSO+RBAC through our existing keycloak setup, but as of now, no user configuration has been done at all.

The logs for the argocd-dex-server pod seem to be completely empty. The pod itself has been running for over an hour without restarts.

Besides some repository credentials and known-host info, everything is running with default configuration.

**Comment by jannfis** [comment]
As long as you don't have SSO configured, the `argocd-dex-server` pod is basically a dummy. 

It watches the `argocd-cm` ConfigMap for changes to SSO configuration, and if a valid configuration is found, it will actually spawn the Dex process inside the container (and handle further configuration changes).

So the metrics endpoint in the service actually points nowhere, unless SSO is configured and Dex server is running (and exposes its metrics endpoint).

**Comment by lanmarti** [comment]
Aha, thank you for clearing this up!
