### ISSUE TITLE
cannot login as admin when Argo CD is installed via operatorhub

### ISSUE THREAD

**Issue by gregsheremeta** [argoproj/argo-cd#3543]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I installed Argo CD on OpenShift 4.4 using the community operator, version 0.0.8. I then created an `argocd` CR to tell the operator to stand up the app:

```shell
$ oc apply -f argocd.yaml
$ oc get pods                                                                                    
NAME                                             READY   STATUS    RESTARTS   AGE
argocd-application-controller-5c6dc959f9-m456x   1/1     Running   0          2m
argocd-dex-server-78f784c575-llp45               1/1     Running   0          2m
argocd-operator-5c47dc76bc-xkcb7                 1/1     Running   0          4m
argocd-redis-79ff859f65-mmpsm                    1/1     Running   0          2m
argocd-repo-server-5d88c4c5dc-zbqp8              1/1     Running   0          2m
argocd-server-5f767f5b7f-vgsqn                   1/1     Running   0          2m
```

I forwarded a port:
```shell
$ kubectl port-forward svc/argocd-server -n argocd 8080:443
```

I cannot login as admin:
```shell
$ argocd login localhost:8080
WARNING: server certificate had error: x509: certificate is valid for argocd, argocd-grpc, argocd.argocd.svc.cluster.local, not localhost. Proceed insecurely (y/n)? y
Username: admin
Password: 
FATA[0008] rpc error: code = Unauthenticated desc = Invalid username or password 
```

I also tried logging in via LoadBalancer IP, and I tried resetting the admin password per "I forgot the admin password, how do I reset it?" in the FAQ. It doesn't help.

When I install manually using step 1 [here](https://argoproj.github.io/argo-cd/getting_started/), I can login fine:
```shell
$ argocd login localhost:8080
WARNING: server certificate had error: x509: certificate signed by unknown authority. Proceed insecurely (y/n)? y
Username: admin
Password: 
'admin' logged in successfully
Context 'localhost:8080' updated
```

I noticed the x509 error message is different in the two cases. Not sure if that's related to the root cause.

**To Reproduce**

See above

**Expected behavior**

I can login as admin when installed via operatorhub.

**Screenshots**

![Selection_712](https://user-images.githubusercontent.com/2248293/81012490-a4531b00-8e27-11ea-867f-fd14485fd1c9.png)

![Selection_713](https://user-images.githubusercontent.com/2248293/81012500-a6b57500-8e27-11ea-9f76-a25db15377f2.png)

**Version**

```shell
argocd version
argocd: v1.5.3+095c5d6
  BuildDate: 2020-05-02T04:19:50Z
  GitCommit: 095c5d616b1cb39f87e8f7a54cabea2643e1c99a
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.3+095c5d6
  BuildDate: 2020-05-02T04:21:47Z
  GitCommit: 095c5d616b1cb39f87e8f7a54cabea2643e1c99a
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Comment by jannfis** [comment]
Hi @gregsheremeta, this issue should probably belong to the operator project, not here. 

Please also have a look at https://github.com/argoproj-labs/argocd-operator/issues/78

**Comment by gregsheremeta** [comment]
Thanks for pointing me to that. I was able to login as admin with the password here:
`kubectl get secret argocd-cluster -o yaml | yq r - "data.admin*" | base64 --decode`

**Comment by melak-cmd** [comment]
kubectl get secret argocd-cluster -o json | jq -r '.data."admin.password"' | base64 -d -

**Comment by joshuacox** [comment]
kubectl get secret -n argocd argocd-secret -o json | jq -r '.data."admin.password"' | base64 -d -

but that is now a bcrypt and wont get you in
