### ISSUE TITLE
Allow black-/whitelisting by resource name

### ISSUE THREAD

**Issue by sfynx** [argoproj/argo-cd#3553]
# Summary

Right now you can create any namespace you want when it is whitelisted in the cluster scope, even if there is a restricted destination namespace pattern. This makes it impossible to create a project that allows management of a select set of namespaces in a secure way.

# Motivation

A common use case is when you want a CI user to manage multiple applications along with their namespaces, but only for certain namespaces. Right now when you whitelist the `Namespace` resource cluster-wide, a user can wipe out any existing namespace by creating it and then deleting it again, because it can create any namespace it wants.

# Proposal

Just like the destination namespace restriction, you could also check the name of a resource using a name pattern:

```
clusterResourceWhitelist:
- group: ''
  kind: Namespace
  name: 'preview-*'
```

With this you could give a project access to manage a certain part of the cluster, including creating and deleting the namespaces, without it being able to touch anything else.

This could be used for all cluster/namespace scoped black-/whitelists to restrict resources by name, allowing for more fine-grained permissions. How difficult would it be to also check the name like this? Of course this field would be optional to retain the previous behavior (allow all names, equivalent to `*`).

# Final remarks

If the destination namespace restriction is also supposed to restrict the creation of namespaces themselves, then this is a bug and should be resolved as such.

**Comment by alexmt** [comment]
The destination namespace restriction does not stop users from creating cluster level resources. You can restrict namespace creation/deletion using `clusterResourceWhitelist` setting. If `clusterResourceWhitelist` is empty then user cannot create/delete any cluster-level resource. 

@sfynx, does `clusterResourceWhitelist` cover your use case?

**Comment by rachelwang20** [comment]
Close for now, will reopen if necessary

**Comment by sfynx** [comment]
@alexmt I actually want to use `clusterResourceWhitelist` to restrict which namespaces a project may create. With the `destination.namespace` key I can configure a project to only be able to create namespaced resources in namespaces `prefix-*`, but I cannot configure it to be able to only create namespaces `prefix-*`.
Because I can only use a group and kind in the `clusterResourceWhitelist`, I can either allow it to create namespaces with arbitrary names, or none at all.

Adding a `name` key to the white-/blacklists to also restrict/allow cluster-level resources by name would allow me to let projects manage their own part of the cluster including creating their own cluster-level resources such as namespaces.

**Comment by Links2004** [comment]
`clusterResourceWhitelist` and `clusterResourceBlacklist` with `name` support is exactly what we need for our use cases.

**Comment by jwenz723** [comment]
Allowing to scope cluster resources by a name pattern would be beneficial with a multi tenant argocd instance to prevent tenants from accidentally managing each other's cluster resources. 

For example, if 2 tenants exist, tenantA and tenantB, and each should be able to create their own k8s namespaces then it would be possible for them to both create namespace foo. Since only one Argo application will be allowed to manage the creation of namespace foo then both tenants would be impacted. 

If whitelist could include a name pattern then each tenant could be restricted to a known set of namespaces (tenantA can create a-* namespaces and tenantB can create b-* namespaces) to prevent them from impacting each other.

**Comment by SamDecrock** [comment]
Not only can anyone create namespaces, you can also create service accounts and ClusterRoles to add yourself as an admin to the cluster 😉

**Comment by paralika** [comment]
This is really useful feature. Any plan to consider it?
