### ISSUE TITLE
Inconsistent RBAC permissions for some resources

### ISSUE THREAD

**Issue by ctrox** [argoproj/argo-cd#3561]
I have already asked about this in Slack, for reference here's the thread: https://argoproj.slack.com/archives/CASHNF6MS/p1588939189434300

**Describe the bug**

For most resources in the argo-cd API it is possible to make a `GET` call without having any RBAC permissions. Instead of an expected `403` a `200` is returned with an empty list of items `{"items":null}`. Here's a (probably incomplete) list of API endpoints which I think behave incorrectly:

```
GET /api/v1/applications
GET /api/v1/clusters
GET /api/v1/repositories
```

In contrast, the endpoint `/api/v1/certificates` behaves differently and returns a `Status: 403`.

**To Reproduce**

1. Create a normal user `alice`
2. Apply the following policy

```
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    p, role:test, repositories, get, *, allow

    g, alice, role:test
```

3. Go to for example `https://server.url/settings/clusters`, in the dev console there is a request to `/api/v1/clusters` that succeeded but with an empty items list

**Expected behavior**

Coming from other RBAC systems I would expect a `get` request to fail, if that permission is not explicitly given. One could argue there is no harm in returning an empty list but I still think the behaviour is incorrect and inconsistent as with `certificates` it behaves differently.

**Version**

```shell
argocd version
argocd: v1.5.4+36bade7
  BuildDate: 2020-05-05T18:59:08Z
  GitCommit: 36bade7a2d7b69d1c0b0c4d41191f792a847d61c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.3+095c5d6
  BuildDate: 2020-05-02T04:21:47Z
  GitCommit: 095c5d616b1cb39f87e8f7a54cabea2643e1c99a
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Comment by agaudreault** [comment]
Has been implemented for a while now
