### ISSUE TITLE
Pod console "field "not showing in UI dropdown list. 

### ISSUE THREAD

**Issue by Karukas** [argoproj/argo-cd#3567]
Hi!
Unfortunately, i couldn't see, how i will get into pod "Console" within UI. In pod dropdown list i can't see the choice pod as said in this link -> https://github.com/argoproj/argo-cd/wiki/Application-details-page-design

Are there any configuration, which need to be turned on or etc?

Best,
Kristjan

**Comment by alexmt** [comment]
Hello @Karukas ,

This feature is not implemented yet. Changing ticket type to feature.

**Comment by mateustanaka** [comment]
Hi @alexmt, some update about this feature? It would be nice to have it.

**Comment by saumeya** [comment]
Pod logs are added in current version, can this issue be closed?

**Comment by Karukas** [comment]
Yes!

Many thanks!
