### ISSUE TITLE
Upgrade to 1.5.4 from 1.4.3 is failing

### ISSUE THREAD

**Issue by chiragthaker** [argoproj/argo-cd#3572]
Post upgrading argocd loading applications is failing and only get 

"failed to verify app state ytfPQWyLSL: EOF" error while trying to access argo.

Understand there was a change with redis with version 1.5 but dont know what other things are messed up . This is blocking stuff for us

**Comment by chiragthaker** [comment]
<img width="890" alt="Screenshot 2020-05-12 at 19 32 50" src="https://user-images.githubusercontent.com/53787398/81726298-730dc700-9487-11ea-885d-7b9ba32250fb.png">

**Comment by alexmt** [comment]
The same conversation is happening in https://github.com/argoproj/argo-cd/issues/3547 . Please, lets use it to track progress on the issue.
