### ISSUE TITLE
OIDC Provider - OneLogin Integration 

### ISSUE THREAD

**Issue by alesabater** [argoproj/argo-cd#3573]
Checklist:

* [*] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**

While setting up OneLogin SSO using the [Existing OIDC Provider](https://argoproj.github.io/argo-cd/operator-manual/user-management/#existing-oidc-provider) and following instructions from [official docs](https://argoproj.github.io/argo-cd/operator-manual/user-management/onelogin/) I keep getting same error: 

```
failed to get token: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"client authentication failed"}
```

I thought it could be related to an environment related issue such as the way I was encoding the **client_secret** of the **OneLogin Application**, so I tried several ways and now luck.

Following [OneLogin documentation](https://developers.onelogin.com/openid-connect) and the different API calls that ArgoCD makes I realised that the **authentication flow** being used is the **Basic flow** which is a 2-step flow designed for for apps that have a back end that can communicate with the IdP.

Once you have configured argo using **argocd-cm.yaml** and **argocd-rbac.cm.yaml** and re-deploy ArgoCD you get the **OneLogin** button, you click it and you even get to the authentication UI or the [OneLogin Auth Code Flow pt. 1](https://developers.onelogin.com/openid-connect/api-v1/authorization-code) - up to here all good. At this point a code is generated for the second step of the authentication flow or [Auth Code Flow pt. 2](https://developers.onelogin.com/openid-connect/api-v1/authorization-code-grant) getting you the above error. Convinced that everything was correctly setup in the OneLogin side I took the generated code from the response of the API call **OneLogin Auth Code Flow pt. 1** and was able to successfully obtain a Token from the shell using the below command: 

```
curl --location --request POST 'https://<region>.onelogin.com/oidc/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic xxxxxxxxxxxxxxxx==' \
--data-urlencode 'code=xxxxxxxxxxxxxxx' \
--data-urlencode 'redirect_uri=https://argocd.myproject.com/auth/callback' \
--data-urlencode 'grant_type=authorization_code'
```

**To Reproduce**

Setup OneLogin OIDC as describe in the [official documentation](https://argoproj.github.io/argo-cd/operator-manual/user-management/onelogin/)

Your **argocd-cm.yaml** should look like:
```
  oidc.config: |
    name: OneLogin
    issuer: https://<region>.onelogin.com/oidc
    clientID: xxxxx
    # This is a base64 encoded value!
    clientSecret: xxxxx
    # Optional set of OIDC scopes to request. If omitted, defaults to: ["openid", "profile", "email", "groups"]
    requestedScopes: ["openid"]
```

Go to your argoCD site, in this case **argocd.myproject.com** click on OneLogin Button, authenticate in the OneLogin UI using the Developer tools in chrome or mozilla, get the response from the [OneLogin Auth Code Flow pt. 1](https://developers.onelogin.com/openid-connect/api-v1/authorization-code) this will contain a **code=xxxxxxxxx** that you will need to obtain the token from the shell. 

The API call in which the authentication fails is:
```
https://argocd.myproject.com/auth/callback?code=xxxxxxx&state=zzzzzzz
```

This should be something like the below instead:

```
curl -XPOST "https://<region>.onelogin.com/oidc/token" \
-H "Authorization: Basic <base64 encoded client_id:client_secret>" \
-H "Content-Type: application/x-www-form-urlencoded" \
-d "grant_type=authorization_code&code=<authorization code>&redirect_uri=<registered redirect uri>"
```

**Expected behavior**

```
curl -XPOST "https://<region>.onelogin.com/oidc/token" \
-H "Authorization: Basic <base64 encoded client_id:client_secret>" \
-H "Content-Type: application/x-www-form-urlencoded" \
-d "grant_type=authorization_code&code=<authorization code>&redirect_uri=<registered redirect uri>"
```

instead of

```
https://argocd.myproject.com/auth/callback?code=xxxxxxx&state=zzzzzzz
```

This should be something like the below instead:

**Screenshots**

**Version**

```shell
argocd: v1.5.2+c2c19f4
  BuildDate: 2020-04-15T16:43:41Z
  GitCommit: c2c19f42ad78ed7a6fb70e86aed117be484feb50
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.5.0+bdda410
  BuildDate: 2020-04-02T16:38:24Z
  GitCommit: bdda41046378a855e289b5f1602d5c923a3f914a
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0
```

**Comment by victorboissiere** [comment]
I have the exact same issue and its becoming very problematic. @alesabater did you find a workaround ?

**Comment by alesabater** [comment]
Hi @victorboissiere, No I ended up using DEX instead. Let me know if you find any solution for this please.

**Comment by conhumi** [comment]
I have tried it with v1.7.1 / v1.7.7 and think it has the same problem.

**Comment by aafishman** [comment]
I am having the same issue I believe - has anyone been able to set up with OneLogin recently? I am new to our orgs one-login setup, though I believe I have set up ArgoCD to default to read-only at least if the creds are not valid.

**Comment by aafishman** [comment]
Update - looks like the documentation needs to be updated - I tried entering the clientsecret **without** base64 encoding and it worked.

**Comment by phajduk** [comment]
@aafishman you are right. I faced same problem and removing base64 encoding fixed the problem.

I've created a PR that updates the doc:
https://github.com/argoproj/argo-cd/pull/4763

**Comment by jannfis** [comment]
Thank you for the documentation update, @phajduk! 

With the PR merged, I think this issue can be closed. @alesabater if you still encounter the issue with updated instructions, feel free to reopen this issue please.

**Comment by aafishman** [comment]
Right on, thanks @phajduk! In other news - Is anyone able to get the ArgoCD CLI working at the same time as the webUI on the same OneLogin app? I can work around by creating a second OneLogin app with the 'Native' Application type and PKCE tokens - that seems to work for the CLI - but the UI stops working. I'd rather not have a second OneLogin app for the same endpoint (more to manage). Not opening an issue at this time since this is likely a OneLogin thing - tho perhaps there is a dex workaround.

**Comment by jutley** [comment]
@aafishman Do you ever get a functional setup for accessing argo-cd via OneLogin from the CLI and Web UI at the same time? I have revisited this periodically, but I don't think the situation has ever improved.

**Comment by aafishman** [comment]
Ultimately I used two OneLogin apps and set the same rules/logic between them for user management (not great solution IMO but this is a OneLogin limitation to not allow multiple callbacks/unique ids per callback).

The trick was in the argo-cd config map OneLogin config block:

```
name: OneLogin
issuer: https://<oidc url>
clientID: <client id from the web ui app in onelogin>
cliClientID: <client id from the CLI app in onelogin>
clientSecret: <client secret from the WEB UI app in onelogin>
```

Since it does a local redirect, seems like the client secret for the webui is what gets used eventually in the chain regardless so this works. The client secret on the 'cli app' doesn't end up being required

**Comment by jutley** [comment]
@aafishman This worked! Thank you so much.
