### ISSUE TITLE
Manifests are incorrectly cached if target revision is tag

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#3577]
**Describe the bug**

Argo CD uses `git show-ref -s <targetVersion>` to get commit sha and retrieve cached manifests. After manifest generation Argo CD uses  `git checkout <targetVersion>; git rev-parse HEAD` to get current commit sha to save generated manifests in cache. 

It appears that `git show-ref -s <targetVersion>` and `git checkout <targetVersion>; git rev-parse HEAD` might return different commits. 🤯

**To Reproduce**

1. Create argocd app using https://github.com/argoproj/argo-rollouts repo and `manifests/cluster-install` as a path.
2. Set target revision to v0.7.0
3. Manifests are supposed to be cached for 24 hours but generated for argo rollouts every 3 minutes. 

```
$ git clone git@github.com:argoproj/argo-rollouts.git
$ cd argo-rollouts
$ git show-ref -s v0.7.0                                                                                                                             
4189b6e95bfdd734dabfb36cd44ff1f9411b3f43
git rev-parse HEAD                                                                                                                               
3b1d4717a1725200698549f5a7f11ba7bef6cb86
```
**Expected behavior**

Manifests should be cached for 24 hours.

**Version**
```shell
v1.5.4
```

**Comment by jannfis** [comment]
This rather seems to be a problem with the specific tag `v0.7.0`, since its commit ref can nowhere be found in the Git log and its HEAD points elsewhere therefore.

```
$ git show-ref -s v0.7.0
4189b6e95bfdd734dabfb36cd44ff1f9411b3f43 refs/tags/v0.7.0
$ git log --all --decorate | grep 4189b6e95bfdd734dabfb36cd44ff1f9411b3f43
$ git show-ref -s v0.7.1
ea6c8d1f254851fe0aa1d9004e0134b6dfa82800 refs/tags/v0.7.1
$ git log --all --decorate  | grep ea6c8d1f254851fe0aa1d9004e0134b6dfa82800
commit ea6c8d1f254851fe0aa1d9004e0134b6dfa82800 (tag: v0.7.1)
```

I'm unsure how this can happen, I guess it's one of the mysteries of Git? Or there was a commit later to that tag, without the tag being updated on the remote?

I think rather the tag reference in the Git meta data should be fixed.
