### ISSUE TITLE
Login fails with SSO after logging out

### ISSUE THREAD

**Issue by rbkaspr** [argoproj/argo-cd#3589]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
After logging out of ArgoCD, SSO login will succeed according to the logs, but any attempt to access the ArgoCD UI will result in the user being redirected back to the login page with a `401 Unauthenticated - no session information error` logged both in the server logs and the browser console. Logins with the local admin account are not impacted by this issue

The issue appears to be circumvented by clearing browser cache, but this is not idea. Our setup is currently using the new --rootpath flag introduced in v1.5.3, not sure if it's related.

**To Reproduce**

Log into ArgoCD for the first time using an SSO account
Log out of ArgoCD
Attempt to log back in with the SSO account

**Expected behavior**

Login should proceed normally and the user should be able to access whatever their RBAC privileges entitle them to

**Version**

```shell
v1.5.4+36bade7
```

**Comment by jannfis** [comment]
Hi, thank you for your report. I think #3552 reports the same, although specific to Keycloak SSO provider.

**Comment by rbkaspr** [comment]
As it happens, I'm also using Keycloak as my SSO provider, though I saw something similar was reported in #2763 with Github SSO. Not sure if that person was having the same issue, they resolved it themselves and closed without reporting their solution. Feel free to close this issue as a duplicate of #3552

**Comment by alexmt** [comment]
Hello @rbkaspr , I'm pretty sure this is due to bug in `--rootpath` support implementation. The bug was fixed by https://github.com/argoproj/argo-cd/pull/3632 and available in [v1.5.8](https://github.com/argoproj/argo-cd/releases/tag/v1.5.8)
