### ISSUE TITLE
Argo should automatically add repositories if it matches a template

### ISSUE THREAD

**Issue by whitleykeith** [argoproj/argo-cd#3591]
# Summary
I think it'd be nice if Argo could automatically configure repositories referenced by an Application if that repo matches an already configured credential template. 

# Motivation

We're using Argo to roll out platform offerings to different teams across the company that have their own configuration repos. All of our config repos fall under a specific URI pattern so we can have one template for essentially all of our repos. However, we have to manually add repos as teams start to use the platform, which is tedious at scale. 

# Proposal

Ideally, if an application's Repo URL matched a pre-defined credential template, it should be automatically added once that application was submitted and picked up by Argo.

**Comment by jannfis** [comment]
Hi @whitleykeith, if you are using credential templates, you don't necessarily need a specific repository configuration to use it as application source. You can just use the repository URL (which is covered by the credential template) as a source for any application. You'd just need a repository configuration when the repository needs a special configuration, for example LFS support.

I think automatically adding repositories would have more unwanted side effects than benefits.

**Comment by whitleykeith** [comment]
So you're saying that if I have a template that matches the prefix then I dont need to specify the url in the repositories section?

**Comment by jannfis** [comment]
Yes, that's correct. The project the application belongs to has to allow the repository as application source so it can be used, tho (the default project allows any repository).

I admit that the current documentation is unfortunately not very clear about this currently. As a quick heads up, I'm working on a complete rewrite of the repositories section of the documentation.

**Comment by whitleykeith** [comment]
can a project allow an repository template?

**Comment by jannfis** [comment]
You can use simple pattern matching for the allowed destination repositories.

Given two repositories at the following locations:
* `https://git.example.com/repos/repos1` and 
* `https://git.example.com/repos/repos2`

You would setup the credential template for `https://git.example.com/repos/` and allow `https://git.example.com/repos/*` as source repository in the project.

**Comment by whitleykeith** [comment]
ah I see, so Argo can still use the source repo as long as it matches a template and the associated projects have the right repo permissions. I think the current behavior works for our use cases.

Thanks!
