### ISSUE TITLE
Support setting '.spec.source.helm.values' with CLI

### ISSUE THREAD

**Issue by sfynx** [argoproj/argo-cd#3601]
# Summary

With `argocd app create` you can set individual Helm parameters with `--helm-set`, but it is currently not possible to put arbitrary values into `.spec.source.helm.values` from an external source. The `--helm-set-file` and `--values` options do not seem to accept the contents of a `.yaml` file that is located on the host were the CLI is being ran.

# Motivation

This functionality is required if you want to pass arbitrary YAML to the application values from an external source, e.g. from a CI pipeline. A common use case is when you have an app-of-apps, where different apps reside in different repositories so that project role security can be enforced, and you want to use values that reside in one repository to create an app that resides in another repository. This way you can give people access to configure an app with arbitrary values, but the actual app and its templates can still be restricted.

# Proposal

Perhaps we can add a `--helm-values-from` parameter where you can specify a file of which the contents will be used in the `.spec.source.helm.values` key of the app being created.

**Comment by sfynx** [comment]
Perhaps `--values-from` would be the better option name so it is clear it is handled by ArgoCD instead of passed on to Helm, and it is also in line with the `--values` option which sets a values file reference instead.

**Comment by davidkarlsen** [comment]
Also some context in https://github.com/argoproj/argo-cd/issues/3365#issuecomment-640597638

**Comment by james-callahan** [comment]
Should this be closed now #3646 is merged?

**Comment by sfynx** [comment]
Yeah, closing this one as this is now released as part of v1.6.

**Comment by michaelajr** [comment]
Sorry to post on a closed issue - but I can not get this to work. I'm doing:

```
argocd app create -f path/to/app-manifest.yaml  --values-literal-file path/to/helm-values.yaml
```
And the app gets created without the values from `helm-values.yaml`. 

```
$ argocd version
argocd: v1.6.0+c10ae24
  BuildDate: 2020-06-16T22:41:56Z
  GitCommit: c10ae246ab02f1356147118a1979fedcd1ceb704
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Comment by michaelajr** [comment]
Yeah. This does not work with the `-f` option. I think it should. It would be a nice way bring values to an app manifest.

**Comment by sfynx** [comment]
Just had a quick look, and the `-f` option actually disables all options that specify part of the manifest, which also includes `--values`, `-p` and `--helm-set`. Only if the value of `-f` is empty it will proceed to use these options, as we can see from this code:
https://github.com/argoproj/argo-cd/blob/1a9453856802a2e73f7cdd0fe3a51ad33e6f9952/cmd/argocd/commands/app.go#L132-L154

Now at first glance it does not seem difficult to change it so that it simply parses them in all cases (overriding anything in the file) by moving it out of the `else` section, but that should be tested thoroughly of course. I agree such a thing could be useful so that you can source a base manifest and make adjustments to it without having to merge things into one file yourself.

As this does not seem to be related to the `--values-literal-file` option specifically, I think this should warrant a separate enhancement request.

**Comment by michaelajr** [comment]
@sfynx I opened a new issue #3943. Thanks.
