### ISSUE TITLE
`ignoreAggregatedRoles` doesn't seem to work

### ISSUE THREAD

**Issue by rokrokss** [argoproj/argo-cd#3602]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I just went through this problem with 1.5.4 so I uploaded to v1.5.5 which has https://github.com/argoproj/argo-cd/pull/3076 merged.
```
resource.compareoptions: |
  ignoreAggregatedRoles: true
```
I put this on `argocd-cm`. I'm afraid the roles were still being out-of-sync by `rules`, which was not expected in https://github.com/argoproj/argo-cd/pull/3076

**Expected behavior**

out-of-sync => restore loop should stop after setting `ignoreAggregatedRoles: true`

**Version**

```shell
$ argocd version
argocd: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:02:57Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:04:43Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Comment by jannfis** [comment]
Hi @rokrokss, the mentioned PR is not yet part of the `v1.5.5` or any other release. I'm setting this bug to invalid.

**Comment by rokrokss** [comment]
@jannfis oh sorry I was mistaken.

**Comment by lippertmarkus** [comment]
@jannfis this doesn't work for me with v1.6.1 either

**Comment by jannfis** [comment]
@lippertmarkus Can you please be a litte more concise? What exactly doesn't work?

**Comment by lippertmarkus** [comment]
I added the following to the `argocd-cm` configmap:
```yaml
resource.compareoptions: |
  ignoreAggregatedRoles: true
```

and deployed Argo Workflows with Argo CD. The aggregate roles stay in a sync loop:
![image](https://user-images.githubusercontent.com/1463140/86236385-4712e600-bb9a-11ea-84e3-a41c6645806d.png)

**Comment by jannfis** [comment]
Hm, your screenshot shows the actual aggregation role _sources_ to be syncing. The toggle `ignoreAggregratedRoles` should not affect the aggregation _source_, but the _destination_ role (the one that actually aggregrates from other roles, i.e. those which have an `aggregationRule` set).

If you set `ignoreAggregationRoles` to `false`, do your `argo-aggregate-to-*` roles actually sync?

**Comment by lippertmarkus** [comment]
Ah okay then I understood the PR wrong, thanks for clarification! Unfortunately the aggregation sources `argo-aggregate-to-*` doesn't sync, independent of the `ignoreAggregatedRoles` setting.

What I further noticed: If I manually delete the `argo-aggregate-to-*` roles via kubectl, the first sync is successful. But
 if I sync a second time then it's stuck in the loop again.

**Comment by lippertmarkus** [comment]
@jannfis Do you have any idea?

**Comment by jannfis** [comment]
@lippertmarkus Judging from your screenshot, apparently your `argo-aggregate-to-*` roles are considered to be hooks. Do you install from a Helm chart that does that? Do the resources have a hook deletion policy?

**Comment by lippertmarkus** [comment]
Yes, `pre-install` hooks with a deletion policy of `before-hook-creation`, see here: https://github.com/argoproj/argo-helm/blob/master/charts/argo/templates/workflow-aggregate-roles.yaml

**Comment by jannfis** [comment]
Thanks. In fact, we noticed some problems with Helm hooks that have a deletion policy, but I couldn't reproduce it reliably yet. Let's see if I could reproduce it with the Argo WF Helm chart. Probably, a new issue would be good for that, yes.

**Comment by lippertmarkus** [comment]
Thanks you, I creaed #3928

**Comment by BostjanBozic** [comment]
I am not sure if I understood correctly, but to my understanding `ignoreAggregatedRoles: true` sets ArgoCD to ignore OutOfSync for `ClusterRoles` that have `aggregationRule` parameter set, right?
Since I am running into same issue - I am trying to sync some aggregating ClusterRoles and they get synced, but stay in OutOfSync (requires pruning) status (using Argo v1.6.1).

**Comment by alexbowers** [comment]
I'm running into this problem too.

I have Argo configured with `resource.compareoptions.ignoreAggregatedRoles` set to `true`. And when I install Emissary Ingress; which has 2 `ClusterRole` resources configured, they are constantly taking themselves out of sync and updating because of the `aggregatedRoles`.

You can see the Emissary config here: https://github.com/emissary-ingress/emissary/blob/master/charts/emissary-ingress/templates/rbac.yaml#L11
