### ISSUE TITLE
Argocd app remains OutOfSync due to app.kubernetes.io/instance: argocd label diff

### ISSUE THREAD

**Issue by ysksuzuki** [argoproj/argo-cd#3603]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We're applying our [manifest](https://github.com/cybozu-go/neco-apps/tree/master/argocd/base) with argocd. It normally works fine, but sometimes argocd application status remains OutOfSync. `argocd app diff` command detects `app.kubernetes.io/instance: argocd` label.

```shell
$ argocd app list
NAME                  CLUSTER                         NAMESPACE    PROJECT  STATUS     HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                               TARGET
argocd                https://kubernetes.default.svc  argocd       default  OutOfSync  Healthy  Auto-Prune  <none>      https://github.com/cybozu-go/neco-apps.git  argocd/base                        6f4670db8385dacbee6db865332cb4cb1f7f8d2d
argocd-config         https://kubernetes.default.svc  argocd       default  OutOfSync  Missing  <none>      <none>      https://github.com/cybozu-go/neco-apps.git  argocd-config/overlays/gcp         6f4670db8385dacbee6db865332cb4cb1f7f8d2d

$ argocd app diff argocd
===== apps/Deployment argocd/argocd-redis ======
5a6
>     app.kubernetes.io/instance: argocd
===== apps/Deployment argocd/argocd-repo-server ======
5a6
>     app.kubernetes.io/instance: argocd
===== rbac.authorization.k8s.io/ClusterRole /argocd-server ======
5a6
>     app.kubernetes.io/instance: argocd
===== rbac.authorization.k8s.io/ClusterRoleBinding /argocd-server ======
5a6
>     app.kubernetes.io/instance: argocd
===== /Service argocd/argocd-server-https ======
7a8
...
```

**To Reproduce**

1. Setup argocd with the manifest [here](https://github.com/cybozu-go/neco-apps/tree/master/argocd/base).
2. Create application with the repository [here](https://github.com/cybozu-go/neco-apps).
3. Argocd application's status remains OutOfSync, and never gets to Healthy. It normally works fine, but sometimes goes wrong.

We creat argocd app with the command below.

```shell
$ argocd app create argocd-config
     --upsert 
     --repo https://github.com/cybozu-go/neco-apps.git 
     --path argocd-config/overlays/kind 
     --dest-namespace argocd
     --dest-server https://kubernetes.default.svc
     --sync-policy none
     --revision master
```

**Expected behavior**

Argocd app's status gets to HEALTY, and all applications are successfully synced.

**Screenshots**

none

**Version**

```shell
argocd: v1.5.1+8a3b36b
  BuildDate: 2020-04-06T15:53:49Z
  GitCommit: 8a3b36bd28fe278f7407b9a8797c79ad859d1acd
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.2+unknown
  BuildDate: 2020-04-23T03:55:18Z
  GitCommit:
  GitTreeState: clean
  GoVersion: go1.13.8
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: unable to determine ksonnet version: exec: "ks": executable file not found in $PATH
  Kustomize Version: {Version:kustomize/v3.5.3 GitCommit:5ba90fe5ef1dc4599e359edd41d1d0e6373b247d BuildDate:2019-12-17T21:57:37Z GoOs:linux GoArch:amd64}
  Helm Version: could not get helm version: exec: "helm": executable file not found in $PATH
  Kubectl Version: v1.17.4
```

**Logs**

none

**Comment by jdfalk** [comment]
Check out: [argocd-cm.yaml](https://argoproj.github.io/argo-cd/operator-manual/argocd-cm.yaml)
You want to add this to your config file. 
```
  # The metadata.label key name where Argo CD injects the app name as a tracking label (optional).
  # Tracking labels are used to determine which resources need to be deleted when pruning.
  # If omitted, Argo CD injects the app name into the label: 'app.kubernetes.io/instance'
  application.instanceLabelKey: mycompany.com/appname
```

**Comment by ysksuzuki** [comment]
We don't need to change instanceLabelKey.
The problem is that argocd detected `app.kubernetes.io/instance: argocd' label diff, even though it added the label itself intentionally. So I don't think that adding `application.instanceLabelKey:` solves our problem.

**Comment by jdfalk** [comment]
I would try it. See if things become more consistent then. In any case, it frees up that label to be used by you, and in other applications. The worst that happens is that I'm wrong and I'll owe you a beer 😸

**Comment by ysksuzuki** [comment]
Sorry for my late replay. We will try it and see things become stable. If the problem occurs with `application.instanceLabelKey` setting, then I'll get back to you.

**Comment by ysksuzuki** [comment]
The problem hasn't occurred since we update ArgoCD to v1.5.6. Things have become consistent so far. Thank you for your support.
