### ISSUE TITLE
Add ability to track helm value file via github for application history and rollback

### ISSUE THREAD

**Issue by smark88** [argoproj/argo-cd#3610]
# Summary
Helm chart revisions are tracked in github history, this would add tracking of out of helm repo value files.

# Motivation
Created app with github repo and github value files and both can be tracked via rollback and history.

`--values "https://raw.githubusercontent.com/differentrepo/app-helm-definitions/master/dev/ms/msDeployment.yaml"` -> tracking for this file via github

```
argocd app create ms-app --project ms-app \
--repo https://github.com/work/app-helm \
--values "https://raw.githubusercontent.com/differentrepo/app-helm-definitions/master/dev/ms/msDeployment.yaml" \
--path charts/app \
--dest-namespace ms \
--dest-server https://kubernetes.default.svc \
--sync-policy automated \
--self-heal
```

**Comment by blakepettersson** [comment]
This should hopefully be addressed with #10432, let me know if that's not the case 😄
