### ISSUE TITLE
Update to kustomize 3.5.5

### ISSUE THREAD

**Issue by chancez** [argoproj/argo-cd#3618]
# Summary

Upgrade kustomize to 3.5.5 to fix the following bug https://github.com/kubernetes-sigs/kustomize/issues/2125 where newlines are being removed from configmaps and secrets. 

# Motivation

Currently, when running `argocd app diff --local` I get different results from the live state because we're using the newer version of kustomize, while argocd is using the older version.

**Comment by roelofjansen** [comment]
Can you please mark this as a bug and not a feature. The configMapGenerator functionality in kustomize 3.5.4 is broken and fixed in 3.5.5. We had a serious production issue after updating to 1.5.5 the day before yesterday.

**Comment by markbenschop** [comment]
Please upgrade from kustomize 3.5.4 to 3.5.5 since 3.5.4. The argocd release that uses kustomize 3.5.4 can cause serious breakages.
