### ISSUE TITLE
redis connection issue

### ISSUE THREAD

**Issue by renperez** [argoproj/argo-cd#3620]
i recently provisioned elastic redis to use for my argocd. I updated the argocd repo server end point for redis but its not working. I am getting tcp connection error. is there any other place i need to update? it seems like the repo server still pointing to old redis service which I have turned off after updating the redis endpoint.

**Comment by jannfis** [comment]
Hi @renperez, you need to point all ArgoCD components - `argocd-server`, `argocd-repo-server` and `argocd-application-controller` - to the same Redis instance. 

Is there a reason you don't want to use the bundled Redis service?

**Comment by renperez** [comment]
@jannfis thank you for the prompt response. we are just trying to be consistent since we are using elastic cache for all our tools. how do i point argo-server and argo application controller to the new redis instance?

**Comment by jannfis** [comment]
@renperez You need to modify the deployment spec for each component and change `--redis` argument to point to your Redis server.

Reference:
```
      --redis string                          Redis server hostname and port (e.g. argocd-redis:6379). 
      --redisdb int                           Redis database.
```

**Comment by renperez** [comment]
@jannfis that worked! thanks again!
