### ISSUE TITLE
Actions and  Resources in contrast

### ISSUE THREAD

**Issue by renhao-0518** [argoproj/argo-cd#3621]
Now :
Actions: [clusters projects applications repositories certificates]
Resources: [get create update delete sync override]

Should :
Actions: [get create update delete sync override]
Resources: [clusters projects applications repositories certificates]

[root@dev-k8s-master1 ~]# argocd account can-i
Can I

Usage:
  argocd account can-i ACTION RESOURCE SUBRESOURCE [flags]

Examples:

# Can I sync any app?
argocd account can-i sync applications '*'

# Can I update a project?
argocd account can-i update projects 'default'

# Can I create a cluster?
argocd account can-i create clusters '*'

Actions: [clusters projects applications repositories certificates]
Resources: [get create update delete sync override]

**Comment by jannfis** [comment]
Can you please elaborate a little more what you are trying to tell us here?

**Comment by renhao-0518** [comment]
argocd cli use  argocd account can-i  

<img width="846" alt="企业微信截图_70db4f95-7bc2-4e92-bf62-9f77e425aa17" src="https://user-images.githubusercontent.com/52058058/82518767-aa990500-9b52-11ea-9051-46a5c8a13674.png">

**Comment by renhao-0518** [comment]
resource should is clusters projects applications repositories certificates 
now is get create update delete sync override

**Comment by jannfis** [comment]
@renhao-0518 Ah! Yes, now I understand :) Thank you for noticing and bringing it up :)
