### ISSUE TITLE
helm3 template with --validate option

### ISSUE THREAD

**Issue by gmoshiko** [argoproj/argo-cd#3640]
# Summary

helm3 has a new template function called lookup. 
The lookup function can be used to look up resources in a running cluster and get metadata from objects on render time. 
this feature was introduced on helm3 release and was working with helm template command, the problem was this is a vulnerability in terms of helm template shouldn't interact with the cluster unless specified the --validate flag. 

in the latest helm3 version they fixed that vulnerability and now helm template wouldn't render this function, but it should render when using --validate flag. 

this feature currently doesn't work with helm template --validate as it should be, but it should be fixed soon and there is also an open issue about it.

# Motivation

get metadata from objects like ConfigMaps so I can decide on which cluster im on, and write logic in helm template to use it instead of writing it in each values.yaml file for each cluster( i have 40 k8s clusters I manage, and 90% of the time the only thing I change between the clusters is the cluster name I'm deploying to.)

# Proposal

ArgoCD uses helm template command before applying with kubectl to the cluster. 
if we could have the option to add --validate to helm template command it could solve the problem and support the lookup function once this issue is solved by helm. 

# Reference

helm functions: https://helm.sh/docs/chart_template_guide/functions_and_pipelines
lookup Function Information Discolosure: https://github.com/helm/helm/security/advisories/GHSA-q8q8-93cv-v6h8
helm template render lookup function issue:  https://github.com/helm/helm/issues/8137

**Comment by rajivml** [comment]
+1 This would be really helpful for deriving private registry addresses, ingress hosts etc. so that we need take these inputs from the user

**Comment by dansou901** [comment]
would also love to see this baked in

**Comment by ebuildy** [comment]
Also, this could fix error when using ``.Capabilities.APIVersions.has`` Helm template function which rely without ``--validate`` option on the kubectl version compiled (mean Helm v3.8 will support k8s v1.23).

**Comment by 13013SwagR** [comment]
FYI, this project provides a decent workaround https://github.com/kuuji/helm-external-val

**Comment by Jorricks** [comment]
Is there any active development on this ticket?

**Comment by crenshaw-dev** [comment]
I believe https://github.com/helm/helm/pull/9426 is a prerequisite.

Should we consider this a duplicate of https://github.com/argoproj/argo-cd/issues/5202 ?

**Comment by crenshaw-dev** [comment]
Closing for now, in favor of 5202.
