### ISSUE TITLE
Add readOnlyRootFilesystem to securityContext

### ISSUE THREAD

**Issue by jkleinlercher** [argoproj/argo-cd#3648]
# Summary

Our security&compliance best practices suggest to use readOnlyRootFilesystem securityContext on every deployment. With this setting it is enforced that no process can write in the container filesystem. Every directory which needs to be written to, must be declared as an emptyDir filesystem.

# Motivation

CIS benchmarks say that as default you should not be allowed to write in a container filesystem. If you need to, it should be explicitly declared.

# Proposal

Define readOnlyRootFilesystem=true in the securityContext of the deployments and if a process needs to write to a directory, define it as emptyDir filesystem.

**Comment by jkleinlercher** [comment]
According to @jannfis a good starting point for emptyDir volumes which still need write access would be

- /tmp and /home/argocd in argocd-repo-server, argocd-server and argocd-application-controller
- /tmp in argocd-dex-server
- redis is unknown

I doubt that trial-and-error is a good methodology here, I am just too afraid that failures due to a read-only filesystem arise too late in production or not at all but just strange side effects. I think we need a proven  methodology here to introduce readOnlyRootFilesystem .

Do we really know where argocd writes to? If not, how can we find out? („docker diff“?) How do we ensure that we check this during further development of argocd?

Are there any experts on this who already accomplished that for their software?

**Comment by mkilchhofer** [comment]
We started a discussion about this in the helm-chart repository over there: argoproj/argo-helm#619

Should we go on and change the default to a read-only file system inside the chart? Besides the fixed issue with `/tmp` and `/app/config/gpg/keys` for repo-server there is currently no other issue.

**Comment by jkleinlercher** [comment]
I would highly appreciate if you can set readOnlyRootFilesystem=true by default in the chart and see if everything works! I would also love if your efforts according readOnlyRootFilesystem would also go in this upstream repo, not "just" in the argo-helm repo. However, I am still not sure if argo-cd is fully functional with readOnlyRootFilesystem=true and if all directories which need write access are known ... however, if you can make those experiences in the argo-helm repo and if everything looks good you can come back we should create a PR also for this repo to make readOnlyRootFilesystem a default. that would be amazing and would push security in argo-cd another step forward!

**Comment by mkilchhofer** [comment]
@davidkarlsen and @yann-soubeyrand WDYT? With the helm3 migration (`apiVersion: v2`) I think there's a breaking change coming anyway. We could change the default within this change. For those using argo without custom plugins, it should work with read-only file system and those wo need customizing (eg. plugins and so on) can set `readOnlyRootFilesystem: false`

**Comment by davidkarlsen** [comment]
sgtm

**Comment by jkleinlercher** [comment]
https://github.com/argoproj/argo-cd/pull/5814

**Comment by alexmt** [comment]
Adding to v2.1 since it is effectively in progress already.

**Comment by sbose78** [comment]
Thanks Alex, all PRs are up, I think.

**Comment by alexmt** [comment]
All related PRs are merged. Argo CD is more secure now :)
