### ISSUE TITLE
When operations complete, force refresh comparison state

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#365]
#It's often the case that immediately following a sync, an application's state will be inaccurate. This is because the comparison result is not updated until the next app refresh. The user is in a confusing situation where a sync succeeded, but the app is OutOfSync.

After operation completes, we should force refresh the app, so that at least the sync status is accurate.

**Comment by merenbach** [comment]
[ ] Front-end changes: https://github.com/argoproj/argo-cd-ui/pull/12
[ ] Back-end changes: #373
