### ISSUE TITLE
argocd 1.5.5 wrong kustomize version

### ISSUE THREAD

**Issue by rosscdh** [argoproj/argo-cd#3664]
Checklist:

* [* ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ *] I've included steps to reproduce the bug.
* [ *] I've pasted the output of `argocd version`.

**Describe the bug**

Hey all, the latest ArgoCD 1.5.5 release proports to have kustomize 3.5.5 but is actually still packaging 3.5.4

```
argocd-server: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:04:43Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

perhaps due to this hack? https://github.com/argoproj/argo-
```
cd/blob/0fdef4861e12026e133224f7c9413072340e2983/hack/installers/install-kustomize-linux.sh (edited) 
```

**To Reproduce**

install 1.5.5 HA

**Expected behavior**

kustomize 3.5.5 is the default

**Screenshots**

**Version**

```shell
argocd version
argocd: v1.5.4+36bade7
  BuildDate: 2020-05-05T18:59:08Z
  GitCommit: 36bade7a2d7b69d1c0b0c4d41191f792a847d61c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:04:43Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jannfis** [comment]
Hi @rosscdh - ArgoCD v1.5.5 is supposed to be bundled with Kustomize v3.5.4. 

Where is it stated that v1.5.5 is bundled with Kustomize v3.5.5? I can see no such information on the releases page or in the Changelog.

**Comment by rosscdh** [comment]
Curious i clicked on the link for the commits on the release page but i see its comparing with master! apologies.. will patch ours with init container to include k 3.5.5 thanks!
