### ISSUE TITLE
Update to kustomize 3.6.1

### ISSUE THREAD

**Issue by daurnimator** [argoproj/argo-cd#3665]
kustomize 3.5.4 and 3.5.5 have several significant issues. e.g.
  - https://github.com/kubernetes-sigs/kustomize/issues/2125
  - https://github.com/kubernetes-sigs/kustomize/issues/2444
  - https://github.com/kubernetes-sigs/kustomize/issues/2494
  - https://github.com/kubernetes-sigs/kustomize/issues/2538

The latest release (3.6.1 right now) should have fixed them.
https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.6.1

**Comment by alexmt** [comment]
🤦  I feel like we should wait a couple more days just in case 3.6.2 got published.
