### ISSUE TITLE
RBAC roles not appearing on UI

### ISSUE THREAD

**Issue by PastNullInfinity** [argoproj/argo-cd#3724]
Checklist:

* [ :heavy_check_mark: ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [:heavy_check_mark: ] I've included steps to reproduce the bug.
* [:heavy_check_mark: ] I've pasted the output of `argocd version`.

**Describe the bug**
I have SSO authz set up on an ArgoCD 1.4.3 deployment, using Keycloak as the server and an external SAML IdP provider. I've created roles according to the documentation by creating a new `policy.csv` section in the rbac configMap, but the roles for the project are not showing up on the UI. There's not much info on how to properly configure a setup like mine (without using a supported OIDC service lika Okta, or Dex.), so I might be missing some steps, or misunderstanding the expected behaviour.

**To Reproduce**

- Set up the `argocd-cm` as follows:
```yaml
    scopes: '[email, group]'
    policy.csv: |
      p, role:developer, applications, get, default/*, allow
      p, role:developer, applications, update, default/*, allow
      p, role:developer, applications, sync, default/*, allow
      p, role:developer, projects, get, default/*, allow
      p, role:developer, projects, update, default/*, allow
      p, role:developer, projects, sync, default/*, allow

      g, proj-admin, role:admin
      g, proj-dev, role:developer
```

**Expected behavior**

I would expect the UI to reflect the currently implemented policies from the RBAC config.

**Screenshots**

![argocd](https://user-images.githubusercontent.com/9055927/84012959-98073400-a978-11ea-8b62-dcde92bd8376.png)

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:04:04Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.4.3+2483411
  BuildDate: 2020-04-15T16:50:22Z
  GitCommit: 24834112d66f453de6ae53901d5dad0ad71ec902
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Comment by alexmt** [comment]
Hello @PastNullInfinity ,

The policy.csv contains Casbin policies definition, not [project roles](https://argoproj.github.io/argo-cd/user-guide/projects/#project-roles). Right now Argo CD does not have UI to visualize configured policies. Argo CD CLI has `argocd account can-i ACTION RESOURCE SUBRESOURCE` command that helps debugging policies.

**Comment by PastNullInfinity** [comment]
Ok, makes sense. Thanks for the clarification!
