### ISSUE TITLE
Adding Health Checks for certain Custom Resources

### ISSUE THREAD

**Issue by whitleykeith** [argoproj/argo-cd#3726]
# Summary

We use Argo in our cluster and have written several Custom Resource Healthchecks we'd like to submit back. The custom resources we have healthchecks for are:

- jaegertracing.io/Jaeger
- kiali.io/Kiali
- install.istio.io/IstioOperator
- zookeeper.pravega.io/ZookeeperCluster
- sparkoperator.k8s.io/SparkApplication
- operator.knative.dev/KnativeEventing
- operator.knative.dev/KnativeServing
- kafka.banzaicloud.io/KafkaCluster

# Motivation

When Argo installs any of the above custom resources

# Proposal

Accept my PR when I make it 😄

**Comment by alexmt** [comment]
More CRD health checks are always welcome!

**Comment by whitleykeith** [comment]
Closed by https://github.com/argoproj/argo-cd/pull/3728
