### ISSUE TITLE
Resource sync fails - status.history.deployStartedAt in body must be of type string: "null"

### ISSUE THREAD

**Issue by janlud** [argoproj/argo-cd#3756]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After updating to master branch (commit in argocd version output) I cannot delete a previously created namespace resource from an application. The namespace resource was created in 1.6.0-rc2. I tested it also on different sync (increase number of replicas in a deployment and got the same error.
Looks like it might be related to the recently merged PR https://github.com/argoproj/argo-cd/pull/3715

We can definitely rollback to rc2 - just wanted to raise the bug report.
EDIT: have to do manual rollback, this bug stops rollback with ArgoCD (managed by itself) rollback.
EDIT2: After returning to rc2 syncing works as expected.

**To Reproduce**

Sync a resource in an application on argoCD commit 9192cd9

**Expected behavior**

Resources are synced.

**Version**

```shell
argocd: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:05:28Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.6.0+9192cd9
  BuildDate: 2020-06-11T22:20:05Z
  GitCommit: 9192cd94c945c8d378af39b12d1d1f3a4aacb26c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0

```

**Logs**
The error message:
```
Unable to deploy revision: Application.argoproj.io "argo-cluster-addons" is invalid: status.history.deployStartedAt: Invalid value: "null": status.history.deployStartedAt in body must be of type string: "null"
```

Log from argocd-server pod:
```
time="2020-06-12T11:23:54Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = Application.argoproj.io \"argo-cluster-addons\" is invalid: status.history.deployStartedAt: Invalid value: \"null\": status.history.deployStartedAt in body must be of type string: \"null\"" grpc.code=InvalidArgument grpc.method=Sync grpc.service=application.ApplicationService grpc.start_time="2020-06-12T11:23:53Z" grpc.time_ms=818.855 span.kind=server system=grpc
```

**Comment by darshanime** [comment]
@janlud, I am not able to reproduce this no `v1.18.0` with the argo-cd versions you mentioned. What's your kubernetes version?

**Comment by darshanime** [comment]
@janlud, I am not able to reproduce this on v1.18.0 with the argo-cd versions you mentioned. What's your kubernetes version?

**Comment by mtribes-ops** [comment]
@darshanime It's 1.16 - latest possible version on EKS.

**Comment by janlud** [comment]
@darshanime It's 1.16 - latest possible version on EKS.

**Comment by alexmt** [comment]
Reproduced it as well. I suspect this is reproducible for apps that had deployment history before introducing `deployStartedAt` field. It appears that `metav1.Time` has known issue: https://github.com/kubernetes/kubernetes/issues/86811. Empty value is incorrectly serialized to `null`. I think the only workaround is to use pointer: `*metav1.Time`

**Comment by alexmt** [comment]
Another workaround is to just remove validation for the field from CRD schema. I think this is acceptable and we already doing it for other fields: https://github.com/argoproj/argo-cd/blob/80515a3b57d5ad9c63e0949c25a471ff135ed1ff/hack/gen-crd-spec/main.go#L48
