### ISSUE TITLE
session/userinfo API no longer returns OIDC information

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#3758]
/api/v1/session/userinfo is used to debug RBAC. But it appears that the API no longer returns all information. I only get:

```json
{
  "loggedIn": true,
  "username": "Jesse_Suen@intuit.com",
  "iss": "https://REDACTED.intuit.com/api/dex"
}
```

This in turns renders the user info page not useful

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/3805
