### ISSUE TITLE
Project Policy UI generates invalid spec

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#3760]
Our UI incorrectly allows an incorrect policy to be attempted to be generated. 

![image](https://user-images.githubusercontent.com/12677113/84534441-c0f03780-ac9e-11ea-9935-b2fe9636ba60.png)

The suggested application field should be `mlp/*`. `mlp` (the project name alone) is never a valid value for an application

**Comment by sanyam1997** [comment]
Hey everyone, I am a first-time contributor and I am interested in this organization. I want to make some open source contributions and learn. I am not looking for getting enrolled in the program.
Sanyam
