### ISSUE TITLE
Add support for TLS client authentication in the CLI

### ISSUE THREAD

**Issue by wdullaer** [argoproj/argo-cd#3778]
# Summary

It should be possible to use the CLI with servers that rely on TLS client authentication.

# Motivation

We use mTLS extensively, this prevents us from using the CLI.

# Proposal

Extend the client.tlsConfig method, along with updates to the config format and cli parameters.

I am creating this issue to have something to point to in my PR.

**Comment by jannfis** [comment]
Closed via #3779
