### ISSUE TITLE
Reducing/stagger git requests when referencing the same repo and revision

### ISSUE THREAD

**Issue by servo1x** [argoproj/argo-cd#3789]
# Summary

When referencing the same git repo and revision (in our case we use a single repo and reference HEAD), it seems unnecessary to make a git request for every application? Ideally we would just need to do it once or however many repo servers or add some sort of rate limiter (to reduce the burst of requests to one repo) or jitter (distribute requests over time) when autosync is enabled.

# Motivation

We use a monorepo to store all of our manifests and at 80+ applications with autosync enabled, causes a huge spike in requests to our git repository. It seems unnecessary to have to do that many requests all at once, especially since the application is referencing the same repo. It also becomes troubling when making commits in rapid succession, each push triggering the webhook will cause a refresh, which leads to an additional spike of git requests being made.

# Proposal

Not sure, but just thought I bring this up for discussion. Currently we set the app sync to be a very long duration, but we are concerned about autosyncing because of the burst of requests that get made.

**Comment by essh** [comment]
I brought up a similar issue a while ago in https://github.com/argoproj/argo-cd/issues/1895 where this behaviour can trigger AWS CodeCommit rate limiting. Some of the changes since then have stopped this from happening so much but it still does happen.

**Comment by servo1x** [comment]
Monorepo performance improvements tracked in: #4583

**Comment by alexmt** [comment]
The PR https://github.com/argoproj/argo-cd/pull/6102 has implemented the proposed change. Now Argo CD executes `git ls-remote` only once per repo per resync period (3 mins by default)
