### ISSUE TITLE
logout of argocd UI does not work

### ISSUE THREAD

**Issue by yydzhou** [argoproj/argo-cd#3792]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ *] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ *] I've included steps to reproduce the bug.
* [ *] I've pasted the output of `argocd version`.

**Describe the bug**
After user logout the UI page, and then click login, the UI will skip login process and directly turn to main page without login requirement. 

**To Reproduce**

Argocd is deployed with helm chart . 
The keycloak is used together for argocd sso support. 
After the argocd and keycloak is configured following the guide from https://argoproj.github.io/argo-cd/operator-manual/user-management/keycloak/. 
The argocd UI can be login with SSO user managed by keycloak. After clicking the LOGOUT button of the argocd UI, the page turn to the https://hostname/login . However, the page turn to the argo https://hostname/applications directly without asking for login after user click the "LOGIN VIA KEYLOAK". This is not right, user should be request to go through the login process again after they logout. 

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.
1. Deploy argocd and keycloak in k8s. 
2. Follow the official doc to setup sso https://argoproj.github.io/argo-cd/operator-manual/user-management/keycloak/
3. Register and login the argocd UI.
4. Logout
5. Click the login via "keycloak" to login again.
6. Then registering user and and login into argocd UI. 
7. Try to logout and login again.

**Expected behavior**

User should be redirected to keycloak for login verification.  instead of directly turn to main page without verification.

**Screenshots**

**Version**
v1.5.4， v1.5.7, v1.5.8, v1.6.1
```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by yydzhou** [comment]
Hi @alexmt could you please take a look or forward this issue to the right person? I am not sure if this problem comes from my misconfiguration or any bug. I really appreciate it if anyone can help me troubleshooting or narrowing down the root cause.

**Comment by yydzhou** [comment]
Finally, I figured out the problem. https://www.keycloak.org/docs/latest/server_admin/#_authentication-flows

Turns out the default authentication flow of keycloak is the cookie first. As long as there is cookie at client side, the username/password validation is skipped. I solved my problem by creating a new flow there.

**Comment by rohithbalaji123** [comment]
@yydzhou , I am facing a similar issue. Can you please share the new flow you had set to resolve the issue?

I tried setting Cookie to `alternative` and Forms to `required`. That still doesn't seem to invalidate the keycloak session during logout. But it does ask for login credentials on further sign in into argoCD. This is still an issue when using Keycloak as SSO, as other projects are also dependent on the same session.

@moderators
Is there a way to configure to also call [keycloak's logout endpoint](https://www.keycloak.org/docs/latest/securing_apps/index.html#logout) on clicking the logout button in ArgoCD?

**Comment by yydzhou** [comment]
> @yydzhou , I am facing a similar issue. Can you please share the new flow you had set to resolve the issue?
> 
> I tried setting Cookie to `alternative` and Forms to `required`. That still doesn't seem to invalidate the keycloak session during logout. But it does ask for login credentials on further sign in into argoCD. This is still an issue when using Keycloak as SSO, as other projects are also dependent on the same session.
> 
> @Moderators
> Is there a way to configure to also call [keycloak's logout endpoint](https://www.keycloak.org/docs/latest/securing_apps/index.html#logout) on clicking the logout button in ArgoCD?

@rohithbalaji123 Right, I can only enforce the user to go through the login process, which at least has some protection. But the session is nether invalid nor reset at all.

**Comment by alexmt** [comment]
@yydzhou in v1.8 you can configure logout endpoint: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/user-management/index.md#configuring-a-custom-logout-url-for-your-oidc-provider

This should invalidate OIDC token but user still can use it to access argo cd. This will be fixed by the following PR: https://github.com/argoproj/argo-cd/pull/5477 . The change likely will be cherry-picked into 1.8

**Comment by downvoteit** [comment]
For anyone lost I managed to get it to work with this edits:

### Alter `argocd-cm` configmap

```bash
cat << EOF | kubectl apply -f -
apiVersion: v1
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  dex.config: ""
  url: https://dev.cake
  oidc.config: |
    name: Keycloak
    issuer: "https://dev.cake/realms/dev-apps"
    clientID: argocd
    clientSecret: "\$oidc.keycloak.clientSecret"
    requestedScopes: ["openid", "profile", "email", "groups"]
    logoutURL: "https://dev.cake/realms/dev-apps/protocol/openid-connect/logout?client_id=argocd&id_token_hint={{token}}&post_logout_redirect_uri=https://dev.cake"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argo-cd-1671301561
    meta.helm.sh/release-namespace: argo-cd
  labels:
    app.kubernetes.io/instance: argo-cd-1671301561
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-cd
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-4.3.7
  name: argocd-cm
  namespace: argo-cd
EOF
```

- The key point here is to add `logoutURL: "https://<my host>/realms/<my realm>/protocol/openid-connect/logout?client_id=<my client id>&id_token_hint={{token}}&post_logout_redirect_uri=<my redirect uri>` field into the cm

### Background details

- k3s version v1.25.4+k3s1 (0dc63334)
- Bitnami Keycloak Helm Chart 19.0.3
- Bitnami Helm Chart ArgoCD 4.3.7

**Comment by dellnoantechnp** [comment]
My `keycloak` client:
![image](https://github.com/argoproj/argo-cd/assets/11703403/46f5ef78-ac7e-436f-8df0-772d311e975b)

My argo-cd `argocd-cm` configmap:
![image](https://github.com/argoproj/argo-cd/assets/11703403/ccdecff7-f395-4964-be74-f8007723e980)

it's work. 
  
Thanks all
