### ISSUE TITLE
New helm / git icon is obtrusive to application names on tiles in the UI

### ISSUE THREAD

**Issue by andy-v-h** [argoproj/argo-cd#3794]
# Summary

The new Helm/Git Icon in the application tile is obstructing the view of the rest of the application name which is commonly long for enterprise use cases. ![Screen Shot 2020-06-17 at 6 41 12 PM](https://user-images.githubusercontent.com/5001148/84966552-09f52100-b0cf-11ea-9a64-4b934678415c.png)

I started a thread [here.](https://argoproj.slack.com/archives/CASHNF6MS/p1592440973412500)

# Motivation

I'd like to see the full application name.

# Proposal

Either move it to a place in the tile that is mostly white space now ( the bottom right corner is blank or to the left of the application name in the tile itself) or make it toggle?

**Comment by seanson** [comment]
I think the left is a fairly nice looking option
![argo_test](https://user-images.githubusercontent.com/603619/84968115-1756ed80-b159-11ea-810c-15ea26ff7d82.png)

**Comment by andy-v-h** [comment]
I think so too. I'm trying to set up my first ArgoCD Contrib so I'm getting my local env set up for this

**Comment by igaskin** [comment]
Sorry about this one lads.  I was the one that put the icons in there, so I felt obligated to fix it: https://github.com/argoproj/argo-cd/pull/3808

Please do setup your local dev envs!  Ping me on slack if you need help getting setup, I recently did this and it is somewhat invovled.
