### ISSUE TITLE
[UI] app detail view splits on "-" and does not show branch

### ISSUE THREAD

**Issue by rosscdh** [argoproj/argo-cd#3801]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ui chops the feature branch on "0"

**To Reproduce**

have a branch with a - in its name

**Expected behavior**

full branch is shown

**Screenshots**

![Screenshot 2020-06-18 at 13 18 59](https://user-images.githubusercontent.com/397106/85034297-3c138b00-b182-11ea-8a0f-328c32fdfe8a.png)

**Version**

```shell
argocd version
argocd: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:05:28Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:04:43Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by igaskin** [comment]
thanks for reporting.  I put up a fix in this PR: https://github.com/argoproj/argo-cd/pull/3820

**Comment by alexmt** [comment]
Fixed. Thank you @igaskin !

**Comment by rosscdh** [comment]
Thanks for the fix!
