### ISSUE TITLE
Cluster install interferes with namespace install on same k8s cluster

### ISSUE THREAD

**Issue by idsvandermolen** [argoproj/argo-cd#3830]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

we would like to setup a cluster-level argocd install, with cluster-wide RBAC permissions (to manage namespaces, clusterroles, rbac etc) and a per-namespace install with permissions limited to that namespace (so teams could manage their own namespace).
We setup the cluster install using the https://github.com/argoproj/argo-cd/tree/master/manifests/cluster-install manifests and were using the https://github.com/argoproj/argo-cd/tree/master/manifests/namespace-install manifests for a namespace install. Both were running in the same cluster. In our git repos we also added an `Application`, so the cluster-install could manage itself. The cluster install functioned correctly, however the namespace install was complaining it couldn't access all kinds of cluster-level resources.
When I added a rolebinding to allow the namespace install to read cluster level resources, the cluster-based install completely disappeared.

It would be really nice if the documentation could describe how to setup a more-or-less multi-tenant installation, where you would have a cluster-wide argocd install to manage cluster-wide resources and a per-namespace install to delegate managing namespace resources to separate teams. Of course this also implies the namespace install should not have write-access to resources outside of its namespace.

**Version**
`1.6.0`

```shell
argocd: v1.6.0+c10ae24
  BuildDate: 2020-06-16T22:41:56Z
  GitCommit: c10ae246ab02f1356147118a1979fedcd1ceb704
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.6.0+c10ae24
  BuildDate: 2020-06-16T22:40:56Z
  GitCommit: c10ae246ab02f1356147118a1979fedcd1ceb704
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Comment by jgwest** [comment]
Closing as multitenancy on Argo CD has improved significantly since this was written (see 'in any namespace' features), and the specific bug (both cluster and namespace scoped instances) that is written for is not a supported scenario.
