### ISSUE TITLE
Sync Window status in argocd CLI is not matched with argocd UI for same sync window

### ISSUE THREAD

**Issue by Rami-Y** [argoproj/argo-cd#3831]
**Describe the bug**
ArgoCD UI is using UTC time and CLI is using local time in sync windows. Due to this, there is a descrepeny on sync window status information between UI and CLI for the sync window.
Example, the status of sync window is displayed as Sync Allowed in CLI when the "Deny Sync Window" is active in ArgoCD UI.

**Steps to reproduce**
1. create a sync window like deny:0 18 * * *:1h in UI
Note: my local time is 14:13 EST which is 18:13 UTC. So, the status of deny sync window shows up active in argo cd UI as UI uses UTC time.
![image](https://user-images.githubusercontent.com/67324739/85411334-35946300-b536-11ea-9a3f-32390a3c864d.png)

2. check the status in argo cd cli using cli command argocd app get APPNAME.
![image](https://user-images.githubusercontent.com/67324739/85414843-9e7dda00-b53a-11ea-9c9a-568048d48753.png)

the status in CLI was displyed as sync allowed instead of sync denied.

**Expected behavior**

Status of a Sync window should be same and match in both UI an CLI.

**Version**
argocd: v1.5.1+8a3b36b

**Comment by jannfis** [comment]
I think this could be solved by implementing #3204
