### ISSUE TITLE
Namespace-only permissions for App deployment

### ISSUE THREAD

**Issue by Unb9rn** [argoproj/argo-cd#3838]
# Summary

It would be great if namespace-deployed argocd could deploy apps in the same namespace it was deployed to. According to [docs](https://argoproj.github.io/argo-cd/operator-manual/security/#cluster-rbac) argocd requires clusterrole with read privileges to do anything on cluster

# Motivation

When deploying applications in isolated environments Argocd is a really useful tool, but it seems to be impossible to use it when you have unlimited permissions on a single namespace.

# Proposal

Why do we need to know what is deployed in another namespaces in the first place? Maybe it's possible to limit cluster permissions to CRDs or something?

**Comment by raelga** [comment]
You can limit argo to a set of namespaces using the `--namespaces` flag. 

Check https://github.com/argoproj/argo-cd/pull/3992.

**Comment by Unb9rn** [comment]
@raelga The secret in documentation contains stringData. I think this means that the value of "namespaces" should be comma separated namespaces? But the doc says it should be a list. Maybe an example would clarify this.

**Comment by raelga** [comment]
Hello @Unb9rn, that's correct is a list of coma separated values. I created this issue to add it to the documentation:

https://github.com/argoproj/argo-cd/pull/4237

**Comment by raelga** [comment]
@Unb9rn merged and published!
