### ISSUE TITLE
Issue with Submodules and ArgoCD 1.5.3

### ISSUE THREAD

**Issue by RR90** [argoproj/argo-cd#3845]
I have an issue with submodules since I upgraded my ArgoCD server from 1.3 to 1.5.3.

I want to deploy an app using manifests defined in one repo that has a second repo as a Submodule.

I don't need that ArgoCD tries to clone the submodule when executing ArgoCD commmands from the CLI. It is a behaviour added from ArgoCD v1.4 (Submodules are now supported and will be picked up automatically. 1).

I tried setting the environment variable ARGOCD_GIT_MODULES_ENABLED=false, however I still see the error that argocd tried to check out the submodule and was denied access.

Has anyone encountered the same issue and successfully deactivated this new behaviour?

Thank you in advance,

**Comment by jannfis** [comment]
Hi @RR90, you need to set this environment variable for the `argocd-repo-server` pod, not in your shell.
