### ISSUE TITLE
Error when adding a git repo: Unable to connect SSH repository: Gateway Timeout

### ISSUE THREAD

**Issue by papanito** [argoproj/argo-cd#3855]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am unable to add/use a git repo. When I try to add a **public git repo in the UI** I get an `Unable to connect SSH repository: Gateway Timeout` error after a while. I still can create them though put it does not work as the path field is not populated

I can see the repos fine with `argocd-cli`

```bash
argocd repo list
TYPE  NAME  REPO                                            INSECURE  LFS    CREDS  STATUS      MESSAGE
git         https://gitlab.com/papanito/k8s.git             false     false  false  Successful  
git         https://gitlab.com/papanito/packer-vagrant.git  false     false  false  Successful  
```
However, I also cannot add a **private repo in the UI** as I get the same error as mentioned above. Trying to do the same via cli ends up with this error

```bash
$ argocd repo add git@gitlab.com:papanito/infrastructure --ssh-private-key-path=argocd.gitlab_rsa --grpc-web
FATA[0060] rpc error: code = Unknown desc = unexpected EOF 
``` 

I don't see anything in the logs from the pods

**To Reproduce**

See bug description

**Expected behavior**

I expect that the

**Screenshots**

![Screenshot from 2020-06-26 07-27-39](https://user-images.githubusercontent.com/15034009/85824026-1ccabe00-b77f-11ea-930f-8b54add7f252.png)

**Version**

```shell
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:39:46Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Logs**

As mentioned above all I see in the `argpcd-repo-server` is this:

```
ubectl -n argocd logs argocd-repo-server-69b575b5b4-7hwhq -f
time="2020-06-25T07:07:55Z" level=info msg="argocd-repo-server v1.6.1+159674e serving on [::]:8081"
time="2020-06-25T07:17:55Z" level=info msg="Alloc=3085 TotalAlloc=16505 Sys=72528 NumGC=10 Goroutines=8"
...
```

**Additional Info**

Connection to gitlab from pod seems fine

```bash
kubectl run -i -t multitool -n argocd --image=praqma/network-multitool --restart=Never /bin/bash
If you don't see a command prompt, try pressing enter.
bash-5.0# nslookup gitlab.com
Server:		10.43.0.10
Address:	10.43.0.10#53
Non-authoritative answer:
Name:	gitlab.com
Address: 172.65.251.78
Name:	gitlab.com
Address: 2606:4700:90:0:f22e:fbec:5bed:a9b9
bash-5.0# curl https://gitlab.com
<html><body>You are being <a href="https://about.gitlab.com/">redirected</a>.</body></html>bash-5.0# 
```
and I can clone from within repo server

```bash
argocd@argocd-repo-server-69b575b5b4-7hwhq:~$ git clone https://gitlab.com/papanito/k8s.git
Cloning into 'k8s'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 13 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (13/13), done.
```

[Conversation in slack](https://argoproj.slack.com/archives/CASHNF6MS/p1593075603162300)

**Comment by papanito** [comment]
I can rule out argocd issue. It has something to do with my setup. I'm using cloudflare to proxy the dns requests and also using it's load balancer.

**Comment by plpetkov-tech** [comment]
How did you fix it, I have the same issue and I also have argo behind an ingressroute with lb and cloudflare :D

**Comment by AceHack** [comment]
Having the same issue
