### ISSUE TITLE
Argo CD server: serve CLI binaries checksums

### ISSUE THREAD

**Issue by yann-soubeyrand** [argoproj/argo-cd#3860]
# Summary

CLI binaries can be downloaded directly from Argo CD server. It could be great if the checksums could also be downloaded from here so that integrity of the downloaded binaries could be checked.

# Motivation

In our CI, we download the CLI binary from Argo CD server so that we always use the right version. We'd like to check the integrity of the downloaded binary.

# Proposal

A new endpoint (/sha256sums.txt) could be added alongside the endpoints serving CLI binaries which would serve a file containing SHA256 sums of the binaries. These checksums could be computed during server startup.

**Comment by sbose78** [comment]
Thank you, have you considered making a PR from https://github.com/camptocamp/argo-cd/commit/43ce74d0e71b216e2ec625435f1b3aa7bf9f5d4c ?

**Comment by yann-soubeyrand** [comment]
> Thank you, have you considered making a PR from [camptocamp@43ce74d](https://github.com/camptocamp/argo-cd/commit/43ce74d0e71b216e2ec625435f1b3aa7bf9f5d4c) ?

Sure: https://github.com/argoproj/argo-cd/pull/3861 ;-)

**Comment by sbose78** [comment]
Hey, thank you @yann-soubeyrand . 
Glad that your PR has to led to a good discussion on where things stand from a release payload perspective as well.
