### ISSUE TITLE
Can't use Azure Container Registry as HELM Repo

### ISSUE THREAD

**Issue by patrickheinzelmann** [argoproj/argo-cd#3865]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We're using Azure Container Registry (ACR) as HELM Repo and we tried to load the integrate it with Argo CD.

When I try to create an application in Argo CD using published chart which was published below xxxxx.azurecr.io/project/service 

If we try to use the published Helm Charts from ACR, the creation of the application fails as Argo CD can't load the dependencies.

As OCI isn't currently supported, I tried to use the HELM2 version of Azure Container Registry to load our helm charts with argo. I created a HTTPS HELM Repo with ACR Login URL: xxxxx.azurecr.io/helm/v1/repo. #3349 

During the creation of the application, we've following error message.
`
Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in development: rpc error: code = Unknown desc = `helm2 dependency build` failed exit status 1: Error: no repository definition for xxxxx..azurecr.io/project. Please add them via 'helm repo add' Note that repositories must be URLs or aliases. For example, to refer to the stable repository, use "https://kubernetes-charts.storage.googleapis.com/" or "@stable" instead of "stable". Don't forget to add the repo, too ('helm repo add').
`
**To Reproduce**

1. Create Container Registry in Azure
2. Follow https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/container-registry/container-registry-helm-repos.md the guide and publish our Helm Chart to Azure Container Registry.
3. Create a service principal to login into Azure Container Registry. https://docs.microsoft.com/de-de/azure/container-registry/container-registry-auth-service-principal
4. Create Helm Repository in Argo CD using the url xxxxx.azurecr.io/helm/v1/repo and the credentials of the service principal of step 3.
5. Create a Git Repo with your Helm info (Chart.yaml, requirements.yaml, values.yaml). The requirements should reference the chart published to Azure Container Registry: xxxxx.azurecr.io/project/service
6. Create an application in Argo CD using the GIT Repo containing the values.yaml for HELM.

**Expected behavior**

Argo CD can load the chart from Azur Container Registry.

**Version**

```shell
argocd: v1.6.0+c10ae24
  BuildDate: 2020-06-16T22:41:56Z
  GitCommit: c10ae246ab02f1356147118a1979fedcd1ceb704
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Comment by patrickheinzelmann** [comment]
Solved!

**Comment by jeffcollaboro** [comment]
@patrickheinzelmann Appologies for necroposting, I've found myself in this position and noted that this is closed without resolution. I wonder if you would mind sharing.
