### ISSUE TITLE
Is argocd support `helm install`

### ISSUE THREAD

**Issue by yaphetsglhf** [argoproj/argo-cd#3867]
# Summary
As mentioned in title, I can't find way to install helm charts like `helm  install`. (No helm release found.)

# Motivation
As we use `helm install` before, integrated with our pipeline,  we want to unify our "cd" mode, both automatically and manually  in case of emergencies.

# Proposal
support `helm install` command optional.

Or if i missed something? thanks for help.

**Comment by daurnimator** [comment]
Did you create an application that points at a helm chart?

see the helm examples in https://github.com/argoproj/argocd-example-apps

**Comment by yaphetsglhf** [comment]
> Did you create an application that points at a helm chart?
> 
> see the helm examples in https://github.com/argoproj/argocd-example-apps

if we use `helm install`, we'll see helm releases typing in `helm ls`, but If i use argocd, no releases found. It seems like `kubectl apply <manifests>`.

**Comment by TPX01** [comment]
> > Did you create an application that points at a helm chart?
> > see the helm examples in https://github.com/argoproj/argocd-example-apps
> 
> if we use `helm install`, we'll see helm releases typing in `helm ls`, but If i use argocd, no releases found. It seems like `kubectl apply <manifests>`.

Based on what I've seen/learned so far:
This is due to the way the plugin is configured. What ArgoCD does (not like the Flux Helm Operator) is basically generating all manifests within the helm chart and apply those. The nice thing of this approach is that you can for example "patch" resources in an open source chart with kustomize but you cannot use "helm ls" as the individual resources have been installed and not a helm chart.

**Comment by turbotankist** [comment]
if argocd would use "helm install", I will stop to use it. 
Now it is works like this: "helm template release | kubectl apply -f - " 
and this is good!

**Comment by yaphetsglhf** [comment]
well, our team were used to use `skaffold` in cd pipeline, which supports helm release install, so at first we want to combine these two tools together. Close the issue since different architecture.

**Comment by abdennour** [comment]
so this means that argo-cd hides helm behind the scenes.
Let's say argocd is broken, i want to jump to cluster and use helm command line ?!
What the solution now ?

**Comment by abdennour** [comment]
This is a critical issue BTW !

Seems like Argo uses Helm as generator of YAML manifests only thru `helm template`.
Please be advised that `helm template` is not aware about the server side namely if your helm chart has some conditions based on the existence of API Versions Capabilities.

Similar GH issues: 

- https://github.com/helm/helm/issues/3377
- https://github.com/argoproj/argo-cd/issues/3631
-  https://github.com/databus23/helm-diff/issues/165

**Comment by OmerKahani** [comment]
> This is a critical issue BTW !
> 
> Seems like Argo uses Helm as generator of YAML manifests only thru `helm template`.
> Please be advised that `helm template` is not aware about the server side namely if your helm chart has some conditions based on the existence of API Versions Capabilities.
> 
> Similar GH issues:
> 
>     * [helm/helm#3377](https://github.com/helm/helm/issues/3377)
> 
>     * #3631
> 
>     * [databus23/helm-diff#165](https://github.com/databus23/helm-diff/issues/165)

I think #1251 solve the capability problem

**Comment by gioppoluca** [comment]
Is this definitive or there is tha change to have Argo behave like `helm install`?
