### ISSUE TITLE
sync local changes with argocd not working as expected

### ISSUE THREAD

**Issue by syedimranhassan** [argoproj/argo-cd#3876]
Hi all,

I have tried to sync argocd locally using this command.
`argocd app sync <app-name> --local <app-dir>`
But running this will sync it to the remote branch and not my local changes. 
And if we specify our local branch in yaml file and that branch will not be in the remote repo it will through error
`Unable to resolve 'branch/local' to a commit SHA`

argocd version
`argocd: v1.4.0+2d02948
  BuildDate: 2020-01-18T05:55:41Z
  GitCommit: 2d029488aba6e5ad48b2a756bfcf43d5cb7abcee
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.0+1b7f4b6
  BuildDate: 2020-01-23T00:03:25Z
  GitCommit: 1b7f4b6f9664ced983e63b46bde35f02f85ccb77
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0`

kustomize version
`{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-17T14:28:58+00:00 GoOs:darwin GoArch:amd64}`

kubctl version
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

Helm version

> `Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}`

**Comment by xvzf** [comment]
Argocd local syncing just takes the folder you are in and does not respect anything git branch related. Maybe that is the issue?

**Comment by syedimranhassan** [comment]
Thanks for replying.
Yeah, argocd syncs to the folder. But like I have updated a port in yaml and sync it locally. It will not be updated in svc. But if we sync the app with the remote branch it will be updated everywhere.

**Comment by iam-veeramalla** [comment]
@syedimranhassan 

>But running this will sync it to the remote branch and not my local changes.
And if we specify our local branch in yaml file and that branch will not be in the remote repo it will through error
I was looking into your issue description and I think you have misunderstood the flag `--local`.

Please find the usage below. It has nothing to do with local or remote branches as using `--local` tag does not query any git server.
`--local string`           ->              `Path to a local directory. When this flag is present no git queries will be made`.
