### ISSUE TITLE
When running in Autosync, syncing takes forever. Proposal to autosync selective only out of sync items

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#3877]
# Summary

We need to speed up syncing, sometimes it takes hours before syncing is ready. We found that a 'normal' sync applies to all items, also the synced items. This takes much time. When we do a selective sync for all 'out-of-sync' items it is ready in seconds.  We like to have an option in the automatic sync to filter all out of sync items. The same as in the UI like here: 
![image](https://user-images.githubusercontent.com/9946020/86143953-5be96e00-baf5-11ea-9207-d6a96a90eef8.png)

# Motivation

We cannot use the autosync right now because the apps stay in syncing state. 

# Proposal

extend the autosync with an option to use selective sync: 'out-of-sync'

**Comment by wmcnamee-tunein** [comment]
I'm curious to know why the syncing takes so long. What does CPU/Memory usage of ArgoCD look like during a sync?

**Comment by ghostsquad** [comment]
I'm curious to know why the syncing takes so long. What does CPU/Memory usage of ArgoCD look like during a sync?

**Comment by peterbosalliandercom** [comment]
We have a lot of resources sub helm charts etc

**Comment by peterbosalliandercom** [comment]
We use argo to deploy multiple namespaces with resources in one time.

**Comment by kshamajain99** [comment]
Looking into this.

**Comment by Smirl** [comment]
Hey @kshamajain99, Any update on this? Any guidance on an open source PR? Our syncs are taking hours to complete now when we only add/update/remove a couple of objects per commit. In our case we have a chart that deploys tenant namespaces, RBAC, resource quotas, etc. as mentioned in https://github.com/argoproj/argo-cd/issues/4521

**Comment by ghostsquad** [comment]
It would nice to have some more debug information on this, like what is it doing that causes it to take so long? (this is a message to the maintainers). Would debug level logging be enough to get this information?

**Comment by kshamajain99** [comment]
@Smirl I am currently working on this issue, you can expect an PR soon in a day or two.

**Comment by alexmt** [comment]
Implemented. Thank you @kshamajain99 !

**Comment by peterbosalliandercom** [comment]
@kshamajain99 Is this option influencing the post sync hooks?

**Comment by Smirl** [comment]
Do you have a timeline/milestone for when this will be release? I don't see it in the 1.9 milestone. It would save hours of each sync for us when it is out.

**Comment by kshamajain99** [comment]
@Smirl This issue is in 1.9 milestone. It will be released in a week or two.

**Comment by Cyben** [comment]
Hey, is there a reason this configuration is not set by default? What would be the reason to sync all resources even when they are already synced?
Is there an available configuration to set `ApplyOutOfSyncOnly` to true in the configuration?
