### ISSUE TITLE
Argo CD - Permission denied error while doing argo sync

### ISSUE THREAD

**Issue by dharmaanu12** [argoproj/argo-cd#3887]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

While doing argo sync, getting this error - 
level=fatal msg="rpc error: code = PermissionDenied desc = permission denied: applications, create,``

**To Reproduce**
App in argo to be synced
**Expected behavior**

no error

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by sunshine69** [comment]
I hit the problems as well. Just some time ago when I first install it it works and today stop working.

**Comment by PabloAlexis611** [comment]
App creation works, but sync fails with: `FATA[0001] rpc error: code = PermissionDenied desc = permission denied` while logged in through the ArgoCD CLI when executing `argo app sync --local`
