### ISSUE TITLE
An application based on a helm repository does not allow wildcards in its "version field" even though it should

### ISSUE THREAD

**Issue by bjoernw** [argoproj/argo-cd#3905]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

Argo-CD version: v1.5.4+36bade7

**Describe the bug**

When adding an application with a helm source repository the version tooltip suggests that you can use wildcards in the version but the UI will not allow you to pass wildcards and will complain with:

```
Unable to save changes: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = invalid constraint in index: Invalid Semantic Version
```

**To Reproduce**

Add a helm repository, then add an application that uses that repo and try to pass a version mask like `1.*`
**Expected behavior**

I would expect a successful submission and subsequent OutOfSync notices when a newer version is available.

**Screenshots**

<img width="202" alt="Screen Shot 2020-07-01 at 1 58 22 PM" src="https://user-images.githubusercontent.com/1467156/86645477-49f34980-bf93-11ea-9c32-54af37ed8e1c.png">

**Comment by bjoernw** [comment]
Relevant slack convo:

```
**jesse:argo:  5 days ago**
Pinning it to a sem version like 0.0.28 implies you want a very specific version, and also that theres will never be a difference in the resulting manifests (unless you change a value). So by definition, it wont notice 0.0.29.
This is what the 0.0.* feature was supposed to support, but I think you exposed a bug.

**jesse:argo:  5 days ago**
Could you file one?
```

**Comment by msonnleitner** [comment]
I am evaluating ArgoCD and have encountered that issue. Given that this issue has not received much attention, is this an unusual thing to do?

**Comment by alexmt** [comment]
I think help text is incorrect. Semver uses `x` instead of `*`. Prepared PR to fix it: https://github.com/argoproj/argo-cd/pull/4976
