### ISSUE TITLE
Updating the Documentation

### ISSUE THREAD

**Issue by yuzujoe** [argoproj/argo-cd#3907]
# Summary
Currently, the argocd documentation only includes an introduction to secret management
Many people are currently having trouble figuring out how to use this information alone (I'm one of them).

# Motivation
To avoid ending up with only a cursory introduction.

# Proposal
I think we need to create and provide an example for use as a sample?

A simple sample will help the developer to avoid confusion (especially with regard to the secret. serverkey is especially important).

**Comment by james-callahan** [comment]
If you click through to e.g. the KSOPS link it has docs and examples for that secret management (https://github.com/viaduct-ai/kustomize-sops#argo-cd-integration-)
Why would it be better to keep those docs in this repository (where they may get out of date) when a link suffices?

**Comment by jgwest** [comment]
See comment and docs have improved since the original post.
