### ISSUE TITLE
Deploying nested Application from helm chart gives "namespace argocd is not permitted in project xxxx"

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#3913]
With argocd 1.6.1 we try to create a nested resource "Application" in project xxx but get error 'namespace argocd is not permitted in project'

**Describe the bug**

When adding the following Application yaml via helm chart it gives "namespace argocd is not permitted in project xxxx" error.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xxxx
  namespace: argocd
spec:
  destination:
    namespace: xx-xx-dev
    server: 'https://kubernetes.default.svc'
  project: xxx-xxx
  source:
    helm:
      valueFiles:
        - values.yaml
    path: apps/neo4j
    repoURL: 'git@xxx.git'
    targetRevision: HEAD
```

**To Reproduce**
Via argocd UI via new App wizard:
1. create helm chart with above application as yaml in the template folder
2. add helm chart as new App via UI wizard.
3. Error occurs on Application sync of nested Application. ("namespace argocd is not permitted in project xxxx")
4. If I put the above yaml then manually via the argocd UI new app and paste as yaml it works fine.

Project permissions are:
````
  destinations:
    - namespace: xx-xx-dev
      server: https://kubernetes.default.svc
````

It looks to me that rbac of the project when using nested Applications is not working correctly

**Expected behavior**

It should deploy the Application in the argocd namespace with destination namespace xx-xx-dev

**Screenshots**

![image](https://user-images.githubusercontent.com/9946020/86775928-14fcfa80-c058-11ea-83fd-2b22caefc1b4.png)

**Version**

1.6.1

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ErikLundJensen** [comment]
In Argo CD 1.5.x you had to add namespace "argocd" to project destinations. Do you expect another functionality in 1.6 ?

**Comment by peterbosalliandercom** [comment]
That's not the issue here. Please follow reproduction senario.

**Comment by ErikLundJensen** [comment]
When you create the application using the UI then the argoproj.io/v1alpha1 Application is always created in the argocd namespace.
When putting the application into a helm chart then Argo CD does not know that it is creating an argo application. It is just Helm that renders the template and objects are created. As destination namespace is only "xx-xx-dev" then Argo CD will not let Helm can't create objects in namespace "argocd"

This is therefore not a bug. Actually it would be a security risk if any project/chart could create objects in the argocd namespace as any chart then could create new applications in any project in your environment.

**Comment by peterbosalliandercom** [comment]
I understand this perfectly, so it is not a bug, maybe a feature than. we want to use multiple layers of nesting argo apps within a helmchart which is nested in another helm chart how do we go about that in the future? We cannot manually apply all these. There should be some sort of authentication  / authorization possible to automate this in a secure manner right?

**Comment by ErikLundJensen** [comment]
If you are using restricted destinations in argo projects then you need to add the argocd namespace to the allowed destinations.
Specify "namespace: argocd" in all you argo "application" manifests -- including the argo applications in the helm charts.
Thereby the helm can create argo applications in the argocd namespace.

**Comment by peterbosalliandercom** [comment]
Yes I understand that, the problem then is that people can create resources in the argocd namespace and overwrite other resources which do not belong to their project

**Comment by ErikLundJensen** [comment]
Correct, that is why "namespaced" Argo CD installation is getting a lot of attention for OpenShift 4 installations. In namespaced setup you install Argo CD in a custom namespace. You will have to setup RBAC and Argo CD ConfigMap with ressources to monitor and permissions to modify objects in other namespaces.
I have a setup of namespaced Argo CD at OpenShift 4 if that matches your requirements.

**Comment by peterbosalliandercom** [comment]
I was hoping that one argocd with rbac would make this possible. With the namespaced setup one must support all the argocd instances. it can quickly add up with a lot of namespaces and teams....We would need 30 argo installs then....

**Comment by ErikLundJensen** [comment]
The Kubernetes RBAC only looks at the object kind. It does not look into the fields of the object. Kubernetes RBAC cannot be used to distinguish between argo application with different value of e.g. project.
Please have a look at issue #3474 which will solve your issues. I hereby suggest that this bug is closed.

**Comment by peterbosalliandercom** [comment]
I will follow rfe.

**Comment by elmariofredo** [comment]
I had similar issue and all I needed was to explicitly allow all resources under project setup

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
...
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
```

**Comment by robozb** [comment]
Thanks a lot, It solved my problem! (The sync was failed with namespace creation problem)

> I had similar issue and all I needed was to explicitly allow all resources under project setup
> 
> ```
> apiVersion: argoproj.io/v1alpha1
> kind: AppProject
> ...
> spec:
>   clusterResourceWhitelist:
>     - group: '*'
>       kind: '*'
> ```

**Comment by crenshaw-dev** [comment]
For people who arrive here via search: start by just enabling namespaces, and add resources as necessary. 

```yaml
spec:
  clusterResourceWhitelist:
    - group: ''
      kind: 'Namespace'
```

**Comment by mukundparmar** [comment]
> For people who arrive here via search: start by just enabling namespaces, and add resources as necessary.
> 
> ```yaml
> spec:
>   clusterResourceWhitelist:
>     - group: ''
>       kind: 'Namespace'
> ```

This worked thanks for the update.
