### ISSUE TITLE
***periodically*** receiving rpc error: code = Internal desc = transport: received the unexpected content-type "text/html

### ISSUE THREAD

**Issue by gbates101** [argoproj/argo-cd#3916]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Background**
- We have argo server running with the `--insecure` flag specified
    - Our ingress supports HTTP/2, but we don't want to terminate SSL at argo. None of our other apps do this, and it would be costly to create a new ingress setup just for accessing argo.
- Our Jenkins server uses an auth token to access argo via grpc ingress.
- Jenkins is running as a pod in the same cluster as argo
- The apps being interacted with by Jenkins in the examples below are in an external cluster
    - I suspect this one isn't relevant since interacting with in-cluster apps also reproduces this issue occasionally.
- We have used grpc ingress and also `--grpc-web` flag, in Jenkinsfile and from local machine, with and without `--insecure` flag. Still periodically get this error.

**Describe the bug**
The `argocd` CLI periodically fails to complete a call to RPC:
```asciitext
time="2020-07-08T17:20:57Z" level=fatal msg="rpc error: code = Internal desc = transport: received the unexpected content-type \"text/html\""
```

Here's a good example of the periodicity (snipped from one of our Jenkins builds running a bash script):
```
# Error below caused from this command:
# CURRENT_VERSION=$(argocd app get $ARGO_APP | grep Target: | tr -s [:blank:] | cut -d" " -f2)
time="2020-07-08T17:20:56Z" level=fatal msg="rpc error: code = Internal desc = transport: received the unexpected content-type \"text/html\""
Current chart version in Argo: 
/usr/local/bin/semver: line 64: [: : integer expression expected
/usr/local/bin/semver: line 68: [: : integer expression expected
Bringing chart up-to-date in Argo.
+ argocd app set beta-app --revision=1.3.2
+ argocd app set beta-app -p spec.image="gcr.io/build/app:beta-202006-47"
time="2020-07-08T17:20:57Z" level=fatal msg="rpc error: code = Internal desc = transport: received the unexpected content-type \"text/html\""
An unexpected exception was thrown
```

The command `argocd app set beta-app --revision=1.3.2` succeeded, despite the surrounding `argocd` commands failing.

Here's a subsequent run (three builds later) with different behavior:
```asciitext
# Error below caused from this command:
# CURRENT_VERSION=$(argocd app get $ARGO_APP | grep Target: | tr -s [:blank:] | cut -d" " -f2)
time="2020-07-08T17:59:36Z" level=fatal msg="rpc error: code = Internal desc = transport: received the unexpected content-type \"text/html\""
/usr/local/bin/semver: line 64: [: : integer expression expected
/usr/local/bin/semver: line 68: [: : integer expression expected
beta-app release is out-of-date (current: , latest: 1.3.2). Updating now.
+ argocd app set beta-app --revision=1.3.2
time="2020-07-08T17:59:36Z" level=fatal msg="rpc error: code = Internal desc = transport: received the unexpected content-type \"text/html\""
+ argocd app set beta-app spec.image="gcr.io/build/app:beta-202006-50"
```
Note that the image parameter was set without error, though the previous calls all failed.

Here's an example running `argocd version` repeatedly from my localhost (logged in via GitHub SSO):

```shell
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0
(base) gbates@Work /c/Projects/Tartan $ argocd version
FATA[0000] rpc error: code = Internal desc = transport: received the unexpected content-type "text/html" 
(base) gbates@Work /c/Projects/Tartan $ argocd version
argocd: v1.5.0+bdda410
  BuildDate: 2020-04-02T16:35:16Z
  GitCommit: bdda41046378a855e289b5f1602d5c923a3f914a
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.0+bdda410
  BuildDate: 2020-04-02T16:38:24Z
  GitCommit: bdda41046378a855e289b5f1602d5c923a3f914a
  GitTreeState: clean
  GoVersion: go1.14
```

**To Reproduce**

It's tricky to reproduce, and all of our helm/git repos are private. It's only happening sometimes as detailed above.

**Expected behavior**

Consistent completion of requests.

**Version**

```shell
argocd: v1.5.0+bdda410
  BuildDate: 2020-04-02T16:35:16Z
  GitCommit: bdda41046378a855e289b5f1602d5c923a3f914a
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.0+bdda410
  BuildDate: 2020-04-02T16:38:24Z
  GitCommit: bdda41046378a855e289b5f1602d5c923a3f914a
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0

```

**Logs**

These failures act as if the server was never hit, so the failures are never logged server-side.

**Comment by thirdeyenick** [comment]
Could it be that this is the [same issue](https://github.com/argoproj/argo-cd/issues/3896) which we experienced as well?. I think the current documented ingress solution (2 separate ingresses) does not 100% work if you are using nginx-ingress controller.

**Comment by gbates101** [comment]
@thirdeyenick Yep, that's most definitely the issue we're running into. We run in GKE, so I worked around it by converting the argocd-server service to a LoadBalancer type and adding our certs to `argocd-secret` so I can drop the `--insecure` flag, which bypasses the nginx ingress controller entirely. Would've preferred not adding another LB, but seems like its the only way to run without the `--insecure` flag on HTTP2.

I'll close this issue in favor of #3896 since I've effectively duplicated your report.
