### ISSUE TITLE
make start failed with multiple errors

### ISSUE THREAD

**Issue by taisho6339** [argoproj/argo-cd#3921]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Whenever I run ```make start```, dex, repo-server, api-server and controller won't be start.

**To Reproduce**
A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

- clone this repository
- ```make test-tools-image```
- ```make build``` & ```make dep-ui```
- run ```make start```

In addition, my local environment is as below.
- minikube version: v1.9.2
- client docker engine version: 19.03.8
- server docker engine version: 19.03.8
- os: Mac OSX Catalina 10.15.5
- kubectl version
```
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-dispatcher", GitCommit:"f2a77f678d6baccda27740d700f6cba2754dfacf", GitTreeState:"clean", BuildDate:"2020-04-21T04:44:03Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- I tried to build & start with virtual tool chain. 
- Result of ```make verify-kube-connect```
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Expected behavior**

- Whenever I run ```make start```, dex, repo-server, api-server and controller will be start.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
Sorry, argocd server wont' be start so this command always fails.

**Logs**

```
07:11:05         dex | FATA[0000] configmap "argocd-cm" not found
07:11:05         dex | exit status 20
07:11:05         dex | Terminating dex
07:11:06 repo-server | INFO[0000] Initializing GnuPG keyring at /app/config/gpg/keys
07:11:06 repo-server | FATA[0000] stat /app/config/gpg/keys: no such file or directory
07:11:06 repo-server | exit status 20
07:11:06 repo-server | Terminating repo-server
07:11:06  controller | INFO[0000] appResyncPeriod=3m0s
07:11:06  controller | INFO[0000] Application Controller (version: v99.99.99+unknown, built: 1970-01-01T00:00:00Z) starting (namespace: argocd)
07:11:06  controller | INFO[0000] Starting configmap/secret informers
07:11:06  controller | E0710 07:11:06.325779     675 reflector.go:123] github.com/argoproj/argo-cd/controller/appcontroller.go:416: Failed to list *v1alpha1.Application: the server could not find the requested resource (get applications.argoproj.io)
07:11:06  controller | E0710 07:11:06.326322     675 reflector.go:123] github.com/argoproj/argo-cd/controller/appcontroller.go:417: Failed to list *v1alpha1.AppProject: the server could not find the requested resource (get appprojects.argoproj.io)
07:11:06  controller | INFO[0000] Configmap/secret informer synced
07:11:06  controller | FATA[0000] configmap "argocd-cm" not found
07:11:06  controller | exit status 20
07:11:06  controller | Terminating controller
07:11:07  api-server | INFO[0000] Starting configmap/secret informers
07:11:07  api-server | INFO[0000] Configmap/secret informer synced
07:11:07  api-server | FATA[0000] configmap "argocd-cm" not found
07:11:07  api-server | exit status 20
07:11:07  api-server | Terminating api-server
```

**Comment by jannfis** [comment]
Hi @taisho6339, before doing a `make start` you need to set-up some ArgoCD related things in your cluster. I'd recommend to push the installation manifests into the `argocd` namespace and afterwards scale down all deployments to 0. Alternatively, you can install CRDs, secrets and config maps manually.

I agree that this is not well documented.

**Comment by taisho6339** [comment]
Hi @jannfis Thank you so much!
I've been able to start servers successfully.

May I add that tips to the Contribution FAQ?

**Comment by jannfis** [comment]
> May I add that tips to the Contribution FAQ?

Sure, that would be much appreciated! Thank you for this offer!

**Comment by taisho6339** [comment]
I'm sorry.
The repo server and dex still won't start.
It looks the Procfile in test/container directory is a bit wrong.
It needs to pass ARGOCD_GNUPGHOME env to repo server.
At least now the repo server is working in my local environment.
