### ISSUE TITLE
Integration of Argo CD with Service Now

### ISSUE THREAD

**Issue by opensourceonly** [argoproj/argo-cd#3927]
# Summary

What change you think needs making ?
Some of the events occurred in Argo CD such as deletion of application, sync issues. deletion or project needs to be able to create incidents in Service Now using the APIs available from Service Now.

# Motivation

When an application is deleted due to a commit that was not intended to happen

Sync Issue occurs due to a bad commit in Git Repo

**Comment by ghostsquad** [comment]
Generally, if events could be published about the things that happen, that should solve this problem. Personally, I'd use Argo Workflows and Argo Events

**Comment by jannfis** [comment]
You could also take a look at [argocd-notifications](https://github.com/argoproj-labs/argocd-notifications) - I think you could easily write an extension for Service Now API.
