### ISSUE TITLE
Add Support for AzureDevops Webhooks

### ISSUE THREAD

**Issue by dustinchilson** [argoproj/argo-cd#3937]
# Summary

Add Support For Azure DevOps WebHooks. 

# Motivation

Github, Bitbucket, etc have support and Azure devops provides similar webhooks. 

https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops

# Proposal

Add Support for the GitPush event,https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#git.push

as seen here, https://github.com/argoproj/argo-cd/blob/95820cf64fe695f0c30eedfc32b6de01a35b851c/util/webhook/webhook.go#L36 and sync associated applications.

**Comment by renardguill** [comment]
Hi !
Have you planned this feature ?

**Comment by ErikLundJensen** [comment]
I have looked a bit into implementing this.
First we are lacking a good parser of Azure Webhook payload written in Go, however, we only need to pick 3 elements from the json payload. Writing a Azure Webhook parser for push-events could be done using dynamic json parsing using "encoding/json".

Mapping of json to variables is as follows:
```weburl``` from ```resource.repository.remoteUrl```
```revision``` from ```resource.refUpdates.name```
The default branch is located in ```resource.repository.defaultBranch```

The parser will also have to handle the basic-auth header if webhook secret has been specified.

Furthermore, there is no HTTP header that indicates that the request is from DevOps git in Azure. Therefore we have to instruct the end-user to insert a specific header into the webhook definition in Azure. For example ```X-Azure-DevOps-Event```

Validation that the ```eventType``` is ```git.push``` could also be validated by the parser.

Finally we need to add a new configuration key for the ```WebHookAzureDevOpsSecret``` and write the documentation for it. (And include the new key in the Helm Chart)

Question is if we should call it ```WebHookAzureDevOpsSecret``` or ```WebHookAzureGitSecret```?

**Comment by jkroepke** [comment]
@ErikLundJensen 

> Question is if we should call it WebHookAzureDevOpsSecret or WebHookAzureGitSecret?

You can do a proposal in form as a Pull Request here and ask this question in form as an own review. Then you have the attention of the correct people who maintain this project.

**Comment by olljanat** [comment]
> Question is if we should call it `WebHookAzureDevOpsSecret` or `WebHookAzureGitSecret`?

Nowadays it most probably should be called for `WebHookAzureReposSecret` https://docs.microsoft.com/en-us/azure/devops/repos/?view=azure-devops

@ErikLundJensen did you made any draft of this one? I maybe be interested to look if I manage implement this (have not really read ArgoCD code yet).

**Comment by ErikLundJensen** [comment]
Sorry for not responding before. I ended up writing a small converter that took Azure DevOps push event and transformed it into GitHub Event. It seamed easier than implementing it all in ArgoCD. The converter runs as a pod and forward the requests to ArgoCD server.

**Comment by crenshaw-dev** [comment]
No updated. I've not yet seen a PR adding this feature.

**Comment by alexmt** [comment]
PR is ready for review https://github.com/argoproj/argo-cd/pull/14969
