### ISSUE TITLE
multi-arch (arm64, amd64) images

### ISSUE THREAD

**Issue by skandragon** [argoproj/argo-cd#3956]
# Summary

Multi-arch image builds

# Motivation

It would be good to have arm64 images as well as the amd64 currently built.  Ideally, use the multi-arch manifest approach so the same tag can refer to either without a special tag name per arch type.

# Proposal

'docker buildx' ...

See https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by crenshaw-dev** [comment]
Done! https://quay.io/repository/argoproj/argocd/manifest/sha256:b6ac16e57a928941c0ddb49c1733d035430afd3f38844d0c6bf6a7718e32aa67
