### ISSUE TITLE
Argo without Cluster Wide Permission possible and is kubernetes inside kubernetes an alternative?

### ISSUE THREAD

**Issue by rsassPwC** [argoproj/argo-cd#3958]
Hi Argo Community,

our team is currently trying to think about the possibilities to install argo into a cluster without cluster wide permissions.

Is there a possibility to install the minimal feature set without the CustomResourceDefinition from Argo?

Has someone also got experience to use the Kubeinception approach (kubernetes inside kubernetes).
I got it already working with kind but I would like to know if someone has experience or documentation regarding possible upcoming problems like scaling etc.

Thanks in advance!

**Comment by iam-veeramalla** [comment]
I hope that is what you are looking for ? @rsassPwC please feel free to re-open the issue if you still face any issue.
