### ISSUE TITLE
Ability to add labels for projects

### ISSUE THREAD

**Issue by eroji** [argoproj/argo-cd#3964]
The current project definition only allows for description. It would be nice to be able to add labels, or something similar in order to store metadata. This would allow more complex integration of ArgoCD using its API and CI/CD pipelines.

**Comment by rachelwang20** [comment]
Closed the above one and open a new one to switch to origin branch - https://github.com/argoproj/argo-cd/pull/4173

**Comment by alexmt** [comment]
implemented by https://github.com/argoproj/argo-cd/pull/4446
