### ISSUE TITLE
rpc error: code = Unknown desc = `helm2 dependency build` failed timeout after 1m30s

### ISSUE THREAD

**Issue by servo1x** [argoproj/argo-cd#3977]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When git calls the webhook to trigger a refresh, we often see these errors:
```
rpc error: code = Unknown desc = `helm2 dependency build` failed timeout after 1m30s`.
```

Our applications end up in an unknown state due to this, we'll see like 40% of applications end up in this state. Are we able to increase the timeout or are there suggested settings we can tweak?

**To Reproduce**

- Monorepo with 100+ applications.
- 100 repo servers deployed.
- Application controller status processors set to 50.
- Application controller operation processors set to 25.
- Repo server timeout seconds set to 300.
- App resync seconds set to 86400.

**Expected behavior**

Retry dependency build or be able to increase the timeout.

**Version**

```shell
argocd: v1.5.6+f46333e
  BuildDate: 2020-06-02T18:40:52Z
  GitCommit: f46333ea82ad2157baffc5a8cf02a86720d4bad4
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
  Kubectl Version: v1.14.0
```

**Logs**

```
rpc error: code = Unknown desc = `helm2 dependency build` failed timeout after 1m30s
```

**Comment by jannfis** [comment]
Hey, you can increase the timeout by setting `ARGOCD_EXEC_TIMEOUT` environment variable to a reasonable duration value (i.e. `240s` - do not forget the unit suffix, otherwise I guess might be interpreted as miliseconds).

Sorry, this is not well (or at all) documented.

**Comment by servo1x** [comment]
That seems to of helped fix things, no longer seeing any timeouts thanks @jannfis!

**Comment by able8** [comment]
We also encounter this error: `helm dependency build` failed timeout after 1m30s
```
ComparisonError
rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed timeout after 1m30s
```

Setting ARGOCD_EXEC_TIMEOUT env fixed this issue.
```
k set env deploy argo-cd-argocd-repo-server ARGOCD_EXEC_TIMEOUT=3m
```

**Comment by mohamedamineghan** [comment]
did you manage to fix it please
