### ISSUE TITLE
Migrate to Homebrew Core

### ISSUE THREAD

**Issue by crunchtime-ali** [argoproj/argo-cd#3978]
# Summary

Migrate the ArgoCD (and Argo) Homebrew formulas from the custom Homebrew tap to homebrew-core

# Motivation

It makes Argo CD even easier to install on MacOS plus the big Homebrew community will co-author necessary changes (e.g. compile for Apple Silicon). Updates will be automated with a GitHub Action

# Proposal

It is already implemented and merged in homebrew-core: https://github.com/Homebrew/homebrew-core/pull/58263#issuecomment-662311877

# PRs:
https://github.com/argoproj/argo-cd/pull/3979
https://github.com/argoproj/homebrew-tap/pull/15

**Comment by jgwest** [comment]
Is this done?
