### ISSUE TITLE
Unable to Connect Repository via SSH

### ISSUE THREAD

**Issue by jajjg** [argoproj/argo-cd#3983]
I am trying to connect a GITHUB repo via SSH.

I have setup a public / private key and have added it to my Github account.
I have authenticated using my github account itself and am able to login successfully.

At the same time I have tried to add a private repo in ArgoCD and after providing all the details I receive the following error:

**Unable to connect SSH repository: permission denied: repositories, create, git@github.com:{{myrepo}}.git**

<img width="1324" alt="Screen Shot 2020-07-22 at 9 43 42 PM" src="https://user-images.githubusercontent.com/13406311/88210032-995c9980-cc64-11ea-8b78-2f160248ce0c.png">

My rbac config is as follows:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, certificates, get, *, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, accounts, get, *, allow
    p, role:readonly, gpgkeys, get, *, allow
    p, role:admin, applications, create, */*, allow
    p, role:admin, applications, update, */*, allow
    p, role:admin, applications, delete, */*, allow
    p, role:admin, applications, sync, */*, allow
    p, role:admin, applications, override, */*, allow
    p, role:admin, applications, action/*, */*, allow
    p, role:admin, certificates, create, *, allow
    p, role:admin, certificates, update, *, allow
    p, role:admin, certificates, delete, *, allow
    p, role:admin, clusters, create, *, allow
    p, role:admin, clusters, update, *, allow
    p, role:admin, clusters, delete, *, allow
    p, role:admin, repositories, create, *, allow
    p, role:admin, repositories, update, *, allow
    p, role:admin, repositories, delete, *, allow
    p, role:admin, projects, create, *, allow
    p, role:admin, projects, update, *, allow
    p, role:admin, projects, delete, *, allow
    p, role:admin, accounts, update, *, allow
    p, role:admin, gpgkeys, create, *, allow
    p, role:admin, gpgkeys, delete, *, allow
    g, role:admin, role:readonly
    g, i8software:i8software:Admins, role:admin
  policy.default: 'role:readonly'
```

**Comment by jannfis** [comment]
Hi, the line in your RBAC configuration `g, i8software:i8software:Admins, role:admin` looks a little fishy. If you click on the user-info pane in the UI, what groups is your user assigned to? Does it match your specification?

**Comment by jajjg** [comment]
> Hi, the line in your RBAC configuration `g, i8software:i8software:Admins, role:admin` looks a little fishy. If you click on the user-info pane in the UI, what groups is your user assigned to? Does it match your specification?

@jannfis - thanks for your reply and in the UI everything looks fine.
<img width="1073" alt="Screen Shot 2020-07-23 at 12 46 50 AM" src="https://user-images.githubusercontent.com/13406311/88227153-3841bf80-cc7e-11ea-8926-1cc5963ed129.png">

**Comment by jannfis** [comment]
It seems your groupname is different. The line `g, i8software:i8software:Admins, role:admin` should be `g, i8software:Admins, role:admin` imho, then you should be fine.

**Comment by illum8** [comment]
> It seems your groupname is different. The line `g, i8software:i8software:Admins, role:admin` should be `g, i8software:Admins, role:admin` imho, then you should be fine.

Dammit - i just noticed that after your comment above and tested it - its working fine.  Thanks for your help!
