### ISSUE TITLE
Application Destination Server doesn't handle mismatched trailing slash

### ISSUE THREAD

**Issue by dustinchilson** [argoproj/argo-cd#3993]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Adding a trailing slash to the server when using a globally registered server, which does not have the trailing slash, results in a mismatch, resulting in an RPC error.

```
{
  "error":"application spec is invalid: InvalidSpecError: Unable to get cluster: rpc error: code = NotFound desc = cluster \"https://10.1.0.1:6443/\" not found",
  "code":3
}
```

**To Reproduce**

1. Add a Cluster to the server using the declarative methods as described here, https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#clusters
2. Ensure the server does not have a trailing slash ie `https://10.1.0.1:6443`
3. Create an application via the web interface or via the api that uses the same url but with a trailing slash ie `https://10.1.0.1:6443/`
4. The application will throw an RPC error

```
{
  "error":"application spec is invalid: InvalidSpecError: Unable to get cluster: rpc error: code = NotFound desc = cluster \"https://10.1.0.1:6443/\" not found",
  "code":3
}
```

**Expected behavior**

These urls are largely the same and should function the same. I was programatically creating applications and the slash was accidentally getting appended.

**Screenshots**

**Version**
v1.6.1+159674e

**Logs**

**Comment by jannfis** [comment]
Thanks for your report, @dustinchilson - I agree that any trailing slash should be stripped from destination URL when creating an application (and probably also when adding a cluster).

**Comment by imrenagi** [comment]
can i take this one?

**Comment by jannfis** [comment]
@imrenagi It would be much appreciated if you do! 

If you need any support while setting up local development environment, just let us know. Just make sure to read [the documentation](https://argoproj.github.io/argo-cd/developer-guide/contributing/).

**Comment by imrenagi** [comment]
Thanks! any pointer on where I should start with this? Is this on cli?

**Comment by jannfis** [comment]
Probably the most appropriate place to start would be in https://github.com/argoproj/argo-cd/blob/master/util/db/cluster.go
