### ISSUE TITLE
Keepalive heartbeat in long living sessions.

### ISSUE THREAD

**Issue by doctornkz** [argoproj/argo-cd#4000]
# Summary
I would like to have `keepalive heartbeat` during long polling application status, as example `argocd wait APPNAME` 

# Motivation
I have such warnings inside gitlab-ci :
```
 time="2020-07-22T15:12:25Z" level=warning msg="watch err: rpc error: code = **Unknown** desc = unexpected EOF"
92 time="2020-07-22T15:13:26Z" level=warning msg="watch err: rpc error: code = **Unknown** desc = unexpected EOF"
93 2020-07-22T15:15:28+00:00  extensions  Deployment   myapp  myapp-app-deployment  OutOfSync  Progressing              deployment.extensions/myapp-app-deployment configured
94 2020-07-22T15:15:28+00:00  extensions  Deployment   myapp  myapp-app-deployment  OutOfSync  Healthy              deployment.extensions/myapp-app-deployment configured
95 time="2020-07-22T15:19:16Z" level=warning msg="watch err: rpc error: code = **Unknown** desc = unexpected EOF"
96 time="2020-07-22T15:20:17Z" level=warning msg="watch err: rpc error: code = **Unknown** desc = unexpected EOF"
```
It because we have `idle timeout` 60 sec in the ingress/ALB configuration. And that [method](https://github.com/argoproj/argo-cd/blob/f9889e3c0b98eadcefee16142b400449d31ec227/pkg/apiclient/apiclient.go#L701) seems like a root cause of unexpected EOF.

# Proposal
Instead of increasing timeouts to extreme level (like 1 hour) my proposal to have `heartbeat`  request (like ping) every 10..20 sec to avoid dropping socket, make `Unknown` noise, reopening connection and so on. Additionally every `heartbeat` request/response should have human readable output like:
``` 
95 time="2020-07-22T15:19:16Z" level=warning msg="Waiting data is too long, keeping connection alive."
96 time="2020-07-22T15:19:16Z" level=warning msg="Waiting data is too long, keeping connection alive." 
```
Or something else more correct. 
PS. Thank you for your job, folks and stay safe!

**Comment by jessesuen** [comment]
argocd wait APPNAME should retry automatically (but spews out logs when it does), is this actually affecting the `wait` behavior at all?

**Comment by doctornkz** [comment]
It retries automaticaly after dropping coonnection, no worries or issues here. My improvement just to prevent **dropping** itself. Like it's done in websocket protocol : https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Pings_and_Pongs_The_Heartbeat_of_WebSockets
