### ISSUE TITLE
Add status badge for project

### ISSUE THREAD

**Issue by victorboissiere** [argoproj/argo-cd#4001]
# Summary

Add a status badge for an entire project

# Motivation

When deploying with a pipeline a set of applications within a project, it could be great to have a status for the full project inside a PR for instance. The feature is only available with application but not for project.

# Proposal

I do not think a status tracking is available for a project but only for single application. When dealing with 20-30 applications by project, a displayed status could be a nice feature to have.

**Comment by gaganhegde** [comment]
Hey @victorboissiere ! you mean a status tracker indicating the success or failure of your pipelines on the UI of your version control system (i.e git)?

**Comment by alexmt** [comment]
@gaganhegde , just to add some context. Argo CD already has a status badge that includes information about sync and health application status: https://argoproj.github.io/argo-cd/user-guide/status-badge/

As I understand @victorboissiere is suggesting a similar badge with the aggregated status of all project apps.

**Comment by gaganhegde** [comment]
Thanks for the context @alexmt , will take a peek into it.

**Comment by gaganhegde** [comment]
Hey @alexmt  https://github.com/argoproj/argo-cd/pull/4301 , is the PR for this issue. Please take a look and let me know if any changes are required. Thanks.

**Comment by tetchel** [comment]
is this complete?

**Comment by gaganhegde** [comment]
Yes, its Merged  @tetchel

**Comment by DoumLaberge** [comment]
I've look at the project badge, but for me this is not complete.  It should have the option to generate a list of status based on every apps of the project.  Not a summary, but a list.  Right now, I have to add every app badge, and maintain the list when I add a new app to argoCD.  Thank you

**Comment by Bogay** [comment]
As #4301 got merged, should we update the relevant doc? i.e. https://argo-cd.readthedocs.io/en/stable/user-guide/status-badge/
Currently only the `name` args is documented.

**Comment by alexmt** [comment]
implemented by https://github.com/argoproj/argo-cd/pull/4301
