### ISSUE TITLE
Upgrade ReDoc to gain Swagger UI API console feature

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#401]
Opening an issue for this so it doesn't get lost. As soon as ReDoc has a release for the API console, we should take advantage of it. Issue can be tracked here:

https://github.com/Rebilly/ReDoc/issues/53

**Comment by alexmt** [comment]
We still need it. Looks like ReDoc won't have feature in the near future. We should consider https://github.com/mrin9/RapiDoc

**Comment by wll8** [comment]
- [👉 View video](https://cdn.jsdelivr.net/gh/wll8/static/Video_20200518145834_redoc_show.mp4)
- [👉 online preview](https://wll8.github.io/redoc-try/index.html)

Add `Try it out` function like [swagger](https://petstore.swagger.io/) on [redoc](https://github.com/Redocly/redoc).

![re-doc try](https://github.com/wll8/redoc-try/raw/master/redoc_show.png)
