### ISSUE TITLE
Question: How often does application-controller query K8S?

### ISSUE THREAD

**Issue by rokrokss** [argoproj/argo-cd#4020]
Hi, I wanted to understand argocd-application-controller in code-level, but it was quite hard for me to figure out. I have few questions.

- How often does application-controller request K8S to refresh to current live state?
- Does it request for all resources in cluster, or check for resources only in generated manifest?
- If I turn  orphaned resource monitoring on, how does it affect requests to k8s?

**Comment by mayzhang2000** [comment]
Here is my understanding:

- application-controller has `defaultAppResyncPeriod` which is 180 seconds that is used to request to refresh to current live state. . [defaultAppResyncPeriod](https://github.com/argoproj/argo-cd/blob/master/cmd/argocd-application-controller/main.go#L38)

**Comment by rokrokss** [comment]
@mayzhang2000 Thanks! Your answer was so helpful!!
