### ISSUE TITLE
Need to remove CoreOS logo from ldap login page

### ISSUE THREAD

**Issue by ssharma2089** [argoproj/argo-cd#4024]
**Describe the bug**
I want to remove coreos log from ldap login page.

**To Reproduce**

1. Deployed HA argocd-v1.6.1 from below link
[https://github.com/argoproj/argo-cd/releases](url)
2. Configure Ldap in argocd-cm configmap
3. Navigate to LLdap login page

**Expected behavior**

Need steps to remove the coreos log and deploy some other logo

**Screenshots**

![Screenshot_54](https://user-images.githubusercontent.com/51249266/89036320-1b7e4980-d35a-11ea-8434-8fcac96162f8.png)

**Version**

```shell
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:39:46Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Comment by jessesuen** [comment]
This is a dex thing. I believe it's possible via dex configuration, which you should have control over.
