### ISSUE TITLE
Login page is slow due to google fonts

### ISSUE THREAD

**Issue by ssharma2089** [argoproj/argo-cd#4025]
**Describe the bug**

We are implementing airgap installation, and hence loading of login and dashboard page is slow since it can not download css fonts etc from internet. It will show waiting for googleapis.com

**To Reproduce**

1. Deploy argocd installation
2. Navigate to login and dashboard page

**Expected behavior**

Pages should load fast with all the required fonts,css etc.

**Version**

```shell
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:39:46Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Comment by jessesuen** [comment]
Fix would be to bundle this into the distribution. Would appreciate community help here!

**Comment by allenyinx** [comment]
any updates here for the css loading issue?

**Comment by tetchel** [comment]
I see that the 'Heebo' font is loaded from `fonts.googleapis.com`, but it looks like all the css is correctly bundled to be inline. Is the "css loading issue" the same as the parent issue, or is there a problem loading some styles too?

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-cd/pull/4324
