### ISSUE TITLE
Use secrets for private git repository credentials

### ISSUE THREAD

**Issue by TrevorPace** [argoproj/argo-cd#4028]
# Summary

Credentials for private git repositories are currently provided by either the argocd-tls-certs-cm.yaml or argocd-ssh-known-hosts-cm.yaml resources. These being configmaps as opposed to secrets, makes them incompatible with kubernetes-external-secrets controller.

# Motivation

Currently, we are running clusters for a customer in which secrets are being pulled into the cluster with use of the kubernetes-external-secrets controller. This works well because it allows us to logically separate credentials and other secrets from the actual construction of the cloud, as well as change credentials "on the fly". However, currently argocd only supports storing TLS certs in a configmap, as opposed to a secret.

It's also logically "weird" that we are storing what are essentially confidential credentials within a configmap.

# Proposal

Change argocd-tls-certs-cm.yaml and argocd-ssh-known-hosts-cm.yaml to secrets compatible with kubernetes-external-secrets-controller. This would require the format of argocd-ssh-known-hosts-cm.yaml to have to change so that each host could be provided individually.

Instead of using just one hard-coded secret resource it might make more sense to allow annotations to be added to the secrets so that host credentials can be added individually if desired. The application control would pick these up automatically and amalgamate them.

**Comment by jannfis** [comment]
We do not store any credentials in the config maps you mentioned (or in any other config map, to my knowledge). The assets in the `argocd-tls-certs-cm` and `argocd-ssh-known-hosts-cm` config maps are generally public ones - *public* host keys, and *public* TLS certs. 

Anyone can retrieve the TLS cert of a web server by just connecting to port 443, likewise with the host key of the SSH server by connecting to port 22. None of these are used for authentication or authorization, their sole purpose is to cryptographically identify a remote server.

IMHO, there's no confidentiality involved here.

**Comment by TrevorPace** [comment]
Yeah you're right. I'm sorry I got mildly confused and thought this was what was getting stored inside kubernetes in terms of credentials. From what I can the only way to actually do this is through the argocd or argo ui.

I'm closing this then. Cheers.
