### ISSUE TITLE
Manifest links are outdated in the latest v1.6.2 release

### ISSUE THREAD

**Issue by LinAnt** [argoproj/argo-cd#4030]
Hi,

I just noticed the manifest links are pointing to the v1.6.1 manifests in the v1.6.2 release.

https://github.com/argoproj/argo-cd/releases/tag/v1.6.2

Correct links would be 
https://raw.githubusercontent.com/argoproj/argo-cd/v1.6.2/manifests/install.yaml
https://raw.githubusercontent.com/argoproj/argo-cd/v1.6.2/manifests/ha/install.yaml
respectively.

**Comment by jannfis** [comment]
Thank you! I have just fixed it on the releases page!

**Comment by LinAnt** [comment]
Nice :)
