### ISSUE TITLE
Apply namespaces, storageClass, NetworkPolicies, etc

### ISSUE THREAD

**Issue by dignajar** [argoproj/argo-cd#4032]
# Summary

Currently, we have everything as a descriptor file (yaml), we have our namespaces, storageclass, networkpolicies in yaml files. So if someday we need to re-deploy the cluster or maybe create a new one for another environment we can just apply our files.

# Motivation

For example, we have the following structure in Git.

```
namespaces/
  tools.yaml
  system.yaml

storageClass/
  ebs.yaml
  io1.yaml
```

# Proposal

Create a section more general than an application in ArgoCD so we can add this files and been apply by ArgoCD. Also, remove the field `namespace` which is strict.

**Comment by alexmt** [comment]
hello @dignajar, 

Argo CD applications might be used to manage system-level components as well. Argo CD respect namespace specified in the resource manifest stored in Git. The namespace field has been made optional in the upcoming v1.7 release. In previous release you might specify non-existing namespace name make sure resource is not created in wrong namespace.
