### ISSUE TITLE
Documentation on how to integrate with Prometheus alert-manager 

### ISSUE THREAD

**Issue by JSIDELIVERETH** [argoproj/argo-cd#4035]
# Summary

The docs [here](https://argoproj.github.io/argo-cd/operator-manual/notifications/) talks about support for Prometheus and alert manager, it will be very helpful to have a step by step doc on this. Or if there is a workaround to send alerts/build notifications to alert manager.

**Comment by Kampe** [comment]
Why'd you close this, how'd you solve?
