### ISSUE TITLE
numbered docker hash converts to scientific notation

### ISSUE THREAD

**Issue by ofirshtrull** [argoproj/argo-cd#4050]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

If an image tag contains only numbers 4651090 then argocd will transfer the number to "465109e+06"
**To Reproduce**

create a value based on numbers only

**Expected behavior**

tag inst converted and docker starts

**Screenshots**

![Screen Shot 2020-08-05 at 10 10 15](https://user-images.githubusercontent.com/28642443/89383315-ef214f00-d704-11ea-805b-fbb907bc48c8.png)
![Screen Shot 2020-08-05 at 10 10 22](https://user-images.githubusercontent.com/28642443/89383319-f0eb1280-d704-11ea-845f-1685852ada35.png)

**Version**
```shell
❯ argocd version
argocd: v1.6.0+c10ae24
  BuildDate: 2020-06-16T22:41:56Z
  GitCommit: c10ae246ab02f1356147118a1979fedcd1ceb704
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
Theres a separate field/option `--helm-set-string` to indicate if the helm value should be treated as a string. This is how to ensure that the input is always treated properly.
