### ISSUE TITLE
bug(ui): Swagger UI stuck loading

### ISSUE THREAD

**Issue by rbreeze** [argoproj/argo-cd#4054]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The Swagger UI at `localhost:8080/swagger-ui` is stuck on the loading screen.
**Screenshots**
<img width="1473" alt="Screen Shot 2020-08-05 at 3 52 40 PM" src="https://user-images.githubusercontent.com/6250584/89471711-b2208100-d733-11ea-911b-85ba3ccc6cda.png">

**Version**

```shell
argocd: v1.6.0+c10ae24
  BuildDate: 2020-06-16T22:41:56Z
  GitCommit: c10ae246ab02f1356147118a1979fedcd1ceb704
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
```

**Comment by alexmt** [comment]
Just an update about the progress here. Looks like issue is related to bug in grpc-ecosystem/grpc-gateway/protoc-gen-swagger : https://github.com/grpc-ecosystem/grpc-gateway/issues/1109 . The change is available in https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v1.12.2 


Tried to [upgrade](https://github.com/alexmt/argo-cd/commit/c8d7633e6045cee9dff0cdd92b9ffb9dab3b88c1) swagger but did not get expected change in generated swagger.json file. The same file was generated.

**Comment by yydzhou** [comment]
@alexmt and @rbreeze  did you get any update here?  I am hitting the same issue after upgrade argocd to 1.7

**Comment by aoighost** [comment]
I'm having the same issue
