### ISSUE TITLE
Stream terminated by RST_STREAM with error code: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by ecojuntak** [argoproj/argo-cd#4057]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We are building an application on top argocd library. We use this application to create project, create application, sync manifest, and other use cases. So far it working fine on argocd 1.5.2 and library version 1.5.2. I also use argocd 1.5.2 binary on my machine and it working fine to communicate with the argocd server.

Then, we upgrade the argocd server to 1.6.1 and also di library and the binary with the same version, and got this error when checking the argocd version after execute my application binary.

**To Reproduce**
- login to argocd 1.6.1 `argocd account login`
- execute `argocd version` -> on this step no error happen
- execute application binary -> the expected behavior is to create an argocd application, but it failed and got error `rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR`
- execute `argocd version` -> on this step it will failed with the same error

`argocd version` command will always success before executing my application binary and also will always fail after executing my application binary

**Expected behavior**
- The server version should be printed
- The argocd application should be created

**Version**

The success case
```shell
argocd version
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:39:46Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```
The fail case
```shell
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:39:46Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
FATA[0000] rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR
```

**Logs**
No relevant log I can provide

**Comment by imrenagi** [comment]
@alexmt is there any workaround for this issue?

**Comment by ecojuntak** [comment]
@alexmt any helps here?

**Comment by aindeev** [comment]
We were also running into this issue on every command `version`, `login`, etc.

Were able to solve by connecting through **grpc-web**. After that, all commands were working 🎉🚀
```
argocd login --sso argocd.example.com --grpc-web
```

------

I think this happens because the grpc ingress is not correctly configured. We have the following networking setup and somewhere along the way the connection seems to be broken:
`Client` -> `GCE Ingress on GKE` -> `Traefik Server` -> `Traefik Ingress Route` -> `Service` -> `Deployment`
