### ISSUE TITLE
Add support for sorting applications by name

### ISSUE THREAD

**Issue by gnagel** [argoproj/argo-cd#4060]
# Summary
The Argo UI doesn't currently allow sorting by name or any other attribute such as last sync time.

# Motivation
I would use this when scanning the list of available apps by name, sorting by deployment time, etc.

# Proposal
Client-side sorting of the fields in memory.

**Comment by alexmt** [comment]
@rbreeze you might want to take a look

**Comment by manuNCL** [comment]
Hi guys, I was wondering if there is any progress on this. This sounds to be a "good first issue" to familiarise myself with ArgoCD.

**Comment by rbreeze** [comment]
@manuNCL We haven't looked into this further yet. Feel free to work on it!

**Comment by manuNCL** [comment]
Great! I'll look into this next week. Today, I managed to compile and run Argo-CD with a virtualized toolchain (I suppose) so I think I'm ready to try things out. I will keep you updated.

**Comment by tetchel** [comment]
@manuNCL have you made any progress on this? otherwise, I will look into improving the applications 'list' view to include sorting.

**Comment by manuNCL** [comment]
> @manuNCL have you made any progress on this? otherwise, I will look into improving the applications 'list' view to include sorting.

@tetchel feel free to work on this. I've got caught up with work stuff and could not look into this.

**Comment by pasha-codefresh** [comment]
@rbreeze are you going to do it ? we can help here if you want

**Comment by gnagel** [comment]
Awesome, thank you for doing this one!
