### ISSUE TITLE
Filter drop down clips itself upwards when there's insufficient space to drop down

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4079]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Filter drop down clips itself upwards when there's insufficient space to drop down

**To Reproduce**

1. visit https://cd.apps.argoproj.io/applications/argoproj
1. click the filter button near the top right
1. make window short (possibly adjust zoom) -- see first picture for sizing
1. zoom in some steps
1. try to scroll to see the extent of the "drop down"

**Expected behavior**

See the top (`Sync`)

**Screenshots**

![window size](https://user-images.githubusercontent.com/2119212/89933137-a2de7f00-dbdc-11ea-80f0-d72f02409d28.png)
![normal](https://user-images.githubusercontent.com/2119212/89932830-3794ad00-dbdc-11ea-99ce-61cc7155be76.png)

![doesn't fit top](https://user-images.githubusercontent.com/2119212/89932777-28adfa80-dbdc-11ea-9f2e-afbeff447691.png)
![doesn't fit bottom](https://user-images.githubusercontent.com/2119212/89932740-1d5acf00-dbdc-11ea-8046-0498727ea045.png)

**Version**

v1.7.0+2854497

**Logs**

**Comment by jsoref** [comment]
For reference, the problem is the `top: -311px`:
```html
<div class="argo-dropdown__content opened is-menu" style="top: -311px; left: 267.429px;">
...
</div>
```
which I believe comes from https://github.com/argoproj/argo-ui/blob/ce762319ed4d6ebdeb812a2c149001ded4e9b3b2/src/components/dropdown/dropdown.tsx#L50

**Comment by saumeya** [comment]
@jsoref this can be closed
