### ISSUE TITLE
Where can I set the init password of new added account ?

### ISSUE THREAD

**Issue by enderson-pan** [argoproj/argo-cd#4090]
I've read the docs, however, can't find how to set the init password of the new added account.
How can I add new account with init password? 
Thanks in advance.

**Comment by alexmt** [comment]
Hello @enderson-pan ,

It is impossible to restore password, but here is instructions to reset it: https://argoproj.github.io/argo-cd/faq/#i-forgot-the-admin-password-how-do-i-reset-it

**Comment by enderson-pan** [comment]
Hi, @alexmt 
Maybe I didn't express my issue correctly. What I asked is not about the admin user, it was about another account added besides the admin account.
I've read the doc about how to add an account, and I‘ve added the accout. For example
![image](https://user-images.githubusercontent.com/1694834/90237705-4aff7c80-de57-11ea-9774-13bb882439f4.png)
So how can I login in use the account holytiny? What's the init password of this local account or how can I init the password?
Thanks in advance.

**Comment by enderson-pan** [comment]
For someone who meets the same issue, the inint passwor of the new added local user is the same as the admin's password.

**Comment by srearnold** [comment]
if you added a new local user named "argocduser",you can edit secret resource argocd-secret where key is 'accounts.argocduser.password' and value is bcrypt(password) like https://argoproj.github.io/argo-cd/faq/ "I forget password" part said.
