### ISSUE TITLE
Run Redis Container Without Root Permissions

### ISSUE THREAD

**Issue by danielhelfand** [argoproj/argo-cd#4092]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Currently, the deployment of argocd requires privileged permissions to run a redis container. In restricted environment where containers cannot run as root, the following happens:

```
container "redis" in pod "argocd-redis-6d7f9df848-w2l45" is waiting to start: CreateContainerConfigError  
```

Digging further into the pod description, the error is actually shown under Events:

```
Error: container has runAsNonRoot and image will run as root 
```

**To Reproduce**

Run `kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml` against a Kubernetes cluster that restricts containers from being run as root. 

**Expected behavior**

Either the container itself should not be run as root, or there should be more detail provided in the [Getting Started](https://argoproj.github.io/argo-cd/getting_started/) section of the argocd website on steps to make sure users don't run into this problem. Additionally, there should be some mention as to why this container needs root privileges to help clarify any confusion.

**Version**

[v1.6.2](https://raw.githubusercontent.com/argoproj/argo-cd/v1.6.2/manifests/install.yaml)

**Comment by jannfis** [comment]
Hi @danielhelfand, this has already been addressed and fixed with https://github.com/argoproj/argo-cd/pull/3934 and will be included with the v1.7 release.

**Comment by danielhelfand** [comment]
@jannfis Great, thanks for the prompt response. Is there a latest or nightly manifest published so I could test these changes?

**Comment by jannfis** [comment]
Sure, you can just use one of the installation manifests from master branch in the repository, e.g. https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml for a cluster wide, non-HA install.

**Comment by danielhelfand** [comment]
Works great and resolves it. Thanks again!
