### ISSUE TITLE
Where can I setup the private repo's credential when using 'Declarative Setup'  ?

### ISSUE THREAD

**Issue by enderson-pan** [argoproj/argo-cd#4097]
Hi,
If I don't want to expose my username and password to the url of a git repo, how can I set them when using 'Declarative Setup'?
I've read the doc of https://argoproj.github.io/argo-cd/operator-manual/application.yaml, but can't find any hint.

Firstly, I fork the example git repo to my private gitlab repo host.

Then I setup a private repo using the web-ui.

If I use web-ui, the username and password was set in the 'init repo ui', and one cann't see the credential of the repo anymore after I setting it.
![image](https://user-images.githubusercontent.com/1694834/90240844-949e9600-de5c-11ea-9fda-a3dd55b14ed1.png)
After setting the repo in web-ui, I try to get any hit from the yaml file, but still can't find one.
```
kubectl describe application guestbook -n=argocd
```
So what's the equivalent way of 'Declarative Setup'?
Thanks in advance.

**Comment by LelandSindt** [comment]
I believe that you are looking for the `repositories` section of the [argocd-cm.yaml](https://argoproj.github.io/argo-cd/operator-manual/argocd-cm.yaml)

The username and password are then stored as Kubernetes secrets and referenced as described in [argocd-cm.yaml](https://argoproj.github.io/argo-cd/operator-manual/argocd-cm.yaml)

**Comment by enderson-pan** [comment]
@LelandSindt

**Comment by enderson-pan** [comment]
T
