### ISSUE TITLE
ClusterRole argocd-application-controller needs 'use' permission for PSPs?

### ISSUE THREAD

**Issue by jkleinlercher** [argoproj/argo-cd#4103]
# Summary

In K8s-Clusters where PodSecurityPolicy admission controller is enabled, the argocd-application-controller serviceaccount is allowed to use any PSP because the argocd-application-controller ClusterRole has every permissions for every object. In such a case the pod security policy controller takes any PSP which doesn't alter the pod and is the first in alphabetical order (that is how I think it works according to https://banzaicloud.com/blog/pod-security-policy/).

# Motivation

We want to have a deterministic result which serviceaccount uses which PSP so we want to be very specific which serviceaccount can use which PSP. It doesn't seem like a good security practice that the argocd-application-controller pod runs with 'some' but not a well definied PSP.

# Proposal

I do not know for which purpose the argocd-application-controller ClusterRole is used and why it needs every permission for every object. Is it really needed that argocd can create all the objects from all applications or is that done in other ways? Would it be okay to define every permission except the "use" permission? Maybe then we already achieve the goal that PSPs can't be used (but still be created).

**Comment by jkleinlercher** [comment]
I actually think it is a security issue not just an enhancement because you are unable to bind any restricted psp to the argocd-application-controller pod.

**Comment by joebowbeer** [comment]
PSP is deprecated and will be removed in 1.25. To be replaced by PSS/PSA.

Upgrade this issue to relate to PSS?

**Comment by joebowbeer** [comment]
@crenshaw-dev please close: obsolete, won't fix
