### ISSUE TITLE
Use cluster name in place of URL in UI

### ISSUE THREAD

**Issue by greenkiwi** [argoproj/argo-cd#4135]
# Summary

Clusters have both Names and URLs.  The names often convey more information to a user than the URLs convey.   As such, it would be great to be able to use this name when filtering and see it in the "destination" of an application

# Motivation

The current cluster filter drop-down has a list of all the URLs.
![image](https://user-images.githubusercontent.com/54169/90829159-5bea4980-e393-11ea-9a6d-3e7cbba41511.png)
We are using EKS and as you can see, the cluster URL is not particularly useful.

The same is true for the application cards:
![image](https://user-images.githubusercontent.com/54169/90829260-85a37080-e393-11ea-91fa-7df14917172c.png)

When you see these in the `Settings / Clusters`, you can see that we have human-readable names
![image](https://user-images.githubusercontent.com/54169/90829337-a66bc600-e393-11ea-845b-a5a3422e91b8.png)

# Proposal

It would be great if one could use both the cluster URL and Name in the clusters filter and that the cluster name was displayed in the application card for the destination field.

**Comment by alex-linx** [comment]
Same issue here.
When deploying a new app via the UI, If I click on cluster name instead of URL nothing happens.
It's a real issue because my clusters are hosted on EKS and their URLS are just a random string, which means I have to go look up that URL, which is error pront and might mean I accidnetally deploy to the wrong cluster

**Comment by crenshaw-dev** [comment]
@alex-linx can you open a new issue? This one is pretty old and seems to be for a slightly different issue.
