### ISSUE TITLE
show x hidden resources should be clear filters to show x additional resources

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4142]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

`Show x hidden resources` doesn't explain what happens when one clicks it. It also doesn't explain why things are hidden.

What's actually happening is that the widget is saying `filters have hidden x resources` + `to see those resources, click here to clear the filters` -- note that depending on how expensive it was to create the filters in the first place, clearing them may be akin to local user dataloss.

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.
1. Visit https://cd.apps.argoproj.io/applications/argo-cd?view=tree&resource=kind%3APod%2Ckind%3ARoleBinding%2Ckind%3AEndpoints
1. Set filters (the url above has some filters, but to make it more realistic, change the filters)
1. See a shiny "show x hidden resources" box
1. Naively click it, not understanding the consequences
1. Realize that your careful effort to construct filters have been lost

**Expected behavior**

The box should say "clear filters to show x additional resources"

**Screenshots**

Actual (the number are random)
![image](https://user-images.githubusercontent.com/2119212/90933058-61fd1c00-e3cd-11ea-823b-6cb5c0bb7aa2.png)

Expected:
![image](https://user-images.githubusercontent.com/2119212/90932344-742a8a80-e3cc-11ea-9321-dd83f626dffd.png)

**Version**

v1.7.0+263e7a8

**Logs**

**Comment by alexmt** [comment]
Fixed. Thank you @jsoref !
