### ISSUE TITLE
failed to enforce max concurrent logins limit

### ISSUE THREAD

**Issue by Cloud-Mak** [argoproj/argo-cd#4148]
Hi All,

I am getting started with argoCD. I have existing K8 (1.17) cluster (1 master, 2 workers) running on LXD containers. Just today, I deployed argoCD using the yaml file available on quickstart guide. I could see argocd namespae with all its resources. Here is main issue - 
Whenever I try to login into argoCD webUI, I get below error :-
`failed to enforce max concurrent logins limit: dial tcp 10.108.18.229:6379: i/o timeout
`

I tried recreating the redis pod, it didn't help. The error not going away. Any idea what might be happening? 

Here is how real time logs are looking for agrocd-server-pod

> time="2020-08-24T15:56:59Z" level=error msg="finished unary call with code Unknown" error="failed to enforce max concurrent logins limit: dial tcp 10.108.18.229:6379: i/o timeout" grpc.code=Unknown grpc.method=Create grpc.service=session.SessionService grpc.start_time="2020-08-24T15:56:59Z" grpc.time_ms=53.738 span.kind=server system=grpc
> time="2020-08-24T15:57:03Z" level=info msg="Alloc=8904 TotalAlloc=74094 Sys=71248 NumGC=52 Goroutines=150"
> time="2020-08-24T15:57:07Z" level=error msg="finished unary call with code Unknown" error="failed to enforce max concurrent logins limit: dial tcp 10.108.18.229:6379: i/o timeout" grpc.code=Unknown grpc.method=Create grpc.service=session.SessionService grpc.start_time="2020-08-24T15:57:07Z" grpc.time_ms=28.253 span.kind=server system=grpc
> time="2020-08-24T15:57:12Z" level=error msg="finished unary call with code Unknown" error="failed to enforce max concurrent logins limit: dial tcp 10.108.18.229:6379: i/o timeout" grpc.code=Unknown grpc.method=Create grpc.service=session.SessionService grpc.start_time="2020-08-24T15:57:12Z" grpc.time_ms=59.252 span.kind=server system=grpc
> time="2020-08-24T15:57:18Z" level=error msg="finished unary call with code Unknown" error="failed to enforce max concurrent logins limit: dial tcp 10.108.18.229:6379: i/o timeout" grpc.code=Unknown grpc.method=Create grpc.service=session.SessionService grpc.start_time="2020-08-24T15:57:18Z" grpc.time_ms=72.987 span.kind=server system=grpc
> 

Here is screenshot of error - http://i.imgur.com/PJrhZDc.png

**Comment by jessesuen** [comment]
This is fixed in v1.7. in the meantime workaround available https://github.com/argoproj/argo-cd/issues/3547#issuecomment-624819065

**Comment by Cloud-Mak** [comment]
Thanks for the workaround. It worked. My install.yaml now have said **env** defined.

Now here is new issue. 

This is my lab K8 setup. Running on a latop (OS - linux mint) over LXD containers. Whenever I reboot the laptop, the argocd-server just looses the "env"  from its deployed manifest. I checekd it with "kubectl -n argocd edit argocd-server" and coouldn't find it. And I am back to square one. The error comes back again. If I deploy argocd server with env defined in install.yaml, it should remain in argoserver forever. Not sure why its loosing it. 

Intestingly - If I run again **kubeclt -n argocd apply -f install.yaml**, it shows every resource unchanged. 

I have other thigns like metallb, ingress, rancher etc deployed on this cluster. With every reboot of laptop (i.e cluster), these thigns remain unaffected along with their resources/configs and works fine (unlike argocd here). 

Any idea why env is not present in argocd-server once I reboot the cluster? Is this suppose to happen?
