### ISSUE TITLE
Error message truncated in UI when it is very long

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4152]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The error box is huge and yet nowhere near big enough to actually read the error. And it doesn't scroll well.

**To Reproduce**

1. Navigate argocd to a pod
1. Click the pod
1. Click Edit in the Live Manifest
1. Go to `spec:` > `containers:` > `env:`
1. Add or otherwise change the environment
1. Click save 

**Expected behavior**

1. Ideally if you know my changes aren't valid, don't let me try to save them
1. The view should scroll wrap/something so I can read the content, it doesn't -- I have to select all and copy to a text editor to read it.

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/91090365-f0b6a680-e622-11ea-9cdd-730ab1c9827f.png)

> Unable to save changes: Pod "github-runner-76cff478cd-8bfqg" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)   

**Version**

v1.6.1+159674e

**Logs**

**Comment by rbreeze** [comment]
> Unable to save changes: Pod "github-runner-76cff478cd-8bfqg" is invalid: spec: Forbidden: pod updates may not change fields other than spec.containers[*].image, spec.initContainers[*].image, spec.activeDeadlineSeconds or spec.tolerations (only additions to existing tolerations)

@jsoref is this how you would like the error message to be formatted? or are you seeing this somewhere else?

**Comment by jsoref** [comment]
@rbreeze: that's just some of the text from the red error box.

No, it isn't how I'd like it formatted.

**Comment by rbreeze** [comment]
@jsoref Unfortunately we can't tell this YAML is invalid until it's sent to the server. We do validate the YAML before sending it, and when it's invalid it displays a nicely formatted error message; in this case the server is sending back a not-so-nicely formatted message, which is what you're seeing. For now, I'll make sure it's scrollable.

**Comment by rbreeze** [comment]
#4195
