### ISSUE TITLE
API requests break when invalid account token exists in secret

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#4156]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

If an invalid token for a local user exists in `argocd-secret`, the API will refuse to process any request with an error message similar to:

```
FATA[0002] rpc error: code = Unknown desc = invalid character 'e' looking for beginning of value
```

**To Reproduce**

Set an invalid token for an existing local user in `argocd-secret`, i.e.

```
accounts.foobar.tokens: someinvalidvalue
```

Then try to use any command in the CLI.

**Expected behavior**

All users except the one with invalid token should be able to continue working with the API.

**Version**

```shell
argocd-server: v1.7.0+ee57ded
  BuildDate: 2020-08-24T23:48:05Z
  GitCommit: ee57ded16f7095498ed84b561aa41ef574cd7a2c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8

```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by chetan-rns** [comment]
@jannfis Can I work on this issue? This looks like a good start to understand the API

**Comment by jannfis** [comment]
> @jannfis Can I work on this issue? This looks like a good start to understand the API

Sure, go ahead @chetan-rns :)

**Comment by alexmt** [comment]
@chetan-rns , you might want to check [parseAccounts](https://github.com/argoproj/argo-cd/blob/master/util/settings/accounts.go#L308) method. I think instead of returning error method should print error to logs and proceed to the next account.
