### ISSUE TITLE
Argo CD does not exclude creationTimestamp from diffing

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#4157]
**Describe the bug**

Argo CD does not exclude `creationTimestamp` from diffing. The `creationTimestamp` is often included in Git manifests and causes false positives during diffing. 

**Expected behavior**

The `creationTimestamp` should be excluded from diffing.

**Version**

```shell
v1.7.0
```

**Comment by aweis89** [comment]
I'm still seeing this when running `argocd app diff` with the CLI
