### ISSUE TITLE
Error logs are rendered with a 60px line spacing because of table row rule

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4169]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Error logs use the table row ui which triggers huge line spacing between log rows

**To Reproduce**

Follow instructions from #4159

**Expected behavior**

Lines of error log should have normal spacing and not 60px.

**Screenshots**

![error with 60px line spacing](https://user-images.githubusercontent.com/1162120/91259624-d9ee8c00-e7a9-11ea-9dfa-058dc724daee.png)

**Version**

v1.6.1+159674e
(also master as I see the relevant code and will be providing a PR shortly)

**Logs**

**Comment by blakepettersson** [comment]
I think this has been fixed since a while back 😄
