### ISSUE TITLE
Force delete option for deleting pods

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#417]
User hit a scenario where a missing node caused pods to enter a "NodeLost" state. The result was that the app had a bunch of pods which needed to be force deleted. We already have a way to delete pods, but no ability to **force** delete pods. This enhancement would allow the user to do this through the API.

NOTE: we may need to also add delete grace period in addition to the force delete.

**Comment by merenbach** [comment]
What would the ramifications be if we _only_ used force deletion on pods, rather than providing a choice?

**Comment by alexmt** [comment]
Done
