### ISSUE TITLE
Custom resource is missing in v1.7.1

### ISSUE THREAD

**Issue by Asuforce** [argoproj/argo-cd#4172]
**Describe the bug**

If you sync a manifest with a custom resource as a new application, it will be missing.
It doesn't happen with applications created with v1.6.2.

**To Reproduce**

Install argo cd to kubernetes v1.15.3 and try to create new application with custom resource.

**Expected behavior**

Custom resources exist in the cluster.
So it should clear the health check.

**Screenshots**

v1.6.2

![Screen Shot 0002-08-27 at 16 36 36](https://user-images.githubusercontent.com/9331040/91411665-9cf6c800-e883-11ea-9de2-b82e74a8b18f.png)

v1.7.1

![Screen Shot 0002-08-27 at 16 43 35](https://user-images.githubusercontent.com/9331040/91412305-93219480-e884-11ea-9cd1-1cd59540e21c.png)

**Version**

```shell
v1.7.1
```

**Logs**

none

**Comment by Asuforce** [comment]
As a workaround, revert to v1.6.2 with the offending application and then update to v1.7.1. This fixes the status of the application.

**Comment by olegsu** [comment]
@Asuforce Can you try on the latest release? 
I have tried on 1.7.1 and 1.7.2 and I seems to be fixed, not sure which commit fixed it.

**Comment by Asuforce** [comment]
I confirmed to fix this issue. Thanks a lot !
