### ISSUE TITLE
While logging via ldap, returning blank group

### ISSUE THREAD

**Issue by ssharma2089** [argoproj/argo-cd#4176]
**Describe the bug**

Ldap and group is configured in respective configmap but while logging it's showing blank group in logs

**To Reproduce**

1. Configure ldap in argocd-cm

connectors:
- type: ldap
  id: ldap
  name: XXX.XXX.XXX
  config:
    host: XXX.XXX.XXX:389
    insecureNoSSL: true
    rootCA: /etc/dex/ldap.ca
    bindDN: "CN=XXX,OU=XXX,DC=XXX,DC=XXX,DC=XXX"
    bindPW:  XXXXXX
    usernamePrompt: SSO Username
    userSearch:
      baseDN: ou=XXX,ou=XXX,DC=XXX,DC=XXX,DC=XXX
      filter: "(objectClass=Person)"
      username: cn
      idAttr: cn
      emailAttr: mail
      nameAttr: displayName
    groupSearch:
      baseDN: cn=XXX,ou=XXX,ou=XXX,ou=XXX,DC=XXX,DC=XXX,DC=XXX
      filter: "(objectCategory=Group)"
      userAttr: cn
      groupAttr: member
      nameAttr: cn

2. Configure rbac group in argocd-rbac-cm.
3. Logging via ldap
4. After logging, check logs of dex server

**Expected behavior**

It should returned the group after logging.

**Version**

```shell
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:39:46Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Logs**

```
time="2020-26-04T14:11:57Z" level=info msg="performing ldap search ou=XXX,DC=XXX,DC=XXX,DC=XXX sub (&(objectClass=Person)(member=xxx))"
time="2020-26-04T14:11:57Z" level=info msg="username \"xxx\" mapped to entry CN=xxx,OU=xxx,OU=xxx,DC=xxx,DC=xxx,DC=xxx"
time="2020-26-04T14:11:57Z" level=info msg="performing ldap search ou=xxx,ou=xxx,DC=xxx,DC=xxx,DC=xxx sub (&(objectCategory=Group)(member=CN=xxx,OU=xxx,OU=xxx,DC=xxx,DC=xxx,DC=xxx))"
time="2020-26-04T14:11:58Z" level=error msg="ldap: groups search with filter \"(&(objectCategory=Group)(member=CN=xxx,OU=xxx,OU=xxx,DC=xxx,DC=xxx,DC=xxx))\" returned no groups"
time="2020-26-04T14:11:58Z" level=info msg="login successful: connector \"ldap\", username=\"xxx\", preferred_username=\"\", email=\"xxx.xxx@xxx.xxx\", groups=[]"
```

**Comment by jessesuen** [comment]
I think this is a dex configuration issue and not Argo CD. Could you check if there is an dex issue?
