### ISSUE TITLE
Permission issues when running "make verify-kube-connect" and "make build" (Fedora 32)

### ISSUE THREAD

**Issue by Shraddhak22** [argoproj/argo-cd#4178]
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.

- [x] I've included steps to reproduce the bug.

- [ ] I've pasted the output of `argocd version`.

**Describe the bug**
Permission issues, while running "Make verify-kube-connect" and "make build" (Fedora 32)
Error while running, "make verify-kube-connect"
```
docker run --rm -it --name argocd-test-client -u 1000 -e HOME=/home/user -e GOPATH=/go -e ARGOCD_E2E_K3S= -e GOCACHE=/tmp/go-build-cache -e ARGOCD_LINT_GOGC=20 -v /home/skharche/go/src:/go/src:delegated -v /home/skharche/go/pkg/mod:/go/pkg/mod:delegated -v /home/skharche/.cache/go-build:/tmp/go-build-cache:delegated -v /home/skharche/.kube:/home/user/.kube:delegated -v /tmp:/tmp:delegated -w /go/src/github.com/argoproj/argo-cd argocd-test-tools:latest bash -c "kubectl version"
error: error loading config file "/home/user/.kube/config": open /home/user/.kube/config: permission denied
make: *** [Makefile:450: verify-kube-connect] Error 1
```
Error while running "make build"
```
docker run --rm -it --name argocd-test-client -u 1000 -e HOME=/home/user -e GOPATH=/go -e ARGOCD_E2E_K3S= -e GOCACHE=/tmp/go-build-cache -e ARGOCD_LINT_GOGC=20 -v /home/skharche/go/src:/go/src:delegated -v /home/skharche/go/pkg/mod:/go/pkg/mod:delegated -v /home/skharche/.cache/go-build:/tmp/go-build-cache:delegated -v /home/skharche/.kube:/home/user/.kube:delegated -v /tmp:/tmp:delegated -w /go/src/github.com/argoproj/argo-cd argocd-test-tools:latest bash -c " make build-local"
make: stat: Makefile: Permission denied
make: *** No rule to make target 'build-local'.  Stop.
make: *** [Makefile:307: build] Error 2
```

**To Reproduce**
Fork and clone the ArgoCD repository to your GitHub¶
- mkdir -p ~/go/src/github.com/argoproj
- cd ~/go/src/github.com/argoproj
- git clone https://github.com/<Your user Id>/argo-cd
- cd argo-cd

Login to Cluster, and follow below steps
- kubectl create namespace argocd
- kubectl apply -n argocd --force -f manifests/install.yaml

**Resolution to above problem (PR work in progress and will be there shortly)**
- Check selinux mode ( Just do ‘getenforce’ in terminal to check mode)
  If its in  in enforcing mode, Change the SELINUX value to SELINUX=disabled in       the file /etc/selinux/config.
(https://www.thegeekdiary.com/how-to-disable-or-set-selinux-to-permissive-mode/)

- Update Makefile (Line 15) from 
```
VOLUME_MOUNT=$(shell if test "$(go env GOOS)" = "darwin"; then echo ":delegated"; elif test selinuxenabled; then echo ":delegated"; else echo ""; fi)
```
To 
```
VOLUME_MOUNT=$(shell if test "$(go env GOOS)" = "darwin"; then echo ":delegated"; elif test selinuxenabled; then echo ":Z"; else echo ""; fi)
```

cc @chetan-rns , @sbose78

**Comment by jessesuen** [comment]
@Shraddhak22 Will you be submitting a fix? I assigned the issue to you

**Comment by Shraddhak22** [comment]
> @Shraddhak22 Will you be submitting a fix? I assigned the issue to you

@jessesuen ,Yes, I am working along with @chetan-rns on this issue, and hoping to have PR raise as soon as possible. Yes you can assign issue on my name. Thanks.

**Comment by aceamarco** [comment]
Were there any updates with this? I'm facing a similar issue where none of my certificates can be found — despite them being accessible on my computer.

**Comment by jgwest** [comment]
Anyone still able to reproduce? I've had no issue using Docker make targets on Fedora.
