### ISSUE TITLE
Summary legend overflow view

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4187]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The summary legend (especially `Progressing`) overflows the box containing the chart

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications?view=summary 
1. If necessary, zoom in/out to trigger the bug

**Expected behavior**

Text for a chart shouldn't flow outside the chart's box.

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/91491375-f1994380-e881-11ea-9d76-882869c485c4.png)

**Version**

v1.7.0+10d05cd

**Logs**

**Comment by keithchong** [comment]
Hi @jsoref, @jessesuen , I can take this.

/assign @keithchong

**Comment by keithchong** [comment]
This also can be reproducible simply by resizing the browser and making its width as small or narrow as possible.  This exposes another issue with the layout and the `Sync` legend overlaps with the `Health` pie chart.

![Screen Shot 2020-10-08 at 11 47 25 PM](https://user-images.githubusercontent.com/7726022/95541175-a7e36300-09c0-11eb-9fe8-9072d01784d5.png)

**Comment by keithchong** [comment]
Here is a demo of the proposed new layout.  Note that the summary section on the left side does not take as much space.

[4187-ResizeRelayout.zip](https://github.com/argoproj/argo-cd/files/5352425/4187-ResizeRelayout.zip)

Compare it with the current behaviour by going here:

https://cd.apps.argoproj.io/applications?view=summary

**Comment by keithchong** [comment]
Thanks for the thumbs up @jsoref.  @alexmt, if you like this new layout, I will submit a PR for it.

**Comment by alexmt** [comment]
Thank you for attaching the proposed layout video. It looks really good.
