### ISSUE TITLE
Applications fail to delete after cluster is removed/terminated

### ISSUE THREAD

**Issue by nxf5025** [argoproj/argo-cd#4198]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I had a few applications deployed using the apps of apps model in an EKS cluster that has since been terminated. Now that the cluster is gone I triggered the deletion of the apps from the argocd interface. These are stuck in deleting state

I see the following in the events log
```
Unable to delete application resources: Get "https://58BE80313EAF335A8EE546511C01D1B9.sk1.us-east-1.eks.amazonaws.com/version?timeout=32s": dial tcp: lookup 58BE80313EAF335A8EE546511C01D1B9.sk1.us-east-1.eks.amazonaws.com on 172.20.0.10:53: no such host
```

I then removed the cluster from argocd and now hit this:
```
Unable to delete application resources: rpc error: code = NotFound desc = cluster "https://58BE80313EAF335A8EE546511C01D1B9.sk1.us-east-1.eks.amazonaws.com" not found
```
Is there a way to force the cleanup?

**To Reproduce**

1. Provision EKS cluster
2. Deploy a set of apps
3. Terminate the EKS cluster
4. Delete the apps from argocd

**Expected behavior**

Apps will be deleted

**Version**

```
argocd: v1.7.2+c342d3f
  BuildDate: 2020-08-27T23:33:37Z
  GitCommit: c342d3fc9c9c9f0d1c18254b6ffa1e106984a76c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.2+c342d3f
  BuildDate: 2020-08-27T23:34:52Z
  GitCommit: c342d3fc9c9c9f0d1c18254b6ffa1e106984a76c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Comment by darshanime** [comment]
did you try using `Delete` without cascade?

**Comment by nxf5025** [comment]
@darshanime - That was it. Closing this issue. Thanks!
