### ISSUE TITLE
Argo Healthcheck stuck in "Progressing" for CRDs such as Istio

### ISSUE THREAD

**Issue by whitleykeith** [argoproj/argo-cd#4220]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x ] I've included steps to reproduce the bug.
* [ x ] I've pasted the output of `argocd version`.

**Describe the bug**

We deploy Istio with ArgoCD and we can see that the health status of the IstioOperator CRD (which we contributed the healthcheck a while back) will get stuck in "Progressing", even though the status of that resource should cause Argo to mark it as healthy.

We can resolve this by restarting the application controller. 

**To Reproduce**

Deploy Istio via Argo (I'm assuming this could also happen with other CRDs, but I haven't been able to reproduce it as easily as with Istio).

**Expected behavior**

Istio is marked as healthy when status.status: HEALTHY

**Version**

```shell
1.7.2
```

**Comment by whitleykeith** [comment]
Looking more into it it seems that this issue and (https://github.com/argoproj/argo-cd/issues/4166#issuecomment-683871453) may be symptoms of the same underlying cause.

**Comment by jessesuen** [comment]
> We can resolve this by restarting the application controller.

Right. This is a strong indication of the inconsistent cache problem that we've been seeing.

**Comment by jessesuen** [comment]
Duping to https://github.com/argoproj/argo-cd/issues/4053
