### ISSUE TITLE
Progress indicators in Argo CD UI

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#4227]
# Summary

Argo CD UI provides the ability to edit/sync application, change project settings, generate token etc. In a real-life environment, each operation might take 1~2 seconds. 

# Motivation

The UI should show a progress indicator to provide visual feedback that the operation is in progress. 

# Proposal

Sync button that triggers app synchronization already has good progress icon:

<img width="307" alt="Screen Shot 2020-09-01 at 12 48 30 PM" src="https://user-images.githubusercontent.com/426437/91899053-781e9e00-ec51-11ea-88b9-c0bad5510579.png">

Buttons that require progress indicator:

* Enable/disable auto-sync buttons:

![image](https://user-images.githubusercontent.com/426437/93822241-ca315e80-fc14-11ea-848f-2c63315f1cd8.png)

* Save button of `EditablePanel` [component](https://github.com/argoproj/argo-cd/blob/e28a3e5ed0181e45d27ec5534e8a7b191b3f1ca3/ui/src/app/shared/components/editable-panel/editable-panel.tsx#L69) (used in multiple places).

![image](https://user-images.githubusercontent.com/426437/93824737-c69fd680-fc18-11ea-8036-ac4ef35462eb.png)

**Comment by keithchong** [comment]
Hi Alex, where do you want to see the progress indicator?  Currently the sliding panel disappears after the sync button is pressed.

**Comment by keithchong** [comment]
Hi @alexmt, @jessesuen , the sync spinner on the application-sync-panel page appears to be different than the sync spinner that is on the application-status-panel.  The sync panel spinner looks like it represents the sync submission Post request (starts spinning on setPending(true)).  It stops spinning when the request returns. (setPending(false)).   However, the latter spinner could be spinning longer and reflects the actual sync operation.

The simple solution is to add the progress monitor to match the spinner that is on the Synchronize button.

What do you think?

**Comment by alexmt** [comment]
Hello @keithchong , 

Probably the description is confusing. The progress indicator should be shown while PATCH/PUT API request is in progress.

The `Synchronize` button click on sync panel triggers  `/api/v1/applications/apps/sync` that starts sync operation. The sync panel is closed after `/api/v1/applications/apps/sync` is completed. If Argo CD has a lot of applications then the  request might take 1~2 seconds. Due to this delay we need to provide some visual feedback. Please see attached video recoding.  [Screen Recording 2020-09-21 at 1.27.10 PM.zip](https://github.com/argoproj/argo-cd/files/5257979/Screen.Recording.2020-09-21.at.1.27.10.PM.zip)


Adding list of Argo CD pages that has the same issue and requires progress indicator.

**Comment by keithchong** [comment]
Hi @alexmt , yes, it makes sense.   I'm also going to add the spinner to the Add Repo connection sliding panel.

<img width="747" alt="ConnectToRepoUsingSSH" src="https://user-images.githubusercontent.com/7726022/93920150-c537e200-fcdc-11ea-93a7-076babfb7a85.png">

**Comment by keithchong** [comment]
Yeah, I was looking at the code for the sync operation. If that sync panel did not disappear (I made it so it did not hide), then the spinner on the synchronize button could potentially cause confusion because it could imply it's for the whole sync operation, and it would stop, whereas the sync spinner on the application page was still spinning.  I realized they are for two different things.

**Comment by keithchong** [comment]
Demo of enable/disable auto sync

[enableDisableAutoSync.zip](https://github.com/argoproj/argo-cd/files/5263846/enableDisableAutoSync.zip)

**Comment by keithchong** [comment]
Demo of save

[saveAppChanges.zip](https://github.com/argoproj/argo-cd/files/5263904/saveAppChanges.zip)

**Comment by keithchong** [comment]
Demo of connecting repo using HTTPS

[connectRepoUsingHttps.zip](https://github.com/argoproj/argo-cd/files/5264150/connectRepoUsingHttps.zip)

**Comment by alexmt** [comment]
All three changes look great! Thank you @keithchong . Looking forward to the PR

**Comment by keithchong** [comment]
Hi @alexmt , could you assign this to me? I created the PR.  Let me know if there could be other places you want a progress indicator. (I also looked at implementing a progress bar)
