### ISSUE TITLE
UI banner mechanism to announce messages

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#4230]
It would be useful to have a mechanism to announce things like maintenance, planned downtime, etc... to all users of an Argo CD instance.

**Comment by gaganhegde** [comment]
Hey @jessesuen , would like to address this issue.

**Comment by gaganhegde** [comment]
Hey @alexmt , Ive included a new component called ui-banner in the argo-ui library, would it be okay to exclude it from the gitignore and raise a PR?

**Comment by gaganhegde** [comment]
A PR for this issue has been raised https://github.com/argoproj/argo-cd/pull/4626 .

**Comment by gaganhegde** [comment]
Hi @alexmt , the comments in the PR have been addressed, kindly take a look and let me know if it needs any changes. thanks.

**Comment by gaganhegde** [comment]
Hi @alexmt @jessesuen @jsoref , can someone review this issue and let me know if it looks okay? Thank you  := )
