### ISSUE TITLE
Truncated synchronize check-boxes should have tooltips

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4233]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/prometheus-operator
1. click the ellipsis by prometheus-operator project
1. click sync
1. scroll down to ` MONITORING.COREOS.COM/SERVICEMONITOR/PROMETHEUS-OPERATOR/PROMETHEUS-OPERATOR`...
1. You can't see the full name of the item
1. You can't differentiate items at all

**Expected behavior**

* Ellipsis should be in the middle, not the end
* Tooltips for anything with ellipsis

**Screenshots**

![top](https://user-images.githubusercontent.com/2119212/91992998-d788b680-ed02-11ea-9827-e6967b0340fd.png)
![identical](https://user-images.githubusercontent.com/2119212/128762424-6d88f11e-cf9f-4c66-9111-0932b98668fe.png)

**Version**

```json
{
    "Version": "v2.1.0+3091bc5",
    "BuildDate": "2021-08-09T10:16:24Z",
    "GitCommit": "3091bc5b6f3d389376feaa999a63fc4986ae72a9",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

**Comment by ciiay** [comment]
@jsoref Hi, I checked out this issue and the check-box label is nicely wrapped in one line with 3 dots ellipsis now. Is a tooltip of the full label is needed for this scenario? If so, we can update this issue and I will work on it. Thank you!

**Comment by jsoref** [comment]
@ciiay: Thanks for checking, I've updated the steps (roughly) and expected results.

The ellipsis at the end is really a bad place for it. They should _probably_ be in the middle (or possibly the beginning? -- open to discussion, but I generally think middle is more common than beginning)

**Comment by ciiay** [comment]
@jsoref Thanks for the update. I have only seen the ellipsis at the tail of a long content. Do you have an image of your expectation as a reference?

**Comment by ciiay** [comment]
@jsoref Oh I think I got what you mean. You mean to show both the beginning and the ending of a content, and ellipsis the middle part of the content, right?

**Comment by ciiay** [comment]
Made a PR to add tooltip for resources and changed ellipsis from end to middle. Bellow screenshot is an example of how it looks like with the change.
<img width="568" alt="Screen Shot 2021-08-11 at 10 09 41 AM" src="https://user-images.githubusercontent.com/26255262/129044745-3c58f4a7-96b3-45e2-b083-cc168a2032a0.png">

**Comment by jsoref** [comment]
Looks pretty good, I'm a little puzzled by the `/SERVICE/` vs `APPS/` at the left for the two rows -- I'd expect them to have the same prefix (`/` or not at all).

**Comment by ciiay** [comment]
@jsoref The beginning of the resource is the real data from test app, I just chained a long string to the end of the original data to simulate a long resource string. Both of the format are very common in the demo app. Please refer this demo link to confirm. Thank you.
https://cd.apps.argoproj.io/applications/istio-operator?resource=kind%3ADeployment%2Ckind%3AService%2Ckind%3APod%2Ckind%3AStatefulSet%2Ckind%3AIngress%2Ckind%3AConfigMap%2Ckind%3AJob%2Ckind%3ADaemonSet%2Ckind%3AWorkflow&deploy=all

**Comment by jsoref** [comment]
ok, so, your picture is perfect.

---
It appears the notation is:

`[APIExtensionSpace]/{RESOURCE_TYPE}/[namespace]/{NAME}`

So, Kubernetes core resources don't have an `APIExtensionSpace` and thus appear to start with `/`, some things are global (e.g. Namespaces and ClusterRoles) and thus don't have namespaces and appear to have `//` later on.

At some point I'd like to know if this specific notation is an ArgoCD thing or a k8s thing. If it's the former, as an end user, I'm not sure I'm a fan.

Looking locally, the filters in the app view lets me filter by namespace, but the sync panel doesn't let me do anything by namespace (sort/filter). -- I'll probably file a bug about that at some point.
