### ISSUE TITLE
ellipsis should offer title tips

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4234]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/prometheus-operator?operation=true
1. Reset browser zoom (ctrl+`0`)
1. Click "Sync OK" (third box, well, it might say error or similar)
1. See `v1/Co... prometheus-operator argocd-dashboard-c... Syn... configmap/argocd-dashboard-cm unchanged`
1. Hover over the ellipsized fields hoping to see the content
1. Zoom out *four* times in order to see content.

**Expected behavior**

Hovering over the ellipsized fields should show content

**Screenshots**

![default zoom](https://user-images.githubusercontent.com/2119212/92000051-11f65180-ed0b-11ea-9197-bc402397ea00.png)
![zoom out four times](https://user-images.githubusercontent.com/2119212/92000338-6a2d5380-ed0b-11ea-811b-9ee357fd9f13.png)

**Version**

v1.7.0+7ead934

**Logs**

**Comment by tetchel** [comment]
this looks like a good first issue; I will add `titles` to the items in this table.

**Comment by tetchel** [comment]
sorry for the commit spam. PR is https://github.com/argoproj/argo-cd/pull/4310

**Comment by tetchel** [comment]
I believe this can be closed

**Comment by jsoref** [comment]
![image](https://user-images.githubusercontent.com/2119212/93156748-c1053680-f6d6-11ea-8bdd-4f4fb3bf1418.png)
