### ISSUE TITLE
Failed manifest generation protection

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#4238]
# Summary

The manifest generation using kustomize/helm/ksonnet is time-consuming. Argo CD relies on manifest caching to save time and avoid making unnecessary git requests. In manifest generation files due to error in Application spec or invalid configuration in the manifest repository then manifests are not cached and repo-server tries to perform full generation every app reconciliation. 

# Motivation

The repo-server should cache manifest generation errors and return previously happened error, instead of attempting to generate manifest.

# Proposal

Repo-server should cache both generated manifests and errors that happened during the generation. Cached errors should be returned instead of trying to generate manifest again.  The errors might be transient, so the cached error should be returned based on number of failed attempts and time since last failure.

**Comment by jessesuen** [comment]
Workaround is to delete applications which are a bad (Unknown) state due to git manifest generation issues.

**Comment by jgwest** [comment]
@alexmt I'll handle this one
