### ISSUE TITLE
Rework local authentication to expire tokens when password is updated

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#424]
Currently, when logging in as a local user, a signed JWT token (by API server) is stored on the user's system. The problem is that this token has no expiration and is valid for eternity, even after a password update.

Instead of having storing the token, we should store the plaintext username/password which will be supplied as base64_encode("username:password") token, in lieu of the JWT session token. This will allow revoking of access and password rotation, while also be friendlier to automated systems.

~When users login via SSO via CLI, we should be giving the dex signed token (which expires), and stop issuing API server signed tokens (which don't expire). When tokens do expire, we need to allow the token to be refreshed as conveniently as possible. Re-logging in should be convenient as well.~ @merenbach took the liberty of breaking this out into #455 so the scope on this ticket is just local auth tokens

**Comment by merenbach** [comment]
@jessesuen question about a possible alternative implementation that won't leave password essentially in plaintext on workstation:

1. Set expiration for tokens, say 30 days.
2. Add token revocation list to server that can be modified only by the superadmin.
3. Whenever token comes in, if it's not expired, it also gets checked against token revocation list.  If it's there, access is denied anyway.
4. If token passes token revocation list check, allow access.

**Comment by jessesuen** [comment]
I rather not complicate the implementation. How/where would you propose storing the revocation list?  It also still has the downside of expiring (albeit for 30 days). Plaintext passwords is how and kuberenetes stores credentials in their kubeconfigs. Docker and git store plaintext passwords as well but they are stored in OSX keychain as well (another complication I would like to avoid). Would you be more comfortable if what was stored was the bearer token base64_encode("username:password") instead of plaintext username password?

**Comment by jessesuen** [comment]
The agreement is that we will continue to use JWT tokens, but additionally keep track of an password mtime (which is the last modification timestamp of a password). If the issued at of a JWT token is earlier than the mtime, the JWT is invalid.

Optimization: I would prefer if we could cache the mtime so that we don't keep hitting etcd on all calls.
