### ISSUE TITLE
replicaset children of deployment should sort by revision

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4249]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Right now, replicaset children of deployments are sorted alphabetically by replicaset name.
Each replicaset has a revision (`rev`), it would be immensely helpful if they were sorted by that before sorting by name.

**To Reproduce**

1. Have a deployment with a replicaset with multiple revisions
1. Publish a bunch of new revisions
1. Look at graph and see things in a fairly randomized order -- namely they are sorted by replicaset name and not rev

**Expected behavior**

Sort first by `rev` and then by `name`

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/92048697-5b1fc300-ed56-11ea-87fc-02768b3e7622.png)

**Version**

v1.6.1+159674e

**Logs**

**Comment by josecv** [comment]
This same issue seems generally applicable to e.g. `ControllerRevision`s but also operator-managed resources such as argo-rollouts' `AnalysisRun`s

**Comment by jsoref** [comment]
@josecv: I think that my PR isn't actually specific to ReplicaSets, it should work for those as well (please review/test).
