### ISSUE TITLE
Argocd persistent storage

### ISSUE THREAD

**Issue by DekelMalul** [argoproj/argo-cd#4255]
Hey guys, I have a problem with the Argocd installment.
I installed the Argocd accordingly to the docs and it worked perfectly.
I created test project and changed the admin password but when I rolled the Argocd pods it restarted my configuration and I needed to start over.
I searched how to map PVC to the relevant pods but couldn't find effective information. 

**To Reproduce**

I took the steps mentioned in https://argoproj.github.io/argo-cd/getting_started/ to install Argocd.
After restarting the pods my configuration was deleted.

**Expected behavior**
My configuration will be saved

Thanks for any help

**Comment by jessesuen** [comment]
Argo CD is mostly stateless and relies on etcd for persistence. We do not use PVCs. 

> when I rolled the Argocd pods it restarted my configuration and I needed to start over.

Can you elaborate ?

**Comment by DekelMalul** [comment]
> Argo CD is mostly stateless and relies on etcd for persistence. We do not use PVCs.

So if my Argo CD deployment will go down I will need to start over?
reconfigure all my projects and so on?

> when I rolled the Argocd pods it restarted my configuration and I needed to start over.

I wanted to check if my configuration will be saved if Argo CD deployment will go down. So I deleted all the relevant deployments and reapply them. I was really surprised that my configurations have been deleted. 
Is there a way to make Argo CD stateful?

**Comment by alexmt** [comment]
Argo CD configuration is stored in K8S resources: Application and Projects are CRDs, repository, and cluster credentials are stored in Secrets/ConfigMaps. So configuration does not disappear even if all Deployments get deleted and re-created.

**Comment by DekelMalul** [comment]
Thanks very much

**Comment by dariodsa** [comment]
yes

**Comment by codechirag5610** [comment]
@alexmt if they do not get removed in the first place why did @DekelMalul faced redeploying all the projects again? I mean when @DekelMalul rolled out argocd, why were all the deployments gone?

**Comment by kingbj940429** [comment]
I wondered too.

thank you!
