### ISSUE TITLE
Document cost considerations

### ISSUE THREAD

**Issue by dcherman** [argoproj/argo-cd#4256]
When looking at my monthly AWS bill, I noticed that my ec2-other has spiked by a few hundred dollars.  Looking into it further, it was primarily Inter-AZ data transfer costs.  Looking at the bandwidth usage of some of the deployments, I've noticed that with even a relatively small number of applications, I'm seeing pretty high sustained bandwidth on the redis/application controller deployments.

I'm wondering if we should document that for cost considerations, you might want to consider scheduling certain deployments in the same AZ.

Also I haven't looked into this to see whether ArgoCD does or doesn't do compression for requests between those services (and maybe compression of the objects in Redis itself), but that's something we might want to consider as well if it's not already implemented.

**Comment by dcherman** [comment]
Looking at Redis, the values stored there are pretty hefty and are not currently compressed.  It looks like by updating the redis client and redis cache implementations, we might get that for free since v8 includes support for it.

I'll upgrade that and test upgrading from an existing ArgoCD installation (uncompressed cache) to the new one that I'm building (with cache compression) to make sure the upgrade will be seamless for users.  It should be since it looks like the redis cache lib detects whether or not compression was used.

**Comment by jessesuen** [comment]
Can we make sure this compression is opt-in configuration? For local redis installations, it's probably not worth any potential performance hits.
