### ISSUE TITLE
List view is missing letters/words

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4262]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

List view icons have no letters/words, unlike tree view

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/argoproj?resource=&view=list
1. See randomly arranged unlabeled glyphs

**Expected behavior**

**Screenshots**

![no letters](https://user-images.githubusercontent.com/2119212/92195576-5e40af00-ee3b-11ea-861d-40cb9b00ffb0.png)
![letters](https://user-images.githubusercontent.com/2119212/92195604-68fb4400-ee3b-11ea-9294-e977a54bf65a.png)

**Version**

v1.7.0+bae5f93

**Logs**

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/4266 . Thank you @jsoref !

**Comment by jsoref** [comment]
I'll need to file another bug about the `listview is missing letters/words` -- I couldn't figure out an easy way to do that. I suspect it'd involve refactoring a component.
