### ISSUE TITLE
AKS external cluster cannot be added via the CLI

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [argoproj/argo-cd#4264]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have deployed Argo CD in an AKS cluster and things are working fine. When I wanted to add another external AKS cluster using the CLI via the command `argocd cluster add <context>` I got the error "no Auth Provider found for name \"azure\"". This is probably due to the azure client plugin not being included.

**To Reproduce**

Try to add an AKS cluster with azure based cluster-user authenticaltion strategy

**Expected behavior**

AKS clusters with azure auth getting added

**Version**

```shell
argocd: v1.7.2+c342d3f
  BuildDate: 2020-08-27T23:37:21Z
  GitCommit: c342d3fc9c9c9f0d1c18254b6ffa1e106984a76c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: windows/amd64
argocd-server: v1.7.2+c342d3f
  BuildDate: 2020-08-27T23:34:52Z
  GitCommit: c342d3fc9c9c9f0d1c18254b6ffa1e106984a76c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Comment by SayakMukhopadhyay** [comment]
I believe that the `"k8s.io/client-go/plugin/pkg/client/auth/azure"` needs to be added here https://github.com/argoproj/argo-cd/blob/c342d3fc9c9c9f0d1c18254b6ffa1e106984a76c/cmd/argocd/main.go#L9

**Comment by SayakMukhopadhyay** [comment]
A cursory look gives me more places that this plugin could be added
https://github.com/argoproj/argo-cd/blob/fe8d47e0eae9fe5bd9dbcf52ca898fe4b4ba9ce1/cmd/argocd-server/main.go#L9
https://github.com/argoproj/argo-cd/blob/c342d3fc9c9c9f0d1c18254b6ffa1e106984a76c/hack/dev-mounter/main.go#L25
https://github.com/argoproj/argo-cd/blob/fe8d47e0eae9fe5bd9dbcf52ca898fe4b4ba9ce1/cmd/argocd-application-controller/main.go#L19
https://github.com/argoproj/argo-cd/blob/fe8d47e0eae9fe5bd9dbcf52ca898fe4b4ba9ce1/cmd/argocd-util/main.go#L37

I can create a PR adding the plugins in the above files. Let me know if adding the plugins only is enough.

**Comment by munjalpatel** [comment]
Hello,

I am running into this issue. Which build is this fix part of?
I just deployed the latest argo (1.7.5): https://hub.docker.com/layers/argoproj/argocd/v1.7.5/images/sha256-355e86fd22acd52a22e020ef761d47e8b87cd09d6940861bd6ca956837682be3?context=explore
I still have the same issue:
```
FATA[0000] no Auth Provider found for name "azure"
```
