### ISSUE TITLE
argo repo server no such host error while running on ec2 

### ISSUE THREAD

**Issue by sivaguru-nathan** [argoproj/argo-cd#4279]
ENV: **ec2**    , accessed by **LoadBalancer**
version:**1.6.2**

while trying to create an app, initially faced "**client: time out exceeded error**"
![Screenshot from 2020-08-25 11-33-37](https://user-images.githubusercontent.com/42261571/91187725-1bc9f480-e70e-11ea-8928-eb0e4e0d7ddc.png)

checked cloning repo inside argocd-server, argocd-repo-server not able to clone

changed DNSpolicy of all the deployment pods to Default. then able to clone inside container. but facing "**transport: Error while dialing dial tcp: lookup argocd-repo-server on 172.31.0.2:53: nosuch host**"

![Screenshot from 2020-08-25 18-44-09](https://user-images.githubusercontent.com/42261571/91187716-18cf0400-e70e-11ea-9e4a-d95ea9bb562a.png)

could anyone help me to solve this problem!!!

_Originally posted by @sivaguru-nathan in https://github.com/argoproj/argo-cd/issues/1510#issuecomment-680092047_

**Comment by nvthuong1996** [comment]
i has same issuse

**Comment by LDeemo** [comment]
have you sovled? bro

**Comment by g13013** [comment]
same issue with message 

![image](https://user-images.githubusercontent.com/2730430/115586448-809d1500-a2c4-11eb-815e-6bdb1a337600.png)

I got the same error when running on local with microk8s and decided to try on aws with a cluster installed with kubespray

**Comment by MrMYHuang** [comment]
> same issue with message
> 
> ![image](https://user-images.githubusercontent.com/2730430/115586448-809d1500-a2c4-11eb-815e-6bdb1a337600.png)
> 
> I got the same error when running on local with microk8s and decided to try on aws with a cluster installed with kubespray

I fix this error with microk8s on Ubuntu 20.04 on WSL2 on Windows 11.
The document https://argo-cd.readthedocs.io/en/stable/getting_started/
said one requirement for Argo CD is: Have a kubeconfig file (default location is ~/.kube/config).
Thus, I generated one by `kubectl config view --minify > ~/.kube/config`
Then, I restarted WSL2: `wsl --shutdown` then `wsl`. (I am not sure if this step is required)
Please try to create an app with Argo CD again :)

**Comment by MrMYHuang** [comment]
> same issue with message
> 
> ![image](https://user-images.githubusercontent.com/2730430/115586448-809d1500-a2c4-11eb-815e-6bdb1a337600.png)
> 
> I got the same error when running on local with microk8s and decided to try on aws with a cluster installed with kubespray

[Update]

I fix this error with microk8s on Ubuntu 20.04 on WSL2 on Windows 11.
Please try this: `microk8s enable dns && microk8s stop && microk8s start`
Then, please try to create an app with Argo CD again :)

**Comment by jgwest** [comment]
Closing as this is likely a very old cluster-specific issue. Anyone encountering this error should investigate the network configuration of their cluster; the configuration of which will differ based on K8s installation mechanism and vendor.
