### ISSUE TITLE
Controller horizontal scaling

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#4284]
# Summary

The application controller is the only Argo CD component that cannot have multiple replicas. Allow to scale up Application Controller to increase the number of clusters on Argo CD can manage. 

# Motivation

Currently number of managed clusters is limited by the amount of memory allowed to one controller instance. It is impossible to grow memory infinitely. Instead, it should be possible to shared clusters among multiple controller replicas.

# Proposal

The Application controller should be converted to a StatefulSet and each replica should handle only a subset of clusters and related applications.

**Sharding method**

Cluster size is not known ahead of time so it is not easy to implement a good sharding method that guarantees well-balanced distribution. Looks like we have two possible options:

1. Dynamic sharding based on cluster size. Controllers should "claim" clusters one by one, evaluate the number of resources in each cluster. This approach should provide better clusters distribution but significantly more difficult to implement and might require some coordination between controller replicas.

2. Simple sharding.  Sharding function might looks like `shard = hash(clusterSecret.metadata.UID) % replicas`.  This should work well if the controller manages a lot of mid-size clusters but won't work if there are several very large clusters, different from others. To address that it should be possible to manually "assign" cluster to the shard.

**Comment by alexmt** [comment]
As a first step I want to start with option 2 but keep the door open for option 1.

High chance that option 1 is just enough. The manual shard assigning allows handling edge cases and we can "automate" it as a next step: periodically Argo CD can evaluate the list of cluster and assign shards to controller replicas. I think this is less error-prone and easier to troubleshoot.

**Comment by vjove** [comment]
This is a very nice addition. Unfortunately it won't help in our case where we have a single cluster with +1000 apps.
Another idea is to allow selecting a specific controller in the App resource by means of an annotation (similar to sync-wave).
If Apps are generated automatically from a process (like in our case), then we could implement a more suitable sharding strategy.

**Comment by eddycharly** [comment]
> This is a very nice addition. Unfortunately it won't help in our case where we have a single cluster with +1000 apps.

We are in the same situation. Is there a specific reason not to distribute the load across replicas regardless of the cluster the app belongs to ?
