### ISSUE TITLE
Helm hook is looping indefinitely

### ISSUE THREAD

**Issue by MrFreezeex** [argoproj/argo-cd#4289]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When I deploy [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/) a job (https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml) in pre-upgrade/pre-sync is created, completed, deleted, created, completed, deleted and so on indefinitely.

**To Reproduce**

Deploys [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/) with default settings.

**Expected behavior**

The job should be executed once and deleted afterwards.

**Version**
1.7.4

**Comment by jessesuen** [comment]
Helm hook delete logic was modified in v1.7, possible regression.

**Comment by mayzhang2000** [comment]
I just tried deploy kube-prometheus-stack using ArgoCD 1.7.4 and got sync OK.
![image](https://user-images.githubusercontent.com/7737306/92665983-dcc6a200-f2bc-11ea-81cf-0a836ef9531f.png)

**Comment by MrFreezeex** [comment]
> I just tried deploy kube-prometheus-stack using ArgoCD 1.7.4 and got sync OK.
> ![image](https://user-images.githubusercontent.com/7737306/92665983-dcc6a200-f2bc-11ea-81cf-0a836ef9531f.png)

Hmm I'm confused when I added webhooks to my existing deployment the hook did loop indefinitely so I assumed It would also appears on a new deployment.  It seems that my argo application was in a weird state. I can't reproduce this behavior after a deletion/creation.

Sorry for this issue. I'm closing it and will reopen If I find a way to replicate it from scratch (and will double check the reproduction path this time).
