### ISSUE TITLE
/api/v1/applications takes significant amount of time 

### ISSUE THREAD

**Issue by cedricboesiger** [argoproj/argo-cd#4296]
**Describe the bug**
The application list page uses GET /api/v1/applications?fields=... which, depending on the number of projects holding OIDC groups, requires more time to answer the request. 
In our environment, it already takes between 12s-14s to answer the request.

![network-duration (1)](https://user-images.githubusercontent.com/22166798/92691652-278afd00-f343-11ea-84e5-d2af6ae705bd.png)

We count:
- Between 50 to 70 OIDC groups per user
- 25 Appprojects each with 2 roles with up to 10 policies that are assigned to 1 oidc group.
- 215 Applications
- We use v1.5.6 in production
 
**To Reproduce**

- Create an empty ArgoCD installation, v1.7.4
- Create a couple 100 Appprojects, each with 2 roles that are assigned to an OIDC group
- Create a couple 100 Applications assigned to the Appprojects
- Use an OpenID User to login
- Check that the response time from /api/v1/applications in the browser console increases with the number of projects with assigned groups.

**Expected behavior**

A response time that is less dependent on the number of applications, projects and groups involved.

**Comment by alexmojo** [comment]
Same issue, we are using v1.7.4

**Comment by alexmojo** [comment]
Also, I've notice, that if login using built-in account to the same api server response more quickly.

**Comment by alexmojo** [comment]
We have about 800+ applications in 2 clusters.
My results with SSO login and RBAC:
![argocd1](https://user-images.githubusercontent.com/10939496/93365263-3d705480-f852-11ea-91a7-e7d68dcf0110.jpg)

Using built-in administrator account:
![argocd2](https://user-images.githubusercontent.com/10939496/93365609-af489e00-f852-11ea-9ed9-b92cdfc94a6b.jpg)

**Comment by jessesuen** [comment]
NOTE: The admin is special because it has no groups and therefore enforcement is simpler.

> Between 50 to 70 OIDC groups per user

I think we need an optimization to use a temporary map to lookup oidc groups rather than current implementation to iterate the groups list

**Comment by kshamajain99** [comment]
Looking into this.

**Comment by rbreeze** [comment]
https://github.com/argoproj/argo-cd/pull/5342 is a workaround for this, but ideally we should still implement a map for OIDC group lookup

**Comment by rbreeze** [comment]
Discussed with @jessesuen and we feel pagination addresses the user experience of slow loading apps.

**Comment by alexmt** [comment]
Hello @cedricboesiger, @boskoop  ,

The v2.1 has a optimization that is supposed to significantly improve API server performance. The change is available in  https://github.com/argoproj/argo-cd/releases/tag/v2.1.0-rc1. Can you give it a try please?

**Comment by alexmt** [comment]
Closing and will reopen if someone reproduce issue again

**Comment by limoges** [comment]
We had very high hopes that this would be fixed with v2.1 and I've come around to making the update to v2.1.2.

Unfortunately, the performance issue is still there. I didn't measure before the update but I don't notice any difference.
![image](https://user-images.githubusercontent.com/281221/132847772-7f6da6c9-f15b-41fb-8d0f-b65669303363.png)

We have ~1000 applications.

**Comment by matoous** [comment]
Can confirm, the load time is still slow
<img width="696" alt="Screen Shot 2021-09-10 at 13 56 04" src="https://user-images.githubusercontent.com/15747583/132850020-4b5d41f2-e497-4d9b-8b3d-2d41953e9155.png">

**Comment by alexmt** [comment]
Thank you @matoous and @limoges ! Reopening ticket. Will attack it in 2.2 again

**Comment by alexmt** [comment]
@yydzhou the API was improved in v2.2. During performance testing, we've reduced API response time from 10 seconds to ~0.5 seconds. Can you please give it a try?

**Comment by amitde69** [comment]
still happens on v2.3.3 with 23 clusters and 1612 applications.

**Comment by wgzhao** [comment]
still happens on v2.4.6 with 10 clusters and 50 applications

**Comment by sidewinder12s** [comment]
With v2.4.17 it can still take 5+ seconds for 1000+ apps to load

**Comment by jujubetsz** [comment]
Same here. 3k+ apps, 1 cluster, v2.4.11

Sometimes it take 30s+ :sad:

**Comment by crenshaw-dev** [comment]
Would y'all be willing to test this? https://github.com/argoproj/argo-cd/pull/11884
