### ISSUE TITLE
Refresh dropdown arrow doesn't do anything

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4304]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Clicking the drop down arrow next to Refresh dismisses the menu instead of showing a submenu.

**To Reproduce**

1. https://cd.apps.argoproj.io/applications/jenkins
1. Click the ⋮ next to the jenkins application
1. Click the ▼ next to Refresh

**Expected behavior**

Show a submenu

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/92803737-b3257d80-f385-11ea-86a0-82f624c99df6.png)

**Version**

v1.7.0+41ca6b2

**Logs**

**Comment by jessesuen** [comment]
https://github.com/argoproj/argo-cd/issues/1524
