### ISSUE TITLE
Swagger document is out of sync with API

### ISSUE THREAD

**Issue by Woland2k** [argoproj/argo-cd#4314]
**Describe the bug**

{"Error converting value 7/14/2020 6:53:50 PM to type 'Models.V1Time'. Path 'items[0].metadata.creationTimestamp'

The swagger documentation defines timestamp as:

```
"creationTimestamp": {
  "nanos": 0,
  "seconds": "string"
}
```

however the api returns just a date value in the following format:

`"creationTimestamp" : "2020-08-10T15:29:35Z",`

This breaks API generated from swagger since types don't match.

**Comment by jessesuen** [comment]
We use the kubernetes openapi gen to generate the swagger from the kubernetes types. So the bug would be with the generator. We should see if theres a newer version that addresses incorrectly generated swagger. 

Either that, or we perform some surgery on the swagger after the generation stage, ideally automated.

**Comment by andreasschramm** [comment]
there are more discrepancies, the swagger.json does not contain any info about auth, and the V1alpha1ResourceNode Type does not match the object the apis delivers... i see the codegen is pulled from an old version, something tells me that there are some dragons sleeping there...

**Comment by Roshick** [comment]
Just ran into this issue which is quite annoying as our service automatically generates the necessary models from the openapi specification and we need to fix it manually afterwards now.

**Comment by mmerrill3** [comment]
I ran into this issue as well.  Temporarily, I just updated the filed that were defined as v1Time object, to type string and format date-time.  I was using swagger codegen from the swagger.json as well.

**Comment by lalitmathwani** [comment]
+1 - we ran into this @ adobe as well on our roll out of argo.

**Comment by crenshaw-dev** [comment]
Does anyone have time to investigate one or both of these?

- v1Time object being returned as string
- v1alpha1ResourceNode response doesn't match the spec

I'd be happy to help w/ dev env. and review a PR.

**Comment by spjmurray** [comment]
Of note, I have written stuff in the past where you generate the internal data types from the schema, and then you are never out of sync.  Just a thought, given I cannot see anything that is doing this (could have missed something!)  I do hold my hands up here and admit the generated code was a little clunky at times, so it may be more trouble than it's worth.

**Comment by pourgholi** [comment]
I ran into this issue either. Generated java code by using open-api code generator and there is exactly the same type mismatch.
