### ISSUE TITLE
No error/warning condition if application destination namespace not monitored by Argo CD

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#4329]
**Describe the bug**

No error is shown If the cluster is connected in "namespaced" mode and application is trying to a namespace that is not listed in a cluster configuration. 

**To Reproduce**

1. Add cluster in a namespaced mode

```
argocd cluster add <my-context> --namespace default
```

2. Create an application that deploys resources to any different namespace. 
3. No error message is shown and all resources are shown as out-of-sync even if resources exist.

**Expected behavior**

Error message that explains that namespace is wrong should be shown.

**Version**

```shell
v1.7.4
```

**Comment by jopit** [comment]
Hi @alexmt, based on your comment in my PR (https://github.com/argoproj/argo-cd/pull/4352#pullrequestreview-490200148) I've been experimenting with a change to the `GetManagedLiveObjs` method in the gitops-engine project

https://github.com/jopit/gitops-engine/blob/af9eedc5e8485a3098405f9758ff27f69595cb65/pkg/cache/cluster.go#L679

When an application is created in a non-managed namespace (if that's the correct terminology), an error shows up on the application page

<img width="646" alt="Screen Shot 2020-09-22 at 4 47 45 PM" src="https://user-images.githubusercontent.com/29612372/93936638-75651500-fcf4-11ea-9845-6073de14cea1.png">

and when you click on the error, it show this message

<img width="941" alt="Screen Shot 2020-09-22 at 4 47 59 PM" src="https://user-images.githubusercontent.com/29612372/93936798-b65d2980-fcf4-11ea-9f37-a45ac7af904f.png">

Is this sort of what you had in mind for this?

**Comment by alexmt** [comment]
That looks correct @jopit. Can you please create PR to gitops-engine ?

**Comment by jopit** [comment]
PR is https://github.com/argoproj/gitops-engine/pull/143
