### ISSUE TITLE
In Network view, pods in same column as service

### ISSUE THREAD

**Issue by eric-intuit** [argoproj/argo-cd#4330]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x ] I've included steps to reproduce the bug.
* [ x ] I've pasted the output of `argocd version`.

**Describe the bug**

UI issue in Network view. 

When a pod is not associated with a service, it's aligned with service UI elements. It looks a bit strange and confusing. It makes it harder to find the pod.

**To Reproduce**

Create an argo cd with pods associated with service/s and also pods not associated a service.

**Expected behavior**

Pods should be aligned with other pods.

**Screenshots**

![image](https://user-images.githubusercontent.com/38798010/93143815-8af79080-f69d-11ea-8aac-04ab6b4777ff.png)

**Version**

```shell
v1.7.4+4c715cf.dirty
```

**Logs**

```
N/A
```

**Comment by keithchong** [comment]
Hi @jessesuen , I can investigate this one.

**Comment by keithchong** [comment]
Hi @alexmt / @jessesuen , the Dagre layout does not let you control the position of nodes directly or easily.  See issue 258 in https://github.com/dagrejs/dagre/issues/

Although, I do have an initial first pass at a solution but it's far from ideal.

(BTW, why don't we make Pods a different color? Something to bring up in the UX meeting, perhaps?)

Before/Current:
<img width="1362" alt="Screen Shot 2021-02-10 at 4 01 09 PM" src="https://user-images.githubusercontent.com/7726022/107572066-bed9d200-6bb9-11eb-835a-a6b3fbadc1c3.png">

After:
<img width="1330" alt="Screen Shot 2021-02-10 at 4 00 55 PM" src="https://user-images.githubusercontent.com/7726022/107572084-c4371c80-6bb9-11eb-8475-1c18cddf12af.png">

**Comment by jessesuen** [comment]
We are going to actually go a different route and group pods as a workload. It should be still right justified, however. Will dup it to https://github.com/argoproj/argo-cd/issues/5468.
