### ISSUE TITLE
Rethink page title construction

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4337]
# Summary

Favor the current application/object over the brand of argocd.

# Motivation

Imagine you have a bunch of argocd tabs open:

1. https://cd.apps.argoproj.io/applications/cert-manager?resource=&conditions=true
1. https://cd.apps.argoproj.io/applications/prometheus-operator
1. https://cd.apps.argoproj.io/applications/nginx-ingress
1. https://cd.apps.argoproj.io/applications/jenkins
1. https://cd.apps.argoproj.io/applications/argo-cd
1. https://cd.apps.argoproj.io/settings/certs
1. https://cd.apps.argoproj.io/settings/clusters
1. https://cd.apps.argoproj.io/settings/accounts

What you see is this:
![image](https://user-images.githubusercontent.com/2119212/93248147-767acd00-f75d-11ea-8da0-1ab8696b2e3f.png)

We run multiple disparate instances of ArgoCD, and the domain of a given instance isn't included at all.
The least important thing to me in the page title is `Argo CD` as the favicon (which I'm unlikely to change) already tells me that.

# Proposal

1. Roughly reverse the structure of the page title.
    > From `Argo CD - Settings / Cluster` to `Cluster Settings (Argo CD)`
    > From `Argo CD - Applications / Jenkins` to `Jenkins Application (Argo CD)` (the `s` in `Applications` should kind of go away)

    Note that this also applies to `Argo - Workflows`

1. Consider making it easy to include a site specific detail - e.g. "alpha", "bravo", "charlie" (I don't want to give a specific example, but imagine that instead of hosting `jenkins` as https://cd.apps.argoproj.io/applications/jenkins it was hosted as https://cd.jenkins.argoproj.io/applications/jenkins and thus was distinct from the argo running on https://cd.apps.argoproj.io

**Comment by jessesuen** [comment]
Both ideas sound nice to have. Feel free to submit a PR

**Comment by alexec** [comment]
I think this is a good idea. I expect you'll then discover many pages have titles that need changing! @alexmt
