### ISSUE TITLE
Logs should favor containers over init containers

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4345]
# Summary

Default active log for pods should not be an init container log.

# Motivation

Init Containers are rarely interesting if the application is running, and thus if a user is visiting a pod which has an active app, they probably want to see the log for the running app.

# Proposal

While init containers should be listed first in pod details (i.e. unchanged from today), the default log that should be opened is the first (non init) container log with output. If there isn't any output in any of them, then fall back to the last init container with output.

# Steps

1. Visit a pod, e.g. [argocd-redis-ha-server-2](https://cd.apps.argoproj.io/applications/argo-cd?resource=kind%3APod&node=%2FPod%2Fargocd%2Fargocd-redis-ha-server-2%2F0)
1. Click [logs](https://cd.apps.argoproj.io/applications/argo-cd?resource=kind%3APod&node=%2FPod%2Fargocd%2Fargocd-redis-ha-server-2%2F0&tab=logs)
1. See 
![image](https://user-images.githubusercontent.com/2119212/93275533-2ca8db80-f78b-11ea-86e4-6eb2c6a00b7f.png)
1. You have to click on [Redis](https://cd.apps.argoproj.io/applications/argo-cd?resource=kind%3APod&node=%2FPod%2Fargocd%2Fargocd-redis-ha-server-2%2F1&tab=logs) to get something vaguely interesting: 
![Redis](https://user-images.githubusercontent.com/2119212/93275559-3c282480-f78b-11ea-8308-8a96b1d50090.png)

**Comment by jessesuen** [comment]
Definitely
