### ISSUE TITLE
CREATED_AT time in local time

### ISSUE THREAD

**Issue by gochist** [argoproj/argo-cd#4347]
# Summary

Please display CREATED_AT time in local time

# Motivation

I would like Argo CD to display the time the k8s object was created in local time. Currently, it is displayed in UTC as shown below.

![Screenshot_2020-09-16 Argo CD - Applications cmp-console-dev9](https://user-images.githubusercontent.com/282159/93317880-f0d44b80-f848-11ea-9ba5-ff4be6074d25.png)

**Comment by tetchel** [comment]
https://github.com/argoproj/argo-cd/pull/4386

**Comment by gochist** [comment]
Fixed in #4383
