### ISSUE TITLE
Support GitHub organization app for git cloning.

### ISSUE THREAD

**Issue by jetersen** [argoproj/argo-cd#4348]
# Summary

Instead of using username, password/token or ssh deploy keys.
It would be nice to support GitHub apps.

Much like
https://github.com/jenkinsci/github-branch-source-plugin/blob/master/docs/github-app.adoc

# Motivation

Reduce complexity in have multiple repos argocd can access across an GitHub organization

# Proposal

Could be implemented using https://github.com/bradleyfalzon/ghinstallation

**Comment by jessesuen** [comment]
Is GitHub apps an authentication protocol specific to GitHub.com (in lieu of username/pass, SSH keys) ? Currently we aren't supporting vendor specific protocol outside of what native git CLI can support. Also, we rely on a golang git client library, so support may need to be added there.

Also, are you aware that you can configure a central credentials to access multiple repos?

**Comment by jetersen** [comment]
one you have a github app installation token with the proper authentication. You can pass that token to the git clone url.

See here: https://github.blog/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/

**Comment by jetersen** [comment]
I'd like to avoid creating a github user with access to our repos as that would cost on licensing.
Much easier to add support for GitHub apps authentication and there should be no modification to the git client library.

**Comment by jetersen** [comment]
I would be happy to work on the feature 👍 In the upcoming month, Hacktoberfest 😉

**Comment by jessesuen** [comment]
> git clone https://x-access-token:<token>@github.com/owner/repo.git

If this is possible, then Argo CD should be able to do this today, by simply configuring it with username: `x-access-token` and password `<token>`.

In fact, internally we already use github access tokens to clone our users and not real github users.

**Comment by jetersen** [comment]
I don't want to provide a personal access token. That is bound to not have access to a org after that guy leaves the company.

**Comment by jessesuen** [comment]
Actually that wasn't my point. The fact that 
```
git clone https://x-access-token:<token>@github.com/owner/repo.git
```
works, implies that basic username/password cloning is possible, which we already support Argo CD. You simply need to configure the repo with username password credentials.

**Comment by jetersen** [comment]
We will need to provide a private key (RSA pem format) and github app id to do the initial authorization of getting a token to clone with.

**Comment by darshanime** [comment]
The issue is that the token created by using the jwt token (encoded with the github app's private key) has an expiry of 1 hour only. So, without explicit support of Github apps in ArgoCD, users will have to write external logic that will regenerate the token and update `argocd-cm` every hour.

**Comment by hendrikmaus** [comment]
Please see https://github.com/argoproj/argo-cd/issues/3086#issuecomment-712826175 - I have started working on the integration, but am quite uncertain if the code would be accepted at all due to its github-specific nature.

**Comment by jetersen** [comment]
We already have vendor specific webhooks in code. Why stop there. If Bitbucket or Gitlab users are interested in adding additional support for authentication they should be welcome to contribute the support?

if it is not possible, than ArgoCD should offer some sort of extensible model where the community can add in features.

**Comment by darshanime** [comment]
seems fair to include it IMO. 
@jessesuen @alexmt @jannfis thoughts?

**Comment by jannfis** [comment]
I can definitely see the use case, and looking at #3086 also the demand for this feature. 

I think it might be worth to explore a more generic approach to get an authentication token for Git, so it could also be extended to other providers that use similar mechanisms. IMHO, a possible implementation should already be designed generic enough to consider the possibility of other similar auth providers (i.e. get an access token from a set of credentials) and the overall design should not be custom-tailored for GitHub apps only. But I put that up for discussion, maybe it would be over-engineered.

One major challenge I see is that these tokens will expire after a maximum of 10 minutes, so we need to find a way to safely store the token and its meta-data for its lifetime. Otherwise we would have to generate a new token for every other request and that becomes expensive. Our cache is imo not suited for storing secrets, so maybe we would have to create a K8s secret for each of such tokens (and metadata). @hendrikmaus, since you said you already started on an integration, did you solve this already?

**Comment by hendrikmaus** [comment]
My implementation was purely targeting github apps and I did not touch on the token ttl at all; it simply created a new token for each request. I wanted to make it work first, then make it pretty. However, my org decided to drop the topic and pay for a github machine user to solve the issue.

**Comment by jetersen** [comment]
@hendrikmaus would you be willing to push the code, so I could continue the work?

**Comment by hendrikmaus** [comment]
Sure, can do. I'll add a couple of comments though to indicate where I left off so you can get up to speed.

**Comment by hendrikmaus** [comment]
@jetersen here you go https://github.com/hendrikmaus/argo-cd/commit/5fa181b16839b827105bec2feee403d1f719c19a hope it helps

**Comment by jetersen** [comment]
Much appreciated, I'll see what I can do.

**Comment by jetersen** [comment]
After exploring the issue, I feel there would be a lot of copy paste to have a working implementation since I would need to support pagination, token extract to properly extract the github app installations to generate an github installation access token.

**Comment by jetersen** [comment]
@jannfis the problem with generalizing is that each of the vendor have slightly different methods for implementing the authorization from an application perspective.
I am not sure you can effectively generalize without knowing each implementation fully.

On the other hand some findings, the GitHub installation authorization token have a life time of one hour while our JWT claim we need to use to find installations have validity of maximum 10 minutes.
We can use `ETag` to avoid making unnecessary call when fetching list of installations.

Once we have the installation we can lookup each `owner` to effectively retrieve an one hour access token.
I honestly think we could safely store these access token in memory and simply renew the access token before they expire (if used) or simply request a new token once expired.

**Comment by hendrikmaus** [comment]
> Even with importing libraries it requires a few hundred lines

I feared for that when writing the pseudo function.

> I am not sure you can effectively generalize without knowing each implementation fully.

Same feeling here. I reckon it would take a redesign of the entire credentials code.

Aside: https://github.com/palantir/go-githubapp has, at a glance, an appealing implementation of a cached client. And I agree, storing stuff in memory is fine as one can re-create tokens at any time.

**Comment by jetersen** [comment]
> https://github.com/palantir/go-githubapp

looks like a nicer library yet it still uses github-go 😅

**Comment by jetersen** [comment]
Based on https://github.com/palantir/go-githubapp/issues/46 I think we are best off actually using that go library and I have already implemented the get installation by repository. With the supported caching feature it should hopefully reduce the amount of code needed to implement the installation access token.

**Comment by jetersen** [comment]
Hmm actually now that I think about it.

It might be simpler to implement when using [`/repos/{owner}/{repo}/installation`](https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#get-a-repository-installation-for-the-authenticated-app)
As you only need to find the installation id for a single repo and than if the installation id is the same as for another repo it still means we can cache the token.
Making the implementation a lot simpler.

**Comment by jetersen** [comment]
I opened: #4673 where I added the token retrieval.

my experience with golang is not the strongest. So feel free to add suggestions to the pull request.

**Comment by diranged** [comment]
Just chiming in - this would be a huge win for our organization. As I mention in https://github.com/argoproj/argo-cd/issues/4420 at https://github.com/argoproj/argo-cd/issues/4420#issuecomment-750332123, we use an SSH Certificate Authority to generate all of our certificates (even for role accounts and third party services) that are short lived. We were able to make this work in the repo server, but it was definitely difficult and felt hacky. I would much prefer to have ArgoCD treated like a Github App and let it dynamically get access to our organizations repos. Any progress on this issue?

**Comment by jetersen** [comment]
I am having a hard time setting up argocd development setup 😰 So very hard for me to work on the issue.

**Comment by stlava** [comment]
I put up #5355 with support for GitHub App repos/repocreds. Re the caching of the auth tokens, I opted to cache them in memory. The underlying `ghinstallation` library handles the refreshes for us.

**Comment by mnacharov** [comment]
I'm new in argocd codebase, so maybe I can't see full picture.
It looks like git-over-https credentials don't cached by repo-server: https://github.com/argoproj/argo-cd/blob/master/util/db/repository.go#L108-L139
So, may be those vendor-specific logic will be better deploy separatelly from main instalation?

**Comment by joebowbeer** [comment]
How does this relate to the declarative setup for GitHub App repos?

https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#github-app-repositories

**Comment by jetersen** [comment]
@joebowbeer it is fully related to that, nobody bothered to close the issue.

**Comment by alexmt** [comment]
thank you for closing it @jetersen !
