### ISSUE TITLE
Support web shell and enable user to exec into pod from argocd UI

### ISSUE THREAD

**Issue by yydzhou** [argoproj/argo-cd#4351]
# Summary

What change you think needs making.

ArgoCD needs to support web shell or EXEC into pod. 

# Motivation

The ArgoCD UI already exposes lots of info that helps users for developing and debugging. However, there is still one important feature missed. Currently user can't login into the pod from argoCD UI for live debugging or developing. So we have to deploy separate tools/authentication to achieve this.  It would be great if we could have this feature within the argocd UI so that we don't need another tool/authentication to support this. 

Please give examples of your use case, e.g. when would you use this.

# Proposal

How do you think this should be implemented?

**Comment by yeya24** [comment]
Hi @pasha-codefresh, have you started working on this issue? If not then I can work on it. Thanks.

**Comment by pasha-codefresh** [comment]
Hi @yeya24 , I'm completing another task right now and going to start work on this ( approximately going to start on Wednesday ).

**Comment by GitHubFor122** [comment]
what is status ?

**Comment by dolefirenko** [comment]
This will be a really good feature for ArgoCD... Awaiting :)

**Comment by yeya24** [comment]
Would love to discuss about the implementation a little bit more here as I am currently working on it.
Based on the kubernetes dashboard implementation, it uses websocket and saves shell sessions in memory in a map. But the main drawback is that it doesn't support multiple replicas.

For us, we are using having multiple replicas so it would be good to make this implementation work for multiple replicas, too. Though ideally configuring service with client session should work, it would be better to store session IDs in Redis or somewhere else. Once the websocket connection is established, the server can get the session ID (maybe via Redis pub/sub) and start processing.

I am new to this and argocd codebase as well so would love to hear more opinions! 

The related dashboard is https://github.com/kubernetes/dashboard/blob/master/src/app/backend/handler/terminal.go and I will finish the in-memory only implementation based on it for the first step.

**Comment by tooptoop4** [comment]
maybe these are relevant: https://github.com/KubeOperator/webkubectl and https://github.com/yudai/gotty

**Comment by yeya24** [comment]
Quick update for our progress. We have already implemented the basic web shell for pod, based on the k8s dashboard implementation.

![image](https://user-images.githubusercontent.com/25150124/154372059-c9d4fe5c-ffdf-47a2-b9f5-66c49270672d.png)

We also find one blocker https://github.com/argoproj/argo-ui/issues/180 for us. The `xterm` dependency used by `argo-ui` project is too low. Can we upgrade it so that we can continue this pr?  @alexmt @pasha-codefresh

**Comment by yeya24** [comment]
> how is RBAC control for web shell?

Good question. Right now we just use `Action Get`. I think we need to add another permission for it for example `EXEC`.

**Comment by FuyuanChu** [comment]
Perhaps we need to update the roadmap in the documentation https://argo-cd.readthedocs.io/en/stable/roadmap/#web-shell

**Comment by aaad** [comment]
This feature looks very nice. :) Our pods have multiple containers (e.g. sidecar proxies), will it possible to switch the containers in the UI as it's already possible for the logs?

**Comment by GitHubFor122** [comment]
what is latest status

**Comment by yeya24** [comment]
We have finished this feature and have been using it locally for weeks.
Unfortunately we cannot upstream it for now due to the dependency issue I mentioned before. If the community can help upgrade that dependency then we can open a pr for this.

**Comment by yeya24** [comment]
> This feature looks very nice. :) Our pods have multiple containers (e.g. sidecar proxies), will it possible to switch the containers in the UI as it's already possible for the logs?

Yes it is supported now.

**Comment by alexmt** [comment]
Created PR that updates xterm: https://github.com/argoproj/argo-ui/pull/183 . Waiting for review

**Comment by alexmt** [comment]
@yeya24 , PR is merged. Please run `yarn add git+https://github.com/argoproj/argo-ui.git` in `ui` directory but upgrade to latest version.

**Comment by Stelagowski-Tomasz** [comment]
@alexmt 
if I am deployed on kubernetes cluster with non-ha v2.3.2,
Where do I have to run that command to get the Web Shell? In one of the argo pods?

**Comment by mtovmassian** [comment]
Would be very useful! +1
