### ISSUE TITLE
Example repository using ArgoCD from a CI pipeline

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#436]
Should have examples for:
Jenkins
ArgoCI
Circle? Travis?
(others?)

**Comment by jessesuen** [comment]
@bhack great article -- thanks for the pointer! I agree with all the major points, especially the point about not giving CI systems direct access to a cluster. When designing ArgoCD, we made a point to divorce CI from CD, as they serve very different purposes, and is an important reason why ArgoCI is a different project than ArgoCD.

Most developer's ultimate end goal is to have their pipeline fully automated, where developers pushes a commit to a codebase, which produces a build (docker image), runs tests, and which eventually deploys to production, all within a single pipeline. But to reach 100% automation the CI system must somehow generate **some** event that will affect prod, either directly (as in a `kubectl apply` in CIOps), or indirectly (via GitOps).

An important point. is that weave Flux and ArgoCD accomplish this in separate ways. In the case of Flux, the docker registry effectively becomes the intermediary. The event which takes something to prod, is the CI system performing a `docker push` of the new image, coupled with a corresponding flux policy to detect the new image and upgrade the deployment. Flux also commits and pushes back to the git config repo to bring the config repo in sync with live, which is something ArgoCD doesn't do.

In the case of ArgoCD, the ArgoCD API server becomes the intermediary. The event which takes something to prod, is the CI system performing a `argocd app sync` after either committing the new image in the config repo, or by setting a parameter value in the app (e.g. `argocd app set -p yourimageparam=yourimagevalue`). 

Note that in the future, we will be providing an option to auto-sync, so that direct interactions from the CI pipeline to ArgoCD would be completely optional. The only thing that would need to be done from the CI pipeline, is to commit and push the new image into the config repo, which effectively makes the commit to the config repo, the event which takes something to prod.

The goal for this bug/issue, is to provide some examples (and different options) for CI pipelines to do some variations of the above.

**Comment by bhack** [comment]
@jessesuen Thank you for the feeback. Take a look also to https://www.weave.works/blog/weaveworks-gitops-developer-toolkit-part-one-skaffold. 
Cause often people use tools like this one in the development process loops.

**Comment by jessesuen** [comment]
Fixed.
