### ISSUE TITLE
Way to force argo to sync even when stuck out of sync

### ISSUE THREAD

**Issue by Kampe** [argoproj/argo-cd#4361]
# Summary
Is there a setting I can set on my apps to *force* current state sync?

# Motivation

We ship hardware out and utilize argocd to lay down software manifests, its possible resources get stuck in the lifecycle, if this happens argocd doesn't ever get to current state. 

# Proposal
allow a setting to ensure rectifying of state against current git repo. 

How do you think this should be implemented?
As an application level setting

**Comment by jessesuen** [comment]
You can already make a resource report that it is Synced with the ignoreDifferences feature. This can be configured at system or application level.
