### ISSUE TITLE
local users ref in Security Considerations seems to be dangling

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4362]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

[user-management local-usersaccounts-v15](https://argoproj.github.io/argo-cd/operator-manual/user-management/#local-usersaccounts-v15) links to [security considerations](https://argoproj.github.io/argo-cd/security_considerations/) but the thing it talks about doesn't seem present.

**To Reproduce**

1. visit https://argoproj.github.io/argo-cd/operator-manual/user-management/#local-usersaccounts-v15
1. Read:
    > Make sure to read about security limitations related to local users in [security considerations](https://argoproj.github.io/argo-cd/security_considerations/) document
1. Click link
1. Look for `security limitations`

**Expected behavior**

Something about `security limitations`

**Screenshots**

**Version**

**Comment by wtam2018** [comment]
Hmm ...  The link does take me to "security considerations".   I don't have problem.

**Comment by jsoref** [comment]
It links to a page and says to look for `limitations`, there's only one instance of that word, and it isn't close to `local users`.

**Comment by wtam2018** [comment]
> It links to a page and says to look for `limitations`, there's only one instance of that word, and it isn't close to `local users`.
I see.

**Comment by jannfis** [comment]
I think the warning message is an artefact from when there has been some security issues (user enumeration, etc) were found in Argo CD and were not fixed.

The warning message can imo be removed without any further consequences. The bugs have long been fixed long ago.
