### ISSUE TITLE
Deleting application stuck deleting because of missing project

### ISSUE THREAD

**Issue by lallinger-arbeit** [argoproj/argo-cd#4369]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
Consider an application (A) which deploys a project and an application (B), which uses this project. Both applications have set the finalizer. If you delete application A the project gets deleted quite fast, but application B gets stuck in deleting with this error:

`DeletionError appproject.argoproj.io "project-name" not found`

**To Reproduce**

Create an application which deploys a project and an application using this project.

**Expected behavior**

All resources from application B, application A and the project get deleted successfully.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/54403915/93492226-dcf11e00-f90a-11ea-8662-9efc7306d481.png)

**Proposal**

1. Make sure to only delete a project if there aren't any applications referencing it anymore.
2. Ignore missing project when deleting an application.

**Version**

```shell
argocd: v1.7.3+b4c79cc
  BuildDate: 2020-09-01T23:17:31Z
  GitCommit: b4c79ccb88173604c3786dcd34e83a9d7e8919a5
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd6
```

**Logs**

```
```

**Comment by jessesuen** [comment]
> Make sure to only delete a project if there aren't any applications referencing it anymore.

This check is already in place, but it exists in the API server and would not be enforced if deleted out-of-band. Did you happen to delete outside of the argocd API server?

If you manage projects declaratively, you'll want to set the project finalizer to ensure this scenario won't happen.

**Comment by lallinger-arbeit** [comment]
I provided an example structure [here](https://github.com/lallinger-arbeit/argocd-example).

The problem occurs when i now want to delete app1. I do this by deleting the folder `applications/app1` and remove `- app1/root-application.yaml` from `applications/kustomization.yaml`.

This triggers the delete correctly and ArgoCD tries to delete `applications/app1/root-application.yaml`, this triggers the deletion of `applications/app1/manifests/project.yaml`, `applications/app1/app1-part1.yaml` and `applications/app1/app1-part2.yaml`, but the deletion of the `project.yaml` finishes before the deletion of `app1-part2.yaml` (which uses `project.yaml` as project) this results in the error:

`DeletionError appproject.argoproj.io "app1-part2-project" not found` 

And therefore the deletion of root-application.yaml is stuck in deleting indefinitely..

I hope you understand my problem, it's always hard to describe these app-of-apps structures.. Also maybe i'm missing something and this is no issue..

**Comment by jessesuen** [comment]
@lallinger-arbeit I think your issues will be solved by adding the finalizer in the project which i mentioned in your project spec here:

https://github.com/lallinger-arbeit/argocd-example/blob/master/applications/app1/manifests/project.yaml#L5

add:
```yaml
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io 
```

**Comment by lallinger-arbeit** [comment]
@jessesuen That fixes the problem! Thank you very much!

**Comment by spkane** [comment]
> @lallinger-arbeit I think your issues will be solved by adding the finalizer in the project which i mentioned in your project spec here:
> 
> https://github.com/lallinger-arbeit/argocd-example/blob/master/applications/app1/manifests/project.yaml#L5
> 
> add:
> 
> ```yaml
> metadata:
>   finalizers:
>   - resources-finalizer.argocd.argoproj.io 
> ```

The documentation could really use some updating to make this much more straightforward.

Neither

https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/

or

https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/#cascading-deletion

make this very clear.
