### ISSUE TITLE
RBAC errors when deploying Elastic Cloud on Kubernetes Operator

### ISSUE THREAD

**Issue by tnixa** [argoproj/argo-cd#4370]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I am trying to deploy the Elastic Cloud on Kubernetes (ECK) Operator on my OpenShift 4.4.17 cluster via ArgoCD app. When the app syncs I get multiple RBAC errors like this one...
```
customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:argocd:argocd-application-controller" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope 
```
**To Reproduce**
1. Install ArgoCD Operator on OpenShift
1. Create namespace for ECK, e.g. `elastic-system`
1. Create and apply Role and RoleBinding for argocd-application-controller
1. Copy the ECK yaml from below into a repo
https://download.elastic.co/downloads/eck/1.2.1/all-in-one.yaml
1. Create an ArgoCD app pointing to the repo directory with the ECK yaml
1. ArgoCD app Syn fails

**Expected behavior**
If I manually apply the yaml the deployment works so I would expect the ArgoCD Sync to work as well 
```
[I] ➜ oc apply -f all-in-one1.yaml
customresourcedefinition.apiextensions.k8s.io/apmservers.apm.k8s.elastic.co created
customresourcedefinition.apiextensions.k8s.io/beats.beat.k8s.elastic.co created
customresourcedefinition.apiextensions.k8s.io/elasticsearches.elasticsearch.k8s.elastic.co created
customresourcedefinition.apiextensions.k8s.io/enterprisesearches.enterprisesearch.k8s.elastic.co created
customresourcedefinition.apiextensions.k8s.io/kibanas.kibana.k8s.elastic.co created
namespace/elastic-system created
serviceaccount/elastic-operator created
secret/elastic-webhook-server-cert created
clusterrole.rbac.authorization.k8s.io/elastic-operator created
clusterrole.rbac.authorization.k8s.io/elastic-operator-view created
clusterrole.rbac.authorization.k8s.io/elastic-operator-edit created
clusterrolebinding.rbac.authorization.k8s.io/elastic-operator created
rolebinding.rbac.authorization.k8s.io/elastic-operator created
service/elastic-webhook-server created
statefulset.apps/elastic-operator created
validatingwebhookconfiguration.admissionregistration.k8s.io/elastic-webhook.k8s.elastic.co created
```

**Screenshots**

![ECK_RBAC_errors](https://user-images.githubusercontent.com/49254259/93494807-0f7f2480-f8d3-11ea-942c-ddcfc800e68b.png)

**Version**

```
[I] ➜ argocd version
argocd: v1.7.4+f8cbd6b.dirty
  BuildDate: 2020-09-05T05:08:44Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: dirty
  GoVersion: go1.15.1
  Compiler: gc
  Platform: darwin/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
I think this a permission problem for your controller specific to your environment. Did you install the cluster-scoped Argo CD set of manifests? Or the namespaced scope?

**Comment by tnixa** [comment]
I followed the install instructions in this link for the Console Install into the default `argocd` namespace:
https://argocd-operator.readthedocs.io/en/latest/install/openshift/
Then this link to create the ArgoCD cluster:
https://argocd-operator.readthedocs.io/en/latest/usage/basics/
I then tried to deploy ECK via ArgoCD app into the `elastic-system` namespace but I ran into the RBAC issues. I tried to create and apply a role and role binding based on the RBAC errors I was seeing but I was still getting RBAC errors. 
I did not install any cluster-scoped or namespaced scoped manifests.
Can you point me to the mainfest(s) which might solve my problem?

**Comment by jessesuen** [comment]
I see. Our default installation gives the controller */*/* privileges to the cluster which it is installed in:
https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml#L2001-L2019

I think argocd-operator is doing it a bit differently, possibly the namespaced scope privilege, which may mean you need to `argocd cluster add CONTEXTNAME --in-cluster` the cluster to itself, in order to gain the right RBAC.
