### ISSUE TITLE
Can not add external AKS cluster

### ISSUE THREAD

**Issue by munjalpatel** [argoproj/argo-cd#4374]
**Describe the bug**

Trying to add an external AKS cluster fails with the following error:
```
FATA[0000] no Auth Provider found for name "azure"
```

**To Reproduce**

1. Deploy ArgoCD to a cluster
2. Install ArgoCD CLI
3. Connect to ArgoCD using CLI
4. Run the following command to add an external AKS cluster
```sh
argocd cluster add <cluster-context-name>
```

Notice the error:
```
FATA[0000] no Auth Provider found for name "azure"
```

**Expected behavior**

The AKS cluster specified above should be registered with ArgoCD

**Version**

```shell
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:46:53Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.5+90cc56c
  BuildDate: 2020-09-15T23:03:57Z
  GitCommit: 90cc56c3a99127f6ed6bcb777abf92e357c1eb00
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Comment by jessesuen** [comment]
This was resolved https://github.com/argoproj/argo-cd/pull/4265 and will be backported to v1.7.6

**Comment by munjalpatel** [comment]
@jessesuen I am willing to upgrade to the version where this is fixed instead of waiting for the backport. Which version is this fix part of? 

I thought I installed the latest v1.7.5 which was released 2 days ago.

**Comment by alexmt** [comment]
hello @munjalpatel , the change is cherry-pick into v1.7.6 already. Just started building release: https://github.com/argoproj/argo-cd/runs/1136507278 It will be ready in a few minutes.
