### ISSUE TITLE
CRD for Beat costantly OutOfSync

### ISSUE THREAD

**Issue by irizzant** [argoproj/argo-cd#4378]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to deploy the ECK operator (https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-overview.html) and I can't get the CRD [Beat](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-api-beat-k8s-elastic-co-v1beta1.html#k8s-api-beat-k8s-elastic-co-v1beta1) in sync despite of diffing customization.

**To Reproduce**
See this repo:
https://gitlab.com/i.rizzante/eck.git

**Expected behavior**

The beats.beat.k8s.elastic.co CRD should be in sync.

**Screenshots**

![image](https://user-images.githubusercontent.com/15982257/93667090-7cd1b780-fa83-11ea-9312-ccd009df798f.png)
![image](https://user-images.githubusercontent.com/15982257/93667100-8eb35a80-fa83-11ea-8deb-d237a061df30.png)

**Version**

v1.7.6+b04c25e

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
It should be possible to ignoreDifferences. Can you paste the configuration that you tried and is not working?

**Comment by irizzant** [comment]
It is in the repo link I shared:
https://gitlab.com/i.rizzante/eck/-/blob/master/apps/elasticsearch-operator.yaml

**Comment by irizzant** [comment]
This should be labelled as bug imho, I've tried to remove the `properties: {}` out of beats.beat.k8s.elastic.co  CRD using this simple kustomize jsonpatch:
```yaml
- op: remove
  path: "/spec/validation/openAPIV3Schema/properties/spec/properties/daemonSet/properties"
```

and it worked fine, while if I apply the very same path to `ignoreDifferences` it doesn't work

**Comment by foxracle** [comment]
we have the same problem when I install the eck 1.2.1 with the same crd: https://download.elastic.co/downloads/eck/1.2.1/all-in-one.yaml

can not work with the same ignoreDifferences config as @irizzant 

ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: beats.beat.k8s.elastic.co
    jsonPointers:
    - /spec/validation/openAPIV3Schema/properties/spec/properties/daemonSet/properties

**Comment by foxracle** [comment]
@jessesuen  any point why ignoreDifferences here did not work?

**Comment by SimoneFalzone** [comment]
Hi everyone, it does not work because the path has changed slightly in the new version.

This works for me in eck version 1.2.1

```yaml
 ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/validation/openAPIV3Schema/properties/spec/properties/daemonSet/properties
```
