### ISSUE TITLE
Visible overflow from long 'sync error' blocks other elements

### ISSUE THREAD

**Issue by tetchel** [argoproj/argo-cd#4389]
It should probably be scrollable instead.

**Screenshots**
![image(1)](https://user-images.githubusercontent.com/8888438/93822696-9a8f5000-fc2e-11ea-87e9-5dc70f4e0c29.png)

**Version**
Latest

**Comment by jessesuen** [comment]
@alexmt and I think we should just truncate it instead of scrollable since you can click into the error
