### ISSUE TITLE
Bearer token missing on cluster add

### ISSUE THREAD

**Issue by donaldgifford** [argoproj/argo-cd#4402]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When adding a new cluster with argocd cli it adds the secret for the cluster but is missing the bearer token. This fails on EKS from 1.14-1.17 with at least 1.6 of argo. We are on 1.7.6 and it still fails to add the bearer token from the shared cluster to argo cluster. When we manually add the bearer token to the secret, it works. 

**To Reproduce**

Add an external cluster? We have tried a few different clusters. 

**Expected behavior**

The bearer token is put into the secret for the cluster in the argo namespace. 

**Screenshots**

**Version**

```shell
v1.7.6+b04c25e
```

**Logs**

```
N/A.
```

**Comment by alexmt** [comment]
Can you share command that was used to add cluster? Did you use `--aws-cluster-name` flag?
