### ISSUE TITLE
Tiles view should offer link to clear filters

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4403]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

There should be a clickable link to clear filters in the tiles view as there is in network and tree views.

**To Reproduce**

1. Load https://cd.apps.argoproj.io/applications/argo-cd?resource=health%3AUnknown (on average, nothing should be unknown)
1. In another window, load https://cd.apps.argoproj.io/applications?view=tiles&proj=&sync=Unknown&health=&namespace=&cluster=&labels= (on average, nothing should be unknown)

See:
> No resources found
> Try to change filter criteria

**Expected behavior**

Both views should have a handy equivalent way to clear filters

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/93964459-9b5adb80-fd2d-11ea-80e1-3a94b03fd5e3.png)
![image](https://user-images.githubusercontent.com/2119212/93964479-ac0b5180-fd2d-11ea-83a7-a82e2abe7d94.png)

**Version**

v1.8.0+fbfa89d

**Logs**

**Comment by tetchel** [comment]
![image](https://user-images.githubusercontent.com/8888438/94455103-b3dd5280-0180-11eb-976d-57690b8677e1.png)
The filters are much more obvious when the window is wider. 

When the window is narrow (as the screenshot above), the filters panel collapses into the FILTERS combo-box and the arrow to expand is it not too obvious. 

I will add a way to 'clear filters' from the 'no applications found' message, and will try to make the expansion arrow more obvious
