### ISSUE TITLE
/api/v1/applications - wrong behavior for querying the application's name.

### ISSUE THREAD

**Issue by xakraz** [argoproj/argo-cd#4404]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Using `/api/v1/applications` endpoint to get 1 application does not behave as stated in the doc

**To Reproduce**

1. Have at least 2 apps running on ArgoCD
2. Query as documented `/api/v1/applications?name=APP_NAME` will return all the applications
3. Query `/api/v1/applications/APP_NAME` will return the actual application APP_NAME data

**Expected behavior**

I am expecting the API endpoint to behave as documented

**Screenshots**

![Screenshot_20200923_121459](https://user-images.githubusercontent.com/1590399/93999708-72bafc00-fd96-11ea-8d69-142538597505.png)

![Screenshot_20200923_121342](https://user-images.githubusercontent.com/1590399/93999712-73ec2900-fd96-11ea-97fd-31183cc8f130.png)

![Screenshot_20200923_121436](https://user-images.githubusercontent.com/1590399/93999710-73539280-fd96-11ea-80f8-da6efeffc71f.png)

**Version**

```shell
v1.5.4+36bade
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by darshanime** [comment]
Hmm, can you elaborate on what the issue is? 
Based on your screenshots, on `/api/v1/applications?name=APP_NAME` you are getting all the applications and on `/api/v1/applications/APP_NAME` you are getting only one as expected.

**Comment by xakraz** [comment]
Hi @darshanime ,

Yes this is exactly what I am saying :smile: 

> Query as documented /api/v1/applications?name=APP_NAME will return all the applications

This is supposed to return me only 1 application, the one called `APP_NAME` but it returns all the applications
-> Not working as expected


The only way I found to get the data I am expecting is
> Query /api/v1/applications/APP_NAME 

-> Not documented

**Comment by aistein** [comment]
@alexmt might I please take a crack at this?

**Comment by alexmt** [comment]
@aistein, sure!

**Comment by kshamajain99** [comment]
Looking into it.

**Comment by jessesuen** [comment]
Fixed
