### ISSUE TITLE
Editing Clusers in the UI drops credentials from the secret

### ISSUE THREAD

**Issue by martinpovolny** [argoproj/argo-cd#4405]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have created a cluster definition at the command line. The definition includes an SA token. Like this:

```
ARGOCD_MANAGER_TOKEN="$(echo -e "$(oc sa get-token argocd-manager -n aicoe-argocd-dev)" | tr -d '[:space:]')"
CLUSTER_SPEC_CONFIG=$(echo -n "{\"bearerToken\":\"${ARGOCD_MANAGER_TOKEN}\",\"tlsClientConfig\":{\"insecure\":true}}" | base64 | tr -d '[:space:]')
oc patch secret dev-cluster-spec -n aicoe-argocd-dev --type='json' -p="[{'op': 'add', 'path': '/data/config', 'value':'${CLUSTER_SPEC_CONFIG}'}]"

# We also need to provide the cluster spec with the location of this server.
API_SERVER_ENCODED=$(echo -ne ${API_SERVER} | base64 | tr -d '[:space:]')
oc patch secret dev-cluster-spec -n aicoe-argocd-dev --type='json' -p="[{'op': 'add', 'path': '/data/server', 'value':'${API_SERVER_ENCODED}'}]"
```

Then editing the "Namespaces" field of the cluster in the UI causes the bearer token to be lost.

**To Reproduce**

1. create a cluster definition (above)
1. edit the cluster definition in the UI
1. observe things starting to fail due to missing access to the cluster for the argo SA

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

Changing the namespaces in the UI should not change other values.

**Screenshots**

### Editing in the UI:
![a1-2020-09-23_12-04](https://user-images.githubusercontent.com/51095/93999709-73539280-fd96-11ea-89b2-164eae8f853c.png)
![a2-2020-09-23_12-04](https://user-images.githubusercontent.com/51095/93999715-73ec2900-fd96-11ea-973c-de9f9e67e36d.png)
![a3-2020-09-23_12-07](https://user-images.githubusercontent.com/51095/93999716-7484bf80-fd96-11ea-80b7-5f32bff4dad4.png)

### Value of the secret before and after editing the namespaces

![a4-2020-09-23_12-08](https://user-images.githubusercontent.com/51095/93999718-751d5600-fd96-11ea-8a78-bc6f4703d6f8.png)

## ArgoCD starts failing due to missing access to the cluster

![a5-2020-09-23_12-13](https://user-images.githubusercontent.com/51095/93999721-751d5600-fd96-11ea-861f-7ab20871d249.png)

**Version**

```shell
$ argocd version
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:44:27Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:45:44Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8

```

**Logs**

```
none relevant
```

**Comment by alexmt** [comment]
The problem is that GET API don't return cluster credentials and we don't have a way to patch some cluster fields. We need to add `PATCH /api/v1/cluster` API that can be used by UI to modify only cluster name, namespaces etc.

**Comment by martinpovolny** [comment]
@alexmt : pardon me if I am mistaked, but does not the fact that I can do:
```
oc patch secret dev-cluster-spec -n aicoe-argocd-dev --type='json' -p="[{'op': 'replace', 'path': '/data/namespaces', 'value':''}]"
```
mean that the API is there already?

**Comment by martinpovolny** [comment]
Or does the change need to happen through the cluster API rather than the secret?

**Comment by jannfis** [comment]
> Or does the change need to happen through the cluster API rather than the secret?

I think what @alexmt was trying to say is that the Argo CD API for managing clusters does not return the cluster secrets on replies to a Get operation. When saving, we're doing a replace of the cluster configuration instead of patching only the things that have changed. This is why the cluster credentials are lost on update.

**Comment by alexmt** [comment]
Unfortunately PATCH requests with [grpc-gateway](https://grpc-ecosystem.github.io/grpc-gateway/docs/patch.html) and [gogo/protobuf](https://github.com/gogo/protobuf) are not supported.

The grpc-gateway requires to use well known type using `Mgoogle/protobuf/field_mask.proto=github.com/gogo/protobuf/types` and grpc-gateway "not entirely obey the -M parameter ": https://github.com/grpc-ecosystem/grpc-gateway/issues/229 ¯\_(ツ)_/¯
