### ISSUE TITLE
switch monkeypatching implementation for license reasons

### ISSUE THREAD

**Issue by ryandawsonuk** [argoproj/argo-cd#4407]
Monkeypatching is being used for one of the tests - https://github.com/argoproj/argo-cd/search?q=bou.ke%2Fmonkey

The implementation is coming from archived git repo and the license says not to use it - https://github.com/bouk/monkey/blob/master/LICENSE.md

This has turned up in a license scan for our project that is using an argocd dependency as it's part of the argocd mod file,[ even though it's a test dependency](https://www.reddit.com/r/golang/comments/98hbvk/go_modules_how_to_deal_with_test_dependencies/).

There is an [MIT-licensed alternative available](https://news.ycombinator.com/item?id=22442523). Could the implementation be switched to that?

**Comment by jopit** [comment]
/assign @jopit 

@alexmt I can look at replacing `bou.ke/monkey` with `github.com/undefinedlabs/go-mpatch` (https://github.com/undefinedlabs/go-mpatch) if that package is acceptable
