### ISSUE TITLE
Private container registry with argocd

### ISSUE THREAD

**Issue by amitcmore** [argoproj/argo-cd#4410]
How to use private container registry with argocd. I have a container registry where I push all my images and want to deploy those from argocd how do I do this.

**Comment by arielhernandezmusa** [comment]
I thing argocd deploy your k8s yamls not the images directly

**Comment by arielhernandezmusa** [comment]
To deploy your images create a fit repo with your k8s yamls containing the specifications with how to deploy your images to Kubernetes and then setup your app on argocd

**Comment by emoxam** [comment]
now keel takes docker images and loads it to the k8s. I want argo to do this. Does argo support docker container registries ? I am using gitlab. How to setup this CR repo?

**Comment by aligolestan** [comment]
you need to install the argocd-image-update plugin and cofigure it to use your private registry.
you use the following link (argocd official docs) to configure your service.

https://argocd-image-updater.readthedocs.io/en/stable/configuration/registries/

**Comment by aligolestan** [comment]
@emoxam I'm using it on selfhosted gitlab and everything works fine.

**Comment by emoxam** [comment]
Thanks i will try when we'll back to the kubernetes deployment )

**Comment by NielsHoogeveen1990** [comment]
> you need to install the argocd-image-updater plugin and cofigure it to use your private registry. you use the following link (argocd official docs) to configure your service.
> 
> https://argocd-image-updater.readthedocs.io/en/stable/configuration/registries/

How does that work? The documentation is very incomplete in my opinion. I created my dockerhub secret, but I don't understand whether I have to use it in the namespace of the application (in my case a FastAPI) or the argocd namespace...
