### ISSUE TITLE
Argo CD should present the live object in the resource version in git

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#4412]
**Describe the bug**

We were trying debug a HPA object, but clicking on the live object in Argo CD shows the v1 version of the HPA, despite the v2beta2 version is the one being managed in git. 

When clicking on the live object, we should show the version of the object that is managed in git. I believe we must be showing the preferred object.

**To Reproduce**

Manage a v2beta2 HPA and click on live object in UI

**Version**

v1.7.4+4c715cf.dirty

**Comment by jaideepr97** [comment]
Hi @jessesuen 
Curious to learn more about this issue and maybe take a crack at it 
Are there any places you could point me to for building context around the involved components and their usage in argoCD?

**Comment by jgwest** [comment]
Hi @jaideepr97 

Was something like this what you were looking for? You should be able to do something like:
- Create an Argo CD sample app (with https://github.com/argoproj/argocd-example-apps/ always being a good place to start) that contains a manifest YAML with a newer version of `HorizontalPodAutoScaler` (for example, `apiVersion: autoscaling/v2beta2` at the root)
- Add and sync that app to the cluster (eg from the UI)
- Click the app within the UI and verify that the old version of the live object is displayed (`apiVersion: autoscaling/v1`), as reported in the issue
- Then determine which API is returning the old version vs the new version, and when, by digging into the code and answering questions like:
  - What version of HPA is being returned to the web UI by the api server?  (see, I think, `ManagedResources` in `server/application/application.go`)
  - What version of HPA is being seen by the controller (see something like 'GetManagedLiveObjs')
  - What version of the HPA is coming from Git (this will be generated by the reposerver and then communicated to the controller  via GRPC)

If you want to see the various versions of the HorizontalPodAutoscaler API that are available, look at the various `types.go` in `vendor/k8s.io/api/autoscaling` in argo-cd repo (and I'm sure there are online resources as well).

**Comment by alexmt** [comment]
A little more info:

I suspect the bug is on the UI side. UI uses `GET /api/v1/applications/<name>/resource` API to load resource but requests incorrect version. The request is initiated here:

https://github.com/argoproj/argo-cd/blob/0767dff025d6394ac6bdc357a2dc3fd567c3ab1a/ui/src/app/applications/components/application-details/application-details.tsx#L270
