### ISSUE TITLE
HPA health check

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#4413]
# Summary

HPA does not have status, but it uses annotations to indicate current problems with the HPA. We could write a health check to look at HPA annotations and mark an HPA as unhealthy based on the annotation.

# Motivation

Currently, problems with HPA are silent because they only emit Events when there are problems, which requires a user to click into the object.

# Proposal

Write a health check for HPA so that it can surface problems.

**Comment by chetan-rns** [comment]
Hi, does it involve writing a custom check using `lua` under resource_customizations? I'm happy to work on it
