### ISSUE TITLE
Streamline access checks for Git and Helm repositories and move them from API server to Repo Server

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#4420]
# Summary

The check for Git and Helm repositories to determine whether a repository is reachable and accessible (using provided credentials) is performed by the API server. This check should be moved to the repository server.

# Motivation

Currently, when adding a Git or Helm repository to Argo CD via UI or CLI, the API server performs an access check to the remote repository before adding the repository to the configuration. This has multiple implications:

* In case of Git, API server and repo server use different mechanisms of connecting the repositories. API server uses go-git (along with pure-go implementation of SSH client), while repo server uses fork/exec of git and openssh client. This makes it impossible to use a custom SSH client config as described in #4106 
* In case of Helm, people might use plugins for accessing remote repositories (or other plugins), which might not be available on the API server (because binaries/configuration were copied using an init container or similar methods)
* If accessing repositories is only possible via means of a proxy server, people tend to configure proxy on the repo server but not on the API server. Also, go-git and git binary might interpret proxy configuration differently. 

# Proposal

* The work for the access check should be moved from API server to repo server
* The repo server provides a new API method for checking the access from the API server and return the result
* The check should use same tools that the repo server will use for actually accessing the repository. This means, I think we should get rid of go-git in favour of fork/exec the git binary, even if that means a few more fork/exec's on the repo-server.

**Comment by jessesuen** [comment]
I agree, theres things like proxy settings that don't work (or have to be duplicated configured) on API server.

**Comment by diranged** [comment]
I would like to see this happen as well. In our environment, we use an SSH Certificate Authority to generate short-lived SSH certs. This makes ArgoCD difficult to use for us. I was able to modify the Repo Server to use an SSH-Agent and run a daemon in the background that was retrieving new certs ... but the UI experience of Argo was completely broken at that point. All of the access checks, UI bits like path drop downs, etc, should all be done through the Repo Server entirely.

**Comment by ishitasequeira** [comment]
I would like to work on this issue.

**Comment by jannfis** [comment]
Thanks @ishitasequeira - assiging the issue to you
