### ISSUE TITLE
Repo-server has silent unmarshalling errors leading to empty applications

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#4423]
**Describe the bug**

We noticed a situation where when retrieving cached manifests from redis, the cache **silently** returned an empty datastructure of cached manifests, despite there being content in the redis key. This made it appear that the manifests at the commit SHA had zero manifests, and Argo CD wanted to prune everything.

When investigating the issue, the problem was traced to the `github.com/vmihailenco/msgpack` library. When connecting directly to redis, it was seen that there was partial text, so there was indeed content in the database for the key. However, when msgpack deserialize it, it returned an empty struct without returning an error, which was interpreted by the repo server as having no manifests.

**To Reproduce**

This is not easy to reproduce.

**Expected behavior**

I think we may need to add some corruption verification, or at least a basic struct check that validates what we retrieve from redis is valid. For example, it could be a checksum against the manifests.

**Version**

v1.7

**Comment by jessesuen** [comment]
> For example, it could be a checksum against the manifests.

@alexmt and I agree we should introduce a new field in the cached manifest datastructure which contains a checksum of the rendered JSON manifests. This checksum would be verified whenever we retrieve manifests it from cache.

/cc @jgwest this might be a good one for you

**Comment by jgwest** [comment]
@jessesuen +1, feel free to assign to me.

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-cd/pull/4708
