### ISSUE TITLE
"dot" files deployed after upgrade from 1.7.3 to 1.7.4

### ISSUE THREAD

**Issue by drewboswell** [argoproj/argo-cd#4432]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
"dot" files are loaded and evaluated for deployment. (example: .bulldozer.bot.yaml, inside path directory). This is an api breaking change in a patch version.

**To Reproduce**
use the following settings in an argocd/application object
```yaml
directory:
      jsonnet: { }
      recurse: true
path: .
```
place a file in the path like so:
```yaml
# name: .this.should.not.load.yaml
{"what": "no way"}
```
Upgrade from 1.7.3 to 1.7.4

It tries to marshall/evaluate/deploy the dot file.

**Version**
```
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:44:27Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
```

**Comment by jannfis** [comment]
Hey, I believe this is rather a side effect of #3942 - the files haven been loaded before, but any errors (i.e. invalid K8s resource YAML) were silently ignored, and now they raise an error.

**Comment by alexmt** [comment]
https://github.com/argoproj/argo-cd/pull/3942 was reverted from 1.8 . This is a good change but we need to work more in 1.8 to handle edge cases better.

**Comment by jessesuen** [comment]
Decision is to:
1. introduce an exclusions field for the directory source
2. by default, the exclusion will ignore hidden files/directories (anything beginning with `.`)
