### ISSUE TITLE
Support for DeleteNamespace SyncPolicy

### ISSUE THREAD

**Issue by booleanbetrayal** [argoproj/argo-cd#4435]
# Summary

Adding support for some mechanism to allow ArgoCD to delete the namespace of its underlying app. This could be limited to apps that were created with a `CreateNamespace` SyncPolicy set.

# Motivation

We're currently using ArgoCD to manage ephemeral environments, automatically spooled with `CreateNamespace` handling the initial namespace creation. It would be great if we could also rely on a Cascade Delete in ArgoCD to also tear down the namespace in addition to the usual resources. It would probably justify some sort of manual user interaction in addition to a new SyncPolicy setting. This could help eliminate the need for extraneous tooling in automated CI environments.

# Proposal

Environments having a SyncPolicy of `DeleteNamespace`, in addition to `CreateNamespace` set, should allow cascade deletes of the underlying namespace, after UI / CLI confirmation.

**Comment by ecda909** [comment]
This would be a big help, because there are no other features I could find that handle this.

**Comment by SamDecrock** [comment]
I guess you could circumvent this by adding a namespace resource to your git folder.

**Comment by james-callahan** [comment]
> I guess you could circumvent this by adding a namespace resource to your git folder.

This was what we had to do before `CreateNamespace` was introduced. We'd love for some way to delete automatically created namespaces.

**Comment by snarlysodboxer** [comment]
+1 for this feature.

> I guess you could circumvent this by adding a namespace resource to your git folder.

If you add a `namespace` object to your manifests, you then can't use the same variant to deploy to many ephemeral namespaces. For each namespace you would have to change the `name` in that namespace manifest and commit the change, which would break delivery for every other namespace.

If you're using kustomize and https://github.com/argoproj/argo-cd/issues/6067 is implemented, then you could provide a namespace object, and kustomize would change it's name and all references to it for you.

**Comment by booleanbetrayal** [comment]
This is exactly the workaround we're using right now. It'd be nice to have less YAML / Helm values though!  =]

**Comment by bitfactory-henno-schooljan** [comment]
> I guess you could circumvent this by adding a namespace resource to your git folder.
Just be aware that that would allow for the management of arbitrary namespaces as right now we cannot white-/blacklist cluster-wide resources by resource name in an application. You could obliterate any namespace by adding it to the Application and then deleting the Application.

**Comment by MazenElzanaty** [comment]
Any workarounds for this?

**Comment by prein** [comment]
It sounds like a dangerous feature to me unless it would prevent deleting a namespace containing objects not directly managed by the app being deleted.

**Comment by ashutosh16** [comment]
seems to be duplicate #[4435](https://github.com/argoproj/argo-cd/issues/4435)

**Comment by mulhotavares** [comment]
I use an ApplicationSet with a PullRequest generator with CreateNamespace, and this is an issue... it would be nice if we could have the namespaces deleted when the application is deleted by the ApplicationSet as well.

**Comment by alexef** [comment]
@blakepettersson does it overlap with: https://github.com/argoproj/argo-cd/issues/11196 ?

**Comment by corinz** [comment]
Between this issue and https://github.com/argoproj/argo-cd/issues/7875 there's 100+ upvotes and dozens of comments with no triage. Small issue, but can we get some input from a contrib, please?

**Comment by blakepettersson** [comment]
Hi @toyamagu-2021! I've added a few comments in your PR #11821.

**Comment by rkubik-hostersi** [comment]
+1

**Comment by laurajsdias** [comment]
That would be so useful! Is there any updates?

**Comment by afernandez-01** [comment]
+1

**Comment by joebowbeer** [comment]
Close this in favor of #7875 ?

The extra annotations mentioned in #7875 work for me.
