### ISSUE TITLE
How to  integrate security tools like fortify, appscan for DAST scanning with Argocd.

### ISSUE THREAD

**Issue by amitcmore** [argoproj/argo-cd#4442]
How to integrate security tools like fortify, appscan for DAST scanning with Argocd.

**Comment by jessesuen** [comment]
This seems like a very open ended question without knowing the nature of those tools. It is likely out-of-scope from argo cd

**Comment by amitcmore** [comment]
How we do/trigger the post deployment testing when the application deployed using ArgoCD

**Comment by omerlh** [comment]
Usually this is something you can do with operators like [Zap Operator](https://github.com/omerlh/zap-operator) (and there are many others)
