### ISSUE TITLE
In logs view, request to retrieve logs are refetched unnecessarily

### ISSUE THREAD

**Issue by imranismail** [argoproj/argo-cd#4450]
**Describe the bug**

Even when reaching the end of the log, the request to /logs endpoint are reinvoked causing the UI to restream the logs.

**To Reproduce**

1. Create a job that logs to stdout
2. Let it run to finish
3. View pod log getting repeated unnecessarily

**Expected behavior**

Stops request once the end of the log is reached

**Screenshots**

![image](https://user-images.githubusercontent.com/6883647/94519998-1e17f500-025e-11eb-9c79-6f6d4ce49e59.png)

**Version**

```shell
1.7.6
```

**Comment by jessesuen** [comment]
We may need to special case pods which are in completed state, and not retry retrieval of the logs.

**Comment by tetchel** [comment]
it also looks like this can result in the output being duplicated

![Uploading image.png…]()

**Comment by darshanime** [comment]
closed in https://github.com/argoproj/argo-cd/pull/4696
