### ISSUE TITLE
Patching a NodePort Service to ClusterIP fails

### ISSUE THREAD

**Issue by ramanNarasimhan77** [argoproj/argo-cd#4459]
Hello
I have a running Ambassador helm chart instance deployed using argocd.

In values.yaml, I had used serviceType NodePort

```
  ambassador:
    service:
      type: NodePort
```

Application got deployed successfully.

```
$ kubectl get svc
NAME                             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                                       AGE
ambassador               NodePort    10.0.58.251           <none>        80:32163/TCP,443:30042/TCP   44h
 
```

Few days later, we decided to expose Ambassador service using an ingress, and so we decided not to use serviceType NodePort and hence changed the values.yaml file to have serviceType ClusterIP

```
  ambassador:
    service:
      type: ClusterIP
```

The service does not get patched and I see a Sync Failure with the error

```
Service "ambassador" is invalid: [spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP', spec.ports[1].nodePort: Forbidden: may not be used when `type` is 'ClusterIP']
```

Looks like ArgoCD is just updating the ServiceType and does not remove the allocated NodePorts.

Is this use-case not supported by ArgoCD?

**Comment by jessesuen** [comment]
This is not an Argo CD issue. Kubernetes does not like the fact that you wwitching back from nodePort to cluster IP while already have allocated node ports to the service. If you delete and recreate the service it should go through. Force option might work as well.
