### ISSUE TITLE
Cannot connect to helm repo for application

### ISSUE THREAD

**Issue by AceHack** [argoproj/argo-cd#4463]
Checklist:

* [ X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `argocd version`.

**Describe the bug**

Cannot point repoUrl to helm repo in Application.

**To Reproduce**

Create an application that points repoUrl to helm repo.

**Expected behavior**

Point to helm repo with from application repoUrl.

**Version**

```shell
argocd: v1.7.6+b04c25e
  BuildDate: 2020-09-19T00:53:13Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
```

**Logs**

```
ComparisonError: rpc error: code = Internal desc = Failed to fetch git repo: `git fetch origin --tags --force` failed exit status 128: fatal: repository 'http://opscert-artifactory.route53.xxx.com/artifactory/list/helm-virtual/' not found. Retrying attempt #2 at 6:30PM.
```

**Comment by AceHack** [comment]
Looks like changing `source.path` to `source.chart` fixes the issue and lets Argo know that `repoUrl` is pointing to a helm repo instead of a git repo.

FYI, this is not intuitive at all and does not seem to be covered in any documentation.  This should be converted to a documentation/usability issues instead of a bug on the code.

**Comment by Rude-Monkey** [comment]
Hi! I opened a PR to update the [declarative setup documentation](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/) as it seemed to be the best place to clarify this point.

Changes can be seen on the PR (#4597). Feel free to share feedback (it's my first contribution to this repository 😄 )
