### ISSUE TITLE
Azure DevOps - Kustomize remote bases

### ISSUE THREAD

**Issue by rumstead** [argoproj/argo-cd#4465]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I posted this on slack but going to post it here as well. 

I have two repositories in Azure DevOps that use the same creds to authenticate to. According to the docs, https://argoproj.github.io/argo-cd/user-guide/kustomize/#private-remote-bases, I would assume that ArgoCD passes the GIT creds down to kustomize to be able to clone the remote base. However, it doesn't seem to be. ArgoCD can clone the first repo fine using the templated creds but kustomize fails to clone the remote base. 

One thing to note is the git URL in the application CR differs from the remote base URL. Ie,
```
https://dev.azure.com/<org>/<project>/<repo_2>.git/<path>?ref=0.1.0 // remote base
https://<org>@dev.azure.com/<org>/<project>/_git/<repo_1> // application cr URL
``` 
I did try adding credentials explicitly for both and some templates but nothing was working. I would guess that is because of the URL being different? 

Another thing I found interesting from inside the repo server pod
```
$ export GIT_ASKPASS=git-ask-pass.sh
$ export GIT_USERNAME=*****
$ export GIT_PASSWORD=*****
$ kustomize build /tmp/https:__MY_ORG@dev.azure.com_MY_ORG_MY_PROJECT__git_MY_REPO/dev
2020/09/30 22:49:40 Error cloning git repo: Cloning into '/tmp/kustomize-873106671'...
fatal: repository 'https://dev.azure.com/MY_ORG/MY_PROJECT/MY_REPO/' not found
Error: accumulating resources: accumulateFile "accumulating resources from ...

$ git clone https://MY_ORG@dev.azure.com/MY_ORG/MY_PROJECT/_git/MY_BASE_REPO
Cloning into 'MY_BASE_REPO'...
remote: Azure Repos
remote: Found 10 objects to send. (93 ms)
Unpacking objects: 100% (10/10), done.
```

**To Reproduce**

Using Azure DevOps, create a kustomize app referencing another ADO repository as a remote base. 

**Expected behavior**

Kustomize clones the remote base and produces the correct Kubernetes manifest. 

**Version**

```shell
argocd: v1.7.6+b04c25e
  BuildDate: 2020-09-19T00:53:13Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.3+b4c79cc
  BuildDate: 2020-09-01T23:19:02Z
  GitCommit: b4c79ccb88173604c3786dcd34e83a9d7e8919a5
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Logs**

```
time="2020-09-30T21:46:54Z" level=error msg="`kustomize build /tmp/https:__MY_ORG@dev.azure.com_MY_REPO/dev` failed exit status 1: 2020/09/30 21:46:54 Error cloning git repo: Cloning into '/tmp/kustomize-316768823'...\nfatal: repository 'https://dev.azure.com/MY_ORG/MY_PROJECT/MY_REPO_BASE/'  not found\nError: accumulating resources: accumulateFile \"accumulating resources from 'https://dev.azure.com/MY_ORG/MY_PROJECT/MY_REPO_BASE.git/base?ref=0.1.0':  YAML file [https://dev.azure.com/MY_ORG/MY_PROJECT/MY_REPO_BASE.git/base?ref=0.1.0 ] encounters a format error.\\nerror converting YAML to JSON: yaml: line 6: mapping values are not allowed in this context\\n\", loader.New \"trouble cloning git repo https://dev.azure.com/MY_ORG/MY_PROJECT/MY_REPO_BASE  in /tmp/kustomize-316768823: exit status 128\"" execID=NeiYf
--
  | time="2020-09-30T21:46:54Z" level=error msg="finished unary call with code Unknown" error="`kustomize build /tmp/https:__MY_ORG@dev.azure.com_MY_ORG_MY_PROJECT__git_MY_REPO/dev` failed exit status 1: 2020/09/30 21:46:54 Error cloning git repo: Cloning into '/tmp/kustomize-316768823'...\nfatal: repository 'https://dev.azure.com/MY_ORG/MY_PROJECT/MY_REPO_BASE/'  not found\nError: accumulating resources: accumulateFile \"accumulating resources from 'https://dev.azure.com/MY_ORG/MY_PROJECT/MY_REPO_BASE.git/base?ref=0.1.0':  YAML file [https://dev.azure.com/MY_ORG/MY_PROJECT/MY_REPO_BASE.git/base?ref=0.1.0 ] encounters a format error.\\nerror converting YAML to JSON: yaml: line 6: mapping values are not allowed in this context\\n\", loader.New \"trouble cloning git repo https://dev.azure.com/MY_ORG/MY_PROJECT/MY_REPO_BASE  in /tmp/kustomize-316768823: exit status 128\"" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2020-09-30T21:47:52Z" grpc.service=repository.RepoServerService grpc.start_time="2020-09-30T21:46:52Z" grpc.time_ms=1877.514 span.kind=server system=grpc
```

**Comment by rumstead** [comment]
Because our repositories are hosted externally, we have to go through a proxy. I will try setting up the ssh proxy tomorrow using an init container and see if that gets around it. I suspect it will.

**Comment by rumstead** [comment]
The issue was with the base URL I was using. I had a git config that redirected my https git to ssh. The below works. 
```
https://dev.azure.com/<org>/<project>/_git/<base_repo>/base?ref=0.1.0 // remote base
https://<org>@dev.azure.com/<org>/<project>/_git/<repo> // application cr URL
```

**Comment by prasobhen** [comment]
Error: accumulating resources: accumulation err='accumulating resources from 'https://dev.azure.com/org/project/_git/<remote_repo>/k8s/backend/bases?': yaml: line 6: mapping values are not allowed in this context': git cmd = '/usr/bin/git fetch --depth=1 origin HEAD': exit status 128

Could someone help me on this error?

**Comment by rumstead** [comment]
I suggest creating a discussion question. Happy to take a look
