### ISSUE TITLE
Port CSS Transitions to argocd sync

### ISSUE THREAD

**Issue by ryancastle** [argoproj/argo-cd#4474]
# Summary

There is a gap missing between hands-on soft launch patterns (canary, blue-green etc) and a true GitOps approach to deployments. I believe ArgoCD could bridge this gap with an abstraction of state transitions, in addition to orchestrating the discrete state change as it currently does.

# Motivation

Any virtual service (eg. Service Mesh) or weighted load balancer approach could benefit from this facility. Typically the pattern is to pre-deploy actual or provisional workloads, and use some service abstraction to shift traffic between these workloads. GitOps patterns cannot capture the in-between state, so the transition is usually performed by release engineers on the CLI. Then there is a process of ensuring that the GitOps declared state matches what has been declared imperatively.

# Proposal

When ArgoCD detects that a manifest diff contains only numeric values, the UI could offer a "Sync" trigger which is not atomic. There could be options available to decide on the transition rate and shape and ArgoCD could mediate the gradual transition from the current values to the target values. The target state would always be GitOps defined, but the process of arriving there might be slightly different (atomic or based on some transition spec).

CSS Transitions are quite a good approximation of the concept. In CSS, prior to this Transitions spec, the visual transitions were done procedurally and the result was poor-quality, inconsistent transition implementations. The spec demonstrated that certain state transitions are fairly easily defined declaratively. In the context of GitOps there are additional requirements - rollbacks, interruptions and inter-dependent transition values (i.e. linked weights). 

Rollbacks could operate essentially how they currently do - an atomic state transition back to the initial state. 

Interruptions/pauses would need to somehow be managed by the UI/CLI.

Inter-dependent state transitions are challenging, but could potentially be left to end users to manage. The primary case is weights that sum to a given figure (i.e. 100), but which are not structurally linked. If transition rates were generally proportional, this may be a small issue. In the naive case of weight transition {v1:100,v2:0} => {v1:0,v2:100} it would not be an issue at all.

**Comment by jessesuen** [comment]
@ryancastle are you aware of [Argo Rollouts](https://github.com/argoproj/argo-rollouts)? which is a canary/blue-green progressive delivery resource intended to allow gradual (progressive) shifts in traffic from old to new via integration with service meshes?

Outside of that, it seems that a gitops committer which gradually updates YAML numeric values may be out of scope from Argo CD.

**Comment by ryancastle** [comment]
@jessesuen Yes. Argo Rollouts are awesome. This is a slightly different idea. It would be agnostic of the specific rollout mechanism. It's more about providing a general purpose mechanism to transition gradually from one resource set to another one.
