### ISSUE TITLE
Missing docs for installing cli on windows

### ISSUE THREAD

**Issue by lcostea** [argoproj/argo-cd#4481]
On the cli installation page there is only Linux and Mac: https://argoproj.github.io/argo-cd/cli_installation/

It would be good to have Windows also as there is binary built for the cli for Windows OS.

**Comment by lcostea** [comment]
Working now to create the PR for this

**Comment by CFR0901** [comment]
I just stumbled over the same problem. If you want to use Chocolatey, it is also installable here: https://chocolatey.org/packages/argocd/1.6.1

**Comment by lcostea** [comment]
You are right @CFR0901 but it was a one time upload. We are looking into making the upload on each release, part of the release pipeline (like it is done for homebrew on: https://github.com/argoproj/argo-cd/blob/master/.github/workflows/release.yaml)

**Comment by kostis-codefresh** [comment]
@lcostea We can close this issue now. Correct?

I see windows instructions are merged in https://argo-cd.readthedocs.io/en/stable/cli_installation/#windows
