### ISSUE TITLE
Sync failure when trying to sync a deployment, Manifest not populating correctly as shown in Argo CD UI 

### ISSUE THREAD

**Issue by rakeshr99** [argoproj/argo-cd#4486]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [yes] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ yes] I've included steps to reproduce the bug.
* [ yes] I've pasted the output of `argocd version`.

**Describe the bug**

I recently started using Argo CD, I have installed Argo CD and deployed an application using helm but I am getting the below error when I am trying to Sync a deployment(resource) which shows outOfSync

**Error**: error validating data: ValidationError(CronJob.spec.jobTemplate.spec.template.spec.volumes[6].projected.sources[0]): unknown field "name" in io.k8s.api.core.v1.VolumeProjection

**To Reproduce**

Sync a resource in the deployment which is outOfSync.

**Expected behavior**

Able to sync from the repo successfully

**Version**
argocd: v1.7.6+b04c25e.dirty
  BuildDate: 2020-09-19T01:06:53Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: dirty
  GoVersion: go1.15.2
  Compiler: gc
  Platform: darwin/amd64

**Logs**

**Error**: error validating data: ValidationError(CronJob.spec.jobTemplate.spec.template.spec.volumes[6].projected.sources[0]): unknown field "name" in io.k8s.api.core.v1.VolumeProjection

The Argo CD UI shows the below section in the generated manifest and I found out that the manifest is incorrectly populating from YAML file provided.
**Manifest as shown in Argo CD UI:**
volumes:
            - emptyDir: {}
              name: vol-workspace
            - hostPath:
                path: /var/log/splunk/dev3
                type: ''
              name: vol-log

**Above volume section in YAML file:**
          volumes:
            - name: vol-workspace
            - emptyDir: {}
            - name: vol-log
              hostPath:
                path: "{{ .Values.global.logs.hostPath }}/{{ .Release.Namespace }}"

The volumes section when populated in the manifest is jumbled somehow. I have already deployed this application without any problems using Jenkins, so the YAML provided is a valid. Could some one help me out with this issue?

**Comment by jessesuen** [comment]
> ValidationError(CronJob.spec.jobTemplate.spec.template.spec.volumes[6].projected.sources[0]): unknown field "name" in io.k8s.api.core.v1.VolumeProjection

This error is the one which is returned from Kubernetes and not Argo CD. 

>  I have already deployed this application without any problems using Jenkins, so the YAML provided is a valid.

Could you try `kubectl apply` manually and see if that works?
