### ISSUE TITLE
[SPIKE] Controller fails to update deployment history

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#449]
Controller fails to execute Patch on Application CRD. Following error was returned by K8S API : 
```
unable to find api field in struct Unstructured for the json field "metadata"
```

Unfortunately no clear steps to reproduce. Probably related to https://github.com/kubernetes/kubernetes/issues/58017

**Comment by jessesuen** [comment]
TODO: grep for frequency to evaluate level of impact.

**Comment by jessesuen** [comment]
This was occurring in pre v0.7 instances. Since then, we've reduced the PATCH calls to the K8s API server. I also grepped the logs for occurrences of this message and did not find any recently. Closing this issue until can be reproduced.
