### ISSUE TITLE
argocd cli: add app restart functionality

### ISSUE THREAD

**Issue by jgournet** [argoproj/argo-cd#4498]
# Summary
Since in the UI, we can restart an application by clicking on the deployment, it would be great to have that same feature in the argocd CLI.

# Motivation
I know the argocd kubectl plugin allows to do that, but we would need to give kubectl rights to our users and automations. At the moment, they don't have direct right access to the kubernetes cluster, but they do have access to argocd (this is because argocd access management makes things a lot easier than using kubernetes access management).

# Proposal
```
argocd app restart APPNAME
```

**Comment by alexmt** [comment]
This is actually supported. The following CLI command restarts all app deployments:

```
argocd app actions run my-app restart --kind Deployment
```

**Comment by jgournet** [comment]
Thanks @alexmt - I did not find this one
Closing this

**Comment by leansii** [comment]
Hello! is it possible to restart from Gitlab CI pipeline?

**Comment by thelman** [comment]
> Hello! is it possible to restart from Gitlab CI pipeline?

@leansii Yes it's possible, I use it
