### ISSUE TITLE
Allow control of cluster level resources independent of namespace options

### ISSUE THREAD

**Issue by hawksight** [argoproj/argo-cd#4502]
# Summary

ArgoCD should allow some flexibility on managing cluster level resources, independent of what namespaces are selected.

# Motivation

I had an issue deploying cert-manager to a cluster in the `cert-manager` namespace. More details are [here](https://github.com/argoproj/argo-cd/issues/4105#issuecomment-704388745).

It was not apparent from the errors that it was ArgoCD's error, but it raised the question about a limitation of the current namespace support for a cluster.

Currently, if you add a cluster but only allow argocd access in certain namespaces, then it cannot manage cluster level resources. In cert-managers case, it needs to create cluster level resources as part of the helm chart.

So perhaps, rather than linking to the namespace selection, there should be additional settings available when adding a cluster to argocd?

# Proposal

I don't have a concrete solution, but here is a couple possibilities:

1) add another flag to `argocd cluster add` command such as:

```
--cluster-resources=true/false (default: true)
```

2) ~Tie in access to cluster resources to argocd's project permissions?~ Scratch this, you can already limit cluster level resources by project.

From a security perspective, I think this is a `cluster add` configuration issue. I'd want to limit the cluster level access of the argocd service account. By default it'll have all, but then controlled by argocd's rbac... but what if the account is breached.. it can do anything in multiple clusters.

The other side is, I want to control the namespaces allowed to have argocd. But I always want argocd to be able to create some cluster level resources to meet my needs. This was, if the service account were breached, it would only have a limited set of permissions. This is preferable to the scenario above.

2 (2nd attempt) - In the cli, we allow a list of cluster resources to be added, that argocd can control:

eg.

```
--cluster-resource=namespaces,clusterrole,clusterrolebinding
# or
--cluster-resource=namespaces --cluster-resource=clusterrole --cluster-resource=clusterrolebinding
```

With the assumption... you can do whatever with those resources if enabled.
Otherwise this becomes more complicated again.

This follows the namespace pattern i've used:

```
argocd cluster add <SOME_CLUSTER> --namespace="fim" --namespace="rabbit" --namespace="monitoring" --namespace="cert-manager" --namespace="default" --upsert
```

**Comment by caseyclarkjamf** [comment]
I think we're running into this exact issue for CustomResourceDefinitions. The jaeger-operator Helm chart requires a CRD to be installed while everything else can be installed to a namespace. The CRD deploys fine with Argo CD as part of the jaeger-operator Helm chart (after we gave the namespaced Argo CD ServiceAccount permissions to deploy CRDs) but afterwards Argo CD always shows that CRD resource as OutOfSync and Missing.

**Comment by hawksight** [comment]
@caseyclarkjamf I think you're right that for any sort of operator this is problematic. Usually most work at a cluster level and implement whatever that custom resource needs.

I guess the current workaround is to go and manually configure the RBAC rules once argocd adds a cluster.

Does anyone know if you can declaratively add a cluster? 
If there was a specification or some yaml, maybe rather than using `--namespace` and any `--cluster-thing`, we could point `argod` to a yaml config file when adding a cluster?
