### ISSUE TITLE
Argo CD UI fail to delete apps that has no cluster URL

### ISSUE THREAD

**Issue by chetan-rns** [argoproj/argo-cd#4534]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The add/edit application form allows the user to add/edit an app either by specifying the cluster name or URL. ArgoCD UI fails to delete applications that have been created by mentioning the cluster name. The deletion works fine when the cluster URL is present.

**To Reproduce**

1. Create a new application by selecting the cluster name in the form
2. Try deleting the newly created application

**Expected behavior**

The UI must successfully delete the application

**Screenshots**

![Screenshot from 2020-10-12 15-06-51](https://user-images.githubusercontent.com/21128732/95731015-9c33bd00-0c9c-11eb-8c61-5a158624f626.png)
**Version**

```shell
argocd: v99.99.99+unknown
  BuildDate: 1970-01-01T00:00:00Z
  GitCommit: 
  GitTreeState: 
  GoVersion: go1.14.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v99.99.99+unknown
  BuildDate: 1970-01-01T00:00:00Z
  GitCommit: 
  GitTreeState: 
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.3.1+g249e521
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.16.0

```

**Comment by chetan-rns** [comment]
I suspect it's because of the cluster URL missing in `application.spec.destination.server`. When the user selects a cluster name, the UI can also add the respective cluster URL behind the scenes.

**Comment by jessesuen** [comment]
@chetan-rns would you like to take this?
