### ISSUE TITLE
ArgoCD fails to add a K3S cluster

### ISSUE THREAD

**Issue by guigo2k** [argoproj/argo-cd#4539]
I'm trying to add a `k3s` cluster to ArgoCD.

**To Reproduce**

1. Create a single node `k3s` cluster. 
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san=<k3s-public-ip>" sh -
```

2. Copy `/etc/rancher/k3s/k3s.yaml` to your machine as `k3s.yaml` and replace `localhost` with the IP of your K3s server.

3. Add the `k3s` cluster to ArgoCD.
```
$ argocd cluster add default --name k3s --kubeconfig k3s.yaml 

INFO[0000] ServiceAccount "argocd-manager" created in namespace "kube-system" 
INFO[0001] ClusterRole "argocd-manager-role" created    
INFO[0001] ClusterRoleBinding "argocd-manager-role-binding" created 
FATA[0032] rpc error: code = Unknown desc = Get "https://<k3s-public-ip>:6443/version?timeout=32s": dial tcp <k3s-public-ip>:6443: i/o timeout 
```

**Expected behavior**

Cluster is added successfully.

**Version**

```
argocd: v1.7.7+33c93ae.dirty
  BuildDate: 2020-09-29T12:06:07Z
  GitCommit: 33c93aea0b9ee3d02fb9703cd82cecce3540e954
  GitTreeState: dirty
  GoVersion: go1.15.2
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.6+b04c25e
  BuildDate: 2020-09-19T00:52:04Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Logs**

```
time="2020-10-12T23:23:57Z" level=error msg="finished unary call with code Unknown" error="Get \"https://<k3s-public-ip>:6443/version?timeout=32s\": dial tcp <k3s-public-ip>:6443: i/o timeout" grpc.code=Unknown grpc.method=Create grpc.service=cluster.ClusterService grpc.start_time="2020-10-12T23:23:27Z" grpc.time_ms=30000.932 span.kind=server system=grpc
```

**Comment by MattFellows** [comment]
@guigo2k What was your solution? I'm hitting a very similar issue, would love to know how you solved it.

**Comment by gdubya** [comment]
Ditto! https://xkcd.com/979/

**Comment by fristedt** [comment]
I had the same issue. The problem for me was that the security group (firewall) in front of the k3s cluster was blocking the cluster running argocd.

**Comment by gdubya** [comment]
Oops, i should have followed up: It was also a firewall causing our issues as well.

**Comment by jlane67** [comment]
If anyone found this ticket searching for a similar problem on EKS, you need to allow HTTPS API access from your whole VPC in your control plane security group to allow Argo CD to manage other EKS clusters in the VPC.

**Comment by omar-pulpo** [comment]
> If anyone found this ticket searching for a similar problem on EKS, you need to allow HTTPS API access from your whole VPC in your control plane security group to allow Argo CD to manage other EKS clusters in the VPC.

I have this problem in EKS, I will try your solution. Thanks
