### ISSUE TITLE
ArgoCD not reporting diff in configMap object

### ISSUE THREAD

**Issue by shivpathak** [argoproj/argo-cd#4540]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

argocd doesn't detect the diff in configMap object if we add/remove something in existing configMap which is managed by argocd. This bug is somewhat similar to [4537](https://github.com/argoproj/argo-cd/issues/4537)

We have tried to add data in configMap object using argocd UI as well as kubectl cli behaviour is same argocd reports no diff but reports data correctly in live manifest as well as on k8s cluster in configMap object.

**To Reproduce**

1 - Edit the exiting configMap (add some arbitrary data to configMap) which is managed by argocd
2 - Go to argocd UI and check live manifest (your newly added data should be there)
3 - Check desired manifest there should not be listed your newly entered data
4 - Check diff it shouldn't complain, it represents like configMap is in sync but in actually there is new data which is not source.

**Expected behavior**

I would expect argocd should show diff because live and desired manifest are not same.

**Screenshots**

- live menifest

![live-manifest](https://user-images.githubusercontent.com/10459864/95822729-18380e80-0d4a-11eb-8bb5-9991e424469d.png)

- desired manifest

![desired-manifest](https://user-images.githubusercontent.com/10459864/95822765-28e88480-0d4a-11eb-9dcb-a9a2d3096589.png)

- argocd diff
![diff](https://user-images.githubusercontent.com/10459864/95822807-3aca2780-0d4a-11eb-86de-e584195a2f35.png)

**Version**

```shell
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:44:27Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
See explanation here : https://github.com/argoproj/argo-cd/issues/4537#issuecomment-707997759
