### ISSUE TITLE
ArgoCD Memory Spike while syncing custom resource

### ISSUE THREAD

**Issue by raogayathri** [argoproj/argo-cd#4548]
I am using ArgoCD version 1.5.1. I am seeing a spike in memory consumption by the application controller while syncing the custom resource. I would like to understand what causes this behavior and also get the fix for it.

**Comment by jessesuen** [comment]
We addressed a lot of memory issues in v1.7. There were improvements when introducing CRDs into the cluster. Please try updating to see if the problem still exists. Closing for now.
