### ISSUE TITLE
Pods ending up on the same node

### ISSUE THREAD

**Issue by robertrbruno** [argoproj/argo-cd#4549]
Found that if all pods end up on the same node (just happened to me) nothing works well at least on our cluster due to hairpin issues.  Any chance the yaml could have anti-affinity set for the pods so they don't end up on the same node by accident?

**Comment by jessesuen** [comment]
We have anti-affinity for the redis pods, but no repo-server or argocd-server. I suppose since we are doing it for redis, we can do it for the others. I think `preferred` is preferable than the hard requirement.

**Comment by mnach** [comment]
Looks like there are podAntiAffinity rules in HA installation for argocd-server and repo-server: https://github.com/argoproj/argo-cd/tree/303925f4a016d7fee80bbe357341df7d3febe298/manifests/ha/base/overlays

In base installation all apps has only one replica, so podAntiAffinity relevant only for scaled-up cases.

Though we can add `preferred` based not only on `app.kubernetes.io/name` label but also on `app.kubernetes.io/part-of` (with lower weight). Thus, argocd installations with one-replica in muli-node clusters woun't fully unavailable when one node crashed/restarted

**Comment by mnacharov** [comment]
looks like fixed?

**Comment by jeremychase** [comment]
As @mnacharov said, this is fixed.

The current ha install.yaml at https://github.com/argoproj/argo-cd/blob/fa46ac178f809577285d8b37480ef1e46e7cb4a4/manifests/ha/install.yaml has `podAntiAffinity` for `argocd-repo-server` and `argocd-server` Deployments. I verified on my own cluster using the above `install.yaml`.

@robertrbruno
