### ISSUE TITLE
Make use of dex refresh tokens

### ISSUE THREAD

**Issue by merenbach** [argoproj/argo-cd#455]
Pulled from #424:

> When users login via SSO via CLI, we should be giving the dex signed token (which expires), and stop issuing API server signed tokens (which don't expire). When tokens do expire, we need to allow the token to be refreshed as conveniently as possible. Re-logging in should be convenient as well.

**Comment by merenbach** [comment]
@jessesuen I think that returning the Dex token should be pretty easy (`server/session/session.go#Create`).  I'm interested in ways we can handle refreshing, barring some mechanism like Amazon Cognito's (refresh tokens valid for 30 days by default that refresh 1-hour access and ID tokens).  One other alternative is to do re-signing, like we're doing now, but not remove the `exp` claim.

In either case, we can ensure that the SSO-produced tokens expire.  How can we then ensure we allow refreshing?

First, a functional definition of `refresh` should probably be decided upon.  If a given token has a refresh grace period of 30 days, how do we distinguish between it and a similarly-privileged token with a 30-days-from-present validity period?

This can inform our design.  **Perhaps even for local use we should be storing a _new_ token each time we reach out to the server**.  It's a lot of token generation and signing, but ensures tokens can stay current, transparently, as long as they have been _used_ at least once in what would otherwise be a timeout threshold.  This could be extended to the browser use case, updating the cookie each time.

@jessesuen or @alexmt Can we request a new Dex token each time through?

**Comment by merenbach** [comment]
Also @jessesuen @alexmt, regarding "re-logging in should be as convenient as possible," what do we need to do for the Web UI, and what improvements can we make over `argocd login` to make the CLI more convenient?  Do we interrupt commands to present a login prompt?

**Comment by jessesuen** [comment]
Dex is already issuing refresh tokens -- we are not taking advantage of them. The job here is simply to store them and redeem them when we detect the auth token is expired. Sent a PR.

**Comment by jessesuen** [comment]
Fixed in 0e78172665396d24a8816085a84b549ae3a19797
