### ISSUE TITLE
Awesome to have a test specific label

### ISSUE THREAD

**Issue by amitkrout** [argoproj/argo-cd#4554]
# Summary

What change you think needs making.

# Motivation

Please give examples of your use case, e.g. when would you use this.
When we use enhancement label, it looks like too generic. As a test contributor i would be happy to search test related task using label something like ```enhancement-test``` or may be  ```enhancement-testing```

# Proposal

How do you think this should be implemented?
Just need to add new label for example ```enhancement-test``` or may be  ```enhancement-testing```

**Comment by jessesuen** [comment]
We just created component:test label for this:

https://github.com/argoproj/argo-cd/labels/component%3Atest

Thanks for the suggestion!
