### ISSUE TITLE
New Applications with misconfiguration show up as "Healthy"

### ISSUE THREAD

**Issue by jutley** [argoproj/argo-cd#4558]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When a new Application is created in a configuration that produces an error when generating the manifests, the Application misleadingly reports as Healthy. When we create a new Kubernetes cluster and have many new Applications, it is hard to see that there is an issue. At a glance, everything looks green.

![image](https://user-images.githubusercontent.com/5660346/96012455-f8abef00-0df8-11eb-91f6-04e492b9226f.png)

**To Reproduce**

1. Create a new Helm-based Application that is entirely valid, except that it points to a non-existent values file.
2. The Application converges to health-status "Healthy" and sync-status "Unknown".

**Expected behavior**

The Application health should report either "Missing" or "Unknown".

**Version**

```shell
argocd: v1.7.3+b4c79cc
  BuildDate: 2020-09-01T23:17:31Z
  GitCommit: b4c79ccb88173604c3786dcd34e83a9d7e8919a5
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.3+b4c79cc
  BuildDate: 2020-09-01T23:19:02Z
  GitCommit: b4c79ccb88173604c3786dcd34e83a9d7e8919a5
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Comment by jessesuen** [comment]
This is expected behavior. Health and Sync status are orthogonal status which do not affect each other. e.g. you can have a completely healthy/running app, but if git is not reachable then we will still report it as healthy.

I think the one exception is that we will show applications which have missing resources as a Missing health status.

**Comment by jutley** [comment]
I understand that this is the current expected behavior, but I think it is a design flaw and a bug from a UX perspective. The application shows green in the list of applications even though there is clearly something wrong. If Argo CD is unable to generate an expectation of what the current state _should_ look like, how can it conclude that the application is healthy overall?
