### ISSUE TITLE
Add authentition config for /api/version

### ISSUE THREAD

**Issue by charles-woshicai** [argoproj/argo-cd#4570]
# Summary

Add authentition config to control whether enable `AuthFuncOverride` for the API of `/api/version`

# Motivation

At present we could call `/api/version` without signing in, which means anonymous user could get information of go version, argocd version, etc. Those information might help someone to hack the server, which is dangerous.

# Proposal

Add a config switch in `values.yaml` to control whether the API of `/api/version` enables `AuthFuncOverride`, and disable it by default.

**Comment by jessesuen** [comment]
After we split out the helm/kustomize/kubectl version from the version endpoint, I dont think this provides any benefit to security. The Argo CD version can be inferred based on the UI elements that we (publically) release and so go version and argocd version could always be inferred.

**Comment by charles-woshicai** [comment]
> After we split out the helm/kustomize/kubectl version from the version endpoint, I dont think this provides any benefit to security. The Argo CD version can be inferred based on the UI elements that we (publically) release and so go version and argocd version could always be inferred.

FYI we got a security issue about this API with low priority issued by our security team, maybe the standard is too strict.

**Comment by charles-woshicai** [comment]
> > After we split out the helm/kustomize/kubectl version from the version endpoint, I dont think this provides any benefit to security. The Argo CD version can be inferred based on the UI elements that we (publically) release and so go version and argocd version could always be inferred.
> 
> FYI we got a security issue about this API with low priority issued by our security team, maybe the standard is too strict.

Well, as the priority of this enhancement is low, I would close this issue as you won't adjust this.
