### ISSUE TITLE
Question: Backup HA ArgoCD deployment configuration for migration

### ISSUE THREAD

**Issue by eroji** [argoproj/argo-cd#4579]
I'm looking for the procedures to migrate an existing HA ArgoCD deployment deployed to Kubernetes to a different cluster. Looking up the documentations [this](https://argoproj.github.io/argo-cd/operator-manual/disaster_recovery/) is the closest thing I found, although I am not clear by just reading this page. Can someone give me a rundown of what is the correct way of doing this? I imagine there are others that may find the instructions useful.

Just looking at the page, I'm assuming I need to do this on a machine with `kubectl` and `kubeconfig` pointing to the cluster where ArgoCD is deployed to. I probably also need Docker as it looks like I need to run an ArgoCD container of the same version to use the `argocd-util` binary to explort out the configuration as a YAML. Is this correct? Furthermore, is this `backup.yaml` a complete configuration backup of everything configured? IE, cluster, authentication, project, applications.

**Comment by jessesuen** [comment]
Your assumptions are correct. Basically you run `argocd-util export` to export everything (which is close but not exactly the same as `kubectl get ___ -o yaml > backup.yaml`), followed by `argocd-util import` to create everything in the backup cluster.  We have a cron job which does exactly that.

The docker image is a convenience to gain access to the CLI, but not strictly required.

**Comment by rohith2094** [comment]
> Your assumptions are correct. Basically you run `argocd-util export` to export everything (which is close but not exactly the same as `kubectl get ___ -o yaml > backup.yaml`), followed by `argocd-util import` to create everything in the backup cluster. We have a cron job which does exactly that.
> 
> The docker image is a convenience to gain access to the CLI, but not strictly required.

can you please share cron job details ?

**Comment by vl-kp** [comment]
also interesting in the cron job
