### ISSUE TITLE
Allow generic ExecProvider settings in Cluster config

### ISSUE THREAD

**Issue by jMarkP** [argoproj/argo-cd#4600]
# Summary

The K8s client-go `rest.Config` ([ref](https://godoc.org/k8s.io/client-go/rest#Config)) supports an `ExecProvider` option which allows users to define an external executable to call on-demand to retrieve API creds.

ArgoCD already supports one specific example of this with the `AWSAuthConfig`, which gets mapped to a `rest.Config.ExecProvider` object ([src](https://github.com/argoproj/argo-cd/blob/303925f4a016d7fee80bbe357341df7d3febe298/pkg/apis/application/v1alpha1/types.go#L2511)). Can we extend this to support generic `ExecProvider` configuration in `Cluster` secrets?

# Motivation

Our self-hosted Kubernetes deployment makes use of `ExecProvider` for authentication. There is currently no way for us to supply the required config directly to ArgoCD in a cluster secret. Instead we have to run a cron job to ahead-of-time generate a bearer token to inject into the `Cluster` secret. This is flaky and we'd rather have ArgoCD authenticate on-demand like our other clients do.

# Proposal

- Add an `ExecProviderConfig` struct to [`ClusterConfig`](https://github.com/argoproj/argo-cd/blob/303925f4a016d7fee80bbe357341df7d3febe298/pkg/apis/application/v1alpha1/types.go#L1120), containing the values available in https://godoc.org/k8s.io/client-go/tools/clientcmd/api#ExecConfig e.g.
```
apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: mycluster.com
  server: https://mycluster.com
  config: |
    {
      "execProviderConfig": {
        "command": "foo",
        "args": [ "--bar", "123" ],
        "env": {
          "ABC": "def"
        }
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64 encoded certificate>"
      }
    }
```
- In [`func (c *Cluster) RawRestConfig() *rest.Config`](https://github.com/argoproj/argo-cd/blob/303925f4a016d7fee80bbe357341df7d3febe298/pkg/apis/application/v1alpha1/types.go#L2491) add a block to map any supplied `ExecProviderConfig` to the equivalent `rest.Config.ExecProvider` settings
- Update the CLI cluster management commands to handle these new options
- Update docs: format for `Cluster` secret, plus pointers to the BYOI docs to ensure the exec provider binary is available for ArgoCD to call

I have the first three steps done on a local branch (working out how to best test it) so happy to raise a PR to fix this if you agree with the feature / my proposed implementation.

Note - this arguably adds a bit of tech debt/redundancy: why have `AWSAuthConfig` if the same effect could be obtained through a `ExecProviderConfig` with command `aws`? To me this feels acceptable in order to provide more flexible Cluster auth options (and maybe `AWSAuthConfig` could be deprecated in future major version upgrades?) but you may disagree with me!

# Alternative proposal

Allow the `ClusterConfig` option to contain a complete https://godoc.org/k8s.io/client-go/rest#Config object so that any valid `rest.Config` options can be supplied to ArgoCD in addition to the existing settings:

```
apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: mycluster.com
  server: https://mycluster.com
  config: |
    {
      "username": "user",
      "password": "pass",
      "additionalRestConfig": {
        "execProvider": {...},
        "impersonate": {...}
        ..
      }
    }
```

In that case I guess that would require a complete shadow clone of the K8s type in Argo so that it can work with the generated proto API. Plus this needs to be representable on the command line as well. This seems like a bigger change to me, but maybe it's the correct one?

**Comment by alexmt** [comment]
Agree with your fisrt proposal (add `ExecProviderConfig` ) and the spec changes. PR would be very welcome.

**Comment by jMarkP** [comment]
Thanks! Will work on finishing off my change and raising a PR

**Comment by MPV** [comment]
This seems related to #4651 (being able to config a Cluster using regular Kubeconfig), but while #4651 prefers referring to an existing secret with a base64-encoded, I understand that your proposal here @jMarkP is about embedding the full Kubeconfig inside the Cluster config. Just wanted to mention this, to see if there's any values in syncing ideas/solutions based on similar/common use cases.

**Comment by jMarkP** [comment]
@MPV - thanks for that link, I think we are both trying to solve similar problems.

> I understand that your proposal here @jMarkP is about embedding the full Kubeconfig inside the Cluster config
Not directly. My proposal here is more limited to just extending the existing ArgoCD cluster secret format (the `ClusterConfig` struct) to add support for the `ExecProvider` options. Having said that, being able to supply an arbitrary kubeconfig file for a `Cluster` that ArgoCD could just deserialize straight into a Kubernetes `rest.Config` would certainly solve my issue, and would seem to allow use cases like yours where all you have is an opaque kubeconfig that you want to use.
