### ISSUE TITLE
Add ssh known host form is missing white background

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4609]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Unlike most forms in argocd, there's no white background in the add ssh known host form

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

1. Visit https://cd.apps.argoproj.io/applications?new=%7B%22apiVersion%22%3A%22argoproj.io%2Fv1alpha1%22%2C%22kind%22%3A%22Application%22%2C%22metadata%22%3A%7B%22name%22%3A%22%22%7D%2C%22spec%22%3A%7B%22destination%22%3A%7B%22name%22%3A%22%22%2C%22namespace%22%3A%22%22%2C%22server%22%3A%22%22%7D%2C%22source%22%3A%7B%22path%22%3A%22%22%2C%22repoURL%22%3A%22%22%2C%22targetRevision%22%3A%22HEAD%22%7D%2C%22project%22%3A%22%22%7D%7D
1. Visit https://cd.apps.argoproj.io/settings/certs?addSSHKnownHosts=true

**Expected behavior**

**Screenshots**

![visible distinction between form fields and outer area](https://user-images.githubusercontent.com/2119212/96536497-375f0080-1262-11eb-9a1f-4c88311bb767.png)
![no visible distinction](https://user-images.githubusercontent.com/2119212/96536554-53fb3880-1262-11eb-9631-67bd245aeee9.png)

**Version**

```shell
{
    "Version": "v1.8.0+05c493b",
    "BuildDate": "2020-10-20T02:01:12Z",
    "GitCommit": "05c493b3a6de9f95f7e11eb35148e1639cf601b4",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.1",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.3.1+g249e521",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.16.0"
}
```

**Logs**

**Comment by iam-veeramalla** [comment]
This issue can be closed now.
