### ISSUE TITLE
Update swagger docs

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4610]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/swagger-ui#tag/AccountService
   * https://cd.apps.argoproj.io/swagger-ui#operation/RunResourceAction
   * https://cd.apps.argoproj.io/swagger-ui#operation/CanI
   * https://cd.apps.argoproj.io/swagger-ui#operation/GetAccount
   * https://cd.apps.argoproj.io/swagger-ui#operation/CreateTokenMixin7
   * https://cd.apps.argoproj.io/swagger-ui#operation/DeleteTokenMixin7
1. Visit https://cd.apps.argoproj.io/swagger-ui#tag/ApplicationService
   * https://cd.apps.argoproj.io/swagger-ui#operation/ManagedResources
   * https://cd.apps.argoproj.io/swagger-ui#operation/ResourceTree
   * https://cd.apps.argoproj.io/swagger-ui#operation/ListResourceActions
   * https://cd.apps.argoproj.io/swagger-ui#operation/RunResourceAction
1. Visit https://cd.apps.argoproj.io/swagger-ui#tag/RepositoryService
   * https://cd.apps.argoproj.io/swagger-ui#operation/GetHelmCharts
1. Visit https://cd.apps.argoproj.io/swagger-ui#operation/GetSyncWindowsState
   > GetSchedulesState returns true if there are any active sync syncWindows

**Expected behavior**

Function should have a description to the right of the function name...

**Screenshots**

> AccountService
> GET ListAccounts
> GET CanI
> PUT UpdatePassword updates an account's password to a new value
> GET GetAccount
> POST CreateTokenMixin7
> DEL DeleteTokenMixin7

**Version**

```shell
{
    "Version": "v1.8.0+05c493b",
    "BuildDate": "2020-10-20T01:22:18Z",
    "GitCommit": "05c493b3a6de9f95f7e11eb35148e1639cf601b4",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.1",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.3.1+g249e521",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.16.0"
}
```

**Logs**

**Comment by mayzhang2000** [comment]
Since the PR is merged already, I am closing it.
