### ISSUE TITLE
Add the ability to add annotations to all automatically created namespaces

### ISSUE THREAD

**Issue by insanemal** [argoproj/argo-cd#4628]
# Summary

Currently Argo CD can automatically create namespaces. We use Rancher UI. These namespaces do not have the RancherUI annotation for Rancher Projects. It would be nice to be able to define on the Project or even application level annotations that get added to automatically created Namespaces.

# Motivation

When using ArgoCD and Rancher UI

# Proposal

I think it could be a project level mapping. That way you could map Argo Projects to Rancher Projects. But possibly with App level overrides. It is really about annotating the namespace.

**Comment by KarstenSiemer** [comment]
Any update or workarounds for this? This is a great feature and this is the somewhat first question you ask yourself when using it.

**Comment by insanemal** [comment]
Yeah, it's still an issue for us. It would be super great for other reasons as well. Using Filebeat/Logstash being able to set project wide annotations is also a boon.

**Comment by whyman** [comment]
👍 From us too, for [External Secrets key name restrictions](https://github.com/external-secrets/kubernetes-external-secrets#using-namespace-annotation)

**Comment by mcorbin** [comment]
I'm also interested by this feature (I can also probably find some time to work on it).
A lot of tools rely on labels or annotations on namespaces and implementing this would I think help a lot of people.

**Comment by rishabh625** [comment]
Instead of adding it as feature, just committing those namespaces in git with required annotations and creating application to manage it wouldn't be enough?

**Comment by insanemal** [comment]
If that were enough would we be here?

**Comment by rishabh625** [comment]
I would like not volunteer for contributing to this feature if no one else is working

**Comment by crenshaw-dev** [comment]
@insanemal how would you feel about this?

```
- CreateNamespaceLabels= io.foo.bar/this=labelValue,io.foo.bar/that=labelValue
```

I like @KarstenSiemer's suggestion to add new fields, but those are big (breaking?) changes. Might be a good idea for v3.0.

@ashutosh16 want to see if you have time to work on this?

**Comment by insanemal** [comment]
I need annotations not Labels. But the syntax is good

**Comment by ashutosh16** [comment]
I'm thinking to add the annotation to the `createnamespace` sync option itself.
```
CreateNamespace=true,io.foo.bar/this=x
```
I made the [code](https://github.com/ashutosh16/argo-cd/blob/feat/customnamespace-annotation/controller/sync.go#L236-L247) change and tested it in local. I'm able to create a namespace with/without annotation. Do we still need a separate sync option?

**Comment by crenshaw-dev** [comment]
@ashutosh16 I think we'll probably want to provide the option to accept the labels/annotations JSON-encoded so people are free to include and `=` or `,` in their config. Like this:

```yaml
- CreateNamespaceAnnotations={"io.foo.bar/this": "x"}
```

**Comment by leoluz** [comment]
> Instead of adding it as feature, just committing those namespaces in git with required annotations and creating application to manage it wouldn't be enough?

@insanemal can you please elaborate on why @rishabh625 suggestion above doesn't satisfy your use-case? I don't use Rancher UI but would like to understand the implications a bit better.

**Comment by crenshaw-dev** [comment]
Reasons for CreateNamespace, per the original issue thread:
* Using external Helm charts that might not come with their own namespace; you'd have to create a second app for the namespace - https://github.com/argoproj/argo-cd/issues/1809#issuecomment-553101410
* If a presync hook depends on the ns, you have to create it in the presync hook; afaik this isn't a huge burden, just a bit more complexity - https://github.com/argoproj/argo-cd/issues/1809#issuecomment-652046108

Not sure if either of these applies to @insanemal.

**Comment by crenshaw-dev** [comment]
@leoluz some additional use cases are described in similar PRs here:
* https://github.com/argoproj/argo-cd/issues/6215
* https://github.com/argoproj/argo-cd/issues/7799
