### ISSUE TITLE
Surface helm parameters to the application level

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#463]
Similar to how we surface ksonnet parameters from `ks param list`. We could also surface helm parameters to application level, by parsing the values.yaml and flattening the map structure into a key value map (with dot notation to separate nested maps). 

Note that helm supports multiple value files (i.e. you can run `helm template <dir> -f values1.yaml -f values2.yaml`. So the implementation will need to take into consideration when multiple value files are supplied. I believe the last values file supplied takes the most precedence.

**Comment by alexmt** [comment]
working on it
