### ISSUE TITLE
argocd proj role create-token project role - missing ability to name a token

### ISSUE THREAD

**Issue by rosscdh** [argoproj/argo-cd#4632]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

the argocd cli when creating project tokens lacks the ability to name the token (as the UI allows)

**To Reproduce**

`argocd proj role create-token project role -n`
or
`argocd proj role create-token project role token-name`

**Expected behavior**

a named token is created

**Version**

```shell
argocd: v1.7.8+ef5010c.dirty
  BuildDate: 2020-10-16T01:33:41Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: dirty
  GoVersion: go1.15.2
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.6+b04c25e
  BuildDate: 2020-09-19T00:52:04Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Comment by tetchel** [comment]
I can pick this up.

**Comment by tetchel** [comment]
There also doesn't seem to be a way to list the tokens for a given role, another feature that is available in the web UI.
