### ISSUE TITLE
Add menu to get command to connect to container

### ISSUE THREAD

**Issue by aaad** [argoproj/argo-cd#4639]
# Summary

When I debug a container in k8 I need to connect to the container. For this I need to query the pod, container and namespace. It would help me if I had a window in argocd that allows me to copy the command to exec into the container. The command may be: kubectl -n namespace exec -it pod-name -c container-name -- /bin/sh  

# Motivation

It would help me work more efficient with k8.

# Proposal

Implement a button that copies the command into the clipboard and next to it a button that shows the command.

**Comment by tetchel** [comment]
hi, is this where you'd want it?
![image](https://user-images.githubusercontent.com/8888438/96883584-94b7a500-144e-11eb-8dff-d5638ca1eb3c.png)

**Comment by aaad** [comment]
Hi, thank you for the fast response.

Yes, but one line for each container that runs inside the pod. Or in the logs.

**Comment by tetchel** [comment]
The logs view already has the containers listed.

Maybe we could rename that view to "Containers" and have the kubectl command somewhere there too.

**Comment by aaad** [comment]
Sounds great! Most of the time when I debug a problem I switch to the logs and sometimes decide to jump into the container. This would be a good place for me and help me a lot. :)

**Comment by dolefirenko** [comment]
This will be a really good feature for ArgoCD... Awaiting :)

**Comment by keithchong** [comment]
Hi @dolefirenko, @aaad, do you still need this enhancement if the following is implemented? 

https://github.com/argoproj/argo-cd/issues/4351

**Comment by aaad** [comment]
Hi, for me #4351 would even be better :)

**Comment by keithchong** [comment]
Ok, @aaad, closing this because of #4351 is already delivered.
