### ISSUE TITLE
Display List of Git Branches as Drop Down

### ISSUE THREAD

**Issue by rajivml** [argoproj/argo-cd#4645]
HI,

# Summary

Is it possible to display list of all branches under a github repo. Since you guys support both branches and tags may be an additional drop drop where user will select he needs branches or tags , if branches is selected then show list of branches as an other drop and if tags is selected then fetch and show list of tags as drop down

![image](https://user-images.githubusercontent.com/46923567/96998357-f3fdde00-1550-11eb-8b91-2c7320c9c236.png)

# Motivation

We are evaluating using argoCD as an deployment option through which our customers can install/upgrade software on varous kubernetes environments. One feedback that has come in, how to customers discover new software releases where release/20.4 is one release and release/20.5 is an other release but how do customers know that from release/20.4 they have to go to release/20.5 without visiting github repo  

Thanks

**Comment by tetchel** [comment]
I will pick this up

**Comment by tetchel** [comment]
1. Is there a use-case for tags here, too? Or are we only interested in branches?

Obviously I don't want to show every revision, since a list of all commit hashes would not be very useful.

2. Is there any preference for the order to display the branches in? 
eg. 
  - Most recently updated
  - Lexographic
  - something else?

**Comment by tetchel** [comment]
![image](https://user-images.githubusercontent.com/8888438/97660093-fc6d8180-1a46-11eb-8f46-8bae592acbad.png)

I went with HEAD, then branches, then tags. I think a way to toggle "show branches" and "show tags" options would be useful, but I will keep it simpler for now.

**Comment by tetchel** [comment]
I added it to the App summary page too. 
![image](https://user-images.githubusercontent.com/8888438/97660184-33439780-1a47-11eb-94b4-5a3b080e54ee.png)

**Comment by rajivml** [comment]
@tetchel Thanks for picking this up so quickly, I was on vacation, so I missed your comments....if we can add toggle option as well i.e. tags vs branches defaulting it to branches it will be more helpful as we use both branches and tags 

shall I raise a different ticket for the toggle feature ? BTW in which argoCD version this feature will be available ?

**Comment by tetchel** [comment]
Hi Rajiv, I opened a new issue for your request. 

I _believe_ this feature will be available in the next argocd release, 1.8. But Alex can confirm

**Comment by rajivml** [comment]
@alexmt can you please confirm which argo version will have this change ? I just now installed argo 1.7.9 and I couldn't see this change

**Comment by rajivml** [comment]
![image](https://user-images.githubusercontent.com/46923567/101607160-41171000-3a2a-11eb-9a55-b04ffc75553b.png)

Installed 1.8 and I can see this change, thanks a lot for making this change
