### ISSUE TITLE
No error marker/message if an invalid filter is applied

### ISSUE THREAD

**Issue by tetchel** [argoproj/argo-cd#4665]
If you enter an invalid filter, IE a project, cluster, or namespace that does not exist, there is no feedback. 

The Filters box already knows what valid entries are - you can see them in the autocomplete. So if a filter that will never be satisfied is applied, we should draw the user's attention to that filter in some obvious way.

![image](https://user-images.githubusercontent.com/8888438/97220445-dd9a9100-17a1-11eb-8d75-1e8c9bd4ff3c.png)

**Comment by saumeya** [comment]
The current implementation shows all the options in the dropdown if the filter is incorrect. Can this be closed?

**Comment by tetchel** [comment]
I haven't worked on ArgoCD in a year and a half, so, probably it can.
