### ISSUE TITLE
Add Istio objects to the Network view

### ISSUE THREAD

**Issue by OmerKahani** [argoproj/argo-cd#4675]
# Summary

Add Istio objects to the network view, to better visualis the network of the application.
Istio has serval objects: Virtual service, Gateway, Ingress-gateway.

# Motivation

We have applications with Istio, so the traffic goes from an Ingress to a service and pods (ingress-gateway), and from there using virtual service and gateway to anther service and pods (the businss pods)

Today we can only see the traffic from the ingress to the ingress gateway.
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/8766193/97318894-02ac0400-1875-11eb-884e-ede39b1c653f.png">

# Proposal

Add gateway and virtual service to the network view.

How do you think this should be implemented?

Virtual service is trival as it is easy to understand which services it will forwrd traffic to.
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/8766193/97318345-71d52880-1874-11eb-92db-3fa353757f85.png">

Gateway is more complicated: virtual services know the gateway but not the other way around. And gateway uses a selctor to find the relvant pods (ingress-gateway) - so it's kinf of the ingress object in the `ResourceNetworkingInfo` but there isn't a built in support for this use case.

**Comment by OmerKahani** [comment]
Hi, about the Gateway and the ingress-gateway:
Gateway uses a selector to config the ingress gateway according to the relevant virtual service.
The virtual service has the name of the relevant gateway in his spec.

This is kind of the ingress object in the `ResourceNetworkingInfo`, where the service added his upstream ingress. 
The gateway should have the option to set the upstream labels (select to ingress-gateway) and the virtual service should be able to set upsream target (the gateway).

The ui will then mach the upstream to existing objects in the application based on the same logic at the downstream mach today.

@alexmt  - does this make sens?  If so I will continue working on it.

**Comment by jessesuen** [comment]
This is fixed
