### ISSUE TITLE
PVC Resizing through ArgoCD

### ISSUE THREAD

**Issue by simran3695** [argoproj/argo-cd#4693]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Argocd is not applying the changes for PVC Resizing when we edit through applications helm values.yaml

**To Reproduce**

1} Deploy an application using helm (application that used pvc and values.yaml of the helm should have dynamic nature of resizing the PVC.)
2) Try changing the pvc size from values.yaml of the helm itself
3) deploy the code and synch from argocd

**Expected behavior**

When I change the PVC size from applications helm values.yaml the Argocd shoes the changes but when logging in to the backend I cannot see any changes in the PVC size. For PVC Resizing I have to manually edit the pvc yaml file and then after file system resizing is completed PVC get resizied and the argocd redeploys the application's statefulset.

We are expecting the changes done on the values.yml and then deploying code and synched back using argocd should reflect the changes in the backend too for PVC Resizing

**Version**

```shell
Paste the output from `argocd version` here.
```
argocd version - v1.6.0

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
This is not the responsibility of Argo CD. Argo CD simply `kubectl applies` desired manifests. If the controller which handles the PVC doesn't resize it, then that is the issue of the backend controller.
