### ISSUE TITLE
argo-server will connect kube-apiserver failed

### ISSUE THREAD

**Issue by wenwenxiong** [argoproj/argo-cd#4705]
https://github.com/argoproj/argo-cd/blob/f02115af155447f47d1921b7220af1effbf7d8e9/util/settings/settings.go#L1261

 hard code k8s cluster will choose cluster.local as dns_domian ,in k8s cluster choose different dns_domain will be connect failed for InitializeSettings with wrong  TLS cert.

**Comment by jessesuen** [comment]
> in k8s cluster choose different dns_domain

Are you saying it is possible to configure these differently? How is this possible?

The auto-generated cert is meant as a temporary self-signed cert (just to have one), but the certs are intended to be replaced with one provided by the user (e.g. with cert-manager)

**Comment by servo1x** [comment]
@jessesuen, kubespray lets users specify their own `dns_domain`: https://github.com/kubernetes-sigs/kubespray/blob/master/docs/vars.md#cluster-variables
