### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by StianOvrevage** [argoproj/argo-cd#4722]
# Summary

Add a dark mode to web console. 

# Motivation

Winter is coming up north and my eyes are hurting.

# Proposal

CSS?

**Comment by jessesuen** [comment]
FYI, CSS can already be customized so technically this is already possible.

**Comment by tete17** [comment]
Hi @jessesuen I think @StianOvrevage was referring more to a toggle feature where the ui can switch from one state to another at the user wish.

Similar to what Grafana or Kibana offers. Can't promise anything but if you give me a couple of tips on where to find these css's I can maybe help out.

I am asking because I know argo keeps all it's ui components in a different project and I am not sure how the glue between the argo app controller (this repo I presume) and the ui work.

**Comment by theNewFlesh** [comment]
+1

**Comment by theNewFlesh** [comment]
I've created a stylish theme for ArgoCD with my dark mode style I use for everything.
Check it out [here](https://userstyles.org/styles/201013/henanigans-for-argocd) if you want.

**Comment by shankiflang** [comment]
+1

**Comment by ernelio** [comment]
+1

**Comment by richardfelkl** [comment]
+1

**Comment by matan1811** [comment]
+1

**Comment by saumeya** [comment]
I'll work on this!

**Comment by theNewFlesh** [comment]
@saumeya  That stylish theme also applies to Argo Workflows BTW.

**Comment by saumeya** [comment]
Looks pretty cool @theNewFlesh, is it applied to argo using configmap?

**Comment by theNewFlesh** [comment]
@saumeya 
Nope.

[Stylish](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe) is a browser extension for chrome and brave. It matches URL's based on regex and or domain and injects a custom CSS that overrides the page. That custom CSS is found as a Stylish package on [userstyles.org](userstyles.org), which is also how you install it.

**Comment by saumeya** [comment]
Ah, thanks for sharing this info. I'll try it out. I was thinking more from the perspective of having a toggle within the application.

**Comment by theNewFlesh** [comment]
Yeah, that would be great. Until then, this is what I use. I recommend you copy the CSS and go from there.

Stylish will disable the theme toggle if the URL of ArgoCD doesn't match what's in the stylish theme settings. So, you will probably have to configure that to some regex and/or domain where you are running Argo. Click Stylish menu icon then [kebab] then edit button of the theme to see the CSS and change the URLs.

**Comment by sergeyshevch** [comment]
I guess it will be great to automatically detect OS light/dark mode and use it for the theme in ArgoCD. I will very much like such feature. (Github works in similar way)

**Comment by crenshaw-dev** [comment]
@sergeyshevch can you open an enhancement request for that?

**Comment by laiminhtrung1997** [comment]
How can I set the dark mode as the default theme when starting the ArgoCD UI?

**Comment by thiagowfx** [comment]
@laiminhtrung1997 filed a FR for it (see above).
