### ISSUE TITLE
(?) icon is used both for unknown and help

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4730]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When an app is first found by argo, or if after being first found by argo, the helm template command fails, argo will show two `(?)` icons ([fa-question-circle](https://fontawesome.com/icons/question-circle)) next to each other, one is an "unknown state", and the other is "help" -- they are ~nearly~ identical and the juxtaposition is problematic.

**To Reproduce**

1. Create an app file pointing to a chart that requires a values file
1. Don't provide the values file
1. Ask argo to digest the set

**Expected behavior**

Don't use nearly identical icons (even if the sizes are slightly different) to refer to unrelated concepts

**Screenshots**

https://cd.apps.argoproj.io/applications/rollouts-demo
![? Missing ?](https://user-images.githubusercontent.com/2119212/98409651-40f9ae00-2041-11eb-826e-2e63e4786fe9.png)

**Version**

```shell
{
    "Version": "v1.8.0+05c493b",
    "BuildDate": "2020-10-20T02:01:12Z",
    "GitCommit": "05c493b3a6de9f95f7e11eb35148e1639cf601b4",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.1",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.3.1+g249e521",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.16.0"
}
```

**Logs**

**Comment by jsoref** [comment]
For my reference, it's in fact the *same* icon: https://github.com/argoproj/argo-cd/search?q=fa-question-circle
https://github.com/argoproj/argo-cd/blob/416969730235593181ab88dc0d6efb80ff0e7902/ui/src/app/settings/components/project-sync-windows-edit/project-sync-windows-edit.tsx#L12-L17
https://github.com/argoproj/argo-cd/blob/3e19b2fdf144bb924ecb92614f9ff4d5eb2b5d35/ui/src/app/settings/components/project-details/project-details.tsx#L32-L37
https://github.com/argoproj/argo-cd/blob/cdb3df1077af6832c53cd72ec8b2fc0f5cdf7998/ui/src/app/applications/components/utils.tsx#L91-L92
https://github.com/argoproj/argo-cd/blob/cdb3df1077af6832c53cd72ec8b2fc0f5cdf7998/ui/src/app/applications/components/utils.tsx#L156-L158
https://github.com/argoproj/argo-cd/blob/cdb3df1077af6832c53cd72ec8b2fc0f5cdf7998/ui/src/app/applications/components/utils.tsx#L185-L187
https://github.com/argoproj/argo-cd/blob/cdb3df1077af6832c53cd72ec8b2fc0f5cdf7998/ui/src/app/applications/components/utils.tsx#L430-L464

**Comment by jsoref** [comment]
Possible icons for unknown:
* https://fontawesome.com/icons/cloudversify 
![cloudversify](https://user-images.githubusercontent.com/2119212/98321954-4957d780-1fb4-11eb-9bdc-253c6ba352c0.png)
* https://fontawesome.com/icons/cloud?style=solid
![cloud](https://user-images.githubusercontent.com/2119212/98322051-88862880-1fb4-11eb-9eb6-21416bc6d0e9.png)
* https://fontawesome.com/icons/meh-blank?style=regular
![meh-blank](https://user-images.githubusercontent.com/2119212/98322214-e9adfc00-1fb4-11eb-96ef-f103814b9099.png)
* https://fontawesome.com/icons/ghost?style=solid
![ghost](https://user-images.githubusercontent.com/2119212/98322284-13ffb980-1fb5-11eb-9d66-f602f9aa50ea.png)

If any of these appeal, I can write a PR for it.

**Comment by jsoref** [comment]
Alternatively, the help icon could be replaced by an info icon, as it isn't really help.
* https://fontawesome.com/icons/info-circle?style=regular
![info-circle](https://user-images.githubusercontent.com/2119212/98322639-ec5d2100-1fb5-11eb-8134-faf4e9fc0139.png)

**Comment by alexmt** [comment]
I think ghost is the best option

* https://fontawesome.com/icons/ghost?style=solid
![ghost](https://user-images.githubusercontent.com/2119212/98322284-13ffb980-1fb5-11eb-9d66-f602f9aa50ea.png)

Argo CD has to show unknown when it does not know status or cannot show it because user don't have permissions.  I think ghost  works well for both cases.
