### ISSUE TITLE
Rollout health lua script needs to be updated for v0.9

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#4732]
**Describe the bug**

There is some changes in the logic in rollouts health assessment that needs to be propagated to Argo CD (consideration of status.stableRS and observedGeneration)

**Version**

v1.7.8

**Logs**

```
Paste any relevant application logs here.
```

**Comment by smitthakkar96** [comment]
Can we backport this to 1.7 URGENTLY as updating Argo Rollouts version is breaking the UI for argocd

**Comment by jessesuen** [comment]
Which version of Rollouts? 

I originally mislabeled the title of this as Argo Rollouts v0.9. In fact, the work I did was make Argo CD v1.8 compatible with Rollouts v0.10

**Comment by jessesuen** [comment]
Argo CD v1.7 should be fully compatible with Rollouts v0.9. The current problem is that rollout actions in Argo CD v1.7 do not work well with Rollouts v0.10. 

The change will be difficult to backport because it depended on a gitops-engine change that is hard to consume from Argo CD v1.7.  If this is urgent, you rollback Rollouts back to v0.9.3
