### ISSUE TITLE
argocd CLI dry-run to produce declarative resources

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#4734]
# Summary

Users often struggle creating the declarative objects in the same way the API server does. 

```shell
argocd app create --dry-run -o declarativeoutput (better name needed)

argocd cluster add CONTEXT --dry-run -o declarativeoutput (better name needed)
```

which would produce the underlying objects (e.g. Repo or cluster secret and config map entry) that need to exist in the argo-cd namespace, so that users could create these object out-of-band.

**Comment by kshamajain99** [comment]
I am looking into this issue.

**Comment by jessesuen** [comment]
Since repos and clusters are underlyingly Secrets, we can't do this through API server. Proposal is to do this in argocd-util, like:

```
argocd-util config app create
argocd-util config approj create
argocd-util config repo add https://git.example.com/repos/repo --username git --password secret
argocd-util config cluster add CONTEXT
```

Syntax TBD

**Comment by djajcevic** [comment]
Hi! Any plans/milestone?

**Comment by jessesuen** [comment]
Fixed
