### ISSUE TITLE
Resources in whitelist\blacklist are ignored with ComparisonError

### ISSUE THREAD

**Issue by Unb9rn** [argoproj/argo-cd#4737]
**Describe the bug**

I've tried placing a namespaced resource which I don't have permissions for into a blacklist, yet the app won't deploy with "ComparisonError" stating that 
`cannot list resource "prometheusrules" in API group "monitoring.coreos.com" in the namespace "equeo-argocd"`
I've also tried replacing this blacklist with a whitelist:
```
  namespaceResourceWhitelist:
  - group: apps
    kind: Deployment
```
The result is still the same. It tries to list the forbidden resource

**To Reproduce**

Create a Project with a blacklist (or a whitelist), set permissions for serviceaccount to be unable to list those blacklisted resources. Try to create an app.

**Expected behavior**

The application is created any synced, blacklisted resources are left out of the picture.

**Screenshots**
![Screenshot from 2020-11-03 13-48-38](https://user-images.githubusercontent.com/25369809/97971002-d09e2300-1ddb-11eb-978d-b0993c898906.png)
![Screenshot from 2020-11-03 13-47-51](https://user-images.githubusercontent.com/25369809/97971006-d1cf5000-1ddb-11eb-92de-a39ceb505909.png)

**Version**

ArgoCD v1.7.8+ef5010c

**Logs**

For example:
```
  Conditions:
    Last Transition Time:  2020-11-03T09:48:29Z
    Message:               failed to load initial state of resource Alertmanager.monitoring.coreos.com: alertmanagers.monitoring.coreos.com is forbidden: User "u-hykiyc2dqb" cannot list resource "alertmanagers" in API group "monitoring.coreos.com" in the namespace "equeo-argocd"
    Type:                  ComparisonError
```

**Comment by jannfis** [comment]
Please have a look [here](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#resource-exclusioninclusion) for how to prevent Argo CD from accessing any resources it is not allowed to by cluster RBAC.

**Comment by Unb9rn** [comment]
> Please have a look [here](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#resource-exclusioninclusion) for how to prevent Argo CD from accessing any resources it is not allowed to by cluster RBAC.

Oh, thanks! Those features don't "overlap"...

**Comment by jannfis** [comment]
I guess whitelist/blacklist on project level enforce what may exist in the source manifest, while resource exclusion/inclusion determine which resources Argo CD will access on the cluster level.

I agree that it can be confusing, however. Maybe there should be a hint in the project documentation to the resource exclusion/inclusion feature and vice versa, better explaining the use cases for the two.
