### ISSUE TITLE
DevTools failed to load SourceMap(s)

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4747]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

SourceMaps are missing

**To Reproduce**

1. Open a browser window
1. Right click and choose inspect
1. In that browser window, visit https://cd.apps.argoproj.io/applications
1. Go back to inspector

**Expected behavior**

No errors in the console -- especially none of the form:
```
DevTools failed to load SourceMap: Could not load content for https://cd.apps.argoproj.io/main.a7497e334a03f6be6e2b.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cd.apps.argoproj.io/4.a7497e334a03f6be6e2b.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cd.apps.argoproj.io/ReactToastify.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Screenshots**

**Version**

```shell
{
    "Version": "v1.8.0+da3ab59",
    "BuildDate": "2020-11-03T19:49:45Z",
    "GitCommit": "da3ab59be0d95f4b644f4598be3789a3971b4be3",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.1",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.0+g7090a89",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.16.0"
}
```

**Logs**

**Comment by alexmt** [comment]
Looks like Chrome does it for all javascript files: https://support.google.com/webdesigner/thread/71102880?hl=en
Seems like there is no way to stop it and it does not affect any one, so I think we can just ignore it. Do you agree @jsoref ?

**Comment by alexmt** [comment]
Looks like we cannot do much to get rid of this warning message. Chrome just shows it when dev console is open,.
