### ISSUE TITLE
Allow configuring Revisions drop down to show only branches or only tags

### ISSUE THREAD

**Issue by tetchel** [argoproj/argo-cd#4751]
As per https://github.com/argoproj/argo-cd/issues/4645#issuecomment-719164409
https://github.com/argoproj/argo-cd/issues/4645#issuecomment-721624622

The [new component](https://github.com/argoproj/argo-cd/blob/master/ui/src/app/applications/components/revision-form-field/revision-form-field.tsx) would require these changes.

**Comment by keithchong** [comment]
Hi @jessesuen , please assign this to me.

**Comment by keithchong** [comment]
Proposed solution:

<img width="1074" alt="Screen Shot 2020-11-05 at 5 28 10 PM" src="https://user-images.githubusercontent.com/7726022/98303638-6ed0eb00-1f8c-11eb-922c-08c02b60dfeb.png">


<img width="1051" alt="Screen Shot 2020-11-05 at 5 27 25 PM" src="https://user-images.githubusercontent.com/7726022/98303685-860fd880-1f8c-11eb-878c-0ed904636e88.png">
