### ISSUE TITLE
Recognize failures to decrypt sealed secrets

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4754]
# Summary
Make it easier to recognize that a node has not properly reached its final happy state. (e.g. a sealedsecret constructing a secret)

# Motivation

We tried to deploy an update to a sealed secret. Unfortunately, the new sealed secret was sealed against a different secret sealer, which meant that it couldn't be decrypted by the cluster.

What we actually did was overwrite the sealed-secret in git and push to git and then argocd recognized there was an update, and updated. Or tried to. It then reported "Healthy", "Synced", and "Sync OK". Unfortunately, because it couldn't decrypt the new secret, it didn't replace the old previously existing secret, and thus nothing worked. But there was no indication in the top level UI to this problem. The only place one would notice is by opening the sealed secret and looking at "events"

![broken secret and good secret](https://user-images.githubusercontent.com/2119212/98169748-d61e6a80-1eba-11eb-8e38-56c1c8f4eab5.png)
![details of broken secret](https://user-images.githubusercontent.com/2119212/98169789-e898a400-1eba-11eb-86d0-60a35d3716c0.png)

# Proposal

How do you think this should be implemented?
1. It would be possible to expose all recent events (filterable) at a top level -- possibly near the most recent sync status?
1. It might be possible to have hooks or something specifically to enable a thing like sealedsecret to trigger an unhealthy status for a case like this

**Comment by jessesuen** [comment]
I'm pretty sure SealedSecrets has status which was built specifically so that tools like Argo CD could display it

**Comment by jessesuen** [comment]
It does:

https://github.com/bitnami-labs/sealed-secrets/blob/661b73ca3da52b2cccaffb61c829549222144e6d/RELEASE-NOTES.md#status-field

```
Now the sealed secrets controller updates the Status field of the SealedSecrets resources. This makes it easier for automation like ArgoCD to detect whether (and when) the controller has reacted to changes in the SealedSecret resources and produced a Secret. It also shows an error message in case it fails (many users are not familiar with k8s events and they may find it easier to see the error message in the status).
```

**Comment by chetan-rns** [comment]
@jsoref @jessesuen  Passing the`--update-status` flag to the SealedSecret controller does update the secret's status. Can we add a custom health check that can monitor the status? Happy to pick this issue

**Comment by jsoref** [comment]
Sounds good to me

**Comment by jsoref** [comment]
For reference, someone wrote a sample health check: https://github.com/bitnami-labs/sealed-secrets/issues/346#issuecomment-637631528

@jessesuen am I right that this should be implemented in https://github.com/argoproj/gitops-engine/ ?

**Comment by chetan-rns** [comment]
@jsoref There's also `resource_customizations` directory where I see similar lua scripts (health.lua) for health checks

**Comment by jannfis** [comment]
> @jessesuen am I right that this should be implemented in https://github.com/argoproj/gitops-engine/ ?

The right place to add health checks for third-party resources is, as @chetan-rns pointed out, at https://github.com/argoproj/argo-cd/tree/master/resource_customizations. There is documentation on how to contribute a health check for third-party CRDs at https://argoproj.github.io/argo-cd/operator-manual/health/#way-2-contribute-a-custom-health-check

**Comment by jannfis** [comment]
@chetan-rns Mind if I assign this issue to you, when you already offered to pick it up? :)

**Comment by chetan-rns** [comment]
Thanks, @jannfis. I'm happy to work on it :+1:

**Comment by jangraefen** [comment]
Could you also please close #3707 then? I just wanted to start working on it, but noticed that there was already a script for it 😉.

**Comment by jannfis** [comment]
Hey, thanks for the pointer @jangraefen and sorry for the confusion with a duplicate issue.

**Comment by jangraefen** [comment]
@jannfis No worries 🙂. Just glad to see this feature coming.
