### ISSUE TITLE
Intermittent failure when running TestWatchClusters_LocalClusterModifications with -race, likely due to race condition

### ISSUE THREAD

**Issue by jgwest** [argoproj/argo-cd#4755]
The `TestWatchClusters_LocalClusterModifications` test is intermittently failing when`-race` is enabled, BUT oddly enough it's **not** failing with a data race error (no data races are reported).

Rather it's failing due a timeout in the test itself, and on further investigation, it's failing because events are being missed in the failing case that are correctly received in the passing case (the `handleModEvent` function in `runWatchTest` should be called twice, but is only called once).

My suspicion is that it's due to a race condition related to the behaviour of [SettingsManager.ensureSynced(...)](https://github.com/argoproj/argo-cd/blob/c9f3c64a584d615cdd66b75d7a352c8c831efe25/util/settings/settings.go#L802), but I was not able to definitively prove that beyond just a minimal level of suspicion.

#### Other notes:
- This also occurs with `TestWatchClusters_CreateRemoveCluster`
- As mentioned, it's intermittent, reproducible about 16% of the time, and it's definitely the case that adding print/log statements to the code can cause it to no longer be reproducible, making this very much a [heisenbug](https://en.wikipedia.org/wiki/Heisenbug)
- In fact, adding a tiny 1 msec delay to the top of `SettingsManager.ensureSynced(...)` causes this to no longer be reproducible
- In the failing case, a watch on the Secrets resource is not established in time, and this, I believe, is what causes the cluster deletion event to be missed in the test itself.
- I'm mainly filing this bug to record my findings, and track it for future reference, but since it's not causing any obvious impact to the product itself, it's likely lower priority versus other more tangible bugs.

### To reproduce:

Run this as a shell script, and wait for it to fail:

```
#!/bin/bash

set -eu

while :
do
/usr/local/go/bin/go test -race -count=1 -timeout 30s github.com/argoproj/argo-cd/util/db -run ^TestWatchClusters_LocalClusterModifications$
done
```

### Test log
```
--- FAIL: TestWatchClusters_LocalClusterModifications (5.00s)
    cluster_test.go:187: 
        	Error Trace:	cluster_test.go:187
        	            				cluster_norace_test.go:19
        	Error:      	Failed due to timeout
        	Test:       	TestWatchClusters_LocalClusterModifications
time="2020-11-04T19:41:42-05:00" level=info msg="clusterSecretInformer cancelled"
FAIL
FAIL	github.com/argoproj/argo-cd/util/db	5.348s
FAIL
```

### Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.

**Comment by jgwest** [comment]
As seen in a conversation on #argo-dev Slack this afternoon, it also appears to intermittently occur when run as a GitHub action during CI build w/o race detection enabled. 

I was personally never able to reproduce w/o `-race` when running locally, but it would make sense that it would be more common on a CPU-limited GitHub runner as it appears _the slower the compute_ (for example, when running with `-race`'s profiling overhead) the more likely it is to occur.

**Comment by crenshaw-dev** [comment]
Closing since this is very old, and I haven't seen this test flake recently.
