### ISSUE TITLE
Use a distinct icon for something

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4817]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

It's still possible to have adjacent identical icons (as of #4783 it's 👻 👻 )

**To Reproduce**

I'm not entirely certain, I think it's in the very initial stages of populating a new application.
I think one is "missing" and one is "unknown"

**Expected behavior**

Adjacent icons should be distinct -- it should be easy to recognize states...

![image](https://user-images.githubusercontent.com/2119212/98888371-e2c83300-2465-11eb-825c-139b65fa3b90.png)
[border-style](https://fontawesome.com/icons/border-style?style=solid)

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/98887689-77319600-2464-11eb-9121-888d445cc920.png)
![image](https://user-images.githubusercontent.com/2119212/98887751-8e708380-2464-11eb-837b-d141a39dd665.png)

**Version**

```shell
{
    “Version”: “v1.8.0+eec8f79",
    “BuildDate”: “2020-11-09T19:41:01Z”,
    “GitCommit”: “eec8f799237efb8532d971ee40e283d1e0435cdf”,
    “GitTreeState”: “clean”,
    “GoVersion”: “go1.14.1",
    “Compiler”: “gc”,
    “Platform”: “linux/amd64",
    “KsonnetVersion”: “v0.13.1",
    “KustomizeVersion”: “v3.8.1 2020-07-16T00:58:46Z”,
    “HelmVersion”: “v3.4.0+g7090a89",
    “KubectlVersion”: “v1.17.8",
    “JsonnetVersion”: “v0.16.0"
}
```

**Logs**

**Comment by reginapizza** [comment]
@jsoref @jessesuen I was going to try to take this issue up if a fix is still desired. If so, I wanted to get some input on what icon you would rather have instead of the ghost. I was thinking that for `Missing` status maybe it could be a question mark icon like [this](https://fontawesome.com/icons/question-circle?style=regular). Let me know what you think!

**Comment by jsoref** [comment]
@reginapizza: You could use `border-style` if someone goes for it as noted in the summary. But I'd want someone to say "sure". I think I'd use that for `missing` and leave `unknown` with ghost. But, again, I'd want someone else to agree with the choice. It's possible that it should be reversed.

**Comment by jsoref** [comment]
Ok, proposal:
* Change question (currently used for help) to https://fontawesome.com/icons/info-circle?style=solid
* Change unknown to question (from above)
* Leave missing as ghost
