### ISSUE TITLE
Setting up the environment for running smoke test

### ISSUE THREAD

**Issue by dewan-ahmed** [argoproj/argo-cd#4819]
# Summary
Breaking down [the parent issue](https://github.com/argoproj/argo-cd/issues/4393) into two separate independent tasks. 

What change you think needs making.
This task will handle setting up a docker container against which the smoke tests will be run.

# Motivation
Due to the challenges faced with setting up the environment, @dewan-ahmed was not able to push the smoke test scripts although the smoke tests were running fine on the local environment. The motivation is to separate the setup of test environment and the smoke tests themselves so that both work can proceed independently. 

Please give examples of your use case, e.g. when would you use this.

# Proposal

How do you think this should be implemented?

[This](https://argoproj.slack.com/archives/CEWCP8TV5/p1604506062335700) is the discussion regarding setting up the required environment for the smoke test.

**Comment by jessesuen** [comment]
@dewan-ahmed can I assign this to you?

**Comment by dewan-ahmed** [comment]
Hi @jessesuen I'd like to focus on https://github.com/argoproj/argo-cd/issues/4820 as I've not been able to make progress with the environment setup part of https://github.com/argoproj/argo-cd/issues/4393. I'd like someone else to take on this issue. I can discuss more during the weekly call and add an agenda item.

**Comment by jgwest** [comment]
Closing in favour of parent issue.
