### ISSUE TITLE
Suspended shouldn't use the same icon as Healthy

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4838]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

People shouldn't be required to be able to see color to distinguish states.

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/istio-rollout

**Expected behavior**

Use distinct icons for Healthy/Suspended

**Screenshots**

![heart](https://user-images.githubusercontent.com/2119212/99197450-8ebc9780-2760-11eb-810b-b0618342b265.png)
![heart](https://user-images.githubusercontent.com/2119212/99197453-94b27880-2760-11eb-81eb-f9628539f071.png)

**Version**

```shell
{
    "Version": "v1.8.0+6cadaa2",
    "BuildDate": "2020-11-15T17:35:22Z",
    "GitCommit": "6cadaa2a5dae0e888b108606a7f3a8f85fd54e83",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.0+g7090a89",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.16.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jsoref** [comment]
I'd propose:
https://fontawesome.com/icons/icicles?style=solid
suspended:
![icicles](https://user-images.githubusercontent.com/2119212/99197483-ccb9bb80-2760-11eb-85ac-ead3aa907eaf.png)

**Comment by jessesuen** [comment]
How about a pause icon for suspended?

**Comment by jsoref** [comment]
Wfm
