### ISSUE TITLE
Unable to pull from self signed repo

### ISSUE THREAD

**Issue by Numblesix** [argoproj/argo-cd#4840]
**Describe the bug**
Hello :)

at my work we have a gitserver which is only reachable internally thereby signed by our inhouse CA while im able to add the Server Cert under the Settings/Repositories im not able to create an application with this repo.
I get the following error

Unable to create application: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Internal desc = Failed to fetch git repo: `git fetch origin --tags --force` failed exit status 128: fatal: unable to access 'https://abc.defg.de/sandro/wordpress.git/': gnutls_handshake() failed: Key usage violation in certificate has been detected.

**To Reproduce**

Create a repo with self signed crt try to create an app from it.

**Expected behavior**

The added cert under Settings should also be added to the repo-server

**Version**
v1.7.7+33c93ae using https://github.com/argoproj-labs/argocd-operator

**Comment by jannfis** [comment]
Hi @Numblesix - have you added the server cert to your repository, or the certificate of your inhouse CA - I would be guessing the former?

The error message suggests that the `git`-Client (using GnuTLS) does a more strict check of the server's certificate than the Go implementation does. 

Most likely, if you added the server cert, it is not allowed to perform validation of TLS connections.

Can you please try to add the CA's certificate under Settings/Repositories and see whether that works?

**Comment by Numblesix** [comment]
I added the server certificate.
I will try to add the root ca der tomorrow aber Share the result :)

**Comment by Numblesix** [comment]
I added the whole chain now server -> intermediate -> root-ca but it still doesnt work, same error.    
I tried a git clone on a normal RHEL7 which has the intermediate in the trust store and there git runs without any issues

**Comment by jannfis** [comment]
I believe there might be a difference in the git clients between the one used by Argo CD (Debian package, built against GnuTLS) and the RHEL one (most likely built against OpenSSL, at least on my Fedora system).

I think that the GnuTLS implementation checks the extended usage bits on the cert of the server as to whether the usage is allowed (server authentication), while the OpenSSL implementation does not.

Please check certificate of the Git HTTPS server for the usage bits:

```
openssl x509 -noout -ext keyUsage,extendedKeyUsage -in <yourcert.crt>
```

It should contain at least contain the following usage bit:

```
X509v3 Extended Key Usage: 
    TLS Web Server Authentication
```

**Comment by Numblesix** [comment]
Thanks for the fast reply :)

checking my cert i can see the following:

```
X509v3 Key Usage: 
    Key Encipherment
X509v3 Extended Key Usage: 
    TLS Web Server Authentication
```

I am also able to recreate that issue with a docker container running latest ubuntu image
```
root@9b625ce24b65:~# GIT_CURL_VERBOSE=1 GIT_TRACE=1 git clone https://abc.defg.de/sandro/wordpress.git/'
08:55:03.534298 git.c:439               trace: built-in: git clone https://abc.defg.de/sandro/wordpress.git/'
Cloning into 'wordpress'...
08:55:03.540221 run-command.c:663       trace: run_command: git-remote-https origin https://abc.defg.de/sandro/wordpress.git/
* Couldn't find host abc.defg.de in the .netrc file; using defaults
*   Trying 1.2.3.4:443...
* TCP_NODELAY set
* Connected to abc.defg.de (1.2.3.4) port 443 (#0)
* found 420 certificates in /etc/ssl/certs
* ALPN, offering h2
* ALPN, offering http/1.1
* gnutls_handshake() failed: Key usage violation in certificate has been detected.
* Closing connection 0
fatal: unable to access 'https://abc.defg.de/sandro/wordpress.git/'': gnutls_handshake() failed: Key usage violation in certificate has been detected.
```

curl works tough

**Comment by jannfis** [comment]
It might be that the X509v3 Key Usage is missing the `Digital Signature` bit, which probably is also required for server certificates.

While I think that GnuTLS should not be that strict on non-critical extensions/constraints (at least, they are not marked as critical from your above output), I'm afraid we have no possibility to change the current behaviour.

However, you might want to ask the Git server administrators to replace the server certificate with one that contains correct usage constraints, so that also GnuTLS will be happy.

**Comment by jannfis** [comment]
The GnuTLS folks even have a dedicated FAQ entry for it: https://www.gnutls.org/faq.html#key-usage-violation

**Comment by Numblesix** [comment]
Thanks that did the trick :) :partying_face:
