### ISSUE TITLE
Provide tooling to test & debug RBAC policies

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#4842]
# Summary

We should provide a mechanism/tool so that users can test & validate RBAC policies before configuring them in live Argo CD instances.

# Motivation

RBAC policies currently can be hard to understand, test and troubleshoot. There is no convenient way for users to check whether the RBAC policies they configure actually do what they expect them to do. This can lead to frustration, as well as insecure or unexpected configurations.

# Proposal

We should provide an easy way for users to test & troubleshoot RBAC policies. Currently, what we provide is the `argocd account can-i` command that users can use to check whether they are authorized for certain operations on given resources in the live system. The limit with that is a) that it's working on the live system and b) checks permissions for the logged in user only.

What we need is a similar tooling that is not running against the API, but work on local policy files. 

I can imagine this built into `argocd-util`, i.e. to check whether a group `somegroup` can perform `get` actions for all `applications` resources from a policy in `~/policy.csv`:

```
argocd-util rbac can somegroup get applications '*' --policy-file ~/policy.csv
```

Additionally, if the user has connection to K8s cluster and appropriate permissions, tooling could read-out the current live policy and test against it to answer certain questions about live state (i.e. user calling saying "I cannot create application, I get permission denied")

**Comment by jessesuen** [comment]
Agree this would be useful
