### ISSUE TITLE
Design Flaw leading to errant delete

### ISSUE THREAD

**Issue by sethgrid** [argoproj/argo-cd#4844]
Not sure if a design flaw is a bug, but this one should be addressed and I think is easy to fix.
In the UI, on a deploy, when you click on it, you can "sync, delete, restart". A very destructive delete is an errant click away from a restart. We just did that. Accidentally clicked delete instead of restart resulting in 10s of thousands of user facing errors before we realized and re-synced. 

Fix suggestion: different color dialog box or a check box "really, I want to delete"

﻿version v.1.5.6

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

UI makes it easy to delete accidentally when you are used to restarting. Same looking dialog box and easy to autopilot your way to a deleted cluster

**To Reproduce**

Go to an application deploy, click hamburger, click delete or restart. Very similar. 

**Expected behavior**

Delete should be more scary :). Confirm check box, red, something. 

**Screenshots**

**Version**

﻿version v.1.5.6

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexmt** [comment]
I agree. Adding to v1.9 milestone as well as https://github.com/argoproj/argo-cd/issues/3205  (application cascade delete) .

**Comment by keithchong** [comment]
Hi @alexmt, I can have a look at this one.  Maybe something like this:

<img width="1073" alt="Screen Shot 2020-11-17 at 2 39 50 PM" src="https://user-images.githubusercontent.com/7726022/99439167-d539ff80-28e2-11eb-85bc-cb2fb599f82c.png">

**Comment by keithchong** [comment]
Or, check video:

[4844-DesignFlawDeleteResource.zip](https://github.com/argoproj/argo-cd/files/5555856/4844-DesignFlawDeleteResource.zip)

**Comment by alexmt** [comment]
@keithchong , 

I was thinking the same. First I was thinking to require a typing resource name before deletion. This might be too much, sometimes we need to delete a lot of resources. I think the prominent color is enough.

**Comment by keithchong** [comment]
We could instead use, or also use, an icon. Although there is code there in place to accommodate an icon, but the layout is a bit off.  The header colour will have to be separate property.

<img width="1040" alt="Screen Shot 2020-11-18 at 3 11 54 PM" src="https://user-images.githubusercontent.com/7726022/99582694-793dac80-29b0-11eb-8f67-977766910985.png">

<img width="1402" alt="Screen Shot 2020-11-18 at 2 52 53 PM" src="https://user-images.githubusercontent.com/7726022/99582698-7b077000-29b0-11eb-9c5e-226112e2d953.png">

@alexmt, what do you mean by requiring a typing resource name before deletion?  You mean the user has to supply the type of the resource in a field (to confirm) and then click ok?  (Just like in GitHub, when you want to delete a repo, you have to type in the name of the repo before deleting it)

**Comment by keithchong** [comment]
The title colour can be customized to be red, yellow or gray.

<img width="1094" alt="Screen Shot 2020-11-20 at 3 16 37 PM" src="https://user-images.githubusercontent.com/7726022/99845947-74f5c880-2b43-11eb-8680-461397277cb6.png">

**Comment by keithchong** [comment]
Adding an extra field to require typing a resource name to confirm isn't that much more work.  @alexmt , I could go either way on this.  Let me know...

![Screen Shot 2020-11-20 at 5 10 05 PM](https://user-images.githubusercontent.com/7726022/100052468-038c7300-2dec-11eb-83aa-58e439046914.png)

**Comment by keithchong** [comment]
FWIW, one might get tired of typing in the lengthy name so the Text field could be converted into an AutocompleteField.  However, https://github.com/argoproj/argo-cd/issues/4924 needs to be fixed first.   

The change could be done in a follow-on enhancement.
