### ISSUE TITLE
argocli --dest-name argument fails with "Destination server missing from app spec"

### ISSUE THREAD

**Issue by james-callahan** [argoproj/argo-cd#4852]
**Describe the bug**

Trying to use `argocd app create --dest-name myclustername` fails with e.g.
> time="2020-11-17T07:25:01Z" level=fatal msg="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Destination server missing from app spec"

**Expected behavior**

An app would be created.

**Version**

Using the argocd cli out of the docker image `argoproj/argocd:v1.7.6@sha256:e561b4caa56a7ec41f59ba305b1f8158ada2c7eaee7a87d29fad8d88da650fec`

Edit: confirmed to also exist with 1.7.8

**Comment by jessesuen** [comment]
I think this only affects when adding using the cluster *name*, but not cluster URL.

**Comment by james-callahan** [comment]
> I think this only affects when adding using the cluster _name_, but not cluster URL.

That's correct.

**Comment by alexmt** [comment]
@james-callahan I was able to reproduce the issue but only with `--validate=false` flag. Without this flag, the application is created successfully. Can you please confirm you were using `--validate=false` as well?

**Comment by kshamajain99** [comment]
Taking a look into this issue.

**Comment by james-callahan** [comment]
> Can you please confirm you were using `--validate=false` as well?

Yes I am.

**Comment by chris-vest** [comment]
I am also seeing this issue after switching to use the cluster name rather than the server URL in our Application definitions. I have a job which scales certain Applications down overnight using `argocd app set`, then another which scales them back up using `argocd app unset`. This is now failing with the error:

```level=fatal msg="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Destination server missing from app spec"```

**Comment by james-callahan** [comment]
I just upgraded to 1.8.0 and I'm still having this problem.

**Comment by james-callahan** [comment]
Can this be reopened?

**Comment by jannfis** [comment]
Re-opening this bug on request, issue seems not to be fixed yet.

**Comment by kshamajain99** [comment]
@james-callahan Can you confirm if this issue still exists in 1.8.3?

**Comment by james-callahan** [comment]
It appears to have been fixed now.
