### ISSUE TITLE
Ability to diff a remote branch

### ISSUE THREAD

**Issue by james-callahan** [argoproj/argo-cd#4853]
# Summary

I'd like to be able to see a diff against a remote branch/tag/commit; this could be used to
  - review pull requests/tags
  - see what was different in an old revision

# Motivation

Currently to diff against an arbitrary commit you need to check it out locally and use `--local`: this in turn requires that you have all renderers (kustomize/helm and any plugins) installed and able to do a full render locally.
At work, we use KSOPS, with the decryption key only available from inside of the argocd namespace. This means that we cannot use `--local`.

# Proposal

  - `argocd app diff` should gain a `--revision` argument; mutually exclusive with `--local`
  - The api server will need to gain a matching field

**Comment by jessesuen** [comment]
This feature has been implemented and is coming in v1.8

Duping to https://github.com/argoproj/argo-cd/issues/4162
