### ISSUE TITLE
Argo missing managed cache leads to reconcile and downtime on HA app

### ISSUE THREAD

**Issue by asafdl** [argoproj/argo-cd#4861]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Application reconciled 3 times in a span of 15 minutes, the app has 2 replicasets with rollingupdate strategy so it should be ZDT.

Looked in our Kibana Logs and found that argo was reporting: "manifest cache error" on one of the apps secrets

and after a few manifest cache error it would report 
Failed to get cached managed resources for tree reconciliation, fallback to full reconciliation" application=healthchecker

I opened argo ui and saw that one of the secrets was out of sync
but no one actually changed it and it was updated properly argo just identified it as out-of-sync.
After I ran sync on chart all the errors and reconciles went away

**To Reproduce**

Not sure how to reproduce as this seems to be a one time error.

**Expected behavior**

We can't have argocd reconciling our ZDT apps and causing downtime

**Screenshots**

**Version**

```shell
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:43:39Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: windows/amd64
argocd-server: v1.5.1+8a3b36b
  BuildDate: 2020-04-06T15:58:54Z
  GitCommit: 8a3b36bd28fe278f7407b9a8797c79ad859d1acd
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
Can you explain how did this led to downtime? What exactly was down your app? Argo CD?

**Comment by asafdl** [comment]
Both pods were down, I suspect since argocd reconciled the whole chart, that the deployment was reconciled and that led to both pods to go down at the same time instead of the conventional rolling update k8s would do if just the pods needed to reconcile. but this is only my suspicion
