### ISSUE TITLE
Use streaming API for Application List UI view

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#4868]
# Summary

If Argo CD instance is managing 3k+ applications then API response might be more than 100mb. Without server side pagination API server might use a lot of memory and get OOM killed. API Server should support server-side pagination to handle 3k+ applications.

# Proposal

Implement server-side pagination so that UI can load applications in chunks.

**Comment by jessesuen** [comment]
The decision is to leverage the existing application stream API to power the application page, and stop using the list API. This will allow apps to display much quicker.

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/5719
