### ISSUE TITLE
Question: what's the best way to add a GitHub Organization without specifying a team?

### ISSUE THREAD

**Issue by vrodomista** [argoproj/argo-cd#4872]
Hey guys! Thanks for your awesome product. I am wondering how to use the `argocd-rbac-cm` to bind a role to a GitHub organization. Was wondering if the following would work? 

`your-github-org:*`

Thanks!

**Comment by jessesuen** [comment]
It depends on your dex configuration, users are also members of `your-github-org`

**Comment by vrodomista** [comment]
@jessesuen so you should be able to omit team?

**Comment by jessesuen** [comment]
Yes, you configure RBAC as: `your-github-org` and not `your-github-org:*` to allow all of `your-github-org` permissions
