### ISSUE TITLE
Duplicated logs in pod logs view

### ISSUE THREAD

**Issue by tomjohnburton** [argoproj/argo-cd#4875]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When viewing pod logs, after some amount of time, the logs are reprinted. 

**Screenshots**
![image](https://user-images.githubusercontent.com/39559415/99832016-3f130d00-2b60-11eb-94d8-f132cb38a6cf.png)

**Logs**

```
020/11/20 16:51:10 config map updated <--------------------------
2020/11/20 16:51:10 performing webhook request (1/1)
2020/11/20 16:51:10 successfully triggered reload
2020/11/20 17:07:17 config map updated
2020/11/20 17:07:17 performing webhook request (1/1)
2020/11/20 17:07:17 error: Received response code 500 , expected 200
2020/11/20 17:07:27 error: Webhook reload retries exhausted
2020/11/20 17:08:47 config map updated
2020/11/20 17:08:47 performing webhook request (1/1)
2020/11/20 17:08:47 error: Received response code 500 , expected 200
2020/11/20 17:08:57 error: Webhook reload retries exhausted
2020/11/20 17:11:27 config map updated
2020/11/20 17:11:27 performing webhook request (1/1)
2020/11/20 17:11:27 successfully triggered reload
2020/11/20 12:30:04 Watching directory: "/etc/config"
2020/11/20 16:25:31 config map updated
2020/11/20 16:25:31 performing webhook request (1/1)
2020/11/20 16:25:31 successfully triggered reload
2020/11/20 16:29:39 config map updated
2020/11/20 16:29:39 performing webhook request (1/1)
2020/11/20 16:29:39 successfully triggered reload
2020/11/20 16:36:27 config map updated
2020/11/20 16:36:27 performing webhook request (1/1)
2020/11/20 16:36:27 successfully triggered reload
2020/11/20 16:51:10 config map updated <--------------------------
2020/11/20 16:51:10 performing webhook request (1/1)
2020/11/20 16:51:10 successfully triggered reload
2020/11/20 17:07:17 config map updated
2020/11/20 17:07:17 performing webhook request (1/1)
2020/11/20 17:07:17 error: Received response code 500 , expected 200
2020/11/20 17:07:27 error: Webhook reload retries exhausted
2020/11/20 17:08:47 config map updated
2020/11/20 17:08:47 performing webhook request (1/1)
2020/11/20 17:08:47 error: Received response code 500 , expected 200
2020/11/20 17:08:57 error: Webhook reload retries exhausted
2020/11/20 17:11:27 config map updated
2020/11/20 17:11:27 performing webhook request (1/1)
2020/11/20 17:11:27 successfully triggered reload
```

```
argocd: v1.7.5+90cc56c.dirty
  BuildDate: 2020-09-16T00:52:53Z
  GitCommit: 90cc56c3a99127f6ed6bcb777abf92e357c1eb00
  GitTreeState: dirty
  GoVersion: go1.15.2
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.5+90cc56c
  BuildDate: 2020-09-15T23:03:57Z
  GitCommit: 90cc56c3a99127f6ed6bcb777abf92e357c1eb00
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Comment by jessesuen** [comment]
Did the pod restart?

**Comment by tomjohnburton** [comment]
No pod restarts. It seems to happen if I leave the Logs tab open for some time. When I exit out of the tab and go back the logs are normal again.

**Comment by tomjohnburton** [comment]
I watched the network logs and this call was triggered 
![image](https://user-images.githubusercontent.com/39559415/99839094-75ee2080-2b6a-11eb-9596-a2d5df672f34.png)

**Comment by jessesuen** [comment]
Probably what's happening is we lose the log stream, restablish the log request stream, without clearing the UI buffer.

**Comment by jessesuen** [comment]
> I watched the network logs and this call was triggered

How many of these log requests was there?

**Comment by jessesuen** [comment]
@darshanime is this something you can take a look at?

**Comment by darshanime** [comment]
@tomjohnburton, this was fixed in https://github.com/argoproj/argo-cd/pull/4696 and you are running `v1.7.5` which does not have this fix.  
Can you try upgrading to [`v1.7.10`](https://github.com/argoproj/argo-cd/releases/tag/v1.7.10) and see if the issue persists?

**Comment by rbreeze** [comment]
@tomjohnburton we also introduced a completely new pod logs viewer in #5233 . Can you see if the issue is present there?

**Comment by tomjohnburton** [comment]
Sorry for my slow reply. Now running 1.8.2 and yes issue is no longer there. Thanks all!

**Comment by saurbhc** [comment]
I'm getting the same issue (duplicate logs) in version `v2.10.9+c071af8`

**Comment by eidmantas** [comment]
Issue seems to persist, perhaps root cause is different?

**Comment by Ziyann** [comment]
In my case, the issue was the default GKE load balancer backend service timeout: https://cloud.google.com/load-balancing/docs/backend-service#timeout-setting. The log stream request timed out after 30 seconds, and a new one was started, causing logs to be reprinted. @saurbhc @eidmantas

**Comment by codrutpanea** [comment]
had the same problem when serving argocd via gateway-api (envoy gateway) which has a default timeout of 15 seconds. I solved the problem by setting the timeouts to 0s on the HTTPRoute serving argocd server
