### ISSUE TITLE
Static assets are being browser cached between upgrades

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#489]
After upgrading an ArgoCD instance, I had to force refresh my browser to get the new UI. We should disable browser caching on the index.

**Comment by alexmt** [comment]
Not reproducible

**Comment by alexmt** [comment]
Chrome shows cached page version if user opens argoui in new tab even through correct no-cache headers are set. Also sometimes user might forget to reload page after upgrade and it causes  weird  issues. 

UI should checks if static assets version matches with backend version and prompt user to refresh page.

**Comment by jessesuen** [comment]
Upgraded probably two dozen argo-cd instances from v0.11 to v0.12 without seeing this issue. I don't think this is a problem anymore.
