### ISSUE TITLE
OAuth return uri might be wrong

### ISSUE THREAD

**Issue by CtheSky** [argoproj/argo-cd#4894]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x ] I've included steps to reproduce the bug.
* [ x ] I've pasted the output of `argocd version`.

**Describe the bug**

When login via keycloak, oauth2 return url might be wrong. It's set to values other than `/auth/callback`. 

**To Reproduce**

I followed the documentation [here](https://argoproj.github.io/argo-cd/operator-manual/user-management/keycloak/).

**Expected behavior**

Set the oauth return url to `http://my-host.com/auth/callback`, got `http://my-host.com/applications/auth/callback` instead.

After I delete the `applications` in url and keep the query parameters, I can login successfully.

**Screenshots**
Return url is `http://my-host/applications` here.
![image](https://user-images.githubusercontent.com/13807244/100079901-2cf6de80-2e80-11eb-8c65-46809c88f33d.png)

The oauth return url becomes `http://my-host/applications/auth/callback` here. 
![image](https://user-images.githubusercontent.com/13807244/100079941-3a13cd80-2e80-11eb-8e52-0dd30baa3201.png)

After I login through keycloak, I stuck here because the return url is not correct:
![image](https://user-images.githubusercontent.com/13807244/100080519-e48bf080-2e80-11eb-8745-d1f865270003.png)

**Version**

```shell
argocd-server: v1.7.9+f6dc8c3
  BuildDate: 2020-11-17T23:19:51Z
  GitCommit: f6dc8c389a00d08254f66af78d0cae1fdecf7484
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jannfis** [comment]
Hi, if you followed the instructions, you probably set `Base URL` to `/applications` in your Keycloak client configuration.

Can you try it with a blank value, or `/` please?

**Comment by CtheSky** [comment]
Hi, I've tried both blank value and `/`, the return uri is still the same.

**Comment by CtheSky** [comment]
@jannfis  I gave the wrong value for url attribute specified [here](https://argoproj.github.io/argo-cd/operator-manual/user-management/keycloak/#configuring-argocd-oidc) in oidc config. Thanks for the quick reply.
