### ISSUE TITLE
Project should have a license

### ISSUE THREAD

**Issue by merenbach** [argoproj/argo-cd#49]
Since `argo-cd` is a public-facing, open-source project, we should have a license in place (either called `LICENSE` or `LICENSE.md` in the root of the project):

  1. To encourage involvement by providing peace-of-mind to contributors in the community regarding access to and use of their code.
  2. To encourage adoption, as a show of good faith.  In prospective corporate adopters, a license may be required by management or procurement departments, even (or especially) for open-source code.

**Comment by saradhis** [comment]
We should use the same license we are using for Argo project. https://github.com/argoproj/argo/blob/master/LICENSE.md

**Comment by merenbach** [comment]
@saradhis I'm not clear whether it's quite as simple as that.  I'm under the impression that we need the full license in the project root, and the `LICENSE.md` from Argo (at your link above) is actually just the segment that goes at the top of source code, in documentation, etc.  Interested in your thoughts.

**Comment by saradhis** [comment]
Yes, we do need to copy the license into the root of the project. I just provided the link as a reference to what we should use.

**Comment by merenbach** [comment]
@saradhis understood.  I'll submit a PR.

**Comment by edlee2121** [comment]
Added license and copyright files.
