### ISSUE TITLE
ArgoCD CLI does not appear to set headers when specified

### ISSUE THREAD

**Issue by geneccx** [argoproj/argo-cd#4918]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to access my ArgoCD instance which is behind Cloudflare Access. This uses HTTP headers to authenticate the request. However, no matter what combination of parameters I pass for arguments, it does not seem like the HTTP headers I specify in the command actually get sent in the request, so I am unable to access my instance.

I have also tried with --grpc-web, and the headers still do not appear to be sent.

**To Reproduce**

1. Start an HTTP/2 server on `argocd.example.com`
1. Attempt to pass headers in a login request:
`argocd login -H foo:bar argocd.example.com`
`argocd login --header foo:bar argocd.example.com`
`argocd login -H=foo:bar argocd.example.com`
`argocd login --header=foo:bar argocd.example.com`
`argocd login --header="foo:bar" argocd.example.com`
`argocd login --header="foo=bar" argocd.example.com`

When logging requests on the server, `argocd.example.com`, it appears that neither of the texts `foo` nor `bar` appear in the headers anywhere.

**Expected behavior**

The header `Foo: Bar` is sent to `argocd.example.com`.

**Screenshots**

N/A

**Version**

```shell
argocd: v1.7.10+bcb05b0.dirty
  BuildDate: 2020-11-20T23:40:45Z
  GitCommit: bcb05b0c2e0f8006aa2d2abaf780e73c9e73c945
  GitTreeState: dirty
  GoVersion: go1.15.5
  Compiler: gc
  Platform: darwin/amd64
```

**Logs**

HTTP/2 Server has the following headers received.
Note the lack of Foo and/or bar anywhere in the headers:
```
-> HEADERS(1)
    - END_STREAM
    + END_HEADERS
    :method: POST
    :scheme: http
    :path: /session.SessionService/Create
    :authority: argocd.example.com:443
    content-type: application/grpc
    user-agent: argocd-client/v1.7.10+bcb05b0.dirty grpc-go/1.15.0
    te: trailers
    token:
```

**Comment by jannfis** [comment]
Could reproduce - headers are only sent on HTTP/1 requests (i.e. grpc-web).

**Comment by iam-veeramalla** [comment]
Hi @jannfis , I am happy to take this. Please let me know.

**Comment by jessesuen** [comment]
@iam-veeramalla yes please take this. We'd like to have it in v1.8 or a subsequent patch if possible.
