### ISSUE TITLE
Diff changes before sync

### ISSUE THREAD

**Issue by yujunz** [argoproj/argo-cd#4919]
# Summary

Allow diff changes before sync within one command

# Motivation

Combine the common patter for app sync into one command

```sh
argocd app diff <app>
argocd app sync <app>
```

# Proposal

```sh
argocd app sync --diff-changes [--yes] <app>
```

`--diff-changes` to preview the diff and ask for user confirmation
`--yes` to confirm sync automatically

**Comment by rishabh625** [comment]
please assign this issue to me
