### ISSUE TITLE
Update Helm 3 because of Helm Bug helm/helm#8940

### ISSUE THREAD

**Issue by cobexer** [argoproj/argo-cd#4921]
If a Chart dependency doesn't specify a repository Helm 3.4.0 fails with "Error: could not find protocol handler for:" -> update Helm to 3.4.1 which fixes https://github.com/helm/helm/issues/8940.

**Version**
1.8.0-rc1

**Logs**

```
time="2020-11-26T10:49:09Z" level=error msg="`helm dependency build` failed exit status 1: Error: could not find protocol handler for:" execID=HSuXQ
```

**Comment by alexmt** [comment]
Thank you @cobexer . PR is ready: https://github.com/argoproj/argo-cd/pull/4938
