### ISSUE TITLE
Allow referring to non-default remote references

### ISSUE THREAD

**Issue by james-callahan** [argoproj/argo-cd#4935]
# Summary

In the application revision field, support specifying any valid remote ref

# Motivation

I'd like to be able to point at a GitHub pull request by specifying a revision of e.g. `refs/pull/168/head`

# Attempted Workaround

I tried to add `remote.origin.fetch=+refs/pull/*/head:refs/remotes/origin/refs/pull/*/head` and using a revision of `origin/refs/pull/168/head` to the repo-server git config, but that didn't seem to work. I guess ArgoCD uses some git implementation that ignores the git config?

**Comment by jessesuen** [comment]
> I'd like to be able to point at a GitHub pull request by specifying a revision of e.g. refs/pull/168/head

It's true that I believe we filter out refs which are not tags, branches, etc... 

I believe https://github.com/argoproj/argo-cd/issues/1604 and https://github.com/argoproj/argo-cd/pull/4893 are related to this.

**Comment by yujunz** [comment]
Yeah, #4893 added support for fetching arbitrary refs and commits from remote without specifying refspecs.

You may set argo-repo-server image to [`yujunz/argocd`](https://hub.docker.com/r/yujunz/argocd) to have an early access and let me know if it works for you. @james-callahan

**Comment by Velyks** [comment]
I'm currently hitting this issue when trying to set targetRevision to something like `refs/pull/1234/head` where the PR is from a forked repository.

Is there a way for ArgoCD to fetch these automatically?

**Comment by james-callahan** [comment]
I've upgraded to 2.0.0 and tried this again.
Using a target revision of e.g. `refs/pull/396/head` which points to commit `8c738aa7d0ab20749ceec1e24423993efde789fa` results in the error message:
```
Unable to save changes: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Internal desc = Failed to checkout 8c738aa7d0ab20749ceec1e24423993efde789fa: `git checkout --force 8c738aa7d0ab20749ceec1e24423993efde789fa` failed exit status 128: fatal: reference is not a tree: 8c738aa7d0ab20749ceec1e24423993efde789fa
```

So it *is* resolving the ref; but for some reason is unable to check it out.

**Comment by james-callahan** [comment]
Perhaps #5605 will fix this?

**Comment by yujunz** [comment]
> Perhaps #5605 will fix this?

Yes. Call for review. @alexmt

**Comment by yujunz** [comment]
> So it _is_ resolving the ref; but for some reason is unable to check it out.

Ref resolve is done in ls-remote which includes all the refs. But the default refspecs does not include `refs/pull/`. It must be fetch explicitly.

**Comment by musabmasood** [comment]
We are on github. For us:

```
# this works fine
argocd app diff myapp --revision=refs/pull/494/head

# this results in error
argocd app diff myapp --revision=refs/pull/494/merge
FATA[0011] rpc error: code = Internal desc = Failed to checkout 47916bbf663575419920f7104390361d566b58ff: `git checkout --force 47916bbf663575419920f7104390361d566b58ff` failed exit status 128: fatal: reference is not a tree: 47916bbf663575419920f7104390361d566b58ff
```

I would really like to run the diff on the merged ref without locally merging it

**Comment by snuggie12** [comment]
> Yeah, #4893 added support for fetching arbitrary refs and commits from remote without specifying refspecs.
> 
> You may set `argo-repo-server` image to [`yujunz/argocd`](https://hub.docker.com/r/yujunz/argocd) to have an early access and let me know if it works for you. @james-callahan

@yujunz Any chance you can update to 2.2.X? Wanted to test if it fixes our issues. I figured that's necessary for the PR anyways.

I inquired about getting the PR reviewed, and if the test container works I'll def push hard to get it reviewed.

**Comment by yujunz** [comment]
@snuggie12 please check https://quay.io/repository/yujunz/argocd?tab=tags for the custom build. The latest release was `2.3.0-be4156fd` 14 days ago

**Comment by snuggie12** [comment]
FWIW my test was successful. I don't have bit bucket so I have no clue if it will still pose a problem but the code looks sound to me.

Also as I'm sure you all saw it should be reviewed soon! Excited for this change as it solves some of our argo diff bot issues we've had (see #5532.)
