### ISSUE TITLE
More information on how to setup declarative Cluster Configmap

### ISSUE THREAD

**Issue by ghostsquad** [argoproj/argo-cd#4936]
# Summary

https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#clusters

This page lists many variables and a vague description of what each is, but there's still a lot of ambiguity around what values are related (and required), and how to _obtain_ these values.

# Motivation

Faster way to get started

# Proposal

Enhanced documentation to describe required & related variables, and how to obtain the values (typically)

**Comment by jessesuen** [comment]
We're working on improving the argocd-util to output how the declarative cluster configuration secret should be created: https://github.com/argoproj/argo-cd/pull/4899

We'll be sure to update documentation on how to use it.

**Comment by kshamajain99** [comment]
Refer documentation https://argoproj.github.io/argo-cd/operator-manual/server-commands/argocd-util_config/ to generate declarative config.

**Comment by jessesuen** [comment]
Fixed
