### ISSUE TITLE
User unable to edit parameters even with permissions

### ISSUE THREAD

**Issue by vrodomista** [argoproj/argo-cd#4945]
<img width="899" alt="Screen Shot 2020-12-01 at 12 37 11 PM" src="https://user-images.githubusercontent.com/63687345/100794341-4b099500-33d2-11eb-85ba-eb212711901c.png">
<img width="1466" alt="Screen Shot 2020-12-01 at 12 37 21 PM" src="https://user-images.githubusercontent.com/63687345/100794348-4cd35880-33d2-11eb-93e5-79d50a7ad110.png">

The top image is what the user sees, the bottom image is what I see. Here are the two roles and permissions:

    p, role:developer, applications, get, dev/*, allow
    p, role:developer, projects, get, dev, allow
    p, role:developer, applications, *, dev/*, allow

those are his permissions, mine are as follows:

    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow

Why the discrepancy?

**Comment by jessesuen** [comment]
We don't expect to see different views of the parameters tab for the same application. Could you include the browsers webconsole output to see if there are any failed requests.

Could you also paste the app spec in the application's manifest tab?

**Comment by claudiuvintila** [comment]
Hi! I have the same problem.
kubernetes server: v1.19.13
argocd chart: 3.12.1

<img width="1699" alt="Screenshot 2021-11-15 at 13 12 44" src="https://user-images.githubusercontent.com/2284316/141780106-56bbe1d2-d90c-47a2-8590-e0cc6c1eb675.png">

server:
  config:
    accounts.syl: login
  podLabels:
    app: argocd
  rbacConfig:
    policy.csv: |
      p, role:sr-d-all, applications, *, sr-d/*, allow
      g, syl, role:sr-d-all
    policy.default: role:''

These are my configs.
I see the filtered/correct apps in the /applications page so that part works as it should, but when I go to one app on the params tab I see the edit button and when I press it I get the exact view posted @vrodomista

Any suggestions? 
I can't upgrade to a new argocd version as I have a but when using private git repos :(

**Comment by matanagazan** [comment]
Hi,
I have the same issue in ArgoCD v2.6.4

  policy.csv: |
    p, role:dev, applications, *, bionic/*, allow
    p, role:dev, exec, create, bionic/*, allow
    p, role:dev, logs, get, *, allow
    g, jenkins, role:admin
    g, dev, role:dev
  policy.default: ''
  scopes: '[groups]'

data:
  accounts.dev: 'apiKey,login'
  accounts.jenkins: 'apiKey,login'
  admin.enabled: 'true'
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: 'true'
  server.rbac.log.enforce.enable: 'false'
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s


<img width="961" alt="Screen Shot 2023-03-29 at 17 46 32" src="https://user-images.githubusercontent.com/62660550/228576830-6637ba23-f256-4ad1-be6a-cae88cc9f504.png">

**Comment by niklastanner** [comment]
Whoever has this problem too. Whe had the following rbac set:
```
p, proj:testapp:readonly, repositories, get, */*, allow
```
But this only worked for flat hierarchy. We also had Argo CD Applications within other Applications. In those Sub-Applications we couldn't see the Parameters.
Only @matanagazan solution fixed it for Sub-Applications too (switched from `*/*` to `*`):
```
p, proj:testapp:readonly, repositories, get, *, allow
```

**Comment by BWagenerGenerali** [comment]
> But this only worked for flat hierarchy. We also had Argo CD Applications within other Applications. In those Sub-Applications we couldn't see the Parameters. Only [@matanagazan](https://github.com/matanagazan) solution fixed it for Sub-Applications too (switched from `*/*` to `*`):
> 
> ```
> p, proj:testapp:readonly, repositories, get, *, allow
> ```

We ran into this and still were having this issue, even with the `repositories, get, *` permission. This happens the user has limited permission for the application.

Specifically `applications, get` is insufficient, `applications, create` is required as well. For more information refer to #28476

**Comment by claudiuvintila** [comment]
My problem got fix by updating to a newer version

**Comment by BWagenerGenerali** [comment]
That's great to hear. The issue I linked occurs on the latest version of ArgoCD (3.4.4).
