### ISSUE TITLE
services network rendering should keep track of namespace

### ISSUE THREAD

**Issue by aogier** [argoproj/argo-cd#4946]
# Summary

Hello, current (1.7.9) network view does not keep track of namespaces when rendering
arrows between services and their selected target. They should track this so we can
aggregate various services in the same application.

# Motivation

For various reason I'm keeping all the ingresses we manage in the same application,
everything goes well so far except for this:

![net](https://user-images.githubusercontent.com/321364/100800222-92217580-3426-11eb-8d64-f765c4fd3d87.png)

The actual situation is one service targets 5 replicas in his namespace, the other only one.
No pod is targeted by either services

# Proposal

I think it would be great if diagram reflects actual configuration so we could freely choose
to aggregate an arbitrary number of services/namespaces in the same application

Thank you for argocd, and have a nice day!

**Comment by jessesuen** [comment]
This is a bug, we should only connect edges between resources in the same namespace
