### ISSUE TITLE
argocdexport fails on Openshift 4.5

### ISSUE THREAD

**Issue by u849296** [argoproj/argo-cd#4951]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

When running the argocd export the job fails to run with permission issues to the /backups folder on local storage PV in Openshift 4.5.

Logs from argocdexport pod:
exporting argo-cd
creating argo-cd backup
encrypting argo-cd backup
Can't open /backups/argocd-backup.yaml for writing, Permission denied
139760326087808:error:0200100D:system library:fopen:Permission denied:../crypto/bio/bss_file.c:69:fopen('/backups/argocd-backup.yaml','wb')
139760326087808:error:2006D002:BIO routines:BIO_new_file:system lib:../crypto/bio/bss_file.c:78:

Pod event log:
example-argocdexport-1606933560-zjgcg
NamespaceNSargocd
2 minutes ago
Generated from kubelet on fzeu2openshiftsbtst-r-hmw98-worker-eastus21-mt7jz
8 times in the last 3 minutes
Back-off restarting failed container

**To Reproduce**

Create any export using openshift 4.5 and local storage RWO

**Expected behavior**

Backups should be able to write to the PV and execute a normal backup 

**Screenshots**

**Version**

Installed with ArgoCD Operator 0.0.14

**Logs**

See Above

**Comment by jessesuen** [comment]
We don't provide any guidance on where to place backups. The error `Can't open /backups/argocd-backup.yaml for writing, Permission denied` is specific to your environment/setup.

See: https://argoproj.github.io/argo-cd/operator-manual/disaster_recovery/

**Comment by u849296** [comment]
I did not configure the location for the backup or create the storage, this was created by the ArgoCD Operator (https://github.com/argoproj-labs/argocd-operator)

**Comment by alexmt** [comment]
@u849296 ,  I think it is better to create an issue in https://github.com/argoproj-labs/argocd-operator repo.

**Comment by u849296** [comment]
Done, thx
