### ISSUE TITLE
Argo rollback error

### ISSUE THREAD

**Issue by vdharmap** [argoproj/argo-cd#4956]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by iam-veeramalla** [comment]
@vdharmap Please provide below details

Describe the bug

A clear and concise description of what the bug is.

Description
To Reproduce
Expected behaviour
Screenshots

**Comment by jessesuen** [comment]
For those confused, this is from an v1.8.0-rc build:

![image](https://user-images.githubusercontent.com/12677113/101091284-cf901b00-356c-11eb-8dd2-9e3c46a26627.png)

**Comment by jessesuen** [comment]
@alexmt already fixed this.
