### ISSUE TITLE
Add Dhall support

### ISSUE THREAD

**Issue by keirlawson** [argoproj/argo-cd#4961]
# Summary

It would be great if Argo could support Dhall-based k8s manifests out of the box

# Motivation

I would like strongly-typed k8s configuration that is not whitespace sensitive so that I am more likely to catch issues prior to the deployment stage

# Proposal

By using the Dhall bindings for Go at https://github.com/philandstuff/dhall-golang

**Comment by jessesuen** [comment]
Rather than build first-class support for additional tooling, we instead want to make config management integration more seamless. See: https://github.com/argoproj/argo-cd/blob/master/docs/roadmap.md#config-management-tools-integrations

**Comment by blakepettersson** [comment]
Seems like this should be possible with a [CMP](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/) nowadays.
