### ISSUE TITLE
Add NTLM Authentication for connecting to repo using HTTPS

### ISSUE THREAD

**Issue by erdiugurlu** [argoproj/argo-cd#4983]
# Summary

Currently, ArgoCD can connect to repositories using HTTPS with basic authentication. If we enable NTLM Authentication to connect to repositories using HTTPS, it will be possible to connect to Azure DevOps from ArgoCD using HTTPS...

# Motivation

We use Azure DevOps as a repo. In order to connect to it from ArgoCD, we need NTLM Authentication.

# Proposal

By using the Azure Go-NTLMSSP library at https://github.com/Azure/go-ntlmssp

**Comment by jessesuen** [comment]
I've briefly tested Argo CD years ago with Azure repos, but didn't come across this limitation. Is this a new requirement for using Azure DevOps?

**Comment by erdiugurlu** [comment]
Yes, you are right. Currently, we have no problem related to between Azure Devops and ArgoCD integration no more... 
Since one of Azure DevOps nodes did not work properly, we were getting authentication error. 

I has used Rest API of Azure DevOps by using NTLM authentication. That' s why, I opened the issue after facing the issue above.

If it is okay for you, I will remove the issue.
