### ISSUE TITLE
change "Table of contents" to "Table of Contents"

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4987]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

For titles, one generally writes `Table of Contents`

**To Reproduce**

1. Visit https://argoproj.github.io/argo-cd/getting_started/
1. Look at the right sidebar

**Expected behavior**

`Table of Contents`

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/101268860-3ad91900-3736-11eb-82c7-2e0399b0d35b.png)

**Version**

**Logs**

**Comment by jessesuen** [comment]
You're a member now so please feel free to assign yourself issues along with PRs =)

**Comment by jsoref** [comment]
Yeah, I filed this w/o a PR because I actually couldn't figure out where it came from :-( -- If I could, I would have... my guess is there's some third party tool?

**Comment by nidhiardent** [comment]
Looks like this is the issue with the Github Pages.
Github pages have created the TOC (Table of Contents) header as _Table of contents_ rather than **Table of Contents**

**Comment by reginapizza** [comment]
I started looking at this a little bit yesterday, you will have to add a custom theme to Material for mkdocs. https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme. I can try to make a PR for it if no one else is working on it? @jsoref @nidhiardent
