### ISSUE TITLE
Success message on cluster/repo removal

### ISSUE THREAD

**Issue by igaskin** [argoproj/argo-cd#5002]
# Summary

Successfully adding a cluster or repository provides a nice message of the form `repository '<foo>' added`.  Conversely successfully removing a cluster or repository does not have any form a visual feedback for the user from the cli. 

# Steps to Reproduce

```bash
$ argocd repo add https://helm.traefik.io/traefik --type helm --name traefik
repository 'https://helm.traefik.io/traefik' added

$ argocd repo rm https://helm.traefik.io/traefik
# note there is no output here
```

# Proposal

After successfully running `argocd cluster/repo rm` print the message `cluster/repository <foo> removed`

**Comment by igaskin** [comment]
idk how to add labels but I would suggest these labels `component:cli type:usability good first issue`

**Comment by jannfis** [comment]
> idk how to add labels but I would suggest these labels `component:cli type:usability good first issue`

I think you would need triage permissions on the repo for that - I added your very good suggestions, thanks!

**Comment by jessesuen** [comment]
@igaskin were you planning on taking this?

**Comment by sidewinder12s** [comment]
I originally raised this in the argo-cd slack channel: https://argoproj.slack.com/archives/CASHNF6MS/p1607397447262900

Looks like if the cluster is no longer existing/available, `argocd cluster rm` silently returns without error. Removing the cluster secret from the argo namespace properly removes the cluster.

**Comment by igaskin** [comment]
> @igaskin were you planning on taking this?

Sure, I can do it.
