### ISSUE TITLE
Support application specific app parameter overrides in Git

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#5003]
# Summary

PR #4084 introduced support for an `.argocd-source.yaml` file to store parameter overrides for an application in Git, decoupled from the parameter overrides in `Application` resources. This feature should be enhanced to support different parameters being set dependent on the application that is created from this source.

# Motivation

Multiple applications can be created using the same Git repository + path combination. If an `.argocd-source.yaml` exists in that path, it will be used by any of the applications spawned. This may be unwanted.

# Proposal

We should support application specific parameter overrides from Git by the following logic:

* `.argocd-source.yaml`  will be merged into parameter overrides for all applications sourced from the directory where this file exists
* `.argocd-source-<application_name>.yaml` will be merged into parameter overrides for application `<application_name>` if sourced from the directory where this file exists 

Alternatively, we could introduce a new field in the `Application` CRD (e.g. `.spec.source.overrideFiles`) which holds a list of override file names to consider when building manifests from Git.

**Comment by jessesuen** [comment]
Correction:

> `. argocd-app.yaml`

It should be `.argocd-source.yaml` and not `. argocd-app.yaml`.

**Comment by jannfis** [comment]
> Correction:
> 
> > `. argocd-app.yaml`
> 
> It should be `.argocd-source.yaml` and not `.argocd-app.yaml`.

Thanks, I have edited original description to be correct now!
