### ISSUE TITLE
[API] documentation doesn't match response for https://<server>/api/v1/repositories/{repo}

### ISSUE THREAD

**Issue by GerbenWelter** [argoproj/argo-cd#5004]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The API documentation states that the response should contain 'privateSshKey' among other keys for Git repos but currently it only reports the following for a Git repository:

```json
{
	"repo": "ssh://git@internal-git.company.com:22/project/repo-name.git",
	"connectionState": {
		"status": "Successful",
		"message": "",
		"attemptedAt": "2020-12-08T20:20:36Z"
	},
	"type": "git",
	"name": "repo-name"
}
```

The private key was supplied when configuring the repo otherwise we wouldn't be able to use it.

**To Reproduce**

- Login with 'admin' user.
- Create a repository using 'Connect repo using SSH'.
- Supply Name (empty or string), url (ssh://git@internal-git.company.com:22/project/repo-name.git) and private ssh key.

Perform API query by requesting this url: https://\<argocd-server\>/api/v1/repositories/\<urlencoded form of repo url\>

**Expected behavior**

According to the https://\<argocd-server\>/swagger-ui documentation for the GET method of the REPOSITORYSERVICE it should return the 'privateSshKey' and possibly also the 'enableLfs' and 'insecure' key.

Confusingly, the argocd cli returns the following:

```
TYPE  NAME        REPO                                                           INSECURE  OCI    LFS    CREDS  STATUS      MESSAGE
git   repo-name   ssh://git@internal-git.company.com:22/project/repo-name.git    false     false  false  false  Successful
```

So atleast the Insecure and LFS setting seem to be parsed by the argocd cli.

**Version**

```shell
argocd: v1.8.0+bb7bdba
  BuildDate: 2020-12-08T17:45:44Z
  GitCommit: bb7bdbab9b3ee09e580d3a3eacf82949ff055617
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.7+33c93ae
  BuildDate: 2020-09-29T04:56:23Z
  GitCommit: 33c93aea0b9ee3d02fb9703cd82cecce3540e954
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
  Jsonnet Version:
```

**Comment by jessesuen** [comment]
The reason why this is happening is because the auto-generated docs will reflect the actual internal data structures, *but* from the API server, we will never return sensitive information, so this specific field will be nulled out before returning to the user. Unfortunately, I don't know a clean way to fix this since the docs are auto-generated.

**Comment by GerbenWelter** [comment]
Oh wow, that's unexpected. I understand about the sensitive information but I assumed it would only return it if the session was authenticated by a user with the correct permissions. So, currently there's no way to determine if the configured ssh key should be updated or not?

**Comment by jannfis** [comment]
You might be able to achieve this by evaluating the `connectionState` field for being everything else than `Success`. The `Message` field will contain the reason, and in case of SSH authentication failure will contain something along the lines: `Unable to connect to repository: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

**Comment by GerbenWelter** [comment]
Yes, that might be an option. I'll try it later. Thanks and closing this issue.
