### ISSUE TITLE
Reorganize binaries to reduce image size

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#5005]
# Summary

It doesn't make sense to have separate: argocd-server, argocd-application-controller, argocd-repo-server binaries, since these are not user-facing binaries and only bloat the image. 

Meanwhile, argocd-util, is a useful binary meant for operators.

# Proposal

1. merge all backend binaries (argocd-server, argocd-application-controller, argocd-repo-server) to a single binary which is included in argocd image
2. Split dex wrapper out of argocd-util and move it into consolidated backend binary
3. remove argocd-util from image.

This should reduce our image size considerably (by estimated ~200MB)

**Comment by jannfis** [comment]
Do you think about something like `busybox` does, so for example having a single binary (i.e. `argocd-server`) that behaves differently depending on how it was called (so, a symbolic link `argocd-repo-server` -> `argocd-server` that changes `argv[0]` and therefore starts repo server) or about introducing new sub-commands for a central binary?

For the latter, I would propose naming this new binary `argocd-server` and following sub-commands:

* `argocd-server api [flags]` starts API server
* `argocd-server repo [flags]` starts repository server
* `argocd-server controller [flags]` starts application controller

I guess for starting locally, testing etc the sub command approach would be more suitable than a busybox-esque approach.

**Comment by iam-veeramalla** [comment]
I hope this task will also look at any unused binaries that are left out or forgot to delete in the build process. Example: we might need a lot of binaries to build the application but a-lot of them are not needed to run the container, I see that we are deleting the binaries that are not required in runtime container but I also think all of them are not removed and few are left out.

**Comment by jannfis** [comment]
What binaries exactly do you mean, @iam-veeramalla?

Actually, we use a multi-stage build process and copy only the required binaries to the final target image that gets distributed. Are there some we have erroneously copied, or do you mean binaries that come from the base image `debian:10-slim`?

**Comment by iam-veeramalla** [comment]
> What binaries exactly do you mean, @iam-veeramalla?
> 
> Actually, we use a multi-stage build process and copy only the required binaries to the final target image that gets distributed. Are there some we have erroneously copied, or do you mean binaries that come from the base image `debian:10-slim`?

@jannfis Yes, I went through the build process, I feel it is well organised with multi-stage build concept. I wonder why we still need binaries likes kubectl in the final target. Argo controller makes api calls with kube-api to fetch the resource information right? Am I missing something here? Please correct me as its my early days with argo.

https://github.com/argoproj/argo-cd/blob/9e61354fa25b179e74e6425a7ebd4136a97e672b/Dockerfile#L64

**Comment by jannfis** [comment]
Ah, good catch about the `kubectl` binary @iam-veeramalla. You are right that we moved away from fork/exec of `kubectl` to leverage the K8s API directly using client libraries, since quite a while now.

@jessesuen / @alexmt - this seems like a relict, can we remove it from the distribution or are there any non-obvious dependencies to `kubectl` still existing?

**Comment by iam-veeramalla** [comment]
> Ah, good catch about the `kubectl` binary @iam-veeramalla. You are right that we moved away from fork/exec of `kubectl` to leverage the K8s API directly using client libraries, since quite a while now.
> 
> @jessesuen / @alexmt - this seems like a relict, can we remove it from the distribution or are there any non-obvious dependencies to `kubectl` still existing?

@jannfis Let me know if you need any PR for this

**Comment by jessesuen** [comment]
> Do you think about something like busybox does, so for example having a single binary (i.e. argocd-server) that behaves differently depending on how it was called (so, a symbolic link argocd-repo-server -> argocd-server that changes argv[0] and therefore starts repo server) or about introducing new sub-commands for a central binary?

Interesting. I didnt realize busybox did that, nor realize that was an option. I don't really have a strong opinion on this, other than that I don't think most people will understand/know that argv[0] will then be significant, and it might make local development annoying.

> this seems like a relict, can we remove it from the distribution or are there any non-obvious dependencies to kubectl still existing?

AFAIK, kubectl can/should be removed.

**Comment by kshamajain99** [comment]
I will take a look at this issue.

**Comment by jessesuen** [comment]
Spoke with @alexmt and we agree the both the busy box approach as well as sub commands is the way to do this. Busybox prevents upgrade/migration release notes. sub commands allow easier development.

**Comment by kshamajain99** [comment]
ArgoCD Binaries Structure:

**argocd/argocd-all**: (busybox format)
1. argocd(cli)
2. argocd-util
3. argocd-server
     - api-server
     - repo-server
     - controller
     - dex

Subcommands for argocd-server:

- `argocd-server api [flags]` starts API server
- `argocd-server repo [flags]` starts repository server
- `argocd-server controller [flags]` starts application controller
- `argocd-server dex [flags]` rundex, gendexcfg

**Comment by jangraefen** [comment]
I just tried to work through the [Contribution guide](https://argoproj.github.io/argo-cd/developer-guide/contributing/#test-connection-from-build-container-to-your-k8s-cluster) and noticed that running `make verify-kube-connection` is now no longer working, since `kubectl` is no longer part of the test tools image.

Is that an intended site-effect of this issue? If so, the documentation would need a rework. It might also be an option to have kubectl only as part of the test image.
