### ISSUE TITLE
[UI] Top level indicator when app is overriding parameters

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#503]
When an application has parameter overrides, the source of truth is in two places: git and the app CRD. When this happens, we should have a top level indicator (e.g. caution icon) to warn users that there are parameter overrides.

Instead of a caution icon, this could also potentially be a warning condition.

**Comment by jessesuen** [comment]
Can we remove this label when there are no overrides?

![image](https://user-images.githubusercontent.com/12677113/45246754-d9584480-b2b7-11e8-9be7-9e98d8ac72db.png)

**Comment by merenbach** [comment]
@jessesuen should be all fixed!
