### ISSUE TITLE
Error creating application from OCI helm chart in ACR

### ISSUE THREAD

**Issue by Firgeis** [argoproj/argo-cd#5030]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

Error "unsupported protocol scheme" when creating an application from an OCI helm chart hosted in ACR. I have tried both repos (both give the same error). This repo is confirmed working (attached a screenshot of helm pulling the chart)
See screenshots below

**Expected behavior**

Application is created

**Screenshots**

Names removed for security purposes
argocd repos
![argo1](https://user-images.githubusercontent.com/6520188/101825434-5c5a4c00-3b0c-11eb-9ec6-a9f1b51578fe.jpg)

error creating 
![argo2](https://user-images.githubusercontent.com/6520188/101825470-6714e100-3b0c-11eb-8429-a7b2666a4fa8.jpg)

helm pulling the chart
![argo4](https://user-images.githubusercontent.com/6520188/101829684-261fcb00-3b12-11eb-972f-488e12e011b0.png)

**Version**

![argo3](https://user-images.githubusercontent.com/6520188/101825506-7562fd00-3b0c-11eb-9db2-d7f9595743d4.png)

**Comment by Firgeis** [comment]
I believe this can be tracked down to https://github.com/argoproj/argo-cd/blob/68f316137bc29c42555854567104d5a8cfce31ff/reposerver/repository/repository.go#L1288

This check is running and looking for an index.yaml even though it is not an OCI repository (Should call the TestOCI method instead of GetIndex)

**Comment by eugentius** [comment]
Same with OCI Harbor registry

**Comment by alexmt** [comment]
Hello @Firgeis ,

I think there are two errors:

* Argo CD assumes that OCI chart path must have exactly two levels. e.g. `<repo-name>/<chart-name>` . In your case chart is stored at `charts/develop/<something>` and Argo CD fallback to non-OCI registry. Chart path should not be used to auto-detect OCI
* Helm does not allow extracting index of OCI registries and does not allow to pull chart by digest. So revision must be set to exact version. Argo CD should return an appropriate error message.


Working on PR with the fix and improved error message.
