### ISSUE TITLE
Show number of pod restarts in the argo ui

### ISSUE THREAD

**Issue by vjpie2002** [argoproj/argo-cd#5041]
Show number of pod restarts in the argo ui.

# Motivation
 Showing number of pod restart counts in the argo ui will help us to see which pods were restarted and how many times without going to any other monitoring dashboards or running kubectl commands. This will be very helpful feature. 

# Proposal

By getting the number of restart count, we can add this count at the bottom of each pod as shown by arrow in the screenshot
![image](https://user-images.githubusercontent.com/22686326/101938001-83119480-3b97-11eb-92aa-4e51a3b8811b.png)

**Comment by jessesuen** [comment]
I think this is a good idea.

**Comment by jessesuen** [comment]
I suggest that the UI or backend should omit it, if the value is zero.

**Comment by keithchong** [comment]
Hi @jessesuen / @alexmt , I could look at this one. I haven't worked on many back-end issues.

**Comment by jannfis** [comment]
@keithchong Thanks for the offer, much appreciated! I will assign this issue to you. Let us know if you have questions or get stuck somewhere.

**Comment by Gaikanomer9** [comment]
Hello everyone!
@keithchong how is it going? Do you need any help? I could start working on this if you don't have time. 
@jannfis what do you think?

**Comment by keithchong** [comment]
Hi guys, sorry about the delay. I got re-focused elsewhere but I have already started on this.  Thanks for understanding.

**Comment by keithchong** [comment]
<img width="1379" alt="Screen Shot 2021-02-02 at 2 42 45 PM" src="https://user-images.githubusercontent.com/7726022/106663374-a0e4ef80-6571-11eb-9c49-d320fb175b04.png">

**Comment by alexmt** [comment]
Thank you for update!

**Comment by keithchong** [comment]
No problem @alexmt.  Jesse said in the above comment to not show it if the restart count is 0:

<img width="1417" alt="Screen Shot 2021-02-02 at 5 09 08 PM" src="https://user-images.githubusercontent.com/7726022/106669486-c544ca00-6579-11eb-8feb-4e52eb9ff8c8.png">

**Comment by vjpie2002** [comment]
Will it be better to show restart count as zero that will ensure that it is
actually showing data rather than showing no data?

- Vijay

**Comment by santavizma** [comment]
How could we see more detailed, when the restarts happened? Thank You.
