### ISSUE TITLE
Commit message overflows box

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5043]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Commit message overflows sync ok box

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/argo-rollouts

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/102000248-72eed780-3cb3-11eb-9995-f02109ac243e.png)

**Version**

```shell
{
    "Version": "v1.8.0+9e61354",
    "BuildDate": "2020-12-11T16:52:16Z",
    "GitCommit": "9e61354fa25b179e74e6425a7ebd4136a97e672b",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by reginapizza** [comment]
I wanted to try to pick this issue up, but wanted to get some clarification on desired behavior first. 

By removing the `height: 75px` on `.application-status-panel__item`, the box will expand to fill the text. 
![removeheightpropertyonly](https://user-images.githubusercontent.com/50851526/103031898-bd324d00-452c-11eb-93be-06163ef7dbb7.png)

However, with more text there, it will expand the box, covering up the application resource tree.
![applicationstatuspaneltoolong](https://user-images.githubusercontent.com/50851526/103031951-dd620c00-452c-11eb-92b2-858aecb70abc.png)

What should be the desired behavior for the box? Should it have a max height and then be able to expand to show all overflowing content when a user clicks on it? Should the message be truncated after the box reaches a certain height and the user should be directed elsewhere to read the information?

 Some good background to know is what would be the most content that would ever be available there?

**Comment by jsoref** [comment]
> Should it have a max height and then be able to expand to show all overflowing content when a user clicks on it?

I think so

I'm not sure that the expand should be straight down, it might be better as "pop out" / "modal center"

**Comment by reginapizza** [comment]
Was considering that as well, is there anywhere else in argo cd that has this functionality that I could reference for styling on a pop out?

**Comment by jsoref** [comment]
Delete confirmations (n.b. some say `Delete x`, others say `Remove y`) come to mind. Beyond that, I'm not sure.

The version info thing pops up to the far right, you might consider that approach -- it doesn't seem like a great match as I don't really want to read a commit message in a narrow column.

The settings views are all fairly center aligned.

n.b. I'm not designing this from a wholistic ArgoCD perspective, mostly just a free imagination view. So please don't take these as absolute instructions, just general "you might consider".

**Comment by reginapizza** [comment]
Great, I'll start looking into these! I like the way the delete confirmation comes up, maybe I could try to do something like that. Thanks!

**Comment by reginapizza** [comment]
I did a little bit of work on this and I have two options for styling I'd like to get some feedback on...

This first fix would just be a gradient and `overflow: hidden` property. The user would not be able to see all the information unless they hit the expand button. However, unless I added in some more logic to it, the gradient would still be applied to shorter messages that would otherwise fit in that space. 
![argo-overflow-gradient](https://user-images.githubusercontent.com/50851526/104328994-6b8d3a80-54ba-11eb-8a35-3c26c79b6f88.png)

The second fix I came up with is to have the info scrollable... you can still hit the expand button to see it more clearly, but the downside of this is that now you would have a scrollbar there. And at that point if you have a scrollbar there, then maybe the whole item should just be scrollable and we wouldn't even need the expand button & info popup.
![argo-overflow-scroll](https://user-images.githubusercontent.com/50851526/104328997-6d56fe00-54ba-11eb-89ba-a832370f74cd.png)

Upon hitting the expand button, this would be the info popup that shows the whole message (I still want to add a little bit more styling to this though, that is if we want to use it)
![info-popup](https://user-images.githubusercontent.com/50851526/104329012-71831b80-54ba-11eb-983b-db19b0001b40.png)

Please let me know your thoughts!

**Comment by jsoref** [comment]
The scrollbar indeed looks ugly. Can you cheat and just add an extra blank line to the end of the content to force the gradient to work better?

For the dialog-ish thing, maybe copy over the styling from the Sync failed above (red circle w/ x, + Red colored Sync failed, + larger font) ? -- Not certain about this. In principle you should be aware of other styles, so if nothing does this, then maybe not, but try it and maybe someone would agree it's the right choice even if there isn't a style for it.

If we're popping out, it'd be great if space below were allocated to report whatever error message there was that explains how ArgoCD decided it failed :-)

**Comment by jsoref** [comment]
Maybe move the `Failed a day ago (timestamp)` into the title-ish area to the right of `Sync failed` instead of leaving it below?

**Comment by reginapizza** [comment]
This is what it would look like with an extra blank line, both with text that would fit in that space normally and  text overflowing. I think it works for the most part but I'm happy to keep trying to improve it if it's not up to standards.
![Screenshot from 2021-01-12 17-38-09](https://user-images.githubusercontent.com/50851526/104383489-e88dd380-54fd-11eb-969b-a87c011f1c98.png)
![Screenshot from 2021-01-12 17-40-00](https://user-images.githubusercontent.com/50851526/104383500-ed528780-54fd-11eb-8eec-40e998ef771a.png)

This is a more styled version of info-popup. It still has the same functionality as before, where if you click on the status it takes you to the side panel. I also included the information that's normally available when you hover over the Help Icon (`daysSinceLastSynchronized`). 
![argocd-info-popup](https://user-images.githubusercontent.com/50851526/104384246-24756880-54ff-11eb-86e4-491dbf22409e.png)

>it'd be great if space below were allocated to report whatever error message there was that explains how ArgoCD decided it failed 

Where would this information be? I don't mind trying to add it, possibly in another PR if that makes more sense. My main worry (without looking too much into it) is that the `Popup` component has a max height and if the information in this popup gets too long, it would need to be scrollable and thus we'd have to add the scrollbar back in, although I don't think that would be as bad as having the scrollbar in the main UI.

Do you know what an edge case would be for how much information might be included in this info-popup? Maybe I should be considering that case anyway if it could potentially be a lot of information.

**Comment by jsoref** [comment]
> Where would this information be?

Not sure offhand

> I don't mind trying to add it, possibly in another PR if that makes more sense.

I'm not opposed to it being a follow-up.

> My main worry (without looking too much into it) is that the `Popup` component has a max height and if the information in this popup gets too long, it would need to be scrollable and thus we'd have to add the scrollbar back in, although I don't think that would be as bad as having the scrollbar in the main UI.

I suspect I'd be willing to pay for that scrollbar if we hit that.
 
> Do you know what an edge case would be for how much information might be included in this info-popup?
> Maybe I should be considering that case anyway if it could potentially be a lot of information.

Commit messages can be incredibly long.

I sometimes create PRs that have a thousand commits (GitHub gets unhappy at 250, but even so), and people will sometimes squash them into a single commit, but with each commit getting a single line in the commit message.

Here's a sample of messages:
* ffb8ce2
* torvalds/linux@f076ef4
* mpv-player/mpv@1e70e82

**Comment by reginapizza** [comment]
Got it, in that case I will make it a scrollbar in the info-popup. Thanks!

**Comment by reginapizza** [comment]
this issue should now be closed @jsoref

**Comment by nsharma-fy** [comment]
Is this issue fixed? I am still seeing it in ArgoCD console version v2.4.0+5921e2a.
