### ISSUE TITLE
Tests should be run with race-condition detector

### ISSUE THREAD

**Issue by merenbach** [argoproj/argo-cd#505]
I believe that the [race-condition detector](https://blog.golang.org/race-detector) would be a good addition to our test suite by helping to detect a class of potential runtime issues that we're not currently able to effectively check for.

Running the tests now with the `-race` flag lists some potential race conditions involving Casbin.  Not sure how to resolve.  Also if we do figure this out, we'll need to change the way that our coverage tests are being generated, omitting the `-covermode` flag or changing it from `count` to `atomic`.

Edit: More info on the race-condition detector [here](https://golang.org/doc/articles/race_detector.html).

Edit 2: Incomplete stack trace of race conditions as detected with `make test`:

```
==================
WARNING: DATA RACE
Read at 0x00c42035c158 by goroutine 9:
  github.com/argoproj/argo-cd/vendor/github.com/casbin/casbin.(*Enforcer).Enforce()
      /Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/github.com/casbin/casbin/enforcer.go:316 +0x44e
  github.com/argoproj/argo-cd/util/rbac.(*Enforcer).Enforce()
      /Users/amerenbach/go/src/github.com/argoproj/argo-cd/util/rbac/rbac.go:83 +0x88
  github.com/argoproj/argo-cd/util/rbac.TestPolicyInformer()
      /Users/amerenbach/go/src/github.com/argoproj/argo-cd/util/rbac/rbac_test.go:98 +0x36a
  testing.tRunner()
      /usr/local/Cellar/go/1.10.3/libexec/src/testing/testing.go:777 +0x16d

Previous write at 0x00c42035c158 by goroutine 16:
  github.com/argoproj/argo-cd/vendor/github.com/casbin/casbin/model.Model.ClearPolicy()
      /Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/github.com/casbin/casbin/model/policy.go:44 +0x14a
  github.com/argoproj/argo-cd/vendor/github.com/casbin/casbin.(*Enforcer).LoadPolicy()
      /Users/amerenbach/go/src/github.com/argoproj/argo-cd/vendor/github.com/casbin/casbin/enforcer.go:207 +0x57
  github.com/argoproj/argo-cd/util/rbac.(*Enforcer).SetUserPolicy()
```

**Comment by hsluoyz** [comment]
Hi. If you use Casbin in a multi-threading manner, you can use the synchronized wrapper of the Casbin enforcer: https://github.com/casbin/casbin/blob/master/enforcer_synced.go. See here: https://github.com/casbin/casbin#multi-threading
