### ISSUE TITLE
Helm Value files from different location

### ISSUE THREAD

**Issue by mojtabacazi** [argoproj/argo-cd#5065]
# Summary

Let helm value files be in a different location than the chart.

# Motivation

Right now, helm value files must be in the same location as the helm chart itself.  If we relax that requirement, it'll make it very easy to deploy 3rd party charts, where you can use the 3rd party chart repo and only store values file in a repo (or any other URL) you manage. 
For 1st party charts, that'll let you separate code (chart itself) from the configuration (value files), which is always a good thing.

# Proposal

How do you think this should be implemented?

I'm not sure about the backend, but the UI should accept a URL as value files. It should also be able to use credentials to fetch the file from a private Github repo.

**Comment by jessesuen** [comment]
The current pattern for this is a git repo containing a helm chart which has the upstream repo as a dependency.

See: https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency

**Comment by mojtabacazi** [comment]
> The current pattern for this is a git repo containing a helm chart which has the upstream repo as a dependency.
> 
> See: https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency

@jessesuen The overhead of creating a chart with dependencies doesn't have any benefits and further complicates the deployment.

**Comment by stefanlsd** [comment]
> The current pattern for this is a git repo containing a helm chart which has the upstream repo as a dependency.
> 
> See: https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency

This doesn't seem to work with helm 3.  We keep getting the below.  
```
Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in argocd/applications/steftest: rpc error: code = FailedPrecondition desc = Failed to unmarshal "Chart.yaml": failed to unmarshal manifest: error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in '{"apiVersion":"v2","appVersion":1,"dependencies":[{"name":"swiss-army-knife","repository":"https://lsdopen.github.io/charts","version":"0.1.0"}],"description":"swiss-army","name":"swiss","type":"application","version":"0.1.0"}'
```

**Comment by daurnimator** [comment]
> The current pattern for this is a git repo containing a helm chart which has the upstream repo as a dependency.
> 
> See: https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency

With helm3 charts I get e.g.
> Error: error unpacking ingress-nginx-3.16.1.tgz in ingress-nginx: apiVersion 'v2' is not valid. The value must be "v1"

Adding in `apiVersion: v2` I get:
>  failed exit status 1: load.go:120: Warning: Dependencies are handled in Chart.yaml since apiVersion "v2". We recommend migrating dependencies to Chart.yaml. Error: validation: chart.metadata.version is required

Adding in `metadata: {version: 0.0.0}` doesn't help, but `version: 0.0.0` does.

I then get:
> load.go:120: Warning: Dependencies are handled in Chart.yaml since apiVersion "v2". We recommend migrating dependencies to Chart.yaml. Error: the lock file (Chart.lock) is out of sync with the dependencies file (Chart.yaml). Please update the dependencies

So moving requirements from requirements.yaml into Chart.yaml, I can finally sync again...


That example needs updating for helm3 now that helm2 stable repository is removed.

**Comment by trim777** [comment]
Looks like ArgoCD already can get values from some external HTTP-endpoint, but without any authentication. This is really blocks us, as a workaround we are going to try nginx as proxy to send authenticated request to external source of values.

**Comment by maruina** [comment]
Do you have a working example of the HTTP endpoint?

**Comment by EppO** [comment]
> Looks like ArgoCD already can get values from some external HTTP-endpoint, but without any authentication. This is really blocks us, as a workaround we are going to try nginx as proxy to send authenticated request to external source of values.

Unfortunately, using HTTP endpoint for values file won't make ArgoCD track for changes on that values file. 
Only supported option is to use an umbrella Chart but there should be a better way. Splitting the manifest templates and the environment settings is a big deal because quite often the access control and approval workflow is driven by git repositories.
Looking at all tickets opened on this subject (#2789, #3988), I would love to see Argo CD team to drive a discussion with the community about it.

**Comment by KlavsKlavsen** [comment]
https://github.com/argoproj/argo-cd/issues/4129 <- yet another proposal for solving this.. and a nice one too.. Does not seem overly complex to implement, nor to use ?

**Comment by Cajga** [comment]
@jessesuen, that workaround cannot be used in case you use a private helm chart repository with authentication.

**Comment by peterhaddad3121** [comment]
Are there any updates for Helm to provide https support and encoding URLs and passwords? This would be an extremely useful feature.

**Comment by crenshaw-dev** [comment]
Loading external values files from http(s) is already supported, but as previously mentioned, Argo CD does not track those files for changes.

Full support will be added for this PR: https://github.com/argoproj/argo-cd/issues/2789

Closing unless I've missed something that distinguishes this one from #2789
