### ISSUE TITLE
Need a way to sync a single resource 

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-cd#508]
As a follow up to #262, we have an ability to sync individual resources.

**Comment by jessesuen** [comment]
Needs a new list in SyncOperation of group, kind, name

**Comment by merenbach** [comment]
@jessesuen does rollback need to support individual resources, as well? If so: is there a way to lock the rollback to the result of the most recent sync? If we sync one resource, is there a technique we can use to ensure that a rollback won't try to rollback multiple resources?

**Comment by merenbach** [comment]
Ah, I see that #628 indicates we want to subsume rollback into Sync, so I'll ignore rollback for now.
