### ISSUE TITLE
Allow resource pruning to be an implicit final wave of a sync operation

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#5080]
# Summary

This feature is to allow the ability for resource pruning to happen as a final, implicit wave of a sync operation, after the other resources have been deployed and become healthy, and after all other waves completed successfully.  Currently, pruning happens at the same time as the first wave of `kubectl apply` of the resources, which causes some challenges with ordering.

# Motivation

There are times when pruning at the beginning of a sync operation is not desired. Two examples are:

1. kustomize configmap/secret generators create new configmaps and secrets with new names whenever the content of the secret or configmap changes. If the pruning of the old configmaps is done early, it would cause the configmap to be deleted out from underneath running pods 
2. a user is migrating from a Deployment to a Rollout (or other resource). It is desired to allow the Rollout to become healthy first, before deleting the Deployment

# Proposal

A new sync option should be provided to indicate that the pruning of resources should happen last, after all sync waves complete successfully (but before PostSync), and only if the other resources become healthy.

This also may be desired to be done more granularly, at a resource level, by annotating a resource with an indication to prune the configmap as a final wave. e.g.:

```yaml
annotations:
  argocd.argoproj.io/sync-options: PruneLast=true
```

**Comment by akhy** [comment]
+1 with similar case as @jessesuen stated

We are using ArgoCD + Argo Rollout + Kustomize Configmap Generator. When in the middle of canary rollout, the *old* configmap would be pruned too early. The old pods are still running, but will fail to restart (e.g. probe fails) since their configmap is already gone.
