### ISSUE TITLE
/!\ icon for overridden parameters should be gavel

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5085]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The current warning icon reads like a warning and not like an override

**To Reproduce**

Define a parameter override and visit the parameters overrides page

**Expected behavior**

Use gavel https://fontawesome.com/icons/gavel?style=solid
![image](https://user-images.githubusercontent.com/2119212/102549251-ced9a780-4089-11eb-9d18-dd8b4b840da0.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/102549281-d8630f80-4089-11eb-918d-962fddb61cfc.png)

**Version**

```shell
{
    "Version": "v1.8.1+c2547dc",
    "BuildDate": "2020-12-10T02:59:21Z",
    "GitCommit": "c2547dca95437fdbb4d1e984b0592e6b9110d37f",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jmacedoleite16** [comment]
Hello , what the icon gavel mean on the History and Rollback?

**Comment by jsoref** [comment]
I have no idea. This issue was closed in 2020. Open a new ticket with at least a picture, preferably a link to an application in https://cd.apps.argoproj.io/applications, but if not that, some steps to reproduce or some descriptive information.

The only instance of `fa-gavel` I know of is used for "overridden parameters".
https://github.com/argoproj/argo-cd/blob/c9c7989f8c12c61d1ff12998b4049699a7178113/ui/src/app/applications/components/application-parameters/application-parameters.tsx#L94
