### ISSUE TITLE
CSS bug: argo-icon-application not centered on firefox

### ISSUE THREAD

**Issue by reginapizza** [argoproj/argo-cd#5103]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

CSS bug in styling on `.argo-icon-application`  that affects users of mozilla firefox.

**To Reproduce**

- start up an instance of Argo CD running locally and open localhost:4000 in firefox browser.
- create an application and you should be able to see it

**Expected behavior**

Would expect icon to be centered, as it is in chrome. 

**Screenshots**

On Chrome it appears centered, like so: 
![chrome-argo-application-resource-icon](https://user-images.githubusercontent.com/50851526/102829127-6d307a80-43b4-11eb-929c-cbf91c5c0f99.png)

On Firefox (version 77), it is not centered:
![firefox-argo-application-resource-icon](https://user-images.githubusercontent.com/50851526/102829137-74f01f00-43b4-11eb-9e4e-6a88a2157327.png)

**Version**

```shell
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:44:27Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
```

**Comment by rbreeze** [comment]
I think this has been fixed, either in a more recent Argo CD version or a newer Firefox version. Below is a screenshot of ArgoCD as of commit 47529ee, in Firefox v85.0.2.

<img width="334" alt="Screen Shot 2021-02-18 at 10 18 54 AM" src="https://user-images.githubusercontent.com/6250584/108402701-b5acbe80-71d2-11eb-8b0d-484eaa8374b0.png">

Going to close this, feel free to reopen if you find it isn't fixed
