### ISSUE TITLE
Add ApplicationSets to the ArgoCD stack 

### ISSUE THREAD

**Issue by sbose78** [argoproj/argo-cd#5104]
Greetings ArgoCD community 👋 

@jgwest @alexmt @jessesuen and I would like to propose the move of ApplicationSets into the ArgoCD stack. 

We will discuss details in the next ArgoCD community meeting, but in brief, this would be an optional "preview" feature to begin with 🎥 . 

Ref:
https://github.com/argoproj-labs/applicationset/issues/86

* What are your thoughts on the same ? 

* What are some of the use cases you would like to handle with ApplicationSets?

**Comment by aelbarkani** [comment]
Awesome !

My use cases:
- As a K8S administrator, I would like to configure my K8S fleet with the same components (Operators, helm charts, quotas, limits,etc) automatically.
- As an application owner, I would like to deploy easily my application in several clusters for high availability.

**Comment by wreed4** [comment]
When this feature is complete, will the `argocd` cli have the ability to label clusters??? Without this feature, a person or system must have kubectl access to the cluster ArgoCD is installed on in order to use ApplicationSets.  Ideally this functionality would be provided through the ArgoCD API.

**Comment by sbose78** [comment]
That's a great suggestion, would you want to provide a more detailed
enhance proposal?

We've been working towards getting ApplicationSets stable enough for use so
far, once done we'll continue adding enhancements to the project as a whole
l.

**Comment by alexmt** [comment]
> When this feature is complete, will the `argocd` cli have the ability to label clusters??? Without this feature, a person or system must have kubectl access to the cluster ArgoCD is installed on in order to use ApplicationSets. Ideally this functionality would be provided through the ArgoCD API.

@wreed4 The ability to label/annotate cluster is available in master. Will be released as part of v2.2

**Comment by jannfis** [comment]
@sbose78  Can this be closed with #8148 merged?

**Comment by alexmt** [comment]
Closing. @sbose78 please ping me if you want to keep it open for some reason.

**Comment by sbose78** [comment]
👍 Thanks!
