### ISSUE TITLE
Translate Unknown errors into proper gRPC codes

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#512]
After enabling log analysis, we noticed a lot of errors are getting categorized as grpc code Unknown. Need to translate these to proper codes. Some that we found:

These are configuration issues:
`ks show` failed
git ls-remote origin 'HEAD' failed: remote: Repository not found
git remote set-head origin -a' failed: fatal: unable to access '<REPONAME>'

**Comment by merenbach** [comment]
@jessesuen Is this essentially an augmentation of `util/grpc/error.go`, as in, no code paths outside that are expected to need to change?
