### ISSUE TITLE
Webhook never fails

### ISSUE THREAD

**Issue by mnacharov** [argoproj/argo-cd#5124]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x]  I've included steps to reproduce the bug.
* [x]  I've pasted the output of `argocd version`.

**Describe the bug**

There is no error when something goes wrong in Webhook usage. It always returns http 200 status

**To Reproduce**

Specify http scheme in webhook settings in git repository provider. This will causes [this](https://github.com/argoproj/argo-cd/blob/v1.8.1/util/webhook/webhook.go#L348-L351) error message in logs:

`level=info msg="Webhook processing failed: invalid HTTP Method"`

But HTTP status of response will remain the same - HTTP 200 OK

**Expected behavior**

Return HTTP 500 with an error message

**Version**

```shell
argocd: v1.8.1+c2547dc
  BuildDate: 2020-12-10T03:00:31Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Logs**

```
level=info msg="Webhook processing failed: invalid HTTP Method"
```

**Comment by jessesuen** [comment]
@mnacharov would you like to submit a PR to fix this?

**Comment by mnacharov** [comment]
Yep! I will submit this week
