### ISSUE TITLE
Export ArgoCD stats as prometheus style metrics

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#513]
To better understand an argocd's instance usage (e.g. how frequent deploys/syncs are happening, API requests, how many apps, health states, users, etc...), ArgoCD should export prometheus style metrics  to be scraped so it can be used in higher level dashboards.

**Comment by jessesuen** [comment]
Can use this as a reference implementation: 
https://github.com/argoproj/argo/pull/935

**Comment by jessesuen** [comment]
First implementation can be limited to health statuses

**Comment by merenbach** [comment]
Blocked by `undefined: proto.InternalMessageInfo` errors when running `make server` and/or `make codegen` whenever Prometheus client libs are imported.  Seems to also occur when switching to `master` branch and updating either `google.golang.org/grpc` or `github.com/grpc-ecosystem/grpc-gateway`.
