### ISSUE TITLE
Token lost when renaming a cluster

### ISSUE THREAD

**Issue by debfx** [argoproj/argo-cd#5135]
**Describe the bug**

When renaming a cluster, Argo CD looses the bearer token and thus is unable to connect to the cluster anymore.

**To Reproduce**

* Dump the argocd config of the cluster: `kubectl -n argocd get secrets cluster-XXX-XXX -o yaml` 
* Change the name of the cluster in the Argo CD web interface.
* Notice that the cache info on the cluster page is blank and apps from that cluster turn into the state unknown.
* Check the config of the cluster again: `kubectl -n argocd get secrets cluster-XXX-XXX -o yaml` 
* Notice that the config is now `{"tlsClientConfig":{"insecure":false,"caData":"..."}}` instead of `{"bearerToken":"...","tlsClientConfig":{"insecure":false,"caData":"..."}}`. The bearerToken key disappeared.

**Expected behavior**

Connection to cluster still works after renaming.

**Version**

```shell
argocd: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:57:57Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Logs**

```
time="2020-12-28T09:20:58Z" level=error msg="finished unary call with code Unknown" error="ComparisonError: forbidden: User \"system:anonymous\" cannot get path \"/apis/apps/v1\"" grpc.code=Unknown grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2020-12-28T09:20:58Z" grpc.time_ms=1.832 span.kind=server system=grpc
```

**Comment by jessesuen** [comment]
I think the problem is that because we never return sensitive information from our API, a cluster update operation drops the sensitive information on the floor as part of the update.

It could be that the cluster update doesn't properly refetch the cluster before saving it, although I don't see any obvious problems from the code:
https://github.com/argoproj/argo-cd/blob/master/server/cluster/cluster.go#L161-L201

**Comment by kshamajain99** [comment]
Taking a look

**Comment by alexmt** [comment]
@kshamajain99 ClusterUpdateRequest message has `updatedFields` field. 
https://github.com/argoproj/argo-cd/blob/98bec61d6154a1baac54812e5816c0d4bbc79c05/server/cluster/cluster.proto#L30

That is a list of fields that should be updated 

https://github.com/argoproj/argo-cd/blob/98bec61d6154a1baac54812e5816c0d4bbc79c05/server/cluster/cluster.go#L145-L155


CLI can use it to specify which fields should be updated.

**Comment by kshamajain99** [comment]
@alexmt There isn't any CLI for cluster update. I have fixed the UI bug in PR https://github.com/argoproj/argo-cd/pull/5220.
