### ISSUE TITLE
Filters should include orphaned object types when showing orphaned objects

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5149]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

It's possible to enable a checkbox to show orphaned resources (this isn't a great name for them, it's more accurate to describe them as unmanaged, unrecognized, or unexpected, but that would be part of #5147).
Once one does that, one can click on `1 Warnings` to be told `Application has 184 orphaned resources`.

**To Reproduce**

1. Enable orphaned resources (see #5147 for steps)
2. Visit an application
3. Click `SHOW ORPHANED`
4. See lots of resources
5. Click the filters thing to try to filter the orphaned resources

**Expected behavior**

1. Showing `orphaned` resources should adjust the filters to include the types of orphaned resources
2. Selecting a resource kind in filters should filter the display to resources that match the filter -- as part of the application or orphaned

**Screenshots**

![OrphanedResourceWarning - Application has 184 orphaned resources](https://user-images.githubusercontent.com/2119212/103310914-d9c7fc80-49e6-11eb-8571-d435455841a7.png)
![SHOW ORPHANED](https://user-images.githubusercontent.com/2119212/103311018-34615880-49e7-11eb-96ae-b34465f97f25.png)
![Incomplete list of kinds in filters](https://user-images.githubusercontent.com/2119212/103310837-9a99ab80-49e6-11eb-80fc-5cff2536c350.png)

**Version**

```shell
{
    "Version": "v1.8.1+c2547dc",
    "BuildDate": "2020-12-10T02:59:21Z",
    "GitCommit": "c2547dca95437fdbb4d1e984b0592e6b9110d37f",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
Agree this is a bug. We should get the filter content from all objects not just in the applications tree.

**Comment by saumeya** [comment]
Hi @jsoref, looks like this is not a problem in the latest code, can we close this? I will try to take a look at 5147
