### ISSUE TITLE
Resource type completion filter should be case insensitive

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5152]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Typing `sec` results in no matches. It should match at least `Secret`

**To Reproduce**

1. Visit http://argocd/settings/projects/default
2. Enable the orphaned stuff
3. Click Add
4. Type `se` into the `Kind` field

**Expected behavior**

It should match `Secret` and other things -- because it should be case insensitive

**Screenshots**

![no filter](https://user-images.githubusercontent.com/2119212/103313186-48a85400-49ed-11eb-9dfd-0743af5c7c3e.png)
![filter for se](https://user-images.githubusercontent.com/2119212/103313300-ad63ae80-49ed-11eb-8859-db30a1dd1fff.png)

**Version**

```shell
{
    "Version": "v1.8.1+c2547dc",
    "BuildDate": "2020-12-10T02:59:21Z",
    "GitCommit": "c2547dca95437fdbb4d1e984b0592e6b9110d37f",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ishitasequeira** [comment]
Looking into this issue

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-cd/pull/5400 . Thank you @ishitasequeira !
