### ISSUE TITLE
Count field should be wide enough to fill `count`

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5176]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I gave a pod `32657` failures, which is the same number of characters as `Count`, but it's truncated as `326..`.

**To Reproduce**

1. Set up a pod that's broken and triggers the backoff counter.
2. Visit the pod in argo
3. Select the events tab

**Expected behavior**

Since `count` is 5 characters, it'd be nice if the field also supported 5 character long values.

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/103597570-9251dc80-4ece-11eb-933d-ed039df460c9.png)

**Version**

```shell
{
    "Version": "v1.8.1+c2547dc",
    "BuildDate": "2020-12-10T02:59:21Z",
    "GitCommit": "c2547dca95437fdbb4d1e984b0592e6b9110d37f",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

**Comment by reginapizza** [comment]
Could someone please assign me to this issue?  Thank you :)

**Comment by reginapizza** [comment]
Tried to look into this and worked with Josh yesterday and couldn't reproduce this bug. If it comes up again and I have a way to reproduce it I would be happy to work on it again.

**Comment by saumeya** [comment]
I'm interested to work on this issue.

**Comment by saumeya** [comment]
@jsoref @jessesuen 
This usually will happen when the browser window is not in full screen. 
![original5176](https://user-images.githubusercontent.com/17771352/123988031-4a2af700-d9e5-11eb-8463-4620e19dab44.png)

One possible solution is to increase the size of the **Count** column but for doing that one other column would have to be reduced in size (change from small-1 to small-2, see code).  [Code Line](https://github.com/argoproj/argo-cd/blob/4a4b43f1d204236d1c9392f6076b292378bfe8a3/ui/src/app/shared/components/events-list/events-list.tsx#L19)

One other solution as suggested by @reginapizza is to add a tooltip on the count value.

**Comment by jsoref** [comment]
@saumeya: I'd endorse both options. Make it able to handle at 6 characters minimum and add a tooltip so if it still gets truncated people can see.

It sounds like you're able to reproduce it, so please go ahead and make a PR. Thanks!

**Comment by saumeya** [comment]
#6611

**Comment by saumeya** [comment]
#6611

**Comment by reginapizza** [comment]
@jsoref @saumeya should this issue be closed now?

**Comment by saumeya** [comment]
> @jsoref @saumeya should this issue be closed now?

yes it can be closed
