### ISSUE TITLE
Support single file as source

### ISSUE THREAD

**Issue by yujunz** [argoproj/argo-cd#5197]
# Summary

Support create application from a single file.

# Motivation

When create application from a single file, it prompts the following error

```
Unable to create application: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = manifests/gerrit/service-ssh.yaml: app path is not a directory
```

It is helpful for fine control of resources while creating directory for each of them seems overkilled sometimes.

# Proposal

Support create application from a single file just like `kubectl apply -f`

**Comment by sbose78** [comment]
Thank you @yujunz for the report.
To be clear, you would have to use a directory with a single file in it, as an alternative, given that pointing to single files is not supported ?

**Comment by alexmt** [comment]
FYI. In v1.9 directory source has `include` parameter which is a glob filter. So you can have directory with multiple files and use `include` to specify required file:

```
source:
  directory:
    include: `service-ssh.yaml`
```

**Comment by jessesuen** [comment]
I think @alexmt suggestion is the proper way to do this pattern so will close this as the solution.

**Comment by yujunz** [comment]
Nice

But I don't see it under UI at the moment.

<img width="546" alt="Screen Shot 2021-01-07 at 4 28 38 PM" src="https://user-images.githubusercontent.com/6813397/103869558-6ec4a700-5105-11eb-91c6-ef9a7c2add81.png">

My version was built from a recent master. Is it too new or just not available in UI yet? @alexmt
