### ISSUE TITLE
Upgrade to 1.8.1 won't work when argocd managing itself

### ISSUE THREAD

**Issue by RomainBelorgey** [argoproj/argo-cd#5210]
I couldn't find any related issue and reporting this if it could help.

Thanks in advance and keep the good work :+1: 

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Argocd is managing itself on my environment.
Following https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#manage-argo-cd-using-argo-cd

The goal was to upgrade from 1.7.10 to 1.8.1.

`kustomization.yaml` file:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v1.8.1
  - https://github.com/argoproj-labs/argocd-notifications/manifests/controller?ref=v0.7.0

resources:
  #Projects configuration
  - projects.yaml
  #Creating all namespaces
  - namespaces.yaml
  #Apps configuration
  # apps/<namespace>.yaml

patchesStrategicMerge:
  #Shared changes
  - ../shared/statefulsets/argocd-application-controller.yaml
  #Specific changes
  - configmaps/argocd-notifications-cm.yaml
```

The only change to make the upgrade was to put `v1.8.1` and to change to statefulSet instead of the deployment for `argocd-application-controller` (to not required gpg).

Applying the changes will remove the deployment `argocd-application-controller` but it won't finish the upgrade. On the UI, I can still see the deployment waiting to sync. Is that because it is now a statefulSet and not a deployment ?

As the deployment was not visible, I couldn't see if removing it will help (from https://argoproj.github.io/argo-cd/operator-manual/upgrading/1.7-1.8/).

To unblock the upgrade, I need to manually run the command:
```
kustomize build <dir> --enable_kyaml=false --load_restrictor none | kubectl apply -f -
```

(`--enable_kyaml=false` because it looks like on my version of kustomize it is giving me a panic error)

**To Reproduce**

Just trying an upgrade.
Could be visible on our 2 environments.

**Expected behavior**

Not having to run manually the `kustomize` command.

**Version**

From `v1.7.10` to `v1.8.1`

**Comment by jessesuen** [comment]
What you described is expected. This was mentioned in release notes, but probably not descriptive enough. What happened was it deleted the application controller before it had a chance to deploy the statefulset and your install was stuck. 

For auto-synced + auto-prune managed argo-cd instances, this would be a problem. 

Note that this use case is now solved via the PruneLast feature: https://github.com/argoproj/argo-cd/issues/5080

Aside from improving the documentation, there isn't any fix to be made to handle v1.7 -> v1.8 upgrades.

**Comment by RomainBelorgey** [comment]
Thanks, I was thinking that it was this behavior (the deployment killed before creating the new statefulset) :+1: 

I will see to put this in the configuration of the `argocd` and make a PR for the documentation ;)

**Comment by RomainBelorgey** [comment]
Just created https://github.com/argoproj/argo-cd/pull/5222, hope it can help :+1:
