### ISSUE TITLE
Icons aren't properly aligned

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5211]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

Trigger progressing (easily done w/ something that triggers an out of sync)

**Expected behavior**

Both circles should have the same tops/bottoms

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/103931378-3796cb80-50ee-11eb-9832-13329ac46782.png)

**Version**

```shell
{
    "Version": "v1.9.0+b081969",
    "BuildDate": "2021-01-06T01:43:28Z",
    "GitCommit": "b0819691d339c5d00e314e6f34fdd530211e042d",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by rbreeze** [comment]
This isn't an issue with alignment but rather the animation. It's a known issue with FontAwesome that spinning icons might "wobble":

https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons

I've tried eliminating this by wrapping the icons in a `display: inline-block` div, but it does nothing. The only solution would be to wrap the icons in a `display: block` div, but A) this isn't guaranteed to work and B) this would require a *lot* of modifications elsewhere, i.e. everywhere one of these icons exists.

**Comment by jsoref** [comment]
😞
