### ISSUE TITLE
Allow background delete option when deleting apps and resources

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#5216]
# Summary

Currently we only allow foreground deletion of objects, but due to Kubernetes GC buggy behavior about deletion, foreground deletion can block indefinitely. The only workaround in Argo CD is a force deletion which is more abrasive approach than performing a background deletion. We should expose an option in UI, CLI, API to perform background deletion of resources and applications.

**Comment by chetan-rns** [comment]
Hi @jessesuen, Is this solved by setting the `PropagationPolicy` as Background while deleting? Could you please assign me this issue?

**Comment by rbreeze** [comment]
@chetan-rns would you still like to work on this?

**Comment by chetan-rns** [comment]
Thanks @rbreeze I'm looking into it. Could you please assign me this issue?

**Comment by rbreeze** [comment]
Will do!
