### ISSUE TITLE
Received a non-integer value when creating project token

### ISSUE THREAD

**Issue by samkeet** [argoproj/argo-cd#5217]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using the project token API to create a new token for a role, the JWT token contains non integer values for issuedAt and expiresAt timestamp values. 

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

1. Use the `POST {argocd-server}/api/v1/projects/{name}/{role}` to create a new project token.
2. Use https://github.com/dgrijalva/jwt-go to parse the JWT token from the response

It should throw an error 
```
json cannot unmarshal number 2414241.2313 into Go struct field StandardClaims.exp of type int64
``` 

**Expected behavior**

JWT token returned as a response from creating ArgoCD project token, should not contain non-integer values for expiresTime and issuedAt timestamps

**Version**

```shell
Paste the output from `argocd version` here.
```

Internal Version - 1.8.1+986rc742

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/5228
