### ISSUE TITLE
ArgoCD about Vault-injector roadmap

### ISSUE THREAD

**Issue by shivakumar12** [argoproj/argo-cd#5224]
# Summary
We have requirement to store all the argo used github secrets into vault. As of now we do not have inbuilt solution to  directory inject the vault secrets into kuberntes pods from argo. Either we have to go with external secret store i,e godaddy or vault operators but these are not approved pattern in our environments.

What change you think needs making.
ArgoCD in build Vault-injector to get the secrets from vault to inside k8s pods
# Motivation

We have requirement to store all the argo used github secrets into vault. As of now we do not have inbuilt solution to  directory inject the vault secrets into kuberntes pods from argo. Either we have to go with external secret store i,e godaddy or vault operators but these are not approved pattern in our environments.

# Proposal

How do you think this should be implemented?
It can be implemented via godaddy or vault operators.

**Comment by jessesuen** [comment]
Are you proposing a way to not use Kubernetes Secrets *at all*? 

Note that this would be very difficult because we also represent clusters and repos as Kubernetes Secrets, not just argo cd configuration.

**Comment by shivakumar12** [comment]
No, We are looking a inbuilt solution to integrate with vault & get the secrets to k8s cluster.
Is this solution already in-place or any roadmap to provide the solution or its not possible?

**Comment by stefanhenseler** [comment]
@shivakumar12 If you use Kustomize,  I think you should be able to use one of the Kustomize secret generator plugins to get the secrets from Vault during syncs:  

- https://github.com/kubernetes-sigs/kustomize/blob/7971ac1/examples/kvSourceGoPlugin.md
- https://github.com/danielsel/kustomize-plugin-vault 
- https://github.com/RealGeeks/kustomize-kvsource-vault

I think you can bundle these plugins like this: https://argoproj.github.io/argo-cd/operator-manual/custom_tools/

**Comment by adamjohnson01** [comment]
You could also try https://github.com/IBM/argocd-vault-plugin

**Comment by blakepettersson** [comment]
The likelihood of vault-injector or any other secrets manager being integrated directly into Argo CD is pretty low as of this time, so closing for now.
