### ISSUE TITLE
Pods groups grows vertically on Pods view

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#5229]
If pods group on the pod view has too many pods then group height increase instead of showing scroll bar

![image](https://user-images.githubusercontent.com/426437/104240899-a8e9bd80-5411-11eb-8d8b-3a7789e69c39.png)

**Comment by alexmt** [comment]
@rbreeze , can you check please?

**Comment by jessesuen** [comment]
Also let's combine os/arch into one line for compactness
