### ISSUE TITLE
Filters floats away from input field

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5236]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The filters box ends up floating divorced from the text field

**To Reproduce**

1. visit https://cd.apps.argoproj.io/applications
2. adjust the size of the window and the position of the namespaces box as shown
3. type `cert`
4. watch as the completions ends up disassociated from the text field -- specifically, its top is anchored to where it would have been if the box had all of its items to reach the top of the text field

**Expected behavior**

the box should be anchored to either just above or just below the text field

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/104365380-ee77ba80-54e5-11eb-83a0-5183f5006f25.png)

**Version**

```shell
{
    "Version": "v1.9.0+64e1c38",
    "BuildDate": "2021-01-11T22:13:14Z",
    "GitCommit": "64e1c3825a421892c7297777e960af48f8139c50",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ciiay** [comment]
@jsoref I tried to reproduce this issue and the I couldn't see the same as described. Could you confirm if this still exists? Thank you!

**Comment by jsoref** [comment]
Can't seem to reproduce, the new design looks like it's protected from this, thanks for checking.
