### ISSUE TITLE
Include ApplicationSet in argocd-util export scope

### ISSUE THREAD

**Issue by jbaskeen** [argoproj/argo-cd#5240]
# Summary

Currently, `argocd-util export` does not export ApplicationSet. This is likely obvious since ApplicationSet is not completely released/implemented. However, for those of those that are using it, it could be a valuable addition.

# Motivation

Recently, our team faced an outage of our ArgoCD instance which currently leverages ApplicationSet for our ArgoCD use case. Although we had a backup taken 24 hours before the incident, the backup was only partially helpful as a majority of our applications are driven via ApplicationSet. After restoring the backup we learned that ApplicationSet was not in scope of the process as we made the assumption that anything relevant within the argocd namespace would be included in the backup process.

# Proposal

If any ApplicationSet is present, include it/them in the backup. If not, don't.

**Comment by jessesuen** [comment]
This makes perfect sense. Note that to implement this, until/unless we import application-set pkg definitions, we'll need to rely on the dynamic client to export (which may be the better approach overall)

**Comment by jessesuen** [comment]
I'll loosely target this for v1.9 but may get dropped.

**Comment by chetan-rns** [comment]
Hi @jessesuen @alexmt,  I would like to work on this. Could you please assign it to me?
