### ISSUE TITLE
Drop down doesn't move when window resizes

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5242]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The drop down box picks a point in space and doesn't shift when the corresponding widget moves

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/argo-cd
2. Narrow the window to ~50% of the screen
3. Click the filter drop down widget
4. Grow the window until the box is visibly detached from the button

**Expected behavior**

The box should remain connected to the button

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/104499520-3c0a2b00-55ab-11eb-9bdb-b3f430dd6242.png)

**Version**

```shell
{
    "Version": "v1.9.0+64e1c38",
    "BuildDate": "2021-01-11T22:13:14Z",
    "GitCommit": "64e1c3825a421892c7297777e960af48f8139c50",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by saumeya** [comment]
Closing because filter menu has moved to sidebar in current version.
