### ISSUE TITLE
remove ksonnet from argocd image

### ISSUE THREAD

**Issue by jkleinlercher** [argoproj/argo-cd#5256]
# Summary

ksonnet is not actively maintained anymore and security vulnerability scans find CVE in ksonnet binaries. Also argocd doesn't support ksonnet anymore: https://argoproj.github.io/argo-cd/user-guide/ksonnet/
I think it is time to remove ksonnet from the argocd image and 

# Motivation

Without ksonnet the argocd image gets more secure

# Proposal

remove ksonnet from Dockerfile and documentation

**Comment by jessesuen** [comment]
Added to v2.4. it's more than removing image. we should also remove backend & front-end logic

**Comment by gdsoumya** [comment]
@jessesuen have raise a PR #8479 for the changes, it removes ksonnet from docker as well as other places in argo-cd code base. Besides changes in argo-cd repo I think we also need to remove ksonnet from the applicationset repo https://github.com/argoproj/applicationset/blob/5787c33af6768d0ed085e11f5f1ece57a4c03a50/manifests/crds/argoproj.io_applicationsets.yaml#L224

**Comment by gdsoumya** [comment]
@chetan-rns we might want to keep this open because ksonnet is still present in the repo manifests because the appset controller still has it. We can create another issue in the appset controller repo and once the changes there are complete, regenerate the manifests in the repo and then close this.

**Comment by blast-hardcheese** [comment]
FYI ksonnet is still linked from [argocd's RTD docs](https://argo-cd.readthedocs.io/en/stable/), which could be misleading and reflect poorly on argo, considering the ksonnet SSL certificate has lapsed.
