### ISSUE TITLE
default schedule options are cropped

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5261]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

1. https://cd.apps.argoproj.io/settings/projects/default?newWindow=true

**Expected behavior**

text shouldn't be cropped.

this can be achieved by rewording or increasing column widths.
`hourly`, `daily`, `monthly`, `daily`

the bottom row should be cropped halfway, not at ~10% if possible

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/104831787-ed35ed00-5859-11eb-9d84-d0fdb0380e26.png)

**Version**

```shell
{
    "Version": "v1.9.0+e26ad30",
    "BuildDate": "2021-01-15T22:56:37Z",
    "GitCommit": "e26ad305b41f706ec23d10fca64d4466d39c7ed2",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ciiay** [comment]
@jsoref It looks like the Schedule period label background width has been increased. We only need to fix the text being cutting off on the bottom row in this issue. Could you confirm that and update this issue? Thank you!

<img width="904" alt="Screen Shot 2021-08-16 at 3 58 52 PM" src="https://user-images.githubusercontent.com/26255262/129622374-212aa07d-1de8-4d01-8026-42b58db04733.png">

**Comment by jsoref** [comment]
Still happens for a somewhat narrow window:
![image](https://user-images.githubusercontent.com/2119212/129629994-08017eea-12a1-47a3-a1a7-c330c3a314bb.png)

**Comment by ciiay** [comment]
I'd love to work on this.
