### ISSUE TITLE
Forms UX

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5262]
# Summary

Forms should behave more or less the same way across the product

# Motivation

Inconsistency and surprise are bad

# Survey

https://cd.apps.argoproj.io/settings/projects?add=true
![image](https://user-images.githubusercontent.com/2119212/104832027-02ac1680-585c-11eb-9b81-f0b4db96bebb.png)
![image](https://user-images.githubusercontent.com/2119212/104832033-0cce1500-585c-11eb-9567-1ee5aa18f5f7.png)

https://cd.apps.argoproj.io/settings/repos?addHTTPSRepo=true
![image](https://user-images.githubusercontent.com/2119212/104832172-389dca80-585d-11eb-8118-26a644c7789b.png)
![image](https://user-images.githubusercontent.com/2119212/104832175-3f2c4200-585d-11eb-9c05-28b162fdef32.png)

https://cd.apps.argoproj.io/settings/gpgkeys?addGnuPGPublicKey=true
![image](https://user-images.githubusercontent.com/2119212/104832051-296a4d00-585c-11eb-827d-ef4011e98957.png)
![image](https://user-images.githubusercontent.com/2119212/104832056-2ec79780-585c-11eb-9f66-18ac082b93a2.png)

https://cd.apps.argoproj.io/settings/certs?addTLSCert=true
![image](https://user-images.githubusercontent.com/2119212/104832061-3d15b380-585c-11eb-8ddd-52e57a33e14e.png)
![image](https://user-images.githubusercontent.com/2119212/104832067-43a42b00-585c-11eb-99f6-af5f8706ea7c.png)

https://cd.apps.argoproj.io/settings/certs?addSSHKnownHosts=true
![image](https://user-images.githubusercontent.com/2119212/104832157-13a95780-585d-11eb-9f83-3fdf2a8ed0a5.png)
![image](https://user-images.githubusercontent.com/2119212/104832160-1a37cf00-585d-11eb-958f-74fb1208a1ab.png)

https://cd.apps.argoproj.io/settings/repos?addSSHRepo=true
![image](https://user-images.githubusercontent.com/2119212/104832074-50288380-585c-11eb-8861-55eb2302d7bc.png)
![image](https://user-images.githubusercontent.com/2119212/104832080-56b6fb00-585c-11eb-9e31-3347964011bf.png)

https://cd.apps.argoproj.io/settings/projects/default?newRole=true
![image](https://user-images.githubusercontent.com/2119212/104832218-9e8a5200-585d-11eb-856f-2d3d81dba3fa.png)
![image](https://user-images.githubusercontent.com/2119212/104832224-a518c980-585d-11eb-83b3-b26abfde9738.png)

https://cd.apps.argoproj.io/settings/projects/default?newWindow=true
![image](https://user-images.githubusercontent.com/2119212/104832226-b06bf500-585d-11eb-8f44-c975d4ea1255.png)
(this form doesn't appear to have any mandatory fields? -- clicking create just triggers an error)
![image](https://user-images.githubusercontent.com/2119212/104832241-e6a97480-585d-11eb-88e6-be78ac090dc7.png)
oddly the kind field gets a dropdown indicator later...

# Proposal

* consistently use white background (followup to #4971)
* consistently place create/cancel buttons (below see that some are LTR and some RTL)
* clearly indicate mandatory fields so users don't have to guess
* help indicators shouldn't wrap away from their text if it's possible to make the field wider (see `DAY OF THE MONTH`)

**Comment by ciiay** [comment]
Hi @jsoref , the PR for this issue has been merged, could you check if this is ready for closing? Thanks!

**Comment by jsoref** [comment]
LGTM, thanks.
