### ISSUE TITLE
minor cleanup for app cli help

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5266]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

https://github.com/argoproj/argo-cd/blob/e26ad305b41f706ec23d10fca64d4466d39c7ed2/cmd/util/app.go#L87
> Add or remove a sync options

should be:

> Add or remove a sync option

**To Reproduce**

Not actually certain. This is from reading the source code.

**Expected behavior**

Help should be grammatically correct.

**Screenshots**

**Version**

e26ad305b41f706ec23d10fca64d4466d39c7ed2

**Logs**

```
Paste any relevant application logs here.
```

**Notes**
Someone picking up this task should probably run all similar text from this file (and maybe its siblings) through app.grammarly.com (or their own personal grammar parser) instead of just fixing this one instance.

**Comment by reginapizza** [comment]
@jsoref could you please close this? Not sure why  my PR for it wouldn't close it automatically. Possibly just worded it wrong and github didn't pick it up
