### ISSUE TITLE
Events list should be sorted by something sane (e.g. last occurred)

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5272]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The list of events shifts periodically even though the counts and times are not

**To Reproduce**

Open events tab for an argocd-redis which appears to be in a crash loop

**Expected behavior**

Lists should be stable unless the content is changing meaningfully.

It's possible that the underlying API produces chaotic results, but for a monitoring tool, this is really unhelpful to end users trying to investigate problems. Updates in display should indicate updates in events, not in someone's random hashing of a list before returning info to a caller.

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/104977457-93563400-59cd-11eb-81ce-68342698ffa5.png)
![image](https://user-images.githubusercontent.com/2119212/104977476-a2d57d00-59cd-11eb-9be1-3af2fb213727.png)

**Version**

```shell
{
    "Version": "v1.9.0+b081969",
    "BuildDate": "2021-01-06T01:43:28Z",
    "GitCommit": "b0819691d339c5d00e314e6f34fdd530211e042d",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
```

**Comment by jessesuen** [comment]
It was intended to be sorted, so this is a UI bug

**Comment by rbreeze** [comment]
Having a hard time reproducing this. How did you get your `argocd-redis` into a crash loop?

**Comment by jsoref** [comment]
Dunno. I definitely wasn't trying to...
