### ISSUE TITLE
Minor cleanup for app errors

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5273]
https://github.com/argoproj/argo-cd/blob/6535d1ac340d91c5fbdd4f121b9e9cf9b65ce2ad/controller/clusterinfoupdater.go#L124

> "Cluster has no application and not being monitored." 

should be closer to:

> "Cluster has no applications and is not being monitored."

**Comment by OmerKahani** [comment]
Should this issue be closed (The PR was merged)?
