### ISSUE TITLE
Consistent commit message rendering

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#5278]
**Describe the bug**

The issue is a follow-up for https://github.com/argoproj/argo-cd/pull/5241 . Proposing several additional improvements:

* There are two commit messages on app details page: "compared to" and "synced to" . The popup should be shown for both. 
* Right now popup shows only the first line on the commit message because API truncates it. https://github.com/argoproj/argo-cd/blob/a12f805bb27c443809f32ccd9656d49c60626d6a/reposerver/repository/repository.go#L1259 

Instead, API should return the first message and UI should truncate it on sync panel and show full message in the popup.

* Couple popup panel nitpicks: space is missing between Sync status and dash ( change `Sync OK- Succeeded` to `Sync OK - Succeeded`); Tooltip is no longer required since panel is supposed to show all information:

![image](https://user-images.githubusercontent.com/426437/105089420-f5587d00-5a51-11eb-8c79-390dc9112159.png)

* Refreshing label is not visible anymore ( since panel hight increased a littlebit )
![image](https://user-images.githubusercontent.com/426437/105225663-c1de2700-5b13-11eb-991a-f89a48f37825.png)

**Comment by jessesuen** [comment]
@reginapizza would you mind taking this?

**Comment by reginapizza** [comment]
@jessesuen sure!

**Comment by reginapizza** [comment]
Hello, I had some questions that I was hoping I could get answered

> There are two commit messages on app details page: "compared to" and "synced to" . The popup should be shown for both.

Do you mean these two boxes? As in the left box is the "compared to" and right is "synced to"? 
![example](https://user-images.githubusercontent.com/50851526/105511104-8a02eb00-5c9d-11eb-9de7-ca1913b2fd00.png)

If this is right, then do you expect the "compared to" to have the same info popup for it's own content (expanded), or should the info popup show all of the information for both of them and be accessible from both boxes?

**Comment by rbreeze** [comment]
Those are the right two boxes. Alex can correct me if I'm wrong but I believe he's hoping for the former - each of those boxes has their own expand button that shows just their own content, expanded.

**Comment by reginapizza** [comment]
hey @alexmt, just wanted to confirm if you need anything else from your original request? I reviewed your PR and it looks like it fits all the user needs, albeit just in a different way (looks even better your way actually). Please let me know so I'll know whether or not to work on this any further, thanks

**Comment by alexmt** [comment]
Ops, sorry @reginapizza . I did not realize you are working on it already. The https://github.com/argoproj/argo-cd/pull/5313 implements all required changes. Thank you for checking
