### ISSUE TITLE
Failed to watch *v1.Node in argocd-server

### ISSUE THREAD

**Issue by yujunz** [argoproj/argo-cd#5281]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Errors in `argocd-server`: `Failed to watch *v1.Node:...`

**To Reproduce**

Build image from master
Override image version and deploy from https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml

**Expected behavior**

No errors

**Screenshots**

N/A

**Version**

```shell
argocd: v1.8.2+94017f2.dirty
  BuildDate: 2021-01-10T06:50:14Z
  GitCommit: 94017f2c8d97588d4aa2213713a71d51005ed62d
  GitTreeState: dirty
  GoVersion: go1.15.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.9.0+7613d9a
  BuildDate: 2021-01-11T03:10:33Z
  GitCommit: 7613d9a85295e15fcbaf0b5f6ba9ed69a74a0919
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.7 2020-11-11T23:14:14Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Logs**

```
 argocd-server-698b89c784-w66gm:E0120 03:34:00.865934       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1.Node: failed to l
 ist *v1.Node: nodes is forbidden: User "system:serviceaccount:argocd:argocd-server" cannot list resource "nodes" in API group "" at the cluster scope
```

**Comment by alexmt** [comment]
Hello @yujunz ,

I'm pretty sure the issue was fixed by https://github.com/argoproj/argo-cd/pull/5208 . API server was trying to load nodes data from the control plain cluster. Now information about nodes is loaded by controller from the target clusters.

**Comment by yujunz** [comment]
Fixed after merging latest master.
