### ISSUE TITLE
Getting Error when updating password

### ISSUE THREAD

**Issue by anais-codefresh** [argoproj/argo-cd#5286]
I have set up argocd on my cluster like specified in the getting started guide.

When I want to update my password I receive the following error message 
> FATA[0011] json: cannot unmarshal number 1611225061.529309 into Go struct field StandardClaims.iat of type int64 

However, the changed password works afterwards -- so it is correctly updating my password as it seems.
![Screenshot](https://user-images.githubusercontent.com/72611059/105339223-bacf1b80-5bdc-11eb-96e0-1f1430faa16d.png)

**Comment by jannfis** [comment]
Hi, this is due to a security upgrade of our JWT library that went into 1.8.2. It has been fixed by https://github.com/argoproj/argo-cd/pull/5228 already, but is not yet released.

**Comment by jessesuen** [comment]
We plan on releasing v1.8.3 today or tomorrow which contains this fix.

**Comment by anais-codefresh** [comment]
Awesome! Thank you for the quick reply. Going to close this issue
