### ISSUE TITLE
Add finalizer from argocd app CLI/API

### ISSUE THREAD

**Issue by james-callahan** [argoproj/argo-cd#5305]
# Summary

When I create an application with `argocd app create` there is no way to add the finalizer `resources-finalizer.argocd.argoproj.io`

# Motivation

I give users the ability to create applications that don't have the ability to `edit` resources in the cluster. I'd like them to be able to request finalization.

# Proposal

New `--cascade-on-delete=true` command line flag for `argocd app create`.

**Comment by jessesuen** [comment]
@james-callahan how are applications being deleted? If they are performing delete through the API server, this is always an API decision, so even if `--cascade-on-delete=true` was set upon create, the delete API will honor whatever comes as part of the delete request.

**Comment by james-callahan** [comment]
> @james-callahan how are applications being deleted?

We are deleting them with `kubectl delete`.
At the moment we follow the guide to patch just before deletion, but the decision on whether it should be deleted or not should IMO be the choice of the application creator/manager; not the thing that deletes it.

**Comment by rishabh625** [comment]
I would like to work on this

**Comment by rishabh625** [comment]
Finalizer addition should be part of app creation and  not only to be patched on deletion, should work as defined [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/) 

But I am confused where to implement this should we set it in api when a flag is passed by cli/ui or cli/ui to prepolulate finalizer and send as an Request to API

**Comment by rishabh625** [comment]
@jannfis : Currently if appication is created via argocd ui/cli , but deleted using kubectl delete command , application resources still reside and there is no option to do cascading deletion unless argocd ui/cli is used , but if we give option for cascading deletion while creating app, deleting the app will honor , how it to be deleted based on how app was created


But what would be the correct place to do changes? in API or in CLI/UI to add finalizer ```resources-finalizer.argocd.argoproj.io```

**Comment by jannfis** [comment]
@rishabh625 When the Application resource is created by Argo CD, it's done by the `argocd-server`'s Application API here: https://github.com/argoproj/argo-cd/blob/f29151eab7cce45c11904e5cbbfe6dd02a20cd18/server/application/application.go#L175

I think the message definitions for both, [create](https://github.com/argoproj/argo-cd/blob/f29151eab7cce45c11904e5cbbfe6dd02a20cd18/server/application/application.proto#L61) and [update](https://github.com/argoproj/argo-cd/blob/f29151eab7cce45c11904e5cbbfe6dd02a20cd18/server/application/application.proto#L67) messages would need to include a new field, that specifies whether a finalizer should be set or not. Depending on that setting, the Create and Update methods should modify the resource that's being created or updated in the cluster.
