### ISSUE TITLE
argocd-dex-server pod in CrashLoopBackOff

### ISSUE THREAD

**Issue by jasvinder-tp** [argoproj/argo-cd#5306]
unknown command "rundex" for "argocd-util"

Error: unknown command "rundex" for "argocd-util"
Run 'argocd-util --help' for usage.

<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>
Details:

Name:           argocd-dex-server-8
Namespace:      argocd
Priority:       0
Node:           gke-k8s-a833487b-0w6x/10.74.0.28
Start Time:     Mon, 25 Jan 2021 15:43:25 +0530
Labels:         app.kubernetes.io/name=argocd-dex-server
                pod-template-hash=858b6dd4b7
Annotations:    <none>
Status:         Running
IP:             10.74.65.13
Controlled By:  ReplicaSet/argocd-dex-server-858b6dd4b7
Init Containers:
  copyutil:
    Container ID:  docker://30da8969f21d913530d8aeb0ffd394dea4b754f67dff28c76c5bdfce3649ebb7
    Image:         argoproj/argocd:latest
    Image ID:      docker-pullable://argoproj/argocd@sha256:f61e5a4ced53aa4875f5ede0b63601874113bac288b8ba3f03b5f1db821bd274
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
      -n
      /usr/local/bin/argocd-util
      /shared
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 25 Jan 2021 15:43:35 +0530
      Finished:     Mon, 25 Jan 2021 15:43:35 +0530
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /shared from static-files (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from argocd-dex-server-token-pvzxw (ro)
Containers:
  dex:
    Container ID:  docker://19ed10551a17e096e9529cfade3c19988c773d59d19525aa35034b22b3f17125
    Image:         quay.io/dexidp/dex:v2.25.0
    Image ID:      docker-pullable://quay.io/dexidp/dex@sha256:7bcf286807b8158c0d772b388a733ce7bb9e5765e82a5f546d2569b5d929c3ef
    Ports:         5556/TCP, 5557/TCP, 5558/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Command:
      /shared/argocd-util
      rundex
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 25 Jan 2021 16:04:54 +0530
      Finished:     Mon, 25 Jan 2021 16:04:54 +0530
    Ready:          False
    Restart Count:  9
    Environment:    <none>
    Mounts:
      /shared from static-files (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from argocd-dex-server-token-pvzxw (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  static-files:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  argocd-dex-server-token-pvzxw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  argocd-dex-server-token-pvzxw
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                                                          Message
  ----     ------     ----                 ----                                                          -------
  Normal   Scheduled  26m                  default-scheduler                                             Successfully assigned argocd/argocd-dex-server-858b6dd4b7-htm5t to gke-k8s-a833487b-0w6x
  Normal   Pulling    26m                  kubelet, gke-k8s-a833487b-0w6x  Pulling image "argoproj/argocd:latest"
  Normal   Pulled     25m                  kubelet, gke-k8s-a833487b-0w6x  Successfully pulled image "argoproj/argocd:latest"
  Normal   Created    25m                  kubelet, gke-k8s-a833487b-0w6x  Created container copyutil
  Normal   Started    25m                  kubelet, gke-k8s-a833487b-0w6x  Started container copyutil
  Normal   Pulling    25m (x4 over 25m)    kubelet, gke-k8s-a833487b-0w6x  Pulling image "quay.io/dexidp/dex:v2.25.0"
  Normal   Pulled     25m (x4 over 25m)    kubelet, gke-k8s-a833487b-0w6x  Successfully pulled image "quay.io/dexidp/dex:v2.25.0"
  Normal   Created    25m (x4 over 25m)    kubelet, gke-k8s-a833487b-0w6x  Created container dex
  Normal   Started    25m (x4 over 25m)    kubelet, gke-k8s-a833487b-0w6x  Started container dex
  Warning  BackOff    60s (x115 over 25m)  kubelet, gke-k8s-a833487b-0w6x  Back-off restarting failed container

Logs:

kubectl logs argocd-dex-server-8 -n argocd
unknown command "rundex" for "argocd-util"
Error: unknown command "rundex" for "argocd-util"
Run 'argocd-util --help' for usage.

**Comment by jshin47** [comment]
Also started getting this issue after restarting Dex this afternoon. It had been running for a month or so prior to today without issue. My Dex version according to the deployment is v2.25.0 .

**Comment by jshin47** [comment]
It appears to be an issue with the "latest" tagged argocd image. When I downgrade the version of argocd image used to copy the `argocd-util` binary to a specific version like `v1.8.3`, it works.

**Comment by alexmt** [comment]
Yes, this change is documented here: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/upgrading/1.8-1.9.md#dex-tool-migrated-from-argocd-util-to-argocd-dex

**Comment by cyclingwithelephants** [comment]
the above links produces a 404 for me

**Comment by Dav1dde** [comment]
I ran into the same issue with 1.8.7 (1.8.3 works), this is my kustomize patch:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      containers:
        - command:
            - /shared/argocd-dex
            - rundex
          name: dex
      initContainers:
        - command:
            - cp
            - -n
            - /usr/local/bin/argocd-dex
            - /shared
          name: copyutil
```

**Comment by jeff51419** [comment]
> the above links produces a 404 for me

try this one

https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/upgrading/1.8-2.0.md#dex-tool-migrated-from-argocd-util-to-argocd-dex
