### ISSUE TITLE
Documentation of argocd-util is not clear namely from where to download it 

### ISSUE THREAD

**Issue by abdennour** [argoproj/argo-cd#5307]
# Summary
Documentation about from where to download argocd-util does not exist.
# Motivation

Struggling a couple of hours to get the binary of argocd-util , but no hope

# Proposal

Add section about installing argocd-util in this page: https://argoproj.github.io/argo-cd/operator-manual/server-commands/argocd-util/

**Comment by jessesuen** [comment]
The documentation is ahead of the feature availability. @reginapizza is working on improving this so that we have separate doc versions per argo  cd.

Argo CD v1.9 will be the first version where we actively distribute `argocd-util` as part of releases.

**Comment by jessesuen** [comment]
Lets leave this open to:
1. add instructions on getting the binary
2. more details on how to use the tool for declarative management (e.g. `argocd-util config` examples)

**Comment by abdennour** [comment]
Hello @jessesuen , is there good news about this issue ?

**Comment by alexmt** [comment]
Update for mac users: after merging https://github.com/Homebrew/homebrew-core/pull/75034 the `argocd-util` will be available via `brew install argocd`

**Comment by tschale** [comment]
What's the state for non-mac users? On ubuntu argocd v2.1.2+7af9dfb doesn't seem to have `argocd-util` available...

**Comment by alexmt** [comment]
Hello @tschale . We've ended up [merging](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.0-2.1/#the-argocd-util-cli-commands-merged-into-argocd-admin) `argocd-util` into `argocd` . The `argocd-util` commands are available under `argocd admin`, e.g. `argocd admin export`

**Comment by tschale** [comment]
Hi @alexmt, thanks for clarifying! It's still referenced as `argocd-util` in the documentation, I stumbled upon it in https://argoproj.github.io/argo-cd/operator-manual/rbac/#testing-a-policy and https://argoproj.github.io/argo-cd/operator-manual/server-commands/argocd-util/. 
Is this known, or this is intended?

**Comment by alexmt** [comment]
Argo CD documentation was migrated to https://argo-cd.readthedocs.io/ but we totally forgot to add a redirect https://argoproj.github.io to a new location. Added redirect.

The updated documentation does not mention argocd-util:

https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/#testing-a-policy
https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_admin/
