### ISSUE TITLE
[ui] Add app-of-apps hierarchy in header breadcrumb

### ISSUE THREAD

**Issue by ebuildy** [argoproj/argo-cd#5314]
Tested version: 1.7.X

# Summary

On app details page, when using app of apps pattern, we use app A to navigate to app B then app C. Will be good to have all the parent/children hierarchy in the header breadcrumb to go back quickly to the parent app.

# Motivation

Improve navigation 

# Proposal

List app of apps hierarchy in the header breadcrumb

**Comment by jessesuen** [comment]
We don't actually want to have special handling of the app-of-apps pattern in Argo CD, especially since we will be pushing ApplicationSets as a better overall feature in the future. So I don't think we should do this.

**Comment by ebuildy** [comment]
Yes I understand, didn't get yet into Application Set .

Thanks you I will give a try .

Le mar. 26 janv. 2021 à 22:23, Jesse Suen <notifications@github.com> a
écrit :
