### ISSUE TITLE
Expose sync retry options on app creation/update in CLI and UI 

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#5318]
# Summary

With release 1.7 (#3997), support for failed sync retries was added. Currently, configuration of this feature is rather inaccessible to users and not well documented. Although being a very useful feature, configuration is only possible editing the manifests directly.

# Motivation

Make this feature more visible and more easy to configure.

# Proposal

1) Expose the feature on `argocd app create` similar to how it is exposed in `argocd app sync` currently
2) Expose the featue on the web UI when creating, editing or viewing an application's details
3) Provide proper documentation about the various tunables and how to configure the sync retry feature

**Comment by jessesuen** [comment]
Would https://github.com/argoproj/argo-cd/issues/5215 cover this use case?

**Comment by jannfis** [comment]
It has a certain overlap for sure, but I interpreted #5215 focusing on consolidating UX on sync options. 

This one would be more about exposing sync retry policy in the CLI, UI and documentation. So I think this should be kept a separate issue.

**Comment by shubhamagarwal19** [comment]
@jannfis, maybe i can have a look at this one !! can you assign this to me ?

**Comment by jannfis** [comment]
Thanks @shubhamagarwal19 - will assign the issue to you.

**Comment by jannfis** [comment]
#5638 only partly resolved this (the CLI part), re-opening for someone to pick up the UI part.

**Comment by rumstead** [comment]
I probably just missed it but do these changes expose all the SyncOptions on the ApplicationSpec? 

https://github.com/argoproj/argo-cd/issues/5214, is an issue I created and thought would be addressed by this issue?

**Comment by aceamarco** [comment]
Hi y'all from what I understand — there's still some remaining work to be done on this, namely 
- [ ] : Expose the feature on the web UI when creating, editing or viewing an application's details
- [ ] : Provide proper documentation about the various tunables and how to configure the sync retry feature

Can I try picking this up to see if I can move it along?

**Comment by jannfis** [comment]
Hey @aceamarco, thank you for your offer! It would be much appreciated if you'd pick the missing pieces from this puzzle.

Please let us know if we can support you during your journey.

**Comment by pasha-codefresh** [comment]
@alexmt i would take it
