### ISSUE TITLE
Change `Compiler` to `Go Compiler` in About

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5329]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

`Compiler` is a bit vague for end users, adding the word `Go` before it would improve user comprehension at minimal cost

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/help
2. Click the version under the logo
3. Wonder what `Compiler` `gc` is

**Expected behavior**

See `Go Compiler` `gc`

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/105939940-2f181d80-6028-11eb-887a-6b5d21914b46.png)

**Version**

```shell
{
    "Version": "v1.9.0+7165b45",
    "BuildDate": "2021-01-26T21:23:37Z",
    "GitCommit": "7165b45aeaa15044cec514e7de3d300d448b2df9",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jannfis** [comment]
I agree, "Go Compiler" might be a better term.

I wonder if we should rename the display name of the Go version to "Go version" as well, as to be consistent with the JSON output, so we'd had:

Go version: 1.14.12
Go compiler: gc

What do you think?

**Comment by jsoref** [comment]
Oh, yes. I was actually only interested in changing the display form, but, yeah, change both :-)

**Comment by jannfis** [comment]
I think this was not fixed by #5337

**Comment by rbreeze** [comment]
@jannfis I think it was, unless the json name needs to be changed as well? 

<img width="526" alt="Screen Shot 2021-01-28 at 11 29 46 AM" src="https://user-images.githubusercontent.com/6250584/106188693-21fc4b00-615c-11eb-8d84-63ab0a5a9234.png">

**Comment by jannfis** [comment]
Hm. that's what is showing in my UI (latest build):

![image](https://user-images.githubusercontent.com/3942683/106190556-1e8fb080-61aa-11eb-8a14-03f4aa52c3be.png)
