### ISSUE TITLE
Expose Cluster Name to tools

### ISSUE THREAD

**Issue by Velyks** [argoproj/argo-cd#5336]
# Summary

I would like the name of the cluster specified in a given argocd application manifest to be exposed as an env to tools.

# Motivation

I have DNS entries automatically being created for services in my ArgoCD cluster  and some applications need to know their own base URL. Since the subdomain of the URL depends on which cluster an application is deployed to it would be nice to be able to see what that is at sync time.

# Proposal

The name of the cluster/server specified in the ArgoCD application's destination should be added to the list of [Standard build environment](https://argoproj.github.io/argo-cd/user-guide/build-environment/) as `$ARGOCD_APP_CLUSTER`

**Comment by blakepettersson** [comment]
Duplicates #14957
