### ISSUE TITLE
Make use of K8s recommended application labels

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#534]
In order to play well with other tooling in the k8s ecosystem (e.g. dashboards), we should start using the recommended application labels as defined here:

https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

We should even consider switching from our current argocd label, to the recommended K8s labels. It would be better to do this sooner rather than later since it will likely need a migration step.

**Comment by jessesuen** [comment]
ArgoCD will inject two labels:
* app.kubernetes.io/managed-by: argocd
* app.kubernetes.io/instance: guestbook-prod

Other labels would be under user control, such as:
* app.kubernetes.io/name

**Comment by jessesuen** [comment]
I confirmed that `app.kubernetes.io/instance` is appropriate to use for labeling apps, and will be compatible with the Application CRD. We also do not need the `app.kubernetes.io/managed-by: argocd` label, since the new v0.11 design does not depend on using additional special labels for managing/querying Argo CD applications.

**Comment by kallangerard** [comment]
> I confirmed that `app.kubernetes.io/instance` is appropriate to use for labeling apps, and will be compatible with the Application CRD. We also do not need the `app.kubernetes.io/managed-by: argocd` label, since the new v0.11 design does not depend on using additional special labels for managing/querying Argo CD applications.

This was not the correct choice
