### ISSUE TITLE
--plugin-env flag missing from app set

### ISSUE THREAD

**Issue by Velyks** [argoproj/argo-cd#5341]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

The flag `--plugin-env` for the command `argocd app set` is no longer there as described in the documentation here. https://argoproj.github.io/argo-cd/user-guide/commands/argocd_app_set/

**To Reproduce**

Try to run `argocd app set <app-name> --plugin-env <env-string>` and you will get `FATA[0000] unknown flag: --plugin-env `

`argocd app set --help` also does not list it.

**Expected behavior**

ArgoCD CLI should set the specified plugin-env on the application.

**Version**

```shell
argocd: v1.8.3+0f9c684
  BuildDate: 2021-01-21T22:21:47Z
  GitCommit: 0f9c68427882bf4633d395cbfcd7c9271795fd9b
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.3+0f9c684
  BuildDate: 2021-01-21T22:20:39Z
  GitCommit: 0f9c68427882bf4633d395cbfcd7c9271795fd9b
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Comment by mayzhang2000** [comment]
This is not released in v1.8 yet. We are working on better versioning of our documentation.
