### ISSUE TITLE
Document assigning clusters to shard.

### ISSUE THREAD

**Issue by HumairAK** [argoproj/argo-cd#5348]
# Summary

Document sharding of clusters to specific replicas . 

# Motivation

Had to ask on slack, and found out about the ability to assign clusters to shards from there. The individual in question had to look into the [swagger](https://github.com/argoproj/argo-cd/blob/master/assets/swagger.json#L4909) json to figure it out. 

# Proposal

I think the best place to add this is [here](https://argoproj.github.io/argo-cd/operator-manual/high_availability/#argocd-application-controller), the bullet point where the sharding behavior is described.

**Comment by nickorlow** [comment]
Hi maintainers (cc @saumeya )!

I'm a CS student at the University of Texas at Austin. I'm taking a class focusing on open-source software and virtualization at the moment. One part of the course is making open source contributions. I'd like to work on this issue.

The class requires that we ask the maintainers and get an OK to work on the issue before it can be counted for credit in the class. Would it be possible for me and my partner in the class to work on this issue?

**Comment by saumeya** [comment]
Hi @nickorlow , sure that sounds awesome! It is ok for you to work on it, thanks for your contribution!

**Comment by crenshaw-dev** [comment]
@nickorlow and you preemptively have the go-ahead to work on any "good first issue" issue. :-) Feel free to tag me for a review or anything else you need, and good luck on the project!

**Comment by sridharnandigam** [comment]
Hey, I'm @nickorlow's partner on the project. I added the documentation and created a pull request. Please let me know if there's anything that needs to be modified.
