### ISSUE TITLE
Docs are incorrect for external links

### ISSUE THREAD

**Issue by james-callahan** [argoproj/argo-cd#5350]
https://argoproj.github.io/argo-cd/user-guide/external-url/ says that the annotation to use is `argocd.argoproj.io/external-link`, however the annotation to use is really a prefix of `link.argocd.argoproj.io/`
https://github.com/argoproj/argo-cd/blob/5f1046103459ac8a16a2cd08e0236a75b6094e9c/common/common.go#L143

**Comment by james-callahan** [comment]
I don't think this was entirely fixed by #5377 

It still needs to be documented that `link.argocd.argoproj.io/` is a prefix and you can place your own string after the `/`

**Comment by smktpd** [comment]
@alexmt please re-open this ticket, @james-callahan is right, the docs are still confusing and the fix should be trivial.
