### ISSUE TITLE
Make Helm v3 the default and remove version auto-detection

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#5359]
# Summary

With Helm v2 now officially deprecated and sun-downed by its maintainers since a while, we should make Helm v3 the default and also disable Helm version detection by evaluating `apiVersion` in `Chart.yaml`.

# Motivation

Many OTS charts need to be rendered using Helm v3, but still specify a `apiVersion: v1` in their `Chart.yaml` (or even specify no `apiVersion` at all). 

When rendering the charts using Helm v3, this is not a problem. But Argo CD will, per default, render those Charts using Helm v2, which may lead to errors in the rendered manifests.

Also, Helm v2 will not be updated anymore, not even for security updates (https://helm.sh/blog/helm-v2-deprecation-timeline/)

# Proposal

1. We should make Helm v3 the default for all Charts rendered using Argo CD - regardless of `apiVersion` specified in the Chart.yaml
2. Complete removal of Helm version auto-detection. That made much sense during Helm v2 -> v3 transition phase, but does not so anymore.
3. Deprecate Helm v2 for being shipped with Argo CD. Target removal after next release + N.
4. Until removal of Helm v2, let users explicitly chose Helm v2 by setting `.spec.source.helm.version: 2` in Application manifest if required

**Comment by jessesuen** [comment]
I agree with the proposal. Is this something we should do for v1.9?

**Comment by ishitasequeira** [comment]
I would like to work on this issue.

**Comment by jannfis** [comment]
Thank you for picking it up, @ishitasequeira

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-cd/pull/5646
