### ISSUE TITLE
Allowing the option to delete Statefulset/Deployment  resources with "--cascade=false"

### ISSUE THREAD

**Issue by bruce-au** [argoproj/argo-cd#5368]
# Summary

Add the option to set deletion of certain resources with the "--cascade=false" option.

# Motivation

We are currently trying to delete our deployment objects without the pods also getting deleted via ArgoCD. This doesn't seem like it's currently possible. This might be useful in cases where a `deployment/statefulset` is moved from one Application to another or updating the `deployment/statefulset` object's immutable fields without having to worry about downtime.

# Proposal

In addition to `force deletes` in the dialog box for deleting resources, we can also expose the `cascade` option as well.

**Comment by jessesuen** [comment]
Are you essentially asking for a checkbox to have a cascade checkbox (similar to the force checkbox)?

![image](https://user-images.githubusercontent.com/12677113/106523304-c43a6c80-6495-11eb-81bd-aff9ac2d45a9.png)

If so, I agree this would be useful.

**Comment by ishitasequeira** [comment]
Looking into this issue

**Comment by jannfis** [comment]
Implemented by #5538
