### ISSUE TITLE
Multiple external URLs for SSO access

### ISSUE THREAD

**Issue by Timoses** [argoproj/argo-cd#5388]
# Summary

Currently, only one `url` can be configured in ArgoCD ConfigMap (`argocd-cm.yaml`; see https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/).
It should be possible to specify more than one valid url.

# Motivation

Our clusters generally have two access paths:
1. via F5 BigIP and
2. via a management network (directly to cluster via nginx Ingress).

This also means that we use 2 differing URLs to access these endpoints.

In general, the F5 path is for end users, whereas the management path is for system administrator use as a last resort mechanism in case the F5 path experiences a downtime. For failure analysis it is important to still be able to access ArgoCD (preferrable via GUI).

Currently, if trying to access ArgoCD via a URL which is not specified in `url` of ArgoCD ConfigMap the response is 
```
Invalid return_url
```

# Proposal

`url` in `argocd-cm.yaml` should accept a list of valid URLs which can be used for SSO.

**Comment by zerodayyy** [comment]
I'm having a similar issue as well, where an ArgoCD instance can be referred to via multiple URLs, and the SSO provider fully supports it. However, due to the hard-coded single-URL logic implemented in #4780, it's only possible to have a single external URL. The change should be as simple as adding `urls` config parameter, accepting the list of URLs, and at some point deprecating the `url` parameter.

I think I'd be able to make a PR for this.

**Comment by alfsch** [comment]
any news on this?

**Comment by KelvinVenancio** [comment]
Any news? We have the same needs here, by using ArgoCD with Cognito for SSO.

**Comment by crenshaw-dev** [comment]
There's an open PR: https://github.com/argoproj/argo-cd/pull/14208/files

The PR backlog is currently long. The best way to help move PRs like this along is to review the code and to build/test in an internal environment, reporting any successes or issues on the PR thread.

**Comment by tjamet** [comment]
Thanks for your comment @crenshaw-dev 

To ease testing, I have pushed an [image with those changes](https://github.com/tjamet/argo-cd/pkgs/container/argo-cd%2Fargocd/126159769?tag=2.9.0-1eb72892), using the standard `master` build scripts, just [adapted](https://github.com/tjamet/argo-cd/commit/1eb728924bbbc7a0231469e27085b7ef0f91bd57) to work on my fork:
https://github.com/tjamet/argo-cd/pkgs/container/argo-cd%2Fargocd/126159769?tag=2.9.0-1eb72892
