### ISSUE TITLE
Add support for immutable ConfigMaps/Secrets

### ISSUE THREAD

**Issue by matthyx** [argoproj/argo-cd#5394]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Feature is in beta since 1.19 and it would be nice to allow using it:
https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable

Problem is, you cannot simply update the configmap/secret, but rather delete and create anew.
Same should be done for the pod mounting it to ensure the application has the proper content.

**To Reproduce**

Create an immutable configmap and let argoCD synchronize it:

```
apiVersion: v1
kind: ConfigMap
metadata:
  ...
data:
  ...
immutable: true
```

Edit the data, sync again and here comes the error:
`ConfigMap xxx is invalid: data: Forbidden: field is immutable when immutable is set`

**Expected behavior**

ArgoCD should sync this ConfigMap without an error and restart pods mounting it.

**Comment by servo1x** [comment]
Have you tried force sync? Force sync should recreate the resource.

**Comment by matthyx** [comment]
> Have you tried force sync? Force sync should recreate the resource.

Indeed, when doing a manual sync with *force sync* it works. Do you have a way to make it without human intervention?
