### ISSUE TITLE
There should be whitespace between warnings and errors

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5409]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

1. Create an argocd instance with an error and a warning:
2. For the warning, enabling showing and whining about non argo tracked resources works well
3. For the error, set up a broke app that points to a non existent directory
4. Visit /applications/app-with-warnings-and-errors?conditions=false
**Expected behavior**

Random text shouldn't run into other random text.

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/106935837-dad90180-66e9-11eb-95fe-97bb6b01a6d5.png)

**Version**

```shell
{
    "Version": "v1.9.0+00f53b5",
    "BuildDate": "2021-01-27T00:04:02Z",
    "GitCommit": "00f53b510d87750492d8446e3303f6ab28258bce",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by saumeya** [comment]
can this be closed @jsoref

**Comment by jsoref** [comment]
It appears this should be fixed by:
https://github.com/argoproj/argo-cd/pull/5458/files#diff-4b88f846774c449afe371a91f0a5184f764cc1cc98a947003281c74407dc4074R22-R24

I'm not a huge fan of centering the messages when wrapping, but I can live with it.

Fwiw, we're running ~2.2.0, and I'm pretty sure I saw this glitch in January 2022.

I'll need to get us upgraded and see if I hit it again.

Note: It'd be really handy if https://cd.apps.argoproj.io/ had an application with multiple conditions so one could just verify the behavior there.
