### ISSUE TITLE
ArgoCD UI External links dropdown caret positioned incorrectly in list view

### ISSUE THREAD

**Issue by nivekastoreth** [argoproj/argo-cd#5462]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

External links dropdown caret is way off to the right and below the hamburger element in the Applications pane with List mode active.

**To Reproduce**

Navigate to `<argocd-ui-server>/applications?view=list` and observe application with multiple ingress configured.

**Expected behavior**

External links dropdown caret is next to the `span` element, as it is in the tiles view

**Screenshots**

Expected tiles behaviour
![image](https://user-images.githubusercontent.com/786082/107301841-44d70b00-6a4a-11eb-9967-8677d07a36fb.png)

Broken list behaviour
![image](https://user-images.githubusercontent.com/786082/107301855-4d2f4600-6a4a-11eb-84c1-28afdbf10b22.png)

**Version**
Not using command line `argocd`. Here's the relevant section from the UI:
```json
{
    "Version": "v1.8.3+0f9c684",
    "BuildDate": "2021-01-21T22:20:39Z",
    "GitCommit": "0f9c68427882bf4633d395cbfcd7c9271795fd9b",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by nivekastoreth** [comment]
Note, I observed this on windows in both chrome, firefox, and edge.

**Comment by ciiay** [comment]
I would like to work on this. Thanks.
