### ISSUE TITLE
Moving applications from projects causes Unauthorized errors

### ISSUE THREAD

**Issue by maberny** [argoproj/argo-cd#5465]
I have also asked about this particular issue in slack.

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

When moving an existing (synced) application to another project, the application then fails to sync with `Unauthorized` errors on all the resources. As well as `one or more synchronization tasks are not valid` error message. This happens in the UI and with the CLI as well. I am using the built-in admin role and never had that issue previously. It also sometimes successfully syncs but it is few and far between. 

**To Reproduce**

1. We are using the apps-of-apps pattern.
2. Have a deployed application belonging to a project.
2. Create a new project with a different name and the same server as destination.
3. Delete the application with cascade=false in the old project.
4. Sync the new application belonging to the new project.
5. At this point you will get the resource sharing warning but after it will go away once synced successfully. However this is where we start getting the `Unauthorized` errors.

**Expected behavior**

The application should be able to be synced successfully since it has completely been moved to a new project.

**Screenshots**
![Screen Shot 2021-02-09 at 12 53 52 PM](https://user-images.githubusercontent.com/32132546/107406383-6087f300-6ad6-11eb-916d-72f341878e0c.png)

**Version**
$ argocd version
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0

**Comment by kshamajain99** [comment]
@maberny This doesn't look like argocd error, it might be coming from kubernetes api server. Please take a look at your application logs for more details on the error.

**Comment by maberny** [comment]
@kshamajain99 I will be closing this as the error was on our side. We ended up having duplicated Clusters registered in ArgoCD different names pointing to the same cluster. We didn't see any application logs highlighting this so it made debugging a bit difficult. Thanks for the reply nonetheless!
