### ISSUE TITLE
Shallow clone option for reposerver?

### ISSUE THREAD

**Issue by askreet** [argoproj/argo-cd#5467]
# Summary

I'm wondering if the team would be interested in having a feature that allows the reposerver to shallow clone the target repository, to an optional depth value. We have a use case that is probably abnormal in that we are provisioning entire environments with their own argocd deployment, and then deploying a fleet of applications. Some of the git repositories have quite a lot of history and exceed the existing exec timeout (which we have had to extend). Using a shallow clone (i.e. `--depth=XXX`) would drastically improve initialization time for us. We may be able to dedicate some resources to the implementation if the feature is desirable.

# Motivation

Deploying argocd often in short-lived environments results in long wait times for initial git clones.

# Proposal

Introduce a tunable option for shallow clones, either as an environment variable or an annotation (which is preferred?).

**Comment by alexmt** [comment]
I think can be optionally enabled per repository. Apparently, the shallow clone is expensive. See https://github.com/Homebrew/discussions/discussions/225

**Comment by askreet** [comment]
@alexmt It puts burden on the server side to compute the bundle that is sent over the wire, if I understand correctly. In Homebrew's case, that's probably a noticeable impact to GitHub (where Homebrew uses GitHub as a backing repository server, essentially, and has a huge commit history).

When you said "I think it can be optionally enabled per repository", you mean if it were to be implemented, right? I haven't missed some feature that already exists, I hope. This would be ideal for us, as most of our repositories are small, but some have huge history where `--depth=1` would help greatly.

**Comment by alexmt** [comment]
Thank you for clarification @askreet !

I was trying to say that the shallow clone should not be the default behavior. This is not supported yet. We would have to introduce e.g. `fetchDepth` field in repository [settings](https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L1378) and use it in git client:

https://github.com/argoproj/argo-cd/blob/fb8096a1f7f3dcca51eff3018288708ce523da7e/util/git/client.go#L264

**Comment by askreet** [comment]
Was doing some experimentation with this this morning and realized that if this does get implemented, it's more involved than simply passing `--depth=1` to the initial clone. As soon as you call `git fetch origin --tags --force` on the new repository, it fetches quite a lot of the historical state you've avoided with `--depth=1`, assuming you have tags dating back to the beginning of the repository.

It could be possible that with `fetchDepth` set we skip fetching tags or some other workarounds.

**Comment by jannfis** [comment]
> It could be possible that with `fetchDepth` set we skip fetching tags or some other workarounds.

I think that's worth a try. With limiting the fetch depth, user explicitly agrees to ignore history of the repo, so we won't require any of it imo.

**Comment by jannfis** [comment]
@alexmt Regarding the new parallellism features with repositories, I understood that we prevent a new clone of the repository for applications. Does it take the target revision into account, or will it switch between target revisions in our checked  out repository on the repo-server?

I haven't looked, but if the latter is true, I think with shallow clones, parallellism would have to be disabled by being tested for here as well:

https://github.com/argoproj/argo-cd/blob/824ff732a2a34874c24fff4af1babc382ecb765a/pkg/apis/application/v1alpha1/types.go#L164-L174

**Comment by phs** [comment]
Popped in to ask for this exact feature.

I was testing manual clones against my own large repo, to understand what I would like argo to even do.  I noticed that while initial checkouts with (say) `--depth 1` worked well, I could not then `git pull --depth 1`, without running into `fatal: refusing to merge unrelated histories` errors.  Likewise explicitly allowing unrelated histories did not help.

Instead, I found that I was required to `git fetch --depth 1` and then `git reset --hard origin/the/branch` to move from one shallow checkout to the next.  Which given the context is completely acceptable to me.  I don't know offhand how argo performs its pulls/merges, but I would hope the hard-reset option remains on the table.

**Comment by dodwmd** [comment]
bumping this request as we're running into `fetch-pack: invalid index-pack output` issues

**Comment by prein** [comment]
Would `git clone [remote-url] --branch [name] --single-branch` be worth considering in addition to `--depth 1`?

**Comment by imtiazc** [comment]
As our repo started growing, we are running into issues where the `argocd-repo-server` is taking too long to fetch the contents and are timing out. 
` level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = Failed to fetch default: `git fetch origin --tags --force` failed timeout after 1m30s" grpc.code=Internal grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2023-02-14T23:22:08Z" grpc.time_ms=90007.375 span.kind=server system=grpc `

**Comment by nuno-silva** [comment]
+1 on supporting shallow clone :pray:

**Comment by emirot** [comment]
I would like to know how that could be implemented ?

Should it be a command argument or an env variable on the repo server that just update that function 
https://github.com/argoproj/argo-cd/blob/master/util/git/client.go#L334


Or when adding a [repository](https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/) by specifying the depth?  So having the option for each repo?

Or it needs to be added at the  application level with a new `depth` field?

```
    ....
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: applicationset/examples/list-generator/guestbook/{{cluster}}
        depth: 5
      destination:
        ....
```

**Comment by dodwmd** [comment]
As applications function as pipelines of sorts, I'd think it would be on the application level. it would possibly mean repos would need to be checked out multiple times per each application. if they were on different shas.

**Comment by QuinnBast** [comment]
Would love to see support for shallow clones. ArgoCD should only really ever need the latest commit of a branch (unless a specific commit is specified), and in either case a `git clone --depth 1` should work to just be able to fetch the current files in the repository/branch. ArgoCD is just running kustomize/kubectl apply/helm commands so shouldn't really need any notion of any git history anyway; not to mention this would also speed-up the sync process :)

**Comment by blakepettersson** [comment]
Something like this is being worked on in #14272

**Comment by batazor** [comment]
any news?

**Comment by crenshaw-dev** [comment]
Consolidating conversation here: https://github.com/argoproj/argo-cd/issues/11198

**Comment by jiridanek** [comment]
* https://github.com/argoproj/argo-cd/pull/24931
* https://akuity.io/blog/optimizing-gitops-at-scale-with-shallow-clones-in-argo-cd
