### ISSUE TITLE
Network view should group pods into higher level workload

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#5468]
# Summary

The network view does not look good when you have a large application with many pods. 

![image](https://user-images.githubusercontent.com/12677113/107435478-0e000400-6ae1-11eb-9526-6e6ba9b3caf8.png)

Most of the time, users don't care how traffic is routed to individual pods, but rather to some higher level workload that created that pod (e.g. ReplicaSet).

# Proposal

Instead of showing lines to many pods, we should connect the service to the parent of the pod. Possibly leveraging what we did in the pod view:

![image](https://user-images.githubusercontent.com/12677113/107436280-2f152480-6ae2-11eb-8872-ac9091294d62.png)

**Comment by jessesuen** [comment]
Whoever fixes this, please also right justify the network view

**Comment by keithchong** [comment]
Hi @jessesuen ,  just want to confirm, you only want to show the "parent resource", which replaces the old 'pod' container. eg. you don't want to show the other group types, like node and top level resource.

**Comment by keithchong** [comment]
@jessesuen / @alexmt , do you think the network targets (findNetworkTargets in application-resource-tree.tsx) needs to be changed?  Currently the targets are the pods, so will the targets be instead the parent resource?

**Comment by rbreeze** [comment]
This was addressed for the normal tree view, but not the network tree view

**Comment by keithchong** [comment]
Maybe something like this:

https://user-images.githubusercontent.com/7726022/161130052-4eb8ed62-c826-45ae-80b8-f98198ba8199.mov
