### ISSUE TITLE
Add noscript content

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5478]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Browsing argocd w/ javascript off yields a blank page

**To Reproduce**

1. Configure your browser to default to not running scripts/showing pictures
   * chrome://settings/content
   * JavaScript - blocked
   * Images - Do not show any images
2. Visit https://cd.apps.argoproj.io/applications
 
**Expected behavior**

Content suggesting enabling JavaScript for this site.

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/107599722-6fae9400-6bef-11eb-8a8a-d32e0d4f0b45.png)
![image](https://user-images.githubusercontent.com/2119212/107599751-94a30700-6bef-11eb-988c-4bc37ac26463.png)

**Version**

```shell
{
    "Version": "v1.9.0+223335d",
    "BuildDate": "2021-02-11T01:58:55Z",
    "GitCommit": "223335d96e5bb054d6081c168f53898072bcac3a",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.1",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jannfis** [comment]
Closed by #5650
