### ISSUE TITLE
Show unfiltered totals in parentheses

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5480]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

It isn't technically wrong to show only filtered counts, but it's somewhat misleading and unhelpful. There's plenty of space to show a secondary unfiltered number.

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications?proj=&sync=OutOfSync&health=&namespace=&cluster=&labels=
2. Show the filters box and filter something

**Expected behavior**

Show totals in parenthesis

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/107601138-c7e79500-6bf3-11eb-953a-b56922b535d2.png)
![image](https://user-images.githubusercontent.com/2119212/107601126-c027f080-6bf3-11eb-9e85-ba3d590c58e9.png)

**Version**

```shell
{
    "Version": "v1.9.0+fb8096a",
    "BuildDate": "2021-02-10T02:10:41Z",
    "GitCommit": "fb8096a1f7f3dcca51eff3018288708ce523da7e",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.1",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ciiay** [comment]
@jsoref It seems the filter count is no longer existing in the latest version. Could you confirm if this is still a valid issue? Thank you!
<img width="225" alt="Screen Shot 2021-08-04 at 6 24 07 PM" src="https://user-images.githubusercontent.com/26255262/128263132-b433694d-e634-4eee-a746-2478cb77702f.png">

**Comment by jsoref** [comment]
Hmm, indeed, at least in the demo it appears the counts are unfiltered.

We tried upgrading ArgoCD today and failed miserably because of some strange interaction between the latest Ubuntu and our container environment. I'm going to assume that if we succeed in upgrading, the demo'd behavior will apply.
