### ISSUE TITLE
pods Tooltip runs offscreen

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5481]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Text is cropped by left window edge

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/prometheus-operator?view=pods
2. Group by top level resource
3. Hover over leftmost pod

**Expected behavior**

Text shouldn't run outside window boundaries

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/107601845-cae38500-6bf5-11eb-8796-32f2c321aadf.png)

**Version**

```shell
{
    "Version": "v1.9.0+fb8096a",
    "BuildDate": "2021-02-10T02:10:41Z",
    "GitCommit": "fb8096a1f7f3dcca51eff3018288708ce523da7e",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.1",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ciiay** [comment]
I would like to work on this issue. Thanks.

**Comment by ciiay** [comment]
@jsoref Could you please confirm if you are able to reproduce it now? If not we can close this issue. Thanks.

**Comment by jsoref** [comment]
@ciiay: here you go:
![image](https://user-images.githubusercontent.com/2119212/124969387-a0ef8c80-dff4-11eb-8fbd-ad562c2e69ae.png)
fresh off:
```
{
    "Version": "v2.0.0+8030f42",
    "BuildDate": "2021-07-08T10:35:31Z",
    "GitCommit": "8030f4202a6e643613e3c208486820723821a01f",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.1.2 2021-04-15T20:38:06Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Comment by ciiay** [comment]
@jsoref Thanks for the quick reply. The issue was I filtered with wrong item. Now I'm able to reproduce it locally. Will work on this. Thank you!
