### ISSUE TITLE
Offer word wrap in log viewer

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5482]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

It's often much easier to read wrapped lines than scrolling

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/prometheus-operator/prometheus-operator/node-exporter/logs?podName=prometheus-operator-prometheus-node-exporter-4rfk5&group=undefined&kind=Pod&name=prometheus-operator-prometheus-node-exporter-4rfk5
2. See Copy, Follow, Moon/Ship's wheel (it's probably supposed to be a sun, but it's too close to the k8s logo), an exclamation mark (no tooltip, totally unclear what it does), and a filter string box

**Expected behavior**

There should be a wrap long lines button

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/107602181-bbb10700-6bf6-11eb-9394-c1f5fbcfd1eb.png)

**Version**

```shell
{
    "Version": "v1.9.0+fb8096a",
    "BuildDate": "2021-02-10T02:10:41Z",
    "GitCommit": "fb8096a1f7f3dcca51eff3018288708ce523da7e",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.1",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ciiay** [comment]
It seems there's no available text wrap icon in the w3 icon libraries except for "wrap_text" from Google Icons. Is that acceptale to add google icons reference to the app or a text label such as "WRAP LOG" is preferred?

**Comment by jsoref** [comment]
@ciiay: personally I want the feature more than I care about the L&F (and to be clear, a significant portion of the bugs I file are L&F bugs). If that means I get a text button today and ArgoCD decides on a solution for an icon next year, that's fine w/ me.

That said, this does look nice:
https://fonts.google.com/icons?selected=Material+Icons&icon.query=wrap_text

**Comment by ciiay** [comment]
@jsoref Thanks for the quick reply. Let me confirm with other members.

@rbreeze Is that okay to add google icons library or a text button is preferred for now?

**Comment by rbreeze** [comment]
@ciiay I think we should go with a word button rather than introducing a whole library for just one icon. I've opened a PR for it (#6889)
