### ISSUE TITLE
nginx Helm Version handling is broken

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5489]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I can't tell what kind of version it is, but it feels like it isn't git. The handler definitely assumes it's git.

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/ingress-nginx?view=tree
2. Click the more by current sync status

**Expected behavior**

Show a version

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/107610753-5702a600-6c10-11eb-813a-5f974a0bc4fe.png)
![image](https://user-images.githubusercontent.com/2119212/107610834-8d402580-6c10-11eb-9302-64473b46885a.png)

**Version**

```shell
{
    "Version": "v1.9.0+223335d",
    "BuildDate": "2021-02-11T01:58:55Z",
    "GitCommit": "223335d96e5bb054d6081c168f53898072bcac3a",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.1",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexmt** [comment]
Thank you @jsoref !


@rbreeze UI should not try to show metadata info for helm versions. Can you please fix it?

**Comment by jsoref** [comment]
Yeah, I thought it was helm. But I had a really hard time proving that to myself.

**Comment by rbreeze** [comment]
Will do!
