### ISSUE TITLE
ArgoCD Application controller Pod crash with memory spike while syncing app with custom resource kind VaultSecret

### ISSUE THREAD

**Issue by Rami-Y** [argoproj/argo-cd#5505]
**Describe the bug**

ArgoCD application controller pod is getting crashed with memory spike around 2Gib while syncing an application with a custom resource of kind VaultSecrect,

**To Reproduce**

Example: 1
a. Argo CD application controller is defined with memory limit 800Mi. 
   - resources:
        limits:
          cpu: 500m
          memory: 800Mi
        requests:
          cpu: 200m
          memory: 600Mi
b.	An app without ValutSecret is synced successfully.
c.	When the Sync is triggered for the app with ValutSecret, it got hung with memory spike and application controller pod went in crash loop back mode. Observed that Memory spiked up to 2 Gib in pod memory usage graph.
![image](https://user-images.githubusercontent.com/67324739/107782311-e72b1300-6d16-11eb-8ff6-4c0099e443f7.png)

Example 2
a.	Memory limit is increased to 3000 Mib in Argo CD application controller.
   - resources:
        limits:
          cpu: 500m
          memory: 3000Mi
        requests:
          cpu: 500m
          memory: 2500Mi

b.	The application with ValutSecret in example1 got successfully deployed/synced.
c.	If we try to sync 2 apps with ValutSecret resources at same time with 3000 Mib limit, it is again crashing the pod and went in to crash loop back mode as it is expecting 2000Mib+ size for each app sync. 

Based on above observation, for each app which has VaultSecret resource is taking around 2Gib memory while deploying/syncing the app. This is a severe issue if multiple applications are synced concurrently at same time as each app takes around 2GiB memory spike.

**Expected behavior**

**Screenshots**

**Version**

version using v1.7.11+97401f9
also observed in previous version v1.6.2

**Comment by alexmt** [comment]
Hello @Rami-Y ,

Does application include CustomResourceDefinition resources? When CRD changes Argo CD reload all instances of that CRD which might cause a memory spike. My theory is that you have custom resource which instances are big in size.

If this is the case we might need to add a setting allows decreasing a page size of K8s list queries to such resources.  I plan to work on a draft PR that introduce metrics that expose cache size per resource and settings.

**Comment by alexmt** [comment]
Totally forgot, another possibility is that memory spike caused by multiple kubectl fork/exec . Can you try to add `--kubectl-parallelism-limit=10` flag to `argocd-application-controller` ?

**Comment by Rami-Y** [comment]
@alexmt 
i tried by adding --kubectl-parallelism-limit=10 flag in argocd app controller but there is no change.

**Comment by jessesuen** [comment]
Can you give an example of a VaultSecret (obviously without any sensitive data). Is a VaultSecret object large in size?

**Comment by trv-smaksym3** [comment]
@jessesuen and @alexmt. I am transitioning this issue from my teammate @Rami-Y 

@alexmt 
No. the application does not include CustomResourceDefinition resources. we used 5 to 10 VaultSecret's in the app that fetches the secret value form HashiCorp vault.  Instance size is not big,  it has just few lines - see attached files.  The attached CRD is for the operator for reference only.
[ExampleVaultSecretAndCRD.zip](https://github.com/argoproj/argo-cd/files/5991131/ExampleVaultSecretAndCRD.zip.)  

We are currently working on the exact scenarios to replicate the memory spike.  However, we have found that if we sync after the ArgoCD Application controller restarts with an application that has a Vault Secret the memory jumps up to between 1.5 and 3GB for a very short while and drops back down.  

We have also excluded the Kind: Secret from synchronizing in case that was causing any circular issues, but that doesn't seem to have any effect.

**Comment by trv-smaksym3** [comment]
@jessesuen and @alexmt When I changed the logging to debug mode in application controller the following messages stand out.

1. time="2021-02-16T21:46:53-05:00" level=debug msg="Could not create new object of type secrets.xxxxxx.net/v1, Kind=VaultSecret: no kind \"VaultSecret\" is registered for version \"secrets.xxxxxx.net/v1\" in scheme \"pkg/runtime/scheme.go:101\""
2. time="2021-02-16T21:47:05-05:00" level=debug msg="Failed to watch Project.project.openshift.io on https://y.y.y.y:443: Recovered from panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 2233 [running]:\nruntime/debug.Stack(0xc001b3f418, 0x1cc2ea0, 0x34fc990)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/argoproj/gitops-engine/pkg/cache.(*clusterCache).watchEvents.func1.1(0xc001b3fae0)\n\t/go/pkg/mod/github.com/argoproj/gitops-engine@v0.1.3-0.20200925215903-d25b8fd69f0d/pkg/cache/cluster.go:404 +0x57\npanic(0x1cc2ea0, 0x34fc990)\n\t/usr/local/go/src/runtime/panic.go:969 +0x166\nk8s.io/client-go/tools/watch.(*RetryWatcher).Stop(...)\n\t/go/pkg/mod/k8s.io/client-go@v0.18.8/tools/watch/retrywatcher.go:281\ngithub.com/argoproj/gitops-engine/pkg/cache.(*clusterCache).watchEvents.func1.4(0x0, 0xc001b3ffd0)\n\t/go/pkg/mod/github.com/argoproj/gitops-engine@v0.1.3-0.20200925215903-d25b8fd69f0d/pkg/cache/cluster.go:447 +0x22\npanic(0x1cc2ea0, 0x34fc990)\n\t/usr/local/go/src/runtime/panic.go:969 +0x166\nk8s.io/client-go/tools/watch.(*RetryWatcher).Done(...)\n\t/go/pkg/mod/k8s.io/client-go@v0.18.8/tools/watch/retrywatcher.go:286\ngithub.com/argoproj/gitops-engine/pkg/cache.(*clusterCache).watchEvents.func1(0x229fe60, 0xc005d0ebb0)\n\t/go/pkg/mod/github.com/argoproj/gitops-engine@v0.1.3-0.20200925215903-d25b8fd69f0d/pkg/cache/cluster.go:464 +0x287\ngithub.com/argoproj/gitops-engine/pkg/utils/kube.RetryUntilSucceed.func1(0xc001b3fc48, 0x0, 0x0)\n\t/go/pkg/mod/github.com/argoproj/gitops-engine@v0.1.3-0.20200925215903-d25b8fd69f0d/pkg/utils/kube/kube.go:375 +0xde\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc001b3fd98, 0xc001b3fc00, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:211 +0x69\nk8s.io/apimachinery/pkg/util/wait.WaitFor(0xc00d054a80, 0xc001b3fd98, 0xc0211866c0, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:541 +0x13a\nk8s.io/apimachinery/pkg/util/wait.PollUntil(0x3b9aca00, 0xc001b3fd98, 0xc00165c300, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:492 +0xc2\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(0x3b9aca00, 0xc001b3fd98, 0xc00165c300, 0xc000c10dc0, 0x4e46a4)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:511 +0xb0\ngithub.com/argoproj/gitops-engine/pkg/utils/kube.RetryUntilSucceed(0x22ede20, 0xc001618f80, 0x3b9aca00, 0xc014e63380, 0x3c, 0xc000c10e38)\n\t/go/pkg/mod/github.com/argoproj/gitops-engine@v0.1.3-0.20200925215903-d25b8fd69f0d/pkg/utils/kube/kube.go:373 +0xae\ngithub.com/argoproj/gitops-engine/pkg/cache.(*clusterCache).watchEvents(0xc0002577a0, 0x22ede20, 0xc001618f80, 0xc0009af220, 0x14, 0xc000b80b48, 0x7, 0xc000b80b40, 0x8, 0x0, ...)\n\t/go/pkg/mod/github.com/argoproj/gitops-engine@v0.1.3-0.20200925215903-d25b8fd69f0d/pkg/cache/cluster.go:401 +0x20c\ncreated by github.com/argoproj/gitops-engine/pkg/cache.(*clusterCache).sync.func1.1\n\t/go/pkg/mod/github.com/argoproj/gitops-engine@v0.1.3-0.20200925215903-d25b8fd69f0d/pkg/cache/cluster.go:578 +0x302\n, retrying in 1s"

**Comment by advissor** [comment]
> Totally forgot, another possibility is that memory spike caused by multiple kubectl fork/exec . Can you try to add `--kubectl-parallelism-limit=10` flag to `argocd-application-controller` ?

Do you have example of adding this flag through helm chart?
Tnx in advance!

**Comment by trv-smaksym3** [comment]
We think we are seeing favorable results with the `--kubectl-parallelism-limit=10` flag to `argocd-application-controller`.  We are currently monitoring the memory and CPU.  Do you know exactly what this flag modifies? Am I right in assuming that an interaction with our Kubernetes cluster would be now limited to 10 concurrent transactions?  Will we experience syncs now at roughly half the rate?

Thanks.  Also we haven't made this change with helm.  We are deploying the ymls.

**Comment by alexmt** [comment]
It appears I was looking for a memory limit at the wrong place. Memory spike actually caused by inefficient `kubectl apply` usage. Argo CD concurrently executes `kubectl apply` twice per each resource. https://github.com/argoproj/gitops-engine/pull/281 improved it. Fix will be available in v2.1

**Comment by Sangamesh-ts** [comment]
Im seeing high memory issue as well for 2.6.10
