### ISSUE TITLE
Health checks for OLM operators

### ISSUE THREAD

**Issue by sbose78** [argoproj/argo-cd#5506]
# Summary
Add health checks for OLM Operators

# Motivation
When an OLM operator is installed, we need to wait for the `Subscription` resource to be _installed_ ( CRDs created, controller deployed etc ). This information needs to be reflected in a health check.

https://olm.operatorframework.io/docs/concepts/crds/subscription/

# Proposal

Add the custom logic to https://github.com/argoproj/argo-cd/tree/master/resource_customizations

**Comment by chetan-rns** [comment]
Fixed by #7126
