### ISSUE TITLE
Sync Apps panel is crashing

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#5507]
**Describe the bug**

Sync Apps panel is crashing:

```
Uncaught (in promise) TypeError: this.props.onSubmitFailure is not a function
    at t.<anonymous> (index.js:1)
    at b (runtime.js:62)
    at Generator._invoke (runtime.js:296)
    at Generator.forEach.e.<computed> [as throw] (runtime.js:114)
    at r (asyncToGenerator.js:17)
    at asyncToGenerator.js:30
```

**To Reproduce**

1. Navigate to Application List page
2. Click 'Sync Apps' button
3. Select several applications and click sync

**Expected behavior**

No error should occure

**Version**

https://github.com/argoproj/argo-cd/commit/65ecd87027ff2e91a0cc46b76a6e66fd8d595a55

**Comment by alexmt** [comment]
@rbreeze , I think this is related to https://github.com/argoproj/argo-cd/pull/5357 . Can you check please?

**Comment by rbreeze** [comment]
Of course, will open PR with fix ASAP! Thanks for catching
