### ISSUE TITLE
Cannot use argoCD to install native ingress-nginx

### ISSUE THREAD

**Issue by riveryc** [argoproj/argo-cd#5514]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to use ArgoCD to manage `ingress-nginx` https://kubernetes.github.io/ingress-nginx/deploy/#gce-gke
The deploy.yaml file: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.44.0/deploy/static/provider/cloud/deploy.yaml
I copy the content of the `deploy.yaml` file, and paste into my own repo.
ArgoCD didn't detect the service account for `ingress-nginx-admission` to be created.
ArgoCD didn't detect the job for `ingress-nginx-admission-patch` to be created.
Thus the deployment `ingress-nginx-controller` cannot be successfully created as it needs the secret to be created by `ingress-nginx-admission-patch`

Anyway... after N mins, the ingress-controller is still remaining as "progressing"...

**To Reproduce**

https://github.com/riveryc/argo-stack

```bash
kubectl apply -f projects.yaml
kubectl apply -f apps.yaml

Please be aware that the latest version argoCD is being managed by this repo too... 
```

**Expected behavior**

The ingress-nginx controller should be installed as normal with all jobs, service accounts etc... just like: 
```shell
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.44.0/deploy/static/provider/cloud/deploy.yaml
namespace/ingress-nginx created
serviceaccount/ingress-nginx created
configmap/ingress-nginx-controller created
clusterrole.rbac.authorization.k8s.io/ingress-nginx created
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx created
role.rbac.authorization.k8s.io/ingress-nginx created
rolebinding.rbac.authorization.k8s.io/ingress-nginx created
service/ingress-nginx-controller-admission created
service/ingress-nginx-controller created
deployment.apps/ingress-nginx-controller created
validatingwebhookconfiguration.admissionregistration.k8s.io/ingress-nginx-admission created
serviceaccount/ingress-nginx-admission created
clusterrole.rbac.authorization.k8s.io/ingress-nginx-admission created
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx-admission created
role.rbac.authorization.k8s.io/ingress-nginx-admission created
rolebinding.rbac.authorization.k8s.io/ingress-nginx-admission created
job.batch/ingress-nginx-admission-create created
job.batch/ingress-nginx-admission-patch created
```

**Screenshots**

n/a

**Version**

```shell
argocd: v1.8.4+28aea3d.dirty
  BuildDate: 2021-02-05T18:42:27Z
  GitCommit: 28aea3dfdede00443b52cc584814d80e8f896200
  GitTreeState: dirty
  GoVersion: go1.15.7
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.4+28aea3d
  BuildDate:
  GitCommit:
  GitTreeState:
  GoVersion:
  Compiler:
  Platform:
  Ksonnet Version:
  Kustomize Version:
  Helm Version:
  Kubectl Version:
  Jsonnet Version:
```

**Comment by jannfis** [comment]
Hi @riveryc, as a quick heads-up there's an ongoing discussion about a similar issue in #5522, with a workaround being available.

**Comment by jessesuen** [comment]
Duping to https://github.com/argoproj/argo-cd/issues/5522

**Comment by datton94** [comment]
Hi @jannfis , #5522 does not help, I'm still getting the same issue with ArgoCD v2.2.0 and Kustomize.

**Comment by datton94** [comment]
Update: changing the application name to `ingress-nginx` solved the issue, my previous application name is `nginx-ingress`. 

With the application name being `nginx-ingress`, If I disable the selfHeal feature, I will get a warning about shared resources between `nginx-ingress` and `ingress-nginx` application and  `ingress-nginx-admission` serviceAccount is not created. That make me confused, I have checked and did not find out any application name `ingress-nginx`

**Comment by hjorth** [comment]
> Update: changing the application name to `ingress-nginx` solved the issue, my previous application name is `nginx-ingress`. 
> 
> 
> 
> With the application name being `nginx-ingress`, If I disable the selfHeal feature, I will get a warning about shared resources between `nginx-ingress` and `ingress-nginx` application and  `ingress-nginx-admission` serviceAccount is not created. That make me confused, I have checked and did not find out any application name `ingress-nginx` 

see https://argo-cd.readthedocs.io/en/stable/faq/#why-is-my-app-out-of-sync-even-after-syncing
