### ISSUE TITLE
Update CRDs to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by chgl** [argoproj/argo-cd#5515]
# Summary

The current CRDs are using v1beta1 of the CustomResourceDefinition (https://github.com/argoproj/argo-cd/tree/master/manifests/crds). We should upgrade it to v1.

# Motivation

v1beta1 is deprecated since Kubernetes v1.16.

# Proposal

Upgrade to v1. The ArgoCD Helm chart CRDs have been updated https://github.com/argoproj/argo-helm/pull/545 or are in the process of being updated https://github.com/argoproj/argo-helm/pull/576.

I can definitely create a PR for this!

**Comment by jannfis** [comment]
Hi @chgl, thanks for bringing this issue up and also for the offer to create a PR for this :)

If you'd like to start working on this, this would be much appreciated. Please be aware that our CRDs are generated, I guess your best bet for getting started is to look at https://github.com/argoproj/argo-cd/tree/master/hack/gen-crd-spec and at the `openapigen` target in our Makefile at https://github.com/argoproj/argo-cd/blob/824ff732a2a34874c24fff4af1babc382ecb765a/Makefile#L179
