### ISSUE TITLE
CLI should not display empty tool version fields from server

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#5519]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

With 1.8.4, we have disabled the output of installation specific version information to unauthenticated consumers of the version endpoint. However, this looks funny when using `argocd version` and not being authenticated.

**To Reproduce**

Run `argocd version` with an unauthenticated client:

```
argocd: v1.8.4+28aea3d
  BuildDate: 2021-02-05T17:54:42Z
  GitCommit: 28aea3dfdede00443b52cc584814d80e8f896200
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.8.4+28aea3d
  BuildDate: 
  GitCommit: 
  GitTreeState: 
  GoVersion: 
  Compiler: 
  Platform: 
  Ksonnet Version: 
  Kustomize Version: 
  Helm Version: 
  Kubectl Version: 
  Jsonnet Version: 
```
**Expected behavior**

The CLI should detect the empty version information and not display the rows at all.

**Version**

Affects 1.8.4 and 1.7.12

**Comment by shubhamagarwal19** [comment]
@jannfis, thanks for the pointing out the issue. Maybe i can take this up ?

**Comment by jannfis** [comment]
@shubhamagarwal19 Awesome, thank you! As discussed, I'll assign the issue to me.
