### ISSUE TITLE
Deprecate docs on argoproj.github.io

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#5535]
# Summary

Now as the migration of our docs to readthedocs.io has been finished, we should go ahead and deprecate and archive the documentation on argoproj.github.io.

# Motivation

Many people will have bookmarks pointing to argoproj.github.io/argo-cd/ docs. We need to make them aware that documentation has a new home, point the users to the new location and kindly ask them to update their bookmarks.

# Proposal

For this, I think we have to:

* Disable automatic builds of our docs and pushes to gh-pages branch in our CI, so that the docs won't be updated automatically anymore.
* Put a sticky (non-disappearing) banner at the top of the page on gh-pages docs with a link to new docs. Currently, there is a banner saying "You are not reading latest version of the docs" with a link to the stable version, but that banner is non-sticky and disappears once you begin scrolling down.
* The message on the banner should clearly state that docs on argoproj.github.io are considered to be deprecated now

**Comment by alexmt** [comment]
Currently, if the user landed on https://argoproj.github.io/argo-cd/ the website is showing a warning that this is documentation of an unreleased version and provides a link to the stable version hosted at RTD.  This is accurate since we continuously publish to both gh-pages and RTD. So another option is to just keep gh-pages as is .

**Comment by jannfis** [comment]
@alexmt Yes, but shouldn't we disable automatic builds of gh-pages instead? IMHO, it can become confusing. I think we should make a hard cut. Also, the banner we show will disappear once user starts scrolling, so if a user has a bookmark to e.g. an anchor on a page, they won't notice the banner at all unless they scroll back all the way up to the top.

**Comment by alexmt** [comment]
@jannfis , agree - it has been long enough since we switched to read the docs. I also think it is safe to do hard cut now.

**Comment by alexmt** [comment]
Created PR to stop publishing docs: https://github.com/argoproj/argo-cd/pull/6688

**Comment by jannfis** [comment]
We still need to make the warning sticky in `gh-pages` branch.

**Comment by alexmt** [comment]
Warning is updated now. Closing.
