### ISSUE TITLE
Infinite request on Logs

### ISSUE THREAD

**Issue by joevermonceda** [argoproj/argo-cd#5537]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

When new sync with new version the logs has infinite http request.

**To Reproduce**

Sync with new version

**Expected behavior**

Call request once

**Screenshots**

![image](https://user-images.githubusercontent.com/66237997/108191464-bb0ff780-7145-11eb-8aee-60ec07b94393.png)

**Version**

```shell
v1.8.1+c2547dc
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by rbreeze** [comment]
Are you using the `Follow` option? And are you viewing aggregated logs for a Deployment, ReplicaSet etc. or are you viewing logs for a single pod?

**Comment by alexmt** [comment]
@joevermonceda please also specify your Argo CD version

**Comment by joevermonceda** [comment]
@alexmt version: v1.8.1+c2547dc

**Comment by joevermonceda** [comment]
@rbreeze im viewing logs for a single pod?

**Comment by rbreeze** [comment]
Can you see if this persists in v2.0?
