### ISSUE TITLE
unable to pull helm charts from oci registry (InvalidSpecError)

### ISSUE THREAD

**Issue by sean-mcgimpsey** [argoproj/argo-cd#5558]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When attempting to pull a chart from **aws ecr**, i receive the following helm error 
```shell
Unable to save changes: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = `helm chart pull https://<account id>>.dkr.ecr.<region>.amazonaws.com/helm-charts/appname:2.0.2` failed exit status 1: Error: ref may only contain a single colon character (:) unless specifying a port number
```

It looks like argocd is construction the wrong syntax for the `helm chart pull` command. I can reproduce the error from my terminal using a dummy registry (removing any reference to aws)

```shell
helm chart pull https://my-example-reg.example-registry/myapp:1.0.0
Error: ref may only contain a single colon character (:) unless specifying a port number
```

**To Reproduce**

* Add repo to argocd with oci support
* Confirm the repo exists within argocd, with oci enabled.
* Update an existing application definition use the oci repo. Example of my config below;

```yaml
project: default
source:
  repoURL: https://<aws_account_id>.dkr.ecr.<region>.amazonaws.com # replace with amazon account and region
  targetRevision: 0.2.0
  plugin:
    name: not-important-info
    env:
      - name: my-env-var
        value: test-var
  enableOCI: true
  chart: helm-charts/my-app
destination:
  namespace: test
  name: test-cluster
syncPolicy:
  automated:
    prune: true
    selfHeal: true
```

On save, you will receive the error reported above. 

**Expected behavior**

The application definition should successfully update app definition, and pull chart from aws ecr.

**Version**

1.8.4

**Comment by rami-vemula-01** [comment]
Experienced the same issue with Azure ACR as well. Any resolutions?

**Comment by sean-mcgimpsey** [comment]
i think the repo should be added without the protocol 
argocd repo add <aws_account_id>.dkr.ecr.<region>.amazonaws.com --type helm --name charts --enable-oci

However argocd is not able to obtain token and authenticate (for ecr at least, as it needs to first obtain a session token.

**Comment by rami-vemula-01** [comment]
Let me try your suggestion with ACR. @sean-mcgimpsey

**Comment by rami-vemula-01** [comment]
@sean-mcgimpsey Your suggestion is not working either, there is altogether different issue.

When I use - 
**Repository URL** - https://abcpqr.azurecr.io/helm/v1/repo
**Chart** - hello-world
**Version** - 1

I am getting below error - 
`Unable to create application: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = `helm chart pull https://abcpqr.azurecr.io/helm/v1/repo/hello-world:1.0.0` failed exit status 1: Error: ref may only contain a single colon character (:) unless specifying a port number`

When I use - 
**Repository URL** - abcpqr.azurecr.io/helm/v1/repo
**Chart** - hello-world
**Version** - 1

I am getting below error - 
`Unable to create application: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = `helm chart pull abcpqr.azurecr.io/helm/v1/repo/hello-world:1.0.0` failed exit status 1: Error: abcpqr.azurecr.io/helm/v1/repo/hello-world:1.0.0: not found`

When I use (which I assume to form a correct URL based on Microsoft ACR Documentation - https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos)
**Repository URL** - abcpqr.azurecr.io/helm/
**Chart** - hello-world
**Version** - 1

I am getting below error - 
`Unable to create application: application spec is invalid: InvalidSpecError: repository not accessible: Get "abcpqr.azurecr.io/helm/index.yaml": unsupported protocol scheme ""`

I tried different other combinations and nothing is working. So I am blocked all ways,

**Comment by perezjasonr** [comment]
this definitely looks like its a bug. helm chart pull does not use that syntax. it wants --version not a colon.

```
HELM_EXPERIMENTAL_OCI=1 helm pull https://github.com/elastic/cloud-on-k8s elastic/eck-operator-crds:1.4.1
Error: chart "eck-operator-crds:1.4.1" matching  not found in elastic index. (try 'helm repo update'): no chart name found
```

now notice how this has no error output and then i can unpack the local tar
```
HELM_EXPERIMENTAL_OCI=1 helm pull https://github.com/elastic/cloud-on-k8s elastic/eck-operator-crds --version 1.4.1
tar -tvf eck-operator-crds-1.4.1.tgz
-rw-r--r-- 0/0             460 2021-03-10 09:12 eck-operator-crds/Chart.yaml
-rw-r--r-- 0/0              43 2021-03-10 09:12 eck-operator-crds/templates/NOTES.txt
-rw-r--r-- 0/0            1562 2021-03-10 09:12 eck-operator-crds/templates/_helpers.tpl
-rw-r--r-- 0/0          172174 2021-03-10 09:12 eck-operator-crds/templates/all-crds.yaml
-rw-r--r-- 0/0             349 2021-03-10 09:12 eck-operator-crds/.helmignore
-rw-r--r-- 0/0            1065 2021-03-10 09:12 eck-operator-crds/README.md
```

using the following source section results in the error mentioned by original issue submitter:

```
source:
    chart: elastic/eck-operator-crds
    repoURL: https://github.com/elastic/cloud-on-k8s
    targetRevision: 1.4.1
status:
  conditions:
  - lastTransitionTime: "2021-03-18T20:39:19Z"
    message: 'rpc error: code = Unknown desc = `helm chart pull https://github.com/elastic/cloud-on-k8s/elastic/eck-operator-crds:1.4.1`
      failed exit status 1: Error: ref may only contain a single colon character (:)
      unless specifying a port number'
```

and no shaving off the https doesn't help:
```
HELM_EXPERIMENTAL_OCI=1 helm chart pull github.com/elastic/cloud-on-k8s/elastic/eck-operator-cr
ds:1.4.1
1.4.1: Pulling from github.com/elastic/cloud-on-k8s/elastic/eck-operator-crds
Error: github.com/elastic/cloud-on-k8s/elastic/eck-operator-crds:1.4.1: not found
```

that :<version> need to be --version <version>

**Comment by sean-mcgimpsey** [comment]
I was able to get this working as intended by; 
Adding the repo directly via the cli. https://argoproj.github.io/argo-cd/user-guide/private-repositories/. When adding I passed the `--enable-oci flag`. I did not pass the protocol with the repo url (no http/https).

Then when using this oci repo with my application definition, i added `repoUrl` without the protocol (no http/https), and passed the option `enableOCI: true` in the yaml . See below for example. 

```
project: default
source:
  repoURL: <aws_account_id>.dkr.ecr.<region>.amazonaws.com # replace with amazon account and region
  targetRevision: 0.2.0
  plugin:
    name: not-important-info
    env:
      - name: my-env-var
        value: test-var
  enableOCI: true
  chart: helm-charts/my-app
destination:
  namespace: test
  name: test-cluster
syncPolicy:
  automated:
    prune: true
    selfHeal: true
```

Though this is working as expected, i feel like there is still a big documentation piece required here. 
I would close this issue but it looks like others still have problems - @perezjasonr  you should export the var.

**Comment by perezjasonr** [comment]
is that enableOCI option new? I'm trying to follow your steps and it ignored it when I originally added the app object, then when I tried to edit it and add it manually

source:
    chart: elastic/eck-operator-crds
    repoURL: github.com/elastic/cloud-on-k8s
    targetRevision: 1.4.1
    enableOCI: true
    
    it gave me:
    <nil>: Invalid value: "The edited file failed validation": ValidationError(Application.spec.source): unknown field "enableOCI" in io.argoproj.v1alpha1.Application.spec.source

**Comment by sean-mcgimpsey** [comment]
Which version are you running? It's available to me on version 1.8.4

**Comment by perezjasonr** [comment]
> my argo isn't that old, v1.8.2

but also those links I provided are current/master, none of them have it in the CRD. So I can't see how you got it in yours when its not even in current source.
are they really in your CRDs?

**Comment by sean-mcgimpsey** [comment]
Actually, though the manifest has enableOCI declared, it doesn't exist in the result (it applies without errors).

**Comment by perezjasonr** [comment]
then it probably works initially applying it (are you just doing kubectl apply?) but if you actually edit it or something then validation is enforced.
either way i'd be willing to bet its not in your CRDs based on my links above because even master doesn't have it.

**Comment by harryleesan** [comment]
> i think the repo should be added without the protocol
> argocd repo add <aws_account_id>.dkr.ecr..amazonaws.com --type helm --name charts --enable-oci
> 
> However argocd is not able to obtain token and authenticate (for ecr at least, as it needs to first obtain a session token.

@sean-mcgimpsey How did you manage to get argocd to obtain token and authenticate?

**Comment by sean-mcgimpsey** [comment]
By using a Kubernetes cronjob that refreshes token to a secret available to Argo every 6 hours. Works well.

**Comment by perezjasonr** [comment]
@sean-mcgimpsey 
just tried it in a manifest and it didn't like it:
kubectl apply -f myargoapp.yaml
error: error validating "myargoapp.yaml": error validating data: ValidationError(Application.spec.source): unknown field "enableOCI" in io.argoproj.v1alpha1.Application.spec.source; if you choose to ignore these errors, turn validation off with --validate=false

can you confirm that enableOCI was under source like this?

source:
...
  enableOCI: true

**Comment by perezjasonr** [comment]
ive updated my version to 1.8.7 thats past the one youre using now and i still got the same validation message.

then I tried --validate=false just to let it go through, which results in:

```
message: 'rpc error: code = Unknown desc = `helm chart pull jaegertracing.github.io/helm-charts/jaegertracing/jaeger-operator:2.19.1`
      failed exit status 1: Error: jaegertracing.github.io/helm-charts/jaegertracing/jaeger-operator:2.19.1 ... not found
```

thats including everything mentioned above, no https://, and with enableOCI true.
and of course this works fine:

`helm pull https://jaegertracing.github.io/helm-charts jaegertracing/jaeger-operator --version 2.19.1`

the tar.gz shows up locally.

the only other thing I can think of is the --enable-oci flag on the repo itself, maybe that part isn't exactly how yours is? Can you show what it looks like, even if its redacted from the configmap?  probably an oci entry, im just guessing based on my attempt to reverse engineer the golang but it looks like it would be something like this:

```
- type: helm
   url: https://jaegertracing.github.io/helm-charts
   name: jaeger-helm-repo
   enableOci: true
```

so does this actually work for you?
`helm chart pull <aws_account_id>.dkr.ecr.<region>.amazonaws.com:0.2.0 # where theres no https://`

if that does work, then the last thing I can conclude is that both the jaeger and elastic helm repo's don't "speak" OCI.

**Comment by sean-mcgimpsey** [comment]
yes, I  now have a complete working example of ArgoCD playing nicely with an OCI repo (AWS ECR). 
 
I'm not entirely sure what you are trying to accomplish but based on the outputted error i'd say there is a problem with the repo / the repo doesnt talk OCI.

**Comment by clarkmcc** [comment]
So what has to happen to get ArgoCD to work with OCI repos? I'm trying to [follow the docs](https://argo-cd.readthedocs.io/en/stable/user-guide/oci/). I'm on 2.14.11. I've created an app
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dragonfly
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly
    targetRevision: v1.34.1
    path: .
    helm:
      valuesObject: {}
  destination:
    server: 'https://35.230.29.163'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

```

But argocd gives me this error

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = failed to list refs: unsupported scheme "oci"
```

<img width="2654" height="284" alt="Image" src="https://github.com/user-attachments/assets/5da86cc8-ce47-4998-907e-25d1e6fabf48" />

What am I missing?

---
Edit, I figured this out, but sadly this wasn't mentioned in the OCI documentation link I sent. Would be great if docs were improved on this.

1. Under **Settings > Repositories** click **Connect Repo**
2. Set the **Connection Method** to HTTPS
3. Set the **Type** to Helm (for my case at least)
4. Under **Repository URL** paste the repo, for me the link I got from Dragonfly docs was this `oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly`, but in ArgoCD I just needed `oci://ghcr.io/dragonflydb/dragonfly/helm`
5. At the very bottom, check **Enable OCI**
6. Create an app using the new repository. The chart and version didn't auto-populate like for git-based helm repos.
