### ISSUE TITLE
ArgoCD Forms aren't customer friendly

### ISSUE THREAD

**Issue by rajivml** [argoproj/argo-cd#5568]
# Summary

ArgoCD forms aren't that customer friendly today, looks the persona targeted are only DevOPS and developers but with some modifications to forms, argoCD can be used as an ALM tool as well i.e. a software which enterprises/b2b companies can deploy to their end users kubernetes environment through which software life cycle (installs / upgrades/ patches) can be managed on K8's irrespective of wherever kubernetes is hosted think of it as an operator life cycle management tool which Openshift has but it's tied to Openshift ecosystem and involves vendor lock in 

I have explored for such tools and there aren't any open source tools in this space and argo has all those features to become one except the forms which has to be re-designed a lot and in the past also I have logged few tickets on similar lines. But yeah if there is any interest on similar lines am happy to discuss my use case further am not sure what's the right form to discuss this though

Anyhow, coming to my original problem, at the time of configuring an application, am passing values-test.yaml but both values.yaml and values-test.yaml i.e. the merge of fields present in both the files are getting rendered as a form, but I just want values-test.yaml to be rendered as form and looks like it's not possible in Argo today

# Motivation

We are working on a project where we are exposing ArgoCD as an application lifecycle management tool (ALM) i.e. our customers will be using ArgoCD to manage the life cycle (install / upgrade) of products deployed on K8's via ArgoCD UI , it's something like OperatorUI framework which openshift offers or the marketplace UI which aws or azure provides

When we are taking input from customers for example what all products to install vs not, we should exclude as much clutter as possible and only the values they are supposed to override should be exposed to them i.e. in my case the values under values-test.yaml 

**Expected Behaviour:**

Only these values (values-test.yaml) should get rendered as a form and the values.yaml should get considered as default in the background

![image](https://user-images.githubusercontent.com/46923567/108614789-b1c3ab00-7423-11eb-9d91-65dfe7fa355d.png)

**Actual Behaviour:**
Merge of values.yaml and values-test.yaml is getting rendered as a form,

![image](https://user-images.githubusercontent.com/46923567/108614827-eafc1b00-7423-11eb-9c82-a66d199d5b39.png)

# Proposal

When we pass values-test.yaml can we just render only values-test.yaml as form and in the background consider values.yaml as default automatically

**Comment by rbreeze** [comment]
Duping to #5569
