### ISSUE TITLE
Memory leak when cluster name is specified with a trailing slash

### ISSUE THREAD

**Issue by ntoofu** [argoproj/argo-cd#5578]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

If a server URL in `Application` resource has a trailing slash, memory consumption of `argocd-application-controller` increases gradually up to more than 10 GiB.

Probably the cause is that [the cluster cache is searched by given argument which may contain a trailing slash](https://github.com/argoproj/argo-cd/blob/7ec8b266f865ae996c786629662618bd5fa43095/controller/cache/cache.go#L242) but [cluster URL from util/db is used as when storing cache](https://github.com/argoproj/argo-cd/blob/7ec8b266f865ae996c786629662618bd5fa43095/controller/cache/cache.go#L315). This inconsintency could cause cache miss every time.

**To Reproduce**

1. Prepare cluster with kind `kind create cluster`
2. Install prometheus stack `helm install prometheus-operator prometheus-community/kube-prometheus-stack`
3. Set up Argo CD `kustomize build "https://github.com/ntoofu/argo-cd-issue-demo-repo.git/?ref=d811164490e714f979452bb6dca629785d8150c1" | kubectl apply -f -`
    * This command installs Argo CD to the `kind` cluster and registers the cluster to the Argo CD as an external cluster. See [demo repository](https://github.com/ntoofu/argo-cd-issue-demo-repo/) for more details.
    * For simplicity, just a single `kind` cluster is used here, but I observed the same issue by using the other cluster out of `kind` and register it to Argo CD on a `kind` cluster.
4. Add some applications whose `spec.destination.server` has a trailing slash `kubectl apply -f https://raw.githubusercontent.com/ntoofu/argo-cd-issue-demo-repo/d811164490e714f979452bb6dca629785d8150c1/application_bad.yaml`
5. After several hours, check the memory usage of `argocd-application-controller` from grafana
6. Delete the application created the previous step, restart `argocd-application-controller`, and retry step 4 and 5 with `application_good.yaml` which contains no trailing slash instead of `application_bad.yaml`

**Expected behavior**

Either of the following:

* Application cannot be created when the destination server URL has a trailing slash
* Argo CD works well without insane memory consumption even if the destination server URL has a trailing slash

**Screenshots**

* With `application_bad.yaml` (green line)

![Screenshot_2021-02-22 Grafana](https://user-images.githubusercontent.com/22923783/108764464-fb340780-7595-11eb-90c5-c321fc3b7382.png)

* With `application_good.yaml` (yellow line)

![Screenshot_2021-02-22 Grafana(1)](https://user-images.githubusercontent.com/22923783/108764480-025b1580-7596-11eb-9117-f623740c1a4c.png)

**Version**

```shell
$ kubectl exec -n argocd -it argocd-application-controller-0 -- argocd version
argocd: v1.8.5+d0f8edf
  BuildDate: 2021-02-20T05:38:50Z
  GitCommit: d0f8edfec804c013d4fc535e8b9022eb47602617
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
command terminated with exit code 1

$ kubectl get po -n argocd argocd-application-controller-0 -o 'jsonpath={.status.containerStatuses[]}' | jq .
{
  "containerID": "containerd://2860cd1d4e4be349e0f49933d02ef0d9c2927d637bbe7ecb6b9cfbada37a619a",
  "image": "docker.io/argoproj/argocd:v1.8.5",
  "imageID": "docker.io/argoproj/argocd@sha256:632e8da815b936dcd0c175fa06d5f095ee887b741c4ab6d8f48852145581c1a4",
  "lastState": {},
  "name": "argocd-application-controller",
  "ready": true,
  "restartCount": 0,
  "started": true,
  "state": {
    "running": {
      "startedAt": "2021-02-22T03:51:20Z"
    }
  }
}

$ kind version
kind v0.9.0 go1.15.2 linux/amd64

$ kustomize version
{Version:kustomize/v4.0.1 GitCommit:516ff1fa56040adc0173ff6ece66350eb4ed78a9 BuildDate:2021-02-13T21:21:14Z GoOs:linux GoArch:amd64}

$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

**Logs**

Sorry, I cannot find any significant logs.

**Comment by kshamajain99** [comment]
I will take a look

**Comment by ntoofu** [comment]
Thank you for fixing the issue. I tried the procedure for reproducing the issue with new `latest` images, and confirmed the memory consumption of argocd-application-controller was less than 1GiB over 6 hours.
![Screenshot_2021-03-01 Home - Grafana](https://user-images.githubusercontent.com/22923783/109541235-ecee6a00-7b06-11eb-9cfb-fdc19f0677e1.png)
