### ISSUE TITLE
Provide first-class support for accessing Git and Helm repos through HTTP proxies

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#5581]
# Summary

We should provide first class support for accessing Git and Helm repositories through HTTP proxy servers.

# Motivation

Often times, Git and Helm repositories connected via HTTPS require the use of HTTP proxy servers to be successfully accessible. Currently, people will need to configure a global HTTP proxy using the proxy environment variables (`http_proxy`, `https_proxy`) for both, API server and Repo Server. Also, they will have to configure exceptions (i.e. `no_proxy`) for the K8s control plane access, because the proxy settings will be used for all HTTP clients within that pod, so also K8s API access. And in the case of a mix of  internal repositories (e.g. GHE, GitLab on-prem) and external repositories (e.g. public GitHub, or Helm repos)

This is not very user friendly and also quite error prone, and might also lead to frustration when adding new clusters (e.g. new cluster API not yet in `no_proxy` exception).

# Proposal

* Add a `httpProxy` configurable to HTTPS-connected Git and Helm repository configuration
* Option should also be exposed via CLI (e.g. `argocd repo add https://github.com/argocd-example-apps --http-proxy http://some.proxy:3128/`) and the UI
* Use the configured proxy for outbound HTTP connections when accessing Git or Helm repositories, even when global `http_proxy` and `https_proxy` env vars are set

**Comment by mnacharov** [comment]
I want to implement this feature, can you assign issue to me?

**Comment by jannfis** [comment]
Hey @mnacharov, thank you! Please be my guest and feel free to bug me with any questions you might have while implementing this.

**Comment by sbose78** [comment]
+1 on this requirement.

**Comment by chetan-rns** [comment]
Hi @mnacharov, are you planning to work on this issue :) If not, I can start with it.
