### ISSUE TITLE
Custom Certificate Authorities not being respected in Git Applications with Helm dependencies

### ISSUE THREAD

**Issue by rbkaspr** [argoproj/argo-cd#5596]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

My organization is using a Helm repo (using goharbor) too host custom charts on our network. This Helm repo is using a certificate signed by a non-public CA. When we add the certificate to the ArgoCD certificate store, and create Application specs that are configured to pull directly from Helm, ArgoCD accepts the certificates and is able to retrieve charts without issue.

We're encountering a case where our development teams are creating Git-based Applications that have Helm dependencies on charts in out self-hosted Helm repo. In the case of these apps, when Helm goes to to a dependency update, it rejects the cert from Harbor as being signed by an unknown authority. In this case, whatever certificate injection Argo is doing for a Helm-based app is clearly not being done when resolving Helm dependencies in a Git-based app. Discussed in-depth in [this thread](https://argoproj.slack.com/archives/CASHNF6MS/p1614199573256000)

**To Reproduce**

1. Create a Git repo containing a Helm chart which has a dependency on a chart hosted in a Helm repo with a self-signed certificate
2. Create an Application using that Git repo
3. Watch the errors fly

**Version**

```shell
v1.8.5
```

**Comment by shubhamagarwal19** [comment]
Hey @jannfis, can you assign this to me? already working on it !!
