### ISSUE TITLE
argocd app list filter by repo

### ISSUE THREAD

**Issue by moensch** [argoproj/argo-cd#5602]
# Summary

I would love to be able to invoke `argocd app list` and filter applications by repository.

# Motivation

For a CI use case, when my CI system is already within t he context of a given git repo, I need to be able to list all argo cd application associated with this repository.

The current workaround is something like:
```argocd app list -p staging-mdw1-autobots -o json | jq '.[] | select(.spec.source.repoURL=="git@github.com:myorg/myrepo.git") | .metadata.name'```

Or a combination of `argocd app list` and `grep` and `awk`.

# Proposal

Would have to extend `ApplicationQuery` with a string type for `repo`:

https://github.com/argoproj/argo-cd/blob/2a1a03a91996c176dabe7b2ee7fe49cd6ac58b62/server/application/application.proto#L17-L29

And probably add a new `FilterByRepo` function to argo utils: https://github.com/argoproj/argo-cd/blob/2a1a03a91996c176dabe7b2ee7fe49cd6ac58b62/util/argo/argo.go

**Comment by andy-v-h** [comment]
@moensch  Could this be a list of repositories? Also does it need to be a repo or would a string match make sense? E.g., if  wanted to say list my applications that are deployed from a particular org.
