### ISSUE TITLE
kube-prometheus-stack latest chart fails to work with argocd and default values generated

### ISSUE THREAD

**Issue by KlavsKlavsen** [argoproj/argo-cd#5608]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**
When trying to install latest kube-prometheus-stack:
```
  - name: kube-prometheus-stack
    version: 13.13.0
    repository: https://prometheus-community.github.io/helm-charts
```
With default values given in values yaml (generated with: helm inspect values prometheus-community/kube-prometheus-stack
and output indented with 2 spaces and kube-prometheus-stack: put in top.

argocd fails generating manifests and outputs this (which i ran locally and get the same error)

```
$ helm template . --name-template kube-prometheus-stack --namespace monitoring --values values.yaml --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions apps/v1 --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1beta1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1 --api-versions flowcontrol.apiserver.k8s.io/v1beta1 --api-versions argoproj.io/v1alpha1 --api-versions bitnami.com/v1alpha1 --include-crds
coalesce.go:94: warning: skipping globals because destination global is not a table.
coalesce.go:94: warning: skipping globals because destination global is not a table.
Error: template: kube-prometheus-stack/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml:1:18: executing "kube-prometheus-stack/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml" at <.Values.prometheusOperator.admissionWebhooks.enabled>: nil pointer evaluating interface {}.admissionWebhooks

Use --debug flag to render out invalid YAML
A clear and concise description of what the bug is.
```

**Version**

```shell
argocd: v1.8.4+28aea3d
  BuildDate: 2021-02-05T17:54:42Z
  GitCommit: 28aea3dfdede00443b52cc584814d80e8f896200
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified 
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by rbankole** [comment]
same issue here. i believe it's the chart and not argocd

**Comment by KlavsKlavsen** [comment]
Well - if you JUST run helm template chartname --values same-valuesfile 
it does not fail. Its all those extra options argo-cd adds to it - that does not seem to cover all the --api-versions this chart needs?

**Comment by dcardellino** [comment]
Is there any update on this issue?

**Comment by pseymournutanix** [comment]
I also see this with 2.3.0-rc1 fwiw

**Comment by fr3fou** [comment]
Is there a workaround to this?

**Comment by caerulescens** [comment]
The latest releases for `argo-cd` helm chart and `kube-prometheus-stack` helm chart work together now; see [here](https://github.com/argoproj/argo-cd/issues/820#issuecomment-1246960210). The important part is specifying `- ServerSideApply=true` for `kube-prometheus-stack`. This issue should be closed because the default valued charts work together; I tested using `minikube` locally.

**Comment by blakepettersson** [comment]
I can confirm that this hasn't been anything I've been able to reproduce lately.

**Comment by caerulescens** [comment]
Can still confirm that ArgoCD deploys `kube-prometheus-stack` successfully.
