### ISSUE TITLE
More invalid assumptions about OCI helm repo paths

### ISSUE THREAD

**Issue by cabrinha** [argoproj/argo-cd#5628]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
In https://github.com/argoproj/argo-cd/pull/5179, it was assumed that only OCI enabled Helm repos used sub-path naming of `https://repo-url/repo-name/chart-name`, which is untrue in the case of the ChartCenter helm repo.

This repo uses a custom index with support for repo namespacing. It is not an OCI compatible helm repository.

Here is an example, using the argo-cd helm chart, pulled through ChartCenter: https://chartcenter.io/argo/argo-cd

```
helm repo add center https://repo.chartcenter.io
helm install argo-cd center/argo/argo-cd
```

**To Reproduce**

Add ChartCenter as a repo to ArgoCD: `argocd repo add center https://repo.chartcenter.io`

Then, deploy any application using that repo.

**Expected behavior**

I expected the helm charts to be pulled through without OCI enabled.

**Version**

```shell
v1.8.4
```

**Logs**

```
Unable to save changes: application spec is invalid: InvalidSpecError: repository not accessible: `helm registry login https://artifactory.my-domain/artifactory/chartcenter-helm-virtual --username ****** --password ******` failed exit status 1: WARNING: Using --password ****** the CLI is insecure. Use --password-stdin. time="2021-02-26T19:49:03Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: login attempt to https://artifactory.my-domain/v2/ failed with status: 404 Not Found" Error: login attempt to https://artifactory.my-domain/v2/ failed with status: 404 Not Found
```

We probably need to remove the assumption about OCI helm repos or introduce a way to tell ArgoCD that the repo is not OCI compatible.

**Comment by igaskin** [comment]
does this issue persist for other repos given that chartcenter has been sunset?

**Comment by cabrinha** [comment]
Pretty sure ChartMuseum has repo namespacing / multitenancy as a feature using the `--depth` flag, so this could crop up there too.

**Comment by jannfis** [comment]
Hm, we're probably trying to be too smart here. I think I have seen a similar issue with Artifactory repositories, which also support namespaces for referencing to charts.

If helm supports this without enabling OCI, we should too, IMHO.

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/5888
