### ISSUE TITLE
Argo CD too frequently fetches Helm repo index that results in a lot of traffic

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#5659]
**Describe the bug**

Argo CD allows creating an application that points directly to the Helm repository. If chart version is not specified explicitly then Argo CD loads whole repository index multiple time per second that results in a lot of traffic and might be costly. 

**To Reproduce**

The issue can be reproduced by just creating an application that points directly to the Helm repository. Every reconciliation argocd loads repo index file.

**Expected behavior**

The index file should be cached or the number of queries should be reduced.

**Version**

```shell
v1.8.6
```

**Comment by jgwest** [comment]
Discussed on https://github.com/argoproj/argo-cd/discussions/5598
