### ISSUE TITLE
Support unset plugin-env

### ISSUE THREAD

**Issue by yujunz** [argoproj/argo-cd#5681]
# Summary

Support unset plugin-env from cli

# Motivation

Plugin env can be set from CLI since #4923 but unset is not supported at the moment. 
In CI/CD pipelines, we have use case to clear the setting.

# Proposal

`argocd app unset --plugin-env ENV_NAME` should remove the env from app.

**Comment by chetan-rns** [comment]
@jannfis Could you please assign me this issue? I'm happy to raise a PR :)

**Comment by jannfis** [comment]
Sure, thank you @chetan-rns :)
