### ISSUE TITLE
'log out' link does not change to 'log in' after token expires

### ISSUE THREAD

**Issue by glhdavenport** [argoproj/argo-cd#5687]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When anonymous is enabled but a user has logged in, once the session has expired, the 'log out' button does not change back to 'log in', even after navigating to another page. This is confusing for users who think they are still logged in and try to perform actions. We often have to use the cliche 'log out and log back in" to help our users work around this bug in the UI. It isn't specific to any one browser. 

**To Reproduce**
-  Configure anonymous users where the default policy is readonly
- Configure a secondary policy where certain users have admin access, or access to to perform actions 
- Log in
- After the session has expired 'log out' will still appear even when navigating around. Perform an action and you will receive a permission error. (This is where we tell our users to log out and log back in)

**Expected behavior**

Ideally Argo Cd should show the correct status for a user, if they are logged in the “login/logout” link should show “logout”, if they are not logged in then it should show “login”

**Screenshots**

![Screen Shot](https://user-images.githubusercontent.com/35355469/109999638-a9932780-7ccf-11eb-8880-655e360d026c.png)

**Version**

```shell
v1.8.6+6dbbb18
```
![versions](https://user-images.githubusercontent.com/35355469/110001253-6a65d600-7cd1-11eb-908d-ca653bfb31d1.png)

**Logs**

**Comment by alexmt** [comment]
This bug annoys me a lot as well :) Every time I navigate to https://cd.apps.argoproj.io/applications I have to logout and login

**Comment by alexmt** [comment]
I believe the issue happens because the anonymous user feature is supposed to allow accessing Argo CD even without a token.

The valid but expired token is an edge case. So if API receives valid and expired tokens it should return 401 even if an anonymous user feature is enabled.

**Comment by jMarkP** [comment]
Interested in picking this up if that's OK? @alexmt from your comment it sounds like you're suggesting changing https://github.com/argoproj/argo-cd/blob/master/server/server.go#L902 to distinguish between 'has no token' and 'has expired token' (and I guess 'has invalid token'?) conditions. Is that correct? So:

- No token, anon access disabled => Deny
- No token, anon access allowed => Accept
- Invalid token => Deny
- Valid but expired token => Deny
- Valid and unexpired token => Accept

**Comment by jMarkP** [comment]
Have raised #5897 with what I think is a fix for this issue.

**Comment by alexmt** [comment]
Ops. https://github.com/argoproj/argo-cd/pull/5897 fixed the issue but at the same time, we broke auto-relogin feature.
