### ISSUE TITLE
Restructure `argocd-util` commands

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#5690]
# Summary

The `argocd-util` commands had been added organically because it used to be an internal tool. Since we are promoting it as an external user-facing tool the command structure should be reorganized.

# Motivation

Provide a clear, self-explanatory commands structure to improve user experience.

# Proposal

<details>
  <summary>Current commands structure:</summary>
  
```
apps
  diff-reconcile-results
  get-reconcile-results
config
  app
  cluster
  proj
  repo
projects
  generate-allow-list
  update-role-policy
rbac
  can
  validate
settings
  resource-overrides
  validate
version
export
help
import
kubeconfig
```
</details>

<details>
  <summary>New commands structure:</summary>
  
```
app
  spec
  diff-reconcile-results
  get-reconcile-results
cluster
  spec
  kubeconfig
proj
  spec
  generate-allow-list
  update-role-policy
repo
  spec
config
  resource-overrides
    health
    ignore-differences
    list-actions
    run-action
  rbac
    can
    validate
  validate
import
export
version
help
```
</details>

**Comment by sbose78** [comment]
> spec

Sorry, what does `spec` imply ? Is it the noun equivalent of `describe`?

**Comment by alexmt** [comment]
hello @sbose78 ,

The command is supposed to help generate resource spec from provided CLI arguments. Similar to `argocd app create` but instead of creating it just generates YAML/JSON. The `spec` is supposed to imply k8s resource specification. The first idea was to use the verb `generate` but I did not like it since it is not clear what will be generated. 

What do you think about `generate-spec`? It looks clear enough, a bit long but not terribly long:


```
argocd-util app generate-spec hello \
  --repo https://github.com/argoproj/argocd-example-apps \
  --project default --dest-name minikube --dest-namespace default
```

**Comment by sbose78** [comment]
Yes, this makes sense Alex. A lot cleaner.

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-cd/pull/5708
