### ISSUE TITLE
POD is not created always when a change is committed in GIt

### ISSUE THREAD

**Issue by aupadh12** [argoproj/argo-cd#5695]
Hi Team,

We have noticed that argocd does not always create a new pod after we make changes in the manifests files. As a result, the required changes are not sent to the live state.
It only takes effect when we delete the pod and a new pod is created.
We would like this to happen automatically.
Can someone please look into it?

Regards,
Ashutosh Upadhyay

**Comment by jkleinlercher** [comment]
Which changes do you mean? Changes in the Deployment/Pod spec should restart the pod automatically. Changes in config maps, secrets, ingress etc. do not restart pods automatically and I do think that works as designed. However, there are other methods how you can enforce pod restarts.

**Comment by aupadh12** [comment]
By chanages I mean the version of the images. For example, I have image version passed into the deployment as a volume mount where a file called application.yml is created. The data in this application.yml is coming from the configmap. So, when I change the image version in my configmap, the pods which are already running needs to be restarted in order for the new changes to take place. Do you think argo rollout can help here ?
