### ISSUE TITLE
kubernetes client logging (--gloglevel) stopped working

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#5697]
When attempting to debug a kubernetes issue and enable kubernetes client logging using our `--gloglevel` flag to api-server and controller, this no longer works. This was attempted on v2.0 (7ad79e5)

**Comment by kshamajain99** [comment]
Logging broke because k8s.io moved to klog/v2. Whereas argo-cd cli is setting verbose level to klog/v1.
