### ISSUE TITLE
v1.8.7 retagged?

### ISSUE THREAD

**Issue by sdelrio** [argoproj/argo-cd#5703]
When Homebrew updated argocd to v1.8.7  the sha was recorded as a97230859344f8906502763743717d7ad7339c55. However, it seems 1.8.76 has been retagged to eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416.

I did a PR (https://github.com/Homebrew/homebrew-core/pull/72635) to update the hash in the Homebrew formula, however, I'd like to double-check that this was intentional and that nothing's a miss here. Thanks!

**Comment by jannfis** [comment]
Hi @sdelrio, we do have a "rolling" tab called `stable`, but usually we don't re-tag any versions. 

The release tags are created and pushed to the repo by our release automation. I have double-checked the release binaries, and they are also built from the correct revision:

```
argocd: v1.8.7+eb3d1fb
  BuildDate: 2021-03-03T07:12:02Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: clean
```

I'm not sure where there https://github.com/argoproj/argo-cd/commit/a97230859344f8906502763743717d7ad7339c55 commit comes from, but GitHub says it doesn't belong to any branch or tag in our repository.

Did that only happen for 1.8.7, or previous versions as well?

**Comment by sdelrio** [comment]
It's the first time it happens to me, with v1.8.2 and v1.8.4 it didn't happened

brew also automates the builds. The only difference I found is that brew on the mac version there was a binary already build with that missing commit id a97230859344f8906502763743717d7ad7339c55

```
❯ argocd version
argocd: v1.8.7+a972308.dirty
  BuildDate: 2021-03-03T06:56:34Z
  GitCommit: a97230859344f8906502763743717d7ad7339c55
  GitTreeState: dirty
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
```
What I found (probably can't see with the copy/paste) is that the tag had an space after the 1.8.7 when brew (mac) upgrade to that version (" Upgrading argocd 1.8.4 -> 1.8.7 ") and the one giving error brew (linux) didn't had when saying "Upgrading argocd 1.8.4 -> 1.8.7"

```
❯ brew upgrade argocd
==> Upgrading 1 outdated package:
argocd 1.8.4 -> 1.8.7
==> Upgrading argocd 1.8.4 -> 1.8.7 
==> Downloading https://homebrew.bintray.com/bottles/argocd-1.8.7.catalina.bottle.tar.gz
```

**Comment by jannfis** [comment]
A quick research revealed that v1.8.7 was indeed released twice. @alexmt was that incidentally?

**Comment by sdelrio** [comment]
Thank you very much.
The PR for the homebrew-core is merged with the correct commit reference.
From my part the issue can be closed.

**Comment by kshamajain99** [comment]
@jannfis v1.8.7 was released twice and it was intentional.
