### ISSUE TITLE
Enable TLS between Argo CD and Redis

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#5707]
# Summary

The Redis cache installed by Argo CD has recently been upgrade to v6.2.1. Redis now supports TLS clients, so we should enable TLS by default.

# Motivation

Data transmitted between Argo CD components and Redis cache is potentially sensitive and therefore, the connection should be safely encrypted.

# Proposal

* Enable TLS between Redis and Argo CD by default. We may need a wrapper similar to Dex in order to support this (generating a certificate if none is user-provided) 
* Provide options to use a custom certificate for Redis (e.g. via a `Secret` mount into the Redis pods)
* Provide option to disable TLS for connections Redis (e.g. `--redis-plaintext) on Argo CD components

**Comment by lcostea** [comment]
@jannfis are you working on this?
If not I was thinking to take it myself as we are interested into having a more secure installation and tls falls into this category.

**Comment by mabushey** [comment]
Istio does this for you, don't try to reinvent the wheel.

**Comment by jannfis** [comment]
While I agree that mTLS feature of Istio would probably well suited for this purpose, we should keep in mind that Istio is pretty heavy-weight and not everyone has a service mesh or wants to setup one as well.

We'll not be reinventing the wheel by setting up TLS between the Redis client and the Redis server IMHO.

**Comment by lcostea** [comment]
After spending some time playing with redis and how tls is enabled for it this is how I would proceed:
- create an init container for the redis deployment, that will take care to generate the certificate and put it in a secret that it is mounted on redis container  and for the other components to access directly
- if the secret is already populated (can be done by the user with his own certificates), the init container will not do anything
- if the secret is missing, the same it will not do anything
- the other components (repo-server, application-controller, server) will check if the secret exists and if it does wait for its population to read the certificates for creating the redis client
- if there is a flag applied to the components, they will not check for tls secret and start the client without tls (so by default they will have tls enabled)
- I saw how dex wrapper was created and how it check for config changes in a loop, I guess a similar thing needs to be done for redis when the tls secret gets updated and I need to see how to recreate the client for the other components

**Comment by lcostea** [comment]
For progress I was able to generate the certificates, start a redis server instance with tls enabled and then create the redis clients (from server, repo-server and controller) with tls enabled. I am able to run the e2e tests local with tls enabled for redis (with some errors from 2-3 tests, but I am not sure they are related to redis tls). Now I am working on different configurations, like disable tls and generate or use a custom certificate.

**Comment by jannfis** [comment]
Hey @lcostea, did you made any progress on this? Are there any blockers?

**Comment by lcostea** [comment]
hey @jannfis 
The only blocker is time, I had a few tough weeks, but I plan to resume working on it this week.

**Comment by jannfis** [comment]
Hey @lcostea, how's the state of the things regarding Redis TLS? I'm asking because release 2.1 is due soon. If you still have no time to work on this, maybe I can pick up where you are at right now?

**Comment by lcostea** [comment]
@jannfis unfortunately I didn't have too much progress, so if you want to pick it up to make it in time for 2.1 it is fine with me. Most of my work has been around getting to start redis with the custom generated certificates, let me see if I can wrap it all together and push it to my remote.

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-cd/pull/6742
