### ISSUE TITLE
Allow users to abort the sync retry

### ISSUE THREAD

**Issue by dewan-ahmed** [argoproj/argo-cd#5716]
Currently when an ArgoCD app is out-of-sync, the sync process is retried for a certain period with increasing delay. While the sync retry is happening, the user cannot delete the application. The user is able to execute the app deletion command via CLI or UI. However, the deletion will take place once the sync retry process is completed - which can last for more than 3/4 minutes (attached screen-recording).

https://user-images.githubusercontent.com/30604461/110486963-85ff2100-80c3-11eb-88d3-22860942d908.mov

### Proposed solution:

If a user initiates an app deletion while the app is trying to sync, there could be a message to the user saying that the app is currently trying to sync. Would they want to abort this process or wait? If they choose to abort, sync retry should be immediately killed and the app deletion should execute. The user, however, can also choose to wait.
 
### Reasoning:

This will provide a better and informed user experience. This will also save users time waiting for app sync whereas they might want to delete the app immediately.

**Comment by dewan-ahmed** [comment]
https://user-images.githubusercontent.com/30604461/114925155-218f5a00-9e05-11eb-9142-ab44d3a5c030.mov

Hi @alexmt I deleted the app while it was syncing but I did not see an option for app termination. Please let me know a step to validate the "termination" option. Thanks.

**Comment by alexmt** [comment]
Thank you for checking it @dewan-ahmed ! The termination option should be available via application details page: 

 * navigate to app details page 
 * click on "Syncing" label in right top corner
 * the 'Terminate' button should be available at the top of sliding panel.

**Comment by dewan-ahmed** [comment]
https://user-images.githubusercontent.com/30604461/114942605-2828cc00-9e1b-11eb-8a23-4bb4e283f047.mov

thanks @alexmt 
I see the termination of sync option and closing this issue.
