### ISSUE TITLE
Target Revision changes to HEAD instead of a tag

### ISSUE THREAD

**Issue by bortek** [argoproj/argo-cd#5723]
For some reason Target revision setting for the ArgoCD App changes from the Tag to HEAD. I am not sure how long does it take but it is definitely days to weeks. I have setup few apps using Git Tag and after few weeks when I looked again it is pointing to HEAD.

To Reproduce

Create argocd app using https://github.com/argoproj/argo-rollouts repo and manifests/cluster-install as a path.
Set target revision to v2.1.0-3

Here is how my refs look like
git show-ref v2.1.0-3
7df69d5a46ee531fd1dcafe8979dfa465def8c1d refs/tags/v2.1.0-3

git rev-parse HEAD
7df69d5a46ee531fd1dcafe8979dfa465def8c1d

git log --all --decorate | grep 7df69d5a46ee531fd1dcafe8979dfa465def8c1d
commit 7df69d5a46ee531fd1dcafe8979dfa465def8c1d (HEAD, tag: v2.1.0-3, origin/master, origin/HEAD, master)

This looks similar to https://github.com/argoproj/argo-cd/issues/3577 but not the same since I have git tag in the logs and revs.

I am using Argocd installed from the operatorhub. So the version is v1.7.7+33c93ae

**Comment by bortek** [comment]
As you understand this is rather important to have ArgoCD App pointing to the code where the tag is pointing. You do not want your argocd app to suddenly start updating and using untested edge code just because someone pushed the latest untested updates to the repo.

**Comment by bortek** [comment]
Anyone ?

**Comment by rafilkmp3** [comment]
I want to deploy latest v1 tag
 
 Unable to save changes: application spec for prod-app-survey is invalid: InvalidSpecError: Unable to generate manifests in manifests: rpc error: code = Unknown desc = Unable to resolve 'v1' to a commit SHA

**Comment by jharris-tc** [comment]
can confirm this is still happening to me, not sure why. very annoying

**Comment by ricardoamaro** [comment]
Apparently, this is still an issue in 2024.
