### ISSUE TITLE
ConfigManagementPlugin enhancement - Parameters support in UI/CLI

### ISSUE THREAD

**Issue by kshamajain99** [argoproj/argo-cd#5734]
# Summary

Refer #5293

Currently, configuration management plugins allow specifying only a list of environment variables. We want to extend its functionality to provide a similar experience as first-class support for existing tools (Helm, Kustomize, Jsonnet, Ksonnet) as part of Config Management Plugin v2.0

# Motivation

Here list of advantages that first-class tools have:

* Argo CD provides list of available parameters, does not require user to guess which parameters are supported. For example it executes helm values and shows list of supported values in the UI
* Argo CD shows default values of each parameter. For example it detects list of images used in Kustomize based app and show image tags as default values
* User friendly UI: parameters are group logically, no rendered as just flat list ( for example Kustomize images are rendered separately from other parameters )

# Proposal

As part one of enhancement config management plugin will be running as a sidecar container in Argo CD repo-server pod. 
All it means that Argo CD CMP 2.0 is,
* A user-supplied container image with all the necessary tooling installed in it. 
* It runs as a sidecar in the repo server deployment and has shared access to the git repositories.
* It contains a CMP YAML specification describing how to render manifests.
* Its entrypoint is a lightweight API server that receives requests by the main repo-server to render manifests, based on the CMP specification.

We will need to brainstorm on how to extend parameters support.

**Comment by crenshaw-dev** [comment]
This is partially implemented. Closing this one and will continue tracking the last bit of work here: https://github.com/argoproj/argo-cd/issues/11754
