### ISSUE TITLE
Invalid Sementic Version

### ISSUE THREAD

**Issue by onuryartasi** [argoproj/argo-cd#5740]
**Describe the bug**
When I set helm version to range 1.0.* or *  got invalid sementic version.

**To Reproduce**

I added helm repository then click to create application button.
Later I filled to required textbox and  I set version section to * for a latest helm chart.

**Expected behavior**
Successfully added application and used to latest helm chart.
**Screenshots**

![image](https://user-images.githubusercontent.com/16039143/110798177-f4daa680-828a-11eb-83a4-b4c8a078c149.png)

**Version**

```shell
argocd: v1.8.7+eb3d1fb.dirty
  BuildDate: 2021-03-07T20:25:24Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: dirty
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.7+eb3d1fb
  BuildDate: 2021-03-03T07:13:34Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Logs**

```
ime="2021-03-11T14:10:01Z" level=info msg="received unary call /application.ApplicationService/Create" grpc.method=Create grpc.request.claims=null grpc.request.content="%!v(PANIC=String method: reflect.Value.Interface: cannot return value obtained from unexported field or method)" grpc.service=application.ApplicationService grpc.start_time="2021-03-11T14:10:01Z" span.kind=server system=grpc
time="2021-03-11T14:10:01Z" level=info msg="took to get index" seconds=0.007807421
time="2021-03-11T14:10:01Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = invalid constraint in index: Invalid Semantic Version" grpc.code=InvalidArgument grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2021-03-11T14:10:01Z" grpc.time_ms=33.873 span.kind=server system=grpc
```

**Comment by onuryartasi** [comment]
Okey, I resolved this problem. If sementic version of one or more chart is wrong in your chart repository then `Tracking and Deployment Strategies` can't work. Maybe invalid semver can be ignored.
![image](https://user-images.githubusercontent.com/16039143/110904880-b260aa80-831a-11eb-8df7-cead88c75796.png)
![image](https://user-images.githubusercontent.com/16039143/110904937-c5737a80-831a-11eb-87b4-7b431ac84352.png)

**Comment by alexmt** [comment]
Thank you for the information @onuryartasi ! 

I think you are right, it is better to ignore invalid semver. I want to reopen this bug. Let's change `MaxVersion` method to ignore invalid semver, instead of failing.

**Comment by onuryartasi** [comment]
I would love to improve this bug.
