### ISSUE TITLE
argocd app diff returns exit code 1

### ISSUE THREAD

**Issue by jdomag** [argoproj/argo-cd#5768]
# Summary

It would be great to get exit code 0 from command `argocd app diff APPNAME` even if there are some changes/differences. 

# Motivation

We have a pipeline where to each PR we want to add an output of command 'argocd app diff APPNAME --local .`. That would simplify review process. However our CICD tool crashed every time as that command return exit code of 1 when it finds a difference. Would be nice to have a flag that exits with 0 anyway.

**Comment by alexmt** [comment]
The `argocd app diff` intentionally returns a non-zero exit code so that CI could detect differences: https://github.com/argoproj/argo-cd/pull/1288/files#diff-95f228706705fc556fbb63b303d638ad4d4ddba8118a50dc83e344ac9b692d49R766


 I think this is an important use case. If this is not required in your case, can you add `argocd app diff APPNAME || true` to avoid crashing pipeline?

**Comment by jdomag** [comment]
That's exactly how I workaround this, however it's not best solution - now when pipeline step should fail due to some other reason e.g. wrong app name, it will be green anyway.

**Comment by jannfis** [comment]
I agree that having an option to change behavior on diff would be good, especially for automation. The `|| true` would likely catch all other errors as well (e.g. connection failures) and void them, which might not be the intention in pipelines.

So, we should stay with current default behavior (which is modeled after UN*X's `diff` command), but provide an option to change that. Git's `diff` has an option `--exit-code` that makes `git diff` exit non-zero on differences, so maybe we should go along with that.

I can imagine adding a flag `--exit-code` similar to `git diff`, but it takes a boolean value which defaults to `true`. To disable non-zero exit code on changes, user could specify `--exit-code=false`.

WDYT?

**Comment by jdomag** [comment]
sounds perfect for me
