### ISSUE TITLE
 Argo CD file descriptor leak that may lead to exhausting opened file descriptor limit

### ISSUE THREAD

**Issue by mayzhang2000** [argoproj/argo-cd#5779]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

There are places in the Argo codebases where temporary files are opened via the ioutil.TempFile​ call, then are written to and are either not closed at all or if the write operation fails, the opened temporary files are not closed. This leaves the (sometimes deleted) temporary file opened and creates a resource leak which can lead to exhausting the available file descriptor limit for a process.
The following code paths demonstrate this issue:
● argo-cd/reposerver/repository/repository.go#L556-L568 ● argo-cd/util/db/gpgkeys.go#L17-L28
● argo-cd/util/gpg/gpg.go#L156-L169
● argo-cd/util/gpg/gpg.go#L252-L264
● argo-cd/util/gpg/gpg.go#L277-L289
● argo-cd/util/gpg/gpg.go#L393-L407
● argo-cd/util/helm/cmd.go#L169-L179
● argo-cd/util/helm/cmd.go#L181-L191
● argo-cd/util/helm/cmd.go#L198-L211
● argo-events/sensors/triggers/argo-workflow/argo-workflow.go#L133-L138 ● argo-workflows/server/artifacts/artifact_server.go#L153-L163
● argo-workflows/workflow/artifacts/git/git.go#L40-L47

**To Reproduce**

Code below shows one of the above listed cases. The temporary file opened in the writeKeyToFile​ function in Argo CD is not closed if the ​ioutil.WriteFile​ call fails. Additionally, the file should be written to through the file object ​f​, instead of by the ioutil.WriteFile​ function. It seems this function was chosen to set particular file permissions. In such case, the temporary file name could be randomized with another function and the ​writeKeyToFile​ function could just use the i​ outil.WriteFile​ function to create and write the key file.
```
// Helper function to write some data to a temp file and return its path
func​ writeKeyToFile(keyData ​string​) (​string​, ​error​) { f, err := ioutil.TempFile(​""​, ​"gpg-public-key"​) if​ err != ​nil​ {
return​ ​""​, err
}
err = ​ioutil.WriteFile(f.Name(), []​byte​(keyData), ​0600​) if​ err != ​nil​ {
 }
os.Remove(f.Name())
 return​ ​""​, err
}
f.Close()
return​ f.Name(), ​nil

(a​ rgoproj/argo-cd/util/gpg/gpg.go#L156-L169​).
```
A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

fix the file descriptor leak cases due to lack of file close operations across Argo codebases. This can often be fixed by deferring the f​ .Close()​ operation along with checking its error result.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexmt** [comment]
Thank you for fixing it @ishitasequeira
