### ISSUE TITLE
 Argo CD command line does not warn about too broad permissions of Argo token file

### ISSUE THREAD

**Issue by mayzhang2000** [argoproj/argo-cd#5780]
# Summary

What change you think needs making.
Argo CD command line does not warn the user when they invoke commands when its ~/.argocd/config​ configuration file has too broad permissions. This may lead the user's Argo CD token to be exposed for a long time if the user misconfigured the file's permissions and did not notice it. As a result, this may allow an attacker to hijack the user's deployments on the Argo CD instance.
```
$ pwd
/Users/dc/.argocd
$ ls -la
total 8
drwxr-xr-x 3 dc staff 96 Mar 2 17:52 .
drwxr-xr-x+ 68 dc staff 2176 Mar 2 17:52 ..
-rwxrwxrwx 1 dc staff 401 Mar 2 17:51 config
$ argocd app list
NAME CLUSTER NAMESPACE PROJECT STATUS HEALTH SYNCPOLICY CONDITIONS REPO PATH TARGET
```

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

How do you think this should be implemented?
Check the Argo CD config file permissions during Argo CD command line invocations and warn the user if the file permissions are too broad. This will help users to keep their Argo CD token more secure and warn them if it was possible for the token to be exposed for other users.

**Comment by asingh016** [comment]
@alexmt  @mayzhang2000  We need to  consider what permission Argo is giving when creating the file and looks like argo-cd is giving full permission 0777
https://github.com/argoproj/argo-cd/blob/d6d620e98c2bdebf771fee262441e307b3b049b7/util/localconfig/localconfig.go#L106-L107


`https://pkg.go.dev/os`
`ModePerm = fs.ModePerm // Unix permission bits, 0o777`

 Do need to give file permission while creating the file and would 600 permission would be okay?

**Comment by ashutosh16** [comment]
@alexmt  @mayzhang2000  We need to  consider what permission Argo is giving when creating the file and looks like argo-cd is giving full permission 0777 to  the config file
https://github.com/argoproj/argo-cd/blob/d6d620e98c2bdebf771fee262441e307b3b049b7/util/localconfig/localconfig.go#L106-L107


`https://pkg.go.dev/os`
`ModePerm = fs.ModePerm // Unix permission bits, 0o777`

 Do we need to give permission while creating the file and would 600 permission be okay?

**Comment by alexmt** [comment]
Good point @ashutosh16 ! I agree argo should create config file with 0600 permissions.
