### ISSUE TITLE
Application OutOfSync due to PVs that are connected to PVCs

### ISSUE THREAD

**Issue by paulwollgast** [argoproj/argo-cd#5810]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

Hello everyone,

while deploying TiDB with ArgoCD I'm encountering a problem with PVs that are not recognized as being claimed by the according PVCs (which on the other hand are correctly recognized as shown in the screenshot below) and are marked for pruning by Argo automatically:

![Bildschirmfoto 2021-03-18 um 20 59 12](https://user-images.githubusercontent.com/37050770/111690840-fa596300-882d-11eb-8f7b-1d72c374cf8f.jpg)

The respective PVCs in the same deployment work just fine:

![Bildschirmfoto 2021-03-18 um 20 59 46](https://user-images.githubusercontent.com/37050770/111691054-2ffe4c00-882e-11eb-9099-0bf046748578.jpg)

I've seen [this](https://github.com/argoproj/argo-cd/issues/1250) thread already, however trying to add the annotations:
```
argocd.argoproj.io/compare-options: IgnoreExtraneous
argocd.argoproj.io/sync-options: Prune=false
```

didn't help either, the TiDB deployment is using a huge CRD file though, I was assuming that this could be the problem?

**To Reproduce**

Deploy the official Kubernetes manifest of TiDB as of: https://docs.pingcap.com/tidb-in-kubernetes/stable/configure-a-tidb-cluster

**Expected behavior**

There are no PVs shown as out of sync

**Version**

```shell
v1.8.6+6dbbb18
```

Any help would be much appreciated!

**Comment by romilpunetha** [comment]
I'm facing the same issue.  How did you solve this?

**Comment by romilpunetha** [comment]
How did you manage to fix this? The annotations on PVC didn't help.

**Comment by CoreyLylyk** [comment]
Any solution to this?
