### ISSUE TITLE
Error when reset application parameters from UI

### ISSUE THREAD

**Issue by mayzhang2000** [argoproj/argo-cd#5823]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
From `App Details`, 'Parameters' tab,  after set images that needs to be override, reset it back to empty results in the error below.

```
Unable to save changes: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = `kustomize edit set image docker.xxxx` failed exit status 1: Error: invalid format of image, use one of the following options: - <image>=<newimage>:<newtag> - <image>=<newimage>@<newtag> - <image>=<newimage> - <image>:<newtag> - <image>@<digest> Usage: kustomize edit set image [flags] Examples: The command set image 
```

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
ArgoCD 2.0

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
This is a UI bug. The UI is sending a bad payload like:

```
"kustomize":{"images":["argoproj/rollouts-demo"]}}
```
