### ISSUE TITLE
Run jobs and cronjobs on-demand

### ISSUE THREAD

**Issue by jan-ludvik-deltatre** [argoproj/argo-cd#5844]
# Summary

When I have cronjob and job resource in UI, I would like to have a button that would run these immediately. Not really sure if this is in scope of ArgoCD - if not please close the issue :)

# Motivation

I am testing some cronjobs and I have to manually edit the cron expressions in UI to the next minute to have them running.

# Proposal

Not really sure - maybe a new job would be created when a cronjob is ran with this feature?

**Comment by jsoref** [comment]
duplicate of #4116
