### ISSUE TITLE
app sync --local connects to repoURL

### ISSUE THREAD

**Issue by gabegorelick** [argoproj/argo-cd#5849]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The docs for `argocd app sync --local` say that "When this flag is present no git queries will be made." However, it does in fact attempt to connect to the repo.

**To Reproduce**

1. Create the following Application:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  foo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thishastobesettosomething/foo.git
```

Note that the schema for `Application` requires that `repoURL` be set, even though if we only use `--local` it shouldn't be necessary. (Perhaps a separate enhancement request to improve this is warranted?)

2. Run `argocd app diff foo --local [dir]` to confirm everything is set up correctly. (`app diff` is not affected by this issue).

3. Run `argcd app sync foo --local [dir]`  and get the following error: `rpc error: code = FailedPrecondition desc = authentication required`. If you change `repoURL` to an SSH address which you're not authorized to access, then you'll get `rpc error: code = FailedPrecondition desc = error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"`. That makes it even more clear that argocd is attempting to connect to the repo server, even though the docs imply that it shouldn't be.

**Expected behavior**

Don't connect to `repoURL` if using `--local` when syncing.

**Version**

argocd: v1.8.7+eb3d1fb.dirty
  BuildDate: 2021-03-07T19:33:57Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: dirty
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64

argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0

**Comment by chetan-rns** [comment]
I'm able to reproduce this issue. Looks like it's trying to resolve `revision` even when `--local` is specified

**Comment by gabegorelick** [comment]
You can also reproduce this by pointing the application to a non-existent `targetRevision`. The sync will complain that the ref doesn't exist, even though that shouldn't matter for --local sync.

**Comment by chetan-rns** [comment]
@jannfis Could you please assign me this issue?
