### ISSUE TITLE
New 'app create' --retry-backoff-* parameters missing reference to sync in description

### ISSUE THREAD

**Issue by jgwest** [argoproj/argo-cd#5868]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

The following parameters were added to `argocd app` commands (for example, `app create`) as part of https://github.com/argoproj/argo-cd/issues/5318:

```
      --retry-backoff-duration duration           Retry backoff base duration. Input needs to be a duration (e.g. 2m, 1h) (default 5s)
      --retry-backoff-factor int                  Factor multiplies the base duration after each failed retry (default 2)
      --retry-backoff-max-duration duration       Max retry backoff duration. Input needs to be a duration (e.g. 2m, 1h) (default 3m0s)
```

These options all refer to sync retry, but neither the description nor the the parameter name mentions sync (see above). AFAICT the other sync options both include 'sync' in the parameter name and referencing syncing in the descripton.

So IMHO we should:
- Either, add `sync-` as a prefix to the parameter name
- Or, add `sync` in the param description (eg `Factor multiples the base duration after each failed sync retry`)
- Or both! :smile: 

Reproduced on recent version on recent master branch of Argo CD.

**Comment by jessesuen** [comment]
> So IMHO we should:
> Either, add sync- as a prefix to the parameter name
> Or, add sync in the param description (eg Factor multiples the base duration after each failed sync retry)
> Or both! 😄

Just spoke with @alexmt and team about this and we agree we should do both.
