### ISSUE TITLE
Generated manifests have hardcoded namespace

### ISSUE THREAD

**Issue by vd-rd** [argoproj/argo-cd#5869]
**Describe the bug**

ArgoCD generated manifest provided in getting started section has hardcoded reference for namespace argocd.
If you're trying to deploy to a different namespace the in-cluster sync will fail because the ClusterRoleBinding is still for argocd

Since the commands shown in quickstart section include a **-n argocd** option, it doesn't make sense to have it hardcoded and seek manual replacement in the cluster afterwards.

**To Reproduce**
Install argocd to any other namespace than the default.

kubectl create namespace not-argocd
kubectl apply -n not-argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

**Expected behavior**

ArgoCD should be deployed successfully (is) and any in cluster resource sync should work(don't).

**Fixes**

Someone already figured this out and has created [a nice guide](https://rtfm.co.ua/en/argocd-an-overview-ssl-configuration-and-an-application-deploy/#ArgocD_ComparisonError_failed_to_load_initial_state_of_resource)

**Version**

```shell
argocd: v1.8.7+eb3d1fb
  BuildDate: 2021-03-03T07:12:02Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
```

**Comment by sbose78** [comment]
Thank you for the report, would you like to summarize your suggestion for the fix?

**Comment by vd-rd** [comment]
The simplest way, IMO, would be a tip in getting started page bringing to your attention that if you want a different namespace, you should edit the manifest as well at [2323](https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml#L2323) and [2306](https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml#L2306).

I think it's easy to overlook the necessary edits in the manifest since the resourcescan be created with **kubectl -n some-ns**
