### ISSUE TITLE
Use encrypted cookie to store OAuth2 state nonce (instead of redis)

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#5873]
**Describe the bug**

Currently (as of v2.0) during the OAuth2 exchange, we store the state nonce in redis, which we retrieve to complete the exchange.

When redis is not functioning (e.g. because of an update), a user that attempts login will get the error: `unknown app state <oidc state nonce>`

Argo Workflows has developed a technique where the state nonce is stored as an encrypted cookie, rather than in redis, which allows them to avoid the use of redis entirely during SSO login.

https://github.com/argoproj/argo-workflows/pull/2745

The following post describes the technique:

https://security.stackexchange.com/questions/140883/is-it-safe-to-store-the-state-parameter-value-in-cookie

**To Reproduce**

Shut down redis, attempt an SSO login

**Expected behavior**

SSO login flow should still work without redis

**Version**

v2.0

**Comment by jabf0923** [comment]
I'm running into this issue and rebooting the both stateful redis and redis  is not helping! do you have a work around?

**Comment by michaelajr** [comment]
@jessesuen I noticed you are closing all the issues around `failed to verify app state` in anticipation of the encrypted cookie change. I notice this this issue is tagged as a 2.3 milestone. Any chance this can be back ported to 2.1 or upcoming 2.2?
