### ISSUE TITLE
Can't add apps from https://repo.chartcenter.io after upgrading from 1.7 to 1.8

### ISSUE THREAD

**Issue by cdobinsky** [argoproj/argo-cd#5883]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading from argocd 1.7.13 to 1.8.4 with the argocd-helm Chart 2.14.7 I can't create an app from https://repo.chartcenter.io

Following error occurs:
```
Unable to create application: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = `helm chart pull https://repo.chartcenter.io/jfrog/artifactory:11.7.4` failed exit status 1: Error: ref may only contain a single colon character (:) unless specifying a port number
```

It doesn't even recognize the values.yaml.

Downgrading to 1.7.13 it works without problems.

**To Reproduce**

In UI
- Add new app
- Fill in necessary fields (App name, project, cluster, namespace)
- Select as Repository https://repo.chartcenter.io and select Helm
- Choose Chart jfrog/artifactory with Version 11.7.4
- Click Create
- Error occurs

**Expected behavior**

The app should successfully be created

**Version**

```shell
argocd: v1.8.4+28aea3d
  BuildDate: 2021-02-05T17:54:42Z
  GitCommit: 28aea3dfdede00443b52cc584814d80e8f896200
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.8.4+28aea3d
  BuildDate: 2021-02-05T17:56:06Z
  GitCommit: 28aea3dfdede00443b52cc584814d80e8f896200
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Comment by kshamajain99** [comment]
Identified issue with how Argo CD is calling `helm chart pull`

https://github.com/argoproj/argo-cd/blob/4ee30a1cff0039293702a1a23d05f68b86e384c7/util/helm/cmd.go#L245

> helm chart pull cannot pull from a chart repository. It can only pull from an OCI registry.

Refer https://github.com/helm/helm/issues/9307#issuecomment-771155945

**Comment by alexmt** [comment]
I think https://github.com/argoproj/argo-cd/issues/5628 is a root cause. Argo CD is trying to be smart and guesses OCI vs non-OCI based on chart path. Instead user should be able to specify it explicitly.
