### ISSUE TITLE
Allow to override Kubernetes config when setting up Port Forward

### ISSUE THREAD

**Issue by raphink** [argoproj/argo-cd#5905]
# Summary

Currently, when ArgoCD sets up a Port Forward, it uses the standard Kube config, without a possibility to override it (except using the `KUBECONFIG` environment variable).

# Motivation

When using the API client in the [ArgoCD Terraform Provider](https://github.com/oboukili/terraform-provider-argocd), it is sometimes necessary to [pass a dynamic Kubernetes config to the provider]. This requires to support it in the API client itself.

# Proposal

Add a `KubeOverrides` field to the API client's options and pass it to the `PortForward` method.

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/5906
