### ISSUE TITLE
Helm example fails with no such file or directory when choosing values file

### ISSUE THREAD

**Issue by ssboisen** [argoproj/argo-cd#591]
Hi,

I tried using the helm example app from argoproj/argocd-example-apps but it fails due to pathing errors. This happens if I choose a values file in the new v8.0.1 feature.

> rpc error: code = Unknown desc = Error: open /tmp/https:__github.com_argoproj_argocd-example-apps.git/helm-guestbook/helm-guestbook/values.yaml: no such file or directory

 It seems like the full path of the values file is appended to the base path of the application/chart.

This problem doesn't happen if no values file is selected.

**Comment by alexmt** [comment]
This was fixed by https://github.com/argoproj/argo-cd/commit/ed484c00db0576fdab5d0c1d1674164a64dc06fa but commit is not it release-0.8 branch. Working on v0.8.3 release with the fix

**Comment by ssboisen** [comment]
great @alexmt - thanks for the update!

**Comment by jessesuen** [comment]
Fix has been cherry-picked to release-0.8 (3e374988cea8239f2511bb95ab5e5150ab1f531b) and will be available in v0.8.3 (monday)

**Comment by rahulroyal924** [comment]
Hi ,

 I am trying this command to deploy the chart in spinanaker

"./helm install -n fd stable/spinnaker -f spinnaker-config.yaml --debug --timeout 600 --version 1.1.6 --wait"

But i am facing below error
"
[debug] Created tunnel using local port: '34897'

[debug] SERVER: "127.0.0.1:34897"

[debug] Original chart version: "1.1.6"
[debug] Fetched stable/spinnaker to /home/mabluh/.helm/cache/archive/spinnaker-1.1.6.tgz

[debug] CHART PATH: /home/mabluh/.helm/cache/archive/spinnaker-1.1.6.tgz


Error: Job failed: BackoffLimitExceeded"

Can anybody please help me to resolve this problem?

Thanks in advance
