### ISSUE TITLE
Is Redis really necessary? 

### ISSUE THREAD

**Issue by dudicoco** [argoproj/argo-cd#5910]
Hi,

There is very little information within the docs regarding the necessity of using redis for caching.

According to https://argo-cd.readthedocs.io/en/stable/operator-manual/architecture/#repository-server:
```
The repository server is an internal service which maintains a local cache of the Git repository holding the application manifests.
```

If the repo server already maintains a local cache, why do we need redis in addition? 
Can we just convert the repo server to a statefulset to maintain the cache during restarts and remove the need for redis?

Thanks

**Comment by exe-r** [comment]
Tried to deploy argocd using helm (latest charts) with redis disabled but I was unable to get it working past SSO login is giving error: failed to verify app state eDJFHSJS: dial tcp: lookup argocd-redis on x.x.x.x:53: server misbehaving. So I ended up with the same question, is redis a requirement or not? if it is it should be clearly stated on the docs IMO.
