### ISSUE TITLE
Docker build broken for ARM

### ISSUE THREAD

**Issue by alinbalutoiu** [argoproj/argo-cd#5911]
**Describe the bug**

Docker build is failing when running on ARM platforms.

**To Reproduce**

Run the following on an ARM platform:

```
make armimage
```

**Expected behavior**

It is expected that the build will succeed and produce the ARM container image.

**Logs**

Build output for ARM when building `v2.0.0-rc2` tag available here: https://cloud.drone.io/alinbalutoiu/argo-cd/47/2/2

**Comment by mickkael** [comment]
it needs further testing, but I think I have built ksonnet for arm64
