### ISSUE TITLE
argocd app create --file doesn't respect metadata.labels

### ISSUE THREAD

**Issue by Velyks** [argoproj/argo-cd#5913]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When using `argocd app create --file` to create an application from a manifest the labels are not correctly applied.

**To Reproduce**

Create a valid yaml manifest for an ArgoCD application which contains the following block:
```yaml
metadata:
  labels:
    my_key: "my_value"
    my_other_label: "12345"
```

**Expected behavior**

An ArgoCD application is created with the labels specified in .metadata.labels 

**Screenshots**

**Version**

```shell
argocd: v1.8.5+d0f8edf
  BuildDate: 2021-02-20T05:38:50Z
  GitCommit: d0f8edfec804c013d4fc535e8b9022eb47602617
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.0-rc1+0ca643f
  BuildDate:
  GitCommit:
  GitTreeState:
  GoVersion:
  Compiler:
  Platform:
  Ksonnet Version:
  Kustomize Version:
  Helm Version:
  Kubectl Version:
  Jsonnet Version:
``` 

For clarification we're using a custom-built image from the official 2.0.0-RC1 image. The only difference being a different version of helm and some extra plugins.

**Comment by kshamajain99** [comment]
We fixed this bug in v2.0 https://github.com/argoproj/argo-cd/pull/5268
