### ISSUE TITLE
Enable helm OCI to work for lots of different URLs without having to create a repo for each one

### ISSUE THREAD

**Issue by Yaytay** [argoproj/argo-cd#5920]
# Summary

If we have a fairly large number of helm charts, all included in a few parent charts (one parent per environment) those included charts all have very different URLs.
With GitLab the natural place to keep artefacts is in the same project as the source code, which leads to these very different URLs.
I think that at the moment to make this work we'd have to create a new repository for each GitLab Project, and thus for each chart, which is a lot of repositories.

# Proposal

I'm not quite sure where the root of the problem is, whether it is with telling ArgoCD that we need the HELM_EXPERIMENTAL_OCI flag or with the specifying of the credentials for accessing the repos.
So I have three suggestions that might help:

1. Always specify HELM_EXPERIMENTAL_OCI.
I'm not sure there is a disadvantage to doing so.
2. Have an application level setting (that could potentially be used for other generic attributes) that allows us to specify that HELM_EXPERIMENTAL_OCI  should be used for this application (regardless of repos).
3. Enable the repos for helm to pick up credentials based on the host and the path root, rather than the exact path.
So a repo like this:
    - url: registry.gitlab.com/my-group
      type: helm
      enableOci: true
      passwordSecret: {name: gitlab-user, key: password}
      usernameSecret: {name: gitlab-user, key: username}

gets used for dependencies like this:
  - name: my-library
    version: 0.0.4
    repository: oci://registry.gitlab.com/my-group/devops/my-library
  - name: my-library
    version: 0.0.5
    repository: oci://registry.gitlab.com/my-group/wibble
  - name: my-library
    version: 0.0.5
    repository: oci://registry.gitlab.com/my-group/fred/wilma/george/ted

**Comment by jannfis** [comment]
I think this change could be made easy by promoting *credential templates for repositories* to *repository templates*, and let the templates also specify repository settings.

**Comment by jannfis** [comment]
> Always specify HELM_EXPERIMENTAL_OCI.
> I'm not sure there is a disadvantage to doing so.

1) It is clearly marked as experimental
2) Helm also requires you to explicitly enable it

So from my point of view, when it's not the Helm default, we should neither set it by default.
