### ISSUE TITLE
Move secret argocd-manager away from kube-system

### ISSUE THREAD

**Issue by damadei-google** [argoproj/argo-cd#5934]
# Summary
Move argocd-manager secret away from kube-system.

# Motivation
The new version of GKE (Google Kubernetes Engine) called autopilot restricts deployments to kube-system, so for Argo CD to be usable with GKE Autopilot, my suggestion would be to allow this secret to be placed somewhere else.

# Proposal
Maybe propose a way to specify a custom namespace or create an argocd namespace inside the application cluster.

**Comment by jannfis** [comment]
Hey, there is already the possibility to create the required `ServiceAccount` (and accompanying secret) in another namespace during cluster connect, by using the `--system-namespace string` parameter to `argocd cluster add`.
