### ISSUE TITLE
rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by anup1384** [argoproj/argo-cd#5935]
EKS version- 1.18
Argocd version- v1.8.3+0f9c684

We are using AWS custom CNI plugin with secondary CIDR and enabled SNAT (https://docs.aws.amazon.com/eks/latest/userguide/external-snat.html) for the need to communicate with other private IP address spaces (for example, Direct Connect, VPC Peering, or Transit VPC).

When we disabled the SNAT feature, Argo projects work properly but when we enabled the SNAT we received the below error:-
"App synch fails with ComparisonError RPC error: code = DeadlineExceeded desc = context deadline exceeded"

**Logs**
```
time="2021-03-31T12:37:09Z" level=error msg="`git fetch origin --tags --force` failed timeout after 1m30s" execID=matso
time="2021-03-31T12:37:09Z" level=info msg=Trace args="[git fetch origin --tags --force]" dir=/tmp/git@bitbucket.org_XXXXXXXXXX operation_name="exec git" time_ms=90001.338883
time="2021-03-31T12:37:09Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = Failed to fetch git repo: `git fetch origin --tags --force` failed timeout after 1m30s" grpc.code=Internal grpc.method=GetRevisionMetadata grpc.request.deadline="2021-03-31T12:36:39Z" grpc.service=repository.RepoServerService grpc.start_time="2021-03-31T12:35:39Z" grpc.time_ms=90008.69 span.kind=server system=grpc
time="2021-03-31T12:37:09Z" level=info msg="git fetch origin --tags --force" dir=/tmp/git@bitbucket.org_XXXXXXXXXX execID=1sVNh
```

**Comment by jannfis** [comment]
To me it seems, that your SNAT will actually prevent the `argocd-repo-server` from connecting to your repositories and it will fail with a timeout. 

Can you manually exec into the pod and clone the repo? If not, how is this an Argo CD bug?
