### ISSUE TITLE
Feature request: Favorites

### ISSUE THREAD

**Issue by pantaoran** [argoproj/argo-cd#5936]
Hi, I hope this is a good place for I don't really have time to search for proper channels.

Just a quick feature request: I would like to define "favorite" projects in the ArgoCD GUI.

My company has hundreds of projects so every time I open Argo I first need to type the name of my project into the search bar to find and open it. If I could mark it as my favorite that could always be displayed first and would save me time.

That's all, thanks for your good work. Argo is really helpful :-)
Best regards
Patrick

**Comment by sbose78** [comment]
Thank you for the feature request. @reginapizza I wonder if there's a way for users to star specific Applications on the UI and have the information stored in a lightweight way in the browser local storage? 

On that note, do we store user/session preferences anywhere at all today?

**Comment by alexmt** [comment]
User preferences are stored using storage API. View Preferences service encapsulates this logic: https://github.com/argoproj/argo-cd/blob/eb70a1e3fa4ffc7e479b75415217e62aa637ecc7/ui/src/app/shared/services/view-preferences-service.ts#L26


I think user preferences is an appropriate place to store favorites.

**Comment by saumeya** [comment]
@hritikgupta if you are working on this please let me know, if not, I'd like to work on this.

**Comment by hritikgupta** [comment]
Hi @saumeya, I haven't started on it, please feel free to take it up!
