### ISSUE TITLE
not able to login with okta configuration

### ISSUE THREAD

**Issue by nandeeshb09** [argoproj/argo-cd#5941]
Hi ,

 I have installed argocd 1.8.7 in EKS 1.15 , when I tried to login via with okta configuration , not able to login.

We are able to see the okta login page , but not able to login.

Please anybody help on this...?

Below is the error:
me="2021-04-01T08:28:47Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = no session information" grpc.code=Unauthenticated grpc.method=List grpc.service=application.ApplicationService grpc.start_time="2021-04-01T08:28:47Z" grpc.time_ms=0.246 span.kind=server system=grpc
time="2021-04-01T08:28:47Z" level=info msg="received unary call /cluster.SettingsService/Get" grpc.method=Get grpc.request.claims=null grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2021-04-01T08:28:47Z" span.kind=server system=grpc

argocd-cm with below configuration and am I missing anything here and also dont see any logs at dex pod.

data:
  dex.config: |
    logger:
     level: debug
     format: json
    connectors:
    - type: saml
      id: okta
      name: Okta
      config:
        ssoURL: https://test.okta.com/app/argocd/sso/saml
        caData: |
        -----BEGIN CERTIFICATE-----
          my cert
          -----END CERTIFICATE-----
        redirectURI: https://argocd.com/api/dex/callback
        usernameAttr: email
        emailAttr: email
        groupsAttr: group

<img width="1182" alt="Screenshot 2021-04-01 at 2 30 03 PM" src="https://user-images.githubusercontent.com/24272141/113289857-69df5000-930e-11eb-9f93-a06b771fc2d0.png">

**Comment by nandeeshb09** [comment]
[](url)
![Uploading Screenshot 2021-04-01 at 2.30.03 PM.png…]()

**Comment by nandeeshb09** [comment]
Hi Team,

Any update on this?

**Comment by jannfis** [comment]
Hey, given your `argocd-cm` example is not well formatted on the issue, it's quite hard to see something. But maybe you are missing `.data.url` field, at least I cannot see it in the text you pasted.

**Comment by nandeeshb09** [comment]
@jannfis ,

Thanks for your response and its working now...

But in doc its not updated, please update if possible.

https://argoproj.github.io/argo-cd/operator-manual/user-management/okta/

**Comment by jannfis** [comment]
Hi @nandeeshb09, thanks for confirming your issue is solved.

The requirement for the `url` key is documented here https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#2-configure-argo-cd-for-sso and also in the FAQ at https://argo-cd.readthedocs.io/en/stable/faq/#i-have-configured-dex-via-dexconfig-in-argocd-cm-it-still-says-dex-is-unconfigured-why - but I do agree it might be placed somewhere more prominent in the docs.
