### ISSUE TITLE
Get() Repository returning confusing reply for non-existing repositories

### ISSUE THREAD

**Issue by janwillies** [argoproj/argo-cd#5951]
**Describe the bug**

I want to check if a specific `repository` exists via api. This was implemented as part of https://github.com/argoproj/argo-cd/issues/2618. In case the `repository` exists, all is good. If it doesn't exists, I'm getting confusing error messages.

Requesting a non-existing `https` repository:
```bash
curl -s -H "Authorization: Bearer $ARGOCD_TOKEN" -k https://localhost:8080/api/v1/repositories/https%3A%2F%2Fgitlab.com%2Ffoo%2Fexample-project.git | jq
```
Instead of a `404` I'm getting a somewhat empty repository back:
```json
{
  "repo": "https://gitlab.com/foo/example-project.git",
  "connectionState": {
    "status": "Failed",
    "message": "Unable to connect to repository: failed to get index: 503 Service Temporarily Unavailable",
    "attemptedAt": "2021-04-02T11:33:48Z"
  },
  "type": "git"
}
```
Pretty similar for `git` repositories:
```bash
curl -s -H "Authorization: Bearer $ARGOCD_TOKEN" -k https://localhost:8080/api/v1/repositories/git%40gitlab.com%3Afoo%2Fexample-project.git | jq
```
```json
{
  "repo": "git@gitlab.com:foo/example-project.git",
  "connectionState": {
    "status": "Failed",
    "message": "Unable to connect to repository: parse \"git@gitlab.com:foo/example-project.git\": first path segment in URL cannot contain colon",
    "attemptedAt": "2021-04-02T12:24:45Z"
  },
  "type": "git"
}
```
**To Reproduce**
```bash
curl -s -H "Authorization: Bearer $ARGOCD_TOKEN" -k https://localhost:8080/api/v1/repositories/git%40gitlab.com%3Afoo%2Fexample-project.git | jq
```

**Expected behavior**

I would expect a `404` for curl, and for the go [RepositoryServiceClient](https://pkg.go.dev/github.com/argoproj/argo-cd@v1.8.7/pkg/apiclient/repository#RepositoryServiceClient) `Get()` call to return a `nil` pointer instead and an appropriate `error`, much like the `DeleteRepository()` call:

```go
	repoQuery := repository.RepoQuery{
		Repo: "git@gitlab.com:foobar/example-project.git",
	}
	_, err := e.client.DeleteRepository(ctx, &repoQuery)
```
> cannot delete Argocd repository: rpc error: code = NotFound desc = repo 'git@gitlab.com:foobar/example-project.git' not found

**Version**

```shell
argocd: v2.0.1+33eaf11.dirty
  BuildDate: 2021-04-17T04:23:35Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: dirty
  GoVersion: go1.16.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.1+33eaf11
  BuildDate: 2021-04-15T22:31:51Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Comment by janwillies** [comment]
@souleb, would you know why this is failing?

**Comment by souleb** [comment]
The code try to get the repository settings(creds) from db and then try the connection. 
https://github.com/argoproj/argo-cd/blob/5c3f1d4b172853696fd4068e62a9c0d847956fda/server/repository/repository.go#L57

The error 503 you get is from gitlab, and I suspect it is from a malformed url.

**Comment by janwillies** [comment]
Thanks! Should there be something similar to https://github.com/argoproj/argo-cd/blob/5c3f1d4b172853696fd4068e62a9c0d847956fda/util/db/repository.go#L255-L257 then?

**Comment by Cylix** [comment]
Hey folks, I'm looking to contribute to argocd and was thinking about taking a look at this issue. I was able to reproduce locally, so I'll dig a little bit in the upcoming days, but let me know if that's something someone else is working on.
