### ISSUE TITLE
Kustomize 4.0+ Support

### ISSUE THREAD

**Issue by starcraft66** [argoproj/argo-cd#5952]
# Summary

ArgoCD currently ships with Kustomize v3 while Kustomize v4 has been out for at least a month. I suspect some users may want to remain on v4 because v4 removed some remote URL schemes.

# Motivation

I'd like to migrate my infrastructure to use Kustomize v4+ for the sake of staying up to date.

# Proposal

The ArgoCD image could either drop support for Kustomize v3 (potentially a breaking change to be released alonv with ArgoCD v2?), the ArgoCD image could have tags for kustomize v3/v4 (potentially messy) or the image could come bundled with both and the Kustomize version to use could be specified in the `Application` CRD.

**Comment by sbose78** [comment]
Related #5851 , #4927

Hi Tristan,

Great request!

We do plan on upgrading to Kustomize 4.x, we would need to find the most
stable version for the same. Would you have suggestions on that? Would love
to hear comments on the PR #4927 as well. Note, this will go in post 2.0.

At the same time, we are also working on making it easy for a deployment to
have custom plugins without having to rebuild the ArgoCD image , please
refer to #5851.

**Comment by Jojoooo1** [comment]
For info tried 4.0 on my github repo today could not make it works because of some utf-8 comparabilities for no reason and had to re downgrade to 3.8.10

**Comment by alexmt** [comment]
@mayzhang2000 is this ticket good to close ?

**Comment by joebowbeer** [comment]
#6059
