### ISSUE TITLE
SealedSecrets health check is stuck in "Progressing"

### ISSUE THREAD

**Issue by gajus** [argoproj/argo-cd#5971]
**Describe the bug**

[SealedSecrets](https://github.com/bitnami-labs/sealed-secrets) health check is stuck in "Progressing".

**To Reproduce**

1. Deploy any sealed secret
2. Observe deployment status in ArgoCD 
3. Wait for sealed secret state to turn to Healthy (it does not) 

**Expected behavior**

1. Deploy any sealed secret
2. Observe deployment status in ArgoCD 
3. Sealed secret state to turns to Healthy

**Screenshots**

<img width="695" alt="Screen Shot 2021-04-05 at 1 33 32 PM" src="https://user-images.githubusercontent.com/973543/113623132-c72b1800-9612-11eb-8656-d00e25cc3bac.png">

**Version**

```shell
argocd: v1.7.3+b4c79cc
  BuildDate: 2020-09-01T23:20:15Z
  GitCommit: b4c79ccb88173604c3786dcd34e83a9d7e8919a5
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v99.99.99+unknown
  BuildDate: 1970-01-01T00:00:00Z
  GitCommit:
  GitTreeState:
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version:
```

Other:

* Despite what the version says, I am using v2.0.0-rc3
* `sealed-secrets-controller:v0.13.1`

**Comment by gajus** [comment]
Upgrading `sealed-secrets-controller` to v0.15.0 does not fix the issue.

**Comment by gajus** [comment]
The only event attached to the sealed secret is:

```
REASON
MESSAGE
COUNT
FIRST OCCURRED
LAST OCCURRED

Unsealed
SealedSecret unsealed successfully
1
2021-04-05T20:34:51Z
2021-04-05T20:34:51Z

```

**Comment by gajus** [comment]
Turns out there is a `--update-status` flag that I need to pass.

https://github.com/bitnami-labs/sealed-secrets/blob/main/RELEASE-NOTES.md#v0150

```yaml
commandArgs:
  - '--update-status'

```

This fixed the issue.

**Comment by jef** [comment]
Seems like this may still be an issue for some...

https://github.com/bitnami-labs/sealed-secrets/issues/555

May not even be working for those on v0.15.0

**Comment by YevheniiPokhvalii** [comment]
Have the same issue. Setup: ArgoCD 2.0.0 and sealed-secrets v0.16.0

Adding the `SEALED_SECRETS_UPDATE_STATUS` variable to "1" in this file https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.16.0/controller.yaml helped to deploy a secret to ArgoCD:


```
apiVersion: apps/v1
kind: Deployment

```

```
    spec:
      containers:
      - args: []
        command:
        - controller
        # env: []
        env:
        - name: SEALED_SECRETS_UPDATE_STATUS
          value: "1"
```

**Comment by YevheniiPokhvalii** [comment]
> 
> 
> Turns out there is a `--update-status` flag that I need to pass.
> 
> https://github.com/bitnami-labs/sealed-secrets/blob/main/RELEASE-NOTES.md#v0150
> 
> ```yaml
> commandArgs:
>   - '--update-status'
> ```
> 
> This fixed the issue.

For those who ran into this issue. It seems that @gajus described it for the Helm chart - the overridden values in the `values.yaml` file:

```
---
sealed-secrets:
  commandArgs:
    - '--update-status'
```
