### ISSUE TITLE
ui: Checkboxes have visual artifacts in macOS Big Sur / Safari latest

### ISSUE THREAD

**Issue by rbreeze** [argoproj/argo-cd#5995]
Appears that Webkit styling is overlapping with Argo CD custom styling

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Screenshots**

<img width="216" alt="Screen Shot 2021-04-08 at 10 49 39 AM" src="https://user-images.githubusercontent.com/6250584/114073442-22018100-9858-11eb-9481-1987744708c9.png">

<img width="567" alt="Screen Shot 2021-04-08 at 10 49 27 AM" src="https://user-images.githubusercontent.com/6250584/114073453-24fc7180-9858-11eb-9785-32f6836d6ee4.png">

**Version**

```
macOS Big Sur    v11.2.3
Safari           v14.0.3
Argo CD          v2.0.0+ae2d0ff
```

**Comment by rbreeze** [comment]
Note: New Checkbox component that addresses are available in `argo-ux` package 

https://github.com/argoproj/argo-ui/pull/100

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/6091
