### ISSUE TITLE
Repositories are not ignored 

### ISSUE THREAD

**Issue by maxtacu** [argoproj/argo-cd#6015]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
After upgrade from 1.7.10 to 1.8.4 argocd is not ignoring anymore `repositories` resource in `argocd-cm`. All existing repositories or new repository added in UI creates a diff in `argocd-cm` and asks to remove it from `argocd-cm` because initially it is not declared in `argocd-cm`. 
P.S. All existing and new repos are successfully connected, but `argocd-cm` complains about OutOfSync

**To Reproduce**
Two ways:
1. Upgrade ArgoCD from 1.7.10 to 1.8.4
2. Create a new ArgoCD cluster with 1.8.4 version and restore the backup from 1.7.10

**Expected behavior**

`argocd-cm` should be in sync after the upgrade or when ArgoCD inserts a new repository in the configmap

**Version**

```shell
argocd version
argocd: v1.8.1+c2547dc.dirty
  BuildDate: 2020-12-10T04:44:20Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: dirty
  GoVersion: go1.15.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.4+28aea3d
  BuildDate: 2021-02-05T17:56:06Z
  GitCommit: 28aea3dfdede00443b52cc584814d80e8f896200
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Comment by blakepettersson** [comment]
Closing since this pertains to a really old version
