### ISSUE TITLE
Unimplemented desc = unknown method TestRepository

### ISSUE THREAD

**Issue by braghettos** [argoproj/argo-cd#6017]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I installed ArgoCD via helm chart version v2.0.0 and I'm trying to create a new application via UI, but once I try to create it I get the following error:

> Unable to create application: application spec is invalid: InvalidSpecError: repository not accessible: rpc error: code = Unimplemented desc = unknown method TestRepository

**To Reproduce**

- Install ArgoCD via helm chart version v2.0.0
- Try to add the chart in the subpath /charts of the repository https://github.com/projectkerberus/martino-stack

**Expected behavior**

Create a namespace and an application on ArgoCD.

**Screenshots**

![image](https://user-images.githubusercontent.com/5436669/114406356-c4e33380-9ba7-11eb-97c8-4e70de43ef79.png)

**Version**

```shell
argocd: v2.0.0+2f92777
  BuildDate: 2021-04-09T16:14:24Z
  GitCommit: 2f92777f719e8ab9e1e917c02140f91f346f8c61
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified  
```

**Logs**

```shell
time="2021-04-12T13:38:33Z" level=info msg="received unary call /application.ApplicationService/Create" grpc.method=Create grpc.request.claims="{\"iat\":1618232229,\"iss\":\"argocd\",\"jti\":\"9d1bb7fa-9e23-491d-afc0-5dfbdf924aec\",\"nbf\":1618232229,\"sub\":\"kerberus-dashboard\"}" grpc.request.content="%!v(PANIC=String method: reflect.Value.Interface: cannot return value obtained from unexported field or method)" grpc.service=application.ApplicationService grpc.start_time="2021-04-12T13:38:33Z" span.kind=server system=grpc
time="2021-04-12T13:38:33Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: repository not accessible: rpc error: code = Unimplemented desc = unknown method TestRepository" grpc.code=InvalidArgument grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2021-04-12T13:38:33Z" grpc.time_ms=9.486 span.kind=server system=grpc
```

**Comment by jannfis** [comment]
It seems you run `argocd-server` deployment with a recent image (e.g. `latest`), but your `argocd-repo-server` workload's image is `v2.0.x`.

**Comment by myrondev** [comment]
> It seems you run `argocd-server` deployment with a recent image (e.g. `latest`), but your `argocd-repo-server` workload's image is `v2.0.x`.

Where id you change argocd-repo-server image?
