### ISSUE TITLE
Imported backup refuses to show up

### ISSUE THREAD

**Issue by tanvir-appveen** [argoproj/argo-cd#6020]
**Describe the bug**

I exported a backup of my argocd cluster but the imported backup refuses to show up. For context, this is running GKE - K8s version 1.18.
It was imported successfully as shown here so why isn't it showing up in the UI :

```
/ConfigMap argocd-cm created
/ConfigMap argocd-rbac-cm created
/ConfigMap argocd-ssh-known-hosts-cm created
/ConfigMap argocd-tls-certs-cm created
/Secret argocd-secret created
/Secret repo-3773579101 created
argoproj.io/AppProject staging created
argoproj.io/AppProject default created
argoproj.io/Application payments created
argoproj.io/Application user created
```

Even the CLI says it can't find
```
$ argocd app get user
FATA[0000] rpc error: code = NotFound desc = applications.argoproj.io "user" not found
```

**Version**

```shell
argocd: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.0+f5119c0
```

**Other information**
For context, before I tried in another argocd setup,  I deleted an app tried and importing it into the same argocd setup I exported from and it didn't show up.

**Comment by kshamajain99** [comment]
@tanvir-appveen I couldn't reproduce the bug. Is it possible that you are connect to different Argo CD instance? It would be great if you share the steps to reproduce this bug.

**Comment by tanvir-appveen** [comment]
> @tanvir-appveen I couldn't reproduce the bug. Is it possible that you are connect to different Argo CD instance? It would be great if you share the steps to reproduce this bug.

Nevermind, I had to add the namespace to the command `argocd-util -n argocd import - < backup.yaml`

I assumed the default namespace for argocd would be `argocd` but it was default as it should be with anything related to K8s.

My bad!
