### ISSUE TITLE
Transport goroutine leak in the argo-cd apiclient

### ISSUE THREAD

**Issue by StephenWeber** [argoproj/argo-cd#6026]
Summary: we noticed a goroutine leak and tracked it down to the `apiclient` code in argo-cd

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [~] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We saw increasing goroutine and memory usage in our service that uses the `apiclient` to contact our ArgoCD installations. 

Using `pprof` and reproducing our service's behavior, we discovered the goroutine were `http.readLoop` and `http.writeLoop` functions -- Go documentation pointed us towards creating new Transport objects for each request when the existing one should be reused.

After thoroughly diagnosing our own system, we turned to making changes in the apiclient and discovered it was creating a new GRPC client each request through the apiclient. By moving the http client (and Transport) creation outside of the grpcproxy request cycle, we were able to eliminate the goroutine leak.

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

Steady-state or occilating goroutine counts that were related to system throughput.

**Screenshots**

Chart of goroutines - thin blue line that does not increase is our canary that was deployed with the altered argo-cd library. Note that the "regular" instances grow without bound over time.

<img width="1220" alt="Screen Shot 2021-04-13 at 4 57 07 PM" src="https://user-images.githubusercontent.com/153632/114635374-71411a80-9c79-11eb-93a1-5588f3f8c0f9.png">

**Version**

argo-cd 1.6.1 `apiclient.Client`

**Comment by StephenWeber** [comment]
Example change can be found at https://github.com/newrelic-forks/argo-cd/commit/b7c362003d064c8fa47536af08eee44c37b81601

We have deployed this to our production systems and verified that this does indeed stabilize goroutine use while preserving `argocd` functionality.

**Comment by uturunku1** [comment]
Hi team! 

To add to what my colleague Stephen already said, there was another small change we made to grcpproxy.go in argo-cd. 

Our Data Race Detector (https://golang.org/doc/articles/race_detector) was giving some intermittent warning pointing to startGRPCProxy function. Here is a little sample of those warnings (but I am happy to share more stack traces if you need them):

```
starts WRITE AT 0x00c00069c120 by goroutine 33:
		sync/atomic.CompareAndSwapInt32()
    /usr/local/go/src/runtime/race_amd64.s:293
  	sync.(*Mutex).Lock()
    /usr/local/go/src/sync/mutex.go:74
  	google.golang.org/grpc.(*Server).Serve()
    shuayhuaca/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:582
		apiclient.(*client).startGRPCProxy.func2()
		/Users/shuayhuaca/Desktop/argo-cd/pkg/apiclient/grpcproxy.go:178
```

After looking into that function, this line got my attention:
https://github.com/argoproj/argo-cd/blob/v1.6.1/pkg/apiclient/grpcproxy.go#L119

I have the impression this line did not mean to re-assign a value to `err =`, but to actually create a new variable `err :=`

After making that change that data race warning seemed to disappear.

Looking forward to hearing your thoughts on these changes!

https://github.com/newrelic-forks/argo-cd/tree/leak-fix

If you agree to them, we are happy to open a PR. We'll just need to know your preference if we should PR against master branch or PR against a release branch (as you can notice we made those changes branching off v1.6.1-branch).

Best,
Luces
