### ISSUE TITLE
ArgoCD auth via Keycloak returns 401

### ISSUE THREAD

**Issue by alexeyzhuchkov** [argoproj/argo-cd#6032]
Greetings,

I have configured ArgoCD auth via Keycloak[1],[2]. The login attempt leads to the loop when UI endlessly requesting https://<argo_URL>/api/v1/clusters with the responce of 401 Unauthorized. The UI continue looping till the expiration of a token. Confusing is that the request cookies consist of completely valid token with correct expiration date, issuer, username, assigned groups and signature, issued by Keycloak.

Why would ArgoCD return 401? Please assist.

[1] -- https://argoproj.github.io/argo-cd/operator-manual/user-management/#existing-oidc-provider
[2] -- https://argoproj.github.io/argo-cd/operator-manual/user-management/keycloak/

**To Reproduce**

```kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  statusbadge.enabled: 'false'
  resource.exclusions: ''
  ga.trackingid: ''
  repositories: |
    - url: https://some.repo/repo.git
    - url: https://some.repo/repo2.git
    - url: https://some.repo/repo3.git
    - url: http://some.repo2/repo4.git
  ga.anonymizeusers: 'false'
  help.chatUrl: ''
  accounts.root: 'apiKey, login'
  url: 'https://argocd.url'
  help.chatText: ''
  kustomize.buildOptions: '--load_restrictor none'
  resource.inclusions: ''
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.url/auth/realms/realmname
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
  repository.credentials: |
    - url: https://some.repo
      passwordSecret:
        name: git-secret
        key: password
      usernameSecret:
        name: git-secret
        key: username
    - url: http://some.repo2
      passwordSecret:
        name: git-hprn-secret
        key: password
      usernameSecret:
        name: git-hprn-secret
        key: username
  dex.config: |
    connectors:
    - config:
        clientID: system:serviceaccount:argocd:argocd-dex-server
        clientSecret: <secret>
        insecureCA: true
        issuer: https://kubernetes.default.svc
        redirectURI: https://argocd.url/api/dex/callback
      id: openshift
      name: OpenShift
      type: openshift
  users.anonymous.enabled: 'false'
  configManagementPlugins: ''
  application.instanceLabelKey: argocd.argoproj.io/instance
```

```kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    g, system:authenticated, role:admin
    g, root, role:admin
    g, ArgoCDAdmins, role:admin
  policy.default: 'role:readonly'
  scopes: '[groups]'
```

**Expected behavior**

The user is able to authenticate in ArgoCD via Keycloak integration.

**Version**

```shell
argocd: v1.7.7+33c93ae
  BuildDate: 2020-09-29T04:54:55Z
  GitCommit: 33c93aea0b9ee3d02fb9703cd82cecce3540e954
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64

argocd-operator.v0.0.14
```

**Logs**

```
time="2021-04-13T14:58:05Z" level=info msg="Web login successful. Claims: {\"<valid_token>\"}"

time="2021-04-13T14:58:06Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = invalid session: failed to verify signature: failed to verify id token signature" grpc.code=Unauthenticated grpc.method=List grpc.service=cluster.ClusterService grpc.start_time="2021-04-13T14:58:06Z" grpc.time_ms=2.707 span.kind=server system=grpc

time="2021-04-13T14:58:06Z" level=info msg="Initializing OIDC provider (issuer: <keycloak url>)"
time="2021-04-13T14:58:06Z" level=info msg="OIDC supported scopes: [openid email groups profile offline_access]" 
```

**Comment by alexmt** [comment]
The `https://<argo_URL>/api/v1/clusters` tries to talk to managed Kubernetes API. If Argo CD itself does not have access to the target cluster it might get 401 from Kubernetes API server. I suspect 401 bubbles up and confuses UI. 

@alexeyzhuchkov can you check if credentials of any cluster connected to Argo CD has expired.

**Comment by alexmt** [comment]
The `https://<argo_URL>/api/v1/clusters` should not return 401 if it failes to talk to managed K8S.

**Comment by alexeyzhuchkov** [comment]
The ArgoCD itself running inside the K8S cluster (Openshift 4.7 more precisely) and has an access to Kubernetes API. Credentials of the only cluster connected to ArgoCD are not expired.

**Comment by FL3SH** [comment]
I am having a similar issue, is any walk-around available?

**Comment by Enrico204** [comment]
This is strange because I have ArgoCD with Keycloak running without issues. I have `v2.0.3+8d2b13d` and I followed that guide

**Comment by Enrico204** [comment]
> I also have the same issue with keycloak.

Can you please share some details? Like the version of ArgoCD and Keycloak, their settings, logs, whatever clue may help :-)

**Comment by alexmt** [comment]
Looks like solution was found. Closing the issue

**Comment by robertogyn19** [comment]
I had the same problem and needed to configure the redirectURI to oidc.config.

`time="2022-01-04T21:46:36Z" level=info msg="Web login successful. Claims: {\"acr\":\"0\",\"at_hash\":\"ZItG36m1NkQlNC5hj9dl_w\",\"aud\":\"argocd\",\"auth_time\":1641332565,\"azp\":\"argocd\",\"email\":\"roberto.junior@gogeo.io\"
time="2022-01-04T21:46:37Z" level=info msg="Initializing OIDC provider (issuer: https://auth.gogeo.io/auth/realms/woctools)"
time="2022-01-04T21:46:37Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = invalid session: Failed to query provider \"https://auth.gogeo.io/auth/realms/woctools\": Get \"http://argocd-dex-server:5556/auth/realms/woctools/.well-known/openid-configuration\": dial tcp 10.110.61.173:5556: connect: connection refused" grpc.code=Unauthenticated grpc.method=List grpc.service=cluster.ClusterService grpc.start_time="2022-01-04T21:46:37Z" grpc.time_ms=1.812 span.kind=server system=grpc`

The message above gives a hint that was trying to use dex's local address.
After adding the redirectURI it started to work.

`name: Keycloak
issuer: https://auth.gogeo.io/auth/realms/woctools
clientID: argocd
clientSecret: $oidc.keycloak.clientSecret
requestedScopes: ["openid", "profile", "email", "groups"]
redirectURI: https://auth.gogeo.io`

I am using version 1.8.7.

**Comment by mcarbonneaux** [comment]
i face to the same problem than @robertogyn19, i think the documentation must be updated to add this attribut.
https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/#configuring-argocd-oidc

**Comment by RossComputerGuy** [comment]
I'm also having the same problem, what should `redirectURI` be set to with `bitnami/keycloak 9.6.9`? I have Keycloak running at `https://cluster.tristanxr.com/keycloak/`.
