### ISSUE TITLE
Adding a new line in a ConfigMap resource is not detected as a difference by ArgoCD

### ISSUE THREAD

**Issue by silviu-paunescu** [argoproj/argo-cd#6033]
**Describe the bug**

Adding a new line in a ConfigMap resource is not detected as a difference by ArgoCD.

**To Reproduce**

1. create an ArgoCD application that uses a ConfigMap and store the resources in a GIT repo.
2. apply the application to an ArgoCD instance
3. check in ArgoCD UI that the application's status is Synced
4. use command `kubectl edit configmaps <app>` to **add a new line** to the ConfigMap
5. ArgoCD UI shows that application's status is still Synced

**Expected behavior**

ArgoCD UI shows that application's status is OutOfSync because the live ConfigMap is different than the ConfigMap from the GIT repo.

**Version**

```shell
argocd: v1.7.3+b4c79cc
  BuildDate: 2020-09-01T23:17:31Z
  GitCommit: b4c79ccb88173604c3786dcd34e83a9d7e8919a5
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
```

**More information**

If step 4 does not add a new line, but **changes an existing line**, the expected behavior occurs.

**Comment by alexmt** [comment]
This is expected behavior that matches `kubectl diff` . Please see https://github.com/argoproj/argo-cd/issues/4537#issuecomment-707997759
