### ISSUE TITLE
Spark application health check stays in unknown state if executors fail to start

### ISSUE THREAD

**Issue by pdrastil** [argoproj/argo-cd#6035]
**Describe the bug**

Custom health check for Spark application CRD fails when status does not contain `executorState` section.

**To Reproduce**

Enforce resource quotas on namespace that will not allow creation of Spark executors.

**Expected behavior**

Argo displays degraded health status for Spark application instead of Unknown state with following error

```
<string>:11: bad argument #1 to pairs (table expected, got nil) stack traceback: [G]: in function 'pairs' <string>:11: in main chunk [G]: ?
```

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/6036
