### ISSUE TITLE
Cluster-Specific ComparisonErrors after v1.8.7 -> 2.0.0 Upgrade

### ISSUE THREAD

**Issue by booleanbetrayal** [argoproj/argo-cd#6039]
**Describe the bug**

Receiving the following error attempting to sync on all applications within a particular cluster (this affects our `argocd` Application as well, as it exists in this cluster):

```
ComparisonError
<string>:6: attempt to index a non-table object(string) with key 'find' stack traceback: <string>:6: in main chunk [G]: ?
```

**To Reproduce**

We upgraded from `1.8.7` to `2.0.0`. In the process, we updated our `argo-cd` Helm chart from `1.0.12` to `1.0.15`. This was done by Syncing the gitops repo changes backing ArgoCD, itself, within ArgoCD. Everything was initially green, but then the above error appeared within "App Conditions" for every Application within one particular cluster. No other Applications in our other two clusters are affected. These Applications cannot be synced, so it is affecting us operationally atm.

**Expected behavior**

No cluster-specific ComparisonErrors for Application Sync attempts.

**Screenshots**

<img width="1091" alt="Screen Shot 2021-04-14 at 4 50 52 PM" src="https://user-images.githubusercontent.com/981825/114790368-e1b36e80-9d41-11eb-88a6-61d87db18f26.png">

<img width="1351" alt="Screen Shot 2021-04-14 at 4 52 23 PM" src="https://user-images.githubusercontent.com/981825/114790389-e8da7c80-9d41-11eb-866e-86632f0f5169.png">

**Version**

```shell
argocd: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

`argocd-application-controller` sanitized (bit chatty, but hopefully grabbed relevant lines):

```

time="2021-04-14T23:06:48Z" level=info msg="updated 'SomeApp' operation (phase: Running)"
time="2021-04-14T23:06:48Z" level=info msg="Initialized new operation: {&SyncOperation{Revision:some-commit-revision-id,Prune:false,DryRun:false,SyncStrategy:&SyncStrategy{Apply:nil,Hook:&SyncStrategyHook{SyncStrategyApply:SyncStrategyApply{Force:false,},},},Resources:[]SyncOperationResource{},Source:nil,Manifests:[],SyncOptions:[],} {some.user@example.com false} [] {0 nil}}" application=SomeApp
time="2021-04-14T23:06:48Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-04-14T23:06:48Z" level=info msg="Comparing app state (cluster: https://SOME-CLUSTER-URL.com, namespace: SomeApp)" application=SomeApp
time="2021-04-14T23:06:48Z" level=info msg="getRepoObjs stats" application=SomeApp build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=48 unmarshal_ms=48 version_ms=0
time="2021-04-14T23:06:48Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-04-14T23:06:48Z" level=info msg="updated 'SomeApp' operation (phase: Error)"
time="2021-04-14T23:06:48Z" level=info msg="Sync operation to some-commit-revision-id failed: ComparisonError: <string>:6: attempt to index a non-table object(string) with key 'find'\nstack traceback:\n\t<string>:6: in main chunk\n\t[G]: ?" application=SomeApp dest-namespace=SomeApp dest-server="https://SOME-CLUSTER-URL.com" reason=OperationCompleted type=Warning
time="2021-04-14T23:06:48Z" level=info msg="Refreshing app status (controller refresh requested), level (2)" application=SomeApp
time="2021-04-14T23:06:48Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-04-14T23:06:48Z" level=info msg="Comparing app state (cluster: https://SOME-CLUSTER-URL.com, namespace: SomeApp)" application=SomeApp
time="2021-04-14T23:06:49Z" level=info msg="getRepoObjs stats" application=SomeApp build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=343 unmarshal_ms=342 version_ms=0
time="2021-04-14T23:06:49Z" level=info msg="No status changes. Skipping patch" application=argocd
time="2021-04-14T23:06:49Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-04-14T23:06:49Z" level=info msg="Comparing app state (cluster: https://SOME-CLUSTER-URL.com, namespace: argocd)" application=argocd
time="2021-04-14T23:06:49Z" level=info msg="Update successful" application=SomeApp
time="2021-04-14T23:06:49Z" level=info msg="Reconciliation completed" application=SomeApp dedup_ms=0 dest-name=some-cluster dest-namespace=SomeApp dest-server="https://SOME-CLUSTER-URL.com" diff_ms=84 fields.level=2 git_ms=343 health_ms=2 live_ms=1 settings_ms=0 sync_ms=0 time_ms=481

```

**Comment by booleanbetrayal** [comment]
So, I traced this down to [this `ExternalSecret` health check](https://github.com/argoproj/argo-cd/blob/b37eee1054e42c873699460dd5e2447c2f9fe5a6/resource_customizations/kubernetes-client.io/ExternalSecret/health.lua), which led me to discover that we had just recently broken a `kubernetes-external-secrets` `ServiceAccount`. This manifests with the following `ExternalSecret` error status (`ERROR, Missing credentials in config`):

```
spec:
  backendType: secretsManager
  data:
  - key: service-name/secret_key_1-5Lzgxi
    name: secret_key_1
    property: null
  region: us-east-1
  roleArn: arn:aws:iam::123456789:role/some-aws-role-arn
status:
  lastSync: "2021-04-13T07:02:21.180Z"
  observedGeneration: 1
  status: ERROR, Missing credentials in config
  ```

So ... Yay! This is an example of a `ExternalSecret` health check validation working ... kinda-ish.   =]

Should I keep this Issue open or is it worthwhile for improving the error handler?

**Comment by Cian911** [comment]
Came here to say we ran into the exact same issue using external secrets. Turned out one of the secrets hadn't been synced correctly which was throwing the same error above. Deleting and re-syncing external secret solved the issue for us.

**Comment by alexmt** [comment]
You are right @Cian911 ,

It passed tests because apparently standard libraries are enabled in tests

https://github.com/argoproj/argo-cd/blob/6fb395f8afb94017fe0f9e4e015306370c25a966/util/lua/lua.go#L60-L61

I'm pretty sure standard libraries are disabled for security reasons. We can add a  `health.lua.useOpenLibs: true` to support complex health checks. E.g.

```
    kubernetes-client.io/ExternalSecret:
      health.lua.useOpenLibs: true
```

Creating feature request to support it. For v2.0 I'm afraid we will have to remove `ExternalSecret` health check and re-introduce it when `useOpenLibs` setting is available

**Comment by alexmt** [comment]
Reverted health check from `release-2.0` branch but keep it in `master`. Created https://github.com/argoproj/argo-cd/issues/6050 that proposes `useOpenLibs` setting

**Comment by ckeragala** [comment]
Hi @alexmt , Could you please tell me how I can deploy Argocd using release-2.0 branch with  health checks for `external-secrets` removed?

**Comment by alexmt** [comment]
Closing since https://github.com/argoproj/argo-cd/issues/6050 has been implemented.

**Comment by XiShanYongYe-Chang** [comment]
> I'm pretty sure standard libraries are disabled for security reasons. 

Hi @alexmt, I'm sorry to bother you. I want to know what security reasons led to the disablement of the standard library, and is there a record of this security reason?
