### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by codex70** [argoproj/argo-cd#6048]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Whenever I try to connect to a helm repository I get an error: x509: certificate signed by unknown authority

for example:

rpc error: code = Unknown desc = Manifest generation error (cached): `helm repo add stable https://charts.helm.sh/stable` failed exit status 1: Error: looks like "https://charts.helm.sh/stable" is not a valid chart repository or cannot be reached: Get "https://charts.helm.sh/stable/index.yaml": x509: certificate signed by unknown authority

I'm sure there's something I'm doing wrong, but I've tried adding certificates, secrets etc. and nothing seems to work. I also don't seem to be able to get any repositories to connect unless I add them via the GUI and set "Skip server verification"

**To Reproduce**

Set the repourl to be any helm chart

**Expected behavior**

The system is able to connect to helm repositories and download the charts.

**Screenshots**

![image](https://user-images.githubusercontent.com/3765397/115017636-1ac11f80-9eb7-11eb-8135-c91b4366807f.png)

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by codex70** [comment]
ArgoCd version: v2.0.0-rc2+960

**Comment by alexmt** [comment]
This is probably environmental specific issue. Just added to https://cd.apps.argoproj.io/settings/repos and repo was added without any error.

I suggest to ssh into argocd pod and `curl https://charts.helm.sh/stable`

**Comment by codex70** [comment]
Hi Alex, and thanks for getting back to me. This is quite interesting, there are 4 pods running:
```
NAME                                                         READY   STATUS    RESTARTS   AGE
pod/argo-cd-argocd-application-controller-6f68dbbffb-26bbz   1/1     Running   0          2d20h
pod/argo-cd-argocd-redis-84c784c894-j4s5z                    1/1     Running   0          2d20h
pod/argo-cd-argocd-repo-server-7494d7bd9c-4w4gq              1/1     Running   0          2d20h
pod/argo-cd-argocd-server-6975845957-gprnv                   1/1     Running   0          2d20h
```
I've done the following to connect to each pod:
`sudo kubectl exec -it -n argocd argo-cd-argocd-application-controller-6f68dbbffb-26bbz /bin/bash`

and then tried to run curl. Each time I get:
`bash: curl: command not found`

**Comment by codex70** [comment]
When I run the docker command to exec into the container as root:

sudo docker exec -it -u root ID-OF-CONTAINER /bin/bash

I am able to run curl and get a standard web page response as expected:
`
*   Trying 185.199.108.153:443...
* TCP_NODELAY set
* Connected to charts.helm.sh (185.199.108.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=charts.helm.sh
*  start date: Apr 12 20:02:15 2021 GMT
*  expire date: Jul 11 20:02:15 2021 GMT
*  subjectAltName: host "charts.helm.sh" matched cert's "charts.helm.sh"
*  issuer: C=DE; ST=HE; O=Lurse AG; OU=IT; CN=pan.lurseag.de; emailAddress=admin@lurse.de
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x555c939e13c0)
> GET /stable/ HTTP/2
> Host: charts.helm.sh
> user-agent: curl/7.68.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200
< server: GitHub.com
< content-type: text/html; charset=utf-8
< x-origin-cache: HIT
< last-modified: Wed, 23 Dec 2020 15:27:43 GMT
< access-control-allow-origin: *
< etag: "5fe361ef-e64"
< expires: Mon, 19 Apr 2021 08:29:16 GMT
< cache-control: max-age=600
< x-proxy-cache: MISS
< x-github-request-id: A3DA:CE42:1764268:1829CB0:607D3D04
< accept-ranges: bytes
< date: Mon, 19 Apr 2021 08:19:16 GMT
< via: 1.1 varnish
< age: 0
< x-served-by: cache-hhn4038-HHN
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1618820357.508201,VS0,VE84
< vary: Accept-Encoding
< x-fastly-request-id: dedd590d0912326b50b3e356722e26f52dcc79c2
< content-length: 3684
<
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


<title>Helm Stable | charts</title>
<meta name="generator" content="Jekyll v3.9.0" />
<meta property="og:title" content="Helm Stable" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="⚠️(OBSOLETE) Curated applications for Kubernetes" />
<meta property="og:description" content="⚠️(OBSOLETE) Curated applications for Kubernetes" />
<link rel="canonical" href="https://charts.helm.sh/stable/" />
<meta property="og:url" content="https://charts.helm.sh/stable/" />
<meta property="og:site_name" content="charts" />
<script type="application/ld+json">
{"@type":"WebPage","headline":"Helm Stable","url":"https://charts.helm.sh/stable/","description":"⚠️(OBSOLETE) Curated applications for Kubernetes","@context":"https://schema.org"}</script>


    <link rel="stylesheet" href="/assets/css/style.css?v=ec7ff964b33661a7d11de5c5847a0baae1fefbac">
  </head>
  <body>
    <div class="container-lg px-3 my-5 markdown-body">

      <h1><a href="https://charts.helm.sh/">charts</a></h1>


      <h1 id="helm-stable">Helm Stable</h1>

<p><a href="https://opensource.org/licenses/Apache-2.0"><img src="https://img.shields.io/badge/License-Apache%202.0-blue.svg" alt="License" /></a></p>

<h2 id="usage">Usage</h2>

<p><a href="https://helm.sh">Helm</a> must be installed to use the charts.
Please refer to Helm’s <a href="https://helm.sh/docs/">documentation</a> to get started.</p>

<p>Once Helm is set up properly, add the repo as follows:</p>

<div class="language-console highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="go">helm repo add stable https://charts.helm.sh/stable
</span></code></pre></div></div>

<p>You can then run <code class="language-plaintext highlighter-rouge">helm search repo stable</code> to see the charts, or browse on CNCF <a href="https://artifacthub.io/packages/search?page=1&amp;repo=helm-stable">Artifact Hub</a>.</p>

<h2 id="contributing">Contributing</h2>


<p>⚠️ Note the <a href="https://github.com/helm/charts/blob/master/README.md#status-of-the-project">status of the project</a>, <a href="https://github.com/helm/charts/blob/master/README.md#deprecation-timeline">deprecation timeline</a>, and the ongoing effort to <a href="https://github.com/helm/charts/issues/21103">relocate charts to new repos</a>.</p>


<p>We’d love to have you contribute! Please refer to our <a href="https://github.com/helm/charts/blob/master/CONTRIBUTING.md">contribution guidelines</a> for details.</p>

<h2 id="license">License</h2>


<p><a href="https://github.com/helm/charts/blob/master/LICENSE">Apache 2.0 License</a>.</p>



      <div class="footer border-top border-gray-light mt-5 pt-3 text-right text-gray">
        This site is open source. <a href="https://github.com/helm/charts/edit/gh-pages/stable/README.md">Improve this page</a>.
      </div>

    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.0/anchor.min.js" integrity="sha256-lZaRhKri35AyJSypXXs4o6OPFTbTmUoltBbDCbdzegg=" crossorigin="anonymous"></script>
    <script>anchors.add();</script>

  </body>
</html>
* Connection #0 to host charts.helm.sh left intact
`

**Comment by codex70** [comment]
OK, after using the docker command to ssh directly into the container as root I was able install curl and got the following output:

`
*   Trying 185.199.111.153:443...
* TCP_NODELAY set
* Connected to charts.helm.sh (185.199.111.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate in certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
`

I will look into this and report back.

**Comment by codex70** [comment]
OK, I've been able to find out the pem file that I need to copy to the cluster. Is there any way I can add the pem file to the cluster using the helm charts I used to set up argocd? 

If not, is there any way I can add it directly to kubernetes as this is likely to affect all of the application running within the cluster?

**Comment by jannfis** [comment]
@codex70 Do you have any component in your outbound path that intercepts TLS connections and uses its own certificate?

As for your question regarding how to integrate this certificate, I suggest you add it to Argo CD as described in the [documentation](https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#self-signed-untrusted-tls-certificates)

**Comment by codex70** [comment]
Hi, I haven't confirmed with our infrastructure team, but it looks likely that this is the case. I did try adding the certificate using the web ui, but will try again, just to confirm

**Comment by jannfis** [comment]
> but will try again, just to confirm

Please be aware that it might take some time between adding the cert via UI and the change to be propagated to the Argo CD pods. You can validate a cert has been propagated by looking at `/app/config/tls` in the `argocd-repo-server` pods and check for a file named like the server existing there.

**Comment by codex70** [comment]
I have created a certificate as described in the documentation, it appears to have created correctly with the details of CN, OU etc. showing as expected. When I ssh into the server running the argocd-repo-server pod and check in /app/config/tls the directory is empty

**Comment by jannfis** [comment]
Usually, it should take at most 1 minute, depending on the cluster's load (the certificates are propagated through a volume mount of the mounts). But if the directory was empty (have you checked also with `ls -a`?), it smells like there's something wrong with your installation. It should at least contain some marker files from the volume mount, i.e.

```
argocd@argocd-repo-server-5f687b5c5d-trfmb:~$ ls -a /app/config/tls/
.  ..  ..2021_04_19_16_11_08.012522581	..data
```

**Comment by codex70** [comment]
Yes, after nearly half an hour the `tls` directory is still empty. 
`
root@argo-cd-argocd-repo-server-7494d7bd9c-4w4gq:/app/config/tls# ls -la
total 8
drwxr-xr-x 2 root root 4096 Mar 29 21:21 .
drwxr-xr-x 1 root root 4096 Mar 29 21:21 ..
`

I also copied the pem file to the pod's `/usr/share/ca-certificates/` and added it using `update-ca-certificates --verbose`. Now curl works from within the pod, but argocd still isn't working.

**Comment by jannfis** [comment]
I think your installation is somehow broken. Do you actually have the required ConfigMap mounts on the `argocd-repo-server` pods?

```shell
$ kubectl -n argocd describe deployments.apps argocd-repo-server 
Name:                   argocd-repo-server
Namespace:              argocd
...
Pod Template:
  Labels:  app.kubernetes.io/name=argocd-repo-server
  Containers:
   argocd-repo-server:
...
    Mounts:
      /app/config/gpg/keys from gpg-keyring (rw)
      /app/config/gpg/source from gpg-keys (rw)
      /app/config/reposerver/tls from argocd-repo-server-tls (rw)
      /app/config/ssh from ssh-known-hosts (rw)
      /app/config/tls from tls-certs (rw)
  Volumes:
   ssh-known-hosts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      argocd-ssh-known-hosts-cm
    Optional:  false
   tls-certs:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      argocd-tls-certs-cm
    Optional:  false
...
```

The `ssh-known-hosts` and `tls-certs` need to be mounted to the pod, but I fear they aren't.

How did you actually install Argo CD?

What versionb

**Comment by codex70** [comment]
First, I installed using Helm, and it seems to have added an extra 'argo-cd' to the front of the name of all the items: 
```
adminkubernetes@node1:~$ sudo kubectl -n argocd describe deployments.apps argo-cd-argocd-repo-server
Name:                   argo-cd-argocd-repo-server
Namespace:              argocd
...
Pod Template:
  Labels:           app.kubernetes.io/component=repo-server
                    app.kubernetes.io/instance=argo-cd
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=argocd-repo-server
                    app.kubernetes.io/part-of=argocd
                    app.kubernetes.io/version=v2.0.0-rc2
                    helm.sh/chart=argo-cd-2.17.5
  Service Account:  default
  Containers:
   repo-server:
    Image:      argoproj/argocd:v2.0.0-rc2
...
    Mounts:
      /app/config/gpg/keys from gpg-keyring (rw)
      /app/config/ssh from ssh-known-hosts (rw)
      /tmp from tmp-dir (rw)
  Volumes:
   gpg-keyring:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
   ssh-known-hosts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      argocd-ssh-known-hosts-cm
    Optional:  false
   tmp-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
...
```
So it looks like you're correct, the link to tls-cers is missing

**Comment by codex70** [comment]
This appears to be an issue with the helm configuration. I've the following to the helm file:
```
  configs:
    tlsCerts:
       data: CERT DATA

```
upgraded the application and now the /app/config/tls directory exists, but still isn't working as expected. I'm tempted to try starting again without using Helm

**Comment by jannfis** [comment]
I'm unfortunately not very familiar with the Helm chart, but maybe you can ask its maintainers for support on this issue?

**Comment by codex70** [comment]
@jannfis first of all, a big thank you for all of your help.

I've now completely uninstalled the Helm version and re-installed using the kubectl yaml as described in the "Getting Started" documentation. Unfortunately it looks like I've ended up with exactly the same problem, it's saying that there is an unsigned certificate.

This time, it has mounted the volumes, and I see the certificate I have added in the `/app/config/tls/` directory when I exec into the repo-server pod. Unfortunately I cannot now run curl from inside the pod, and even as root I am unable to install anything using `apt-get` as I'm seeing `(1: Operation not permitted)` when I try to run `apt-get update`

It looks like there's little else that I can do. I can install things that are in a repo if I add it manually and tell it to "Skip server verification". Obviously this isn't ideal, especially in a production environment, but better than nothing.

**Comment by jannfis** [comment]
This seems weird. You do have added the certificate with a key (server name) of `charts.helm.sh`, right? 

Also, does the PEM file contain any intermediate certificate that would be required to validate the TLS endpoint?

**Comment by codex70** [comment]
@jannfis I think you may have just given me what I need to fix it! I had added each of the certificates individually as there were 3 different certificates. It looks like I needed to be really careful in making sure that each of the "server name" entries that I added exactly matched the CN in the certificate.  I also added all 3 certificates for the repository bitnami that I was trying to connect to:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tls-certs-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  charts.bitnami.com: |
    -----BEGIN CERTIFICATE-----
    MIIDljCCAn6gAwIBAgIQb89mGA9h56VJB9EC2fk1wTANBgkqhkiG9w0BAQsFADBy
    ....
    hQV01JCvbSlVsDYtFrurp00CmSkUkolKOZGCQKnaT7742ZS80i/CeEURTUjNzYWv
    op0EHzW+bCnqdQ==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFiDCCBHCgAwIBAgITHQAAABIHQKGsF7bFigAAAAAAEjANBgkqhkiG9w0BAQsF
    ....
    J3/1AxCkmIweGBN380I8xkDzC9lbM9CYubpCHg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDdzCCAl+gAwIBAgIQHAsKoFuqr7pCBPybhym4rzANBgkqhkiG9w0BAQsFADBC
    ....
    +RyI0EZ4PV4OyS39EIUKBCRyCoB6ccKcf6df
    -----END CERTIFICATE-----
```
I'm not sure at the moment which of these 2 fixed the issue (or even whether I should do what I've shown above), but it appears to have fixed the issue! Thanks you once again.

**Comment by jannfis** [comment]
Just to summarize what's in https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#self-signed-untrusted-tls-certificates:

Argo CD uses a kind of certificate pinning - that means, each certificate is pinned to the name of the repository _server_, and must be configured accordingly. The CN in the configured certificate is irrelevant, as long as it can be used to validate the server's certificate (e.g. when you supply a CA certificate to validate TLS connections). What is relevant is the certificate supplied by the remote server - this needs to be properly set-up with a SAN that actually identifies the server (through SAN extension `DNS:<servername>`, for example). One of the SAN entries must match the name of the server as being used to connect to it.

If this is working now, can we close this issue then?

**Comment by codex70** [comment]
@jannfis once again, thanks for all of your help and the explanation. Yes I am now closing the issue.

**Comment by Meza1923** [comment]
Hey, 
I saw this case cause I have similar problem.

I have setup all the chain of my helm repo and also his certificate, 
in the pod I can see the certificates in /app/config/tls/. 
although all this, I still getting  "x509: certificate signed by unknown authority".

It's important to say that I have already success to establish connection to the helm-repo, 
but I try  to do it again, and it's failed. 

I feeling that I'm not completely understand the process, so there is someone who can help me solved this issue?

**Comment by GitHubFor122** [comment]
I meet such issue, what is soltuion ?

**Comment by rishabh625** [comment]
@GitHubFor122 : user was facing issues due to non mounted of vol in repo-server and incorrect addition of certs, fixing those fixed for them , what issue u r facing?

**Comment by GitHubFor122** [comment]
the issue happening in helm pull/push <registry>,  i guess it is helm issue

**Comment by Zeratoxx** [comment]
Hi, is it possible to mount `argocd-tls-certs-cm` in Pods outside of the `argocd` namespace?

**Comment by neo502721** [comment]
> Hi, is it possible to mount `argocd-tls-certs-cm` in Pods outside of the `argocd` namespace?

This is not support by kubernetes to mount other namesapce's configMap or Secret.

**Comment by geowalrus4gh** [comment]
> SAN extension

would this work with wildcard certificates too ? In my case the certificate works only when installed in to the argocd pod.

**Comment by geowalrus4gh** [comment]
> Just to summarize what's in https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#self-signed-untrusted-tls-certificates:
> 
> Argo CD uses a kind of certificate pinning - that means, each certificate is pinned to the name of the repository _server_, and must be configured accordingly. The CN in the configured certificate is irrelevant, as long as it can be used to validate the server's certificate (e.g. when you supply a CA certificate to validate TLS connections). What is relevant is the certificate supplied by the remote server - this needs to be properly set-up with a SAN that actually identifies the server (through SAN extension `DNS:<servername>`, for example). One of the SAN entries must match the name of the server as being used to connect to it.
> 
> If this is working now, can we close this issue then?

would this work with wildcard certificates too ? In my case the certificate works only when installed in to the argocd pod.

> 

would this work with wildcard certificates too ? In my case the certificate works only when installed in to the argocd pod.
