### ISSUE TITLE
Support Dynamic Namespaces via Kustomize

### ISSUE THREAD

**Issue by snarlysodboxer** [argoproj/argo-cd#6067]
# Summary

Add support for `kustomize edit set namespace <name>` in `Application` CRD.

# Motivation

`Application.spec.destination.namespace` is often insufficient for deploying to dynamic namespaces. Kubectl can set objects' `metadata.namespace` (only if unset,) but it does not set `ClusterRoleBinding.subjects[*].namespace`, `APIService.spec.service.namespace`, namespace in CustomResource objects, and more. Kustomize handles changing the namespace in all the right places, even custom places via transformerConfigs, all by setting `namespace: <name>` in the kustomization.yaml.

This would better support things like namespaced PR based ephemeral environments, client-per-namespace environments, and those of us who like to explicitly set namespace in our configs rather than use the one in the kubeconfig.

# Proposal

ArgoCD already implements `kustomize edit set ...` commands, to change `commonAnnotations`, `commonLabels`, `images`, `namePrefix`, and `nameSuffix`, all configured via `Application.spec.source.kustomize.<config>`. I propose we implement `Application.spec.source.kustomize.namespace` which runs `kustomize edit set namespace <name>`.

**Comment by danopia** [comment]
I just ran into this with the error message `ClusterRoleBinding.rbac.authorization.k8s.io "example" is invalid: subjects[0].namespace: Required value`. Maybe that now helps other users find this issue via search.

Since the helm integration seemingly plumbs namespace through for the chart to rig up, I expected the `Application.spec.destination.namespace` value to be enough, but `Application.spec.source.kustomize.namespace` would be a workable solution too.

**Comment by zfrhv** [comment]
Any updates on this issue?

**Comment by qixiaobo** [comment]
Look for this

**Comment by snarlysodboxer** [comment]
I'd like to work on this, but am unsure if this enhancement proposal has been accepted. Could we get some feedback on this?

**Comment by crenshaw-dev** [comment]
Sorry for the lack of communication on this thread! Just merged Andrew's PR, the feature will be in 2.7. :-)

**Comment by snarlysodboxer** [comment]
This is excellent! Thank you, this allows us to remove a ton of complexity in our configs.

In case anyone is looking for a link documenting this feature: https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#setting-the-manifests-namespace
