### ISSUE TITLE
App creation in UI not working anymore

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#6068]
**Describe the bug**

One of the recent changes between `5bc72979` and now has broken Argo CD. It is not possible to access repositories anymore. 

**To Reproduce**

* Run Argo CD from the latest commit in `master`
* Create a new application from via the UI
* The "Repository" dropdown in the app creation dialogue doesn't work anymore
* If repository entered manually, the list of directories is shown (weird enough)
* If a source path is chosen that contains a Kustomize application, dialogue will still show `Directory` as type
* If you click on "Create", the error message shown is "Repository is not found"
  
**Expected behavior**

Application created successfully.

**Further information**

The last known working code was from commit `5bc72979`, which I had running before noticing this behavior. Rolling back to that version lets me create the application. So any commit between the most recent one at time of this issue (`9c5ed913`) and `5bc72979` must be the culprit.

**Comment by jannfis** [comment]
This seems to only affect application creation via UI:

```
$ ./dist/argocd app create guestbook --repo https://github.com/argoproj/argocd-example-apps --path kustomize-guestbook --dest-server https://kubernetes.default.svc --dest-namespace guestbook
application 'guestbook' created

**Comment by jannfis** [comment]
From the logs, when creating app via UI (in this case, repo is `https://github.com/argoproj/argocd-example-apps`)

Giving the repo manually and chosing the path:
```
07:52:20    api-server | INFO[0234] received unary call /repository.RepositoryService/GetAppDetails  grpc.method=GetAppDetails grpc.request.claims=null grpc.request.content="source:<repoURL:\"https://github.com/argoproj\" path:\"kustomize-guestbook\" targetRevision:\"HEAD\" chart:\"\" > appName:\"guestbook-two\" " grpc.service=repository.RepositoryService grpc.start_time="2021-04-20T07:52:20Z" span.kind=server system=grpc
07:52:21    api-server | ERRO[0234] finished unary call with code Unknown         error="rpc error: code = Unknown desc = repository not found" grpc.code=Unknown grpc.method=GetAppDetails grpc.service=repository.RepositoryService grpc.start_time="2021-04-20T07:52:20Z" grpc.time_ms=355.634 span.kind=server system=grpc
07:52:21   repo-server | ERRO[0235] finished unary call with code Unknown         error="repository not found" grpc.code=Unknown grpc.method=GetAppDetails grpc.request.deadline="2021-04-20T07:53:20Z" grpc.service=repository.RepoServerService grpc.start_time="2021-04-20T07:52:20Z" grpc.time_ms=324.5 span.kind=server system=grpc
```

Creating the app:
```
07:53:41    api-server | INFO[0315] received unary call /application.ApplicationService/Create  grpc.method=Create grpc.request.claims=null grpc.request.content="%!v(PANIC=String method: reflect.Value.Interface: cannot return value obtained from unexported field or method)" grpc.service=application.ApplicationService grpc.start_time="2021-04-20T07:53:41Z" span.kind=server system=grpc
07:53:42   repo-server | ERRO[0316] finished unary call with code Unknown         error="repository not found" grpc.code=Unknown grpc.method=TestRepository grpc.request.deadline="2021-04-20T07:54:41Z" grpc.service=repository.RepoServerService grpc.start_time="2021-04-20T07:53:41Z" grpc.time_ms=451.384 span.kind=server system=grpc
07:53:42    api-server | INFO[0315] finished unary call with code InvalidArgument  error="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: repository not accessible: rpc error: code = Unknown desc = repository not found" grpc.code=InvalidArgument grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2021-04-20T07:53:41Z" grpc.time_ms=480.916 span.kind=server system=grpc
```

**Comment by jannfis** [comment]
Tracked down to https://github.com/argoproj/argo-cd/commit/6fb395f8afb94017fe0f9e4e015306370c25a966

@rbreeze Can you please have a look?

**Comment by alexmt** [comment]
thank you for investigation @jannfis !

**Comment by jessesuen** [comment]
Doesn't affect v2.0 only master (v2.1)

**Comment by alexmt** [comment]
Same error on application details page. Cannot use "edit" to change app repo url
