### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by bainss** [argoproj/argo-cd#6101]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

we have a local helm chart registry that has a self signed certificate,  the certificate file for this host has been added and can be seem mounted in /app/config/tls in both the argocd  and repo server pods

in the 'hostnamed' file

when trying to sync to the private helm registry the following error is presented.

rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: could not download https://private-helm-registry/charts/postgresql-6.3.12.tgz: Get "https://private-helm-registry/charts/postgresql-6.3.12.tgz": x509: certificate signed by unknown authority

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
argocd: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
**Logs**

```
Paste any relevant application logs here.
```

**Comment by jgwest** [comment]
Dupe to https://github.com/argoproj/argo-cd/issues/3539
