### ISSUE TITLE
CLI - argocd login error - FailedPrecondition unexpected content type

### ISSUE THREAD

**Issue by FourFifthsCode** [argoproj/argo-cd#611]
When logging in from CLI using command:
`argocd login`

Receiving this error after entering username and password:
`FATA[0016] rpc error: code = FailedPrecondition desc = transport: received the unexpected content-type "text/plain; charset=utf-8"`

Server is also using self signed cert.

**Comment by jessesuen** [comment]
@FourFifthsCode 

1. can you give more details about how the argocd-service is exposed? (e.g. is the service of type LoadBalancer? Are you using ingress?) 

2. Does the same error happen if you port forward and attempt to login to localhost?
```
kubectl port-forward -n argocd svc/argocd-server 8443:443
argocd login localhost:8443
```

**Comment by jessesuen** [comment]
Based on the error message "transport: received the unexpected content-type "text/plain;" this is an issue with Ingress with the request hitting the default backend. Will be providing guidance on how to use ingress with ArgoCD in https://github.com/argoproj/argo-cd/issues/585 and upcoming documentation. See issue #585 for a working ingress manifest
