### ISSUE TITLE
ComparisonError - The provided continue parameter is too old to display a consistent list result

### ISSUE THREAD

**Issue by liorfranko** [argoproj/argo-cd#6113]
**Describe the bug**
All the applications are stuck in Unknown, with the following error:
`failed to sync cluster https://172.20.0.1:443: failed to load initial state of resource Runner.actions.summerwind.dev: The provided continue parameter is too old to display a consistent list result. You can start a new list without the continue parameter, or use the continue token in this response to retrieve the remainder of the results. Continuing with the provided token results in an inconsistent list - objects that were created, modified, or deleted between the time the first chunk was returned and now may show up in the list.`

**To Reproduce**
Don't know what caused it.

**Screenshots**
![Screen Shot 2021-04-27 at 16 45 49](https://user-images.githubusercontent.com/20726865/116252265-137ff880-a778-11eb-95ad-0c5587fa7581.png)
![Screen Shot 2021-04-27 at 16 46 01](https://user-images.githubusercontent.com/20726865/116252251-111d9e80-a778-11eb-852d-384d77b91330.png)

**Version**
```shell
argocd: v1.8.6+6dbbb18
  BuildDate: 2021-02-26T21:21:11Z
  GitCommit: 6dbbb18aa963a0c9e608fcfeab4065c6fb46f8cb
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
```

**Comment by alexmt** [comment]
This error means that K8S API is too slow and the controller is unable to use pagination to load `actions.summerwind.dev/Runner` resources. I suspect you would get the same result if you run `kubectl get runners --all-namespaces`

The workaround is to exclude runners from the list of monitored resources. Can you try to add this to `argocd-cm` ConfigMap?

```yaml
data:
  resource.exclusions: |
    - apiGroups:
      - actions.summerwind.dev
      kinds:
      - Runner
```

**Comment by liorfranko** [comment]
Thanks, it was indeed a problem on our side, we had 750k runners.

**Comment by tho93** [comment]
@alexmt I'm running into a similar issue. Any way I can exclude a subset of resources by annotation/label from the list of monitored resources?
