### ISSUE TITLE
UI: Tabs urls don't work anymore

### ISSUE THREAD

**Issue by rbreeze** [argoproj/argo-cd#6128]
To reproduce: 

1. Visit [cd.apps.argoproj.io](https://cd.apps.argoproj.io)
2. Go to an application, then switch to pod view
3. Click a pod to get the pod menu, then click Logs
4. The logs tab isn't opened

**Comment by alexmt** [comment]
Looks like it is still broken. Same steps to reproduce. @rbreeze FYI
