### ISSUE TITLE
Special handling of CustomResourceDefinitions

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#613]
I think we need to consider adding special handling when dealing with CustomResourceDefinitions, since deletion of the CRD will cause all objects of that type to be deleted, across all namespaces.

1. I don't think the CRD should be considered part of any single "app"
2. By virtue of 1, we should not inject our label on CRDs
3. Also by virtue of 1, we should not delete CRDs, at least not by default

**Comment by jessesuen** [comment]
Reopening because I still see our labels getting injected into CRDs

**Comment by alexmt** [comment]
looking
