### ISSUE TITLE
Receive webhook notifications to trigger sync

### ISSUE THREAD

**Issue by bergkvist** [argoproj/argo-cd#6146]
# Summary

Provide a way for ArgoCD to receive webhook notifications to trigger a sync.

Example of creating a webhook in GitLab: 
![image](https://user-images.githubusercontent.com/410028/116830169-86d69f80-aba8-11eb-9466-ed191807cd83.png)

# Motivation

I've enabled automatic sync using `argocd app set bergkvist-default --sync-policy automated`, but it takes several minutes from when the push happens until it is detected by ArgoCD. I imagine might be a result of ArgoCD polling the repository every few minutes.

# Proposal

I would love for ArgoCD to react immediately to push events, and having ArgoCD receive webhook notifications might be an easy way of accomplishing this, since GitHub and GitLab already supports sending webhook events when a push happens.

**Comment by mayzhang2000** [comment]
Is this what you are looking for? https://argo-cd.readthedocs.io/en/latest/operator-manual/webhook/

**Comment by bergkvist** [comment]
Oh, that seems to be exactly what I'm looking for! Thanks @mayzhang2000 !
