### ISSUE TITLE
EKS Clusters Broken Due To ReadOnly Filesystem

### ISSUE THREAD

**Issue by toneill818** [argoproj/argo-cd#6148]
Checklist:

* [ X ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X ] I've included steps to reproduce the bug.
* [ X ] I've pasted the output of `argocd version`.

**Describe the bug**
It appears after setting `readOnlyRootFilesystem`   to `true` prevents the call to get-token since /home/argocd/.aws is read only.
PR #5819 changed the FS to read only

**To Reproduce**

Add an AWS EKS cluster with a role-arn to assume
Create an application that targets this cluster

**Expected behavior**

The container should be able to call get-token

**Version**

```shell
argocd: v2.0.1+33eaf11
  BuildDate: 2021-04-15T22:31:51Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.0+fad9030
```

**Logs**
```
[errno 30] read-only file system: '/home/argocd/.aws'
```

**Comment by jannfis** [comment]
Thanks for reporting this, @toneill818.

The workaround most likely is to have `/home/argocd` become an `emptyDir` volume mount.

The change from PR #5819 has not yet been released, so this affects only `latest` images.
