### ISSUE TITLE
Buggy CLI can't get account

### ISSUE THREAD

**Issue by hakuno** [argoproj/argo-cd#6151]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Given the list of accounts:

```
$ argocd account list --grpc-web
NAME       ENABLED  CAPABILITIES
admin      true     login
bitbucket  true     apiKey
```

It retrieves `admin` only.

**To Reproduce**

```
$ argocd account get bitbucket --grpc-web
Name:               admin
Enabled:            true
Capabilities:       login

Tokens:
NONE
```

It returns `admin` only.

**Expected behavior**

I need to get the selected user.

**Version**

```shell
argocd: v2.0.1+33eaf11
  BuildDate: 2021-04-15T22:31:51Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Comment by hakuno** [comment]
I found the real problem. The CLI seems okay.

But the documentation is missing some informations.

I sent this PR https://github.com/argoproj/argo-cd/pull/6152

**Comment by hakuno** [comment]
Thank you all @rbreeze @alexmt

**Comment by alexmt** [comment]
Thank you for fixing the doc @hakuno !
