### ISSUE TITLE
proposal: docs: Implement installation guide for ArgoCD Server in the getting started

### ISSUE THREAD

**Issue by Dentrax** [argoproj/argo-cd#6164]
# Summary
In order to prepare our working environment, we need to add a new section on the [Getting Started](https://argoproj.github.io/argo-cd/getting_started) page that will describe how to install the Argo CD API Server on the cluster, just before [Access The Argo CD API Server](https://argoproj.github.io/argo-cd/getting_started/#3-access-the-argo-cd-api-server) part.

# Motivation
As someone who new at the ArgoCD, I was just following the Getting Started documentation. I followed the document step by step until [Download Argo CD CLI](Download Argo CD CLI) section. In the next section, which is [Access The Argo CD API Server](https://argoproj.github.io/argo-cd/getting_started/#3-access-the-argo-cd-api-server), it does not show the installation and running instructions for the Argo CD API server, so I think there is a missing part called "Installing Argo CD API Server". We _may_ need to create an installation guide for `argocd-server` service on the cluster. I had to incomplete the demo here because the Getting Started page couldn't tell me exactly what should I do in order to prepare our environment just after install the `argocd` CLI.

<img width="851" alt="Screen Shot 2021-05-05 at 14 03 43" src="https://user-images.githubusercontent.com/16493751/117131878-b7862700-adaa-11eb-9ac1-a22f31980cac.png">

**Comment by dominikbraun** [comment]
> In the next section, which is Access The Argo CD API Server, it does not show the installation and running instructions for the Argo CD API server, so I think there is a missing part called "Installing Argo CD API Server".

This is described in the [1. Install Argo CD](https://argoproj.github.io/argo-cd/getting_started/#1-install-argo-cd) section. The `kubectl apply` command installs the API server.
