### ISSUE TITLE
Rename server.crt and server.key to tls.crt and tls.key

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#617]
We should update the argocd-secret such that it uses the standard `tls.crt` and `tls.key` keys in the secret instead of its current keys: server.crt and server.key. This will make the argocd-secret compatible with things like Ingress and Cert Manager. Note that this will require the user to perform a manual step of copying or renaming the keys before the upgrade and needs to be documented as a breaking change in the release notes.

**Comment by jessesuen** [comment]
I confirmed that cert-manager will update an existing secret with just those two keys and not replace the entire secret:
https://github.com/jetstack/cert-manager/pull/221

/cc @ke

**Comment by mrbobfrog** [comment]
> I confirmed that cert-manager will update an existing secret with just those two keys and not replace the entire secret:
> jetstack/cert-manager#221

@jessesuen We may want to add that tidbit to the argocd docs to save the next person the trouble of tracking release notes to issues and comments...  I can make a PR
