### ISSUE TITLE
Update documentation on resource customizations 

### ISSUE THREAD

**Issue by jmatis-bullhorn** [argoproj/argo-cd#6175]
# Summary

when customizing sealed-secrets in order for app to not stay in a perpetual Progressing state I struggled to understand when to use `resource.customizations.health` as per current documentation versus:
```
 resource.customizations: |-
    bitnami.com/SealedSecret:
      health.lua: |
```
which eventually worked (please note missing `.health`. 
This should either be part of the submitted https://github.com/argoproj/argo-cd/tree/master/resource_customizations or properly explained https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/health.md 
Also  `bitnami.com/SealedSecret` was just plain guesswork (this might be related to my current knowledge of Kubernetes). 
I'm guessing it's related to 

```
spec:
  conversion:
    strategy: None
  group: bitnami.com
  names:
    kind: SealedSecret

``` 
from 
`# kubectl get crd sealedsecrets.bitnami.com -o yaml`

but again - health.md example does not use `/` but `_` :
 
Following example demonstrates a health check for cert-manager.io/Certificate.
```data:
  resource.customizations.health.cert-manager.io_Certificate: |
```

# Motivation

documentation update

# Proposal

by updating https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/health.md

**Comment by dnskr** [comment]
It would be helpful to have list of all possible health statuses and some explanations for them just to be clear when to use what.
For now I found only [this](https://github.com/argoproj/argo-cd/blob/b37eee1054e42c873699460dd5e2447c2f9fe5a6/server/badge/color.go#L20-L27):
```
	HealthStatusColors = map[health.HealthStatusCode]color.RGBA{
		health.HealthStatusDegraded:    Red,
		health.HealthStatusHealthy:     Green,
		health.HealthStatusMissing:     Purple,
		health.HealthStatusProgressing: Blue,
		health.HealthStatusSuspended:   Grey,
		health.HealthStatusUnknown:     Purple,
	}
```

**Comment by kshamajain99** [comment]
@jmatis-bullhorn Documentation mentioned in https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/health.md is correct and up-to date. The resource it looks different in  https://github.com/argoproj/argo-cd/tree/master/resource_customizations is because `resource.customizations: |-
    bitnami.com/SealedSecret:
      health.lua: |` is older way of submitting customization values vs `resource.customizations.health.cert-manager.io_Certificate:` is the updated way.
      
You can see the older versions of doc https://argo-cd.readthedocs.io/en/release-1.8/

**Comment by ChetHosey** [comment]
@kshamajain99 is the previous method still supported? The current Operator docs [still reference it](https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#resource-customizations-example). Specifically:

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: resource-customizations
spec:
  resourceCustomizations: |
    PersistentVolumeClaim:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.phase ~= nil then
            if obj.status.phase == "Pending" then
              hs.status = "Healthy"
              hs.message = obj.status.phase
              return hs
            end
            if obj.status.phase == "Bound" then
              hs.status = "Healthy"
              hs.message = obj.status.phase
              return hs
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for certificate"
        return hs
```

I couldn't find anything in the CRD that seemed to support generating the newer format.

**Comment by servo1x** [comment]
Hi, anyone have an updated answer for this? I am confused whether we should be using the newer format or not.

**Comment by andrii-korotkov-verkada** [comment]
I'll take a look at this soon, just figuring out a few details about the new format.
