### ISSUE TITLE
argocd cluster add <context> --in-cluster fails with `x509: certificate signed by unknown authority`

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#6233]
It seems the `--in-cluster` flag in `argocd cluster add` can fail like so:

```
$ argocd cluster add <CONTEXT> --in-cluster
 INFO[0001] ServiceAccount "argocd-manager" already exists in namespace "kube-system"  
INFO[0001] ClusterRole "argocd-manager-role" updated     
INFO[0001] ClusterRoleBinding "argocd-manager-role-binding" updated 
 FATA[0002] rpc error: code = Unknown desc = Get "https://kubernetes.default.svc/version?timeout=32s": x509: certificate signed by unknown authority 
```

I believe this is happening because it's trying to use the certs of the kubeconfig rather than the in-cluster certs.

Possible fixes:

1. In CLI, we can nil out the CA/Cert data from the context (hoping that it will fall back to the certificate of the pod). Not sure if this will work:
 
```
			clst := cmdutil.NewCluster(contextName, clusterOpts.Namespaces, conf, managerBearerToken, awsAuthConf, execProviderConf)
			if clusterOpts.InCluster {
				clst.Server = common.KubernetesInternalAPIServerAddr
				clst.Config.TLSClientConfig.CAData = nil   // << don't use cert from context 
				clst.Config.TLSClientConfig.CertData = nil  // << don't use cert from context
			}
```

2. On server side, when we see `https://kubernetes.default.svc` is the cluster being registered, we fill in cert data of the *in-cluster* cert.

```golang
func (s *Server) Create(ctx context.Context, q *cluster.ClusterCreateRequest) (*appv1.Cluster, error) {
	if err := s.enf.EnforceErr(ctx.Value("claims"), rbacpolicy.ResourceClusters, rbacpolicy.ActionCreate, q.Cluster.Server); err != nil {
		return nil, err
	}
	c := q.Cluster
	if c.Server == "https://kubernetes.default.svc" {
		c.Config.TLSClientConfig = // < FILL with in-cluster cert data
	}
```

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexmt** [comment]
Looks like I reopened ticket by mistake. No longer can reproduce the issue
