### ISSUE TITLE
[repo-server]When using json logformat, not all logoutput is json

### ISSUE THREAD

**Issue by yu-croco** [argoproj/argo-cd#6234]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When setting logformat to json, there is a line on repo-server that is not json format.
This is related to https://github.com/argoproj/argo-cd/issues/5641 . It looks like the issue is still unfixed on repo-server. 🤔 

repo-server
```
time="2021-05-13T06:29:36Z" level=info msg=Trace args="[helm template . --name-template foo-bar --namespace foo-bar --values /tmp/values-836517096.yaml --api-versions v1 ...]" dir=/tmp/git@123.45.6.789_foo_bar-helm-charts/aws-load-balancer operation_name="exec helm" time_ms=1609.515198
time="2021-05-13T06:29:35Z" level=info msg=Trace args="[helm dependency build]" dir=/tmp/git@123.45.6.789_foo_bar-helm-charts/foo-bar operation_name="exec helm" time_ms=780.675204
time="2021-05-13T09:16:23Z" level=info msg=Trace args="[git fetch origin --tags --force]" dir=/tmp/git@123.45.6.789_foo_bar-helm-charts operation_name="exec git" time_ms=211.71025
```

**To Reproduce**

Using helm add json as logoutput:

```
argo-cd:
  controller:
    logFormat: json
  server:
    logFormat: json
  repoServer:
    logFormat: json
```

**Expected behavior**

The logoutput is printed as json format.

**Version**

```
$ argocd version
argocd: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

repo-server
```
time="2021-05-13T06:29:36Z" level=info msg=Trace args="[helm template . --name-template foo-bar --namespace foo-bar --values /tmp/values-836517096.yaml --api-versions v1 ...]" dir=/tmp/git@123.45.6.789_foo_bar-helm-charts/aws-load-balancer operation_name="exec helm" time_ms=1609.515198
time="2021-05-13T06:29:35Z" level=info msg=Trace args="[helm dependency build]" dir=/tmp/git@123.45.6.789_foo_bar-helm-charts/foo-bar operation_name="exec helm" time_ms=780.675204
time="2021-05-13T09:16:23Z" level=info msg=Trace args="[git fetch origin --tags --force]" dir=/tmp/git@123.45.6.789_foo_bar-helm-charts operation_name="exec git" time_ms=211.71025
```

**Comment by jannfis** [comment]
Traced this down to https://github.com/argoproj/argo-cd/blob/5c41377ca661313e4d68fd47717c17b2bd5d86bb/util/exec/exec.go#L38, which uses https://github.com/argoproj/gitops-engine/blob/master/pkg/utils/tracing/logging.go with a new, unconfigured instance of `logrus`, thus ignoring all logger options.

**Comment by yu-croco** [comment]
Thank you for telling me the root cause! 

May I try to fix this issue like below? :eyes:
*If there are easier ways, please let me know. :pray:

---

### 1. add function on logrus to get current formtter config
As far as I investigated, we have no way to get current formatter config on logrus.
So I will make PR to get current formatter name (or something).

```go
// return formatter name. "JSONFormatter" or "TextFormatter"
func GetFormatterName() string {
 // ...
}
```

### 2. fix how to init logrus on `RunWithRedactor`

```go
// init logrus by using current logrus config, so the log format will inherit original one.
// maybe this function will be at util/log/logrus.go
func NewWithCurrentConfig() *logrus.Logger {
	l := logrus.New()
	l.SetFormatter(logrus.GetFormatterName())
	l.SetLevel(logrus.GetLevel())
	return l
}

// argo-cd/util/exec/exec.go
func RunWithRedactor(cmd *exec.Cmd, redactor func(text string) string) (string, error) {
	opts := argoexec.CmdOpts{Timeout: timeout}
	span := tracing.NewLoggingTracer(log.NewLogrusLogger(log.NewWithCurrentConfig())).StartSpan(fmt.Sprintf("exec %v", cmd.Args[0]))
	...
}
```

**Comment by jannfis** [comment]
Thanks for your offer to try to fix this, @yu-croco !

As for your ideas, I think it will be hard to get something new into `github.com/sirupsen/logrus`, because as far as I understood the project, they are in maintenance mode. 

However, I think we could provide our own method to get the settings of the currently used logger (there are more settings to consider, for example the log level).

**Comment by yu-croco** [comment]
> As for your ideas, I think it will be hard to get something new into github.com/sirupsen/logrus, because as far as I understood the project, they are in maintenance mode.

Oh... :innocent:

> I think we could provide our own method to get the settings of the currently used logger (there are more settings to consider, for example the log level).

I see!
Is it kinda like below ?

1. create some new methods (and maybe struct as well?) on argo-cd repository
2. in order to set current logger config to our own state(we create at `1.` ), call the methods at same place as `cli.SetLogFormat()` and `cli.SetLogLevel()`
3. use the methods to get current used log config.

**Comment by yu-croco** [comment]
This is fixed on this PR https://github.com/argoproj/argo-cd/pull/6301 , so I close this issue. 🙋
