### ISSUE TITLE
Argo CD support RBAC for Users that dont belong to any group ?

### ISSUE THREAD

**Issue by iam-veeramalla** [argoproj/argo-cd#6250]
# Summary
Argo CD RBAC currently does not support or provide any  privileges to users that dont belong to any group. 

Background:
I am trying to set up Keycloak as an Identity broker for argo cd instance where openshift-v4 is configured as Identity provider in Keycloak. As of today, keycloak does not fetch group details from openshift/ openshift does not send group claims to keycloak. Due to this, openshift cannot be used as Identity provider, However there are few work arounds to get this done.

What change you think needs making.
Should Argo CD support RBAC for Users who do not belong to any groups on the client ?

# Motivation
https://argoproj.github.io/argo-cd/operator-manual/user-management/keycloak/
https://www.keycloak.org/docs/latest/server_admin/#openshift-4

**Comment by jannfis** [comment]
Hey @iam-veeramalla, there is a `policy.default` option in the RBAC configuration (refer to https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/#tying-it-all-together) which allows you to specify a role that gets applied to all users, regardless of their group memberships or other roles. 

By default, this is set to `role:readonly`, which gives every logged in user read access to everything.

**Comment by iam-veeramalla** [comment]
Hi @jannfis , Thanks for the response.

I was looking at option for user level access. Something like read-only for user A and admin for user B. I understand, this can be achieved by adding them to groups but as I mentioned in the background, keycloak unfortunately cannot fetch groups from OpenShift users :)

**Comment by jannfis** [comment]
Ah ok, sorry, I misunderstood.

Then you may override the scopes used for RBAC in the `argocd-rbac-cm`, the following would allow policies on the email of the logged in user:

```
scopes: '[groups,email]'
policy.csv: |
  g, foo@example.com, role:admin
```

You can inspect the values in the JWT returned by Keycloak for further scopes you might be interested in.

**Comment by iam-veeramalla** [comment]
Thanks Jann :) This works for me :)
