### ISSUE TITLE
Remove/Disable default project

### ISSUE THREAD

**Issue by hairmare** [argoproj/argo-cd#6251]
# Summary

I would like to remove or disable the `default` project that gets created on startup since #535

# Motivation

Our best-practice involves never using the default project to ensure that our users are "forced" to follow the least access principal. Our setup is purely declarative ad not having the default project available would make it clearer that it is not to be used.

# Proposal

Creating the `default` project should be optional or there should be a way to disable it. Something similar to how we can disable the default admin user with `admin.enabled=true` would help us ensure that no one can use the default project.

# Workarounds

I can configure the `default` project so it doesn't allow anything as well as taking care of not assigning it to any roles so this is really more of a cosmetic change that helps guide the inevitable `role:admin` person in the right direction.

**Comment by jannfis** [comment]
Keep in mind that when you manage your resources in a declarative way, it wouldn't matter if the `default` project exists or not. You can specify invalid (non-existing) projects in `.spec.project` of the `Application` resource and the Kubernetes API would not complain. Argo CD would just mark this Application as _Unknown_ with an error that the referenced project does not exist. 

Likewise, if you lock-down the `default` project to not allow any resource to be synced (e.g. everything is on the deny list), the Application would be in a similar state, just with another error message (e.g. that the destination namespace and/or cluster is forbidden by the project).

So it's a very similar behavior between a _nonexisting_ project and a _locked down_ project. Therefore, I fail to see much value in removing the `default` project here.

**Comment by diranged** [comment]
I'd like to re-open this issue... I believe at the very least this should be configurable. This problem makes IAC tools have problems managing these resources declaratively (see https://github.com/aws/aws-cdk/issues/31697).

**Comment by crenshaw-dev** [comment]
@diranged the discussion has continued here: https://github.com/argoproj/argo-cd/issues/11058
