### ISSUE TITLE
Visual representation of all Applications' Health

### ISSUE THREAD

**Issue by rbreeze** [argoproj/argo-cd#6275]
# Summary

On the Applications List, it would be useful to have a small visual representation of the proportion of Apps that are Healthy, Progressing, etc. 

# Proposal

Something like this, at the top of the Apps List: 

<img width="1009" alt="Screen Shot 2021-05-19 at 1 35 40 PM" src="https://user-images.githubusercontent.com/6250584/118881019-6f392f80-b8a7-11eb-8b80-f7f1243e5ff5.png">

Could also have something similar for Sync Status.

**Comment by reginapizza** [comment]
I would love to pull this issue into our next sprint to work on :) just wanted to see if UX folks have any feedback/suggestions on it beforehand? @bgliwa01 @serenamarie125

**Comment by serenamarie125** [comment]
@reginapizza any way we could get a screenshot of what the entire page looks like for some context?
This looks to be an 100% stacked bar chart.  If using this, i'd suggest using a tooltip similar to what we do in pipelines, showing numbers of all status along with a block of color for each.  In the case you have 100 apps, and only 1 app has one of the statuses, that portion of the bar could be very small and hard to hover over.

Once I see the screenshot of the entire page, i'll likely have more thoughts.

**Comment by reginapizza** [comment]
hey @rbreeze! I started to work on this and I have a few questions that I was hoping you can provide some input on it. First of all, should Suspended health status be included in this status bar? It's a health status but I don't see it listed as part of healthColors in applications-summary.tsx (it's not even listed in this file at all): 
```
const healthColors = new Map<models.HealthStatusCode, string>();
healthColors.set('Healthy', COLORS.health.healthy);
healthColors.set('Progressing', COLORS.health.progressing);
healthColors.set('Degraded', COLORS.health.degraded);
healthColors.set('Missing', COLORS.health.missing);
healthColors.set('Unknown', COLORS.health.unknown);
```

The colors for Missing and Unknown, as well as Suspended, are also all the same grey color, which would make for a very confusing status bar. The grey color also just makes it seem like empty space and that the percentages don't equal 100%.

https://user-images.githubusercontent.com/50851526/124638302-ccd60b00-de58-11eb-9e5c-c10fc567e692.mp4

Should we choose other colors to represent these health statuses?

**Comment by rbreeze** [comment]
I think `Suspended` should be included in the bar - maybe the same yellow as `OutOfSync`. Then we could group `Unknown`, and `Missing` into one group for the bar and leave the grey color, or black.

**Comment by ciiay** [comment]
I am adding color for `health.suspended` and assigning `OutOfSync` yellow color to `Missing` health status as part of #5200 . I just want to confirm if it's okay to go ahead and ungroup `Unknown` and 'Missing` in the health status bar.

**Comment by rbreeze** [comment]
Sounds good to me
