### ISSUE TITLE
Out of bounds in log view -- Page 2 (Lines 101 to 100)

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#6278]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

It's possible for the logs view to show an invalid range in the title (it's unclear what it's doing under the hood):

`Page 2 (Lines 101 to 100)`

**To Reproduce**

1. Go to an app with a running cron job
2. open logs
3. navigate back
4. try to navigate forward (something bad happens)
5. kill the job (it was manually started)
6. fix something (in kubernetes)
7. start the job again
8. click the replacement pod trying to get back to logs

(fwiw, I "fixed" this by removing `&untilTimes=...` from my URL)

**Expected behavior**

Take me to the live logs for the current pod.

Certainly, don't leave me at a broken view where the next/previous buttons don't work.

**Screenshots**

**Version**

```shell
{
    "Version": "v2.0.0+d085636",
    "BuildDate": "2021-03-30T19:10:08Z",
    "GitCommit": "d085636fd72c170d0553a2db1f0de8e6ea0df398",
    "GitTreeState": "clean",
    "GoVersion": "go1.16",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.9.4 2021-02-09T19:22:10Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.4",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexec** [comment]
maybe fixed, re-open if still issue
