### ISSUE TITLE
[CLI] Support --dry-run=client flag for generating Apps

### ISSUE THREAD

**Issue by shibumi** [argoproj/argo-cd#6285]
# Summary

What I am missing right now is a nice way to create applications and projects via command line for GitOps.
It would be cool if argo would has a dry-run flag for generating apps.

The behavior could be similar to kubectl's --dry-run=client functionality. For example:

argocd app create infrastructure --repo https://github.com/foobar/stage-cluster --path deployments/infrastructure --dest-server https://kubernetes.default.svc --directory-recurse --project infrastructure --dry-run=client > app.yaml

This little addition would enhance our workflow with the app-of-apps-pattern.

# Motivation

For the app-of-apps pattern it's recommended to have a repository with all apps. Generating these apps via the Web UI is not the gitops way and generating via argocd cli is toilsome (additionally not all options are supported by the cli).

We could fix this issue with providing a --dry-run=client flag that just prints the generated YAML.

# Proposal

The --dry-run=client flag would just print the generated YAML. I am not sure how this is implemented right now. I expect that, right now, argocd is just generating JSON and sends this to the argocd operator. The new --dry-run=client flag would send nothing to the server. Instead the cli would parse the JSON, transform it to YAML and prints it to stdout.

**Comment by kshamajain99** [comment]
@shibumi You can use existing argocd  cli option to generate declarative config for your application.

```
argocd-util app generate-spec APPNAME [flags]
````
For more details check out the [docs](https://argoproj.github.io/argo-cd/operator-manual/server-commands/argocd-util_app_generate-spec/)

**Comment by shibumi** [comment]
@kshamajain99  Thanks a lot! this works. Closed the issue
