### ISSUE TITLE
Argocd install failure

### ISSUE THREAD

**Issue by dwding18** [argoproj/argo-cd#63]
With the latest release v0.2.0, following the cmd to run `argocd install` and got resources created in argocd ns.
However the pods are not coming up:
```
kc get pod -n argocd
NAME                                     READY     STATUS             RESTARTS   AGE
application-controller-f85b84c9f-ddkqj   0/1       CrashLoopBackOff   6          7m
argocd-repo-server-85b697d4f7-dcggf      0/1       ImagePullBackOff   0          7m
argocd-server-5bb977f748-vhqb5           0/1       CrashLoopBackOff   6          7m
```
any hint?

**Comment by alexmt** [comment]
Helllo @dwding18 ,  you've caught us in a middle of the release. Attached argocd cli binary had wrong default image tag. I've reattached correct binaries. If you re-run `argocd install` then issue should be resolved.

**Comment by oluranticode** [comment]
i have the same issue please can you help me?

**Comment by crenshaw-dev** [comment]
@oluranticode would you mind opening a new issue and filling out the template with details?
