### ISSUE TITLE
Endpoints diff confused by ports sorting

### ISSUE THREAD

**Issue by zebraincognito** [argoproj/argo-cd#6300]
**Describe the bug**

Hello, I believe the bug is similar to this one https://github.com/argoproj/argo-cd/issues/1816#issue-460419608
but happens with endpoints with multiple ports defined.
Endpoints that have multiple ports definitions in yamls are always OutOfSync due to difference between desired manifest and applied one with reordered ports entries:
![argocd-diff](https://user-images.githubusercontent.com/19332054/119207948-da058900-baa8-11eb-8173-8dca38f5c436.PNG)

**To Reproduce**

Sync Endpoints manifest with multiple defined ports.

**Expected behavior**

If reordering happens it shouldn't be considered as manifests difference.
Endpoints should be in sync.

**Version**

Argo CD
v2.0.0+f5119c0

**Comment by jessesuen** [comment]
We currently special case Endpoint diffing by sorting upper-level array but not currently ports. Should sort ports as well.

**Comment by wtam2018** [comment]
Please assign to me.

**Comment by alexmt** [comment]
Discovered that issue is fixed by https://github.com/argoproj/gitops-engine/pull/258 . Fix will be available in 2.1

**Comment by zebraincognito** [comment]
The issue still persists in 2.1, could you take a look?

**Comment by doyelese** [comment]
Encountering this issue also with subset addresses:

![Screen Shot 2021-09-02 at 1 21 54 PM](https://user-images.githubusercontent.com/65038083/131903967-4be9cb48-fa84-427c-beca-24a97d21a0d6.png)

**Comment by alexmt** [comment]
PR argoproj/gitops-engine#347 fixed ports issue but addresses issue is still there. Working on second PR to fix it as well

**Comment by alexmt** [comment]
Created separate ticket for endpoint addresses https://github.com/argoproj/argo-cd/issues/8287

**Comment by MPV** [comment]
@alexmt Looks lik #8288 only bumped the gitops engine to `0.5.x` but https://github.com/argoproj/gitops-engine/pull/347 isn't included until `0.6.x`. Time to bump it again?
