### ISSUE TITLE
Getting error on application create 

### ISSUE THREAD

**Issue by jitendrs** [argoproj/argo-cd#6302]
Hi All,

* [-] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [-] I've included steps to reproduce the bug.
* [-] I've pasted the output of `argocd version`.

**argocd version**: v2.0.0
**argocd cli version**: v2.0.2+9a7b0bc.dirty
Kubernetes version: 1.19 (EKS)
Repo:- Private connected via user details.

I able to install argocd server successfully however when I am trying to login via UI I am getting below errors

argocd server is behind the ambassador controller and its running in insecure mode. with root-path based routing.

Error:-
```
time="2021-05-23T06:31:22Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2021-05-23T06:31:22Z" grpc.time_ms=2.038 span.kind=server system=grpc
time="2021-05-23T06:31:22Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = invalid session: token signature is invalid" grpc.code=Unauthenticated grpc.method=List grpc.service=cluster.ClusterService grpc.start_time="2021-05-23T06:31:22Z" grpc.time_ms=1.138 span.kind=server system=grpc
time="2021-05-23T06:31:22Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.claims=null grpc.request.content= grpc.service=session.SessionService grpc.start_time="2021-05-23T06:31:22Z" span.kind=server system=grpc
time="2021-05-23T06:31:22Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2021-05-23T06:31:22Z" grpc.time_ms=1.658 span.kind=server system=grpc
time="2021-05-23T06:31:23Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = invalid session: token signature is invalid" grpc.code=Unauthenticated grpc.method=List grpc.service=application.ApplicationService grpc.start_time="2021-05-23T06:31:23Z" grpc.time_ms=0.846 span.kind=server system=grpc
```
Steps to reproduce:
1.  Create argocd behind ambassador controller with DNS.
2.  update the default login password
3.  try to login via UI

mapper yaml

```
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: argocd-server
  namespace: infra-argo
spec:
  prefix: /argocd
  rewrite: /argocd
  service: argocd-server:443
```

**Comment by alexmt** [comment]
I suspect this is because Argo CD creates token for `/` path. Instead of using `rewrite` you need to add `--rootpath` flag to `argocd-server` deployment: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#argocd-server-and-ui-root-path-v153

**Comment by jitendrs** [comment]
@alexmt Thanks for responding. There was  issue with certificate.
