### ISSUE TITLE
Sync is green when plugin generate script fails

### ISSUE THREAD

**Issue by Velyks** [argoproj/argo-cd#6316]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using a custom plugin to generate application yaml the sync step goes green even when the plugin script exits with non-zero (1 in my case) and no yaml is generated.

**To Reproduce**

Create a plugin script that just exits with 1

**Expected behavior**

The sync should fail with the error printed from the plugin script

**Screenshots**

**Version**

```shell
argocd: v2.0.0-rc2+9603ae3
  BuildDate: 2021-03-29T21:31:44Z
  GitCommit: 9603ae37765dadd6e6db519896b8065ca277a775
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Comment by kshamajain99** [comment]
@Velyks We are not able to reproduce this error. What argocd command are you running? Also, would be able to share some logs?
