### ISSUE TITLE
Compare option to ignore extraneous resources only in other namespaces

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#6324]
# Summary

We currently provide the annotation `argocd.argoproj.io/compare-options` to control some parts of the diffing behavior. If set to `IgnoreExtraneous`, Argo CD will ignore resources that have the application's instance label set from overall sync status. 

This option should be extended to only ignore such resources that do _not_ exist in the application's target namespace, but do exist somewhere else in the cluster.

# Motivation

There are a couple of Kubernetes Operators out there that will watch for certain resources (such as a secret), and copies those resources to different namespaces within the cluster, including all labels and annotations. If the original resource is managed by Argo CD (and thus has an application instance label set), the clone of the resource will be detected as part of the application by Argo CD. However, the clone is not part of the manifests, and Argo CD will mark the cloned resource as _pruning required_ and eventually prune the resource - just to have the Operator re-create the clone from the original resource. This may lead to an endless loop, if auto-sync with auto-prune is enabled.

A workaround is to set `argocd.argoproj.io/compare-options: IgnoreExtraneous` and possibly `argocd.argoproj.io/sync-options: Prune=false` on the original resource. However, this leads to the original resource not being updated when the manifest changes and not being pruned when it is deleted from the source manifests, so the original resource eventually becomes a stale and unmanaged one.

# Proposal

The `IgnoreExtraneous` compare option and `Prune` sync option should be parameterizable to only consider resources that are outside the application's target namespace (i.e. in "foreign" namespaces)

For example:

```
argocd.argoproj.io/compare-options: IgnoreExtraneous=foreign
argocd.argoproj.io/sync-options: Prune=falsewhenforeign
```
or alternatively

```
argocd.argoproj.io/compare-options: IgnoreForeignExtraneous
argocd.argoproj.io/sync-options: PruneForeign=false
```

These annotations would only consider resources that exists outside the application's target namespace.

**Comment by alexmt** [comment]
Closing in favor of https://github.com/argoproj/argo-cd/pull/6425
