### ISSUE TITLE
RBAC conflict application-controller

### ISSUE THREAD

**Issue by MikeK184** [argoproj/argo-cd#6326]
Hi, while inspecting some issues in our Kubernetes Cluster I've noticed that in the install.yaml file there is a Role and a Clusterrole bound to the same Service-Account. Considering the Clusterrole simply gives away all permissions, is the definded Role of any use, considering that RBAC in Kuberentes are purely additive?

> An RBAC Role or ClusterRole contains rules that represent a set of permissions. Permissions are purely additive (there are no "deny" rules). [K8s RBAC](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole)

I've just copy pasted the affected K8s Objects into a file as it's easier to see what I mean. (Had to upload it as .md file as GitHub doesn't allow .yml files to be uploaded...)

[RBAC_Objects_ArgoCD.md](https://github.com/argoproj/argo-cd/files/6546622/RBAC_Objects_ArgoCD.md)

**Comment by jkleinlercher** [comment]
@MikeK184 is talking about the following Role https://github.com/argoproj/argo-cd/blob/5fd7ffdb7a511744eb2617eca28f51153df74075/manifests/install.yaml#L2506-L2543

and the ClusterRole https://github.com/argoproj/argo-cd/blob/5fd7ffdb7a511744eb2617eca28f51153df74075/manifests/install.yaml#L2607-L2625

**Comment by jkleinlercher** [comment]
My suspicion is, that with https://github.com/argoproj/argo-cd/issues/580 argocd introduced the mentioned ClusterRole. However, to support also a "only namespace" installation there is still the mentioned Role in addition to the ClusterRole. That is pretty okay I think. So we can close this issue.
