### ISSUE TITLE
Aggregated pod logs viewer is broken

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#6329]
**Describe the bug**

UI no longer allows viewing Deployment/ReplicaSet logs. Looks like instead of aggregated logs view it is showing single pod logs.

**To Reproduce**

* Navigate to https://cd.apps.argoproj.io/applications/argo-cd?node=apps%2FDeployment%2Fargocd%2Fargocd-server%2F0&tab=logs
* See single pod logs

**Expected behavior**

Log viewer should be able to render logs of multiple pods

**Version**

```shell
v2.0.0+cc98954
```

**Comment by alexmt** [comment]
@rbreeze can you help to fix it please?

**Comment by rbreeze** [comment]
will do!

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/6534
