### ISSUE TITLE
UI: group related resources closer or overlap them?

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#6335]
![image](https://user-images.githubusercontent.com/1142830/119732740-6f987400-be2d-11eb-9483-0e3e30ecaf69.png)

In the above example, there is no visual cue to pod grouping. The argo-server pods could be grouped together more tightly, 

E.g.

![image](https://user-images.githubusercontent.com/1142830/119732983-c140fe80-be2d-11eb-8ea4-c9415389b3d4.png)

Or be overlapped:

![image](https://user-images.githubusercontent.com/1142830/119733197-06fdc700-be2e-11eb-964b-145e6a4ea5d8.png)

**Comment by saumeya** [comment]
@ciiay - I think you have implemented this in this #7632, can this be closed?

**Comment by ciiay** [comment]
Hi @alexec, It seems the compact view (#7349) resolves this issue, could you confirm if we can safely close this one?

**Comment by jsoref** [comment]
I believe this is implemented:

https://cd.apps.argoproj.io/applications/argocd/argo-workflows?resource=kind%3APod%2Ckind%3ADeployment%2Ckind%3AReplicaSet

<img width="1289" alt="image" src="https://github.com/argoproj/argo-cd/assets/2119212/427d6b45-77dd-4acb-a4b4-aad15d6ce633">

Additional bugs can be filed to iterate on it (amongst other things, the URL doesn't encode that you're grouping).
