### ISSUE TITLE
UI: Clusters autocomplete options dropdown do not show after choose one filter option

### ISSUE THREAD

**Issue by HuanxinHu** [argoproj/argo-cd#6350]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**
1. Choose clusters filter, you can see the all options dropdown.
2. Select one option, and then add one more, the dropdown do not show anymore.

**Expected behavior**
Cluster autocomplete dropdown should show all the cluster options.

**Screenshots**
![step-1](https://user-images.githubusercontent.com/7131790/119882734-95805000-bee3-11eb-9727-20674e58769e.jpg)
![step-2](https://user-images.githubusercontent.com/7131790/119882744-97e2aa00-bee3-11eb-9439-5c1a615d7da2.jpg)

**Version**

```shell
v2.0.2+9a7b0bc
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by HuanxinHu** [comment]
unfiltered applications should be passed as props into applications-filter component

**Comment by rbreeze** [comment]
I believe this will be fixed in https://github.com/argoproj/argo-cd/pull/6091
