### ISSUE TITLE
UI: Resize option for pod view

### ISSUE THREAD

**Issue by igaskin** [argoproj/argo-cd#6371]
# Summary
For larger deployments, the "pod" view adds a scroller in order to view all the pods in a given replica set.  To get a better top-level view of the health of pods, it would be nice if the boxes were resizable such that all pods fit in a single box.

![Screen Shot 2021-05-28 at 10 29 45 AM](https://user-images.githubusercontent.com/5673097/120367154-61cb6e80-c2c5-11eb-8353-b21340dc9506.png)

**Comment by jessesuen** [comment]
I personally wouldn’t mind variable-sized boxes that scaled to the pod count of the object. I would even argue it should be the default/only behavior.
