### ISSUE TITLE
UI: recently synced resources filter 

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#6379]
I'd like to just see recently synced resources (last 15m or last 30m). 

This will allow me to see what just happened when I do a sync. 

I'd like to combine this with the out-of-sync resources, so I can see what just changed, and what will shortly change.

**Comment by alexec** [comment]
@rbreeze

**Comment by aceamarco** [comment]
Can I give this issue a shot?

**Comment by alexec** [comment]
please

**Comment by aceamarco** [comment]
Will do :) can I be assigned to it?

**Comment by alexec** [comment]
@alexmt ?
