### ISSUE TITLE
Helm Multiple values.yaml profiles bugs

### ISSUE THREAD

**Issue by xuanyuanaosheng** [argoproj/argo-cd#6387]
**To Reproduce**

I use the https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-mongodb-exporter to monitor mongodb cluster.

![image](https://user-images.githubusercontent.com/4197714/120612445-cb937600-c487-11eb-9fd7-38ad7bd5b194.png)

the results in prometheus:

![image](https://user-images.githubusercontent.com/4197714/120612630-f978ba80-c487-11eb-8fbc-73f0b2af6725.png)

**Expected behavior**

Using multiple helm values.yaml,  there should be multiple sets of resources.  But only the latest configuration takes effect.

**Comment by xuanyuanaosheng** [comment]
All the test is failed, Could you please give some examples?

**Comment by blakepettersson** [comment]
Feel free to re-open if that's not the case.
