### ISSUE TITLE
orphaned resource alerts

### ISSUE THREAD

**Issue by cjyar** [argoproj/argo-cd#6391]
# Summary

Provide a metric that indicates if a given Application has orphaned resources.

# Motivation

The only way to identify orphaned resources is to click into each Application in the ArgoCD UI. In a large installation, this takes a long time. If orphaned resources are later created, there's no way to know other than clicking through all the Applications again. If there were a metric, an alert could be written.

# Proposal

A new metric `argocd_app_orphaned_resources_count{name}` would contain the count of orphaned resources per Application.

**Comment by elvis-cai** [comment]
great to see this issue already opened before I start to raise an issue for getting orphan resource metrics, will keep an eye on this issue.

**Comment by KlavsKlavsen** [comment]
hoping for this one too

**Comment by viveksahu26** [comment]
@alexmt  Any updates on this feature ?

**Comment by jaehanbyun** [comment]
@crenshaw-dev What do you think about this feature? If you think it's a good idea, I'd like to try working on it.
