### ISSUE TITLE
Numeric parameters incorrectly templated with helm template during upgrade/install

### ISSUE THREAD

**Issue by Xanadjin** [argoproj/argo-cd#6397]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using helm templates, and long numeric values, Scientific format (E+n) is applied by ArgoCD.

**To Reproduce**

Use a helm template with a parameter;
![image](https://user-images.githubusercontent.com/3648905/120752463-0e962d80-c50a-11eb-87ca-f00eabff3c98.png)

Initiate a deploy of the application
```
argocd app create --upsert [...] --helm-set global.projectNumber="880444307210"
```
In ArgoCD GUI, under the application, parameters, the parameter appears correct:
![image](https://user-images.githubusercontent.com/3648905/120752954-c297b880-c50a-11eb-90bd-1ebbecf4aca6.png)

However, when you check the live manifest, ArgoCD has applied the parameter's value in Scientific format (E+n)
![image](https://user-images.githubusercontent.com/3648905/120753208-1dc9ab00-c50b-11eb-9d43-ff42292b5f38.png)

**Expected behavior**

ArgoCD should treat parameters as strings, and they should be literal replaced in the template, as heml3 does.

**Screenshots**

Screenshots embedded.

**Version**

```shell
argocd: v1.7.8+ef5010c.dirty
  BuildDate: 2020-10-23T06:59:36Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: dirty
  GoVersion: go1.15.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.8.2+94017f2
  BuildDate: 2021-01-10T05:40:54Z
  GitCommit: 94017f2c8d97588d4aa2213713a71d51005ed62d
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
```

**Logs**

N/A

**Comment by Xanadjin** [comment]
One workaround is to use `argocd.argoproj.io/hook: PreSync annotation`, the PreSync handles the numeric parameter values correctly. However, this will cause ArgoCD to remove and recreate the object on every upstert of the application, since default deletion policy is `BeforeHookCreation`. Would be good if we could add a deletion policy to not delete at all. E.g. `None` or `Keep`.

**Comment by servo1x** [comment]
You should use `--helm-set-string` to coerce the value to be a string.

**Comment by Xanadjin** [comment]
I also found that removing the quotes (") around the member: in my helm chart resolved the issue. However, it works when doing a helm upgrade from command line, so it is still inconsistent behavior.

**Comment by Xanadjin** [comment]
Well, removing the quotes (") only solved the issue in one component, not all. However, `--helm-set-string` seems to do the trick, thank you @servo1x  for the workaround / resolution.

Any opinion if this should still be regarded as a bug for the inconsistent behavior from helm, or should we close this?

**Comment by servo1x** [comment]
This is more of a helm thing and it is working as intended. They provide `--helm-set-string` for the exact case where you want the value to always be a string. From the Helm side I do not think they can assume parameters will be a string because then they would have to handle cases where people want the type to be a boolean or number, etc.

**Comment by Xanadjin** [comment]
Thank you very much for this solution @servo1x, we have now tested it, and it works. Closing this issue.
