### ISSUE TITLE
UI: Cluster filter doesn't do an exact match

### ISSUE THREAD

**Issue by servo1x** [argoproj/argo-cd#6399]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When filtering items on the ArgoCD UI, clusters that contain characters for the desired cluster are shown.

**To Reproduce**

- Add a cluster, with the name: `ex-cluster`
- Add another cluster, with the name: `ex-cluster1`
- On the UI, select `ex-cluster1` in the clusters dropdown
- Results for `ex-cluster` and `ex-cluster1` are shown

**Expected behavior**

Only applications for `ex-cluster1` should be shown, not `ex-cluster`.

**Version**

```shell
argocd-server: v2.0.3+8d2b13d
```

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/6340
