### ISSUE TITLE
CRDs having preserveUnknownFields: False causing argo-cd out of sync

### ISSUE THREAD

**Issue by rovindraacquia** [argoproj/argo-cd#6401]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In kubernetes 1.18 preserveUnknownFields is already set as default to False and if some CRDs specifically mentioning it in their spec then argo-cd is going out of sync because of defaulting and while querying the kubernetes API this field is dropped.

**To Reproduce**

Just install the Kubernetes-External-Secrets from here:-
https://github.com/external-secrets/kubernetes-external-secrets

**Expected behavior**

Argo-cd should be ignoring the default fields and status should be in sync

**Screenshots**

![image](https://user-images.githubusercontent.com/65294161/120824196-d3314880-c575-11eb-82bb-3a5efa1c966c.png)

**Version**

```shell
argocd-server: v2.0.0+f5119c0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
This is a known problem with CRD v1. I'll paste the problem I mention in Argo Rollouts release notes.

> Argo Rollouts v1.0 now vends apiextensions.k8s.io/v1 CustomResourceDefinitions (previously apiextensions.k8s.io/v1beta1). Kubernetes v1 CRDs no longer supports the preservation of unknown fields in objects, and rejects attempts to set spec.preserveUnknownFields: true (the previous default). In order to support a smooth upgrade from Argo Rollouts v0.10 to v1.0, spec.preserveUnknownFields is explicitly set to false in the manifests, despite false being the default, and only option in v1 CRDs. However this causes diffing tools (such as Argo CD) to report the manifest as OutOfSync (since K8s drops the false field).

The workaround for the issue is to have this in the ingoreDifferences of the Application Spec or at the system level:

```yaml
spec:
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
```

**Comment by jessesuen** [comment]
Although Argo CD is correctly reporting the diff, I do think this may be a common enough problem to have a special case handling in the diffing logic in Argo CD.

**Comment by rovindraacquia** [comment]
I have already tried this configuration at application level but still out of sync.

**Comment by subbuv26** [comment]
I am interested, will look into this one.

**Comment by subbuv26** [comment]
I am able to reproduce this issue with both latest stable version (Bump version to 2.0.2) and v2.0.0 with out "ignoreDifferences".

After adding "ignoreDifferences" the issue was still there with v2.0.0, but not in latest stable version.

So, I think the issue is already solved in latest stable.

**Comment by alexmt** [comment]
This is a very common case so it makes sense to add first-class support so that every user don't have to make config changes. We already "auto-ignore" CRD statuses. Please find example here: https://github.com/argoproj/argo-cd/blob/0f6c1ab01ecece8000c3ec3e0fa1eeae114684d4/util/settings/settings.go#L556
