### ISSUE TITLE
Search for Resource in Application Resource List

### ISSUE THREAD

**Issue by rbreeze** [argoproj/argo-cd#6403]
# Summary

A search field at the top of this table, to filter Resources by name, would be useful.

<img width="1412" alt="Screen Shot 2021-06-04 at 10 17 13 AM" src="https://user-images.githubusercontent.com/6250584/120839639-09db7480-c51e-11eb-955e-9c12568d8157.png">

**Comment by pasha-codefresh** [comment]
@alexmt i would take it

**Comment by pasha-codefresh** [comment]
@rbreeze we have merged PR that fix this issue. Could you close it? ( we forgot to add Closes tag inside PR )
