### ISSUE TITLE
sync-waves kind: Application

### ISSUE THREAD

**Issue by suppix** [argoproj/argo-cd#6411]
Hello . 

I'm trying to create dependencies between applications but it looks like sync-waves don't work. 

Can you please explain sync-waves works with kind: Application ? 
Do I need this https://argo-cd.readthedocs.io/en/latest/operator-manual/health/#argocd-app ? 

argocd - 2.0.3

**Comment by suppix** [comment]
As I noticed , ArgoCD doesn't wait until Application fully deployed (become sync and healthy), ArgoCD starts sync other applications just after it synced previous wave. Am I right ?

**Comment by suppix** [comment]
I have such settings:
app-of-apps - sync-wave: -3
app1: sync-wave: -2
app2: sync-wave: -1
app3: sync-wave: 0
app4: sync-wave: 0
app5: sync-wave: 0

But when I push new image tag, I can see 
app1 sync first, then somehow argo waits about 2 minutes, and then all other apps app2-5 start to sync

**Comment by suppix** [comment]
I've tried with your example but modify it a little bit: 
https://github.com/suppix/argocd-6411

<img width="1263" alt="Screen Shot 2021-06-06 at 1 14 46 PM" src="https://user-images.githubusercontent.com/8777567/120920792-4e574380-c6c9-11eb-8ce1-54f1cd26de8c.png">
Why app1 app2 started to sync simultaneously? 

<img width="1257" alt="Screen Shot 2021-06-06 at 1 16 06 PM" src="https://user-images.githubusercontent.com/8777567/120920815-69c24e80-c6c9-11eb-8be2-877c701fd725.png">

**Comment by alexmt** [comment]
Hello @suppix , Please see https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/upgrading/1.7-1.8.md#health-assessement-of-argoprojioapplication-crd-has-been-removed 

Starting 1.8 you need to enable app health assessment
