### ISSUE TITLE
Error when patching Argo CD service to include service type load balancer in Getting Started guide

### ISSUE THREAD

**Issue by pcgeek86** [argoproj/argo-cd#6418]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm following the [Getting Started guide](https://argo-cd.readthedocs.io/en/stable/getting_started/) for ArgoCD. When I run the `kubectl` command to patch the `argocd-service` service on my Kubernetes cluster, I am getting the following error.

```
Error from server (BadRequest): invalid character 's' looking for beginning of object key string
```

**To Reproduce**

```
kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
```

**Expected behavior**

Kubectl applies the patch to the `argocd-server` service on Kubernetes.

**Screenshots**

n/a

**Version**

```shell
argocd: v2.0.3+8d2b13d
  BuildDate: 2021-05-27T17:42:53Z
  GitCommit: 8d2b13d733e1dff7d1ad2c110ed31be4804406e2
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: windows/amd64
```

**Kubectl Version**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**

```
n/a
```

**Comment by alexmt** [comment]
I've tried to copy and run command from both Getting Started instructions as well as from this ticket. In both cases command was executed successfully. @pcgeek86  can you please double check if command got corrupted when you copied it? E.g. quotation marks got replaced?

**Comment by pcgeek86** [comment]
@alexmt Hello Alexander, I actually re-typed the command out myself, to ensure that quotes and curly braces were being interpreted correctly. I'm on Windows 10 Insiders using PowerShell, however the quoting rules are substantially similar as Bash, at least in this case.

I also ran PowerShell with the `-NoProfile` option, just to make sure that no customizations to my shell are interfering. PowerShell is interpreting the single-quoted string perfectly fine, by itself.

It seems that the Kubernetes API server is mangling the payload somehow. Which version of the control plane are you using?

![image](https://user-images.githubusercontent.com/466713/121070599-2a106b00-c78c-11eb-9d45-176dd5806929.png)

**Comment by pcgeek86** [comment]
Okay, I figured it out. I've been using PowerShell for the last 15 years ever since it came out. I can assure you that single-quoted strings are interpreted as literals, but apparently `kubectl` works "differently" when running in PowerShell, instead of Bash.

This command in PowerShell:

```
kubectl patch svc argocd-server -n argocd -p '{\"spec\": {\"type\": \"LoadBalancer\"}}'
```

Produces this output:

```
service/argocd-server patched
```

https://stackoverflow.com/questions/55602559/kubectl-patch-works-on-linux-bash-but-not-in-windows-powershell-ise

**Comment by alexmt** [comment]
Thank you for explaining. I think it would be too much to add powershell specific example to Argo CD documentation. We would have to update a lot of other sample commands. So closing ticket. Please let me know if want to reopen it.
