### ISSUE TITLE
500 status code when searching a repository

### ISSUE THREAD

**Issue by psibi** [argoproj/argo-cd#6424]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When trying to create a new application, I see 500 status code from the argocd server when I start typing something in the "Repository URL"'s textbox. Example snapshot demonstrating the issue:

![argocd-error](https://user-images.githubusercontent.com/737477/121141442-92c51980-c858-11eb-8025-196b61d1eb8b.png)

**To Reproduce**

1. Install ArgoCD as documented here: https://argoproj.github.io/argo-cd/getting_started/#1-install-argo-cd
2. Access the ArgoCD server either by port forwarding or by changing the svc to `LoadBalancer` as documented here: https://argoproj.github.io/argo-cd/getting_started/#3-access-the-argo-cd-api-server
3. Login inside ArgoCD
4. Open your browser's Developer tool.
5. Click on "New App" and then go to the "Source" section of the new interface that just popped out. Inside the "Source" section, you have a textbox for "Repository URL". Start typing something in the text box and you will see 500 status code error in the browser's developer too.

**Expected behavior**

A non 500 status code!

**Screenshots**

Screenshot attached above.

**Version**

```shell
$ argocd version
argocd: v1.7.5+90cc56c
  BuildDate: 2020-09-15T23:02:33Z
  GitCommit: 90cc56c3a99127f6ed6bcb777abf92e357c1eb00
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.3+8d2b13d
  BuildDate: 2021-05-27T17:38:37Z
  GitCommit: 8d2b13d733e1dff7d1ad2c110ed31be4804406e2
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
```

**Logs**

Logs from the argo-cd server when I get the 500 status code:

```
time="2021-06-08T06:46:33Z" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = repository not found" grpc.code=Unknown grpc.method=ListRefs grpc.service=repository.RepositoryService grpc.start_time="2021-06-08T06:46:32Z" grpc.time_ms=293.903 span.kind=server system=grpc
time="2021-06-08T06:46:33Z" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = repository not found" grpc.code=Unknown grpc.method=ListApps grpc.service=repository.RepositoryService grpc.start_time="2021-06-08T06:46:32Z" grpc.time_ms=391.914 span.kind=server system=grpc
time="2021-06-08T06:46:33Z" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = repository not found" grpc.code=Unknown grpc.method=ListApps grpc.service=repository.RepositoryService grpc.start_time="2021-06-08T06:46:33Z" grpc.time_ms=302.989 span.kind=server system=grpc
time="2021-06-08T06:46:33Z" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = repository not found" grpc.code=Unknown grpc.method=ListRefs grpc.service=repository.RepositoryService grpc.start_time="2021-06-08T06:46:33Z" grpc.time_ms=380.383 span.kind=server system=grpc
```

**Comment by pasha-codefresh** [comment]
@alexmt i would take it
