### ISSUE TITLE
Azure Repos do not work as a repository

### ISSUE THREAD

**Issue by essh** [argoproj/argo-cd#643]
Azure Repos (previously Visual Studio Team Services/VSTS) repository URLs do not include a .git suffix and do not work if one is added. As a result of the git repo URL normalization that was added in #162 this means Azure Repos do not currently work with Argo CD.

For reference an Azure Repos URL is currently of the form `https://<account>.visualstudio.com/<project>/_git/<repository>` where `<repository>` does not include .git. This will apparently be changing in the future to `https://dev.azure.com/<account>/<project>/_git/<repository>` based on 
https://aka.ms/new-domain.

**Comment by jessesuen** [comment]
Thanks for reporting this @essh. I think this can be addressed this as part of issue #536, which will make repo management friendlier for config and make normalization no longer necessary.

But since #536 will not be available v0.10, let's see if this can be addressed earlier in a v0.9 patch which special cases visualstudio.com and azure.com to not include the .git suffix.

**Comment by jessesuen** [comment]
@essh I pushed some images to my personal docker hub with a fix. To use the images with the fix, you can run:
````
kubectl -n argocd set image deployment/argocd-server argocd-server=jessesuen/argocd-server:azure-git
kubectl -n argocd set image deployment/application-controller application-controller=jessesuen/argocd-application-controller:azure-git
```

Let me know if this resolves the issue.

**Comment by jessesuen** [comment]
Fixed. Will be available in v0.9.2 and v0.10.X

**Comment by tannerpaige** [comment]
I've been trying to add my `https://dev.azure.com/<account>/<project>/_git/<repository>` multiple times today with no success on v0.9.2. It will connect, but when I try to add an application, I get the following error. I must be doing the correct credentials, they are the same ones I use for the repo on the command line.

`Unable to load data: Failed to fetch git repo: unexpected client error: unexpected requesting "https://dev.azure.com/<account>/<project>/_git/<repository>/git-upload-pack" status code: 400`

I'm trying to follow the Getting Started doc with plain yaml files.

**Comment by JacobHeidelbachDFDS** [comment]
Has anyone actually made this work with v.0.11.0 against Azure DevOps?

I get the exact same error as @tannerpaige.
