### ISSUE TITLE
Allow argo-cd to build on ppc64le

### ISSUE THREAD

**Issue by dberg1** [argoproj/argo-cd#6442]
# Summary

Argo CD runs fine on ppc64le with minor changes.
See https://github.com/argoproj/argo-cd/pull/6441

# Motivation

Want to run Argo CD on ppc64le.

# Proposal

See https://github.com/argoproj/argo-cd/pull/6441

**Comment by jaywcarman** [comment]
Hi @alexmt! @dberg1 and I are part of the team that is enabling `ppc64le` arch in [Red Hat Advanced Cluster Management for Kubernetes](https://www.redhat.com/en/technologies/management/advanced-cluster-management), along with it's various integrations with software like Argo CD. How can we help get the discussion started here?

**Comment by geoffrey-pascal** [comment]
Hi! This would be very useful to have the ppc64le architecture available in ArgoCD. I am building it manually on ppc64le for a while and as @dberg1 said it requires only minor changes. Thanks

**Comment by mayurwaghmode** [comment]
> Hi! This would be very useful to have the ppc64le architecture available in ArgoCD. I am building it manually on ppc64le for a while and as @dberg1 said it requires only minor changes. Thanks

Hi, @geoffrey-pascal! Can you let us know the changes required to make ArgoCD work on ppc64le architecture? 
I tried to build the image from your repository but I am facing the below errors.
"[4/5] STEP 9/10: ARG BUILD_ALL_CLIS=true
[4/5] STEP 10/10: RUN if [ "$BUILD_ALL_CLIS" = "true" ] ; then     make BIN_NAME=argocd-darwin-amd64 GOOS=darwin argocd-all &&     make BIN_NAME=argocd-windows-amd64.exe GOOS=windows argocd-all     ; fi
find /go/src/github.com/argoproj/argo-cd -name debug.test | xargs rm -f
CGO_ENABLED=0 go build -v -ldflags '-X github.com/argoproj/argo-cd/v2/common.version=2.1.3 -X github.com/argoproj/argo-cd/v2/common.buildDate=2021-11-23T10:50:52Z -X github.com/argoproj/argo-cd/v2/common.gitCommit=a709c2c706e6c2a64df9298bcb443c11abfdefdc -X github.com/argoproj/argo-cd/v2/common.gitTreeState=clean -X github.com/argoproj/argo-cd/v2/common.gitTreeState=clean -X github.com/argoproj/argo-cd/v2/common.kubectlVersion=v0.21.0 -extldflags "-static"' -o /go/src/github.com/argoproj/argo-cd/dist/argocd-darwin-amd64 ./cmd
cmd/go: unsupported GOOS/GOARCH pair darwin/ppc64le
make: *** [Makefile:238: argocd-all] Error 2
error building at STEP "RUN if [ "$BUILD_ALL_CLIS" = "true" ] ; then     make BIN_NAME=argocd-darwin-amd64 GOOS=darwin argocd-all &&     make BIN_NAME=argocd-windows-amd64.exe GOOS=windows argocd-all     ; fi": error while running runtime: exit status 2
"

**Comment by geoffrey-pascal** [comment]
@mayurwaghmode you need to turn off the build for other CPU architectures. You can add this argument to your docker build command or in the Makefile: ` --build-arg BUILD_ALL_CLIS="false"`

**Comment by mayurwaghmode** [comment]
Thanks, @geoffrey-pascal! It worked.

**Comment by kabhiibm** [comment]
Hi @dberg1 , since argocd builds are available for ppc64le, do we need this issue ?

**Comment by kabhiibm** [comment]
Hi @dberg1 , @georgember ,
can you please close this issue ?
