### ISSUE TITLE
OCI Helm Repo app re-sync on underlying image change

### ISSUE THREAD

**Issue by rajivml** [argoproj/argo-cd#6445]
**Describe the bug**

HI, 

We are using docker (ACR) based helm repos  i.e. OCI helm repos https://helm.sh/docs/topics/registries/

Problem that we are facing is, if we are updating the underlying docker image without changing the tag, Argo isn't syncing those changes. Is their any way we can direct argo to re-pull the image ?

![image](https://user-images.githubusercontent.com/46923567/121396850-651fc380-c971-11eb-8f5b-4b83f49b6934.png)

**To Reproduce**

Just try updating the updating the docker image with same tag and sync application, argo wouldn't detect any changes.

**Expected behavior**

Argo should sync the changes 

**Version**

2.0.1

I think argo should compare the current digest and latest and then decide whether to re-sync vs not

**Comment by 91pavan** [comment]
+1, facing this issue as well

**Comment by alexmt** [comment]
Hello @rajivml , you can use Argo CD app "hard-refresh" to re-pull updated chart. CLI `argocd app get <app> --hard-refresh` or using 'Refresh' dropdown in UI.

**Comment by rajivml** [comment]
@alexmt aah nice, "Hard Refresh" from UI did the trick, but it took me some time to figure out how to find "hard refresh" button, once has to exactly click on that downward triangle slight miss here and there you will not be able to find that option
