### ISSUE TITLE
Missing errgroup package when installing via dep ensure

### ISSUE THREAD

**Issue by merenbach** [argoproj/argo-cd#647]
`make`, `make server`, etc. error out in local development because of a missing `errgroup` package unless `errgroup` is installed beforehand with something like `go get -u golang.org/x/sync`.

Whereas:

  * `errgroup` appears to be a compile-time dependency required by `packr`; and
  * `dep ensure` I believe should install _all_ compile-time dependencies outside of the base Golang install, some minor tooling, and `dep`;

Therefore, I propose that we include `errgroup` in the `required` package list in `Gopkg.toml`, unless we have another way to ensure that it gets installed.

**Comment by dthomson25** [comment]
As a followup to this specific package, I think we should have someone with a fresh machine try to bring up argo-cd to make sure that we don't the same issue with any other packages.
