### ISSUE TITLE
menu for application loses text when title area buttons collapse

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#6474]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Menu text disappears when window is a bit narrower than some very large size

**To Reproduce**

1. Click three dots by application (in tree view)
2. narrow window until top buttons collapse

**Expected behavior**

if menu wants to hide text, it shouldn't reserve space for text, but in this case, i don't think it should hide text

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/121930555-82a5b200-cd10-11eb-9998-55121b1fa225.png)
![image](https://user-images.githubusercontent.com/2119212/121930589-8a655680-cd10-11eb-877f-c4021658629f.png)

**Version**

```shell
{
    "Version": "v2.0.0+c62012d",
    "BuildDate": "2021-06-12T23:57:27Z",
    "GitCommit": "c62012d526b2cef09aa67401b6c8cfc9fea3d30c",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.4",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.1.2 2021-04-15T20:38:06Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
```

**Comment by ciiay** [comment]
I'd like to work on this.

**Comment by jsoref** [comment]
@ciiay: please be my guest
