### ISSUE TITLE
argo-repo-server deployment in HA manifests is using the default serviceaccount

### ISSUE THREAD

**Issue by fabricev** [argoproj/argo-cd#6500]
# Summary

All statefulsets / deployments in the current (2.0.3) HA manifests have their own service account, except argocd-repo-server which is using the default service account.

# Motivation

Consistency in the solution.

# Proposal

Add a service account, a role and a role binding for the repo-server deployment.

**Comment by olvesh** [comment]
Yeah, this stopped me just now. 

Trying to install ksops, which is added in https://github.com/viaduct-ai/kustomize-sops#ksops-repo-sever-patch
I run this in GKE, and trying to use Workload Identity I did not have a service account to pin the IAM Service Account to.

**Comment by jannfis** [comment]
Hey, the repo server has no ServiceAccount mounted to it for security reasons - it does execute third party binaries and possibly semi-trusted input, with user provided input.

So, we won't provide a ServiceAccount mounted to repo server and appropriate Role/RoleBindings per default.

Users can always opt-in to have a Kustomize overlay for this.
