### ISSUE TITLE
Configure health check for Google ConfigConnector Resources

### ISSUE THREAD

**Issue by romachalm** [argoproj/argo-cd#6501]
# Summary

I use [the operator Config Connector](https://cloud.google.com/config-connector/docs/overview) from Google to provision with argo-cd some infra assets (IAM service account, policies, GCS buckets) together my applications provisioning. 

I have seen that the status of  [iam.cnrm.cloud.google.com/IAMServiceAccount](https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iamserviceaccount) from Google's Config Connector is not correctly handled by argo-cd : errors are shown in events (like the length of the name), but the resource is displayed as `Healthy` in argo-cd 

# Motivation

Config Connector manages the CRD listed in https://cloud.google.com/config-connector/docs/reference/overview

Config Connector is currently advertised by Google to be the future way to provision infra in GCP with declarative YAML manifests managed by k8s control plane. So having them integrated by default will be a good integration for argo-cd. 

# Proposal

Adding healthchecks in `resource_customizations` to correctly handle the status of Config Connector resources.  For the ones I know, the resources statuses are based on `conditions.type=Ready`, completed with `conditions.Reason`, easily manageable by lua script. 

It could be simplified with implementation of #4212, but it can be easily handled CRD per CRD.

**Comment by romachalm** [comment]
I have open a draft PR #6502 to integrate the work I have already integrated in our argo-cd instance (`argocd-cm`) and help the discussion about the feature.

**Comment by DWSR** [comment]
@romachalm Is #6502 ready to be reviewed?

**Comment by romachalm** [comment]
Yes, it is. Sorry, forgot to remove the draft tag. 

By the way, I have also the healthcheck ready for IAMPolicyMember. 
What do I add a PR linked to this issue, or is it better to open one issue per GCP resource ?

**Comment by DWSR** [comment]
I'm not a project maintainer, but I think adding all the PRs to this issue makes the most sense.

**Comment by crenshaw-dev** [comment]
Done in https://github.com/argoproj/argo-cd/pull/9878
