### ISSUE TITLE
App of Apps Incorrect Health status

### ISSUE THREAD

**Issue by rajivml** [argoproj/argo-cd#6507]
HI,

Right now we are relying on the Lua code documented here for monitoring the health of app-of-apps application
https://argoproj.github.io/argo-cd/operator-manual/health/#argocd-app

But this logic doesn't capture some other scenarios where for example if an helm chart path is wrong or the github URL is wrong i.e. basically if there any issue w.r.t application spec, then this logic simply ignores that error and move forward executing apps in other waves.

We have modified this logic a bit and now the InvalidPath error is getting caught .

Do you guys think of any other scenarios which we should tackle such that app-of-apps health check is full proof ?

Do we also have to add DeletionError, InvalidSpecError, SyncError and UnknownError as well , will it result in any false positives by including the same ?

```
    argoproj.io/Application:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "ComparisonError" then
                hs.status = "Degraded"
                if condition.message ~= nil then
                  hs.message = condition.message
                end
                return hs
              end
            end
          end
          if obj.status.health ~= nil then
            if obj.status.health.status ~= nil then
              hs.status = obj.status.health.status
              if obj.status.health.message ~= nil then
                hs.message = obj.status.health.message
              end
              return hs
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for application"
        return hs
```

**Comment by alexmt** [comment]
Hello @rajivml , I've checked current behavior. The app health changes to `Unknown` if controller is unable to get resources, access cluster etc. I think this is correct behavior. Any "Error" condition means controller cannot really tell if app is Healthy or Degraded so `Unknown` is correct status in this case. What do you think?
