### ISSUE TITLE
Integration with Keptn

### ISSUE THREAD

**Issue by jetzlstorfer** [argoproj/argo-cd#6513]
# Summary

Provide an integration with [Keptn](https://keptn.sh).

# Motivation

It would be great to have an integration with ArgoCD for deploying the applications, and have Keptn for orchestrating deployments, test, evaluation etc.

Therefore, it is needed that Keptn provides a Git repo that can be leveraged by ArgoCD.
From the ArgoCD side, it is necessary to have an integration that sends back a cloud-event to Keptn indicating if the deployment did successfully finish or not. With this information, Keptn can then trigger the next task in a sequence.

High-level overview as presented at GitOpsDays 2021
![image](https://user-images.githubusercontent.com/7677092/122790840-fd467280-d2b8-11eb-9f41-04cb689ab0c6.png)

# Proposal

The proposal is described in the [issue in the Keptn Github repo](https://github.com/keptn-sandbox/argocd-service/issues/1)

**Comment by jessesuen** [comment]
> From the ArgoCD side, it is necessary to have an integration that sends back a cloud-event to Keptn indicating if the deployment did successfully finish or not. With this information, Keptn can then trigger the next task in a sequence.

We actually have Argo CD notification controller which was built for this use case. Applications can be annotated to send a custom payload to a web endpoint. You could leverage the [`on-deployed`](https://argocd-notifications.readthedocs.io/en/stable/catalog/) trigger to send a custom template (with a keptn specific payload) to a [webhook template](https://argocd-notifications.readthedocs.io/en/stable/services/webhook/).

**Comment by alexmt** [comment]
Thank you @jessesuen . I was about to add the same suggestion. Most common notification triggers and templates are stored in argocd notifications catalog: https://github.com/argoproj-labs/argocd-notifications/tree/master/catalog/ . I would suggest to create keptn specific templates/triggers and store them in keptn git repository so that Argo CD users could include them into Argo CD installation.

**Comment by TannerGabriel** [comment]
I just tried to rewrite a simple Keptn cloud event to an Argo webhook using `argocd-notifications` but ran into some problems. Let me know if you prefer Slack for these kinds of conversations or if Github is fine.

Here is the JSON body of the cloud event I'm trying to recreate as well as a CURL example:

```
{
            "type": "sh.keptn.event.deployment.finished",
            "contenttype": "application/json",
            "specversion": "0.2",
            "source": "test-event",
            "id": "f2b878d3-03c0-4e8f-bc3f-454bc1b3d79d",
            "time": "2019-06-07T07:02:15.64489Z",
            "shkeptncontext": "08735340-6f9e-4b32-97ff-3b6c292bc111",
            "data": {
              "project": "sockshop",
              "stage": "dev",
              "service": "carts",
              "testStrategy": "performance",
              "deploymentStrategy": "direct",
              "tag": "0.10.1",
              "image": "docker.io/keptnexamples/carts",
              "labels": {
                "testid": "12345",
                "buildId": "build17",
                "runby": "JohnDoe"
              },
              "deploymentURILocal": "http://carts.sockshop-staging.svc.cluster.local",
              "deploymentURIPublic":  "https://carts.sockshop-staging.my-domain.com"
            }
          }
```


```
curl -X POST "$URL/api/controlPlane/v1/event" -H  "accept: application/json" -H  "x-token: $API_TOKEN" -H  "Content-Type: application/json" -d "{            \"type\": \"sh.keptn.event.deployment.finished\",            \"contenttype\": \"application/json\",            \"specversion\": \"0.2\",            \"source\": \"test-event\",            \"id\": \"f2b878d3-03c0-4e8f-bc3f-454bc1b3d79d\",            \"time\": \"2019-06-07T07:02:15.64489Z\",            \"shkeptncontext\": \"08735340-6f9e-4b32-97ff-3b6c292bc509\",            \"data\": {              \"project\": \"sockshop\",              \"stage\": \"dev\",              \"service\": \"carts\",              \"testStrategy\": \"performance\",              \"deploymentStrategy\": \"direct\",              \"tag\": \"0.10.1\",              \"image\": \"docker.io/keptnexamples/carts\",              \"labels\": {                \"testid\": \"12345\",                \"buildId\": \"build17\",                \"runby\": \"JohnDoe\"              },              \"deploymentURILocal\": \"http://carts.sockshop-staging.svc.cluster.local\",              \"deploymentURIPublic\":  \"https://carts.sockshop-staging.my-domain.com\"            }          }"
```

Here is the Argo notification file I came up with:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  defaultTriggers: |
    - on-sync-status-unknown

  defaultTriggers.mattermost: |
    - on-sync-running
    - on-sync-succeeded

  service.webhook.keptn: |
    url: $URL
    headers:
    - name: Authorization
      value: x-token $TOKEN

  template.keptn-deployment-started: |
    webhook:
      keptn:
        method: POST
        path: /api/controlPlane/v1/event
        body: |
          {
            "type": "sh.keptn.event.deployment.finished",
            "contenttype": "application/json",
            "specversion": "0.2",
            "source": "test-event",
            "id": "f2b878d3-03c0-4e8f-bc3f-454bc1b5d80d",
            "time": "2019-06-07T07:02:15.64489Z",
            "shkeptncontext": "08735340-6f9e-4b32-97ff-3b6c292bc111",
            "data": {
              "project": "sockshop",
              "stage": "dev",
              "service": "carts",
              "testStrategy": "performance",
              "deploymentStrategy": "direct",
              "tag": "0.10.1",
              "image": "docker.io/keptnexamples/carts",
              "labels": {
                "testid": "12345",
                "buildId": "build17",
                "runby": "JohnDoe"
              },
              "deploymentURILocal": "http://carts.sockshop-staging.svc.cluster.local",
              "deploymentURIPublic":  "https://carts.sockshop-staging.my-domain.com"
            }
          }
```

After deploying the config map in the `argocd` namespace of my Kubernetes cluster, I tried to change something in my repo, but I could not find the cloud event. Is there any way to debug if the specific web hook was executed and the status of the webhook? When executing the template manually using `argocd-notifications template notify keptn-deployment-started podtatohead` I get the following message:

```
failed to notify 'console:stdout': template 'keptn-deployment-started' is not supported
```

**Comment by mowies** [comment]
Current Keptn maintainer here 👋🏼 
I think this can be closed, since we have a fully new version of Keptn available and the argocd-service mentioned here is deprecated and out of date.
@jetzlstorfer could you close this please? :)

**Comment by jetzlstorfer** [comment]
Closing this as of request from @mowies 

If there are any further questions please reach out to him :)
