### ISSUE TITLE
Add support for refined permissions used by ArgoCD role

### ISSUE THREAD

**Issue by nwang92** [argoproj/argo-cd#6529]
# Summary

Add support for:
* Customized role permissions during `argocd cluster add` phase
* Using a pre-defined `Role` for `argocd-manager-role` - the current behavior always upserts
* Allowlist/denylist of which cluster API resources are scanned/reconciled during `argocd app sync` phase

# Motivation

For bullet 1: I've been evaluating the use of ArgoCD in a Kubernetes cluster with a tighter security posture. So while I have a namespace where I have the ability to deploy resources, I don't have the the wildcard permissions as required by the in-namespace policies given to the `argocd-manager` service account: https://github.com/argoproj/argo-cd/blob/master/util/clusterauth/clusterauth.go#L39-L46

Attempts to run the `argocd cluster add` here result in errors of the following nature:
```bash
$ argocd cluster add k8s-cluster-1 --namespace user-nwang --system-namespace user-nwang
INFO[0000] ServiceAccount "argocd-manager" created in namespace "user-nwang"
FATA[0000] Failed to create Role "user-nwang/argocd-manager-role": roles.rbac.authorization.k8s.io "argocd-manager-role" is forbidden: user "nwang" is attempting to grant RBAC permissions not currently held:
{APIGroups:["*"], Resources:["*"], Verbs:["*"]}
```

I've been able to workaround this by forking the CLI tool and replacing the above code with some more granular permissions (ex: limiting access to just deployments, pods, services, etc.). However, it would be convenient if there was a way to pass in a pre-defined set of policies or to even use an existing role name.

For bullet 2: I realized after adding the cluster to ArgoCD that under the hood, it does rely on those wildcard rules because it's listing all the API resources within the above namespace (`user-nwang` in the above case). Due to my team's security posture, that's also not feasible. While some resources/custom resources are scoped to namespaces, there's no access given to list or create them. 

So what ends up happening is when I try to perform an `argocd app sync`, I get the following:
```bash
$ argocd app sync guestbook --resource V1:Service:guestbook-ui
WARN[0002] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
TIMESTAMP  GROUP        KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE

Name:               guestbook
Project:            default
Server:             https://k8s-cluster-1.domain
Namespace:          user-nwang
URL:                https://argocd.domain/applications/guestbook
Repo:               https://github.com/argoproj/argocd-example-apps.git
Target:
Path:               guestbook
SyncWindow:         Sync Allowed
Sync Policy:        <none>
Sync Status:        Unknown
Health Status:      Healthy

Operation:          Sync
Sync Revision:
Phase:              Error
Start:              2021-06-22 10:14:43 -0700 PDT
Finished:           2021-06-22 10:14:44 -0700 PDT
Duration:           1s
Message:            ComparisonError: failed to sync cluster https://k8s-cluster-1.domain: failed to load initial state of resource RequestAuthentication.security.istio.io: requestauthentications.security.istio.io is forbidden: User "system:serviceaccount:user-nwang:argocd-manager" cannot list resource "requestauthentications" in API group "security.istio.io" in the namespace "user-nwang";ComparisonError: failed to sync cluster https://k8s-cluster-1.domain: failed to load initial state of resource RequestAuthentication.security.istio.io: requestauthentications.security.istio.io is forbidden: User "system:serviceaccount:user-nwang:argocd-manager" cannot list resource "requestauthentications" in API group "security.istio.io" in the namespace "user-nwang"
```

Unfortunately, I am not able to grant access for the `argocd-manager-role` to allow this because it's an RBAC permission that I don't hold either. What would be nice-to-have here is some configuration option to only sync given set of API groups/resources instead of needed everything. I even tried supplying the `--resource V1:Service:guestbook-ui` flag in hopes that it would also limit what gets read but to no avail.

Looks like the [relevant lines of code](https://github.com/argoproj/gitops-engine/blob/579ea1d764b88d3eb8da38bd8ab101127a6d5dad/pkg/cache/cluster.go#L657-L692) that impact the 2nd issue are within the gitops-engine library if I'm not mistaken? This would be a complementary feature ask to accompany the 1st issue. 

# Proposal

* Add support for the use of a predefined `argocd-manager-role` - that would help resolve the first item?
* Configurable option to to sync/cache only authorized API groups/resources

**Comment by jessesuen** [comment]
> Using a pre-defined Role for argocd-manager-role - the current behavior always upserts

The argocd-manager role can be explicitly specified with the `--service-account` flag:

```
argocd cluster add CONTEXT

Usage:
  argocd cluster add CONTEXT [flags]

Flags:
...
      --service-account string             System namespace service account to use for kubernetes resource management. If not set then default "argocd-manager" SA will be created
```

> Customized role permissions during argocd cluster add phase

The permissions which Argo CD needs, can be fine-tuned with resource inclusions and exclusions:
https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#resource-exclusioninclusion

The use case is that if Argo CD needs to run with a limited RBAC role, you would also include/exclude resource kinds which Argo CD cannot monitor.

> Allowlist/denylist of which cluster API resources are scanned/reconciled during argocd app sync phase

Unless I misunderstand your request, I think the project settings are precisely what you are looking for. See:

![image](https://user-images.githubusercontent.com/12677113/123183741-0c5b2b00-d447-11eb-871b-8ae852259ce1.png)

**Comment by jessesuen** [comment]
> Using a pre-defined Role for argocd-manager-role - the current behavior always upserts

The argocd-manager role can be explicitly specified with the `--service-account` flag:

```
argocd cluster add CONTEXT

Usage:
  argocd cluster add CONTEXT [flags]

Flags:
...
      --service-account string             System namespace service account to use for kubernetes resource management. If not set then default "argocd-manager" SA will be created
```

> Customized role permissions during argocd cluster add phase

The permissions which Argo CD needs, can be fine-tuned with resource inclusions and exclusions:
https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#resource-exclusioninclusion

The use case is that if Argo CD needs to run with a limited RBAC role, you would also include/exclude resource kinds which Argo CD cannot monitor.

> Allowlist/denylist of which cluster API resources are scanned/reconciled during argocd app sync phase

Unless I misunderstand your request, I think the project settings are precisely what you are looking for. See:

![image](https://user-images.githubusercontent.com/12677113/123183741-0c5b2b00-d447-11eb-871b-8ae852259ce1.png)

**Comment by nwang92** [comment]
The resource exclusion/inclusion seems to be what I was looking for regarding my second issue! I guess I missed that from the docs.

For the first point, I thought I was using the `--service-account` option but looking back I might be mistaken. I'll go back through and see if this solves this issue (a cursory glance through the code seems to suggest it would work).
