### ISSUE TITLE
argocd-server logs credentials in plain text when adding git repositories

### ISSUE THREAD

**Issue by twz123** [argoproj/argo-cd#653]
When adding git repositories, argo-cd server writes confidential credentials (username, password, SSH key) to its log stream.

I'd rather expect that those credentials are obfuscated during logging. 

Steps to reproduce:

Issue some CLI command like this:

    argocd repo add ssh://git@server/repo.git --sshPrivateKeyPath /path/to/ssh/key

Inspect the argocd-server logs like this:

    kubectl -n argo logs argocd-server-6fb798d5b4-57qp8  | grep -F 'RSA PRIVATE KEY'

The output looks like this:

> time="2018-09-27T09:47:54Z" level=info msg="received unary call /repository.RepositoryService/Create" grpc.method=Create grpc.request.claims="{\"at_hash\":\"RIAPRIwsFlbL1wuCd8wVvA\",\"aud\":\"argo-cd-cli\",\"email\":\"user@provider.com\",\"email_verified\":false,\"exp\":1538124151,\"iat\":1538037751,\"iss\":\"https://argocd/api/dex\",\"name\":\"User Name\",\"sub\":\"CiQ4ODdkZjAyMC0yMTRjLTQ5YzItYTlkZC03MDcxYmU2MzI2YjMSA3k2Yg\"}" grpc.request.content="repo:<repo:\"ssh://git@server/repo.git\" username:\"\" password:\"\" sshPrivateKey:\"-----BEGIN RSA PRIVATE KEY-----\\n THE FULL KEY IS LOGGED \\n-----END RSA PRIVATE KEY-----\\n\" connectionState:<status:\"\" message:\"\" > > " grpc.service=repository.RepositoryService grpc.start_time="2018-09-27T09:47:54Z" span.kind=server system=grpc

**Comment by jessesuen** [comment]
Fixed. Will be available in v0.9.2 and v0.10.X
