### ISSUE TITLE
Argocd is unable to connect with Private GKE | URGENT

### ISSUE THREAD

**Issue by abhinayguptapeoplegrove** [argoproj/argo-cd#6554]
### Discussed in https://github.com/argoproj/argo-cd/discussions/6553

<div type='discussions-op-text'>

<sup>Originally posted by **abhinayguptapeoplegrove** June 24, 2021</sup>
PROBLEM STATEMENT:

-  Unable to add private GKE cluster in Argocd

SUMMARY:
- We have created a public GKE cluster for hosting all ArgoCD components
- We are using this cluster to deploy k8 resources to other multiple private GKE clusters across  different GCP projects

STEPS FOLLOWED:

- 1- We created the private GKE cluster and added our IP in the authorised network
- 2- We install the argoCD Cli on our laptop and we did the argocd login
- 3- We are able to access the ArgoCD UI and apps 
- 4- To add the private GKE cluster via argocd cli, we executed above command and got the error

ERROR:
We are getting below error while adding the private GKE cluster via argocd CLI

```
**➜$ argocd cluster add gke_*******_us-******-c_*******
INFO[0000] ServiceAccount "argocd-manager" already exists in namespace "kube-system" 
INFO[0001] ClusterRole "argocd-manager-role" updated    
INFO[0002] ClusterRoleBinding "argocd-manager-role-binding" updated
FATA[0035] rpc error: code = Unknown desc = Get "https://34.xx.xx.xx/version?timeout=32s": dial tcp 34.xx.xx.xx:443: i/o timeout** 
```

DEBUG INFORMATION:
Cloud - GCP 
Argo version- v2.0.2
GKE version- 1.19.10-gke.1600
Private GKE cluster features enabled:
 > Control plane global access: TRUE
 > Control plane authorized networks: TRUE     ("Added our public CIDR to it")

P.S: This is an urgent Issue. Please help</div>

**Comment by jannfis** [comment]
Not a bug. Discussion opened in parallel: https://github.com/argoproj/argo-cd/discussions/6553
