### ISSUE TITLE
`#f4c030 minus #111` is deprecated and will be an error in future versions

### ISSUE THREAD

**Issue by reginapizza** [argoproj/argo-cd#6559]
[Line #123 of pod-view.scss](https://github.com/argoproj/argo-cd/blob/master/ui/src/app/applications/components/application-pod-view/pod-view.scss#L123) has a function that will be deprecated and will cause an error in future versions, I suggest we modify that line to use Sass color functions instead like the warning suggests.

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
![deprecationwarning](https://user-images.githubusercontent.com/50851526/123326983-e34e9f00-d507-11eb-84f6-b38b553d9e47.png)

**To Reproduce**

Run `make start` and warning will be there

**Expected behavior**

Warning should not be there. 

**Version**

```shell
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:44:27Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
```
@rbreeze let me know if this doesn't seem right, otherwise I can submit a PR for it!

**Comment by jannfis** [comment]
Good catch @reginapizza, I think this should be fixed.
