### ISSUE TITLE
repo-server race condition bug when deploying ArgoCD with an application

### ISSUE THREAD

**Issue by djfinnoy** [argoproj/argo-cd#6564]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When deploying ArgoCD with the  [official Helm chart](https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd), and including an app within the helm chart, there appears to be a race condition issue with deploying that app.

The app defined via the Helm chart fails:
```
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp xx.xxx.xx.xx:8081: connect: connection refused"
```
If I hit the Refresh button in the UI, everything works as expected.
It would appear that ArgoCD attempts to sync the app before the repo-server is ready.
At the moment, I have to manually refresh the application after bootstrapping.

My apologies if this issue should be placed in the Helm chart's repository, but I think the fix belong within the application, not the Helm chart.

**To Reproduce**
Deploy ArgoCD to k8s with your app defined in the `additionalApplications` Helm value.

**Expected behavior**

The application should wait, or automatically retry if the repo-server is inaccessible.

**Version**
ArgoCD: 2.0.3
Helm chart: 3.6.9

**Comments**
Are there any workarounds? Eg. can I configure my app to automatically refresh if it encounters the aforementioned error?

**Comment by jannfis** [comment]
I think the application would refresh automatically at the next app refresh interval (which is 3 minutes by default).

But thinking about it, when the app refresh interval is set to a very high value (which would not be uncommon in large setups), a transient error with the repo server when Argo CD receives an external refresh event (e.g. a web hook from the repository) could result in hard to resolve situations without a manual refresh of the application in question.

**Comment by mkilchhofer** [comment]
`additionalApplications` had multiple caveats and it was removed in chart version 5.x (https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#500). I'd suggest to onboard your app(-of-apps) via the new/separate helm chart: https://github.com/argoproj/argo-helm/tree/main/charts/argocd-apps

**Comment by djfinnoy** [comment]
> `additionalApplications` had multiple caveats and it was removed in chart version 5.x (https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#500). I'd suggest to onboard your app(-of-apps) via the new/separate helm chart: https://github.com/argoproj/argo-helm/tree/main/charts/argocd-apps

Indeed.
