### ISSUE TITLE
Admin token expired after 24h, but it shouldn't

### ISSUE THREAD

**Issue by der-eismann** [argoproj/argo-cd#6567]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We have a chatbot interacting with ArgoCD, so it needs a JWT to communicate. With ArgoCD 1.8 this wasn't a problem, the token never expired. After the ArgoCD 2.0 upgrade we needed to create a new token, but this one is expiring after 24 hours and there is no way to extend it. In the [security docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/security/#authentication) it says:
> For the local admin user, a username/password is exchanged for a JWT using the /api/v1/session endpoint. This token is signed & issued by the Argo CD API server itself, and has no expiration.

This seems to be not true, this is the JWT payload I get when curling the /api/v1/session endpoint with `curl -X POST https://example.com/api/v1/session -d $'{"username":"admin","password":"password"}'`:
```
{
  "exp": 1624713708,
  "jti": "...",
  "iat": 1624627308,
  "iss": "argocd",
  "nbf": 1624627308,
  "sub": "admin:login"
}
```

As you can see it has an `exp` property which shouldn't be the case. Interestingly the web UI and the CLI offer an `--expires-at` option which isn't available via the API. But when I try to either one I get the following error:
CLI
```
$ argocd account generate-token -e 0s                                
FATA[0000] rpc error: code = Unknown desc = account 'admin' does not have apiKey capability
```
UI (https://example.com/settings/accounts/admin)
```
Unable to generate new token: account 'admin' does not have apiKey capability
```

**To Reproduce**

See above

**Expected behavior**

I want to get a non-expiring JWT token for the admin account.

**Version**

```shell
argocd-server: v2.0.4+0842d44
  BuildDate: 2021-06-23T01:27:53Z
  GitCommit: 0842d448107eb1397b251e63ec4d4bc1b4efdd6e
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Comment by alexmt** [comment]
Hello @der-eismann ,

You increase expiration duration by changing `users.session.duration` ([example](https://github.com/argoproj/argo-cd/blob/0e9aa8e6b61e3135422042b16b6f0a5b8cc74ab1/docs/operator-manual/argocd-cm.yaml#L19)) but this is not recommended. 

I would recommend creating a system account and generate a token:

* Add `accounts.my-account: apiKey` to `argocd-cm` ConfigMap.
* Grant permissions to the account `policy.cvs` field of in `argocd-rbac-cm` e.g.
```
policy.csv: |
    # Grant admin permissions to new account
    g, my-account, role:admin
```
* Generate token : `argocd account generate-token --account my-account`

**Comment by jannfis** [comment]
I think we forgot to fix some places in the docs.

The unlimited validity of admin token was considered a [security issue](https://github.com/argoproj/argo-cd/security/advisories/GHSA-9h6w-j7w4-jr52), as was the usage of `admin` account for API access.

We need to clarify this in the documentation.

**Comment by der-eismann** [comment]
Hello @alexmt, thanks for your workaround/fix! I just set it up and it works perfectly. :slightly_smiling_face: 

We were running 1.8.3 before, so we didn't encounter the issue earlier, I thought it was because of the major version change. It would probably still be helpful to clarify the session duration constraints in places like the [API docs](https://argo-cd.readthedocs.io/en/stable/developer-guide/api-docs/) or [security docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/security/#authentication).
