### ISSUE TITLE
CI job does not update code coverage results

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#657]
All  jobs on Coveralls https://coveralls.io/repos/224753/builds were triggered manually. Looks like CI is unable to upload results to coveralls. We should fix it.

**Comment by merenbach** [comment]
I'm wondering if the `COVERALLS_TOKEN` env var is somehow not getting passed through to the process running the coverage test. Coveralls data won't be submitted if this token is absent. Will take a look after another merge to `master`.

**Comment by merenbach** [comment]
Troubleshooting is currently difficult. Blocked by Argo CI cluster instability at this time. Will be easier to proceed once Argo CI tasks are run in a different namespace with resource quotas attached.

**Comment by alexmt** [comment]
working on it
