### ISSUE TITLE
App creation UI should allow specifying values files outside of helm app directory

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#658]
Value files are not necessary inside helm app directory. It should be possible to specify files outside of directory as well.

API `/api/v1/repositories/{repo}/apps/{path}` should return all value files of repo instead of only files inside helm directory

**Comment by jessesuen** [comment]
Consider the case of github.com/helm/charts. I think showing all value files of that repo is excessive. I think showing only what's in the directory, but also providing a text field allowing the user to point it out of the directory, or a URL would be sufficient.

**Comment by alexmt** [comment]
Good suggestion @jessesuen .

It seems like people are expecting that values path should be relative to git repo root path, not to the chart path. In addition to text box should we make path relative to git repo root path? (in controller and api )

**Comment by marcellodesales** [comment]
@alexmt @jessesuen I had the same issue this week... Could we have filters to define the pattern for files? Helm files can be in any name, not necessarily prefixed with `values-`...

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd-ui/pull/56 . Dropdown had been replaced with textbox + autocompletion. Now user can specify and values file location.
