### ISSUE TITLE
shift-click to force delete resource without typing name of resource

### ISSUE THREAD

**Issue by process0** [argoproj/argo-cd#6580]
# Summary

Resources that are protected from deletion requiring typing the name of the resource.  Shift clicking the resource can also prevent the deletion of the resource and prevent requiring typing long resource names.

# Motivation

I have resources with long names and typing each one when developing is time consuming

# Proposal

Allow shift click to force delete without typing the resource name

**Comment by reginapizza** [comment]
I mentioned this on #6206, but including it here as well. 

After trying to come up with something for this I'm not sure it can be implemented without a lot of really intrusive changes, if not entirely impossible. I tried to give an event listener to the form as another field with validate and submit and while it could pick that up, it was losing the functionality of validate. I think just the way it's structured with react forms would make it a complicated/impossible change, so maybe better to go with a different quick/bulk delete, as #6206 is proposing. Saying this with a disclaimer though that maybe someone with more experience could think of some better, less complicated way to do it.

**Comment by reginapizza** [comment]
(Copied from  #6206 ) Restating here what was discussed in the Argo CD contributor's meeting on Thursday, we will not go with shift-click to delete but will change the delete confirmation to consist of a checkbox that the user will have to check to confirm that they understand what they are deleting, and then they must click the delete button. The user will no longer have to type in the entire resource name. The name of the resource being deleted will also be changed to be more prominent so hopefully there will be less of a chance of accidental deletion of the wrong resource.

**Comment by jgwest** [comment]
Closing as dupe based on comments
