### ISSUE TITLE
Syncing a missing deployment within an application, fails. 

### ISSUE THREAD

**Issue by collinbowers** [argoproj/argo-cd#6583]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Using argocd cli to sync a missing deployment within an application, argocd prints status of application, rather than actually syncing the deployment specified.

This could be resolved with a more recent version, but I could not find anything in the docs that related to this.

**To Reproduce**

Have deployment within app that is missing, then try to sync that deployment from cli:

```shell
# Resource should be formatted as GROUP:KIND:NAME. If no GROUP is specified then :KIND:NAME
  argocd app sync my-app --resource :Deployment:my-deployment

# This prints out a status of the application, rather than actually syncing the deployment specified.
```

**Expected behavior**

To sync the deployment specified. 

**Version**

```shell
argocd: v1.5.4+36bade7
```

**Comment by jannfis** [comment]
> Resource should be formatted as GROUP:KIND:NAME. If no GROUP is specified then :KIND:NAME
  argocd app sync my-app --resource :Deployment:my-deployment

`Deployment` is not part of the core API group, so it really should be specified as `apps:Deployment:my-deployment` imho. Have you tried that as well?

**Comment by collinbowers** [comment]
> `Deployment` is not part of the core API group, so it really should be specified as `apps:Deployment:my-deployment` imho. Have you tried that as well?

This ended up helping us. Thank you so much!
