### ISSUE TITLE
OIDC Groups claim mapping

### ISSUE THREAD

**Issue by whereismyjetpack** [argoproj/argo-cd#6595]
# Summary

Allow a user to change the claim that contains ones `groups` 

# Motivation

We use AzureAD, and the `groups` claim for some users is too large, and gets omitted in the cookie. See: https://github.com/argoproj/argo-cd/issues/2165 

# Proposal

Something like this in oidc.config

```
...
oidc.config
  groupsClaim: "roles"
```

This would be akin to --oidc-groups-claim in kubectl oidc config.

**Comment by alexmt** [comment]
Hello @whereismyjetpack ,

I think this is already supported. You can specify which claim has groups using `scopes` setting of `argocd-rbac-cm` ConfigMap: https://github.com/argoproj/argo-cd/blob/1d0b5fc7ecabfd511829f81df0b0e9cc0ca29a7f/docs/operator-manual/argocd-rbac-cm.yaml#L29

Additionally, you can control which scopes and claims should be requested by Argo CD using oidc config: https://github.com/argoproj/argo-cd/blob/1d0b5fc7ecabfd511829f81df0b0e9cc0ca29a7f/docs/operator-manual/argocd-cm.yaml#L63

**Comment by whereismyjetpack** [comment]
@alexmt  -- thank you so much, I overlooked the '`scopes:'` parameter in the rbac config, i was able to se that to use `roles` instead of `groups` and like magic it started working..

Thank you so much!

**Comment by sebastianbuechler** [comment]
> @alexmt -- thank you so much, I overlooked the '`scopes:'` parameter in the rbac config, i was able to se that to use `roles` instead of `groups` and like magic it started working..
> 
> Thank you so much!

Hi @whereismyjetpack, we have exactly the same problem. However, we are not able to solve it just with the `scopes` parameter. Do you mind sharing some example config files from you successful solution?

**Comment by whereismyjetpack** [comment]
@sebastianbuechler  -- we solved this by adding the following to `argocd-rbac-cm` 

```---
apiVersion: v1
data:
  scopes: '[roles]'
  policy.csv: |```
... # some policy junk 
```

Then on the AzureAD side creating roles, and mapping those roles to security groups.

**Comment by sebastianbuechler** [comment]
> @sebastianbuechler -- we solved this by adding the following to `argocd-rbac-cm`
> 
> ```
> apiVersion: v1
> data:
>   scopes: '[roles]'
>   policy.csv: |```
> ... # some policy junk 
> ```
> 
> Then on the AzureAD side creating roles, and mapping those roles to security groups.

Thanks for the reply @whereismyjetpack! And how do you map the role of AzureAD to the security groups exactly?

**Comment by whereismyjetpack** [comment]
You create an `App Role` within the app registration 
![Screen Shot 2021-09-15 at 11 53 31 AM](https://user-images.githubusercontent.com/3694886/133467107-1bf26241-4027-4afb-a762-17ab19e080e3.png)

Then in the "Enterprise Aplications side of the app registration, you find "Users and Groups" add a user or group, then bind it to that role 

if a member of that group logs in, in my example they will be emitted a roles clam of 'test'

I don't know how better to describe it, and i'm not sure if our environment is different because of my level of permissions (i'm not an AD admin, just members of apps) and i have to go into the 'App Registrations'  to make the role, then 'Enterprise Applications' to bind said role to humans. 

Hope this helps

**Comment by whereismyjetpack** [comment]
oh, yes sorry -- i omitted that becuase of institutional stuff 

but one of our roles looks like this
```p, role:devteam, applications, get, defalt/devs-*, allow```
