### ISSUE TITLE
Unable to Set Headers to CLI Login with SSO

### ISSUE THREAD

**Issue by dtaniwaki** [argoproj/argo-cd#6614]
* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

My ArgoCD is running behind a basic-auth protected proxy, but the CLI cannot log in with SSO because it doesn't set headers.

**To Reproduce**

Just prepare a basic-auth protected proxy in front of the ArgoCD server, and try to log in with sso.

**Expected behavior**

Login with SSO succeeds.

**Screenshots**

N/A

**Version**

```shell
$ argocd version --port-forward-namespace argocd
argocd: v1.8.7+eb3d1fb.dirty
  BuildDate: 2021-03-07T19:33:57Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: dirty
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.4+0842d44
  BuildDate: 2021-06-23T01:27:53Z
  GitCommit: 0842d448107eb1397b251e63ec4d4bc1b4efdd6e
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Logs**

```
$ argocd --port-forward --port-forward-namespace argocd --header "Authorization: Basic XXXXXXXX" login --sso
FATA[0003] Failed to query provider "https://argocd.example.com/api/dex": 401 Unauthorized:
```

**Comment by jessesuen** [comment]
```
$ argocd --port-forward --port-forward-namespace argocd --header "Authorization: Basic XXXXXXXX" login --sso
```

@dtaniwaki can I understand your use case a bit better? So you are using both `--port-forward` flag as well as `--sso` ? Am I to understand that your use case requires that the Argo CD API server be accessible only when user has `kubectl` access to `argocd` namespace, but at the same time Argo CD is secured via SSO? I don't think we ever anticipated this combination. I also question if there would be any security benefits because if you have access to `argocd` namespace, you already have access to its secrets.

Also, you should be aware that we are considering a new headless model of Argo CD where the API server is completely optional and does not run as a Deployment anywhere. But the UI would still be available **_locally_** through a `argocd admin dashboard` command.

**Comment by jessesuen** [comment]
> My ArgoCD is running behind a basic-auth protected proxy

Also, if it is behind a proxy, then port-forwarding would completely bypass that proxy, no?

**Comment by dtaniwaki** [comment]
@jessesuen Thank you for your comment.

Here's my environment.

![Untitled](https://user-images.githubusercontent.com/1162120/124213306-4e612c80-db2b-11eb-9f03-d2a62783c395.png)

[Roles]
Operators: Release updated Kuberentes manifests via ArgoCD
Developers: Set up ArgoCD and Applications and AppProjects

The operators don't have access directly to Kubernetes so using the local UI is not possible.

The command above is necessary to run `argocd cert add-ssh` and `argocd repo add` for the developers. These operation can be done by the operators, but I'd like the developers to set up everything first. Is it not a common use case of ArgoCD?

I actually fixed the CLI so it sets headers to login w/ SSO and succeeded to pass the basic auth, but failed to get token via dex after the callback redirection.

```
FATA[0044] oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"Invalid client credentials."}
```

**Comment by jessesuen** [comment]
So it sounds like even if we make the client fix in Arog CD, your use case is not resolved until there is a fix in dex?

**Comment by dtaniwaki** [comment]
Yes. I’m still not sure if it’s an issue of dex. Using basic auth for OAuth2 client verification a standard way. I’m thinking to send a PR in the dex repo to identify the client verification method, or maybe, let the basic auth proxy drop the Authorization header. In either way, ArgoCD need to put headers to OIDC requests in SSO login.

**Comment by dtaniwaki** [comment]
@jessesuen I think handling this case in dex is not a great approach. We should remove unnecessary headers on the proxy so dex won't be affected by the proxy's restriction.

**Comment by dtaniwaki** [comment]
Please tell me if we should use a different flag for this headers.
