### ISSUE TITLE
Cluster filter is broken on applications list page

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#6616]
**Describe the bug**

Cluster filter is broken on applications list page

**To Reproduce**

* Try to apply any cluster-level filter:
* See no applications is shown

**Expected behavior**

Applications should be filtered correctly.

**Version**

v2.1.0-unreleased

**Comment by ciiay** [comment]
I would like to work on this issue.

**Comment by rbreeze** [comment]
@ciiay You're welcome to take a look - if you change your mind or want help let me know. Thanks!
