### ISSUE TITLE
Fix the Unstable Docs Version Warning banner to Header 

### ISSUE THREAD

**Issue by iam-veeramalla** [argoproj/argo-cd#6624]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
The Unstable docs version warning banner is not fixed to the header. 

When someone lands on Old/Unstable docs page from google search they see a warning banner and a link to stable docs, which is good.  However this disappears as they scroll down on the docs, there is a good chance that someone would not see it on a very first sight and scroll down.

Also, I would suggest if we can change the warning/recommendation banner to a strong font and colour. 

**To Reproduce**

Google search for the Argo CD Docs would mostly land you on the older version of docs and you should see the issue that I mentioned in the description.

**Screenshots**

<img width="1254" alt="Screenshot 2021-07-03 at 12 17 21 AM" src="https://user-images.githubusercontent.com/43399466/124316998-18a45e00-db94-11eb-833c-a0773e623728.png">

**Version**
NA

```shell
NA
```

**Logs**
NA

```
Paste any relevant application logs here.
```

**Comment by iam-veeramalla** [comment]
@reginapizza, @saumeya I think this should be an easy bug to fix If I am not mistaken :)

**Comment by saumeya** [comment]
I'll take a look.

**Comment by saumeya** [comment]
#6682 
@reginapizza Please could you review.
