### ISSUE TITLE
Unable to Connect Repo Via SSH

### ISSUE THREAD

**Issue by EHSchmitt4395** [argoproj/argo-cd#6628]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**
When adding ssh key for repository i recieve: 
```
Repository 'ssh://git@github....' cannot be initialized, because its root would be system temp at /tmp
```
Via the gui or via adding a private key results in same error. 
**To Reproduce**

```
argocd repo add --name test ssh://git@github.myurl.git --ssh-private-key-path ~/.ssh/id
```
A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

I am deploying Argocd Operator latest version. No changes. On latest openshift 4.7.13  CodeReady Containers version: 1.28.0+08de64bd

**Expected behavior**

The key should be added and it should enable connection to repo.

**Version**

```shell
argocd: v2.0.3+8d2b13d.dirty
  BuildDate: 2021-05-27T19:03:08Z
  GitCommit: 8d2b13d733e1dff7d1ad2c110ed31be4804406e2
  GitTreeState: dirty
  GoVersion: go1.16.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17

```
Repository 'ssh://git@github....' cannot be initialized, because its root would be system temp at /tmp
```

**Comment by jessesuen** [comment]
> ssh://git@github.myurl.git

Is this url representative of what you were adding? Because it is missing the repo so I would not expect this to work

**Comment by EHSchmitt4395** [comment]
negative that is a sanitized url - i removed it for this report

**Comment by jessesuen** [comment]
> negative that is a sanitized url - i removed it for this report

Just to be clear, the URL should have a colon `:` and a slash `/` in it. e.g. `git@github.com:argoproj/argo-rollouts.git` 

Is that true in your case?

**Comment by EHSchmitt4395** [comment]
```
ssh://git@github.xxx.xxxxxxxx.net:XXX/xx_xxxx.git
```
Yessir

**Comment by jessesuen** [comment]
Ok. That is strange. Here is the code that you are hitting:
https://github.com/argoproj/argo-cd/blob/master/util/git/client.go#L126-L133

specifically:

```golang
root := filepath.Join(os.TempDir(), r.ReplaceAllString(NormalizeGitURL(rawRepoURL), "_"))
```

For you to reach this error, root would have to be equal to `/tmp` 

NormalizeGitURL calls https://github.com/argoproj/argo-cd/blob/ba4c65540b178f50078f138e171b2b282842b06d/util/git/git.go#L55-L72

Which only returns empty string if `url.Parse(repo)` returns error. Which is what I think is happening in your case.

Can we test this theory? Visit:

https://play.golang.org/p/vepW2HgWjKg

and replace 
```
gitURL := "git@github.com:argoproj/argo-rollouts.git"
```
with your own. Please let me know if it prints anything

**Comment by EHSchmitt4395** [comment]
I appreciate the haste in help!  i entered my url and it did print and change to : 
```
git@github.xxx.xxxxxxxxxx.xxx/xxx/xx_xxxx
```
it was initially this 
```
git@github.xxx.xxxxxxxx.net:XXX/xx_xxxx.git
```
I inputed this url into the gui with key for adding ssh connectivity to repository and received
```
ssh://git@github.xxx.xxxxxxxxxx.xxx/xxx/xx_xxxx
Unable to connect SSH repository: ssh: handshake failed: knownhosts: key is unknown
```

Which tells me its not a fan of our new format? 
thanks!

**Comment by jannfis** [comment]
Just for completeness, there are subtle differences in how Git repositories are referenced when accessing via SSH:

* The `scp`-Style way: `<user>@<host>:<repo>`, where the colon `:` separates host from path and no port specification is possible.
* The `ssh://`-URL way: `ssh://<user>@<host>[:<port>]/<repo>`, where the `/` separates the host from path and the (optional) colon `:` can be used to denote the port where SSH server is listening at. These work much like HTTP URLs.

As for the latest error message

> Unable to connect SSH repository: ssh: handshake failed: knownhosts: key is unknown

So you either need to [let Argo CD know](https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#unknown-ssh-hosts) about your repository server's SSH host key or connect the repository using insecure method of skipping the verification (not recommended for production use).

**Comment by EHSchmitt4395** [comment]
That errors to be expected - i am still struggling with initial unexpected bug error. The regular format for ssh://user:repo etc fails before it even attempts to authenticate. I can put any fake user and ill still receive initial error 
```
cannot be initialized, because its root would be system temp at /tmp
```
Again repo is in correct proper format 
```
ssh://user@github.xxx.xxxxxxx.net:XXX/xx_xxxx.git
```
Key is being passed as kubernetes secret. but i get the same error when using argocli and referencing key file. Argocd is latest and no changes were made to install

**Comment by EHSchmitt4395** [comment]
just gave it another go -- apologies it was formatting, however instruct make it seem like you require the ssh:// heading, when in reality it wants the ssh format, without it similar to scp , thanks all !
