### ISSUE TITLE
App Creation UI for Helm Apps shows only files prefixed with `values-`  

### ISSUE THREAD

**Issue by marcellodesales** [argoproj/argo-cd#663]
# Problem

The current UI only shows files prefixed with `values-*.yaml` from a given directory where `Chart.yaml` if found.

# Requirement

Helm files can be any with `.yaml` extension... We usually create separate files for specifics such as `ingress.yaml`, `region.yaml`, etc. We'd like to be able to select any of the `yaml` files.

**Comment by alexmt** [comment]
Dropdown had been replaced with textbox + autocompletion. Autocompletion still suggest `values-*.yaml` repository might have to many yaml  files, but user can specify and values file path. 

@marcellodesales please feel to reopen ticket if you think that additional improvement is required
