### ISSUE TITLE
Unable to add Repository Configuration as Secrets ?

### ISSUE THREAD

**Issue by parasappafluke** [argoproj/argo-cd#6637]
Hi,
As documented in _https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/_ i have created _**argocd-repositories.yaml and argocd-repo-creds.yaml**_ files as per the spec provided in the example. I applied this to argocd ns using _**kubectl apply**_ command. In the UI i couldn't see any repositories and credentials template added. Below is my sample credentials template and repo secrets.

Checklist:
**ArgoCD Version: v2.0.4**

**Repository Secret:**
`apiVersion: v1 kind: Secret metadata: name: test-repo-name namespace: argocd labels: argocd.argoproj.io/secret-type: repository stringData: url: https://github.com/testOrg/test-repo-name`

**Repo Credential Template Secret:**

`apiVersion: v1 kind: Secret metadata: name: testOrg-https-creds namespace: argocd annotations: managed-by: argocd.argoproj.io labels: argocd.argoproj.io/secret-type: repo-creds type: Opaque stringData: url: https://github.com/testOrg password: **** username: ****`

**Expected behavior**
Expect all the repository and repository creds template should appear in the argocd UI repository section.

**Comment by sathish-kumar-narayanan** [comment]
yeah, Its not working as expected with v2.0.4. 
I tried to use the UI to configure credential template and, Argocd stores it in [legacy format](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#legacy-behaviour)

**Comment by jannfis** [comment]
Hi @parasappafluke, I'm afraid you are looking at the wrong documentation and this feature has not been released with the 2.0 branch of Argo CD yet (it comes with v2.1).

For documentation on the current stable version, please refer to https://argo-cd.readthedocs.io/en/stable/ instead.

**Comment by parasappafluke** [comment]
@jannfis Thanks for the update and documentation reference.
