### ISSUE TITLE
We should be able to select the order of the `yaml` files while creating a Helm App

### ISSUE THREAD

**Issue by marcellodesales** [argoproj/argo-cd#664]
# Problem

* The order of the yaml files dictates the final values for the objects declared in more than one `yaml` file selected. That is, the final object between 2 `.yaml` files is not idempotent... 

`a.yaml,b.yaml` will result in different objects when using `b.yaml,a.yaml`

The current Values UI imposes an ordering and we can't change it.

# Request

* Could the ui maintain the order of the selection of the files defined by the user?

I'm really impressed by the Power of ArgoCD and the UI makes our team very productive! Thanks a lot!

**Comment by jessesuen** [comment]
As a workaround, the CLI should preserve order.
