### ISSUE TITLE
Token Generated from Argo CD UI via Accounts Section Disappears Almost Immediately

### ISSUE THREAD

**Issue by mt185257** [argoproj/argo-cd#6687]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to generate a token from the Argo CD UI using an admin account that has apiKey permissions. These permissions were provided from a config YAML. When I generate a token from the UI, the token disappears almost immediately after successfully creating it, and attempting to use the generated token to make an API request gives the error: {'error': 'invalid session: account admin does not have token with id 65f42760-0fa2-4c13-a470-6d58d090b853', 'code': 16, 'message': 'invalid session: account admin does not have token with id 65f42760-0fa2-4c13-a470-6d58d090b853'}

**To Reproduce**

I am generating the API token by going to the Settings > Accounts > admin page and then generate new under Tokens. The token I generate from here disappears from the list below showing all generated tokens after approximately 10 seconds regardless of the ID given to the token or the expiry time of the token. The repo is private to my company and only accessible by its members.

**Expected behavior**

To generate an API token that does not disappear shortly after generating

**Screenshots**

The page where I am generating tokens 
<img width="1398" alt="Screen Shot 2021-07-09 at 2 37 27 PM" src="https://user-images.githubusercontent.com/84591959/125140980-c0b0ae80-e0e1-11eb-822a-baab5af710b5.png">
Page showing successful token generation before token disappears before refreshing
<img width="1266" alt="Screen Shot 2021-07-09 at 2 37 19 PM" src="https://user-images.githubusercontent.com/84591959/125140988-c60df900-e0e1-11eb-96b5-a44a11b109ae.png">

**Version**

```
mt185257_ncr_com@cug01-2-vm:~$ argocd version
argocd: v1.8.3+0f9c684
  BuildDate: 2021-01-21T22:19:20Z
  GitCommit: 0f9c68427882bf4633d395cbfcd7c9271795fd9b
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

Error that comes up after trying to make an API request with a generated token:
```
{'error': 'invalid session: account admin does not have token with id 65f42760-0fa2-4c13-a470-6d58d090b853', 'code': 16, 'message': 'invalid session: account admin does not have token with id 65f42760-0fa2-4c13-a470-6d58d090b853'}
```
Config YAML
```
apiVersion: v1
data:
  accounts.admin: apiKey, login
  admin.enabled: "true"
  dex.config: |
    connectors:
    # GitHub OAuth
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $github.clientId
          clientSecret: $github.clientSecret
          orgs:
            - name: ncr-swt-sre
              teams:
                - gsre-admin
                - gsre-dev
                - gsre-contributors
  repositories: |
    - url: https://github.com/ncr-swt-sre/argocd-apps
    - url: https://github.com/ncr-swt-sre/deploy-cloudbot
    - url: https://github.com/ncr-swt-sre/deploy-guestbook
    - url: https://github.com/ncr-tech-content-dev
  repository.credentials: |
    - url: https://github.com/ncr-swt-sre
      passwordSecret:
        name: argocd-secret
        key: github.token
      usernameSecret:
        name: argocd-secret
        key: github.username
    - url: https://github.com/ncr-tech-content-dev
      passwordSecret:
        name: argocd-secret
        key: github.ncr.tech.token
      usernameSecret:
        name: argocd-secret
        key: github.ncr.tech.username
  statusbadge.enabled: "true"
  url: https://gsre-argocd.preprod.ncrsaas.com
  users.anonymous.enabled: "false"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"admin.enabled":"false","dex.config":"connectors:\n# GitHub OAuth\n  - type: github\n    id: github\n    name: GitHub\n    config:\n      clientID: $github.clientId\n      clientSecret: $github.clientSecret\n      orgs:\n        - name: ncr-swt-sre\n          teams:\n            - gsre-admin\n            - gsre-dev\n            - gsre-contributors\n","repositories":"- url: https://github.com/ncr-swt-sre/argocd-apps\n- url: https://github.com/ncr-swt-sre/deploy-cloudbot\n- url: https://github.com/ncr-swt-sre/deploy-guestbook\n- url: https://github.com/ncr-tech-content-dev\n","repository.credentials":"- url: https://github.com/ncr-swt-sre\n  passwordSecret:\n    name: argocd-secret\n    key: github.token\n  usernameSecret:\n    name: argocd-secret\n    key: github.username\n- url: https://github.com/ncr-tech-content-dev\n  passwordSecret:\n    name: argocd-secret\n    key: github.ncr.tech.token\n  usernameSecret:\n    name: argocd-secret\n    key: github.ncr.tech.username\n","statusbadge.enabled":"true","url":"https://gsre-argocd.preprod.ncrsaas.com","users.anonymous.enabled":"false"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd-gsre"}}
  creationTimestamp: "2021-06-14T18:57:05Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:dex.config: {}
        f:repositories: {}
        f:repository.credentials: {}
        f:statusbadge.enabled: {}
        f:url: {}
        f:users.anonymous.enabled: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-06-14T18:58:08Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:accounts.admin: {}
        f:admin.enabled: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-07-09T16:54:50Z"
  name: argocd-cm
  namespace: argocd-gsre
  resourceVersion: "346205563"
  selfLink: /api/v1/namespaces/argocd-gsre/configmaps/argocd-cm
  uid: c0c9bee5-c98b-493f-9c7b-67378cfd9276

```

**Comment by alexmt** [comment]
Thanks for reporting it @mt185257 . Looks like a bug specific for admin account only. The only workaround I see is to create another account . Will try to get fix into 2.1 and will cherry-pick it into 2.0

**Comment by jannfis** [comment]
Please keep in mind that we don't encourage using `admin` for API access at all, and that's why (by default), the `admin` user has no `apiKey` capabilities.

**Comment by mt185257** [comment]
We tried generating tokens from another account we created with apiKey permissions and the tokens are still disappearing. We have also tried restarting the Argo instance as well.

**Comment by jannfis** [comment]
Do you, by any chance, sync your `argocd-secret` from Git maybe?

**Comment by jb185555** [comment]
> Do you, by any chance, sync your `argocd-secret` from Git maybe?

Can you elaborate on what that means?

**Comment by alexmt** [comment]
I incorrectly assumed that argocd always drops admin account tokens but could not reproduce it. Tried with both v2.0 and 1.8. Joining @jannfis question. 

@jb185555 Any chance that `argocd-secret` is managed by Argo CD itself or some other controller?

**Comment by jb185555** [comment]
Yes. We have argocd deployed in GCP on a GKE cluster. We use the Kubernetes external secrets controller. We store all our secrets inside GCP secret manager.

**Comment by alexmt** [comment]
Probably this is the reason. I suspect Kubernetes external secrets controller removes key if it does not expect in it the secret. 

The upcoming 2.1 release (rc-1 is expecting by Monday) has a feature that might help: https://github.com/argoproj/argo-cd/issues/4188 : now secret value can be referenced from any secret labeled with app.kubernetes.io/part-of: argocd label.
