### ISSUE TITLE
Errors deploying YAML manifests with unicode in comments. MSG = ... yaml: invalid trailing UTF-8 octet

### ISSUE THREAD

**Issue by alexei-matveev** [argoproj/argo-cd#6706]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

```
        Deployment   a   YAML   manifest   as   a   resource   listed   in
        kustomization.yaml with a unicode symbol like "ü", "ä", "ß", or in
        fact anything,  used in YAML  comments leads to an  error message,
        hier wrapped and partially censored:

            rpc error: code = Unknown desc = `kustomize build
            /tmp/https:__XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`
            failed exit status 1: Error: map[string]interface
            {}{"apiVersion":"v1", "data":map[string]interface
            {}{"unused":"XXXXXXXXXXXXXXXX"}, "kind":"Secret",
            "metadata":map[string]interface {}{"labels":map[string]interface
            {}{"XXXXXXXXXXX":"XXXXXXXXXXX"}, "name":"fixme",
            "namespace":"XXXXXXXXXXXXXXXXX"}, "type":"Opaque"}: yaml: invalid
            trailing UTF-8 octet

        The important recurrent part is:

            "yaml: invalid trailing UTF-8 octet"

        There are no hits for "octet" in ArgoCD Issues:

            https://github.com/argoproj/argo-cd/issues?q=is%3Aissue+is%3Aopen+octet

        Also nothing relevant in the  search for "trailing".  So there not
        issue for this problem as of  2021-07-13.  A Google search for the
        whole string  leads after  a few  indirections to  the "underlying
        yaml parser":

            https://github.com/go-yaml/yaml/issues/578

        Das Issue was created on 2020-02-25. Closed on 2020-06-02 with the
        CrossRef to Commit:

            https://github.com/go-yaml/yaml/commit/913338de1bd29d0c7b979a5bb8a947a9f6f05c2e

```
**To Reproduce**

Deploy YAML by liting it as a resource in kustomization.yaml:

```
# Die  Datei   wird  weder  von  Kubectl/Kustomize   noch  von  ArgoCD
# berücksichtigt, solange  sie nicht in ./kustomize.yaml  explizit als
# Resource eingetragen ist ...
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: fixme
data:
  unused: "dXRmOA=="
```

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

Secret ist picked from a git repo and gets deployed.

**Version**

 ArgoCD report "v2.0.0+f5119c0" in GUI, here all of it:

```
            {
              "Version": "v2.0.0+f5119c0",
              "BuildDate": "2021-04-07T06:00:33Z",
              "GitCommit": "f5119c06686399134b3f296d44445bcdbc778d42",
              "GitTreeState": "clean",
              "GoVersion": "go1.16",
              "Compiler": "gc",
              "Platform": "linux/amd64",
              "KsonnetVersion": "v0.13.1",
              "KustomizeVersion": "v3.9.4 2021-02-09T19:22:10Z",
              "HelmVersion": "v3.5.1+g32c2223",
              "KubectlVersion": "v0.20.4",
              "JsonnetVersion": "v0.17.0"
            }
```

**Comment by alexmt** [comment]
Looks like error happened in kustomize. I've found several similar bug reports in kustomize github. E.g. https://github.com/kubernetes-sigs/kustomize/issues/3778 

The suggested workaround is to disable kyaml. You should be able to do it by adding `kustomize.buildOptions: --enable_kyaml=false` in `argocd-cm` ConfigMap

**Comment by alexei-matveev** [comment]
Yes the workaround seems to help, I checked with 2.0.4 here: https://github.com/alexei-matveev/hello-argocd#workaround-for-yaml-invalid-trailing-utf-8-octet

Thanks for workaround and the product! Someone will probably still need to update the buggy dependency though. Are there chances for v2.1?

**Comment by alexmt** [comment]
Checked kustomize [issue](https://github.com/kubernetes-sigs/kustomize/issues/3778) it is still open. Unfortunately, there is no much we can do on Argo CD side. Will upgrade kustomize version once new version is available.

**Comment by alexmt** [comment]
Closing issue since there is no actionable items from argocd
