### ISSUE TITLE
Allow specifying root CA to use for external OIDC provider

### ISSUE THREAD

**Issue by clive-jevons** [argoproj/argo-cd#6713]
# Summary

When configuring an external OIDC provider it should be possible to optionally specify a root CA to use to verify the certificates served by that provider in the case that it uses a private PKI.

# Motivation

We have a Keycloak running in our cluster which is to be used for OIDC integration with ArgoCD in order to authenticate and authorise our users. The Keycloak uses certificates signed by our private PKI.

The current implementation behaves as follows:
- default: the self-signed ArgoCD cert is loaded as root CA, but the TLS Config then has InsecureSkipVerify set to true, hence not actually verifying the certificate. Works in principal, but is insecure
- when running ArgoCD in insecure mode (e.g. behind istio), the default TLS Config is used and then the OIDC integration fails because ArgoCD doesn't recognise the certificate from Keycloak

# Proposal

Allow specifying a Root CA PEM in the OIDC config which is then used when communicating with the OIDC provider. I've knocked up a PR here: https://github.com/argoproj/argo-cd/pull/6712

**Comment by jannfis** [comment]
Closed by #6712
