### ISSUE TITLE
SharedResourceWarning when deploying cert-manager

### ISSUE THREAD

**Issue by Hunter-Thompson** [argoproj/argo-cd#6728]
```
CustomResourceDefinition/certificaterequests.cert-manager.io is part of applications example project and cert-manager
```

When deploying cert manager CRD's, this error comes up. This causes Argo notifications to spam our MM channel with these warnings.

**Comment by Hunter-Thompson** [comment]
Turns out, cert manager CRD's have an annotation that is also used by ArgoCD Application, which causes this warning.

Removing the following annotation from the CRD's helped.

```
    app.kubernetes.io/instance: cert-manager
```

**Comment by HariSekhon** [comment]
I've worked around this issue by removing the label from the chart using a json patch, eg:

https://github.com/HariSekhon/Kubernetes-configs/blob/master/cert-manager-kustomization.yaml

**Comment by algo7** [comment]
> I've worked around this issue by dynamically removing the label from the helm chart in Kustomize using a json patch, eg:
> 
> https://github.com/HariSekhon/Kubernetes-configs/blob/master/cert-manager/base/kustomization.yaml

Is there a side effect of doing so? Is the label being used for something else within the context of cert manager?
