### ISSUE TITLE
Adding kustomize app via UI fails in v0.9.2

### ISSUE THREAD

**Issue by twz123** [argoproj/argo-cd#673]
I tried to create the "pause" app located [here][app] via the UI, which fails with a red error bar at the top saying "Unable to load app details: e.helm is undefined".

[app]: https://github.com/twz123/argocd-playground/tree/master/pause
![screenshot_2018-10-04 argo cd](https://user-images.githubusercontent.com/1215104/46457741-b8e6b180-c7b3-11e8-9e36-8073e0d71160.png)

**Comment by alexmt** [comment]
Hello @twz123 . Just tried to add app using your repo and could not reproduce error. It is consistently failing ? Can you open url `https://<argocd-hostname>/api/v1/repositories/https%3A%2F%2Fgithub.com%2Ftwz123%2Fargocd-playground.git/apps/pause%2Fkustomization.yaml?revision=HEAD` and attach output?

**Comment by twz123** [comment]
Sure! Output is

```
{"type":"kustomize","kustomize":{"path":"pause/kustomization.yaml"}}
```

**Comment by alexmt** [comment]
Thank you! I've reproduced the exact same error when tried to run v0.8 UI and v0.9 backend. It could happen if you never reloaded argocd page after upgrade or https://github.com/argoproj/argo-cd/issues/489 came back. 

Can you reload argocd ui and try again ? If it does not help try hard reload Ctrl+Shift+R

**Comment by alexmt** [comment]
Thank you for helping debugging it! 

Index.html (right click -> View Page Source) should import single javascript bundle with version hash . `<script type="text/javascript" src="main.<hash>.js"></script>` The v0.9.2 should have `main.7c35b07195f1495fc66a.js` . Do you have the same?

**Comment by twz123** [comment]
OMG! I have it.

I'm using the kustomize manifests from the git tag, which have broken/incomplete image tags :see_no_evil:

https://github.com/argoproj/argo-cd/blob/v0.9.2/manifests/base/kustomization.yaml#L25

I reckon this has been fixed upstream.

After fixing this manually, everything is working... Bummer. That took some time!

Thanks for your help, much appreciated!

**Comment by alexmt** [comment]
Ah, I did not realize you installed argocd using kustomize. Missing tags were added but not cherry picked into v0.9.2 https://github.com/argoproj/argo-cd/commit/523c7ddf82e90f66cc484746a271027753ec4f77#diff-859fdac5500a20e6d59120d6eed81e2e
