### ISSUE TITLE
UI: Text overlap in source field on list view

### ISSUE THREAD

**Issue by reginapizza** [argoproj/argo-cd#6733]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The text in the source field for apps when viewed in list view is overlapped by the target revision and label of metadata.  

**To Reproduce**
Have apps (with a longer name for a source repo), and have target revision and label metadata present. View it in List view and bug should be visible. 

**Expected behavior**

Probably would expect the source repo to truncate + have a tooltip available so you can still read it

**Screenshots**

![text-overlap-argocd](https://user-images.githubusercontent.com/50851526/125814952-57bc9ac0-e3c3-4ac9-819a-3f5297af72f9.png)

![text-overlap-argocd-closeup](https://user-images.githubusercontent.com/50851526/125815053-01bd93cd-3a6b-4052-9572-a092ead110d2.png)

**Version**

```shell
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:44:27Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
```

**Comment by pasha-codefresh** [comment]
@alexmt i would take it
