### ISSUE TITLE
Exec plugin returning bad version

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-cd#6749]
I'm trying to use exec plugin and I'm getting this error. I tried v1, v1beta1, v1alpha1 to no avail. Any suggestions?

```
Get "https://x.x.x.x/version?timeout=32s": getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1beta1, plugin returned version client.authentication.k8s.io/__internal
```

```
apiVersion: v1
kind: Secret
metadata:
  name: playground-west
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: playground-west
  server: https://x.x.x.x
  config: |
    {
      "execProviderConfig": {
        "command": "gcloud",
        "args": [
          "config",
          "config-helper",
          "--format=json"
        ],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      }
    }
```

```
gcloud version
Google Cloud SDK 347.0.0
alpha 2021.06.25
beta 2021.06.25
bq 2.0.69
core 2021.06.25
gsutil 4.64
```

**Comment by jessesuen** [comment]
This issue seems to indicate the client is the problem:
https://github.com/kubeless/kubeless/issues/1037

**Comment by pjamenaja** [comment]
See my comment here - https://github.com/argoproj/argo-cd/issues/5958#issuecomment-984502516.

**Comment by alexmt** [comment]
Sorry @rwong2888 , Unfortunately I had no time last month and could not help. The native GKE support was merged https://github.com/argoproj/argo-cd/pull/9190 and will be available in v2.4

The simplest possible was to get it in v2.3 is to build golang using this snippet below, make sure binary is available in application controller pod and use instructions from the [PR](https://github.com/argoproj/argo-cd/pull/9190) to configure cluster secret.

```golang
package commands

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"golang.org/x/oauth2/google"
)

var (
	// defaultGCPScopes:
	// - cloud-platform is the base scope to authenticate to GCP.
	// - userinfo.email is used to authenticate to GKE APIs with gserviceaccount
	//   email instead of numeric uniqueID.
	// https://github.com/kubernetes/client-go/blob/be758edd136e61a1bffadf1c0235fceb8aee8e9e/plugin/pkg/client/auth/gcp/gcp.go#L59
	defaultGCPScopes = []string{
		"https://www.googleapis.com/auth/cloud-platform",
		"https://www.googleapis.com/auth/userinfo.email",
	}
)

func newGCPCommand() *cobra.Command {
	var command = &cobra.Command{
		Use: "gcp",
		Run: func(c *cobra.Command, args []string) {
			// Preferred way to retrieve GCP credentials
			// https://github.com/golang/oauth2/blob/9780585627b5122c8cc9c6a378ac9861507e7551/google/doc.go#L54-L68
			cred, err := google.FindDefaultCredentials(context.Background(), defaultGCPScopes...)
			if err != nil {
				panic(err)
			}
			token, err := cred.TokenSource.Token()
			if err != nil {
				panic(err)
			}
			_, _ = fmt.Fprint(os.Stdout, formatJSON(token.AccessToken, token.Expiry))
		},
	}
	return command
}
```

**Comment by rwong2888** [comment]
Thank you @alexmt, I hope you are feeling better now and have more free time.

Your follow-up is much appreciated.

I look forward to 2.4 and will test it out post-release.

I will keep this issue open until then.

**Comment by rekiemfaxaf** [comment]
Hey guys, I'm having the same problem with argocd [v2.4.0-rc2](https://github.com/argoproj/argo-cd/releases/tag/v2.4.0-rc2)
So there is some workaround to avoid the error?
Any help will be very welcome! Thanks!

**Comment by rwong2888** [comment]
@rekiemfaxaf following the doc works. I am on `v2.4.0-rc4`
https://argo-cd.readthedocs.io/en/latest/operator-manual/declarative-setup/#clusters

Thank you @alexmt , closing the issue.
