### ISSUE TITLE
Project filter selector does not get unset upon clear filters

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#6750]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When selecting a project from the left hand filter pane that has no applications associated to it, user is shown the following page:

![image](https://user-images.githubusercontent.com/3942683/126041204-4f94be7e-d2ed-47a1-9702-b534d7d05c06.png)

When user clicks on the "Clear filters" link, the filter actually will be cleared, but this is not reflected in the left hand filter pane:

![image](https://user-images.githubusercontent.com/3942683/126041289-5a9ec97d-9968-4191-9298-f5232fb2c941.png)

**To Reproduce**

* Set project filter to a project that has no apps associated to it
* Click on "clear filters" link on the page saying that no apps matched your filter
* See that project filter still has the empty project set to it

**Expected behavior**

I would have expected that the filter on the left pane would be reset as well

**Screenshots**

See above.

**Version**

Latest build from master

**Comment by jannfis** [comment]
This is actually affecting _all_ the left hand side filters, not only projects.

**Comment by rbreeze** [comment]
@jannfis This seems to be fixed, at least in my browser. Could you verify that this bug is no longer happening?

**Comment by jannfis** [comment]
@rbreeze I use Firefox 90.0, and the issue is still there on the latest build. Let me try using Chrome tomorrow on a different laptop.

**Comment by rbreeze** [comment]
Ah that makes sense, I was using Safari. I'll debug it with Firefox

**Comment by jannfis** [comment]
It's also reproducible with Chrome 91.0.4472.114 (on Linux)

**Comment by rbreeze** [comment]
Thanks for checking @jannfis. It's very odd, I can't reproduce this in Firefox 89, or 90, or Brave (Chromium) 92. Do you have any non-default settings turned on in your browser? (The only settings I could imagine would affect this is ones involving cookies or local storage)

**Comment by ciiay** [comment]
Hi @rbreeze , I am able to reproduce it on Chrome  (on MacOS). If you don't mind I can work on this. Thank you!
