### ISSUE TITLE
Argocd sync transparently skipping applying few resources

### ISSUE THREAD

**Issue by rajivml** [argoproj/argo-cd#6751]
Checklist:

**Describe the bug**

we are seeing this issue many a times where Argo is transparently skipping applying few resources (RoleBindings, configmaps, pvc's etc.) and on manual sync they are getting created. Is this a known issue and is there any fix we could try ?

**Expected behavior**

Argo should sync all resources committed to git

**Screenshots**

![image](https://user-images.githubusercontent.com/46923567/126070285-c3ba6d9c-40a4-433d-8c53-e4c5492a3f7a.png)

**Version**
2.0.1

**Logs**

```
We couldn't find any errors related to this missing resource under logs 
```

**Comment by jessesuen** [comment]
Do you have auto sync enabled with self healing?

**Comment by rajivml** [comment]
We don't have self healing enabled, we didn't enabled it thinking it, if pods are evicted during Memory/Disk pressure then if we have this enabled argo will try to sync the deployments again and the eviction will keep going on 

```
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - PruneLast=true
    - Validate=true
```

**Comment by rajivml** [comment]
btw enabling self healing is just a workaround right and not the root cause for the issue
