### ISSUE TITLE
Dropdown menu doesnt work for allowed resources in projects for SSO users- ArgoCD UI

### ISSUE THREAD

**Issue by jakirpatel** [argoproj/argo-cd#6752]
**Describe the bug**

Bug : ArgoCD UI doesn't dropdown the resources allowed under specific project for users other than admin. 

**To Reproduce**

1. Create a new project 
2. Add repo to new project 
3. Try to deploy through UI - Dropdown menu of repositories doesnt show up allowed repos. 

**Expected behavior**

1. Dropdown menu should load the allowed resources same like admin user. 

**Screenshots**
<img width="1031" alt="Screen Shot 2021-07-19 at 2 08 13" src="https://user-images.githubusercontent.com/31799856/126076139-f9c9ddd3-cae3-49ef-8060-157c3a8aa294.png">
<img width="1057" alt="Screen Shot 2021-07-19 at 2 06 36" src="https://user-images.githubusercontent.com/31799856/126076142-1498c9d2-6362-49c7-9b99-960f05ae6c20.png">

**Version**
```shell
P81668:manager jakir.patel$ argocd version
argocd: v2.0.1+33eaf11.dirty
  BuildDate: 2021-04-17T04:23:35Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: dirty
  GoVersion: go1.16.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.2+9a7b0bc
  BuildDate: 2021-05-20T19:30:25Z
  GitCommit: 9a7b0bc35048835516fc5f5f31a93d4c1bd61242
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
P81668:manager jakir.patel$
```

**Comment by rbreeze** [comment]
This is expected behavior. A couple solutions: Change default policy to readonly
or explicitly introduce role that allows read of list of repos
