### ISSUE TITLE
Create Application throwing error "api/v1/applications" POST 504

### ISSUE THREAD

**Issue by Anishmourya** [argoproj/argo-cd#6753]
I have been using Argocd for the last 6 months, I have deployed 10 services on this and many revisions have also been added too. I recently noticed that It has been very slow responding in Sync and creating the application also throwing 504 error too.

I think the increasing number of revisions becomes slow the ARGOCD. However, I am using the HA solution for Argocd.
 
To Reproduce this error.

- Install ARGOCD v1.8.7+eb3d1fb  on Kubernetes
- Install many applications and revisions on it. Try to create a new application 
-  Inspect the page and see "/api/v1/applications" POST request throws 504 error.
-  Sometimes Filtering the source during the creation of an application is also huge slow.

The expected behaviour should be working as normal seamless responding to all APIS.

![Screenshot 2021-07-19 at 7 45 00 PM](https://user-images.githubusercontent.com/6560320/126174314-3c579bba-e13d-4832-a0e3-2d1218d64d88.png)

**Versions** 
```
**Argocd** 
v1.8.7+eb3d1fb

** Go**
go1.14.12

** Kubernetes**
EKS 1.20.0

** SourceCode**
Bitbucket
```

**Comment by rbreeze** [comment]
Can you post logs for the Argo CD API server and repo server?

**Comment by Anishmourya** [comment]
@rbreeze  Deleting the pod and adding `- '--parallelismlimit'
            - '10'` fixed the issue. going to close this.
