### ISSUE TITLE
Azure AD RBAC for group inconsistent behaviour

### ISSUE THREAD

**Issue by andrei-dascalu** [argoproj/argo-cd#6759]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

I have setup ArgoCD with Azure AD SSO using OIDC using the steps from the documentation, provided a group ID and everything seemed to be ok (eg: users can login as expected). I've setup the following RBAC configuration

```
p, role:org-admin, applications, *, *, allow
p, role:org-admin, projects, *, *, allow
p, role:org-admin, clusters, *, *, allow
p, role:org-admin, repositories, *, *, allow
g, "<uuid of group>", role:org-admin
```

Users coming in from Azure AD seem to be in the ballpark of defined rights, with one exception:  when trying to sync any app, there's the following error:

```
Unable to deploy revision: permission denied: applications, sync, <app namespace>/<app name>, sub: AgBv6URBG0ryzVwx7Es1k3KStKVNFqJ0LW_QMslP1LU, iat: 2021-07-20T06:53:38Z
```

Otherwise, users are able to create apps / projects / repositories / etc

Note: some users have accessed the instance before the RBAC was properly set in place (eg: projects were restricted to "get"). I am not sure if there's any caching for RBAC and/or users coming in from Azure AD - I've restarted Redis pods as well as all Argo-related pods but no change.

**To Reproduce**

1. ArgoCD deployed with helm on Kubernetes 1.20 Azure Cluster
2. Setup Azure AD SSO using OIDC
3. Provide users within a given group
4. Setup RBAC as per example above

**Expected behavior**

According to ArgoCD CLI tool and documentation, users within the group should have the ability to perform sync on applications. 

**Screenshots**

I can provide screenshots, but I would rather not add them to the issue here.

**Version**

```shell
argocd: v2.0.4+0842d44
  BuildDate: 2021-06-23T01:27:53Z
  GitCommit: 0842d448107eb1397b251e63ec4d4bc1b4efdd6e
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

I am unsure about which logs I should provide, I haven't seen any clear errors.

**Comment by andrei-dascalu** [comment]
I believe I found the issue - still testing.

The documentation for OIDC says about creating the AD Application: "Also, on "Token Configuration" page add groups claim for the groups assigned to the application"

This is slightly misleading. On the DEX configuration part, it specifically mentions that you should add those groups that should access Argo to the application, but there's no hint that you should look at DEX if you need to configure OIDC (so I skipped it).

You don't necessarily need to add the groups to the application, though it's good advice. You can also allow access to Security groups, which is what "az ad group create" will create a by default.

**Comment by MattMencel** [comment]
Hi @andrei-dascalu can you show where you added the group, according to the DEX config?

I've set up the OIDC auth and I get this exact error when trying to sync when logged in with my AAD account. But only if the default policy is set to `role:readonly`.

```
data:
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, projects, *, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    g, "AAD-GROUP-ID", role:org-admin
  policy.default: role:readonly
```

If I set the `policy.default: role:org-admin` then it works fine.

**Comment by andrei-dascalu** [comment]
@MattMencel  your config looks ok (where the ADD-GROUP-ID is the group's object ID). You should check that  after logging in to Argo, your AAD users have the expected group-id.

In my case, the immediate issue was that Argo wasn't receiving the group ID along with the user so it would only apply the default.
