### ISSUE TITLE
Proposal: support multiple sources for an Application

### ISSUE THREAD

**Issue by fabriziofortino** [argoproj/argo-cd#677]
Currently, an `Application` supports a single `ApplicationSource`. In some scenario it would be useful to support more than one source.

Here is a typical example: we have an `Application` that uses the [elasticsearch helm chart](https://github.com/helm/charts/tree/master/incubator/elasticsearch) as source. We need to create a separate `Application` to configure the [elasticsearch-exporter](https://github.com/helm/charts/tree/master/stable/elasticsearch-exporter) to expose Prometheus metrics.

From a logical point of view, these could be seen as a single application. In this way, the application can be `composed` using different sources/charts. What do you think? 🙇

**Comment by alexmt** [comment]
Great idea! I've faced the same scenario today and had to copy manifests of one app into another app. The composable app would be much cleaner. 

We would have to provide some way to solve possible naming conflicts. E.g. if two helm charts create deployments with the same name it should be possible to use different release names for each chart

**Comment by jessesuen** [comment]
Specifying multiple sources can now be accommodated by the configuration management plugins. I think adding native support multiple sources will complicate the implementation too greatly.

**Comment by alexec** [comment]
I think you can use app-of-apps to solve this? https://argoproj.github.io/argo-cd/operator-manual/cluster-bootstrapping/

**Comment by rltvty** [comment]
App-of-apps can take care of this, but I think it would be cleaner if the Application object itself could support multiple helm charts.  I realize this would complicate the ArgoCD implementation, but I think it would improve the user experience greatly.

**Comment by robseidel** [comment]
In our company we want to use different levels in our ops repositories, like global/cluster/application. We are already using a custom management plugin to get all these things together, but we are running into the problem, that argo syncs only a single source. So if the application config gets changed, argo recognize the change and start the deployment, but if the cluster configuration gets changed, nothing happens. The only way to sync such changes is manually refresh/hard or sync apps/force.

**Comment by jessesuen** [comment]
> I think adding native support multiple sources will complicate the implementation too greatly.

We originally eschewed this feature due to the added complexity of supporting 2+ sources for a single application. However, due to the refactoring needed to support https://github.com/argoproj/argo-cd/issues/2789, we are now reconsidering this feature.

Reopening.

**Comment by RafPe** [comment]
I am also looking for this! Would make life so much easier when deploying applications which co-exist together!

**Comment by blackandred** [comment]
For me the use case would be to install Helm & provide externally a secret that Helm requires but does not create. The same for service accounts and optional configmaps.

**Comment by subhashchy** [comment]
Would be great for us to have as well.  For us each application is a set of Frontend, edge-api-gateway, redis and 2 different edge workers.

**Comment by joebowbeer** [comment]
See https://github.com/argoproj/argo-cd/issues/2789#issuecomment-1207172980

**Comment by danielbraun89** [comment]
The use case of creating a cluster-role and a role-binding for an app separately is ridiculously common
Many Helm charts create service accounts for you but understandly never create the roles for you and this adds another layer for provisioning alongside argocd

**Comment by blackandred** [comment]
I have a workaround for this - it may be helpful for somebody.

Instead of using Helm directly use Helm via Kustomize - just set a source type in `kind: Application` to point to a kustomization.yaml, and in kustomization.yaml use e.g. Helm Chart, or multiple Helm Charts + plain YAML resources you would like to mix as part of one application.

In order to use Helm in kustomize you need also to change the build args in `argocd-cm` to enable helm during `kustomize build`.

**Comment by keskad** [comment]
I wrote about this topic on my blog, maybe somebody could be interested on how to handle this in few different ways: https://medium.com/p/424bc3a6bc8
