### ISSUE TITLE
unable to find the argocd-initial-admin-secret when upgraded to v2.0.4

### ISSUE THREAD

**Issue by kannamr** [argoproj/argo-cd#6787]
### Discussed in https://github.com/argoproj/argo-cd/discussions/6786

<div type='discussions-op-text'>

<sup>Originally posted by **kannamr** July 22, 2021</sup>
Hi,
    I have upgarded argo to v2.0.4. The last version I used was v1.7. I see after v1.9, the pod name is no longer admin password. From the docs, argocd-initial-admin-secret has be in the secrets. But unfortunately, I couldn't find the secret when using ```kubectl get secret -n argocd``` Resetting the password works, but I don't want to reset and I would like to use the initial password itself. Can someone help me with the issue. </div>

**Comment by kannamr** [comment]
New update from the discussion. It seems the upgrade doesn't create ```argocd-initial-admin-secret```. Is there way to do this? If not how to I retrieve the admin.password from ```argocd-secret```

**Comment by kannamr** [comment]
didn't get any response

**Comment by LiorLieberman** [comment]
any updates on this?
