### ISSUE TITLE
argocd account delete-token doesn't work

### ISSUE THREAD

**Issue by xiaoyaocloud** [argoproj/argo-cd#6816]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x ] I've included steps to reproduce the bug.
* [ x ] I've pasted the output of `argocd version`.

**Describe the bug**

`argocd account delete-token -a xxx-account-name`  doesn't work
`argocd account delete-token xxx-tokenId`  doesn't work

**To Reproduce**
1. create account named my-account (according to https://github.com/argoproj/argo-cd/issues/6567#issuecomment-868676896)
2. run `argocd account get -a my-account`, the output is as follows:
root@ubuntu:~# argocd account get -a my-account
Name:               my-account
Enabled:            true
Capabilities:       

Tokens:
ID                                    ISSUED AT                  EXPIRING AT
2367bc92-9234-4e56-b230-44b66e801e05  2021-07-27T17:43:01+08:00  never

3. Neither `argocd account  delete-token -a my-account`  or `argocd account  delete-token 2367bc92-9234-4e56-b230-44b66e801e05` doesn't work。the details can be seen from the screenshot

4. Then, I download the latest argocd(v2.0.5), the problem still exists!!!

**Expected behavior**

The command `argocd account delete-token xxx-tokenId` and `argocd account delete-token -a xxx-account-name` both work properly

**Screenshots**
![image](https://user-images.githubusercontent.com/20721018/127148654-75b3cdb0-869c-4405-8b99-3990c982c2d3.png)

**Version**

```shell
root@ubuntu:~# argocd version
argocd: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Logs**

```

```

**Comment by mayzhang2000** [comment]
I tried below and it is working for me.
```
argocd account get -a alice                  
Name:               alice
Enabled:            true
Capabilities:       apiKey, login

Tokens:
ID                                    ISSUED AT                  EXPIRING AT
9f99d9a9-513b-47c3-acf5-b8c624c1f009  2021-07-27T13:41:15-07:00  never

argocd account delete-token -a alice 9f99d9a9-513b-47c3-acf5-b8c624c1f009

argocd account get -a alice                                     
Name:               alice
Enabled:            true
Capabilities:       apiKey, login

Tokens:
NONE

```

**Comment by xiaoyaocloud** [comment]
> I tried below and it is working for me.
> 
> ```
> argocd account get -a alice                  
> Name:               alice
> Enabled:            true
> Capabilities:       apiKey, login
> 
> Tokens:
> ID                                    ISSUED AT                  EXPIRING AT
> 9f99d9a9-513b-47c3-acf5-b8c624c1f009  2021-07-27T13:41:15-07:00  never
> 
> argocd account delete-token -a alice 9f99d9a9-513b-47c3-acf5-b8c624c1f009
> 
> argocd account get -a alice                                     
> Name:               alice
> Enabled:            true
> Capabilities:       apiKey, login
> 
> Tokens:
> NONE
> ```

`argocd account delete-token -a account-name Token-ID` also works for me, but I did not see this form of command in the documentation （https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_account_delete-token/). Anymore, Is there an error in the example in the documentation？
![image](https://user-images.githubusercontent.com/20721018/127255370-8adba320-dd87-489f-835b-927da0926bc4.png)

**Comment by mayzhang2000** [comment]
Yes, the usage example is not correct. I created https://github.com/argoproj/argo-cd/pull/6831.

**Comment by xiaoyaocloud** [comment]
> Yes, the usage example is not correct. I created #6831.

@mayzhang2000  That's great. Thank you so much.
