### ISSUE TITLE
Application page load very slowly

### ISSUE THREAD

**Issue by karthikvijayan3** [argoproj/argo-cd#6821]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Argocd manages below 100 applications and 3 cluster takes more than 14 seconds to load application page( sometimes takes more 20 seconds), attached screenshot for reference

**To Reproduce**

Install ArgoCD v1.8.1+c2547dc and integrate with 100 apps and 3 EKS cluster

**Expected behavior**

Load time less than 10 seconds

**Screenshots**
<img width="1440" alt="Screenshot 2021-07-28 at 6 47 17 AM" src="https://user-images.githubusercontent.com/22365154/127248914-1930102c-d6d2-493c-a53a-5b659537d458.png">

**Version**

```shell
Version - v1.8.1+c2547dc
```

How to scale ArgoCD server to support more loads? Argocd repo, controller server scale docs are available but not able to find one for argocd server.

**Comment by mnacharov** [comment]
Hi!
We had the same issue, and partially solved it by increasing ARGOCD_CONTROLLER_REPLICAS in StatefulSet argocd-application-controller. This option enables sharding.
Also, take a look at [High Availability](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller) guide

**Comment by alexmt** [comment]
This slowness might be caused by large number of groups in JWT token. @karthikvijayan3 can you please check https://github.com/argoproj/argo-cd/issues/4296 - does it looks like the same issue?

**Comment by karthikvijayan3** [comment]
Looks like same issue..closing this ticket.
