### ISSUE TITLE
Add parameter to "argocd app rollback" to rollback to previous revision without providing its ID

### ISSUE THREAD

**Issue by jdomag** [argoproj/argo-cd#6825]
# Summary

Add additional parameter to command `argocd app rollback [APP]` that will perform rollback to previous release. As for now we need to find out previous revision ID from the history and then issue the rollback command.

# Motivation

In our CICD we deploy the app with `argocd app sync` and then run the tests of the application. When the tests fail for any reason, in the next step of CICD we do rollback with `argocd app rollback` - however it's complex as we need to get the previous ID somehow (from `argocd app history`). Would be great to have something like `--previous` switch in `argocd app rollback` to simply rollback to previous version without checking its ID.

**Comment by Junnplus** [comment]
Can we support `argocd app rollback [APP]` to simply rollback to previous version, like `helm rollback [RELEASE]`?

**Comment by pasha-codefresh** [comment]
i would take it
