### ISSUE TITLE
Add a metric to express connection status to each cluster

### ISSUE THREAD

**Issue by jutley** [argoproj/argo-cd#6855]
# Motivation

In the past, we have occasionally made misconfigurations that caused ArgoCD to get disconnected from some clusters. This is easy to detect if we manually check for the connectivity, but this isn't a task we would do under normal circumstances. To enable proactive fixing of this issue, we would like to have a metric for ArgoCD's cluster connectivity which we can alert on.

# Proposal

Adding a metric like this (probably in the application controller) would be sufficient.

```
argocd_cluster_connection_status{server="https://kubernetes....",name="my-cluster",version="1.21"} == 1
```

**Comment by Rol111-hub** [comment]
[Tatrabanka.sk](Tatrabanka.sk) VÚB banka.sk

**Comment by Rol111-hub** [comment]
Thanks
