### ISSUE TITLE
page navigator is missing on argocd v2.1.0-rc1

### ISSUE THREAD

**Issue by yydzhou** [argoproj/argo-cd#6867]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
The new web UI on v2.1.0-rc1 has lost its page navigator when there are multiple pages applications to list.

When there are too many applications, the UI allows user to select 5/10/15/20 per page for application list. However, there is no way to go to pages other than the first page as the page navigator is not show up on the UI. 

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

**Version**
v2.1.0-rc1

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by rwong2888** [comment]
I am seeing the same

**Comment by rbreeze** [comment]
Thanks for noticing this! I'll send a fix.
