### ISSUE TITLE
Should skip TLS warning with --insecure even the server is not running

### ISSUE THREAD

**Issue by Hongbo-Miao** [argoproj/argo-cd#6875]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Just a small UX issue.

One time, I forget to forward the port first

```shell
kubectl port-forward service/argocd-server --namespace=argocd 31026:443
```

When I login with `--insecure`, I got TLS warning

```shell
argocd login localhost:31026 --username=admin --password=xxx --insecure
WARNING: server is not configured with TLS. Proceed (y/n)?
```

**To Reproduce**

Just run

```shell
argocd login localhost:31026 --username=admin --password=xxx --insecure
```

without port forwarding first.

**Expected behavior**

I expect it fails directly without asking below y/n input from user.

> WARNING: server is not configured with TLS. Proceed (y/n)?

**Screenshots**

N/A

**Version**

```shell
argocd: v2.0.4+0842d44.dirty
  BuildDate: 2021-06-23T06:31:09Z
  GitCommit: 0842d448107eb1397b251e63ec4d4bc1b4efdd6e
  GitTreeState: dirty
  GoVersion: go1.16.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.5+4c94d88
  BuildDate: 2021-07-22T20:52:31Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Logs**

N/A

**Comment by pasha-codefresh** [comment]
hi @Hongbo-Miao , i can`t reproduce this issue with 2.0.5, please update your cli and try it again

**Comment by Hongbo-Miao** [comment]
Thanks @pasha-codefresh for following up!
I will close for now assuming it fixed. I will reopen if the issue is still there in future!

**Comment by marcelstange** [comment]
change --insecure to --plaintext

argocd login localhost:31026 --username=admin --password=xxx --plaintext

this will work...
