### ISSUE TITLE
argocd out-of-sync on GKE's BackendConfig object

### ISSUE THREAD

**Issue by stevesea** [argoproj/argo-cd#6894]
**Describe the bug**

After recent k8s master upgrades on GKE (to v1.18.19+) , my argocd applications that have a BackendConfig report 'out of sync'

```shell
# argocd diff shows live< vs desired>
❯ ./argocd app diff test-gateway-web                                                                                                            
===== cloud.google.com/BackendConfig test/gateway-web ======
18c18,19
<   securityPolicy: {}
---
>   securityPolicy:
>     name: ca-allow-only-cloudflare-source


# but, kubectl shows the manifest has the securityPolicy.name set 
❯ kubectl get backendconfig -o yaml gateway-web       
....redacted...
spec:
  connectionDraining:
    drainingTimeoutSec: 240
  securityPolicy:
    name: ca-allow-only-cloudflare-source
  timeoutSec: 3600
...redacted...
```

Per discussion in argocd slack https://cloud-native.slack.com/archives/C01TSERG0KZ/p1627918105136200 , there's at least one other user with the same problem. 

I assume the issue with with the BackgroundConfig CRD or other API differences after upgrading k8s master. But, I'm not sure where to go from here to diagnose it further. 

**Version**

```shell
> argocd version
argocd: v1.8.7+eb3d1fb
  BuildDate: 2021-03-03T07:14:50Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.7+eb3d1fb
  BuildDate: 2021-03-03T07:13:34Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
  
> kubectl version 
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.19-gke.1701", GitCommit:"d7cecefb99b58e8968f59b59d76448eb1e6ea403", GitTreeState:"clean", BuildDate:"2021-06-23T21:51:59Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alexmt** [comment]
Most likelly BackendConfig controller set the security policy to the default value. Such controller behavior frequently causes Argo CD or `kubectl diff` to report the difference. 

Technically this is controller bug. The workaround is described here: https://argo-cd.readthedocs.io/en/stable/faq/#why-is-my-application-still-outofsync-immediately-after-a-successful-sync

You might either change manifest and add default value or use [diffing customization](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/) and exclude security policy from diffing.

**Comment by stevesea** [comment]
as a work around, I added ignoreDifferences to my Applications
```yaml
ignoreDifferences:
  - group: cloud.google.com
    kind: BackendConfig
    jsonPointers:
    - /spec/securityPolicy
```

**Comment by stevesea** [comment]
Ahhh. Looks like our BackendConfig manifests are out-of-date. Once I change the apiVersion, argocd no longer reports out-of-sync. 


previously:
`apiVersion: cloud.google.com/v1beta1`

now:
`apiVersion: cloud.google.com/v1`
