### ISSUE TITLE
API Server fails to return apps due to grpc max message size limit

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#690]
If ArgoCD is trying to manage a lot of apps then API Server fails to return full list due to GRPC max message size limit.

We should increase limit and add pagination once kubernetes supports CRD pagination

**Comment by alexmt** [comment]
Seems like kubernetes now supports pagination for CRD: https://github.com/kubernetes/kubernetes/issues/68743

**Comment by jessesuen** [comment]
Now that we (1) increased the gRPC message size limit and (2) removed storing resource manifests in the application.status, I think we will be okay for a while since the app payload is much, much smaller. If needed, we can file a separate issue to support pagination.
