### ISSUE TITLE
ParseDurationFromEnv almost always returns default value

### ISSUE THREAD

**Issue by noam-codefresh** [argoproj/argo-cd#6910]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

When trying to use the new `timeout.reconciliation` value in the `argocd-cm`, we realized that the repo-server does not actually use it. Looking at it's logs we saw
```
time="2021-08-04T15:35:25Z" level=warning msg="Value in ARGOCD_RECONCILIATION_TIMEOUT is 10s, which is greater than maximum 2.147483647s allowed"
```
Looking at the code, it seems like the max value of ParseDurationFromEnv is wrongly set to 2.14 seconds.

**To Reproduce**
Add `timeout.reconciliation: 10s` to your `argocd-cm` data, and restart the repo-server.

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

Valid duration values should be allowed for `timeout.reconciliation`. Specifically, a max value of just over 2 seconds seems wrong.

**Screenshots**

**Version**

```shell
argocd: v2.0.5+4c94d88.dirty
  BuildDate: 2021-07-23T05:12:02Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: dirty
  GoVersion: go1.16.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.0-rc1+458416b
  BuildDate: 2021-08-01T13:34:35Z
  GitCommit: 458416bff1963c0ea75274fb2468f7343e20c629
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.1.2 2021-04-15T20:38:06Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0```

**Logs**

```
time="2021-08-04T15:35:25Z" level=warning msg="Value in ARGOCD_RECONCILIATION_TIMEOUT is 10s, which is greater than maximum 2.147483647s allowed"
```

**Comment by alexmt** [comment]
Thank you! Looking
