### ISSUE TITLE
Non-cryptographically secure random function

### ISSUE THREAD

**Issue by mayzhang2000** [argoproj/argo-cd#6922]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

The ​argoproj/pkg​ utility library​ implements r​and​ module with a RandString​ and RandStringCharset​ functions for generating cryptographically-secure pseudo-random strings. However, this rand modules the ​math/rand​ Go module which is not intended for security-sensitive work​. Additionally, the Argo CD codebase implements the same logic in its u​ til/rand/rand​ module​.

**Comment by harikrongali** [comment]
argoCd is refactored and require verification @mayzhang2000

**Comment by alexmt** [comment]
Ops, I was thinking this [PR](https://github.com/argoproj/argo-cd/pull/5138) fixed it but looks like it is not.

Can you please use "secure" rand string instead of insecure one here:
https://github.com/argoproj/argo-cd/blob/3091bc5b6f3d389376feaa999a63fc4986ae72a9/util/settings/settings.go#L1489

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/6938
