### ISSUE TITLE
pubsub.go:168: redis: discarding bad PubSub connection: redis: ping timeout

### ISSUE THREAD

**Issue by jasvinder-tp** [argoproj/argo-cd#6933]
**Describe the bug**
there was an update in nodepool, or in maintenance and every pods of argocd come up new. After come up, we are facing pubsub.go:168: redis: discarding bad PubSub connection: EOF issue in argocd.

**Every pod is up: described as below**

pod/argocd-application-controller-0            1/1     Running   0          38h
pod/argocd-dex-server-7fd8d769bd-jpw8n         1/1     Running   0          39h
pod/argocd-redis-ha-haproxy-76d7bd9bdc-5fhg5   1/1     Running   0          146m
pod/argocd-redis-ha-haproxy-76d7bd9bdc-8m8gj   1/1     Running   0          146m
pod/argocd-redis-ha-haproxy-76d7bd9bdc-nhhbh   1/1     Running   0          145m
pod/argocd-redis-ha-server-0                   2/2     Running   0          20m
pod/argocd-redis-ha-server-1                   2/2     Running   0          20m
pod/argocd-redis-ha-server-2                   2/2     Running   0          21m
pod/argocd-repo-server-5f87ccdcf-d6sjw         1/1     Running   0          38h
pod/argocd-repo-server-5f87ccdcf-df2fd         1/1     Running   0          38h
pod/argocd-server-7d5699b87f-5954d             1/1     Running   0          3h20m
pod/argocd-server-7d5699b87f-lclsj             1/1     Running   0          3h19m

**Logs of argocd-redis-haproxy as:**

**kubectl -n argocd logs pod/argocd-redis-ha-haproxy-76d7bd9bdc-5fhg5**

[WARNING] 220/113525 (9) : Server check_if_redis_is_master_2/R1 is DOWN, reason: Layer4 connection problem, info: "Connection refused at step 1 of tcp-check (connect)", check duration: 1031ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 220/113531 (9) : Server check_if_redis_is_master_2/R1 is UP, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 1ms. 3 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
[WARNING] 220/113541 (9) : Server check_if_redis_is_master_2/R0 is DOWN, reason: Layer4 timeout, info: " at step 1 of tcp-check (connect)", check duration: 3001ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 220/113548 (9) : Server check_if_redis_is_master_2/R0 is UP, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 1ms. 3 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.

**Logs of pod/argocd-redis-ha-server-0 as:**

kubectl -n argocd logs pod/argocd-redis-ha-server-0 -c redis

1:S 09 Aug 2021 12:03:21.042 * Connecting to MASTER 10.74.137.200:6379
1:S 09 Aug 2021 12:03:21.042 * MASTER <-> REPLICA sync started
1:S 09 Aug 2021 12:03:21.042 * Non blocking connect for SYNC fired the event.
1:S 09 Aug 2021 12:03:21.043 * Master replied to PING, replication can continue...
1:S 09 Aug 2021 12:03:21.043 * Partial resynchronization not possible (no cached master)
1:S 09 Aug 2021 12:03:21.043 * Master is currently unable to PSYNC but should be in the future: -NOMASTERLINK Can't SYNC while not connected with my master

**Logs of pod/argocd-server-7d5699b87f-5954d as:**
redis: 2021/08/09 12:04:40 pubsub.go:168: redis: discarding bad PubSub connection: write tcp 10.74.67.3:47904->10.74.140.27:6379: write: connection reset by peer
redis: 2021/08/09 12:04:40 pubsub.go:168: redis: discarding bad PubSub connection: write tcp 10.74.67.3:47904->10.74.140.27:6379: write: connection reset by peer
redis: 2021/08/09 12:04:40 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/09 12:04:40 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/09 12:04:41 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/09 12:04:41 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/09 12:04:41 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/09 12:04:41 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/09 12:04:41 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/09 12:04:41 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/09 12:04:41 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/09 12:04:41 pubsub.go:168: redis: discarding bad PubSub connection: EOF

**Version**
➜  .kube argocd version
argocd: v1.5.1+8a3b36b
  BuildDate: 2020-04-06T15:59:42Z
  GitCommit: 8a3b36bd28fe278f7407b9a8797c79ad859d1acd
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.5+4c94d88
  BuildDate: 2021-07-22T20:52:31Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4

Finally I have update the image of argocd-redis-ha-server from redis:5.0.10-alpine to v6.2.4, but not luck.

and haproxy:
    Image:        haproxy:2.0.22
    
    
    Can someone help on it.

**Comment by rajdeep2001** [comment]
I am getting the same exact error as soon as installed HA version of argocd:-

 $**k logs -f argocd-redis-ha-haproxy-59dfb5c7c7-9wwmr -n argocd**

[NOTICE]   (1) : New worker #1 (7) forked
[WARNING]  (7) : Server check_if_redis_is_master_1/R0 is DOWN, reason: Layer7 timeout, info: " at step 5 of tcp-check (expect string '172.20.58.12')", check duration: 2753ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING]  (7) : Server check_if_redis_is_master_2/R0 is DOWN, reason: Layer7 timeout, info: " at step 5 of tcp-check (expect string '172.20.88.133')", check duration: 2002ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING]  (7) : Server check_if_redis_is_master_1/R1 is DOWN, reason: Layer7 timeout, info: " at step 5 of tcp-check (expect string '172.20.58.12')", check duration: 2506ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING]  (7) : Server check_if_redis_is_master_1/R2 is DOWN, reason: Layer7 timeout, info: " at step 5 of tcp-check (expect string '172.20.58.12')", check duration: 2256ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[NOTICE]   (7) : haproxy version is 2.4.2-553dee3
[NOTICE]   (7) : path to executable is /usr/local/sbin/haproxy
[ALERT]    (7) : backend 'check_if_redis_is_master_1' has no server available!
[WARNING]  (7) : Server check_if_redis_is_master_2/R1 is DOWN, reason: Layer7 timeout, info: " at step 5 of tcp-check (expect string '172.20.88.133')", check duration: 2002ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING]  (7) : Server check_if_redis_is_master_2/R2 is DOWN, reason: Layer7 timeout, info: " at step 5 of tcp-check (expect string '172.20.88.133')", check duration: 2001ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[ALERT]    (7) : backend 'check_if_redis_is_master_2' has no server available!
[WARNING]  (7) : Server bk_redis_master/R1 is DOWN, reason: Layer7 timeout, info: " at step 5 of tcp-check (expect string 'role:master')", check duration: 2755ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING]  (7) : Server bk_redis_master/R2 is DOWN, reason: Layer7 timeout, info: " at step 5 of tcp-check (expect string 'role:master')", check duration: 2505ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING]  (7) : Server bk_redis_master/R0 is DOWN, reason: Layer4 timeout, info: " at step 1 of tcp-check (connect)", check duration: 3001ms. 0 active and 0 backup servers left. 4 sessions active, 0 requeued, 0 remaining in queue.
[ALERT]    (7) : backend 'bk_redis_master' has no server available!
[WARNING]  (7) : Server check_if_redis_is_master_0/R0 is DOWN, reason: Layer4 connection problem, info: "Connection refused at step 1 of tcp-check (connect)", check duration: 0ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING]  (7) : Server check_if_redis_is_master_0/R1 is DOWN, reason: Layer4 connection problem, info: "Connection refused at step 1 of tcp-check (connect)", check duration: 1030ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING]  (7) : Server check_if_redis_is_master_0/R2 is DOWN, reason: Layer4 timeout, info: " at step 1 of tcp-check (connect)", check duration: 3000ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[ALERT]    (7) : backend 'check_if_redis_is_master_0' has no server available!
[WARNING]  (7) : Server bk_redis_master/R0 is UP, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 8ms. 1 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
[WARNING]  (7) : Server check_if_redis_is_master_0/R0 is UP, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 2ms. 1 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
[WARNING]  (7) : Server check_if_redis_is_master_0/R1 is UP, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 2ms. 2 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
[WARNING]  (7) : Server check_if_redis_is_master_0/R2 is UP, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 3ms. 3 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
[WARNING]  (7) : Server bk_redis_master/R0 is DOWN, reason: Layer4 timeout, info: " at step 1 of tcp-check (connect)", check duration: 3000ms. 0 active and 0 backup servers left. 2 sessions active, 0 requeued, 0 remaining in queue.
[ALERT]    (7) : backend 'bk_redis_master' has no server available!

$ **k logs -f argocd-server-57df8b4ffc-vmt4x -n argocd**

redis: 2021/08/10 13:58:19 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/10 13:58:19 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/10 13:58:19 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/10 13:58:19 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/10 13:58:19 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/10 13:58:19 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/10 13:58:19 pubsub.go:168: redis: discarding bad PubSub connection: write tcp 100.65.209.22:51618->172.20.63.189:6379: write: broken pipe
redis: 2021/08/10 13:58:19 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/10 13:58:20 pubsub.go:168: redis: discarding bad PubSub connection: EOF
redis: 2021/08/10 13:58:20 pubsub.go:168: redis: discarding bad PubSub connection: redis: ping timeout

**Please please help!! Appreciate it.**

**Comment by rajdeep2001** [comment]
SOLVED - I was getting 404 not b'coz of above errors but since the static assets were missing in the **argocd-server** deployment manifest. I've added below container cmd arguments and ArgoCD UI started working..
        - --insecure
        - --staticassets
        - /shared/app
![image](https://user-images.githubusercontent.com/26584741/129821713-3e560d62-dc16-4a3c-95af-dbeb8a8ce226.png)
