### ISSUE TITLE
Argo RC 2.1 -config referenced '$google-auth-secret:oidc.auth0.clientid', but key does not exist in secret"

### ISSUE THREAD

**Issue by rubenssoto** [argoproj/argo-cd#6934]
Hello Guys,

Im trying to configure SSO with secrets on the argocd 2.1 RC, could you help me?

Error:
`time="2021-08-09T17:48:59Z" level=warning msg="config referenced '$google-auth-secret:google.auth0.clientid', but key does not exist in secret"
time="2021-08-09T17:48:59Z" level=warning msg="config referenced '$google-auth-secret:google.auth0.clientsecret', but key does not exist in secret"`

but the secret exists:
<img width="595" alt="Captura de Tela 2021-08-09 às 14 49 48" src="https://user-images.githubusercontent.com/36298331/128750974-3ad608b7-d7af-4e2f-a683-394ad1aac597.png">

**Comment by rubenssoto** [comment]
I forgot the label...thank you

**Comment by alexmt** [comment]
Hello @rubenssoto , 

I think you are missing: `app.kubernetes.io/part-of: argocd` label on the secret. https://argo-cd.readthedocs.io/en/latest/operator-manual/user-management/#alternative . Can you give it a try please?
