### ISSUE TITLE
UI: Tree elements overlap with filters

### ISSUE THREAD

**Issue by rbreeze** [argoproj/argo-cd#6935]
<img width="477" alt="Screen Shot 2021-08-09 at 10 55 48 AM" src="https://user-images.githubusercontent.com/6250584/128751727-3839efd7-12f6-4c2e-ba6d-ca06f5958cfd.png">

**Comment by pasha-codefresh** [comment]
@alexmt i would take it

**Comment by pasha-codefresh** [comment]
@rbreeze could you please add details how to reproduce it?

**Comment by rbreeze** [comment]
Looks like it's been fixed with the latest improvement to filters
