### ISSUE TITLE
UI: Grid-tree view to improve information density and preserve visual hierarchy

### ISSUE THREAD

**Issue by rbreeze** [argoproj/argo-cd#6936]
# Summary

A new view to supplement (or someday replace) the tree view to improve the amount of information shown on screen at a time. This view would pack Resources into a grid that can display parent/child relationships like the tree view, but uses smaller elements to represent tree nodes, like the Pod view.

# Motivation

It's true many Argo CD users use large monitors, where this is less of an issue. However, regardless of screen size, space in tree view isn't used as efficiently as it might be. This is especially clear on my 13" laptop: 

<img width="1362" alt="Screen Shot 2021-08-09 at 10 57 55 AM" src="https://user-images.githubusercontent.com/6250584/128752590-a3fed75d-2d59-4f02-96ac-b9aba6b5deaf.png">

Even at the most "dense" portion of the tree, there's still quite a bit of empty or redundant space: 
<img width="1373" alt="Screen Shot 2021-08-09 at 10 58 14 AM" src="https://user-images.githubusercontent.com/6250584/128752621-d6e2df20-2025-4d9f-b3b9-441cd6712cf5.png">

# Proposal

TODO: Post mockup here

**Comment by ciiay** [comment]
Is this one similar with [Compact application resources tree #7349](https://github.com/argoproj/argo-cd/issues/7349)?
