### ISSUE TITLE
Horizontal filters on applications screen waste space

### ISSUE THREAD

**Issue by bgolding355** [argoproj/argo-cd#6945]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

There are two positions of the filters, the top and the side. On the side view, space is efficiently used. On the top view however, each non-standard filter they form a single column which is
a) taller than everything else, and nearly even in height when collapsed
b) wastes space to the right

**To Reproduce**

1. Go to https://cd.apps.argoproj.io/applications?proj=&sync=&health=&namespace=&cluster=&labels=
2. Press "Show" next to the filters funnel
3. Zoom out until the filters are above the content area
4. Collapse Labels, Projects, Clusters, and Namespaces
5. Observe the wasted space to the right as well as the trapped whitespace to the left. 

**Expected behavior**

Space should be used more efficiently

**Screenshots**
![Screenshot from 2021-08-10 16-54-24](https://user-images.githubusercontent.com/60831565/128933645-af3b1779-984c-4101-a763-3861af072225.png)

**Version**

```shell
{
    "Version": "v2.1.0+c5eb25c",
    "BuildDate": "2021-08-10T02:22:42Z",
    "GitCommit": "c5eb25cebac5c8a48f2f6db8bd2136a1672fbb2f",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexmt** [comment]
Agree - I'm trying to improve it in this PR: https://github.com/argoproj/argo-cd/pull/6931#issuecomment-895705410
