### ISSUE TITLE
Node list jumping on unschedulable button press

### ISSUE THREAD

**Issue by bgolding355** [argoproj/argo-cd#6946]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When the 'unschedulable' button is pressed in the Pod view grouped by Node. The list below jumps up/down

**To Reproduce**

1. Go to https://cd.apps.argoproj.io/applications/argo-cd?view=pods&orphaned=false
2. Press the 'unschedulable' button

**Expected behavior**

The list should not move

**Screenshots**

https://user-images.githubusercontent.com/60831565/128938282-82118921-2574-4fe5-9c45-66182c6fbe06.mp4

**Version**

```shell
{
    "Version": "v2.1.0+c5eb25c",
    "BuildDate": "2021-08-10T02:22:42Z",
    "GitCommit": "c5eb25cebac5c8a48f2f6db8bd2136a1672fbb2f",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by saumeya** [comment]
I will work on this.
