### ISSUE TITLE
Question / Unable to view events

### ISSUE THREAD

**Issue by tannerpaige** [argoproj/argo-cd#695]
When I deployed argo-cd, I deployed it into its own namespace, argocd. Deploying my application, I want it in its own namespace, also. However, in the Argo CD UI, when I click on something like a Deployment, I get the following error:

`User "system:serviceaccount:argocd:argocd-server" cannot list events in the namespace "other"`

What can I edit to get this user access to the "other" namespace? Or just all namespaces?

Also, do resources have to be certain apiVersions? And where would that information be in your docs? For example, I had a Deployment of apiVersion `apps/v1` but Argo CD ignored it until I changed it to `apps/v1beta2`.

Lastly, is this where I should be asking my dumb questions, or is there somewhere else you would prefer?

**Comment by jessesuen** [comment]
@tannerpaige thanks for discovering this. This is a bug in the install manifests. You can add:
```
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
```
to the argocd-server-clusterrole ClusterRole.

> Also, do resources have to be certain apiVersions? And where would that information be in your docs? For example, I had a Deployment of apiVersion apps/v1 but Argo CD ignored it until I changed it to apps/v1beta2.

We do not expect resources to be of a certain apiVersion. It's strange for Argo CD to ignore it, unless the manifest itself was malformed. For example, our sock shop example is with apps/v1. If you think this a bug, you can file a separate issue.

> Lastly, is this where I should be asking my dumb questions, or is there somewhere else you would prefer?

We have a slack. Specifically the #argo-cd channel is where you can get quicker responses. You can join here:
https://join.slack.com/t/argoproj/shared_invite/enQtMzExODU3MzIyNjYzLTA5MTFjNjI0Nzg3NzNiMDZiNmRiODM4Y2M1NWQxOGYzMzZkNTc1YWVkYTZkNzdlNmYyZjMxNWI3NjY2MDc1MzI

**Comment by jessesuen** [comment]
Duping to #704
