### ISSUE TITLE
ArgoCD ignores LimitRange manifest

### ISSUE THREAD

**Issue by sidh** [argoproj/argo-cd#6959]
Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**

We have argocd helmfile-based application configured to autosync. This application has a LimitRange manifest.

This manifest is rendered and installed manually via helmfile without any issues (we see the LimitTange in template output). Argocd on the other hand does not see it at all. It does not show up UI, no diff for it and obviously it is not applied when our application is synced.

All other manifests are fine.

We use https://hub.docker.com/r/chatwork/argocd-helmfile for reposerver to add helmfile support.

**To Reproduce**

1. Add LimitRange manifest.
2. Commit to git repo.
3. ArgoCD does not detect LimitRange manifest.

**Expected behavior**

ArgoCD detects LimitRange manifest and applies it.

**Version**

argocd version
argocd: v2.0.5+4c94d88
  BuildDate: 2021-07-22T20:52:31Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.5+4c94d88

argocd helm chart - 3.11.5 (didnt work with earlier versions too)
chatwork/argocd-helmfile - 2.0.5-0.140.0

**Comment by alexmt** [comment]
Looks like use are using this command to produce manifests:

```
helmfile --namespace $ARGOCD_APP_NAMESPACE template | sed -e '1,/---/d' | sed -e 's|apiregistration.k8s.io/v1beta1|apiregistration.k8s.io/v1|g'
```

Can you try to run it locally and confirm that LimitRange present?

**Comment by sidh** [comment]
You are absolutely correct! I completely forgot we use this custom command line with sed. `sed -e '1,/---/d'` removes first block with '---' in it and that block happens to be LimitRange.

Closing this ticket.

**Comment by alexmt** [comment]
Thank you for confirming!
