### ISSUE TITLE
Regression in Release Candidate 2.1

### ISSUE THREAD

**Issue by Reamer** [argoproj/argo-cd#6968]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
 
PR #5814 changes the root file system to read-only. During startup in Openshift the entrypoint script `uid_entrypoint.sh` is called, the attempt to add an [additional line in `/etc/passwd`](https://github.com/argoproj/argo-cd/blob/97e8c7d00db8c4bd4a532ab99e5f0bbdc2243234/uid_entrypoint.sh#L8) fails because of the read-only file system. After that git+ssh checkouts fail.

**To Reproduce**

Start argocd-repo-server in Openshift and try to clone a repository with ssh.

**Expected behavior**

argocd-repo-server should be able to check out Git repositories via ssh.

**Version**

```shell
argocd: v2.1.0-rc2+b067879
  BuildDate: 2021-08-03T17:08:07Z
  GitCommit: b067879892d3586bb2392dfc2f0932e9bde231dd
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2021-08-12T07:41:12Z" level=error msg="`git fetch origin --tags --force` failed exit status 128: No user exists for uid 1000690000\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists." execID=oFo59
```

**Comment by sbose78** [comment]
Note, there's no official Red Hat support for Openshift versions below 4.7 at the moment.

**Comment by sbose78** [comment]
@Reamer which version of OpenShift do you usually run Argo CD run?

**Comment by Reamer** [comment]
> @Reamer which version of OpenShift do you usually run Argo CD in?

At the moment Argo CD is running on okd 4.7.

**Comment by sbose78** [comment]
@Reamer thank you, that's helpful.

Would you have a chance to make a PR with solution (2) ?

**Comment by Reamer** [comment]
@sbose78 I created a PR against Branch release-2.1 or should I create a PR against master?
I have also tested this change manually.

**Comment by alexmt** [comment]
Thank you @Reamer ! Please create PR agains master and I will cherry-pick it to release-2.1

**Comment by Reamer** [comment]
> Thank you @Reamer ! Please create PR agains master and I will cherry-pick it to release-2.1

Done.

**Comment by Reamer** [comment]
@alexmt The PR has been merged into Master.
I am waiting for a cherry pick :-D

**Comment by jannfis** [comment]
@Reamer I just cherry picked it, thanks!
