### ISSUE TITLE
Docs: missing repository type for declarative setup

### ISSUE THREAD

**Issue by MehrCurry** [argoproj/argo-cd#6984]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When added repository secrets as describe in the docs the repos are not accessible.

**To Reproduce**

Apply secrets as described in https://argo-cd.readthedocs.io/en/latest/operator-manual/declarative-setup/#repository-credentials

**Possible fix**

After a little try&error i figured out the `type: git` is missing in the docs.

**Version**

```shell
argocd: v2.0.1+33eaf11.dirty
  BuildDate: 2021-04-21T18:44:13Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: dirty
  GoVersion: go1.16.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.0-rc3+5700faf
  BuildDate: 2021-08-11T19:44:44Z
  GitCommit: 5700faf0d17dacad93c5fe96edd42fb6dd1ae7b1
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0```

**Comment by jannfis** [comment]
Hey @MehrCurry, would you like to submit a PR for this?

**Comment by MehrCurry** [comment]
PR created. I am not sure if it is complete. I suppose that the helm example lack something like `type: helm`. But i didn't checked that.
