### ISSUE TITLE
Docs: Hint how to use labels for sealed secrets

### ISSUE THREAD

**Issue by MehrCurry** [argoproj/argo-cd#6985]
# Summary

When creating `argocd.argoproj.io/secret-type: repo-creds` and using `kubeseal` the labels got lost.

# Motivation

The secret seams to be used anyway but is not shown in the UI.

# Proposal

The labels have to be re-added to the sealed secret like described here: https://github.com/bitnami-labs/sealed-secrets#sealedsecrets-as-templates-for-secrets

Perhaps a small notice should be added to the documentation since to documentation recommends using sealed-secrets.

**Comment by jannfis** [comment]
Hey @MehrCurry, would you be willing to contribute this to the docs?

**Comment by MehrCurry** [comment]
Also fixed by #7013
