### ISSUE TITLE
Unable to login to Argo CD using auto generated initial password

### ISSUE THREAD

**Issue by sagar-jadhav** [argoproj/argo-cd#6996]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Unable to log in to freshly installed Argo CD UI using the username as `admin` and auto-generated initial password. I have followed the steps mentioned [here](https://argo-cd.readthedocs.io/en/stable/getting_started/#4-login-using-the-cli).

**To Reproduce**

Follow steps mentioned [here](https://argo-cd.readthedocs.io/en/stable/getting_started/).

**Expected behavior**

I should be able to login using username `admin` and with auto generated initial password.

**Screenshots**

![Screen Shot 2021-08-16 at 12 13 46 PM](https://user-images.githubusercontent.com/6671846/129525184-186501cd-6f9a-4f05-89f7-00e9825424cc.png)

**Version**

```shell
v2.0.5
```

```

**Comment by jannfis** [comment]
Did you follow the instructions for pre-2.0 versions or post-2.0? I.e. did you get the password from the pod name or using the following snippet?

```
kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
```

**Comment by sagar-jadhav** [comment]
I am able to log in with the password I retrieved using the below command:

```
kubectl get secret argocd-initialh='{.data.password}' -n argocd | base64 -d
```

If it's the right step to fetch the auto-generated initial password then documentation needs to be updated.

**Comment by sagar-jadhav** [comment]
> Did you follow the instructions for pre-2.0 versions or post-2.0? I.e. did you get the password from the pod name or using the following snippet?
> 
> ```
> kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
> ```

Password as Pod name not working. I tried the other approach i.e. getting the password from `argocd-initial-admin-secret`

**Comment by jannfis** [comment]
The method has been changed starting with 2.0 release of Argo CD. We tried denoting that in the documentation with "Version 1.8 and earlier" and "Version 1.9 and later". We removed that in the current HEAD of the documentation (https://argo-cd.readthedocs.io/en/latest/getting_started/#4-login-using-the-cli), which will become the stable docs with the 2.1 release.

**Comment by sagar-jadhav** [comment]
> The method has been changed starting with 2.0 release of Argo CD. We tried denoting that in the documentation with "Version 1.8 and earlier" and "Version 1.9 and later". We removed that in the current HEAD of the documentation (https://argo-cd.readthedocs.io/en/latest/getting_started/#4-login-using-the-cli), which will become the stable docs with the 2.1 release.

Thank you @jannfis I was following the `stable` version docs.
