### ISSUE TITLE
Argo-server panics unexpectly while logging.

### ISSUE THREAD

**Issue by cbl315** [argoproj/argo-cd#7006]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

See logs

**To Reproduce**

Need to figure out more to reproduce.

**Expected behavior**

No panic

**Screenshots**

**Version**

```shell
➜  ~ argocd version
argocd: v2.0.5+4c94d88
  BuildDate: 2021-07-22T20:54:35Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.5+4c94d88
```

**Logs**

```go
panic: send on closed channel

goroutine 868 [running]:
github.com/argoproj/argo-cd/v2/server/application.mergeLogStreams.func2(0xc03efa48e7023b01, 0x677ed0795)
	/go/src/github.com/argoproj/argo-cd/server/application/logs.go:114 +0x4d4
github.com/argoproj/argo-cd/v2/server/application.mergeLogStreams.func3(0xc002b30820, 0xc004203218, 0xc002b6b4a0, 0x5f5e100, 0xc002cba060)
	/go/src/github.com/argoproj/argo-cd/server/application/logs.go:128 +0x179
created by github.com/argoproj/argo-cd/v2/server/application.mergeLogStreams
	/go/src/github.com/argoproj/argo-cd/server/application/logs.go:123 +0x2a5
```

**Comment by jcputter** [comment]
i'm hitting this exact issue trying to retrieve log stream via the api. (/api/v1/applications/{name}/logs)

**Comment by ashutosh16** [comment]
@jcputter Can you provide more information on this issue? I tried reproducing the issue on argocd v2.4 & v2.0.5 but haven't been able to reproduce it.

**Comment by nicc777** [comment]
Hi - we had the same issue and we have been able to replicate the problem and observe the conditions. In our case we had a process using ArgoCD to monitor logs while a service was deploying. In this specific instance, a lot of logs were generated, and ArgoCD eventually ran out of memory (using defaults for the Helm chart). It also appears that several days after a large data fetch which did not crash the server, the memory is not cleared. It gives the impression of a memory leak or data objects that are never delete. 

I hope this info helps

**Comment by crenshaw-dev** [comment]
@nicc777 were you able to identify what precisely was using up memory? Was it the logs themselves, or something else?

There's a known issue with Helm where, if an App points at a version that no longer exists, Helm downloads large files and fails to clean them up. That can cause a disk space issue. https://github.com/helm/helm/issues/11171

**Comment by nicc777** [comment]
> @nicc777 were you able to identify what precisely was using up memory? Was it the logs themselves, or something else?
> 
> There's a known issue with Helm where, if an App points at a version that no longer exists, Helm downloads large files and fails to clean them up. That can cause a disk space issue. [helm/helm#11171](https://github.com/helm/helm/issues/11171)

It appears to be the logs themselves. We can recreate the problem by deploying a known problematic application and consuming the logs through the ArgoCD API. The way we found it was that one of our pods were creating a crazy amount of log messages (mostly exception stack traces, btw). The memory consumption was constantly growing and the moment we deleted that application, memory usage growth stopped but it never goes down again.

I suspect the memory is never cleared. Reason I say this is that we observed several Argocd Server pod restarts over time but we could never put our finger on it - it appears very random. Now that we have made the link, we can predict more or less when a restart will happen. We are now updating our processes not to use this API feature, but to rather obtain log info by other means. However, I tihink it would be good if the problem can be (or has been) fixed.

Issue  #11171 could very well also be related, as we do use Helm extensively. It's a development/testing environment, so there can be several application deployments through the day, and they have a limited lifespan.

**Comment by tooptoop4** [comment]
i'm getting this on v2.7.16

**Comment by bgehman** [comment]
Seeing same intermittent crash v2.10.2

**Comment by morapet** [comment]
I have observed similar problem, with my limited knowledge of go, I assume the problem is in here 
https://github.com/argoproj/argo-cd/blob/81de487cf6dfc4e160ea1d791d5407f384179e66/server/application/logs.go#L147
There is no code which prevents close(merge) happend and then the timer above to timeout exactly when merge was closed, either the timer should be canceled before cancel(merge) or a lock is needed or send should not try to send data into closed stream

solutions:
a. reverse operations during end
ticker.Stop()   <- stop timer before close so the expiration after merge before stop does not crash the argocd
close(merged)

b. use lock to prevent timer to expire and flush at the time is being closed
c. prevent send to try to send on something being closed

The a) seems as simplest solution from my perspective

![image](https://github.com/user-attachments/assets/3be3b36b-d256-4e9f-9e18-74441ff5164a)

**Comment by crenshaw-dev** [comment]
Just observed this in 2.13.1, I don't think the above fixed it.

```
panic: send on closed channel

goroutine 446 [running]:
github.com/argoproj/argo-cd/v2/server/application.mergeLogStreams.func2(0x1)
        /go/src/github.com/argoproj/argo-cd/server/application/logs.go:114 +0x46c
github.com/argoproj/argo-cd/v2/server/application.mergeLogStreams.func3()
        /go/src/github.com/argoproj/argo-cd/server/application/logs.go:128 +0x113
created by github.com/argoproj/argo-cd/v2/server/application.mergeLogStreams in goroutine 368
        /go/src/github.com/argoproj/argo-cd/server/application/logs.go:123 +0x2eb
```

**Comment by krkjack** [comment]
This is related to #12031. By grabbing logs using `argocd app logs` you can observe `argocd-server` Goroutines going up and never coming back down, until it restarts.

**Comment by crenshaw-dev** [comment]
@krkjack can you describe how they're related? This panic causes argocd-server to crash, so I'm not sure how it could contribute to a goroutine leak.

**Comment by kjackowski-ca** [comment]
> @krkjack can you describe how they're related? This panic causes argocd-server to crash, so I'm not sure how it could contribute to a goroutine leak.

From my observations of the `argocd-server` Goroutines chart, the panic appears to occur at approximately the same Goroutines count of ~1k, so at a glance they look correlated.

**Comment by krkjack** [comment]
> @krkjack can you describe how they're related? This panic causes argocd-server to crash, so I'm not sure how it could contribute to a goroutine leak.

From my observations of the `argocd-server` Goroutines chart, the panic appears to occur at approximately the same Goroutines count of ~1k, so at a glance they look correlated.
