### ISSUE TITLE
Argocd is slack integration is not working as expected #100a

### ISSUE THREAD

**Issue by satishreddys** [argoproj/argo-cd#7014]
Issue

Argocd-notifications-controller is able to trigger event but slack integration is not working expected

NAME TEMPLATE CONDITION
on-deployed app-deployed app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'

Sample APP
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: guestbook
annotations:
notifications.argoproj.io/subscribe.on-deployed.slack: argocd-alerts
spec:
destination:
namespace: argocd
server: https://kubernetes.default.svc
project: default
source:
path: kustomize-guestbook
repoURL: https://github.com/argoproj/argocd-example-apps.git
targetRevision: HEAD
syncPolicy:
automated: {}

Steps followed to integrate slack

https://argocd-notifications.readthedocs.io/en/stable/services/slack/

We only have oauth token specified in the secret as per documentation but not webhook url .

**Comment by alexmt** [comment]
Can you please open this issue in https://github.com/argoproj-labs/argocd-notifications ?
