### ISSUE TITLE
Application Health Status Bar is reproduced at bottom of page

### ISSUE THREAD

**Issue by reginapizza** [argoproj/argo-cd#7023]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`. 

**Describe the bug**

The application status health bar is also present at the bottom of the page.

**To Reproduce**
Visit https://cd.apps.argoproj.io/applications and scroll to bottom

**Expected behavior**

There should only be one application health status bar at the top, should not be reproduced at the bottom of the screen

**Screenshots**
![doublestatusbar](https://user-images.githubusercontent.com/50851526/130096308-0ed8e0c3-0260-472d-ace5-e42e31374705.png)

**Version**

2.1.0

**Comment by rbreeze** [comment]
To be honest I thought this was intended behavior. I think it could be useful to have at both the top and bottom, but I don't have a strong opinion either way.

**Comment by servo1x** [comment]
Perhaps it should be sticky?

**Comment by reginapizza** [comment]
Trying to come up with a solution to this- would it be okay to move it out of it's current space and move it above the paginate component so it doesn't duplicate, and also include an inline button to disable it? I've heard some feedback on the Red Hat side that some users want an option to disable/hide it, so might be good to give users that option... what do you think @rbreeze?

**Comment by reginapizza** [comment]
What about something like this? 

https://user-images.githubusercontent.com/50851526/131897344-3b28c650-eab6-4142-9c8c-e93145388c30.mp4

(Sidenote: there are some implementation issues I'm working out with this still, especially at different screen sizes. I would still need further testing to make sure this is a fully functional solution)

**Comment by saumeya** [comment]
can this be closed @reginapizza
