### ISSUE TITLE
x509: certificate signed by unknown authority on private git repo

### ISSUE THREAD

**Issue by jaxxstorm** [argoproj/argo-cd#703]
Is it possible to specify my CA certificate, or have it not check the certs validity?

**Comment by jaxxstorm** [comment]
I just noticed this is all available via the command line tool, I was attempting to use the webui

**Comment by papanito** [comment]
I have the same problem
```
Unable to load data: Get https://scm.intra/argocd/test/info/refs?service=git-upload-pack: x509: certificate signed by unknown authority
```
