### ISSUE TITLE
Release Linux/ARM64 Argo-CD binary to the GitHub Releases

### ISSUE THREAD

**Issue by odidev** [argoproj/argo-cd#7035]
Hi Team, 

I am working on Argo-CD over Linux/ARM64 platform. I could see that Argo-CD does not release binaries for ARM64 architecture in the GitHub releases. 

I have successfully generated Linux/ARM64 binaries on the native platform using below command: 
~~~ 
go build –o argocd-linux-arm64 ./cmd/ 
~~~ 

There is already a PR raised for releasing Linux/ARM64 Argo-CD docker image. It will be helpful if ARM64 binaries are also made available in the GitHub releases.  

Are you planning on releasing ARM64 Argo-CD binaries? If required, I am happy to help and contribute.

**Comment by iam-veeramalla** [comment]
Hi @odidev , Yes, there is some work going on in the PR #6758 to release the ARM64 Images. I think the binaries would be part of the release when ARM images are made part of the release but @jannfis can confirm this. 

@jannfis can we assume if the decision is made to release ARM images it would also include the release of the ARM binaries ?

**Comment by wtam2018** [comment]
milestone v2.2

**Comment by odidev** [comment]
@wtam2018 @iam-veeramalla  ..... Thank you for adding this activity to milestone v2.2. May I know if there is an ETA for the same?

**Comment by iam-veeramalla** [comment]
@alexmt can answer this :)

**Comment by damntourists** [comment]
I am also interested in this.

**Comment by tbbharaj** [comment]
Eagerly looking forward to arm64 release...would be interested to know if there's timeline planned for it :)

**Comment by booleanbetrayal** [comment]
Just trying to follow the status of ARM64 binaries availability for the Releases page. Is this currently slated for the v2.3 milestone?
