### ISSUE TITLE
Cluster filter popping out of box

### ISSUE THREAD

**Issue by karthikvijayan3** [argoproj/argo-cd#7046]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**
Cluster filter popping out of box

**To Reproduce**

Install argocd 2.1.1 and add an EKS cluster.

**Expected behavior**
Cluster name should be properly formatted within box 

**Screenshots**

<img width="283" alt="Screenshot 2021-08-23 at 12 25 16 AM" src="https://user-images.githubusercontent.com/22365154/130366881-8a4b731e-5cf2-41fc-a11d-24342ab54f78.png">

**Version**

```shell
v2.1.0+d0b2d55
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by iam-veeramalla** [comment]
@saumeya or @ciiay  may be interested

**Comment by alexmt** [comment]
or @rbreeze

**Comment by rbreeze** [comment]
I think this will need to be fixed in https://github.com/argoproj/argo-ui. I can take a look
