### ISSUE TITLE
Ability to define retry options during app creation

### ISSUE THREAD

**Issue by pasha-codefresh** [argoproj/argo-cd#7057]
# Summary

Ability to define retry options during argocd app creation

# Motivation
It is possible to define the retry option during sync, but it is impossible to define it during app creation

During sync flow :
<img width="590" alt="During sync flow" src="https://user-images.githubusercontent.com/39732895/130589485-bf14ff97-8408-40f6-98ba-54da32ba889d.png">

During app creation flow :

<img width="1302" alt="App creation flow" src="https://user-images.githubusercontent.com/39732895/130589603-d4b62792-d300-4986-ad57-0c0da6829405.png">

**Comment by plakyda-codefresh** [comment]
I would take it

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-cd/pull/7252
