### ISSUE TITLE
"Show orphaned" overlapping

### ISSUE THREAD

**Issue by plakyda-codefresh** [argoproj/argo-cd#7079]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Show orphaned overlaps (Resources list view)

**Screenshots**

![image](https://user-images.githubusercontent.com/41683345/130769432-fa00a8ea-8526-4f61-9136-7a3e2bfe733f.png)

**Version**
v2.1.0+ca5003f

**Comment by plakyda-codefresh** [comment]
Let's move show orphaned to filter block
![image](https://user-images.githubusercontent.com/41683345/130770108-8a7aaf2d-1ea7-401d-9b41-763acb7e5627.png)

**Comment by iam-veeramalla** [comment]
@plakyda-codefresh Thanks for the issue !! @saumeya or @ciiay  do you think this is a simple fix to consider for the next milestone?

**Comment by plakyda-codefresh** [comment]
@iam-veeramalla I would take this issue

**Comment by rbreeze** [comment]
Hi @plakyda-codefresh, thanks for pointing this out. You’re more than welcome to fix this standalone, but as a heads up, I currently have a PR that will relocate filters and the `Show Orphaned` checkbox, so this will be fixed in that PR: 

https://github.com/argoproj/argo-cd/pull/6966

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/7082
