### ISSUE TITLE
Is it possible to pass a list on ApplicationSet file generator?

### ISSUE THREAD

**Issue by AndresJulia** [argoproj/argo-cd#7086]
I need to pass a list to ApplicationSet file generator, but not sure if it is possible.

```
{
  "app": {
    "test": ["a", "b", "c", "d"],
  }
}

```
When i pass that, the Application wont recognize {{app.test}}.

**Comment by iam-veeramalla** [comment]
Hi @AndresJulia I know that there is a matrix generator where you can use child generators
https://argocd-applicationset.readthedocs.io/en/stable/Generators-Matrix/

cc: @jgwest

**Comment by blakepettersson** [comment]
Closing, if there's a good reason to re-open this issue let me know 😄
