### ISSUE TITLE
UI pollutes browser location history

### ISSUE THREAD

**Issue by warmfusion** [argoproj/argo-cd#7090]
We recently upgraded to ArgoCD v2.1.0+d0b2d55 and have noticed that when browsing the UI the history in Firefox gets really polluted when changing pages.

## Steps to reproduce;

1. Open a new browser tab
2. Navigate to ArgoCD
3. Long-press back button on browser

## Expected
- A single entry for ArgoCD

## Actual

History contains 15 separate entries for the same URI, preventing the back button being functional in any real term

![image](https://user-images.githubusercontent.com/2294568/130940123-27ab965e-eccd-4833-816b-71890416a541.png)

This issue also manifests when;

- side-scrolling wide application views
- clicking any element inside a viewport

**Comment by tylerauerbeck** [comment]
@alexmt I'd be happy to give this an update. For some clarity though, is it just updating `navigation.goto` calls with this parameter within this file? Or would this be across the board within the ui?

**Comment by alexmt** [comment]
Thank you @tylerauerbeck ! I was thinking across the board. In particular, code that opens/closes sliding panels on applications list and application details pages. I think this is the main contributor that pollutes history.

**Comment by keithchong** [comment]
Hi @alexmt, @pasha-codefresh , when clicking on the views, eg. Tree, Node, or List view in the details page, then clicking Back button on the browser will bring you back to the Application List page.  Before, it would just go back to the different view page that you had visited. I thought that was helpful.
