### ISSUE TITLE
in ArgoCD 2.1.1 Parameters shown in ArgoCD UI for helm based applications do not match parameters used

### ISSUE THREAD

**Issue by patrickhuy** [argoproj/argo-cd#7099]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Since ArgoCD 2.1 it seems like the parameters shown in the ArgoUI do not match the actual parameters used for templating helm charts. I'm deploying the same helm chart with multiple values files as multiple applications to different clusters and the UI shows parameters from unrelated values files. It seems like actual templating is using the correct values (as it does not template the helm charts with the incorrect values)

**To Reproduce**

Create multiple ArgoCD applications all referencing the same helm chart from the same git repository but configure different valueFiles for each.
For each app the UI will correctly show the selected valueFiles not it will show parameters derived from different valueFiles.

**Expected behavior**

Parameters from the correct value files are shown

**Version**

```shell
argocd: v2.1.1+aab9542
  BuildDate: 2021-08-25T15:12:04Z
  GitCommit: aab9542f8b3354f0940945c4295b67622f0af296
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.1.1+aab9542
  BuildDate: 2021-08-25T15:12:04Z
  GitCommit: aab9542f8b3354f0940945c4295b67622f0af296
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```

**Comment by todaywasawesome** [comment]
Do you mind sharing the screenshots along with the output of helm template on the relevant repos?

**Comment by patrickhuy** [comment]
It can be reproduced with a trivial helm chart like this one: https://github.com/patrickhuy/argocdui/tree/master/simple

this application uses values-a.yaml but testValueNotInValues shows "b": `nameOverride` shows empty which is the value specified in `values.yaml`, both `values-a` and `values-b` change it's value.
![image](https://user-images.githubusercontent.com/66731536/131634387-29aa7916-0968-4654-bc67-2c316357d069.png)

it however templates correctly:
![image](https://user-images.githubusercontent.com/66731536/131634505-249ab003-a4c3-490d-aeb5-d73cf2961506.png)
![image](https://user-images.githubusercontent.com/66731536/131634460-f59f0315-c3de-4beb-b6d1-25a2313c123d.png)

**Comment by Atoms** [comment]
I had this issue also on 2.0.x thought some bug in that version, now I see that it's still on 2.1 also.

When you add helm chart from git repo and want to use values file, previously it was suggesting names for values files, now it does not suggest, and when you enter manually, it's not saved to application manifest, as a workaround you can edit application manifest and add valueFiles manually. this is very inconvenient.

I have no possibility to test now, but it started at a time when I started to use subfolders in the repo for applications. When there was one level of folders for applications it was working fine, maybe this gives some clue...
