### ISSUE TITLE
Allow users to disable deletion for specific objects when application is cascade-deleted

### ISSUE THREAD

**Issue by mvazquezc** [argoproj/argo-cd#7124]
# Summary

Add a new sync option that allows users to disable deletion for specific objects when the application is cascade-deleted.

This will be useful when running patches through Argo CD on objects such as nodes, oauth configs, etc. without this option if the app gets deleted with cascade deletion enabled those objects are deleted.

# Motivation

I need to add a label to a node, I add that label in a yaml file on my repo. Argo CD reads the file and patches the node object adding this new label. Then I delete my Argo CD application with cascade deletion and my node object is deleted. I'd like to have a sync option to disable the deletion for specific objects that I don't want to be deleted on cascade.

# Proposal

Add a new sync-option "Delete=false" that gets checked before deleting the object, if it's found then the object deletion is skipped.

**Comment by jannfis** [comment]
We do have sync option `Prune=false` already. Have you tested using that?

**Comment by mvazquezc** [comment]
> We do have sync option `Prune=false` already. Have you tested using that?

Yes. Prune false works as expected when you delete content from Git and you don’t want it to be deleted from the cluster. In this case we need that when deleting the app, I tested deleting the app with prune=false and the patched content was deleted as well. Am I missing anything?

**Comment by ceesgeene** [comment]
This would be a useful option to allow PersistentVolumeClaims (and the PersistentVolume they are bound to) to survive the temporary deletion of their ArgoCD application that is subsequently be recreated.

**Comment by chary1112004** [comment]
@jannfis I have tested then pvc is still deleted even add annotation as below:

metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false

![image](https://user-images.githubusercontent.com/76929085/217793627-5ddc48e3-23d4-444f-ae6b-06efe7b7946b.png)

Any solution to resolve this issue would be very much appreciated.

Thanks!
