### ISSUE TITLE
Tooltips run up into top bar

### ISSUE THREAD

**Issue by reginapizza** [argoproj/argo-cd#7146]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
The tooltips on application tiles will persist even when the tile is not visible. It will run up over the top bar. 

**To Reproduce**

See video for visual example but basically hover over anything with a tooltip on the application tiles and then scroll up

**Expected behavior**
Would expect tooltips to disappear once their associated component is out of view.

**Screenshots**

https://user-images.githubusercontent.com/50851526/131893632-daa52375-f48f-49cf-8671-3089f1dddf34.mp4

**Version**
v2.2.0+9025318

**Comment by duyngle** [comment]
Can I work on this bug @mayzhang2000

**Comment by alexmt** [comment]
Sure, Thank you @duyngle !
