### ISSUE TITLE
Cant Add Cluster Ipv6

### ISSUE THREAD

**Issue by kimkybuom123** [argoproj/argo-cd#7154]
WARNING: This will create a service account `argocd-manager` on the cluster referenced by context `kubernetes-admin@kubernetes` with full cluster level admin privileges. Do you want to continue [y/N]? yes
INFO[0004] ServiceAccount "argocd-manager" already exists in namespace "kube-system" 
INFO[0004] ClusterRole "argocd-manager-role" updated    
INFO[0005] ClusterRoleBinding "argocd-manager-role-binding" updated 
WARN[0011] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
FATA[0012] rpc error: code = Unknown desc = Get "https://****:6443/version?timeout=32s": dial tcp [2403:bf40::1:0:32]:6443: connect: network is unreachable 
thanhtruc@thanhtruc-Nitro

I depoy cluster on control plane dns ipv6 on VM cloud . And when i add cluster into my argocd local`s , the network is unreachable . I can loggin cluster from local but argocd is unreachable .
What the happen ? thanks

**Comment by jopit** [comment]
What version of argocd are you using?

**Comment by kimkybuom123** [comment]
> What version of argocd are you using?

argocd-server version : 2.0.4
argocd cli : 2.1.1
