### ISSUE TITLE
Fail application sync if it creates resource already managed by another Application CRD

### ISSUE THREAD

**Issue by lsolovey** [argoproj/argo-cd#7156]
# Summary

Provide a way to fail Argo CD application sync if it creates resource with the same `namespace/name/type` as already created by another Application. 

Current behavior is that the last app being synced actually "wins", resource is being overwritten, and another app (which was synced before) gets `SharedResourceWarning`.

# Motivation

Current Argo CD behavior (proceeding with sync) is opposite from the Helm behavior. Helm actually fails with the following error (as example) if one release tries to overwrite resource from another release:

`ConfigMap "..." in namespace "..." exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "...": current value is "...."`

As we deploy Helm charts through Argo CD, we'd like to observe similar behavior as if we used pure Helm directly.

# Proposal

Provide new setting on the Application CRD to enforce shared resources condition as error, rather than warning.

# Side note 

I discussed this issue in Argo CD slack channel, and got suggestion to implement the check for name-uniqueness as part of the PR checks. However I still want to open this Enhancement proposal to gather wider community feedback. 

Personally I think there should be a way to match original Helm behavior (error out) in Argo CD.

**Comment by alexmt** [comment]
The logic that detects resources managed by another namespace already exists here: 

https://github.com/argoproj/argo-cd/blob/eb70a1e3fa4ffc7e479b75415217e62aa637ecc7/controller/state.go#L473

I think it makes sense to use `SyncOptions` to prevent syncing when `ApplicationConditionSharedResourceWarning` is detected.

https://github.com/argoproj/argo-cd/blob/eb70a1e3fa4ffc7e479b75415217e62aa637ecc7/pkg/apis/application/v1alpha1/types.go#L644

**Comment by strantalis** [comment]
I can take this enhancement on if it still needs someone to work on it.
