### ISSUE TITLE
Message on Synced -> More field popping out

### ISSUE THREAD

**Issue by karthikvijayan3** [argoproj/argo-cd#7158]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

*[ *] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ *] I've included steps to reproduce the bug.
* [ *] I've pasted the output of `argocd version`.

**Describe the bug**
1. Message content not get wrapped into More box
2. We are providing link to the code change in commit message. Currently the link in the message not clickable, is it possible to make it clickable?

**To Reproduce**

Commit message with more than 100 or 200 words.

**Expected behavior**

Message should be wrapped in the white box and link inside the commit message should be clickable.

**Screenshots**
![image](https://user-images.githubusercontent.com/22365154/132067585-177ab5ef-e87c-41dd-9b24-6cc2cffbf372.png)

**Version**

```shell
v2.1.2+7af9dfb
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by saumeya** [comment]
I'll try to reproduce and fix this
