### ISSUE TITLE
Is argocd-util deprecated in docker image?

### ISSUE THREAD

**Issue by rayshoo** [argoproj/argo-cd#7170]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**
```sh
$ argocd version | grep server
argocd-server: v2.1.1+aab9542

$ export VERSION=v2.1.1

$ docker run -v ~/.kube:/home/argocd/.kube --rm argoproj/argocd:$VERSION argocd-util -n argocd export > backup.yaml
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "argocd-util": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled 

$ docker run -it -v ~/.kube:/home/argocd/.kube argoproj/argocd:v2.1.1 /bin/bash
$ which argocd-util
there is no stdout
$ exit

$ docker run -it --user root -v ~/.kube:/home/argocd/.kube argoproj/argocd:v2.1.1 /bin/bash
$ find / -name "argocd-util"
there is no stdout
$ exit 

# version 1.0.1 as stated in the documentation have argocd-util but not 2.1.1!
$ docker run -it -v ~/.kube:/home/argocd/.kube argoproj/argocd:v1.0.1 /bin/bash
$ which argocd-util
/usr/local/bin/argocd-util
```
A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**
argocd version 2.1.1 export test

**Screenshots**

I tried this
https://argoproj.github.io/argo-cd/operator-manual/disaster_recovery/
but docker image argoproj/argocd:v2.1.1 seems no have any argocd-util

**Version**
argocd v2.1.1

```shell
Paste the output from `argocd version` here.
argocd: v2.1.2+7af9dfb
  BuildDate: 2021-09-02T18:05:23Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.1.1+aab9542
  BuildDate: 2021-08-25T15:12:04Z
  GitCommit: aab9542f8b3354f0940945c4295b67622f0af296
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0

```

**Logs**

```
$ docker run -v ~/.kube:/home/argocd/.kube --rm argoproj/argocd:$VERSION argocd-util -n argocd export > backup.yaml
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "argocd-util": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled 
```

**Comment by chetan-rns** [comment]
Hi @rayshoo, from v2.1.0 onwards argocd-util commands will be available under `argocd admin`. https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.0-2.1/#the-argocd-util-cli-commands-merged-into-argocd-admin   

Can you please try replacing argocd-util with `argocd admin`? I believe the [disaster recovery docs](https://argoproj.github.io/argo-cd/operator-manual/disaster_recovery/) should be updated to reflect this change

**Comment by rayshoo** [comment]
@chetan-rns Thank you very much! I solved the problem thanks to you. It looks like the docs need to be updated. Good luck and have a nice day!! :)
