### ISSUE TITLE
Cmd+Click on multiple applications opens each application in the same browser tab

### ISSUE THREAD

**Issue by jutley** [argoproj/argo-cd#7192]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I cmd+click multiple applications, a new browser tab is opened for the first application, but each successive application opens in the same browser tab as the first application. Typically, a cmd+click always opens in a brand new tab, and in the case of Argo CD we often want to view multiple applications to compare. The current functionality is surprising and makes this difficult.

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.
1. Go to https://cd.apps.argoproj.io/applications
2. Cmd+click any application to open it in a new tab
3. Go back to the previous tab which lists all applications
4. Cmd+click a different application than in step 2
5. The new application is loaded in the tab from step 2

**Expected behavior**

I would expect multiple cmd+click actions to open each application in its own tab.

**Version**

We are currently running `v2.0.4+0842d44`, though this is also true of the demo Argo CD, which is currently running `v2.2.0+fc49eb2`.

**Comment by oleksandr-codefresh** [comment]
i would take it

**Comment by alexmt** [comment]
Fixed
