### ISSUE TITLE
Enable/Disable auto sync button behavior improvement

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#7197]
**Describe the bug**

The enable/disable autosync button behavior needs an improvement:

* Enable/Disable autosync button click handles does not show error message if API fails to change policy (catch is missing):
https://github.com/argoproj/argo-cd/blob/b37eee1054e42c873699460dd5e2447c2f9fe5a6/ui/src/app/applications/components/application-summary/application-summary.tsx#L320-L327

* By default API server runs expensive, time-consuming validation when the application is updated. This is not required when only sync policy changes. UI can disable it by supplying `validate=false` query parameter.

https://github.com/argoproj/argo-cd/blob/a38f3176e2550ea5f7d82c975e6c57c61058244d/ui/src/app/shared/services/applications-service.ts#L90

**Version**

```shell
v2.1.2
```

**Comment by ThoughtHopper** [comment]
I guess having an error message would help, but if the #3895 Unable to disable auto-sync is a bug, that should be fixed

Thanks
