### ISSUE TITLE
`argocd login` and local ~/.argocd/config for CLI

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#72]
After auth is added, all CLI command will need to be authenticated. This implies we need `argocd login` command which would generate this file in the user's home directory. The credentials would be supplied for future CLI requests.

**Comment by merenbach** [comment]
@jessesuen working on this now.  How long should the credentials be valid? cc @alexmt

**Comment by jessesuen** [comment]
Since the CLI will be needed for automation, I actually don't think it should expire.
