### ISSUE TITLE
UI: Add quick-action buttons to Pod View top level resources

### ISSUE THREAD

**Issue by rbreeze** [argoproj/argo-cd#7208]
In the Application List Tiles view, there are "quick action" buttons to easily refresh, sync, etc. an application: 

<img width="405" alt="Screen Shot 2021-09-13 at 3 50 59 PM" src="https://user-images.githubusercontent.com/6250584/133167153-c4f31df5-a9f9-4436-b4b1-e1583b8d3c26.png">

This could be added to the Pod View so that users do not have to click the "three dots" button to restart a deployment or perform other common actions:

<img width="315" alt="Screen Shot 2021-09-13 at 3 50 24 PM" src="https://user-images.githubusercontent.com/6250584/133167193-19fa5fc7-9b69-4d8e-96ea-ca4709b14320.png">

**Comment by reginapizza** [comment]
I was thinking about maybe trying to work on this...  it seems like most pods ([using this as an example](https://cd.apps.argoproj.io/applications/argo-cd?resource=&view=pods)) only have Details, Delete, and Logs, although I see some of them having up to 5 options (Details, Sync, Delete, Logs, Restart), are you suggesting they all be "quick start" options or just some of them if they're available?

**Comment by rbreeze** [comment]
I was thinking quick actions for the parent / top level resources rather than the pods, as most of these boxes have multiple pods so it would be unclear which pod the action should be applied to. But I do think it would be a good idea to have each menu option be available as a button.

It would be really nice to have one-click access to a Deployment’s logs, or to restart the Deployment, for example.

**Comment by rbreeze** [comment]
Yeah, exactly. We don't need a "Details" button as clicking the header of the white box does this already, but I think a 'Sync', 'Delete', 'Logs', and 'Restart' button are all good to have. If a pod group doesn't have one of these actions available we can just grey it out.

If there's not enough room to include all of these with full text labels, we can probably just use the icon and use a tooltip to show the text.

One last thing - can we use the `ActionButton` component from `argo-ui/v2` for these? Since we're in the process of migrating old buttons anyway

**Comment by reginapizza** [comment]
In that case, does it still make sense to have the dropdown at all? Having the dropdown in addition to something like this seems a little redundant to me

![quick-starts](https://user-images.githubusercontent.com/50851526/134410111-94bb30f2-2aa9-4f90-b541-1c60aba2a266.png)

**Comment by rbreeze** [comment]
Oh, that's a good point. Yeah, if all of the actions fit, let's get rid of the dropdown. Also, could we center all the buttons? If you put them in a flex box, you can just do `justify-content: center`.

Otherwise looks great so far! Thanks
