### ISSUE TITLE
Support customizing name prefix in helm and kustomize

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#721]
User should be able to customize resources name prefix for helm and kustomize apps.

We need to introduce name prefix field in app spec which should be translated into:

* `helm template . --name <prefix>` for helm 
* `kustomize edit set -p nameprefix=<prefix>` for kustomize

**Comment by jessesuen** [comment]
> kustomize edit set -p nameprefix=<prefix> for kustomize

I think you mean:
```
`kustomize edit set nameprefix <prefix>` for kustomize
```
