### ISSUE TITLE
`namespace: undefined` should not say `undefined`

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#7213]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

1. Add a yaml file `ssd-storage-class.yaml`:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
```

to an application and commit it.
2. push
3. wait for argocd to notice the commit
4. visit http://argocd/applications/applications?resource=&conditions=false
5. hover over the ghost & out-of-sync icons
6. look at the namespace

**Expected behavior**

Options:
1. Don't list `namespace:` at all for objects that aren't namespaced
2. use `n/a` instead of `undefined` for objects that aren't namespaced
3. use `(global)` or similar instead of `undefined` for objects that aren't namespaced

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/133295510-035fcd9a-e993-421d-8cff-acb7c15daa68.png)

**Version**

```shell
{
    "Version": "v2.1.0+50b0010",
    "BuildDate": "2021-08-04T00:28:17Z",
    "GitCommit": "50b00104704f28780b320ae043ecbda64214f132",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by duyngle** [comment]
Hi @alexmt , can I work on this bug
