### ISSUE TITLE
Filters should favor matching on short names

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#7214]
# Summary

What change you think needs making.

# Motivation

Entering `sts`, or `pvc` or `cr` or `crd` should filter/highlight matching short names

# Proposal

1. Visit https://cd.apps.argoproj.io/applications/argo-cd?resource=
2. In kinds, enter `svc` or `crd` or `rs` or `cm` or `rb` or `sts`
3. Expect to see first and foremost in the list the item whose shortname corresponds to the entered short form.

# Current behavior

![image](https://user-images.githubusercontent.com/2119212/133299272-773db4b0-6c56-4c88-aed9-a3b27c800124.png)

```
{
    "Version": "v2.2.0+3df6be7",
    "BuildDate": "2021-09-14T05:19:41Z",
    "GitCommit": "3df6be73e79a2cab8a04bf659e1d7e432aa2b60c",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Comment by saumeya** [comment]
Hi @jsoref, I can try taking a look at this
