### ISSUE TITLE
Unable to create Ingress from helm chart

### ISSUE THREAD

**Issue by LarsAC** [argoproj/argo-cd#7216]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using a helm chart for an app, there is an error message `Resource networking.k8s.io:Ingress is not permitted in project xy` 

I have added 

````
  namespaceResourceWhitelist:
  - group: ''
    kind: '*'
  - group: 'apps'
    kind: '*'
````
to my AppProject definition, so had expected Ingress objects to be whitelisted.

**To Reproduce**

Use the declarative approach to create an app that uses helm to create, among others, an Ingress object.

**Expected behavior**

Ingress is created a part of the app.

**Screenshots**

**Version**

```shell
argocd: v2.1.1+aab9542
  BuildDate: 2021-08-25T15:12:04Z
  GitCommit: aab9542f8b3354f0940945c4295b67622f0af296
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.1.1+aab9542
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jannfis** [comment]
I think you might be missing

```
  - group: 'networking.k8s.io'
    kind: 'Ingress'
```
from your list of allowed resources.

**Comment by LarsAC** [comment]
Great, confirmed working. Thanks a lot.

Does the group tag correspond to the namespace ?

Lars

**Comment by jannfis** [comment]
`group` specifies the API group for resources
