### ISSUE TITLE
UI: List view not showing all resource types

### ISSUE THREAD

**Issue by shakaluu** [argoproj/argo-cd#7236]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In the UI choosing the list view to show resources in an application results in a list which shows not all resources in the project. The most prominent resource type missing is "pod". It seems the list view is only showing parent resources.

**To Reproduce**

- Browse ArgoCD UI
- Click on an application
- Choose list view

**Expected behavior**

To see a full list of all deployed resources in this application. In the screenshot you can see an application deployment in the list view instead of the tree view, which is lacking resources. I would expect to find also pod, controllerrevisions, pvcs, ... resources in this list.

![image](https://user-images.githubusercontent.com/5822567/133591799-f5fc6687-f4ad-46f9-9127-ac4d5b3838c7.png)

**Version**

```shell
argocd: v2.1.2+7af9dfb
  BuildDate: 2021-09-02T18:05:23Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

There are no relevant logs for this bug, since it is actually questionable to define this as bug, maybe this could also be an enhancement request.

**Comment by saumeya** [comment]
I'll take a look at this
