### ISSUE TITLE
Diff view shows incorrect base/value comparison

### ISSUE THREAD

**Issue by marcellodesales** [argoproj/argo-cd#725]
# Problem

* The diff view is showing the opposite changed/new value of the current revision in github.

> NOTE: I had pushed a commit --amend between the changes to sync. Not sure if that affected the comparison

# Steps to Reproduce

* Push a new change to the branch an app is sync'ing

<img width="1016" alt="screen shot 2018-10-25 at 10 27 30 am" src="https://user-images.githubusercontent.com/131457/47518840-d7831a00-d840-11e8-851b-9ab622fcdc70.png">

* Go to the ArgoCD related app and click on the resource that was affected
* In the Manifest diff view, look for the changed value

# Observed Behavior

* Went to the view of the Deployment object and the view of the change is reverted

![image](https://user-images.githubusercontent.com/131457/47518877-f5507f00-d840-11e8-94e1-ab78c0e3d595.png)

# Expected behavior

* The diff should be the opposite values for comparison

**Comment by jessesuen** [comment]
Interesting! I agree we should be consistent. Should be simple change to swap the ordering.

**Comment by jessesuen** [comment]
Fixed. I think after https://github.com/argoproj/argo-cd/pull/746 is merged, the UI will get this for free.
