### ISSUE TITLE
Pause/resume action for Deployments

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#7250]
# Summary

Deployments can be paused and resumed (spec.paused). We could create a lua action for Deployments to modify this field.

# Motivation

An action that allows this would remove the kubectl access currently needed for doing this.

# Proposal

Implement the lua script for a pause and resume action for Deployments.

**Comment by ishitasequeira** [comment]
@jessesuen I would like to work on this issue

**Comment by jessesuen** [comment]
Sure!
