### ISSUE TITLE
ui: Add refresh/hard refresh apps button

### ISSUE THREAD

**Issue by servo1x** [argoproj/argo-cd#7256]
# Summary

To have a Refresh/Hard Refresh Apps button next to the Sync Apps button, so multiple apps can be selected to be refreshed.

# Motivation

We frequently run into situations where we have hundreds of apps that need to be refreshed or hard refreshed due to some upstream issue like the repository was not reachable. Currently some users who are heavy web-ui users have to click through each app that needs to be refreshed.

# Proposal

It would be helpful to have a refresh button next to the Sync Apps button, so multiple apps can be refreshed.

**Comment by ciiay** [comment]
I'd like to work on this.
