### ISSUE TITLE
Allow UI Banner to be non-closable or non-dismissible

### ISSUE THREAD

**Issue by keithchong** [argoproj/argo-cd#7261]
# Summary

See original enhancement https://github.com/argoproj/argo-cd/issues/4230

The banner is good for notification type messages and the behaviour now is that the banner can be dismissed and not shown again.  However, those who can edit the argocd-cm could want the banner to be non-dismissible so that the header is permanent.  

# Motivation

It is possible multiple instances of ArgoCD can be deployed to a cluster.  The user could have multiple Argo CD UIs opened. This can be used to easily help identify different Argo CD instances with a banner with unique text. 

# Proposal

The proposal is to add an additional option to hide the "Dismiss for now" and "Don't show again" buttons so the banner is permanent. The default is that if the option is not provided, then the banner is dismissible, like it is now.

If agreed this is acceptable, please assign this to me and I'll work on it.

**Comment by keithchong** [comment]
@alexmt @rbreeze @jannfis, your thoughts?

**Comment by rbreeze** [comment]
I like this idea. I think as long as it is a configurable option in `argocd-cm` and the default is the previous behavior, that works with me. Thanks Keith

**Comment by keithchong** [comment]
The option to position the banner at the top or the bottom will be covered by the issue: https://github.com/argoproj/argo-cd/issues/7313
