### ISSUE TITLE
Application details view performance issue

### ISSUE THREAD

**Issue by pasha-codefresh** [argoproj/argo-cd#7262]
Application details view has issue with CPU consuming

Checklist:

* [X ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Application details consume 100% of CPU.

**To Reproduce**

Go to application details, switch between tabs a few times . 
If you cant reproduce it , try different application

https://cd.apps.argoproj.io/applications/argo-events?resource=&node=argoproj.io%2FApplication%2Fargocd%2Fargo-events%2F0

**Screenshots**

<img width="1675" alt="Снимок экрана 2021-09-20 в 17 14 00" src="https://user-images.githubusercontent.com/39732895/134018066-5b909847-ccd6-41d7-b17a-628494f4a3bc.png">

**Version**

2.2.0

**Comment by plakyda-codefresh** [comment]
I would take it

**Comment by alexmt** [comment]
Fixed. Thank you #oleksandr-codefresh!
