### ISSUE TITLE
Ability to read secrets from a non-argocd specific secret

### ISSUE THREAD

**Issue by aupadh12** [argoproj/argo-cd#7271]
# Summary

Hi Team,

I am using AzureAD based oidc for authentication and logging into ArgoCD which I have deployed in my EKS cluster.
So, I have specific client id and client secret. clinet secret is stored as base64 encoded and is then used in argocd-secret which is then used in argocd-cm.
Now, I am storing all the secrets including the AzureAD one in AWS Secrets manager and encrypting using KMS. Then an external secret is created by name azureAD_client_secret in the same namespace as argocd. 
So, my question is, can I refer to the client secret coming in from this new external secret and mention the same in argocd-cm rather than specifying the client secret in argocd-secret which although base64 encoded will end up on bitbucket or git and can be easily decoded.

# Motivation

We would like to avoid a slightest possibility of secrets or password leakage and that is why we are leveraging AWS Secrets Manager alongwith KMS for encryption.

# Proposal

There should be a way to reference the secrets other than argocd-secret

**Comment by wanghong230** [comment]
argocd-secret is hard coded, so it has to be "argocd-secret" and argocd-secret should never be checked into the repository.

You may explore the solution like a secret-controller to read from KMS and inject the secret data into the argocd-secret instead.

**Comment by alexmt** [comment]
Actually, v2.1 already supported: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#alternative

You can `app.kubernetes.io/part-of: argocd` label to any secret in same namespace where Argo CD is deployed and reference key from it using `$<secret-name>:<key>`
