### ISSUE TITLE
ArgoCD Controller UI Refresh Gets stuck at random times

### ISSUE THREAD

**Issue by iaditya0375** [argoproj/argo-cd#7273]
Checklist:

* [ yes ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ yes ] I've included steps to reproduce the bug.
* [ yes ] I've pasted the output of `argocd version`.

**Describe the bug**

We have been using the ArgoCD for over a year now with version v1.5.8. And sometimes what we see is that when we try to view any app on argo UI, it takes a lot of time to load and after we remove focus from the open window, it can be seen that the Refresh button is stuck. With this, as we try to view any other app on the UI, all of them start getting stuck.

In order to fix the issue, we kill the argocd controller pod and then it is observed to fix the issue.

**To Reproduce**

There is no concise way to reproduce this issue, as it has been happening at random times.

**Expected behavior**

The app should load its manifest and not get in stuck state.

**Screenshots**

![image](https://user-images.githubusercontent.com/91144473/134203798-1a113d34-5c2b-41a4-bb21-674cd8d81b6a.png)

**Version**

Version of ArgoCD in use : v1.5.8

**Logs**

No relevant logs present as of now

**Comment by wanghong230** [comment]
v1.5.8 is quite an old version. We have spent quite some time addressing issues. Maybe consider moving to the latest stable version.
