### ISSUE TITLE
core-install.yaml always refers to latest argocd image

### ISSUE THREAD

**Issue by fedorlitau** [argoproj/argo-cd#7278]
Hi,

when getting the `install.yaml` for a specific version, we get expected behavior:

```console
$ curl -s https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.2/manifests/install.yaml | grep image:
        image: ghcr.io/dexidp/dex:v2.27.0
        image: quay.io/argoproj/argocd:v2.1.2
        image: redis:6.2.4-alpine
        image: quay.io/argoproj/argocd:v2.1.2
        image: quay.io/argoproj/argocd:v2.1.2
        image: quay.io/argoproj/argocd:v2.1.2
```

For `.../argo-cd/v2.1.2/manifests/...` we get `image: ... v2.1.2`

when getting the `core-install.yaml` for a specific version, we always the the `latest` image tag:

```console
$ curl -s https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.2/manifests/core-install.yaml | grep image:
        image: redis:6.2.4-alpine
        image: quay.io/argoproj/argocd:latest
        image: quay.io/argoproj/argocd:latest
```

Does it need to be corrected?

**Comment by alexmt** [comment]
ops, sorry @ishitasequeira . I noticed that you've assignedthe issue too late. Created PR that fixes the problem: https://github.com/argoproj/argo-cd/issues/7278
