### ISSUE TITLE
Migrate to helm 3.7.0

### ISSUE THREAD

**Issue by sergeyshaykhullin** [argoproj/argo-cd#7318]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Helm 3.7.0 change/rename some commands. Now argo cd is not working with new oci images generated with helm 3.7.0

**To Reproduce**
1. Package and push oci image with helm 3.7.0. Example https://github.com/appany/helm-oci-chart-releaser/blob/bab2336e72a9e42cd69d99f3a8be4831b24100e3/action.yaml#L42
2. Add repo, credentials, enable oci support. Example https://github.com/appany/helm-oci-chart-releaser#argocd
3. Add application with oci helm chart
3. Go to argo cd ui

**Expected behavior**
```
helm pull ghcr.io/appany/some-tag:0.1.0
```

**Version**

```
{
    "Version": "v2.1.2+7af9dfb",
    "BuildDate": "2021-09-02T18:05:23Z",
    "GitCommit": "7af9dfb3524c13e941ab604e36e49a617fe47d2e",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
rpc error: code = Unknown desc = `helm chart pull ghcr.io/appany/some-tag:0.1.0` failed exit status 1: Error: manifest does not contain a layer with mediatype application/tar+gzip
```

**Additional info**
Related to https://github.com/appany/helm-oci-chart-releaser/issues/4

**Comment by KlavsKlavsen** [comment]
And we need Helm 3.7.0 to atleast partially mitigate the constand helm cache failure on "2 operations on one runner-pod" - https://github.com/argoproj/argo-cd/issues/5107#issuecomment-933145692

**Comment by sathieu** [comment]
Done in #7249?

**Comment by KlavsKlavsen** [comment]
It would seem so - looking forward to that release :)
