### ISSUE TITLE
Failed to edit argocd application because retry options are empty

### ISSUE THREAD

**Issue by pasha-codefresh** [argoproj/argo-cd#7320]
Failed to edit argocd application because retry options are empty
My recommendation add checkbox in same way as we are doing inside sync panel

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

<img width="1321" alt="Снимок экрана 2021-09-29 в 19 54 51" src="https://user-images.githubusercontent.com/39732895/135314460-4127fd42-d2d8-41f8-9e33-ff071ef5c7d0.png">

**Version**
argocd version` here.

2.2.0

**Logs**

```
Paste any relevant application logs here.
```

**Comment by plakyda-codefresh** [comment]
I would take it
