### ISSUE TITLE
External Secret Sync failure

### ISSUE THREAD

**Issue by joaomo** [argoproj/argo-cd#7324]
Every time an external secret is in a failed state it prevents ArgoCD from doing a sync of changes and requires a delete of the resource. 

This behavior was reported here: https://www.gitmemory.com/issue/argoproj/argo-cd/6039/821598989

**Comment by jessesuen** [comment]
The error:

```
ComparisonError
<string>:6: attempt to index a non-table object(string) with key 'find' stack traceback: <string>:6: in main chunk [G]: ?
```

is from this health check:
