### ISSUE TITLE
Kubernetes Warning events should show up in yellow(?) - not red

### ISSUE THREAD

**Issue by mikebryant** [argoproj/argo-cd#7325]
# Summary

Events should show the type (Warning, Error) and use a different colour for warnings

# Motivation

One of our users was confused today on the events tab for a resource. We have some policy warnings from Kyverno showing up, and it's not clear that they're warnings rather than a reason something failed

![Screenshot 2021-09-30 at 11 16 40](https://user-images.githubusercontent.com/1478103/135437383-1c89c945-c4f9-4af9-8869-dd717dd0f65f.png)

# Proposal

Add a new column for event type, and new colour for warnings

**Comment by jessesuen** [comment]
There are only two possible colors since Kubernetes Events can only be either `Warning` or `Normal`. If there was a third level (e.g. `Error`) then I would agree. But since there are other things like CrashLoopBackoff categorized as `Warning`, we need to convey this sense of urgency.

**Comment by mikebryant** [comment]
Oh, I didn't realise this. Makes sense, sorry for wasting your time
