### ISSUE TITLE
`wait` must throw an error if application deployment failed

### ISSUE THREAD

**Issue by bappr** [argoproj/argo-cd#733]
`argocd wait` don't throw error if application deployment failed
-> forever loop

**Comment by jessesuen** [comment]
So `argocd wait` has a --timeout option which limits the time the wait command will run for. 

In some ways, you can think of this similar to k8s deployment.spec.ProgressDeadlineSeconds but at the CLI / application level. Would `--timeout` solve your use case?

**Comment by bappr** [comment]
Unfortunately no. :-/
Cause the deployment actually really fails so I don't want to wait for the timeout. I would expect the same behaviour as `helm` or `argo ... --wait`.
I ll deal with the `--timeout` for the moment (already configured) but it s annoying.

**Comment by alexmt** [comment]
I agree. `argocd wait` should fail in application reaches Degraded state

**Comment by jessesuen** [comment]
It's possible for an app to be in a Degraded state to begin with, and a `argocd app wait` was called to wait until the app returns healthy (e.g. `argocd app sync myapp && argocd app wait myapp`). What should the behavior be in this scenario?

**Comment by bappr** [comment]
@jessesuen I agree but the problem here is that you can find errors (any type of error, easiest one is `namespace not found`) in the deployment in the argocd ui but the `argocd app wait myapp` is still running.

**Comment by jessesuen** [comment]
I think the heuristic should be: if the health of the deployment **transitions** from a Progressing state to Degraded, then it is safe to fail earlier than the CLI timeout. However in the case where `argocd wait` is called against an app which is already degraded to begin with, then it would wait until the CLI timeout is reached.
