### ISSUE TITLE
Compact application resources tree

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#7349]
# Summary

Introduce an ability to collapse leaf resources nodes into one node on the application resource details page.

# Motivation

The large application might contain dozens of resources. The resource tree view might be hard to use with such applications. User should be able to switch to compact view as described below:

# Proposal

Once compact view is enabled leaf (node without children) nodes of the same kind that belong to the same parent should be collapsed into group node. The example below demonstrates sample application:

``` 
app
├── config-map1
├── config-map2
├── deploy1
│   ├── rs1
│   ├── rs2
│   └── rs3
│       ├── pod1
│       ├── pod2
│       └── pod3
└── deploy2
    ├── rs1
    ├── rs2
    └── rs3
        ├── pod1
        ├── pod2
        └── pod3
```

Once the compact mode is enabled the tree should be changed as following (g - means grouped node):

```
app
├── config-map (g)
├── deploy1
│   ├── rs (g)
│   └── rs3
│       └── pod (g)
└── deploy2
    ├── rs (g)
    └── rs3
        └── pod (g)
```

The user shuold be able to click on group node and see the list of nodes that belong to the group. The list should be displayed in a sliding panel.

**Comment by ciiay** [comment]
I'd like to work on this.

**Comment by ciiay** [comment]
Do we have an icon candidate for the compact view button?

**Comment by ciiay** [comment]
Hi @alexmt , I created a collapsed resources display as the below screenshots. Does this look right to you? And what kind of information is expected to show in the sliding panel for collapsed resources?
Before collapse (Tree view)
![Tree view](https://user-images.githubusercontent.com/26255262/137804543-43132a71-b32d-4835-9774-b0cb16236ebd.png)
After collapse (Compact view)
![Compact view](https://user-images.githubusercontent.com/26255262/137804631-cbc38cc2-59f3-470c-8a73-c8e02788a4c1.png)
