### ISSUE TITLE
Merge Argo CD Notifications into Argo CD

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#7350]
# Summary

Merge Argo CD Notifications into Argo CD

# Motivation

The https://github.com/argoproj-labs/argocd-notifications became a thin wrapper around https://github.com/argoproj/notifications-engine. In order to improve user experience the notifications controller should
be added directly into Argo CD.

# Proposal

Similar to Argo Rollouts the ArgoCD Notifications should be controlled by the separate ConfigMap and a Secret. The main difference is that controller code should be merged into Argo CD controller so that user don't have to install it separatly.

**Comment by pasha-codefresh** [comment]
Done: https://github.com/argoproj/argo-cd/pull/7744

**Comment by james-callahan** [comment]
This merged in the basic notifications component; but not the bot (code at https://github.com/argoproj-labs/argocd-notifications/blob/d34f62998ceb9d03bbedcb65d95e798ed59de5e8/cmd/bot.go)

How can we allow slack users to manage their own subscriptions?

**Comment by mkilchhofer** [comment]
> This merged in the basic notifications component; but not the bot (code at https://github.com/argoproj-labs/argocd-notifications/blob/d34f62998ceb9d03bbedcb65d95e798ed59de5e8/cmd/bot.go)
> 
> How can we allow slack users to manage their own subscriptions?

Created dedicated issue for that: 
- #9869
