### ISSUE TITLE
docs: Getting Started: Login Using CLI. Add `echo` to avoid printing `%`

### ISSUE THREAD

**Issue by mustafa89** [argoproj/argo-cd#7355]
# Summary

A very minor change. I would like to update the getting started documentation. 

# Motivation

So that the '%' is not printed at the end of the secret (due to missing newline) and makes copying easy.

# Proposal

How do you think this should be implemented?

Append an `echo` after the `kubectl` command.
here: https://argo-cd.readthedocs.io/en/stable/getting_started/#4-login-using-the-cli

```bash
kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
```

**Comment by chetan-rns** [comment]
Fixed by PR #7403
