### ISSUE TITLE
Failing repo after argocd upgrade from v2.0.1 to 2.1.3

### ISSUE THREAD

**Issue by ArsenyBelorukov** [argoproj/argo-cd#7369]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Some private repo doesn't work after upgrading argocd from v2.0.1 to 2.1.3.

Adding repo via argocd cli:
```
argocd repo add git@reposerver.service.msk.consul:k8sdeployments.git  --name k8sdeploy --type git --ssh-private-key-path ./key
FATA[0003] rpc error: code = Unknown desc = repository not found
```
argocd-repo-server log:
`{"error":"repository not found","grpc.code":"Unknown","grpc.method":"TestRepository","grpc.request.deadline":"2021-10-04T14:52:04Z","grpc.service":"repository.RepoServerService","grpc.start_time":"2021-10-04T14:51:05Z","grpc.time_ms":20.457,"level":"error","msg":"finished unary call with code Unknown","span.kind":"server","system":"grpc","time":"2021-10-04T14:51:05Z"}`

In case if the repo is set via secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: k8sdeploymentsold
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@reposerver.service.msk.consul:k8sdeployments
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
.....
```
Argocd web UI  shows ‘failed’ status.
Argocd cli util shows:
```
argocd repo list
TYPE  NAME  REPO                                                INSECURE  OCI    LFS    CREDS  STATUS      MESSAGE
git         git@reposerver.service.msk.consul:k8sdeployments    false     false  false  false  Failed      Unable to connect to repository: rpc error: code = Unknown desc = parse "git@reposerver.service.msk.consul:k8sdeployments": first path segment in URL cannot contain colon
git         git@github.XXXX.dev:services/k8s-infrastructure.git  false     false  false  false  Successful
```

**To Reproduce**

Add repo, that is provided via ssh (?)

**Expected behavior**

Repository works correctly and has 'Successful' status

**Version**

```shell
argocd version
argocd: v2.1.3+d855831.dirty
  BuildDate: 2021-09-30T22:11:24Z
  GitCommit: d855831540e51d8a90b1006d2eb9f49ab1b088af
  GitTreeState: dirty
  GoVersion: go1.17.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.3+d855831
  BuildDate: 2021-09-29T21:51:21Z
  GitCommit: d855831540e51d8a90b1006d2eb9f49ab1b088af
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```

**Logs**

```
{"error":"repository not found","grpc.code":"Unknown","grpc.method":"TestRepository","grpc.request.deadline":"2021-10-04T14:52:04Z","grpc.service":"repository.RepoServerService","grpc.start_time":"2021-10-04T14:51:05Z","grpc.time_ms":20.457,"level":"error","msg":"finished unary call with code Unknown","span.kind":"server","system":"grpc","time":"2021-10-04T14:51:05Z"}
```

**Comment by leoluz** [comment]
@ArsenyBelorukov can you please confirm that when you create the repo via secret that you have the key `type` defined? I was able to reproduce the error with message `first path segment in URL cannot contain colon` if the secret doesn't have the  `type` attribute.

The `repository not found` error is returned by the git library that we use in ArgoCD. It seems that this repo is not reachable from where ArgoCD is deployed.
