### ISSUE TITLE
Application conditions should have timestamp

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#737]
Application conditions should have the timestamp. Timestamp should be visible in CLI output and UI

**Comment by alexec** [comment]
![Screen Shot 2019-03-21 at 10 55 56](https://user-images.githubusercontent.com/1142830/54773958-eab7cd00-4bc7-11e9-8ecd-84654f4597ae.png)

**Comment by alexec** [comment]
@alexmt did you fix this?

**Comment by alexmt** [comment]
It is fixed, but that was not me. Thanks to @dgoodwin for implementing it!
