### ISSUE TITLE
Get git-sha of application git repository

### ISSUE THREAD

**Issue by epa095** [argoproj/argo-cd#740]
We are deploying some resources using ksonnet and Argo-CD, and would like to know if it is possible to have Argo-CD expose the git revision of the application git repository to ksonnet (and as such the app being deployed)? We would like to include this git-sha in some metadata being produced by the app itself.

**Comment by marcellodesales** [comment]
@epa095 I'd like the same functionality. All applications should show that's sync, but we don't know exactly which revision.

**Comment by alexmt** [comment]
Fixed

**Comment by alexmt** [comment]
Sorry, closed it by mistake

**Comment by jessesuen** [comment]
This should be fixed. We now display the revision in which the app has been compared to:

![image](https://user-images.githubusercontent.com/12677113/54877712-385a5280-4ddf-11e9-9f13-21461bd7c3c2.png)

![image](https://user-images.githubusercontent.com/12677113/54877715-51fb9a00-4ddf-11e9-9e1d-fd4753e4bcab.png)

As well as the revision it was last synced to in the application history:

![image](https://user-images.githubusercontent.com/12677113/54877755-14e3d780-4de0-11e9-8ce8-63c6a5ce389e.png)
