### ISSUE TITLE
argocd-repo-server problem with istio 

### ISSUE THREAD

**Issue by slawekgh** [argoproj/argo-cd#7425]
* [YES ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ YES] I've included steps to reproduce the bug.
* [ YES] I've pasted the output of `argocd version`.

```
$ argocd version
argocd: v2.1.1+aab9542
  BuildDate: 2021-08-25T15:12:04Z
  GitCommit: aab9542f8b3354f0940945c4295b67622f0af296
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
```

Namespace = argocd 

istio auto-injection turned-on NS=argocd

argocd PODS are running except argocd-repo-server :

```
-sh-4.2$ kubectl get po
NAME                                 READY   STATUS             RESTARTS   AGE
argocd-application-controller-0      2/2     Running            0          64m
argocd-dex-server-7df97cb6dd-qsldr   2/2     Running            0          64m
argocd-redis-5cb684fdf8-77p7p        2/2     Running            0          64m
argocd-repo-server-dc7c98c-j28n7     0/2     CrashLoopBackOff   17         20m
argocd-server-7dcc49c9bd-g6dfs       2/2     Running            0          64m
```

seems that argocd-reposerver container is starting properly:

```
$ kubectl logs -f argocd-repo-server-dc7c98c-j28n7
time="2021-10-13T08:58:52Z" level=info msg="Initializing GnuPG keyring at /app/config/gpg/keys"
time="2021-10-13T08:58:52Z" level=info msg="gpg --no-permission-warning --logger-fd 1 --batch --generate-key /tmp/gpg-key-recipe788457281" dir= execID=jY8NR
time="2021-10-13T08:58:52Z" level=info msg=Trace args="[gpg --no-permission-warning --logger-fd 1 --batch --generate-key /tmp/gpg-key-recipe788457281]" dir= operation_name="exec gpg" time_ms=196.04948
time="2021-10-13T08:58:52Z" level=info msg="Populating GnuPG keyring with keys from /app/config/gpg/source"
time="2021-10-13T08:58:52Z" level=info msg="gpg --no-permission-warning --list-public-keys" dir= execID=M2ExS
time="2021-10-13T08:58:52Z" level=info msg=Trace args="[gpg --no-permission-warning --list-public-keys]" dir= operation_name="exec gpg" time_ms=6.160423
time="2021-10-13T08:58:52Z" level=info msg="gpg --no-permission-warning -a --export Fxxxxxxxxxxxxxxxxxx" dir= execID=STOmc
time="2021-10-13T08:58:52Z" level=info msg=Trace args="[gpg --no-permission-warning -a --export Fxxxxxxxxxxxxxxxxxx]" dir= operation_name="exec gpg" time_ms=3.8181000000000003
time="2021-10-13T08:58:52Z" level=info msg="gpg-wrapper.sh --no-permission-warning --list-secret-keys Fxxxxxxxxxxxxxxxxxx" dir= execID=yyyyyW
time="2021-10-13T08:58:52Z" level=info msg=Trace args="[gpg-wrapper.sh --no-permission-warning --list-secret-keys Fxxxxxxxxxxxxxxxxxx]" dir= operation_name="exec gpg-wrapper.sh" time_ms=5.878002
time="2021-10-13T08:58:52Z" level=info msg="Loaded 0 (and removed 0) keys from keyring"
time="2021-10-13T08:58:52Z" level=info msg="argocd-repo-server v2.1.1+aab9542 serving on [::]:8081"
time="2021-10-13T08:58:52Z" level=info msg="Starting GPG sync watcher on directory '/app/config/gpg/source'"
```

but corresponding istio-proxy container has a problem :

```
$ kubectl logs -f argocd-repo-server-dc7c98c-j28n7 -c istio-proxy
[...]
2021-10-13T09:03:55.098737Z     info    JWT policy is third-party-jwt
2021-10-13T09:03:55.098744Z     info    Extract GCP metadata from env variable GCP_METADATA: dev-anthos2|xxxx7|beta-provider-test|euYYYY
2021-10-13T09:03:55.163743Z     info    Pilot SAN: [istiod-asm-1102-3.istio-system.svc]
2021-10-13T09:03:55.163787Z     info    CA Endpoint meshca.googleapis.com:443, provider GoogleCA
2021-10-13T09:03:55.163928Z     info    stsserver       Start listening on 127.0.0.1:15463
2021-10-13T09:03:55.164274Z     info    ads     All caches have been synced up in 70.860303ms, marking server ready
2021-10-13T09:03:55.164513Z     info    sds     SDS server for workload certificates started, listening on "./etc/istio/proxy/SDS"
2021-10-13T09:03:55.164543Z     info    xdsproxy        Initializing with upstream address "istiod-asm-1102-3.istio-system.svc:15012" and cluster "xxx.xxxx.yyy"
2021-10-13T09:03:55.164676Z     fatal   Agent start up errorfailed to start xds proxy: failed to build TLS dial option to talk to upstream: open ./var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
```

this problem affects only argocd-repo-server , other PODs are running properly

**Comment by slawekgh** [comment]
+1

**Comment by slawekgh** [comment]
@jannfis thanks a lot 
I made 2 repos - with and without istio - both of them works fine 

one additional info for others - Temporary Redirect during argocd login is not ok for envoy-proxies - there is a need for connecting to IP POD directly and everything works great

**Comment by kf-rammanokar** [comment]
I have resolved this issue by disabling sidecar injection for argocd-repo-service deployment,

```
sidecar.istio.io/inject: "false"

```
[https://istio.io/v1.9/docs/setup/additional-setup/sidecar-injection/#policy:~:text=sidecar.istio.io/inject%3A%20%22false%22](https://istio.io/v1.9/docs/setup/additional-setup/sidecar-injection/#policy:~:text=sidecar.istio.io/inject%3A%20%22false%22 
)

**Comment by slawekgh** [comment]
> I have resolved this issue by disabling sidecar injection for argocd-repo-service deployment,
> 
> ```
> sidecar.istio.io/inject: "false"
> ```
> 
> https://istio.io/v1.9/docs/setup/additional-setup/sidecar-injection/#policy:~:text=sidecar.istio.io/inject%3A%20%22false%22

it is not the solution :-) 
finding similar solutions -  you can also disable istio for the whole cluster and disable argocd and disable the whole cluster

**Comment by kf-rammanokar** [comment]
Hi @slawekgh, yes you can disable the whole cluster, nobody will stop you. 🥇 

Isio sidecar requires a service-account to spin up a pod, but Argocd does not recommend using a service account for repo-server deployment.

The best option for me is to disable "sidecar injection" for Argocd repo server deployment. I have posted here because this may help to someone else who is facing the similar issue.

**Comment by slawekgh** [comment]
this is issue about running argocd with istio 

so solutions like "turn of the istio for argo" doesnt make any sense

**Comment by kf-rammanokar** [comment]
Hi @slawekgh I'm not suggesting to turnoff istio-sidecar for whole arogcd deployment. 
disable sidecar only for **argocd-repo-server**  not for other deployments.

**Comment by tiwarisanjay** [comment]
@slawekgh What is the solution you applied to get the deployment work with istio?

**Comment by tamipangadil** [comment]
> **Hi @slawekgh , yes you can disable the whole cluster, nobody will stop you.** 1st_place_medal
> 
> Istio sidecar requires a service-account to spin up a pod, but Argocd does not recommend using a service account for repo-server deployment.
> 
> The best option for me is to disable "sidecar injection" for Argocd repo server deployment. I have posted here because this may help to someone else who is facing the similar issue.

This solved my issue for fixing our git connection issue which is `Unable to connect to repository: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake`. For now, I can sleep soundly at night after burning my weekend to find this workaround. But I also agree with @slawekgh that just disabling the sidecar is not the solution. ArgoCD is working for us for few years until we upgraded our Istio version to 1.17. This might not be a frequently asked question to ArgoCD team/community but it would be nice if we could have a page that says whether the ArgoCD version is incompatible with those popular service mesh tools like Istio.
