### ISSUE TITLE
BeforeHookCreation fails to delete job resulting in "field is immutable"

### ISSUE THREAD

**Issue by chrisdoherty4** [argoproj/argo-cd#7430]
**Describe the bug**

_I'm looking for feedback initially having had no response in slack. I expect I'll add to the issue gradually as I learn more._

Jobs configured with the default deletion policy of BeforeHookCreation are not deleted correctly resulting in a 'field is immutable' error. The problem occurs ad-hoc making it hard to reproduce so we're working with theories/observations right now.

```
Job.batch "<omitted>" is invalid: spec.template: Invalid value: <omitted>: field is immutable
```

**To Reproduce**

Its difficult to reproduce.

1. Create a job manifest and deploy with ArgoCD.
2. Somehow have the spec.template configuration mutated (we don't fully understand whats happening here so feedback/ideas are welcome).
3. Have ArgoCD attempt to sync the job.
4. Repeat until the error is observed.

**Expected behavior**

Jobs are correctly deleted so they can be recreated on sync.

**Version**

```shell
v1.8.7+eb3d1fb
```

**Logs**

None yet. Just Kubernetes event with the error above.

**Comment by EwdAger** [comment]
sames here

**Comment by chrisdoherty4** [comment]
I could never consistently reproduce this and I don't have bandwidth to look. Closing for now.

**Comment by hyei** [comment]
This looks similar, if not the same as what we have been seeing happening every few syncs. We get the field is immutable error, with what looks like a failure to create the pre-sync hook, which simply sends a slack notification.

**Comment by hyei** [comment]
We worked around this by using generateName for unique job names, so no longer see immutable failures anymore.  However it looks like preSync and syncFail hooks aren't being deleted based on the deletion policy of HooksSucceeded, and we start collecting dangling jobs.

**Comment by 24601** [comment]
@hyei We have a workaround that we are using with relatively good success that works on all versions of kustomize that support namesuffix and Argo. Check out https://github.com/kubernetes-sigs/kustomize/issues/641#issuecomment-1316367513 for details.

We also set the job TTL to avoid dangling jobs, and the hooks to delete are working, too.

**Comment by chrisdoherty4** [comment]
@hyei I recall seeing the same thing. The workarounds @24601 suggest seem like they'd smooth things out but certainly wouldn't fix it :(

**Comment by joshperry** [comment]
For future searchers (and I guess chatgpt), the problem we were having is that the `argocd.argoproj.io/hook` annotation was accidentally added to the podspec instead of the job annotations. If your job is actually running as a hook, it will have an icon in the argo UI.

![image](https://github.com/argoproj/argo-cd/assets/298053/c132b599-95ab-4955-beb0-ddbd4a780c73)
