### ISSUE TITLE
Filter group is cutoff by notification message

### ISSUE THREAD

**Issue by keithchong** [argoproj/argo-cd#7443]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

When the notification banner appears, the filter group isn't shifted down like the other parts of the page.  It is cut off at the top. Not sure if this will be fixed, since the revamped filter is integrated into the sidebar, but opening this bug for the record.  This appears to have been there since the banner was first introduced.

**To Reproduce**

1. Add notification banner
2. See top of filter get chopped off.
3. See screenshot

**Expected behavior**

The top part should not be covered.

**Screenshots**
For example, see https://github.com/argoproj/argo-cd/pull/7264 and https://github.com/argoproj/argo-cd/issues/7261

**Version**
Latest

**Comment by keithchong** [comment]
I opened this for the record, but I think this issue might be moot once this gets merged: https://github.com/argoproj/argo-cd/pull/6966 . FYI, @rbreeze

**Comment by saumeya** [comment]
Hi @keithchong , the PR to address this issue is now closed, should this be solved then?
