### ISSUE TITLE
enhancement: annotation for Force Syncing

### ISSUE THREAD

**Issue by automaticgiant-ml** [argoproj/argo-cd#7459]
i would like to be able to set this on specific manifests rather than everywhere

### Discussed in https://github.com/argoproj/argo-cd/discussions/5172

<div type='discussions-op-text'>

<sup>Originally posted by **rumstead** January  4, 2021</sup>
Hi all! I want to be able to automatically “kubectl apply --force” my Kubernetes manifests so I don't have to force sync via the UI when a label or something immutable changes. I saw the [SyncOptions](https://github.com/argoproj/argo-cd/blob/v1.8.1/pkg/apis/application/v1alpha1/types.go#L590) and tried adding “--force”, “force=true”, and “Force=true” but none seemed to work. I then stumbled across [SyncStrategy](https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L735). I was able to set this on the Application Resource and it seems to work but I want to make sure this is the best way to do it.</div>

**Comment by thesuperzapper** [comment]
I think the best solution is proposed in https://github.com/argoproj/gitops-engine/issues/414, please raise your support there, or help propose the PR!
