### ISSUE TITLE
Declaratively add helm repositories

### ISSUE THREAD

**Issue by amarrella** [argoproj/argo-cd#747]
Hello, I'm facing a problem where one of my `requirements.yaml` is hosted on a non-default repo. 
It would be nice to have a way to add the repo to helm in a declarative way. Currently my argocd deploy fails due to the fact that it needs to execute "helm repo add" :(
Thanks in advance, and thank you for this great project :)

**Comment by jessesuen** [comment]
I think this request makes sense. Question is, is there a way to infer what values to use for `[NAME]` and `[URL]` after `helm repo add`?

If not, one way is that we introduce a helm specific section in the argocd-cm ConfigMap where we hold global helm repo's, urls, and username/passwords as secret references.

This is also relevant to the work we are doing for:
https://github.com/argoproj/argo-cd/issues/536

**Comment by mduarte** [comment]
I don't think there's a way to infer that, but I am not helm specialist :)

The option to introduce a a helm specific section in the argocd-cm ConfigMap seems to me the most declarative and flexible way to implement this.

**Comment by jessesuen** [comment]
The istio helm chart is example of where they use subcharts (in the same repo) and may require repo registration. When trying to create istio from the path: `install/kubernetes/helm/istio`, the application error we get is:

> rpc error: code = Unknown desc = Error: no repository definition for @istio.io. Please add them via ‘helm repo add’

**Comment by jessesuen** [comment]
@alexmt - when using disposable HELM_HOME directories, please initiate the helm dir using the command: `helm init --client-only --skip-refresh`. The `--skip-refresh` flag prevents an attempt to reach out over the network to download the repo index, which is necessary for any users who are using fire-walled networks.
