### ISSUE TITLE
Missing health check for bare Pods and Jobs

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#751]
For Argo CD health checks, we have more or less come to the same health assessments as the "Core Resource Adaptations" described in the proposal here:

https://github.com/kubernetes-sigs/application/issues/78

However, two things which we are missing, is that we do not assess the health of a bare Pods or  ReplicationController. While it's a small use case, we should add those health assessment for completeness.

**Comment by jessesuen** [comment]
Will forgo defunct ReplicationController but add Jobs, now that hooks are visible from UI

**Comment by dthomson25** [comment]
Fixed.
