### ISSUE TITLE
UI should render pending deletion application state

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#752]
Application is deleted asynchronously by the controller. After user click delete application is still available for few seconds. UI should render label/icon which indicates that application is pending deletion.

**Comment by jessesuen** [comment]
This is somewhat related, but I actually want to change the behavior of how apps are deleted. See #636. Basically, I think we should not delete the application object until we know for sure it's associated resources have been deleted. By doing this, we will give users insight on the progress of the deletion.
