### ISSUE TITLE
Add support for Google Cloud Source repositories

### ISSUE THREAD

**Issue by david-becher** [argoproj/argo-cd#7534]
# Summary

This enhancement aims at adding support for Google Cloud Source repositories. There are already a couple of issues (see #3379 and #2814), where the overall consensus was that it is currently not possible or experimental at best. Also, there is no documented and easy to use solution to clone Google Cloud Source repositories.

# Motivation

ArgoCD users with repositories hosted on Google Cloud Source are currently unable to use these repositories with ArgoCD. Adding support for such repositories would allow such users to use ArgoCD as well.

# Proposal

I am proposing support for Google Cloud Service Account credentials in JSON format as part of one of the ArgoCD repository or repository credential secrets, which can be used to create access tokens to clone Google Cloud Source repositories.

I already have a locally tested solution for this. I am planning to refactor a couple of bits, create proper documentation, argocd-cli support, etc. and then to create a PR referencing this enhancement proposal.

**Comment by hixichen** [comment]
can we grant workload identity to argo cd which may allow gcp service account for argo cd to read source repo？

**Comment by eduartua** [comment]
@hixichen Yes you can add Workload Identity but still won't work. I have verified this. Argocd requires a traditional way to authenticate to access the repo. Before running any git command the authentication must be done which so far it only support SSH or User and Passwords (tied to the GCP user).

**Comment by narutolied** [comment]
you can access the Source repositories through https. You just need to click on the 3. tab and generate a git cookie. Just look through it. You can find user and password inside and connect via that.

**Comment by david-becher** [comment]
The git cookie is only valid for 60 minutes however. I guess you will have something more permanent. That's the reason for this PR

**Comment by narutolied** [comment]
are you sure about that ? i connected a repo yesterday and it is still syncing

**Comment by hixichen** [comment]
I am so excited to see this change got merged. 

@david-becher  Great work!

**Comment by crenshaw-dev** [comment]
That was all @alexef on the rewrite. Thanks for the work, glad we could finally get it done!
