### ISSUE TITLE
Helm: argocd app set appname -p variable=value -> fails due to ksonnet validation

### ISSUE THREAD

**Issue by runonautomation** [argoproj/argo-cd#756]
Helm: argocd app set appname -p variable=vaule fails due to ksonnet validation
```
argocd app set appname -p variable=value
```
This documentation references that it is possible for helm.
https://argoproj.github.io/docs/argo-cd/docs/application_sources.html

However the result is:
```
FATA[0000] Expected ksonnet parameter of the form: component=param=value. Received: image.tag=latest
```
Which indicates it tries to interpret the parameter in ksonnet format.

```
argocd: v0.10.4+89ece31
  BuildDate: 2018-11-08T01:59:55Z
  GitCommit: 89ece317624db92907f305dab32ddde7e40b92de
  GitTreeState: clean
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v0.10.3+c5814d5
  BuildDate: 2018-10-29T06:38:40Z
  GitCommit: c5814d5946c265eb72ff8d8281bc65d0cc288c4d
  GitTreeState: clean
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.0
```

**Comment by jessesuen** [comment]
Argo CD is mistaking your app as a ksonnet app. Do you happen to have a file called app.yaml in the directory?

**Comment by jessesuen** [comment]
Actually I understand why. The CLI is assuming your app is a ksonnet app because it has an "environment" field set. `--env` is a ksonnet specific setting.

If you run:
```bash
argocd app set <appname> --env ""
```

It should fix things.

**Comment by runonautomation** [comment]
Sorry for late reply.

I reproduced to confirm your idea:
```
argocd app set testapp --env "dev"
argocd app set testapp -p variable=value -->ERROR!!!
FATA[0000] Expected ksonnet parameter of the form: component=param=value. Received: variable=value
argocd app set testapp --env ""
WARN[0000] Parameter variable in  does not exist in ksonnet, parameter override dropped
cloudshell:~/argocd $ argocd app set testapp -p variable=value --> SUCCESS!!!
```
It was a bit unclear that when using helm env field must not be set.

Thanks a lot!

**Comment by runonautomation** [comment]
Issue is resolved. The proposed solution works.
