### ISSUE TITLE
Unclear error messages in Sync result and app conditions

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#757]
If argocd fails to generate yaml using `ks show`, `helm template` etc then error message has only templating tool output, without explanation that happened.

It is unclear to the user that output is from templating tool and not internal argocd error.

**Comment by OmerKahani** [comment]
Hi just want to add:

I added a new application and got this screen:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/8766193/59277809-7f7f1380-8c69-11e9-8b1d-1869f9402c5e.png">

in the logs of "argocd-repo-server" I found:
"helm dependency build` failed: Error: Can't get a valid version for repositories ****. Try changing the version constraint in requirements.yaml\n"

This error should be in the UI

**Comment by alexec** [comment]
Fixed in v1.2
