### ISSUE TITLE
Ability to disable https://kubernetes.default.svc

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#7571]
# Summary

Many users run Argo CD in a mode where that Argo CD instance doesn't ever need or want to deploy Applications to the same cluster Argo CD is running in (e.g. Intuit does this). For these users, the `https://kubernetes.default.svc` should be disabled and removed as an option. 

# Motivation

The ability to disable https://kubernetes.default.svc is both a security improvement as well as usability improvement since end-users do not see cluster which they cannot use.

# Proposal

Argo CD should have an option to disable https://kubernetes.default.svc as a managed cluster so that it becomes impossible to deploy to.

**Comment by jessesuen** [comment]
Changes probably needed here:
https://github.com/argoproj/argo-cd/blob/fe3cc7218caf18276dd6864198783c2ff7c9b064/util/db/cluster.go#L55-L79

**Comment by pixelsoccupied** [comment]
Hi there, to reiterate -- if the user provides `https://kubernetes.default.svc` with `.spec.destination.server` or with cli `--dest-server https://kubernetes.default.svc` we would need to check need if there's a (new?) flag present before we proceed. If there's no flag just go on with the usual flow else log an error? 

Could you talk a bit more about this flag/option to disable `https://kubernetes.default.svc`? Would the the user provide it during installation only? Or would there be a UI/CR/CLI/post-installation way as well? What would the flag be called?

**Comment by terrytangyuan** [comment]
@pixelsoccupied This will be a new key in ArgoCD ConfigMap so you can update it on the fly as well.

**Comment by terrytangyuan** [comment]
I created a draft PR in #7620. Feel free to leave your feedback there.

**Comment by agaudreault** [comment]
This does not seem to prevent Application from being created using this cluster. The only thing it is doing iis hiding the cluster from the list of available clusters. https://github.com/argoproj/argo-cd/issues/21207
