### ISSUE TITLE
Telepresence support

### ISSUE THREAD

**Issue by itziklavon** [argoproj/argo-cd#7584]
I don't know if it is actually a bug, or feature, or maybe i'm doing something wrong
the issue is as following:
i would like to intercept workload in specific namesapce using telepresence to enable live debugging
when app is being deployed with argo, interception is not working (argo manifest is being changed to tm-XXXX)
when doing the same after deploying manually the application, interception do work, and i'm able to debug application locally

argo version: v1.8.4+28aea3d
telepresence version: 2.4.5

commands being used:
telepresence connect (works, i'm connected to cluster and able to send requests)
telepresence intercept -p 9000:80 monolith --namespace koala --service monolith -w monolith (monolith is the name of application that is being intercepted), no errors appear
same commands work when deploying application manually

thanks!

**Comment by martinformi** [comment]
Is this not a required behavior? ArgoCD will just sync back to the deployment without hidden port, so it is not working. If you deploy it manually, argo will not monitor this workload, thus the port will be correctly forwarded.
