### ISSUE TITLE
Moving to another instance of git

### ISSUE THREAD

**Issue by marct83** [argoproj/argo-cd#7588]
Here's the situation. We are moving to another instance of git. We need to move our deployment project to this new instance. Once this is done we will need to update argo to use the new project. What I dont want to happen is argo rip everything down and redeploy everything.

What would be the cleanest way to do this?

**Comment by omgapuppy** [comment]
- Turn off auto-sync of the given application
- Point to new git repo
- Examine diff if any
- Sync to new SHA (if tracking git)
- Re-enable auto-sync (if used)

As long as the templated resources match the cluster state, things should just work.
