### ISSUE TITLE
`argocd sync` failure

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#760]
argocd app sync failed. see logs below

```
+ /argocd app sync <appName>

KIND  NAME  STATUS  HEALTH  HOOK  OPERATIONMSG

Ingress     pa-tier-service                 ingress.extensions/pa-tier-service unchanged

Service     pa-tier-service                 service/pa-tier-service unchanged

Deployment  pa-tier-service                 deployment.apps/pa-tier-service configured

time="2018-11-08T18:40:29Z" level=fatal msg="rpc error: code = Unknown desc = Application event object failed conversion: { <nil>}"

```

**Comment by bappr** [comment]
I am seeing the same issue from time to time with `argocd app create ...`.
Very annoying.

`time="2018-12-05T06:32:11Z" level=fatal msg="rpc error: code = Unknown desc = Application event object failed conversion: { <nil>}"`

**Comment by alexmt** [comment]
Please disregard my comment about kubernetes/client-go#334 . We were using channel incorrectly.  Issue was fixed by https://github.com/argoproj/argo-cd/commit/0afc671723a985e28a0ddbeb5efe002bb8ae3109

Same error still might happen in `/applications/<app>?refresh=true` API call. Working on fixing it
