### ISSUE TITLE
ignores deployment containers env changes in live manifest

### ISSUE THREAD

**Issue by ruatag** [argoproj/argo-cd#7611]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD show no differencies if live deployment manifest changes: one or more environment variables added to container

**To Reproduce**

Sync deployment with ArgoCD then change live deployment manifest. Add one or more variables to container.
When I apply the change to the live manifest ArgoCD app status chages to progressing till deploy finishes.
ignoreDifferences NOT used in application.
Application uses kustomize.
Tried several different ArgoCD applications and two ArgoCD instances
Reproduses on ArgoCD 2.0.5 and after update to 2.1.6

**Expected behavior**

Should show the difference

**Screenshots**
![live](https://user-images.githubusercontent.com/42776471/140066508-7ec098ce-f6ec-42c2-81d4-2ddd4124d9c6.png)

![desired](https://user-images.githubusercontent.com/42776471/140066535-0c235953-f387-49c6-9df8-63ebe1f1bf8e.png)

![image](https://user-images.githubusercontent.com/42776471/140066593-fe162186-e6a7-4272-9404-f3c62b05829d.png)

**Version**

```shell
argocd: v2.1.6+a346cf9
  BuildDate: 2021-10-28T19:59:40Z
  GitCommit: a346cf933e10d872eae26bff8e58c5e7ac40db25
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

No errors or something unusual

**Comment by jessesuen** [comment]
I believe you must have added/removed the env var out-of-band from kubectl apply / gitops (e.g. using the resource editor or `kubectl edit`), in which case we will not detect it as a diff since it will be treated like a defaulted field (similar to how we don't detect diffs on mutating webhooks that inject sidecars).

This is expected behavior.

**Comment by ruatag** [comment]
Can't understand how to compare completely different things like envs from deployment and webhooks injecting sidecars
If someone did ad-hoc change in the cluster an this is not detected this brokes GitOps approach itself as we can't understand what is the real configuration applied. In this way ArgoCD doesn't look better then kubectl apply
ignoreDifferences can be used for indirect changes we expect
It's ok to ignore some advanced and non standard configuration ways like special annotations but ignoring envs in deployment which is the facto standard kubernetes configuration really strange
For me it looks like an attempt just close the problem

**Comment by jessesuen** [comment]
> In this way ArgoCD doesn't look better then kubectl apply

You are right. We intend to work exactly like `kubectl apply`, because we use `kubectl apply` and we wish to match diffing behavior of `kubectl diff`.

> For me it looks like an attempt just close the problem

Yes, because this is working exactly as designed.

**Comment by fdcds** [comment]
> This is expected behavior.

The reason is also explained in https://github.com/argoproj/argo-cd/issues/4537#issuecomment-707997759
