### ISSUE TITLE
Out of sync reported if Secrets with stringData are used

### ISSUE THREAD

**Issue by twz123** [argoproj/argo-cd#763]
When using Secrets with the `stringData` feature in the input manifests, those Secrets are always reported out of sync.

Maybe this needs some special casing which merges `data` and `stringData` somehow, as the API server does during apply?

**Comment by jessesuen** [comment]
I agree. I think stringData is something that can be special cased during the diff

**Comment by jessesuen** [comment]
Fixed in v0.11
