### ISSUE TITLE
Support diffing a local Helm app to the live application state

### ISSUE THREAD

**Issue by zx8** [argoproj/argo-cd#764]
Similar to https://github.com/argoproj/argo-cd/pull/298

Would be great to be have this functionality for local Helm charts, as well as being able to pass in Helm values/parameters for the diff as well.

**Comment by jessesuen** [comment]
We actually have a `ks app diff --local <localpath>` flag that supports this mode for ksonnet. We will look at expanding this to helm and kustomize.

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo-cd/pull/863
