### ISSUE TITLE
UI: Include image tag in the deploy object

### ISSUE THREAD

**Issue by manivannan-g** [argoproj/argo-cd#7646]
# Summary

At times the users (especially Dev/QA) find it difficult to find which image/tag is deployed. So showing up which tag of the image is deployed would be helpful right next to the revision label `rev`

Example:
Highlighted the requested enhancement in yellow.
![image](https://user-images.githubusercontent.com/18187267/140708689-83969a36-d29d-4daa-8783-46499af3ee33.png)

# Motivation

Enables the non-devops/SRE users to know the current deployment.

# Proposal

Probably we can give user more control on what all the labels they want to view on the deployment object.

**Comment by jessesuen** [comment]
The images used are already surfaced at an application level. See:

![image](https://user-images.githubusercontent.com/12677113/140842938-30fbae25-e816-48be-99c6-61ce694924be.png)

This suggestion can't really scale inside a tiny tree node box, especially when there are many sidecars and long image names.
