### ISSUE TITLE
ArgoCD scalability challenges

### ISSUE THREAD

**Issue by Sea-you** [argoproj/argo-cd#7647]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Recently as we have added a new cluster, and the number of non-ArgoCD managed apps started to grow, we are experiencing instability. 

Our use case is quite special as on each cluster we have 10k+ apps (Deployments, PVs, PVCs, Secrets, etc) that are managed elsewhere, but apart from that, we have quite a few apps on each cluster that are being managed by ArgoCD. All resources that cause the issue are in the default namespace. 

We set `80/80` status/operation processors.

ArgoCD Application Controller has enough resources, it uses 6+cores and 7GB of memory on peaks. The reconciliation timeout is 10 minutes. 

Remote clusters are in the same DC.

```
argo-cd-argocd-application-controller-0       1/1     Running     0          2d17h
argo-cd-argocd-dex-server-68f5d64cc7-hzccw    1/1     Running     0          4d21h
argo-cd-argocd-redis-544ff9dd8c-9x2wm         1/1     Running     1          130d
argo-cd-argocd-repo-server-8455757876-6xb8x   1/1     Running     0          4d21h
argo-cd-argocd-repo-server-8455757876-nll58   1/1     Running     0          4d21h
argo-cd-argocd-repo-server-8455757876-qrrd4   1/1     Running     0          4d21h
argo-cd-argocd-server-86dddb6c96-d78ts        1/1     Running     0          4d21h
```

Halp! :)

**To Reproduce**

Not sure where the sweet spot is, but if you check the screenshots, it's clear where it started to not scale anymore.

**Expected behavior**

We love ArgoCD so, it'd be nice to make this work for this use case as well.

**Screenshots**

The point where things started to go sideways:
![image (14)](https://user-images.githubusercontent.com/8708247/140716351-e1d43ae6-7495-4595-8114-561ea3d8b39a.png)

App states over a 24h period:
<img width="1607" alt="Screenshot 2021-11-08 at 10 13 42" src="https://user-images.githubusercontent.com/8708247/140715067-43921254-2df4-4f3a-8618-fc70fd40c8fc.png">

Number of objects seen by ArgoCD:
<img width="1612" alt="Screenshot 2021-11-05 at 18 14 36" src="https://user-images.githubusercontent.com/8708247/140715274-8e4c18c5-3d77-42a7-bc3a-0f302902b094.png">

Related error in ArgoCD:
![image](https://user-images.githubusercontent.com/8708247/140714835-ab8c7fc2-5b76-4b12-92fa-f5c31abd8200.png)

**Version**

```shell
argocd: v2.1.6+a346cf9
  BuildDate: 2021-10-28T19:59:40Z
  GitCommit: a346cf933e10d872eae26bff8e58c5e7ac40db25
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  ```

**Logs**

```
Pretty much the same as in the screenshot above.
time="2021-11-05T19:04:25Z" level=error msg="Failed to cache app resources: failed to sync cluster https://REDACTED: failed to load initial state of resource ConfigMap: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 29757; INTERNAL_ERROR" application=REDACTED dedup_ms=0 diff_ms=0 git_ms=204525 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0
```

**Comment by jessesuen** [comment]
I think you will need to start sharding your controller. Have you seen the docs on this?

https://github.com/argoproj/argo-cd/blob/43cba9cc0b30ae1f597771b8960ba9daed524a87/docs/operator-manual/high_availability.md#argocd-application-controller

**Comment by Sea-you** [comment]
Thanks @jessesuen I have seen the docs, although it wasn't entirely clear that it could help with these cases as well. I have sharded with 2 replicas for a while, and as you can see from the screenshot below, it's somewhat similar:

![image](https://user-images.githubusercontent.com/8708247/142173224-527bf645-5dcd-44be-b2bd-2205b44d39ff.png)

Then yesterday I increased to 3 replicas, and while it's not super-stable, I'm somewhat ok with that...

![image](https://user-images.githubusercontent.com/8708247/142173406-9eed90d3-66f7-4d1f-b682-5dde6308697e.png)

I'll check it further and get back to this issue if I have any more updates.
