### ISSUE TITLE
Pod view memory size units should be binary based and not decimal based (eg Mi instead of MB)

### ISSUE THREAD

**Issue by keithchong** [argoproj/argo-cd#7649]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

The memory that is shown in the pod, group by node view, shows the wrong units for memory.  They should be in binary units. I discovered this while working on https://github.com/argoproj/argo-cd/issues/6989.

**To Reproduce**

1. See https://cd.apps.argoproj.io/applications/rollout-experiment
2. Hover over the memory bar in one of the pod cards.

**Expected behavior**

The unit should be Mi or MiB (binary) instead of MB (decimal)

**Screenshots**

<img width="353" alt="Screen Shot 2021-11-08 at 11 02 04 AM" src="https://user-images.githubusercontent.com/7726022/140777460-887da750-f637-47f0-8c0a-41ff542588bc.png">

<img width="254" alt="Screen Shot 2021-11-08 at 11 02 16 AM" src="https://user-images.githubusercontent.com/7726022/140777482-140dc969-d228-4238-b949-627b1191b06e.png">

(I did this also in my deployment, by specifically using Mi)

**Version**
Latest

**Logs**
N/A

**Comment by jessesuen** [comment]
Here is an example payload we return to UI:

```yaml
        {
          "resourceName": "memory",
          "requestedByApp": 33554432000,
          "requestedByNeighbors": 668991488000,
          "capacity": 8349945856000
        }
```

The requestedByApp is called by summing up `MilliValue()`:

```golang
		for _, pod := range appPods {
			for name, resource := range pod.ResourceRequests {
				if !supportedResourceNames[name] {
					continue
				}

				info := resources[name]
				info.RequestedByApp += resource.MilliValue()
				resources[name] = info
			}
		}
```

Which is in decimal:

```golang
// MilliValue returns the value of ceil(q * 1000); this could overflow an int64;
// if that's a concern, call Value() first to verify the number is small enough.
func (q *Quantity) MilliValue() int64 {
	return q.ScaledValue(Milli)
}
```

The UI in turn is calculating in decimal:

```typescript
function formatMetric(name: ResourceName, val: number) {
    if (name === ResourceName.ResourceStorage || name === ResourceName.ResourceMemory) {
        // divide by 1000 to convert "milli bytes" to bytes
        return formatSize(val / 1000);
    }
    // cpu millicores
    return (val || '0') + 'm';
}
```

So unless I'm missing something, it seems to be working as expected.

**Comment by keithchong** [comment]
Hey @jessesuen

We know that 32 MiB = 33.554432 MB

In the above example, the backend is sending 33554432000.

To convert from milli to bytes:
33554432000 * 10^-3 = 33554432
( eg. https://github.com/argoproj/argo-cd/blob/a3517d594ba96bccb680c11328bd7ed4a6095d9d/ui/src/app/applications/components/application-pod-view/pod-view.tsx#L428)

To convert this value in bytes to MB:
33554432 * 10^-6 = 33.55432 MB
Or, 33554432 / k^2 = 33.554432 MB, where k =1000

However, to convert this to MiB:
3355432 / k^2 = 32 MiB, where k=1024

So
https://github.com/argoproj/argo-cd/blob/a3517d594ba96bccb680c11328bd7ed4a6095d9d/ui/src/app/applications/components/application-pod-view/pod-view.tsx#L419
k = 1024 here means we are converting from decimal to binary, eg. MB to MiB
k = 1000 instead means we are leaving it in decimal, but converting it from bytes to KB, MB, GB, etc.

Either change the k value, or we change the constant strings from decimal to binary units

const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];

https://github.com/argoproj/argo-cd/blob/a3517d594ba96bccb680c11328bd7ed4a6095d9d/ui/src/app/applications/components/application-pod-view/pod-view.tsx#L414

Note, in the deployment yaml (see line 153 in the second screenshot in the bug description), the requested memory is specified in Mi. So, it has to match in the Argo CD UI.

**Comment by jessesuen** [comment]
Ah, I missed the whole formatSize part of the implementation. You're right. To fix this, I agree we can switch the `const sizes` to return binary units.

**Comment by keithchong** [comment]
<img width="413" alt="WithFix" src="https://user-images.githubusercontent.com/7726022/142078330-da33522c-e153-4ab3-ac1f-b3d6fca97415.png">
