### ISSUE TITLE
User-Agent missing version

### ISSUE THREAD

**Issue by james-callahan** [argoproj/argo-cd#7669]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The HTTP User-Agent sent by the ArgoCD application controller is missing version information.
Out kubernetes API server sees: `argocd-application-controller/v0.0.0 (linux/amd64) kubernetes/$Format`

**To Reproduce**

  - Use official ArgoCD docker container
  - Look at your kube api server logs

**Expected behavior**

User-Agent sent by ArgoCD should contain the ArgoCD version.

**Version**

Argo CD v2.1.2+7af9dfb

**Logs**

As seen by `kube-apiserver-audit`:
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Request","stage":"ResponseComplete","verb":"get","userAgent":"argocd-application-controller/v0.0.0 (linux/amd64) kubernetes/$Format",......}
```

**Comment by jannfis** [comment]
I agree, we could supply the version in the user agent.

**Comment by hzliangbin** [comment]
@jannfis I would like to give it a try, may I take this ?
