### ISSUE TITLE
certificate signed by un known authority

### ISSUE THREAD

**Issue by calvinShan** [argoproj/argo-cd#7675]
Hello,

I have successfully installed argocd and added the repo by commande line.

Now, I want to create an application by this command line:

argocd app create rawmaterial-refom --dest-namespace argocd --dest-server https://kubernetes.default.svc --repo https://gitlab-ri.xxl.wans/FormulationCenter/xx/configurationkubernetes --path test/dev

FATA[0000] rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: repository not accessible: rpc error: code = Unknown desc = Get "https://gitlab-ri.xxl.wans/FormulationCenter/xx/configurationkubernetes/info/refs?service=git-upload-pack": x509: certificate signed by un known authority

We have already uploaded the certificate in argocd, and we could also create the parent apps via UI argo

But I don't understand why it does not work to create the parent app by command line

Thanks

**Comment by mayzhang2000** [comment]
From `--dest-server https://kubernetes.default.svc `, you are deploying your application to the cluster where ArgoCD resides. You need to do `argocd cluster add` with `--in-cluster` flag.

**Comment by jessesuen** [comment]
> Get "https://gitlab-ri.xxl.wans/FormulationCenter/xx/configurationkubernetes/info/refs?service=git-upload-pack": x509: certificate signed by un known authority

Please see docs on how to configure TLS certificates:
https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#self-signed-untrusted-tls-certificates

https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#tls-client-certificates-for-https-repositories
