### ISSUE TITLE
Application controller should export workqueue depth metrics

### ISSUE THREAD

**Issue by Ailsa-Wu** [argoproj/argo-cd#7682]
# Summary

Application controller should export workqueue depth metrics

# Motivation

Queuing delay and queue length are important information to debug control plane performance in large scale applications(3k+).

We use one ArgoCD instance to manage about 3K applications. And the number is still increasing, followed by the performance downgrade, for example it would take more time to trigger the auto sync or it can't refresh the resources status and keep with live status.

We have tried multi method to enhance performance.
1. scale up the replicas of ArgoCD server and repo-server with the [HA guide](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/) 
2. increase the `--status-processors` to 200 and `--operation-processors` to 100 refer to the [doc](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller)
3. configure server replicas with the HPA.

But unfortunately we still need about 20s to list application and update project role, e.g.

![image](https://user-images.githubusercontent.com/66725688/141254528-548c8d79-550b-4519-8a17-c31b79393104.png)
![image](https://user-images.githubusercontent.com/66725688/141254613-5e53641c-27b9-4031-b80e-d04c5546a11c.png)

And after we switch to HA mode, the reconcile performance looks worse.
![image](https://user-images.githubusercontent.com/66725688/141255515-8044ff3a-6169-46bf-a9ec-87911510047a.png) 

Not sure if I am understanding this right, any response would be appreciated🙏.

# Proposal

Application controller export the workqueue depth metrics.

**Comment by alexmt** [comment]
Hello @Ailsa-Wu ,

The controller workqueue depth metric is already available. You might use the following query to get it: `sum(workqueue_depth{name=~"app_.*"})` .

However, the API response slowness is not related to the controller. It is possible that you are affected by this issue https://github.com/argoproj/argo-cd/issues/4296 . The issue has a fix already and will be available in v2.2-rc1 that will be published later today. I would appreciate it if you give it a try and let us know if performance improved in your environment.

**Comment by Ailsa-Wu** [comment]
Hi @alexmt , thanks for your response. I have tried to get the metric by accessing the endpoint `http://localhost:8082/metrics` . But I could not find this metric `workqueue_depth`. If there was some issues?🧐
```sh
k port-forward svc/argocd-application-controller-metrics -n argocd 8082:8082
```

![image](https://user-images.githubusercontent.com/66725688/141714339-3bbb9737-f95f-4123-9e18-7cb9e0e9c061.png)

**Comment by sidewinder12s** [comment]
@jessesuen @alexmt I also don't think I see workqueue_depth on version 2.1.5 anymore.

**Comment by yeya24** [comment]
@alexmt @jessesuen I don't think this works as well. We only registers workqueue metrics to the registry inside `component-base` library and we don't register it when serving `/metrics` endpoint. We need to register workqueue metrics to controller's own registry

**Comment by yeya24** [comment]
I just created https://github.com/argoproj/argo-cd/pull/8318 to fix this.

**Comment by taliastocks** [comment]
This appears to be an issue again as of (at least) the 2.9 release.

**Comment by joshuabezaleel** [comment]
+1. the `workqueue_depth` also disappeard on our side.
![Screen Shot 2023-12-25 at 00 19 54](https://github.com/argoproj/argo-cd/assets/7043511/c054d75f-2942-484e-aad2-2db6de30951b)
