### ISSUE TITLE
Allow Resource Hooks to target syncs of specific resources.

### ISSUE THREAD

**Issue by Roshick** [argoproj/argo-cd#7691]
# Summary

It would be great to have a selector/filter annotation for resource hooks to only apply when resources with a certain name/label are synced.

# Motivation

A job that should run on config map syncs, a job that only needs to run when a deployment is synced, many use cases imo. Not sure if it fits into resource hooks or should rather be done by workflows.

# Proposal

An annotation on the job definition.

**Comment by jannfis** [comment]
May I ask concrete use-cases behind this?

**Comment by Roshick** [comment]
Of course. In our case we have a renovatebot which is a job that runs based on a configmap, in which repositories are configured that should be checked for dependency updates. Now we have one configmap (and one job) for each team in our company, so whenever a configmap is changed/synced it should trigger the corresponding job instead of all jobs. Since these jobs share secrets and environment variables from a different configmap we would rather avoid having to split each of them into different applications.

**Comment by jannfis** [comment]
I'm not sure whether it would be a good idea to move the scope of hooks from application lifecycle to certain resource's lifecycle, to be honest. As you mentioned, to me this sounds more like a job for workflows than for resource hooks.

Although it may sound a little complex at first, I guess a combination of Argo CD (for syncing the ConfigMaps), Argo Workflows (for running the renovate jobs) and Argo Events (to trigger the workflow on change of the ConfigMap) would be solid solution for this use case.

**Comment by jannfis** [comment]
That being said, maybe there are also other opinions.

**Comment by ebuildy** [comment]
Our use case:

> We run Jobs to configure elasticsearch, the config content is inside a configMap, we would like to execute the configurator job **only on ConfigMap changes**.

(same thing for Kibana, Vault, etc...)
