### ISSUE TITLE
Workflow for blue-green deployment while preserving original deployment name

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#77]
Problem:
I want to define a *single* deployment and service in ksonnet/git. The resource names of the corresponding deployment and service would be jesse-deploy and jesse-svc, respectively. I will have 5 replicas of the deployment. I want the ability to perform a blue-green deployment where I surge to 10 concurrently running pods, half of which are running the newer version, then perform a DNS/service level cutover to the new version via an update of the jesse-svc service resource with the new label selector.

The challenge is that we want to preserve the deployment resource/name, while also not wanting to redefine the same deployment twice as two deployment components in the ksonnet app (i.e. blue and green). In other words, I do not want jesse-deploy-green.yaml and jesse-deploy-blue.yaml deployment manifests checked in anywhere in git.

Current blue-green kubernetes techniques describe the creation of a new deployment with a new name and updating the service to point to the new deployment. However, this does not work well with GitOps because it implies the new deployment and new name would need to be checked-in with a new name.

I am proposing the following workflow to achieve blue-green deployment while preserving the original deployment resource, and without requiring a user to manage two duplicate deployment manifests in their git repo.

1. a deployment jesse-deploy and service jesse-svc start out running version 1 of the image, with selector app=jesse and 5 replicas.
2. blue-green deploy action is invoked via argo-cd API
3. a new, ephemeral deployment jesse-deploy-tmpXYZ is created at version 1, with selector app=jesse-tmpXYZ
4. jesse-deploy-tmpXYZ becomes healthy with 5 replicas. At this point in time, we have 10 pods running version 1 of the image, split equally between the two deployments. But no traffic is directed to the ephemeral deployment jesse-deploy-tmpXYZ because the label is unique.
5. service jesse-svc is patched to use selector app=jesse-tmpXYZ (which is still running version 1). At this point, all traffic is directed to the ephemeral deployment jesse-tmpXYZ running version 1
6. jesse-deploy is updated with the new manifest to run version 2
7. jesse-deploy becomes healthy and with 5 replicas. At the point, we have 5 pods running version 2, and 5 pods running version 1. No traffic is being directed to version 2 yet.
8. The service jesse-service is updated with the original app selector app=jesse. At this point, all traffic is directed back to jesse-deploy which is running version 2.
9. jesse-deploy-tmpXYZ is no longer receiving any traffic. It is now safe to delete the ephemeral deployment. Once deleted, the live state of the deployment and service should now reflect the state in git and the app should be considered synced.

**Comment by merenbach** [comment]
Trying my hand at this.

**Comment by mukulikak** [comment]
where and when do we run the tests to test version 2?
