### ISSUE TITLE
Guidance on custom binaries, Helm plugins, kustomize generators

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#772]
We need to provide some documentation and guidance on how end users may customize their repo-servers to have the necessary binaries/plugins to perform manifest generation. Some use cases:

1. Support for helm plugins
2. Different versions of kustomize, helm, ksonnet than what Argo CD bundles
3. Scripts and CLIs needed in kustomize generators

I believe that we can support all of the above today, using PATH manipulation combined with volume mapping binaries into the repo-server.

**Comment by jessesuen** [comment]
Updated docs to support custom binaries:
https://github.com/argoproj/argo-cd/blob/master/docs/custom_tools.md

**Comment by RobertKozak** [comment]
correct path is https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/custom_tools.md
