### ISSUE TITLE
core-install manifest references undefined argocd-server ServiceAccount

### ISSUE THREAD

**Issue by joebowbeer** [argoproj/argo-cd#7760]
**Describe the bug**

The core-install manifest includes a ClusterRoleBinding for an `argocd-server` ServiceAccount, but it does not define this service account:

https://github.com/argoproj/argo-cd/blob/master/manifests/core-install.yaml#L2729

Analysis: The extraneous ClusterRoleBinding for argocd-server originates here:

https://github.com/argoproj/argo-cd/blob/master/manifests/cluster-rbac/argocd-server-clusterrolebinding.yaml#L15

**To Reproduce**

1. Look at the core-install [manifest](https://github.com/argoproj/argo-cd/blob/master/manifests/core-install.yaml) and search for `kind: ServiceAccount`
1. Note that there is no ServiceAccount resource for `argocd-server` but this service account is [referenced](https://github.com/argoproj/argo-cd/blob/master/manifests/core-install.yaml#L2729) in a ClusterRoleBinding.

**Expected behavior**

ClusterRoleBindings will only reference existing ServiceAccounts.

**Version**

master/2.2

**Comment by chetan-rns** [comment]
I don't think Argo CD in core mode uses the argocd-server since it doesn't install the API server/UI. Maybe we could have a patch to exclude the argocd-server resources
