### ISSUE TITLE
Add app list and details page specific views to navigation history (regression in behavior)

### ISSUE THREAD

**Issue by keithchong** [argoproj/argo-cd#7776]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I was selecting the various views in the details page and when I pressed the browser's Back button, it brought me back to the Application list page. Before, it would just switch back to the Details-specific view that I had just visited.  The change for this was due to https://github.com/argoproj/argo-cd/issues/7090. 

IMHO, while I do agree that the sliding panels should not be part of the navigation history, I think the fix for this went a bit too far in removing the views from the history.  The buttons along the left side-bar are part of the history at least.

**To Reproduce**

1. Go to https://cd.apps.argoproj.io/applications?proj=&sync=&health=&namespace=&cluster=&labels=
2. Click on one of the apps to drill down to its details page
2. Select several views, eg. Pods, Network, List and Tree views in succession
3. Press the browser's Back button
--> you will go back to the Application List page 

**Expected behavior**

These views should be part of the navigation history

Just to compare:
- Simply look at the current github page, select the various tabs above (Issues, Pull requests, Discussions) - they are part of the navigation history
- Amazon navigation 'tabs' as well
- Walmart navigation tabs
- (not that I'm checking out Black Friday sales or anything....)
- Go to the fluxcd.io page and click on the top right menus

**Version**
Latest

**Comment by keithchong** [comment]
Hi @pasha-codefresh, I can take this.

**Comment by keithchong** [comment]
See https://github.com/argoproj/argo-ui/issues/164

**Comment by pasha-codefresh** [comment]
Thank you @keithchong
