### ISSUE TITLE
UI should use pagination to render pod logs

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#781]
UI is trying to load all pod logs which does not work well for long-living pods which are printing a lot of logs. Logs pagination should be used instead.

**Comment by alexec** [comment]
Driven by user feedback.

**Comment by alexec** [comment]
Option - consider providing deep link into Splunk (or other logging facility).

**Comment by alexmt** [comment]
Additional improvement: support viewing previous logs (`kubectl logs -p`)

**Comment by szalapski** [comment]
Even if it isn't pagination, it would be nice to just keep the window stable so that it doesn't automatically scroll, and to enable Ctrl+C to copy and Ctrl+A to select all.

**Comment by rbreeze** [comment]
@szalapski That should be a pretty easy change to make. Pagination is a bigger change, will do scrolling first

**Comment by rbreeze** [comment]
@szalapski What do you mean by keeping the window stable? That the logs should not move when new lines are written?

**Comment by szalapski** [comment]
Yes.  How can I read the top of the log when it keeps scrolling to the
bottom for me?
