### ISSUE TITLE
Trailing line in Filter Dropdown Menus

### ISSUE THREAD

**Issue by bgolding355** [argoproj/argo-cd#7821]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Clicking into a filter box brings up a dropdown. In this dropdown there is a ruled line at the bottom of the list of items, no such line exists at the top.

**To Reproduce**

1. Go to https://cd.apps.argoproj.io/applications/guestbook?resource=
2. Click in the filter box `KINDS`
3. Observe that a ruled line exists at the bottom of the list

**Expected behavior**

No ruled line at the bottom

**Screenshots**

![argo-with-trailing-line](https://user-images.githubusercontent.com/60831565/144310547-afb9afaf-13b3-442b-b173-b2e851be42aa.png)

**Version**

```shell
{
    "Version": "v2.2.0+b977813",
    "BuildDate": "2021-12-01T17:43:05Z",
    "GitCommit": "b977813e9a6baa93dc44cb75f66efa091adfdded",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.7.1+g1d11fcb",
    "KubectlVersion": "v0.22.2",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**
N/A

**Comment by ciiay** [comment]
I'd like to work on this.
