### ISSUE TITLE
cannot add new application using UI

### ISSUE THREAD

**Issue by kimhongji** [argoproj/argo-cd#7843]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I add new application(helm) using +NEW APP button on UI, the values file has gone.

**To Reproduce**

1. click the `NEW APP` button 
2. set source, destination, and helm values file  (the source is git)
3. click the `CREATE` button
4. the error
or
1. click the `NEW APP` button
2.  set source, destination, and helm values file  (the source is git)
3. click the `EDIT AS YAML `button
4. and back to last page (edit on ui)
5. the helm values files disappears

the source was git , and the destination was external cluster (for reproducing the bug exactly)

**Expected behavior**

The Application should be created also on UI

**Screenshots**

1. I set the value file like this
 
![image](https://user-images.githubusercontent.com/36401495/144534371-45da59a7-efbf-495d-a51f-5703406a44bf.png)

2. and I pushed `CREATE` button, the error message is showed 
3. so, I tried to edit yaml on UI (`EDIT AS YAML` button), the helm values has gone like this
![image](https://user-images.githubusercontent.com/36401495/144534600-2a961d8e-3392-4790-82c6-077b170fd6c0.png)

4. and then if I back to last page, the values file disappeared.. like this

![image](https://user-images.githubusercontent.com/36401495/144534661-837b9599-6e37-42b7-ac1c-02dc8a619828.png)

So, I have to edit as yaml and manually added helm spec like this, then after click `SAVE` button and `CREATE` button,  the application create success 
```
...
    helm:
      valueFiles:
        - values/feature.values.yaml
 ...
```

**Version**

```shell
argocd: v2.1.4+d5c6608.dirty
  BuildDate: 2021-10-20T04:27:54Z
  GitCommit: d5c66088272c83e1b8b78562ce100006833c2d74
  GitTreeState: dirty
  GoVersion: go1.17.2
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.5+a8a6fc8
  BuildDate: 2021-10-20T15:16:40Z
  GitCommit: a8a6fc8dda0e26bb1e0b893e270c1128038f5b0f
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```

**Logs**
the error when I tried to add application on UI 
```
Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in <app>: rpc error: code = Unknown desc = `helm template . --name-template <app> --namespace straw --kube-version 1.17 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions apps/v1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1beta1 --api-versions cilium.io/v2 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1 --api-versions <api version> --api-versions <api version> --api-versions events.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions snapshot.storage.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions v1 --include-crds` failed exit status 1: Error: template: <app>/templates/http/service.yaml:10:20: executing "<app>/templates/http/service.yaml" at <.Values.http.service.port>: nil pointer evaluating interface {}.service Use --debug flag to render out invalid YAML
```

**Comment by keithchong** [comment]
Hi @kimhongji , curious, when you clicked on the 'Values file' field, does the combo box drop down show the list of yamls?

**Comment by kimhongji** [comment]
@keithchong 
Hi, thank you for the response,
When I click the 'Value File' field, I can't see any drop box.
my helm chart directory is like this.
```
.
├── Chart.yaml
├── charts
├── templates
│   ├── common
│   │   ├── configMap.yaml
│   │   ├── metric.yaml
│   │   ├── namespace.yaml
│   │   └── rbac.yaml
│   ├── console
│   │   ├── deployment.yaml
│   │   ├── envConfigMap.yaml
│   │   ├── ingress.yaml
│   │   └── service.yaml
│   └── http
│       ├── deployment.yaml
│       ├── envConfigMap.yaml
│       ├── hpa.yaml
│       ├── ingress.yaml
│       └── service.yaml
└── values
    └── feature.values.yaml
```

**Comment by keithchong** [comment]
Hi @kimhongji , could you try moving the values yaml file out of the values folder, to the parent folder?  I think Helm expects that structure.  Then see if it shows up.  If it doesn't show up, then try renaming it to values.yaml, and try again.

**Comment by kimhongji** [comment]
@keithchong Thanks! 
now I can see the list on the values file field, when I move the values.yaml to the parent folder and renaming to values.yaml. But, I want to separate the values file like feature/develop/prod .. etc.. 

so I'd like to know what is the best practice to separate values file for multi cluster environment.

**Comment by keithchong** [comment]
np @kimhongji , there can still be some usability improvements here, like feedback or validation whenever an invalid values file is detected.  That way, you will see immediately that an invalid file was entered in.  Perhaps this issue could address this usability problem.

I'm not an expert at Helm so I'd prefer not to advise you on what is the best practice at this time.  Maybe this example could be helpful (it has multiple values files)

https://github.com/codefresh-contrib/helm-promotion-sample-app

**Comment by kimhongji** [comment]
@keithchong 
 ok, thank you for recommendation. 
I think the values file's name doesn't problem. If I just move the values file to parent folder, the drop box is shown. 
I solved this issue by moving the values file to parent folder.  But, I think , I hope to improve this way like feedback  as you told me . thanks and I will closing this issue.
