### ISSUE TITLE
Update admin password fails on v0.10.6, kube v1.12.x

### ISSUE THREAD

**Issue by kuznero** [argoproj/argo-cd#785]
Even though `./argocd login ...` ran successfully, consequent call to update password always fails for `admin`:

```
./argocd account update-password
*** Enter current password:
*** Enter new password:
*** Confirm new password:
FATA[0006] rpc error: code = InvalidArgument desc = password can only be changed for local users, not user ""
```

`argocd-server` is running with `--disable-auth` switch (the setup is behind reverse proxy).

As a workaround for now:

* Remove `--disable-auth` switch from `argocd-server`
* Login and update password with `argocd`
* Add `--disable-auth` switch to `argocd-server` again

**Comment by kuznero** [comment]
Problem appeared when I installed argocd-server with `--disable-auth` from the very beginning (not changing the config, but installing fresh with `--disable-auth`). I also assume that once `argocd login ...` succeeded, the content of `~/.argscd` should be consistent and ok.

**Comment by jessesuen** [comment]
Ah, that explains it. If auth is disabled, then there is no logged in user. If there is no logged in user, then  it doesn't have a username to adjust the password for.

The behavior somewhat expected when auth is disabled. Can I close the bug?

**Comment by jessesuen** [comment]
> The only thing left is then to let argocd tool to prompt for username but not password, or at least allow for empty password. WDYT?

I don't think I like the idea of accepting a username as part of the payload of a change password request. This implies that the API supports the ability to change the password of any arbitrary user. The current model, which is always inferring the user from the session token, makes it impossible to change, (or attempt to change) the password of another user. Most password update API's that I've seen, behave in this manner.

**Comment by kuznero** [comment]
I probably was not clear enough. I meant that once we disable authentication on the server it makes sense to stop asking for a password on `argocd login ...`
