### ISSUE TITLE
Docker build for ArgoCD is using old version of kubectl

### ISSUE THREAD

**Issue by cydergoth** [argoproj/argo-cd#7859]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `argocd version`.

**Describe the bug**

Kubectl is out of date in the docker image

**To Reproduce**

Deploy the latest docker image and pull the versions

**Expected behavior**

kubectl is a contemporary version

**Version**

```shell
{
    "Version": "v2.2.0+23967f8",
    "BuildDate": "2021-11-22T17:37:20Z",
    "GitCommit": "23967f8717a4cbf007ece9bc8b4bd1b398db7752",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.7.1+g1d11fcb",
    "KubectlVersion": "v0.22.2", <--------  Should be closer to 1.22.3
    "JsonnetVersion": "v0.17.0"
}
```

**Comment by cydergoth** [comment]
From here: https://github.com/argoproj/argo-cd/blob/master/hack/installers/install-kubectl-linux.sh
the version should be 
https://storage.googleapis.com/kubernetes-release/release/stable.txt

**Comment by cydergoth** [comment]
Looks like this file: 
https://github.com/argoproj/argo-cd/blob/master/hack/tool-versions.sh

Needs updating for kubectl and maybe kubectx too

**Comment by jannfis** [comment]
The kubectl version report from the API's version endpoint is actually the version of Kubernetes API we're using. For some weird reason, `0.22.2` here means the API from Kubernetes 1.22.2 release.

The kubectl binary itself is not bundled anymore with the Argo CD container image. However, it still is bundled with the toolchain container image for setting up CI, and is used within the GitHub Actions CI as well. I agree that we could update it.

**Comment by cydergoth** [comment]
Thanks!
