### ISSUE TITLE
Failed to deploy helm chart into different namespaces in v0.10.6, kube v1.12.2

### ISSUE THREAD

**Issue by kuznero** [argoproj/argo-cd#787]
Argo CD complains that I need to provide another namespace value (presumably for the argo app).

**Comment by jessesuen** [comment]
I think this is a duplicate of https://github.com/argoproj/argo-cd/issues/696. @kuznero can you confirm?

**Comment by kuznero** [comment]
Yes, I can confirm - it very much looks like a duplicate (sorry, didn't spot it myself when was issueing this one). Another example that deploys to multiple namespaces is `prometheus-operator`. Please feel free to close this issue and/or join with #696.

**Comment by jessesuen** [comment]
Thanks! Closing as dup.
