### ISSUE TITLE
Backing from /applications/{applicationName} to /applications not working

### ISSUE THREAD

**Issue by MikeK184** [argoproj/argo-cd#7872]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Backing from /applications/{applicationName} to /applications is not working. (Firefox, Edge have been tested).
As example from `https://argocd.prod-002.k8s.m086/applications/dynatrace-fullstack-addon?` to `https://argocd.prod-002.k8s.m086/applications?` doesn't work when you press the back arrow on the browser
It takes about 8-10 clicks on the back arrow to finally go back to the parent application.

**Expected behavior**

Pressing the back button bringing me back to the parent application

**Version taken from GUI**

```json
{
    "Version": "v2.1.7+a408e29",
    "BuildDate": "2021-11-17T22:10:27Z",
    "GitCommit": "a408e299ffa743213df3aa9135bf7945644ec936",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Relevant Info**
The console shows the following two errors: 
![grafik](https://user-images.githubusercontent.com/56921065/144989991-3f8d4179-ac76-4df2-a3c9-63a6bafca65f.png)

**Comment by keithchong** [comment]
Hello @MikeK184, taking the errors that you see aside, I think the Back button issue you are seeing has been addressed by 

PR https://github.com/argoproj/argo-cd/pull/7327, where it is in the release-2.2 branch.
Issue https://github.com/argoproj/argo-cd/issues/7090

which will further be updated and enhanced by:

https://github.com/argoproj/argo-cd/issues/7776

Could you please confirm that if you press/click and hold the browser Back button, you see multiple entries of the same title?

**Comment by MikeK184** [comment]
Hi there @keithchong, thanks for letting me now! And yes, there are multiple entries: 
![image](https://user-images.githubusercontent.com/56921065/145354294-d32a6bb9-c763-4e6e-af37-04d74bc2c568.png)

I'll be waiting for the new release then.

**Comment by keithchong** [comment]
Hi @MikeK184 , the console errors that you were seeing might be a different/separate problem. Not sure why it could not connect to the API server. So perhaps open another issue for this, if that is reproducible, or if there are other issues related to that.
