### ISSUE TITLE
Scheduled ... First occurred is unix epoch

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#7879]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The `Scheduled` event is effectively rendering a 0 timestamp

**To Reproduce**

1. Have a pod w/ >~250 events
2. open events
3. check the first event

**Expected behavior**

don't render 0 epoch

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/145052918-c278b071-fe1c-4c99-ae4e-1a8365aa0efa.png)
![image](https://user-images.githubusercontent.com/2119212/145057549-7d8d461f-9108-4bd4-a9bc-951c4d7594a3.png)

**Version**

```shell
{
    "Version": "v2.2.0+78e256e",
    "BuildDate": "2021-12-03T22:39:09Z",
    "GitCommit": "78e256eef3dc5fdb8553e58c024d234d8e354e20",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.7.1+g1d11fcb",
    "KubectlVersion": "v0.22.2",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by keithchong** [comment]
The UI is getting back a null timestamp

**Comment by keithchong** [comment]
We're getting the events from the k8s client api. Looks like we just have to handle the null firstTimestamp and null lastTimestamp.

**Comment by keithchong** [comment]
Reproduced issue:
<img width="1089" alt="7879-Issue" src="https://user-images.githubusercontent.com/7726022/145342362-214d572f-47ce-4006-aa05-47f686497918.png">

With Fix:
<img width="1088" alt="7879-WithFix" src="https://user-images.githubusercontent.com/7726022/145342395-40f2e6b2-c2b3-4b24-9efb-5640c53261d6.png">

Describe Pod - Events:
<img width="1038" alt="7879-DescribePod-Events" src="https://user-images.githubusercontent.com/7726022/145342405-1eab3348-ee65-4cb6-803a-646cb4fc9825.png">
