### ISSUE TITLE
Constantly getting "runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by zonnie** [argoproj/argo-cd#7888]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Every time I apply an "app-of-apps" it's stuck as `Unknown` for quite a while with an error `runtime error: invalid memory address or nil pointer dereference`

Refreshing the app manually in ArgoCD's UI solves this...otherwise it takes quite a while to resolve itself

**To Reproduce**

Apply any "app-of-apps" (it happens to all of them in my case)
The smallest one is 5 apps

**Expected behavior**

Application would synchronize and eventually be deployed

**Version**

```shell
argocd: v2.1.6+a346cf9.dirty
  BuildDate: 2021-11-01T02:05:06Z
  GitCommit: a346cf933e10d872eae26bff8e58c5e7ac40db25
  GitTreeState: dirty
  GoVersion: go1.17.2
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.6+a346cf9
```

**Logs**

From `argocd-controller` logs
```
time="2021-12-08T17:14:12Z" level=info msg="updated 'redis-servers-env-2' operation (phase: Failed)"
time="2021-12-08T17:14:12Z" level=info msg="Sync operation failed: Invalid operation request: no operation specified (retried 3 times)." application=redis-servers-env-2 dest-namespace=env-2 dest-server="https://kubernetes.default.svc" reason=OperationCompleted type=Warning
time="2021-12-08T17:14:12Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 189 [running]:\nruntime/debug.Stack(0xc004291940, 0x29f0040, 0x52affa0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj/argo-cd/v2/controller.(*ApplicationController).processRequestedAppOperation.func1(0xc0034e21c0, 0xc004291be0, 0xc00078aa00, 0xc005b88400)\n\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:968 +0x5d\npanic(0x29f0040, 0x52affa0)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/argoproj/argo-cd/v2/controller.(*ApplicationController).processRequestedAppOperation(0xc00078aa00, 0xc005b88400)\n\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:1052 +0x47f\ngithub.com/argoproj/argo-cd/v2/controller.(*ApplicationController).processAppOperationQueueItem(0xc00078aa00, 0x203001)\n\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:681 +0x4df\ngithub.com/argoproj/argo-cd/v2/controller.(*ApplicationController).Run.func4()\n\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:590 +0x36\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00066af40)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:155 +0x5f\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00066af40, 0x3bf6040, 0xc00057b200, 0x1, 0xc000872f00)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:156 +0x9b\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00066af40, 0x3b9aca00, 0x0, 0x1, 0xc000872f00)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:133 +0x98\nk8s.io/apimachinery/pkg/util/wait.Until(0xc00066af40, 0x3b9aca00, 0xc000872f00)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:90 +0x4d\ncreated by github.com/argoproj/argo-cd/v2/controller.(*ApplicationController).Run\n\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:589 +0x51f\n" application=redis-servers-env-2
time="2021-12-08T17:14:12Z" level=info msg="Update successful" application=redis-servers-env-2
time="2021-12-08T17:14:12Z" level=info msg="Reconciliation completed" application=redis-servers-env-2 dedup_ms=0 dest-name= dest-namespace=env-2 dest-server="https://kubernetes.default.svc" diff_ms=0 fields.level=825146262304 git_ms=23 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=71
time="2021-12-08T17:14:12Z" level=info msg="updated 'redis-servers-env-2' operation (phase: Error)"
time="2021-12-08T17:14:12Z" level=info msg="Sync operation failed: runtime error: invalid memory address or nil pointer dereference" application=redis-servers-env-2 dest-namespace=env-2 dest-server="https://kubernetes.default.svc" reason=OperationCompleted type=Warning
```

**Comment by zonnie** [comment]
I see it's aiming for `v2.3`, I'd appreciate if someone could give me a workaround or explain what's triggering this...
Thanks 🙏🏻

**Comment by alexmt** [comment]
Hello @zonnie , 

@jomenxiao  just implemented fix for this issue. Merging it and cherry-picking into v2.1 and releasing patch release shortly.

**Comment by zonnie** [comment]
Thanks @alexmt ! 
ArgoCD is the only project I actually open bugs because you guys actually handle them !

**Comment by zonnie** [comment]
Sorry for being annoying but what's the estimation on the patch release ?
Our deployments currently require manual intervention otherwise the process doesn't converge...
Appreciated 🙏🏻

**Comment by alexmt** [comment]
Patch release has been published https://github.com/argoproj/argo-cd/releases/tag/v2.1.8

**Comment by zonnie** [comment]
It still fails, the error is different but the end result is the same...I still need to manually "Refresh" the app...
![Screen Shot 2021-12-14 at 10 06 11 AM](https://user-images.githubusercontent.com/7836993/146024165-a6732f2e-4dc5-4daa-a90f-d90ac5c6b2ac.jpg)
Which log should I check ? `controller` and `server` doesn't have anything interesting...

**Comment by alexmt** [comment]
Can you please share how do you start sync operation?  Do you use UI or CLI?

**Comment by zonnie** [comment]
It's all my fault...
We are interacting with ArgoCD programmatically using the Golang interface. 
Seems like we kept passing nil for the Sync pointer and since it eventually converges on it's own we missed it.

**Comment by alexmt** [comment]
@zonnie we've got a meaningful error message :)  Now it became clear why sync was failing
