### ISSUE TITLE
configurable listen address for argocd admin dashboard 

### ISSUE THREAD

**Issue by ryane** [argoproj/argo-cd#7891]
# Summary                                                                                                                                                                                 

When using ArgoCD  core and the `argocd admin dashboard` command, I would like to be able to specify a listen address other than `localhost`.

 # Motivation

 When working on remote development environments, having the ability to specify a listen address (like a specific IP or `0.0.0.0`) would allow users to (more) easily access the dashboard from a local browser.

# Proposal

Add a new `--address` flag to the `argocd admin dashboard` command that allows the user to specify the address to listen on (similar to the existing `--port` flag and to similar options in other tools (like `kubectl port-forward`)).

(I have this working in a local build already b/c I needed it. Happy to polish it up and PR.)

**Comment by jannfis** [comment]
I like this idea. WDYT @alexmt?

**Comment by avinashupadhya99** [comment]
Hi, can I work on this? Can you please assign me this? Thanks
