### ISSUE TITLE
Can not set a token for a user in the `argocd-secret`

### ISSUE THREAD

**Issue by sekthor** [argoproj/argo-cd#7894]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**

When I attempt to set a token for a user, as described in issue [3185](https://github.com/argoproj/argo-cd/issues/3185#issuecomment-595488681), the token is loaded, but seems to be malformed in some way.
The UI indicates, that the token has no ID and an *invadid date (invalid date)*.
The token may not be used to make API-calls.
The server answers with `{"error":"invalid session: account username <username> does not have token with id <token id>","code":16,"message":"invalid session: account <username> does not have token with id <token id>"}`

**To Reproduce**

- Generate a Token with the ArgoCD UI
- For security purposes, the token is persisted in a password manager
- Load the token into the `argocd-secret` directly, using a shell script

```shell
$USER_TOKEN= #code that fetches token in format ["token"]
cat << EOL
apiVersion: v1
data:
  ....
  accounts.user.tokens: $USER_TOKEN
  ...
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  ...
EOL | kubectl apply -f -
```

I have also tried setting `$USER_TOKEN` to the raw token and putting it into the config map in variations of this:

``` 
accounts.user.tokens: "[\"$USER_TOKEN\"]"
accounts.user.tokens: ["$USER_TOKEN"]
accounts.user.tokens: "[$USER_TOKEN]"
```

All of these resulted in an error in ArgoCD.
Only when I set the `$USER_TOKEN` to be `["<token>"]`, and used it like `accounts.user.tokens: $USER_TOKEN` , as in the example above, would it even show up in ArgoCD.
However, it showed up without id and an invalid date.

**Expected behavior**

Being able to use this token for the as `Authorization: Bearer token` to authenticate to the API.
I expected it to properly import the token from the `argocd-secret`.

**Screenshots**

![image](https://user-images.githubusercontent.com/47781316/145399157-ed421579-286d-4bf0-b457-5b3500789646.png)

**Version**

```json
{
    "Version": "v2.1.0+d0b2d55",
    "BuildDate": "2021-08-20T05:30:54Z",
    "GitCommit": "d0b2d55e3fb7fe8b17385d6687886de41651f31b",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ONordander** [comment]
Hi. I recently looked into doing this as well and wanted to give my input.
If you inspect a token that has been created by ArgoCD:
`kubectl get secret -n argocd argocd-secret -o jsonpath="{.data.accounts\.<argo-account>\.tokens | base64 -d`

You should get an output like this:
`[{"id": "token-id", "iat": 123}]`

You should be able to append similar objects to this secret, just remember that the JWT (that you for example get from the UI) must have the same information.

**Comment by sekthor** [comment]
Thank you very much @ONordander. Your answer made me realize I have been putting tokens in the wrong format into the kubernetes secret.
As you said, the correct format is `[{"id": "token-id", "iat": 123}]`, whereas I assumed it needed to be in the base64-JWT format of e.g: `["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXN0IjoidGVzdCJ9.ljmhQFQyD3RFJIiB1yxxEmai2qF-3E8SyjYvlGYThQ8]"]`
