### ISSUE TITLE
Unable to start argo on ampere (arm) cluster

### ISSUE THREAD

**Issue by thedewpoint** [argoproj/argo-cd#7914]
I have done a fresh install of k3s on an Oracle ampere 4 core vm. This is an ARM architecture. Upon installing argo the application-controller, the dex-server, repo-server, and server all get stuck in a crashbackoffloop. Many have this error in the logs
```
standard_init_linux.go:228: exec user process caused: exec format error
```
Some googling shows that this is related to using the wrong docker image for the architecture, but I'm unsure what to do to get this to install properly. Searching through the issues on this github has told me that arm is supported but I don't see any special instructions for installing on it.

```
ubuntu@instance-20211211-151:~$ uname -m
aarch64
```

**Comment by fdelucchijr** [comment]
> We don't support arm64 (or other architectures than x86_64) yet.
> 
> There is some ongoing efforts to make this possible:
> 
> #7035 #6366 #4211
> 
> Closing this.

This is a weird issue. The last week I run ArgoCD in one Amphere Cluster without problems. Yesterday in the night I’ve tried to run with same helm chart parameters but getting the same @thedewpoint error.
