### ISSUE TITLE
Updating Opensearch Helm chart fails

### ISSUE THREAD

**Issue by KlavsKlavsen** [argoproj/argo-cd#7924]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**
When I try to upgrade opensearch Helm chart (from v1.0.4 to 1.2.1) - it fails - even with "replace" in 'sync' - with this error:
```
error when replacing "/dev/shm/148566228": StatefulSet.apps "opensearch-cluster-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

**To Reproduce**

install v1.0.4 from https://opensearch-project.github.io/helm-charts - and then v1.2.1 and try to sync.. it fails on statefulset - even with replace set for that it fails.

**Version**

v2.1.7+a408e29

**Comment by acjohnson** [comment]
+1

**Comment by acjohnson** [comment]
This is a opensearch helm chart issue, nothing to do with argo-cd https://github.com/opensearch-project/helm-charts/pull/37#discussion_r769264518

**Comment by KlavsKlavsen** [comment]
so we're sure a helm upgrade would fail in this? seems to me someone would have noticed.. I'll have to try and install + upgrade with helm to see if thats the case then :)

**Comment by acjohnson** [comment]
> so we're sure a helm upgrade would fail in this? seems to me someone would have noticed.. I'll have to try and install + upgrade with helm to see if thats the case then :)

We did notice :sweat_smile:
