### ISSUE TITLE
Add application project as build env var

### ISSUE THREAD

**Issue by ninjaslothx** [argoproj/argo-cd#7946]
# Summary

Add a env var that would pass the applications project to the build vars for use with plugins etc. 
Currently it supports things like ARGOCD_APP_NAME, but would be good to have access to ARGOCD_APP_PROJECT.

https://argo-cd.readthedocs.io/en/stable/user-guide/build-environment/

# Motivation

This would enable easier configuration of various plugins and also help drive some RBAC logic at the plugin level. 

For example the [argocd vault plugin](https://argocd-vault-plugin.readthedocs.io/en/stable/howitworks/) could use the project name to determine the vault role that an application can use without the need for it to be specified in the application manifest directly. 

# Proposal

Add additional var ARGOCD_APP_PROJECT

**Comment by blakepettersson** [comment]
Duplicate of #15185
