### ISSUE TITLE
[UI] Support dry run and hook vs. apply strategy during sync

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#798]
UI currently does not support performing a dry-run sync, or syncing using the apply vs. hook strategy.

**Comment by alexec** [comment]
Can we close this - I don't hear many people asking for it.

**Comment by leominov** [comment]
It's looks helpful for us. In case when we need rollback on another revision without applying migrations that may falls and stops release.

**Comment by alexec** [comment]
This is partially fixed in v1.2

**Comment by alexec** [comment]
Broke into two issues.
