### ISSUE TITLE
Misleading output in App Details view when Retry is not enabled

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#7990]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

In the UI's App Details view, looking at the retry options when retry is not configured, it says "Retry not installed":

![image](https://user-images.githubusercontent.com/3942683/146670744-adc264a3-33ac-451e-b18a-9f58936cccd8.png)

This is a little confusing and suggests that "Retry" is some kind of add-on that has to be installed rather than to be configured.

**To Reproduce**

1. Click on the App Details which doesn't have Retry configured
2. Scroll to "Retry Options"
3. Observe misleading text

**Expected behavior**

It should read "Retry disabled" instead of "Retry not installed"

**Version**

Latest (`v2.3.0+ad1ed1d`)

**Logs**

```
Paste any relevant application logs here.
```

**Comment by pasha-codefresh** [comment]
Thank you @plakyda-codefresh
