### ISSUE TITLE
Private repo credentials deleted from disk before plugin is run

### ISSUE THREAD

**Issue by davemann-mgl** [argoproj/argo-cd#7995]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using ArgoCD 2.2.0 with an existing plugin (Not using the new plugin server), the environment contains a `GIT_SSH_COMMAND` which includes an ssh identity on shared memory containing the private key for the detected repository, placed there by ArgoCD. In the latest changes for the CMP server, the file is deleted before it can be read due to the pluginEnv's being constructed in a seperate `getPluginEnvs` method now which itself does a defer cleanup of the SSH key before the plugin itself has run.

https://github.com/argoproj/argo-cd/blame/6d8ff61b16163e960126f2205166513d924a64a9/reposerver/repository/repository.go#L1142

**To Reproduce**

Create an application with a config management plugin that internally uses git and is pointed at a private repository.
Attempt to refresh the application

**Expected behavior**

The identity file contained in the GIT_SSH_COMMAND is not deleted before the plugin is run

**Screenshots**

N/A

**Version**

2.2.0

**Logs**
```
Warning: Identity file /dev/shm/254152362 not accessible: No such file or directory.
```

**Comment by davemann-mgl** [comment]
https://github.com/argoproj/argo-cd/blame/6d8ff61b16163e960126f2205166513d924a64a9/reposerver/repository/repository.go#L1167 on this commit message you can see it talks on the change being made to support kustomize remote bases. 

We use these, but via a plugin, so that we can pass environment variables down to kustomize (as this is now supported in Kustomize - https://github.com/kubernetes-sigs/kustomize/blob/master/api/kv/kv.go#L163, potentially the default `kustomize` plugin can gain an `env` field?)

**Comment by dhild** [comment]
I ran into this same issue. I may have a simple fix in code; but I am just setting up a test environment for the first time so this may take awhile to validate.

**Comment by eupestov** [comment]
I'd suggest to re-open the issue as the fix was reverted in https://github.com/argoproj/argo-cd/pull/9105

**Comment by jmcshane** [comment]
I have a PR going that should resolve both this issue and #8820. Would love a review: #15107
