### ISSUE TITLE
Argo CD server and repo server fails to start if installed into custom namespace

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#80]
```
ERROR: logging before flag.Parse: E0409 23:04:38.881595       1 reflector.go:205] 
github.com/argoproj/argo-cd/controller/controller.go:76: Failed to list *v1alpha1.Application: applications.argoproj.io is forbidden:
User "system:serviceaccount:argocd-fusion:application-controller" cannot list applications.argoproj.io in the namespace "argocd-fusion"
```

**Comment by merenbach** [comment]
@alexmt trying to determine steps to reproduce.  I tried this and so far it worked:

```
kubectl create namespace argocd-fusion
./dist/argocd install --namespace argocd-fusion
sed -i'.bak' 's/$/ --namespace argocd-fusion/g' Procfile
goreman start
```

**Comment by alexmt** [comment]
@merenbach please use following steps to reproduce:

- install argocd to kubernetes cluster with RBAC enabled into namespace different from argocd. `argocd install --intall-namespace test`

- controller and api server pods are failing to start.

Error happens because installer creates role bindings in argocd namespace always:

- https://github.com/argoproj/argo-cd/blob/master/install/manifests/03c_application-controller-rolebinding.yaml
- https://github.com/argoproj/argo-cd/blob/master/install/manifests/04c_argocd-server-rolebinding.yaml

**Comment by jessesuen** [comment]
Just tried this from tip and it's working. Not sure if you are running older version but the flag `--install-namespace` has been removed since we now look at `--namespace`
