### ISSUE TITLE
Ability to customise values section when deploying a helm chart

### ISSUE THREAD

**Issue by mcbenjemaa** [argoproj/argo-cd#8013]
# Summary

I want to customise and patch argocd application resources using `kustomize`,
 there's no support for patching values because `spec.source.helm.values` is a string.

The only way is to patch with `spec.source.helm.parameters` but that's annoying when you have many nested values.

# Motivation

I'm maintaining apps of apps for many platforms, and I would avoid DRY.

Using  kustomize to  customise my apps in different platforms/ and environments without the need to replicate manifests. single source of truth for my platforms.

# Proposal

How do you think this should be implemented?

Add a field that holds values as raw yaml instead of string (make it backward compatible of course!)

I was assuming that argocd application has a field that supports yaml (like crossplane provider helm does https://github.com/crossplane-contrib/provider-helm/blob/master/apis/release/v1beta1/types.go#L71)

This is a super important feature!

**Comment by Joibel** [comment]
This is the problem I have written https://github.com/crumbhole/argocd-lovely-plugin to solve for myself.

**Comment by joggeli34** [comment]
This would also be handy for changing the values with yq more easily. We are using this to change the image tags when releasing a new image directly from a ci/cd pipeline.

**Comment by crenshaw-dev** [comment]
Closing in favor of duplicate https://github.com/argoproj/argo-cd/issues/2936
