### ISSUE TITLE
Support kubectl.kubernetes.io/default-container annotation

### ISSUE THREAD

**Issue by chicocvenancio** [argoproj/argo-cd#8015]
# Summary

Support `kubectl.kubernetes.io/default-container` annotation. Currently the main use-case is reordering containers on logs view. 

# Motivation

`kubectl.kubernetes.io/default-container` is used to define the container kubectl will pick in operations that act in a container and have none defined (logs, exec, attach, cp). Viewing logs seems to be the relevant operation for argo-cd for now.

# Proposal

The ui would show the container listed in `kubectl.kubernetes.io/default-container` as the chosen container when changing to a pod logs tab. Either through reordering of the containers (default as first), or leaving them in the same order but choosing the default one.

**Comment by jannfis** [comment]
I actually like this proposal from a UX point of view :+1:

**Comment by Mokto** [comment]
That would be super useful when using service meshes (linkerd in my specific case.)
