### ISSUE TITLE
`kubectl auth reconcile` auto-creates namespaces

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#803]
I found some surprising behavior of `kubectl auth reconcile`. This command seems to auto-create namespaces if the rbac resource is of type Role or RoleBinding.  If I run `kubectl auth reconcile --namespace my-namespace` of the following Role:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
rules:
- apiGroups:
  - ""
  resources:
  - pod
  verbs:
  - list
```

From the command output log, kubectl is performing a POST against the namespace endpoint to create it:

```
I1118 03:11:37.985224   89185 loader.go:359] Config loaded from file /Users/jsuen/.kube/config
I1118 03:11:37.992831   89185 loader.go:359] Config loaded from file /Users/jsuen/.kube/config
I1118 03:11:37.994312   89185 decoder.go:224] decoding stream as YAML
I1118 03:11:38.001754   89185 loader.go:359] Config loaded from file /Users/jsuen/.kube/config
I1118 03:11:38.189988   89185 loader.go:359] Config loaded from file /Users/jsuen/.kube/config
I1118 03:11:38.222982   89185 round_trippers.go:405] GET https://REDACTED/apis/rbac.authorization.k8s.io/v1/namespaces/my-namespace/roles/my-role 404 Not Found in 32 milliseconds
I1118 03:11:38.261152   89185 round_trippers.go:405] POST https://REDACTED/api/v1/namespaces 201 Created in 37 milliseconds
I1118 03:11:38.304245   89185 round_trippers.go:405] POST https://REDACTED/apis/rbac.authorization.k8s.io/v1/namespaces/my-namespace/roles 201 Created in 40 milliseconds
role.rbac.authorization.k8s.io/my-role reconciled
```

Since this is unexpectedly creating resources which the user may not expect, we need to prevent this behavior.

/cc @edlee2121

**Comment by edlee2121** [comment]
Creates the namespace if it doesn't exisst? It doesn't recreate it if it does exist, correct?

**Comment by jessesuen** [comment]
Yes it creates the namespace if it doesn't exist. If it already exists than it will not touch it.

**Comment by edlee2121** [comment]
I agree that we shouldn't let users create namespaces as a side effect of deployment since those are cluster-level resources and could allow users to circumvent controls (e.g. ResourceQuota, NetworkPolicy) associated with namespaces.

**Comment by jessesuen** [comment]
Filed an upstream, since the behavior doesn't seem correct, nor documented. https://github.com/kubernetes/kubernetes/issues/71185

But we will need to work-around it by checking for namespace existence first before calling auth reconcile.

**Comment by edlee2121** [comment]
Cool. Would like to hear their thoughts on it. They may be relying on RBAC.

**Comment by jessesuen** [comment]
Fixed

**Comment by jessesuen** [comment]
Reopening due to concerns in:
https://github.com/argoproj/argo-cd/pull/808#issuecomment-440116166

**Comment by jessesuen** [comment]
Fixed (again) in https://github.com/argoproj/argo-cd/commit/db92f0b569d0d633973d9f651fe148fc7bd6ff3e.
