### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by jay-lee-otsk** [argoproj/argo-cd#8033]
**Describe the bug**

![argocd-issue-8033](https://user-images.githubusercontent.com/48072944/147611865-ac32b002-9b3f-44e1-b9dc-c7dc6bb0131f.gif)

When I click **Sync** button, ArgoCD UI crashes with the following error log: 

```
Something went wrong!

Consider submitting an issue here.


Stacktrace:

TypeError: Cannot read properties of null (reading 'index')
    at https://otsk-argocd.xxx.com/main.b7d612426d4d6ec1854c.js:59:392933
    at Array.map (<anonymous>)
    at https://otsk-argocd.xxx.com/main.b7d612426d4d6ec1854c.js:59:392811
    at t.value (https://otsk-argocd.xxx.com/main.b7d612426d4d6ec1854c.js:8:21316)
    at Hi (https://otsk-argocd.xxx.com/main.b7d612426d4d6ec1854c.js:869:70056)
    at Ri (https://otsk-argocd.xxx.com/main.b7d612426d4d6ec1854c.js:869:69851)
    at gs (https://otsk-argocd.xxx.com/main.b7d612426d4d6ec1854c.js:869:105644)
    at fl (https://otsk-argocd.xxx.com/main.b7d612426d4d6ec1854c.js:869:96894)
    at cl (https://otsk-argocd.xxx.com/main.b7d612426d4d6ec1854c.js:869:96819)
    at tl (https://otsk-argocd.xxx.com/main.b7d612426d4d6ec1854c.js:869:93852)
```

**To Reproduce**

(Edited)
_It happened one day of a sudden, so I cannot imagine how to list up the steps to reproduce the issue. Even cannot figure out how to work around this issue. Please help._

I have found the root cause. 
If the secret name has something like this as below, this issue is occurring. Please help resolve it. 
(Please note the **name** part - 35.240.138.122-3997517001)

```
apiVersion: v1
kind: Secret
metadata:
  name: 35.240.138.122-3997517001
type: Opaque
data:
  config: xyz
  name: Y2
  server: aH
```

**Expected behavior**

Sync helper side pop-up screen should show without any errors. 

**Version**

If I changed back to **ArgoCD v2.1.1**, the issue went away.

```shell
argocd: v2.2.0+0f2f9a9
  BuildDate: 2021-11-30T02:49:56Z
  GitCommit: 0f2f9a97e3d3fbeb1eaa1564f7757114905e77db
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.2.1+122ecef
```

**Logs**

Please find the frontend log attached above.

**Comment by pasha-codefresh** [comment]
@jay-lee-otsk I have added secret same as you and it works for me, maybe somebody else can reproduce it

**Comment by jay-lee-otsk** [comment]
Hi @pasha-codefresh 

Thanks for your kind input. 
I guess it probably does not match with your ArgoCD version. 
My colleagues at my workplace are also facing this issue. 
In addition, I included the related video on the top capturing at the moment. 
It should happen when you try `ArgoCD Self Management` with the existing Cluster Secret resource.

**Comment by pasha-codefresh** [comment]
Thank you @jay-lee-otsk . I have reproduced that.

**Comment by jay-lee-otsk** [comment]
Thank you @pasha-codefresh . Please let me know if there is anything I can help.

**Comment by jay-lee-otsk** [comment]
I have checked and confirmed that `ArgoCD v2.2.2` resolved the described issue. Thanks a lot! :)
