### ISSUE TITLE
Make use of API server dry-run in K8s v1.13

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#804]
Today, we do a `kubectl apply --dry-run` of all resources, before performing the actual apply, in hopes of catching any manifest errors before deploying anything to the cluster. This is far from foolproof and the dry-run does not catch a lot of errors that only happen during the `apply` phase, which results in a partial successful deployment. An examples of these may be where a deployment's label selectors do not match the pod template labels.

There is a new API server feature (will be beta in v1.13) which will perform the validation server side, which will improve the experience by performing deeper checks on the user's manifests:

https://github.com/kubernetes/enhancements/issues/576

To support this, we simply need to check if the cluster is running v1.13 and use the new `--server-dry-run` flag in place of `--dry-run`.

**Comment by leoluz** [comment]
Closing this in favor of https://github.com/argoproj/argo-cd/issues/11574
