### ISSUE TITLE
Bundled argocd-notifications troubleshooting commands aren't available

### ISSUE THREAD

**Issue by NickLarsenNZ** [argoproj/argo-cd#8071]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm not sure if it's a bug, or just not yet updated docs...
The docs suggest running commands such as `argocd-notifications template get`

**To Reproduce**

Follow the steps as per docs:
<https://argo-cd.readthedocs.io/en/latest/operator-manual/notifications/troubleshooting/#in-your-cluster>

1. Get a shell on the `argocd-notifications-controller` container
2. Run `argocd-notifications template get`

**Expected behavior**

I'm unsure, as the docs don't give an example of expected output. I assume a list of configured templates.

**Screenshots**

![image](https://user-images.githubusercontent.com/10092581/147819374-33630059-d331-44f4-b737-c2472ea1e93a.png)

**Version**

```shell
argocd: v2.3.0+ae9abe5
  BuildDate: 2021-12-30T02:18:34Z
  GitCommit: ae9abe517579503403edb8c43daa8a490cfaabd6
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

N/A

**Comment by alexmt** [comment]
Thank you for reporting it @NickLarsenNZ ! We need to upgrade documentation to use `argocd admin notifications` subcommand (currently it is `argocd admin argocd-notifications` but should be changed to `argocd admin notifications` )

@pasha-codefresh can you please take a look when you have time? No rush!

**Comment by NickLarsenNZ** [comment]
Perfect, thanks @alexmt.

Feel free to close this issue if there's another one covering doc updates.

```
argocd@argocd-notifications-controller-549bb9885-6zp7t:/app$ argocd admin argocd-notifications trigger get
NAME                    TEMPLATE                 CONDITION
on-created              app-created              true
on-deleted              app-deleted              app.metadata.deletionTimestamp != nil
on-deployed             app-deployed             app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
on-health-degraded      app-health-degraded      app.status.health.status == 'Degraded'
on-sync-failed          app-sync-failed          app.status.operationState.phase in ['Error', 'Failed']
on-sync-running         app-sync-running         app.status.operationState.phase in ['Running']
on-sync-status-unknown  app-sync-status-unknown  app.status.sync.status == 'Unknown'
on-sync-succeeded       app-sync-succeeded       app.status.operationState.phase in ['Succeeded']
argocd@argocd-notifications-controller-549bb9885-6zp7t:/app$ argocd admin argocd-notifications template get
NAME                     PREVIEW
app-created              Application {{.app.metadata.name}} has been created.
app-deleted              Application {{.app.metadata.name}} has been deleted.
app-deployed             {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} is now r...
app-health-degraded      {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{.app.metadata.name}} has degraded.
app-sync-failed          {{if eq .serviceType "slack"}}:exclamation:{{end}}  The sync operation of application {{.app.metada...
app-sync-running         The sync operation of application {{.app.metadata.name}} has started at {{.app.status.operationStat...
app-sync-status-unknown  {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{.app.metadata.name}} sync is 'Unkn...
app-sync-succeeded       {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} has been...
```

**Comment by pasha-codefresh** [comment]
Sure @alexmt , i will take a look as first thing once back from vacation :)

**Comment by pasha-codefresh** [comment]
@NickLarsenNZ @alexmt im working on this ticket
