### ISSUE TITLE
Ubuntu image version has to be upgraded

### ISSUE THREAD

**Issue by velann21** [argoproj/argo-cd#8075]
# Summary

Currently, I can see that we are using the ubuntu docker image version 21.04, based on the official release documents from ubuntu this version is sooner going to end of life to it.

# Motivation

If this happens then it would make all the users who using this argo version will encounter an issue

# Proposal

Proposing to upgrade the image version to `21.10` because it has the support until July 2022

**Comment by sidprak** [comment]
Can we use an LTS image so we don't have to keep updating it so often? If we switch to 20.04, it will remain supported until 2025.

**Comment by jannfis** [comment]
> Can we use an LTS image

We had that discussion when we moved from Debian to Ubuntu, but decided against it: https://github.com/argoproj/argo-cd/issues/5047

**Comment by alexmt** [comment]
Created PR just in case: https://github.com/argoproj/argo-cd/pull/8230 
@jannfis  please let me know if I'm missing something

**Comment by sidprak** [comment]
@jannfis how often do you normally do releases? Is it possible to do a release for this soon since the EOL date for Ubuntu 21.04 was today?
