### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by seblaz** [argoproj/argo-cd#8082]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The docs have a broken link.

**To Reproduce**

Go to the [docs](https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#declarative-configuration) and click on "declarative setup".

**Expected behavior**

The window should focus on the repositories section, but it's not.

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/8080
