### ISSUE TITLE
Repo server incompatible with legacy GPG keyring format

### ISSUE THREAD

**Issue by miguelaeh** [argoproj/argo-cd#8086]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The regular expressions used at `utils/gpg/gpg.go` are not valid for the legacy keyring format. In other words, they fail with the following error when the keyring file is `.gpg` instead of `.kbx`:

```
time="2022-01-04T12:20:47Z" level=fatal msg="Invalid line: pub   2048R/EC571D70 2022-01-04 [expires: 2022-07-03] (len=0)"
```

For Centos 7 repo server is unable to start since it uses the keyring legacy format not the new format.

The following is the different files format for Debian 10 and centos 7:

Debian 10:
```
/app/config/gpg/keys/pubring.kbx
--------------------------------
pub   rsa2048 2022-01-04 [SC] [expires: 2022-07-03]
      D2FA1428F912DF120DB82C18067E960CFA3C67D5
uid           [ultimate] Anon Ymous (ArgoCD key signing key) <noreply@argoproj.io>
```

Centos 7:

```
/app/config/gpg/keys/pubring.gpg
--------------------------------
pub   2048R/124B8B8D 2022-01-04 [expires: 2022-07-03]
uid                  Anon Ymous (ArgoCD key signing key) <noreply@argoproj.io>
```

It looks like just changing the regular expressions won't be enough since the data obtained from each format are also in different formats.

**To Reproduce**

Build Argo CD for Centos 7 and deploy all the components using Centos 7. The repo-server will fail with the following:

```
time="2022-01-04T12:20:47Z" level=info msg="Initializing GnuPG keyring at /app/config/gpg/keys"
time="2022-01-04T12:20:47Z" level=info msg="gpg --no-permission-warning --logger-fd 1 --batch --gen-key /tmp/gpg-key-recipe2209922600" dir= execID=242ff
time="2022-01-04T12:20:47Z" level=info msg=Trace args="[gpg --no-permission-warning --logger-fd 1 --batch --gen-key /tmp/gpg-key-recipe2209922600]" dir= operation_name="exec gpg" time_ms=440.97866600000003
time="2022-01-04T12:20:47Z" level=info msg="Populating GnuPG keyring with keys from /app/config/gpg/source"
time="2022-01-04T12:20:47Z" level=info msg="gpg --no-permission-warning --list-public-keys" dir= execID=1adb7
time="2022-01-04T12:20:47Z" level=info msg=Trace args="[gpg --no-permission-warning --list-public-keys]" dir= operation_name="exec gpg" time_ms=3.832701
time="2022-01-04T12:20:47Z" level=fatal msg="Invalid line: pub   2048R/EC571D70 2022-01-04 [expires: 2022-07-03] (len=0)"
```

**Expected behavior**

Argo CD should work for Centos 7.
I think it will also be a good idea to add tests for Centos.

**Version**

```shell
I have no name!@argo-cd-repo-server-6fb5f79b58-rpngg:/$ argocd version
argocd: v2.2.2+03b17e0
  BuildDate: 2022-01-01T09:13:43Z
  GitCommit: 03b17e0233e64787ffb5fcf65c740cc2a20822ba
  GitTreeState: clean
  GoVersion: go1.17.5
  Compiler: gc
  Platform: linux/amd64
```

**Comment by emirot** [comment]
I just encountered the same issue using `Amazonlinux:2` any ideas on how to fix that?

**Comment by emirot** [comment]
Except setting ARGOCD_GPG_ENABLED to false, is there a better way?

**Comment by emirot** [comment]
building new gpg version on al2: https://github.com/emirot/amazon-linux-gpg

**Comment by jannfis** [comment]
I believe CentOS 7 uses a pretty old 2.0.x version of GnuPG. I think it makes no sense in adding support for something to Argo CD which is not supported upstream anymore. https://gnupg.org/download/index.html lists 2.2.x as the LTS version, and 2.3.x as the current stable one.

Probably it makes more sense to install a recent version of GnuPG to your CentOS 7 based container images.

**Comment by crenshaw-dev** [comment]
Closing this in favor of Jann's suggested workaround (upgrade GnuPG on your CentOS image. Will reopen if that workaround isn't viable!
