### ISSUE TITLE
Option to not allow users to dismiss the ui.banner

### ISSUE THREAD

**Issue by burkempers** [argoproj/argo-cd#8105]
# Summary

I would like a flag in the argocd-cm to be added that would remove the dismiss options in the ui banner.

# Motivation

I have multiple argocd instances per my development, integration, and production environments.  Each of the envs has a different LDAP server that I have argocd configured for user login.  Users between the envs have different LDAP role to give higher or lower privileges in that env.  I use these role to map to argocd-rbac roles.
Since my use case makes me have different argocd I want to use the ui.banner as a static banner to always have up for users to know which argocd instance they are using.
I can just have a custom css style sheet to get the point across this, but then users have to remember which color is what env.  I would like it to just be plan words

# Proposal

Add a ui.banner.static = true or false (default=false) that could be added the the cm that removes the dismiss options in the banner.

**Comment by alexmt** [comment]
Hello @burkempers ,

I think this is already supported. You can add `ui.bannerpermanent: "true" ` setting to disable close button:

https://github.com/argoproj/argo-cd/blob/37851b165e539a1117f2dfd2532adf05d272be21/docs/operator-manual/argocd-cm.yaml#L240

**Comment by burkempers** [comment]
ah, yes it is.  it doesnt work for me currently since i am running 2.1.2.
also https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#atomic-configuration
the argocd-cm.yaml link in that page does not link to that version to show the added options

thank you.

**Comment by saumeya** [comment]
@burkempers, is this still an issue? Or can it be closed? 
I have created a PR to update the docs -  https://github.com/argoproj/argo-cd/pull/10907
