### ISSUE TITLE
Adding a GitHub repository resolves the domain name to my routers public IP

### ISSUE THREAD

**Issue by hannesknutsson** [argoproj/argo-cd#8106]
I have asked for help on Slack, StackOverflow and some Discord servers in which I usually receive good advice. None of those channels have yielded any solution, so now I come here in hope of help.

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When adding my GitHub repository to my newly set up ArgoCD deployment it fails (screenshot attached further down).

As you can see in the last line of the log attached further down; It is trying to connect to the public IP address of the router instead of connecting to the IP address of github.com.

When making the same SSH connection manually from the node/host machine, the IP is resolved correctly and I could access my repo at github.com as expected. I am using cloudflare's 1.1.1.1 server for DNS. I have started a maintenance pod in the same namespace and run ´nslookup github.com´ from there. It resolved the IP address correctly.

I have taken a tcpdump of the request and inspected it in wireshark to make sure it is not the routers firewall that is blocking the request. This proved that ArgoCD is connecting directly to my routers public IP.

I have also checked for network policies restricting egress from the argocd namespace, but could not find any.

When setting up a https:// repository instead of a SSH one, I get the same problem, but it connects to port 443 instead, as expected.

**To Reproduce**

1. Install a kubernetes cluster on some cheap physical machines
2. Install Flannel as CNI add-on
3. Install MetalLB for loadbalancing
4. Install ArgoCD following the "Getting started" guide
5. Add a GitHub git-repository to your new ArgoCD server

**Expected behavior**

It should resolve the domain github.com correctly and set up the repository in ArgoCD without any problems.

**Screenshots**

ArgoCD error message:
![asdfasdfasdfasdf](https://user-images.githubusercontent.com/33489566/148456690-d3edd51d-891e-4c92-8470-03393aae3138.png)

Wireshark:
![asdfqwerasdfqw3erasdfqwer](https://user-images.githubusercontent.com/33489566/148457064-4544c693-b5df-4426-b884-a94012bed464.png)

**Version**

```shell
argocd: v2.2.2+03b17e0
  BuildDate: 2022-01-01T06:27:52Z
  GitCommit: 03b17e0233e64787ffb5fcf65c740cc2a20822ba
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.2.2+03b17e0
```

**Logs**

Output from `kubectl logs -n argocd argocd-repo-server-784b48858f-c57ch` :
```
time="2022-01-06T21:33:53Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Check grpc.request.deadline="2022-01-06T21:34:53Z" grpc.service=grpc.health.v1.Health grpc.start_time="2022-01-06T21:33:53Z" grpc.time_ms=0.102 span.kind=server system=grpc
time="2022-01-06T21:33:54Z" level=error msg="finished unary call with code Unknown" error="error testing repository connectivity: dial tcp <my public IP address>:22: connect: connection refused" grpc.code=Unknown grpc.method=TestRepository grpc.request.deadline="2022-01-06T21:34:54Z" grpc.service=repository.RepoServerService grpc.start_time="2022-01-06T21:33:54Z" grpc.time_ms=41.657 span.kind=server system=grpc
```

**Comment by hannesknutsson** [comment]
I solved my problem!

My /etc/resolv.conf had two lines that caused trouble:
```
domain <my domain>
search <my domain>
```

These lines were put there as a step in the installation of my host machine's OS that I did not realize would affect me in this way. After removing these lines, everything is now working perfectly.

**Comment by blackliner** [comment]
Hi, I have the exact same issue, but commenting out the search domain in `/etc/resolv.conf` seems to not help (did not try a reboot yet).

What is argocd trying to do here? I get that my wildcard domain might lead to a public resolution to my public IP, but what is argocd trying to resolve here?

**Comment by blackliner** [comment]
UPDATE: ok, so it was a nice mix of DNS wildcard and [microk8s using google DNS](https://microk8s.io/docs/addon-dns) by default. What helped was telling microk8s to take my own, internal DNS that know how to resolve the local search domain.

But I think argocd does something weird, what domain does it try to resolve for this "add repo test"?
