### ISSUE TITLE
SSO should support readonly for all authorized github users

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#811]
Currently, Argo CD SSO does not support following use case: readonly role for any authorized github user and admin role for users from some orgs.

Two changes are required:
1.  Upgrade to new dex release which includes https://github.com/dexidp/dex/pull/1340
2. Use separate header for JWT token since cookie might not fit token with all user groups

**Comment by jessesuen** [comment]
Relevant: https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

**Comment by alexmt** [comment]
Both issues are addressed now
