### ISSUE TITLE
feature: run setup script after sync

### ISSUE THREAD

**Issue by zfrhv** [argoproj/argo-cd#8129]
# Summary

after deploying the application for the first time (applying the yaml files), add option to run job (with some service account), that runs some custom setup script and configures the application through its api with basic curl queries.

# Motivation

after installing any operator like keycloak,eck... or any other applications, it would be cool to have an option to run a job that will configure the application.

for example configure certificates, or different authentication configurations, or indices policies, realms, users...

i know its possible to create the job in git and then just tell argo to apply it, but its a lot of work to write a whole deployment + service account + roles + manage the versions for each application.
it would be nice to just have a block where i can paste a setup script just as i can change the values in the helm chart, and then argo will run it after applying the yamls (or run after each sync).

# Proposal

when creating a new app, have optional block at the bottom of the configuration where i could write few curl commands that will setup the application.

it would be also nice to be able to use the resources that are being created in the same app. that way i can use the application service account tokens to have previlages to setup, or i can pull useful information for example the ingress that was created (to know where to connect)

**Comment by BWagener** [comment]
Sounds like your use case can be covered using resource hooks: https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/

**Comment by zfrhv** [comment]
yeah looks great, thank you a lot !

we will try to use it, if i dont reply then everything is perfect 👍
