### ISSUE TITLE
Cluster name in application destination affects controller performance

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#8132]
**Describe the bug**

The cluster name in the application destination affects controller performance. See attached CPU profile:

 https://share.polarsignals.com/fbdddca/
![image](https://user-images.githubusercontent.com/426437/148809519-64790088-01a2-4a29-8b49-4e87fae0a318.png)

**To Reproduce**

The issue is visible on a large Argo CD instance with multiple applications. Each application should be using cluster name instead of cluster server URL

**Expected behavior**

Usage of cluster name should not affect performance.

**Version**

```shell
v2.2.2
```

**Comment by yeya24** [comment]
Hi @alexmt, are you working on this issue now or is it open to take?

**Comment by alexmt** [comment]
Hello @yeya24 , I'm working on it. Just created PR with the fix: https://github.com/argoproj/argo-cd/pull/8133
