### ISSUE TITLE
Config Map support when deploying application via argocd using helm 

### ISSUE THREAD

**Issue by pratyushmck** [argoproj/argo-cd#8151]
Hello Team, We had a scenario where we were looking forward to your opinion- We utilize an enterprise-wide helm chart that has extensive vetted logic. The chart is provided with a values,yaml file and additionally with config map and secrets files via the helm --set-file argument. These are application specific and housed in an external git repository. Our query is when we use argocd coupled with helm for deploying our applications, how do we handle this use case via the declarative setup in argocd?

**Comment by jgwest** [comment]
https://github.com/argoproj/argo-cd/discussions/8150
