### ISSUE TITLE
General questions on ArgoCD

### ISSUE THREAD

**Issue by pavan-kumar-ceemala** [argoproj/argo-cd#8167]
### Discussed in https://github.com/argoproj/argo-cd/discussions/8164

<div type='discussions-op-text'>

<sup>Originally posted by **pavan-kumar-ceemala** January 13, 2022</sup>
Hi,
1st of all, thanks for creating such a wonderful tool, I really liked the ease of deployment, the Git as a source approach, pull mechanism, the sync process etc, this satisfies my small projects, which I've worked till now.
Now I would like to leverage it for a very big project where I need a CD tool which can scale to deploy 500+ microservices per k8s cluster in a multi cluster environment, I've few generic questions to understand if argocd can scale to cater our requirement.

1.  What is an appx upper limit of number of clusters a single argocd can connect and deploy before showing any issues.?
2. How many apps can I create/deploy continuously using argocd before showing any issue?
3. How many max repositories can I configure in argocd?
3. ArgoCD uses kubernetes etcd as its storage, can we externalize this to some other key-value pair storage?

Could you please share any benchmarking reference for the above points, 

Regards,
Pavan
</div>

**Comment by pmorch** [comment]
You might have a better chance of a response in Discussions rather than creating an issue for this.

Also, you're asking others for benchmarks. Have you yourself tried to benchmark this?

**Comment by pavan-kumar-ceemala** [comment]
Thanks for responding @pmorch, I could not try it myself, I'm trying my luck if somebody has done this already and can share here.

**Comment by pavan-kumar-ceemala** [comment]
I will follow up on the discussion one, hence closing this.
