### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by exocode** [argoproj/argo-cd#8181]
Checklist:

* [ X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X ] I've pasted the output of `argocd version`.

**Describe the bug**

I often try to open an application which is still deploying/syncing, then this errors appears in the UI: `Cannot convert undefined or null to object`

```bash
Something went wrong!

Consider submitting an issue here.


Stacktrace:

TypeError: Cannot convert undefined or null to object
    at Object.children (http://localhost:8888/main.1702c5fe397269593f33.js:59:400054)
    at t.render (http://localhost:8888/main.1702c5fe397269593f33.js:59:157038)
    at Hi (http://localhost:8888/main.1702c5fe397269593f33.js:869:70056)
    at Ri (http://localhost:8888/main.1702c5fe397269593f33.js:869:69851)
    at gs (http://localhost:8888/main.1702c5fe397269593f33.js:869:105644)
    at fl (http://localhost:8888/main.1702c5fe397269593f33.js:869:96894)
    at cl (http://localhost:8888/main.1702c5fe397269593f33.js:869:96819)
    at tl (http://localhost:8888/main.1702c5fe397269593f33.js:869:93852)
    at http://localhost:8888/main.1702c5fe397269593f33.js:869:45525
    at t.unstable_runWithPriority (http://localhost:8888/main.1702c5fe397269593f33.js:877:4072)
```

**Expected behavior**

Normally I expect an drawer appearing from right side with status informations.

**Screenshots**
<img width="413" alt="Bildschirmfoto 2022-01-14 um 15 49 27" src="https://user-images.githubusercontent.com/1597621/149535439-a9be33d0-b10a-4da1-8a05-06a33ecfed26.png">

**Version**

```shell
❯ argocd version
argocd: v2.2.1+122ecef.dirty
  BuildDate: 2021-12-17T18:11:03Z
  GitCommit: 122ecefc3abfe8b691a08d9f3cecf9a170cc8c37
  GitTreeState: dirty
  GoVersion: go1.17.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.2.0+6da92a8

```

I hope that's enough information to investigate this issue.

**Comment by jannfis** [comment]
@keithchong Could you have a look at this one, please?

**Comment by keithchong** [comment]
Hi @exocode , looks like you are doing this locally?  Could you use the browser developer tools and try to unminify the source?

**Comment by alexmt** [comment]
UI is probably served by `argocd admin dashboard`. @exocode if you could download and attach http://localhost:8080/main.1702c5fe397269593f33.js it would help as well.

**Comment by exocode** [comment]
I am simply port-forwarding my argocd deployment. The cluster is in the cloud.

And `argocd admin dashboard` returns that:
```
FATA[0000] configmap "argocd-cm" not found
```

Only wanna mention, that I am not using port `8080` I use `8888`

[main.1702c5fe397269593f33.js.zip](https://github.com/argoproj/argo-cd/files/7874578/main.1702c5fe397269593f33.js.zip)

**Comment by exocode** [comment]
> Could you use the browser developer tools and try to unminify the source? (I want to see where Object.children is)

The current problem is, that I have "pending syncs" right now, so the error currently does not appear. but when something is not syncing I will immediately will post it. (It will happen, because it happend often before posting this issue)
