### ISSUE TITLE
Does anyone has syncWindows examples other than provided in the documentation

### ISSUE THREAD

**Issue by raviusit** [argoproj/argo-cd#8197]
### Discussed in https://github.com/argoproj/argo-cd/discussions/8195

<div type='discussions-op-text'>

<sup>Originally posted by **raviusit** January 17, 2022</sup>
Does anyone has syncWindows examples other than those provided in the documentation (https://argo-cd.readthedocs.io/en/stable/user-guide/sync_windows/) 
I am looking for some real-world examples and implementations </div>

**Comment by jannfis** [comment]
Close as duplicate of #8195
