### ISSUE TITLE
The ConfigMap is invalid: metadata.annotations: Too long: must have at most 262144 characters

### ISSUE THREAD

**Issue by kuznero** [argoproj/argo-cd#820]
Does it apply to Argo CD managed helm charts? Can it be overwritten/overcome somehow?

**Comment by jessesuen** [comment]
This error is happening during kubectl apply phase for one of your ConfigMap resources, and is not just specific to helm. We use `kubectl apply` to perform deployments.  One of the downsides of using `kubectl apply` is that it stores the entire spec as an annotation in the object (which it uses to understand how handle defaulted vs. deleted fields). What's happening is that the `data` fields in the ConfiMap is likely exceeding 262144 characters enforced by the K8s API server, and thus it cannot fit in the `last-applied-configuration` kubectl annotation.

Theres not a workaround other than a Sync hook which performs the deploy in a manner different than apply (e.g. kubectl replace). Which helm chart is causing problems?

**Comment by basvandenbrink** [comment]
> 
> 
> This error is happening during kubectl apply phase for one of your ConfigMap resources, and is not just specific to helm. We use `kubectl apply` to perform deployments. One of the downsides of using `kubectl apply` is that it stores the entire spec as an annotation in the object (which it uses to understand how handle defaulted vs. deleted fields). What's happening is that the `data` fields in the ConfiMap is likely exceeding 262144 characters enforced by the K8s API server, and thus it cannot fit in the `last-applied-configuration` kubectl annotation.
> 
> Theres not a workaround other than a Sync hook which performs the deploy in a manner different than apply (e.g. kubectl replace). Which helm chart is causing problems?

@jessesuen This issue occurs when install [Grafana](https://github.com/helm/charts/tree/master/stable/grafana) with a large dashboard using ConfigMaps.

Wouldn't it be better to use `kubectl create` or `kubectl replace`?

I am also curious to the sync hook workaround.

**Comment by phantomnat** [comment]
I also have problem with grafana.
For the workaround adding these annotations to the resources that need to be deleted before apply.
```
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
```

**Comment by cabrinha** [comment]
> I also have problem with grafana.
> For the workaround, try adding these annotations to the resources that need to be deleted before apply.
> 
> ```
>   annotations:
>     "helm.sh/hook": pre-install
>     "helm.sh/hook-weight": "-1"
>     "helm.sh/hook-delete-policy": before-hook-creation
> ```

Using these annotations seems to have kinda-worked... I still get caught up on a few of the larger config-maps. They just won't sync with the same error.

**Comment by Thakurvaibhav** [comment]
> I also have problem with grafana.
> For the workaround, try adding these annotations to the resources that need to be deleted before apply.
> 
>   annotations:
>     "helm.sh/hook": pre-install
>     "helm.sh/hook-weight": "-1"
>     "helm.sh/hook-delete-policy": before-hook-creation

This does not seem to work in case of a grafana dashboards configmap. Please suggest a workaround / fix

**Comment by mprzygrodzki** [comment]
> > I also have problem with grafana.
> > For the workaround, try adding these annotations to the resources that need to be deleted before apply.
> > annotations:
> > "helm.sh/hook": pre-install
> > "helm.sh/hook-weight": "-1"
> > "helm.sh/hook-delete-policy": before-hook-creation
> 
> This does not seem to work in case of a grafana dashboards configmap. Please suggest a workaround / fix

Same problem, annotations doesnt seem to work in case of Grafana chart.

**Comment by jdomag** [comment]
Same here. @kuznero can you reopen the issue?

**Comment by ebuildy** [comment]
Hello @jessesuen  where did you see argocd can use "create" instead of "apply"?

Tried with

```
annotations:
   argocd.argoproj.io/hook: PostSync
   argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
   argocd.argoproj.io/sync-options: Validate=false
```

![Capture d’écran 2021-02-09 à 11 59 38](https://user-images.githubusercontent.com/1219817/107355162-65957400-6acf-11eb-8adf-d5a8210fac71.png)

**Comment by abdennour** [comment]
same issue here . exactly same. 
![image](https://user-images.githubusercontent.com/1788384/110239441-e709e600-7f57-11eb-98e0-2e982d7dc64f.png)

**Comment by abdennour** [comment]
any deadline for fixing this issue ? 
Could you , for example, patching the YAML before applying it ( removing the annotation `last-applied-configuration` , .. so on) ?

**Comment by diranged** [comment]
We just ran into this on a CRD from Strimzi.io:

```
apiextensions.k8s.io/v1beta1/CustomResourceDefinition
strimzi-operator
kafkas.kafka.strimzi.io
 SyncFailed
CustomResourceDefinition.apiextensions.k8s.io "kafkas.kafka.strimzi.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes```

We obviously cannot have the CRD deleted and re-created for an upgrade.. what should we do?

**Comment by alexmt** [comment]
The https://github.com/argoproj/gitops-engine/pull/252 adds special handling for CRDs. Argo CD will try to just use K8S update request for CRDs if `Replace=true` option present. The update won't try to recreate resource so it is safe to use with CRDs.

**Comment by neuwerld3** [comment]
So how can we fix this in the helm chart for ArgoCD?

**Comment by diranged** [comment]
> > We just ran into this on a CRD from Strimzi.io:
> > ```
> > apiextensions.k8s.io/v1beta1/CustomResourceDefinition
> > strimzi-operator
> > kafkas.kafka.strimzi.io
> >  SyncFailed
> > CustomResourceDefinition.apiextensions.k8s.io "kafkas.kafka.strimzi.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
> > ```
> > 
> > 
> >   
> >     
> >     
> >   
> > 
> > 
> > We obviously cannot have the CRD deleted and re-created for an upgrade.. what should we do? This is the resource it's trying to apply: https://github.com/strimzi/strimzi-kafka-operator/blob/0.22.1/install/cluster-operator/040-Crd-kafka.yaml
> 
> @diranged where you able to find a workaround for this particular issue? We are also running into this using the helm chart deployed with argoCD

Upgrade to the latest 2.x series of ArgoCD - it's solved there for you. You might have to then do a manual sync and checkmark "replace".. but otherwise it seems to work for us now.

**Comment by sunilnandihalli** [comment]
@diranged I am facing the same isssue when running a argo-workflow. my argo version is 

argo: v3.0.4+d7ebc54.dirty
  BuildDate: 2021-05-14T06:20:08Z
  GitCommit: d7ebc548e30cccc6b6bfc755f69145147dbe73f2
  GitTreeState: dirty
  GitTag: v3.0.4
  GoVersion: go1.16.3
  Compiler: gc
  Platform: darwin/amd64

How can I fix this?

**Comment by acuteaura** [comment]
This occurs with [kubevela](https://github.com/oam-dev/kubevela/tree/master/charts/vela-core) in the `fluxcd` configmap

**Comment by LukeRobbo** [comment]
Just came across this issue whilst applying changes with large CRDs... if anyone else is having this issue there is now a flag you can use when syncing resources on argocd v2 or later to use replace instead of apply.

**Comment by jessesuen** [comment]
> Just came across this issue whilst applying changes with large CRDs... if anyone else is having this issue there is now a flag you can use when syncing resources on argocd v2 or later to use replace instead of apply.

WARNING, you almost never want to couple `replace` with the `--force` **_especially_** as it pertains to CRDs. `kubectl replace --force` will delete the CRD, then create it. Deleting a CRD means all of the CR instances will be deleted as well, which is likely be devastating to your cluster.

The second problem with `replace` is that it will drop the `last-applied-configuration` annotation. `kubectl apply` relies on this annotation to calculate the correct patch to apply when updating the object and decide what fields needs to be removed.

For something like a ConfigMap, which is a key/value pair of strings, this is maybe not as big a deal. But for more complex objects like a Deployment, losing the `last-applied-configuration` annotation could cause unexpected behavior for subsequent updates by not removing fields as necessary.

**Comment by LukeRobbo** [comment]
> > Just came across this issue whilst applying changes with large CRDs... if anyone else is having this issue there is now a flag you can use when syncing resources on argocd v2 or later to use replace instead of apply.
> 
> WARNING, you almost never want to couple `replace` with the `--force` **_especially_** as it pertains to CRDs. `kubectl replace --force` will delete the CRD, then create it. Deleting a CRD means all of the CR instances will be deleted as well, which is likely be devastating to your cluster.
> 
> The second problem with `replace` is that it will drop the `last-applied-configuration` annotation. `kubectl apply` relies on this annotation to calculate the correct patch to apply when updating the object and decide what fields needs to be removed.
> 
> For something like a ConfigMap, which is a key/value pair of strings, this is maybe not as big a deal. But for more complex objects like a Deployment, losing the `last-applied-configuration` annotation could cause unexpected behavior for subsequent updates by not removing fields as necessary.

Thanks @jessesuen, very valid point, I've only used this in some testing environments where the full on replacement of our CRDs isn't a big issue.

**Comment by gw0** [comment]
> > Just came across this issue whilst applying changes with large CRDs... if anyone else is having this issue there is now a flag you can use when syncing resources on argocd v2 or later to use replace instead of apply.
> 
> WARNING, you almost never want to couple `replace` with the `--force` **_especially_** as it pertains to CRDs. `kubectl replace --force` will delete the CRD, then create it. Deleting a CRD means all of the CR instances will be deleted as well, which is likely be devastating to your cluster.

Just a thought: If you have everything in ArgoCD and self-healing enabled, then all CR instances will eventually get recreated and this should not be so devastating. Or am I missing something?

**Comment by jemag** [comment]
@jessesuen given the `replace` drawbacks you mentioned, what would be the recommended way for ArgoCD users to handle such use cases? 

I am guessing at some point server-side apply could be used (https://github.com/argoproj/argo-cd/issues/2267), but not sure for the best way to proceed meanwhile.

**Comment by lukipro** [comment]
> 
Yes, you are missing the case where a CR is for example database.mongo.xxx.org/v1. Then recreating a CR would actually delete a database and recreate a new one, but empty xD

**Comment by lukipro** [comment]
> > > Just came across this issue whilst applying changes with large CRDs... if anyone else is having this issue there is now a flag you can use when syncing resources on argocd v2 or later to use replace instead of apply.
> > 
> > 
> > WARNING, you almost never want to couple `replace` with the `--force` **_especially_** as it pertains to CRDs. `kubectl replace --force` will delete the CRD, then create it. Deleting a CRD means all of the CR instances will be deleted as well, which is likely be devastating to your cluster.
> 
> Just a thought: If you have everything in ArgoCD and self-healing enabled, then all CR instances will eventually get recreated and this should not be so devastating. Or am I missing something?
Yes, you are missing the case where a CR is for example database.mongo.xxx.org/v1. Then recreating a CR would actually delete a database and recreate a new one, but empty xD

**Comment by magzim21** [comment]
I somehow fixed this issue with the following combination.
```yaml
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - PruneLast=true
```

**Comment by kanwalnainsingh** [comment]
> annotations:
>    argocd.argoproj.io/hook: PostSync
>    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
>    argocd.argoproj.io/sync-options: Validate=false

This helped me fix.

**Comment by jkroepke** [comment]
Please mention that ArgoCD v2.5 is introducing an option to perform a manifest sync with side-server apply.

https://github.com/argoproj/argo-cd/pull/9711

This would resolve this issue, because side-server apply would not create an annotation like `kubectl.kubernetes.io/last-applied-configuration`.

Until its release, you can read about this feature here and why it would resolve this issue inside ArgoCD: https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/sync-options.md#server-side-apply

**Comment by tobilarscheid** [comment]
Hi @jkroepke, any ETA on when ArgoCD v2.5 will be released?

**Comment by jkroepke** [comment]
No. The Milestone on github says something like 1 month passed (https://github.com/argoproj/argo-cd/milestone/26)

**Comment by tobilarscheid** [comment]
Yes, I saw this as well. Though you might know more...

**Comment by crenshaw-dev** [comment]
I'm optimistic that we'll have an RC by the end of this week (i.e. by Friday, October 7).

We've been trying to get multi-source apps into the release, which is the reason for the delay.

**Comment by blackliner** [comment]
Similar thing happens with `kube-prometheus-stack` from `https://prometheus-community.github.io/helm-charts`. The prometheuses.**** CRD is HUGE, makes ArgoCD webUI lag like 1969

**Comment by dlemfh** [comment]
> The [argoproj/gitops-engine#252](https://github.com/argoproj/gitops-engine/pull/252) adds special handling for CRDs. Argo CD will try to just use K8S update request for CRDs if `Replace=true` option present. The update won't try to recreate resource so it is safe to use with CRDs.

> Please mention that ArgoCD v2.5 is introducing an option to perform a manifest sync with side-server apply.
> 
> #9711
> 
> With ArgoCD 2.5+
> 
> ```yaml
> apiVersion: argoproj.io/v1alpha1
> kind: Application
> spec:
>   syncPolicy:
>     syncOptions:
>     - ServerSideApply=true
> ```
> 
> would resolve this issue in ArgoCD, because side-server apply would not create an annotation like `kubectl.kubernetes.io/last-applied-configuration` anymore.
> 
> Until its release, you can read about this feature here and why it would resolve this issue inside ArgoCD: [`master`/docs/user-guide/sync-options.md#server-side-apply](https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/sync-options.md?rgh-link-date=2022-09-14T15%3A43%3A04Z#server-side-apply)

Hey @alexmt, @crenshaw-dev,

now that argocd v2.5 is out, which solution would you recommend for the problem with CRD's being too long?
```
CustomResourceDefinition.apiextensions.k8s.io "kafkas.kafka.strimzi.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

- `Replace=true`

or

- `ServerSideApply=true`

?

**Comment by nallenscott** [comment]
In my experience, `Replace` is substantially faster than `ServerSideApply` when deploying lots of large CRDs, especially when you have a local copy. My CRDs spin up almost instantly with the following setup (if you deploy to the same cluster as Argo, replace the `ApplicationSet` with an `Application`):

1. Use [braid](https://github.com/cristibalan/braid) to copy the CRDs to a local directory (simply `braid update` to trigger a sync in Argo):
```bash
$ braid add --branch main --path bitnami/kube-prometheus/crds https://github.com/bitnami/charts <local_path>/crds
```
2. Create an `ApplicationSet` pointing to the crds in your repo:
```yaml
source:
  path: <path_to_crds>
  repoURL: git@github.com:<username>/<repo>.git
  targetRevision: <branch_or_commit>
```
3. Create an `Application` to deploy the AppSet, or place the AppSet in the path of an existing App:
```yaml
source:
  path: <path_to_app_set>
  repoURL: git@github.com:<username>/<repo>.git
  targetRevision: <branch_or_commit>
```

**Comment by jkroepke** [comment]
@nallenscott Nice catch, but it seems a bit outdated. There is an semi official helm chart now that holds the Prometheus CRDs

https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-operator-crds

which natively allows setup annotations, if required.

Local local copy required

**Comment by nallenscott** [comment]
@jkroepke Yeah, I tried it. Used `Replace` and `ServerSideApply` and CRDs take minutes to sync. My setup syncs almost instantly.

**Comment by jkroepke** [comment]
Not talking about Replace and ServerSideApply. But using the Chart replaces the braid hack

**Comment by nallenscott** [comment]
@jkroepke Clarified my comment.

**Comment by nallenscott** [comment]
Additionally, it seems wise to manage CRDs externally, seeing as helm is unable to upgrade or delete them after they're deployed. From the argo-cd helm repo: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#custom-resource-definitions

**Comment by davhdavh** [comment]
Couldnt argo just recognize this specific error message and use create on it?

**Comment by crenshaw-dev** [comment]
@davhdavh theoretically, but it's not always safe to Replace resources. I think it's better to leave it to the user to decide.

Although, I do think it would be worth adding a note in the UI to say, "Maybe you can use Replace (with the usual safety caveats) or ServerSideApply."

**Comment by Prateek-Wayne** [comment]
for me `kubectl replace` worked 
:)

**Comment by vbqualops** [comment]
https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/

using argocd here is your fix 
for application 


```
        syncOptions:
          - ServerSideApply=true
```
