### ISSUE TITLE
Fails to parse json when argocd handle jsonnet with a shared libary

### ISSUE THREAD

**Issue by peterbean410** [argoproj/argo-cd#8219]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I used the same setup here https://github.com/argoproj/argo-cd/issues/4541 with only the basic.jsonnet file and a `vendored` folder and here is what I got

```
rpc error: code = Unknown desc = Manifest generation error (cached): rpc error: code = FailedPrecondition desc = Failed to unmarshal "jsonnetfile.json": Object 'Kind' is missing in '{ "version": 1, "dependencies": [ { "source": { "git": { "remote": "https://github.com/grafana/grafonnet-lib.git", "subdir": "grafonnet" } }, "version": "master" } ], "legacyImports": false }'
```
**To Reproduce**
1. Run `jb install` to generate vendor folder
 ```
jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@main # Creates `vendor/` & `jsonnetfile.lock.json`, and fills in `jsonnetfile.json`
```

2. move the generated `vendored` folder to the same repo as argocd app, the app has this manifest file `basic.jsonnet`
```
local kp = (import 'kube-prometheus/main.libsonnet') + {
  values+:: {
    common+: {
      namespace: 'monitoring',
    },
  },
};

[kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus)] +
[kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator)] +
[kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter)] +
[kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics)] +
[kp.prometheus[name] for name in std.objectFields(kp.prometheus)] +
[kp.prometheusAdapter[name] for name in std.objectFields(kp.prometheusAdapter)]
```

**Expected behavior**
`prometheus-operator` should have been installed without issue

**Screenshots**
Not applicable

**Version**

```shell
argocd: v2.1.7+a408e29
  BuildDate: 2021-11-17T22:10:27Z
  GitCommit: a408e299ffa743213df3aa9135bf7945644ec936
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.2.2+03b17e0
  BuildDate: 2022-01-01T06:27:52Z
  GitCommit: 03b17e0233e64787ffb5fcf65c740cc2a20822ba
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.7.1+g1d11fcb
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0
```

**Logs**
NA

**Comment by peterbean410** [comment]
Finally settled with `exclude` rules, so closing this issue

**Comment by peterbean410** [comment]
> Hi,
> 
> > Finally settled with `exclude` rules, so closing this issue
> 
> I'm facing the same issue as you, would you mind sharing a bit more about your fix please? I'm currently struggling to work around this issue.
> 
> Thanks!

you can try this

```
spec:
    directory:
      exclude: "**/*.json"
      recurse: true
```

However, I ran into another issue and finally gave up using jb approach and finally built the manifest locally.

**Comment by GlacierWalrus** [comment]
> > Hi,
> > > Finally settled with `exclude` rules, so closing this issue
> > 
> > 
> > I'm facing the same issue as you, would you mind sharing a bit more about your fix please? I'm currently struggling to work around this issue.
> > Thanks!
> 
> you can try this
> 
> ```
> spec:
>     directory:
>       exclude: "**/*.json"
>       recurse: true
> ```
> 
> However, I ran into another issue and finally gave up using jb approach and finally built the manifest locally.

I got here too. The glob pattern is applying to subdirectories, and for me my jsonnetfile.json was on the same level as the jsonnet files I wanted to target, so my exclude pattern is `*.json`

my working config:
```
directory:
  jsonnet:
    libs:
      - jsonnet/vendor
  exclude: "*.json"
```
