### ISSUE TITLE
Escape key should close sliding window in UI

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#8225]
# Summary

In the UI, when a slider window opens, it should be closable using the Escape key.

# Motivation

Better user experience for people using the UI with keyboard and mouse in combination. Being able to close popups/modals using the Escape key seems best practice.

# Proposal

Have the slider closable using the Escape key.

**Comment by reginapizza** [comment]
I'll try to take this one!

**Comment by reginapizza** [comment]
I have a question about implementation... I've gotten it to work, but the way I have it now is that pressing the escape key will close any sliding panel as a default behavior. The change will have to be in argo-ui, which I know workflows also uses. Would this change be okay as a default behavior or would it be better to make it into an optional prop that the the sliding panels in only argo cd use. Please lmk, thanks!

cc @alexmt @rbreeze

**Comment by jannfis** [comment]
Good catch @reginapizza!

@alexec From a workflows UI perspective, would you think this change is something you want to use as well (then we can make it global), or should we make it a property so consumers can decide themselves?
