### ISSUE TITLE
Stop bundling and shipping Helm v2 binaries

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#8228]
# Summary

For backwards-compatibility reasons, we still ship a version of Helm 2 binaries with the Argo CD container image. We have deprecated Helm v2 in v2.0.0 and promised shipping Helm v2 for the next two consecutive releases.

For release v2.4, we should stop bundling and shipping Helm v2 and remove any support for it from the code base.

# Motivation

Helm v2 is end-of-life since a while. We should stop shipping deprecated and potentially dangerous things.

# Proposal

Remove all Helm v2 related assets from our build & ship process.

**Comment by shuker85** [comment]
Hello @jannfis. In addition to binaries should the tests be also removed ? On 1st sight i found lots of places where helm2 is referenced.

**Comment by jannfis** [comment]
Yes, probably everything related to Helm v2 should be removed from the code base.
