### ISSUE TITLE
Self signed certificates prevents access with chrome using kubectl port-forward; identity and access control for argo cd

### ISSUE THREAD

**Issue by jlewi** [argoproj/argo-cd#828]
I followed the getting started guide
https://github.com/argoproj/argo-cd/blob/master/docs/getting_started.md

and deployed Argo.

I'm now trying to connect to Argo using kubectl port-forward

```
kubectl -n argocd port-forward service/argocd-server 8080:80
```

When I now try to connect to the UI via chrome

I get an exception

```
NET::ERR_CERT_INVALID
```

Presumably this is because Argo CD is using a self signed certificate.

Using firefox I was able to add an exception and connect. I'd expect chrome also allows adding exceptions.

Question is why is ArgoCD serving https on port 8080? 

It looks like port 8080 is redirecting automatically to https.

I'm guessing this is because ArgoCD has elevated privileges so extra precautions are being taken to secure it.

In the case of Kubeflow we'd like to manage ingress and login centrally( see figure in https://github.com/kubeflow/kubeflow/issues/11).

In the ideal end state there is a single secure ingress to the cluster which enforces IAM. Access to individual services would be controlled via ISTIO. We'd like user's identity to be securely stored in requests via JWTs. ISTIO can then be configured to reject traffic to individual services based on the JWT.

Likewise, ideally Argo CD would get the user identity from the JWT rather than having its own IAM system.

**Comment by jlewi** [comment]
There's a flag that needs to be set in chrome to allow self-signed certificates for localhost.
https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate

**Comment by jessesuen** [comment]
> It looks like port 8080 is redirecting automatically to https.

That's correct. The default settings are such that the argocd-server can be exposed with type LoadBalancer, or passthrough SSL, and will be secure out of the box.

If you want ArgoCD to work with your own ingress and want to terminate TLS at ingress LB, there is a flag in the API server, `--insecure`, which will disable TLS on the server.

Theres some more details in the ingress docs: https://github.com/argoproj/argo-cd/blob/master/docs/ingress.md docs

**Comment by jlewi** [comment]
Thanks. I think the insecure option is what I was looking for.
