### ISSUE TITLE
UI crash when using proxy

### ISSUE THREAD

**Issue by guilhem** [argoproj/argo-cd#8281]
**Describe the bug**

UI crash when using proxy

![Screenshot-20220126104208-1818x426](https://user-images.githubusercontent.com/486876/151141199-68675a73-eb18-41b8-8cd4-2114773d3fb7.png)

**To Reproduce**

Install argo on a rancher controlled cluster and use proxy:
![image](https://user-images.githubusercontent.com/486876/151141362-f6f0633f-a2dd-4d5f-a2b3-9864f9ea66fe.png)

**Expected behavior**

Having the UI working (it worked with 1.X version)

**Version**

2.2.2

**Comment by jannfis** [comment]
What do you mean by "and use proxy"? 

Use proxy between client (browser) and server (argocd-server), or when there is proxy environment defined for the Argo CD pods?

**Comment by stefangrosaru** [comment]
@jannfis This is a "dynamic proxy" enabled by the Rancher UI, it basically allows you to access services inside the k8s cluster without needing to expose them outside the cluster.

I'm also experiencing this issue, does ArgoCD need to be told about any proxies?

I'm using the same setup to access other internal services such as Prometheus, Grafana, Longhorn, etc. And there are no issues when accessing these services through the Rancher UI.
