### ISSUE TITLE
Sync Failed (Cluster-Bootstrapping) on external cluster due to missing CRD 

### ISSUE THREAD

**Issue by wofr** [argoproj/argo-cd#8282]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**
 
I followed the the instruction using the cluster-bootstrapping ( https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/)  .  I had no problem adding the project (https://github.com/argoproj/argocd-example-apps/tree/master/apps) to argo-cd but the synchronisation does not work for the applications, the sync for the namespaces worsk fine, but for the applications  I always get the error argoproj.io/v1alpha1/Application argocd helm-guestbook  SyncFailed Application.argoproj.io "" not found   and I do not know how to fix it. Any ideas?  (Used Version argocd-server: v2.2.2+03b17e0) (bearbeitet) 

If I do the deployment on the cluster where Argo-Cd is running everything works fine (whole deplyoment)

I thought I solved the problem by extracting the `applications.argoproj.io` CRD form the cluster where ArogCD is running and deploying it manually (with kubectl) on the destination cluster.  Now the project are marked in green and synced but argo-Cd does not create any apps inside ArgoCD nor on the destination cluster.

Argo-CD is running on a GKE cluster
Destination Cluster is also an GKE cluster

**Expected behavior**

Deployment using the Apps of App pattern should work on externl clusters as well, without extracting a CRD manually, at least I would expect it that way. 

**Screenshots**

![image](https://user-images.githubusercontent.com/2195242/151137826-b35d694c-58eb-43bf-b55b-0745e3cbc842.png)

**Version**

argocd: v2.1.8+2fdaf7a
  BuildDate: 2021-12-13T23:21:58Z
  GitCommit: 2fdaf7a9add4ba6d6657d28dc32228419cb8b8f5
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.2.2+03b17e0
  BuildDate: 2022-01-01T06:27:52Z
  GitCommit: 03b17e0233e64787ffb5fcf65c740cc2a20822ba
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.7.1+g1d11fcb
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0

kubectl 

client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1302", GitCommit:"639f3a74abf258418493e9b75f2f98a08da29733", GitTreeState:"clean", BuildDate:"2021-10-21T21:35:48Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}

**Logs**

```
Paste any relevant application logs here.
```

**Comment by wofr** [comment]
The problem seems definilty to be liked to the app of apps pattern.  If I add the application one by one the deployment works like expected.  Otherwise I currently do get the Sync-error

![grafik](https://user-images.githubusercontent.com/2195242/151518215-afdcd0a1-6d39-4733-8c10-352f94c272d5.png)

**Comment by jannfis** [comment]
In an app-of-apps pattern, the `Application` used as parent app needs to have your local cluster and Argo CD namespace (usually `argocd`) as destination.

**Comment by wofr** [comment]
Ok this did the trick.

I adpated my values.yaml 

```
spec:
  destination:
    # Adapt detination url
    server: https://kubernetes.default.svc
    destserver: <IP-dest-cluster>
  source:
    repoURL: git@git.atosone.com:global-manufacturing/energy-simu-deployment-k8.git
    targetRevision: HEAD
```

In my apps yaml I used the  `server: {{ .Values.spec.destination.destserver }}` as destination cluster.  I added the project with `argocd app create energy-simu-devops --repo git@git.atosone.com:global-manufacturing/energy-simu-deployment-k8.git --path argo/apps --dest-server https://kubernetes.default.svc --dest-namespace default`

and now its working.  Maybe its just me but I at this point the documation was somehow misleading for me (https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/) .  Happy it worked out, argocd is just a great tool!!

**Comment by wofr** [comment]
Ok this did the trick.

I adpated my values.yaml

spec:
  destination:
    # Adapt detination url
    server: https://kubernetes.default.svc
    destserver: <IP-dest-cluster>
  source:
    repoURL: git@git.atosone.com:global-manufacturing/energy-simu-deployment-k8.git
    targetRevision: HEAD

In my apps yaml I used the server: {{ .Values.spec.destination.destserver }} as destination cluster. I added the project with argocd app create energy-simu-devops --repo git@git.atosone.com:global-manufacturing/energy-simu-deployment-k8.git --path argo/apps --dest-server https://kubernetes.default.svc --dest-namespace default

and now its working. Maybe its just me but I at this point the documation was somehow misleading for me (https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/) . Happy it worked out, argocd is just a great tool!!

**Comment by markdaniels850** [comment]
which values.yaml did you edit? the app of apps yaml?
