### ISSUE TITLE
Custom repository certificates are removed after addition (v2.2.2+u)

### ISSUE THREAD

**Issue by gorantornqvist** [argoproj/argo-cd#8284]
**Describe the bug**

We had argocd running fine for a while connected with our internal GitLab that uses a certificate issued from our internal PKI.
We had repository certificates containing the host cert, issuing ca cert and root certificate.
Today argocd stopped working with the error "x509: certificate signed by unknown authority"
The repo certs arent displayed in Settings / Certificates and if I try to add them again they are shown but if I reload the page they disappear again.
Cant see any error in pod logs.

We are running version v2.2.2+u (deployed with Openshift Gitops Operator 1.4.0)
We have one identical argocd that run v2.1.8+u and we dont have that issue on that version.

**To Reproduce**

Add repository certificate from internal custom PKI

**Expected behavior**

The repo certs should not be removed.

**Screenshots**

N/A

**Version**

```shell
sh-4.4$ argocd version
argocd: v2.2.2+unknown
  BuildDate: 2022-01-24T18:25:50Z
  GitCommit: 
  GitTreeState: clean
  GoVersion: go1.16.12
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Cant see any errors
```

**Comment by cnukwas** [comment]
We have noticed same issue after OpenShift GitOps operator upgraded to 1.4.0 version. Opened a support case as I don't see an option to revert the operator and Argo CD to an earlier version.

**Comment by iam-veeramalla** [comment]
Hi @gorantornqvist , Thanks for raising the issue. However, this is not the right place. OpenShift-GitOps issues are tracked here.
https://github.com/redhat-developer/gitops-operator

Please feel free to raise an issue there.

**Comment by iam-veeramalla** [comment]
@gorantornqvist I raised an issue with the gitops-operator
https://github.com/redhat-developer/gitops-operator/issues/271

**Comment by gorantornqvist** [comment]
Aaah operator overwrite, of course. 
Thanks ...

**Comment by cnukwas** [comment]
@iam-veeramalla, thanks for the update. I saw your post on RH bug list and workaround details. It's working now.
