### ISSUE TITLE
Clicking text next to radio buttons doesn't work in delete resource dialog

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#8289]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Radio buttons and their associated text are supposed to work the same way -- clicking either should activate a radio button

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/argo-cd?view=tree&resource=
2. Click the ⋮ next to an object, e.g. `argocd-redis-ha-announce-2`:
    ![image](https://user-images.githubusercontent.com/2119212/151272884-2bac16a7-87d4-4544-8568-45b3dfd3f924.png)
3. Click `Delete`
    ![image](https://user-images.githubusercontent.com/2119212/151272970-cf2eaca6-94d6-4a29-b4e0-e88b574bccae.png)
4. Click `FORCE DELETE` or `NON-CASCADING (ORPHAN) DELETE` -- but not the ◎ next to the text

**Expected behavior**

The ◎ should be selected 🔘.

**Screenshots**

**Version**

```shell
{
    "Version": "v2.3.0+ecc3ab3",
    "BuildDate": "2022-01-26T19:14:24Z",
    "GitCommit": "ecc3ab3cabb8a41328a2b5c5d69e819ef4a675c5",
    "GitTreeState": "clean",
    "GoVersion": "go1.17.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.7.2+g663a896",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by surajyadav1108** [comment]
this is non-reproducible in 2.14, we can close this.
