### ISSUE TITLE
Horizontal Scrolling doesn't appear until page end

### ISSUE THREAD

**Issue by saumeya** [argoproj/argo-cd#8298]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The horizontal scroll bar on the tree view and network view doesn't appear till the very end. In larges applications with a lot of resource nodes, it is difficult to scroll horizontally to see child resources.

**To Reproduce**
Visit, https://cd.apps.argoproj.io/applications/argo-cd?resource=  and scroll horizontally.

**Expected behavior**
Horizontal scroll to be visible at all times.

**Screenshots**
![scroll](https://user-images.githubusercontent.com/17771352/151415171-e2349a8b-b305-4a65-9a20-0615eb415945.png)

**Version**

```shell
argocd: v2.0.3+8d2b13d
  BuildDate: 2021-05-27T17:38:37Z
  GitCommit: 8d2b13d733e1dff7d1ad2c110ed31be4804406e2
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v99.99.99+unknown
  BuildDate: 1970-01-01T00:00:00Z
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.7.1+g1d11fcb
  Jsonnet Version: v0.17.0

```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by reginapizza** [comment]
Hey! I've looked into this, I'm not sure if this change is possible without extensive changes to the frontend unfortunately, so I'm not sure if it's worth it especially with the UI v2 in progress. If someone else wants to try their hand at it and prove me wrong I would love to see how you achieved it

**Comment by keithchong** [comment]
Hey @reginapizza , I created a PR for this. Check it out.

![8298-HorizontalScrollBar](https://user-images.githubusercontent.com/7726022/153483649-9d6e61b4-4738-4df4-87ad-1c7647404828.gif)

**Comment by saumeya** [comment]
This looks great @keithchong
