### ISSUE TITLE
argocd delete CLI:  code = PermissionDenied desc = permission denied even though it works

### ISSUE THREAD

**Issue by marcellodesales** [argoproj/argo-cd#830]
# Problem

*  Deleting an app returns an error even though it deletes the app

```
 argocd --auth-token eyJhbG******lkq-2g --server cplane.company.com \
    --insecure app delete services-config-configserver-usw2-dev-dev 
    --cascade false
```

# Current behavior 

*  stderr is set
* exit code is > 0, 
* error message is printed

```
time="2018-11-24T10:17:26Z" level=fatal msg="rpc error: 
    code = PermissionDenied desc = permission denied"
```

# Expected behavior

* The command works
* Exit code = 0
* Success message

**Comment by jessesuen** [comment]
> Deleting an app returns an error even though it deletes the app

I find this very difficult to believe. Here is the delete logic: 

```
func (s *Server) Delete(ctx context.Context, q *ApplicationDeleteRequest) (*ApplicationResponse, error) {
	a, err := s.appclientset.ArgoprojV1alpha1().Applications(s.ns).Get(*q.Name, metav1.GetOptions{})
	if err != nil && !apierr.IsNotFound(err) {
		return nil, err
	}

	s.projectLock.Lock(a.Spec.Project)
	defer s.projectLock.Unlock(a.Spec.Project)

	if !s.enf.Enforce(ctx.Value("claims"), rbacpolicy.ResourceApplications, rbacpolicy.ActionDelete, appRBACName(*a)) {
		return nil, grpc.ErrPermissionDenied
	}
...
``` 

How are you confirming that the app was deleted? If you don't see the app from the Argo CD UI/CLI, it's probably because we filter out apps from your view which you don't have permissions to access.

**Comment by bruno-arruda-base** [comment]
Today I got into the same issue, I made login with admin user and proceeded to delete an application, in `--cascade` mode.

The command returns the error `time="2024-02-06T13:47:17Z" level=fatal msg="rpc error: code = PermissionDenied desc = permission denied"` and exits with error, but the application and resources are deleted successfully from cluster.

I can't understand what ArgoCD is complaining about. This closed issue was the only one closer to what I'm facing here in my environment.

**Comment by GCHQDeveloper926** [comment]
I'm also seeing this problem, server version v2.9.3, client version v2.10.0.

**Comment by msaavedra-healthgorilla** [comment]
I got this problem when scripting commands. When trying to `argocd app ` anything right after deleting (like create or get) I would get the error because it take time to delete (in deleting status). I had to add the `--wait` option.

**Comment by AllanMNoguera** [comment]
I got the same issue, but notice that there might be a communication issue with argocd and k8s cli. I was using `--core true` as per the documentation this uses k8s directly instead of argocd. But if I only use `--core` it works.
