### ISSUE TITLE
Auto Sync parts of a ksonnet application?

### ISSUE THREAD

**Issue by jlewi** [argoproj/argo-cd#831]
Is it possible to configure a subset of components in a kosnnet application for auto sync?

Using the UI, it seems I can only enable sync on the entire application. I also didn't see anyway to define an application consisting of only a subset of ksonnet components.

Here's my use case:

We have an ML application 
https://github.com/kubeflow/examples/tree/master/code_search/kubeflow

that consists of multiple components. Some of these components are batch jobs that are run to train the model. Others are deployments for the UI/Webapp.

I'd like to enable auto-sync for the deployment but not the other components. Trying to auto-sync batch jobs would probably produce undesirable side effects.

As a short term work around I can split my app into multiple ksonnet applications. Long term, I'd prefer not to have two maintain multiple apps just to sync a subset of components.

It would be nice to be able to configure auto-sync on a subset of ksonnet components or modules.

**Comment by jessesuen** [comment]
@jlewi it should be possible to achieve what you are trying to do with a `Skip` resource lifecycle hook:

https://github.com/argoproj/argo-cd/blob/master/docs/resource_hooks.md

To use it, the job which you don't want to get created, should be annotated with the `argocd.argoproj.io/hook: Skip`. When Argo CD sees this annotation (and is performing a hook based sync strategy -- the default strategy and the one used in auto-sync), it will skip the resource when performing the sync.

**Comment by twz123** [comment]
I was also pondering about how to solve a similar use case. My initial thought was to have some label selectors to filter down the stuff that gets synced, just like the `-l` flag to kubectl.

**Comment by jessesuen** [comment]
Since this bug was filed, we now have partial sync. However, as a convenience, we want to have label selection for sync. See https://github.com/argoproj/argo-cd/issues/1241.  Duping this to #1241.
