### ISSUE TITLE
Build environment should be available to kustomize

### ISSUE THREAD

**Issue by jacekszlachtass** [argoproj/argo-cd#8317]
# Summary

Build environment should be available to sources using kustomize.
At the moment this is not supported: https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#build-environment

# Motivation

It is possible to use env variables with kustomize, please see these links:
https://rm3l.org/using-system-envvars-with-kustomize/
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#configmapgenerator
https://github.com/kubernetes/website/pull/30348

# Proposal

How do you think this should be implemented? 

I have no idea how, but I am guessing this could be done the same way as for helm, jsonnet and custom tools.

**Comment by jannfis** [comment]
Maybe this could be extended to also set arbitrary environment variables for kustomize applications, instead of only passing build environment?

**Comment by alexmt** [comment]
This has been implemented already. Please see latest version of build environment: https://argo-cd.readthedocs.io/en/latest/user-guide/build-environment/

**Comment by crenshaw-dev** [comment]
Closing since the original use case is solved. Added an issue for Jann's suggestion.
