### ISSUE TITLE
v2.3.0-rc1 minor manifest image issues

### ISSUE THREAD

**Issue by dlh** [argoproj/argo-cd#8331]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I had some minor issues trying out v2.3.0-rc1.

The manifests for [v2.3.0-rc1](https://github.com/argoproj/argo-cd/releases/tag/v2.3.0-rc1) use `quay.io/argoproj/argocd:v2.3.0-rc1` as the image for deployments, etc, and this image does not exist. The tagged image is [2.3.0-rc1](https://quay.io/repository/argoproj/argocd?tag=2.3.0-rc1&tab=tags), which differs from the naming convention of past releases. I use kustomize to deploy, so a work-around is to use the following block: 

```
images:
- name: quay.io/argoproj/argocd
  newTag: 2.3.0-rc1
```

Also, the `applicationset` image is using `latest`, `quay.io/argoproj/argocd-applicationset:latest`.

**To Reproduce**

1. Attempt to install v2.3.0-rc1 from the manifests:

```kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.0-rc1/manifests/install.yaml```

2. The pods will fail to start, due to image pull errors.

**Comment by alexmt** [comment]
Reopening. https://github.com/argoproj/argo-cd/pull/8336 has to be merged to fix applicationset image tag
