### ISSUE TITLE
argocd repo add -->> error --ssh-private-key-path is only supported for SSH repositories 

### ISSUE THREAD

**Issue by Meza1923** [argoproj/argo-cd#8334]
Hey

I have tried to run - 
**argocd repo add ssh://<azure-devops-git-repo>:22/path/to/repo/ --ssh-private-key-path ./key-for-repo**
to enable connection to the azure-devops repo and I get the next error - 
**FATA[0000] --ssh-private-key-path is only supported for SSH repositories**

As you see I tries to connect to SSH repository so I don't understand why it happen.

It's important to say that I'm in on-perm environment.

By the way, I saw that there is a bug when trying to connect azure-devops repository via https to argocd, that was solved? 
   

**Version**

```shell
argocd: v2.1.2+unknown 
  BuildDate: 2021-10-27T13:19:31Z
  GitCommit:
  GitTreeState: clean
  .
  .
  .
  .
argocd-server: v2.1.2+unknown 
  BuildDate: 2021-10-27T13:19:31Z
  GitTreeState: clean
  .
  .
  .  
```
Thanks a lot,
Guy.

**Comment by samyak-jn** [comment]
Hi @Meza1923,

There is a similar issue that talked about the same issue, kindly take a look [here](https://github.com/argoproj/argo-cd/issues/3016).

**Comment by Meza1923** [comment]
Hey @samyak-jn,
I have tried this change --> ssh://server:22/path/to/repo ssh://git@server:22/path/to/repo/
and now I stuck  with 
**ssh: handshake failed: knownhosts: key is unknown**

Do you familiar with that error? it could happened cause the previous error?

**Comment by samyak-jn** [comment]
Can you print your $HOME/.ssh/known_host, the error that you are getting means that the host is not found on it?

**Comment by Meza1923** [comment]
@samyak-jn 

I can't show you the file content, but I execute this commands
 - ssh-keyscan <servername> >> /root/.ssh/known_hosts
 - ssh-keyscan <servername> | argocd cert add-ssh --batch
and it still annoying with that message.

When I add the flag --insecure-skip-server-verification it's work fine.

**Comment by samyak-jn** [comment]
Aha, I should have been more clear with print, I wanted you to verify it locally.
But, you can refer to this section for more details: [Self-signed & Untrusted TLS Certificates](https://argo-cd.readthedocs.io/en/release-1.8/user-guide/private-repositories/#self-signed-untrusted-tls-certificates).

**Comment by Meza1923** [comment]
thanks a lot, I'm very appreciate your help! 👍
 
I saw in the link you send:
"It can take up to a couple of minutes until the changes performed by the argocd cert command are propagated across your cluster, depending on your Kubernetes setup."
and that was my case, after 1 minute the command worked for me.
