### ISSUE TITLE
Argo cd doesn't respect waves

### ISSUE THREAD

**Issue by alekc** [argoproj/argo-cd#8358]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

Similar to https://github.com/argoproj/argo-cd/issues/5146 and https://github.com/argoproj/argo-cd/issues/5585
**Describe the bug**

When applying multiple argocd application (not apps of the apps) with different sync waves annotations, they are not respected. I.e
Having 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{"argocd.argoproj.io/sync-wave":"-20"},"finalizers":["resources-finalizer.argocd.argoproj.io"],"name":"kyverno","namespace":"argocd"},"spec":{"destination":{"namespace":"runtime","server":"https://kubernetes.default.svc"},"project":"runtime","source":{"chart":"kyverno","helm":{"skipCrds":false,"values":""},"path":"","repoURL":"https://kyverno.github.io/kyverno/","targetRevision":"v2.1.10"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"retry":{"backoff":{"duration":"5s","factor":2,"maxDuration":"3m"},"limit":10},"syncOptions":["CreateNamespace=true"]}}}
  creationTimestamp: "2022-02-03T14:38:47Z"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  generation: 17
  name: kyverno
  namespace: argocd
  resourceVersion: "105603"
  uid: d642eddc-74a9-4b25-8b78-ea3a699a6dcc
spec:
  destination:
    namespace: runtime
    server: https://kubernetes.default.svc
  project: runtime
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: v2.1.10
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 10
    syncOptions:
    - CreateNamespace=true
```
and 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{"argocd.argoproj.io/sync-wave":"0"},"finalizers":["resources-finalizer.argocd.argoproj.io"],"name":"cluster-overprovisioner","namespace":"argocd"},"spec":{"destination":{"namespace":"dummy","server":"https://kubernetes.default.svc"},"project":"runtime","source":{"chart":"cluster-overprovisioner","helm":{"skipCrds":false,"values":"deployments:\n  - name: default\n    replicaCount: 9\n    topologySpreadConstraints:\n      - maxSkew: 3\n        topologyKey: kubernetes.io/hostname\n        whenUnsatisfiable: ScheduleAnyway\n    resources:\n      requests:\n        cpu: 100m\n        memory: 100Mi\n"},"path":"","repoURL":"https://charts.deliveryhero.io/","targetRevision":"0.7.5"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"retry":{"backoff":{"duration":"5s","factor":2,"maxDuration":"3m"},"limit":10},"syncOptions":["CreateNamespace=true"]}}}
  creationTimestamp: "2022-02-03T14:38:47Z"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  generation: 12
  name: cluster-overprovisioner
  namespace: argocd
  resourceVersion: "106793"
  uid: 72774a77-4ce3-4a06-a9ab-e8ef1c0c145e
spec:
  destination:
    namespace: dummy
    server: https://kubernetes.default.svc
  project: runtime
  source:
    chart: cluster-overprovisioner
    helm:
      values: |
        deployments:
          - name: default
            replicaCount: 9
            topologySpreadConstraints:
              - maxSkew: 3
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: ScheduleAnyway
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
    repoURL: https://charts.deliveryhero.io/
    targetRevision: 0.7.5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 10
    syncOptions:
    - CreateNamespace=true
```

Kyverno starts much later 
```
- deployStartedAt: "2022-02-03T14:39:18Z"
    deployedAt: "2022-02-03T14:39:33Z"
```
than overprovisioner
```
 - deployStartedAt: "2022-02-03T14:38:47Z"
    deployedAt: "2022-02-03T14:38:48Z"
```

I've also tried to follow https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/1.7-1.8/#health-assessement-of-argoprojioapplication-crd-has-been-removed and changed my argocd-cm
```
apiVersion: v1
data:
resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
```
(for which btw there is no mention about it here https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/)
but still no luck. 

**To Reproduce**

**Expected behavior**

Resources pass from one wave to another only when the previous wave is finished and all applications are in synced and healthy state

**Screenshots**

**Version**

2.2.3

**Comment by jannfis** [comment]
Hi. Sync-waves only apply during the same sync context, and not globally. So, they are not respected across different Applications, since each Application will have its own sync context.

There is some ongoing effort to implement dependencies between Applications (#7437, #3892).

I think we should close this issue as a duplicate.

**Comment by alekc** [comment]
Oh, I see. Docs description was not clear at all in regard. 

So the only feasible way for this to work (right now) is to wrap these apps inside one giant helm chart to emulate apps of apps behaviour?

**Comment by alekc** [comment]
In my pipeline I did a very bad thing....

 Basically used a wrapper based on
https://artifacthub.io/packages/helm/kiwigrid/any-resource to create a set
of argo applications. In this way argo sees them as apps of apps and
respects wave attributes.

It is ugly but it works. So far I was unable to find a better way to deal
with this issue given my deployment requirements.

**Comment by flaviomoringa** [comment]
But in app of apps how do you define the dependencies using waves? I'm probably missing something obvious here :-( 

And thanks for the help

**Comment by flaviomoringa** [comment]
Did you had to add this: https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/1.7-1.8/#health-assessment-of-argoprojioapplication-crd-has-been-removed ?

**Comment by rafilkmp3** [comment]
this makes waves work ?

**Comment by alekc** [comment]
Yes because in this way, they are under the same context as described in
https://github.com/argoproj/argo-cd/issues/8358#issuecomment-1029759522

**Comment by wrmedford** [comment]
@alekc Could you clarify if this preserved order only during bootstrap? Or does this also preserve order when syncing differences across both applications at the same time?

**Comment by alekc** [comment]
not sure I understand. As long as the apps manifesto are part of the same helm chart (see example above), it will respect the wave settings on them during the installation and during sync stages.
