### ISSUE TITLE
Missing ApplicationSet Controller in ArgoCD-HA Install | v2.3.0-rc2

### ISSUE THREAD

**Issue by KojoRising** [argoproj/argo-cd#8365]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We had recently upgraded to argocd:v2.3.0-rc1 to get the applicationset-controller for free, with no issues.

However when we upgraded to argocd:v2.3.0-rc2, we noticed the applicationset-controller was not present upon building via kustomize. 

**To Reproduce**
Please check screenshots below as well. 

v2.3.0-rc1: https://github.com/argoproj/argo-cd/blob/v2.3.0-rc1/manifests/ha/base/kustomization.yaml
v2.3.0-rc2: https://github.com/argoproj/argo-cd/blob/v2.3.0-rc2/manifests/ha/base/kustomization.yaml

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/29113963/152417863-f6f6eafa-276b-4ca8-85e6-12faaee4b7ef.png)

![image](https://user-images.githubusercontent.com/29113963/152417946-b518bcf3-7f26-4805-b041-81c639cc350e.png)

**Version**

```shell
argocd: v2.3.0-rc2+37f01f6
  BuildDate: 2022-02-02T22:44:15Z
  GitCommit: 37f01f6f3242680c52df44fabe62db090fdf9c1d
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ishitasequeira** [comment]
The process of building ArgoCD add-ons like ApplicationSet has been automated in PR [#8336](https://github.com/argoproj/argo-cd/pull/8336).

**Comment by KojoRising** [comment]
Great, thanks for that!

I was able to add the addon as a resource in our Kustomization.yaml's resources:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- https://github.com/argoproj/argo-cd/manifests/addons/applicationset/stable?ref=v2.3.0-rc4
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.3.0-rc4
```
