### ISSUE TITLE
Application's destination namespace does not override Kubernetes manifests

### ISSUE THREAD

**Issue by rumstead** [argoproj/argo-cd#8386]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When deploying, the application destination namespace does not override what is in the Kubernetes manifests.

**To Reproduce**

Git repo to reproduce: https://github.com/rumstead/argocd-namespace-bug

```shell
❯ k get po -n default                                                                      
No resources found in default namespace.

 ❯ k get po -n notdefault                                                                                                                                               
NAME                                      READY   STATUS              RESTARTS      AGE
demo-app-kust-6c97c4d4-pcvv7              0/1     RunContainerError   3 (98s ago)   7m21s
demo-app-raw-7f6484d5cf-mhkvx             0/1     RunContainerError   0 (50s ago)   2m50s
helm-app-demo-app-helm-6795c89cb5-rl2lp   0/1     ErrImagePull        0             38s
```

```shell
k get applications.argoproj.io -n argocd --no-headers | awk '{print $1}' | xargs -I% kubectl get applications.argoproj.io -n argocd % -o jsonpath --template '{.spec.destination.namespace}{"\n"}'
default
default
default
```

You can see that the applications were deployed to the 'notdefault' namespace instead of the Argo CD destination namespace of 'default'. 

**Expected behavior**
I would expect the Argo CD destination namespace to take precedence. I wasn't able to find any documentation saying the manifests take precedence. At the minimum, I think it should be documented. Happy to contribute it. 

**Screenshots**

**Version**

```shell
argocd: v2.2.3+987f665.dirty
  BuildDate: 2022-01-20T00:38:45Z
  GitCommit: 987f6659b88e656a8f6f8feef87f4dd467d53c44
  GitTreeState: dirty
  GoVersion: go1.17.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.2.4+78d749e
  BuildDate: 2022-02-03T20:41:00Z
  GitCommit: 78d749ec88bea5a5e851fc48b9404fdf067192b6
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.7.1+g1d11fcb
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0

```

**Comment by crenshaw-dev** [comment]
Tiny docs improvement: https://github.com/argoproj/argo-cd/pull/8383

Probably need some more.
