### ISSUE TITLE
Multi-arch for Argo CD

### ISSUE THREAD

**Issue by sbose78** [argoproj/argo-cd#8420]
* @alexmt to consider running builds once per release.
* Figure out who our multi-arch contact would be.

**Comment by grid-dev** [comment]
Possible duplicate to https://github.com/argoproj/argo-cd/issues/3956

**Comment by otterley** [comment]
It looks like this is coming in v2.3.0 since #8108 was applied.

**Comment by crenshaw-dev** [comment]
I think we've done this.  :-) 
<img width="1346" alt="Screenshot of Quay image registry showing that Argo CD supports multi-arch images" src="https://user-images.githubusercontent.com/350466/195860804-980502f1-a480-48a8-99cf-92f42c4c6c1f.png">
