### ISSUE TITLE
Failing to generate login password on the Amazon-Linux ARM64 AWS instance

### ISSUE THREAD

**Issue by odidev** [argoproj/argo-cd#8429]
**Describe the bug**

Hi Team, 

I am working with argocd on the **Amazon-Linux ARM64 AWS instance** and facing issues while generating the password to login to argocd server.  

I am following the getting started guide here: < https://argo-cd.readthedocs.io/en/stable/getting_started/ >. I have confirmed that I am working with the correct namespace as used in this documentation and using the correct yaml file. But while executing the below command to generate the password, I am getting the below error: 
~~~ 
$ kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo 

Error from server (NotFound): secrets "argocd-initial-admin-secret" not found 
~~~ 
It seems that the secret “argocd-initial-admin-secret” is not getting generated.  However, all the resources mentioned in the yaml file are getting generated successfully and are running (as can be verified with `kubectl get all –n argocd` ). 

Things are working properly on the **Ubuntu ARM64 AWS instance**, the issue only exists for **Amazon-Linux ARM64 AWS instance**. 

Can you please provide me with some pointers on the same? Does argocd supports/works on the Amazon-Linux ARM64 AWS instance? 

**To Reproduce**

I am following the getting started guide here: < https://argo-cd.readthedocs.io/en/stable/getting_started/ >.

**Expected behavior**

The secret should contain the password for login.

**Version**

```
  argocd: v2.3.0-rc5+aa54aa7
  BuildDate: 2022-02-05T00:47:53Z
  GitCommit: aa54aa7eda70f5e049c9e25df75221d899efff4b
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/arm64
```

**Logs**

```
$ kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo 

Error from server (NotFound): secrets "argocd-initial-admin-secret" not found 
```

**Comment by jannfis** [comment]
Hi. Can you confirm that the `argocd-server` pod is actually running correctly?

**Comment by jannfis** [comment]
Sorry, clicked the wrong button.

**Comment by odidev** [comment]
@jannfis, thank you for the response. 

I have noticed that the pods are running and crashing very randomly on the Amazon-Linux ARM64 AWS instance. Sometimes “kubectl get all –n argocd” command shows that pods are running. If I check them again after a few minutes, the same pods are seen crashing. This is only the case with Amazon-Linux ARM64 AWS instance. In Ubuntu ARM64 AWS instance, argocd-server is running continuously.  

I have cross-checked by creating a new Amazon-Linux ARM64 AWS instance, the similar behavior is seen again.

**Comment by otterley** [comment]
The issue is most likely that since you're on arm64, there aren't any release builds yet for that architecture. It appears that multi-arch builds for amd64 + arm64 will be available once v2.3.0 is released. Try installing this instead in the meantime:

```
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.0-rc5/manifests/install.yaml
```

When I did this, all but one deployment started its pods, and the `argocd-initial-admin-secret` became available. I was able to log in to the admin web console.

The lone exception is `quay.io/argoproj/argocd-applicationset:v0.3.0`, which appears still not to have a multi-arch image just yet.

**Comment by otterley** [comment]
argocd-applicationset relevant PR: https://github.com/argoproj/applicationset/pull/499

**Comment by odidev** [comment]
@otterley, Thank you for the response.  

I have used the yaml script for the pre-release version, i.e. 2.3.0-rc*, < https://github.com/argoproj/argo-cd/releases/tag/v2.3.0-rc5 >, and everything is working fine now. 

May I know, is there any ETA for v2.3.0?
