### ISSUE TITLE
argocd-util needs static compilation

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#844]
We copy argocd-util into OTS dex container and run dex as a wrapper (so that we can restart it). A recent change I made no longer statically compiles argocd-util, and since dex's container base is alpine, it broke. Need to switch back argocd-util to static compilation. I think the repo-server, application-controller, api-server can remain dynamically linked.

**Comment by zcahana** [comment]
I came across this too today - attempting to start the Dex container results with `/shared/argocd-util: file not found`.

Submitted a small fix at #845.
