### ISSUE TITLE
Expose `--kubectl-parallelism-limit` as an environment variable

### ISSUE THREAD

**Issue by tomelliff** [argoproj/argo-cd#8442]
# Summary

It looks like [not all of the command line flags](https://github.com/argoproj/argo-cd/blob/master/cmd/argocd-application-controller/commands/argocd_application_controller.go#L153-L167) can be passed as environment variables. In particular I'd like to pass the `--kubectl-parallelism-limit` flag as an environment variable.

# Motivation

`--kubectl-parallelism-limit` can be useful to limit memory usage of ArgoCD and prevent OOM deaths when it suddenly syncs a bunch of applications.

We're using kustomize to pull in [the HA manifests](https://github.com/argoproj/argo-cd/tree/master/manifests/ha) and would prefer to just be able to set this with environment variables so we don't need to keep the command in line when overwriting it with kustomize.

# Proposal

[`kubectlParallelismLimit`](https://github.com/argoproj/argo-cd/blob/e01ab05d555b799cba08097710482afac3be601e/cmd/argocd-application-controller/commands/argocd_application_controller.go#L164) doesn't currently have a default that pulls from an environment variable like many of the other config options do so the simplest thing to do is to change it to:

```go
command.Flags().Int64Var(&kubectlParallelismLimit, "kubectl-parallelism-limit", env.ParseNumFromEnv("ARGOCD_APPLICATION_CONTROLLER_KUBECTL_PARALLELISM_LIMIT", 20, 0, math.MaxInt64), "Number of allowed concurrent kubectl fork/execs. Any value less the 1 means no limit.")
```

**Comment by jannfis** [comment]
Please feel free to submit a PR for this :)
