### ISSUE TITLE
Allow application sync by project name

### ISSUE THREAD

**Issue by kamil-wojcik** [argoproj/argo-cd#8469]
# Summary

It would be useful to allow argocd application sync via project name

# Motivation

In my case I would like use call argocd app sync with some arguments that would sync all alls in given project.

Currently it is

# Proposal
There are two ways I think it could be done.
1. Add project label to each application based on the project it belong to so eg. argocd.argoproj.io/project=myproject. 
It could be automatically assigned by argocd.
that way to sync project it would be matter of calling `argocd app sync -l argocd.argoproj.io/project=myproject`
2. Add explicit argument to `argocd app sync -p myproject`. This would be same as for  `argocd app list -p myprject`

**Comment by chetan-rns** [comment]
@kamil-wojcik There is an open PR https://github.com/argoproj/argo-cd/pull/8343 for this feature

**Comment by jessesuen** [comment]
Duplicate of https://github.com/argoproj/argo-cd/issues/8320
