### ISSUE TITLE
Hight CPU consumption  on argocd-application-controller and argocd-repo-server

### ISSUE THREAD

**Issue by bhupenderS012** [argoproj/argo-cd#8471]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

    I am using ArgoCD helm chart for argocd deployment. CPU consumption is high on argocd-application-controller and argocd-repo-server.

      Number of applications running on argocd: 70
      Number of cluster argocd monitoring: 20

      Deployment chart: https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd

**To Reproduce**
    
    ============= **controller deployment configuration** ========
    controller:
    enableStatefulSet: true
    replicas: 9
    env:
      - name: "ARGOCD_CONTROLLER_REPLICAS"
        value: "9"

    ## Application controller commandline flags
    args:
      # -- define the application controller `--status-processors`
      statusProcessors: "10"
      # -- define the application controller `--operation-processors`
      operationProcessors: "5"
      # -- define the application controller `--app-resync`
      appResyncPeriod: "180"
      # -- define the application controller `--self-heal-timeout-seconds`
      selfHealTimeout: "5"
      # -- define the application controller `--repo-server-timeout-seconds`
      repoServerTimeoutSeconds: "60"

    extraArgs:
      - --kubectl-parallelism-limit
      - "10"
    resources:
      limits:
        cpu: 2000m
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi
     
    ========= **Repo Server deployment configuration** ===========
     repoServer:
    # -- Repo server name
    name: repo-server
    autoscaling:
      # -- Enable Horizontal Pod Autoscaler ([HPA]) for the repo server
      enabled: true
      # -- Minimum number of replicas for the repo server [HPA]
      minReplicas: 2
      # -- Maximum number of replicas for the repo server [HPA]
      maxReplicas: 12
      # -- Average CPU utilization percentage for the repo server [HPA]
      targetCPUUtilizationPercentage: 75
      # -- Average memory utilization percentage for the repo server [HPA]
      targetMemoryUtilizationPercentage: 75

    # -- Additional command line arguments to pass to repo server
    extraArgs:
    - --parallelismlimit
    - "2"

    # -- Resource limits and requests for the repo server pods
    resources:
      limits:
        cpu: 3000m
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi

**Expected behavior**

**Screenshots**

**Version**

```shell
Argo CD
v2.2.5+8f981cc
```

**Logs**

```
# I am running 9 replicas of argocd-application-controller
kubectl top pods -n argocd | grep argocd-application-controller
NAME                                                   CPU(cores)   MEMORY(bytes)
argocd-application-controller-0                        7m           76Mi
argocd-application-controller-1                        658m         232Mi
argocd-application-controller-2                        8m           85Mi
argocd-application-controller-3                        2m           31Mi
argocd-application-controller-4                        1512m        594Mi
argocd-application-controller-5                        126m         198Mi
argocd-application-controller-6                        579m         319Mi
argocd-application-controller-7                        570m         240Mi
argocd-application-controller-8                        319m         127Mi

# I am running 12 replicas of argocd-application-controller
kubectl top pods -n argocd | grep argocd-repo-server
NAME                                                   CPU(cores)   MEMORY(bytes)
argocd-repo-server-6f9884bdf8-62x6k                    202m         63Mi
argocd-repo-server-6f9884bdf8-7qv2t                    981m         64Mi
argocd-repo-server-6f9884bdf8-9whc6                    795m         111Mi
argocd-repo-server-6f9884bdf8-bfpvm                    1289m        63Mi
argocd-repo-server-6f9884bdf8-fb6ws                    737m         112Mi
argocd-repo-server-6f9884bdf8-gkbdr                    1176m        136Mi
argocd-repo-server-6f9884bdf8-gn7ch                    1121m        98Mi
argocd-repo-server-6f9884bdf8-mlwtb                    660m         131Mi
argocd-repo-server-6f9884bdf8-prp67                    310m         62Mi
argocd-repo-server-6f9884bdf8-sdr9h                    854m         63Mi
argocd-repo-server-6f9884bdf8-v5shw                    487m         123Mi
argocd-repo-server-6f9884bdf8-vdw4c                    668m         71Mi
```

**Comment by richardpj** [comment]
I am also seeing this behaviour. Repo servers are ok but controller cpu very high on 4 replicas. From the logs it seems to be doing duplicate recon. Is it maybe not repecting the replica count env var?

**Comment by richardpj** [comment]
> I am also seeing this behaviour. Repo servers are ok but controller cpu very high on 4 replicas. From the logs it seems to be doing duplicate recon. Is it maybe not respecting the replica count env var?

I was wrong. The sharding is working. We have 7 external clusters plus in cluster and around 400 apps. Even scaling to 4 controller replicas didn't work.

**Comment by renan-morilha-sentia** [comment]
Any resolution for this issue ?
I'm facing the same, app controller ins tatefulset mode consuming loads of CPU, disregarding of how many replicas it has.

**Comment by jkdihenkar** [comment]
Hi, same issue - did anyone figure out some solution?

**Comment by bogdanmuresan** [comment]
In our case this helped: https://github.com/argoproj/argo-cd/issues/4358#issuecomment-1031983396
We still had the old 1.7.8 deployment running - after deleting it, the CPU usage went back to normal.
Hope it helps.

**Comment by adcoutinho** [comment]
Hi, similar issue here for a specific cluster :(!
In my understand from https://github.com/argoproj/argo-cd/issues/4284#issuecomment-703866390 the number of replicas will only help to share the load against multiple clusters splitting each cluster to a replica, but not a big cluster to several replicas.

**Comment by brat002** [comment]
The same issue. 102 app running, 4 clusters
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/3972720/219272439-58b88dc9-b2f0-44b4-8497-c10086a67d16.png">
<img width="958" alt="image" src="https://user-images.githubusercontent.com/3972720/219272506-d8870068-dcd5-4926-bcdc-b0985b327713.png">

**Comment by brat002** [comment]
https://github.com/argoproj/argo-cd/issues/6108#issuecomment-1171320758 here is workaround

**Comment by rmorilha** [comment]
Yo @brat002 , not sure if this workaround actually works over ArgoCD v2.6.4 (deployment through helm).
In our case here, ArgoCD already has orphaned resources set to false by default on all projects and apps.

Yet (with 3 controller replicas - 3 servers - 3 repo servers + redis ha enabled):
![image](https://user-images.githubusercontent.com/37163836/225245077-5a3d1100-d982-45e2-bc29-26bb2713a13a.png)

Additionally, the throttling high alert spams quite often.
![image](https://user-images.githubusercontent.com/37163836/225245736-ae93ce75-ea90-42cb-a4a7-50bfe3f5c2a0.png)

**Comment by rmorilha** [comment]
Checking over the metrics of argo controller, I could see that even I have 3 replicas, most of the kubectl commands are mainly executed by one replica only (the first replica -0).

Checked the metrics by this expression in grafana, checking the last 24 hours:

`sum(argocd_kubectl_exec_total) by (command, pod)`

**Comment by ebuildy** [comment]
This is fine to increase cpu limit. Actually, you can even dont set cpu limit at all.

Also, you better set memory request and limit to same value.

(I let you search on internet for long explanation ^^)

**Comment by agaudreault-jive** [comment]
The behavior can be configured in [`ignoreResourceUpdates`](https://argo-cd.readthedocs.io/en/release-2.8/operator-manual/reconcile/) to resolve this issue.

For repo-server

**Comment by tman5** [comment]
@agaudreault-jive is this feature scheduled to be back ported to argo 2.7.x? We are using 2.7 and experience this very issue. Or is only moving to 2.8 the solution

**Comment by crenshaw-dev** [comment]
@tman5 fornthe sake of stability, we won't backport such a big feature.

**Comment by tman5** [comment]
@crenshaw-dev If we can't move to 2.8 right away, is there any other workaround for the time being? I read about disabling warnings for orphaned resources, but then discussion how it doesn't help in 2.6+
