### ISSUE TITLE
Continuous deployment of OCI helm charts

### ISSUE THREAD

**Issue by distorhead** [argoproj/argo-cd#8475]
Hi!

# Summary

Automatically rollout latest version of OCI helm chart gitops-style.

# Motivation

I have an application which is bundled as a chart into the OCI container regsitry. This chart is versioned using some semver. I need to rollout this chart by the argocd application automatically based on some policy: always latest semver or latest semver within constraint/mask. This will enable Continous Deployment of my application with argocd.

# Proposal

So I see following variants to implement this:

1. Charts continuous deployment operator. This has similar internal mechanics to the existing argocd-image-updater (https://github.com/argoproj-labs/argocd-image-updater), but simplified algorithm:
    1. Check OCI registry (argocd application repoURL) for the latest version of chart by semver policy (always latest or latest within semver constraint).
    2. Change argocd application targetRevision to this version.
    
    Then argocd will automatically perform its job and rollout new version.

2. There is support for semver constraint/mask in current argocd version for an application with helm repository source, which is not OCI. So we could add support for semver constraints with OCI based charts. As I understand, chart will be updated only on next argocd synchronization. BUT, I don't see any controller which would perform this syncrhonization automatically. Following questions arise:
    1. Will argocd somehow automatically on its own detect latest helm chart version and perform sync?
    2. Does argocd have an ability to resync periodically?

Seems 1st solution is more explicit, straightforward and transparent (current version will always be in the argocd application targetRevision). Maybe there already is another solution to this problem.

I want to implement some solution of the problem and need your feedback to make it right way.

**Comment by distorhead** [comment]
Update. Created MVP to try 1st solution to the problem and get your feedback if possible: https://github.com/argoproj-labs/argocd-image-updater/pull/405.

**Comment by blakepettersson** [comment]
Isn't this something which exists now (various issues with `GetTags` notwithstanding) @alexef?

**Comment by alexef** [comment]
Yes, if your oci registry uses basic auth, then you can just target “*” to get latest version automatically deploued
