### ISSUE TITLE
argocd admin dashboard gives 500 error

### ISSUE THREAD

**Issue by NotAFile** [argoproj/argo-cd#8486]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When testing v2.3.0-rc5, `argocd admin dashboard` does not serve the dashboard, instead it produces the following error:
```
open dist/app/index.html: file does not exist
```

**To Reproduce**

Install rc5, run `argocd admin dashboard`

**Expected behavior**

Dashboard serves normally, as it does with v2.2.5

**Screenshots**

**Version**

```shell
argocd: v2.3.0-rc5+aa54aa7
  BuildDate: 2022-02-05T00:45:42Z
  GitCommit: aa54aa7eda70f5e049c9e25df75221d899efff4b
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.0-rc5+aa54aa7
  BuildDate: 2022-02-05T00:45:42Z
  GitCommit: aa54aa7eda70f5e049c9e25df75221d899efff4b
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: unable to determine ksonnet version: exec: "ks": executable file not found in $PATH
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
$ argocd admin dashboard
Argo CD UI is available at http://localhost:8080
^C⏎
```

**Comment by NotAFile** [comment]
Interestingly, I get a different error with curl:
```
$ curl localhost:8080
<pre>
<a href="gitkeep">gitkeep</a>
</pre>
```

**Comment by NotAFile** [comment]
I further bisected the error to somewhere between v2.2.5 and v2.3.0rc1

**Comment by chetan-rns** [comment]
@alexmt I think the dashboard command relies on the embedded static UI assets. There was a PR to fix it in the Makefile https://github.com/argoproj/argo-cd/pull/7715

**Comment by alexmt** [comment]
@chetan-rns , I've noticed your comment and your PR after creating my own PR, sorry. 


Looks like we implemented almost the same fix, but in https://github.com/argoproj/argo-cd/pull/7715 CI failed since CI host don't have all tools to build UI. In https://github.com/argoproj/argo-cd/pull/8536 I'm using docker build to create UI assets.
