### ISSUE TITLE
Change the new user password created

### ISSUE THREAD

**Issue by bat79a** [argoproj/argo-cd#8509]
**Describe the bug**

Hi all.

I have the admin user enabled, I can login on the UI with this admin user, and have created 2 users with a configmap.

I can list and see this 2 users with :
```
$ argocd account list --port-forward service/argocd-server --insecure
```

But when I want to create password for this 2 new local users like the docs explain, it's impossible :
```
$ argocd account update-password --account baptiste --current-password the_admin_password --new-password the_new_password --port-forward service/argocd-server --insecure
```

return to me :

```
This command can be used to update the password of the currently logged on
user, or an arbitrary local user account when the currently logged on user
has appropriate RBAC permissions to change other accounts.

Usage:
  argocd account update-password [flags]
...
```

**To Reproduce**

helm install ...

**Expected behavior**

Add a password to the new user just created before

**Version**

Tested with the v2.2.2,  the v2.2.3 and the v2.2.5 version of argo-cd.

Thx a lot.
Baptiste.

**Comment by blakepettersson** [comment]
Closing since this is pretty old (and from what I can see, works in newer versions of Argo CD)
