### ISSUE TITLE
3-stage application sync - plan, approve, execute

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#8511]
Currently, when you click sync, you don't have the option of knowing exactly what will happen. This is mostly mitigated by checking the app-diff view. However, it does not cater for sync waves, sync-hooks, or other ordering. 

Lest break the sync into two parts. 

1. Create a "plan".
2. Get the user to "approve" the plan is correct.
3. "Execute" then plan.

The plan is a JSON document stored in Redis that describes the operation. 

Having a plan stored has benefits:

* We can render the plan graphically, showing exactly what action will be executed in what order.
* We can use the plan for auditting.
* We can use plans in rollback and history.

**Comment by crenshaw-dev** [comment]
Similar to #17240, closing because it's unclear what the plan UI should include. I see there are quite a few reactions. Please describe what you believe the plan experience should look like.
