### ISSUE TITLE
UI: Favorite star icon is cut off

### ISSUE THREAD

**Issue by rbreeze** [argoproj/argo-cd#8530]
<img width="360" alt="Screen Shot 2022-02-16 at 09 10 12" src="https://user-images.githubusercontent.com/6250584/154318816-30dc9eaa-f096-4ff1-95d2-f2d6f66ecac4.png">

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Comment by ciiay** [comment]
@rbreeze Could you provide more details how you get this issue? I'm not able to see the same issue from my end.

**Comment by rbreeze** [comment]
I use Safari, so it could be a Safari specific issue. Otherwise, my environment was pretty standard (13" laptop sized browser window)

**Comment by ciiay** [comment]
Yes, it's due to a smaller default font size in Safari and the `line-height` is calculated by the font size.
