### ISSUE TITLE
Helm OCI repositories connectivity test unsupported protocol scheme

### ISSUE THREAD

**Issue by rouke-broersma** [argoproj/argo-cd#8548]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When connecting a helm OCI repository the repository connectivity check marks the connection as failed:

`Unable to connect to repository: rpc error: code = Unknown desc = error testing repository connectivity: Get "xxxxxxxxxxx.azurecr.io/index.yaml": unsupported protocol scheme ""`

However the repository works fine and any applications using this repository can deploy the OCI helm charts.

**To Reproduce**

1. Create a container registry with OCI capabilities such as gitlab registry or azure container registry
2. Create a helm OCI enabled repository credential for the registry
3. See in argocd UI that the repository connection is marked as failed
4. Create an application using this repository and notice that the deployment succeeds

**Expected behavior**

I would expect that since the application deployment can authenticate with the repository just fine, that the repository health check also succeeds.

**Screenshots**

![image](https://user-images.githubusercontent.com/3595932/154469415-af3c8585-a626-4b9c-ae76-9ccf6808d6ed.png)

**Version**

```shell
{
    "Version": "v2.2.5+8f981cc",
    "BuildDate": "2022-02-05T01:33:25Z",
    "GitCommit": "8f981ccfcf942a9eb00bc466649f8499ba0455f5",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.11",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.7.1+g1d11fcb",
    "KubectlVersion": "v0.22.2",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

_Please let me know which logs would be useful to figure out this problem so I can attach those_
```
Paste any relevant application logs here.
```

**Comment by HetrTiXc** [comment]
@rouke-broersma Do you get the same error if you try to sync on an umbrella version, i.e. 1.4.x instead of 1.4.3, of a chart stored in AzureCR? I get the error whenever I try to do so: 
![image](https://user-images.githubusercontent.com/1378912/165460317-f98e642b-cb17-4005-806d-6765732f75e9.png)

**Comment by rouke-broersma** [comment]
I've never tried that but I would assume that fails because argo/helm can't read the repo listing and thus can't determine what version number x should be.

**Comment by HetrTiXc** [comment]
Yeah, it seems to be fine for HTTPS repos, only a problem for OCI ones. After further reading I think that is related to Helm and this bug #6686

**Comment by stevenspinoza** [comment]
For me, it worked just adding the repo when I created the app, also had to figure out the urls segments for the REPO URL and CHART fields.. (not too intuitive)

![image](https://user-images.githubusercontent.com/5944011/178127288-d53b8070-ba85-4d0f-a7f1-81a7835dd7f9.png)

![image](https://user-images.githubusercontent.com/5944011/178127311-731743ab-9098-4400-8959-610e7291f1c8.png)

**Comment by rouke-broersma** [comment]
@stevenspinoza like I said deploying a chat works fine, it's just the connectivity check that fails.

**Comment by alexef** [comment]
The changes in #10641 fix this failing connectivity check for me.

**Comment by jemag** [comment]
I also have this failed connectivity check, even with 2.6.0, : 
![image](https://user-images.githubusercontent.com/7985687/217322304-21b776f1-1967-478c-8e4c-2aa75b36bcdc.png)

**Comment by alexef** [comment]
@jemag if it complains about index.yaml, then it is not oci enabled. Use either no protocol or `oci://` when defining the repo (but not https://)

**Comment by jemag** [comment]
@alexef you can see oci is enabled in the screenshot, as for the protocol, none is specified, just xxx.azurecr.io

**Comment by alexef** [comment]
hmm, okay, that's [really weird then, as the check for index happens only for non-oci](https://github.com/argoproj/argo-cd/blame/master/reposerver/repository/repository.go#L2431)

**Comment by jemag** [comment]
initially I had a typo in my enableOCI that got fixed afterwards. Is there a possibility that somehow the check is still happening even if now OCI is enabled properly?

**Comment by jemag** [comment]
@alexef after manually removing the repo and its associated secret and then adding it back the error is now gone:
![image](https://user-images.githubusercontent.com/7985687/217350453-9e991478-70b0-45ba-874a-e8aecd8dd83b.png)


Seems like the check kept happening since the secret went from `enableOCI: false` to `enableOCI: true`. It would probably be best if the check stops once OCI is properly enabled.

**Comment by alexef** [comment]
I saw this reported somewhere, I believe by @blakepettersson . a broken repo config does not recover after update. you need to remove and recreate.

**Comment by blakepettersson** [comment]
I did (see [comment](https://github.com/argoproj/argo-cd/issues/10218#issuecomment-1359504869)), but I still cannot reproduce this locally (although this is still an issue at `$job` with EKS) ...
