### ISSUE TITLE
ArgoCD ignores immutable secrets with randAlphaNum inside

### ISSUE THREAD

**Issue by jprecuch** [argoproj/argo-cd#8551]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We are trying to migrate our current environment under argoCD. We are using helmcharts for this currently.
Some of our helmchart secrets are using randAlphaNum to generate random password
```
data:
  admini-key: {{ randAlphaNum 88 | b64enc | quote }}
```
We also tried to set immutable option inside of these secrets
```
data:
  admini-key: {{ randAlphaNum 88 | b64enc | quote }}
immutable: true
```
Before sync to argoCD:
```
apiVersion: v1
data:
  admini-key: aWthZVNIQnROTw==
 ```
After sync to argoCD
```
apiVersion: v1
data:
  admini-key: R1dLNGJBZHkwRw==
```
These are fine and preserved during helm upgrades. However when we initially bring this helm environment under argocd, these secrets are deleted and recreated from scratch instead with new random passwords.
This breaks our application because these passwords can not be reset every time we do "sync".

**To Reproduce**

1. Deploy environment with helmchart secret with randAlphaNum and immutable true
2. Add this cluster as application under ArgoCD with using same version (helmchart)
3. Check that secrets are re-created from scratch

**Expected behavior**

argoCD should not ignore immutable field and delete/create secrets which has this set.
Also it shouldn't recreate secret every time we sync when randAlphaNum is specified

**Version**

```shell
argocd: v2.2.5+8f981cc
```

**Comment by jessesuen** [comment]
This is known/documented behavior if you are using non-hermetic config management tooling & features such as randAlpha. See:
https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/diffing.md#diffing-customization

Fundamentally, we work differently than helm because we invoke `helm template` early and often. Whereas helm only invokes this at point of install or upgrade. Unfortunately, there's not much to be done here since we expect hermetic output produced from contents in git.

**Comment by Ornias1993** [comment]
In case someone also hits this:
To ensure it's immutable and works cleanly for argo... use a helm lookup to keep the value the same every helm run regardless of immutable.

**Comment by Amir-Wollman** [comment]
> In case someone also hits this: To ensure it's immutable and works cleanly for argo... use a helm lookup to keep the value the same every helm run regardless of immutable.

This won't work as ArgoCD uses `helm template` which doesn't communicate with the Kubernetes API

**Comment by sysuco** [comment]
Strictly from a what-does-helm-support point of view, `helm template --dry-run=server` does execute `lookup` towards the server during templating operations

**Comment by mordax7** [comment]
I am having a similar issue which I described here: https://github.com/bitnami/charts/issues/29758#issuecomment-2424378424

From my understanding I should not use ´randAlphaNum´ for Helm secrets?
