### ISSUE TITLE
UI: Application Health Status bar toggle is broken

### ISSUE THREAD

**Issue by rbreeze** [argoproj/argo-cd#8569]
The Application health status bar toggle (the ruler icon to the right of the search bar on the Applications List page) is broken; clicking this button once hides the status bar as intended, but clicking again does not re-show the status bar. 

Using Safari v15.1

**Comment by reginapizza** [comment]
I'll try to take a look at this

**Comment by terrytangyuan** [comment]
@reginapizza I wasn’t aware of this issue earlier until @ciiay brought it up during code review. This will be fixed by https://github.com/argoproj/argo-cd/pull/8668.
