### ISSUE TITLE
Show sync wave order in UI

### ISSUE THREAD

**Issue by bdelage** [argoproj/argo-cd#8598]
# Summary

It would be nice to be able to sort or show the Sync wave information within an App in the UI.

# Motivation

It would be especially interesting for those of us who use the App of Apps pattern in combination with the Sync waves.

- Easier for operators to see the waves 
- Investigate which app is preventing another app of deploying
- Identify Apps that are in the same wave without having to look at the manifests

# Proposal

![image](https://user-images.githubusercontent.com/64499127/155412305-3b6c8166-8802-4004-8246-538fc5d82ba5.png)
The List view could show the Sync wave number.

Maybe a dedicated view that would show a Tree view of the resources grouped/organized by waves.

**Comment by keithchong** [comment]
Yi said she wants to look into this.

**Comment by ciiay** [comment]
@bdelage Do you have an example app which configured with sync-waves?

**Comment by bdelage** [comment]
@ciiay I cannot share it here. But in our case we have a "root-app" which is a helm chart, and the chart contains multiple App manifests and all those manifests are part of different waves so they get deployed according to dependencies. Some manifests can be part of the same waves as they are not interdependent.

**Comment by ciiay** [comment]
Hi @bdelage , I looked into this issue and I noticed that not every resource has an annotation about sync. And the current list view page doesn't have any kind of sorting feature. So how about we add a toggle button to enable sorting with "Sync order"? The sorting logic references this link: https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/#how-does-it-work. Let me know how you think.

**Comment by ciiay** [comment]
Or just show the sync-wave first in this issue?

**Comment by bdelage** [comment]
@ciiay showing the sync-wave in the UI would already be a good start, sorting by "Sync Order" would be awesome :)
