### ISSUE TITLE
Support for customizable resource actions as Lua scripts

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#86]
Repurposing this issue for a different proposal:

A use case is to perform some kind of custom action on an application resource. Some example actions are:

* pause / resume an Argo Rollout
* suspend / resume a CronJob
* set some istio traffic shaping weights on a VirtualService

This proposal is to support customized actions on application resources. These actions would be made available from the API and CLI. The "action" would be a lua script that mutates the resource object in some way.

Some considerations:
* we may need a way to list available actions on a resource (to present in UI). For example, if a cronjob is suspended, then it should show "resume" as an available action but not "suspend"
* some actions may require inputs. For example, to set weights for a Istio VirtualService
* actions may return errors. For example, if someone supplied invalid input to an action

**Comment by alexmt** [comment]
working on it

**Comment by alexmt** [comment]
Done!
