### ISSUE TITLE
Can't publish the argocd-example-apps demo

### ISSUE THREAD

**Issue by SeibertronSS** [argoproj/argo-cd#8619]
I want to publish a demo through the UI interface , but I get the following error
`
Unable to create application: application spec for guestbook is invalid: InvalidSpecError: repository not accessible: rpc error: code = Unknown desc = error testing repository connectivity: Get "https://github.com/argoproj/argocd-example-apps.git/info/refs?service=git-upload-pack": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
`

The git repo is `https://github.com/argoproj/argocd-example-apps.git`
Is it because my cluster cannot access github?

**Comment by crenshaw-dev** [comment]
It does look like a github access issue. Can you post your Application spec so I can try to reproduce the issue?

**Comment by SeibertronSS** [comment]
I have found out the reason because my machine can't access GitHub..........



---- 回复的原邮件 ----
| 发件人 | Michael ***@***.***> |
| 日期 | 2022年03月02日 00:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [argoproj/argo-cd] Can't publish the argocd-example-apps demo (Issue #8619) |

It does look like a github access issue. Can you post your Application spec so I can try to reproduce the issue?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by crenshaw-dev** [comment]
@SeibertronSS gotcha. Closing unless you need further guidance! Hope you're able to restore GitHub access.

**Comment by saddique164** [comment]
> I have found out the reason because my machine can't access GitHub..........
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Michael ***@***.***> | | 日期 | 2022年03月02日 00:00 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [argoproj/argo-cd] Can't publish the argocd-example-apps demo (Issue #8619) | It does look like a github access issue. Can you post your Application spec so I can try to reproduce the issue? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

I am facing the exactly same issue. could you please tell me how did you resolve it?
