### ISSUE TITLE
How to Integrate Checkmarx scan into argocd

### ISSUE THREAD

**Issue by rushikeshsawant143** [argoproj/argo-cd#8691]

**Comment by keithchong** [comment]
Hi @rushikeshsawant143 , I'm not familiar with Checkmarx, but could you elaborate on your request?

**Comment by todaywasawesome** [comment]
@rushikeshsawant143 security scanning should be done in CI/CD pipelines that are creating the image. You can add attestations with cosign and then use Kyverno or OPA gatekeeper to verify those attestations before.
