### ISSUE TITLE
applicationset-controller not included in the HA Kustomization

### ISSUE THREAD

**Issue by chrism417** [argoproj/argo-cd#8699]
The applicationset-controller is not included here: https://github.com/argoproj/argo-cd/blob/v2.3.0/manifests/ha/cluster-install/kustomization.yaml

Therefore it's not being deployed as part of version 2.3.0.

**Comment by ohauer** [comment]
It is, https://github.com/argoproj/argo-cd/blob/v2.3.0/manifests/ha/base/kustomization.yaml

**Comment by crenshaw-dev** [comment]
@ohauer I'm pretty sure it's not. It's added to the compiled install.yaml as a separate build step, but it's not included in the kustomization.yaml by default. https://github.com/argoproj/argo-cd/blob/f90514587bafcce51e0e2cd6044195fed2266707/hack/update-manifests.sh#L30

**Comment by rwong2888** [comment]
Below works for me, but maybe we can PR addons into the ha kustomization

```
kind: Kustomization

bases:
- github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.3.0
- github.com/argoproj/argo-cd/manifests/addons/applicationset/stable?ref=v2.3.0
```

**Comment by rainerfrey-inxmail** [comment]
It is also not included in non-HA Kustomize manifests. At the very least it should be mentioned in the upgrade guide. That only says to remove references to https://github.com/argoproj-labs/applicationset, but not to add a reference to the add-on kustomization.

Also  github.com/argoproj/argo-cd/manifests/addons/applicationset/stable?ref=v2.3.0 just refers to https://raw.githubusercontent.com/argoproj/applicationset/v0.4.1/manifests/install.yaml (i.e. the generated install, not the customisation directory), in the old repository where the readme says that it's deprecated.

**Comment by rainerfrey-inxmail** [comment]
> It is also not included in non-HA Kustomize manifests. At the very least it should be mentioned in the upgrade guide. That only says to remove references to https://github.com/argoproj-labs/applicationset, but not to add a reference to the add-on kustomization.
> 
> Also github.com/argoproj/argo-cd/manifests/addons/applicationset/stable?ref=v2.3.0 just refers to https://raw.githubusercontent.com/argoproj/applicationset/v0.4.1/manifests/install.yaml (i.e. the generated install, not the customisation directory), in the old repository where the readme says that it's deprecated.

All this applies to the Branch release-2.3, it seems to be already addressed in master
