### ISSUE TITLE
ArgoCD cannot connect to gitlab helm repository with escaped characters

### ISSUE THREAD

**Issue by matt-demers** [argoproj/argo-cd#8710]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to connect to a gitlab helm repository from their [package registry](https://docs.gitlab.com/ee/user/packages/helm_repository/) by creating a new repo using https in the UI.

The URL I'm trying to use is structured like https://gitlab.example.com/api/v4/projects/{my-project-id}/packages/helm/stable

You can see from the linked documentation, the registry supports the `project-id` being either the gitlab project id number, or a URL-encoded path to the project (like `group%2Fproject`),

so in full I am trying to set the repository URL to `https://gitlab.example.com/api/v4/projects/mygroup%2Fmyproject/packages/helm/stable`

When I use the helm CLI to connect to that URL, things work fine.

If I use the project id directly in argo, the helm repository connects just fine, but if I try to use the escaped path to the project, the repo fails to connect. I can see in the repo server logs there is an error 

```
repo-server time="2022-03-07T23:20:27Z" level=error msg="finished unary call with code Unknown" error="error testing repository connectivity: failed to get index: 404 Not Found" grpc.code=Unknown grpc.method=TestRepository grpc.request.deadline="2022-03-07T23:21:27Z" grpc.service=repository.RepoServerService grpc.start_time="2022-03-07T23:20:27Z" grpc.time_ms=83.696 span.kind=server system=grpc        
```

I traced the error message back to this section of the code: https://github.com/argoproj/argo-cd/blob/f36510200caf4d080ef31ecaee94d9996bce1dcf/util/helm/client.go#L293

The url.Parse function is automatically removing the escaped characters in the URL.

I threw it into a simple example go program to inspect the URL object and this is the output
```go
func main() {
	a, _ := url.Parse("https://gitlab.example.com/api/v4/projects/abc%2Fdef/charts")
	fmt.Printf("%+v\n", *a)
}
```
```shell
{Scheme:https Opaque: User: Host:gitlab.example.com Path:/api/v4/projects/abc/def/charts RawPath:/api/v4/projects/abc%2Fdef/charts ForceQuery:false RawQuery: Fragment: RawFragment:}
```

It would be nice to be able to use the escaped path because we will have a lot of projects we need to add, and maintaining a map of project name to project id is not ideal.

**Version**

```shell
argocd: v2.2.3+987f665.dirty
  BuildDate: 2022-01-20T02:00:16Z
  GitCommit: 987f6659b88e656a8f6f8feef87f4dd467d53c44
  GitTreeState: dirty
  GoVersion: go1.17.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.2.3+987f665.dirty
  BuildDate: 2022-01-20T02:00:16Z
  GitCommit: 987f6659b88e656a8f6f8feef87f4dd467d53c44
  GitTreeState: dirty
  GoVersion: go1.17.6
  Compiler: gc
  Platform: darwin/amd64
  Ksonnet Version: unable to determine ksonnet version: exec: "ks": executable file not found in $PATH
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0
```

**Comment by keithchong** [comment]
Hi Matt, thank you for providing the details and tracking down the issue. Perhaps we should use EscapedFragment() instead.

`repoURL.EscapedPath()`
