### ISSUE TITLE
Hanging to delete prometheus-operator

### ISSUE THREAD

**Issue by wotkddl21** [argoproj/argo-cd#8712]
Checklist:

* [O] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [O] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I'm using prometheus operator with kube-prometheus-stack helm chart.

I made an argocd app "kube-prometheus-stack" with the chart above.

After sync the app, it is successful to deploy prometheus operator.

As you know, the prometheus operator generates the desired prometheus statefulset and keeps the prometheus alived so that there is no statefulset.yaml for prometheus in my helm chart.

When I try to delete the app, the argocd tries to delete prometheus statefulset.

Whenever the argocd deletes the prometheus statefulset, my prometehus operator generates prometheus statefulset...!

So there was infinite ping-pong between argocd and prometheus operator.

Only after I deleted the prometheus operator manually, the app can be deleted.

**To Reproduce**
1. Using kube-prometheus-stack (https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) with maing directory charts including node-exporter, grafana and kube-state-metrics templates, generates base helm chart.

2. With kustomization.yaml, makes the argocd app for the helm chart above.

3. Visit argocd GUI and press button "SYNC" for the app above.

4. After sync, press button "delete" for the app above.

5. Then there would be infinite war between the argocd which wants to kill prometheus statefulset and prometheus operator which tries to keep prometheus alived.

**Expected behavior**

The app should be deleted clearly.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

It would be useful for user to choose the order of deletion of manifests before the argocd deletes them.

**Comment by wotkddl21** [comment]
argocd version 2.1.6

**Comment by duizabojul** [comment]
Any update on this?

**Comment by wotkddl21** [comment]
I didn't change anything but the prometheus-operator deleted before the prometheus object.
So the total app deleted well...
I want to reproduce this bug, but I can't
