### ISSUE TITLE
ArgoCD 2.3.x - no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1" on Kubernetes 1.22.x

### ISSUE THREAD

**Issue by amoravek** [argoproj/argo-cd#8756]
**Describe the bug**

Installing ArgoCD 2.3.0 or 2.3.1 on Kubernetes 1.22.5 fails with:

Error: INSTALLATION FAILED: failed to install CRD crds/crd-application.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

Using Helm chart from https://argoproj.github.io/argo-helm

**To Reproduce**
Run:
helm install argocd argo/argo-cd --version 2.3.1 --create-namespace 
on Kubernetes 1.22.x

**Expected behavior**

ArgoCD 2.3.1 is successfully installed on Kubernetes 1.22.x

**Version**

```shell
argocd: v2.3.1+b65c169
  BuildDate: 2022-03-11T00:01:03Z
  GitCommit: b65c1699fa2a2daa031483a3890e6911eac69068
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
$ helm install argocd argo/argo-cd --version 2.3.1 --create-namespace
Error: INSTALLATION FAILED: failed to install CRD crds/crd-application.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

**Comment by shuker85** [comment]
You need to provide the `Chart Version` in helm install, in this case 4.2.1
```
helm search repo argo/argo-cd
NAME        	CHART VERSION	APP VERSION	DESCRIPTION                                       
argo/argo-cd	4.2.1        	v2.3.1     	A Helm chart for Argo CD, a declarative, GitOps...
```

**Comment by amoravek** [comment]
oh, you're right. thank you
