### ISSUE TITLE
Port-forward timeout

### ISSUE THREAD

**Issue by bappr** [argoproj/argo-cd#876]
When doing the port-forward to the argo-cd server, I am getting a lot of timeout and I have to restart the port-forward. It s very annoying since I am expecting my UI to be accessible all time through this port-forward.

Is this a known issue? any workaround (except exposing the endpoint)?

**Comment by jessesuen** [comment]
I don't think this is an argo-cd issue. Do you see errors in `kubectl port-forward`? Maybe this will help:

https://stackoverflow.com/questions/47484312/kubectl-port-forwarding-timeout-issue

**Comment by bappr** [comment]
Actually, it s only happening with `argo-cd`.

```
kubectl port-forward -n argocd svc/argocd-server 8081:80
Forwarding from 127.0.0.1:8081 -> 8080
Forwarding from [::1]:8081 -> 8080
Handling connection for 8081
Handling connection for 8081
E1205 14:32:13.727126   21412 portforward.go:303] error copying from remote stream to local connection: readfrom tcp6 [::1]:8081->[::1]:58157: write tcp6 [::1]:8081->[::1]:58157: write: broken pipe
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
E1205 14:33:07.313769   21412 portforward.go:303] error copying from remote stream to local connection: readfrom tcp6 [::1]:8081->[::1]:58190: write tcp6 [::1]:8081->[::1]:58190: write: broken pipe
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
E1205 14:35:20.650357   21412 portforward.go:303] error copying from remote stream to local connection: readfrom tcp6 [::1]:8081->[::1]:58513: write tcp6 [::1]:8081->[::1]:58513: write: broken pipe
E1205 14:36:42.490481   21412 portforward.go:303] error copying from remote stream to local connection: readfrom tcp6 [::1]:8081->[::1]:58273: write tcp6 [::1]:8081->[::1]:58273: write: broken pipe
```

**Comment by kuznero** [comment]
I also observe this behavior. But to be fare this happened to other services too.

**Comment by bappr** [comment]
I am getting this timeout much more than any other services actually.
Mostly when updating/syncing/creating an application.

**Comment by mnaser** [comment]
I am running into this quite often... and it's only specifically with Argo's UI

**Comment by ecurtin2** [comment]
This commonly happens to me at work behind corporate firewalls, etc but I haven't noticed it if I use argo ui on local machine (minikube / docker-for-mac k8s)

**Comment by philippeboyd** [comment]
Happens to me too when running with Minikube
```
Forwarding from 127.0.0.1:9999 -> 8080
Forwarding from [::1]:9999 -> 8080
Handling connection for 9999
Handling connection for 9999
Handling connection for 9999
Handling connection for 9999
Handling connection for 9999
Handling connection for 9999
E0220 10:44:49.462605    3899 portforward.go:372] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:9999->127.0.0.1:54136: write tcp4 127.0.0.1:9999->127.0.0.1:54136: write: broken pipe
```

**Comment by melalj** [comment]
Same here. The port forwarding keeps timing out.

**Comment by L-U-C-K-Y** [comment]
Having the same issue with the newest argocd version:

```
Handling connection for 8080
E0903 15:36:48.756701   11386 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured
Handling connection for 8080
E0903 15:37:18.759391   11386 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured
Handling connection for 8080
E0903 15:37:48.766846   11386 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
E0903 15:40:42.781019   11386 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured
E0903 15:40:46.358790   11386 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured
E0903 15:40:46.359085   11386 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured
Handling connection for 8080
E0903 15:41:16.362030   11386 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
```

**Comment by cfarrend** [comment]
Experiencing the same, thought it was an issue with resources but after increasing them I still get time outs. Usually happens after the pod has been up for a few hours, the fix has just been to kill the pod.

**Comment by kheraud** [comment]
Same experience here

```
Handling connection for 8080
Handling connection for 8080
E0204 10:11:09.966242   15947 portforward.go:372] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:8080->127.0.0.1:51138: write tcp4 127.0.0.1:8080->127.0.0.1:51138: write: broken pipe
Handling connection for 8080
E0204 10:11:10.662920   15947 portforward.go:372] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:8080->127.0.0.1:51140: write tcp4 127.0.0.1:8080->127.0.0.1:51140: write: broken pipe
```

I have this issue when I port forward to argocd-server. No problem when port-forwarding to other pods

**Comment by MiteshSharma** [comment]
Even I am facing the same issue on the Kubernetes server. Although after a few retries i am able to open UI.

```
kubectl port-forward svc/argocd-server -n argocd 8080:443
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
E0206 14:26:07.317868   30094 portforward.go:362] error creating forwarding stream for port 8080 -> 8080: Timeout occured
Handling connection for 8080
E0206 14:27:02.968909   30094 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured
Handling connection for 8080

**Comment by edersonbadeca** [comment]
I have this issue too running in minikube when I try to sync some app.

```
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
E0420 16:34:27.261994   40277 portforward.go:372] error copying from remote stream to local connection: readfrom tcp6 [::1]:9001->[::1]:60542: write tcp6 [::1]:9001->[::1]:60542: write: broken pipe
E0420 16:34:27.264820   40277 portforward.go:372] error copying from remote stream to local connection: readfrom tcp6 [::1]:9001->[::1]:60540: write tcp6 [::1]:9001->[::1]:60540: write: broken pipe
E0420 16:34:28.407587   40277 portforward.go:372] error copying from remote stream to local connection: readfrom tcp6 [::1]:9001->[::1]:60520: write tcp6 [::1]:9001->[::1]:60520: write: broken pipe
E0420 16:34:28.408755   40277 portforward.go:372] error copying from remote stream to local connection: readfrom tcp6 [::1]:9001->[::1]:60532: write tcp6 [::1]:9001->[::1]:60532: write: broken pipe
```

**Comment by melalj** [comment]
Same here event on the latest version `v2.0.0+f5119c0` - It's becoming more frequent than the `1.8`.
There is plenty of CPU and RAM on the server, and I couldn't see what is the bottleneck!

**Comment by touchthesun** [comment]
getting the same issue now, only with argocd, and it was working fine yesterday. any idea what's going on here?

> kubectl port-forward svc/argocd-server -n argocd 8080:443 &
andling connection for 8080
E0625 12:03:58.359264   35218 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occurred
E0625 12:04:01.072451   35218 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occurred
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
WARNING: server is not configured with TLS. Proceed (y/n)? y
Handling connection for 8080
E0625 12:04:25.140869   35218 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occurred
E0625 12:04:31.075431   35218 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occurred
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
E0625 12:04:45.143408   35218 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occurred

**Comment by ozbillwang** [comment]
Still get the same issue with latest argocd, any fixes?

**Comment by karlderkaefer** [comment]
drop https port https://github.com/argoproj/argo-cd/issues/2784#issuecomment-645643227

**Comment by leotomas837** [comment]
I was experiencing the issue and fixed it. On my side it was not an argocd's bug, but a misconfiguration on my side, which may be your case too.

It was due to the fact that I was syncing argocd's resources themselves via the argo-helm/argo-cd helm chart with an argocd app (apps-of-apps pattern). When doing a simple sync (every 3 minutes or triggering it manually in the UI or via the argocd cli), no disconnection occurred. Indeed as you will see below a simple sync does not take into account changes in `values.yaml`.
But when hard-syncing an application (at every template change of argocd, or via cli or the UI, or every 24h according to [--default-cache-expiration and --repo-cache-expiration options](https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/argocd-repo-server/) of the `argocd-repo-server` bin used by the argocd repo server pod), not simple sync, the changes of the values of the helm chart are re-synced too. I was experiencing the disconnection at each hard-syncing but no syncing. It became very obvious when changing the 2 options mentioned above to 180s, I was getting disconnected every 3 minutes.
The root cause is that at every hard-sync, the values of argocd's chart gets updated, especially the `configs.secret.argocdServerAdminPasswordMtime` value, which corresponds to the date time of the creation of the admin password of the argocd-server. It gets updated because if not present, argocd set it to the current time by default, see [here](https://github.com/argoproj/argo-helm/blob/5c6ad38b15fccd082da657bc577d23a803808d09/charts/argo-cd/values.yaml#L428). As the values get updated, argocd prunes and recreates the argocd-server pod, which disconnects you. 

The solution is to set an arbitrary date time in the past for the creation of the password, then it won't be update at each hard-syncing and you won't be disconnected (the argo-cd chart sets it to the current time only if not set, and setting a date in the future creates issues, so the only solution is a date in the past), for example:

```yaml
# values.yaml of the argocd's chart
[...]
configs:
    secret:
        argocdServerAdminPasswordMtime: "2022-01-01T00:00:00Z"
[...]
```

A side note: you will obviously still get disconnected when you restart the argocd-server pod... But you can't get around this.

**Comment by CzapBran** [comment]
I guess it's a silly answer, but has anyone tried setting the service type to NodePort?

`kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "NodePort"}}' `

Changing the service type and then port forwarding exposed the ArgoCD UI.  I am testing this locally on a Minikube cluster

**Comment by laviniamnedelea** [comment]
I am experiencing the same behavior with minikube. This issue shouldn't be closed.

**Comment by object88** [comment]
Same here as well.  The UI becomes unresponsive.

**Comment by diranged** [comment]
While we don't use this feature for our production clusters - for our pure dev/test clusters we rely on this and we run into the exact same problem.

**Comment by diranged** [comment]
I've opened a new fresh bug for this.. https://github.com/argoproj/argo-cd/issues/14414

**Comment by harshita3199** [comment]
Did we get anything to resolve this issue. I am also getting the same issue. 
```
E0310 22:16:35.509070   14518 portforward.go:379] error copying from remote stream to local connection: readfrom tcp6 [::1]:8080->[::1]:55278: write tcp6 [::1]:8080->[::1]:55278: write: broken pipe
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
```

**Comment by MonicaMagoniCom** [comment]
I'm experiencing the same issue, only with ArgoCD

**Comment by born2ngopi** [comment]
i got same issue on my local machine

i use wsl2 and docker dekstop for windows

step: 
1. follow [this doc](https://argo-cd.readthedocs.io/en/stable/getting_started) without setup ingress, i use port-forwading
``` bash
$ kubectl port-forward svc/argocd-server -n argocd 8080:443
```

2. create an user with role
``` yaml
# user
data:
  accounts.ch: apiKey, login
# rbac
data:
  policy.csv: |
    g, ch, role:admin
```

3. generate token
4. then run curl
``` bash
$ curl -v -H "Authorization: Bearer $TOKEN" http://localhost:8080/api/v1/applications
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /api/v1/applications HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> Authorization: Bearer $TOKEN
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 307 Temporary Redirect
< Content-Type: text/html; charset=utf-8
< Location: https://localhost:8080/api/v1/applications
< Date: Fri, 26 Jul 2024 03:07:46 GMT
< Content-Length: 78
<
<a href="https://localhost:8080/api/v1/applications">Temporary Redirect</a>.

* Connection #0 to host localhost left intact
```
output from kubectl
```
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
E0726 09:49:02.785880   89886 portforward.go:381] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:8080->127.0.0.1:36644: write tcp4 127.0.0.1:8080->127.0.0.1:36644: write: broken pipe
Handling connection for 8080
Handling connection for 8080
E0726 09:59:30.066055   89886 portforward.go:381] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:8080->127.0.0.1:56782: write tcp4 127.0.0.1:8080->127.0.0.1:56782: write: broken pipe
```

**Comment by Hanyman8** [comment]
Hello, we have a similar issue
```
E1107 13:10:30.011081   35972 portforward.go:385] error copying from remote stream to local connection: readfrom tcp6 [::1]:8080->[::1]:36988: write tcp6 [::1]:8080->[::1]:36988: write: broken pipe
E1107 13:10:41.016435   35972 portforward.go:385] error copying from remote stream to local connection: readfrom tcp6 [::1]:8080->[::1]:37026: write tcp6 [::1]:8080->[::1]:37026: write: broken pipe
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
E1107 13:11:11.030401   35972 portforward.go:351] error creating error stream for port 8080 -> 8080: Timeout occurred
Handling connection for 8080
E1107 13:11:11.060905   35972 portforward.go:374] error creating forwarding stream for port 8080 -> 8080: Timeout occurred
E1107 13:11:11.139602   35972 portforward.go:374] error creating forwarding stream for port 8080 -> 8080: Timeout occurred
Handling connection for 8080
Handling connection for 8080
E1107 13:11:13.208261   35972 portforward.go:374] error creating forwarding stream for port 8080 -> 8080: Timeout occurred
Handling connection for 8080
E1107 13:11:41.044253   35972 portforward.go:351] error creating error stream for port 8080 -> 8080: Timeout occurred
E1107 13:11:42.149718   35972 portforward.go:374] error creating forwarding stream for port 8080 -> 8080: Timeout occurred
E1107 13:11:48.198999   35972 portforward.go:351] error creating error stream for port 8080 -> 8080: Timeout occurred

```

**Comment by q-markglozier** [comment]
We have the same problem

**Comment by dpunkturban** [comment]
We have also the same problem :/

**Comment by Archisman-Mridha** [comment]
I'm also getting the same problem :(.

**Comment by L3monJuic3** [comment]
I am also getting the timeout problem

**Comment by guymoreillon** [comment]
Same here, very annoying.

**Comment by Tarasovych** [comment]
Same issue with 2.13.3
