### ISSUE TITLE
Docs are not published for releases 2.2 and 2.3 .  Stable published docs are not up to date with docs that exist in the stable tag. 

### ISSUE THREAD

**Issue by c1505** [argoproj/argo-cd#8761]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
The last release with published docs is 2.1 https://argo-cd.readthedocs.io/en/release-2.1/ .  There are no docs published for 2.2 or 2.3 .  The stable docs also appear to not be updated to what is in the stable tag.  Argo-notification docs are missing from published documentation.  

**To Reproduce**
* Navigate to https://argo-cd.readthedocs.io/en/latest/ .
* click the dropdown for versions
* 2.1 is the most recent version

* Navigate to https://argo-cd.readthedocs.io/en/release-2.2/ or 2.3
* The page does not have any meaningful content ( see screenshot)

**Expected behavior**
* Documentation is published for all minor version releases (2.2 and 2.3
* Documentation is updated for stable 

**Screenshots**
![Screen Shot 2022-03-11 at 9 42 11 AM](https://user-images.githubusercontent.com/6599077/157890356-07f7858d-f241-40e5-92b3-4df5a34f17e2.png)

**Comment by alexmt** [comment]
Thank you for bringing this up ! Fixed: both 2.2 and 2.3 are available now.

**Comment by c1505** [comment]
Thanks!  @alexmt Curious what the problem was that was fixed?  It seems like readthedocs should automatically build the docs.  I didn't look deep enough to be able to figure out how that was configured in this repository to work with tags/releases .

**Comment by alexmt** [comment]
Readthedocs automatically detect changes in branches/tags but new branches should be enabled manually. ReadTheDocs supports config file in the repo but there is no option to enable/disable which versions should be active: https://docs.readthedocs.io/en/stable/config-file/v2.html
