### ISSUE TITLE
argocd v2.3.1 reverts to tile view after app delete non-cascading

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-cd#8764]
Repro:

- choose list view
- click on an app
- delete the app with noncascading chosen
- jumps back to main page in tiles mode

**Comment by rwong2888** [comment]
same for when noncascading is not chosen in delete

**Comment by crenshaw-dev** [comment]
Failed to reproduce the issue in 2.2.14, reproduced it in 2.3.9.
