### ISSUE TITLE
docs: yaml code blocks under Slack notification service doesn't render properly

### ISSUE THREAD

**Issue by omBratteng** [argoproj/argo-cd#8776]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The YAML examples are rendered as inline code, rather than a code block

**To Reproduce**

See step 8-10 at https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/services/slack/

**Expected behavior**

The YAML examples are rendered as code blocks

**Screenshots**

![image](https://user-images.githubusercontent.com/1681525/158231204-d73d967a-1607-46f6-b7ec-0e8347d099c4.png)

**Version**

Both in [stable](https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/services/slack/) and [latest](https://argo-cd.readthedocs.io/en/latest/operator-manual/notifications/services/slack/) version of docs.

**Logs**

N/A only docs

**Comment by GalvinGao** [comment]
Was trying to fix the highlights in #10280 then I noticed such issue here. Any helps needed? I can file a new PR to pick up the fix if you'd like :D

**Comment by omBratteng** [comment]
There is a PR open to fix the latest broken section https://github.com/argoproj/notifications-engine/pull/97

**Comment by GalvinGao** [comment]
I noticed that the indentation of the code block in Step 8 is invalid
<img width="671" alt="image" src="https://user-images.githubusercontent.com/12567059/184217660-9c32fa20-9268-426f-a02f-d90632cb12fe.png">

Mind me contribute to your branch so you could also bring this fix to upstream?

**Comment by omBratteng** [comment]
I see that now. Sure, go ahead. I can cherry-pick the fix into the PR branch.

**Comment by omBratteng** [comment]
I have fixed the indentation, and put you as the author @GalvinGao, so you can get the credit for it.

**Comment by omBratteng** [comment]
Once it gets merged, I'll open a PR here to get the correct version of the go module

**Comment by GalvinGao** [comment]
I think we can close this as #10311 is merged :D

**Comment by omBratteng** [comment]
Unsure if it is actually out. I see @crenshaw-dev added, and then removed, the cherry-pick label.
Unsure how the release process for this works. But last time I checked (some while ago), the fix wasn't properly out yet.

**Comment by omBratteng** [comment]
Never mind, just checked now. It's out on the stable version of the docs.

**Comment by pasha-codefresh** [comment]
Let close it @omBratteng ?

**Comment by omBratteng** [comment]
Should be closed now.
