### ISSUE TITLE
Support `[skip ci]` / `[ci skip]` in commit messages

### ISSUE THREAD

**Issue by zx8** [argoproj/argo-cd#878]
It would be good to be able to configure Argo to ignore specific commits based on the content of the commit message, e.g. in the case I intentionally don't want to deploy something or I know I've updated something that doesn't make a difference to the deployment (e.g. a README file).

This is a pattern supported by various other CI/CD tools and was surprised that Argo didn't support it.

Related: https://circleci.com/docs/2.0/skip-build/

**Comment by alexmt** [comment]
Argo CD compares K8s resource manifests defined in git repo and the cluster. If manifests stay the after commit then no action is performed by Argo CD.

**Comment by zx8** [comment]
@alexmt I understand this behaviour. As stated, I sometimes intentionally do not want to deploy a change I'm committing _immediately_. This is quite common during development when the manifests themselves are unstable.

Additionally, it would be useful to skip the overhead of having Argo CD regenerate all the manifests and hit the Kubernetes API unnecessarily to determine that nothing has changed if I'm committing a change to an irrelevant/README file.

Would you be open to PRs to support this, or are you against adding the functionality entirely?

**Comment by alexmt** [comment]
Thank you for the explanation! This use-case is solved using `--targetRevision` parameter. The `targetRevision` defines commit, tag, or branch in which to sync the application to. E.g. if application's `targetRevision` is set to `production` then developers might update `master` any time and release changes to production once master is stable.

Argo CD reconciles app state in response to multiple events: any change in target cluster, commit in repo, periodically after some time. So there is just no place in code where Argo CD could check for commit message.

Your point about overhead is valid: argo cd should not regenerate manifests/hit k8s api unnecessary. We are caching generated manifests as well as target cluster state to avoid making unnecessary API calls.
