### ISSUE TITLE
HPA with unreachable cutom metric is shown as "healthy" in version 2.3.1

### ISSUE THREAD

**Issue by hivl** [argoproj/argo-cd#8782]
Hi guys, after I updated argocd from version 2.2.x to 2.3.1 I have a bit strange behaviour/display with HPA.
I have an HPA with custom metric. One namespace is not configured in prometheus and therefore this metric is not available and HPA is not working properly.
In argocd version 2.2.x this HPA was always shown as "progressing". After the update to v 2.3.1 the same HPA is now "Healthy" which is definitly not the case. Is it a bug or some configuration problem?
![hpa](https://user-images.githubusercontent.com/1629464/158353113-276748d0-23b9-4265-b3e3-48b2d911f6a0.jpg)

**Comment by todaywasawesome** [comment]
@hivl did you figure this out? Is it still relevant?
