### ISSUE TITLE
Allow tracking of individual files/subdirectories

### ISSUE THREAD

**Issue by zx8** [argoproj/argo-cd#880]
We store our Kubernetes manifests across all environments in a single Git repository, in separate subdirectories (`test`, `staging`, `production`). We've configured Argo CD to monitor this repository and deploy to the corresponding separate Kubernetes clusters.

The problem is: Argo CD will pick up any commit made to this repository and trigger 3 separate deployments, even if the commit only modified the `test` subdirectory. Rather than split out these 3 directories into 3 separate repositories, it would be fantastic if we could configure Argo CD to monitor specific directories.

**Comment by alexmt** [comment]
This is already supported.th Directory path can be specified during application creation:

```
argocd app create --name <app-name> --repo <repo-url> --dest-server <cluster> --dest-namespace <namespace> --path <path>
```

**Comment by alexmt** [comment]
In this case I would suggest creating three separate applications. Each application should be pointing to the same chart but use different values file and cluster:
```
argocd app create --name ... --dest-cluster <test-cluster> --values test.yaml
argocd app create --name ... --dest-cluster <staging-cluster> --values test.yaml
argocd app create --name ... --dest-cluster <production-cluster> --values production.yaml
```

Additionally you might "package" test/staging/production apps into another argocd app. https://github.com/argoproj/argoproj-deployments repo here is example which does it.

We are also considering to support composable applications. https://github.com/argoproj/argo-cd/issues/677

**Comment by zx8** [comment]
Fantastic! Thanks for the reference. I'll give this a go and reopen this issue if it doesn't work as advertised.

I've subscribed to https://github.com/argoproj/argo-cd/issues/677 as I actually prefer that approach in principle.
