### ISSUE TITLE
Parameters not showing fields from custom helm values file

### ISSUE THREAD

**Issue by EdwinPhilip** [argoproj/argo-cd#8808]
**Describe the bug**

When using helm charts as the source of applications, we intend to have multiple values file targeting each environment, say qa-values.yaml, prod-values.yaml.
Till argo cd version 2.2.5, the Parameters tab shows fields from all the values file chosen, both from the default values file and the overridden custom values file chosen.
With latest 2.3.1, Parameters tab shows only fields from the default values file. 

**Expected behavior**

Parameters tab should show fields from both default values file and overridden values file

**Version**

```shell
argocd: v2.3.1+b65c169
```

**Comment by rbabyuk-vs** [comment]
right, we see the same issue. it appeared after upgrade to 2.3.1

**Comment by SashaScherbina** [comment]
so, after upgrading to 2.3.1 we have same behavior. With latest 2.3.1, Parameters tab shows only fields from the default values file.

**Comment by jlirochon** [comment]
Same on `v2.3.2+ecc2af9`

Maybe related : when you call `GetParameterValueByName` in a notification template, `app-sync-running` in my case, it can only read values from `values.yaml`.

For example `{{ (call .repo.GetAppDetails).Helm.GetParameterValueByName "my_parameter" }}` returns the value of `my_parameter` if it's defined in `values.yaml`, but returns an empty string if it's defined in say `values-staging.yaml`

Also `{{ (call .repo.GetAppDetails).Helm.ValueFiles }}` only returns `[values.yaml]`

**Comment by mblsf** [comment]
Same issue here, please fix

**Comment by mihma** [comment]
Also affected by this issue

**Comment by guyelia** [comment]
same here

**Comment by burakovsky** [comment]
just added that it appeared in 2.2.6 version

**Comment by mihma** [comment]
Is this issue getting any traction?

**Comment by guitmz** [comment]
we are running v2.4.3 and the issue is still present

**Comment by crenshaw-dev** [comment]
@guitmz can you elaborate? Where have you set the overriding image.tag that you expect to see?

**Comment by guitmz** [comment]
@crenshaw-dev I have `image.tag` it defined in `values` (not `values files`).

I expect to see the defined `image.tag`  there and not the `YYYY` placeholder default string I have in my chart.

**Comment by crenshaw-dev** [comment]
Thanks @guitmz! I reopened that issue.

**Comment by ale-conekta** [comment]
HI,
We are running v2.4.7 and dependency chart, the issue is still present ?
The values and parameters looks ok and are corrected read from values.yaml, but when I sync it, the values applied are the default.

**Comment by crenshaw-dev** [comment]
@ale-conekta I believe this issue was about values not appearing in the UI but actually applying.

If you're having an issue with values appearing in the UI but not applying, I think that's a new issue.

**Comment by ale-conekta** [comment]
@crenshaw-dev thanks you for your feedback, I will try to open an issue.
Thanks
