### ISSUE TITLE
Stop sync and error on SharedResourceWarning

### ISSUE THREAD

**Issue by thomassandslyst** [argoproj/argo-cd#8811]
# Summary

Currently if two ArgoCD applications create the same resource ArgoCD will overwrite the former with the latter, mark the former as out-of-sync, and raise a SharedResourceWarning. I would like an option to treat this as an error instead of a warning which would stop the sync process (or revert it) so that no resource is overwritten.

# Motivation

Due to some naming conventions in places such as mine where names of resources are made of strings appended to others, for example the application "user-service" might have a deployment called "web" resulting in a deployment object named "user-service-web", there are chances that this can create a clash when another application called "user" has a deployment called "service-web" which also results in the deployment object name "user-service-web".

# Proposal

When a suitable ArgoCD option is set the sync process should not proceed if it believes that it is going to apply a resource that is controlled by another application, instead stopping the sync with a suitable error.

**Comment by blakepettersson** [comment]
There is [an option](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#fail-the-sync-if-a-shared-resource-is-found) to error in case a resource is shared with another (I'm guessing this issue was added after this issue was submitted).
