### ISSUE TITLE
Application advanced configuration of views to other metrics tools.

### ISSUE THREAD

**Issue by burkempers** [argoproj/argo-cd#8822]
# Summary

Allow addition to pod and network views for an application with iframes redirects to grafana, kiali, or other visualization tools

# Motivation

In the pod view for an application argocd displays some generic information about the cpu and memory information for the nodes the pod is running on.  I would like to be able to change this view to point to my grafana dashboard that breaks out even more metrics on the given pod/s.

I am running some of my namespaces with istios injection, and for the network view in an application i would like that view to show a kiali display that has even more metics on what the network is doing.

# Proposal

In each application configuration; i think it would be nice to be able to have advanced options with configuration to have urls for those views.

**Comment by leoluz** [comment]
Closing this in favor of #9562 as we have already ongoing discussion in it.
