### ISSUE TITLE
Running commands on a kube-context different than current

### ISSUE THREAD

**Issue by elad-codefresh** [argoproj/argo-cd#8829]
# Summary

It's currently possible to run argocd commands only on the current kube-context.

# Motivation

A user might want to just run a specific command quickly, such as 'clusters list', on a different context - without having to switch to a different context and then switch back.

# Proposal

We can implement a kube-context flag, which will allow to override the ConfigOverrides.CurrentContext property.
I have a pr ready with this addition.

**Comment by pasha-codefresh** [comment]
Use case it is ability do port-forward to another context without switch to different context
