### ISSUE TITLE
argocd application.resourceTrackingMethod annoation+label does not work if application.instanceLabelKey is defined

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-cd#8839]
I added the below tracking method, but I do not see [annotations.argocd.argoproj.io/tracking-id](http://annotations.argocd.argoproj.io/tracking-id):  get added to my resource. Am I missing something?

```
data:
  application.instanceLabelKey: argocd/application
  application.resourceTrackingMethod: annotation+label
```

https://cloud-native.slack.com/archives/C020XM04CUW/p1647870883332059

**Comment by TBurda** [comment]
Hi @rwong2888, I have same problem. How did you resolve it ?

**Comment by echung808** [comment]
I'm also seeing this behavior on Argocd v2.5.0+b895da4
