### ISSUE TITLE
bug in doc: is build enviornment supported in kustomize

### ISSUE THREAD

**Issue by huikang** [argoproj/argo-cd#8848]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Contradict description on supporting build environment by kustomize:

- The kustomize page (https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#build-environment) says "Kustomize does not support parameters and therefore cannot support the standard [build environment](https://argo-cd.readthedocs.io/en/stable/user-guide/build-environment/)."

- The build environment (https://argo-cd.readthedocs.io/en/stable/user-guide/build-environment/) says "Custom tools, Helm, Jsonnet, and Kustomize support the following build env vars:"

Should the doc be clarified on how kustomize supports build env?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by christianh814** [comment]
This issue should be closed by #9534
