### ISSUE TITLE
Web UI for version v2.3.1+b65c169 loads too long

### ISSUE THREAD

**Issue by yevgeniyo** [argoproj/argo-cd#8925]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Web UI for version v2.3.1+b65c169 loads too long in comparison with v2.1.7+a408e29
As I saw in network inspection, file main.js started to be heavier x2
See screenshoots 

**Screenshots**

2.3.1+b65c169
![Screen Shot 2022-03-29 at 18 00 10](https://user-images.githubusercontent.com/14246521/160643390-df138ca0-b064-4ebf-8a79-3b9f8f666324.png)

v2.1.7+a408e29
![Screen Shot 2022-03-29 at 17 59 41](https://user-images.githubusercontent.com/14246521/160643405-16b9f2c0-60c1-41ad-a6f8-51832cadcdc9.png)

**Version**

2.3.1+b65c169

**Comment by blakepettersson** [comment]
Have you [enabled gzip compression](https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/argocd-server/#options)? Alternatively it's likely that this is something that would be addressed with an implementation of #14947.

Since this issue is pretty old I'll close it for now.
