### ISSUE TITLE
`argocd version --client` tries to reach server

### ISSUE THREAD

**Issue by daurnimator** [argoproj/argo-cd#8931]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] :rofl:  I've pasted the output of `argocd version`.

**Describe the bug**

```
$ argocd version --help | grep 'client version'
      --client                         client version only (no server required)
$ argocd version --client
W0330 13:03:13.477308 1068827 reflector.go:324] k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.ConfigMap: Get "https://localhost:6443/api/v1/namespaces/argocd/configmaps?labelSelector=app.kubernetes.io%2Fpart-of%3Dargocd&limit=500&resourceVersion=0": dial tcp [::1]:6443: connect: connection refused
W0330 13:03:13.477319 1068827 reflector.go:324] k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.Secret: Get "https://localhost:6443/api/v1/namespaces/argocd/secrets?limit=500&resourceVersion=0": dial tcp [::1]:6443: connect: connection refused
```

**Expected behavior**

`argocd version --client` should never try and connect to a server

**Version**

```shell
Paste the output from `argocd version` here.
```

2.3.3

**Comment by danielhelfand** [comment]
This was fixed in this pr: https://github.com/argoproj/argo-cd/pull/8341

Unfortunately, it has not been released yet. I would keep an eye out for this fix in an upcoming release.

**Comment by daurnimator** [comment]
Ah. I only searched open issues not closed PRs.
