### ISSUE TITLE
Application controller HA

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#894]
In v0.11, the application-controller now has APIs to:

1. return the resource tree of an application
2. return the managed resource diff of the application

The Argo CD API server exposes the controller APIs by relaying requests to the controller after performing auth.

Because the application-controller is now in the data path of serving requests (where it didn't use to before), we need to make it HA. The trouble is that, if we were to scale to multiple application controllers today, they would fight over updates to an application.

It should be noted that both the api-server and repo-server are already HA in v0.10. But until v0.11, the application controller had no need to become HA since it was not in the direct data path, and a quick reschedule of the controller was considered as sufficient as having HA.

The proposal is to implement leader election in the controller so that there will be a single application writer, but multiple readers to handle the resource tree/diff requests. Each controller will maintain their own kubernetes watch, and have their own live state cache.

More on leader election in kubernetes:
https://tunein.engineering/implementing-leader-election-for-kubernetes-pods-2477deef8f13

**Comment by alexmt** [comment]
Application controller is no longer in the data path. As part of this ticket we need to provide documentation/kustomize package which bundles HA redis

**Comment by alexmt** [comment]
Done
