### ISSUE TITLE
Argo CD CLI throws misleading warning about cluster privileges when adding a cluster with namespace privileges

### ISSUE THREAD

**Issue by caseyclarkjamf** [argoproj/argo-cd#8957]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The Argo CD CLI throws a misleading warning about cluster level privileges when adding a cluster with namespace level privileges.

Only the warning looks wrong, the cluster is still added to Argo CD with namespace level permissions. 

**To Reproduce**

1. Add a cluster using the Argo CD CLI with the `--namespace` flag.
2. View the WARNING provided by the CLI
```
WARNING: This will create a service account `argocd-manager` on the cluster referenced by context `example-kube-context` with full cluster level admin privileges.
```

**Expected behavior**

The WARNING is not displayed because the `argocd-manager` ServiceAccount is not created with cluster level admin privileges. 

**Screenshots**

**Version**

```shell
argocd: v2.1.10+de6735c
  BuildDate: 2022-02-05T01:20:40Z
  GitCommit: de6735c386b2bc6cad2372f43881df7898fb13cb
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.10+de6735c
  BuildDate: 2022-02-05T01:18:20Z
  GitCommit: de6735c386b2bc6cad2372f43881df7898fb13cb
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by iam-veeramalla** [comment]
I am able to reproduce this issue.

```
➜  argocd cluster add kind-sandbox **--namespace default**
**WARNING: This will create a service account `argocd-manager` on the cluster referenced by context `kind-sandbox` with full cluster level admin privileges. Do you want to continue [y/N]? y**

INFO[0014] ServiceAccount "argocd-manager" already exists in namespace "kube-system"
INFO[0014] Role "default/argocd-manager-role" updated
INFO[0014] RoleBinding "default/argocd-manager-role-binding" updated
```

**Comment by iam-veeramalla** [comment]
I think it should be fixed by adding a condition for `--namespace` in the below code
https://github.com/argoproj/argo-cd/blob/ad3c315e0c86ca58d2e52068f6f33c67a76d5383/cmd/argocd/commands/cluster.go#L119
