### ISSUE TITLE
cli: remove argocd rbac when cluster is removed 

### ISSUE THREAD

**Issue by danielhelfand** [argoproj/argo-cd#8958]
# Summary

When you add a cluster via the CLI, the following rbac is created in the kube-system namespace:

Service Account argocd-manager
ClusterRole argocd-manager-role
ClusterRoleBinding argocd-manager-role-binding

When you run `argocd cluster rm cluster-name`, the RBAC is still present on the cluster and is not cleaned up

It would be helpful to remove this RBAC as part of the cleanup process. 

# Motivation

Unused resources shouldn't be left on the cluster. It also looks like there is a [TODO](https://github.com/argoproj/argo-cd/blob/ba0c249457edf732467a05128a37b16fe37a28c4/cmd/argocd/commands/cluster.go#L262) to implement this feature.

# Proposal

I have a rough draft pushed [here](https://github.com/danielhelfand/argo-cd/commit/9119998b987eb814c4c6a9bc782fd4da9be98b22).

The cluster rm command should perform a get call to pull back the cluster name (i.e. context name) to set up the rest config and k8s clientset. Then the [UninstallClusterManagerRBAC](https://github.com/argoproj/argo-cd/blob/d6f3f87c694f5e589fcff883adf3facc2ac42866/util/clusterauth/clusterauth.go#L254) can be called to remove the RBAC.

**Comment by iam-veeramalla** [comment]
@danielhelfand Thanks for bringing this up :) . Can I go ahead and assign this issue to you ?

**Comment by danielhelfand** [comment]
@iam-veeramalla Yes, please assign me. Thanks!
