### ISSUE TITLE
Exposing Default Metric Port for ApplicationSet Controller in Manifest Files

### ISSUE THREAD

**Issue by hcelaloner** [argoproj/argo-cd#8999]
# Summary

Out of the box, ApplicationSet presents some controller-runtime metrics on port 8080. However, the metric port is not defined as a container port in manifest files, therefore, they are not accessible. By default, can we make it accessible?

# Proposal

By default, define it as a port definition in the manifest port.

Note: Copy of https://github.com/argoproj/applicationset/issues/495 since applicationset repo moved into argocd

**Comment by iam-veeramalla** [comment]
@hcelaloner Thanks for raising the issue as well as PR. I have assigned the issue to your name. I hope you are okay with it :)
