### ISSUE TITLE
GitLab Deploy Token support

### ISSUE THREAD

**Issue by EppO** [argoproj/argo-cd#901]
Hi,

instead of using username/password to connect to a GitLab Git repository, it would be nice to have the possibility to use an deploy token instead: https://docs.gitlab.com/ce/user/project/deploy_tokens/

Tokens are revocable and can expire, it's easier to manage that username/password. Morever, it only allows read access to the git repository, instead of creating a specific user with Reporter permissions.

**Comment by jessesuen** [comment]
@EppO according to this document, you use gitlab deploy tokens just as you would a password. They use the example:
```
git clone http://<username>:<deploy_token>@gitlab.example.com/tanuki/awesome_project.git
```

So from the perspective of git, they are the same thing as passwords which we already support. Github tokens behave in the same manner, where the  github token is the password, and can be revoked.

**Comment by jessesuen** [comment]
Closing since I believe this to be working.

**Comment by EppO** [comment]
Indeed, cloning using https and the deploy token works fine! sorry for the confusion.

**Comment by fayak** [comment]
Hi,

I'm facing the same issue, and if modifying the URL works, it doesn't fit well our needs of security as the token isn't stored in a Kubernetes' Secret.
What would be the way to use a Gitlab Deploy Token while having it "securily" stored in a Secret ? I believe this might be important for us

**Comment by jannfis** [comment]
@fayak Just add the HTTPS repository using whatever string as username and the token as password (i.e. `argocd repo add https://gitlab.com/your/repo --username nonexistant --password <deploy token>`) -- then it will be safely stored as a Kubernetes secret.

**Comment by fayak** [comment]
Ok so apparently it does work, but in our case we forgot to specify `https` instead of `http`, which lead to a weird error message making use think that Gitlab Deploy Token weren't supported this way. Sorry for bumping such an old issue !
