### ISSUE TITLE
The favourite icon makes it look like an app has been favourited when it has not

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#9026]
The current fav icon makes me think the app has been faved, when it has not. The fav icon should be an outlined star, not a filled star. 

<img width="421" alt="image" src="https://user-images.githubusercontent.com/1142830/162030798-0a1a8ec4-18ac-4b9a-bddc-381d57a18d65.png">

Not fav:

<img width="138" alt="image" src="https://user-images.githubusercontent.com/1142830/162030909-b256be55-d242-4c97-bac2-39c647b19254.png">

Fav:

<img width="127" alt="image" src="https://user-images.githubusercontent.com/1142830/162030935-4112f9c8-804c-4a78-ba09-e105e0211bb3.png">

**Comment by ashutosh16** [comment]
I would recommend to move the favorite(star) icon to bottom right, as it overlapping with application name and making it clutter
![Screen Shot 2022-04-06 at 1 22 25 PM](https://user-images.githubusercontent.com/11219262/162064206-db68b987-9a09-4b6a-ade9-a2f26b8b94a4.png)
.

**Comment by saumeya** [comment]
> I would recommend to move the favorite(star) icon to bottom right, as it overlapping with application name and making it clutter ![Screen Shot 2022-04-06 at 1 22 25 PM](https://user-images.githubusercontent.com/11219262/162064206-db68b987-9a09-4b6a-ade9-a2f26b8b94a4.png) .

There is also a route icon in some cases that appears before favourites, does that overlap too?

**Comment by ashutosh16** [comment]
@saumeya  I haven't seen the other icons on the ui, do you have a screenshot?

**Comment by saumeya** [comment]
> @saumeya I haven't seen the other icons on the ui, do you have a screenshot?

@ashutosh16 This is a valid concern, I will probably discuss it further, if it requires the icons to be moved and address this issue in another PR. Thanks!!
![overlap](https://user-images.githubusercontent.com/17771352/163428216-08b13673-067e-494c-b745-c1ce31fc4ce7.png)
