### ISSUE TITLE
applicationset security context not set

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#9028]
These issues should be fixed:

```
manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml: (object: <no namespace>/argocd-applicationset-controller apps/v1, Kind=Deployment) container "argocd-applicationset-controller" does not have a read-only root file system (check: no-read-only-root-fs, remediation: Set readOnlyRootFilesystem to true in the container securityContext.)

manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml: (object: <no namespace>/argocd-applicationset-controller apps/v1, Kind=Deployment) container "argocd-applicationset-controller" is not set to runAsNonRoot (check: run-as-non-root, remediation: Set runAsUser to a non-zero number and runAsNonRoot to true in your pod or container securityContext. Refer to https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ for details.)
```

**Comment by rishabh625** [comment]
Please assign this to me

**Comment by alexec** [comment]
More broadly, does applicationset need a security review?

**Comment by crenshaw-dev** [comment]
> More broadly, does applicationset need a security review?

It does. I think part of that will happen naturally as people review https://github.com/argoproj/argo-cd/pull/9016. I think we also need a docs review. AppSet should be considered very much an admin tool until we introduce finer-grained RBAC. I'm not sure the docs make that clear enough.

> More issues:
>
> https://app.snyk.io/org/argoproj/project/f6443593-7316-45ce-a9fb-d60ccf8c10a5

Thankfully those issues won't be relevant as of 2.4, when appset and argocd will share the same base image. Check out the latest image to see what that looks like: https://app.snyk.io/org/argoproj/project/d937faf3-d422-452a-97b5-93582bcb8a33

**Comment by alexec** [comment]
Sure. Though bear in mind, that new base image could introduce new issues.
