### ISSUE TITLE
ArgoCD Client set/use proxy

### ISSUE THREAD

**Issue by CUBITECH** [argoproj/argo-cd#9040]
# Summary

ArgoCD actually ignores environment proxy variables http_proxy and https_proxy (also uppercase). 

# Motivation

Deployment of apps during CI with ArgoCD client behind corporate proxy with ArgoCD beeing the leading RBAC system

# Proposal

Like any other cli accepts http(s)_proxy environment variables

**Comment by ishitasequeira** [comment]
can you elaborate a bit more on your proposal @CUBITECH?

**Comment by CUBITECH** [comment]
![argocd-proxy](https://user-images.githubusercontent.com/37175678/164168235-6252dd58-cb27-42c9-b744-f6dc0937f62d.png)
Hi,

i have drawn  the desired behavior. 
Actually the CLI does not use any known way of setting a proxy.
Let me know if i can support more

**Comment by 55octet** [comment]
This is an issue that I have with the argocd client application.  It will not work behind a corporate proxy, even when the https_proxy or http_proxy variables are set.

**Comment by olegeech-me** [comment]
Hello guys, that's a very relevant issue for me as well. I have to workaround it using proxy forwarding, but adding a feature for "digesting" env http/s proxy settings would be super natural thing to have.

**Comment by yushiwho** [comment]
Hi. I am trying to add a feature for socks proxy. Maybe this PR can help.
https://github.com/argoproj/argo-cd/pull/10451

**Comment by CUBITECH** [comment]
Hi, looks good to me. Hope it goes quickly into master.
Thanks yushiwho!

**Comment by janblahovec** [comment]
Hello everybody! any updates on this topic?

**Comment by peterballay** [comment]
Hello everyone, is there any progress here? Would the PR be merged?
Solving the problem with running argocli behind corporate proxy would help us a lot otherwise we are in the death end.
