### ISSUE TITLE
Only show commits with changes to path manifests only in history and rollback

### ISSUE THREAD

**Issue by Hax7** [argoproj/argo-cd#9043]
Summary

In a monolith repository there is a lot of commits not related to the manifests path and some of these commits show up in history and rollback for an application.

Motivation

We are using a repository with both source code and manifests and that means most of the commits won't be related to the manifests but if I go to some application and click on history and rollback I would see non related commits although surprisingly not all commits(I don't know how this features decide which commit to include and which one not) which makes it confusing. 

Proposal

If there is a way we can tell the application to just include commits with changes to files in path only it would be much cleaner and helpful to use this feature.

**Comment by gaeljw** [comment]
Note that it's considered best practice to store manifests in a different Git repository than the application source code.

Though your suggestion can still make sense as manifests repository can still contain manifests of many apps.

**Comment by tribu** [comment]
Also in mon git-repo with multiple manifests/services where each folder is a microservices chart this will be a useful feature.

**Comment by crenshaw-dev** [comment]
I haven't investigated deeply, but I wonder if this PR will get us this fix "for free": https://github.com/argoproj/argo-cd/pull/16295

**Comment by agaudreault** [comment]
@alexymantha Do you know if the history and rollback list is filtered properly when using the annotation?

**Comment by agaudreault** [comment]
@Hax7 feel free to reopen if this is happening on version >2.11.0

**Comment by mihstaub** [comment]
Hello - can you share please the annotations used here?

**Comment by parkerirving45** [comment]
Hey all we are still experiencing this behavior on version v3.3.9
