### ISSUE TITLE
Unable to activate SSO with Keycloak according to the documentation

### ISSUE THREAD

**Issue by ccaillet1974** [argoproj/argo-cd#9044]
Hi all,

I've the following issue : I was unable to use authentication via Keycloak, configured as the documentation described in https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/

I follow step by step the configuration described but it does'nt work. I've also activated environment variable on argocd-server pod for specifying the usage of http_proxy, https_proxy and no_proxy vars without this definition argocd-server was unable to contact the keycloak as described in oidc.config.

The oidc.config  is defined as 
```
oidc.config:
----
name: Keycloak
issuer: https://<hostname>/auth/realms/k8sint
clientID: argocd
clientSecret: $oidc.keycloak.clientSecret
requestedScopes: ["openid","profile","email","groups"]

```

I obtained the following error message continuosly : 

Failed to query provider "https://<hostname>/auth/realms/k8sint": 401 Unauthorized : You need a valid user and password to access this content

My k8s is behind a haproxy for external access and after that ingress-controller on k8s redirect to the correct service according to the hostname.

NOTE: with the regular authentication method it works perfectly but with keycloak it doesn't. 

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I've the following issue : I was unable to use authentication via Keycloak, configured as the documentation described. 

I follow step by step the configuration but it does'nt work. I've also activated environment variable on argocd-server pod for specifying the usage of http_proxy, https_proxy and no_proxy vars without those definitions argocd-server was unable to contact the keycloak as described in oidc.config.

**To Reproduce**

Configure SSO for keycloak according the documentations found in https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/

**Expected behavior**

Keycloak authentication is displayed and user was able to specify his credentials before being redirected to the argocd interface

![image](https://user-images.githubusercontent.com/95746753/162410018-295cb89d-5cbc-4cd1-b297-4a71e611959a.png)

![image](https://user-images.githubusercontent.com/95746753/162409813-0c388e4e-f69e-46d7-9858-f21e7e43c3c0.png)

**Version**

v2.3.2+ecc2af9 deployed via Helm chart

**Logs**

Here is the only log line that refer to OIDC : 

```
time="2022-04-08T08:02:45Z" level=info msg="Initializing OIDC provider (issuer: https://lyo0-int-keycloak.pfd.sfr.net/auth/realms/k8sint)"
```

**Comment by d7volker** [comment]
Please change your oidc.config:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://<your argo url>
  oidc.config: |
    name: Keycloak
    issuer: https://<your keycloak url>/realms/master
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
```
Please note the change:

https://<your keycloak url>/auth/realms/master

is replaced by:

https://<your keycloak url>/realms/master

This was changed in recent keycloak releases.

**Comment by ccaillet1974** [comment]
Hi,

First thanks or your answer ... and immediatly tested ... without any success

My Keycloak version is : for APPVERSION : 16.1.1 for Chart verison 7.1.10 from Bitnami ... need to test other helm deployment especially those with 17.x.y verison for Keycloak ... 

On other apps I've replaced the Bitnami chart with other chart due to bug on Bitnami ... :'(

Come back later with results

Regards

**Comment by d7volker** [comment]
Strange I faced the same issue like you. I am using version 18. But I could fixed it by the above mention change in the issuer URL.

**Comment by ccaillet1974** [comment]
Could you advise me on a specific Helm chart for deploying Keycloak ?

**Comment by d7volker** [comment]
Unfortunately I don't use Helm for this. I build my own using kustomize.
