### ISSUE TITLE
TestFailedConversion e2e test fails when running locally

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#9046]
The test is failing on docker-desktop with k8s version 1.22.5.

@zachaller has investigated a fix here: https://github.com/argoproj/argo-cd/pull/8941

**Comment by crenshaw-dev** [comment]
The test exists because when local kubectl version conversion fails, you have to fall back to server-side conversion. The test makes sure that fallback happens.

I think we can accomplish the same thing by writing a unit test that mocks kubectl calls. The kubectl conversion call should fail, and the test should make sure that there's a subsequent `GetResource` call that specifies the version (this implicitly invokes the server-side conversion).

**Comment by rishabh625** [comment]
There is one more test TestSyncOptionsValidateTrue, which is skipped as k3s does not validate , not related to this
