### ISSUE TITLE
Surface Service/Ingress external IPs, hostname to application

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#908]
A useful feature would be for the UI to surface all external facing IPs & hostnames at the application view. This would simply be the hostname / ip address fields of any Ingress or Service objects that are part of the application. 

Currently, the process is to visually inspect objects for service or ingress, and then click into the object to look at the manifests.

**Comment by alexmt** [comment]
External hosts information is required for https://github.com/argoproj/argo-cd/issues/357 . So moving it into v0.13 milestone

**Comment by alexmt** [comment]
Implemented
