### ISSUE TITLE
TestCustomToolWithSSHGitCreds is flakey

### ISSUE THREAD

**Issue by danielhelfand** [argoproj/argo-cd#9094]
# Summary

TestCustomToolWithSSHGitCreds seems to be flakey as shown in logs [here](https://github.com/argoproj/argo-cd/runs/6010779459?check_suite_focus=true) and [here](https://github.com/argoproj/argo-cd/runs/6012447215?check_suite_focus=true) and mentioned in #9054.

The cause seems to be that the status for the App [doesn't reach a status of Synced](https://github.com/argoproj/argo-cd/blob/fa46ac178f809577285d8b37480ef1e46e7cb4a4/test/e2e/custom_tool_test.go#L121). This causes the test to be timed out and fail.

#9054 attempted to fix this, but it does not appear that even 30 seconds is enough some times. 

We should consider raising the timeout more or figuring out if the test needs further changes.

The test was introduced in #8389.

**Comment by crenshaw-dev** [comment]
@danielhelfand I notice that the command being printed by the flakey test shows `--timeout 10`. I wonder if a second timeout needs to be extended.
