### ISSUE TITLE
Make maxPodLogsToRender configurable

### ISSUE THREAD

**Issue by eslam-adel92** [argoproj/argo-cd#9131]
# Summary
I have an Issue with showing k8s deployment logs, I found that the error is the logs of deployment can not be displayed for a certain amount of pod for example I have 20 pods in one deployment when I try to show the logs of each pod it appears but when I try to get the logs of the whole deployment I can not and I get the below error:
rpc error: code = Unknown desc = Max pods to view logs are reached. Please provide more granular query.

# Proposal
Can this value `"maxPodLogsToRender"` be configurable.

Thanks.

**Comment by todaywasawesome** [comment]
Seems like a good idea +1

**Comment by dfroberg** [comment]
Could we pretty please, with sugar on top, get maxPodLogsToRender not to be hardcoded?

**Comment by dmttrm** [comment]
Bumping this as it's a problem in our organization too.

**Comment by josecsotomorales** [comment]
Bumping this, would be nice to have!

**Comment by danielm-codefresh** [comment]
Any updates on this one?

**Comment by itamadev** [comment]
Just encountered this, is there a reason for this to be hard-coded?
