### ISSUE TITLE
Need a way to "force" refresh an app (invalidate its cache)

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#914]
With kustomize, it's possible to reference a remote base (e.g. the manifests of a git url tag). The issue with this feature, is that the remote base may change meaning over time, even if the application's source git repository does not change.

We currently cache manifests at the repo server for one day, incorporating the commit SHA as part of the key. This was assumed to be safe to do because the contents of files produced at a git commit sha were considered immutable. But with the potential for a remote kustomize base to change meaning, this assumption is no longer true.

We need to provide an ability to "force" refresh an application, which will get current state of the git repo, as well as the live state (from k8s)

**Comment by mojtabacazi** [comment]
@alexmt do you know if this is actually implemented ? If so can you point me to the PR or documentation please?

**Comment by alexmt** [comment]
Hello @mojtabacazi . Yes this is implemented. You can forcefully refresh cache using `argocd app get <appName> --hard-refresh` or using by clicking 'Hard Refresh' button in UI:


![image](https://user-images.githubusercontent.com/426437/73674838-318aa600-4666-11ea-9ab7-b09f8ae3ad2b.png)

**Comment by mojtabacazi** [comment]
So that's what that arrow is for, the click hit area is so tiny that I thought it's just a ui bug.

**Comment by mojtabacazi** [comment]
@alexmt Is it possible to hard-refresh all apps ? either with CLI or the UI

**Comment by sspreitzer** [comment]
Some search engine users may land on this issue when searching for a way to hard refresh a repository with the argocd cli, instead with the webui.

As of today one way to hard refresh a repository in the argocd cli is:

```shell
argocd repo list
argocd repo get --refresh hard <repository url>
argocd app sync --prune <application name>
```

**Comment by lhriley** [comment]
adding to @sspreitzer suggestion:
```
argocd app list -o name [- l my.label/matcher=foo] | xargs -I {} argocd app get --refresh {}
```

**Comment by evgenii-rodionov-affise** [comment]
is it possible to refresh the cache via REST API?

**Comment by Eroyi** [comment]
> > is it possible to refresh the cache via REST API?
> 
> Yes, all commands of argocd-cli use the REST API.
> 
> You can explore the API eg. by opening https://generator.swagger.io/ and filling in https://raw.githubusercontent.com/argoproj/argo-cd/master/assets/swagger.json

Sorry to bother but I'm still unable to find a valid way to make a hard refresh with REST API.
The only weird way I know to refresh (shallow) is by calling `http://argocd.my.domain/api/webhook` with
```json
{
  "ref": "refs/heads/master",
  "project":{
    "web_url":"https://gitlab.my.domain/project/repo.git",
    "default_branch":"master"
  }
}
```
Would you mind enlight me the right way to do a deep refresh? perhaps the shallow refresh either?

**Comment by Eroyi** [comment]
Oh, I found it, open the DevTool and you can see it in XHR:
It using GET method to call `http://argocd.my.domain/api/v1/applications/appName?refresh=hard&appNamespace=argocd`
The corresponding part in the swagger-ui is `#operation/ApplicationService_Get`

**Comment by stevenpitts** [comment]
> Some search engine users may land on this issue when searching for a way to hard refresh a repository with the argocd cli, instead with the webui.
> 
> As of today one way to hard refresh a repository in the argocd cli is:
> 
> argocd repo list
> argocd repo get --refresh hard \<repository url\>
> argocd app sync --prune \<application name\>

It seems this is incorrect or outdated. I've had no luck with `argocd repo get --refresh hard <repository url>` refreshing a repository in the same way that a Git webhook would, and [the docs](https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_repo_get/) don't seem to suggest it would either, as it only refreshes "connection status":

> --refresh string   Force a cache refresh on connection status , must be one of: 'hard'

**Comment by pre** [comment]
>. I've had no luck with argocd repo get --refresh hard <repository url> refreshing a repository in the same way that a Git webhook would

I can confirm. Also with argocd-applicationset-controller there is no way to refresh anything except resetting the whole Redis cache and recreating argocd-repo-server pods. (Repro: Try changing any ApplicationSet values without the webhook.)

Also anytime there is ”(cached)” visible in the repo-server logs, hard refresh / sync did not actually take the latest manifests into use. Typically this happens when there has been an error and possibly some backoff mechanism has been triggered, and only cache is used without an actual refresh.

**Comment by QuinnBast** [comment]
There has definitely been a regression here. I am running into this as well. The hard refresh button is not clearing our git cache in ArgoCD and ArgoCD wants to hang on to a commit that was pushed over 3 days ago and can't find any of the multiple new commits that were made over the past few days.

**Comment by dberardo-com** [comment]
is this still possible from the GUI or from the CRD manifest in v 3.7.1 ?
