### ISSUE TITLE
Custom resource actions overrides default actions

### ISSUE THREAD

**Issue by pokgak** [argoproj/argo-cd#9147]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I added a custom resource action to Deployments in my `argocd-cm.yaml` and then after it is applied, I lost the option to restart my deployment. I am using Argo CD version 1.21 which only has `restart` defined in `resource_customizations/apps/Deployment/actions`.

When not using the same action name as the default actions, I expect the default actions will not be overwritten, and instead the custom resource actions will be appended to the list of actions allowed on the resource. If the user wants to explicitly override the default actions, then they can use the same action name as the default.

**To Reproduce**

Add the following entry to `data` in `argocd-cm.yaml`:

```
resource.customizations.actions.apps_Deployment: |
    discovery.lua: |
      actions = {}
      -- actions defaults to disabled
      actions["scaleReplicaToZero"] = {["disabled"] = true}

      local replicas
      -- get current replica count
      if obj.spec.replicas ~= nil then
          replicas = obj.spec.replicas
      end

      if replicas != 0 then
          -- enable scaleReplicaToZero if current replica count is not 0
          actions["scaleReplicaToZero"]["disabled"] = false
      end
      return actions
    definitions:
    - name: scaleReplicaToZero
      action.lua: |
        obj.spec.replicas = 0
        return obj
```

**Expected behavior**

Both the `restart` action and custom resource actions will show up in the UI/CLI.

**Actual behavior**

Only the custom resource actions showed up in the UI/CLI. The `restart` action is not there and got overwritten.

**Screenshots**

**Version**

```shell
argocd: v2.3.3+07ac038.dirty
  BuildDate: 2022-03-30T05:20:22Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.9+5c51d5d
  BuildDate: 2022-02-03T20:30:01Z
  GitCommit: 5c51d5dae0a8c8940979db3eff5cc6be7bff9250
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by pokgak** [comment]
Looked into the code a bit and I think the following code is probably causing this issue. As I suspected, there's no merging of the config there, it's currently either-or. Will try to make it merge the config instead. Do point out if I'm wrong.

https://github.com/argoproj/argo-cd/blob/248929cacdc322411337140895daa1bddf8239dc/util/lua/lua.go#L283-L299

**Comment by sumanthkumarc** [comment]
Hit this bug, just when i thought how modular Argo is :p I think the possible workaround for now is just adding the upstream actions into our own argocd-cm configmap?

For example for deployment, take everything under this https://github.com/argoproj/argo-cd/tree/master/resource_customizations/apps/Deployment/actions and add this to our list of custom actions i guess.

**Comment by morey-tech** [comment]
As of Argo CD `2.13.0`, with the introduction of `mergeBuiltinActions: true` (https://github.com/argoproj/argo-cd/pull/19708), you can achieve the expected behaviour!

```
  resource.customizations.actions.apps_Deployment: |
    mergeBuiltinActions: true  # <--- This will fix it.
    discovery.lua: |
      actions = {}
      actions["Scale to Zero"] = {}
      return actions
    definitions:
      - name: Scale to Zero
        action.lua: |
          obj.spec.replicas = 0
          return obj
  ```
