### ISSUE TITLE
Users should be able to pass environment variables to Kustomize

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#9165]
# Summary

The user should be able to specify environment variables to be passed to Kustomize. Plugins enable this via the `spec.source.plugins.env` field.

# Motivation

Kustomize has some [interesting features](https://cloud-native.slack.com/archives/C01U45M2SVB/p1650059242036069?thread_ts=1649688703.512869&cid=C01U45M2SVB) that rely on reading environment variables.

@jannfis pointed out on [another issue](https://github.com/argoproj/argo-cd/issues/8317#issuecomment-1028390920) that this could be useful.

# Proposal

We could add a `env` field to the `kustomize` source. We'd want to either blocklist certain env vars (e.g. `GIT_` vars) or prefix all env vars for security.

**Comment by SelfhostedPro** [comment]
The main thing I'm using in the `interesting features` link above is using a [configmap generator from a file](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/#configmap-from-file) and not defining a value for the variable.

In the example from the documentation link above, the `application.properties` file would look like the following:
```
FOO
```
