### ISSUE TITLE
CMP commands are killed with KILL signal, preventing any cleanup

### ISSUE THREAD

**Issue by kklimonda-fn** [argoproj/argo-cd#9180]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Currently, when CMP command is running over timeout, cmpserver sends KILL signal to the process to cancel it. This can lead to various issues if the process expects to be able to cleanup after itself. One example of that would be running ssh-agent in the background to authenticate against additional repositories - ssh-agent prints its pid on stdout, and this information is lost when the process gets killed, making cleanup of ssh-agents problematic.

**To Reproduce**

A simple init scripts that will fork `ssh-agent` into background and then sleep for long enough to trigger timeout in repo-server.

Something akin to:

```python3
import re
import subprocess
import time
import os

def _parse_ssh_agent_output(output):
    _pattern = re.compile(
        r"SSH_AUTH_SOCK=(?P<SSH_AUTH_SOCK>[^;]+).*SSH_AGENT_PID=(?P<SSH_AGENT_PID>\d+)",
        re.MULTILINE | re.DOTALL,
    )
    match = _pattern.search(output)
    return match.groupdict()

result = subprocess.run(["ssh-agent", "-s"], text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
ssh_variables = _parse_ssh_agent_output(result.stdout)
os.environ.update(ssh_variables)
time.sleep(3600)
subprocess.run(["ssh-agent", "-k"], check=True)
```

With every interrupted iteration there should be an extra `ssh-agent -s` running.

**Expected behavior**

cmpserver should first send TERM signal, and KILL signal only after a few seconds, to allow process to do any potential cleanup if needed.

**Version**

quay.io/argoproj/argocd:v2.3.3

**Comment by crenshaw-dev** [comment]
Here's the important line: https://github.com/argoproj/argo-cd/blob/acfc396ac01c2be6cb4f2cdb7cb4581a5c8cf608/cmpserver/plugin/plugin.go#L98

**Comment by Ashwin901** [comment]
Hello @crenshaw-dev I would like to work on this issue. Can you please assign this issue to me ?

**Comment by crenshaw-dev** [comment]
@Ashwin901 we usually don't do assignments for relatively small tasks. Feel free to go ahead and open a PR! :-)

**Comment by Ashwin901** [comment]
So in this case we can use a timer to wait for a few seconds before killing the process so as to allow to do any cleanup if required?
