### ISSUE TITLE
Can't Argo CD install itself using Argo CD?

### ISSUE THREAD

**Issue by drozzy** [argoproj/argo-cd#9182]
This is going to be a very dumb question, as I'm completely new to Argo CD, but can't argo cd instructions here:
https://argo-cd.readthedocs.io/en/stable/getting_started/
be replaced with argo cd way of doing this?

In other words, if Argo CD advocates for declarative way of installing things, why are its own instructions procedural?

Perhaps I am misunderstanding something.

**Comment by rodrigo14miguel** [comment]
Im not sure if I understood the question.
The first time you create an ArgoCD instance you'll need to do it by hand (kubectl apply ...).

What you can do is, in an ArgoCD instance, create an app that self manages ArgoCD itself (for config updates or lifecycle management). 
Be aware that if anything goes wrong during a sync (like some misconfiguration), you might lose access to your ArgoCD instance and have to correct it by hand.

Another thing you can do is create other ArgoCD instances though the first one, as you would create any other app.

**Comment by drozzy** [comment]
Ok thanks.
