### ISSUE TITLE
can't open https://cd.apps.argoproj.io/

### ISSUE THREAD

**Issue by sugesslee** [argoproj/argo-cd#9192]
https://github.com/argoproj/argo-cd/discussions/9191

**Comment by gaeljw** [comment]
Duplicate of #9185

**Comment by michtek** [comment]
The site is down again

**Comment by crenshaw-dev** [comment]
@leoluz do you have time to take a look?

**Comment by leoluz** [comment]
Issue is remediated. Need to invest time to fix the root cause.
