### ISSUE TITLE
Cannot import argocd as dependency

### ISSUE THREAD

**Issue by wangli1030** [argoproj/argo-cd#9198]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hi, I am trying to import [types.go](https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go) to unmarshall the API response. However, since `k8s.io/kubernetes v1.23.1` is required in the [go.mod](https://github.com/argoproj/argo-cd/blob/master/go.mod#L226), it will caused an error when import `go: k8s.io/kubernetes@v1.23.1 requires k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0`. [As it mentioned](https://github.com/kubernetes/kubernetes/issues/90358), it should not depend directly on `k8s/kubernetes`. Argo Rollouts had similar [issue](https://github.com/argoproj/argo-rollouts/issues/1837). 

**To Reproduce**

**Expected behavior**

`k8s.io/kubernetes v1.23.1` should be safely removed from go.mod.

**Screenshots**

**Version**

```shell
argocd-server: v2.2.5+8f981cc
```

**Logs**

```
go: k8s.io/kubernetes@v1.23.1 requires k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**Comment by xyq175com** [comment]
I will work on this and submit PR later

**Comment by Lirt** [comment]
Any chance someone from ArgoCD team could look at it?

**Comment by crenshaw-dev** [comment]
Yep, to reiterate @Lirt's comment, the solution is documented here: https://argo-cd.readthedocs.io/en/stable/user-guide/import/
