### ISSUE TITLE
Argo-cd perimeter/integration

### ISSUE THREAD

**Issue by bhack** [argoproj/argo-cd#92]
What is the scope of argo-cd over [Jenkins X plans](http://jenkins-x.io/news/changes-april-11-2018/) and [Spinnaker interaction with k8s](https://www.spinnaker.io/guides/tutorials/codelabs/kubernetes-source-to-prod/). 
Also, is it planned any integration with the new emerging k8s [dev tools](https://blog.hasura.io/draft-vs-gitkube-vs-helm-vs-ksonnet-vs-metaparticle-vs-skaffold-f5aa9561f948) that are starting to be discussed in [sig-apps](https://github.com/kubernetes/community/pull/2040)?

**Comment by jessesuen** [comment]
Thanks for the interest! Let me preface my answer by first explaining that I have a surface level experience with Spinnaker (from when we were evaluating its Kubernetes features ourselves), and have only read about Jenkins X. 

From my limited understanding, I would say the main differences are:
* Scope is much smaller: ArgoCD is solely concentrated on K8s, whereas Spinnaker handles pretty much all cloud providers and container orchestrators. Jenkins X is k8s based, but is a complete platform and helps bootstrap your entire development process, deployment model, with integrations with your issue tracker
* ArgoCD will stray into the territory of CO (continuous operations) and provide ops functionality such as application monitoring, user-defined actions
* ArgoCD is GitOps based (declarative, level driven), where Spinnaker is event/pipeline driven
* ArgoCD is agnostic to your CI, and provides gRPC/REST/CLI to integrate with your CI of choice. Jenkins X of course requires Jenkins
* ArgoCD is less opinionated. It's current opinion is that that manifests be described in ksonnet (which will likely expand in the future) apps in git. Spinnaker uses naming conventions. Jenkins X appears to mandate separate git repositories for environments

We haven't looked at dev tool integration, but it's definitely something we're open to.

**Comment by bhack** [comment]
To summarize.. with the integration of dev tools it will be quite complete.

**Comment by bhack** [comment]
@jstrachan I've seen that you have started also to integrated some of the metnioned dev tools right?

**Comment by jessesuen** [comment]
By now the perimeter of Argo CD is pretty clear. Also we've now documented how Argo CD can be used with Kubeflow

https://www.kubeflow.org/docs/use-cases/gitops-for-kubeflow/

**Comment by jgbiii** [comment]
Jenkins X does not require Jenkins, although it is an option. However, it can also run entirely independent leveraging Tekton.
