### ISSUE TITLE
Argocd-server gets unauthorised response to watch secrets/configMap,login from UI fails

### ISSUE THREAD

**Issue by divya-prakash2** [argoproj/argo-cd#9201]
argocd-server pod logs are as follows 
![image](https://user-images.githubusercontent.com/55496734/165050851-4acac5e1-8945-438a-b8dc-36adaf071e61.png)

During the same time, logging into argocd UI also is not possible

Only solution is to kill the argocd-server pod and allow it to respawn the new argocd-server pod.

Is there a way to force relogin the argocd-server ? Are the user session getting expired which is not properly cleaned on the argocd-server end

**Version**

2.2.5
gl-gateway002-k3s-master-vm1:~ # kubectl get all -n argocd -o wide
NAME                                     READY   STATUS    RESTARTS   AGE    IP            NODE                   NOMINATED NODE   READINESS GATES
pod/argocd-application-controller-0      1/1     Running   0          11d    10.42.3.13    gl-gateway002-sles01   <none>           <none>
pod/argocd-application-controller-1      1/1     Running   0          11d    10.42.4.14    gl-gateway002-sles02   <none>           <none>
pod/argocd-dex-server-798c94fbb6-2wj8q   1/1     Running   0          11d    10.42.5.11    gl-gateway002-sles03   <none>           <none>
pod/argocd-redis-75588ff885-jvfnp        1/1     Running   0          11d    10.42.4.11    gl-gateway002-sles02   <none>           <none>
pod/argocd-repo-server-5f46f46fc-dplg7   1/1     Running   0          11d    10.42.4.12    gl-gateway002-sles02   <none>           <none>
pod/argocd-server-67bd4c9b9d-wvgzp       1/1     Running   0          142m   10.42.4.171   gl-gateway002-sles02   <none>           <none>

NAME                            TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE   SELECTOR
service/argocd-dex-server       ClusterIP      10.43.118.52    <none>          5556/TCP,5557/TCP,5558/TCP   11d   app.kubernetes.io/name=argocd-dex-server
service/argocd-metrics          ClusterIP      10.43.112.129   <none>          8082/TCP                     11d   app.kubernetes.io/name=argocd-application-controller
service/argocd-redis            ClusterIP      10.43.136.169   <none>          6379/TCP                     11d   app.kubernetes.io/name=argocd-redis
service/argocd-repo-server      ClusterIP      10.43.199.254   <none>          8081/TCP,8084/TCP            11d   app.kubernetes.io/name=argocd-repo-server
service/argocd-server           LoadBalancer   10.43.106.217   172.16.18.204   80:30230/TCP,443:30589/TCP   11d   app.kubernetes.io/name=argocd-server
service/argocd-server-metrics   ClusterIP      10.43.135.163   <none>          8083/TCP                     11d   app.kubernetes.io/name=argocd-server

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS           IMAGES                           SELECTOR
deployment.apps/argocd-dex-server    1/1     1            1           11d   dex                  ghcr.io/dexidp/dex:v2.30.2       app.kubernetes.io/name=argocd-dex-server
deployment.apps/argocd-redis         1/1     1            1           11d   redis                redis:6.2.6-alpine               app.kubernetes.io/name=argocd-redis
deployment.apps/argocd-repo-server   1/1     1            1           11d   argocd-repo-server   quay.io/argoproj/argocd:v2.2.5   app.kubernetes.io/name=argocd-repo-server
deployment.apps/argocd-server        1/1     1            1           11d   argocd-server        quay.io/argoproj/argocd:v2.2.5   app.kubernetes.io/name=argocd-server

NAME                                           DESIRED   CURRENT   READY   AGE   CONTAINERS           IMAGES                           SELECTOR
replicaset.apps/argocd-dex-server-798c94fbb6   1         1         1       11d   dex                  ghcr.io/dexidp/dex:v2.30.2       app.kubernetes.io/name=argocd-dex-server,pod-template-hash=798c94fbb6
replicaset.apps/argocd-redis-75588ff885        1         1         1       11d   redis                redis:6.2.6-alpine               app.kubernetes.io/name=argocd-redis,pod-template-hash=75588ff885
replicaset.apps/argocd-repo-server-5f46f46fc   1         1         1       11d   argocd-repo-server   quay.io/argoproj/argocd:v2.2.5   app.kubernetes.io/name=argocd-repo-server,pod-template-hash=5f46f46fc
replicaset.apps/argocd-server-67bd4c9b9d       1         1         1       11d   argocd-server        quay.io/argoproj/argocd:v2.2.5   app.kubernetes.io/name=argocd-server,pod-template-hash=67bd4c9b9d

NAME                                             READY   AGE   CONTAINERS                      IMAGES
statefulset.apps/argocd-application-controller   2/2     11d   argocd-application-controller   quay.io/argoproj/argocd:v2.2.5

Please let us know if there any further information needed

**Comment by divya-prakash2** [comment]
Any updates on this issue ? Any parameters we need to set for the above issue ?

**Comment by divya-prakash2** [comment]
Seems like the issue was with ntp sync issue on master and agent pods of kubernetes cluster. Syncing the time properly helped resolve this issue. Closing for now. Thanks

**Comment by DjarallahBrahim** [comment]
Hello

i'm having the same problem on GKE with argocd-server !
