### ISSUE TITLE
When is helm's remote value .yaml file supported

### ISSUE THREAD

**Issue by liuwenzhi0318** [argoproj/argo-cd#9211]
At present, only the value file of the chart can be read. When can the value.yaml file in the remote configuration be read, such as gitlab github

**Comment by crenshaw-dev** [comment]
Duplicate of https://github.com/argoproj/argo-cd/issues/2789.

At the moment, it's looking like that will be a 2.5 feature.

**Comment by liuwenzhi0318** [comment]
In the first stage, the build product is to upload the file to the gocd-server, so can the gocd-server download the product in the second stage?
