### ISSUE TITLE
Unauthorized error when refreshing state

### ISSUE THREAD

**Issue by lbrictson** [argoproj/argo-cd#924]
The argocd UI shows "Unauthorized" as the error when refreshing deployment state of remote kubernetes clusters, this is happening when querying remote EKS clusters using IAM auth.

I believe the issue is the auth token that is being cached is expiring before it is refreshed.  This is consistently repeatably and happens on a deployment about 5 times per hour.

Steps to replicate
1.  Install argocd in cluster A
2.  Give argocd access to deploy to Cluster B (Cluster B is an EKS cluster in AWS using IAM auth)
3.  Do a deployment, refresh the page every few minutes and you will see the unauthorized error

I think we need to be more aggressive about refreshing the IAM auth token for EKS clusters.

**Comment by alexmt** [comment]
Argo CD does not cache token. If AWS IAM authentication is configured Argo CD generates appropriate K8S config and relies on kubectl/k8s client:

https://github.com/argoproj/argo-cd/blob/1deeada249d98c30f12820a55669e834d02a2d5d/pkg/apis/application/v1alpha1/types.go#L763-L771

I suspect issue might be in aws-iam-authenticator: https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/30 

@lbrictson is would help if you could attach relevant application-controller logs .

**Comment by jessesuen** [comment]
I suspect it's this: https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/133. I can't tell which version this was fixed in, but the version of aws-iam-authenticator that we use, predates October 13th, when this was merged.

**Comment by lbrictson** [comment]
so maybe simply updating the aws-iam-authenticator binary will yield a fix?

**Comment by jessesuen** [comment]
Yes, I believe so. I took a look at the fix. The version of aws-iam-authenticator we are bundling does not set expiration of tokens so go-client does not seem to know to refresh it until it’s too late. Their fix is to set a refresh time at an interval less than the one AWS uses (14 minute refresh vs. a 15 minute token).

**Comment by jessesuen** [comment]
@lbrictson if you replace aws-iam-authenticator with the v0.4.0-alpha.1 release, will things start working? You would have to `kubectl cp` the binary to the argocd-server and application-controller pods and replace the binary.

https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/0.4.0-alpha.1

If things work, I think we can ship Argo CD with v0.4.0-alpha.1 aws-iam-authenticator release, so long as nothing else is regressing. I don't have an EKS cluster readily available to test with at the moment.

**Comment by lbrictson** [comment]
@jessesuen that seems doable, i'll drop that into the containers and see what happens.  The issue happens several times per hour so it should be easy to see the effects of.

I'll report back later today with the results

**Comment by lbrictson** [comment]
@jessesuen changing to the new iam authenticator breaks it because the new authenticator has a different output that it looks like argo is having trouble parsing

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo-cd/pull/948
