### ISSUE TITLE
Long application names become unreadable in the UI

### ISSUE THREAD

**Issue by janpieper** [argoproj/argo-cd#9241]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When having long names for ArgoCD applications, they may become unreadable in the UI and there is no tooltip or similar to make the full name visible.

https://github.com/argoproj/argo-cd/blob/6d19813c468af843dec274b175c5929720a3efa7/ui/src/app/applications/components/applications-list/applications-tiles.tsx#L139-L144

**To Reproduce**

Create an ArgoCD application with a very long name. I've used `example-application-name-that-is-very-long` for my example.

**Expected behavior**

Adding a tooltip could help to make the full application name visible by hovering the application name.

![Screenshot from 2022-04-28 13-27-21](https://user-images.githubusercontent.com/426371/165742402-de5a960d-6412-4d5d-a2e7-920e30d52aeb.png)

**Screenshots**

![Screenshot from 2022-04-28 13-21-20](https://user-images.githubusercontent.com/426371/165741459-4b5884d0-69f2-444d-9ca4-a102e582a3cf.png)

**Version**

```shell
$ argocd version
argocd: v2.2.3+987f665
  BuildDate: 2022-01-18T17:53:49Z
  GitCommit: 987f6659b88e656a8f6f8feef87f4dd467d53c44
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.3+07ac038
  BuildDate: 2022-03-30T00:06:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.5.2+ksops.v3.0.2 2022-04-14T07:20:55Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

_None_

**Comment by saumeya** [comment]
Hi @janpieper, there is currently a PR open to address the issue - https://github.com/argoproj/argo-cd/pull/9130

**Comment by janpieper** [comment]
Ooops, there already is an issue + PR for this topic. Seems like my search-fu wasn't good enough :wink:

Closing in favor of #9130!

**Comment by saumeya** [comment]
No problem, thanks for noticing and creating it :)
