### ISSUE TITLE
ApplicationSet Pull Request Generator for GitLab

### ISSUE THREAD

**Issue by DevSpork** [argoproj/argo-cd#9262]
# Summary

There is a mention of the possibility to use GitLab as a source for the Pull Request Generator in the [docs](https://github.com/argoproj/argo-cd/tree/master/applicationset/services/pull_request), still, there is no code for this type of generator present in the [corresponding folder](https://github.com/argoproj/argo-cd/tree/master/applicationset/services/pull_request). Accordingly, it is currently not possible to use GitLab as a source.

# Motivation

This would make it possible for people hosting their repositories on GitLab to use the Pull Request Generator.

# Proposal

Like for GitLab, Bitbucket and GitTea there should be an option to use GitLab (SaaS and SelfHosted) as a source for the ApplicationSet Pull Request Generator.

**Comment by iverberk** [comment]
@DevSpork I have a branch ready for this, just need to write the tests to create the PR. This is the code so far: https://github.com/iverberk/argo-cd/commit/69d07d63ae80530b9ecfe8ae5cce9765f6800ecf

**Comment by DevSpork** [comment]
@iverberk That's great news. If I can help you in any way, that doesn't require knowledge in Go let me know.

**Comment by iverberk** [comment]
Ok, #9264 is ready for review and merge (all checks should pass, otherwise I'll fix). Not sure who to ping, or just wait for the enhancement process to do its work. This is a relatively simple extension of existing functionality so I can't see much problems with it being accepted. Implementation-wise, I guess we'll find out :-)

**Comment by mcouliba** [comment]
Hello @iverberk, I just tested it and it works well 
Good job!
