### ISSUE TITLE
outofsync healthy status when there is no diff to find. 

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#927]
argocd: v0.11.0-rc1+476e351
  BuildDate: 2018-12-10T17:44:44Z
  GitCommit: 476e351d12f8633e464f27927d95b171027fa622
  GitTreeState: clean
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v0.11.0+483872a
  BuildDate: 2018-12-10T15:19:41Z
  GitCommit: 483872a190f39a5520d02fb8bb37a7d8f7b7b4ee
  GitTreeState: clean
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.0

I'm getting  OutOfSync  Healthy on syncing the application:

extensions                 NetworkPolicy       xxxx              allow-ops-kubesystem                   OutOfSync  Healthy
extensions                 NetworkPolicy       xxxx              allow-within-namespace                 OutOfSync  Healthy

When doing a diff there is nothing to find:

 argocd app diff generic-all-cluster
===== NetworkPolicy allow-ops-kubesystem ======
===== NetworkPolicy allow-within-namespace ======

**Comment by peterbosalliandercom** [comment]
It looks like it only appears t be happening with network policies, the other are synced and healthy (role, rolebinding, namespace, clusterrole and clusterrolebinding.

**Comment by peterbosalliandercom** [comment]
some network policies are synced fine:

networking.k8s.io          NetworkPolicy       xxxx allow-within-namespace                 Synced     Healthy

and some not, where the difference is the group name: extensions:

extensions                 NetworkPolicy       xxxx  allow-within-namespace                 OutOfSync  Healthy

**Comment by peterbosalliandercom** [comment]
it looks like there are duplicates

argocd app get generic-all-cluster | grep within | grep demo
networking.k8s.io          NetworkPolicy       demo                  allow-within-namespace                 Synced     Healthy
extensions                 NetworkPolicy       demo                  allow-within-namespace                 OutOfSync  Healthy

**Comment by peterbosalliandercom** [comment]
Maybe it has to do with syncing? At first I synced from the UI, then I got outofsync items which were not able to sync from the UI. Then I started a sync from the argocd client.

**Comment by peterbosalliandercom** [comment]
Before syncing:

![image](https://user-images.githubusercontent.com/9946020/49873749-ef2c5700-fe1c-11e8-85cb-ef0efe77c021.png)

after syncing, see the red arrow, those are 'created'? the syncing went ok but these extensions where are they coming from:

![image](https://user-images.githubusercontent.com/9946020/49873853-27cc3080-fe1d-11e8-8d7b-0e84441158b9.png)

**Comment by jessesuen** [comment]
Ah. This looks like another Kind that is duplicated in both extensions and another api group (networking.k8s.io). We have special handling of the extensions group to reduce the duplication of effort when dealing with Deployments, ReplicaSets, DaemonSets, etc... which exists in both extensions and apps. We need to handle this.

**Comment by alexmt** [comment]
Thank you for finding it @peterbosalliandercom ! The `extensions` group is deprecated in Kubernetes and we have special handling in argocd. We already have handling for DaemonSet, ReplicaSet and Deployment but forgot about NetworkPolicy. Fixing it
