### ISSUE TITLE
Error in manifest for ha/namespace-install.yaml

### ISSUE THREAD

**Issue by awca22** [argoproj/argo-cd#9282]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
There is currently an issue with the manifests for ha-namespaced install,  it seems like it is currently broken.  
Specifically [this deployment](https://github.com/argoproj/argo-cd/blob/master/manifests/ha/namespace-install.yaml#L1212). 

Compared with the the other manifests seems like it is using `[quay.io/argoproj/argocd:latest](http://quay.io/argoproj/argocd:latest)` instead of `[quay.io/argoproj/argocd-applicationset:v0.4.1](http://quay.io/argoproj/argocd-applicationset:v0.4.1)` also the container command was recently changed but it is also broken:
```
      containers:
      - command:
        - entrypoint.sh
        - argocd-applicationset-controller
```

The second command `argocd-applicationset-controller` doesn't work as it isn't yet updated in the image and still uses `applicationset-controller`.

**To Reproduce**

Do an apply of [this deployment](https://github.com/argoproj/argo-cd/blob/master/manifests/ha/namespace-install.yaml#L1212) and it will not install correctly as it is currently broken, the applicationset-controller pod fails.

**Expected behavior**

Installation should work fine with this manifest.

**Version**

```shell
❯ argocd version --grpc-web
argocd: v2.3.3+07ac038.dirty
  BuildDate: 2022-03-30T05:14:36Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.3.3+07ac038
  BuildDate: 2022-03-30T00:06:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Comment by chetan-rns** [comment]
Hi @awca22, can you please share the error message? I was able to install the `argocd-applicationset-controller` without any issues. And regarding the image, the applicationset was recently merged into argocd and is available within the same image.

**Comment by mpodolsk** [comment]
why does your installation yamls use a sliding tag "latest" ?
`quay.io/argoproj/argocd:latest`
https://github.com/argoproj/argo-cd/blob/master/manifests/namespace-install.yaml#L974

this makes no sense, it means that my pod could pull the latest image "upgrade" itself randomly :) without me knowing about it... 
Idk if that was a mistake on some version in manifests or what but i did the namespace install and ended up with        
 image: quay.io/argoproj/argocd:latest in my deployment

**Comment by awca22** [comment]
@chetan-rns I think the issue was bad on the previous latest version I was using.
It seems to be fixed now.

@mpodolsk I think you should be using the manifest version from the releases, that's what I did to fix this issue.

Seems like this branch is only using the latest for all the manifests.
