### ISSUE TITLE
Use mocks for ApplicationSet Gitea, GitHub, and GitLab unit tests

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#9287]
# Summary

The Gitea unit tests for the PR and SCM generators currently make external API calls. This makes the tests flaky. We should instead use a mocked service.

https://github.com/argoproj/argo-cd/blob/master/applicationset/services/scm_provider/gitea_test.go
https://github.com/argoproj/argo-cd/blob/master/applicationset/services/pull_request/gitea_test.go

# Motivation

Last week integration tests were broken for a couple days because of a change in the tested Gitea org.

# Proposal

We could follow the model of the Bitbucket tests and use a mocked service.

https://github.com/argoproj/argo-cd/blob/1d765a072cfdf3921cf7bf43c353bda61d57347c/applicationset/services/pull_request/bitbucket_server_test.go#L14

**Comment by ashutosh16** [comment]
@crenshaw-dev  Can you assign the issue to me? thx!

**Comment by rishabh625** [comment]
Lets include github and gitlab mock too with this issue
@ashutosh16 : I am raising PR for github and gitlab , i hopw u worked for gitea only

**Comment by rishabh625** [comment]
@crenshaw-dev : can u assign to me as well, as github supports multiple asignee

**Comment by rishabh625** [comment]
@ashutosh16 : any update for gitea change?

**Comment by crenshaw-dev** [comment]
Reopened for gitea.
