### ISSUE TITLE
Argo CD may benefit from a code of conduct

### ISSUE THREAD

**Issue by merenbach** [argoproj/argo-cd#93]
A code of conduct can promote inclusiveness and describe step-by-step processes for addressing conflict within the project.  See <https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/>.

**Comment by jessesuen** [comment]
Probably should just copy the one from argo:
https://github.com/argoproj/argo/blob/master/CODE_OF_CONDUCT.md

**Comment by merenbach** [comment]
@jessesuen considering that we have contributor agreements, is it possibly worth integrating a clause to abide by the agreed-upon code-of-conduct into those?

**Comment by edlee2121** [comment]
The community docs in the main argo repo https://github.com/argoproj/argo apply to all argoproj projects.
