### ISSUE TITLE
support stable helm charts with seperate values.yaml file

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#932]
Don't know if already possible but presume not. I would like to create an app like this:

app create grafana-test --repo https://github.com/helm/charts.git --path stable/grafana --dest-server https://xxxxx --dest-namespace default --values <file on local machine>

where the file comes from my laptop for example, instead of declaring all parameters with -p

Furthermore, it should probably be possible to create app from helm stable chart from explicit chart version

**Comment by alexmt** [comment]
I think helm supports remote values file. So you can put URL instead of path  into '--values' flag

**Comment by peterbosalliandercom** [comment]
Alright with public repo this works, but with private?

**Comment by jessesuen** [comment]
We currently can only do what is possible with the `helm template` command, since under the covers, we simply run `helm template` to generate the manifests. I'm not sure if helm will look to .netrc files for stored http credentials, but if they do, if this file was volume mapped to the repo-server, the repo-server would be able to get the values files from private repos.

**Comment by peterbosalliandercom** [comment]
Looks like if you request the raw page from github the (personal) token is added to the URL with this complete URL it is possible to create the app with this raw values.yaml like this: 

The user where the token comes from you do this with should have only read rights on certain repo's.

argocd app create grafana-test --repo https://github.com/helm/charts.git 
--path stable/grafana 
--dest-server https://dest.server
--dest-namespace default 
--values https://raw.githubusercontent.com/xxxxxxxxxxx/sourcelocation/master/grafana/helm-config.yaml?token=xxxxxxxxxxxxxxxxxxxxx

**Comment by peterbosalliandercom** [comment]
Problem there is that I have not found a way to delete the token or change it for security purposes

**Comment by peterbosalliandercom** [comment]
Thanks for the feedback, will search further.

**Comment by wilalalee** [comment]
trying to specify a helm chart values file (with path,and file locates at git repo) on web ui, but can't save successfully.
![image](https://user-images.githubusercontent.com/48674402/58550165-c1f32a00-823f-11e9-81e8-1fb3ff9c655b.png)

**Comment by Aliabbask08** [comment]
@wilalalee any solution you got?
