### ISSUE TITLE
Cronjob triggers instantly on schedule update

### ISSUE THREAD

**Issue by doverk96** [argoproj/argo-cd#9331]
ArgoCD version: v2.0.0+f5119c0

**Describe the bug**
Whenever I am trying to update schedule for an existing cronjob, inspite of triggering it at scheduled time, it triggers it on update.

**To Reproduce**

Change any existing cronjob schedule, set it to any time other than now.
It will trigger job immediately, inspite if triggering it as per the schedule.

**Expected behavior**

It should not trigger the job other than the scheduled time.
**Version**

v2.0.0+f5119c0

**Comment by blakepettersson** [comment]
Is this still an issue?
