### ISSUE TITLE
Application Set unable to process github webhook event 

### ISSUE THREAD

**Issue by rishabh625** [argoproj/argo-cd#9349]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

If applicationset url is added as a github webhook, webhook is not posted to application it fails with below error
Webhook processing failed: invalid character &#39;p&#39; looking for beginning of value
with response code 400

**To Reproduce**

Add application set url to recieve webhook from github, github sends event
and get failed response 
Webhook processing failed: invalid character &#39;p&#39; looking for beginning of value

**Comment by rishabh625** [comment]
it was a misconfiguration at my side.

**Comment by BeryJu** [comment]
For us this was caused by having the wrong content-type set, make sure it's set to application/json 
<img width="411" alt="image" src="https://user-images.githubusercontent.com/1932513/234263880-f291e9b4-c56e-461f-9deb-a5ac972eacc5.png">
