### ISSUE TITLE
provide helm chart for installing argo-cd

### ISSUE THREAD

**Issue by davidkarlsen** [argoproj/argo-cd#935]
If would be nice to have a helm-chart for installing argo-cd.

**Comment by jessesuen** [comment]
I agree. Having a chart is pretty much expected these days. 

We so have one for argo workflows and events, but not for argo cd: https://github.com/argoproj/argo-helm. I also think we should move to official chart repository.

**Comment by mduarte** [comment]
Any plans to have the argocd official helm chart available for this new 0.11 release?

**Comment by lcostea** [comment]
I am also interested with this because I started using argo-cd recently and I am used to Helm charts. 
Would you accept PRs for it? 
Just from using argo-cd I see a crd-install hook would be needed and also a parameter to install it with cluster-admin access or namespace level install.

**Comment by jessesuen** [comment]
@lcostea we would most definitely accept a helm chart for Argo CD. You can send the PR to:
https://github.com/argoproj/argo-helm

**Comment by lcostea** [comment]
I am actively working on this, you can see the progress at https://github.com/lcostea/argo-helm
There are still some things to be done: parameterize dex deployment, helm hook for crds, separate cluster and namespace install by parameter, crds cleanup with hook-delete-policy and maybe others. But if you have some time and want to check the current work, your feedback will be highly appreciated (so we don't leave it all for the PR).

**Comment by lcostea** [comment]
PR is submitted, feedback will be highly appreciated:
https://github.com/argoproj/argo-helm/pull/34

**Comment by lcostea** [comment]
The issue can be closed, the chart is here:
https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd

**Comment by alexmt** [comment]
Thank you @lcostea !
