### ISSUE TITLE
AppSets allow arbitrary `api` fields for SCM generators - document risk to secrets

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#9352]
# Summary

I think we should edit documentation to further emphasize that ApplicationSets should _only_ be createable/editable by admins. 

There are numerous risks (including arbitrary `Project` fields). One risk is that a malicious user could set the `api` field for an API endpoint to something that they control. They could then read the secret which is sent to that endpoint by the ApplicationSet controller.

# Motivation

As an Argo CD admin I might be tempted to grant non-admins access to create or update ApplicationSet resources. It would be good to know that secret exfiltration is a risk.

# Proposal

The information described above should be added to the ApplicationSet documentation, and links to that documentation should be added to each place in the Argo CD docs that suggest ApplicationSet use cases.

**Comment by romuduck** [comment]
I agree. On our side we indeed groups appset into a dedicated repo that only admin can manage... it's too sensitive/risky otherwise

**Comment by spzala** [comment]
Hi @crenshaw-dev I was looking at this issue from a triage perspective, and I think the needed work is nicely done by you under https://github.com/argoproj/argo-cd/pull/9466 (i.e. new security doc, referencing it to other appsets doc etc), so I guess we can close this issue? Also, not sure if my understanding is correct :) but have I opened a related PR https://github.com/argoproj/argo-cd/pull/10087 just to add `api` field as an example. Thanks!
