### ISSUE TITLE
Abort sync on Application warnings

### ISSUE THREAD

**Issue by slok** [argoproj/argo-cd#9376]
### Discussed in https://github.com/argoproj/argo-cd/discussions/9255

<div type='discussions-op-text'>

<sup>Originally posted by **slok** April 29, 2022</sup>
Hi! :wave: 

Today we had an incident regarding this. I'll try to give some context first:

- We are using app-of-apps pattern.
- This Application (app-of-apps), has an Application identified with the name `my-app-1`.
- Accidentally during a service migration, we created another app named the same (`my-app-1`), this new app, pointed to another repo path, and had automated prune enabled. :facepalm:
- With the bad luck that ArgoCD decided to apply the last one (new one), so it applied the settings of this other path and auto-prune, so it pruned all the old app resources (including ingress, ns...).
- And this situation was one of the main causes of the incident.

Argo was correctly [warning about having 2 resources with the same identifiers](https://github.com/argoproj/argo-cd/issues/1070). But there wasn't anything we could do at that point, it was late, everything was applied, and returning 5xx.

:question: My question is: app-of-apps is a very critical Application (if not the most one) in our ArgoCD setup, is there an option or a way of avoiding syncing the app with any kind of warning?

Thanks!</div>

**Comment by brunocascio** [comment]
I faced something similar. Probably this would help you https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#prevent-an-applications-child-resources-from-being-deleted-when-the-parent-application-is-deleted
