### ISSUE TITLE
sync error when deploying stable grafana chart with default values.yaml

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#939]
![image](https://user-images.githubusercontent.com/9946020/50157285-550f5780-02d1-11e9-9dcc-f1b85bf0ffb5.png)
After deploying stable chart sync does not work. 

argocd app create grafana-test --repo https://github.com/helm/charts.git --path stable/grafana --dest-server https://xxxxxx --dest-namespace test

**Comment by peterbosalliandercom** [comment]
stacktrace from controller:

Recovered from panic: interface conversion: interface {} is nil, not []interface {}\ngoroutine 75 [running]:\nruntime/debug.Stack(0xc421984e90, 0x1541dc0, 0xc4218b07c0)
/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem.func1(0xc42050a460, 0x14aeb60, 0xc422ab6930)
/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:646 +0x8e\npanic(0x1541dc0, 0xc4218b07c0)
/usr/local/go/src/runtime/panic.go:502 +0x229\ngithub.com/argoproj/argo-cd/util/json.removeFields(0x146e580, 0xc422c541e0, 0x0, 0x0, 0xc4223b40b8, 0xc422751e01)
/go/src/github.com/argoproj/argo-cd/util/json/json.go:44 +0x1d2\ngithub.com/argoproj/argo-cd/util/json.RemoveMapFields(0xc422751d40, 0xc422751b30, 0xc421985140)
/go/src/github.com/argoproj/argo-cd/util/json/json.go:58 +0x126\ngithub.com/argoproj/argo-cd/util/diff.ThreeWayDiff(0xc42088c418, 0xc42088c420, 0xc42088c3f8, 0xc420ab5d20, 0x0, 0x0)
/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:82 +0x92\ngithub.com/argoproj/argo-cd/util/diff.Diff(0xc42088c3e8, 0xc42088c3f8, 0xc420ab5d20)
/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:44 +0xbf\ngithub.com/argoproj/argo-cd/util/diff.DiffArray(0xc4206a4a80, 0xb, 0x10, 0xc4220a42a0, 0xb, 0xb, 0x7, 0xc420b70cb0, 0x7)
/go/src/github.com/argoproj/argo-cd/util/diff/diff.go:221 +0xea\ngithub.com/argoproj/argo-cd/controller.(*appStateManager).CompareAppState(0xc42009db60, 0xc420c3e900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/argoproj/argo-cd/controller/state.go:198 +0x1041\ngithub.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem(0xc42050a460, 0x1)
/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:680 +0x3cf\ngithub.com/argoproj/argo-cd/controller.(*ApplicationController).Run.func1()
/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:326 +0x36\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4204da910)
/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4204da910, 0x3b9aca00, 0x0, 0x1, 0xc4200a6180)
/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd\nk8s.io/apimachinery/pkg/util/wait.Until(0xc4204da910, 0x3b9aca00, 0xc4200a6180)
/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d\ncreated by github.com/argoproj/argo-cd/controller.(*ApplicationController).Run
/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:325 +0x1eb\n

**Comment by alexmt** [comment]
Thank you for reporting it @peterbosalliandercom! Sent PR to fix it: https://github.com/argoproj/argo-cd/pull/940

Note: grafana helm chart as well as some other charts has an issue described at https://github.com/argoproj/argo-cd/issues/941  .

**Comment by peterbosalliandercom** [comment]
After building docker file and running it won't startup: 

2018/12/19 07:41:22 [Model:]
2018/12/19 07:41:22 r.r: sub, res, act, obj
2018/12/19 07:41:22 p.p: sub, res, act, obj, eft
2018/12/19 07:41:22 e.e: some(where (p_eft == allow)) && !some(where (p_eft == deny))
2018/12/19 07:41:22 m.m: g(r_sub, p_sub) && keyMatch(r_res, p_res) && keyMatch(r_act, p_act) && keyMatch(r_obj, p_obj)
2018/12/19 07:41:22 g.g: _, _
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x13dfcc5]
goroutine 1 [running]:
github.com/casbin/casbin/persist.LoadPolicyLine(0xc420645569, 0x1, 0xc4205d5320)
        /go/src/github.com/casbin/casbin/persist/adapter.go:37 +0x125
github.com/qiangmzsx/string-adapter.(*Adapter).LoadPolicy(0xc4204d92a0, 0xc4205d5320, 0xc420645400, 0xc42014e000)
        /go/src/github.com/qiangmzsx/string-adapter/adapter.go:48 +0xa6
github.com/casbin/casbin.(*Enforcer).LoadPolicy(0xc4204f4fc0, 0x5, 0xc420911988)
        /go/src/github.com/casbin/casbin/enforcer.go:208 +0x53
github.com/argoproj/argo-cd/util/rbac.(*Enforcer).SetBuiltinPolicy(0xc42060e480, 0xc420644500, 0x4aa, 0x4, 0x198fe94)
        /go/src/github.com/argoproj/argo-cd/util/rbac/rbac.go:147 +0x117
github.com/argoproj/argo-cd/server.NewServer(0x100, 0xc420541ed0, 0x4, 0x199bf67, 0x16, 0x7fff9ae2c533, 0xb, 0x19814bd, 0x1, 0x1c77440, ...)
        /go/src/github.com/argoproj/argo-cd/server/server.go:204 +0x4a5
github.com/argoproj/argo-cd/cmd/argocd-server/commands.NewCommand.func1(0xc42024b440, 0xc420698570, 0x0, 0x3)
        /go/src/github.com/argoproj/argo-cd/cmd/argocd-server/commands/root.go:78 +0x428
github.com/spf13/cobra.(*Command).execute(0xc42024b440, 0xc42003a110, 0x3, 0x3, 0xc42024b440, 0xc42003a110)
        /go/src/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/spf13/cobra.(*Command).ExecuteC(0xc42024b440, 0xc420548140, 0xc420548160, 0xc420548180)
        /go/src/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/spf13/cobra.(*Command).Execute(0xc42024b440, 0xc4207ebf78, 0xc4200b2058)
        /go/src/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
        /go/src/github.com/argoproj/argo-cd/cmd/argocd-server/main.go:14 +0x27

**Comment by alexmt** [comment]
Peter, did you run `make image` to build new image? Just tried to deploy
master and controller started successfully. My only guess is that your
controller was built with different version of casbin or modified
`builtin-policy.csv`/`model.conf`


Thanks,
Alex

**Comment by peterbosalliandercom** [comment]
@alexmt Weird thing is that I build the docker image on a windows 10 machine within ubuntu. This resulted in a non functioning version. A fellow worker did it on a full linux laptop with the same commands and it worked flawlessly. I don't understand why
