### ISSUE TITLE
ArgoCD API "PatchResource patch single application resource" endpoint Error

### ISSUE THREAD

**Issue by danielloynaz** [argoproj/argo-cd#9410]
### Discussed in https://github.com/argoproj/argo-cd/discussions/9390

<div type='discussions-op-text'>

<sup>Originally posted by **danielloynaz** May 12, 2022</sup>
Hi,

I'm trying to patch an application resource following the swagger documentation for the API. (https://cd.apps.argoproj.io/swagger-ui#operation/ApplicationService_PatchResource). But I'm getting error response. I have try different ways without luck.

**Request Info**
URL: https://xx.xxxxxx.xxx/api/v1/applications/<app-name>/resource

Query Params:
namespace:       my-namespace
resourceName: config-map
kind:                  ConfigMap
patchType:        application/json-patch+json

Body: (JSON)
```
{
"data": {
        ".env": ""
    }
}
```
I have tried many different formats, including, passing the parameters in the request body.
```
{
    "Namespace": "my-namespace",
    "ResourceName": "config-map",
    "Kind": "ConfigMap",
    "PatchType":"application/json-patch+json",
    "Patch": "{\"data\": {\".env\": \"\"}}"
}
```

Always getting this error response:

```
{
    "error": "json: cannot unmarshal object into Go value of type string",
    "code": 3,
    "message": "json: cannot unmarshal object into Go value of type string"
}
```
Is there a place where I can find more detailed information about the request format?
Can you provide a full example of how to use this endpoint?

Best regards,</div>

**Comment by almoge** [comment]
It would be great if a full example can be shared

**Comment by jgwest** [comment]
Appears to have been answered in the linked discussion.
