### ISSUE TITLE
Enable handling Applications which do have the same Applicationname

### ISSUE THREAD

**Issue by wofr** [argoproj/argo-cd#9442]
# Summary

So far applicatons-name have to be unique, to gain more flexibility while hosting differnt projects on ArgoCD and to avoid destroying existing deployments (resources) while adding new one it would make sense to include project-name as well as the cluster-destination name together with the application-name for deciding if this is a new or existing ressource.

# Motivation

I run into a problem where an appliation name which was used twice, in differnt projects for different destination cluster,  screwed up my existing deployment, described here https://github.com/argoproj/argo-cd/issues/9420 

# Please give examples of your use case, e.g. when would you use this.

E.g I do have a Repo where I have a deployment description. Each branch of the repository represent the deployment for the differnt customer. The only differnt between this deplyoments is the destination-cluster and the project name.  So far I 've to rename all application names on all branches when using the same ArogCD instance for deployment otherwise I destroy existing deployments.

# Proposal

Include Project-name and destination-cluster into the physical grouping.

**Comment by wofr** [comment]
https://github.com/argoproj/argo-cd/issues/9420 is covered when using the namespace at the right level

**Comment by wofr** [comment]
Reopen as adding the namespace to the application definiton doesn't help

**Comment by KrustyHack** [comment]
Facing the same issue here.

Our context : 

I'm using one ArgoCD instance to manage my production and my staging. I have an app which is on both environment, imagine name is "myapp". I've created 2 ArgoCD projects, on for staging and one for production. On staging ArgoCD project I've created my app "myapp" which is deployed on K8S cluster "staging". Now I'm trying to create a second app "myapp" on production ArgoCD project and which should be deployed on K8S cluster "production". And I can't choose another app name as the app name is used for the Helm chart name too by ArgoCD when deploying it.

The idea : 

Allow using same name for ArgoCD apps if namespace/destination are differents.

**Comment by wofr** [comment]
Good idea in my opinion. As you said the application-name need to be unique. 
Is there a way to avoid that `kubectl apply -f application.yaml` overwrittes an existing application? I guess not I assume using the argocd cli would do check.   Its somehow related to that issue and could really cause some pain when it happens.

**Comment by hmehta** [comment]
Good point @KrustyHack / @wofr . But as long as we are confined to a single namespace (the one used by ArgoCD) and using naming from `metadata.name`, this is not really achievable from k8s side either - one just cannot have objects with identical name.

One way to workaround this would be to have multiple namespaces in the cluster ArgoCD is ran, e.g. argocd-production-apps and argocd-staging-apps. Alternatively ArgoCD could support Applications in the namespace they are installed to. Both options seem quite hacky to me :thinking: 

Only thing that I can think of that is not totally horrible would be to use some sort of automated UID suffix for each Application created in the namespace, similarly to how k8s Pods are done. The bad thing is that this makes updating Applications quite cumbersome.

**Comment by wofr** [comment]
Very good summary! Its more or less a "k8 issue" you could not really solve with argocd.  
I some how do like the idea of having multiple namespaces on the argo-cluster for this purpose. Its better than adding prefixes to the application-names.

**Comment by wofr** [comment]
Via using the argocd-cli this could work. 
I currently use almost exculsivly kubectl when working with argocd, only for registering the cluster I use the argocd-cli, but as @hmehta mentioned  here we run into the "limitation" of k8.

**Comment by blakepettersson** [comment]
These use cases should be covered by the [ApplicationSet](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/#the-applicationset-resource).

**Comment by blakepettersson** [comment]
Closing for now; see above.

**Comment by tulsluper** [comment]
ApplicationSet does not cover these cases. I think everybody agrees that a unique App name is good, but if we want to have resources with the same names in different namespaces or different clusters - it seems Argo doesn't allow us to do it.

**Comment by blakepettersson** [comment]
> but if we want to have resources with the same names in different namespaces or different clusters 

You absolutely can, if they are truly in different namespaces/clusters and not cluster-scoped (if on the same cluster). Argo doesn't allow for multiple Argo CD `Application`s to have the same name but the _resources_ within two different apps can have the same name assuming they're in different namespaces.

**Comment by tulsluper** [comment]
Yep, I had to read documentation, releaseName solved my issue - https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-release-name

**Comment by AaveshK** [comment]
@tulsluper How did you solve it? I specified the intended name in `sources[i].helm.releaseName` field but it still takes the application name as the release name.
