### ISSUE TITLE
Monorepo deployment considerations with declarative GitOps using ArgoCD

### ISSUE THREAD

**Issue by kush-work** [argoproj/argo-cd#9472]
# Summary

With more than 1000s of application being deployed from a declarative monorepo, ArgoCD should be able to detect which project has been changed with the following commit rather than trying to send all the projects into an unknown state.

# Motivation

We are using the manifest-generate-path annotation as well as have setup for repo-server auto scaling, even then all our 100 projects go into an unknown state for a minute whenever a new commit is pushed to deploy a new application.

We have setup repo-server autoscaling as well & during each sync repo-server spins upto 20 pods. All of our applications get put into unknown state which is later reconciled. This is a potential blocker in case of integration with Argo-notification-controller, as with change from unknown state->healthy, a lot of `New Deployed` notifications would be sent by the controller.

# Proposal

A include/exclude path parameter which could watch the corresponding sub-directories for the change & then update the respective application. We have also explored ApplicationSet controller but the Exclude part takes precedence in the CRD which makes it difficult for us to manually write each directory exclusions while onboarding new applications.

**Comment by jannfis** [comment]
Hi. Do you use webhooks to notify Argo CD about the changes in the repository, or do you let Argo CD check for changes by interval?

Also, for status comparison and update, the application controller is the responsible component. Have you considered raising its status processors, as described at https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller?

**Comment by kush-work** [comment]
Hi @jannfis, Thanks for the reply.

> Do you use webhooks to notify Argo CD about the changes in the repository, or do you let Argo CD check for changes by interval?

We let argocd check for the changes by interval.

> Have you considered raising its status processors, as described at https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller?

We have around 100 application, given the scaling consideration in the doc (50 processors for 1000 Applications) we haven't scaled it up from the default number.



Do you think having a webhook corresponding for each application will solve this issue, but then it would add a troublesome boilerplate as we would need to send event for each new application being onboarded? All of our issue would be solved if the unknown state sync issue is bypassed, this is a blocker for us in integration with argo-notification as well argo-events since we would get a lot of ghost notification when a unknown state gets into healthy state again.

**Comment by jannfis** [comment]
> > Do you use webhooks to notify Argo CD about the changes in the repository, or do you let Argo CD check for changes by interval?
> 
> We let argocd check for the changes by interval.

There's a substantial difference between the logic Argo CD is using to determine which applications to update, depending on whether you use webhooks or interval checking. With webhooks, the sender will notify Argo CD about details of the change, such as the files that have been changed. This is where the `manifest-generate-paths` annotation can come to help. 

If you let Argo CD check changes to the repository, Argo CD will only compare if the target revision of the application (e.g. `HEAD`)  has moved to another commit. If it has, it will re-render the manifests for given applications and check if there are differences. Argo CD does not know which paths have changed in this scenario. 
 
> > Have you considered raising its status processors, as described at https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller?
> 
> We have around 100 application, given the scaling consideration in the doc (50 processors for 1000 Applications) we haven't scaled it up from the default number.

Ah. Sorry, then I misread from your original description, which stated:

> With more than 1000s of application being deployed from a declarative monorepo

However, I would recommend to increase the status processors to 40 or 50 anyway.

> Do you think having a webhook corresponding for each application will solve this issue, but then it would add a troublesome boilerplate as we would need to send event for each new application being onboarded? All of our issue would be solved if the unknown state sync issue is bypassed, this is a blocker for us in integration with argo-notification as well argo-events since we would get a lot of ghost notification when a unknown state gets into healthy state again.

You don't need to setup a webhook per application. The webhook is per repo, and if you use a mono repo, then configuring a single webhook should be sufficient.  And this should also work fine in combination with `manifest-generate-paths` on your `Application` resources. Additionally, you may want to increase the interval time from the 3 minutes to something more sensible (e.g. 2h or even 24h) to decrease the amount of Git requests to your repository.

**Comment by kush-work** [comment]
> There's a substantial difference between the logic Argo CD is using to determine which applications to update, depending on whether you use webhooks or interval checking. With webhooks, the sender will notify Argo CD about details of the change, such as the files that have been changed. This is where the manifest-generate-paths annotation can come to help.

Thanks for the detailed explanation @jannfis, this clears my doubt that why the manifest-generate-paths annotation were not working. We will try the webhook approach and see how it goes in our case.

**Comment by jackevans43** [comment]
I've been trying to use `manifest-generate-paths` but unfortunately it doesn't support bitbucket. Could polling support be added by doing a `git diff --name-only` to determine which files have changed between the previously synced commit and the incoming one? Then webhook configuration and disabling of pulling would need to be configured.

**Comment by agaudreault** [comment]
There have been significat improvment to scaling monorepos in ArgoCD 2.11, notably https://github.com/argoproj/argo-cd/pull/15636 and https://argo-cd.readthedocs.io/en/stable/operator-manual/reconcile/, https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#monorepo-scaling-considerations.

@jackevans43 Support for `manifest-generate-paths` on Bitbucket and Azure is not implemented. Do you mind opening a new enhancement proposal to implement those.
