### ISSUE TITLE
The "annotation" tracking method does not delete application resources

### ISSUE THREAD

**Issue by EugeneLugovtsov** [argoproj/argo-cd#9522]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD does not delete application resources when using the annotation tracking method.

**To Reproduce**

1. Add param `application.resourceTrackingMethod: annotation` to argocd-cm configmap;
2. Sync application with new tracking method enabled;
3. Delete Application via clicking on the delete button
![зображення](https://user-images.githubusercontent.com/34510252/170533962-15fc5ee1-951f-4c11-baca-e5dfb280f295.png)

**Expected behavior**

ArgoCD removes the application and all resources marked with `argocd.argoproj.io/tracking-id` annotation by this app.

**Version**

```shell
argocd: v2.2.3+987f665
  BuildDate: 2022-01-18T17:58:47Z
  GitCommit: 987f6659b88e656a8f6f8feef87f4dd467d53c44
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.3.4+ac8b7df
  BuildDate: 2022-05-18T11:41:37Z
  GitCommit: ac8b7df9467ffcc0920b826c62c4b603a7bfed24
  GitTreeState: clean
  GoVersion: go1.17.10
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Comment by mmerickel** [comment]
Semi-related, when using the "annotation" tracking method, if a resource is removed from the config then argo-cd currently stops tracking it instead of showing the resource as out of sync. This behavior is different than when using the "label" tracking method.

I put it as semi-related because both behaviors seem to make argo-cd just forget about these resources. Happy to make a separate bug report for this if ya'll disagree.

**Comment by mmerickel** [comment]
Actually looks like https://github.com/argoproj/argo-cd/issues/6061 explains my issue.

**Comment by rhyswilliamsza** [comment]
I'm experiencing the same issue :)

**Comment by todaywasawesome** [comment]
Closing in favor of #6061, lets keep focus on a single issue.
