### ISSUE TITLE
ApplicationSet - matrix generator for SCM provider + git (dir) generator  OR expose path in SCM provider

### ISSUE THREAD

**Issue by jdomag** [argoproj/argo-cd#9526]
# Scenario
I have multiple repositories, each repository contains multiple components with their corresponding helm chart. I would like to automatically discover the repositories (SCM provider) and find all the "Helm" folders inside those repositories to create Application object for each "Helm" folder.
My first thought was to use matrix generator to first discover all the repos (SCM provider) and then find all the "Helm" folder (Git generator) - but I guess it's not possible to pass repos found by SCM provider to Git generator. 

# Proposal

1) SCM provider support "directories" parameter same as Git generator to find multiple folders and exposes "path" template parameters same as git dir generator
2)  matrix generator allows to pass template from one child generator to another one
3) other?

**Comment by rishabh625** [comment]
may be after merge of [this](https://github.com/argoproj/argo-cd/pull/9080) this can be possible

**Comment by jdomag** [comment]
looks like it solves the problem
