### ISSUE TITLE
Error listing all apps via argocd client

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#953]
Since building a docker image from the latest master we cannot list the apps anymore:
 argocd app list
FATA[0000] rpc error: code = Internal desc = grpc: error unmarshalling request: proto: wrong wireType = 0 for field Refresh

**Comment by peterbosalliandercom** [comment]
this is since commit : d42fabaa7aa424dc56e930618ad0403107ca2ee5

**Comment by jessesuen** [comment]
@peterbosalliandercom we made a breaking change between rc1 and tip of master by reusing protobuf ids. Since it was pre-release, we thought  it was okay to do. If you rebuild everything from tip (including client), it should work.

**Comment by jessesuen** [comment]
I pointed this out here: https://github.com/argoproj/argo-cd/pull/931#discussion_r242372114

**Comment by peterbosalliandercom** [comment]
Thanks for the response, how do I build the linux binary from the code?

**Comment by jessesuen** [comment]
Try ‘make cli-linux’ it should end up in the dist directory

**Comment by peterbosalliandercom** [comment]
thanks

**Comment by peterbosalliandercom** [comment]
it actually was 'make cli'

**Comment by jessesuen** [comment]
@peterbosalliandercom please rebuild CLI yet again. This was another breaking gRPC change we will be making in v0.11. 

It was caused by this:
https://github.com/argoproj/argo-cd/pull/951/files#diff-45d9a586e897271e2313fb64832ff000R394

Sorry for the instability. We are using v0.11 as our chance to get the API correct

**Comment by peterbosalliandercom** [comment]
Maybe waiting for new release?

**Comment by jessesuen** [comment]
Actually you may need to rebuild the server image if your CLI is newer. They just need to be at the same changeset.

**Comment by peterbosalliandercom** [comment]
I did both... still not working

[pbos@L-AW26PO:~/go/src/github.com/argoproj/argo-cd/dist] $ ./argocd version
argocd: v0.11.0+881d052.dirty
  BuildDate: 2018-12-21T13:16:28Z
  GitCommit: 881d052f0d8208ae71a81e326c00f031a3978d6b
  GitTreeState: dirty
  GoVersion: go1.10.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v0.11.0+6389fc5
  BuildDate: 2018-12-20T15:10:06Z
  GitCommit: 6389fc5c6d3e706e327c597c92116600858f9927
  GitTreeState: clean
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.0

**Comment by alexmt** [comment]
👍
