### ISSUE TITLE
Sync errors with Kubernetes 1.13.1

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#954]
Argo CD fails to sync applications to Kubernetes 1.13.1:

* resource name may not be empty. Looks like error is happening with RBAC resources:

```
time="2018-12-20T19:27:11Z" level=info msg="added resource ClusterRole/grafana-datasource-controller status: SyncFailed, message: resource name may not be empty" application=grafana-datasource-controller
time="2018-12-20T19:27:11Z" level=info msg="added resource ClusterRoleBinding/grafana-datasource-controller status: SyncFailed, message: resource name may not be empty" application=grafana-datasource-controller
```

* `kubectl apply` fails for random resources without error message

**Comment by mgoodness** [comment]
> Looks like error is happening with RBAC resources

AFAICT it's only ClusterRoles and ClusterRoleBindings. Roles and RoleBindings are created without problem.

**Comment by jessesuen** [comment]
Also, v0.10.X and v0.11.0-rc1 are both using kubectl v1.11.3. We may want to consider trying kubectl v1.12 or v1.13 to see if the issue is due to a version incompatibility.

**Comment by mgoodness** [comment]
I've been injecting kubectl v1.13.1 into the repo-server as a custom tool.

**Comment by jessesuen** [comment]
> I've been injecting kubectl v1.13.1 into the repo-server as a custom tool.

Actually kubectl is used in application-controller, which is the service which performs the deploys. I think it is worth a shot injecting it there, to see if will help.

**Comment by jessesuen** [comment]
> time="2018-12-20T19:27:11Z" level=info msg="added resource ClusterRole/grafana-datasource-controller status: SyncFailed, message: resource name may not be empty" application=grafana-datasource-controller

This is due to namespace being empty when we are applying a resource. We are running a command like:
```
INFO[0034] [kubectl --kubeconfig /var/folders/_m/991sn1ds7g39lnbhp6wvqp9d_j5476/T/215795749 -n  auth reconcile -f - --dry-run] 
```
Notice that nothing comes after the namespace arg: `-n`. We need to conditionally add `-n` depending if namespace was provided.

**Comment by jessesuen** [comment]
The "resource name may not be empty" issue will be addressed as part of PR:
https://github.com/argoproj/argo-cd/pull/944/commits/72534cc02ac88edf56fdeb999c58cb45dcf5cc0d

**Comment by jessesuen** [comment]
FYI Argo CD v0.11.0 will ship with v1.13.1 kubectl. v0.11.0-rc4 has been updated with the new kubectl version.

**Comment by jessesuen** [comment]
We believe all known issues with v1.13 should be addressed.
