### ISSUE TITLE
groups logging too verbose

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-cd#9549]
i get logs like this every 15 seconds but the list of groups is 6000 characters long so the log storage becomes expensive
```
time="2022-06-01T05:52:39Z" level=info msg="received unary call /application.ApplicationService/List" grpc.method=List grpc.request.claims="{\"at_           hash\":\"redact\",\"aud\":\"argo-cd\",\"c_hash\":\"redact\",\"email\":\"redact\",\"email_ver           ified\":true,\"exp\":1654144159,\"groups\":[\"AC......really long list here....
```

https://github.com/argoproj/argo-cd/blob/b37eee1054e42c873699460dd5e2447c2f9fe5a6/util/grpc/logging.go#L20

**Comment by crenshaw-dev** [comment]
@tooptoop4 would you be up for a PR wrapping that with a debug log level check?

**Comment by tooptoop4** [comment]
@crenshaw-dev https://github.com/argoproj/argo-cd/pull/9862

**Comment by crenshaw-dev** [comment]
@tooptoop4 lmk if you need this cherry-picked. https://github.com/argoproj/argo-cd/pull/9947

Otherwise I'll just leave it for 2.5.

**Comment by tooptoop4** [comment]
yes pls @crenshaw-dev
