### ISSUE TITLE
Unable to add a private bitbucket repository from the UI/CLI

### ISSUE THREAD

**Issue by iamShantanu101** [argoproj/argo-cd#955]
Hi,

I am trying to add a private bitbucket repository but is getting exited with `connnection refused` error. I've tried from the UI as well as from the CLI but they're giving same error.

Here's the log of argocd server pod I am seeing

```
time="2018-12-24T13:26:57Z" level=error msg="finished unary call with code Unknown" error="Get https://bitbucket.org/myusername/test-repo.git/info/refs?service=git-upload-pack: dial tcp 185.82.212.199:443: connect: connection refused" grpc.code=Unknown grpc.method=Create grpc.service=repository.RepositoryService grpc.start_time="2018-12-24T13:26:57Z" grpc.time_ms=250.744 span.kind=server system=grpc
W1224 13:27:34.977895       1 reflector.go:270] github.com/argoproj/argo-cd/util/rbac/rbac.go:184: watch of *v1.ConfigMap ended with: too old resource version: 43787825 (43788157)
```

Any idea why this might be happening? Or is this not yet supported with BitBucket?

The CLI command I am running is:
```
argocd repo add https://bitbucket.org/myusername/test-repo.git --username myusername --password mypassword
```

**Comment by alexmt** [comment]
It looks like bitbucket.org might be unreachable from pod. Can you try to ssh into argocd-repo-server pod and try to `https://bitbucket.org` ? 

I've tried adding private bitbucket repo and could not reproduce the issue.

**Comment by jessesuen** [comment]
> error="Get https://bitbucket.org/myusername/test-repo.git/info/refs?service=git-upload-pack: dial tcp 185.82.212.199:443: connect: connection refused

I agree. "connection refused" implies this is an environmental problem and not an Argo CD issue

The message: `watch of *v1.ConfigMap ended with: too old resource version: 43787825 (43788157)` is benign and can be ignored.

**Comment by iamShantanu101** [comment]
Yes, it was an environment issue. Now, it is working. Thanks.

**Comment by jyyoo0530** [comment]
> Yes, it was an environment issue. Now, it is working. Thanks.

Hello, I have same issue here. Can you explain what environment issue  was and how you solved.

**Comment by sndevops** [comment]
Verify your dns running on kuberneteas, in my case I using microk8s following command fixed it.
microk8s enable dashboard dns ingress
