### ISSUE TITLE
Controller doesn't skip refreshes for disallowed resources or for ignored fields

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#9558]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Suppose I have a frequently-updated resource in a namespace that is monitored by one or more Apps (whether explicitly or via an orphanedResources policy).

The App is refreshed even in these cases:
1. When the resource is monitored as part of an orphanedResource policy, but is disallowed by the App's Project.
2. When the changed fields are ignored at the App level.
3. When the changed fields are ignored at the argocd-cm level.

This fills up logs.

**To Reproduce**

1. Create a resource (say, a ConfigMap) called test-cm in a new namespace called test-namespace.
2. Create an App called test-app pointing to that namespace. Make sure `orphanedResources: {}` is set in the App.
4. Update the ConfigMap and note the line in the app controller logs: `Refreshing app XYZ for change in cluster of object test-namespace/test-cm of type v1/ConfigMap`
5. Add ConfigMaps to the `ignoreDifferences` in argocd-cm. Update the ConfigMap and notice that the refresh is still logged.
6. Add ConfigMaps to the `ignoreDifferences` in the Application. Update the ConfigMap and notice that the refresh is still logged.
7. Edit the test-app's Project to allow only non-ConfigMap resources (say, by adding Deployment as the only allowed namespaced resource). Update the ConfigMap and notice that the refresh is still logged.
8. Remove the `orphanedResource: {}` line from the App. Update the ConfigMap and notice that the refresh is **no longer logged**.

I believe this line is the problem:

https://github.com/argoproj/argo-cd/blob/61f48d56b1962d188ee8ff9c30f84583e087afd7/controller/appcontroller.go#L295

The comment indicates disallowed/ignored resources shouldn't trigger a refresh. But as far as I can tell, no such check is being performed.

**Expected behavior**

I expected the controller to not refresh the app for an ignored or disallowed resource.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
There's reason to believe this doesn't only happen to orphaned resources. Any resource in the tree will be refreshed regardless of ignoreDifferences: https://cloud-native.slack.com/archives/C01TSERG0KZ/p1654110592010629

**Comment by theluckiesthuman** [comment]
@crenshaw-dev I can work on this issue.

**Comment by sidewinder12s** [comment]
@theluckiesthuman Did you get a chance to raise anything?

**Comment by pepe9012** [comment]
When a new `ignoreResourceUpdates`  feature come to argocd v2.8, I've found that it's also affected. When orphanedResources are monitored, `ignoreResourceUpdates` is absolutely ignored. 

**CPU Usage** with and without orphanedResources in AppProject:
![controller_cpu](https://github.com/argoproj/argo-cd/assets/127219779/364d9ae0-632f-4b3c-a253-fa2e4fbfbd04)

**Reconcilitation** with and without orphanedResources in AppProject:
![reconcilitation](https://github.com/argoproj/argo-cd/assets/127219779/f2214af8-f175-4ad1-8a95-babf149f8ad2)

@agaudreault-jive maybe interested in fixing this one? :pray:  i saw more related issues with cpu usage when orphaned resources are monitored, but all of them are closed, but `ignoreResourceUpdates` is not a working solution.

**Comment by khorn7sk** [comment]
This is issue also impact us. We are using VPA, and VPA controller often refresh their CR, this is triggered ArgoCD for refreshing. A lot of refreshes make DDos attack on our git instance.

**Comment by duizabojul** [comment]
Any update on this? This is a fairly serious issue imho.

**Comment by icecoffee531** [comment]
We also have the same problem. We are using HPA without GitOps. Since HPA is an untracked resource, even if we configure the `ingnoreUpdateResources`, `argocd-application-controller` cannot ignore the changes to these HPAs.

**Comment by jdomag** [comment]
@crenshaw-dev can you shed some light on how objects that doesn't belong to an App cause the App refresh?
Example:
* I use aws-load-balancer-controller - the controller creates a configmap that doesn't belong to the App object. 
* Every time the configmap changes, it causes App to be refreshed - how does argocd know to refresh it when it doesn't track it? The configmap doesn't have any labels or annotations point to argocd - see below:
```
  5 apiVersion: v1
  6 kind: ConfigMap
  7 metadata:
  8   annotations:
  9     control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"aws-load-balancer-controller-848cf7dfdc-88dpg_
 10   creationTimestamp: "2021-09-29T09:13:01Z"
 11   name: aws-load-balancer-controller-leader
 12   namespace: kube-system
 13   resourceVersion: "1408042931"
 14   uid: 6677c3a5-9022-44a7-8cb9-xyz
```
* what's more I see in the debug logs that changes in above configmap causes the refresh of kube2aim Application - which has nothing to do with aws-load-balancer-controller 
```
application-controller {"api-version":"v1","application":"argocd/kube2iam","cluster-name":"","fields.level":1,"kind":"ConfigMap","level":"debug","msg":"Requesting app refresh caused by object update","name":"aws-load-balancer-controller-leader","namespace":"kube-system","server":"https://kubernetes.default.svc","time":"2024-05-06T09:53:02Z"}
```
