### ISSUE TITLE
AppDetails doesn't get Helm params for specified values files

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#9565]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

* Create an app pointed at https://github.com/crenshaw-dev/values-app.git, adding `values-2.yaml` to the Helm parameters at the bottom of the page
* Look at the Parameters tab of the app in the UI
* Note that `some: yaml` is not listed in the parameters (that's the contents of values-2.yaml)

**Expected behavior**

I expected the UI to load the contents of values-2.yaml as Parameters.

**Screenshots**

This is the expected interface:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/350466/171543041-6ca3451e-8fd1-4b98-8c6c-f2ea843388d6.png">

**Version**

v2.3.4

**Comment by LiberoScarcelli** [comment]
**Still broken in 2.3.4**

![stillbroken](https://user-images.githubusercontent.com/101608253/174763618-3f115753-194e-45af-a5c8-61ab026026db.jpg)

![stillbroken2](https://user-images.githubusercontent.com/101608253/174763684-21761caa-1212-486b-a743-d289ede053a0.jpg)
