### ISSUE TITLE
Applications going out-of-sync when 'Release.Time' is used in checksum/config

### ISSUE THREAD

**Issue by alok183** [argoproj/argo-cd#9582]
Configuration:
1. Deployment manifest has  annotation "checksum/config: {{ .Release.Time | quote | sha256sum }}"

Issue:
Applications are out-of-sync with showing diff in "checksum/config" even when no commits and manual updates done.
![image](https://user-images.githubusercontent.com/24774682/172037485-d0ec156e-b1db-4cbc-8f32-eef63b8fbcaa.png)

Not sure what I am doing wrong. Any insight appreciated, thanks.

**Comment by BlueCog** [comment]
Filling that annotation is probably a Helm 'trick' to force redeployment of components on each Helm Upgrade (via a checksum of  .Release.Time). 

What i'm thinking happens here (correct me if i'm wrong) is dat ArgoCD is constantly checking the state from Git and is processing  {{ .Release.Time | quote | sha256sum }} each time. What results in a new checksum and a out-of-sync application.

I'm not sure why this Helm Deployment is forcing a redeploy on each Helm Upgrade. I'm thinking a better solution will be to create the checksum only for components (secrets/configmaps/..) and redeploy only when needed...
