### ISSUE TITLE
Client retries between internal services

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#959]
If the application-controller has an in-flight API call to the repo-server, who's connection is then disconnected by a pod being killed (e.g. due to a node upgrade), the reconciliation will fail and the application may enter an Unknown comparison state.

We should have some retry mechanism between our internal services, so that we can tolerate minor network disruptions.

**Comment by jessesuen** [comment]
Here is the repo-server clientset:
https://github.com/argoproj/argo-cd/blob/master/controller/clientset.go

This could be improved to install an client-side gRPC interceptor which handles a class of gRPC network errors (timeout, disconnects) and automatically retries with some configurable backoff

**Comment by jessesuen** [comment]
Client-side gRPC interceptor example:
https://github.com/grpc/grpc-go/blob/master/examples/features/interceptor/README.md

**Comment by alexmt** [comment]
I'm still seeing intermittent failures during every upgrade.

**Comment by alexec** [comment]
Back-ported to v1.3
