### ISSUE TITLE
how to close polls Git repositories every three minutes？

### ISSUE THREAD

**Issue by kzcPo** [argoproj/argo-cd#9620]
**Describe the bug**

https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/
Argo CD polls Git repositories every three minutes to detect changes to the manifests.
How to close polls Git repositories every three minutes？

I try to use [Create The WebHook In The Git Provider](https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/#1-create-the-webhook-in-the-git-provider) but there are still rotation tests.

Application unknown occasionally appears on my side.

**Screenshots**

![image](https://user-images.githubusercontent.com/16077203/172755045-014bd291-f3f6-4b30-9887-5c6900f56e76.png)

**Version**

```shell
argocd: v2.3.3+07ac038
  BuildDate: 2022-03-30T00:06:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2022-06-09T02:57:22Z" level=info msg="Start processing" resource=argocd/j63-online
time="2022-06-09T02:57:22Z" level=info msg="Trigger on-sync-status-unknown result: [{[0].6SzWb05EK-0v90hwjyytTbN7S6A  [app-sync-status-unknown] true}]" resource=argocd/j63-online
...
time="2022-06-09T02:57:23Z" level=info msg="Processing completed" resource=argocd/j63-online
time="2022-06-09T02:57:23Z" level=info msg="Start processing" resource=argocd/j63-online
time="2022-06-09T02:57:23Z" level=info msg="Trigger on-sync-failed result: [{[0].H9WjsqG1dKYm6njOZ7yUQYOA1Wk  [app-sync-failed] false}]" resource=argocd/j63-online
time="2022-06-09T02:57:23Z" level=info msg="Trigger on-sync-running result: [{[0].xGlbhcF_taGYrI3UsrQsINn2hl0  [app-sync-running] false}]" resource=argocd/j63-online
time="2022-06-09T02:57:23Z" level=info msg="Trigger on-sync-status-unknown result: [{[0].6SzWb05EK-0v90hwjyytTbN7S6A  [app-sync-status-unknown] true}]" resource=argocd/j63-online
time="2022-06-09T02:58:11Z" level=info msg="Start processing" resource=argocd/j63-online
time="2022-06-09T02:58:11Z" level=info msg="Trigger on-sync-status-unknown result: [{[0].6SzWb05EK-0v90hwjyytTbN7S6A  [app-sync-status-unknown] true}]" resource=argocd/j63-online
...

```

**Comment by ohauer** [comment]
From https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/
try with a higher reconciliation time in the argocd-cm ConfigMap e.g.
timeout.reconciliation: "3600s"

**Comment by kzcPo** [comment]
你好，我已经收到邮件！

**Comment by kzcPo** [comment]
> From https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/ try with a higher reconciliation time in the argocd-cm ConfigMap e.g. timeout.reconciliation: "3600s"

I try to configure `timeout Reconciliation`, but it has no effect!

![image](https://user-images.githubusercontent.com/16077203/173474691-e7e1d2da-16af-440b-b64b-74894a36c5c0.png)

Unknown is still detected！

**Comment by ohauer** [comment]
Have you also restarted your argocd-repo-server pods after adjusting the values?

check applied values 
```sh
kubectl -n <argocd-namespace> get configmap argocd-cm -o jsonpath='{.data.timeout\.reconciliation}'
```

restart argocd-repo-server
```sh
kubectl -n <argocd-namespace> rollout restart deploy argocd-repo-server
```
