### ISSUE TITLE
Project filter is not applied to refreshing applications from other projects 

### ISSUE THREAD

**Issue by romachalm** [argoproj/argo-cd#9651]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When I apply a  `projects` filter on applications, the applications are correctly filtered. But each time an application from another project gets its status updated (`progressing` for instance), it appears in the list of the filtered applications, 

When I refresh the page, the list is reverted with the correct filter until the changing applications start appearing in the list. 

I haven't seen this behaviour with cluster filter nor namespace filter. 

**To Reproduce**

You need to have several applications from several projects

- Apply a project filter
- Wait until an app from another project has its status changed and watch it dynamically appearing in the list of filtered applications

**Expected behavior**

Once the project filter is applied, no application from another project should be listed
**Screenshots**

**Version**

v2.4.0+91aefab

**Logs**

**Comment by saumeya** [comment]
The project filter is implemented on the server side unlike the other filters - https://github.com/argoproj/argo-cd/pull/8102

**Comment by djfinnoy** [comment]
I think this applies to apps that are refreshing as well. I'm seeing apps from other projects come and go, even though the UI is indicating that they are synced and healthy.

**Comment by romachalm** [comment]
I confirm : refreshing apps from other projects appears in the filtered list, whatever the actual status of the application is.

**Comment by rphua** [comment]
I can confirm this is also the case for our team this happened after v.2.4.0

> Problem first appeared after upgrading to v2.4.0
