### ISSUE TITLE
Namespaced install fails to sync CRDs

### ISSUE THREAD

**Issue by cabrinha** [argoproj/argo-cd#9654]
When using ArgoCD in a namespaced install, CRDs fail to sync. We've given ArgoCD Application Controller full access using the "Role" and "RoleBindings", but it seems we need to use the ClusterRole and ClusterRoleBindings, however we have another cluster-side install inside the same cluster and don't want these resources to conflict.

```
failed to sync cluster [https://192.168.0.1:443](https://192.168.0.1/): failed to load initial state of resource ConstraintTemplatePodStatus.status.gatekeeper.sh: constrainttemplatepodstatuses.status.gatekeeper.sh is forbidden: User "system:serviceaccount:sig-argocd:argocd-application-controller" cannot list resource "constrainttemplatepodstatuses" in API group "status.gatekeeper.sh" at the cluster scope
```

**Comment by oscrx** [comment]
CRD's are not namespaced in Kubernetes, you cannot install the same CRD twice.
You can find out what api's are namespaced in your cluster with this command: `kubectl api-resources --namespaced`
