### ISSUE TITLE
Add short SHA in PR generator

### ISSUE THREAD

**Issue by Redlinkk** [argoproj/argo-cd#9668]
# Summary

In the PR generator, I only have access to the long SHA in the output. The short SHA is also often used during CI/CD, it would be great to have an easy access to this value.

# Motivation

I'm using the short SHA as a tag for docker images. I could find ways to cut the long SHA in the rest of my CD workflow, but it would be much easier to get it directly from the generator.

# Proposal

I suggest to add another output to the PR generator named `head_short_sha`. This output can be directly obtained from the pull request head SHA by taking the first 7 characters.

**Comment by nar3k** [comment]
@Redlinkk  Hi! I think its a great feature , can you please also add short sha to scp generator?

**Comment by Redlinkk** [comment]
@nar3k Yes I'll do that
