### ISSUE TITLE
how to deal with params ?

### ISSUE THREAD

**Issue by k8sedu** [argoproj/argo-cd#967]
should i override params from the frontend? 
if values.yaml or params.jsonnet file has changed, the app will be outofsync?

**Comment by alexmt** [comment]
Yes, app will be OutOfSync if you change manifest in any way.

You might choose to update parameters using Argo CD UI/CLI if your application is changing frequently and you don't want to pollute git with multiple commits (e.g. if your app is a dev environment and you continuously update it). 

Please check [tracking strategies](https://argoproj.github.io/docs/argo-cd/docs/tracking_strategies.html) and [parameters](https://argoproj.github.io/docs/argo-cd/docs/parameters.html) for more information.

**Comment by k8sedu** [comment]
em, but when i change the helm values-xxx.yaml(change replicaCount from 1 to 2), it was not OutOfSync.

**Comment by k8sedu** [comment]
ty. could u add one config that it can be skipped since that different ingress controllers make different behaviors
