### ISSUE TITLE
argocd auto-refesh doesn't use the project filter

### ISSUE THREAD

**Issue by survivant** [argoproj/argo-cd#9697]
I'm using Argocd v2.4.0+91aefab

the problem is simple.  I have 2 projects with multiple applications.  When argo do is "refresh-synchronisation"  around 3-7 minutes.  When the refresh occurs, the applications displayed are not filtered.  In the first screen, it will display all my applications (project iep-monitor + dev).  

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/191879/174129001-fb0776ce-b257-4d78-a9c9-31ce1b8ffed6.png">

After few seconds/1-2min, the screen refresh again with the filter applied correctly.  

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/191879/174129061-1fd4db35-cd4e-45de-8acf-05c28434aaba.png">

**Comment by crenshaw-dev** [comment]
@survivant thanks for the details/screenshots! I'm going to close as a duplicate of https://github.com/argoproj/argo-cd/issues/9651, but let me know if I'm incorrect about that.
