### ISSUE TITLE
ApplicationSet remains in degraded state forever

### ISSUE THREAD

**Issue by lbaschiera-tdh** [argoproj/argo-cd#9698]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Hi all,

Little bit of context:
I have an ArgoCD installation that currently manages 3 clusters: Dev, Stage and Loadtest. Applications are first installed into Dev, and then promoted to Loadtest and Stage in the same step.
For each of them, I have an ApplicationSet that deploys the Helm charts contained in my configuration repository, with the following structure (Based on this [argo-cd discussion](https://github.com/argoproj/argo-cd/discussions/5667) and [this approach](https://codefresh.io/blog/how-to-model-your-gitops-environments-and-promote-releases-between-them/)):
```
.
├── base
│   ├── chart-1
│   └── chart-2
└── dev
    ├── only-dev-chart-1
    ...
    └── only-dev-chart-n
```

Dev AppSet creates an app out of each chart in `./dev` and `./base`, while Stage and Loadtest AppSets create apps only for charts in `./base`

The issue I'm currently facing is that when I promote one chart from Dev to Stage and Loadtest (This translates into moving the helm chart from `./dev` to `./base`), the ApplicationSet for Dev is marked as 'degraded' and the Health detail is: 
> _ApplicationSet appset-dev contains applications with duplicate name: dev-chart-x_

Even though there's only one Application named dev-chart-x with the correct NEW repo path, that is `./base/chart-x`.

I have tried hard refreshing the cache for the Application in charge of deploying the ApplicationSets and deleting the dev-chart-x Application and syncing for it to be reinstalled, but the AppSet is still in degraded state and I can't find a way to fix it.

Any ideas on how to proceed?

**To Reproduce**

1. Create an ApplicationSet that tracks 2 separate folders in the same repo
2. Move one chart from one folder to the other and push the changes
3. ApplicationSet is now marked as `Unhealthy`

**Expected behavior**

ApplicationSet is refreshed and remains healthy

**Version**

```shell
argocd: v2.3.3+07ac038.dirty
  BuildDate: 2022-03-30T05:20:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: darwin/amd64
```

**Logs**

```
time="2022-06-16T19:45:30Z" level=info msg="generated 32 applications" generator="{<nil> <nil> <nil> <nil> <nil> <nil> 0xc000fb6c60 <nil>}"
time="2022-06-16T19:45:30Z" level=error msg="validation error found during application validation: ApplicationSet appset-dev contains applications with duplicate name: dev-chart-x"
time="2022-06-16T19:45:30Z" level=info msg="unchanged Application" app=dev-chart-x appSet=appset-dev
1.655408730224738e+09	DEBUG	events	Normal	{"object": {"kind":"ApplicationSet","namespace":"default","name":"appset-dev","uid":"c95587ba-8a49-4300-93d8-5c80ca27216f","apiVersion":"argoproj.io/v1alpha1","resourceVersion":"6385297"}, "reason": "unchanged", "message": "unchanged Application \"dev-chart-x\""}
```

**Comment by mannro** [comment]
i've run into same problem.
what is the solution?
