### ISSUE TITLE
Scaling issue - webhook not working on appliction with targetRevision different than HEAD

### ISSUE THREAD

**Issue by valvin1** [argoproj/argo-cd#9706]
Hello,

We are having scaling issue we are trying to solve using the [guide](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/high_availability.md). We actually have 300 applications which are unfortunately mainly Monorepo which is the main issue as mentionned in the guide.

We have already scalled up:
* repo-server, (hpa)
* server (3 replicas)
* controller by increasing processors and its not possible to shard it because we have only one cluster
* and of course implementing webhook

Unfortunately on webhook implementation it works great on HEAD targetRevision but looks like more complex on other targetRevision. 

Hook is well received ex: `Received push event repo: https://gitlab.com/readacted, revision: feat/redacted, touchedHead: false` but then nothing happened. We have to wait the refresh to have the synchronization. Is there another metadata than `argocd.argoproj.io/manifest-generate-paths:` to specify when we are not working on HEAD?

We are running ArgoCD 2.1.7

Thank you :)

**Comment by valvin1** [comment]
We have upgraded to v2.4.2 and it looks it works better. I'll confirm in few days and close this issue.

**Comment by crenshaw-dev** [comment]
@valvin1 okay to close?

**Comment by valvin1** [comment]
Yes of course.
