### ISSUE TITLE
argocd command line args "--plaintext"  

### ISSUE THREAD

**Issue by ljzx489** [argoproj/argo-cd#9736]
argocd-server version : 2.3.1

several days ago， my  argocd-server  is rebooted in unknow reason.  since then，when i run argocd command line with  arg "--plaintext" will cause a problem.

what does the argocd command line arg "--plaintext"  means .

here is the docs that records the results when i run argocd command line. 
[pngs.docx](https://github.com/argoproj/argoproj/files/8917663/pngs.docx)

**Comment by todaywasawesome** [comment]
It disables TLS.
