### ISSUE TITLE
Unclear specification for parameters

### ISSUE THREAD

**Issue by PaulVanStaden** [argoproj/argo-cd#974]
When using the docs/parameters.md file I got confused as to how to use the example. I ended up finding out that it is normal yaml. 

It only states `argocd app set -p (COMPONENT=)PARAM=VALUE` and the example states 
`argocd app set guestbook -p guestbook=image=example/guestbook:abcd123`

It would be nice having a section specifying something like `argocd app set guestbook -p guestbook=ingress.enabled=true` that will show that it expects a yaml path

**Comment by alexmt** [comment]
Closed by https://github.com/argoproj/argo-cd/commit/88dbcee873fb34738fa096cf5798d7f69b962680
