### ISSUE TITLE
SharedResourceWarning to non-existing app

### ISSUE THREAD

**Issue by VladoPortos** [argoproj/argo-cd#9749]
**Describe the bug**

I have added Longhorn helm chart to my Argo CD instance. I might have try to create the app before with name `longhorn` but did not save it as I was not sure about some setting. Later I created app with name `longhorn-storage-provider` everything deployed ok. Except I have one warning: 

`SharedResourceWarning
CustomResourceDefinition/recurringjobs.longhorn.io is part of applications longhorn-storage-provider and longhorn`

Which does not make much sense to me, there is no app called 'longhorn'

```shell
oot@control01:~/longhorn# argocd app list           
NAME                       CLUSTER                         NAMESPACE        PROJECT       STATUS  HEALTH   SYNCPOLICY  CONDITIONS             REPO                                                          PATH                 TARGET
docker-registry-tls        https://kubernetes.default.svc  docker-registry  k3s-bootsrap  Synced  Healthy  Auto        <none>                 https://gitlab.privatecloud.sk/vladoportos/k3s-bootstrap.git  docker-registry-tls  HEAD
longhorn-storage-provider  https://kubernetes.default.svc  longhorn-system  k3s-bootsrap  Synced  Healthy  <none>      SharedResourceWarning  https://charts.longhorn.io                                                         1.3.0
redis                      https://kubernetes.default.svc  redis-server     k3s-bootsrap  Synced  Healthy  Auto-Prune  <none>                 https://gitlab.privatecloud.sk/vladoportos/k3s-bootstrap.git  redis
```

**To Reproduce**

Not sure, I can't remove and recreate it again, since the longhorn is in use now.

**Expected behavior**

No warning

**Screenshots**

**Version**

```shell
root@control01:~/longhorn# argocd version
argocd: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:46:43Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/arm64
argocd-server: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:23:37Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Comment by VladoPortos** [comment]
Well solved. I have edited the CRD called `recurringjobs.longhorn.io` its live manifest. 

Removed ` app.kubernetes.io/instance: longhorn`  saved, synced all green.

**Comment by yogeek** [comment]
ok I think I found the root cause : https://argo-cd.readthedocs.io/en/stable/faq/#why-is-my-app-out-of-sync-even-after-syncing
