### ISSUE TITLE
Long application names become unreadable in the UI - List view

### ISSUE THREAD

**Issue by rodrigo14miguel** [argoproj/argo-cd#9752]
# Summary

Would be nice to have a tooltip for application name on List view.

# Motivation

Long application names become unreadable in the UI in List view

# Proposal

Issue #9241 addressed this for Tiles view.

**Comment by saumeya** [comment]
@rodrigo14miguel, which version are you on? This should be fixed in the current version.

**Comment by rodrigo14miguel** [comment]
@saumeya, version 2.4.2
I've done a clean install. The tooltip shows the name in tile view but there is no tooltip for list view.

**Comment by saumeya** [comment]
Thanks for clarifying, my bad. I didn't read the summary properly.

**Comment by rodrigo14miguel** [comment]
Thank you @saumeya !!
