### ISSUE TITLE
Argo CD 2.4.0: RBAC resources exec and logs not known to the projects REST API

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-cd#9783]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hey there! 
We started upgrading our Argo CD instances to 2.4.0. To give permissions to our developers, we create a role on each project in ArgoCD allowing the assigned groups to only do certain actions with their apps. As 2.4.0 introduces two new RBAC resources `logs` and `exec` we started adding them to our roles too. However we encounter issues when creating new Argo CD projects using the REST API. It complains that the RBAC resources `exec` and `logs` are not found.

The exact error message:

```json
{"error":"invalid policy rule 'p, proj:guestbook:guestbook, exec, create, guestbook/guestbook, allow': project resource must be: 'applications', 'repositories' or 'clusters', not 'exec'","code":3,"message":"invalid policy rule 'p, proj:guestbook:guestbook, exec, create, guestbook/guestbook, allow': project resource must be: 'applications', 'repositories' or 'clusters', not 'exec'"}
```

This must either be a bug, or a misunderstanding on our side as the resources `exec` and `logs` are not meant to be set at project-level.

**To Reproduce**

Do an API Call to Argo CD REST API using the following command:

```bash
curl -X POST -d @guestbook.json $ARGOCD_SERVER/api/v1/projects -H "Authorization: Bearer $ARGOCD_TOKEN"  -H 'Content-Type: application/json' -v 
```

where `guestbook.json` contains the following:
```json
{
  "project": {
    "metadata": {
      "name": "guestbook",
      "namespace": "argocd"
    },
    "spec": {
      "clusterResourceBlacklist": [
        {
          "group": "none",
          "kind": "none"
        }
      ],
      "description": "ArgoCD Project for guestbook",
      "destinations": [
        {
          "namespace": "guestbook",
          "server": "https://kubernetes.default.svc"
        }
      ],
      "roles": [
        {
          "groups": [
            "mygroup",
            "anothergroup"
          ],
          "name": "guestbook",
          "policies": [
            "p, proj:guestbook:guestbook, applications, action/*, guestbook/guestbook, allow",
            "p, proj:guestbook:guestbook, applications, delete, guestbook/guestbook, allow",
            "p, proj:guestbook:guestbook, applications, get, guestbook/guestbook, allow",
            "p, proj:guestbook:guestbook, applications, sync, guestbook/guestbook, allow",
            "p, proj:guestbook:guestbook, exec, create, guestbook/guestbook, allow",
            "p, proj:guestbook:guestbook, logs, get, guestbook/guestbook, allow"
          ]
        }
      ],
      "sourceRepos": [
        "https://github.com/liechtinat/guestbook.git"
      ]
    }
  },
  "upsert": true
}
```

This results in the following error message:

```json
{"error":"invalid policy rule 'p, proj:guestbook:guestbook, exec, create, guestbook/guestbook, allow': project resource must be: 'applications', 'repositories' or 'clusters', not 'exec'","code":3,"message":"invalid policy rule 'p, proj:guestbook:guestbook, exec, create, guestbook/guestbook, allow': project resource must be: 'applications', 'repositories' or 'clusters', not 'exec'"}
```

**Expected behavior**

The Project should be created without any error as `exec` and `logs` are valid RBAC resources since v2.4.0.

**Version**

```shell
v2.4.0+91aefab
```

**Logs**

```
time="2022-06-24T13:07:17Z" level=info msg="received unary call /project.ProjectService/Create" grpc.method=Create grpc.request.claims="{\"iat\":1651649987,\"iss\":\"argocd\",\"jti\":\"dce64e3a-1cd7-46a4-b12b-8a00d2fdcd49\",\"nbf\":1651649987,\"sub\":\"username\"}" grpc.request.content="%!v(PANIC=String method: reflect.Value.Bytes of non-byte slice)" grpc.service=project.ProjectService grpc.start_time="2022-06-24T13:07:17Z" span.kind=server system=grpc
time="2022-06-24T13:07:17Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = invalid policy rule 'p, proj:guestbook1:guestbook1, exec, create, guestbook1/guestbook1, allow': project resource must be: 'applications', 'repositories' or 'clusters', not 'exec'" grpc.code=InvalidArgument grpc.method=Create grpc.service=project.ProjectService grpc.start_time="2022-06-24T13:07:17Z" grpc.time_ms=12.376 span.kind=server system=grpc
```

**Comment by sotkovsky** [comment]
i think it's not just a projects scope problem:

```
argocd admin settings rbac can role:XXX create exec --namespace argocd
FATA[0000] error in RBAC request: 'exec' is not a valid resource name

argocd admin settings rbac can role:XXX get logs --namespace argocd
FATA[0000] error in RBAC request: 'logs' is not a valid resource name
```

**Comment by liechtinat** [comment]
Interesting, because the Admission Controller in K8s doesn't reject the setting.

Maybe for others stumbling upon that, a workaround that worked for us was adding the following lines to the global `argocd-rbac-cm`:

```
p, role:swisspost-default, logs, get, */*, allow
p, role:swisspost-default, exec, create, */*, allow
```

This allows everyone that has access to an application to also exec into pods and get logs, then you'd just have to control who is able to see which application.

**Comment by crenshaw-dev** [comment]
@liechtinat yep, this seems like a CLI/API bug. Configuring directly via the ConfigMap should be fine.

Be carefully granting the exec privilege. It's a powerful one.  :-)

**Comment by jessesuen** [comment]
Fix for this should go here:
https://github.com/argoproj/argo-cd/blob/c7ff388b8476a85d10e888f457e35e050658a1c8/pkg/apis/application/v1alpha1/types.go#L1556-L1560

**Comment by reggie-k** [comment]
I will work on that for both resources.

**Comment by the-technat** [comment]
> 

Yeah of course it's a powerful one, but we wanted to roll that out with our next release so the workaround we came up with was to allow exec to everyone. If we limit who can see which app it won't be that dangerous though.

**Comment by reggie-k** [comment]
> Fix for this should go here:
> 
> https://github.com/argoproj/argo-cd/blob/c7ff388b8476a85d10e888f457e35e050658a1c8/pkg/apis/application/v1alpha1/types.go#L1556-L1560

I will add it for both resources then
