### ISSUE TITLE
Enhance securityContext in ha manifests

### ISSUE THREAD

**Issue by joebowbeer** [argoproj/argo-cd#9810]
# Summary

Enhance securityContext in HA installs to comply with PSS/restricted level.

https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted

This is the part of #9743 that was not fixed by #9765

# Motivation

The following ha manifests do not comply with PSS/restricted policies:
* `manifests/ha/cluster-install`
* `manifests/ha/namespace-install`

The following command reports 6 failures for `manifests/ha/namespace-install`:

```bash
kustomize build https://github.com/kyverno/policies//pod-security | \
  kyverno apply --policy-report -r \
  <(kustomize build https://github.com/argoproj/argo-cd//manifests/ha/namespace-install) \
  -
```

(With similar results for `manifests/ha/cluster-install`, and for manifests that are generated from these `ha` folders as well.)

The 6 failures are because 3 properties are missing from the `securityContext` in each of the 2 deployments: `argocd-redis-ha-haproxy` and `argocd-redis-ha-server`

```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
    add:
    - NET_BIND_SERVICE
  seccompProfile:
    type: RuntimeDefault
```

NOTE: Adding NET_BIND_SERVICE is not required by PSS but it is permitted, and it looks like haproxy needs this capability:

[haproxy/templates/deployment.yaml#L112](https://github.com/haproxytech/helm-charts/blob/d8ded40f078f96267ac637d1be780068292f103e/haproxy/templates/deployment.yaml#L112)

# Proposal

Add the missing parts to the securityContext in these deployments and verify that they still function.

Eventually the [upstream](https://github.com/DandyDeveloper/charts/issues/204) should provide these security contexts.

**Comment by jessesuen** [comment]
Good suggestion. We just need a few more overlays here:
https://github.com/argoproj/argo-cd/tree/master/manifests/ha/base/redis-ha/overlays

**Comment by Devamparikh** [comment]
Could I take this up? Hi all! , I'm new here and I find continues delivery is interesting part of devops/gitops and want to get my hands on with it. I could use all the help here. Thank you. ;)

**Comment by crenshaw-dev** [comment]
@Devamparikh it will involve editing the source Kustomize files in `manifests` and then running `make manifests`.

**Comment by souravsk** [comment]
How can an "Enhance security context" be a good-first issue. can anyone explain

**Comment by crenshaw-dev** [comment]
@souravsk the original post specifies which changes need to be made.

**Comment by souravsk** [comment]
@crenshaw-dev thanks for your time.
honestly speaking sir  I don't the whole thing so if you have time then can you please explain
1. what do I do to understand this issue
2. how to do that.
It will be very helpful if you can explain this to me

**Comment by souravsk** [comment]
thank you @crenshaw-dev for your time
I read the documentation of  `` security context`` so I understand what the Restricted policy is .
I also read about kustomize and understand the use  of it

So what I understood is that these two files didn't follow the correct instruction 
[manifests/ha/cluster-install](https://github.com/argoproj/argo-cd/blob/master/manifests/ha/cluster-install/kustomization.yaml)
[manifests/ha/namespace-install](https://github.com/argoproj/argo-cd/blob/master/manifests/ha/namespace-install/kustomization.yaml)

so what I have to do is edit these files in the correct way
sorry if I'm wrong I really want to help understand so that I can help with more issues

**Comment by souravsk** [comment]
so I fork this project but how do I test locally in my minikube

**Comment by souravsk** [comment]
installed kustomize in my system and kyverno in the minikube which take too much time because it keeps giving some errors
so after installing i run this command 

kustomize build https://github.com/kyverno/policies//pod-security | \
  kyverno apply --policy-report -r \
  <(kustomize build ./manifests/ha/namespace-install) \ -

but it keeps giving the error kyverno command not found, as you can see the kyverno is running

![Screenshot from 2022-07-07 19-25-45](https://user-images.githubusercontent.com/33636054/177825175-8ae52446-0d26-4e4d-b6aa-d1737b3a7c54.png)

**Comment by joebowbeer** [comment]
Install kyverno-cli: https://kyverno.io/docs/kyverno-cli/

**Comment by souravsk** [comment]
I did install but still, it's showing the same error
![Screenshot from 2022-07-08 15-28-24](https://user-images.githubusercontent.com/33636054/177968689-0990aff2-ef8f-4211-971d-135323eea43d.png)
As you can see I have installed the kyverno version 1.7.1

**Comment by joebowbeer** [comment]
The version reported is for the kyverno plugin for kubectl, not the standalone kyverno CLI.

**Comment by souravsk** [comment]
can please give me the steps to install it will be very helpful because I tried every step from the official website.

**Comment by joebowbeer** [comment]
@souravsk I ran `brew install kyverno` on macos

If you have more questions concerning kyverno itself, please refer to https://kyverno.io/community/

**Comment by souravsk** [comment]
thanks, @joebowbeer this final work https://kyverno.io/docs/kyverno-cli/#building-the-cli-from-source
I run this command and I get this output 
![Screenshot from 2022-07-09 01-30-54](https://user-images.githubusercontent.com/33636054/178062637-2648a029-1e4e-4a41-ad9c-d4d3f0342f99.png)
as I can see it has 6 fail
so how do i make 0 fail

**Comment by souravsk** [comment]
thanks, @joebowbeer for the help I tried everything, and then this work https://kyverno.io/docs/kyverno-cli/#building-the-cli-from-source
I run the commands and as you stayed it has fail 6 
so to remove that i have add this 

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  seccompProfile:
    type: RuntimeDefault

or i have to do something else

**Comment by joebowbeer** [comment]
@souravsk in the process of answering your questions, I ended up creating a PR that I think will fix the issue:

#9930 

In the description, I added the commands I used to perform a static check of the manifests.

Do you want to install these manifests in minikube and give them a spin?

**Comment by souravsk** [comment]
I'm sorry @joebowbeer for all the trouble. 
Yes will install those manifests in minikube

**Comment by reggie-k** [comment]
This change breaks Openshift ArgoCD installations. Solvable by adding new SCC with seccomp profile for use of each ArgoCD workload. Should be in the docs. Perhaps integration tests on OKD in addition to k8s is beneficial, but obviously a big change

**Comment by joebowbeer** [comment]
According to the discussion below, this change is compatible with OpenShift 4.11+ right?

https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/1417

```yaml
 securityContext:
   # Do not use SeccompProfile if your project must work on 
   # old k8s versions < 1.19 and Openshift < 4.11
   seccompProfile:
      type: RuntimeDefault
```

**Comment by reggie-k** [comment]
Thanks for the link.
We run Openshift 4.8, currently removed the seccomp from ArgoCD workloads,
and it is up just fine. But still investigating
