### ISSUE TITLE
Support PKCE for web logins

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#9890]
# Summary

The CLI currently supports PKCE. The web interface should do so as well.

# Proposal

I believe the API server will have to maintain a cache of code verifiers.

**Comment by todaywasawesome** [comment]
+1

**Comment by andrewkaczynski** [comment]
+1 :)

**Comment by mmerrill3** [comment]
@crenshaw-dev, this looks interesting, is anyone working on this yet?  I guess redis would be ideal for keeping the link between code verifier and the authorization token?

**Comment by mmerrill3** [comment]
@crenshaw-dev  you can assign to me
