### ISSUE TITLE
Docs Bug: UI with AWS ALB Ingress does not work

### ISSUE THREAD

**Issue by SC-CTS** [argoproj/argo-cd#9898]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.

**Describe the bug**

Related to: https://github.com/argoproj/argo-cd/issues/8765

Configuring an ALB Ingress for an EKS hosted ArgoCD instance, as described in the official docs: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#aws-application-load-balancers-albs-and-classic-elb-http-mode will lead to the UI not loading correctly and only displaying a white page.

The problem is that neither the CSS nor JS can be served (404 for both resources).

The Problem is the `path`/`pathType` settings. Switching the `pathType` from `ImplementationSpecific` to `Prefix` solves this issue.

**To Reproduce**

1. Deploy ArgoCD to EKS using the Helm Chart
2. Follow the Ingress Documentation to create a secondary Service for the RCP calls and setup the Ingress as described
3. Open UI, see that it's a blank page and notice 404 for the CSS & JS Resources

**Expected behavior**

The Documentation should provide a working Ingress configuration for an AWS ALB Ingress that serves the UI.

**Comment by too-z** [comment]
I've got a similar issue (empty page), but I installed argocd with yaml
and it solved the problem
Thanks you, you saved my day
