### ISSUE TITLE
Support files in 'argocd.argoproj.io/manifest-generate-paths' annotation

### ISSUE THREAD

**Issue by jmwri** [argoproj/argo-cd#9907]
# Summary

The current implementation of `argocd.argoproj.io/manifest-generate-paths` only supports a list of directories, which is fine 99% of the time, but it would be nice to be able to specify specific files here as well.

# Motivation

I am using the app-of-apps pattern within a monorepo with a directory structure similar to the following:

```
apps-app.yaml -> defines application with source of deployments dir
deployments/
  app-a/
  app-b/
  app-c/
  app-d/
  app-a-app.yaml -> defines application with source of app-a dir
  app-b-app.yaml
  app-c-app.yaml
  app-d-app.yaml
  kustomization.yaml -> includes all app definitions as resources
```

With this directory structure  I would like to set the following annotation on the `apps-app`: `argocd.argoproj.io/manifest-generate-paths: /deployments/kustomization.yaml`. This would enable my `apps-app` to only refresh when a child app has been added or removed.

Currently, I am unable to use the kustomization in the annotation, and instead have to use the entire deployments directory, causing a lot of unnecessary refreshes.

# Proposal

Check if `file == item` within `util/webhook.go` `func appFilesHaveChanged(app *v1alpha1.Application, changedFiles []string) bool`. 

As it's only a small change I went ahead and created a quick PR: https://github.com/argoproj/argo-cd/pull/9908.

**Comment by jmwri** [comment]
@crenshaw-dev Is there any chance to get this into the next release?

**Comment by crenshaw-dev** [comment]
@jmwri I'll see if there's any opposition to cherry-picking it back. If not, I'll add it to 2.4.7 (within the next 3ish days). https://cloud-native.slack.com/archives/C020XM04CUW/p1657899841866619

**Comment by jmwri** [comment]
That would be fantastic, thanks!
