### ISSUE TITLE
Drop all references to exec unless the feature is enabled

### ISSUE THREAD

**Issue by marcelofabricanti** [argoproj/argo-cd#9920]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The UI needs to drop all references to exec unless the feature is enabled.
The pod details page do not show the terminal tab, but context menu doesn't have the same rule.

**To Reproduce**

- Install ArgoCD v2.4.0 or above
- *Do not* enable 'exec' feature trought CofigMap argocd-cm.

**Expected behavior**

The UI shows exec option on context menu of a pod.

**Screenshots**

![173369827-e3d05a27-9fd5-48fa-8cc2-74165a2345d6](https://user-images.githubusercontent.com/75024600/178048362-ed6460e5-a7b7-4e30-82c9-1c84a57eec47.png)
![173369809-37d667e5-31da-42eb-965f-d65307a31d5f](https://user-images.githubusercontent.com/75024600/178048367-08109599-f825-4fcc-9f6e-3b690d0dec85.png)

**Version**

```shell
❯ argocd --server xxxxxx version
argocd: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:38:43Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.4.0+91aefab
```

**Comment by Kerwood** [comment]
Is it possible to only show the "Exec" menu if the features is enabled **and** the user as the proper permissions?

Eg.
```
p, role: org-admin, exec, create, my-proj/*, allow
```
My issues is that I want the feature enabled, but not all users to have access the feature and I don't want the users without access to see the menu item or the tab on the pod overview.

If the feature is enabled but the user does not have access to exec an error will appear when selecting the "Exec" menu item.

![image](https://user-images.githubusercontent.com/4029521/178717863-b96c02f4-0276-4d41-8423-e42ba0bfada9.png)

**Comment by crenshaw-dev** [comment]
It should be possible! That PR would follow the pattern of this one: https://github.com/argoproj/argo-cd/pull/9828

**Comment by Kerwood** [comment]
@crenshaw-dev Will you assign this to me? I think I will give this a go.

**Comment by Kerwood** [comment]
I fixed the Terminal tab issue with inspiration from the PR @crenshaw-dev linked to. That was pretty easy.
I also only want to show the "Exec" menu option if exec is enabled or allowed.

![image](https://user-images.githubusercontent.com/4029521/180158820-77480255-3392-4634-b9c9-40d5a60995bd.png)

I'm having some trouble figuring out how to do that the best way.
In the [utils.tsx file line 443](https://github.com/Kerwood/argo-cd/blob/fix/exec-ui-reference/ui/src/app/applications/components/utils.tsx#L433) `&& execEnabled && execAllowed` can be added to the `if` statement to only show if enabled or allowed, like I have done [here.](https://github.com/Kerwood/argo-cd/blob/fix/exec-ui-reference/ui/src/app/applications/components/resource-details/resource-details.tsx#L117)
```
    if (resource.kind === 'Pod' && execEnabled && execAllowed) {
        items.push({
            title: 'Exec',
            iconClassName: 'fa fa-terminal',
            action: () => appContext.apis.navigation.goto('.', {node: nodeKey(resource), tab: 'exec'}, {replace: true})
        });
    }
```
The issues is I needs to call two async functions. The `services.authService.settings()` and `services.accounts.canI()` function as seen [here.](https://github.com/Kerwood/argo-cd/blob/fix/exec-ui-reference/ui/src/app/applications/components/resource-details/resource-details.tsx#L269,L272) I am just not sure where to place them.

Any help would be appreciated.
