### ISSUE TITLE
Migrate argocd to another k8s cluster

### ISSUE THREAD

**Issue by josericardomcastro** [argoproj/argo-cd#993]
Hi guys! 

I need some help, i have to migrate my Argocd to another cluster kubernetes. 

Is there any easy way to do this? I want to export all the configurations (repositories, clusters, projects and applications) and import into another place, another argocd.

Anyone? Thanks!

**Comment by jessesuen** [comment]
@josericardomcastro, I haven't tried this, but it should be possible to do something like:
```
kubectl get cm --export -o yaml >> backup.yaml
kubectl get secrets --export -o yaml >> backup.yaml
kubectl get app --export -o yaml >> backup.yaml
kubectl get appproj --export -o yaml >> backup.yaml
```
And then run `kubectl create -f backup.yaml`

Some extra work would be needed if you also need to change the namespace.

**Comment by chocopowwwa** [comment]
@jessesuen i've tried migrating argocd to another cluster with those commands, and it works, thank you.  I've sucessfully restore my argocd, but those commands doesn't have yaml separator in between them, so i slightly change the command to 

```kubectl -n argocd get cm,secrets,app,appproj --export -o yaml >> backup.yaml```

**Comment by alexmt** [comment]
Thanks to stalebot for reminding about it. The argocd-util binary now support import and export commands which we user to backup/restore the state. We only need to document it

**Comment by alexmt** [comment]
@alexec added documentation! https://argoproj.github.io/argo-cd/operator-manual/disaster_recovery/

**Comment by krikeri** [comment]
@alexmt do you know if the argocd-util binary also supports exporting apps from all namespaces https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/?

I tried to run the export but it only exported apps that are living in the same namespace as the ArgoCD itself.

**Comment by aberenshtein** [comment]
@krikeri according the doc, you pass the namespace with `-n`
https://argo-cd.readthedocs.io/en/latest/user-guide/commands/argocd_admin_export/
