### ISSUE TITLE
Terminal does not work with windows containers 

### ISSUE THREAD

**Issue by EugeneLugovtsov** [argoproj/argo-cd#9951]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I can open the terminal tab and it successfully connects to the pod, but I cannot type anything in the terminal window. 

![image](https://user-images.githubusercontent.com/34510252/178490999-8a64d246-e599-4147-b726-65883d40d235.png)

**To Reproduce**

1. Try to type some commands in the windows container with PowerShell.

**Expected behavior**

The Terminal feature works for Linux and Windows based containers

**Screenshots**

**Version**

```shell
argocd: v2.2.3+987f665
  BuildDate: 2022-01-18T17:58:47Z
  GitCommit: 987f6659b88e656a8f6f8feef87f4dd467d53c44
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.4.4+fe80bdc
  BuildDate: 2022-07-07T07:11:00Z
  GitCommit: fe80bdcfdc847372f268f5d711d3112c7d1e39bf
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Comment by notfromstatefarm** [comment]
I believe this is fixed in #9895, which will be released in 2.4.6.

**Comment by todaywasawesome** [comment]
@EugeneLugovtsov [2.4.6](https://github.com/argoproj/argo-cd/releases/tag/v2.4.6) was just released which includes #9895 , do you want to give it a try?

**Comment by EugeneLugovtsov** [comment]
@todaywasawesome yes, I have already given it a shot. I have the ability to type commands in ArgoCD v2.4.6. However, I can see that the terminal freezes sometimes, and the cursor is jumping around the terminal window
![image](https://user-images.githubusercontent.com/34510252/179022791-0591a964-db83-437f-9e19-e45380189c58.png)

**Comment by crenshaw-dev** [comment]
I wonder if this is a race condition on the WriteMessage call. @EugeneLugovtsov if I wrote a patch, would you be able to build the image and test it?

**Comment by crenshaw-dev** [comment]
Can you give this a try? https://github.com/argoproj/argo-cd/pull/9994

I'm sharing the read and write lock. It's possible we could get away with write having its own lock.

**Comment by crenshaw-dev** [comment]
(My suspicion is that this might solve the hanging issue but not the intermingled text issue.)

**Comment by EugeneLugovtsov** [comment]
@crenshaw-dev I build the ArgoCD image from your branch. However, the terminal tab is missing now  :(
To make the image I followed this wiki https://argo-cd.readthedocs.io/en/stable/developer-guide/running-locally/#run-your-own-argocd-images-on-your-cluster

**Comment by crenshaw-dev** [comment]
My bad @EugeneLugovtsov, I based that PR on master instead of release-2.4. Can you give this one a try? https://github.com/argoproj/argo-cd/pull/10005

**Comment by EugeneLugovtsov** [comment]
The terminal window just freezes (only once after ~1 minute it turned on, but the commands appeared on the screen very slowly)
![image](https://user-images.githubusercontent.com/34510252/179256968-7f1c4c15-b529-4a18-87f0-29b4e9c5ad30.png)

**Comment by crenshaw-dev** [comment]
Gotcha, so shared read/write lock probably hurts performance and doesn't solve the problem.

Are there any error logs in the browser (dev tools console or network traffic) or in the argocd-server?

**Comment by EugeneLugovtsov** [comment]
Nothing from the browser dev console, but I see a lot of errors in argo-server logs
![image](https://user-images.githubusercontent.com/34510252/179262909-03801268-68a8-4556-9a6b-50fbb8ac9b40.png)

**Comment by crenshaw-dev** [comment]
You mentioned it fails after ~1m. Is it possible there's a timeout on a reverse proxy? https://stackoverflow.com/a/57706152/684776

**Comment by jgwest** [comment]
Based on comments, appears individual environment specific

**Comment by dankellett** [comment]
> @todaywasawesome yes, I have already given it a shot. I have the ability to type commands in ArgoCD v2.4.6. However, I can see that the terminal freezes sometimes, and the cursor is jumping around the terminal window ![image](https://user-images.githubusercontent.com/34510252/179022791-0591a964-db83-437f-9e19-e45380189c58.png)

Did you find a resolution to the output glitch you describe? We have an environment with the same symptoms.
