### ISSUE TITLE
ADA-ARGO-SA-01: `help.chatUrl` should be validated

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#9956]
It can currently be a `javascript:` link. Only admins can set this value, so it's reasonably safe. But it's probably better to URL validate that value to help admins avoid doing something dangerous.

**Comment by saumeya** [comment]
I'd like to work on this, what does `javascript:` link mean @crenshaw-dev

**Comment by crenshaw-dev** [comment]
@saumeya, I believe the `href` attribute for the "chat" button can start with `javascript: `, meaning it can be used to run arbitrary JavaScript code instead of navigating to an external page. If I were a malicious Argo CD admin, I could embed code in that `href` to take malicious actions using the victim's credentials (do things like deleting an app).

The fix could make use of some of this validation code: https://github.com/argoproj/argo-cd/commit/8bc3ef690de29c68a36f473908774346a44d4038

**Comment by crenshaw-dev** [comment]
Just to clarify: if someone is an Argo CD admin, there are a lot more malicious things they can do than this. So this isn't really a vulnerability. It would just be good to add an extra layer of protection.  :-)
