### ISSUE TITLE
TOB-ARGO-TM8: Set a reasonable default if UserSessionDuration parsing fails

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#9962]
# Summary

When UserSessionDuration is parsed from `argocd-cm`, failed parsing defaults to 0. Instead, set a reasonable default.

https://github.com/argoproj/argo-cd/blob/fdceed6051f2659adff206498a9417695e23e74c/util/settings/settings.go#L1274

**Comment by deepto98** [comment]
Can I pick this up?

**Comment by y-takuya** [comment]
Hi @deepto98 , are you still working on this issue? If you don't have enough time to work on it, I can do it.

**Comment by y-takuya** [comment]
Hello @crenshaw-dev, the work on this Issue seems to be on hold. Is it possible for me to take over and work on it?

**Comment by crenshaw-dev** [comment]
Thanks @y-takuya!
