### ISSUE TITLE
TOB-ARGO-TM2: Add network policies for ApplicationSet and Notifications controllers

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#9968]
# Summary

Certain components do not need to be able to talk to each other.

# Motivation

If an attacker were able to get access to, say, the applicationset controller, they should not have unrestricted network access to other Argo CD components. The applicationset controller does not need to be able to make API calls to, for example, the API server.

This was mentioned as item 2 in the Trail of Bits security audit threat modeling document: https://github.com/argoproj/argoproj/blob/master/docs/argo_threat_model.pdf

# Proposal

https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by notfromstatefarm** [comment]
Aren't there already network policies? 🤔 

i.e. https://github.com/argoproj/argo-cd/blob/master/manifests/base/repo-server/argocd-repo-server-network-policy.yaml

**Comment by crenshaw-dev** [comment]
Ah! I should read our manifests some time.

I think we're still missing policies for the ApplicationSet and Notification controllers. I guess this issue can track those two.
