### ISSUE TITLE
UI does not display related RS or Pod of Deployment

### ISSUE THREAD

**Issue by cconnert** [argoproj/argo-cd#9973]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ~] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

The UI does not display any related RS or Pod resource (see screenshot). Not sure why this is the case. Just upgraded ArgoCD 2.2.5 to the latest version.

**To Reproduce**

I suspect that it might be related to the HPA, but I honestly do not know right now how to reproduce the issue. On other deployments the UI does display the related resources properly.

**Expected behavior**

I would expect it to look similar to this 
![grafik](https://user-images.githubusercontent.com/4414974/178776053-4d1e43f0-beb3-4d1a-972d-2692ffa30747.png)

**Screenshots**

![grafik](https://user-images.githubusercontent.com/4414974/178775310-45e379d9-6cbc-4091-83a8-3451bb8b2b4b.png)

**Version**

```shell
{
    "Version": "v2.4.6+a48bca0",
    "BuildDate": "2022-07-12T22:31:17Z",
    "GitCommit": "a48bca03c79b6d63be0c34d6094831bc6916b3bc",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.1+g5cb9af4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
```

**Comment by crenshaw-dev** [comment]
If the Application's Project is using a resource allow-list, make sure all the resources you want to see are allow-listed.

**Comment by cconnert** [comment]
Thanks for the quick reply. Just updated my project and could managed to verify that the issue got resolved by extending the allow-list. 
But actually I would have preferred not disallow the creation of those kind of resources by our teams. Well, nothing we can do about that I guess...

**Comment by crenshaw-dev** [comment]
If your users have the ability to create Deployments, don't they already have the ability to create Pods and ReplicaSets by proxy?

**Comment by cconnert** [comment]
True that, but maybe I want to force them to utilize Deployments as interaction point.

**Comment by cconnert** [comment]
Perfect, I'll crate an enhancement request
