### ISSUE TITLE
argocd-server Username or Password not working on fresh install

### ISSUE THREAD

**Issue by hulu1522** [argoproj/argo-cd#998]
I followed the documentation but changed the version to v0.11.0-rc5 and I can't seem to to `argocd login ...` as if the password was not updated somewhere.  I get the following error:

```
FATA[0016] rpc error: code = Unauthenticated desc = Invalid username or password
```

Any suggestions on what to try would be appreciated.  The only workaround was to disable auth with the flag `--disable-auth` for the argocd-server deployment.

**Comment by jessesuen** [comment]
We broke this going from rc4 to rc5. We will be releasing a new rc with the fix here:
https://github.com/argoproj/argo-cd/pull/1000

**Comment by alexec** [comment]
https://github.com/argoproj/argo-cd/blob/master/docs/faq.md#i-forgot-the-admin-password-how-do-i-reset-it

**Comment by adynetro** [comment]
I've tried all the above and still have the same issue. I can login with openshift but I dont't have permissions to sync.

**Comment by romaissa1999** [comment]
> I've tried all the above and still have the same issue. I can login with openshift but I dont't have permissions to sync.

the same issue, did you find a way to solve the problem ?

**Comment by zfrhv** [comment]
> kubectl patch secret argocd-secret  -p '{"data": {"admin.password": null, "admin.passwordMtime": null}}'

i tried to modify but its being overwritten, 
if you install argocd on openshift try checking the `argocd-cluster` secret instead of `argocd-secret`

**Comment by sylnsr** [comment]
As for `v.2.14`, this works for me:

```bash
#!/usr/bin/env bash

kubectl patch secret argocd-secret -p '{"data": {"admin.password": null, "admin.passwordMtime": null}}' -n argocd && \
kubectl delete secret argocd-initial-admin-secret -n argocd && \
kubectl rollout restart deployment argocd-argo-cd-server -n argocd && \
sleep 30 && \
kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath="{.data.password}" | base64 --decode
echo ""
```

**Comment by Lorddistrict** [comment]
> #!/usr/bin/env bash
> 
> kubectl patch secret argocd-secret -p '{"data": {"admin.password": null, "admin.passwordMtime": null}}' -n argocd && \
> kubectl delete secret argocd-initial-admin-secret -n argocd && \
> kubectl rollout restart deployment argocd-argo-cd-server -n argocd && \
> sleep 30 && \
> kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath="{.data.password}" | base64 --decode
> echo ""

```sh
secret/argocd-secret patched
secret "argocd-initial-admin-secret" deleted
Error from server (NotFound): deployments.apps "argocd-argo-cd-server" not found
```

**Comment by opentokix** [comment]
This script is slightly adjusted from @sylnsr to work with the manifest-installed v3.0.0
```
#!/usr/bin/env bash

kubectl patch secret argocd-secret -p '{"data": {"admin.password": null, "admin.passwordMtime": null}}' -n argocd && \
kubectl delete secret argocd-initial-admin-secret -n argocd && \
kubectl rollout restart deployment argocd-server -n argocd && \
sleep 30 && \
kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath="{.data.password}" | base64 --decode
echo ""

```
