### ISSUE TITLE
Terminal doesn't load when opening via deploy/STS/etc

### ISSUE THREAD

**Issue by krisrang** [argoproj/argo-cd#9980]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Opening pod terminal via parent resource such as deployment, statefulset, etc doesn't work.
It tries to open a terminal using the name of the parent resource instead of a suitable related pod.

For example with a deployment `devbot-prod-4-50-skyltmax-sidekiq` that has a pod `devbot-prod-4-50-skyltmax-sidekiq-76c5446f57-7vxfc` the UI will try to open a terminal to pod `devbot-prod-4-50-skyltmax-sidekiq`.

**To Reproduce**

Open a deployment or statefulset and select the terminal tab.

**Expected behavior**

I expect it to pick a random/first pod in the deployment and open the terminal for that.

**Screenshots**

![image](https://user-images.githubusercontent.com/20186/178827698-41edc193-a453-4487-9439-27d077eb7e33.png)

**Version**

```shell
argocd: v2.4.6+a48bca0
  BuildDate: 2022-07-12T22:53:14Z
  GitCommit: a48bca03c79b6d63be0c34d6094831bc6916b3bc
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.4.6+a48bca0
```

**Logs**

```
Pod doesn't belong to specified app
```

**Comment by notfromstatefarm** [comment]
Confirmed, ran into this myself.
