### ISSUE TITLE
intermittent unknown sync state, ssh connection reset by peer

### ISSUE THREAD

**Issue by mmerickel** [argoproj/argo-cd#9981]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

`app.status.sync.status == Unknown`

Regularly we are receiving network errors from the repo-server when connecting to git repos over ssh. URL format is `git@redacted.hostname:sub/path.git`. One or more apps (I've seen up to 6 apps at once) enter the unknown sync state at the same time. See below the `ssh: handshake failed` message with `read: connection reset by peer`. Clicking retry or waiting 3 minutes for argocd to try again fixes the issue every time.

All of this traffic is within a single AWS VPC from EC2 to EC2 and we have not observed any connectivity issues with our self-hosted gitlab instance except here with argocd. Something in argocd is struggling with establishing the ssh connection reliably. All of these apps are connected to the same self-hosted gitlab server. We use app-of-apps so some apps are connected to the same repo and some to different ones, but all of them to the same server endpoint. Dunno if that could trigger the issue more often in the connection subsystem.

I've never seen this issue happen from a manual refresh, only from the automatic refresh.

This issue happens frequently, almost every automatic refresh, several times per hour.

Note also that this is likely the same issue reported at https://github.com/argoproj/argo-cd/issues/2472 that was closed by the author.

**Expected behavior**

The application should never timeout talking to gitlab over ssh, or automatically retry the connection a limited number of times. Manually triggering a refresh, or waiting 3 minutes for argocd to try again has fixed the issue every single time so it should be marked as an ephemeral issue that is retryable similar to #9739.

**Reproduce**

Connect several apps using git-over-ssh and observe them sporadically entering the unknown state and then recovering.

**Version**

```
argocd-server: v2.4.6+a48bca0
  BuildDate: 2022-07-12T22:31:17Z
  GitCommit: a48bca03c79b6d63be0c34d6094831bc6916b3bc
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

I enabled debug logging on the repo server but there was nothing interesting other than these error messages.

```
repo-server time="2022-07-13T23:18:25Z" level=error msg="finished unary call with code Unknown" error="ssh: handshake failed: EOF" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2022-07-13T23:18:25Z" grpc.time_ms=15.526 span.kind=server system=grpc
repo-server time="2022-07-13T23:18:25Z" level=error msg="finished unary call with code Unknown" error="ssh: handshake failed: read tcp 10.32.7.116:60348->10.32.14.251:22: read: connection reset by peer" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2022-07-13T23:18:25Z" grpc.time_ms=258.859 span.kind=server system=grpc
repo-server time="2022-07-13T23:18:25Z" level=error msg="finished unary call with code Unknown" error="ssh: handshake failed: read tcp 10.32.7.116:60346->10.32.14.251:22: read: connection reset by peer" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2022-07-13T23:18:25Z" grpc.time_ms=261.199 span.kind=server system=grpc
repo-server time="2022-07-13T23:18:25Z" level=error msg="finished unary call with code Unknown" error="ssh: handshake failed: read tcp 10.32.7.116:60344->10.32.14.251:22: read: connection reset by peer" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2022-07-13T23:18:25Z" grpc.time_ms=270.75 span.kind=server system=grpc
repo-server time="2022-07-13T23:18:25Z" level=error msg="finished unary call with code Unknown" error="ssh: handshake failed: read tcp 10.32.7.116:60340->10.32.14.251:22: read: connection reset by peer" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2022-07-13T23:18:25Z" grpc.time_ms=274.842 span.kind=server system=grpc
repo-server time="2022-07-13T23:18:25Z" level=error msg="finished unary call with code Unknown" error="ssh: handshake failed: read tcp 10.32.7.116:60342->10.32.14.251:22: read: connection reset by peer" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2022-07-13T23:18:25Z" grpc.time_ms=270.478 span.kind=server system=grpc
```

**Comment by yiyan-wish** [comment]
This issue does not appear again when I scaled out the argocd-repo-server.

**Comment by mmerickel** [comment]
I have 23 apps connected to 7 git repos over ssh. I have tried 1, 2, and 5 repo servers with no improvement.

**Comment by yiyan-wish** [comment]
I have 80+ applications to 4 git repos.
ref to the [https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller)
And I also add `.argocd-allow-concurrency` file to the git repos

**Comment by mmerickel** [comment]
I'm not sure these workarounds explain why I'm receiving the `connection reset by peer` error in the ticket. I am using the `.argocd-allow-concurrency` config on the git repos and that has not made it functionally better.

**Comment by mmerickel** [comment]
I think I have pinned down the problem. Will reopen if it comes back but adjusting `MaxStartups` in the `/etc/ssh/sshd_config` on the gitlab server seems to have helped as I haven't seen issues since adjusting it.
