### ISSUE TITLE
Allow cluster update through the CLI

### ISSUE THREAD

**Issue by TdSch** [argoproj/argo-cd#9996]
# Summary

Update cluster information through the CLI. Currently the only options for cluster in the CLI are get, add, rm. 

# Motivation

I need to update the managed namespace of my cluster every time there is a new application. My applications are created by an automated script and I would like to add the required step of adding the namespace in the cluster in that script.

# Proposal

New command in CLI. Either a full edit or a simple set command to update target properties.

**Comment by danielhelfand** [comment]
You should be able to use the `--upsert` option with `argocd cluster add` to update the cluster details:
https://github.com/argoproj/argo-cd/blob/7d31d612ef2309a4d6dfef3a47e565af4742586f/cmd/argocd/commands/cluster.go#L154

**Comment by TdSch** [comment]
Unfortunately that expects the context to be present on my local kubeconfig to perform the operation. For various segregation concerns I do not have this config.
However, when done through the web interface it calls a PUT endpoint with simply the ˋupdatedFields` set to namespace.

**Comment by danielhelfand** [comment]
> Unfortunately that expects the context to be present on my local kubeconfig to perform the operation. For various segregation concerns I do not have this config.


Thanks for this detail. Makes sense as a feature to me then.
